### PR TITLE
Use the default Capybara registered puma server configuration

### PR DESCRIPTION
**Pull request by twalpole**
The `puma_rails` "server" registered by Rails for system tests doesn't force Puma into "in process" mode.  This means if the user happens to have a `config/puma.rb` configuration file which is configuring puma in cluster mode for production it will also run Puma in cluster mode for tests.  Since cluster mode runs Puma in new processes it defeats the connection sharing needed for transactional testing, and prevents Capybara from being able to monitor open connections at the end of tests.

This PR changes the behavior to just use the default Capybara registered  `puma` "server" which does pass the needed options, and I don't really see the benefit of Rails registering its own "server" config.

### CODE REVIEW

**Comment by maschwenk** [comment]
This issue directly impacted me, and will probably impact other Rails users as more people migrate to SystemTests. Like most people running Puma in the dev/prod stack, I had some configuration in `config/puma.rb` that was overriding the SystemTests-configured Puma. It took a long time to figure out what the cause was until I directly messaged @twalpole over Gitter. 

@eileencodes in the evolution of the PR I saw you placed a big emphasis on sensible defaults and out-of-the-box functionality. To that point, it makes sense to me that SystemTests should strongly enforce a Puma configuration that takes advantage of the connection sharing (and maybe leave the  port to be configurable?)

**Comment by eileencodes** [comment]
I think this is fine because I originally meant for the port to be settable but now that I think about it that eventually got removed with a few refactorings. If we need the port to be configurable beyond the `config/puma.rb` it makes sense to add that feature to system tests - but we don't need to delay this PR for that.

**Comment by eileencodes** [comment]
@twalpole can you add a changelog note for this?

**Comment by twalpole** [comment]
@eileencodes Done

**Comment by eileencodes** [comment]
@twalpole thanks for pointing that out, I've removed it from the 5.1.5 milestone.

**Comment by guilleiguaran** [comment]
Isn't possible to backport this to 5.1.x? This allow using another web servers without changing puma as the default, e.g in my app I can do something like:

```
config.before(:suite)   { Capybara.server = :passenger }
```

**Comment by maschwenk** [comment]
@guilleiguaran if you look directly above in stream, we have already back-ported it in #30712

**Comment by guilleiguaran** [comment]
@maschwenk even when #30712 makes registered `:rails_puma` match the behavior of Capybara registered `puma` it doesn't allow the use of alternatives servers since Puma Rack Handler is required and initialized in the code.

**Comment by guilleiguaran** [comment]
@twalpole: but Rails fails if puma isn't present in the Gemfile, so you need to add it as a dependency even if you want to use another server. See https://github.com/rspec/rspec-rails/issues/1882

The current solution in RSpec 3.7 is to disable System Tests entirely if puma can't be loaded: https://github.com/rspec/rspec-rails/pull/1884/files

**Comment by twalpole** [comment]
@guilleiguaran So include the puma gem in the test environment, registering the server doesn't actually  initialize puma until that server is used, so as long as you set an alternative before Capybara attempts to start the server puma will never be used -  Note: this PR didn't remove the `require "rack/handler/puma"` line from the file so it would still required puma to be in the project.

**Comment by twalpole** [comment]
@guilleiguaran Or just stick to writing feature specs which don't have a requirement of puma and still get the connection sharing/transactional testing/remove database_cleaner benefits under Rails 5.1

**Comment by guilleiguaran** [comment]
> Note: this PR didn't remove the require "rack/handler/puma" line from the file so it would still require puma to be in the project.

Yup, I already removed it in Rails master: https://github.com/rails/rails/commit/50f697664edf0d2deff22f3f1a1c8e01d54a74ca

> still get the connection sharing/transactional testing/remove database_cleaner benefits under Rails 5.1

Didn't know about this, I think that's good enough for me.

**Comment by obromios** [comment]
Is a possible workaround for this to put a guard clause in config/puma.rb that skips the relevant puma cluster configuration code unless Rails.env.production?.

**Pull request merged**
