### PR TITLE
Add default pwa manifest and service worker file

### PR DESCRIPTION
**Pull request by dhh**
Having the PWA manifest and service-worker.js files under `app/views/pwa` means we can work on them dynamically with ERB and other techniques. They're mounted via a built-in Rails controller and explicitly revealed in the routes.rb file to ensure there are no surprises.

- [ ] Consider adding `--skip-pwa`, although I'm not sure that's needed. This feels like default files akin to 404.html and icon.png.
- [ ] Add some tests?
- [ ] Explain the example code in service-worker.js better? Or wait for Action Notifier to drop to integrate it out the box?

### CODE REVIEW

**Comment by joemasilotti** [comment]
What’s the general consensus on acronyms like `PWA`? I usually add them to the inflections file so we can `PWAController` and such.

**Comment by dhh** [comment]
I don't find it worth adding custom inflections. Pwa is imo fine.

**Comment by rossta** [comment]
It could be helpful also to generate the serviceworker registration script and add an import statement into application.js to get the serviceworker running in the browser. In serviceworker-rails, it's called the serviceworker companion:

```js
if (navigator.serviceWorker) {
  navigator.serviceWorker
    .register("/service-worker.js", { scope: "./" })
      .then(function() {
        console.log("[Companion]", "Rails Service worker registered!")
      })
      .catch(function(error) {
	      // registration failed :(
        console.log("[Companion]", "Rails Service worker registration failed: " + error)
      })
}
```

https://github.com/rossta/serviceworker-rails/blob/a81aa1f138716e4eda8c1241c8b8152c1b1bda9c/lib/generators/serviceworker/templates/serviceworker-companion.js#L1-L11

**Comment by rctneil** [comment]
I think stuff like this is nice, but by default it only applies to new apps.  How do we know what to add to get the same in an existing app?

Same question applies to other features in 7.2 and other rails updates.   Please don;t just focus on new apps.  Tell us what to do to add these new and cool features to our existing apps. What changes we need to make.

I keep seeing people say that they want to make Rails easier for people to learn but stuff like this just keeps getting skipped as far as I can tell.

I could be wrong, If I am then point me in the right direction and i'll go read!

Thanks!

**Comment by rctneil** [comment]
I'll see what I can do.  I just feel that if something new is added to Rails, then it should be explained how to get it / use it for both new apps AND existing apps.

Could the release notes for tommorrow be updated to include details of how to do this for both this and devcontainers?

**Comment by dhh** [comment]
Yeah, good to link up projects to where you can learn more about them. Please do pitch some patches!

**Comment by rctneil** [comment]
@dhh  I'll try, but need to look into them myself first.  I don't any anything about the items i mentioned.  I just read about them in the RC1 release notes and literally said to myself "Huh? Sounds cool but I don't know what they are".

New features are cool, but documentation needs to tell us how to use them.

I'll leave it at be now. I've explained enough.   No need for me to keep pushing my point as I have a habit of doing, :-)

**Comment by davegson** [comment]
@rctneil check out the amazing [raildiff project](https://github.com/railsdiff/railsdiff).

You can pick two rails versions and see what differences between new project in each are, eg: diff between 7.1 and 7.2.2:
https://railsdiff.org/7.1.0/7.2.2

for this case, it shows all new PWA files for easy copy paste. I've been heavily using it since I found it.

Might even be worth linking to in the upgrade guides @dhh?

**Comment by trebeil** [comment]
Yes, makes sense. Its just that to me, it seems that having the upgrade tool add all new features and opt-out by deleting files or rejecting code changes is much easier than having it adding only some stuff and than having to manually opt-in by searching for what you may have missed and copying/pasting. Besides that, if a new Rails app comes by default with these new features, it's because it was discussed a lot, it fits the vision of the maintainers and it's considered the best default from now on (again, omakase), right? So when I was upgrading to this new version, I was intuitively expecting everything to be added automatically and then being able to opt-out instead of have the minimum added and having to manually opt-in.

I think an interactive upgrade step prompting for the opt-in permission to add new features would be the best solution indeed. Right now, I wouldn't be able to work on this too, so I thought that at least mentioning on the Guide the idea of using the `rails new` generator as a way to ensure that you get all the files and changes for the new features and then opting-out by deleting files and rejecting code changes could be helpful. Again, as I'm new to all of this, I don't know if this approach was obvious or if its not even desirable at all. If so, no problem. In my personal notes, I've documented this approach to be my standard when upgrading anyway.

**Pull request merged**
