### PR TITLE
Fix mis-labled code block that caused lint failures

### PR DESCRIPTION
**Pull request by dustinbrownman**
### Motivation / Background

I noticed in [another PR](https://github.com/rails/rails/pull/49638) that I was getting unrelated Rubocop failures. Looks like something in the job configuration made it start scanning these code snippets. I'm seeing the failures in [other PRs](https://github.com/rails/rails/actions/runs/6518650915/job/17704306689?pr=49637) as well. Interestingly, this failures doesn't happen locally (for me anyway).

### Detail

This PR fixes the Rubocop build issue by changing the type of that code block labels.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [ ] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by simi** [comment]
Similar problem is at line 3566. IMHO moving from "```ruby" to "```" should fix this.

**Comment by dustinbrownman** [comment]
I'm trying to spot check for these issues in the file, but since I can't reproduce the error locally, I'm having to respond to the errors in CI. So apologies for the noise on this :(

**Comment by dustinbrownman** [comment]
I was able to reproduce by targeting that file specifically with Rubocop!

```
bundle exec rubocop guides/source/configuring.md
```

**Comment by jonathanhefner** [comment]
Thank you, @dustinbrownman! :policeman:

**Pull request merged**
