### PR TITLE
Refactor enum to use `value` instead of `label` in the scope

### LINKED ISSUE #28945: enum scope generates wrong SQL WHERE condition when using nil as an enum value
### Context and TL;DR
I'm trying to put rails on top of a legacy DB.
This DB stores enumerated status information in the `tp_Measure.Disposal_Unit` column (as `Integer`).
Some of these enum values are `NULL` instead of an `int`. When calling the class scope for the values that are `NULL`, the generated `WHERE` statement checks equality with `= NULL` instead of `IS NULL`.

I am aware that this may be a very rare use case and would like to know if others have had this problem as well, or if the enum implementation is not supposed to handle this case.

Below you'll find code to describe the issue in more detail. If you think that this might really be a bug, I'll gladly prepare a test case and/or reproduction scenario.

### Steps to reproduce
Create a class that has an enum where one enum value is `nil` instead of an int or string.
Create some records of this class that have `nil` as their enum value.
```ruby
class Measure < ApplicationRecord
  self.table_name = 'tp_Measure'

  alias_attribute :disposal_unit, :Disposal_Unit

  enum disposal_unit: {
    cubic_meter: 1,
    tons: 2,
    no_data: 0,
    nothing: nil
  }
end
```

### Expected behavior
When calling the generated scopes, the generated SQL statement should consider the possibility that instead of a correctly set enum value, the DB value might be `nil`, and therefore generate the following `WHERE` condition:

```ruby
irb(main):017:0> Measure.nothing
  Measure Load (1.4ms)  SELECT `tp_Measure`.* FROM `tp_Measure` WHERE `tp_Measure`.`Disposal_Unit` IS NULL
=> #<ActiveRecord::Relation [#<Measure ... >, #<Measure ... >, ...]>
```

### Actual behavior
Currently, it is just assumed that the enum DB column only contains enum values and it is always possible to query the DB with the `=` operator.

When calling the generated class scope `Measure.nothing`:
```ruby
irb(main):017:0> Measure.nothing
  Measure Load (1.4ms)  SELECT `tp_Measure`.* FROM `tp_Measure` WHERE `tp_Measure`.`Disposal_Unit` = NULL
=> #<ActiveRecord::Relation []>
```

### System configuration
**Rails version**: 5.0.2
**ActiveRecord version**: 5.0.2
**Ruby version**: ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]

### PR DESCRIPTION
**Pull request by kamipo**

### CODE REVIEW

**Comment by robin850** [comment]
Could you add a changelog entry please ? Otherwise, nice fix !

**Comment by matthewd** [comment]
While I like the change of variable names here, I think it's cheating to call it a fix: if I'm understanding this correctly, `Book.where(status: "forgotten").first` would still fail -- we're just changing the generated scope to avoid the known-broken behaviour. (Is that right?)

**Comment by kamipo** [comment]
Yes, `Book.forgotten.first` works but `Book.where(status: "forgotten").first` still fail.
Should I remove `Fixes #28945` in the comment?

**Comment by matthewd** [comment]
Yeah, I think so. It does technically fix the exact case described in that issue, but as we don't have another issue tracking @maclover7's generalisation in https://github.com/rails/rails/issues/28945#issuecomment-298430412, probably better to leave that one open.

**Comment by kamipo** [comment]
I agree with you. Removed the comment in the commit.

**Pull request merged**
