### PR TITLE
Add `by:` parameter to `assert_changes`

### PR DESCRIPTION
**Pull request by alainravet**
Add `by:` parameter to `assert_changes`
```
assert_changes :@object, by: 1 do
  @object.increment
end
```

### CODE REVIEW

**Comment by alainravet** [comment]
There is one - unrelated -  broken test in CI:
```  1) Error:
EventedRedisAdapterTest#test_broadcast_after_unsubscribe:
RuntimeError: eventmachine not initialized: evma_connect_to_server
    /home/travis/build/rails/rails/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:677:in `connect_server'
```

**Comment by gsamokovarov** [comment]
The `assert_changes` method is about generic change detection. The `by` can be used comparable objects responding to `-` (according this implementation) which narrows down the usage of it. If you need to detect changes `by` something, you can already do that in `assert_difference`.

**Comment by alainravet** [comment]
@gsamokovarov 
I was surprised by the absence of `by:` in `assert_change`, coming from RSpec where I could write

```
  expect { Counter.increment }.to change{ Counter.count }.from(0).to(1)
  expect { Counter.increment }.to change{ Counter.count }.by(1)
```

Compared to `assert_difference`, the explicit `by:` parameter clarifies the meaning of the passed value
```
assert_change     'Counter.count', by: 1 do .. end  # clearer
assert_difference 'Counter.count', 1     do .. end
```

**Comment by kaspth** [comment]
Thanks, but we're gonna stick with `assert_difference -> { Post.count }, +1` 😊

**Pull request closed without merging**
