### PR TITLE
Reduce Array allocation by mutating when possible

### PR DESCRIPTION
**Pull request by schneems**
### Summary

This PR uses the [Rubocop feature I implemented](https://github.com/rubocop-hq/rubocop/pull/6234) that looks for cases where arrays are allocated and thrown away for example:

```ruby
array = ["a", "b", "c"]
array.compact.flatten.map { |x| x.downcase }
```

Can be replaced with:

```ruby
array = ["a", "b", "c"]
array.compact!
array.flatten!
array.map! { |x| x.downcase }
array
```

### Other Information

In testing with CodeTriage this change saw 999283 bytes to 977094 bytes reduction in memory (2.22%) which roughly corresponds to a 2.22% decrease in execution time.

Since the optimization was applied across the board instead of only to hotspots different applications will see fairly different effects by this change based on the APIs that they're using.

### CODE REVIEW

**Review by matthewd — CHANGES_REQUESTED** [review]
These look pretty ugly to me... I'm quite unexcited about making a global switch to this style just for the sake of a handful of maybe-hot paths.

> roughly corresponds to a 2.22% decrease in execution time

Can we please actually measure that? I'm both surprised and confused by the claim that short-term object allocations correspond directly to runtime outside of microbenchmarks that do nothing else.

(And even then I'd like to understand whether there's a small handful of these that account for the bulk of the difference. This feels like a rubocop rule that's more suited to "btw there's an uglier-but-very-slightly-faster alternative you might want to consider here, depending on how the trade-offs balance out" notification, not a bulk change & enforced rule.)

**Comment by ahorek** [comment]
This should be changed only on places that are proven to be bottlenecks.
Partial evaluation may eliminate the overhead of chaining and I hope mjit can do something simmilar in the future.

**Comment by jonathanhefner** [comment]
@mockdeep  Good thinking, but in microbenchmarks I've found that the overhead of `tap` dwarfs the performance benefits of bang methods.  For example:

```ruby
require "benchmark/inputs"

INPUTS = [
  [1, 2, 3],
  [1, nil, 2, nil, 3, nil],
  [nil, nil, nil],
]

Benchmark.inputs(INPUTS) do |job|
  job.dup_inputs = true
  job.report("Array#compact"){|array| array.compact }
  job.report("Array#compact!"){|array| array.compact! }
  job.report("Array#tap(compact!)"){|array| array.tap(&:compact!) }
  job.compare!
end
```

Results in:
```
       Array#compact!:   2231626.2 i/s
        Array#compact:   1982646.8 i/s - 1.13x slower
  Array#tap(compact!):   1320809.5 i/s - 1.69x slower
```

**Comment by mockdeep** [comment]
Oh, interesting. Well nevermind that then.

**Comment by schneems** [comment]
Try symbol_to_proc with tap instead of using an actual block. It’s faster.

**Comment by jonathanhefner** [comment]
@schneems Did you mean the reverse?  It looks like using an actual block is indeed faster, but still not enough to overcome the overhead of `tap`:

```ruby
require "benchmark/inputs"

INPUTS = [
  [1, 2, 3],
  [1, nil, 2, nil, 3, nil],
  [nil, nil, nil],
]

Benchmark.inputs(INPUTS) do |job|
  job.dup_inputs = true
  job.report("compact"){|array| array.compact }
  job.report("compact!"){|array| array.compact! }
  job.report("tap(&:compact!)"){|array| array.tap(&:compact!) }
  job.report("tap{|a| a.compact! }"){|array| array.tap{|a| a.compact! } }
  job.compare!
end
```

Results:
```
              compact!:   2201732.2 i/s
               compact:   1994791.3 i/s - 1.10x slower
  tap{|a| a.compact! }:   1682900.8 i/s - 1.31x slower
       tap(&:compact!):   1309621.1 i/s - 1.68x slower
```

**Comment by schneems** [comment]
Here was my benchmark https://gist.github.com/schneems/78164e61485bf3d130e35e7347d61ae0

**Comment by jonathanhefner** [comment]
@schneems I believe the reason you're seeing "same-ish" is because the `dup` is being included in the benchmark along with the actual method calls, and it's dominating the measurement.  To confirm if that's the case, try benchmarking the non-bang variants (i.e. just `array.flatten.uniq.compact`) and see if you actually get a higher i/s.  If so, the `dup` is probably the culprit.

The [gem](https://github.com/jonathanhefner/benchmark-inputs) I'm using to benchmark is one that I wrote to exclude `dup` from the measurements, so that's why I'm seeing a difference.

Here's `flatten` + `uniq` + `compact` with that gem:
```ruby
require "benchmark/inputs"

INPUTS = [
  [1, 2, 3],
  [1, nil, 2, nil, 3, nil],
  [nil, nil, nil],
]

Benchmark.inputs(INPUTS) do |job|
  job.dup_inputs = true
  job.report("normal"){|array| array.flatten.uniq.compact }
  job.report("bang!"){|array| array.flatten!; array.uniq!; array.compact! }
  job.report("tap(&:bang!)"){|array| array.tap(&:flatten!).tap(&:uniq!).tap(&:compact!) }
  job.report("tap{|a| a.bang! * 3 }"){|array| array.tap{|a| a.flatten!; a.uniq!; a.compact! } }
  job.report("tap{|a| a.bang! } * 3"){|array| array.tap{|a| a.flatten! }.tap{|a| a.uniq! }.tap{|a| a.compact! } }
  job.compare!
end
```

Results:
```
                  bang!:    172013.5 i/s
  tap{|a| a.bang! * 3 }:    165071.0 i/s - 1.04x slower
                 normal:    160889.3 i/s - 1.07x slower
  tap{|a| a.bang! } * 3:    158352.6 i/s - 1.09x slower
           tap(&:bang!):    145242.9 i/s - 1.18x slower
```

**Comment by mockdeep** [comment]
I had the random idea to use `lazy` instead to avoid the allocations, but it looks like it adds quite a bit of overhead, at least for this example. And it doesn't work for things like `flatten` and `compact`.

```rb
require "benchmark/inputs"

INPUTS = [
  [1, 2, 3],
  [1, nil, 2, nil, 3, nil],
  [nil, nil, nil],
]

Benchmark.inputs(INPUTS) do |job|
  job.dup_inputs = true
  job.report("lazy"){|array| array.flatten.compact.lazy.uniq.to_a }
  job.report("normal"){|array| array.flatten.uniq.compact }
  job.report("bang!"){|array| array.flatten!; array.uniq!; array.compact! }
  job.report("tap(&:bang!)"){|array| array.tap(&:flatten!).tap(&:uniq!).tap(&:compact!) }
  job.report("tap{|a| a.bang! * 3 }"){|array| array.tap{|a| a.flatten!; a.uniq!; a.compact! } }
  job.report("tap{|a| a.bang! } * 3"){|array| array.tap{|a| a.flatten! }.tap{|a| a.uniq! }.tap{|a| a.compact! } }
  job.compare!
end
```

Results:

```
lazy
  279535.8 i/s (±0.92%)
normal
  936240.2 i/s (±1.68%)
bang!
  1014623.9 i/s (±1.31%)
tap(&:bang!)
  856689.9 i/s (±1.96%)
tap{|a| a.bang! * 3 }
  950116.8 i/s (±1.63%)
tap{|a| a.bang! } * 3
  858171.6 i/s (±1.36%)

Comparison:
                  bang!:   1014623.9 i/s
  tap{|a| a.bang! * 3 }:    950116.8 i/s - 1.07x slower
                 normal:    936240.2 i/s - 1.08x slower
  tap{|a| a.bang! } * 3:    858171.6 i/s - 1.18x slower
           tap(&:bang!):    856689.9 i/s - 1.18x slower
                   lazy:    279535.8 i/s - 3.63x slower

```

**Pull request closed without merging**
