### PR TITLE
Add link to 'Pry' in debugging guide [ci skip]

### PR DESCRIPTION
**Pull request by bogdanvlviv**
Add link to [Pry](https://github.com/pry/pry) in "Debugging Rails Applications" guide

### CODE REVIEW

**Comment by vipulnsward** [comment]
We don't happen to "refer" it in this guide, any motivation to add it here?

**Comment by bogdanvlviv** [comment]
It will be good if i will add it to section "6 Plugins for Debugging"?

**Comment by vipulnsward** [comment]
@bogdan yes, that is a more appropriate place

**Comment by bogdanvlviv** [comment]
@vipulnsward done.

**Comment by vipulnsward** [comment]
Thanks!

**Comment by bogdanvlviv** [comment]
@vipulnsward thanks!

**Comment by bogdanvlviv** [comment]
What about replace [Byebug](https://github.com/deivid-rodriguez/byebug) to [Pry](https://github.com/pry/pry)?

**Comment by vipulnsward** [comment]
It was originally added in https://github.com/rails/rails/commit/93559da4826546d07014f8cfa399b64b4a143127 by @rafaelfranca 
I don't use it, so can't comment on its preference.

**Comment by kaspth** [comment]
Rails includes byebug for its own development, so we won't be removing that. 😁

**Comment by rafaelfranca** [comment]
Neither adding support to pry by default in applications. Byebug is our
preferred debugger.

**Pull request merged**
