### PR TITLE
Remove :sorted test order for isolated tests

### PR DESCRIPTION
**Pull request by bogdanvlviv**

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Is not this going to cause more random failures in the already failing test suite?

**Comment by bogdanvlviv** [comment]
When i was working on #28849, i didn't see that this changes provided more random failing test suite? In any way it is correct, it is one of the main purposes `unlock-minitest`, to run tests in random order, isn't it?

**Comment by rafaelfranca** [comment]
Yes, but before adding more entropy in the system we should have a stable system.

**Comment by bogdanvlviv** [comment]
Agree with you, we should leave this for later.

**Pull request closed without merging**
