### PR TITLE
Fix addition of two Active support durations

### LINKED ISSUE #37749: ActiveSupport::Duration hours/minutes/seconds is always seconds
### Steps to reproduce

```ruby
(8.hours + 1.second).parts
=> {:hours=>8, :seconds=>1}
(8.hours + 1.second).seconds
=> 28801 seconds
(8.hours + 1.second).hours
=> 28801 hours
```

### Expected behavior

I'd expect it do return the number of hours/minutes/seconds.

### Actual behavior

It returns the number of seconds but printed as hours?
Perhaps this is a private API or something, but what it prints is very confusing :)

### System configuration
**Rails version**: 5.2.3

**Ruby version**: 2.6.5

### PR DESCRIPTION
**Pull request by vikasvr**
This fixes https://github.com/rails/rails/issues/37749.
When we write 8.hours it creates ActiveSupport::Duration object https://github.com/rails/rails/blob/f78fb42b51c2226b5e87d5c637604f1d85b68b14/activesupport/lib/active_support/core_ext/numeric/time.rb#L29 which multiples with number of seconds it contains thus multiplying 8 * 60 * 60 setting attribute `value` as 28800.
When we call minutes on this object, since ActiveSupport::Duration doesn't have any instance method `minutes` it goes to method missing defined here https://github.com/rails/rails/blob/f78fb42b51c2226b5e87d5c637604f1d85b68b14/activesupport/lib/active_support/duration.rb#L429

This method call method `minutes` on the value of the current instance which is `28800` which is of numeric class and respond from https://github.com/rails/rails/blob/f78fb42b51c2226b5e87d5c637604f1d85b68b14/activesupport/lib/active_support/core_ext/numeric/time.rb#L21 where it creates ActiveSupport::Duration minutes object with argument 28800 which is same as calling 28800.minutes

Therefore added instance methods minutes, hours, days, weeks, months and years thus using value of the current instance dividing with seconds it contains , for example for hours it will divide with 3600, for minutes dividing with 60 returning our expected result.

They are two ways to fix it, either modify method missing method implemented for ActiveSupport::Duration or add these methods to the class. In this pull request I have added methods but alternative approach would fix it too.

Now calling methods like minutes, hours gives more consistent results.

```
Before Change:
1.hour 
=> 1 hour
1.hour.minutes 
=> 3600 minutes
1.hour.minutes.minutes 
=> 216000 minutes

After Change:
1.hour 
=> 1 hour
1.hour.minutes 
=> 60 minutes
1.hour.minutes.minutes 
=> 60.minutes
1.hour.minutes.minutes.minutes
=> 60.minutes
```

### CODE REVIEW

**Comment by vikasvr** [comment]
Now calling methods like minutes, hours gives more consistent results.

```
In master:
1.hour 
=> 1 hour
1.hour.minutes 
=> 3600 minutes
1.hour.minutes.minutes 
=> 216000 minutes

Now:
1.hour 
=> 1 hour
1.hour.minutes 
=> 60 minutes
1.hour.minutes.minutes 
=> 60.minutes
1.hour.minutes.minutes.minutes
=> 60.minutes
```

**Comment by vikasvr** [comment]
Hey @pixeltrix , any comments on the code I did to fix the issue ?

**Comment by jasonyork** [comment]
This seems somewhat similar to the PR I submitted here: #38699

**Comment by vikasvr** [comment]
@jasonyork That's ok I think, We all are coming with almost same solutions. 
I came up with this solution in Jan, you coming up with yours in march and I see one more developer coming in April.

We all are tying our best to fix issues and that's whats count I guess.

**Comment by KapilSachdev** [comment]
Resolved in #38699

**Pull request closed without merging**
