### PR TITLE
Fix activejob integration test

### PR DESCRIPTION
**Pull request by troter**
- fix activejob integration test's queue_adapter initialization.
- avoid double initialization error caused to sidekiq

### CODE REVIEW

**Comment by rafaelfranca** [comment]
If what you wrote about initializers orders is true this is a bug in the code, not in the test suite. Also can we not call `Sidekiq::CLI#boot_system`?

**Comment by troter** [comment]
@rafaelfranca thank you for your comments.

> If what you wrote about initializers orders is true this is a bug in the code, not in the test suite.

This is initializer dipendencies of 4-2-stable and master.
- https://gist.github.com/troter/99e70bbd1292e3273bab#file-4-2-stable-master-diff

`active_support.halt_callback_chains_on_return_false` is seem to cause.

- https://gist.github.com/troter/99e70bbd1292e3273bab#file-4-2-stable-master-diff-L20

> Also can we not call Sidekiq::CLI#boot_system?

`Sidekiq::CLI#run` call `Sidekiq::CLI#boot_system` at first.

- https://github.com/mperham/sidekiq/blob/master/lib%2Fsidekiq%2Fcli.rb#L49

I guess that it is possible to call a `Sidekiq::Launcher` directly.

**Comment by rafaelfranca** [comment]
Could you print the actual initializer order instead of the order by name and run the compare them?

@mperham what do you think about https://github.com/troter/rails/commit/3184b964aa57a333eb0051dbfe656eb1d60d9798?

**Comment by rafaelfranca** [comment]
Yeah, just found that `halt_callback_chains_on_return_false` is the cause of that problem. I'll fix it.

**Comment by mperham** [comment]
@rafaelfranca I would use Sidekiq::Launcher.  The CLI code is not designed to run within another process.

**Comment by rafaelfranca** [comment]
@troter the first commit should not be necessary after 0a120a818d413c64ff9867125f0b03788fc306f8. Now could you use `Sidekiq::Launcher`?

**Comment by troter** [comment]
@rafaelfranca I add commit 9c047c8, this change use `Sidekiq::Launcher` directly. please re-review it.

**Comment by rafaelfranca** [comment]
Thank you. Merged at https://github.com/rails/rails/commit/b126e7aaaa61c9264481e52053c43d624fef2034

**Pull request closed without merging**
