### PR TITLE
Use Cssbundling::BUNDLER_LIST on rails new

### PR DESCRIPTION
**Pull request by ceritium**
### Summary

New output:

```
[--css=CSS] ... # Choose CSS processor [options: tailwind, bootstrap, bulma, postcss, sass]
```

### Other Information

Related to: https://github.com/rails/rails/issues/43251
It depends on: https://github.com/rails/cssbundling-rails/pull/25

## TODO:

- [x] Rebase with main after merge https://github.com/rails/rails/pull/43256 or similar fix.
- [ ] Update Gemfile if cssbundling-rails PR is merged

### CODE REVIEW

**Comment by dhh** [comment]
I'd rather we point to the cssbundling-rails repo, actually. I purposefully made it such that we didn't have to change rails when we gained new installers. Just need to make the docs match.

**Comment by ceritium** [comment]
Do you think something like this?

```
[--css=CSS] ... # Choose CSS processor [options: tailwind, postcss, sass... check https://github.com/rails/cssbundling-rails]
```

It's ok for me, but it requires upgrading the gemfile.lock on rails anyway when we gain new installers.

**Comment by dhh** [comment]
"requires upgrading the gemfile.lock on rails", shouldn't. It runs the installer from the gem that's installed with the new app. Not the one linked in Rails. So should automatically pickup new installers.

**Comment by ceritium** [comment]
You are right again, with `rails new ~/work/rails-test-edge --edge --css=bootstrap` it works fine, but I was testing it with `bundle exec rails new ~/work/rails-test --dev --css=bootstrap` inside the `rails` repo.

It fails with: 
```
      append  config/importmap.rb
       rails  css:install:bootstrap
rails aborted!
Don't know how to build task 'css:install:bootstrap' (See the list of available tasks with `rails --tasks`)
Did you mean?  css:install:postcss
```

It is the expected behavior with `--dev`? In any case, I will take it into account in the future.

Because the path is clear, I am going to close both PRs. Thanks for your time!

**Pull request closed without merging**
