### PR TITLE
Fix redirect location for protocol relative URL

### PR DESCRIPTION
**Pull request by timothee-alby**
[RFC 2616](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.30) require an absolute URL for the location header. Although it's deprecated since June 2014, many user agents still implement it.
Most user agents follow protocol relative redirection fine, but some don't and might fail to follow the redirect.

### CODE REVIEW

**Comment by matthewd** [comment]
> some user agents fails to follow protocol relative URL

Which ones?

By the time proxies get involved, I'm sure this will be a breaking change for some people. So if we're going to change documented behaviour in order to conform with a (relatively) rarely enforced rule in a deprecated RFC, let's explore the nature of the trade-off.

**Comment by timothee-alby** [comment]
I have no such example at hand, unfortunately. The issue was reported by one of our users using PHP, I'll try to get more info.

Agree not to merge that if the change actually has a bigger impact that I thought

**Comment by timothee-alby** [comment]
I did some tests and found an implementation causing the issue: PHP's `file_get_content` (tested with version `5.5.20`). 
When `file_get_content` hit a redirect it will try to follow it, but that doesn't handle the protocol-relative URLs and thread them as a relative paths.

Now that might be PHP's problem, not Rails', but IMHO it's generally better to be strict with the output. Up to you guys to decide.

**Comment by timothee-alby** [comment]
@matthewd any view on my update?

**Comment by manish-shrivastava** [comment]
@timothee-alby , As per my understandings your changes seems not satisfactory as you have fixed protocol to `http` in `"//www.rubyonrails.org/` before it was flixible enough to support other protocols as well. i.e. `https` etc.

**Comment by timothee-alby** [comment]
Indeed it's fixed to `http` in the tests, but the code uses `request.protocol`, so it will create a link using whatever protocol is currently used.

**Comment by rafaelfranca** [comment]
> By the time proxies get involved, I'm sure this will be a breaking change for some people. So if we're going to change documented behaviour in order to conform with a (relatively) rarely enforced rule in a deprecated RFC, let's explore the nature of the trade-off.

Yeah, I think it is not worth to introduce a breaking change for this case.

Thank you so much.

**Pull request closed without merging**
