### PR TITLE
Remove legacy mysql adapter

### PR DESCRIPTION
**Pull request by kamipo**
Follow up to #22642.

### CODE REVIEW

**Comment by sgrif** [comment]
I'd like to re-raise this issue. I'd like to propose that we revert #22642 and hold of on merging this until master is tracking 5-1-stable. There's very little cost to us maintaining this for a few more weeks, and we can save our users that are still using the legacy adapter a full version before they have to deal with upgrade pain. It would also give us more time to deal with getting it extracted to a gem that someone else can maintain.

**Comment by rafaelfranca** [comment]
> There's very little cost to us maintaining this for a few more week

It is not a few week. It is until the Rails 5.2 or whatever the N+2 release will be called. Don't forget that we still support the stable release and sometimes two stable releases, what means that we may support it for more that 2 years.

**Comment by sgrif** [comment]
I'm fine with being responsible for bugfixes for however long 5-0-stable is supported.

**Comment by rafaelfranca** [comment]
@sgrif I'm fine with that. Of course I don't mind to support too, but we would have removed it in Rails 4.2 and we didn't finished. I don't see why keep it in Rails 5. People can upgrade to mysql2 adapter before upgrading to Rails 5. Or we can finish the extraction to a gem before the Rails 5 final. I prefer to extract it now and I think it is possible if someone focus on that.

**Comment by sgrif** [comment]
@rafaelfranca Don't get me wrong. The adapter has been painful to keep around and I'm happy to see it go, and I'm definitely in favor of extracting it. But it doesn't seem like there's much work on that front, and I'd like to make sure that anyone still using it has a straightforward migration path for Rails 5 (assuming that just switching to mysql2 isn't necessarily an option).

I guess for now let's go ahead and continue as we have, and if the issue hasn't been resolved by the time we get into RCs we can revisit.

**Comment by rafaelfranca** [comment]
@sgrif agree. Let make sure we have it extracted before the RC. @seuros mind to work on that?

**Comment by bronson** [comment]
Worth updating the docs and guides too?  I can file a PR.

I only see two locations that need updating:

* https://github.com/rails/rails/blob/master/guides/source/development_dependencies_install.md#active-record-setup
* https://github.com/rails/rails/blob/master/guides/source/contributing_to_ruby_on_rails.md#testing-active-record

**Comment by matthewd** [comment]
@bronson :+1:

**Comment by bronson** [comment]
OK, it's in https://github.com/rails/rails/pull/22983

Doing what I can to discourage this PR from being reverted.  :)

**Pull request merged**
