### PR TITLE
ImmutabilityValidator

### PR DESCRIPTION
**Pull request by dsounded**
This validator helps to keep attributes in the same state as their were
created by default. They works for persited records in AR and base
objects in ActiveModel.

Use cases: If you need default values to not be changed in ActiveModel objects or not changeable values in the database in ActiveRecord objects

Usage:

```
class Person < ActiveRecord::Base
  validates_immutability_of :first_name
end
```

### CODE REVIEW

**Comment by bogdan** [comment]
+1 for that. That is pretty common case.

**Comment by simi** [comment]
Isn't  [attr_readonly ](http://api.rubyonrails.org/classes/ActiveRecord/ReadonlyAttributes/ClassMethods.html#method-i-attr_readonly) meant to do this? Maybe ```attr_readonly :ryba, validation: true``` can be added.

**Comment by rafaelfranca** [comment]
> Isn't attr_readonly meant to do this?

Yes, it is.

**Comment by rafaelfranca** [comment]
Thank you for the pull request but I don't think this is a pretty common case. Also you can use `attr_readonly` for that.

**Comment by vbyno** [comment]
Unfortunately `attr_readonly` just ignores sent value and does not add an error to the model. Would vote +1 for this too

**Comment by rafaelfranca** [comment]
Like I said, I don't think this is a pretty common case to include in the framework, but feel free to build a gem with it.

**Comment by simi** [comment]
Actually this doesn't make sense at all. Why would you show input field in the form if that can't be saved?

**Comment by vbyno** [comment]
@simi, It would be useful for API requests
@rafaelfranca, it's just a thought :smile:, never mind

**Comment by simi** [comment]
@vbyno in API request you know if that field should be passed to model or not (via strong params for example).

**Comment by vbyno** [comment]
@simi, I agree. Developer knows what fields should be passed. But what about the user? He/she sends valuable params and they are just ignored by strong params or `attr_readonly` with no error. 200 OK.

**Comment by simi** [comment]
That should be marked as unexpected input and 422 (or 400 - depends on situation) status should be responded.

**Pull request closed without merging**
