### PR TITLE
Make Rubocop happy about ActiveStorage

### PR DESCRIPTION
**Pull request by claudiob**
Running `rubocop activestorage` before this commit resulted in 20 offenses.
All the straightforward offenses have been fixed.
Only the "Redundant curly braces around a hash parameter" offenses are left
since I'm not sure what is the best way to clean up that code:
https://github.com/rails/rails/blob/9394451/activestorage/test/models/attachments_test.rb#L69-L92

```
Inspecting 74 files
C...C..CC.CCC...................C...........C..................C.......C..

Offenses:

activestorage/activestorage.gemspec:30:4: C: Final newline missing.
end

activestorage/app/controllers/active_storage/disk_controller.rb:34:1: C: Extra blank line detected.
activestorage/app/controllers/active_storage/disk_controller.rb:43:1: C: Extra blank line detected.
activestorage/app/models/active_storage/attachment.rb:4:97: C: Trailing whitespace detected.
activestorage/app/models/active_storage/blob.rb:66:1: C: Extra blank line detected.
activestorage/app/models/active_storage/blob.rb:118:1: C: Extra blank line detected.
activestorage/app/models/active_storage/blob.rb:161:1: C: Extra blank line detected.
activestorage/app/models/active_storage/variant.rb:66:1: C: Extra blank line detected.
activestorage/app/models/active_storage/variation.rb:3:104: C: Trailing whitespace detected.
activestorage/config/routes.rb:11:1: C: Extra blank line detected.
activestorage/config/routes.rb:12:6: C: Put one space between the method name and the first argument.
  get  "/rails/active_storage/variants/:signed_blob_id/:variation_key/*filename" => "active_storage/variants#show", as: :rails_blob_variation
     ^^
activestorage/config/routes.rb:24:1: C: Extra blank line detected.
activestorage/test/controllers/disk_controller_test.rb:21:1: C: Extra blank line detected.
activestorage/test/dummy/config/application.rb:15:1: C: Extra blank line detected.
activestorage/test/models/attachments_test.rb:61:1: C: Extra blank line detected.
activestorage/test/models/attachments_test.rb:72:7: C: Redundant curly braces around a hash parameter.
      { io: StringIO.new("IT"), filename: "country.jpg", content_type: "image/jpg" })
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
activestorage/test/models/attachments_test.rb:81:7: C: Redundant curly braces around a hash parameter.
      { io: StringIO.new("IT"), filename: "country.jpg", content_type: "image/jpg" })
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
activestorage/test/models/attachments_test.rb:92:7: C: Redundant curly braces around a hash parameter.
      { io: StringIO.new("IT"), filename: "country.jpg", content_type: "image/jpg" })
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
activestorage/test/models/attachments_test.rb:99:1: C: Extra blank line detected.
activestorage/test/service/s3_service_test.rb:38:101: C: Space inside } missing.
      config  = SERVICE_CONFIGURATIONS.deep_merge(s3: { upload: { server_side_encryption: "AES256" }})
                                                                                                    ^

74 files inspected, 20 offenses detected
```

### CODE REVIEW

**Comment by georgeclaghorn** [comment]
Almost all of the extra newlines you removed are intentional. We should remove the RuboCop rule that flags them.

**Comment by georgeclaghorn** [comment]
Regarding the “redundant curly braces” offenses, the cop has a `:context_dependent` option that should be set to true. See [this discussion](https://github.com/rails/activestorage/pull/45#discussion_r127338463).

**Comment by sgrif** [comment]
If the methods can be logically grouped together to the point where we want to visually separate them, should they be extracted to a new object or module?

**Comment by georgeclaghorn** [comment]
No, most of these groups don’t warrant a new module.

**Comment by matthewd** [comment]
A single `#` separator might satisfy rubocop, while keeping the rule to catch more accidental double-newlines. Maybe?

(I'm not particularly attached to it -- my own style uses this form of grouping too -- but if we're going to enforce rules, we have to have rules to enforce)

**Comment by georgeclaghorn** [comment]
Appeasing RuboCop with an empty comment just so we can continue to enforce a rule that doesn’t suit us sounds backwards.

**Comment by claudiob** [comment]
I've revisited this specific commit to only fix:
    
- Trailing whitespace detected
- Space inside } missing
- Put one space between the method name and the first argument.
    
The other offenses are left since they might be intentional. 
Can be removed later.

**Comment by rafaelfranca** [comment]
> Appeasing RuboCop with an empty comment just so we can continue to enforce a rule that doesn’t suit us sounds backwards.

I'm sorry but this "These are all intentional to group related method sets together" rule that was recently added, and I don't think it suits us, so if there is something backwards is this new rule.

I particularly think is a bad thing to add invisible characters to group methods. Grouping methods together with invisible characters only makes sense in the head of who wrote them. For who is reading that group may not make any sense. So if we need to group something let at least make that group explicit with a comment.

 It is also opening cases were we have a lot of blank lines that are only added by mistake, so I really prefer us to keep enforcing that rule that was always enforced and if we need to group methods let add comments describing why those groups make sense.

**Comment by rafaelfranca** [comment]
Like could you explain why `service_url`, `service_url_for_direct_upload`, `service_headers_for_direct_upload`, `upload` and `download`? I can see a reason for the first three be grouped together but the last two don't seem to be in the same group.

And how about `signed_id`, `key`, `filename`, `image?`, `audio?`, `video?` and `text?`? It looks like two different groups to me but they are all in the same group.

That said, I don't think this kind of visual group created with an empty line adds anything to who is reading the code, or who is going to contribute to that code, that is the main target here because uses usually only look at the API website and on that website those groups are not visible at all.

**Comment by georgeclaghorn** [comment]
I really don’t think this needs the attention it’s getting, so I‘ll bow out. /cc @dhh

**Comment by dhh** [comment]
Agree with @georgeclaghorn. I like using extra lines to group related methods, and I don't see "pleasing rubocop" as a compelling reason to stop. I don't agree with groupings only making sense in the head of people who made them. We have all sorts of visual tools to better present the code. This is one of those tools in the arsenal.

Happy to discuss which particular groupings make sense, though. But I don't see a compelling discussion on the merits of "does visual groupings through extra linebreaks make for better reading code". That's an inherently subjective assessment, and thus I'm happy to simply invoke creator's privilege on that count. (Unless there are other arguments that I haven't considered that extend beyond "well, I don't think it's better").

**Comment by rafaelfranca** [comment]
I'm merging this since it doesn't remove the grouping. I disagree with the reasons for those grouping, but I'm happy to agree to disagree.

**Comment by dhh** [comment]
❤️👌

**Pull request merged**
