### PR TITLE
ActiveRecord update_all and delete_all - add support for lock!

### PR DESCRIPTION
**Pull request by stefkin**
### Summary
Sometimes it's useful to perform explicit locking in delete and update statements. It can help to avoid deadlocks.

When I try to perform explicit locking on scope update_all and delete_all ignores it.

I described it in detail in the issue #38889

I added support for lock in ActiveRecord update_all and delete_all

I have only changed prepare_update_subquery in arel/visitors/to_sql for now so it doesn't work for mysql. I'll update it if the changes look good to you.

### CODE REVIEW

**Comment by simi** [comment]
:wave: I'm working on similar change supporting (keeping) WITH (CTE) statements around. You can find the code at https://github.com/rails/rails/pull/37973/files#diff-242004ec18334e8a5e3b3ceb84ea468b. Our approaches seems same. :+1: 

:thinking: I was wondering if there's any way to do other way around and at least warn if any of your statement modified into INSERT/UPDATE/DELETE statement would not preserve any of nodes from original statement to prevent unexpected queries being executed.

**Comment by stefkin** [comment]
>  I was wondering if there's any way to do other way around and at least warn if any of your statement modified into INSERT/UPDATE/DELETE statement would not preserve any of nodes from original statement to prevent unexpected queries being executed.

It would be nice to notify users if any of the statement parts were dropped when building a subquery. Certainly helps to avoid similar issues.
But it seems like quite a big change. It could affect other features in development and requires detailed discussion in the core team.

**Comment by simi** [comment]
Sure, that comment wasn't meant to be addressed in this pull request.

**Comment by stefkin** [comment]
I fixed the issue for mysql as well as the tests for sqlite. Waiting for review.

**Comment by kamipo** [comment]
Similar with https://github.com/rails/rails/pull/39618#discussion_r443119612:

> Unlike `ORDER`, `LIMIT`, and `JOIN`, AFAICS `GROUP BY` and `HAVING` are not valid clauses for UPDATE and DELETE statements in all supported RDBMSes (the formers are valid clauses for UPDATE and DELETE statements in MySQL, that is the reason why those are had in the statements to avoid subselect generation).
>
> So I'd suggest to push the conditions as subselect from the beginning if a relation has a `GROUP BY` or `HAVING`.

If `lock` (`FOR UPDATE`) is always a part of subquery, can we push the conditions as a subselect from the beginning in that case?

**Comment by stefkin** [comment]
@kamipo
Thanks for your feedback, good point. 
I've tried to build subselect straight away and realised that we use a different approach to building it in MySql
(see comments for details: https://github.com/rails/rails/blob/master/activerecord/lib/arel/visitors/mysql.rb#L75)

As a result, we'd have to know which adapter we're using in AR::Relation which is not ideal (we can access it via @klass.connection but it seems messy)

Maybe we could use my previous approach with building the subquery in visitor or you could suggest some way of implementing the mysql-specific subselecting from the beginning more cleanly?

**Comment by stefkin** [comment]
@kamipo Please check out the updated version. I've added the mysql-specific logic I mentioned before.

**Comment by stefkin** [comment]
@kamipo @simi please review when you have time

**Comment by coffenbacher** [comment]
I'm trying to resolve a deadlock and I feel like this feature would have been helpful. Was an equivalent ever implemented?

**Comment by stefkin** [comment]
> I'm trying to resolve a deadlock and I feel like this feature would have been helpful. Was an equivalent ever implemented?

AFAIK no

**Pull request closed without merging**
