### PR TITLE
Fix grammar errors in security and migrations docs master [ci skip]

### PR DESCRIPTION
**Pull request by mgm702**
Hi there,

I found some grammatical errors in the Rails documentation that I felt needed to be fixed. The changes are on this pull request, please let me know if you need anything else!

### CODE REVIEW

**Comment by maclover7** [comment]
Can you add `[ci skip]` to your commits, and squash down?

**Comment by mgm702** [comment]
Yes, I can do that. The commits now have the [ci skip] added to them and they're squashed down as well.

**Comment by maclover7** [comment]
:+1: Thank you for your contribution!

**Comment by maclover7** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by mgm702** [comment]
Thanks, I appreciate it! :smile:

**Pull request merged**
