### PR TITLE
Verify postgresql database name configuration

### PR DESCRIPTION
**Pull request by AaronCowan**
### Summary

This pull request references #29429. An error occurs when a database name is all numbers (12345) or the first character is a number. My changes will halt execution and display an informative error message if the name is all numbers or begins with a number.

### CODE REVIEW

**Review by gmcgibbon — COMMENTED** [review]
Still a problem in `6.0.0.alpha` but only when dumping and loading schemas. If we're certain we don't want to stringify `args` in `#run_command`, validating all config values are strings (or maybe just stringifying non-nil values in the initializer) seems like enough to me.

**Comment by AaronCowan** [comment]
I would like to work on this if nobody else has already.

**Comment by AaronCowan** [comment]
If this is an approved implementation I'll add the verify_configuration! method to loading the schema as well.

**Comment by gmcgibbon** [comment]
🤔 I took another look at this and it seems that I misspoke. Its not `#run_command`, its `#run_cmd` [here](https://github.com/rails/rails/blob/d690af13fcdae086b08dc0043643f5a66ea8cb06/activerecord/lib/active_record/tasks/mysql_database_tasks.rb#L105) (and the same method in classes for [PostgreSQL](https://github.com/rails/rails/blob/d690af13fcdae086b08dc0043643f5a66ea8cb06/activerecord/lib/active_record/tasks/postgresql_database_tasks.rb#L116) and [SQLite](https://github.com/rails/rails/blob/d690af13fcdae086b08dc0043643f5a66ea8cb06/activerecord/lib/active_record/tasks/sqlite_database_tasks.rb#L72)). Migrating, creating DBs, and dumping/loading schemas works with numeric database names as of d690af13fcdae086b08dc0043643f5a66ea8cb06.

At this point, I'm more in favor of just stringifying args in `#run_cmd` because adding validations for the structure dumping and loading tasks only seems like overkill. What do you think @rafaelfranca?

**Pull request closed without merging**
