### PR TITLE
Switch to native unicode implementation for ruby 2.4+

### PR DESCRIPTION
**Pull request by mtsmfm**
### Summary

@jeremy proposes switching to native unicode implementation.

https://github.com/rails/rails/pull/26743#issuecomment-279277662

So I tried to implement that.

(cc @amatsuda)

If we merge this PR:

- Drop public API on Ruby 2.4+ (but these methods are internal use only and should be private I think)
  - [in_char_class?](https://github.com/rails/rails/blob/e5ce096823798a920fdabe9d020f45e2cdc8fb06/activesupport/lib/active_support/multibyte/unicode.rb#L71)
  - [reorder_characters](https://github.com/rails/rails/blob/e5ce096823798a920fdabe9d020f45e2cdc8fb06/activesupport/lib/active_support/multibyte/unicode.rb#L143)
- We won't be able to bump ActiveSupport's unicode version

  Ruby has its own supported unicode version and also ActiveSupport.
  If we bump unicode version on Rails 5.2, `AS::Multibyte` can handle chars as 10.0.0 on ruby 2.3 but 9.0.0 on 2.4.

| Rails | Ruby version      | Unicode version | Unicode implementation |
| ----- | ----------------- | -------------   | ---------------------  |
| 5.1   | 2.3               | 9.0.0           | Non-native             |
| 5.1   | 2.4               | 9.0.0           | Native                 |
| 5.2   | 2.3               | 10.0.0          | Non-native             |
| 5.2   | 2.4               | 9.0.0 (!!!)     | Native                 |

### CODE REVIEW

**Review by jeremy — COMMENTED** [review]
This is cool. Nice work!

> If we bump unicode version on Rails 5.2, AS::Multibyte can handle chars as 10.0.0 on ruby 2.3 but 9.0.0 on 2.4.

It's confusing for sure. However, this is getting close to the endgame we've always imagined for AS::Multibyte: to step aside when Ruby has comparable native Unicode support.

One route we could take is to let apps choose their Unicode backend rather than have it chosen for you based on Ruby 2.4+ usage. That'd give us the first step toward (eventually) deprecating this entire subsystem.

**Comment by mtsmfm** [comment]
> let apps choose their Unicode backend rather than have it chosen for you based on Ruby 2.4+ usage

Thank you for your advise!
I'll implement it!

**Comment by mtsmfm** [comment]
@jeremy I Implemented Unicode backend.
Could you review this PR? :pray: 

----------

I think it is better to delegate Unicode methods to backend instance or module rather than  using `undef_method`/`define_method`.
But for backward compatibility, I can't find any way to not use these hack :dizzy_face: 

Let's think of following case:

```ruby
$: << "./activesupport/lib"
require "active_support/all"

class Foo
  include ActiveSupport::Multibyte::Unicode

  def initialize
    @default_normalization_form = :kc
  end

  def foo
    normalize("ｆｏｏ")
  end
end

class Bar
  include ActiveSupport::Multibyte::Unicode

  def bar
    normalize("ｂａｒ")
  end
end

puts Foo.new.foo
# => foo
puts Bar.new.bar
# foo.rb:20:in `bar':  is not a valid normalization variant (ArgumentError)
#         from foo.rb:26:in `<main>'
```

We must consider instance-level `@default_normalization_form` for `normalize`
because it isn't only declared as class-level instance variable but also instance-level instance variable by [`attr_accessor`](https://github.com/rails/rails/blob/fde46f43bd8913c06e42f936dfde363a55edf774/activesupport/lib/active_support/multibyte/unicode.rb#L19) and [`extend self`](https://github.com/rails/rails/blob/fde46f43bd8913c06e42f936dfde363a55edf774/activesupport/lib/active_support/multibyte/unicode.rb#L4).
It may be not intentional behavior, however, this is how current implementation works.

**Comment by tenderlove** [comment]
Adding the backend seems good. Should we emit a warning if people change the backend though? This seems like an escape valve we should remove at some point.

**Comment by mtsmfm** [comment]
@tenderlove Did you mean "we should emit a warning when `ActiveSupport::Multibyte::Unicode.backend=` is called" ?

**Comment by kamipo** [comment]
Closing in favor of #26743.

**Pull request closed without merging**
