### PR TITLE
Use frozen-string-literal in ActiveRecord

### PR DESCRIPTION
**Pull request by kirs**
Follow-up to https://github.com/rails/rails/pull/29655

Extends `Style/FrozenStringLiteralComment` Rubocop rule to `activerecord/`.

ref https://github.com/rails/rails/pull/29728

@matthewd @rafaelfranca

### CODE REVIEW

**Comment by matthewd** [comment]
Missed the rule change itself?

(I'm assuming these are just a change to `.rubocop.yml` + a run of `rubocop -a`, right?)

**Comment by kirs** [comment]
> Missed the rule change itself?

Forgot to git add `.rubocop.yml` 🙈 

> (I'm assuming these are just a change to .rubocop.yml + a run of rubocop -a, right?)

Yes, except one test that verified that the first line contains the comment (now it's the second line):

```diff
diff --git a/activerecord/test/cases/migration_test.rb b/activerecord/test/cases/migration_test.rb
index eff6e09..bb68968 100644
--- a/activerecord/test/cases/migration_test.rb
+++ b/activerecord/test/cases/migration_test.rb
@@ -1,3 +1,4 @@
+# frozen_string_literal: true
 require "cases/helper"
 require "cases/migration/helper"
 require "bigdecimal/util"
@@ -912,7 +913,7 @@ def test_copying_migrations_without_timestamps
     assert_equal [@migrations_path + "/4_people_have_hobbies.bukkits.rb", @migrations_path + "/5_people_have_descriptions.bukkits.rb"], copied.map(&:filename)

     expected = "# This migration comes from bukkits (originally 1)"
-    assert_equal expected, IO.readlines(@migrations_path + "/4_people_have_hobbies.bukkits.rb")[0].chomp
+    assert_equal expected, IO.readlines(@migrations_path + "/4_people_have_hobbies.bukkits.rb")[1].chomp

     files_count = Dir[@migrations_path + "/*.rb"].length
     copied = ActiveRecord::Migration.copy(@migrations_path, bukkits: MIGRATIONS_ROOT + "/to_copy")
```

**Comment by koic** [comment]
@kirs Thanks for introducing frozen string literal.

`Layout/EmptyLineAfterMagicComment` cop enabled at #29748.

Would you please apply autocorrect of `Layout/EmptyLineAfterMagicComment` cop?

**Comment by kirs** [comment]
Thanks for letting me know @koic!

I rebased and updated the PR. I think it's good to merge it.

**Comment by matthewd** [comment]
@kirs the failures look real to me

**Comment by yahonda** [comment]
`FoxyFixturesTest#test_namespaced_models` error reproduces only when tests executed in this order.

```ruby
ARCONN=mysql2 bundle exec ruby -w -I"lib:test" -I"/home/yahonda/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib" "/home/yahonda/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/rake_test_loader.rb" "test/cases/associations/belongs_to_asso
ciations_test.rb" "test/cases/fixtures_test.rb"
ARCONN=postgresql bundle exec ruby -w -I"lib:test" -I"/home/yahonda/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib" "/home/yahonda/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/rake_test_loader.rb" "test/cases/associations/belongs_to_
associations_test.rb" "test/cases/fixtures_test.rb"
```
Also it has already fixed by #29808 in `unlock-minitest` branch .

**Comment by yahonda** [comment]
Current conflicts with #29812.

**Comment by kirs** [comment]
Thanks for letting me know @yahonda. I spent some time last weekend trying to figure out what caused those fixtures tests to fail, but I couldn't reproduce them. Good to know they've been fixed by #29808!

I rebased the branch. Let's see what the CI shows.

**Comment by yahonda** [comment]
Thanks for the quick response. Unfortunately, CI is still showing failures since #29808 has been made for `unlock-minitest` branch discussed in #29271, not merged to master yet.  I should have mentioned more clearly.

Since we cannot control test orders then how about cherry-picking https://github.com/rails/rails/pull/29808/commits/ad22c38d77ad3ea62aee04f822e8a5e571c5d4e3 to your pull request which would address `FoxyFixturesTest#test_namespaced_models` errors for this pull request.

**Comment by kirs** [comment]
Cherry-picked the fix. ActiveRecords tests are now 🍏

**Comment by kirs** [comment]
@matthewd this should be good to merge. Sorry for pinging you last time and not making sure that the CI is green.

**Pull request merged**
