### PR TITLE
Fix connections reaper not running after forking.

### PR DESCRIPTION
**Pull request by tgxworld**
This broke in 3e2e8eeb9ea552bd4782538cf9348455f3d0e14a where it switched
to one reaper thread per process. However, the implementation will only
spawn the reaping thread if the reaping frequency has not been seen.
Since the reaping frequencies are stored in a class instance variable,
that variable is copied when the process is forked. As such, a forked
process will not spawn a new reaping thread since the class instance
variable would have contain the reaping frequency that was seen in the
parent process.

Also reverts the use of `WeakRef` introduced in
6302e56d6c1fec048f6438d9f1ac6a8cfaed7eb9 since we properly deregisters
connection pools from the reaper upon discard/disconnect.

### Script to reproduce the problem

```
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'pg'
  gem 'rails', path: '/home/tgxworld/work/rails'
end

require 'active_record'

ActiveRecord::Base.establish_connection(
  :adapter => "postgresql",
  :database => "testdb",
  :reaping_frequency => 1,
)

puts "#{Process.pid} main process"

fork do
  puts "#{Process.pid} forked process"

  ActiveRecord::Base.establish_connection(
    :adapter => "postgresql",
    :database => "testdb",
    :reaping_frequency => 1,
  )

  loop { sleep 1; puts "#{Process.pid} #{Thread.list}"; }
end

loop { sleep 1; puts "#{Process.pid} #{Thread.list}" }
```

cc @jhawthorn @rafaelfranca  @tenderlove

### CODE REVIEW

**Comment by tgxworld** [comment]
@jhawthorn Thanks for the background regarding the use of weakref. I've updated the PR to properly remove the connection pool from the reaper upon disconnect  as well.

**Comment by jhawthorn** [comment]
@tgxworld Could you take a look at #36998 based on this ❤️

I've tried to test the behaviour we expect to see (connections in a fork are reaped) rather than the implementation specifics. I'm also not comfortable using `ObjectSpace` in a test, I think it will be unreliable even if we explicitly GC.

I also didn't apply the `reaper.stop`/`deregister_pool`, I don't believe we should need it, since we can just find any GC'd pools at the next pass of the reaper.

**Comment by tgxworld** [comment]
Closed by https://github.com/rails/rails/pull/36998

**Comment by tgxworld** [comment]
> I've tried to test the behaviour we expect to see (connections in a fork are reaped) rather than the implementation specifics.

@jhawthorn  Thank you for this :+1: I read through your test cases and I agree that testing the behavior is much more resilient than testing for the implementation details.

**Pull request closed without merging**
