### PR TITLE
Collation in MySQL, PostgreSQL and SQLite adaptors.

### PR DESCRIPTION
**Pull request by akshay-vishnoi**
## Status: Completed
1. Add collation on columns.
2. Give migration support for collation in
   1. `create_table`
   2. `add_column`
   3. `change_column`
3. Update `schema.rb`
## Status: Pending
1. Test Coverage.
2. Add method `change_column_collation`

@rafaelfranca - Please have a look at it. Check [this gist](https://gist.github.com/rafaelfranca/7274fd46f3195b46734f)(private) for reference. Please review this and let me know if you want some changes. I will add tests after review.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Related with https://github.com/rails/rails/pull/17574

**Comment by akshay-vishnoi** [comment]
@rafaelfranca  - I didn't see #17574. Do I need to close this PR?

**Comment by rafaelfranca** [comment]
No. I'm just linking both PRs to make easier to review

**Comment by jeremy** [comment]
:metal:

**Comment by rafaelfranca** [comment]
@akshay-vishnoi now that @jeremy merged #17574, could you rebase it?

**Comment by akshay-vishnoi** [comment]
@rafaelfranca  - Rebase Done!!

**Comment by rafaelfranca** [comment]
@akshay-vishnoi now we only need the sqlite3 support. Can you get the @kamipo's tests from #19978 and implement it.

**Comment by akshay-vishnoi** [comment]
@rafaelfranca  - I have raised PR #20041. Please review it, we can close this PR then.

**Comment by kamipo** [comment]
#20041 is already merged.

**Pull request closed without merging**
