### PR TITLE
Fix primary_abstract_class with engines

### LINKED ISSUE #43247: `primary_abstract` has conflicts with multiple engines in Rails 7.0.0.alpha2
### Steps to reproduce
I've created this app https://github.com/pinzonjulian/primary_abstract to reproduce the issue I'm having. Each commit in it is one of the following steps:
- Create new host rails app using 7.0.0.alpha2
- Create an engine: `ExampleApp`
- Create model in the engine: `User`
- Create second engine: `DifferentApp`
- Create model in second engine: `User`

### Expected behaviour
I should be able to access both models from the Rails console in the host app

### Actual behaviour
```zsh
# /host_app
rails c
```
```ruby
DifferentApp::User.count
# => 0

ExampleApp::User.count
# => .asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-7.0.0.alpha2/lib/active_record/inheritance.rb:168:in `primary_abstract_class': 

# The `primary_abstract_class` is already set to DifferentApp::ApplicationRecord(abstract). There can only be one `primary_abstract_class` in an application. (ArgumentError)
```
The first model called sets what the abstract class will be for the entire app and creates a conflict when a second model is called.

As a test, I tried making the `ApplicationRecord` class from the host app the class all engine models inherit from (which I'm not sure it's architecturally correct) and got the following error:

```ruby
DifferentApp::User.count
# => 0

ExampleApp::User.count
# => .asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-7.0.0.alpha2/lib/active_record/connection_adapters/postgresql/database_statements.rb:19:in `exec': ERROR:  

# relation "example_app_application_records" does not exist (PG::UndefinedTable)
```

The only way I got it to work was by changing all `primary_abstract_class` method calls in the 3 `ApplicationRecord` files to `self.abstract_class = true` which seems to be the previous behaviour. 

---

The documentation on the edge guides site encourages user to upgrade to using `primary_abstract_class` when using multiple databases but the generators have been updated for the method to be included by default in apps and engines/plugins which seems to be conflicting since there is supposed to be only 1 `primary_abstract_class` per database from my understanding. 

I'm not sure if there is an actual bug but if it's not it's a bit hard to understand what the rules are for this new method in the context of engines.

Thanks!

### System configuration
**Rails version**:
7.0.0.alpha2
**Ruby version**:
3.0.1

### PR DESCRIPTION
**Pull request by eileencodes**
With engines this would result in an error because there can only be one
`primary_abstract_class`. This is the class that your app connects to on
boot when it's connecting lazily and you're using multiple databases.
This change just removes `primary_abstract_class` from the engine
`ApplicationRecord` classes and keeps them as `self.abstract_class =
true`.

Fixes https://github.com/rails/rails/issues/43247

### CODE REVIEW

**Comment by pinzonjulian** [comment]
Thanks for tackling this @eileencodes !

**Comment by jamesw** [comment]
This is not fixed for me, is there a work around?

**Comment by jamesw** [comment]
Looking at the details the merged commit failed

**Comment by eileencodes** [comment]
The merge did not fail, but this change is only in `main` and not in any release yet. It will be in the next release of the 7 beta.

**Pull request merged**
