### PR TITLE
[ci skip] use ApplicationRecord as parent class on guides

### PR DESCRIPTION
**Pull request by edudepetris**
### Summary

Change ActiveRecord::Base by ApplicationRecord

### CODE REVIEW

**Comment by kaspth** [comment]
Intentional. Base is still valid to inherit from.

**Comment by andyatkinson** [comment]
@kaspth I know this is a minor nit, and I understand it's valid code, but wouldn't it be worth moving docs to match what's generated when running `rails g model Foo` (`class Foo < ApplicationRecord`)?

**Comment by kaspth** [comment]
Don't think so, no. We can still have these separate superclasses. I'm a little curt because we've rejected this before, so there may be other more elaborate explanations in the issues tracker.

**Comment by andyatkinson** [comment]
Thanks for sharing your perspective/prior art @kaspth

**Pull request closed without merging**
