### PR TITLE
Fix longer sequence name detection for serial columns

### LINKED ISSUE #28332: Long model names break db:schema:load on Postgres
### Steps to reproduce
1. `$ rails new issue_reproduction --database=postgresql`
1. `$ rails g scaffold MyVeryLongExampleModelNameBecauseIThinkSchemaLoadBreaksSometimes title:string body:text`
1. `$ rails db:create db:migrate`
1. `$ rails db:drop db:create db:schema:load`

Example repo: https://github.com/skiningham/issue_reproduction
Single-file reproduction: https://gist.github.com/skiningham/fb6f380c75ca5a6c65909958f5f52a31

### Expected behavior
`$ rails db:schema:load` should succeed without errors.

### Actual behavior
The command fails with:
```
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "my_very_long_example_model_name_because_i_think_schema_l_id_seq" does not exist
: CREATE TABLE "my_very_long_example_model_name_because_i_think_schema_load_bre" ("id" bigint DEFAULT nextval('my_very_long_example_model_name_because_i_think_schema_l_id_seq'::regclass) NOT NULL PRIMARY KEY, "title" character varying, "body" text, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL)
```

### System configuration
**Rails version**: 5.0.2, 5.1.0.beta1

**Ruby version**: 2.2.3p173

**Postgres version**: 9.5.4

### Additional information
I can reproduce this error with ActiveRecord 5.0.2 and 5.1.0.beta1. I did not try against master. I cannot reproduce this error against ActiveRecord 4.2.8. Apologies for the rough single-file reproduction; this error does not occur against SQLite so I made an attempt at adjusting the default template for Postgres. `$ rails db:structure:load` succeeds in the example application when a `structure.sql` is dumped. `$ rails db:drop db:create db:migrate` succeeds in the example application.

### PR DESCRIPTION
**Pull request by kamipo**
Fixes #28332.

### CODE REVIEW

**Comment by pixeltrix** [comment]
Would it not be better to use `pg_depend` to find the sequence identifier that is attached to the primary key? That's seems to be what Django has done in this [ticket][1].

[1]: https://code.djangoproject.com/ticket/27090#comment:14

**Comment by kamipo** [comment]
In my understanding, the issue is whether to consider the sequence name as made by serial type.

```ruby
create_table "my_very_long_example_model_name_because_i_think_schema_load_bre", id: :integer, default: -> { "nextval('my_very_long_example_model_name_because_i_think_schema_l_id_seq'::regclass)" }, force: :cascade do |t|
```

We already found the sequence name `my_very_long_example_model_name_because_i_think_schema_l_id_seq`.
But we could not consider the sequence name as made by serial type due to missed max identifier length limitation.

I addressed the sequence name consideration to respect the max identifier length.

**Comment by pixeltrix** [comment]
@matthewd you were the one who suggested using `pg_depend` - wdyt? Is this sufficient?

**Comment by matthewd** [comment]
I'm not excited about us reproducing more of PG's sequence-name-building logic.

If it's practical to get the information where we need it, I do think I'd prefer to use pg_depend. If that proves troublesome, though, this seems a perfectly fair improvement on our current approach.

**Comment by kamipo** [comment]
I'm going to merge this since #28332 is a regression since Rails 5.0.
If we want to regard the dependent sequence object as a serial regardless of whether a serial like name or not, we can change the implementation in a future version of Rails.

**Pull request merged**
