### PR TITLE
typo fix [ci skip]

### PR DESCRIPTION
**Pull request by manish-shrivastava**
Removed `'` which was placed at wrong place.

### CODE REVIEW

**Comment by manish-shrivastava** [comment]
@jonatack Please review once -  `sub-projects' codebases` seems not correct. as `'` is after sub-projects

**Comment by manish-shrivastava** [comment]
I think, it should be either  `sub-project's codebases` or `subprojects codebases`.

**Comment by manish-shrivastava** [comment]
I am sorry. I was not aware of after word apostrophe use. This PR should be discarded.

**Comment by seuros** [comment]
Thank you for your contribution.

**Pull request closed without merging**
