### PR TITLE
Update: Action Mailbox documentation with example [ci skip]

### PR DESCRIPTION
**Pull request by benkoshy**
### Why this PR?

* If you want to test for attachments: how is this done? Documentation seems a little sparse on this question. This PR obviates the need to look further. 
* It also highlights an important use case: you can customise the mail object directly.

### CODE REVIEW

**Comment by benkoshy** [comment]
hi @eugeneius - wondering if this is worth a look or can safely be closed?

chrs

Ben

**Comment by benkoshy** [comment]
@kamipo hi was hoping you could review this PR? It is a pure documentation change (does not touch the code base) - so the risk is very low.

appreciate the work everyone has been putting into rails.

Chrs.
Ben

**Comment by georgeclaghorn** [comment]
A high-level guide like this one needn’t cover every use case exhaustively. We can link to the [`ActionMailbox::TestHelper`](https://api.rubyonrails.org/classes/ActionMailbox/TestHelper.html) API docs, which cover building a `Mail::Message` object (via `{create,receive}_inbound_email_from_mail` with a block).

**Comment by benkoshy** [comment]
@georgeclaghorn chrs for reviewing, will post a patch with the link.

**Comment by benkoshy** [comment]
Chrs @georgeclaghorn - I've created a new PR following your advice above: #41791. 

I hope it is useful -- if not feel free to close, or let me know what amendments are required. 

I appreciate all your work - thank you for your contributions to open source.

**Pull request closed without merging**
