### PR TITLE
Eager load all models in test case

### PR DESCRIPTION
**Pull request by kuldeepaggarwal**
This will alert user to detect any issues in production environemnt, like in #14603

### CODE REVIEW

**Comment by kuboon** [comment]
@kuldeepaggarwal I think this change slows down partial test.

**Comment by kuboon** [comment]
Is there a way to determine which is running full test or partial?

**Comment by rafaelfranca** [comment]
Indeed. I believe that is not a good idea to have this as default. You can always change the configuration of you think it is needed. Thank you for the pull request

**Comment by kuboon** [comment]
@rafaelfranca do you remember this your comment? https://github.com/rails/rails/issues/14603#issuecomment-52733909

**Comment by rafaelfranca** [comment]
Yes, I do.

**Comment by kuldeepaggarwal** [comment]
I respect for the judgement of Rails core team member to close this issue, but please clarify that can we sacrifice the correctness of test cases against speed? AFAIK, test cases are there to ensure that code will work in production env but if, both the environments will behave differently then it is very difficult to rely on test cases as well.

**Comment by rafaelfranca** [comment]
> but please clarify that can we sacrifice the correctness of test cases against speed?

Yes, we can, this is what you do when you mock things in your test suite.

This option is a configuration and everyone that want correctness of test can change it. You can even have different values depending if you are running the test locally or in the CI environment.

**Pull request closed without merging**
