### PR TITLE
Removed Active Support deprecations

### PR DESCRIPTION
**Pull request by ricardotk002**
### Summary

Hey, in this PR I removed most of the deprecations announced for Rails 5.1. I left a couple more because I need more context to remove/clean up the code, specially for the ActiveSupport `halt_callback_chains_on_return_false` config.

### CODE REVIEW

**Comment by ricardotk002** [comment]
Looks like there's an odd fail, I've re-run the failing specs on my end and everything went fine.

**Comment by rafaelfranca** [comment]
Thank you for the pull request but we don't accept pull request with deprecations removal.

**Comment by ricardotk002** [comment]
@rafaelfranca Sorry, I didn't know that. I'm wondering the reasons behind this, maybe it should appear somewhere in the contribution guide.

**Comment by rafaelfranca** [comment]
The release managers is the only people that have the context behind the deprecation so they are the best people to remove the deprecations and cleanup the code.

**Pull request closed without merging**
