### PR TITLE
Add link to API documentation

### PR DESCRIPTION
**Pull request by tjai89**
Add a link to [API ActionController docs](http://api.rubyonrails.org/classes/ActionController.html) in the beginning of an article.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Please add ci skip to the commit message

**Comment by utilum** [comment]
Speaking of links from guides to the API documentation, several guides have none. Would it be worth its own issue?

**Comment by tjai89** [comment]
Done

**Comment by tjai89** [comment]
I believe it makes sense to add links at the beginning of every article on its related api docs.

**Pull request merged**
