### PR TITLE
attributes should be an Hash at least in AttributeSet

### PR DESCRIPTION
**Pull request by acapilleri**

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Could you explain why this change is needed?

**Comment by acapilleri** [comment]
Because  the methods that access to the ```attributes``` make an assumption that ```@attributes``` is an Hash without check it.
ex:
``` 
a = AttributeSet.new(nil)
a.key?('name') => raise exception
```

**Comment by rafaelfranca** [comment]
But where are we passing something that is not a hash? Also you patch do not fix the case you presented.

As you can see this class is internal of the framework and we are always passing the right object to it, so there is no need to make the argument optional.

**Comment by rafaelfranca** [comment]
Thank you for the pull request.

**Comment by acapilleri** [comment]
Why my patch does not fix the case presented?
I'm not agree with ```we are always passing the right object to it```because you cannot be sure that in the future it will not used by other methods.
I can agree that is not a important patch, but noticed this code during a code review.
Thanks to you.

**Comment by rafaelfranca** [comment]
> Why my patch does not fix the case presented?

Because:

```
a = AttributeSet.new(nil)
a.key?('name') => raises exception
```

Will still behave in the same way.

> because you cannot be sure that in the future it will not used by other methods.

If we can't assure that the framework will call its own objects correctly it is hard to see how it works.

**Pull request closed without merging**
