### PR TITLE
Backport #24616 to 4-2-stable

### PR DESCRIPTION
**Pull request by niconegoto**
This PR backports PR #24616 to the 4-2-stable branch.

### CODE REVIEW

**Comment by eugeneius** [comment]
There was a followup fix that would need to be incorporated here too: https://github.com/rails/rails/commit/1f190c4873963598eea306a99b56c4a24cb817d0

**Comment by niconegoto** [comment]
@eugeneius thank you for your pointing out 👍

**Comment by rafaelfranca** [comment]
Thank you for the pull request but we are already working on this here https://github.com/rails/rails/pull/27473

**Comment by matthewd** [comment]
@niconegoto sorry I didn't deal with this earlier when you opened it. :pensive:

As @rafaelfranca noted, I've already folded #24616 into #27473, so this will be addressed when that is merged.

**Comment by niconegoto** [comment]
@rafaelfranca @matthewd Thank you for the merge !! 😄

**Pull request closed without merging**
