### PR TITLE
Adjusted README.md paragraph structure.

### PR DESCRIPTION
**Pull request by Baron-burton**
I adjusted the opening paragraphs just so that they look a little neater from a structure point of view. I did this for the "Model layer", "Control layer", "View layer" paragraphs as well as the paragraph describing the "Active" libraries that come with Rails.

### CODE REVIEW

**Comment by matthewd** [comment]
You've just removed the text wrapping, right?

No thanks.

**Comment by Baron-burton** [comment]
I apologize, I think it just looked weird on my end. I got a little too eager in seeing something I thought needed fixing when it didn't.

**Comment by rafaelfranca** [comment]
@Baron-burton don't worry. Keep searching for something! I'm sure you will find. Take a look in our issue tracker you may find something easy too.

**Comment by Baron-burton** [comment]
Thanks, I appreciate that. I'll definitely search through it!

**Pull request closed without merging**
