### PR TITLE
Grammar correction

### PR DESCRIPTION
**Pull request by hemalijain**

### CODE REVIEW

**Comment by ronakjangir47** [comment]
Please remember to add [ci skip] to the commit message for further documentation patches. This will prevent Travis from running.

**Comment by hemalijain** [comment]
Sure. Thank You :+1:

**Comment by kaspth** [comment]
Thanks!

**Comment by hemalijain** [comment]
@matthewd  , Can you please let me the reason for reverting my commit change. Thank you in advance :-)

**Comment by jonatack** [comment]
The PR changed the text from correct to incorrect English.

**Pull request merged**
