### PR TITLE
Add each schema parameter as its own argument.

### PR DESCRIPTION
**Pull request by ckoenig**
At least on my machine the existing code fails, if there is more than
one schema in the search path, with the following error message:

```
pg_dump: No matching schemas were found
```

Passing each schema parameter as its own argument fixes the problem.

### CODE REVIEW

**Comment by senny** [comment]
@ckoenig can you add a test-case to prevent against regressions?

**Comment by ckoenig** [comment]
@senny I added a test-case. I hope it's fine like that.

**Comment by senny** [comment]
@ckoenig I just noticed your PR is targeting `4-2-stable`. We merge changes against `master` and then backport the merge commit to release branches. Would you mind opening a new PR against `master`. At the same time, could you squash your commits together into a single one? this way we can keep the git history less noisy. Thank you :yellow_heart:

**Comment by ckoenig** [comment]
#22345 should be the same fix against master AFAIS.

**Comment by senny** [comment]
@ckoenig thanks, for the xref!

**Comment by senny** [comment]
@ckoenig #22345 is merged and backported to `4-2-stable`. Thanks for your work :yellow_heart:

**Pull request closed without merging**
