### PR TITLE
Add support to use bun on rails new command

### PR DESCRIPTION
**Pull request by lairtonmendes**
### Motivation / Background

This Pull Request has been created because was add bun support on jsbundling-rails.

### Detail

This Pull Request  update the `rails new` command  to be possible use the option bun on javascript params.

### Additional information

This depends on a new release of jsbundling-rails, but according to this [comment](https://github.com/rails/rails/pull/49229#issuecomment-1714742170), if I didn't understand it wrong, maybe there's no problem with this being merge before.

### CODE REVIEW

**Comment by duduribeiro** [comment]
nice @lairtonmendes 💯 

Can you add your changes on `railties/CHANGELOG.md` as well?

**Review by brunoprietog — COMMENTED** [review]
We could add more details to the working with javascript guide. We also need to make the Dockerfile compatible with Bun. We must also handle this case in action cable and action text installers. I was working on that in the morning but I can continue in the evening

**Comment by duduribeiro** [comment]
FYI. The changes applied here is also covered at this PR https://github.com/rails/rails/pull/49241/files from @terracatta 
maybe we can close this in favor of https://github.com/rails/rails/pull/49241/files? 

wdyt?

**Comment by lairtonmendes** [comment]
> FYI. The changes applied here is also covered at this PR https://github.com/rails/rails/pull/49241/files from @terracatta maybe we can close this in favor of #49241 ?
> 
> wdyt?

Yes I will close this

**Pull request closed without merging**
