### PR TITLE
[ci skip] Add style guide about comma

### PR DESCRIPTION
**Pull request by yui-knk**
We discussed about comma style [here](https://github.com/rails/docrails/commit/9876a16904f817e11713bc85479dd70da1de454b).

Ping @fxn :)

### CODE REVIEW

**Comment by yui-knk** [comment]
@schneems  oh! thanks :)

**Comment by schneems** [comment]
Reasons I like this change: explicit is better than implicit, least chance for ambiguity in docs, and I really wanted to use an Oxford comma in this comment. Thanks :heart:

**Comment by yui-knk** [comment]
I wonder so many people and rails developers prefer Oxford comma :smiling_imp: 
I agree explicit is better than implicit :+1:

**Comment by yui-knk** [comment]
:smile: :smile: :smile:

**Comment by fxn** [comment]
Is the grammar correct? I would say "use *the* Oxford comma, or "use Oxford *commas*", but I am not native. What do you think @schneems?

**Comment by schneems** [comment]
You're right should be `"Please use the Oxford comma"` to be sure I googled the phrase, it has 4k results, "please use oxford comma" has 4. Sorry I missed that, I silently added the word in my head while reading through the first time.

**Pull request merged**
