### PR TITLE
ADD: new method for logging response status code and response content length

### PR DESCRIPTION
**Pull request by grzegorzblaszczyk**
## Summary

If log_start_response_message is set to true in application config,
Rails logs also:
Started response HTTP 200 (12345 bytes) for [request details]
### Other Information

This is useful when you need to measure not only internal processing time in Rails
within action_dispatch (like rendering views time, ActiveRecord time,
Elasticsearch time etc.) but also from "Started GET / for 127.0.0.1 at ..." until
very end just before sending response back to the client.

In normal circumstances this time spent from "Started GET / 127.0.0.1 at ..." to
actual processing the request by Rails is almost nothing, but when the system is
upon heavy load, this time can become significant part of processing the request
from the client's perspective (Rails processing is fast but waiting to get into
action_dispatch may take some time).

By logging also "Started response HTTP 200 (1234 bytes) for ..." you can easily
analyze whether internal Rails processing is the bottleneck or your setup with
phusion-passenger/unicorn or nginx/Apache HTTPd is not optimal.

There is no calculating (end_time - start_time) because it might affect system
performance, but a simple log line with a timestamp when the response has
actually started to being sent is enough for performance analysis.

Additionally, we can detect pretty fast Content-Length header value of any
response.

### CODE REVIEW

**Comment by arthurnn** [comment]
I am not sure I like a new config for this. I would only add configurations for things we cannot accomplish otherwise, and this logging probably can be done via a new Middleware or something like that.

**Comment by grzegorzblaszczyk** [comment]
@arthurnn Can you guide me with any link, so I can provide this as a proper Middleware implementation?

**Comment by arthurnn** [comment]
@grzegorzblaszczyk what I meant was that you can implement a Middleware in your application to log those things, and that does not need to be part of Rails itself.

**Comment by kaspth** [comment]
Crap, I forgot all about this! I concur with @arthurnn that this would be better off in a middleware in your app. Thanks for the pull request! ❤️

**Pull request closed without merging**
