### PR TITLE
unify puma types and remove blocks

### PR DESCRIPTION
**Pull request by grosser**
- remove 4 unnecessary blocks (ints/strings are cheaper to create and handle)
 - remove 3 places that could include a bug because they are string or int, so they will be int locally and then string in production
 - validate that value given via ENV is a number

### CODE REVIEW

**Comment by matthewd** [comment]
Hmm... I think the blocks better offset the parts users may want to edit.

Considering this gets evaluated once at application boot, performance seems irrelevant.

.. and the type-checking feels like it'd be better placed upstream.

r? @schneems

**Comment by schneems** [comment]
Puma should convert or error in a non valid input. If it doesn't, we should add it in there.

I think the boot time savings is extremely negligible. That being said, if we are doing any fetch calls with blocks at runtime they should probably be converted as long as the default value isn't expensive to compute.

**Comment by grosser** [comment]
The time/error savings here are negligible either way, but I think this is showing users the 'right' pattern ... "do not use blocks when a simple value is needed" and "validate your inputs", so I think it's better than before ... if someone made the opposite PR to add blocks where we had a simple value would you accept that ?

**Comment by grosser** [comment]
@rafaelfranca thx for digging up these old PRs, I bet there are a ton :D 💖

**Pull request merged**
