### PR TITLE
doc: corrected spelling mistake - round tripping

### PR DESCRIPTION
**Pull request by manish-shrivastava**
doc: small correction roundtripping to round tripping

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Could you squash your commits?

**Comment by manish-shrivastava** [comment]
yes, I was about to do that.

**Comment by jonatack** [comment]
round-tripping might be better than round tripping.

**Comment by jonatack** [comment]
@manish-shrivastava don't close and open a new PR, you can squash your commits here. See this from yesterday: #20392

**Pull request closed without merging**
