### PR TITLE
Add poppler to Dev Dependency guide [ci skip]

### PR DESCRIPTION
**Pull request by skipkayhil**
### Summary

Package listings:

debian/apt - https://packages.ubuntu.com/jammy/poppler-utils
fedora     - https://packages.fedoraproject.org/pkgs/poppler/poppler-utils/
arch linux - https://archlinux.org/packages/extra/x86_64/poppler/
freebsd    - https://www.freshports.org/graphics/poppler-utils

Also updated the Active Storage dependency list because Poppler is
required on any platform to run tests.

### Other Information

Follow up to #44992

Similar to last time, I was able to test installing all of these except FreeBSD, and would definitely appreciate someone correcting me if I got that one wrong.

### CODE REVIEW

**Comment by yahonda** [comment]
I usually do not use FreeBSD so tested it by installing FreeBSD 13.1 using Vagrant as follows.

```
% vagrant init freebsd/FreeBSD-13.1-STABLE
% vagrant ssh
vagrant@freebsd:~ % uname -a
FreeBSD freebsd 13.1-STABLE FreeBSD 13.1-STABLE #0 stable/13-n250927-e5b204542f3: Fri May 27 02:19:17 UTC 2022     root@releng3.nyi.freebsd.org:/usr/obj/usr/src/amd64.amd64/sys/GENERIC amd64
```

Here are findings.

1. pkg requires sudo
```
vagrant@freebsd:~/rails % pkg install sqlite3 mysql80-client mysql80-server postgresql11-client postgresql11-server memcached imagemagick ffmpeg mupdf yarn libxml2 vips poppler-utils
pkg: Insufficient privileges to install packages
```

2. Unable to install `imagemagick` out of the box
```
% sudo pkg install sqlite3 mysql80-client mysql80-server postgresql11-client postgresql11-server memcached imagemagick ffmpeg mupdf yarn libxml2 vips poppler-utils
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
pkg: No packages available to install matching 'imagemagick' have been found in the repositories
```

3. poppler-utils 22.05.0 has been installed by removing `imagemagick` from the list
```
% sudo pkg install sqlite3 mysql80-client mysql80-server postgresql11-client postgresql11-server memcached ffmpeg mupdf yarn libxml2 vips poppler-utils
Updating FreeBSD repository catalogue...
... snip ...
	poppler-utils: 22.05.0
```

Here are the entire output.
https://gist.github.com/yahonda/9e2e003378143b836111dc12fad5740d

**Comment by yahonda** [comment]
Would you add ` sudo` for `pkg install` on FreeBSD?

**Comment by yahonda** [comment]
I've found `imagemagick6` works. It looks like there are `imagemagick6` and `imagemagick7`. Compared ImageMagick-related packages on my Ubuntu 22.04 and Red Hat Enterprise Linux 9, Both have version 6 installed.

The bottom line is:

```
sudo pkg install sqlite3 mysql80-client mysql80-server postgresql11-client postgresql11-server memcached imagemagick6 ffmpeg mupdf yarn libxml2 vips poppler-utils
```

The entire output is https://gist.github.com/yahonda/9e2e003378143b836111dc12fad5740d?permalink_comment_id=4186881#gistcomment-4186881

**Comment by skipkayhil** [comment]
Updated, thank you for the review and the tip on running FreeBSD!

**Pull request merged**
