### PR TITLE
Fix after_commit on: :create being fired twice if save is called within

### PR DESCRIPTION
**Pull request by Geesu**
Fixes https://github.com/rails/rails/issues/31104

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Tests are broken

**Comment by badosu** [comment]
@Geesu Let me know if you intend to address this PR, otherwise I can cherry-pick your commits and make the necessary adjustments if you don't mind.

**Comment by Geesu** [comment]
Feel free to cherry pick - I may not be able to get to it anytime soon.

**Comment by badosu** [comment]
Thanks for the quick feedback!

**Comment by badosu** [comment]
@kamipo At #32303 I fixed an edge case that would impat other places, there even an added test. If things are workig now thank you anyway,

**Pull request closed without merging**
