### PR TITLE
Defer route drawing to the first request, or when url_helpers called.

### LINKED ISSUE #51906: Deferred route drawing causes problems with some tests
This issue is related to https://github.com/rails/rails/pull/51614

### Steps to reproduce
I haven't been able to write a minimal reproduction script. In our case, the issue we had was that a test for a helper that used some URL helpers and these are undefined after #51614. This is how the test looks like: 

```ruby
require "test_helper"

class AttachmentsBrowserHelperTest < ActionView::TestCase
  test "attachments_browser_backlink with a context" do
    assert_match /Back to Sent Mail/, attachments_browser_backlink(context: topics_sent_path)
  end
```

Looks like #51614 caused some issues with `rspec-rails` as well, according to [this comment](https://github.com/rails/rails/pull/51614#issuecomment-2123136767) and https://github.com/rspec/rspec-rails/issues/2761. 

### Expected behavior
The test passes normally. 

### Actual behavior
It fails with 
```
NameError: undefined local variable or method `topics_sent_path' for an instance of AttachmentsBrowserHelperTest
    test/helpers/attachments_browser_helper_test.rb:17:in `block in <class:AttachmentsBrowserHelperTest>'
```

To work around this, I've used the following: 
```ruby
 setup do
    routes_reloader = Rails.application.routes_reloader
    routes_reloader.execute_unless_loaded if routes_reloader&.respond_to?(:execute_unless_loaded)
  end
```

### System configuration
**Rails version**: Edge (targeting main branch)

**Ruby version**: 3.3.0

### PR DESCRIPTION
**Pull request by gmcgibbon**
Retry of https://github.com/rails/rails/pull/51614

Closes https://github.com/rails/rails/issues/51906

### Motivation / Background

This Pull Request has been created because apps with lots of routes take a long time to boot. A developer could boot an app for reasons that don't involve routes at all (like running unit tests, migrations, rake tasks, etc.) so I think this should be deferred in dev and test.

### Detail

This Pull Request changes engine and app route sets to a `Rails::Engine::RouteSet`, which knows about the current Rails application. The default middleware stack has also changed to include a `Rails::Rack::LoadRoutes` middleware that loads routes if needed. This PR loads routes under the following circumstances:

In dev/test:
- The first request via middleware
- When application or engine `url_helpers.some_path` is called via `method_missing?`
- When application or engine `url_helpers.respond_to?(:some_path)` is called via `respond_to_missing?`

In production:
- In the finisher eagerly, which is the previous behaviour

If, for some reason, a developer wishes to revert to the previous behaviour, they could add an initializer with `Rails.application.reload_routes!`. However, if we wanted to be more safe, we could also hide this behaviour behind a configuration variable.

### Additional information

This is loosely inspired by https://github.com/amatsuda/routes_lazy_routes

I'm a bit concerned this is too much of a hack, but I think the speed benefit might be worth it. In an app with 2000 routes:

Before:
```
% time bin/rails runner ""
bin/rails runner ""  0.66s user 0.33s system 95% cpu 1.036 total
```

After:
```
% time bin/rails runner ""
bin/rails runner ""  0.47s user 0.32s system 98% cpu 0.791 total
```

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by gmcgibbon** [comment]
The main difference with this PR compared to the last is the implementation of `route_defined?` which will load routes when we ask the route set if a route is defined. This is because the Action View test case uses this API here: https://github.com/rails/rails/blob/3769f1eee6a1ec4f6438155d67477db6d192577f/actionview/lib/action_view/test_case.rb#L426

**Comment by gmcgibbon** [comment]
Another change: To fix the controller tests / rspec-rails bug, I needed to load routes when `generate_extras` was called on the route set. This makes sense because controller tests need to ask the app route set if it has a route for the controller you are making a request for.

**Comment by jeremy** [comment]
Hit issues with this in production. Haven't dug in deeply yet, but I'm seeing that routes are not loaded when executing a job despite eager loading being enabled:

```
<head></head>
NoMethodError: undefined method `blob_url' for an instance of #<Class:0x00007f75911100b8>

/usr/local/bundle/ruby/3.3.0/bundler/gems/rails-16d8b82d5e2a/railties/lib/rails/engine/route_set.rb:39:in `method_missing'
/usr/local/bundle/ruby/3.3.0/bundler/gems/rails-16d8b82d5e2a/railties/lib/rails/engine/route_set.rb:37:in `public_send'
/usr/local/bundle/ruby/3.3.0/bundler/gems/rails-16d8b82d5e2a/railties/lib/rails/engine/route_set.rb:37:in `method_missing'
/usr/local/bundle/ruby/3.3.0/bundler/gems/rails-16d8b82d5e2a/actionpack/lib/action_dispatch/routing/polymorphic_routes.rb:242:in `public_send'
/usr/local/bundle/ruby/3.3.0/bundler/gems/rails-16d8b82d5e2a/actionpack/lib/action_dispatch/routing/polymorphic_routes.rb:242:in `polymorphic_method'
/usr/local/bundle/ruby/3.3.0/bundler/gems/rails-16d8b82d5e2a/actionpack/lib/action_dispatch/routing/polymorphic_routes.rb:125:in `polymorphic_url'
/usr/local/bundle/ruby/3.3.0/bundler/gems/rails-16d8b82d5e2a/actionpack/lib/action_dispatch/routing/route_set.rb:571:in `polymorphic_url'
/rails/config/initializers/active_storage.rb:38:in `to_rich_text_attributes'
/usr/local/bundle/ruby/3.3.0/bundler/gems/actiontext-cfd786e91771/lib/action_text/attachment.rb:27:in `from_attachable'
…
```

**Comment by jeremy** [comment]
Can trigger directly in dev. Polymorphic mapping lookup would also need to trigger lazy loading.
```ruby
Loading development environment (Rails 8.0.0.alpha)
>> b = ActiveStorage::Blob.take
  ActiveStorage::Blob Load (1.1ms)  SELECT `active_storage_blobs`.* FROM `active_storage_blobs` LIMIT 1
=> 
#<ActiveStorage::Blob:0x0000000121d9ba08
...
>> Rails.application.routes.url_helpers.polymorphic_url(b, only_path: true)
 
(haystack):2:in `<main>': undefined method `blob_url' for an instance of #<Class:0x000000012105da30> (NoMethodError)
Did you mean?  box_url
```

**Comment by gmcgibbon** [comment]
Thanks @jeremy, I'll work on patching this right away!

**Comment by jeremy** [comment]
Thanks @gmcgibbon. Reverting for now.

I'd also be helpful to see the lazy routeset completely omitted when eager loading is enabled, e.g.
```diff
diff --git a/railties/lib/rails/engine.rb b/railties/lib/rails/engine.rb
index 3d17061646..42e2d087f2 100644
--- a/railties/lib/rails/engine.rb
+++ b/railties/lib/rails/engine.rb
@@ -544,11 +544,16 @@ def env_config
     # Defines the routes for this engine. If a block is given to
     # routes, it is appended to the engine.
     def routes(&block)
-      @routes ||= RouteSet.new_with_config(config)
+      @routes ||= new_route_set
       @routes.append(&block) if block_given?
       @routes
     end
 
+    def new_route_set
+      klass = config.eager_load ? ActionDispatch::Routing::RouteSet : RouteSet
+      klass.new_with_config(config)
+    end
+
     # Define the configuration object for the engine.
     def config
       @config ||= Engine::Configuration.new(self.class.find_root(self.class.called_from))
```

And give the lazy routeset a clarifying name like LazyLoadingRouteSet so we have more than the module namespace to indicate expected role & behavior.

**Pull request merged**
