### PR TITLE
`pluck` should use `records` (`load_target`) when `loaded?` is true

### PR DESCRIPTION
**Pull request by kamipo**

### CODE REVIEW

**Comment by matthewd** [comment]
We seem to be adding far too many methods to collection proxy... I get the feeling we're patch-fixing individual issues without understanding the root cause of a problem.

https://github.com/rails/rails/pull/25877 is a mass effort in the same direction, but also doesn't feel quite right. :confused:

**Comment by kamipo** [comment]
If we want to avoid queries when loaded target, we should not delegate to `scope`. And basically `FinderMethods` and `Calculations` works without delegating to `scope` because `CollectionProxy` inherits `Relation`. But some test cases expects no queries for null relation. 

https://github.com/rails/rails/blob/v5.0.0/activerecord/lib/active_record/null_relation.rb

But `CollectionProxy` cannot extend `NullRelation` thus should delegate to `scope` when an association is a null scope.

**Comment by matthewd** [comment]
> If we want to avoid queries when loaded target, we should not delegate to `scope`

Couldn't we fix that by (for example) populating `scope` with the loaded target?

**Comment by kamipo** [comment]
It is difficult for now. `scope` is made to the new to each call.

**Comment by kamipo** [comment]
How about it?

```diff
--- a/activerecord/lib/active_record/associations/collection_proxy.rb
+++ b/activerecord/lib/active_record/associations/collection_proxy.rb
@@ -911,7 +911,9 @@ def scoping
 
       # Returns a <tt>Relation</tt> object for the records in this association
       def scope
-        @association.scope
+        scope = @association.scope
+        scope.load_records(records) if loaded?
+        scope
       end
       alias spawn scope
```

**Comment by rafaelfranca** [comment]
I'll merge this since it fixes a bug but I agree with @matthewd. @kamipo could you investigate a way to fix those issues without reimplementing many methods?

**Comment by rafaelfranca** [comment]
Backported in 5bbcdf1

**Comment by dsander** [comment]
I noticed that `pluck` now returns data from new records if the association is loaded:
```
associations = current_user.associations.load;
new = associations.build
ids = current_user.associations.pluck(:id)
ids
=> [...., nil]
```

Is that a regression or intended behavior?

**Pull request merged**
