### PR TITLE
 Fix typo in Creating and Customizing Rails Generators & Templates guide...

### PR DESCRIPTION
**Pull request by yatmsu**
Fix typo in Creating and Customizing Rails Generators & Templates guides

### CODE REVIEW

**Comment by seuros** [comment]
Thank you. Please add [ci skip] to the commit message for no code change

**Comment by vipulnsward** [comment]
@yatmsu @seuros This is wrong. See sentence above why this has an extra %

**Comment by seuros** [comment]
my bad, i will revert.

**Comment by vipulnsward** [comment]
:+1:

**Comment by yatmsu** [comment]
Sorry,I made a mistake.

**Pull request merged**
