### PR TITLE
Change the location of a compiled rails-ujs.js

### PR DESCRIPTION
**Pull request by knu**
Tools like [yarn autoclean](https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/autoclean.js#L28) and [node-prune](https://github.com/tj/node-prune/blob/master/prune.go#L101) list `assets` as a directory to prune, and just because `rails-ujs.js` is placed under `lib/assets/compiled` it is deleted by them.

In my case, rails-ujs was the only package out of more than 1300 packages that got dysfunctional after running `node-prune` (or `yarn autoclean --init && yarn install`).

A warning is added to the README document by [#31881](https://github.com/rails/rails/pull/31881), but it is easily missed.  If there is no strong reason to use the subdirectory name `assets`, the path name should be changed so that no user attention or action is required.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
There is a string reason to put in a subdirectory. `lib/assets` is included in the assets pipeline while `lib/compiled/` is not. Thank you for the pull request.

**Comment by knu** [comment]
OK.  Would it be possible to change the subdirectory name in a node package while keeping the location when compiling via assets pipeline?  Would that be too tricky?

**Comment by rafaelfranca** [comment]
I think that is worth doing. Do you want to update this PR to do that?

**Comment by knu** [comment]
I'm a little short of time.  I'll refile a decent PR when I get to address this.

**Pull request closed without merging**
