### PR TITLE
Remove unused require and unused model stub

### PR DESCRIPTION
**Pull request by maclover7**

### CODE REVIEW

**Comment by jeremy** [comment]
@maclover7 When did these stop being used? Nice to have a ref back to the commit that should have removed them.

**Comment by maclover7** [comment]
@jeremy updated

**Comment by jeremy** [comment]
Looks like the string access require was _added_ in that commit. Guess it was masking another missing require?

**Comment by maclover7** [comment]
Yeah, based on looking at that commit, it's kind of hard to tell why the `require` was introduced -- it wasn't there before the change 😬

**Comment by maclover7** [comment]
^ Build failures are unrelated, master is currently failing 😬

**Comment by maclover7** [comment]
👍

**Pull request closed without merging**
