### PR TITLE
Fixed typos in rails guide

### PR DESCRIPTION
**Pull request by manish-shrivastava**
Fixed typos in rails guide also added div tag to kindle text.

### CODE REVIEW

**Comment by manish-shrivastava** [comment]
Please let me know if anything.

**Comment by manish-shrivastava** [comment]
@rafaelfranca , May I ask you why this commit is not showing (at Rails Contributors list)[http://contributors.rubyonrails.org/contributors/manish-shrivastava/commits]

**Comment by matthewd** [comment]
@manish-shrivastava it'll be because your git author name is different... though I'm not entirely sure why it's not just showing up as a separate contributor. @fxn?

**Comment by manish-shrivastava** [comment]
@matthewd  @fxn , I spend whole day to look into issues. and anyhow I learnt to submit a pull request to make my contribution count to 2. :( .

Please have a look.

**Comment by manish-shrivastava** [comment]
@matthewd , @fxn 
Regarding different author name : Please find my both commits as https://github.com/rails/rails/commit/8145880541abf5a2454a161a80927791dec99d0b (latest which is not reflecting) and https://github.com/rails/rails/commit/6252d0aece57fbdc4e424e348fb301a22b6262b3f (older-which is reflecting) at  [Rails Contributors list](http://contributors.rubyonrails.org/contributors/manish-shrivastava/commits).

Please have a look.

**Comment by fxn** [comment]
@manish-shrivastava hey, calm down please, you may have worked a whole day, I have personally worked months in that application and as you can see in the source code with a sincere aim at giving due credit no matter the circumstances.

So, I'll have a look, but remember that is volunteer time and I do not own you anything. So please relax.

**Comment by ror-infobeans** [comment]
@fxn Thanks for reply. I am Okay.

I agree it is a volunteer work. But still, I wish is to reach at-least half or yours someday :) .

Actually, you can say I have just initiated. **Count on contributors list encourage me to do more**. But if I say count of my contribution will be 1 forever. I don't think, it is a good reflection for me or anybody.

**Comment by manish-shrivastava** [comment]
@fxn Thanks for reply. I am Okay.

I agree it is a volunteer work. But still, I wish is to reach at-least half or yours someday :) .

Actually, you can say I have just initiated. Count on contributors list encourage me to do more. But if I say count of my contribution will not increase. I don't think, it is a good reflection for me or anybody.

**Comment by matthewd** [comment]
@manish-shrivastava No, you're not okay. You're being rude, and far too panicked over an apparent software bug you reported a couple of hours ago. In a very low-priority piece of volunteer-maintained software.

These two things are not the same:
```
% git show 8145880 | grep Author:
Author: manish-shrivastava <er.manishshrivastava@gmail.com>
% git show 6252d0a | grep Author:
Author: Manish shrivastava <er.manishshrivastava@gmail.com>
```

If you can't (calmly, and patiently) wait until someone has a chance to investigate and fix the bug, feel free to [have at it](https://github.com/fxn/rails-contributors).

**Comment by fxn** [comment]
@manish-shrivastava you have to understand that the Rails Contributors website is there to give due credit and recognition. So it is something from Rails to the people as gratitude.

What motivates your contributions to open source is not something that list cares a lot.

The commits use different author names, so the easiest way to get your contributions there automatically is to avoid doing that.

We are going to revise this case when we can as a particular case of the general goal of that website, regardless of what motivates you personally. Hundreds of people contributed to Rails before this website ever existed.

**Comment by manish-shrivastava** [comment]
I beg pardon @fxn I . I understood the mistake. and I will keep in mind to keep Author same while any commit.
Thanks @matthewd for `git show id | grep Author:` output.

**Comment by fxn** [comment]
[In production](http://contributors.rubyonrails.org/contributors/manish-shrivastava/commits).

**Comment by manish-shrivastava** [comment]
Thanks a lot Xavier @fxn . I owe you for the [contributors site upgrades](http://contributors.rubyonrails.org/contributors/manish-shrivastava/commits). 
See you soon with better PR request. Thanks a lot again.

**Pull request merged**
