### PR TITLE
Use Rails.configuration instead of Rails.application.config in initializers

### PR DESCRIPTION
**Pull request by lukehorvat**
Given that there's no difference between `Rails.configuration` and `Rails.application.config`, surely it is better to use the one that is more concise and aesthetically pleasing?

### CODE REVIEW

**Comment by maclover7** [comment]
To me, this seems like a cosmetic change -- the current code appears to work fine :)

**Comment by rafaelfranca** [comment]
When the cosmetic change is in the generated code it is fine. I recall that sometimes `Rails.configuration` doesn't work so it is good to check if this code is fine before merging.

**Comment by prathamesh-sonpatki** [comment]
I created a new app based off this branch and `Rails.configuration` seems to be working. 

Also https://github.com/rails/rails/blob/a7d587f284b1360aec9c93695571520b6bdaac45/railties/lib/rails.rb#L44 just delegates to `Rails.application.config`.

**Comment by rafaelfranca** [comment]
Tests are broken. @lukehorvat could you take a look?

**Comment by matthewd** [comment]
Hmm... I prefer to configure via the application, because it makes it clearer what's going on, and keeps the path towards multiple apps more obviously open.

While this isn't an actual change in behaviour, to me, preferring it makes `Rails.configuration` feel like a separate global. :confused:

I guess I'm questioning whether it is concise, or merely compact.

**Comment by rafaelfranca** [comment]
That make sense. I always use the application too even though `Rails.configuration` exists and I prefer clear over compact code.

Thank you for the pull request.

**Pull request closed without merging**
