### PR TITLE
Move SourceAnnotationExtractor under Rails module

### PR DESCRIPTION
**Pull request by sikachu**
This is pretty much just a housekeeping PR.

I was browsing http://edgeapi.rubyonrails.org/ and notices that this class is listed on the left size with no namespace prefix. Given that this class belongs to Rails framework, and that it's already in `railties/lib/rails` hierarchy, I believe it's best to move this class down into `Rails` module.

In some sense, I believe that this could be considered a breaking change. However, given that user will access this class through rake task, I think this is fine to change.

Please let me know what you think.

### CODE REVIEW

**Comment by matthewd** [comment]
https://github.com/search?l=Ruby&q=SourceAnnotationExtractor+-filename%3Aannotations.rake&type=Code seems to show some usage, so I think it's worth a deprecation.

**Comment by sikachu** [comment]
@matthewd sounds good. So deprecate the constant in 6.0, then remove it in 6.1?

**Comment by matthewd** [comment]
Yup. Rename stays the same; we just add in a http://api.rubyonrails.org/classes/ActiveSupport/Deprecation/DeprecatedConstantProxy.html for the old name.

**Comment by sikachu** [comment]
@matthewd sorry for the delay — I just updated the PR with two things:

* I add deprecation notice for SourceAnnotationExtractor as you suggested.
* I also moved the Annotation sub-struct into a proper class so RDoc would properly render it in the documentation.

Please let me know if you have any feedback. Thanks!

**Comment by sikachu** [comment]
I added a commit to update bootsnap to the latest version to fix the issue with `Kernel.require` that caused a test failure. This is ready for another look.

**Comment by kaspth** [comment]
Thanks, @sikachu!

**Comment by eugeneius** [comment]
RSpec Rails is broken by this change because it [accesses `SourceAnnotationExtractor::Annotation` directly](https://github.com/rspec/rspec-rails/blob/v3.7.2/lib/rspec-rails.rb#L12), and `ActiveSupport::Deprecation::DeprecatedConstantProxy` can't handle nested constants:

```
TypeError: Rails::SourceAnnotationExtractor is not a class/module
/Users/eugene/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-rails-3.7.2/lib/rspec-rails.rb:12:in `<class:Railtie>'
/Users/eugene/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-rails-3.7.2/lib/rspec-rails.rb:8:in `<module:Rails>'
/Users/eugene/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-rails-3.7.2/lib/rspec-rails.rb:6:in `<module:RSpec>'
/Users/eugene/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rspec-rails-3.7.2/lib/rspec-rails.rb:4:in `<top (required)>'
```

Is there a way we can avoid breaking `SourceAnnotationExtractor::Annotation`, while still deprecating the top-level `SourceAnnotationExtractor` constant?

**Comment by sikachu** [comment]
😦 interesting. I'm sorry for breaking your code.

Let me try to find a way to work around that. I assume that this only happen when `rspec-rails` is built against Rails `master` right?

**Comment by matthewd** [comment]
http://api.rubyonrails.org/classes/ActiveSupport/Deprecation/DeprecatedConstantAccessor.html exists for that purpose, but I don't like the idea of using it at the top level :confused:

Maybe we can make DeprecatedConstantProxy inherit from Module, and then define both `method_missing` and `const_missing`?

**Comment by eugeneius** [comment]
> I assume that this only happen when `rspec-rails` is built against Rails `master` right?

Right 👍 I discovered the problem when testing my application against Rails master, which I'm only doing to try to flush out regressions in Rails. I'm not blocked by it, no apology necessary 🙂 

> Maybe we can make DeprecatedConstantProxy inherit from Module

This does appear to work! 💥

**Pull request merged**
