### PR TITLE
formatting changes

### PR DESCRIPTION
**Pull request by manishspuri**

### CODE REVIEW

**Comment by kaspth** [comment]
Thanks! Next time if you're doing a documentation fix remember to prefix your commit with [ci skip] so Travis doesn't run :smile:

**Comment by manishspuri** [comment]
sure thanks :+1:

**Comment by kaspth** [comment]
@manishspuri Eh, wasn't this commit supposed to be #20369 and #20368 in one? :smile:

**Comment by manishspuri** [comment]
man i messed up my commits somehow...!

**Pull request merged**
