### PR TITLE
Point links in AR README to Rails Guides or API [ci skip]

### PR DESCRIPTION
**Pull request by maxbeizer**
I noticed all the links in the README for `rails/activerecord/` 404'd. Some of these lines appear to be DHH's from 2005. I tried to find a specific link in the Rails Guides or the API for each existing link. I'm happy to update if better links are suggested. 

I would be happy to try to find some more of these in other READMEs if you all give the :+1: .

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Thank you for the pull request, but these links are broken by design. They are made to be read at http://api.rubyonrails.org/files/activerecord/README_rdoc.html

**Comment by maxbeizer** [comment]
Oh. Ok. Thanks and sorry for the stray PR.

Congrats on being named a Ruby Hero, by the way!

**Comment by rafaelfranca** [comment]
Don't worry, we have a lot of these PRs, but not sure how to make it clear cc @fxn.

> Congrats on being named a Ruby Hero, by the way!

Thank you :smile:

**Comment by maxbeizer** [comment]
Maybe a section in the [contributing guide](http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#contributing-to-the-rails-documentation) on where *not* to update the docs? Thanks for all you do for the Rails community.

**Pull request closed without merging**
