### PR TITLE
Fix for has_and_belongs_to_many & has_many_through associations

### LINKED ISSUE #19663: HABTM new records error when saving when partial writes are off
Example spec fail here - https://gist.github.com/malmckay/1262766f0d8980db6fe7

When I disable partial_writes my HABTM association error on save (in some cases).

PrimaryKey#id_was raises, because the join table does not have a primary key.

### PR DESCRIPTION
**Pull request by meinac**
Fix for has_and_belongs_to_many & has_many_through associations while partial_writes is false

This will fix #19663
Also with this fix, active record does not fires unnecassary update queries while partial_writes is true

### CODE REVIEW

**Comment by meinac** [comment]
I believe travis failure is not about my commit.

**Comment by maclover7** [comment]
Please rebase.

**Comment by arthurnn** [comment]
Can you add a changelog for it, and rebase. I will merge it after that. 

Thanks

**Comment by meinac** [comment]
Hi @arthurnn, I've rebased and added a changelog entry.

**Comment by meinac** [comment]
I've rebased again.

**Comment by arthurnn** [comment]
sorry, this felt out of my radar.

merged into master https://github.com/rails/rails/commit/a0a37d9fd3c35f44fa58439fa41b4cdff2d25a98

**Pull request merged**
