### PR TITLE
Rails 5.0 needs ruby 2.2.1 or higher

### PR DESCRIPTION
**Pull request by jvanbaarsen**
Since there was a bug in 2.2.0, the minimum ruby requirement is 2.2.1. 
See https://github.com/rails/rails/commit/8ed0b89b

### CODE REVIEW

**Comment by kaspth** [comment]
I think you need to add [ci skip] to your commit message otherwise Travis will run on the merge commit.

**Comment by jvanbaarsen** [comment]
@kaspth Ah ok. Wil fix :)

**Comment by eileencodes** [comment]
Thanks!

**Comment by gsamokovarov** [comment]
Thanks @jvanbaarsen!

**Pull request merged**
