### PR TITLE
Run `test:prepare` unless exact tests are specified

### PR DESCRIPTION
**Pull request by jonathanhefner**
Follow-up to #46664.

In #46664, `bin/rails test` _without_ args, `bin/rails test:all`, and `bin/rails test:system` were made to run the `test:prepare` task. However `bin/rails test` _with_ args (e.g. `bin/rails test --seed 1234`) and other `test:*` commands (e.g. `bin/rails test:models`) were not made to do so.

This commit changes `bin/rails test` to always run `test:prepare` unless exact tests are specified via path arguments (e.g. `bin/rails test path/to/test.rb`) or a name pattern (e.g. `bin/rails test -n test_foo`).

This commit also refactors the testing Rake tasks so that all of the logic regarding which files to load and whether to run `test:prepare` is contained within the `TestCommand` class.

### CODE REVIEW

**Comment by dhh** [comment]
All I really care about is this:

1. All versions of "test", that is running the entire suite or a subsection like "all model tests", should run db:prepare and test:prepare.
2. All versions of "test specific_file.rb" or "test -n named_case" or "test file:29" should NOT run db:prepare/test:prepare, as these loops need to be as quick as possible for development flow.

**Comment by ghiculescu** [comment]
Hey @jonathanhefner a few things to clarify from https://github.com/rails/rails/pull/46664. Thanks for the writeup.

- The intent of https://github.com/rails/rails/pull/46664 was to make it easier to run all rails tests in CI with a single command (without having to remember to `test:prepare`).
- As a result I overlooked commands like `test:models` becuase I'd never run those in CI. That said I agree with you they should run `test:prepare`. Thanks for fixing.
- I agree with DHH that running a specific file or test should *not* run `test:prepare`. That was deliberately left out of my PR, it wasn't an oversight or confusion. `test:prepare` is a placeholder, but if you use any of the new Rails approaches to frontend (eg `tailwindcss-rails`) you'll have something hooking into it, and those hooks are not instant. That's the performance concern he's alluding to.
- I think [this comment](https://github.com/rails/rails/blob/3cca0d5205329e28a9879739bb2d3ae3cff1b14f/railties/lib/rails/test_unit/testing.rake#L21) is wrong and should be removed. As far as I can tell `test:prepare` doesn't do that, and I think the comment is confusing it with `db:test:prepare`. See also [this discussion](https://github.com/rails/rails/pull/46664#issuecomment-1379522169).

-------------

Since https://github.com/rails/rails/pull/46664 was merged, @rafaelfranca observed something (in Discord), which is that if you have never done an asset compilation, then running `test -n named_case` will also fail. An example:

- You freshly clone a repo and immediately do `bin/rails test -n the_test`
- As a result,  `test:prepare` never run
- "the_test" makes a request to a page that has a `stylesheet_link_tag "tailwind"`, and you're using `tailwindcss-rails`, which hooks into `test:prepare`.
- the request will crash, as the Tailwind file was never generated.


The best idea so far is for sprockets/propshaft to have some sort of "asset missing" hook that `tailwindcss-rails` (etc) can hook into. This would solve for the asset compilation case (which is what I was looking to fix in the first place) but not the more general case if you have `test:prepare` doing other stuff. I don't think this PR should tackle that, just flagging it here as something else to consider.

**Comment by ghiculescu** [comment]
You’d also need to sweep that file when things change (say, you add a new asset). It would get complex quick 🤔

Let me know if you want a CR on this when it’s ready.

**Comment by jonathanhefner** [comment]
> You’d also need to sweep that file when things change (say, you add a new asset). It would get complex quick

At that point it seems like either (1) `test:prepare` should actually always be run, and the responsibility of not doing unnecessary / expensive work falls on the code that hooks into it, or (2) the user is responsible for manually running `test:prepare` as necessary when they want to use a fast dev loop with e.g. `test -n`.

> Let me know if you want a CR on this when it’s ready.

I think everything here is good to go.  What do you think?

**Comment by ghiculescu** [comment]
> the user is responsible for manually running `test:prepare` as necessary when they want to use a fast dev loop with e.g. `test -n`

For this PR I vote this, that was the intended outcome from my PR, and it seems simpler than option 2 (which would require updates to a bunch of other gems).

**Review by ghiculescu — APPROVED** [review]

**Comment by dhh** [comment]
I don't think we need to do anything around the fact that if you run a single test case prior to running the full suite, that you won't have compiled assets. Beyond, maybe, just catching the exception in test and giving you a clue on what to do. It's totally fine that you manually have to generate assets once first.

**Comment by etiennebarrie** [comment]
Maybe we could add a `test:prepare` in `bin/setup`, that way it works if you clone, simply run `bin/setup` and then run a single test.

**Pull request merged**
