### PR TITLE
Move respond_with to the responders gem

### PR DESCRIPTION
**Pull request by josevalim**
respond_with (and consequently the class-level respond_to)
are being removed from Rails. Instead of moving it to a 3rd
library, the functionality will be moved to responders gem
(at github.com/plataformatec/responders) which already provides
some responders extensions.

### CODE REVIEW

**Comment by runwaldarshu** [comment]
I am wondering if I add responders gem into gemspec why will it still need to be added in Gemfile where gemspec is included in Gemfile.
I am seeing failures while doing that.

**Comment by jedschneider** [comment]
Is rails not using semantic versioning? This should not have been included in a minor release without providing backwards support for 4.x apps that use responders. A deprecation warning and request to move would have been OK, but breaking changes should have been done at 5.0.

**Comment by rafaelfranca** [comment]
> Is rails not using semantic versioning?

http://guides.rubyonrails.org/maintenance_policy.html

> This should not have been included in a minor release without providing backwards support for 4.x apps that use responders.

http://guides.rubyonrails.org/4_2_release_notes.html#respond-with-class-level-respond-to

**Comment by chancancode** [comment]
@runwaldarshu when adding something to the gemspec, it will add that library to your gem's dependency graph, so that when you `gem install your-gem`, rubygems would know that it needs to install `your-dependency` too. However, it does not automatically `require your-dependency` for you.

On the other hand, the `Gemfile` in `your-library` (as opposed to your Rails app's Gemfile) is only used for development purpose, and does not affect the dependency graph of your published gem (`your-library`). However, adding something to the `Gemfile` also, by default, requires it automatically (unless you specified `require: false`).

So, if you are packaging a gem/engine that uses `responsers`, your set up should probably look like this:

```
# your_engine/your_engine.gemspec

  ...
  s.add_dependency "responsers", "..."
  ...
```

```
# your_engine/Gemfile

gemspec
```

```
# your_engine/lib/your_engine.rb
require 'your_engine/version'
...
require 'responders'
...
```

**Comment by jedschneider** [comment]
@rafaelfranca thanks for the clarification. Working with a student that is having a hard time getting responders loaded in her project. Since my last comment I upgraded an app to 4.2 without issue, but devise was included so it was already complaining that I needed the responders gem for that dependency to work. For me it was seamless, but apparently not for everyone.

**Comment by rafaelfranca** [comment]
@jedschneider the version of Devise compatible with Rails 4.2 already include responders gem as dependecy https://github.com/plataformatec/devise/blob/v3.4.1/devise.gemspec#L28

**Comment by jedschneider** [comment]
@rafaelfranca FWIW had to `bundle update devise` as well to pick up that change (and it did work). But I'd probably rather leave the dependency fully qualified in my Gemfile anyway, since I'm using responders directly in my controllers. Thanks again.

**Comment by jedschneider** [comment]
@rafaelfranca worked through the student's issue. I think the confusion was associated with the installation of the responders gem, and the bootstrapping that it does with the generator, vs what you need to do directly in rails (just require). I'm not sure thats worth a note or not.

**Comment by rafaelfranca** [comment]
@jedschneider yeah, installation of responders seems to confuse people. Maybe we should make explicit that the install process is optional at responders README.

**Comment by lacostenycoder** [comment]
I've read through this but don't quite understand "why" the responders have been removed from rails. Is there a better way of doing this in rails 4.2 ?

**Comment by rafaelfranca** [comment]
@lacostenycoder with variants and things like jbuilder this feature becomes out of date. The idea of variants would not work with it so we chose to just remove from the core. Pay attention that the feature is still supported, just outside of the default Rails stack.

**Pull request merged**
