### PR TITLE
[ci skip] fix #23157

### LINKED ISSUE #23157: Getting Started guide should be more informative about :references
The getting started guide does not explain why it is generating a model with a :references data type column. It should be explained in a bit of details.. Section 6.1
http://guides.rubyonrails.org/getting_started.html

### PR DESCRIPTION
**Pull request by shakib609**

### CODE REVIEW

**Comment by shakib609** [comment]
@maclover7 Is it ok now?

**Comment by maclover7** [comment]
:+1: Thank you for your contribution!

**Comment by maclover7** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by shakib609** [comment]
:+1: :smiley:

**Pull request merged**
