### PR TITLE
Update test dummy application defaults to remove warnings

### PR DESCRIPTION
**Pull request by zzak**
Affected gems:

* actionmailbox
* activestorage
* actiontext

This fixes the following warning:

```
DEPRECATION WARNING: Using legacy connection handling is deprecated. Please set
`legacy_connection_handling` to `false` in your application.

The new connection handling does not support `connection_handlers`
getter and setter.

Read more about how to migrate at: https://guides.rubyonrails.org/active_record_multiple_databases.html#migrate-to-the-new-connection-handling
 (called from require at ~/.gem/ruby/3.1.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34)
 ```

### CODE REVIEW

**Comment by eugeneius** [comment]
👍 

Active Storage and Action Text also have dummy apps, which have the same problem:

https://buildkite.com/rails/rails/builds/77642#459f0e23-956a-4900-b577-692fc85b0c69/1067-1083
https://buildkite.com/rails/rails/builds/77642#cc40736e-2f80-45e3-af04-7d1db31f59ce/1067-1091

**Comment by zzak** [comment]
@eugeneius Thanks! I will patch those too and put them in this same commit

**Comment by zzak** [comment]
@eugeneius Done! 🙏

**Comment by zzak** [comment]
Ok I see some actually relevant errors in CI:

```
ActiveStorage::PreviewTest#test_previewing_on_the_writer_DB:
--
&nbsp; | NotImplementedError: `while_preventing_writes` is only available on the connection_handler with legacy_connection_handling
&nbsp; | /rails/activerecord/lib/active_record/connection_adapters/abstract/connection_handler.rb:104:in `while_preventing_writes'
&nbsp; | /rails/activestorage/test/models/preview_test.rb:58:in `block in &lt;class:PreviewTest&gt;'
```

Will work on fixing these first.

**Comment by zzak** [comment]
@eugeneius I fixed the ActionMailbox tests and pulled in some commits from #42543 that fixed the ActiveStorage tests. This should be good to go 🙏

**Comment by pixeltrix** [comment]
@zzak thanks! 👍🏻

**Comment by vipera** [comment]
Would it be possible to backport this change to 6.1, as I've actually run into a bug using `ActiveStorage::VariantWithRecord` without the service delegate when calling processed on an ActiveStorage variant using the track_variants feature:

```
undefined method `service' for #<ActiveStorage::VariantWithRecord:...>
```

**Pull request merged**
