### PR TITLE
Return immediate result after attach method calls

### PR DESCRIPTION
**Pull request by sinankeskin**
### Summary

As described [here](https://github.com/rails/rails/issues/36238) before, starting from v6.0 ActiveStorage changed the behavior with returning boolean value instead of attachment(s).

But this caused some overhead in our app. 

Let's say we have a model like this:

```ruby
class Company < ApplicationRecord
  has_many_attached :images
end
```

and we are attaching some images, we used to have:

```ruby
if attached = @images.attach(image_params[:signed_id])
  render json: attached,
          width: 150,
          height: 150,
          root: 'company_image',
          status: :created
else
  render json: { errors: company.errors.full_messages },
          status: :unprocessable_entity
end
```

but after that changes, we need to change these lines like this:

```ruby
if @images.attach(image_params[:signed_id])
  render json: @images.includes(:blob)
                      .where(active_storage_blobs: { id: image_params[:blob_id] })
                      .first,
         width: 150,
         height: 150,
         root: 'company_image',
         status: :created
else
  render json: { errors: company.errors.full_messages },
         status: :unprocessable_entity
end
```

This PR returns the behavior to pre v6.0 again.

### Other Information

Also this behavior is good for SPAs. For example: We usually create an Ember Data model for this kind of records like: **CompanyImage** and in our situation Ember expects a json representation of a model for return after the attach. It reloads the model on background and refreshes the data if we display on the screen.

Let's say we have a dynamic drag & drop upload section. After the attachments sent to the API if we return json representations Ember automatically tracks the updated URLs and displays the images on the screen.

I hope I can describe the issue here.

Thanks.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Can you add a CHANGELOG entry and also document that this method now return a record?

**Comment by sinankeskin** [comment]
Sure. On it. Thanks @rafaelfranca

**Comment by sinankeskin** [comment]
Updated accordingly @rafaelfranca 

If anywhere I should update please let me know.

Thanks a lot.

**Comment by sinankeskin** [comment]
Why?

**Comment by p8** [comment]
@sinankeskin we automatically close issues without recent activity to keep the amount of issues manageable.
Sorry, but a similar PR got merged recently, https://github.com/rails/rails/pull/44439.
As your PR is older it should have gotten precedence.

The other PR only handled the persisted case.
Could you rebase on main and add tests for the non-persisted case?

**Comment by sinankeskin** [comment]
> @sinankeskin we automatically close issues without recent activity to keep the amount of issues manageable. Sorry, but a similar PR got merged recently, #44439. As your PR is older it should have gotten precedence.
> 
> The other PR only handled the persisted case. Could you rebase on main and add tests for the non-persisted case?

No need. Thank you @p8

**Pull request closed without merging**
