### PR TITLE
Fixed ActionController link in `Layouts and Rendering in Rails` docs

### LINKED ISSUE #46023: Documentation bug: Layouts and Rendering in Rails link to ActionController::Base#render
### Steps to reproduce

Got to https://guides.rubyonrails.org/layouts_and_rendering.html#using-render and click the link titled `ActionController::Base#render`

### Expected behavior

You are taken to https://api.rubyonrails.org/v7.0.4/classes/ActionController/Rendering.html#method-i-render

### Actual behavior

You are taken to https://api.rubyonrails.org/v7.0.4/classes/AbstractController/Rendering.html#method-i-render

I.e. there is a typo in the href, it should be `ActionController` not `AbstractController`

### PR DESCRIPTION
**Pull request by sreeram-venkitesh**
Fixes the typo mentioned in #46023

### CODE REVIEW

**Comment by p8** [comment]
ActionController::Base#render is inherited from AbstractController::Base#render.
Changing the link won't show the doucmentation for `#render`.

I think we should change line 108 to mention `AbstractController::Rendering` instead:
```
In most cases, the [`AbstractController::Rendering#render`][controller.render] method does the heavy ...
```

**Comment by p8** [comment]
Thanks @sreeram-venkitesh !
Can you squash your commits?

**Comment by sreeram-venkitesh** [comment]
@p8 I've squashed the commits and have force pushed. Please let me know if this is fine!

**Comment by p8** [comment]
Thanks @sreeram-venkitesh 🙌 !

**Pull request merged**
