### PR TITLE
The `model_name` method should be called on `to_model`

### PR DESCRIPTION
**Pull request by mcls**
See https://github.com/rails/rails/issues/18646

Should the same be done for the following lines? E.g. `model.respond_to?(:human_attribute_name)`
https://github.com/rails/rails/blob/v4.2.0/actionview/lib/action_view/helpers/tags/placeholderable.rb#L22-L24

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Actually I think we should call set `object = object.to_model` and use it later.

**Comment by mcls** [comment]
Is there a reason it doesn't happen immediately when doing the `retrieve_object`?

https://github.com/rails/rails/blob/v4.2.0/actionview/lib/action_view/helpers/tags/base.rb#L41

**Comment by rafaelfranca** [comment]
I don't think so. Try it and see how tests responds to the change.

**Comment by mcls** [comment]
Yeah, never mind, they blew up. I'll try to find that out for myself later.

I'll just add the `object = object.to_model` for now.

Thanks for the help

**Comment by mcls** [comment]
Hmm... found very similar code here: https://github.com/rails/rails/blob/v4.2.0/actionview/lib/action_view/helpers/tags/label.rb#L20-L32

I'll try to clean that up

**Comment by mcls** [comment]
Not to sure about that last commit. 

It reduces the duplication, but it could probably be done in a clearer way.

**Comment by mfazekas** [comment]
There is a bug in the merged version:
https://github.com/rails/rails/commit/79100b8a3a8057c5826dc064fea91b73f0080b4c#diff-75ef522cd1bc95094df58064c185a4efR11

```ruby
@model = object.respond_to?(:to_model) ? object.to_model : object```

we should not set ```@model``` if it's not responds to ```:to_model```, this breaks 
```ruby
form_for(OpenStuct.new(....),)
```
see #18834

**Pull request merged**
