### PR TITLE
Update 'rails_welcome.png' to reflect a more diverse population

### PR DESCRIPTION
**Pull request by asianmack**
rails-welcome-new

cc @dhh

### CODE REVIEW

**Comment by dukedave** [comment]
Love it! Probably can update the [Twitter banner](https://twitter.com/rails) too? 💫

**Comment by dhh** [comment]
Good point. I've updated the banner 👍

**Comment by coderliu** [comment]
Where is the dog? This hurt people who love dog.

**Comment by ismailarilik** [comment]
Cat stays but dog leaves; it is not inclusive I think (Let's remove all animals from this image to get more place for people.). Also I think inclusive should mean including members of common religions and races.

**Comment by onomojo** [comment]
There's no dog anymore. I'm offended.

**Pull request merged**
