### PR TITLE
Hashing in AR wthout array allocation and updating corresponding documentation to reference the class

### PR DESCRIPTION
**Pull request by brocktimus**
### Summary

I noticed the comment in c8be4574 by @sgrif mentioning array allocation he didn't like. I'd read elsewhere that multiple hashes could just be combined with xor. Also updating documentation to reference that we're also hashing in the class.
### Other Information

Only addressing because of comments in the prior commit. I'm obviously not going to hunt around trying to shave an object allocation from random methods. Probably more useful for the documentation side of the commit more than anything else.

Does this need a change log since previous change didn't have one?

### CODE REVIEW

**Comment by sgrif** [comment]
You can technically combine two hashes with xor, but it's not the same as applying multiple values in the hashing function, and is more likely to cause collisions. Debating whether it bothers me more than the allocation does

**Comment by brocktimus** [comment]
Looks like this was basically merged in a6da7938017647dd6e19e23d3d47126cb7a3e1fe

**Comment by sgrif** [comment]
Ah shit sorry @brocktimus I forgot there was a PR for this. I was having a discussion at work about hashing and decided to go forward with it. Sorry about that! :heart:

**Comment by brocktimus** [comment]
No worries :+1: love the work!

**Comment by prathamesh-sonpatki** [comment]
@brocktimus @sgrif The documentation still needs to be updated?

**Comment by sgrif** [comment]
The documentation is still generally correct. I don't think we need to document the specific implementation of it. The externally visible behavior hasn't changed.

**Pull request closed without merging**
