### PR TITLE
Fix `ActionDispatch::Http::URL` docs [ci skip]

### PR DESCRIPTION
**Pull request by ojiry**
Use `ActionDispatch::Request` instead of `Request` because an error occurred.

### CODE REVIEW

**Comment by prathamesh-sonpatki** [comment]
Thanks, can you please tell what error occurred?

**Comment by ojiry** [comment]
@prathamesh-sonpatki 
Thanks, An error has occurred in the following code.
```shell
$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
$ rails -v
Rails 5.0.0.1
$ rails new example
$ cd example
$ bin/rails console
class Request < Rack::Request
  include ActionDispatch::Http::URL
end
=> Request
req = Request.new 'HTTP_HOST' => 'example.com'
ArgumentError: wrong number of arguments (given 1, expected 0)
```

**Comment by prathamesh-sonpatki** [comment]
Thanks @ojiry! Can you update the commit message to say -->

`Use ActionDispatch::Request instead of Request because ActionDispatch::Request no longer inherits from Rack::Request.`

**Comment by ojiry** [comment]
Thanks @pramod-sharma! Updated the commit message.

**Comment by vipulnsward** [comment]
@ojiry is it because the resolution is being done in a wrong way?
I see https://github.com/rack/rack/blob/master/lib/rack/request.rb#L9 accepts arguments, what does "Request" class actually point to, in your case?

**Comment by prathamesh-sonpatki** [comment]
@vipulnsward Starting from 529136d670c46bd66b56c519d4f51e `AD::Request` no longer inherits from `Rack::Request`. 

The examples were written keeping in mind that `AD::Request` inherits from `Rack::Request` which is no longer true.

**Comment by prathamesh-sonpatki** [comment]
And in this case, the URL module defines its own initialize method -- https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/http/url.rb#L187 which is throwing the error @ojiry mentioned.

**Comment by ojiry** [comment]
Thanks @prathamesh-sonpatki, @vipulnsward!

**Pull request merged**
