### PR TITLE
Fix `enum` with `alias_attribute`

### LINKED ISSUE #25892: Aliased attributes don't play nice with enum
### Steps to reproduce

Create a model which has an `enum` declared on an aliased attribute:

```
class Person < ActiveRecord::Base
  alias_attribute :citizenship_status, :citizen

  enum citizenship_status: { citizen: 1, foreigner: 0 }
end
```

### Expected behavior

The query methods (`citizen?` and `foreigner?`) should function on model instances and return `true` if their respective values equal `citizenship_status`.

### Actual behavior

The query methods always return `false`.

### System configuration

**Rails version**: 4.2.7, 5.0.0

**Ruby version**: 3.2.1

### PR DESCRIPTION
**Pull request by kamipo**
Fixes #25892.

### CODE REVIEW

**Comment by eileencodes** [comment]
Thanks for fixing that 🐛 !

**Comment by thomasfedb** [comment]
Thanks @kamipo!

**Comment by rafaelfranca** [comment]
Backported in 919a876

**Comment by thomasfedb** [comment]
@rafaelfranca do you know what release this will make it into?

**Comment by rafaelfranca** [comment]
5.0.1

**Pull request merged**
