### PR TITLE
Update permissions policy list

### PR DESCRIPTION
**Pull request by guillaumecabanel**
### Summary

The list of available [Permissions Policy](https://github.com/w3c/webappsec-permissions-policy/blob/master/features.md#policy-controlled-features) has evolved.

This pull request add the new stable features to `ActionDispatch::PermissionsPolicy`.

List of features supported in Chrome (version) added with this pull request:
- hid (Chrome 89)
- idle-detection (Chrome 94)
- screen-wake-lock (Chrome 84)
- serial (Chrome 89)
- sync-xhr (Chrome 65)
- web-share (Chrome 86)

### Other Information

There also features not present in the W3C list and I don't know what we should do about them:
- speaker
- vibrate
- vr

### CODE REVIEW

**Comment by jonathanhefner** [comment]
> There also features not present in the W3C list and I don't know what we should do about them:
>
>     * speaker
>     * vibrate
>     * vr

These were apparently listed as [policy-controlled features](https://github.com/w3c/webappsec-permissions-policy/blob/6d8bbbe738368c317d280bb866c66cedaef3391c/features.md) around the time when #33439 was first written (2018-07-25), but they are now obsolete.  Since those methods are part of the Rails public API, we should deprecate them before removing them (even though they are non-functional).  So I submitted #46199 to do that.

Thank you, @guillaumecabanel! :smile:

**Comment by guillaumecabanel** [comment]
Alright, thank you @jonathanhefner for your explanation :+1:

**Comment by p8** [comment]
@guillaumecabanel Could you add a CHANGELOG entry for this as well?

**Comment by guillaumecabanel** [comment]
> @guillaumecabanel Could you add a CHANGELOG entry for this as well?

Yes, sure! I just added a CHANGELOG entry in https://github.com/rails/rails/pull/46215

**Pull request merged**
