### PR TITLE
actionpack: Code style optimization

### PR DESCRIPTION
**Pull request by RoxasShadow**
Today I started reading the rails' codebase, and for every file I read I tried to make little optimizations and code style enhancements.
Things like private methods were a little mess. For example, just in the actionpack atm I see all [these](http://sprunge.us/LVFW?rb) three ways used but I can't find any reference to follow a sort of standard. In this case, I tried to keep the way that actually we used most so far.

Following some examples of the changes I did with a little explaination next:
- `"something"` -> `'something'`: When no interpolation is needed, single quotes are faster
- `:some => :thing` -> `some: :thing`: As suggested in the rails' guidelines
- `'s'` -> `?s`: Chars are a little more performant than strings and also are more coherent in cases like this
- Brackets, spaces and some `#freeze`s because why not.

I think that a work like this one is worth the time if we'll be more strict in front of a PR with LoCs written with too much freedom compared to the actual rails' codebase.

If even you guys think the same I can spend more time doing this in both actionpack and the other components.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Thank you so much for the pull request, but we don't accept cosmetic changes as explained at http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#write-your-code.

**Comment by RoxasShadow** [comment]
Well, even though there are lots of cosmetic changes, some of them are also related to the performance. Consider `'` in place of `"`, the use of `?` for the chars and the `#freeze`s I applied on some strings.

If you still think this PR is not acceptable I'm ok with this, it's just to highlight the nature of some changes I submitted.

**Comment by rafaelfranca** [comment]
> ' in place of "

They have the same performance.

And we only accept performance optimizations if they are justified with benchmark.

**Comment by RoxasShadow** [comment]
```
pry(main)> Benchmark.ips do |x|
pry(main)*   x.report('"') { "something" }  
pry(main)*   x.report('\'') { 'something' }  
pry(main)* end  
Calculating -------------------------------------
                   "   28.546k i/100ms
                   '    32.544k i/100ms
-------------------------------------------------
                   "      3.276M (±19.1%) i/s -     15.615M
                   '      3.516M (±14.4%) i/s -     16.988M
```

The performance gap is very little, but it still exists.

**Comment by rafaelfranca** [comment]
If you take in consideration the standard deviation of almost 20% on your benchmark, they are the same.

**Pull request closed without merging**
