### PR TITLE
Improve handling of querying and loading data with ignored_columns

### PR DESCRIPTION
**Pull request by jasonroelofs**
There are multiple situations that led to investigating how
`ignored_columns` works, how it interacts with querying and how to make
it better in more situations.

The first problem is that the use of `ignored_columns` in a class was
breaking migrations that ran after the removal of a column in that class
(a column that was not added to `ignored_columns`). This turned out to
be because when `ignored_columns` has entries, AR was exploding the full
list of known columns in the query (including the column that was just
removed , instead of letting `Arel.star` just return the database's known
list. While this is solvable by adding `reset_column_information` in the
migration between column removal and the failing code, this research led
to our next concern.

Our second concern is the performance effects of splatting out the full
column list for every query for a model with `ignored_columns` set. We
haven't done explicit performance testing but processing a list of
`arel_columns` is definitely slower than a simple `Arel.star`, and this
could easily add up for high traffic sites.

As such, we wanted to find a way to support `ignored_columns` properly,
including keeping the correct `reload` functionality, without resorting
to a full set of columns for every query.

This commit contains two changes to fix the above concerns.

* When a select set is explicitly given, remove the columns that are in
the `ignored_columns` list.
* When loading a record from the database, ignore the attributes that
are in the `ignored_columns` list.

/cc @eileencodes @tenderlove

### CODE REVIEW

**Comment by matthewd** [comment]
The documentation says "Ignored columns won't have attribute accessors defined, and won't be referenced in SQL queries."

While "don't explicitly reference this in queries, because we're in the middle of dropping it" is a popular use case for that functionality, I'm not sure it's the only one: it seems pretty reasonable to be using it to exclude the big `posts.body_text` column (and then manually load on demand), for example. Forcefully excluding the column ~even~ only when it's been explicitly requested seems to break that twice over.

**Comment by jasonroelofs** [comment]
That is an interesting use case. If there are people using `ignored_columns` this way then yes these changes will break that flow.

**Comment by eileencodes** [comment]
For some background @matthewd we have a User table that has an ignored_column on it. It's a pretty large table so we end up having to select every single column to ignore 1 and we're worried it's going to affect performance

**Comment by matthewd** [comment]
I do think this option is currently doing double duty.. sometimes to mean "don't mention this" and others to mean "don't pull these values over the wire". Maybe it's worth splitting it internally into two names, so they can be overridden individually?

I don't think the explicit removal from select is desirable… IMO if you've gone out of your way to ask for it, we should give it to you -- specific [parameters on a query] beats general [method on a model].

How far could we get by extracting a
```ruby
def select_all_columns(table)
  if ignored_columns.any?
    column_names.map { |field| arel_attribute(field, table) }
  else
    table[Arel.star]
  end
end
```

from `build_select`?

That'd keep `ignored_columns` doing its existing double duty by default, but would allow the projection to be overridden separately (e.g., to force it back to Arel.star).

**Comment by jasonroelofs** [comment]
Right, looking at this again, dropping explicit selects is probably the wrong thing to do and would be unexpected behavior. If the column doesn't exist and you're explicitly asking for it, the query will explode.

Which then also follows that asking for an ignored column explicitly means it needs to come into the model when the result comes back.

I'll give this some more thought, thanks for the feedback.

**Pull request closed without merging**
