### PR TITLE
Fixed ActionCable::Connection::ClientSocketTest test

### PR DESCRIPTION
**Pull request by vipulnsward**
- Fixed ActionCable::Connection::ClientSocketTest that was overriding ActionCable::Connection::StreamTest test name
- Only add attr_readers for required attributes

### CODE REVIEW

**Comment by maclover7** [comment]
cc @matthewd

**Comment by jeremy** [comment]
Let's keep the separate test and just correct the test class name (omit the second commit)

**Comment by vipulnsward** [comment]
Ok, done.

**Pull request merged**
