### PR TITLE
remove unnecessary synchronize calls

### PR DESCRIPTION
**Pull request by grosser**
@pmahoney @thedarkone

### CODE REVIEW

**Comment by thedarkone** [comment]
Hi @grosser, is your goal perf optimization?

**Comment by pmahoney** [comment]
Is that an atomic operation? What's the rationale here? I tend to err on the side of safety, but I'm interested to learn.

**Comment by grosser** [comment]
returning an integer and comparing an integer are atomic, so we don't need to synchronize ... a performance refactor on code that looked shady to me

**Comment by thedarkone** [comment]
> returning an integer and comparing an integer are atomic, so we don't need to synchronize

If we are talking in general (i.e. not about how Rails uses these methods), this is not correct. Yes, it is true that reading an integer is atomic, but it is not true that without synchronization you are guaranteed to see an up to date value. Specifically Ruby VM is allowed to hoist the read out of the loop, so a code like this would be broken:

```ruby
loop do
  submit_work!
  # careful not to overwhelm the queue, lets wait if too many threads are queued up!
  while queue.num_waiting >= 3
    # busy spin...
  end
end
```

A compiler might transform the above code into smth like this:

```ruby
loop do
  submit_work!
  # careful not to overwhelm the queue, lets wait if too many threads are queued up!
  __tmp = queue.num_waiting
  while __tmp >= 3
    # busy spin...
  end
end
```

----

Since both of the methods are not on a typical hot code path (check out, check in), I don't think this should be merged.

**Comment by grosser** [comment]
This sounds wrong to me ... it's a method call in a while ... it will execute on ever iteration ... otherwise soooo many things would break.

The only reason I could think of would be an inconsistent value during operation ... for example here if we used synchronize we would never see the `0`
```
sync do
  @num = 0
  ... do work ...
  @num = 5
end
```

but none of the code in this file works like that

**Comment by thedarkone** [comment]
> This sounds wrong to me ... it's a method call in a while ... it will execute on ever iteration ... otherwise soooo many things would break.

My bad, I now see I wasn't clear in my reply, I've skipped over a couple of things. What I meant is that when the `loop do` body is compiled, method inlining might be done by the compiler. So the body of the `num_waiting` method is inlined into the `loop do` body and compiled as a simple `@num_waiting` i-var read, and that i-var read is then optimized and hoisted out of the loop.

Nothing would break, these are basic and legal optimizations that for example https://github.com/graalvm/truffleruby does.

**Comment by utilum** [comment]
No need to have a test for this?

**Comment by matthewd** [comment]
Regardless of whether they're needed for full correctness, having these as unsynchronized methods on a generally lock-happy object will just distract me every time I look past this code.

... and as far as I can see, this doesn't actually save us any lock acquisitions: each time the ConnectionPool calls one of these methods, it's already inside a synchronize. synchronize while already holding the lock isn't free, but it's pretty darn close -- even before we consider the complexity of adjacent operations.

None of what I just said is a particularly strong argument, but I think I prefer to keep it, just so the methods don't demand a second glance.

Thanks!

**Pull request closed without merging**
