### PR TITLE
Action cable testing

### PR DESCRIPTION
**Pull request by palkan**
This PR is a remake of the older PRs (https://github.com/rails/rails/pull/23211 and https://github.com/rails/rails/pull/27191).

After [discussing it again](https://github.com/rails/rails/pull/23211#issuecomment-413219187) we decided to get it done for Rails 6.

This PR is the first one in the series (and the base). The idea is to merge [`action-cable-testing`](https://github.com/palkan/action-cable-testing) gem into Rails, step by step:

- [x] Add Test adapter
- [x] Add Test helper (for broadcasting tests)
- [x] Add channels unit-testing support (https://github.com/rails/rails/pull/33969)
- [x] Add connections unit-testing support (https://github.com/rails/rails/pull/34845)
- [x] Generators (https://github.com/rails/rails/pull/34933)
- [x] Guides (https://github.com/rails/rails/pull/34933)

/cc @dhh @matthewd @kaspth

### CODE REVIEW

**Comment by dhh** [comment]
I like this! There are some improvements to the implementation we can make, but I'd be happy to merge this first, and then make those improvements. Thanks again 👌

**Comment by eileencodes** [comment]
Merged so we can make more progress and since DHH said he is happy to merge first.

**Comment by kaspth** [comment]
@palkan thanks for all your help with this! I'm sorry it took so long ❤️

**Comment by victorhazbun** [comment]
Thank you @palkan

**Comment by ahcarpenter** [comment]
Thanks for this @palkan!!

**Comment by rmacklin** [comment]
@palkan
After discovering anycable last year, I had found #23211 and had checked in on that PR from time to time. I'm super glad to see your contributions finally make it into rails after all this time! Thanks very much for persevering!

**Comment by seanfcarroll** [comment]
Until we all update to v6, there is [this gem](https://github.com/palkan/action-cable-testing) available.

**Comment by kunal6673** [comment]
Start

**Pull request merged**
