### PR TITLE
Use thread pool for ActionController::Live

### PR DESCRIPTION
**Pull request by tgwizard**
### Motivation / Background

Currently, all controllers that use `ActionController::Live` create a new thread to process every request. Creating threads is somewhat expensive. We can avoid that by using a thread pool, which we do already elsewhere in rails.

### Detail

This PR introduces `ActionController::Live.live_thread_pool_executor`, which can contain any number of threads, keeping them around for a while (60s is the default in concurrent-ruby).

I also clean up the thread locals we copy over from the parent thread. This is a bit messy. There are probably some tests required, though I'm not entirely sure where to put them.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Tests are here https://github.com/rails/rails/blob/main/actionpack/test/controller/live_stream_test.rb. There are tests for copying the locals. But note that this test class is overriding the method you changed, so we need to remove the override.

**Comment by tgwizard** [comment]
@rafaelfranca tests added, should be good to review now. (Some seemingly unrelated tests were flaky on CI, but now they all pass).

**Comment by tgwizard** [comment]
@rafaelfranca and team, please have a look.

**Comment by rafaelfranca** [comment]
Test are failing:

```

ActionController::LiveStreamTest#test_exception_callback_when_committed:
--
  | fatal: No live threads left. Deadlock?

```

**Comment by tgwizard** [comment]
Thanks @rafaelfranca, I found a way to reproduce it, and pushed a fix. Tests are green now.

**Pull request merged**
