### PR TITLE
Fix nil return on belongs_to call to non existing klass

### PR DESCRIPTION
**Pull request by fedeagripa**
### Summary

Solves https://github.com/rails/rails/issues/39214
First checking `foreign_key_present?` returns nil that ends up returning prematurely in `belongs_to_assocation#find_target?` method.

### Other Information

I tried to fix it by changing `belongs_to_assocation#foreign_key_present?` by checking `reflection.klass` but as belongs_to can be used for polymorphic cases, a lot of other tests were broken.
I initially think this makes sense due to the different ways that a belongs to can behave (due to polymorphism), but please point me out if i'm wrong on my thoughts.

### CODE REVIEW

**Comment by fedeagripa** [comment]
@kamipo @rafaelfranca @tenderlove I see some errors that i'm not really familiar with on buildkite, could you provide any comment on the approach being taken 🙏

**Comment by kamipo** [comment]
All failures are fixed on current master, can you rebase?

**Comment by fedeagripa** [comment]
Thanks @kamipo all green now :)

**Comment by fedeagripa** [comment]
@kamipo do you think this is good to go, or should I add more info on some topic?

**Comment by kamipo** [comment]
An error is raised or not in `find_target?` was just an implementation fluke.

I think it is preferable to  raise a specific error explicitly more earlier time at least on `record.association(:foo)` if misconfigurated.

**Comment by fedeagripa** [comment]
What specific error would you like to see in this case? Cause NameError seems more than descriptive to me.

**Comment by kamipo** [comment]
For example, we have some error classes for misconfigrated associations:

https://github.com/rails/rails/blob/e93e45a502264e9869c35649afef28a89a38228d/activerecord/lib/active_record/associations.rb#L7-L235

**Comment by fedeagripa** [comment]
@kamipo sorry the delay, had a hard week.. 
I fixed it to raise an error as you propose and tests also, anyway I left the change that raises `NameError` when accessing. Because asides it being a fluke, I want to keep consistency as much as possible, hope you agree on this.

Finally let me know if you think any test is missing  😄

**Comment by fedeagripa** [comment]
@kamipo after some goes and backs I find out the problem being a test in `activerecord/test/cases/reflection_test.rb` that was adding some invalid belongs_to associations to non-existing classes.
Should I just keep this removal or change it to use valid classes?

**Comment by fedeagripa** [comment]
@kamipo giving one last poke to see if you find this interesting/desirable

**Comment by kamipo** [comment]
I think it is a bit expesive to traverse all association reflections on each `klass.new` for making this.

As I said at https://github.com/rails/rails/pull/39396#issuecomment-636289772, how about raising an error on `record.association(:foo)`?

**Comment by fedeagripa** [comment]
@kamipo completely agree on it being expensive. But I found that calling `Record.create!` does not raise an error if I place the check on `record.association(:foo)` from `association.rb#inverse_association_for`. That's why I went to update `inheritance#new`

My interpretation from your call to raise an error earlier was that if we can detect this on `record.new` instead of building the whole object and wait for a failure call to unexisting relation, it was preferred. Did I get it wrong?

**Comment by kamipo** [comment]
If no runtime overhead, an error on `record.new` is fine to me.

What I said at https://github.com/rails/rails/pull/39396#issuecomment-636289772 is that it is preferable to raise a specific error explicitly more earlier time than *`find_target?`*, at least on `record.association(:foo)` if misconfigurated, it is more consistently works for all association types.

**Comment by fedeagripa** [comment]
@kamipo my point on throwing an error at `record.association(:foo)` is that when I execute tests for `create` that code you propose is not being executed. That's why I end up placing a check on`inheritance#new`.

What I can do that may improve performance is to filter on `reflect_on_all_associations` to minimize the iteration size. Does that make sense or is not acceptable either?

**Pull request closed without merging**
