### PR TITLE
Include option to update the updated_at value for methods in ActiveRe…

### LINKED ISSUE #26724: ActiveRecord::CounterCache methods should have an option to change updated_at
ActiveRecord::CounterCache should provide an option to update `updated_at` when any one of these methods are called.
- [update_counters](https://github.com/rails/rails/blob/a9dc45459abcd9437085f4dd0aa3c9d0e64e062f/activerecord/lib/active_record/counter_cache.rb#L76)
- [reset_counters](https://github.com/rails/rails/blob/a9dc45459abcd9437085f4dd0aa3c9d0e64e062f/activerecord/lib/active_record/counter_cache.rb#L20)
- [decrement_counter](https://github.com/rails/rails/blob/a9dc45459abcd9437085f4dd0aa3c9d0e64e062f/activerecord/lib/active_record/counter_cache.rb#L120)
- [increment_counter](https://github.com/rails/rails/blob/a9dc45459abcd9437085f4dd0aa3c9d0e64e062f/activerecord/lib/active_record/counter_cache.rb#L102)

My application implements a trash module, so I must call `decrement_counter` when sending a record to the trash, and `increment_counter` when restoring a record. I'm displaying a counter cache in a view, and I would like for the fragment cache to expire whenever I increment or decrement the counters by updating the `updated_at` value. However, I must make a second call to the database to update the `updated_at` value after incrementing or decrementing the counter cache.

I think there should be an additional argument to send to these methods to change `updated_at` when changing the counter cache. For example:

``` ruby
Post.decrement_counter(:comments_count, 1, true) # This would change the post's updated_at value
Post.decrement_counter(:comments_count, 1, false) # This would NOT change the post's updated_at value
Post.decrement_counter(:comments_count, 1) # This would NOT change the post's updated_at value
```
### Expected behavior

ActiveRecord::CounterCache should be able to change a record's `updated_at` value.
### Actual behavior

ActiveRecord::CounterCache does not have the ability to change a record's `updated_at` value.
### System configuration

**Rails version**: 4.2.5.1

**Ruby version**: 2.2.3

### PR DESCRIPTION
**Pull request by jtrost**
### Summary

This fixes #26724. There are cases in which calling the methods in `ActiveRecord::CounterCache` should update the `updated_at` value of the affected records. For example, if a counter cache is included in a view that is fragment cached, it would be convenient if the fragment cache was expired when the counter cache was updated by changing the updated_at value.

Working with the API was a bit difficult here because each method in this module has a slightly different signature. This pull request ensures compatibility with the current implementation of these methods while providing this new feature. I'll go through each method to explain the changes:

**.reset_counters** accepts any number of counters as a splat argument, so the `{updated_at: true}` option is added as a double splat argument to separate it from the `counters` argument.

**.update_counters** accepts any number of counters as a hash. There is no way to add another argument at the end of this method signature since the current implementation looks like this:

```
Topic.update_counters(@topic.id, replies_count: 2, unique_replies_count: 2)
```

Therefore, I tacked `updated_at: true` onto the end of the `counters` argument, and it's removed from the hash before iterating through the counters.

**.increment_counter** and **.decrement_counter** accept a separate options hash much like `.reset_counters` does. These methods call `.update_counters`, so the options hash is merged into the `counters` hash.

### CODE REVIEW

**Comment by eileencodes** [comment]
In our Basecamp code we do update  do increment / decrement counters based on the creation / deletion record (comments on a message for example). We do this by explicitly touching the parent record in a callback.

One issue I see with this PR is that it assumes that the timestamp the code wants to update is always `updated_at`. In our codebase we use `last_discussed_at` as well as `updated_at` timestamps. The reason for this is because adding a comment isn't necessarily the only time a message is updated. In that case we have `last_discussed_at` for when a comment is added but `updated_at` can be changed for editing a message.

If we're going to include this addition in Rails it needs to support timestamps that are not called `updated_at`. Because of requiring the column name it might actually be easier for the programmer to add a callback that touches the correct code, but I'm open to seeing the implementation you come up with.

**Comment by jtrost** [comment]
@eileencodes Thanks for the feedback. Hard coding `updated_at` into this PR was a concern I had as well. Does Rails provide a way to find custom timestamp columns like `last_discussed_at`? I looked through [ActiveRecord::Timestamp](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/timestamp.rb), but that does not look like it supports custom timestamp names.

**Comment by eileencodes** [comment]
I don't think that Rails provides a way to collect the timestamps. It would have to be explicitly passed in like we do for `cache_key`: https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation.rb#L325

**Comment by kaspth** [comment]
How about a `:touch` option as the public API for this:

```ruby
# Uses `timestamp_attributes_for_update_in_model`:
Message.reset_counters [ 2, 18 ], comments_count: 5, touch: true

# Touch just one timestamp:
Message.reset_counters [ 2, 18 ], comments_count: 5, touch: :last_discussed_at

# The assumed rare case where you want to touch `updated_at` plus `last_discussed_at`:
Message.reset_counters [ 2, 18 ], comments_count: 5, touch: %i( updated_at last_discussed_at )
```

**Comment by kaspth** [comment]
Yeah, it looks like it got messed up. Can you try rebasing again or something?

**Pull request closed without merging**
