### PR TITLE
Allowing to convert to other file formats

### PR DESCRIPTION
**Pull request by mengqing**
### Summary
This change allows variant to accept `convert` parameter and convert the activestorage attachment to the requested format.

This is related to https://github.com/rails/rails/issues/37737

### Other Information

Currently the `convert` parameter takes any given format and tries to convert to requested format without any validations, and it would be ideal for `image_processing` to be able to validate the format and returns the relevant `content_type`

### CODE REVIEW

**Comment by mengqing** [comment]
Hi @georgeclaghorn, will this PR be looked at?

**Comment by rafamanzo** [comment]
Can I help out with this? I'm also interested in getting images in different formats such as webp for my app

**Comment by mengqing** [comment]
@rafamanzo I'm currently using this feature in my own project and it worked well for me for my requirement. I'm not sure what the status is for this PR though as to whether there's still more needed to be done

**Comment by rafamanzo** [comment]
Thanks @mengqing !

Let's hope it was just a matter of solving the conflict :)

I'll try to monkey patch my app in 6.0.3.1 with your changes.

**Comment by rafamanzo** [comment]
I'm sorry to bother @georgeclaghorn . Is there something we can help with so we get this merged?

**Comment by trobrock** [comment]
Here to help out if needed as well, would love to see this merged.

**Comment by strobilomyces** [comment]
This would be useful to me as well. Thank you.

**Comment by mashedkeyboard** [comment]
Adding another voice to the pile of "happy to help out with whatever's blocking this" - would be really handy to get this sorted.

**Comment by fareesh** [comment]
+1 will help to get this in. Please let us know what's needed

**Comment by Timmitry** [comment]
Just wondering why this was closed? Does the linked PR fix the issue? Doesn't sound like it to me, but I might be wrong 😇 

Does converting an existing image to webp now work in activestorage (and if so, how?)?

**Pull request closed without merging**
