### PR TITLE
ActiveJob - Sucker Punch adapter - Enqueue_at implementation

### PR DESCRIPTION
**Pull request by brandonhilkert**
Adds `enqueue_at` implementation for the `sucker_punch` adapter.

### CODE REVIEW

**Comment by kevinjalbert** [comment]
Figure I would drop this issue as well - https://github.com/brandonhilkert/sucker_punch/issues/97. Where it was initial brought up.

**Comment by seuros** [comment]
What will happen if the app is restarted ?

**Comment by brandonhilkert** [comment]
@seuros Jobs will go away since they're stored in memory. It's the same thing that happens if you build up a huge of jobs and the process gets restarted. This happens occasionally on heroku at least once a day or so, which is why I suggest people don't use sucker punch for anything really important. To me, email and logging fall in to the good use cases and what I personally use it for quite a bit.

**Comment by seuros** [comment]
If i recall correctly, we did have it like that and changed it (either in a PR or in the history) because it unreliable.

**Comment by seuros** [comment]
https://github.com/rails/activejob/commit/0c46094c770f233a6d3aa4660c84c9b9b4248d30

**Comment by brandonhilkert** [comment]
I don't think it warrants not being implemented. The same risk exists when using the gem outside of ActiveJob and as long as the user is educated, it seems reasonable to let them make that call, no?

@mperham Looks like you removed the implementation in the commit above. Curious if there were other reasons for it.

**Comment by mperham** [comment]
@dhh objected to it.  He didn't want the adapters to implement functionality that wasn't in the underlying library.

**Comment by dhh** [comment]
What @mperham said. If sucker punch adds this in the library, then we can gateway to that. But otherwise I'm not a fan.

**Comment by matthewd** [comment]
IMO, the difference is that an "immediate enqueue" is expected to get run some time in the very near future (seconds, minutes, whatever.. depending on your queue size); the "run at this time" functionality, on the other hand, is intended to be able to be used for serious deferrals... days, weeks, etc.

**Comment by brandonhilkert** [comment]
@dhh I understand. 

My only counterpoint would be that Sucker Punch itself is nothing more than a glorified DSL for Celluloid Pools. Sucker Punch itself doesn't even implement queues, it relies on Celluloid's internals to manage it. 

And with that same logic, the method `after` used in the `enqueue_at` method here is implemented within Celluloid. 

So I guess if we're being strict about the definition of implementation, it doesn't seem like Sucker Punch should be included at all, which would be a bummer I think due to the different of being in-process unlike most of the other adapters.

Not sure if that changes anyone's opinion, but I'd love your thoughts.

@matthewd - And there's nothing saying that job couldn't run weeks later if the process was still alive. Again, Sucker Punch has this same issue with the jobs enqueued. There are trade-offs, you don't have spin up another worker and doesn't add additional infrastructure overhead, but yet it's more unreliable. I think each of these libraries has their strengths and as long as that's known up front, it seems reasonable for the developer to make those decisions.

**Comment by cristianbica** [comment]
AFAIR we rejected `enqueue_at` for SP because scheduled jobs have a high chance of never being executed. I personally would like to keep this decision as having a feature that will probably drop data in the framework is a bad thing. However this can easily be implemented by users with a few lines of code or in a gem and in this way people really know the danger.

**Comment by brandonhilkert** [comment]
@cristianbica Sounds like it wasn't the case above. As I mentioned above, it's already implemented in the gem itself https://github.com/brandonhilkert/sucker_punch#perform-in.

**Comment by maclover7** [comment]
Closing in favor of #23284.

**Pull request closed without merging**
