### PR TITLE
 Run SQL only if attribute changed for update_attribute method

### PR DESCRIPTION
**Pull request by prathamesh-sonpatki**
- This is based on https://github.com/rails/rails/issues/18400 but
  tackling same issue with update_attribute method instead of update method.

### CODE REVIEW

**Comment by vipulnsward** [comment]
LGTM. I think we should add CHANGELOG

**Comment by prathamesh-sonpatki** [comment]
Right. Just wanted to get some eyes before adding changelog

**Comment by prathamesh-sonpatki** [comment]
@rafaelfranca What do you think

**Comment by spastorino** [comment]
Looks good, please add a CHANGELOG entry

**Comment by prathamesh-sonpatki** [comment]
@spastorino Done.

**Pull request merged**
