### PR TITLE
Add ParallelQuery module to support parallel query execution in Postg…

### PR DESCRIPTION
**Pull request by janarthanan-shanmugam**
### Description

This pull request introduces a new ParallelQuery module to the ActiveRecord library, specifically designed to enhance query performance for PostgreSQL databases by leveraging parallel execution capabilities.

### Motivation
Modern databases, including PostgreSQL, support parallel query execution to utilize multiple CPU cores for faster data retrieval. However, Rails' ActiveRecord does not natively configure these parallel settings, potentially missing out on significant performance improvements for complex queries. This module aims to bridge that gap by dynamically configuring PostgreSQL settings to enable and optimize parallel execution.
#### Why This Feature Is Important
**Performance Improvement:** Parallel queries can drastically reduce execution times for large and complex queries, especially those involving heavy computational operations or large datasets.
**Resource Utilization:** Makes better use of modern multi-core processors by distributing query execution across multiple CPU cores.
**Scalability:** Enhances the scalability of Rails applications by improving the database layer's efficiency, which is often a bottleneck in high-load scenarios.

#### Introduction of ParallelQuery Module:

A new module, ActiveRecord::ParallelQuery, is added. This module provides a parallel_query method that configures the PostgreSQL settings for parallel execution before executing the provided block of code.
Dynamic Configuration of PostgreSQL Settings:

The parallel_query method sets several PostgreSQL parameters to optimize parallel execution:
**max_parallel_workers_per_gather**: Sets the maximum number of workers that can be used for parallel execution.
**work_mem**: Increases the memory available for internal operations to avoid disk I/O.
**parallel_setup_cost** and **parallel_tuple_cost**: Lowers the costs to make parallel execution more attractive to the query planner.
**min_parallel_table_scan_size** and **min_parallel_index_scan_size**: Ensures even small scans are considered for parallel execution.
**Resetting Settings Post-Execution:**

After executing the query block, the method ensures that all PostgreSQL settings are reset to their original values to avoid unintended side effects on subsequent queries.

**Compatibility with Other Adapters:**

The module includes a conditional check to ensure that it only applies these settings to PostgreSQL adapters. For other adapters (e.g., MySQL, SQLite, SQL Server), the query block is executed without modification, there we can add the changes if in future those adapters supports this functionalities.

#### Detailed Code Changes
**Module Definition:**
Added lib/active_record/parallel_query.rb with the new ParallelQuery module.
Integration with ActiveRecord:
Included the ParallelQuery module in ActiveRecord::Base to make the parallel_query method available to all models.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by MatheusRich** [comment]
@janarthanan-shanmugam could you explain the differences between this and [`load_async`](https://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-load_async)?

**Comment by janarthanan-shanmugam** [comment]
> @janarthanan-shanmugam could you explain the differences between this and [`load_async`](https://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-load_async)?

@MatheusRich 
Please find the diff between the Load_async and Parallel execution.

**load_async:** will have a background thread and runs the query in background without affecting original thread.
but it does not speedup the query itself, only prevents blocking.

**parallel query:**  
Parallel query execution involves running different parts of a single query simultaneously across multiple CPU cores. 
The parallel execution divides the query into smaller sub-queries, processes them concurrently, and then combines the results.
it speeds up the query itself.

i have created a detailed documentation about this parallel query vs load async.
please refer below for more detailed explanation.

https://docs.google.com/document/d/1j3TmQ-WGN58FCIeyo7YfGP0aLEKHaAzi4cCEPAhOxVc/edit?usp=sharing

**Comment by p8** [comment]
@janarthanan-shanmugam Thanks for the PR!
Could you provide some benchmarks of the performance improvement?
Maybe I missing something but I'm not sure make calls to the database to update settings around a query would help with performance.
Also what would happen if another thread/process makes a query that shouldn't be parallel?
If the settings haven't been reset, would the query still use the parallel setttings?

**Comment by simi** [comment]
@MatheusRich This PRs seems to do something little different than I would expect by reading the title. It tries to convince PostgreSQL planner to use (prefer) parallel execution nodes by applying some specific configurations values, which can work for author's application and DB setup, but are not generic enough and for example in DB setup I do maintain it will actually lower the performance. Also I'm not sure how safe are those config queries when running with some connection pooling.

**Comment by MatheusRich** [comment]
> @MatheusRich This PRs seems to do something little different than I would expect by reading the title. 

@simi Yes, that confused me as well. TY for the clarification.

**Comment by janarthanan-shanmugam** [comment]
@p8 
please find the bench mark of the parallel execution vs non parallel execution.
image
By using parllel execution , the time taken for the quey has been reduced more than 55 % from (49ms to 21 ms)
script used for testing
image

2. There wont be any impact on the if multiple query runs and some uses parallel and other dont.
   Since these settings are applied using SQL SET commands, which only affect the current database connection.
   
   For example two queries were there, one uses parallel execution and other goes without parallel, the first query will use parallel execution and the other query will run independently as it uses default db config since it doesn't call parallel query method.
   
   **Session-Specific Settings: The SET commands modify settings only for the current session (connection). Other sessions (connections) in the database are not affected.**

**Comment by janarthanan-shanmugam** [comment]
> @MatheusRich This PRs seems to do something little different than I would expect by reading the title. It tries to convince PostgreSQL planner to use (prefer) parallel execution nodes by applying some specific configurations values, which can work for author's application and DB setup, but are not generic enough and for example in DB setup I do maintain it will actually lower the performance. Also I'm not sure how safe are those config queries when running with some connection pooling.

@simi @MatheusRich 

 The implementation is designed to ensure that the parallel execution settings apply only to the **specific query** executed within the **parallel_query block** and are r**eset immediately** after the query execution.

 The parallel query settings (max_parallel_workers_per_gather, work_mem, etc.) are applied only within the **context of the database session (connection)** used by the parallel_query method.

These settings are specific to the session and **do not affect other connections** in the pool.

The ensure block in the **parallel_query** method guarantees that the settings are reset to their defaults immediately after the query execution.

This **reset mechanism** ensures that any subsequent queries using the same connection will run with the default settings, **maintaining isolation** and preventing unintended side effects.

The parallel query settings applied within one connection do not impact other connections, ensuring that the connection pool configuration remains unaffected.

**The default values provided in the **parallel_query** method are chosen based on a combination of typical use cases, industry standards, and empirical performance observations. Please find how these  settings will work well on the  applications on the below standard documentation**:

https://docs.google.com/document/d/1aKaIJ-fols-YQj9uANCokBqCqfKvX_Bvux8VYTiVy8Y/edit?usp=sharing

Please let me know if there are any further questions or additional information needed.

**Comment by simi** [comment]
> > @MatheusRich This PRs seems to do something little different than I would expect by reading the title. It tries to convince PostgreSQL planner to use (prefer) parallel execution nodes by applying some specific configurations values, which can work for author's application and DB setup, but are not generic enough and for example in DB setup I do maintain it will actually lower the performance. Also I'm not sure how safe are those config queries when running with some connection pooling.
> 
> @simi @MatheusRich
> 
> The implementation is designed to ensure that the parallel execution settings apply only to the **specific query** executed within the **parallel_query block** and are r**eset immediately** after the query execution.
> 
> The parallel query settings (max_parallel_workers_per_gather, work_mem, etc.) are applied only within the **context of the database session (connection)** used by the parallel_query method.
> 
> These settings are specific to the session and **do not affect other connections** in the pool.

> The ensure block in the **parallel_query** method guarantees that the settings are reset to their defaults immediately after the query execution.
> 
> This **reset mechanism** ensures that any subsequent queries using the same connection will run with the default settings, **maintaining isolation** and preventing unintended side effects.
> 
> The parallel query settings applied within one connection do not impact other connections, ensuring that the connection pool configuration remains unaffected.

I don't agree on this. There are various problems in here. Values are "reset" to default values, no to previous ones. And it also depends on pooling used, for example (per my understanding) with pgbouncer statement `pool_mode` this can leak outside.

> **The default values provided in the parallel_query method are chosen based on a combination of typical use cases, industry standards, and empirical performance observations. Please find how these settings will work well on the applications on the below standard documentation**:
> 
> https://docs.google.com/document/d/1aKaIJ-fols-YQj9uANCokBqCqfKvX_Bvux8VYTiVy8Y/edit?usp=sharing
> 
> Please let me know if there are any further questions or additional information needed.

There is nothing like typical use case and industry standard for PostgreSQL configuration and I don't expect `ActiveRecord` to tweak mentioned PostgreSQL settings. IMHO the only "industry standard" is to monitor, understand, tweak, maintain and configure you database cluster to provide the best performance.

**Comment by janarthanan-shanmugam** [comment]
> > > @MatheusRich This PRs seems to do something little different than I would expect by reading the title. It tries to convince PostgreSQL planner to use (prefer) parallel execution nodes by applying some specific configurations values, which can work for author's application and DB setup, but are not generic enough and for example in DB setup I do maintain it will actually lower the performance. Also I'm not sure how safe are those config queries when running with some connection pooling.
> > 
> > 
> > @simi @MatheusRich
> > The implementation is designed to ensure that the parallel execution settings apply only to the **specific query** executed within the **parallel_query block** and are r**eset immediately** after the query execution.
> > The parallel query settings (max_parallel_workers_per_gather, work_mem, etc.) are applied only within the **context of the database session (connection)** used by the parallel_query method.
> > These settings are specific to the session and **do not affect other connections** in the pool.
> 
> > The ensure block in the **parallel_query** method guarantees that the settings are reset to their defaults immediately after the query execution.
> > This **reset mechanism** ensures that any subsequent queries using the same connection will run with the default settings, **maintaining isolation** and preventing unintended side effects.
> > The parallel query settings applied within one connection do not impact other connections, ensuring that the connection pool configuration remains unaffected.
> 
> I don't agree on this. There are various problems in here. Values are "reset" to default values, no to previous ones. And it also depends on pooling used, for example (per my understanding) with pgbouncer statement `pool_mode` this can leak outside.
> 
> > **The default values provided in the parallel_query method are chosen based on a combination of typical use cases, industry standards, and empirical performance observations. Please find how these settings will work well on the applications on the below standard documentation**:
> > https://docs.google.com/document/d/1aKaIJ-fols-YQj9uANCokBqCqfKvX_Bvux8VYTiVy8Y/edit?usp=sharing
> > Please let me know if there are any further questions or additional information needed.
> 
> There is nothing like typical use case and industry standard for PostgreSQL configuration and I don't expect `ActiveRecord` to tweak mentioned PostgreSQL settings. IMHO the only "industry standard" is to monitor, understand, tweak, maintain and configure you database cluster to provide the best performance.

Thank you for the detailed feedback. I understand the importance of maintaining database settings integrity and the potential issues related to connection pooling. can we address these concern by below strategy?

1. Handling of PostgreSQL Settings
Restoring Previous Values:

we can captures the current settings before making any changes and restores them after execution. 
This ensures that the values are reset to their previous states, not just default values.
**Example:**

```
class ApplicationRecord < ActiveRecord::Base
  def self.parallel_query(settings: {}, &block)
    default_settings = {
      "max_parallel_workers_per_gather" => 4,
      "work_mem" => '64MB',
      "parallel_setup_cost" => 100,
      "parallel_tuple_cost" => 0.01,
      "min_parallel_table_scan_size" => 0,
      "min_parallel_index_scan_size" => 0
    }
    settings = default_settings.merge(settings)

    original_settings = {}
    settings.keys.each do |key|
      original_settings[key] = connection.select_value("SHOW #{key}")
    end

    settings.each do |key, value|
      connection.execute("SET #{key} = '#{value}'")
    end

    result = yield

  ensure
    original_settings.each do |key, value|
      connection.execute("SET #{key} = '#{value}'")
    end
    result
  end
end
```

2. Thanks @simi for the feedback over  database configuration best practices. 
  Default settings are provided to offer a starting point, but also can we allow the users to  adjust these based on their own database performance monitoring and tuning practices. This ensures that the method can be adapted to a variety of use cases without enforcing a one-size-fits-all approach? Your thoughts on this?

**Comment by rafaelfranca** [comment]
Thank you for the pull request but we don't have any interest in a first class API for a postgresql specific feature. It shouldn't be hard to implement this in your own application or in a gem if you want to share with the community.

**Comment by andyatkinson** [comment]
Hi [janarthanan-shanmugam](https://github.com/janarthanan-shanmugam). I'd recommend considering writing this up a blog post discussing how you changed Postgres parallel query execution parameters to improve performance for your Active Record workload.

You might get feedback on the specific values, params, concerns like what was raised earlier about compatibility with a connection pooler.

From there, you could determine next steps, whether it makes sense to find equivalent parameters in the other supported DB systems or not, and whether to try and provide modified parameter values in a generic way.

I do think education for these parameters, and how they're targeting different aspects than async query execution, is helpful. Thanks!

**Pull request closed without merging**
