### PR TITLE
Pick up fixtures ending in .yml.erb

### PR DESCRIPTION
**Pull request by lukel97**
### Summary

This changes Active Record test fixtures to pick up any fixtures ending in
`.yml.erb`. It both a `.yml.erb` file and `.yml` file exist, the `.yml.erb`
will take precendece.

### Other Information

Addresses https://github.com/rails/rails/issues/17436

### CODE REVIEW

**Comment by p8** [comment]
Hi @bubba, thanks for the PR.
Any reason you want to support fixtures ending in .`yml.erb`?
The current fixtures already support erb and this PR adds more complexity.

**Comment by bubba** [comment]
Mainly for consistency and better editor support.
The current convention in `app/views` is that template `html`/`js`/`xml` files have the `erb` prefix in their extension, and so I was surprised whenever I added a fixture file ending in `.yml.erb` that wasn't picked up.
The second being that my editor (Vim) didn't apply correct syntax highlighting to the erb syntax unless the my fixture file had the `.yml.erb` extension.

**Comment by p8** [comment]
I think we only support nested extensions for app/views.
There are a lot of other `YAML` files like `config/database.yml`, `config/cable.yml` that also support inline erb.

**Comment by bubba** [comment]
> I think we only support nested extensions for app/views.
There are a lot of other YAML files like config/database.yml, config/cable.yml that also support inline erb.

I was wondering about the latter as well, is ERB supported on all arbitrary configuration files or just those specific ones?
Either way those are fair enough points, I'm happy to close this PR and leave it if it needs more discussion

**Comment by p8** [comment]
ActiveSupport::ConfigurationFile supports erb.
https://github.com/rails/rails/blob/c453a5fa88e89bc0bc8efde3b397f2464712bb49/activesupport/lib/active_support/configuration_file.rb
It's used in different places to load configs: https://github.com/rails/rails/search?q=ConfigurationFile.

You can also try getting some feedback/discussion in the Rails-Core forum: https://discuss.rubyonrails.org/c/rubyonrails-core/5

**Comment by bubba** [comment]
[Discourse post is here](https://discuss.rubyonrails.org/c/rubyonrails-core/5)

**Pull request closed without merging**
