### PR TITLE
Fix NumericalityValidator fails on equal decimal to decimal comparisons #26085

### LINKED ISSUE #26085: NumericalityValidator fails on equal decimal to decimal comparisons
### Steps to reproduce

Migration:

``` ruby
create_table :number_ranges do |t|
  t.decimal :low
  t.decimal :high
end
```

Model:

``` ruby
class NumberRange < ApplicationRecord
  validates :high, numericality: { greater_than_or_equal_to: :low }
end
```

Spec:

``` ruby
describe NumberRange do
  describe "#high :greater_than_or_equal_to :low validation" do
    it "is valid with equal high and low" do
      # This fails because the validator compares Float('65.6') to BigDecimal('65.6')
      expect(FinalCost.new(low: '65.6', high: '65.6').to be_valid
    end
  end
end
```
### Expected behavior

When validating numericality's `greater_than_or_equal_to` on a decimal column against the value of another decimal column, two equal raw values ought to validate correctly.
### Actual behavior

`NumericalityValidator#parse_raw_value_as_a_number` always parses with `Kernel.Float(raw_value)`, so the validated value is a float, while the comparison value is a `BigDecimal`, and so, due to precision differences, equal numbers will fail validation.
### System configuration

**Rails version**:
`5.0.0` (verified on current master as well)

**Ruby version**:
`2.3.1p112`

### PR DESCRIPTION
**Pull request by moeabdol**
Fix #26085

### Summary

NumericalityValidator#parse_raw_value_as_a_number always parses with Kernel.Float(raw_value), so the validated value is a float, while the comparison value is a BigDecimal, and so, due to precision differences, equal numbers will fail validation. This PR fixes this #26085  .

### Other Information

Test file provided by @maclover7 [here](https://gist.github.com/maclover7/f2f118e70d1191a722c7f8669a93c887) was used and is included as part of this PR.

### CODE REVIEW

**Comment by Sayanc93** [comment]
@moeabdol Hey you are supposed to add tests in here I think
https://github.com/rails/rails/blob/master/activemodel/test/cases/validations/numericality_validation_test.rb

**Comment by moeabdol** [comment]
Thank you @Sayanc93 I added the test file under `validations/numericality_validation_test.rb` as you mentioned

**Comment by matthewd** [comment]
Looks like it's currently failing the test recently added by https://github.com/rails/rails/pull/29249.

**Comment by kamipo** [comment]
Closing in favor of #32852.

**Pull request closed without merging**
