### PR TITLE
PERF: 45% faster attributes for readonly usage

### PR DESCRIPTION
**Pull request by kamipo**
Instantiating attributes hash from raw database values is one of the
slower part of attributes.

Why that is necessary is to detect mutations. In other words, that isn't
necessary until mutations are happened.

`LazyAttributeHash` which was introduced at 0f29c21 is to instantiate
attribute lazily until first accessing the attribute (i.e.
`Model.find(1)` isn't slow yet, but `Model.find(1).attr_name` is still
slow).

This introduces `LazyAttributeSet` to instantiate attribute more lazily,
it doesn't instantiate attribute until first assigning/dirty checking
the attribute (i.e. `Model.find(1).attr_name` is no longer slow).

It makes attributes access about 35% faster for readonly (non-mutation)
usage.

<details>
<summary>https://gist.github.com/kamipo/4002c96a02859d8fe6503e26d7be4ad8</summary>

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "sqlite3"
  gem "benchmark-ips"
  gem "benchmark-memory"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")

ActiveRecord::Schema.define do
  create_table :models, force: true do |t|
    t.string :col1
    t.string :col2
    t.string :col3
    t.string :col4
    t.string :col5
    t.string :col6
    t.string :col7
    t.string :col8
    t.string :col9
  end
end

ActiveRecord::Base.immutable_strings_by_default = true

class Model < ActiveRecord::Base; end

ENV["RECORDS"] ||= "10000"

Model.transaction do
  ENV["RECORDS"].to_i.times do |i|
    Model.create!(
      col1: "hello, world!",
      col2: "hello, world!",
      col3: "hello, world!",
      col4: "hello, world!",
      col5: "hello, world!",
      col6: "hello, world!",
      col7: "hello, world!",
      col8: "hello, world!",
      col9: "hello, world!"
    )
  end
end

benchmark = -> x {
  x.report("attribute access") do
    records = Model.find_by_sql("SELECT * FROM models")
    records.each do |record|
      record.id
      record.col1
      record.col2
      record.col3
      record.col4
      record.col5
      record.col6
      record.col7
      record.col8
      record.col9
    end
  end
}

puts "IPS"
Benchmark.ips(&benchmark)

puts "MEMORY"
Benchmark.memory(&benchmark)
```
</details>

Before:

```
IPS
Warming up --------------------------------------
    attribute access     1.000  i/100ms
Calculating -------------------------------------
    attribute access      3.444  (± 0.0%) i/s -     18.000  in   5.259030s
MEMORY
Calculating -------------------------------------
    attribute access    38.902M memsize (     0.000  retained)
                       350.044k objects (     0.000  retained)
                        15.000  strings (     0.000  retained)
```

After (with `immutable_strings_by_default = true`):

```
IPS
Warming up --------------------------------------
    attribute access     1.000  i/100ms
Calculating -------------------------------------
    attribute access      4.652  (±21.5%) i/s -     23.000  in   5.034853s
MEMORY
Calculating -------------------------------------
    attribute access    27.782M memsize (     0.000  retained)
                       170.044k objects (     0.000  retained)
                        15.000  strings (     0.000  retained)
```

* PERF: Avoid extra delegation to `LazyAttributeHash`

The extra delegation to `LazyAttributeHash` has non-negligible overhead.

Avoiding that delegation makes attributes access about 45% faster for
readonly (non-mutation) usage.

After (with `immutable_strings_by_default = true`):

```
IPS
Warming up --------------------------------------
    attribute access     1.000  i/100ms
Calculating -------------------------------------
    attribute access      5.066  (±19.7%) i/s -     25.000  in   5.024650s
MEMORY
Calculating -------------------------------------
    attribute access    27.382M memsize (     0.000  retained)
                       160.044k objects (     0.000  retained)
                        15.000  strings (     0.000  retained)
```

### CODE REVIEW

**Comment by rafaelfranca** [comment]
This also changes the result of `Marshal.dump` and made the application not being able to read cache results in a worker that don't have the new constant yet.

**Comment by kamipo** [comment]
Hmm... I'd intentionally left `LazyAttributeHash` which is not used in new version to keep `Marshal.load` backward compatibility.

I've prepared a PR #39769 to mitigate breaking `Marshal.load` forward compatibility, but I'm not sure how much we should be aware of `Mashal.load` forward compatibility.
Especially if we should keep perfectly forward compatibility, we almost have no chance to improve object layout (includes ivar usage).

As another point of view, we sometimes decided to choose deployment order sensitive change (required worker side deployment first).

For example https://github.com/rails/rails/pull/38267#discussion_r368732772.
Unlike #38260, #38267 is required to deploy to a worker side first if using Ruby 2.7, otherwise a worker cannot restore symbol keys correctly.

**Comment by ghiculescu** [comment]
With this change, `LazyAttributeHash` is not used anywhere in Rails anymore, and it's private since https://github.com/rails/rails/commit/3ecc5d30eb0901f4e3c4d3bca1957f633a6a695b

Should we look at deprecating/removing it?

**Comment by kamipo** [comment]
`LazyAttributeHash` is intentionally left in Rails 6.1 for cache rotation safely.
I'll remove it before the next release.

**Pull request merged**
