### PR TITLE
Use current_database + current_schema for advisory_lock_id

### PR DESCRIPTION
**Pull request by marksiemers**
Migrator should use both database and schema when creating
a lock so concurrent migrations can be executed across
schemas. This is most obviously useful for the 'apartment'
gem where running identical migrations across many schemas
is common.

See: #31627 and https://github.com/influitive/apartment/issues/506

### Summary
This unblocks the ability to run `parallel_migration_threads` using the
apartment gem.

An example where this is useful:
A migration takes 10 seconds to execute
The database has 1800 schemas
The migration now takes 5 hours (18,000 seconds)

This makes deploying from any reasonable CI impossible and requires
connecting to the database from a local laptop and running the migrations
from a local codebase - then checking back 5 hours later to see if it finished.
Then you can deploy.

### CODE REVIEW

**Comment by marksiemers** [comment]
The issue this addresses was closed for being "stale" (not for being resolved or being a non-issue) - https://github.com/rails/rails/issues/31627

**Comment by tgxworld** [comment]
> parallel_migration_threads using the
apartment gem.

Is this running multiple migrations using threads? We’ve tried running migrations in parallel at Discourse recently and found out that migrations are not thread safe.

**Comment by marksiemers** [comment]
@tgxworld - It depends on the migrations. Are you using a "tenant" system like apartment? Where the same schema definition exists across N number of schemas?

As long as there aren't two threads trying to make changes to the same schema, what would cause the thread safety issue?

The apartment readme: https://github.com/influitive/apartment#parallel-migrations
> Parallel Migrations
Apartment supports parallelizing migrations into multiple threads when you have a large number of tenants. By default, parallel migrations is turned off. You can enable this by setting parallel_migration_threads to the number of threads you want to use in your initializer.

> Keep in mind that because migrations are going to access the database, the number of threads indicated here should be less than the pool size that Rails will use to connect to your database.

The relevant code is here: https://github.com/influitive/apartment/blob/5fd9391988ee2e66417e3bdbeca4d82d38cdbdd1/lib/tasks/apartment.rake#L123

**Comment by tgxworld** [comment]
> what would cause the thread safety issue?

I wrote about this previosuly in https://discuss.rubyonrails.org/t/should-rails-migration-be-thread-safe/76020/5 but the gist of it is that there are still spots in Rails migration that are not thread safe. For example, 

https://github.com/rails/rails/blob/fb852668dff2786a4cfb30ad923830da9eed2476/activerecord/lib/active_record/migration.rb#L605-L606

If you're running migrations in different threads, one thread can `disable_ddl_transactions` while another thread is running. 

With all that being said, I don't see any major downsides to this change and it is non-breaking. @eileencodes I think this change is fine but was wondering what you think about it. 

@marksiemers Alternatively, you can still get `parallel_migration_threads` working by disabling advisory locks in the mean time.

**Comment by eileencodes** [comment]
Seems fine to me except for one thing. I'm wondering if it makes more sense to define this method in the postgres adapter so we don't need `respond_to`. That's generally how we handle different databases. The implementation here implies that other dbs could support this but I don't think that's the case.

**Comment by marksiemers** [comment]
@tgxworld - Thanks for that advice. It is rare, but more than 0 times we've been saved by the advisory lock. I suppose we could disable it when we know a migration will be particularly long.

@eileencodes - Agreed, I don't think mysql will ever need to support it (the db doesn't even have schemas, I don't think).

I am unsure where to put it. Looking here: https://github.com/rails/rails/tree/master/activerecord/lib/active_record/connection_adapters/postgresql

I don't see an obvious file/object. Any suggestions?

**Comment by tgxworld** [comment]
@marksiemers You can follow something like how it is done for advisory locks

https://github.com/rails/rails/blob/f624ed09abba4a0bae64eb699c9fc2e3f9bdc2dc/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb#L429-L431

In each adapter, you will then override the method depending on whether the adapter supports schemas or not.

**Pull request closed without merging**
