### PR TITLE
Sam/reenable automatic inference of inverse of for autosave associations

### PR DESCRIPTION
**Pull request by samsondav**
See: https://github.com/rails/rails/pull/23197#event-843715046

### CODE REVIEW

**Comment by samphilipd** [comment]
cc @sgrif

**Comment by rafaelfranca** [comment]
This PR broke a lot of test in my application. I still didn't investigated yet why but this is a sign that it is not safe to applied to a stable branch so I'm reverting.

**Comment by rafaelfranca** [comment]
The problem is a `has_one` association with `autosave: true` is not inserting the record in the database because the foreign key is NULL in the belongs to side. But I also found this problem in a has_many association without `autosave: true`. The foreign key is being set to true.

**Comment by rafaelfranca** [comment]
Reverted in f5957d0

**Comment by sgrif** [comment]
Have you checked master as well?

**Comment by rafaelfranca** [comment]
I can't point Shopify to master yet :(

**Comment by sgrif** [comment]
Ok. I'll see if I can isolate and investigate further tomorrow

**Pull request merged**
