### PR TITLE
Remove version header from railties CHANGELOG.md

### PR DESCRIPTION
**Pull request by maclover7**
[ci skip]

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Weird. We should not have any headers now. Do we have? The headers are only added when doing the release to avoid conflicts.

**Comment by maclover7** [comment]
Railties has one -- https://github.com/rails/rails/blob/master/railties/CHANGELOG.md#rails-510alpha 😬

**Comment by maclover7** [comment]
If the proper thing is for CHANGELOGs to not have them, I can amend my PR to remove that then. 😄

**Comment by rafaelfranca** [comment]
> If the proper thing is for CHANGELOGs to not have them, I can amend my PR to remove that then.

👍

**Comment by rafaelfranca** [comment]
David added that, maybe because he doesn't know about when the headers are added.

**Comment by maclover7** [comment]
@rafaelfranca updated 👍

**Comment by maclover7** [comment]
👍

**Pull request merged**
