### PR TITLE
Convert "static" strings into symbols

### PR DESCRIPTION
**Pull request by deepj**
Solving  a notice mentioned here https://github.com/rails/rails/pull/20241#issuecomment-104216203

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Thank you for the pull request but we don't accept allocation reduction unless it is proven that the place is a hot stop and it will make a lot of difference.

**Comment by deepj** [comment]
On the other hand it keeps consistence with code style...

**Comment by rafaelfranca** [comment]
Yeah, but this fall at cosmetic change category.

**Comment by thedarkone** [comment]
@deepj your PRs (#20246 or #20241) are being rejected because they appear to be "cosmetic" in nature.

This does not mean that the changes of `send('foo')` into `send(:foo)` are without merit! What you need to do:
 * justify that the code you want changed is indeed a hotspot,
 * provide benchmarks showing that the change results in a measurable perf benefit.

**Pull request closed without merging**
