### PR TITLE
Revert "Set environment even when no migration runs"

### PR DESCRIPTION
**Pull request by sgrif**

### CODE REVIEW

**Comment by schneems** [comment]
ACK. Do you know what the failure was?

**Comment by sgrif** [comment]
MigrationTest#test_internal_metadata_stores_environment [test/cases/migration_test.rb:383]:
Expected: "test"
  Actual: "foofoo"

https://travis-ci.org/rails/rails/builds/102442263

**Comment by schneems** [comment]
Thanks. I'm able to reproduce with some difficulty

```
$ while bundle exec rake test:sqlite3 TEST=test/cases/migration_test.rb; do :; done
```

**Comment by sgrif** [comment]
Yup, appears to be intermittent.

**Pull request merged**
