### PR TITLE
Bump `mail` version to 2.6.0

### PR DESCRIPTION
**Pull request by bobf**
Security update: http://www.openwall.com/lists/oss-security/2015/12/11/3

### CODE REVIEW

**Comment by mattolson** [comment]
:+1: for this. Any ideas why tests are failing?

**Comment by jeremy** [comment]
Can't do a major version bump of a dep on a stable branch. The best route is a patch-level release of the mail library.

**Comment by mattolson** [comment]
Opened an issue with the mail gem. Not sure how difficult it will be to backport the fix.

https://github.com/mikel/mail/issues/944

**Comment by bobf** [comment]
Had a failing test before I made any changes, assumed it was something up with my platform (was locale-related). Not sure about the others. Thanks for taking action on this; am running a forked Rails at the moment. : )

**Pull request closed without merging**
