### PR TITLE
Make README's welcome section a bit easier to read

### PR DESCRIPTION
**Pull request by TomK32**
I noticed the README file is actually hard to read because of all the, well, README links to the major modules. Instead I linked the modules directly and also highlighted the M, C and V to help the reader jump through the text quicker.

### CODE REVIEW

**Comment by TomK32** [comment]
Adding to this, I just noticed that [railties/RDOC_MAIN.rdoc](https://github.com/rails/rails/blob/master/railties/RDOC_MAIN.rdoc) is the main file for [the api website](http://api.rubyonrails.org/) but is lagging behind the `README.me`. Maybe something to be fixed?

**Comment by rafaelfranca** [comment]
They should be similar, talking about the same components but should not be the same since they are for two different audiences. Could work on getting them similar?

**Comment by TomK32** [comment]
To stick to the pull request: All those README links in the current version are visually confusing and my improvements fix that.

@rafaelfranca you're right about the audiences being two different ones, README.md has an audience working ON Rails while the api website's audience is working WITH Rails. I'll start a separate pull request once this one is accepted.

**Comment by TomK32** [comment]
@senny you agree with @maclover7 about more work needed on this?

**Pull request closed without merging**
