### PR TITLE
Replace problematic `ActiveStorage::Current` for a service-level config

### PR DESCRIPTION
**Pull request by santib**
### Motivation / Background

This Pull Request has been created because there have always been lots of complains about `ActiveStorage::Current` not being set, especially in tests. While there are always suggestions like:
1. set it in the test setup
2. use Rails' `url_for` instead of service urls

there is [another case](https://github.com/rails/rails/issues/40855#issuecomment-1711683168) where the setting is being cleared because the way `ActiveSupport::CurrentAttributes` work.

### Detail

This Pull Request changes `ActiveStorage::Current` (thread-level config for the DiskService) for configs at the service level (`config/storage.yml` or similar).

Q: Is there any reason why it needs to be a thread-level config?

### Additional information

If the solution is accepted I can add more tests, a CHANGELOG entry, and we'll probably want to deprecate the old behavior rather than replacing it just like I did.

### Checklist

Before submitting the PR make sure the following are checked:

* [X] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [ ] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [ ] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Review by rafaelfranca — CHANGES_REQUESTED** [review]
This now isn't reading the information from the request anymore and people need to manually configure. That isn't the experience we want.

**Comment by santib** [comment]
What if we just go with returning a path (instead of full url) and that way not having to configure protocol/host/port anywhere?

**Comment by natematykiewicz** [comment]
> What if we just go with returning a path (instead of full url) and that way not having to configure protocol/host/port anywhere?

That only works for requests in a browser, while visiting from the current domain. API responses that are to a 3rd party or native app need a full URL, not just a path.

Honestly, I think the proper solution to this problem (and a bunch of others) is this issue:
https://github.com/rails/rails/issues/39566

Each Rails gem currently needs the host set independently. It's incredibly confusing, tedious, and easy to miss one of them.
`Rails.application.url` would make everything much much simpler.

**Comment by santib** [comment]
> > What if we just go with returning a path (instead of full url) and that way not having to configure protocol/host/port anywhere?
> 
> That only works for requests in a browser, while visiting from the current domain. API responses that are to a 3rd party or native app need a full URL, not just a path.
> 
> Honestly, I think the proper solution to this problem (and a bunch of others) is this issue: #39566
> 
> Each Rails gem currently needs the host set independently. It's incredibly confusing, tedious, and easy to miss one of them. `Rails.application.url` would make everything much much simpler.

100% agree with you that that issue/PR is the final solution for this and other problems. I hope it makes it for Rails 8 🙏 Fortunately, https://github.com/rails/rails/pull/42520 is looking solid, I guess it's just a matter of time.

**Pull request closed without merging**
