### PR TITLE
Use delete instead of gsub

### PR DESCRIPTION
**Pull request by yhirano55**
### Summary

```
require 'benchmark'

TIMES = 1_000_000

s = "oh\nmy\nstring\n"

Benchmark.bmbm do |x|
  x.report("delete") do
    TIMES.times { s.delete("\n") }
  end

  x.report("gsub with string") do
    TIMES.times { s.gsub("\n", "") }
  end
end

Rehearsal ----------------------------------------------------
delete             0.465423   0.001219   0.466642 (  0.468006)
gsub with string   1.293566   0.002449   1.296015 (  1.298087)
------------------------------------------- total: 1.762657sec

                       user     system      total        real
delete             0.459217   0.002126   0.461343 (  0.463790)
gsub with string   1.283116   0.002070   1.285186 (  1.287792)
```

### CODE REVIEW

**Comment by kamipo** [comment]
We don't drive performance improvements in the framework using micro benchmarks. See https://github.com/rails/rails/pull/30962#issuecomment-339768047.

**Comment by yhirano55** [comment]
I understood. Thanks.

**Comment by bdewater** [comment]
The real fix would be to use `Base64.strict_encode64` 😄

**Comment by yhirano55** [comment]
@bdewater Good point. Please open the pull request.

**Comment by bdewater** [comment]
@yhirano55 done!

**Pull request closed without merging**
