### PR TITLE
Add Namibia to Timezones.

### PR DESCRIPTION
**Pull request by manfrin**
https://github.com/rails/rails/issues/21285

### CODE REVIEW

**Comment by thomasfedb** [comment]
Looks like a straightforward change. CI failure appears to be unrelated.

**Comment by maclover7** [comment]
Please rebase - there were CI failures on master yesterday.

**Comment by vipulnsward** [comment]
AFAIK, adding new timezones has been frozen. cc @pixeltrix

**Comment by matthewd** [comment]
It looks like the correct name would be Windhoek: apart from the major regional TZs, I believe the only departures from the "capital city" rule are islands. (But yes, per https://github.com/rails/rails/issues/10276, we're reluctant to keep maintaining this list.)

**Comment by rafaelfranca** [comment]
https://github.com/rails/rails/issues/22440#issuecomment-178095649

**Pull request closed without merging**
