### PR TITLE
Memoize RouteSet#url_helpers to not generate unnecessary modules.

### PR DESCRIPTION
**Pull request by jcoleman**
Also seems to solve issues with accessing engine routesets in a multithreaded environment that occur because of https://bugs.ruby-lang.org/issues/10871

### CODE REVIEW

**Comment by eileencodes** [comment]
Thanks for the PR! Almost exactly a year ago I made this same change and we reverted it for a myriad of reasons. I had done this as part of speeding up integration tests and we undid it because we found another better way to prevent multiple modules from being re-resolved in integration tests.

Because we've already reverted this change once I'm going to close. Maybe @tenderlove will remember why memoizing was a bad idea here?

**Comment by tenderlove** [comment]
Mainly because we don't need to add the complexity for the speed.  In fact doing the *check-then-set* operation will be slower than what we have today.  This patch is a workaround for a bug in Ruby.  The bug should be fixed in Ruby, so I don't think we need this.

**Comment by jcoleman** [comment]
@tenderlove The bug in Ruby is only fixed (fully) in 2.3, and given the number of people still on 2.2 I thought we should patch a workaround.

If people are calling `Rails.application.routes.url_helpers` to generate routes outside of views, I don't see how the existing code path could be faster than the memoized version unless I'm missing something.

**Comment by tenderlove** [comment]
@jcoleman you can do your own memoization, if required.

**Comment by jcoleman** [comment]
@tenderlove When people need to use URL helpers outside of views what's the recommended thing to use?

**Comment by tenderlove** [comment]
It's fine to use that method if you want, just mix it in to a class and use an instance of that class (or just as class methods on the class).  Since you only mixed it in once, you'll get the speed benefit.

Adding memoization to this method couples the method's implementation to the cache.  If we decide to change the routing tables at runtime (for example if the routes.rb file gets changed and we want to update route helpers in development) then we have to add cache expiration.

**Pull request closed without merging**
