### PR TITLE
Prevent breaking lines in guides for `pre`, `tt` and `code` tags

### PR DESCRIPTION
**Pull request by bogdanvlviv**
Before:

After:

### CODE REVIEW

**Comment by fxn** [comment]
@joefiorini you introduced this CSS rule back in #6475. Would like to give some feedback on this patch?

**Comment by rafaelfranca** [comment]
Horizontal scroll in mobile view is really bad UX. You may want to scroll to the left and it is not soon that you will notice you have changed the page to the previous page.

Because of this I'm 👎  for this change but I'm not a UX expert.

**Comment by vipulnsward** [comment]
Same here. Its harder to read while scrolling horizontally and not a natural interaction.

**Comment by fxn** [comment]
Agree, I was wondering if we could make this responsive. You know, scroll bar in desktop, and word wrap in mobile.

But not an UX guy either. If @joefiorini can give us feedback in that sense, great. Otherwise we may apply our best judgement.

**Comment by bogdanvlviv** [comment]
I've analyzed docs of other libs (for example docker's docs https://docs.docker.com/get-started/part2/#requirementstxt) and saw that horizontal scrolling is more acceptable, but I'm not UX expert too, so feel free to close this PR if it doesn't fit :smile:

**Comment by bogdanvlviv** [comment]
Horizontal scrrolliing of a table reminded me about these changes. Let's make decision about this PR.
LOGO

**Pull request closed without merging**
