### PR TITLE
Don't double-encode nested `field_id` and `field_name` index

### LINKED ISSUE #45483: ActionView::FormBuilder#field_name returns incorrect field name for deeply-nested associations
`field_name` is adding an extra index parameter, the extra `[0]` in `parent[children_attributes][0][0][grandchildren_attributes][]`

### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "sqlite3"
  gem 'rails'
  gem 'sprockets-rails'
end

require 'rails'
require "active_record/railtie"
require "action_controller/railtie"
require "action_view/railtie"
require "sprockets/railtie"
require "minitest/autorun"

class TestApp < Rails::Application; end

Rails.application.routes.draw do
  resources :parents
end

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :parents, force: true do |t|
  end

  create_table :children, force: true do |t|
    t.integer :parent_id
  end

  create_table :grandchildren, force: true do |t|
    t.integer :child_id
  end
end

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

class Parent < ApplicationRecord
  has_many :children
  accepts_nested_attributes_for :children
end

class Child < ApplicationRecord
  belongs_to :parent
  has_many :grandchildren
  accepts_nested_attributes_for :grandchildren
end

class Grandchild < ApplicationRecord
  belongs_to :child
end


TEMPLATE = <<~ERB
<%= form_with model: parent do |f| %>
 <%= f.field_name :children_attributes, multiple: true %>
  <%= f.fields_for :children do |child_f| %>
     <%= child_f.field_name :grandchildren_attributes, multiple: true %>
  <% end %>
<% end %>
ERB

class ApplicationController < ActionController::Base
  include ActionDispatch::Routing::UrlFor
  include Rails.application.routes.url_helpers
end

class BugTest < Minitest::Test

  def setup
    @parent = Parent.new
    child = Child.new
    grandchild = Grandchild.new
    child.grandchildren << grandchild
    @parent.children << child
    @rendered = ApplicationController.renderer.render inline: TEMPLATE, locals: { parent: @parent }
  end

  def test_grandchildren_field_name
    assert_match('parent[children_attributes][0][grandchildren_attributes][]', @rendered)
  end
end

```

### Expected behavior
Don't add an extra index parameter (parent[children_attributes][0]~~[0]~~[grandchildren_attributes][])

### Actual behavior
An extra index parameter is added

### System configuration
**Rails version**: 7

**Ruby version**: 3

### PR DESCRIPTION
**Pull request by seanpdoyle**
### Motivation / Background

Closes https://github.com/rails/rails/issues/45483
Closes https://github.com/rails/rails/pull/45523

To quote #45483:

> `field_name` is adding an extra index parameter, the extra `[0]` in
> `parent[children_attributes][0][0][grandchildren_attributes][]`

### Detail

To resolve that issue, this commit reads its default `field_id` and `field_name` method's `index:` option directly from the `@options`. Prior to this commit, that value was read from the `@index` instance variable.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by l15n** [comment]
:wave: is this PR missing anything to be merged? Would love to have this included in a future update so that I can get ride of a workaround. https://github.com/rails/rails/issues/45483#issuecomment-1598778454

**Comment by amatsuda** [comment]
@seanpdoyle This looks good. Thank you for the fix! Could you update CHANGELOG?

**Comment by seanpdoyle** [comment]
@amatsuda thank you for the review. I've rebased, added a CHANGELOG entry, and re-pushed.

**Comment by amatsuda** [comment]
@seanpdoyle Thank you!

**Comment by l15n** [comment]
Thanks for following up!

**Comment by shanecav84** [comment]
@seanpdoyle Thanks!

**Pull request merged**
