### PR TITLE
fix(guides): Update AWDwR book link in Releasing Rails guide [ci skip]

### PR DESCRIPTION
**Pull request by KapilSachdev**
### Summary
Point to the latest edition for `Rails 6`.

### Other Information
The current link responds with 404.

### CODE REVIEW

**Comment by KapilSachdev** [comment]
The current guide makes the following statement about Sam Ruby tests:

>You can check the status of these tests here:
> https://intertwingly.net/projects/dashboard.html

These are sample output as per the [test suite](https://github.com/rubys/awdwr) Readme, but makes one wonder if Rails have stopped making Sam Ruby happy, or it doesn't want to be happy anymore.

Shouldn't the guide convey the same that these are the sample outputs from the test?

Also do we update the test information [here](https://intertwingly.net/projects/) as i'm unable to find `Rails 6` there, or its not rails maintainer's work.

**Review by composerinteralia — APPROVED** [review]
Thanks for the URL fix. That looks good to me.

As for whether we are still "making Sam Ruby happy", I am not sure whether the folks who release Rails are still doing that. Since this document is mainly for them, I would be tempted to leave the rest of this section as is for now and let them update it if needed.

The dashboard itself definitely looks out of date, but I do see signs in the code of supporting Rails 6. I saw you made some PRs over on that repo as well 👍 . It may be worth asking there about the out-of-date dashboard, if you haven't already. They link to it at the bottom of their README.

**Comment by KapilSachdev** [comment]
Thanks for the feedback.

I know that this PR might not had been a good place to ask (but i thought was better than creating a new issue), so I just wanted to confirm as to who manages it (rails or [rubys/awdwr](https://github.com/rubys/awdwr)) because in the Releasing Rails guide it sounds like whoever releases should make it "happy" and makes one think of the dashboard should be maintained by them as well.

I hope the "releasers" will take a look at it.

> It may be worth asking there about the out-of-date dashboard, if you haven't already. They link to it at the bottom of their README.

Sure, rubys/awdwr#23 was created for the purpose of clarification and to start a conversation for the same.

**Comment by KapilSachdev** [comment]
Cross-referencing rubys/awdwr#24 as well for outdated dashboard and rails 6 test reports.

**Pull request merged**
