### PR TITLE
fixed comment for example sql statement

### LINKED ISSUE #47903: An improvement for an example from Ruby On Rails API website
From [Ruby on Rails API](https://api.rubyonrails.org/classes/ActiveRecord/Calculations.html#method-i-ids) website, there is an example for Calculations Method: `ids` that might have a minor mistake in its inline comment (the sql statement) which not make fully sense.

```ruby
Person.joins(:companies).ids # SELECT people.id FROM people INNER JOIN companies ON companies.person_id = people.id
```

Perhaps more appropriate to have it like this:

```ruby
Person.joins(:companies).ids # SELECT people.id FROM people INNER JOIN companies ON companies.id = people.company_id
```

### PR DESCRIPTION
**Pull request by jetjodh**
### Motivation / Background

This Pull Request has been created because fixes #47903  

### Detail

This Pull Request changes example SQL statement to be more coherent to the user.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by vipulnsward** [comment]
The current example is correct- 

```
> User.joins(:devices).ids
=> User Pluck (3.5ms)  SELECT "users"."id" FROM "users" INNER JOIN "devices" ON "devices"."user_id" = "users"."id"
```

Did this produce a different response for you?

**Review by zzak — APPROVED** [review]

**Comment by zzak** [comment]
@vipulnsward Either is "correct", it depends on the association right? In this case saying "this person belongs to this company" is more natural than "this company belongs to this person", IMO. I guess the reference could be a table of CEOs!

**Comment by zzak** [comment]
I think here is another good example, ignoring the second join:

https://github.com/rails/rails/blob/385903754e1e51e55d87169b48edb6704d97f586/guides/source/active_record_querying.md?plain=1#L1346-L1354

**Comment by vipulnsward** [comment]
Sounds good, I generally go with the generated console output instead of what looks better, since many open PRs sometimes saying its wrong.

**Comment by zzak** [comment]
> Sounds good, I generally go with the generated console output instead of what looks better, since many open PRs sometimes saying its wrong.

In this case the output is generated from models we don't actually have access to the full schema though, right? So we're kind of making things up as we go.

**Pull request merged**
