### PR TITLE
PostgreSQL: Use async libpq API for all queries

### PR DESCRIPTION
**Pull request by larskanis**
`res=conn.async_exec(sql)` is basically a shortcut for:
```
   conn.get_last_result
   conn.send_query(sql)
   conn.block
   res=conn.get_last_result
```
In both cases the statement is sent to the server and the result is awaited by proper ruby C-functions (`rb_wait_for_single_fd`, `rb_thread_fd_select`).

In the contrary `res=conn.exec(sql)` internally calls libpq's `PQexec()`, which waits for the result by it's own select/poll loop. The same for `exec_prepared`.

The GVL is released in both cases, but using `conn.block` has two advantages:

1. `conn.block` can be aborted by signals (like Strg-C), while `conn.exec` blocks signal processing until the query is answered.
2. Ruby gets notified about IO blocked operations. It can therefore schedule GC while queries are running like in this proposal:    https://bugs.ruby-lang.org/issues/14723

The downside is, that calling 3 methods is obviously minimal slower than calling only one. However the overhead of ActiveRecord is too big, to measure any difference. Moreover `conn.block` runs in parallel to the execution of the statement by the PostgreSQL server, so that only `conn.get_last_result` counts as additional sequential call.

### CODE REVIEW

**Comment by funny-falcon** [comment]
Travis CI fails are not because of this patch.

**Comment by matthewd** [comment]
Will these leave the connection in a consistent state if one of the earlier methods raises an exception, so `get_last_result` doesn't get called? 

Seems like it might be nice for upstream to offer an `async_foo` for every `send_foo`, if you're not already considering it.. but as long as we have the logic right, I'm happy to take this change as is rather than force a dependency bump.

**Comment by jagnarong** [comment]
Good

**Comment by larskanis** [comment]
As discussed at [this pg PR](https://github.com/ged/ruby-pg/pull/21) we'll change pg.gem so that it makes use of the async API per default. The above changes are therefore no longer necessary, when pg-1.1.0 is released. However pg-1.1.0 introduces some deprecations, which are triggered by ActiveRecord, so that I'll open a PR (probably [something like this](https://github.com/rails/rails/compare/master...larskanis:pg-1.1) ) in the next weeks.

Thank you for discussing this issue!

**Pull request closed without merging**
