### PR TITLE
Mention Shakapacker for the updated Webpacker.

### PR DESCRIPTION
**Pull request by justin808**
### Summary

Doc update for mentioning Shakapacker for the updated Webpacker.

### CODE REVIEW

**Comment by matthewd** [comment]
This feels like quite a caveat to put into the opening fine-print... do you think it would make sense for shakapacker to adopt this guide?

(And then I'm imagining we might hollow this out to just "webpacker is retired; shakapacker exists; there's a guide for using it _over here_")

**Comment by justin808** [comment]
Hi @matthewd, Sure. I'd be happy to adopt it in https://github.com/shakacode/shakapacker/tree/master/docs.

Right now, having this document here is surely adding to the confusion.

@tomdracz thoughts? Any chance that you can give me a hand with this?

@matthewd, BTW, @rafaelfranca is working on getting me:

> Can I get 2 new labels to organize the PRs: 'shakapacker merged' and 'shakapacker pending merge' ?

If you can get me those labels, I'll go through all the recently closed issues and PRs and ensure that they got transferred over to Shakapacker.

I've also updated the comparison to jsbundling-rails: https://github.com/rails/jsbundling-rails/pull/79 and that's pending review.

So what's the next step? Maybe merge this one right now? Or I can make a new PR with the document moved?

**Comment by tomdracz** [comment]
@justin808 Agree that we can adapt this in shakapacker repo.

Doc is definitely confusing, with the support dropped it is probably best to just leave retirement message and link to other options here or remove this completely.

**Comment by justin808** [comment]
@tomdracz What's the next step?

**Comment by skipkayhil** [comment]
I'm going to close since the Webpacker guide was removed from `main` in a46f4c28c1cf2c9ffec46df05e7b77ae5bf85faa.

Thank you for the PR

**Pull request closed without merging**
