### PR TITLE
Able to add Symbol parameter(alias column name) with where clause

### PR DESCRIPTION
**Pull request by amagasu**
Hi!, Everyone.
this is my first PR. please review.
I want to add the Symbol parameter to the Where function and use the Where function with a column alias.

If legacy column names did not be created  Rails's naming rule, you may wish to use only alias.
We are developing  with legacy tables that could not be created according to Rails  naming rules.

Legacy Table
```
CREATE TABLE TArticle (
  taId int,
  taTitle varchar(40),
  taContent varchar(100),
  taCreated date time,
)
```
The column names of all the tables are defined as aliases.
Rails Model
```
class Legacy::Article < ApplicationRecord
  self.table_name = 'TArticle'
  self.primary_key = 'taId'

  alias_attribute :title, :taTitle
  alias_attribute :content, :taContent
  alias_attribute :published_at, :taCreated
end
```

I can select data with using origin column name
`Legacy::Article.where('taCreated> ?', 10.days.ago)`

But I can’t select data with using alias column name. 
I want to use alias column name.

I edited `where_clause_factory.rb` 
If you  just write an alias ​column ​name  in the first parameter of the where function.
please review and merge.

After change.
```
Legacy::Article.where(:published_at, ’ > ? ', 10.days.ago)
```
SQL
```
SELECT [TArticle].* FROM [TArticle] WHERE  (taCreated > '07-04-2019 19:40:25.29’);
```

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Does `Legacy::Article.where(published_at: 10.days.ago)` work already?

I'm afraid of adding a new special syntax in `where` just for a few operators like `>`.

**Comment by amagasu** [comment]
Does`Legacy::Article.where('taCreated> ?', 10.days.ago)` work already.
but I want to use alias name.

**Comment by rafaelfranca** [comment]
Yeah, I get it. But like I said we want to avoid making the `where` syntax more complex for cases like this. If the equal condition already work with the current code there is no reason to add a new special syntax. Thank you for the pull request.

**Comment by amagasu** [comment]
Thank you!

**Comment by inopinatus** [comment]
with ruby 2.7 and rails master this is done in hash conditions with ranges

    Legacy::Article.where(published_at: 10.days.ago..) # >=
    Legacy::Article.where(published_at: ..10.days.ago) # <=
    Legacy::Article.where(published_at: ...10.days.ago) # <
    Legacy::Article.where.not(published_at: ..10.days.ago) # >

or, you go down a floor and use Arel.

    scope :published_after, ->(time) { where(arel_attribute(:published_at).gt(time)) }

**Comment by amagasu** [comment]
@inopinatus 
Thank you for explaining and example!

**Pull request closed without merging**
