### PR TITLE
TIP added to solve common Windows issue

### PR DESCRIPTION
**Pull request by MarshP**
### Summary

TIP added to solve common Windows issue preventing successful completion of the tutorial

### Other Information

Added a TIP for a common Windows problem which is not solved by uncommenting therubyracer gem to the generated Gemfile.

### CODE REVIEW

**Comment by guilleiguaran** [comment]
I think a better suggestion for Windows is installing Node.js

**Comment by sevenseacat** [comment]
How is that a fix for the problem? You're changing the JS reference to a broken link, meaning no JS will appear on your page...

**Comment by MarshP** [comment]
@sevenseacat I literally just put into the docs what various friends recommended when I showed them the issue - enough to continue the tutorial and no more.  I understand the feeling it'd be better to tackle the underlying problem (which is absolutely beyond me), but this at least allows the user to continue though the tutorial. 

But it's definitely an issue I neither know enough about, nor am interested enough in, to make a stronger case than that.

**Comment by guilleiguaran** [comment]
> But it's definitely an issue I neither know enough about, nor am interested enough in, to make a stronger case than that.

Enough said 🙂

**Pull request closed without merging**
