### PR TITLE
Remove deprecation warning URI.escape is obsolete

### PR DESCRIPTION
**Pull request by artofhuman**

### CODE REVIEW

**Comment by senny** [comment]
@artofhuman could you elaborate where that deprecation is shown? Also a reference as of when this is deprecated would be nice.

**Comment by artofhuman** [comment]
@senny is deprecated at ruby 1.9.2 https://github.com/ruby/ruby/commit/238b979f1789f95262a267d8df6239806f2859cc

**Comment by artofhuman** [comment]
deprecation show in tests for Rails::InfoController

**Comment by senny** [comment]
Judging from the discussion in https://www.ruby-forum.com/topic/207489 simply replacing `URL.escape` with the internal code doesn't seem like a viable solution.

/cc @pixeltrix

**Comment by carlosantoniodasilva** [comment]
Just to add to the discussion, I think we've been using `URI.parser.escape` elsewhere, which is an extension Rails adds.

**Comment by pixeltrix** [comment]
@senny @artofhuman what @carlosantoniodasilva said :smile:

**Comment by artofhuman** [comment]
I think we can use there `URI.parser.escape` instead `URI::DEFAULT_PARSER`.

**Pull request closed without merging**
