### PR TITLE
Validate keys in the `_fixture` field

### LINKED ISSUE #42441: Configuring _fixture.class_name does not change the table_name for the fixture
Here, the fixture is initialized, and the table name is set according to the class name:

https://github.com/rails/rails/blob/f95c0b7e96eb36bc3efc0c5beffbb9e84ea664e4/activerecord/lib/active_record/fixtures.rb#L654-L664

However, the class name is determined from the fixture file name, and setting the `_fixture.class_name` in the fixture itsenf does not change it.

It would be nice to be able to configure the table name and the class independently

The use case I have is that I have a model that is backed by a read-only view, which is used for all querying, and a separate table that I use for write access. I need to read from the view but write to the separate table.

### PR DESCRIPTION
**Pull request by casperisfine**
Fix: https://github.com/rails/rails/issues/42441

Otherwise it can be very hard to figure out that we made a typo.

### CODE REVIEW

**Comment by pixeltrix** [comment]
Can't we use `assert_valid_keys` for this?

**Comment by casperisfine** [comment]
I actually wasn't aware of `assert_valid_keys`, I'll look into it and report back.

**Comment by casperisfine** [comment]
done.

**Review by pixeltrix — APPROVED** [review]

**Comment by pixeltrix** [comment]
Maybe a CHANGELOG is warranted? Was it silently ignoring the keys before? If so an app's test suite might start failing after upgrading.

**Comment by casperisfine** [comment]
Make sense. I'll add the changelog entry and merge.

**Pull request merged**
