### PR TITLE
Delegate `empty?` query method to relation

### PR DESCRIPTION
**Pull request by fatkodima**
```ruby
User.empty? # => false
```

There is already `none?`, but `empty?` seems more natural to me personally and associated with `exists?`. 
But `none?` associated with the need to iterate the whole collection and I always have to double check, if that is true or not.

### CODE REVIEW

**Comment by jhawthorn** [comment]
I don't think we should do this. `empty?` has a fairly strong meaning as [the default for objects which define `empty?` is to use it for `blank?`](https://edgeapi.rubyonrails.org/classes/Object.html#method-i-blank-3F).

This means that as of this commit we get the following behaviour:

```
> User.present?
D, [2022-06-02T22:33:20.262413 #23566] DEBUG -- :   User Exists? (0.5ms)  SELECT 1 AS one FROM `users` LIMIT 1
=> true
```

Calling `.present?` on any ActiveRecord class will now issue a query (and might return false!). This is going to cause issues because it's fairly common for folks to use unnecessary `.present?` to check things.

We could work around it by defining `blank?` on to always return `false`, but I think it's surprising for blank to have different behaviour from the default of checking `empty?` (one might expect to be able to replace one with the other in a refactor).

I think it would be best to revert this to avoid confusion.

**Comment by fatkodima** [comment]
Thanks, you are right. I missed this when proposed that change. 
As a follow up to the revert, I think it would be worthwhile to add some tests for `SomeModel.present?` with and without records.

**Comment by jhawthorn** [comment]
Thanks! I think normally we wouldn't test behaviour that is default/implicit, but in this case that seems like a good idea to catch a similar regression in the future.

**Comment by byroot** [comment]
Agreed. Thanks for the revert John.

**Comment by byroot** [comment]
>  other than the present?/blank? awkwardness this seems like a great change

I wonder if we could define `ActiveRecord::Base.blank?` to get rid of the behavior and still delegate `empty?`

**Pull request merged**
