### PR TITLE
Set port environment variable when using the puma webserver

### PR DESCRIPTION
**Pull request by AaronCowan**
### Summary
This pull request references the bug recorded in issue #27834. 

**Bug**
When running the command `rails server -p 3001` the following is logged.
```
=> Booting Puma
=> Rails 5.0.1 application starting in development on http://localhost:3001
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.7.0 (ruby 2.3.0-p0), codename: Snowy Sagebrush
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3000
```
Note the last line Listening on tcp://0.0.0.0:3000 should read  Listening on tcp://0.0.0.0:3001

This is because of this line in `config/puma.rb`
`port        ENV.fetch("PORT") { 3000 }`

No ENV variable named "PORT" exists, so it is defaulting to port 3000.

My code changes will check to see if the server being started is Puma and if so it will set ENV["PORT"] equal to the passed parameter.

### CODE REVIEW

**Comment by robin850** [comment]
Hi @AaronCowan,

Thanks for the pull request ! Could you please put [a changelog entry](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#updating-the-changelog) to describe your change ?

Also your test is failing because `ENV['PORT']` isn't empty when you try to call `||=` in your test (the empty string isn't considered as a missing value). I can't tell you what is filling the empty string inside the environment variable, but a simple solution is to do a `ENV['port'] = nil` at the beginning of your test.

**Comment by AaronCowan** [comment]
Hey @robin850 

After I submitted this pull request @rafaelfranca commented on the [issue](https://github.com/rails/rails/issues/27834) saying we should not have any Puma specific code and that this is a bug in Puma. So, I'm no longer confident in my changes.

**Comment by robin850** [comment]
Ah, I should have fully read the thread before posting, let's wait for his feedback then ; I don't know if we want to temporarily fix this on our side waiting Puma to release a new version with a fix or not.

**Comment by rafaelfranca** [comment]
How about always setting the PORT env? This way we fix it but we don't have any check for puma.

**Comment by AaronCowan** [comment]
@rafaelfranca I can do that.

**Comment by ayghor** [comment]
setting PORT would be a ugly hack in any case, since everyone should obey rack specs. if we keep adding alternative ways to make specific servers happy (even though we don't explicitly check for them), what is teh point on having a standard?

you can always downgrade puma until a fix is released:
```
bundle exec puma --version
puma version 3.6.2
```
is working fine for me.

**Comment by AaronCowan** [comment]
Puma 3.6.2 works for me as well

```
$ bundle exec puma --version && rails server -p 3001
puma version 3.6.2
=> Booting Puma
=> Rails 5.0.1 application starting in development on http://localhost:3001
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.6.2 (ruby 2.3.0-p0), codename: Sleepy Sunday Serenity
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://localhost:3001
Use Ctrl-C to stop
```

**Comment by rafaelfranca** [comment]
So it is a problem with puma 3.7.0?

**Comment by ayghor** [comment]
you said it was a bug with puma. since `3.6.2` works. then it must be with some other version, perhaps `3.7.0`. i havent tested. take a look at #24435

**Comment by ayghor** [comment]
teh test with webrick on #27834 also suggest it only affects some puma specific version.

**Comment by rafaelfranca** [comment]
OK. So we should open an issue in the puma issue tracker. Could any of you take care of it? Closing this one.

**Comment by rafaelfranca** [comment]
BTW, thank you for sending the PR

**Comment by AaronCowan** [comment]
@rafaelfranca Anytime. I just want to get involved. I actually don't think this is a Puma problem. I did a little more research and I found that if you do the following.

1. `rails new puma-test`
2. comment / delete line 12 in `config/puma`
    - `port        ENV.fetch("PORT") { 3000 }`
3. run `rails server -p 3001` or `rails server`

Notice everything is working as expected.
I'm not sure why this works, but it leads me to believe that the port option is being sent correctly to Puma, but is being overridden by our puma configuration file.

**Comment by rafaelfranca** [comment]
Good point. I imagined that. Can we try understand why that line was added to config/puma?

**Comment by AaronCowan** [comment]
The line was added during at this [commit](https://github.com/rails/rails/commit/5563c329eee5febc22a3330e16fe8a6899d42fe2). 

"reading in from `PORT` environment variable this config can work with containerized deployments, such as on Heroku."

This is not an issue for Heroku because the server is initialized with the -p command anyway.
Heroku logs assign port number:
`heroku[web.1]: Starting process with command `bin/rails server -p 23166 -e production``

I cannot speak for other containerized deployment methods because I've only used Heroku.

**Comment by ayghor** [comment]
see https://github.com/puma/puma/commit/42bec4600c51ab8a1c1ee5a0e1b738a4ffd82bf2, it was tagged `v3.6.2` and was __NOT__ merged on `v3.7.0` for some reason:

>     Revert "fix access priorities of each level in LeveledOptions"
>     
>     This reverts commit 15f0847289d0815284f87eeea4625100b581c026.
>     
>     See #1154, this commit unintentionally changed behavior regarding the
>     importance of command line options.

cant test reverting teh reversion right now

**Pull request closed without merging**
