### PR TITLE
Add metadata value for presence of audio channel in video blobs

### PR DESCRIPTION
**Pull request by brenogazzola**
### Summary
When working with video files it is often useful to know if the file has an audio channel or not, since any ffmpeg command that includes a filter for audio will fail otherwise.

This PR uses information already extracted by `probe_from` in `video_analyzer` to add an boolean named `audio` to the metadata that is set to `true` is the file contains an audio channel, and `false` if it doesn't.

### CODE REVIEW

**Comment by ghiculescu** [comment]
Thanks for your contribution. Agree this looks useful. Could you please add a changelog entry?

**Comment by brenogazzola** [comment]
Done. I forgot to mention, the new video file is just the existing `video.mp4` with the following applied to it:
```
ffmpeg -i video.mp4 -c copy -an video_without_audio_stream.mp4
```

**Comment by brenogazzola** [comment]
I had added it to the wrong changelog. It's fixed now. Sorry for the mess in the CI.

**Comment by zzak** [comment]
@brenogazzola Can you rebase please? 🙇

**Comment by brenogazzola** [comment]
@zzak Done. Is there a way to avoid conflicts due to the `CHANGELOG` file? Should I place the entries lower? Otherwise it seems to me that every time a PR with `CHANGELOG` changes is merged, the other PRs with `CHANGELOG` entries need to be updated.

**Comment by zzak** [comment]
@brenogazzola No such luck, so we try to ask until after all discussions seem resolved and the PR is ready to be merged.

**Pull request merged**
