### PR TITLE
Update `config.ru` when running `app:update` task

### PR DESCRIPTION
**Pull request by bensheldon**
### Motivation / Background

This PR ensures that the `config.ru` file is updated when running `bin/rails app:update`

### Detail

This Pull Request has been created because changes were made to the default `config.ru` file to support a `Railtie#server do` hook in https://github.com/rails/rails/pull/39953 and merged via https://github.com/rails/rails/commit/f8a1a8acc340da29cee8771f1ddc3861a57948de). 

Inspecting the initial PR vs the final commit, the PR contains the change to `#config_when_updating`, but the subsequent commit does not, so maybe just an oversight: https://github.com/rails/rails/pull/39953/files#diff-4521b0667f0d930737cfa0a1ced7dd5c00a15909503123cf3752a6c6ebfcca04R143

As a gem developer who would love to use this hook in my Railties/Engines, I've noticed that many older Rails apps have not updated their `config.ru` to trigger this hook. Which also means I've done [gross workarounds](https://github.com/bensheldon/good_job/blob/cba4d92ac475bd3c6a0816ad9cb8f8d34b184425/lib/good_job/configuration.rb#L362-L368), which I'd love the chance to slightly avoid.

Noted in https://github.com/bensheldon/good_job/pull/1106#issuecomment-1760612041

### Checklist

Before submitting the PR make sure the following are checked:

* [X] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [X] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [ ] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by skipkayhil** [comment]
Ref: #41083 where updating `config.ru` was removed

**Comment by bensheldon** [comment]
@skipkayhil oh, that's a bummer, but I understand the intent, though I guess:

> as they change very rarely at the framework level,

...may be true, but it's important that they do change when they do change.

I'll go back to the drawing board then. Maybe I could try logging a (Deprecation?) warning if say `Rails::Server` is defined by the server hook hasn't been called. Not sure how else to indicate to devs "hey, this framework file needs to be updated or you might be missing out on functionality"

**Comment by bensheldon** [comment]
> Maybe I could try logging a (Deprecation?) warning if say Rails::Server is defined but the server hook hasn't been called

Oh, but that would need to live in middleware or like a `before_action` hook and that seems messy 🤔

**Comment by skipkayhil** [comment]
Ah, sorry I didn't mean to say this wouldn't be accepted, just trying to add some context 😅 

I agree it's unfortunate that there was only a single (6.1) version of Rails that updated `config.ru` and updated it with `app:update`. It seems like running `app:update` for each version is still not common knowledge for people. I think adding `config.ru` back to `app:update` could be a good change

**Pull request closed without merging**
