### PR TITLE
Fix links in README for ActiveModel [ci skip]

### PR DESCRIPTION
**Pull request by yhirano55**
### Summary

Almost of all links to api doc are broken. So I fixed them.

### CODE REVIEW

**Comment by prathamesh-sonpatki** [comment]
Thanks but those links are meant to be read on the API website and not on github: https://github.com/rails/rails/issues/28608#issuecomment-290277451

**Comment by yhirano55** [comment]
@prathamesh-sonpatki Thanks for the reviewing. I understood.

By the way, is [this](http://api.rubyonrails.org/classes/ActiveModel.html) the API website? I don't know where we can read this README.
Would you mind if teach me the URL of page?

**Comment by kamipo** [comment]
http://edgeapi.rubyonrails.org/files/activemodel/README_rdoc.html

Related #30306.

**Comment by yhirano55** [comment]
@kamipo Thank you so much.

**Pull request closed without merging**
