### PR TITLE
table name should be plural

### PR DESCRIPTION
**Pull request by tonytonyjan**

### CODE REVIEW

**Comment by sgrif** [comment]
Can you rebase this, and add `[ci skip]` to the commit message?

**Comment by rafaelfranca** [comment]
@sgrif I already merged it

**Comment by tonytonyjan** [comment]
@sgrif It's done, thanks.

**Comment by sgrif** [comment]
Merged by https://github.com/rails/rails/commit/69acffa30ed8f44261c7dfce7ed6d0d3570a2b7a

**Comment by sgrif** [comment]
#concurrency-problems

**Pull request merged**
