### PR TITLE
Fixes FIXME: rb-inotify 0.99 has been released

### PR DESCRIPTION
**Pull request by utilum**
### Summary

https://rubygems.org/gems/rb-inotify

### CODE REVIEW

**Comment by rafaelfranca** [comment]
I don't know why, the build is now failing with Ruby 2.4.1 after this was merged

**Comment by utilum** [comment]
Strange!
Excuse my ignorance: where is the build log?

**Comment by rafaelfranca** [comment]
Here https://travis-ci.org/rails/rails/builds/245019489

**Comment by matthewd** [comment]
https://github.com/guard/rb-inotify/pull/49#issuecomment-309283345

**Comment by utilum** [comment]
Umm... shall I revert this to an older version and add another `FIXME: pending...` ?

**Pull request merged**
