### PR TITLE
Clarify ActiveSupport::Rescuable#rescue_from behaviour to fallback to cause

### PR DESCRIPTION
**Pull request by acaron**
### Summary

A specific behaviour was used inside a `rescue_from` block because the
specified class was expected. It turns out that it can be the cause of
a specified class so an error was raised inside the block. The
documentation is not clear about the intended behaviour.

I proposed a solution to decide whether it should fall back or not to
the cause if the handler is not found. I would like to discuss the
matter and, later, add the conclusion to the documentation.
### Problem

`ActiveSupport::Rescuable.rescue_from` will select handlers by first
finding a handler for the specific exception. If no handler is found
and the exception has a `cause`, it will search a handler for the
cause and so on.

There are two ways to interpret `rescue_from`. The first one is to
assume that the block argument will be one of the specified classes.
The second is to assume that specified classes will be rescued by
their cause if no handler is found.

Here is a quick example:

``` ruby
rescue_from ActiveResource::ClientError do |error|
  if error.response.code == "402"
    render :payment_required
  else
    render :error
  end
end

def fetch_remote_resource
  main_resource = RemoteResource.find
  # load more resources
rescue ActiveResource::ResourceNotFound => e
  log("failed to load associations of #{main_resource.id}")
end
```

If the load of `main_resource` fails, the `rescue_from` will be called
with a `NoMethodError`. `NoMethodError` obviously doesn't respond to
`response.code`. I understand the rationale of matching
`exception.cause` in cases where the handler is very generic, like
logging or rendering an error message. For specific handlers, it means
the handler needs to check if the handler is exception is actually
what's expected. In the previous example, I think it would have been
sane to let the `NoMethodError` bubble up to the middleware and get
caught by `ActionDispatch::DebugExceptions` or equivalent.
### Solution

Add a `fall_back_to_cause` property that is `true` by default. If set to
`false`, the error does not fall back to its cause if the handler is not
found in the first place.

### CODE REVIEW

**Comment by gmalette** [comment]
does anyone recall what the rationale was to use `cause` by default? seems to me like it should be the opposite

**Comment by rafaelfranca** [comment]
The commit is e35b98e6f5c54330245645f2ed40d56c74538902. I don't have full context about the change and both behaviors make sense to me, so I'd let @jeremy decide.

**Comment by nightscape** [comment]
We just ran into a problem with exactly this part of the code. In our case JRuby raised an error (when trying to split an invalid UTF-8 String) that was its own `cause`. There was no exception handler for this exception, so `find_rescue_handler` kept calling itself until there was a StackOverflowError.
One could question why JRuby raises exceptions that are their own `cause`, but in Java land this seems to be rather common and probably should be taken care of. Either by preventing this explicit case, or as @gmalette mentioned, inverting the default.

**Comment by acaron** [comment]
bump @jeremy

**Comment by jeremy** [comment]
Looks like the issue here is that we look up the handler based on the exception, then fall back to looking up the handler based on the exception.cause, but call the handler with the original exception in both cases.

We mean to fall back to handling the cause, not using the cause's handler to handle the original exception, so this is a bug. We'll "just" fix by calling the handler with the cause 😊

**Comment by sgrif** [comment]
The underlying problem has been fixed in https://github.com/rails/rails/commit/f48bb1b4ad86bad71ae9c3e5dd3db6b4cb80e4d1.

**Pull request closed without merging**
