### PR TITLE
Merge Arel

### PR DESCRIPTION
**Pull request by matthewd**
We've been bumping Arel in lockstep with AR for some time now: every Rails release requires a new Arel release, and Arel releases occur specifically for Rails releases.

We're not gaining any maintenance freedom by keeping it as a separate gem, while we are paying the costs of coordination.

Scrolling through https://rubygems.org/gems/arel/reverse_dependencies shows few notable downstreams that aren't also depending on Active Record, so this change doesn't force new dependencies onto the ecosystem at large. We'll release a new version of the `arel` gem that depends on the new version of `activerecord`, so people will still be able to smoothly upgrade: this just means they'll need AR installed (but not loaded/required).

We have no plans to rename the top level `Arel` constant.

---

Housekeeping:
- [x] Copyright/license: https://github.com/rails/rails/commit/17ca17072dcdff11b3702a6b45f2fb0c8f8fe9a4#diff-d80e0e1d20abc3da5a7e0d873241b585R3
- [x] Tests integrated
- [x] Rubocop reformat
- [x] `:nodoc: all`

Anything else?

### CODE REVIEW

**Comment by composerinteralia** [comment]
1,749 commits doesn't sound quite right

**Comment by matthewd** [comment]
@composerinteralia https://github.com/rails/arel has 1746, plus my three.

**Comment by composerinteralia** [comment]
Got it. Thanks

**Comment by pixeltrix** [comment]
Glad to see you haven't made the same mistake I did when integrating Journey and have changed the test file names from `test_*.rb` to `*_test.rb`. 👍

**Review by sgrif — APPROVED** [review]

**Review by eileencodes — APPROVED** [review]

**Review by rafaelfranca — APPROVED** [review]

**Comment by yahonda** [comment]
This commit will help me a lot because when some `git bisect` was necessary it was very difficult to bisect `rails` and `gem` repositories at the same time.

As a 3rd party database adapter maintainer, I'd like to know if if there is a plan to separate visitors for non bundled database adapters, such as `oracle`, `oracle12`, `ibm_db`, `mssql` and `informix` .

Actually, I'd like Arel will have these visitors at least for Rails 6, Just wanted to prepare if there is a plan.

Thank you.

**Comment by matthewd** [comment]
@yahonda in the short term, we'll keep the visitors in place, despite the inconsistency.

Looking forward, I'd like to rebalance some responsibilities between the Arel and AR parts, and at that time I expect we'll try to move them closer together. But no concrete plans for now.

**Comment by yahonda** [comment]
@matthewd Thanks for the answer and I am happy to hear there will be no change in the short term.
Of course, I'm looking forward to getting any updates for future plans.

**Pull request merged**
