### PR TITLE
Eliminate sporadic integration test failures

### LINKED ISSUE #25836: Caching within Rails::Application#env_config interferes with integration testing
### Steps to reproduce

In order to verify that a subclass of `ActionDispatch::PublicExceptions` was correctly assigned as the `config.exceptions_app`, I wrote a test (a subclass of `ActionDispatch::IntegrationTest`). In the `setup` method of the test, I explicitly set `Rails.configuration.consider_all_requests_local = false` and `Rails.configuration.action_dispatch.show_exceptions = true`, because in this test, and this test only, I want the custom exceptions app to handle rendering the response rather than raising an exception like the stock behavior.

The test fails because the exceptions app is never invoked. It is not invoked because the `env_config` method of `Rails::Application` caches its return value inside `app_env_config` and there is no publicly exposed means to clear the cache. Making matters worse, when tests are executed in isolation, they pass, because no other test has caused `env_config` to be called before.

The workaround I've developed overrides `env_config` within `application.rb`:
```ruby
def env_config
  @app_env_config = nil if Rails.env.test?
  super
end
```

### Expected behavior
I believe that every element of the application should be easily testable without having to overload the default behavior of `Rails::Application`, including integration tests featuring exception apps.

### Actual behavior
Tests can be flaky because they can't fully isolate themselves from each other.

### System configuration
**Rails version**: At least 4.2.7 and 4.2.6; I didn't have this problem a few months ago before I switched from Rails 3.2.18.
**Ruby version**: ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
I have also reproduced this issue on various versions of JRuby

### PR DESCRIPTION
**Pull request by JasonLunn**
### Summary

Fixes #25836 by eliminating the memoization within `env_config`.

### CODE REVIEW

**Comment by matthewd** [comment]
This seems to be a rather production-runtime-expensive solution, to a problem I don't believe is as isolated as this issue implies: we use the configuration during application startup, and changing it after that can have unexpected / insufficient effects.

**Comment by rafaelfranca** [comment]
Like I said in #25836, we don't want to users to even know that `env_config` exists, even more to know t hat it is being cached. Again, the proper way to now having sporadic integration tests failures is using the public API to those tests that is the rack environment headers.

Thank you for the pull request.

**Comment by JasonLunn** [comment]
This PR doesn't expose env_config, @rafaelfranca . I don't see a performance problem as `env_config` is only called outside of a test inside a single function in ActionCable. The existing "public API" is insufficient as it requires introducing bogus HTTP headers that don't actually have any impact outside of tests.

**Comment by rafaelfranca** [comment]
it is not a bogus HTTP header it is a rack environment value, and like any other rack environment value it can't be sent in a regular request but it is a totally valid rack environment value.

`env_config` is called in every request.

Like I also said in the original issue the application is cached after it is booted and it is expected to be cached. You can't change configurations after it is booted for example, the behavior is the same in tests.

**Comment by JasonLunn** [comment]
I think I might have just spotted a problem that explains why you and I are thinking about this so differently, @rafaelfranca. It looks like the example you originally pointed me to, https://github.com/rails/rails/blob/5-0-stable/actionpack/test/dispatch/show_exceptions_test.rb - is incorrectly using the `headers` hash to pass the override for `'action_dispatch.show_exceptions'`. It should be using the `env` hash instead. In that way, it would not be representing this override as a bogus HTTP header, but properly segregating it as something limited to manipulating the environment of the request.

If that explanation makes sense to you, I'll create a different pull request that corrects that test.

**Pull request closed without merging**
