### PR TITLE
Added documentation for nulls not distinct option for postgres sql [ci skip]

### PR DESCRIPTION
**Pull request by khhizr007**
### Motivation / Background

This Pull Request has been created because of #52852 

### Detail

This Pull Request adds documentation for the method `add_index_options` along with the option `nulls_not_distinct` in the `activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb`

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [ ] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by zzak** [comment]
Thanks for your PR!

Can you make the options list follow our guidelines?
https://edgeguides.rubyonrails.org/api_documentation_guidelines.html#description-lists

**Comment by khhizr007** [comment]
@zzak can you please take a look ?

**Comment by zzak** [comment]
Agh, I'm sorry. I didn't realize this method was private (`:nodoc:`) at first. It should go under `add_index` if they are not already covered there.

**Comment by khhizr007** [comment]
Yes, realised this after creating the pr. Closing this since another pr has closed the issue.

**Comment by zzak** [comment]
Sorry about that, it would have been nice to include you both in the change as co-authors. Next time!

**Pull request closed without merging**
