### PR TITLE
Rails documentation standard is american english. [ci skip]

### PR DESCRIPTION
**Pull request by karanarora**

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Since this is the third pull request for the same thing I'll wait you to fix all the entries you need to be fixed in this same PR. Let me know when it is done.

**Comment by karanarora** [comment]
alright @rafaelfranca I will go through the whole documentation once and let you know if any other changes are required. Thanks.

**Comment by karanarora** [comment]
@rafaelfranca  I have made changes in some files.. I think this can go in.

**Comment by arthurnn** [comment]
Dont forget to squash your commits in one. thanks

**Comment by karanarora** [comment]
@arthurnn done!

**Comment by zzak** [comment]
Great thanks!

**Pull request merged**
