### PR TITLE
Add support for index option with add_column

### PR DESCRIPTION
**Pull request by deepakmahakale**
### Motivation / Background

With `create_table` and `add_reference` supporting the `index` option, 
most developers assume the `index: true` should work with `add_column` as well.

```ruby
create_table :users do |t|
  t.string :email, index: { unique: true }
end
```
```ruby
add_reference(:orders, :user, index: true)
```

Which is not the case.

Screenshot 2023-09-07 at 16 51 33
_Screenshot of a discussion we had last month:_

### Detail

This pull request adds support for the `index` option on the `add_column`

**Before:**

```ruby
class AddEmailAndPhoneNumberToUsers < ActiveRecord::Migration[7.1]
  def change
    add_column :users, :email, :string
    add_column :users, :phone_number, :string

    add_index :users, :email, unique: true
    add_index :users, :phone_number
  end
end
```

**After:**

```ruby
class AddEmailAndPhoneNumberToUsers < ActiveRecord::Migration[7.1]
  def change
    add_column :users, :email, :string, index: { unique: true }
    add_column :users, :phone_number, :string, index: true
  end
end
```

```sql
                                           Table "public.users"
    Column    |              Type              | Collation | Nullable |              Default
--------------+--------------------------------+-----------+----------+-----------------------------------
 id           | bigint                         |           | not null | nextval('users_id_seq'::regclass)
 phone        | character varying              |           |          |
 created_at   | timestamp(6) without time zone |           | not null |
 updated_at   | timestamp(6) without time zone |           | not null |
 email        | character varying              |           |          |
 phone_number | character varying              |           |          |
Indexes:
    "users_pkey" PRIMARY KEY, btree (id)
    "index_users_on_email" UNIQUE, btree (email)
    "index_users_on_phone_number" btree (phone_number)
```

### Checklist

Before submitting the PR make sure the following are checked:

* [ ] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [ ] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [ ] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by fatkodima** [comment]
I remember it was proposed before (2 times), but was rejected by @rafaelfranca. 
I was not able to quickly find these PRs, maybe you will.

**Comment by deepakmahakale** [comment]
I will definitely check 👍 

Given that people are raising the PRs for this feature, can we consider adding this support?

This also makes it more consistent with other methods to add columns and provide an optional index option.

**Comment by akhilgkrishnan** [comment]
> I remember it was proposed before (2 times), but was rejected by @rafaelfranca. I was not able to quickly find these PRs, maybe you will.

https://github.com/rails/rails/pull/20616#issuecomment-144870870

**Comment by shalvah** [comment]
It seems like the major objection was conceptual (add_column should only add a column). If we decide to keep it that way, could we at least raise an error if unsupported options (like `index`) are passed? It's a common cause of confusion.

**Comment by skipkayhil** [comment]
> > I remember it was proposed before (2 times), but was rejected by @rafaelfranca. I was not able to quickly find these PRs, maybe you will.
> 
> [#20616 (comment)](https://github.com/rails/rails/pull/20616#issuecomment-144870870) #17584

Since this was decided pretty intentionally before and nothing new has been added, I'm going to close. Thank you for the PR and I'm sorry this wasn't resolved more quickly 🙏

**Pull request closed without merging**
