### PR TITLE
quote fix ` to ' in exception_wrapper_test

### PR DESCRIPTION
**Pull request by amitsuroliya**

### CODE REVIEW

**Comment by senny** [comment]
@amitsuroliya what is the purpose of this PR? Please don't submit pull requests with empty description. This looks pretty cosmetic to me.

**Comment by amitkumarsuroliya** [comment]
@senny  Sorry for empty description.  
In `exception_wrapper_test`, Trace messages started with quote(`) and ends with (') like - 
```
"lib/file.rb:42:in `index'"
```
This should be started and ends with (') like below -
```
"lib/file.rb:42:in 'index'"
```
Thanks..........:)

**Comment by senny** [comment]
@amitsuroliya but why should they start with `'`?

When I look at Ruby traces they start with `

```
/Users/senny/.rbenv/versions/2.2.2/lib/ruby/2.2.0/irb/workspace.rb:86:in `eval'
/Users/senny/.rbenv/versions/2.2.2/lib/ruby/2.2.0/irb/workspace.rb:86:in `evaluate'
/Users/senny/.rbenv/versions/2.2.2/lib/ruby/2.2.0/irb/context.rb:379:in `evaluate'
/Users/senny/.rbenv/versions/2.2.2/lib/ruby/2.2.0/irb.rb:489:in `block (2 levels) in eval_input'
/Users/senny/.rbenv/versions/2.2.2/lib/ruby/2.2.0/irb.rb:623:in `signal_status'
/Users/senny/.rbenv/versions/2.2.2/lib/ruby/2.2.0/irb.rb:486:in `block in eval_input'
/Users/senny/.rbenv/versions/2.2.2/lib/ruby/2.2.0/irb/ruby-lex.rb:245:in `block (2 levels) in each_top_level_statement'
/Users/senny/.rbenv/versions/2.2.2/lib/ruby/2.2.0/irb/ruby-lex.rb:231:in `loop'
/Users/senny/.rbenv/versions/2.2.2/lib/ruby/2.2.0/irb/ruby-lex.rb:231:in `block in each_top_level_statement'
/Users/senny/.rbenv/versions/2.2.2/lib/ruby/2.2.0/irb/ruby-lex.rb:230:in `catch'
/Users/senny/.rbenv/versions/2.2.2/lib/ruby/2.2.0/irb/ruby-lex.rb:230:in `each_top_level_statement'
/Users/senny/.rbenv/versions/2.2.2/lib/ruby/2.2.0/irb.rb:485:in `eval_input'
/Users/senny/.rbenv/versions/2.2.2/lib/ruby/2.2.0/irb.rb:395:in `block in start'
/Users/senny/.rbenv/versions/2.2.2/lib/ruby/2.2.0/irb.rb:394:in `catch'
/Users/senny/.rbenv/versions/2.2.2/lib/ruby/2.2.0/irb.rb:394:in `start'
```

**Comment by amitsuroliya** [comment]
Thanks @senny for explanation. I was wrong on this.

**Pull request closed without merging**
