### PR TITLE
Add support for conditional values to TagBuilder

### PR DESCRIPTION
**Pull request by joelhawksley**
This PR adds support for conditional values to TagBuilder,
extracting logic we use in the GitHub application,
inspired by https://github.com/JedWatson/classnames.

It’s common practice to conditionally apply CSS classes
in Rails views. This can lead to messy string interpolation,
often using ternaries:

```ruby
content_tag(
  "My username",
  class: "always #{'sometimes' if current_user.special?} another"
)
```

By adding support for hashes to TagBuilder, we can instead write the following:

```ruby
content_tag(
  "My username",
  class: ["always", "another", { 'sometimes' => current_user.special? }]
)
```

cc @JedWatson

### CODE REVIEW

**Review by tenderlove — COMMENTED** [review]
I think this makes a lot of sense for CSS classes.  Should it be applied to all options though?

**Comment by joelhawksley** [comment]
@tenderlove this probably doesn't make much sense for values to arguments besides `class` 👍

**Comment by nashbridges** [comment]
> This can lead to messy string interpolation,

For honest comparison with the new version, one could use arrays (that were already supported) + pure Ruby

```ruby
content_tag(
  "My username",
  class: ["always", "another", ("sometimes" if current_user.special?)]
)
```

vs

```ruby
content_tag(
  "My username",
  class: ["always", "another", { 'sometimes' => current_user.special? }]
)
```


Probably, the hash notation was inspired by JS [Classnames](https://github.com/JedWatson/classnames#usage) library. Because in JS something like

```js
[1, 2, (if (true) { 3 })]
```

is not only ugly, but also an invalid syntax.

**Comment by kenn** [comment]
@nashbridges I guess this API has parity with #37918 in mind.

**Comment by joelhawksley** [comment]
@nashbridges - @kenn is correct. This PR was meant to enable #37918.

**Comment by nashbridges** [comment]
@kenn @joelhawksley I see, thanks guys! 

On our project we use [slim](https://github.com/slim-template/slim), so the `class_names` equivalent would be

```slim
.wrapper class=("active" if item.for_sale?)
``` 

but yeah, I can see that for ERB users the result is much more cleaner.

**Pull request merged**
