### PR TITLE
ConnectionMonitor.disconnected now called

### PR DESCRIPTION
**Pull request by danielrhodes**
### Summary

This is to fix an issue in ActionCable which @javan pointed out in reference to #23976 where on the client side `ConnectionMonitor.disconnected()` was not being called when there was a disconnect.

### CODE REVIEW

**Comment by javan** [comment]
:+1:

What do you think about calling `connected` from `Connection`'s `open` handler too? Then there'd be no need for a special `welcome` message.

**Comment by danielrhodes** [comment]
Yeah I can do that. However, on the way I found a couple bugs that might make the `welcome` message useful to keep. The bugs are as follows:

1. If the server side calls `reject_unauthorized_connection` when the client initially connects, the ConnectionMonitor keeps trying to reconnect as it had no indication that the disconnection was abnormal.
2. Although not for "direct user manipulation", if `Connection.close()` is called, the `ConnectionMonitor` detects the change and immediately tries to re-open the connection, which defeats the point of `close` being there in the first place.

The way the `welcome` message helps is that to overcome especially the first bug, the ConnectionMonitor won't start until the `welcome` message has been received. If we get rid of the welcome message, we don't have a way of overcoming that elegantly.

I made a couple changes locally and it seems to prevent this cycle.

Thoughts?

**Comment by danielrhodes** [comment]
Ok @javan, I came up with a more elegant way of dealing with this: when a connection is unauthorized on the server side, the server does not upgrade the connection to a websocket and instead responds with a 401 (causing the websocket to throw an `onerror` event). Then we can remove the `welcome` message, and the ConnectionMonitor does not go into a cycle.

https://github.com/rails/rails/compare/master...danielrhodes:enhancement/ac-no-upgrade-on-reject

**Comment by javan** [comment]
`ConnectionMonitor`'s primary job is to handle reconnects when the connection closes or encounters an error, events that could happen for any number of reasons: flakey connections, server restarts / crashes, etc. I think it'd be better to implement an intentional way of stopping the monitor via a message a message from the server and / or a client side API call.

**Comment by danielrhodes** [comment]
Sorry I screwed up a rebase on that branch. I made a new PR above ^

**Pull request closed without merging**
