### PR TITLE
Don't perform unnecessary check with false, just use true/false values

### PR DESCRIPTION
**Pull request by vipulnsward**
Don't perform unnecessary check with false, just use true/false values for @active on SQLite adapter.

### CODE REVIEW

**Comment by jeremy** [comment]
This means `connection.active?` will be true before before it's configured.

**Comment by matthewd** [comment]
@jeremy that's already the case though, isn't it?

**Comment by jeremy** [comment]
Yes indeed. Odd git history…

**Comment by vipulnsward** [comment]
Yes, it already behaves this way, let me see, if I can move it around to intended place.

**Comment by vipulnsward** [comment]
@jeremy by the time we reach here, we already have a connection to `SQLite3::Database` from `sqlite3_connection`, along with other configurations setup. So its active/properly configured here.

**Comment by jeremy** [comment]
👍👍

**Pull request merged**
