### PR TITLE
Delete unneeded `require 'set'`.

### PR DESCRIPTION
**Pull request by bogdanvlviv**

### CODE REVIEW

**Comment by matthewd** [comment]
These are needed

**Comment by bogdanvlviv** [comment]
For what? Set isn't used in these files.

**Comment by kaspth** [comment]
@bogdanvlviv Yes, they are. These files call `to_set` on Enumerables, which is a method that's only there if set is required.

I'm guessing you may say "well, the tests pass", and you'd be partly right. If this was merged we'd also run isolation tests and these would likely fail because these requires are needed.

In the future, can you please make a more solid reason in your PR description? A blank one hurts you because it doesn't instill confidence in your abilities. Thanks! 😁

**Comment by bogdanvlviv** [comment]
I got it. Thanks @kaspth!

**Pull request closed without merging**
