### PR TITLE
Allow default to be configured for Enum

### PR DESCRIPTION
**Pull request by kamipo**
```ruby
class Book < ActiveRecord::Base
  enum status: [:proposed, :written, :published], _default: :published
end

Book.new.status # => "published"
```

### CODE REVIEW

**Comment by dwightwatson** [comment]
Maybe a silly question, but why is default prefixed with an underscore?

**Comment by abhaynikam** [comment]
@dwightwatson I had similar question asked here: https://github.com/rails/rails/pull/39895#issuecomment-662330647 

Thanks, @kamipo 👍 . 

> People may have a default column. 

I am sorry but I did not clearly understand so I am putting it here again. Hope you don't mind 😊 . The enum options like `_default` or `_prefix` get deleted here(https://github.com/rails/rails/blob/master/activerecord/lib/active_record/enum.rb#L164-L169) so how would default column get affected by the naming convention used for enum options? I tried adding a default column in sample Rails app with renaming `_default` -> `default`. Worked fine at least. I am sure I am missing something here 😅

**Comment by kamipo** [comment]
If people have a `enum default: [:foo, :bar]` definition, introducing new option as `:default` will break the code.

**Comment by sebastiandeutsch** [comment]
@kamipo would it be possible to have a second parameter that will be hash (to differentiate between data) like:

```ruby
enum default: [:foo, :bar], { default: :foo }
```

**Comment by kamipo** [comment]
It is impossible to omit hash braces for non-last arguments.

**Comment by sebastiandeutsch** [comment]
But then you would run into the double key default problem.

**Comment by pomartel** [comment]
It looks like the default value does not apply to `NULL` database values. Here is my use case. I have a database with millions of records. I want to add an enum column (integer) in the database but it would be disruptive to also set the default value for millions of records. I would prefer the ActiveRecord enum to just use the default value when the database column is` NULL`. Is this something that makes sense?

**Comment by joemsak** [comment]
@pomartel For what it's worth, I was feeling the same way when I discovered the same issue today, and was about to write up a test for a pull request, but as I thought about it, I'm pretty sure rails expects us to add the default value. I can't say I share your opinion that it would be disruptive to add this change even with millions of rows of nulls. If you want the default to be a certain value in the code, what's stopping you from making it so in the database? Happy to hear your explanation if you'd like to elaborate.

**Comment by pomartel** [comment]
@joemsak  I am not quite sure how to update millions of records in a non-blocking way but I am also no database expert. I just wish there was a way to set a default for NULL values without touching the database. I tried to override the getter but it did not play nice with the enum.

**Comment by joemsak** [comment]
@pomartel Gotcha yeah. I would have to say it would have to be done in a scheduled maintenance window while shutting down access to the database. Unless you have rolling migrations enabled but I don't know off hand how to do that. I prefer scheduling the maintenance period, alerting customers, getting a backup snapshot, and doing the migrations at the scheduled time.

As for overriding, yeah, I started getting into the guts of active record enum/attributes and based on the workflow of the code it really seems like Rails would prefer we just have a default set and updated on all null rows in the database.

**Pull request merged**
