### PR TITLE
Minor grammatical correction [ci skip]

### PR DESCRIPTION
**Pull request by amitsuroliya**

### CODE REVIEW

**Comment by senny** [comment]
This sentence is perfectly fine as is. Please don't submit arbitrary changes like this. It takes time to create and to review but they have no real gain.

**Comment by schneems** [comment]
"Feedbacks are" isn't correct. The plural of feedback is feedback https://www.google.com/search?q=plural+of+feedback&oq=plural+of+feedback&aqs=chrome..69i57.2729j0j7&sourceid=chrome&es_sm=91&ie=UTF-8

**Comment by amitsuroliya** [comment]
@schneems Great! Thanks for explanation.

**Pull request closed without merging**
