### PR TITLE
fix `ActiveSupport::Tryable` to work with `DelegateClass(x)`

### LINKED ISSUE #31045: `try` doesn't work with `DelegateClass(x)`
`try` was patched to work with delegators in https://github.com/rails/rails/commit/af53280a4b5b3323ac87dc60deb2b1b781197b2b

It does work correctly with subclasses of `SimpleDelegator`, but not with subclasses of `DelegateClass(x)`, even though `DelegateClass(x)` has `ActiveSupport::Tryable` in its ancestors

### Reproduction Script

```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  git "https://github.com/rails/rails.git" do
    gem "activesupport"
  end
end

require "active_support/core_ext/object/try"
require "minitest/autorun"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

class Dog
  def bark
    :woof
  end
end

class DogDelegator < SimpleDelegator
  def bark
    :meow
  end
end

class DogDelegate < DelegateClass(Dog)
  def bark
    :meow
  end
end

class DelegatorTryTest < Minitest::Test
  def test_simple_delegator_uses_try_correctly
    delegator = DogDelegator.new(Dog.new)

    assert_includes delegator.class.ancestors, ActiveSupport::Tryable, "the object is Tryable"

    assert_equal :meow, delegator.bark
    assert_equal :meow, delegator.try(:bark)
  end

  def test_delegate_class_uses_try_correctly
    delegate_instance = DogDelegate.new(Dog.new)

    assert_includes delegate_instance.class.ancestors, ActiveSupport::Tryable, "the object is Tryable"

    assert_equal :meow, delegate_instance.bark
    # this is where it fails
    assert_equal :meow, delegate_instance.try(:bark)
  end
end

```

### System configuration

**Rails version**: master
**Ruby version**: MRI 2.3.3

### PR DESCRIPTION
**Pull request by danielma**
Fixes https://github.com/rails/rails/issues/31045

That issue points out a bug where `try` doesn't work on instances of
`DelegateClass(x)`.

Fix it by marking `try` and `try!` as public API on `Delegator` so
that when `DelegateClass(klass)` is called, it does not copy the
`Tryable` methods from `klass`.

The explanation is that `DelegateClass(klass)` uses `define_method` to
copy instance methods for `klass.instance_methods`, with the exception
of methods considered public API on `Delegator`.

`Delegator.public_api` was added in https://github.com/ruby/ruby/commit/e1797bc7dd2178550cf15d7a6af4f7f0eae003b4
to keep a constant snapshot of methods that exist on `Delegator` and
therefore should not use the definition from `klass`.

In the context of ActiveSupport, this means that
`DelegateClass(klass)` will `define_method(:try)` pointing to `klass`
instead of `Delegator` because `try` exists on `klass` at runtime, but
is not included in `Delegator.public_api` because `@delegator_api` is
created _before_ we include `ActiveSupport::Tryable`

For reference, the use of `Delegator.public_api` is here: https://github.com/ruby/ruby/blob/a5a8ba7d571815e5adafb929ae0d97a0ea6e93dc/lib/delegate.rb#L389

### CODE REVIEW

**Comment by matthewd** [comment]
Eugh! This seems extremely intimate, but it also doesn't look like `DelegateClass` gives us much choice.

ISTM `public_api` should be something more like `ancestors.take_while { |a| a != superclass }.flat_map { |a| a.public_instance_methods(false) }` -- if anything's been added directly to Delegate, it's clearly supposed to be there. But that would be inconsistent with the 1.8-era "it matters when you `require 'delegate'`" behaviour. 😒 


@rafaelfranca any thoughts on manipulating `@delegator_api` vs overriding `self.public_api`? Or even mutating the return value from `self.public_api`, I suppose. They all seem pretty similarly undocumented and fragile.

**Comment by danielma** [comment]
I definitely agree that this is kind of a crazy solution, but I felt it was the best I could come up with. 

I’m open to any improvements or changes

**Comment by sgrif** [comment]
It seems like this probably affects things other than `try`, doesn't it? e.g. `acts_like?` and `tap`?

**Comment by danielma** [comment]
@sgrif based on some quick console work, it looks like `tap` works correctly with `DelegateClass` while `acts_like?` has the same behavior as `try` where it's passed directly to the underlying object.

However, I think there's a case to be made that that behavior is expected, since `Delegator` is a `BasicObject`. `try.rb` is the only file in the [`core_ext/object`](https://github.com/danielma/rails/tree/2d04b3dce91329a0452541465a5d2bed64473f10/activesupport/lib/active_support/core_ext/object) directory that modifies `Delegator`. All the other files only modify `Object` and descendants of `Object`

**Comment by sgrif** [comment]
Ah I missed that we were directly modifying `Delegator` for `try`. You're right that this feels like a special case. :+1: from me, though I would like to see @rafaelfranca's response to @matthewd's concerns before merging

**Comment by rafaelfranca** [comment]
All options are bad but I prefer to override an private API method than changing a value of an equally private instance variable. It is more likely to Ruby rename that variable that is only referenced in one place than renaming that method.

**Pull request closed without merging**
