### PR TITLE
Increment execution count before deserialize arguments

### PR DESCRIPTION
**Pull request by y-yagi**
Currently, the execution count increments after deserializes arguments. Therefore, if an error occurs with deserialize, it retries indefinitely.

In order to prevent this, the count is moved before deserialize.
Fixes #33344.

### CODE REVIEW

**Comment by yahonda** [comment]
Small typo found. "exectuion" should be "execution".

**Comment by y-yagi** [comment]
Thanks for pointing out! I fixed.

**Comment by georgeclaghorn** [comment]
Nice catch! :heart:

**Comment by y-yagi** [comment]
Backport to 5-2-stable 6fa2fc91dd0b2bf9eb44890569d78699afd23b2d.

**Pull request merged**
