### PR TITLE
Another solution to linkifing sources in the docs

### PR DESCRIPTION
**Pull request by pjump**
FILE: rails_guides/markdown/renderer.rb
This one adds another markdown "tag" called SRC_REF to the NOTICE, IMPORTANT, etc.,
family.

SRC_REF creates divs with HTML classes 'note' and 'src_ref'.

FILE:   source/active_support_core_extensions.md
The SRC_REF tags replace NOTE tags for all source code references.

FILE:   assets/javascripts/guides.js
The added JavasScript linkifies all ".src_ref code" (< css/jquery path) code
blocks.

FILE:   source/layout.html.erb
Exports rails version as a global JavaScript variable for the JavaScript
linkifier to use.

### CODE REVIEW

**Comment by pjump** [comment]
I started the linkifier in Ruby, but and wanted to do the linkification inside `RailsGuides::Markdown::Renderer#convert_notes`, but then the backtics were already converted to `<code>` / `</code>` tags and I idiotically forgot I ruby had Nokogiri for DOM parsing and just went for JS.

**Comment by robin850** [comment]
Hey @pjump!

Sorry if I wasn't clear in my comment on the other pull request! I actually meant to transform, inside the `#paragraph` method, the existing if with an elsif and add an if before it to treat notes with these links.

> backtics were already converted to `<code>` / `</code>`

This is not really a problem, you just have to change the regular expression. If you want, here's [a diff](https://gist.github.com/robin850/4b7525cfec4556d6f6cc) that gets the job done.

I don't think using JavaScript is a good solution either. Anyway, let's wait @fxn feedback before taking any action, I may be wrong!

Also please in the future, force push to your branch if you want to update a pull request, having different tickets for a single change makes a lot of noise on the tracker, thanks ! :-)

**Comment by pjump** [comment]
I don't really care how it's done. :D i just thought links to the source code would be nice, and I learned a little bit and I head a little bit of fun while hacking together a couple of solutions to that.

**Comment by pjump** [comment]
Anyhow, anything like this /^\s*NOTE:\s+Defined\s+/ won't do anymore because in the newer version, the source references don't all start this way any more. That's why think that defining a new type of note (the SRC_REF as I named it) would be in order, the semantics of which semantics would be approx. "create a div with the note class and linkify all code tags inside it". 

I don't think it would be a good idea to try and parse a DOM fragment with regexes.

**Comment by fxn** [comment]
Hey, really busy these day, I'll try to come back to this issue as soon as I can.

**Comment by fxn** [comment]
Hi guys, I have this PR in mind, but I am not yet convinced about what to do, need to think about it.

**Comment by matthewd** [comment]
Implemented by #27232

**Pull request closed without merging**
