### PR TITLE
Deprecate `supports_migrations?` on connection adapters

### PR DESCRIPTION
**Pull request by kamipo**
`supports_migrations?` was added at 4160b518 to determine if schema
statements (`create_table`, `drop_table`, etc) are implemented in the
adapter. But all tested databases has been supported migrations since
a4fc93c3 at least.

### CODE REVIEW

**Comment by pixeltrix** [comment]
@kamipo are we sure that all the major third-party adapters support migrations too? Also are there any schema-less databases with AR adapters that might make use of this?

**Comment by kamipo** [comment]
> are we sure that all the major third-party adapters support migrations too?

Most adapters (firebird, frontbase, mysql, oracle, postgresql, sqlite, sqlserver, sybase) were true at least as of Rails 1.2.

https://github.com/rails/rails/blob/1-2-stable/activerecord/lib/active_record/connection_adapters/firebird_adapter.rb#L286-L288
https://github.com/rails/rails/blob/1-2-stable/activerecord/lib/active_record/connection_adapters/frontbase_adapter.rb#L270-L272
https://github.com/rails/rails/blob/1-2-stable/activerecord/lib/active_record/connection_adapters/mysql_adapter.rb#L159-L161
https://github.com/rails/rails/blob/1-2-stable/activerecord/lib/active_record/connection_adapters/oracle_adapter.rb#L133-L135
https://github.com/rails/rails/blob/1-2-stable/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L106-L108
https://github.com/rails/rails/blob/1-2-stable/activerecord/lib/active_record/connection_adapters/sqlite_adapter.rb#L101-L103
https://github.com/rails/rails/blob/1-2-stable/activerecord/lib/active_record/connection_adapters/sqlserver_adapter.rb#L215-L217
https://github.com/rails/rails/blob/1-2-stable/activerecord/lib/active_record/connection_adapters/sybase_adapter.rb#L340-L342

db2 and openbase adapters were false, but looks like that `create_table`, `drop_table`, `add_column`, `remove_column`, `add_index`, and `remove_index` works at least.

`supports_migrations?` was used for two purposes.

1. to determine if schema statements (`create_table`, `drop_table`, etc) are implemented in the adapter in tests. But since a4fc93c3 any adapter never be able to run tests without `create_table` and `drop_table` are implemented at least (and `supports_migrations?` condition in migration_test.rb was removed at 2158a700).

2. to determine to allow migration (`rake db:migrate`) to the adapter. I think that disallowing migration is unneeded because not only schema statements can be used in migration.

**Comment by pixeltrix** [comment]
> I think that disallowing migration is unneeded because not only schema statements can be used in migration.

Definitely - you could write all your migrations use `execute`

**Comment by pixeltrix** [comment]
Thanks for the additional research @kamipo 👍

**Pull request merged**
