### PR TITLE
Show permitted flag in the output of AC::Parameters#inspect

### LINKED ISSUE #23822: AC::Parameters#inspect doesn’t reveal what’s permitted
```rb
a = ActionController::Parameters.new(foo: 'bar')
#=> <ActionController::Parameters {"foo"=>"bar"}>
b = ActionController::Parameters.new(foo: 'bar').permit(:foo)
#=> <ActionController::Parameters {"foo"=>"bar"}>
a == b
#=> false
a.inspect == b.inspect
#=> true
```
This makes it hard to debug failing specs (here, a snippet from RSpec output):

```
expected: (<ActionController::Parameters {foo: "bar"}>)
     got: (<ActionController::Parameters {foo: "bar"}>)
```

### PR DESCRIPTION
**Pull request by prathamesh-sonpatki**
- Fixes #23822.

r? @rafaelfranca

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Thank you

**Comment by bquorning** [comment]
Since this changes an unreleased feature, does it need a CHANGELOG entry?

**Comment by rafaelfranca** [comment]
It doesn't. I was removing it since it is faster than asking to remove :smile:

**Comment by prathamesh-sonpatki** [comment]
Ah, thanks :)

**Pull request merged**
