### PR TITLE
Add Touch method to ActiveRelation

### PR DESCRIPTION
**Pull request by duggiefresh**
This allows for more efficient touching of many records

### CODE REVIEW

**Comment by rafaelfranca** [comment]
I think we should address the optimistic locking issue on this method. `touch` at instance level increment it, so lets keep the same behaviour at the class method.

**Comment by repinel** [comment]
@duggiefresh Anything I can help you with on this PR?

**Comment by oesgalha** [comment]
Any updates on this PR? Can I help on anything? This feature would be handy. :)

**Comment by duggiefresh** [comment]
@oesgalha please feel free to own the PR :)

Thanks for checking in

**Pull request closed without merging**
