### PR TITLE
Remove extra space

### PR DESCRIPTION
**Pull request by joemasilotti**
Code formatting.

### CODE REVIEW

**Comment by eileencodes** [comment]
Thanks for the PR @joemasilotti! We don't accept pull requests that are cosmetic changes (removing whitespace, changing all the hash rockets to the new hash syntax, etc). If you were to refactor something else in this method you could remove the whitespace, but we won't merge commits that are just adjusting whitespace because it makes traversing the git history harder.

**Comment by joemasilotti** [comment]
Gotcha, thanks for the explanation! I was reading through the code and it caught my eye.

For future readers and potential contributors, it might make sense to add this to the [contribution guides](https://github.com/rails/rails/blob/master/CONTRIBUTING.md) that are referenced when opening a new PR.

**Comment by eileencodes** [comment]
We do mention it here http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#write-your-code

Do you want to take a shot at adding it to the other version?

**Comment by joemasilotti** [comment]
Submitted!

**Pull request closed without merging**
