### PR TITLE
CI against PostgreSQL 10

### PR DESCRIPTION
**Pull request by yahonda**
### Summary

This pull request should enable CI against PostgreSQL 10.  Although I have not tested this pull request in advance since Rails unit tests cannot run on forked Rails.

This pull request would help to test #31336
Also, there has been some PostgreSQL 10 support which should be tested:

Refer https://github.com/travis-ci/travis-cookbooks/pull/923#issuecomment-366132082 and https://docs.travis-ci.com/user/database-setup/#Using-a-different-PostgreSQL-Version how to run PostgreSQL at Travis CI.

### CODE REVIEW

**Comment by yahonda** [comment]
Looks like PostgreSQL 10 use port 5433.  Active Record unit tests expect it is 5432 by default. Let me take a look at how to use non-default port number for Active Record unit tests for PostgreSQL.

**Comment by matthewd** [comment]
Without looking properly, a quick note: this could get tricky, because I guess the package isn't specifically configured for 5433, but is instead [at package install time] automatically picking the next available port after 5432 (because that's already taken by the also-installed [?] 9.x instance).

**Comment by yahonda** [comment]
Thanks for the information. 

Compared Travis CI log files between PostgreSQL 9.6 and PostgreSQL 10 and found:

- Both attempt to shut down all PostgreSQL versions and startup the PostgreSQL.
- Both connect to port 5432 and 5433. Unfortunately, the STDOUT and STDERR are redirected to /dev/null I do not know if these commands are successfully finished or not.

Then I assume only one PostgreSQL server is up and port 5433 is explicitly configured for PostgreSQL 10 but not sure.

* PostgreSQL 9.6 https://travis-ci.org/rails/rails/jobs/390974258

```
Starting PostgreSQL v9.6
1.35s$ sudo service postgresql stop
 * Stopping PostgreSQL 9.2 database server
   ...done.
 * Stopping PostgreSQL 9.3 database server
   ...done.
 * Stopping PostgreSQL 9.4 database server
   ...done.
 * Stopping PostgreSQL 9.5 database server
   ...done.
 * Stopping PostgreSQL 9.6 database server
   ...done.
2.28s$ sudo service postgresql start 9.6
 * Starting PostgreSQL 9.6 database server
   ...done.
0.92s$ sudo -u postgres createuser -s -p 5432 travis &>/dev/null
0.56s$ sudo -u postgres createdb -O travis -p 5432 travis &>/dev/null
0.06s$ sudo -u postgres createuser -s -p 5433 travis &>/dev/null
0.06s$ sudo -u postgres createdb -O travis -p 5433 travis &>/dev/null
```

* PostgreSQL 10
https://travis-ci.org/rails/rails/jobs/390762435

```
Starting PostgreSQL v10
0.61s$ sudo service postgresql stop
 * Stopping PostgreSQL 10 database server        
 * Stopping PostgreSQL 9.2 database server        
 * Stopping PostgreSQL 9.3 database server        
 * Stopping PostgreSQL 9.4 database server        
 * Stopping PostgreSQL 9.5 database server        
 * Stopping PostgreSQL 9.6 database server       
2.43s$ sudo service postgresql start 10
 * Starting PostgreSQL 10 database server       
0.05s$ sudo -u postgres createuser -s -p 5432 travis &>/dev/null
0.05s$ sudo -u postgres createdb -O travis -p 5432 travis &>/dev/null
0.07s$ sudo -u postgres createuser -s -p 5433 travis &>/dev/null
0.38s$ sudo -u postgres createdb -O travis -p 5433 travis &>/dev/null

```

This document also says`PGPORT=5433` .

https://docs.travis-ci.com/user/database-setup/#Using-a-different-PostgreSQL-Version

```
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433
```

**Comment by yahonda** [comment]
Now CI against PostgreSQL 10 is green by replacing port number from 5433 to 5432 and restarting PostgreSQL 10 service.

**Comment by yahonda** [comment]
The CI failure has been addressed. All of CI are green now.

**Pull request merged**
