### PR TITLE
Updating Query Tracer github repository

### PR DESCRIPTION
**Pull request by thiagopradi**
Hi Folks,

This PR updates the Query Tracer link to an updated version of the gem. This version works with Rails 3+ (Also, it works with Rails 4+).

Thiago

### CODE REVIEW

**Comment by arthurnn** [comment]
We use https://github.com/basecamp/marginalia for this, which works pretty great.

**Comment by tchandy** [comment]
@arthurnn I can update the documentation to include both links. It's just that the linked repository only works for Rails 2.x and needed to be updated.

**Comment by arthurnn** [comment]
marginalia has a different functionality from what you are replacing, i just realized that now.
Marginalia is to add a log on the DB level, and this adds a log on the rails logger level.
I guess it is fine to just replace the link for now.
thanks

**Comment by tchandy** [comment]
Thanks @arthurnn ! :)

**Pull request merged**
