### PR TITLE
Removes mandatory arguments from AR exceptions

### PR DESCRIPTION
**Pull request by rwz**
Follow up on https://github.com/rails/rails/issues/21474

This PR makes all descendants of AR::ActiveRecordError instantiate with no arguments.

### CODE REVIEW

**Comment by egilburg** [comment]
WDYT of a pattern like:

```ruby
message = "Some error"
message << " because of #{record}"

super(message)
```

This will reduce duplication and make messages more consistent whether or not the record is provided.

**Comment by rwz** [comment]
> This will reduce duplication and make messages more consistent whether or not the record is provided.

**Comment by eileencodes** [comment]
Thanks for the PR! There are a few things that I think need to be addressed before I can merge this.

* Since we're already touching all this code it seems punctuation was and is inconsistent. Can you make all these sentences end with a period (except for the ones that should end with a question mark of course).
* Can you squash your commits? Let me know if you're unsure how to do that.
* Can you update your commit message to explain why you're making this change and the benefits so we don't need to come back to github and read another issue to find out?

Thanks!

**Comment by rwz** [comment]
@eileencodes done

**Comment by eileencodes** [comment]
Looks good, thanks! :smile:

**Pull request merged**
