### PR TITLE
Specify mysql engine on creation

### PR DESCRIPTION
**Pull request by Intrepidd**
I merged #8242 so it can be applied cleanly

I didn't squash because I don't want @kenmazaika 's contribution to be lost, and he does not seem to want to merge this himself.

Thanks

### CODE REVIEW

**Comment by kenmazaika** [comment]
Thanks for picking up the work on this, @Intrepidd! :)  Super appreciated.

**Comment by repinel** [comment]
Is the request still valid? @Intrepidd, are you working on it?

**Comment by Intrepidd** [comment]
This PR is stale and I don't have the time to work on it at the moment. There was too many questions, help from a core team member would be really beneficial but I'm not sure if lots of people need this feature.

**Comment by kenmazaika** [comment]
Hehe.  Same thing happened to me with #8242, @Intrepidd

**Comment by kamipo** [comment]
@repinel @Intrepidd @kenmazaika #17569 was merged, the PR contains the feature that ENGINE name specifying.

**Comment by rafaelfranca** [comment]
Thank you for the pull request. It is now possible with the `options` parameter to create table. `create_table :foo, options: "ENGINE=MyISAM"`

**Pull request closed without merging**
