### PR TITLE
remove unused `RedirectBackError` class

### PR DESCRIPTION
**Pull request by y-yagi**
Follow up to 333bfd896e87862cece95deb1ef88132d5f54ba8

### CODE REVIEW

**Comment by arthurnn** [comment]
thanks

**Comment by matthewd** [comment]
@arthurnn we should probably deprecate this

**Comment by arthurnn** [comment]
@matthewd as far as I understood, it was deprecated before https://github.com/rails/rails/commit/333bfd896e87862cece95deb1ef88132d5f54ba8 , and now it is just removed.

**Comment by matthewd** [comment]
My worry is that someone who was just rescuing the exception wouldn't've previously seen the deprecation. But as there isn't much more information for us to give them (e.g., a new name for the constant), on second thought this is probably fine.

**Pull request merged**
