### PR TITLE
Use `squish` rather than `strip_heredoc`

### PR DESCRIPTION
**Pull request by kamipo**

### CODE REVIEW

**Comment by kaspth** [comment]
Thanks, but `strip_heredoc` is the preferred approach and this seems a cosmetic commit ❤️

**Comment by kamipo** [comment]
Originally, this error message was written by `\` in #25241. Not intended to include a break line.

```ruby
        raise ActiveRecordError,
          "cannot touch on a new or destroyed record object. Consider using " \
          "persisted?, new_record?, or destroyed? before touching"
```

This PR fixes to inspect the error.

Before:

```
$ ARCONN=sqlite3 bundle exec ruby -w -Itest test/cases/touch_later_test.rb -n test_touch_laster_raise_if_non_persisted
/Users/kamipo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/rubygems_integration.rb:468: warning: method redefined; discarding old find_spec_for_exe
/Users/kamipo/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems.rb:241: warning: previous definition of find_spec_for_exe was here
Using sqlite3
Run options: -n test_touch_laster_raise_if_non_persisted --seed 17655

# Running:

#<ActiveRecord::ActiveRecordError: cannot touch on a new or destroyed record object. Consider using
persisted?, new_record?, or destroyed? before touching
>
.

Finished in 0.026475s, 37.7715 runs/s, 75.5430 assertions/s.

1 runs, 2 assertions, 0 failures, 0 errors, 0 skips
```

After:

```
$ ARCONN=sqlite3 bundle exec ruby -w -Itest test/cases/touch_later_test.rb -n test_touch_laster_raise_if_non_persisted
/Users/kamipo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/rubygems_integration.rb:468: warning: method redefined; discarding old find_spec_for_exe
/Users/kamipo/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems.rb:241: warning: previous definition of find_spec_for_exe was here
Using sqlite3
Run options: -n test_touch_laster_raise_if_non_persisted --seed 45541

# Running:

#<ActiveRecord::ActiveRecordError: cannot touch on a new or destroyed record object. Consider using persisted?, new_record?, or destroyed? before touching>
.

Finished in 0.026327s, 37.9838 runs/s, 75.9676 assertions/s.

1 runs, 2 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by kamipo** [comment]
```diff
--- a/activerecord/test/cases/touch_later_test.rb
+++ b/activerecord/test/cases/touch_later_test.rb
@@ -12,9 +12,10 @@ def test_touch_laster_raise_if_non_persisted
     invoice = Invoice.new
     Invoice.transaction do
       assert_not invoice.persisted?
-      assert_raises(ActiveRecord::ActiveRecordError) do
+      e = assert_raises(ActiveRecord::ActiveRecordError) do
         invoice.touch_later
       end
+      p e
     end
   end
 
```

**Comment by kamipo** [comment]
https://github.com/rails/rails/blob/v5.0.0/activerecord/lib/active_record/reflection.rb#L409-L413

```ruby
          raise ArgumentError, <<-MSG.squish
            The association scope '#{name}' is instance dependent (the scope
            block takes an argument). Preloading instance dependent scopes is
            not supported.
          MSG
```

**Comment by kaspth** [comment]
Lots of our other error messages use `strip_heredoc` and contain line breaks. I don't understand what makes these so different?

**Comment by matthewd** [comment]
@kaspth got some examples? I only see a few, all of which are using the line breaks for structure, rather than word wrapping.

OTOH, I don't like this message anyway, so... :confused:

**Comment by kamipo** [comment]
See also #23838.

**Comment by rafaelfranca** [comment]
Backported in 6c0fd9f

**Comment by kaspth** [comment]
@matthewd right you are, that was used for structure.

All good here 👍

**Pull request merged**
