### PR TITLE
Update documentation for strong parameters

### PR DESCRIPTION
**Pull request by bquorning**
Two changes to the `ActionController::Parameters` documentation:
1. The examples showing `#require` accepting two arguments were wrong – you have to wrap them in an array. See #19565 and eefb6db4a92dd87baac257e92197671421e48d9b.
2. `ActionController::Parameters` has an `#inspect` method now, and the documentation should reflect that. See #23732,

r? @fxn

### CODE REVIEW

**Comment by maclover7** [comment]
Can you squash your commits, please?

**Comment by bquorning** [comment]
Sure. I just thought they were different enough to warrant two commits.

**Comment by maclover7** [comment]
:+1: Thank you for your contribution!

**Comment by maclover7** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
