### PR TITLE
Update asset_pipeline.md

### PR DESCRIPTION
**Pull request by kentendo**
Should be ...
config.assets.serve_static_files = true
Wasted about an hour on this.

### CODE REVIEW

**Comment by sgrif** [comment]
Thanks. Please add `[ci skip]` to your commit message in the future if you're only changing documentation

**Comment by kentendo** [comment]
Oh snap, np.Thanks dude.

**Comment by jonatack** [comment]
Question: What is the basis for this change? I could be missing something, but I don't find it in the Rails master codebase or documented anywhere.

**Comment by kentendo** [comment]
I was trying to serve some static images.
The docs say to do this...

`config.serve_static_files = true`

...but that doesn't work, this does though...

`config.assets.serve_static_files = true`

**Comment by rafaelfranca** [comment]
This is not right. This config [is in the root config option](https://github.com/rails/rails/blob/cfb371e96a2789790359ec1db779df490fd253d6/railties/lib/rails/application/configuration.rb#L16) not in the assets option. I'm revirting, thanks

**Comment by rafaelfranca** [comment]
Reverted in 172c25e7b62b4b7f7c8ef7c7174ed4d17c8dacfe

**Pull request merged**
