### PR TITLE
Run CI for ActionPack on JRuby

### PR DESCRIPTION
**Pull request by gaurish**
actionpack is green on local. Checking to see if this goes green on CI too. 

related: #11700

cc: @bf4 @rafaelfranca

### CODE REVIEW

**Comment by gaurish** [comment]
```
Finished in 114.025057s, 41.8768 runs/s, 116.3428 assertions/s.
4775 runs, 13266 assertions, 0 failures, 0 errors, 9 skips
You have skipped tests. Run with --verbose for details.
Rails build finished successfully
```

Ok, the build is green but travis isn't recognizing this for some reason.  Investigating why.

**Comment by gaurish** [comment]
Does anyone know how do I cancel a running build?

**Comment by gaurish** [comment]
Yay, I have gotten the build green. finally :v:

**Comment by kares** [comment]
@gaurish very najs, thanks. next, let us :pray: for `as`.

**Comment by gaurish** [comment]
sure but can this be merged?

**Comment by rafaelfranca** [comment]
This is really slow and it is giving us a lot of timeout in travis. I'll revert until we have 9.0.5.0 cached in travis.

**Comment by bf4** [comment]
@rafaelfranca what do you think about running JRuby on a different CI service? https://github.com/rails/rails/pull/23499#issuecomment-185027289

**Comment by rafaelfranca** [comment]
@bf4 that looks like a good option to me.

**Pull request merged**
