### PR TITLE
Simplify AC::Parameters#permitted_scalar_filter.

### PR DESCRIPTION
**Pull request by tgxworld**

### CODE REVIEW

**Comment by rafaelfranca** [comment]
This is less code but harder to follow, so I can't see this as simplification.

There are any advantage in the performance side to justify making the code harder to read?

**Comment by tgxworld** [comment]
@rafaelfranca No obvious advantage in the performance side aside from not having to call `has_key?(key)`. I noticed that since we were already `grep`ing the keys, we can just reduce the line of code. Your call now :smile_cat:

**Comment by rafaelfranca** [comment]
Right. I prefer to keep the code as it is. Easier to read than trying to understand the regexp.

Thank you for the pull request.

**Comment by tgxworld** [comment]
@rafaelfranca No worries. I fully understand :smile: Thanks for reviewing!

**Pull request closed without merging**
