### PR TITLE
Dockerfile binfile fixups; primarily for Windows users

### PR DESCRIPTION
**Pull request by rubys**
### Motivation / Background

This Pull Request has been created because Rails applications created on Windows will fail to deploy using the generated Dockerfile as the binstubs they have won't work on Linux.

### Detail

This Pull Request will emit a Dockerfile RUN instruction, when needed, that will make the following conversions:

 * chmod +x
 * CRLF => LF
 * ruby.exe => ruby

If Rails new is run on a MacOS or Linux machine, no fixups are required or emitted to the Dockerfile.

### Additional information

On a new Windows 11 machine with Ruby installed with RubyInstaller, `rails new` produces binstubs with shebang lines that look like the following:

```
#!/usr/bin/env ruby.exe
```

These lines won't work on Linux machines.  Additionally, with NTFS, I don't have executable bits, so these scripts won't run anyway.  Finally, Windows users always seem to find ways to insert windows CRLF line endings into these files and that is also a source of failure.
### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`

I don't know how to create tests for "Ruby was installed on a Windows 11 machine using Ruby Installer".  What I will say is that I have tested on a MacOS machine and verified that no sed commands were added to the Dockerfile; I have tested on a Windows machine and produced the following:

```
# Adjust binfiles to be executable on Linux
RUN chmod +x bin/* && \
    sed -i "s/\r$//g" bin/* && \
    sed -i 's/ruby\.exe$/ruby/' bin/*
```

And finally, I have tested those command on a Linux machine to verify that they perform the correct modifications.

No changelog entries are required for this change.

### CODE REVIEW

**Comment by rubys** [comment]
attn: @dhh

buildkit actioncable timeout appears unrelated.

On the topic of binstubs, a question for you: why does the Dockerfile not use binstubs for running assets:precompile?

```
RUN SECRET_KEY_BASE_DUMMY=1 bundle exec rails assets:precompile
```

**Comment by dhh** [comment]
Hmm, I take that this is something you've seen repeatedly at Fly? Don't love all these specific mechanics living in the app generator like this. But also, shouldn't bar Windows/RubyInstaller folks from enjoying an easy path. Is everything otherwise working fully with RubyInstaller, Docker, and Fly out of the box? Or are we just patching a small hole in an otherwise leaky bucket?

Should use the binstub instead of bundle exec. Not sure why that's there.

**Comment by rubys** [comment]
Starting with the comment that requires action:

> Don't love all these specific mechanics living in the app generator like this.

Where should specific mechanics live?  Overall, I'd like to see less logic live in the template.  As an example, I'd like to compute the list of Debian packages that need to be installed before invoking the template.

> Hmm, I take that this is something you've seen repeatedly at Fly?  But also, shouldn't bar Windows/RubyInstaller folks from enjoying an easy path. Is everything otherwise working fully with RubyInstaller, Docker, and Fly out of the box? Or are we just patching a small hole in an otherwise leaky bucket?

Windows is definitely the problem child here.  Whenever I can I encourage WSL2 where things actually are pretty good.  And, yes, we do see Windows developers at Fly, and yes they won't have a good experience unless this is addressed.

And, yes, this is it.  Well, until I rule out any problems with setting the yarn version, but that either will just work or will be small.  Everything binary-ish is already in the .dockerignore.  binstubs are the only non-binary platform specific files.

> Should use the binstub instead of bundle exec. Not sure why that's there.

Cool.  I'll fix.

**Comment by dhh** [comment]
> Where should specific mechanics live? Overall, I'd like to see less logic live in the template. As an example, I'd like to compute the list of Debian packages that need to be installed before invoking the template.

It's more the peculiar mechanics needed. Is there not a way to fix this such that the binstubs become cross platform? We can't somehow make "ruby" work on windows without "ruby.exe"?

Anyway, do appreciate you looking out for the Windows crowd. They don't get a lot of attention otherwise! Just dislike having to carry these fixing warts.

**Comment by rubys** [comment]
> Is there not a way to fix this such that the binstubs become cross platform?

Sadly, no.  At a minimum, the files won't be marked executable, and won't work on Linux unless they are.

I still haven't figured out how `\r` is getting into those files, perhaps it is a [git setting](https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings), or perhaps users can't resist the temptation to use a text editor.  But an example of the aftermath: https://community.fly.io/t/rails-5-2-3-windows-10-error-ruby-r-no-such-file-or-directory/8584 .

Once fixups are needed anyway, the  small matter of`.exe` don't quite seem worth changing.  I haven't verified that the following is the *only* place shebangs are created, but allowing the developer to control what is placed there seems intentional:

https://github.com/rails/rails/blob/19a6979cfc134951755a6b6fc311276ce0b98f3c/railties/lib/rails/generators/base.rb#L397-L411

Even ignoring the option, `File.basename(Thor::Util.ruby_command)` seems better than hardcoding `ruby`.  Personally, I'd rather not mess with something that has been working and needs to work in environments that we don't control, and focus on making what adjustments are necessary to work in an environment that we do control.

> Anyway, do appreciate you looking out for the Windows crowd. They don't get a lot of attention otherwise! Just dislike having to carry these fixing warts.

Hopefully they will eventually get the hint and jump on the WSL2 bandwagon.  Meanwhile a fixing wart is necessary, and so the focus needs to be on containment.  I've done what I can to make sure that the adjustments are only added when needed.  Those of us on MacOS and Linux won't ever see this.

**Pull request merged**
