### PR TITLE
Update w3c_validtors for Ruby 3 compatibility

### PR DESCRIPTION
**Pull request by utilum**
This leaves us waiting for google-api-client and listen to be released

https://github.com/googleapis/google-api-ruby-client/issues/907
https://github.com/guard/listen/pull/490

And for redis-namespace fix and release

https://github.com/resque/redis-namespace/pull/175

### CODE REVIEW

**Comment by eugeneius** [comment]
It looks like we're still waiting on https://github.com/w3c-validators/w3c_validators/pull/48.

**Comment by utilum** [comment]
Right!
Sorry, I missed that. When I patch the other gem versions locally and `bundle install` w3c_validators reverts to v. 1.2 which does not require a Ruby version. 

Shall I close this for now?

**Comment by kamipo** [comment]
Can you update the w3c_validators version to 1.3.6?

https://rubygems.org/gems/w3c_validators
https://github.com/w3c-validators/w3c_validators/releases/tag/1.3.6

That version includes https://github.com/w3c-validators/w3c_validators/pull/48.

**Comment by utilum** [comment]
Done. Thank you.
`google-api-client` 0.44.2 has been released in the mean time, also fixes this issue. Shall I add it here? Open a separate pull?
Either way, this would leave us waiting for `listen` and `redis-namespace`.

**Comment by kamipo** [comment]
If `google-api-client` is released, please include it in this PR, then I'll (squash) merge (like 858e429bcafd0f29a0d728bcd7586743ed0d9a6c).

Personally I don't think it's worth updating one by one commits, it will not be buildable in Ruby 3 until all gems have been updated.

**Comment by utilum** [comment]
Done.
But I see your point. Perhaps better to leave this open as a WIP and only merge when all gems have been updated?
Or close and ditto?

**Comment by kamipo** [comment]
I'll merge this anyway since `listen` and `redis-namespace` are less frequently released.

https://rubygems.org/gems/listen
https://rubygems.org/gems/redis-namespace

**Pull request merged**
