### PR TITLE
Display link to Rails upgrade guide at the end of `rails app:update` task.

### PR DESCRIPTION
**Pull request by prathamesh-sonpatki**
Looks like this - 

``` sh
       exist  bin
   identical  bin/bundle
   identical  bin/rails
   identical  bin/rake
   identical  bin/setup
   identical  bin/update

After this, check Rails upgrade guide at http://guides.rubyonrails.org/upgrading_ruby_on_rails.html for more details about upgrading your app.
```

### CODE REVIEW

**Comment by prathamesh-sonpatki** [comment]
@rafaelfranca Thoughts about this one? We can also add a link to release notes.

**Comment by rafaelfranca** [comment]
Backported in aabbd8b. Sadly I missed it for the release :(

**Comment by prathamesh-sonpatki** [comment]
No problem 😃

**Pull request merged**
