### PR TITLE
Do not add master key when `RAILS_MASTER_KEY` env specified

### LINKED ISSUE #31917: `bin/rails credentials:edit` is ignoring the ENV['RAILS_MASTER_KEY']
It seems that `bin/rails credentials:edit` ignores the Rails master key if it's set via `ENV` var rather than `config/master.key`.

### Steps to reproduce

1. Generate a new Rails app
1. `cd <new_app> && cat config/master.key` prints `8fe10c494a635b461cfe23bf24999433`
1. `bin/rails credentials:show` prints the contents, as expected.
1. `bin/rails credentials:edit` opens editor.
     On save and close of file we see `New credentials encrypted and saved.`
1. `rm config/master.key`
1. `bin/rails credentials:show` reports `Missing master key to decrypt credentials. See bin/rails credentials:help`
1. `RAILS_MASTER_KEY=8fe10c494a635b461cfe23bf24999433 bin/rails credentials:show` prints the contents, as expected.
1. `RAILS_MASTER_KEY=8fe10c494a635b461cfe23bf24999433 bin/rails credentials:edit` generates a new key:

```
Adding config/master.key to store the master encryption key: bbfeef5bedd12d45078725d8bf1a7e33

Save this in a password manager your team can access.

If you lose the key, no one, including you, can access anything encrypted with it.

      create  config/master.key
```

### Expected behavior
`bin/rails credentials:edit` should respect the `RAILS_MASTER_KEY` ENV Var.

### Actual behavior
Removing the `config/master.key` and invoking with an ENV var ignores the ENV Var:

```
$ RAILS_MASTER_KEY=8fe10c494a635b461cfe23bf24999433 bin/rails credentials:edit
Adding config/master.key to store the master encryption key: bbfeef5bedd12d45078725d8bf1a7e33

Save this in a password manager your team can access.

If you lose the key, no one, including you, can access anything encrypted with it.

      create  config/master.key

New credentials encrypted and saved.
```

### System configuration
**Rails version**: `5.2.0.rc1`

**Ruby version**: `2.5.0`

### PR DESCRIPTION
**Pull request by y-yagi**
Fixes #31917

### CODE REVIEW

**Comment by y-yagi** [comment]
cc @kaspth

**Comment by stevenharman** [comment]
@y-yagi Assuming this is merged, can we expect a back-port to the `5-2-stable` branch for the next RC?

**Review by kaspth — APPROVED** [review]
👍, don't forget to backport to 5-2-stable :)

**Comment by y-yagi** [comment]
Sure!  Backport: dc09b9952115e291360949a1643b9800bd7c0e22

**Pull request merged**
