### PR TITLE
Add error message value formatter to the numericality validator

### PR DESCRIPTION
**Pull request by joaomangilli**
### Summary

Sometimes, we need to format the value being shown in an error message in the numericality validator (like `greater_than_or_equal_to: 25`, we want to format the number 25 to something like 25.00) to match a monetary value or something like that. 

This PR opens an option to format that value the way you need it.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Makes sense. Can you add a CHANGELOG entry?

**Comment by joaomangilli** [comment]
@rafaelfranca done

**Comment by jonathanhefner** [comment]
@joaomangilli Do you have a use-case in mind that would benefit from `:value_format` instead of [specifying a `:message` `Proc`](https://guides.rubyonrails.org/v6.1/active_record_validations.html#message)?  A `:message` `Proc` [can access the validation value via `:count`](https://guides.rubyonrails.org/i18n.html#error-message-interpolation), e.g.:

```ruby
validates_numericality_of :approved, greater_than: 50000, 
  message: -> (record, data) { "must be greater than #{do_something(data[:count])}" }
```

Perhaps this could be improved by allowing the `:message` `Proc` to modify and return the `data` Hash, thus still relying on the framework to perform interpolation?  e.g.:

```ruby
validates_numericality_of :approved, greater_than: 50000, 
  message: -> (record, data) { data.merge(count: do_something(data[:count])) }
```

**Comment by joaomangilli** [comment]
@jonathanhefner thanks! I think this is a best way to solve the problem. This can pave the way for solving more problems. I'll make the change.

**Comment by jonathanhefner** [comment]
@joaomangilli To clarify: I'm not sure if returning a Hash from a `:message` `Proc` is the best way to solve this.  I was just brainstorming out loud. :smiley:

Another possibility might be using [`Errors#generate_message`](https://api.rubyonrails.org/v6.1/classes/ActiveModel/Errors.html#method-i-generate_message) or a similar method.  For example, if the `data` Hash included the non-humanized attribute name and the error type, you could write something like:

```ruby
validates_numericality_of :approved, greater_than: 50000, message: -> (record, data) do 
  data[:count] = do_something(data[:count])
  record.errors.generate_message(data[:attribute_symbol], data[:type], data)
end
```

**Comment by joaomangilli** [comment]
@jonathanhefner sorry, I wanted to say that it looks like a ** better ** (not the best) solution. 

But the more I think about it the more I think that this validator should offer a native option to format the count value, without the need to deal with the message. 

I know that this value is part of the message, but I think it makes sense to pass this value already formatted, so we don't have to deal with it in the message. 

Because to do this in the message, we need to change the method of the message to offer more options or flexibility and it still won't solve the problem, as we will still need to use this method to "interpolate" the formatted value in the message.

What do you think?

**Comment by joaomangilli** [comment]
@rafaelfranca can we go ahead with this?

**Pull request closed without merging**
