### PR TITLE
Move ActionMailer options to an initializer

### PR DESCRIPTION
**Pull request by lucascaton**
This Pull Request moves ActionMailer options to an initializer, which will contain most of the available options.

The goal here is to make the setup of a new app more straight forward.

This follows the way that assets options are now being initialized.

### CODE REVIEW

**Comment by senny** [comment]
What is the benefit of only having one set of options for all the environment? When I look at my applications I usually use different settings for every environment. I don't see much of a reason to combine that into an initializer. In the end, that's what the environment files are for.

/cc @rafaelfranca

**Comment by lucascaton** [comment]
@senny Thanks for replying. I always ended up creating a initializer for it anyway, because I usually share the same configs between the environments. And I've seen many people doing that as well.

Also, IMHO, to have all available options is way easier than check the documentation before doing something that most apps do (send emails), but it would be too much options to have in `config/application.rb`.

**Comment by matthewd** [comment]
> I usually use different settings for every environment

Agree.

And as the person who moved the asset configs, I'll note that we moved a very small subset of the asset-related options -- only those two that actually transcend environmental differences.

Even `config.assets.digest`, which is true everywhere by default these days, appears separately in `production.rb` and `development.rb` because it is reasonably likely for people to want them to diverge.

**Comment by lucascaton** [comment]
Ryan Bates used to do it Rails Casts: http://railscasts.com/episodes/206-action-mailer-in-rails-3.

Also, I've found 2 popular Rails example apps in Github and both are using the same config for both development and production environment:

* [rails-stripe-membership-saas - development](https://github.com/RailsApps/rails-stripe-membership-saas/blob/master/config/environments/development.rb#L27-L42)
* [rails-stripe-membership-saas - production](https://github.com/RailsApps/rails-stripe-membership-saas/blob/master/config/environments/production.rb#L74-L87)
* [rails3-bootstrap-devise-cancan - development](https://github.com/RailsApps/rails3-bootstrap-devise-cancan/blob/master/config/environments/development.rb#L16-L52)
* [rails3-bootstrap-devise-cancan - production](https://github.com/RailsApps/rails3-bootstrap-devise-cancan/blob/master/config/environments/production.rb#L64-L81)

**Comment by lucascaton** [comment]
IMHO, to have different configs for environments is the exception, which isn't following "convention over configuration". Please let me know your thoughts. Thanks.

**Comment by lucascaton** [comment]
Perhaps to add mailer credentials to `config/secret.yml` would be a better approach?

**Comment by rafaelfranca** [comment]
Thank you for the pull request. 

That if Rails.env is a smell that this config should be per environment. In development it also need to use a different configuration. What means that it is not an exception that the config are different per environment.

**Comment by lucascaton** [comment]
@rafaelfranca,

`# ActionMailer::Base.raise_delivery_errors` is commented because the default is `true`. We could get rid of that actually.

`ActionMailer::Base.delivery_method = :test` could be the only thing in `config/environments/test.rb`, as well as assets does with different `digest` options.

But I believe the rest of the file would be very useful.

**Comment by rafaelfranca** [comment]
The point is: You don't need any of that configuration on development or
test, you only need at production unless I'm missing something here.

**Comment by lucascaton** [comment]
Well, you need to send emails in development and staging, don't you? :smile:

**Comment by rafaelfranca** [comment]
I don't think it is a good idea to send emails in development. You should
use the logged message that Rails automatically does. And if you need to
test the email interface use the mail previews.

And about staging, in my opinion is a bad practice to have different
environment file instead of using production. Even if you would use you
still don't need the mail configuration in development and test.

**Pull request closed without merging**
