### PR TITLE
ActionMailer - wait until after initialization before using config

### PR DESCRIPTION
**Pull request by Benjamin-Dobell**
### Summary

Wait until initialization has completed before we assign `config.action_mailer` to `ActionMailer::Base`.

Eager loading of `app/mailers` must also be disabled.

### Other Information

The ActionMailer railtie looks at `config.action_mailer` and assigns these options to `ActionMailer::Base`. However, it was previously doing so as soon as soon as `ActionMailer` was loaded (`ActiveSupport.on_load(:action_mailer)`).

We now wait for initialization to complete (`ActiveSupport.on_load(:after_initialize)`) _as well_ as the `ActionMailer` being loaded.

This is an important change because `ActionMailer` (and its config) is explicitly designed to be extensible, specifically ActionMailer allows third-party gems to register additional "delivery methods".

Delivery methods can be registered with third-party Railtie by using:

```ruby
class Railtie < ::Rails::Railtie
  initializer "foo_mail.register_delivery_method" do
    ActionMailer::Base.add_delivery_method :foo, FooMailer
  end
end
```

or ideally:

```ruby
class Railtie < ::Rails::Railtie
  initializer "foo_mail.register_delivery_method" do
    ActiveSupport.on_load(:action_mailer) do
      add_delivery_method :foo, FooMailer
    end
  end
end
```

`add_delivery_method` adds support for `ActionMailer::Base.foo_settings` and `config.action_mailer.foo_settings` (https://github.com/rails/rails/blob/master/actionmailer/lib/action_mailer/delivery_methods.rb#L51).

However, calling `add_delivery_method` requires `ActionMailer` to be loaded, and _prior_ to this commit, the config would already have been assigned on `ActionMailer::Base`, so there's no opportunity to do:

```ruby
config.action_mailer.foo_settings = {
    foo_auth: 'bar'
} 
```

If you were previously to put the above in your environment config, you'd get an error because when `ActionMailer` when `ActionMailer` is eager loaded in production, third-party gems haven't run their initializers so `undefined method 'foo_settings=' for ActionMailer::Base:Class` is raised (e.g. https://github.com/mailgun/mailgun-ruby/issues/104).

Instead, if you were to move your logic into `app/initializers/foo_mail.rb` e.g.

```ruby
Rails.application.configure do
  config.action_mailer.delivery_method = :foo
  config.action_mailer.foo_settings = {
      api_key: ENV['FOO_API_KEY'],
      domain: ENV['FOO_DOMAIN'],
  }
end
```

this _silently_ fails _in production_ (with eager loading enabled), because we're (without this PR) assigning the config _after_ `ActionMailer` has been loaded (and the config copied across), so although we've set the config it is never used and out of sync with `ActionMailer::Base`, which for example still returns `:smtp` for `ActionMailer::Base.delivery_method`, even though `Rails.application.config.action_mailer.delivery_method` correctly returns `:foo`.

This commit resolves the issue by ensuring we wait until all initializers have run _before_ settings up `ActionMailer::Base` with options from `action_mailer.config`.

We can now in `app/initializers/foo_mailer.rb` do:

```ruby
ActiveSupport.on_load(:action_mailer) do
  Rails.application.configure do
      config.action_mailer.delivery_method = :foo
      config.action_mailer.foo_settings = {
        api_key: ENV['FOO_API_KEY'],
        domain: ENV['FOO_DOMAIN'],
      }
  end
end
```

### CODE REVIEW

**Comment by Benjamin-Dobell** [comment]
Hmm, will investigate the test failures in the next few days and report back.

**Comment by Benjamin-Dobell** [comment]
_Sigh!_ The app's `mailers` are eager loaded in production, so they subclass `ActionMailer::Base` before `ActiveSupport.on_load(:after_initialize)`, and hence before being configured (in this PR).

The`ActionMailer` design is in general highly problematic. There's probably a reason for it, but presumably it would make a lot more sense if it just read the config on demand (when creating mail) rather than differing in behavior when eager loading is enabled.

**Comment by rafaelfranca** [comment]
Yeah, we can't change the way configurations are loaded in the framework.

The correct way too add deliveries methods is using:

```
class Railtie < ::Rails::Railtie
  initializer "foo_mail.register_delivery_method" do
    ActiveSupport.on_load(:action_mailer) do
      add_delivery_method :foo, FooMailer
    end
  end
end
```

even if you always use this way it is not possible to set the `config.action_mailer.foo_settings`?

**Comment by Benjamin-Dobell** [comment]
Unfortunately, no it doesn't work, that will raise a missing method error because ‘add_delivery_method‘ is set to be called once ‘ActionMailer::Base‘ is loaded, which is too late.

Basically it's a catch 22, we need the ActionMailer loaded to add a delivery method, but we need the delivery method added before hand so the delivery method can be configured.

The approach I've taken in this PR is likely too major of a change. The alternative is to add `method_missing` method that matches `(.+)_settings=` and stores the hash, even though the delivery method is not available yet. It's a lot less invasive than this approach.

**Comment by Benjamin-Dobell** [comment]
Just to clarify the issue is eager loading. It *will* work in development because the gems initializer and hence its `on_load(:action_mailer)` hook gets called before the config is copied. However, in production (eager loading) ActionMailer is loaded before the gems initializer is called so the hooks get called in the reverse order an an error is raised.

**Comment by rafaelfranca** [comment]
In eager load `ActionMailer` is not loaded before the gems initializer. It only happens in the application Finisher so it is after all railties initializers are run.

Can you create an example application reproducing the issue? It would be good if you don't use any gem and instead build a rails plugin inline because the problem might be in the gem you are using.

**Comment by Benjamin-Dobell** [comment]
Closing this PR as the approach being taken is too major of a change e.g. disabling eager loading of `app/mailers`.

However, I've opened https://github.com/rails/rails/issues/35416 to document the issue and will try my hand at a less intrusive PR.

@rafaelfranca A example application (and a fake `foomailer` gem) reproducing the issue is available in the issue mentioned above.

**Pull request closed without merging**
