### PR TITLE
List available skip options in command line guide

### PR DESCRIPTION
**Pull request by yoones**
### Summary

Issues such as https://github.com/rails/rails/issues/36280 and https://github.com/rails/rails/issues/35484 are due IMHO to a lack of documentation regarding the skip options available when running `rails new` command. I suggest we add a list of options to the documentation.

### CODE REVIEW

**Comment by eileencodes** [comment]
I like this!

**Comment by omnilord** [comment]
What does it _mean_ to "skip javascript files"?  For example, I don't want Webpack, but I do want to use the old asset pipeline configuration to include javascript files from `app/assets/javascript/`.  Is there an undocumented option for --use-javascript-assets that skips webpack but DOES include javascript files?

**Comment by yoones** [comment]
@omnilord Webpacker is the default javascript asset pipeline in Rails 6, which means `--skip-javascript` will skip installing the default javascript asset pipeline (=> Webpacker).

It doesn't mean you can't put javascript in your application in another way. Since Sprockets is still present, you can use it as a javascript asset pipeline. You just have to create `app/assets/javascripts` which is still registered by default in `Rails.application.config.assets.paths` and use `javascript_include_tag` in your views.

_That being said, if it's not too painful to migrate your code to Webpacker, I would highly suggest you take the time to do that. Here are some good reasons why it's better to keep up with Rails evolutions: https://www.youtube.com/watch?v=jxBAkhaRtNg_

**Comment by omnilord** [comment]
Most of my applications are ERB and don't rely extensively on massive quantities of transpiled cruft to function properly.  This makes webpacker undesirable as it adds significant overhead for no benefit.  The only things I typically bring in are jQuery, bootstrap, and font-awesome, and most of my javascript is less than 50 lines to tie it all together, if I need any javascript at all (usually for some sort of bootstrap initializing or quick button wiring).  To require 150 MEGABYTES(!!!!) of webpack for 50 lines of Javascript is severely asinine.

Think of it this way.  Most applications built are akin to building a small house.  Webpacker is the construction company that moguls hire to build skyscrapers.  Small homes do not need 2000 construction works, 20 dumptrucks, 5 cement mixers, and 2 tower cranes to construct a simple house and most developers do not need webpacker to build their simple applications.  It is an unnecessary show of brute force via build tools.

To put my point in perspective, I ran `rails new` with both the full build and the skip flags (yes, you need both `--skip-javascript` and `--skip-webpack-install` to remove webpack entirely, it still runs webpacker install even with `--skip-javascript`.

```
$ time rails new full
real	0m42.337s
user	0m34.199s
sys	0m23.316s
$ du -chs full/
146M	full/
146M	total
```

```
$ rails new --skip-javascript --skip-webpack-install nojs
real	0m5.613s
user	0m4.561s
sys	0m0.877s
$ du -chs nojs
296K	nojs
296K	total
```

Webpacker installs an extra 145 Megabytes of cruft and takes 9x the time to setup.  That's just on the initialization.  How bad must it be when the application is being built to serve or when spring reloads it after editing something?

So, yes, I think there is a need for a `--use-javascript-sprockets-only` or whatever it was in the past to make sure the gems are included, the templates are put in place, and we can go on with our simple lives.

Rails was an oasis of happiness in a desert of technology WTFs.  With the addition of Webpacker, Rails is just another WTF because Webpacker is the ultimate WTF.  I feel like my trust has been betrayed by the inclussion of webpack in what was a very pure thing prior to Rails 6.

**Comment by jakeNiemiec** [comment]
@omnilord, I [made a similar post](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/rubyonrails-talk/ST2Z8S85CFM/5479TroGIgAJ) a few months ago on the mailing list (I come from the JS/vanilla-webpack side of things). The best thing we can do is post constructive concerns to the https://github.com/rails/webpacker repo. [This happened back in 2017](https://blog.shakacode.com/webpacker-lite-why-fork-webpacker-f0a7707fac92), and webpacker is now 200+% better for it.

Webpacker has been around since 2016. After the initial push into the spotlight with rails 6, I think it will get better with more attention (like in 2017).

Switching tracks...
<hr>

### Let me do for you what no one did for me back then: answer the question "webpacker, why are you the way that you are?"

> Webpacker installs an extra 145 Megabytes of cruft and takes 9x the time to setup.

Here is a visualization of a fresh app with 1 controller 😱 (I am on OS X):
image

You will see that `node_modules` and `public` are the largest contributors. Lucky you said something, `public` is not deleting stale JS and .map builds as it should. I'll be looking into that 😅. If you think the build files are too big, they shrink down to K for production. 

**Aside**: Dev builds have nifty little features that enable you to do things **like style mapping**! Ever wonder if a style comes from a vendor or your own stylesheet?
image
image
When I click one of those lines, it will open up the file in my IDE to that line. You can even edit the .scss files from within the chrome dev tools. This works the same for the JS console.

Now for `node_modules` @ 61.6 M. The discrepancy shrinks when you account for the fact that your `296K` did not account for the size of gems. `node_modules` is the `/lib/ruby/gems` of the JS world...and it must be a sibling in the file system to your `package.json` file.

```bash
du -chs /Users/username/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems
1.4G    /Users/username/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems
1.4G    total
```

Since I am ranting, let's see how that `61.6 M` is put to use:
- `node-sass` 4.9M: since [`ruby-sass` is end-of-life](http://sass.logdown.com/posts/7081811), `node-sass` is a popular replacement. The size will change based off the bindings your OS needs. It just wraps libsass (C++), and it's distributed with the source code.
-`terser`4.6M: a better version of the uglifyJS gem.
-`@babel`2.4M: everything you need to target older platforms and use the latest JS features.
- `fsevents`1.9M: webpack needs to be able to watch the file system in order to recompile in the background
- `node-forge`1.6M: TLS protocol in JS used for proxy magic (so you leave running webpack to rails)
- `node-gyp`1.6: needed by `node-sass` for the OS binding stuff
- `postcss`1.3M: same as babel, but for css & more. Replaces `autoprefixer-rails` gem
- But, for the remaining 40M: https://youtu.be/12LLJFSBnS4?t=18 (you can see [here](http://npm.anvaka.com/#/view/2d/%2540rails%252Fwebpacker%25404.0.0-rc.7) if you really want to know)

Hope this helps

**Comment by omnilord** [comment]
Comparing storage of node modules to gems is comparing apples and oranges.  Yes, in theory they do the same things, but in actuality they function _very_ differently.  Example, for Gems, you get one copy of each version and you can manage those versions very meticulously for security purposes.  With node modules, you get numerous copies of the same version strewn all around your projects.  If you need to truncate one version because it's been found to be a security problem, oh well, you'll never find them all.

And regarding storage:
424M	/Users/username/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems

Again, one location, one copy.  If you have 20 or 30 projects on your harddrive and each one has 150MBs default, then you start cramming more things in there, it's going to quickly fill up your 128GB SSD.

There is no good reason to have Webpack in a majestic monolith ecosystem.  I'm just going to have to find some other framework built for programmer happiness or fuck off programming entirely for the rest of my life.  This is the stuff that gives me nightmares and keeps me up at night.

**Comment by jakeNiemiec** [comment]
>If you need to truncate one version because it's been found to be a security problem, oh well, you'll never find them all.

I use to think this, but someone showed me how to force updated versions with `resolutions`: https://github.com/rails/webpacker/issues/2077#issuecomment-492476915

>With node modules, you get numerous copies of the same version strewn all around your projects...Again, one location, one copy. If you have 20 or 30 projects on your harddrive and each one has 150MBs default

Let me quell some of your nightmares, yarn uses symlinks to populate node_modules 👍. 

But even _that_ does not matter since `dependency unwinders` like [Yarn Plug’n’Play](https://www.freecodecamp.org/news/getting-rid-of-node-modules-with-yarn-plugn-play-a490e5e747d7/) and [npm tink](https://blog.npmjs.org/post/178027064160/next-generation-package-management) **will eliminate the need for a `node_modules` altogether** 🎉. I made an issue about this for https://github.com/rails/webpacker/issues/2112. I hope we can eliminate some friction with this.

I don't want to continue discussing here since it is **very off-topic**, but if you continue to have nodejs nightmares or want to discuss further: my email is listed on my profile.

**Comment by omnilord** [comment]
> I don't want to continue discussing here since it is very off-topic, but if you continue to have nodejs nightmares or want to discuss further: my email is listed on my profile.
Yes, I did go off on a tangent.

Back on topic:

what is the process for setting up a pre-rails6 asset pipeline using sprockets for javascript?  Is it literally just adding the usual files in `app/assets/javascripts/` and placing `<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>` in the appropriate layouts, or are there gems that need to be included explicitly?  Will ActionCables/ActiveStorage still work or has they been exclusively migrated to webpack?

**Comment by jakeNiemiec** [comment]
> what is the process for setting up a pre-rails6 asset pipeline using sprockets for javascript?

I am not too experienced with how rails used sprockets internally, so I can't answer that one; but I have seen other issues in passing that asked something similar: https://github.com/rails/rails/issues/35484 https://github.com/rails/rails/issues/36280

> or are there gems that need to be included explicitly? Will ActionCables/ActiveStorage still work

I think they will all still work since they still include both source and compiled versions: https://github.com/rails/rails/blob/master/activestorage/app/assets/javascripts/activestorage.js

**Pull request merged**
