### PR TITLE
Generate a PDF preview without print margins

### PR DESCRIPTION
**Pull request by genezys**
### Summary

When a PDF is used for both printing and displaying. It will most likely
contain a crop box in order to hide print margins when displaying the PDF.

Use Poppler's parameter to automatically use the crop box (visible box)
rather than the media box (printable box) in order to remove those margins
when drawing the PDF.

See https://manpages.debian.org/testing/poppler-utils/pdftoppm.1.en.html

### Other Information

I don't see anything else. Please advise.

### CODE REVIEW

**Comment by georgeclaghorn** [comment]
Does `mutool draw` use the crop box by default? If not, is there an equivalent flag we can add to [the MuPDF previewer](https://github.com/rails/rails/blob/0b244ff44c0fd78a925e8806cee7461f7ff5a409/activestorage/lib/active_storage/previewer/mupdf_previewer.rb)?

**Comment by genezys** [comment]
`mutool draw` does use the crop box by default already. I discovered this difference of behavior when we switched our app from MuPDF to Poppler.

**Comment by georgeclaghorn** [comment]
Okay. Thoughts on a [test](https://github.com/rails/rails/blob/e5b07258c281ce23bc5df28680408fe85a331c45/activestorage/test/previewer/poppler_pdf_previewer_test.rb)?

**Comment by genezys** [comment]
I will. Thank you for the link.

**Comment by genezys** [comment]
I added tests similar to the existing ones previewing a PDF file. These new tests preview a new cropped PDF based on the existing one.

I chose to remove the setup from previewer tests to prevent multiple blobs creation during the tests, I hope this is OK.

**Comment by georgeclaghorn** [comment]
Merged with a CHANGELOG entry in 3803671.

**Comment by genezys** [comment]
@georgeclaghorn Since the change is so small, any advice on how to backport it to 5.2 and 6.0?

**Comment by georgeclaghorn** [comment]
Backported in 33b70ca (6-0-stable) and 5d0e5f0 (5-2-stable).

**Comment by KapilSachdev** [comment]
5.2 can only receive security fixes as per the maintenance policy. But this has been backported to it, so has there been any change in the policy?

**Comment by genezys** [comment]
@KapilSachdev If I understand the policy correctly, as long as there is a patch, they are happy to apply it: https://guides.rubyonrails.org/maintenance_policy.html#unsupported-release-series

But they will not release a new version of 5.2 for this fix. For those that want it, they will need to work directly with the `5-2-stable` branch or wait until the next security release concerning 5.2.

**Pull request closed without merging**
