### PR TITLE
#20710 parse RSS/ATOM responses as XML, not HTML

### PR DESCRIPTION
**Pull request by simsalabim**
Addresses #20710
@rafaelfranca @tomhughes

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Thank you for the pull request but I think this is just the tio of the iceberg. Can we not use the mime object and keep using the regexp comparation?

**Comment by simsalabim** [comment]
@rafaelfranca you're right, it is. Switched back to regexp.

**Comment by sgrif** [comment]
In the future please open pull requests against master, not 4-2-stable. We will backport as needed.

**Comment by sgrif** [comment]
Forward ported in https://github.com/rails/rails/commit/ea9bc06c9a47b839d5e2db94ba6bf7e29c8f0ae9

**Pull request closed without merging**
