### PR TITLE
Add discussions link to the guides page

### PR DESCRIPTION
**Pull request by ghost**
### Summary

Added discussions link to the guides page, top navigation bar.

### CODE REVIEW

**Comment by jonathanhefner** [comment]
Related: rails/homepage#140

**Comment by jonathanhefner** [comment]
@rolandasb Since rails/homepage#140 has been merged, would you mind changing the link from "Discussions" to "Forum" to match?

**Comment by rafaelfranca** [comment]
I just merged https://github.com/rails/rails/commit/6c8d7d2d987c872f57915a38edb0e74a7a9832d4. Sorry, didn't see this one. Thank you for the contributions.

**Comment by jonathanhefner** [comment]
Oh, thank you @rafaelfranca!  And thank you @rolandasb for bringing this up!

**Pull request closed without merging**
