### PR TITLE
Update some i18n references in guides

### PR DESCRIPTION
**Pull request by shioyama**
The `Globalize::Backend::Static` class no longer exists in the [globalize](https://github.com/globalize/globalize) gem, so far as I can tell. I think this section of the guide is way out of date.

### CODE REVIEW

**Comment by shioyama** [comment]
Summary of changes:

- Remove reference to `Globalize::Backend::Static` which no longer exists in globalize gem
- Remove reference to rails-i18n google group, which is no longer maintained
- Remove confusing reference to Globalize3
- Add section on storing translations, reference top three popular gems for doing this (Globalize, Mobility, Traco) (Disclosure: I'm the author of Mobility.)

I think a lot more could be done to update this guide, just skimming it I found these issues but there are probably more. I think adding a section on translating content is important because it's a topic that comes up a lot, and can be very confusing for people unaware of the distinction with the standard I18n API.

Also: I'm aware that technically you *can* store strings in the database with i18n using the ActiveRecord backend, but it's an edge use case and gems like Globalize and Mobility are much more commonly used for this.

**Comment by shioyama** [comment]
@svenfuchs Since you were the original author of this guide, maybe you could comment on the changes? :smile:

**Comment by shioyama** [comment]
There were some formatting issues, fixed them in 5cb14f0.

**Comment by pixeltrix** [comment]
@shioyama thanks!

**Comment by shioyama** [comment]
Thanks! I don't suppose there's any chance this could get cherry-picked to 5-2-stable as well? Or should I make a PR to that branch for that?

**Comment by pixeltrix** [comment]
@shioyama cherry-picked to 5-2-stable in 78d47aa4bf0bf33a216cc7d9f1c6eeb182f178f4

**Comment by shioyama** [comment]
:+1: Thanks!

**Comment by svenfuchs** [comment]
Thanks for all your great work in the I18n space, @shioyama! 

❤️

**Comment by shioyama** [comment]
:blush:

**Pull request merged**
