### PR TITLE
Enumerable#many? in line with Enumerable#any?

### PR DESCRIPTION
**Pull request by eval**
### Summary

Currently the following can happen when a collection contains `false` or `nil` elements:
```ruby
[nil, false].none? # => true
[nil, false].many? # => true
```

This PR:
```ruby
[nil, false].many? # => false
```

It also introduces a `pattern` argument similar to `Enumerable#any?` (and `#none?` and `#all?`):
```ruby
[1, :b, 3.0].many?(Integer) # => false
possible_emails.many?(EMAIL_REGEXP)
```

### CODE REVIEW

**Comment by byroot** [comment]
While I agree that behaving more line `any? / all?` etc would be good, it's a bit tricky to change the method behavior in a backward incompatible way after all these years. This could definitely break some apps.

**Comment by eval** [comment]
Right, that could indeed cause some surprises and transitioning to this stricter implementation seems impossible.

How about an alternative method that would have this semantics?

What would be gained:
- it would be a `many?`-alternative that uses the semantics of `none?/any?/all?/one?` so when `this_new_method?` than always `any?` and never `none?`
- it would accept a pattern and a block like `any?` cs
- users can be made aware of the fact that while `many?` (without arguments) looks similar to `any?` and friends, it's actually just concerned with the size of the collection (like e.g. `empty?`) and an alternative exists.

The name `multiple?` (dictionary: "consisting of, including, or involving more than one") seems apt.

Thoughts?

**Comment by byroot** [comment]
> Thoughts?

In my opinion, core_ext methods shouldn't be added lightly. The "usefulness bar" for them is much higher than for any other Rails API.

And while I see the usefulness of such method, I don't think it's useful enough to justify a new method on `Enumerable`. That's just my opinion though.

**Comment by eval** [comment]
Makes sense - thanks both!

**Pull request closed without merging**
