### PR TITLE
Collapse all new default initializers into a single file

### PR DESCRIPTION
**Pull request by prathamesh-sonpatki**
- Adjusted tests also for this new behavior.
- Based on the discussion in
  https://github.com/rails/rails/pull/25184#issuecomment-222454583.

r? @dhh

### CODE REVIEW

**Comment by prathamesh-sonpatki** [comment]
Build failures are unrelated.

**Comment by nthj** [comment]
I love this. It cleans up the initializers folder, and intuitively I think it encourages new developers to familiarize themselves with the available configurations. Thanks, @prathamesh-sonpatki. :)

**Comment by maclover7** [comment]
Do we need to write up some internal docs about how changing framework defaults will work going forward?

**Comment by dhh** [comment]
@maclover7 I think this is more self-explanatory than what we had before. Before it was a grey area of whether the initializers were intended to be tweaked or whether they were new framework defaults. Now the file is literally called new_framework_defaults.rb. So think we're good.

**Comment by kaspth** [comment]
Love this, great simplification! I got some post review though :)

> so it is introduced as a configuration option to ensure that apps
 made on earlier versions of Rails are not affected when upgrading.

This is mentioned in every config. We should move this to the top of the file, so users know what to expect within it.

Though for every config it would be nice to see what the 4.2 version of the config was and the new 5.0 default + maybe a sentence about why it's changing. Showing past and present defaults would help knowing what to set the flags to and how far you are in staying up to date.

**Comment by kaspth** [comment]
@dhh should this be backported to 5.0.0? It would make sense because that's when people are most likely to run `bin/rails app:update` and get the file.

Backported to 5-0-stable @ f79dec5.

**Comment by dhh** [comment]
Yes please!

**Comment by prathamesh-sonpatki** [comment]
@kaspth We don't have any Rails 4.2 alternatives for any of the config options here. 

Except for `per_form_csrf_tokens` and `forgery_protection_origin_check` all of them require the notice - 'This is new Rails 5.0 default ... backward compatibility...`.  

Opened https://github.com/rails/rails/pull/25235 with some more cleanup.

**Comment by kaspth** [comment]
@dhh backported to 5-0-0 @ https://github.com/rails/rails/commit/5bcbd44ba92349c959959de84ced62ad285196c0

@prathamesh-sonpatki sure, but doesn't mean we couldn't say something like:

```ruby
# Rails 5 makes `belongs_to` required by default while they were optional in past versions.
# This migration option, which will be removed in the next Rails release, you can opt-out
# with false.
Rails.application.config.active_record.belongs_to_required_by_default = true
```

**Comment by prathamesh-sonpatki** [comment]
@kaspth Not sure about 

```
# This migration option, which will be removed in the next Rails release, you can opt-out
# with false.
```

Do we want to `which will be removed in the next Rails release` ? Rest looks fine to me. :+1:

**Comment by kaspth** [comment]
You're right. We could communicate that at the top of the file.

That's basically what I'm looking for, that the file sets expectations slightly better: these are migration options and you'd best start making your app use the new defaults as soon as you're on 5.0 (or whatever the release might be).

**Comment by prathamesh-sonpatki** [comment]
Ok. I will incorporate this in https://github.com/rails/rails/pull/25235

**Review by djmaze — COMMENTED** [review]
Sorry for the spam - Cannot delete this ;-/

**Pull request merged**
