### PR TITLE
Save index order :desc to schema.rb (sqlite). Fixes #30902

### LINKED ISSUE #30902: Index order :desc isn't saved into schema.rb after migration
### Steps to reproduce

*I tried to create a [bugreport testcase](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_migrations_gem.rb) but couldn't figure out all the API calls needed to reproduce entirely, so here are manual steps:*

```
$ rails new example
$ cd example
# I don't use Node.js, so:
$ sed -i '/rubyracer/s/^# //' Gemfile
$ bundle install

$ ./bin/rails g model topic subject:string body:text bumped_at:datetime
$ ./bin/rails db:migrate
$ ./bin/rails g migration AddIndexOnTopics

# Edit the migration file so it becomes:
class AddIndexOnTopics < ActiveRecord::Migration[5.1]
  def change
    add_index :topics, :bumped_at, order: {bumped_at: :desc}
  end
end

$ ./bin/rails db:migrate
$ grep INDEX log/development.log
   (3.1ms)  CREATE  INDEX "index_topics_on_bumped_at" ON "topics" ("bumped_at" DESC)
$ sqlite3 db/development.sqlite3
SQLite version 3.8.7.1 2014-10-29 13:59:56
Enter ".help" for usage hints.
sqlite> .fullschema
CREATE TABLE "schema_migrations" ("version" varchar NOT NULL PRIMARY KEY);
CREATE TABLE "ar_internal_metadata" ("key" varchar NOT NULL PRIMARY KEY, "value" varchar, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL);
CREATE TABLE "topics" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "subject" varchar, "body" text, "bumped_at" datetime, "created_at" datetime NOT NULL, "
updated_at" datetime NOT NULL);
CREATE INDEX "index_topics_on_bumped_at" ON "topics" ("bumped_at" DESC);
/* No STAT tables available */
sqlite>
```

Ok so far so good. However the schema.rb has no mention of the sort order:

```
$ grep -A1 -B1 index db/schema.rb
    t.datetime "updated_at", null: false
    t.index ["bumped_at"], name: "index_topics_on_bumped_at"
  end
```

So when I drop and recreate the database, the index is added without the DESC:

```
$ ./bin/rails db:drop
$ ./bin/rails db:schema:load
$ grep INDEX log/development.log|tail -1
   (10.5ms)  CREATE  INDEX "index_topics_on_bumped_at" ON "topics" ("bumped_at")
$ sqlite3 db/development.sqlite3
SQLite version 3.8.7.1 2014-10-29 13:59:56
Enter ".help" for usage hints.
sqlite> .fullschema
CREATE TABLE "topics" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "subject" varchar, "body" text, "bumped_at" datetime, "created_at" datetime NOT NULL, "
updated_at" datetime NOT NULL);
CREATE INDEX "index_topics_on_bumped_at" ON "topics" ("bumped_at");
CREATE TABLE "schema_migrations" ("version" varchar NOT NULL PRIMARY KEY);
CREATE TABLE "ar_internal_metadata" ("key" varchar NOT NULL PRIMARY KEY, "value" varchar, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL);
/* No STAT tables available */
sqlite>
```

### Expected behavior

The information relating to index sorting order should be persistent after applying a migration.

### Actual behavior

The index sorting order is lost when dropping the database and loading via `db:schema:load`.

### System configuration
```
$ ruby -v
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
$ rails -v
Rails 5.1.4
```

### PR DESCRIPTION
**Pull request by rohitpaulk**
### Summary

Fixes #30902. 

Although the sqlite adapter supports index sort orders, they weren't being written to db/schema.rb.

This uses [`index_xinfo`](https://sqlite.org/pragma.html#pragma_index_xinfo) instead of [`index_info`](https://sqlite.org/pragma.html#pragma_index_info) (which was used previously), as the latter doesn't contain information about the sort order.

### CODE REVIEW

**Comment by rohitpaulk** [comment]
There are test failures, I'm looking into them.

**Comment by rohitpaulk** [comment]
Looks like `PRAGMA index_xinfo` was only added in sqlite 3.8.9, and the current version on Travis is 3.8.2.

**Comment by rafaelfranca** [comment]
We can add a method to check if it is supported and conditionally use `index_xinfo`

**Comment by rohitpaulk** [comment]
I ended up extracting ordered columns from the sql query itself, like [the postgres adapter does](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb#L127).

**Pull request merged**
