### PR TITLE
Fire callbacks if object state is changed

### PR DESCRIPTION
**Pull request by siddhantbajaj**
### Summary

`after_commit` callbacks are not always fired in case of soft delete records. In soft_deletion, we don't delete the record from database instead just updates some attributes of the record (like `is_deleted` etc). 
The hash of base record and soft delete records is the same therefore following code returns false and the callbacks are not fired.
```
should_run_callbacks = already_run_callbacks[record] ||= trigger_callbacks
```

To fix this, we should check is the state of the record is changed from the first callback to the last.

### Other Information

Run this [script](https://github.com/siddhantbajaj/Rails-after-commit/blob/master/ruby_script.rb), to see the example of above.

Thanks for contributing to Rails! -->

### CODE REVIEW

**Comment by feixionglee** [comment]
should `after_create` be ` after_commit` in the summary ?

**Comment by siddhantbajaj** [comment]
cc @rafaelfranca , @Edouard-chin

**Comment by hillazz** [comment]
Hey, here we noticed that if product(s) is/are deleted by using bulk delete ( select multiple orders and delete), then product deleted webhook is not sent. Is this PR going to fix this issue? We have several support tickets open, so just want to be sure that nothing should be investigated. Thanks!

**Comment by siddhantbajaj** [comment]
Sorry I didn't get much time to look into this last week, as mentioned above we might need to look for a fix in the gem we use internally for this issue. I am working on another high priority issue but I will try to give it another look ASAP.

**Pull request closed without merging**
