### PR TITLE
Test basic auth with symbols in password

### PR DESCRIPTION
**Pull request by denisenkom**
Test basic auth with symbols in password

Related to: https://github.com/rails/rails/pull/21019

### CODE REVIEW

**Comment by georgeclaghorn** [comment]
What do you think about breaking this out into a separate test with a descriptive name?

**Comment by denisenkom** [comment]
I thought about it but couldn't find decisive arguments for it or against it.
Having single test that covers multiple conditions is simpler and fewer code.
Having separate test for password with symbols is good too but it is more code to maintain.
If you think having separate test is better, let me know I will update pull request.

**Comment by arthurnn** [comment]
I am also in favor of creating a new test for those cases.

**Comment by denisenkom** [comment]
Ok, implemented as a separate test, please take a look

**Comment by maclover7** [comment]
Are we ready to merge here?

**Comment by kaspth** [comment]
Looked good to me, thanks all!

**Comment by maclover7** [comment]
:+1:

**Pull request merged**
