### PR TITLE
Display railtie class name in `rails initializers`

### PR DESCRIPTION
**Pull request by ta1kt0me**
### Summary

I add a class name to recognize same macro name like `load_config_initializers` and `load_environment_config` etc in `rails initializers`.

### CODE REVIEW

**Comment by schneems** [comment]
Not comfortable relying on an `instance_variable_get(:@context)` in this case. Is there no public interface for this info? Could we add one?

**Comment by ta1kt0me** [comment]
@schneems Thanks. I've updated with your advise.

**Comment by schneems** [comment]
Looks better, can you add a test, then I think we're looking good to move forwards.

**Comment by ta1kt0me** [comment]
I've changed implementation. Old one expected that `@context` is always `Rails::Railtie`'s subclass. I thought it's no problem because `initializer` method bases `Rails::Railtie`. But it wasn't modulability. I only want to know a class which defineds initializer in this PR, then I've defined new interface. Please tell me if we need rebase it.

**Comment by ta1kt0me** [comment]
@schneems Anything else I need to add to this?

**Comment by schneems** [comment]
I'm fine with this. Thanks!

**Pull request merged**
