### PR TITLE
Prevent generators from creating classes in the application module

### PR DESCRIPTION
**Pull request by codebaker95**
Fix for [this](https://github.com/rails/rails/issues/21476) issue. I explain my reasoning in comments.

### CODE REVIEW

**Comment by pixeltrix** [comment]
@codebaker95 how does this play with engines? I know we automatically add a table_name_prefix method to the engine's module I just wondered what this check did when generating a new engine.

**Comment by magikid** [comment]
:+1

**Comment by rafaelfranca** [comment]
Agree with Gannon. If you chose to namespace your models in the application name your application can still work with the proper requires, you just need to add them. So I don't see why not allowing this. That said I'm going to close this PR. Thank you.

**Comment by AkankshaSh** [comment]
@gmcgibbon : Thank you for the answer. Can you please elaborate with an example?

**Comment by gmcgibbon** [comment]
When you generate a rails app, it creates a module with the name you pass to `new` (eg. `rails new dummy`). You can see this module in `config/application.rb` (eg. `Dummy::Application`). If you define a model nested in your application's module, autoload won't look for said module unless you explicitly tell it to with `require_dependency`.

So, if I define a table in my dummy app called `Dummy::Thing` (`rails g model dummy/thing`) I have to add `require_dependency 'dummy'` to the top of my model definition at `app/models/dummy/thing.rb` to tell autoload to search my autoload paths and find `app/models/dummy.rb`.

Does that make sense?

**Comment by vizcay** [comment]
From https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#ruby-constant-lookup-compliance

> In zeitwerk mode that does not matter anymore, you can pick either style.
> 
> The resolution of a constant could depend on load order, the definition of a class or module object could depend on load order, there was edge cases with singleton classes, oftentimes you had to use require_dependency as a workaround, .... The guide for classic mode documents these issues.
> 
> **All these problems are solved in zeitwerk mode, it just works as expected, and require_dependency should not be used anymore, it is no longer needed.**

I'm missing something here?

**Pull request closed without merging**
