### PR TITLE
Ruby 2.2.3 in windows need nokogiri 1.6.7.rc3

### PR DESCRIPTION
**Pull request by Eric-Guo**
It's the only version having correct pre-compiled so files.

### CODE REVIEW

**Comment by sgrif** [comment]
r? @rafaelfranca 

Does anybody have a way to test this? That regex looks funky to me either way. Does Bundler not provide a way to detect Windows? Does the affect users of Rails? Changing the Gemfile will only affect running the Rails test suite, not the gemspec.

**Comment by Eric-Guo** [comment]
The regex just improved, maybe [app template](https://github.com/rails/rails/blob/master/railties/lib/rails/generators/rails/app/templates/Gemfile#L53) also can using this way. I understand change here only affect test suite and I'm tring to run it in Windows. :smile:

**Comment by rafaelfranca** [comment]
We don't specify nokogiri version in application Gemfile so we can't force users to use RC. Also I believe this will be fixed when 1.6.7 is released.

This change is good to me. Also please open a PR to change the app template to use this Bundler check.

**Comment by pixeltrix** [comment]
@rafaelfranca do we want to backport this to 4-2-stable

**Comment by rafaelfranca** [comment]
I'm not sure. Do we care about 4.2 tests running on Windows? It is a stable
branch and if something is broken on Windows (and I'm sure it is) I'd not
do too much change on it. But if we want to backport this I'm fine. Beware
that I changed this patch a lot on master.

**Comment by marutosi** [comment]
> But if we want to backport this I'm fine.

+1

As I wrote at https://github.com/sparklemotion/nokogiri/issues/1256#issuecomment-151797415 ,
It is annoying many users claims Redmine cannot run on Windows Ruby 2.2.

**Pull request merged**
