### PR TITLE
Fix #43978 - Use the application record class when doing migrations

### LINKED ISSUE #43978: Rails 7 Schema Load ignores primary abstract class connection
### Steps to reproduce
See https://github.com/codeodor/rails-7-schema-load-test/blob/main/README.md for a test application I made that exhibits the behavior. 

I wasn't sure how to do the multi-db setup in the provided scripts, so I hope that repository I made helps. 

### Expected behavior
I expect that when running within `Model.connected_to(shard: shard_2)` that loading the Schema file would operate on the database specified in the `shard_2` config. 

### Actual behavior
It operates on the default shard database instead. 

### System configuration
**Rails version**: 7.0.0

**Ruby version**: ruby 2.7.1p83

### PR DESCRIPTION
**Pull request by codeodor**
So they will be performed in the correct database specified by `ApplicationRecord.connected_to(...)` when using the block syntax to perform everything in a specific database/shard

### Summary
Possible fix for #43978

### CODE REVIEW

**Comment by codeodor** [comment]
Added some more changes that I found when trying to run migrations rather than just load the schema file. In this case, I found several instances where even using my own `ApplicationSchemaMigration` it was running it on the DB specified in AR::Base, rather than that we were `connected_to` 

As part of this, would it make sense to (move this code)[https://github.com/rails/rails/blob/7-0-stable/activerecord/lib/active_record/schema_migration.rb#L12-L52] into a module that could then be included in `SchemaMigration` (and in particular, for client code to be able to re-use when they need their own `ApplicationSchemaMigration` with the same code but a different superclass?

**Comment by codeodor** [comment]
I checked several of the failed tests, and all that I checked said something along the lines of "ERROR: manifest for 973266071021.dkr.ecr.us-east-1.amazonaws.com/builds:rubylang-ruby-master-nightly-focal-e6ddd1ba-4ae7-4301-b0fb-d75492f458e9 not found: manifest unknown: Requested image not found" 

Not sure what I can do about that. Anything?

**Comment by rafaelfranca** [comment]
Can you please change this PR to point to the main branch? We don't merge anything in 7-0-stable

**Comment by codeodor** [comment]
Closing in favor of #44079, which targets the correct branch.

**Pull request closed without merging**
