### PR TITLE
Fix detecting `IDENTITY` columns for PostgreSQL < 10

### LINKED ISSUE #49591: Rails 7.1.1 breaks Postgres < 10
pg_attribute.attidentity was introduced in 10. See https://www.postgresql.org/docs/9.6/catalog-pg-attribute.html vs. https://www.postgresql.org/docs/10/catalog-pg-attribute.html. According to Rails docs at https://guides.rubyonrails.org/active_record_postgresql.html, back to 9.3 is supported.

End result when running against Postgres 9.6:

```
PG::UndefinedColumn: ERROR:  column a.attidentity does not exist
LINE 4:        a.attidentity AS identity,
               ^
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:19:in `exec'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:19:in `block (2 levels) in query'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:1024:in `block in with_raw_connection'
/usr/local/bundle/gems/activesupport-7.1.1/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:996:in `with_raw_connection'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:18:in `block in query'
/usr/local/bundle/gems/activesupport-7.1.1/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
/app/lib/switchman/sharded_instrumenter.rb:26:in `instrument'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:1134:in `log'
/app/lib/switchman/active_record/abstract_adapter.rb:39:in `log'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:17:in `query'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/connection_adapters/postgresql_adapter.rb:1075:in `column_definitions'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:109:in `columns'
/app/lib/switchman/active_record/postgresql_adapter.rb:132:in `block in columns'
/app/lib/switchman/active_record/postgresql_adapter.rb:98:in `with_local_table_name'
/app/lib/switchman/active_record/postgresql_adapter.rb:132:in `columns'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/connection_adapters/schema_cache.rb:346:in `block in columns'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/connection_adapters/schema_cache.rb:345:in `fetch'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/connection_adapters/schema_cache.rb:345:in `columns'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/connection_adapters/schema_cache.rb:354:in `block in columns_hash'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/connection_adapters/schema_cache.rb:353:in `fetch'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/connection_adapters/schema_cache.rb:353:in `columns_hash'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/connection_adapters/schema_cache.rb:58:in `columns_hash'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/connection_adapters/schema_cache.rb:188:in `columns_hash'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/model_schema.rb:616:in `load_schema!'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/attributes.rb:264:in `load_schema!'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/encryption/encryptable_record.rb:127:in `load_schema!'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/model_schema.rb:561:in `block in load_schema'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/model_schema.rb:558:in `synchronize'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/model_schema.rb:558:in `load_schema'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/model_schema.rb:439:in `attribute_types'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/attribute_methods.rb:256:in `_has_attribute?'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/inheritance.rb:61:in `new'
/usr/local/bundle/gems/activerecord-7.1.1/lib/active_record/persistence.rb:54:in `create!'
```

### PR DESCRIPTION
**Pull request by fatkodima**
Fixes #49591.

While testing changes made in this PR, I identified that quite a few tests are broken for PostgreSQL < 10. So I fixed them as a separate commit.

### CODE REVIEW

**Comment by andyatkinson** [comment]
@fatkodima Version 10 of PostgreSQL is no longer supported by PostgreSQL, FWIW

https://www.postgresql.org/support/versioning/

Supported=No
Final Release=November 10, 2022

Do you know what the policy is for Rails on EOL versions of DB adapters?

For new versions of Rails, I'd propose that PostgreSQL 10 is not supported. Maybe Rails version 8 drops PostgreSQL 10 support?

**Comment by fatkodima** [comment]
I don't think there is any policy regarding dropping older versions of dbms'es. Maybe when maintaining it becomes unnecessary harder?

cc @rafaelfranca @yahonda

**Comment by andyatkinson** [comment]
@fatkodima Sounds good.

My recommendation would be Ruby on Rails consider dropping support for version 10 of PostgreSQL. This is based on the open source community distribution guidance above, and what I've seen from major cloud hosting providers like AWS. AWS stopped supporting PostgreSQL version 10 for example:

https://repost.aws/questions/QUph1IFLkkRiyc0pCdTH493Q/announcement-amazon-rds-for-postgresql-10-deprecation

As you probably know, PostgreSQL major versions are released annually since version 10, and there have been 6 newer annual releases since then. The current version is 16 released in September 2023.

I'm sure there are still many Ruby on Rails applications running with PostgreSQL 10 (or even earlier versions) in the wild, so I acknowledge there's a need for advanced communication.

I could put this into an Issue if that's a better way to make a proposal.

The goal to me would be able to remove code and tests that are only for unsupported versions.

Thanks!

**Comment by andyatkinson** [comment]
@fatkodima This was kind of a rabbit hole from finding that this test didn't pass for me locally. If you have any tips let me know, I may be doing something wrong: https://github.com/rails/rails/pull/49744

**Comment by matthewd** [comment]
> Maybe when maintaining it becomes unnecessary harder?

Yep. Especially because of how much inertia database servers in particular can have, I like to use a threshold of "unreasonably complicated".

Previously: https://github.com/rails/rails/pull/41526#issuecomment-784240069

There are also some edge cases involving protocol-compatible forks/variants/similar, which can also trail the upstream version. We're not going to do work to support them in ways where they _differ_ from upstream, but again, refusing to connect just out of principle seems needlessly punitive.

That said, while I'd hesitate to drag us all the way up to the EOL boundary, it probably does make sense to review what conditionals & branches we can eliminate by at least requiring a higher `9.x`, or even `>= 10`.

**Comment by andyatkinson** [comment]
> There are also some edge cases involving protocol-compatible forks/variants/similar, which can also trail the upstream version.

Good point. You're referring to things like pgbouncer, Citus extension, AWS Aurora, Neon, YugabyteDB etc. that might be PostgresSQL protocol compatible, but behind on versions, correct?

Even though they aren't officially supported/tested by Active Record, there would need to be some significant value and justification to explicitly break something that's working: agreed.

**Pull request merged**
