### PR TITLE
Fix lazy translation in partial with block

### LINKED ISSUE #40900: Rails 6.1 - problem with lazy translations inside view partial
I'm trying to migrate my app into rails 6.1 and discovered braking change for the translation view helper for the lazy partial translations. 

For example I have a `organization/_form` template with `t ".title"` inside. This partial is rendered in `admin/organization/show`. In rails 6.0 this lazy translation is expanded into `organization.form.title` and in rails 6.1 into `admin.organization.show.title`.

The difference between 6.0 and 6.1 cames from the `TranslationHelper.scope_key_by_partial` method implementation: in 6.0 `@virtual_path` is used (evaluated into `organization.form`) and in 6.1 `@current_template&.virtual_path` (evaluated into `admin.organization.show`).

This change was introduced by: https://github.com/rails/rails/commit/dd7a673782f102d2b58194007bf18a8e496818e3.

### PR DESCRIPTION
**Pull request by mkasztelnik**
https://github.com/rails/rails/pull/39060/commits/dd7a673782f102d2b58194007bf18a8e496818e3 introduces breaking change in the way how lazy translation is evaluated in the partial with block. Let's suppose that we have `home/index.html.erb` with the following content:

```erb
<%= render "partial" %>
<%= render "partial" do %>
<% end %>
```
and the partial (`home/_partial.html.erb`):

```erb
<%= t ".foo" %>
<%= yield %>
```
The first partial render (without block) updates `@current_template` and everything is ok (lazy translation is evaluated into `home.partial.foo`) but the second partial render (with block) is not updating `@current_template` variable (see https://github.com/rails/rails/blob/master/actionview/lib/action_view/renderer/partial_renderer.rb#L285 and https://github.com/rails/rails/blob/master/actionview/lib/action_view/base.rb#L245). As a result, lazy translation is evaluated into `home.foo`.

This PR adds tests for partial and partial with block render with lazy translation and a rollback of the change introduced in https://github.com/rails/rails/pull/39060/commits/dd7a673782f102d2b58194007bf18a8e496818e3. 

Fixes #40900

### CODE REVIEW

**Comment by AxelTheGerman** [comment]
@mkasztelnik first of all, thank you for working on this! 

I just upgraded my app to Rails 6.1.1 and this seems to be causing issues.

I'm seeing the following error as my test environment is set up to raise on missing translations:
```
ActionView::Template::Error: translation missing: en.shared.user_menu.toggle.active
    app/views/personal_numbers/index.html.erb:64
    app/views/personal_numbers/index.html.erb:13:in `each_with_index'
    app/views/personal_numbers/index.html.erb:13
    app/views/shared/_user_menu.html.erb:50
    app/views/personal_numbers/index.html.erb:2
    app/controllers/application_controller.rb:35:in `use_user_time_zone'
    lib/test_session_middleware.rb:10:in `call'
    test/controllers/personal_numbers_controller_test.rb:103:in `block in <class:PersonalNumbersControllerTest>'
```

Previously it loaded the localized string from `en.personal_numbers.index.toggle.active`.

Here are the most relevant lines:
```
# personal_numbers/index.html.erb
<div class=container>
  <%= render 'shared/user_menu' do %>
    ...
              <%= link_to t(".toggle.#{number.status}"), [:toggle_active, :user_home, number], method: :put, class: 'button is-text' %>
```

```
# shared/user_menu.html.haml
<div class="columns">
  <div class="column is-narrow">
    ...
  </div>
  <div class="column">
    <%= yield %>
  </div>
</div>
```

I hope this helps as you have more context about how the code works. If not I can create a new rails app that has just the error - or even try to write a failing spec in the test suite.

Let me know what you think!

**Comment by mkasztelnik** [comment]
@AxelTheGerman thank you for bringing this issue up. It occurs to many people (me included) and indeed it is tricky (take a look for example at #16499 or [here](https://dev.to/zspencer/surprising-behavior-with-rails-i18n-lazy-lookups-and-partials-5g78)) but it is not a bug - see https://github.com/rails/rails/issues/16499#issuecomment-66149957. 

The `6.1` introduces the side effect, which will work for simple case, but fails with a more complex example, e.g.:

`home/index.html.erb`:
```erb
<%= render "partial_with_partial" do %>
<% end %>
```
`home/_partial_with_partial.html.erb`:
```erb
<%= render "partial" do %> 
  <%= t ".foo" %>
<% end %>
<%= yield %>
```

`home/_partial.html.erb`:
```erb
<%= yield %>
```

in this case `.foo` should be evaluated into `en.home.partial_with_partial.foo` but it is evaluated into `en.home.index.foo`.

**Comment by owen2345** [comment]
The problem persists on `7.0.1`

**Comment by AxelTheGerman** [comment]
Thanks @mkasztelnik - I agree with @rafaelfranca [comment](https://github.com/rails/rails/issues/16499#issuecomment-66149957) but that discussion is quite old.

It probably would be useful to provide a couple of examples with their current and expected behaviour (especially as some of the previous discussions are quite old).

Then we could decide whether there's an issue, if it can be fixed or if everything works as expected.

**Pull request merged**
