### PR TITLE
remove reference to `register_javascript_expansion` and `register_stylesheet_expansion` from guide [ci skip]

### PR DESCRIPTION
**Pull request by y-yagi**
These methods no longer exists.

### CODE REVIEW

**Comment by idoo** [comment]
What about CHANGELOG ?

**Comment by senny** [comment]
@y-yagi thanks :+1:

**Comment by y-yagi** [comment]
@senny Thanks!

**Comment by senny** [comment]
@idoo Other than with code changes we don't add changelog entries for minor updates in the guides.

**Pull request merged**
