### PR TITLE
Use Node's ecosystem in guides

### PR DESCRIPTION
**Pull request by yhirano55**
### Summary

Currently, It's hard to maintain stylesheets and javascripts in guides. So I thought it's better to use Node's ecosystem (webpack, babel, eslint, node-sass ... and more) in guides, too. In the future, we can get start to use turbolinks or stimulusjs in guides.

In this PR, my concerning is assets migrations to ride on Node's ecosystem. So I didn't refactor css and javascripts.

#### Merits

* Become easy to maintain or change.
* Become easy to update libraries.
* Become secure scripts with eslint.
* Become compressible.

#### Demerits

* Demand knowledge about yarn or npm.

#### Setup

```
$ cd guides/
$ yarn
$ yarn build # Compile ./src sources
$ bundle exec rake guides:generate:html
$ yarn start # Boot node server with localhost:9000 (publicPath is /output dir)
```

BTW, we have to support old browsers (e.g. IE7, IE8...etc) in guides...?

### CODE REVIEW

**Comment by pixeltrix** [comment]
> Currently, It's hard to maintain stylesheets and javascripts in guides.

That's a bold assumption that doesn't appear to be backed up when looking at the git history for [assets][1] - there doesn't seem to be a lot of churn and this PR adds 7000+ lines just to keep us where we are. Not that I don't think the Rails Guides could do with a bit of a refactoring when it comes to generation, however I'd prefer to see us move to an existing static site generator like jekyll which would hopefully reduce the amount of code we have.

The other thing we have to bare in mind is any impact on generation of assets for the [doc server][2] - using node build tools sounds like that'd need reworking too.

@fxn do you have any thoughts?

[1]: https://github.com/rails/rails/commits/master/guides/assets
[2]: https://github.com/rails/rails-docs-server

**Comment by fxn** [comment]
Same as yours Andrew.

This project barely uses JavaScript, and has only a bunch of CSS which as you said does not change much. I think it is fine and _simple_ the way it is.

On the other hand, an effort to move guides to a static site generator would be worthwhile.

**Comment by yhirano55** [comment]
@pixeltrix @fxn Thanks for the comments. I felt so, too. Well, I'll close this PR. Thank you so much.

**Comment by fxn** [comment]
@yhirano55 this PR took time to prepare, thanks a lot for it anyway ❤️.

**Pull request closed without merging**
