### PR TITLE
Remove unused `BLANK_RE`

### PR DESCRIPTION
**Pull request by kamipo**
Follow up to #24658.

r? @fxn

### CODE REVIEW

**Comment by schneems** [comment]
People may be using it.

**Comment by schneems** [comment]
We could deprecate and remove in 5.1

**Comment by simi** [comment]
https://github.com/search?utf8=%E2%9C%93&q=BLANK_RE+language%3ARuby+language%3ARuby&type=Repositories&ref=advsearch&l=Ruby&l=Ruby

Is that public API?

**Comment by schneems** [comment]
It's not :nodoc: which is how we specify when something is private API.

Don't know if there's good patterns around deprecating a constant.

**Comment by schneems** [comment]
Could use a const missing http://stackoverflow.com/questions/29695995/how-to-mark-a-class-as-deprecated-in-ruby

**Comment by rafaelfranca** [comment]
Can we just update it to match the new implementation?

**Comment by schneems** [comment]
The new implementation uses the opposite logic.

**Comment by rafaelfranca** [comment]
`BLANK_RE` is not in the edgeguides.rubyonrails.org so I guess it is fine to remove.

**Comment by schneems** [comment]
I'm fine with it if you are. It's up to you.

**Pull request merged**
