### PR TITLE
Set assert_not as alias to refute

### PR DESCRIPTION
**Pull request by bogdanvlviv**

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Thank you but I prefer to keep the method definition and the documentation. Aliasing may change behavior in minitest and reflect in rails.

**Comment by bogdanvlviv** [comment]
Sorry but i confused by it. How does it can change behavior in minitest?

**Comment by rafaelfranca** [comment]
I mean if minitest changes the message or the behavior of refute it will
change the behavior of Rails and we don't want that

**Comment by bogdanvlviv** [comment]
The methods `#refute_*` are using `#refute` for their own implementation.
Also we have aliases like `alias :assert_not_* :refute_*`
I think we should also trust minitest in case `assert_not` as alias for `refute`

The default message for `refute` in minitest is `"Expected #{mu_pp(test)} to not be truthy"`, and for `assert_not` is `"Expected #{mu_pp(object)} to be nil or false"`, both LGTM.
Thanks!

**Pull request closed without merging**
