### PR TITLE
PostgreSQL, remove varchar limit.

### PR DESCRIPTION
**Pull request by senny**
Closes #13435
Closes #9153

There is no reason for the PG adapter to have a default limit of 255 on :string
columns. See this snippet from the PG docs:

```
Tip: There is no performance difference among these three types, apart
from increased storage space when using the blank-padded type, and a
few extra CPU cycles to check the length when storing into a
length-constrained column. While character(n) has performance
advantages in some other database systems, there is no such advantage
in PostgreSQL; in fact character(n) is usually the slowest of the
three because of its additional storage costs. In most situations text
or character varying should be used instead.
```

### CODE REVIEW

**Comment by lukewendling** [comment]
Just ran my first migration after 4.2 upgrade and ```rake db:schema:dump``` now adds ```limit: 255``` to all string cols in db even though I'm using postgres. Is there an option to prevent this behavior?

**Comment by senny** [comment]
@lukewendling the `db/schema.rb` is used to exactly recreate your database. All your string columns were added before `4.2` with an implicit limit of `255`. At that time it was not necessary to dump the limit to `db/schema.rb` because it was the default. Now that we've changed the default to `no limit`. We must dump these limits to recreate the database.

**Comment by constantm** [comment]
I have a similar problem to @lukewendling. We have two dev boxes both running Rails 4.2, but as soon as I create a migration and it gets run on the other box, it adds limits to all the string fields in the schema file. When a migration is created on the other dev box, it does not do this.

**Comment by Envek** [comment]
@constantm it means that databases in these boxes are become different: one does have limits and another does not (for example someone have run migrations from scratch on another box after upgrade).

You should stick to the configuration you have in production. Dump database schema from production database, restore it on one of dev boxes, run `rake db:schema:dump` and commit `db/schema.rb` into version control system.

If you do not want to have limits on string columns, create migration that will remove them:

```ruby
class RemoveLimitFromStringColumns < ActiveRecord::Migration
  def up
    # repeat for all your tables and all your columns
    execute 'ALTER TABLE "your_table" ALTER COLUMN "your_column" TYPE character varying;'
  end

  def down
    # repeat for all your tables and all your columns
    execute 'ALTER TABLE "your_table" ALTER COLUMN "your_column" TYPE character varying(255);'
  end
end
```

If you do not have production yet, just drop database and rerun all migrations from scratch.

Anyway, **current behaviour is correct**, and previous Rails versions were buggy by creating columns with implicit limit and not displaying it in `db/schema.rb`.

**Comment by constantm** [comment]
@Envek Okay great thanks, I'll dump the schema from production then.

**Comment by fphilipe** [comment]
Out of curiosity, why did you go with `character varying` and not `text`?

**Comment by Envek** [comment]
@fphilipe It's kind of convention to use `character varying` columns for single line values and `text` for multiline. For example libraries like [simple_form] are rendering `input` tags for `character varying` type attributes and `textarea` tags for `text` type values. It's quite convenient.

[simple_form]: https://github.com/plataformatec/simple_form

**Comment by fphilipe** [comment]
@Envek Makes perfect sense! Thanks for the explanation :+1:

**Pull request merged**
