### PR TITLE
correctly check error message

### PR DESCRIPTION
**Pull request by y-yagi**
`assert_raise` does not check error message. However, in some tests, it seems like expecting error message checking with `assert_raise`.　Instead of specifying an error message in `assert_raise`, modify to use another assert to check the error message.

### CODE REVIEW

**Comment by yui-knk** [comment]
* activerecord/test/cases/finder_test.rb
* activesupport/test/core_ext/object/json_gem_encoding_test.rb

Each of them define `assert_raises_with_message`. What do you think about defining `#assert_raises_with_message` to `ActiveSupport::TestCase`?

**Comment by y-yagi** [comment]
> defining #assert_raises_with_message to ActiveSupport::TestCase?

I think that is good.
However, since it needs discussion and there is also an influence on existing code, I'd like to do a place to fix problematic tests first.

**Comment by arthurnn** [comment]
great catch.

**Comment by y-yagi** [comment]
Thanks!

**Pull request merged**
