### PR TITLE
Add `Array#extract!`

### PR DESCRIPTION
**Pull request by bogdanvlviv**
The method removes and returns the elements for which the block returns a true value.
If no block is given, an Enumerator is returned instead.

```ruby
numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
odd_numbers = numbers.extract! { |number| number.odd? } # => [1, 3, 5, 7, 9]
numbers # => [0, 2, 4, 6, 8]
```

Also, I added commit [Use `Array#extract!` where possible](https://github.com/rails/rails/commit/2f7d607cf8966c1dc226a422c639f965bfb019b6) in order to show that we can improve Rails code base by this method.

```diff
- nils, values = values.partition(&:nil?)
- ranges, values = values.partition { |v| v.is_a?(Range) }
+ nils = values.extract!(&:nil?)
+ ranges = values.extract! { |v| v.is_a?(Range) }
```
Looks more readable if use `Array#extract!`, doesn't it?

I know we try to omit adding new methods to ActiveSupport, but I think this one has a good chance to be added since we can apply it in Rails code base.
By the way, we already added `Hash#extract!`
https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/hash/slice.rb#L41-L47

Post: https://gitlab.com/bogdanvlviv/posts/-/issues/14, https://bogdanvlviv.com/posts/ruby/rails/array-extract-to-activesupport-6-0.html

 I have tried to add Active Support's `Array#extract!` as `Array#extract` to Ruby, see [Feature #15831: "Add `Array#extract`, `Hash#extract`, and `ENV.extract`"](https://bugs.ruby-lang.org/issues/15831).

Thanks!

### CODE REVIEW

**Comment by rafaelfranca** [comment]
I'm ok with this one. @dhh what do you think of this name?

**Review by sikachu — APPROVED** [review]

**Comment by sikachu** [comment]
I honestly thought that this is what `select!` does, but apparently not. So, 👍from me too.

**Comment by matthewd** [comment]
FWIW, it would be named `extract` upstream... but as we already have `Hash#extract!`: 🤷🏻‍♂️

> Also, I added commit Use Array#extract! where possible in order to show that we can improve Rails code base by this method.

💯. This was very helpful, thank you.

On the implementation: I'd like to avoid allocating the second array. What do you think of something like `reject! { |el| extracted_elements << el if yield el }` ?

Let's also avoid `unless`/`else` in favour of an early return; the double-negative of that `else` can be confusing, even though the code layout is nearly the same.

**Comment by bogdanvlviv** [comment]
Thanks for the review guys!

@matthewd I applied your suggestions in [Refactor `Array#extract!`](https://github.com/rails/rails/pull/33137/commits/0a8e9ef43a3defcc015db08b723774c5786934d0).

> On the implementation: I'd like to avoid allocating the second array. What do you think of something like reject! { |el| extracted_elements << el if yield el } ?

I prepared benchmarks in order to ensure that the changes speed up the method:
```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update
your Bundler"
  raise e
end

class Array
  def extract_v1!(&block)
    unless block_given?
      to_enum(:extract!) { size }
    else
      extracted_elements, other_elements = partition(&block)

      replace(other_elements)

      extracted_elements
    end
  end

  def extract_v2!
    return to_enum(:extract!) { size } unless block_given?

    extracted_elements = []

    reject! do |element|
      extracted_elements << element if yield(element)
    end

    extracted_elements
  end
end

gemfile(true) do
  source "https://rubygems.org"

  gem "benchmark-ips"
end

arrays_for_partition = Array.new(1000) { (0..10000).to_a }
arrays_for_extract_v1 = Array.new(1000) { (0..10000).to_a }
arrays_for_extract_v2 = Array.new(1000) { (0..10000).to_a }

Benchmark.ips do |x|
  x.report("Array#partition")  do
    arrays_for_partition.each do |numbers|
      odd_numbers, numbers = numbers.partition { |number| number.odd? }
      numbers
    end
  end

  x.report("Array#extract_v1!")  do
    arrays_for_extract_v1.each do |numbers|
      odd_numbers = numbers.extract_v1! { |number| number.odd? }
      numbers
    end
  end

  x.report("Array#extract_v2!")  do
    arrays_for_extract_v2.each do |numbers|
      odd_numbers = numbers.extract_v2! { |number| number.odd? }
      numbers
    end
  end

  x.compare!
end
```

The result of the benchmarks:

```bash
ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
```

```bash
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using benchmark-ips 2.7.2
Using bundler 1.16.1
Warming up --------------------------------------
     Array#partition     1.000  i/100ms
   Array#extract_v1!     1.000  i/100ms
   Array#extract_v2!     1.000  i/100ms
Calculating -------------------------------------
     Array#partition      1.390  (± 0.0%) i/s -      7.000  in   5.044843s
   Array#extract_v1!      2.781  (± 0.0%) i/s -     14.000  in   5.050589s
   Array#extract_v2!      3.151  (± 0.0%) i/s -     16.000  in   5.080608s

Comparison:
   Array#extract_v2!:        3.2 i/s
   Array#extract_v1!:        2.8 i/s - 1.13x  slower
     Array#partition:        1.4 i/s - 2.27x  slower
```

> Let's also avoid unless/else in favour of an early return; the double-negative of that else can be confusing, even though the code layout is nearly the same.

Yeah, It will be more readable and also using of early return would improve `git diff`
in some cases if we needed to change this method I think.

**Review by rafaelfranca — APPROVED** [review]

**Comment by sikachu** [comment]
I rerun the test case (twice, in the span of 6 days ..ha) and it is now passing. @matthewd @rafaelfranca would either of you mind merging this in if this is good to go?

**Pull request merged**
