### PR TITLE
Fix turbolinks warning in railties test

### PR DESCRIPTION
**Pull request by yhirano55**
### Summary

* Upgrade turbolinks from v5.0.1 to v5.1.0
* Fix warning in railties test: `warning: assigned but unused variable - visit_action`

### CODE REVIEW

**Comment by kamipo** [comment]
Released gem won't fix the warning?

**Comment by yhirano55** [comment]
@kamipo Yes. After bump 5.1.0, fixed the warning.

**Comment by pixeltrix** [comment]
Perhaps we should just release a 5.1.1 version of the gem? The node module is on 5.1.1 already so it's not like we're matching versions.

**Comment by yhirano55** [comment]
@pixeltrix Thanks for the comment. I'll wait v5.1.1 release [[link](https://github.com/turbolinks/turbolinks-rails/pull/36)]. If v5.1.1 releases, I'll remove github shorthand from thurbolinks line in Gemfile.

**Comment by rafaelfranca** [comment]
5.1.1 was released now we just need to update this PR.

**Comment by yhirano55** [comment]
I'll fix this soon. Thanks.

**Comment by yhirano55** [comment]
I've fixed this.

**Pull request merged**
