### PR TITLE
ActiveRecord::Associations::Preloader should not count all records as already preloaded if only first is

### PR DESCRIPTION
**Pull request by faucct**
I have found this bug using the `Preloader` directly instead of `includes`, so I am still trying to get a minimal reproducible example.

### CODE REVIEW

**Comment by faucct** [comment]
I don't think there is a way to get already loaded mixed with not loaded when using `Relation#preload`. I won't be able to provide an example for this one.

**Comment by kamipo** [comment]
Why do you want to pass already loaded records mixed with not loaded records?

**Comment by faucct** [comment]
Because in our project `Preloader#preload` is being called per serializer field.
Here is a data structure we have: there `Plan <- Phase <- Billing`.
Plan serializer has two fields containing phases, but only the first one requires billing to be loaded to calculate its value. So first call to preloader preloads plans phases with billings, second call preloads just plans phases, third call is the preload of Billings for Phases from both Plan fields. Then first phases will have billings preloaded and the second ones won't.

**Comment by faucct** [comment]
So, what do you think?

**Comment by faucct** [comment]
ping

**Comment by faucct** [comment]
ping

**Pull request closed without merging**
