### PR TITLE
[WIP] Log the code/routes reloading attempts to help debugging

### PR DESCRIPTION
**Pull request by chancancode**
This was briefly discussed with @fxn earlier, so here is a quick implementation to make sure we are on the same page.

I guess my main question is if the message is clear enough? Also, should this be a full-on AS::Instrumentation? I don't see much value in the constant flushing (that's supposed to take almost no time, c/d?) but knowing how long it takes to rebuild the routes table would be helpful, I think. However, that should probably be added inside the routing code directly (and could be tackled separately)?

### CODE REVIEW

**Comment by andyatkinson** [comment]
@chancancode I read the log messages. They'd give me enough information to search in Rails and look at the code in more detail if I needed to during debugging. :+1:

**Comment by maclover7** [comment]
:+1:

**Comment by chancancode** [comment]
@fxn does this still look reasonable? If there are other changes I need to make I can probably fix it and merge before the beta; otherwise if we are feeling meh about it, I can just close it :smile:

**Comment by fxn** [comment]
@chancancode I think the idea of the warning is fine, but there are a few things that I don't see clear. For example, if routes are being reloaded, constants are reloaded also. Same with locales, which do not have a warning in the patch.

Then "classes and constants" mixes two levels of details. Technically all we unload/reload are constants. If the file *app/models/x.rb* defines `X = 1`, that one is going to be reloaded. So we have two levels, either we are informal and say "class and modules" to be less precise but understandable by more people probably, or else only "constants".

What do you think?

**Comment by fxn** [comment]
Another option is "application code", which is even more vague, and therefore the license we take is even more obvious and understandable for those that know what is going on, and the same time good enough to communicate to a beginner.

**Pull request closed without merging**
