### PR TITLE
Backport #20569 and #17885 into 4-2-stable

### PR DESCRIPTION
**Pull request by davidcornu**
Cherry picked 40664444eef2432fc564d8eecb647854bd06e5c3 from #20569 and 07f8a96aa14b642a8641dcb22dad07f995d3917e from #17885 into `4-2-stable`.

### CODE REVIEW

**Comment by davidcornu** [comment]
cc @theSteveMitchell & @rafaelfranca

**Comment by rafaelfranca** [comment]
R? @rafaelfranca

@senny made some modifications in the original commit so it is better to backport it 3931cec9cd3091ef4b8ee40066b896385d2085ea. For completness please backport cd3983a95a82ff361e111df02006549d88e71dbe too

**Comment by davidcornu** [comment]
> For completness please backport cd3983a too

Will do. Am getting the tests working first

**Comment by davidcornu** [comment]
@rafaelfranca Good to go.

**Comment by davidcornu** [comment]
@senny any reason you removed `ActiveRecord::Tasks::DatabaseTasks.run_cmd` when you merged https://github.com/rails/rails/pull/17885? I ended up merging the commit in the PR but didn't notice the changes you made in the merge.

**Comment by senny** [comment]
@davidcornu I outlined in the PR why I made those changes. See https://github.com/rails/rails/pull/17885#issuecomment-129890986

**Comment by davidcornu** [comment]
@senny makes sense. Thanks for making the change. I meant to fix it once you replied but the PR was yolomerged before I could.

Thanks all :tada:

**Pull request merged**
