### PR TITLE
Fix QueryCache concurrent issue

### LINKED ISSUE #40608: can't add a new key into hash during iteration lib/active_record/connection_adapters/abstract/query_cache.rb
### Steps to reproduce

Since it is caching problem, it is tricky to reproduce

### Expected behavior

No error

### Actual behavior

backlog from the first case:

```ruby
gems/activerecord-6.1.0.rc1/lib/active_record/connection_adapters/abstract/query_cache.rb:54:in `block in initialize': can't add a new key into hash during iteration (RuntimeError)
    from gems/activerecord-6.1.0.rc1/lib/active_record/connection_adapters/abstract/query_cache.rb:111:in `block in cache_sql'
    from gems/activesupport-6.1.0.rc1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
    from gems/activesupport-6.1.0.rc1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
    from gems/activesupport-6.1.0.rc1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
    from gems/activesupport-6.1.0.rc1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
    from gems/activesupport-6.1.0.rc1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
    from gems/activerecord-6.1.0.rc1/lib/active_record/connection_adapters/abstract/query_cache.rb:109:in `cache_sql'
    from gems/activerecord-6.1.0.rc1/lib/active_record/connection_adapters/abstract/query_cache.rb:101:in `select_all'
    from gems/activerecord-6.1.0.rc1/lib/active_record/connection_adapters/mysql/database_statements.rb:12:in `select_all'
    from gems/activerecord-6.1.0.rc1/lib/active_record/relation/calculations.rb:200:in `block in pluck'
    from gems/activerecord-6.1.0.rc1/lib/active_record/relation.rb:868:in `skip_query_cache_if_necessary'
    from gems/activerecord-6.1.0.rc1/lib/active_record/relation/calculations.rb:196:in `pluck'
```

yet another one:
```
gems/activerecord-6.1.0.rc1/lib/active_record/connection_adapters/abstract/query_cache.rb:54:in `block in initialize': can't add a new key into hash during iteration (RuntimeError)
    from gems/activerecord-6.1.0.rc1/lib/active_record/connection_adapters/abstract/query_cache.rb:111:in `block in cache_sql'
    from gems/activesupport-6.1.0.rc1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
    from gems/activesupport-6.1.0.rc1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
    from gems/activesupport-6.1.0.rc1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
    from gems/activesupport-6.1.0.rc1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
    from gems/activesupport-6.1.0.rc1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
    from gems/activerecord-6.1.0.rc1/lib/active_record/connection_adapters/abstract/query_cache.rb:109:in `cache_sql'
    from gems/activerecord-6.1.0.rc1/lib/active_record/connection_adapters/abstract/query_cache.rb:101:in `select_all'
    from gems/activerecord-6.1.0.rc1/lib/active_record/connection_adapters/mysql/database_statements.rb:12:in `select_all'
    from gems/activerecord-6.1.0.rc1/lib/active_record/querying.rb:47:in `find_by_sql'
    from gems/activerecord-6.1.0.rc1/lib/active_record/statement_cache.rb:150:in `execute'
    from gems/activerecord-6.1.0.rc1/lib/active_record/associations/association.rb:227:in `find_target'
    from gems/activerecord-6.1.0.rc1/lib/active_record/associations/collection_association.rb:274:in `load_target'
    from gems/activerecord-6.1.0.rc1/lib/active_record/associations/collection_proxy.rb:43:in `load_target'
    from gems/activerecord-6.1.0.rc1/lib/active_record/associations/collection_proxy.rb:1002:in `records'
    from gems/activerecord-6.1.0.rc1/lib/active_record/relation/delegation.rb:88:in `each'
```

### System configuration
**Rails version**: 6.1.0.rc1

**Ruby version**: 2.5.8

Connect replaygaming/replaypoker#4860
Connect #24627

### PR DESCRIPTION
**Pull request by kvokka**
<del>This should fix it. By the way, Mutex_m is a stdlib goodie, so i did not bring any extra dependency.</del>

<del>Re-use common lock, running the patch as a canary in production (since idk how to properly reproduce it locally). </del>

`Hash#default_proc` is not thread safe, which leads to random errors under high load. The problem is, that with `default_proc` hash is actually add elements on any read attempt:

```
[1] pry(main)> h = Hash.new {|h,k| h[k]={} }
=> {}
[2] pry(main)> h[:foo]
=> {}
[3] pry(main)> h
=> {:foo=>{}}
```

With this change we will do all writes in 1 place under the lock how it should be.

This change was already tested in our production environment for a few days.

Close #40608

### CODE REVIEW

**Comment by rafaelfranca** [comment]
All operations over the query cache are already syncronized with the same lock. Are you sure your application is not iterating over the query cache without syncronizing in the lock?

**Comment by kvokka** [comment]
No. I'm in the process of rails upgrade and with the previous versions it just worked out of the box (and i did not find any hint that i need to do such a change in release notes or upgrade notes). And since i'm getting it in a very different parts of the application the idea was that it is something rails related.

Are you suggesting to add locking manually instead?

by the way, the addition of the synchroniser to `@query_cache` did not make a change :(

**Comment by rafaelfranca** [comment]
I'm suggesting that maybe you have some code, or a gem, that is iterating in the query cache without acquiring the lock. We have a huge Rails application, running this current code and he didn't see this problem ever manifest. Not only we, but Basecamp and GitHub. Looking the code in that file all places that iterating in the query cache already acquire the lock so I think the source of your problem is not inside Rails.

**Comment by kvokka** [comment]
To iterate query_cache directly is required to make a huge spike, cos query_cache is a private method and . But using `Hash#default_proc` here is not safe, cos any attempt to read from the Hash will also write in it (adding `{}` as a value, and this may produce boom).

I will not argue, that the problem might be in our code (or some dependencies), since Rails are very well tested under a huge load. But in my case, with out this change i got ~5 errors per day in production in random places with very similar backlog.

This small change fix it. Maybe it'll save somebody's day or will help reveal the root of the problem later on.

**Comment by EtienneDepaulis** [comment]
Thanks to @rafaelfranca comment I think we might have identified the issue on our side. Only one gem (`activerecord-import`) was manipulating the query cache without the locking strategy. 
https://github.com/zdennis/activerecord-import/pull/719 is supposed to fix it (but this kind of issue is hard to reproduce in a test suite :().

To identity the gem I opened my `./rbenv/version/2.7.2` folder and did a quick search on `query_cache` and `QueryCache` and voila :)
I hope it helps

**Pull request closed without merging**
