### PR TITLE
Add options to ActiveRecord::Relation#explain

### PR DESCRIPTION
**Pull request by aderyabin**
Support database specific options for ANALYZE requests.

### Summary
`EXPLAIN` displays the execution plan for the supplied statement and supports very useful options according to [documentation](https://www.postgresql.org/docs/9.4/static/sql-explain.html) like `ANALYZE`. For example, usage `EXPLAIN ANALYZE`displays timing information.

Another option is a `FORMAT`. It specifies the output format. 

Current implementation `ActiveRecord::Relation#explain` does not support any options. 
I've implemented support for PostgreSQL's options (`ANALYZE`, `VERBOSE`, `BUFFERS`, `TIMING` and `FORMAT`). 

`FORMAT` supports `TEXT`, `XML`, `JSON`, or `YAML`. 

MySQL [supports](https://dev.mysql.com/doc/refman/5.7/en/explain.html) support `EXTENDED`, `PARTITIONS ` and `FORMAT` options.

#### PostgreSQL
```ruby
JSON.load(Author.where(id: 1).explain(format: :json)[0])

# [{"Plan"=>{"Node Type"=>"Index Scan", "Parallel Aware"=>false, "Scan Direction"=>"Forward", "Index Name"=>"authors_pkey", "Relation Name"=>"authors", "Alias"=>"authors", "Startup Cost"=>0.15, "Total Cost"=>8.17, "Plan Rows"=>1, "Plan Width"=>120, "Index Cond"=>"(id = '1'::bigint)"}}]

Author.where(id: 1).explain(analyze: true)
#                                                        QUERY PLAN
# ------------------------------------------------------------------------------------------------------------------------
#  Index Scan using authors_pkey on authors  (cost=0.15..8.17 rows=1 width=120) (actual time=0.005..0.005 rows=1 loops=1)
#    Index Cond: (id = '1'::bigint)
#  Planning time: 0.059 ms
#  Execution time: 0.015 ms
# (4 rows)

puts Author.where(id: 1).includes(posts: [:comments]).explain(format: :json)
[
  {
    "Plan": {
      "Node Type": "Index Scan",
      "Parallel Aware": false,
      "Scan Direction": "Forward",
      "Index Name": "authors_pkey",
      "Relation Name": "authors",
      "Alias": "authors",
      "Startup Cost": 0.15,
      "Total Cost": 8.17,
      "Plan Rows": 1,
      "Plan Width": 120,
      "Index Cond": "(id = '1'::bigint)"
    }
  }
]
[
  {
    "Plan": {
      "Node Type": "Bitmap Heap Scan",
      "Parallel Aware": false,
      "Relation Name": "posts",
      "Alias": "posts",
      "Startup Cost": 4.16,
      "Total Cost": 9.50,
      "Plan Rows": 2,
      "Plan Width": 136,
      "Recheck Cond": "(author_id = '1'::bigint)",
      "Plans": [
        {
          "Node Type": "Bitmap Index Scan",
          "Parent Relationship": "Outer",
          "Parallel Aware": false,
          "Index Name": "index_posts_on_author_id",
          "Startup Cost": 0.00,
          "Total Cost": 4.16,
          "Plan Rows": 2,
          "Plan Width": 0,
          "Index Cond": "(author_id = '1'::bigint)"
        }
      ]
    }
  }
]
[
  {
    "Plan": {
      "Node Type": "Seq Scan",
      "Parallel Aware": false,
      "Relation Name": "comments",
      "Alias": "comments",
      "Startup Cost": 0.00,
      "Total Cost": 15.36,
      "Plan Rows": 8,
      "Plan Width": 216,
      "Filter": "(post_id = ANY ('{1,2,4,5,6}'::integer[]))"
    }
  }
]
```

#### MySQL
```ruby
JSON.load(Author.where(id: 1).explain(format: :json)[0])
# {"query_block"=>{"select_id"=>1, "cost_info"=>{"query_cost"=>"1.00"}, "table"=>{"table_name"=>"authors", "access_type"=>"const", "possible_keys"=>["PRIMARY"], "key"=>"PRIMARY", "used_key_parts"=>["id"], "key_length"=>"8", "ref"=>["const"], "rows_examined_per_scan"=>1, "rows_produced_per_join"=>1, "filtered"=>"100.00", "cost_info"=>{"read_cost"=>"0.00", "eval_cost"=>"0.20", "prefix_cost"=>"0.00", "data_read_per_join"=>"2K"}, "used_columns"=>["id", "name", "author_address_id", "author_address_extra_id", "organization_id", "owned_essay_id"]}}}
```

### CODE REVIEW

**Comment by fatkodima** [comment]
duplicate? https://github.com/rails/rails/pull/15829

**Comment by aderyabin** [comment]
@fatkodima Good question.

There are several differences:
* `FORMAT` option returns raw result. And you can export it to Explain analyzers.
```
JSON.load(Author.where(id: 1).explain(format: :json)[0])
```
* Checks `FORMAT` value
* Works correctly with eager loading and collects all queries
* Supports `FORMAT` option for MySQL
* Up to date without conflicts

**Comment by simi** [comment]
I have created PR just supporting just JSON ("machine readable") format at https://github.com/rails/rails/pull/37970.

**Comment by simi** [comment]
:information_source: Just to explain difference in here and #37970. This seems to be more developer oriented and personally I think developer can just get query, extend and run on its own. Also it would be probably hard to support all adapter only related options in here.

At #37970 the motivation is slightly different. I would like to use explain on query to get estimated amount of rows returned, which could be handy to show in application (for example for long running exports to notify user about the predicted amount of lines). Currently (I mean without current API) it is possible only by parsing explain result. Introducing JSON format makes it possible to ingest explain data as Ruby hash making this much easier. Also JSON format of explain is supported by both main adapters (MySQL and PostgreSQL) and code change is much smaller.

**Comment by dorianmarie** [comment]
Too bad this didn't get merged, this would be very helpful

**Comment by aderyabin** [comment]
@schneems What do you think about reincarnation the PR with up-to-date code?

**Pull request closed without merging**
