### PR TITLE
Allow rails to serve brotli encoded assets

### PR DESCRIPTION
**Pull request by RyanEdwardHall**
When using an external build process (webpack, grunt) it's helpful for
rails to be able to serve those assets. Brotli has better compression
than gzip and should eventually replace it for static assets.

### CODE REVIEW

**Comment by swrobel** [comment]
@schneems @matthewd any chance of this making it in? I'm working on the compressed filetype changes we [discussed here](https://github.com/rails/rails/commit/8e31fa3b72892f7421b85b5a79d71a2d726ccddd#commitcomment-23933895) and I'm wondering if I should keep these changes in mind.

**Comment by RyanEdwardHall** [comment]
I would still love to see these changes go in and can find a little time to work on the pull request to accommodate any feedback. Just let me know :+1:

**Comment by schneems** [comment]
I'm not opposed to the idea. I'm worried about implementation overhead. Very few people touch action dispatch static or the underlying behavior.

@nateberkopec any thoughts?

**Comment by matthewd** [comment]
The current implementation looks wrong, because (unless I'm misreading) it fails to return a Vary header when the compressed file exists but the current client doesn't accept it. But that's fixable easily enough.

(If I'm right about that, it suggests we're already missing a test on that behaviour for gzip.)

It's yet another file stat for every [deemed potentially-compressible] response from Static... but maybe the difference from 2 to 3 isn't worth caring so much about.

**Comment by nateberkopec** [comment]
> It's yet another file stat for every [deemed potentially-compressible] response from Static... but maybe the difference from 2 to 3 isn't worth caring so much about.

I think that's definitely the case here. Brotli has a lot of adoption and will probably become more and more standard over the next 5 years. [Most browsers accept it now](https://caniuse.com/#feat=brotli), it's mostly CDNs that are slow on the uptake.

**Comment by brian-kephart** [comment]
I've been looking into serving brotli compression and came across this PR. It doesn't appear to have been reviewed since the issue pointed out by @matthewd was fixed. Any chance of it getting a look?

**Comment by jmreid** [comment]
I ran some benchmarks for this PR vs master:
https://gist.github.com/jmreid/a2b63e1d013e43ee518f2585d58bbdc1

```
============================== No Accept-Encoding ==============================

Warming up --------------------------------------
              Master     1.414k i/100ms
      RyanEdwardHall     1.179k i/100ms
Calculating -------------------------------------
              Master     14.969k (±11.7%) i/s -     73.528k in   5.007588s
      RyanEdwardHall     12.686k (±10.3%) i/s -     62.487k in   5.005175s

Comparison:
              Master:    14969.1 i/s
      RyanEdwardHall:    12685.9 i/s - same-ish: difference falls within error


============================= gzip Accept-Encoding =============================

Warming up --------------------------------------
              Master     1.425k i/100ms
      RyanEdwardHall     1.135k i/100ms
Calculating -------------------------------------
              Master     13.699k (±13.2%) i/s -     66.975k in   5.019272s
      RyanEdwardHall     11.261k (±13.1%) i/s -     55.615k in   5.076301s

Comparison:
              Master:    13699.4 i/s
      RyanEdwardHall:    11261.1 i/s - same-ish: difference falls within error


=========================== gzip,br Accept-Encoding ============================

Warming up --------------------------------------
              Master     1.371k i/100ms
      RyanEdwardHall     1.149k i/100ms
Calculating -------------------------------------
              Master     13.812k (±11.3%) i/s -     68.550k in   5.059261s
      RyanEdwardHall     11.238k (±12.6%) i/s -     55.152k in   5.028531s

Comparison:
              Master:    13811.7 i/s
      RyanEdwardHall:    11238.4 i/s - same-ish: difference falls within error
```

**Comment by swrobel** [comment]
This would be really great to see merged now that [Webpacker supports brotli](https://github.com/rails/webpacker/pull/2273)

**Comment by nateberkopec** [comment]
Just to chime back in, Brotli is certainly _as_, if not _more_ relevant than it was in 2017.

**Comment by schneems** [comment]
Might be worth revisiting. I agree it's more important now. I'm concerned about the performance impact for developers who are not serving brotli files.

Do you have any data on what browsers support is like? If all major browsers support it, we should perhaps move sprockets from generating gzip files to brotli by default?

**Comment by jmreid** [comment]
Browser support is very high:
https://caniuse.com/#search=brotli

image

My vote is to get Brotli support into Rails ASAP. In one case for our apps, Brotli would save 750+ KB of JS, 21KB+ of CSS, 150KB+ of SVG (if the whole front-end app was loaded). And a lot of apps have nice smaller wins (like dropping a highly used js file from 85KB to 73KB). On slower cellular connections this ends up being some major savings.

**Comment by swrobel** [comment]
@schneems would love to see if there's interest on your end at this point, esp since Heroku is one of the rare situations where one is serving assets directly from the rails server rather than through nginx, where it's easy to configure brotli assets to be served.

**Comment by gnclmorais** [comment]
@swrobel, people that use Amazon CloudFront have to compress their own assets and upload them, they don’t support anything besides gzip out of the box (as we can see on their [documentation][0]).

[0]: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html#compressed-content-custom-origin

**Comment by nateberkopec** [comment]
@gnclmorais 

> But if you want to compress other file types, or if you want to use a compression algorithm that isn’t gzip , such as brotli , you can compress the files on your own server, and then serve the files by using CloudFront. 

^^ That is exactly what this pull request would enable.

**Comment by gnclmorais** [comment]
Yes, sorry if I misunderstood @swrobel — I guess I’m adding to the argument and kindly asking for this feature to be considered…! 🙇🏻‍♂️

**Comment by jeremy** [comment]
Merged in #38674. Thanks @RyanEdwardHall!

**Pull request closed without merging**
