### PR TITLE
Improving av

### PR DESCRIPTION
**Pull request by printercu**
Related to https://github.com/rails/rails/issues/27273

Here are some changes which help investigate the leak, and choose the right strategy.

### CODE REVIEW

**Comment by kaspth** [comment]
Thanks, but these achanges are cosmetic ones, which we don't accept 😊

**Comment by printercu** [comment]
@kaspth Why do you need non-instantiatable classes? It's hard to understand, if its used anywhere as instance or not. Take a look at a batch of methods with long list of arguments.

It's all about code smell.

**Comment by printercu** [comment]
Ok, let it be WIP commit for fixing #27273. Is fixing memory leak a cosmetic change?

**Comment by kaspth** [comment]
@printercu just because a class isn't instantiated doesn't necessarily mean it should become an includable module. Then having these as classes better fits our intent, I think.

> Ok, let it be WIP PR for fixing #27273. Is fixing memory leak a cosmetic change?

Yes, let's fix that in a new PR: https://github.com/rails/rails/issues/27273#issuecomment-265384347

**Pull request closed without merging**
