### PR TITLE
Documentation: a Rails guide for concerns

### PR DESCRIPTION
**Pull request by maryammouse**
I noticed that there's no Rails guide on concerns and how to use them/what they're for. I've written up a guide on how, when and why to use concerns. I consider it a 'work in progress' guide, as I know there is more to concerns than I have written (especially conceptually) and this is my first contribution! I hope it's all right. :)

EDIT Dec 18th 2019 -- 
Due to very early feedback to this PR, the last commit drastically shortens the Guide, in preparation for it to be put in a different section - but I never heard back from the contributors about what to do next. If you'd like to see the full guide, please check out the first 2-3 commits. Or https://github.com/rails/rails/pull/21114/commits/b09e0d4b04c02db7268505bf5048faddd1ded6cf?short_path=302f83d#diff-302f83dd09e2a6ff90f3fb9ab6df03e2 -this is the last commit before I drastically shortened it. Be sure to un-hide the rest of the guide so you can see beyond the changes in that single commit! :) I would be happy to restore this version of the guide, so if you would like that, please let me know.

### CODE REVIEW

**Comment by matthewd** [comment]
cc @fxn

**Comment by fxn** [comment]
Thanks for working on this proposal.

About the draft itself, needs guidelines applied, refer to *methods* rather than *functions*.... The concern in the example does not need `ActiveSupport::Concern`.... The draft needs a pass.

But besides, I have the feeling that it's a lot of material to just say: concerns are supposed to be modules shared among different controllers or models, and added to `autoload_paths`. That's basically all there is to it. Hence, not sure it deserves a guide by itself, but on the other hand the intent of this folder should be documented.

Maybe in some of the existing guides?

**Comment by maryammouse** [comment]
Looking through the other guides I can't see one where this information would fit except possibly the 'Getting Started with Rails' guide, or a new 'Miscellaneous' section. I understand that concerns are not a major feature of Rails so not necessarily worth a guide dedicated to them but they are also enough their own 'thing' that they don't seem to fit anywhere else. If you can see a place for it in an existing guide, I'll happily put a shortened version of the guide there :) Thanks for the feedback by the way! I didn't realize there was a guidelines guide also available on the Rails guides - I'll definitely be checking it out.

**Comment by aditya-kapoor** [comment]
@fxn I am :+1: on adding a miscellaneous topics in the Rails guides. These include shorthand and crisp topics which do not need an entire guide.

**Comment by maryammouse** [comment]
Hello everyone, just wanted to see where we are with this :) Once I have a go-ahead I'll make the Miscellaneous guide and put a small 'Concerns' section in it with the proper guidelines applied.

**Comment by mrtorks** [comment]
A :+1: for the suggestion made by @maryammouse

**Comment by maryammouse** [comment]
All right, that is a go-ahead - I'll make the changes then! I just read through some material that told me that any changes I make to my fork will be included in the pull request, which is good to know (didn't want to lose this comment history).

Now, I'd be happy to know one other thing if anyone can answer - what is the etiquette on mentioning people here? It seems that fxn and others seem to have the authority on pull requests and their content, and I was wondering if anyone could mention them or if that is something they prefer that only those who have contributed a lot do. I'd like to get input -  from one of them at least (more feedback is always welcome!) - on my updated proposal, but I can do without until I have actually made the new guide.

**Comment by fxn** [comment]
@maryammouse this proposal has the support of some people, but that doesn't mean a go-ahead. That's a decision of the [Rails core team](http://rubyonrails.org/core/).

Personally, I am not yet convinced to have a misc guide because there's only one potential topic candidate so far, and because even if it was decided that such candidate deserves a misc guide, it may easily become a kitchen sink.

Volunteering to write these docs is really appreciated, only we need to kind a place for them.

**Comment by maryammouse** [comment]
All right, that makes sense. :) No problem! Thanks for the link. I figured a proper go-ahead would be from the people who really run Rails but I did not want to presume someone was or wasn't part of the team and wasn't sure where to find out who was. You learn something new every day, eh?

If anyone has other ideas for where to put it or a decision is made, please let me know :) It seems like the consensus is that this is a useful bit of documentation but we just need to find a good place. I'm excited about contributing and eager to find that place.

**Comment by maryammouse** [comment]
I've condensed the guide so that it's smaller and satisfies the guidelines. :)

**Comment by sgrif** [comment]
r? @fxn 

This seems fine to me, but I'll leave the final decision to you.

**Comment by maryammouse** [comment]
Heya @fxn - it's been a while, so I figured I'd tag you as a reminder! If this is how long it usually takes to accept/reject a pull request, let me know.

**Comment by fxn** [comment]
@maryammouse thanks for the ping.

The time for acceptance/rejection depends, some things are in right away, some need thought, or whoever is working on them just doesn't have enough bandwith.

This particular PR, as is, cannot be merged because of the reasons I explained above. But I didn't want to reject because I appreciate your effort to write this and thought maybe we can insert this or a reduced version of this somewhere. Just didn't get to investigate it.

**Comment by maryammouse** [comment]
I appreciate the reply!  think, in edited and further reduced forms, it could be added as:

Section (3.1) of Active Controller Overview's Chapter 3: Methods and Actions 
Section (6.3) of Active Record Validations Chapter 6: Performing Custom Validations
(possibly) as a sidenote in Active Record Callbacks Chapter 9: Callback Classes

Or, as a yellow-info-box for each Chapter, instead.

If you agree, I'll alter this PR so that it no longer has concerns.md and instead has edited versions of each of those guides. For each section that I would add, I will of course _not_ add the current file as is, but would write a smaller, more specific version for each guide.

 EG for Ch 3: Methods and Actions, I would remove any mentions of models and most of the other stuff, leaving something like: 

>  If you find your controller file getting too big, you might want to write a concern. A concern is a module you create in controllers/concerns that should contain methods you would like to be able to use for multiple controllers and/or actions. They are a good way to keep your controllers small and keep your code DRY. Simply include or extend the concern module into your controller to use its methods.


@fxn ? :)

**Comment by maryammouse** [comment]
@fxn I know it's been a long long time, but wondered if this could be added or a decision had been made? I wrote a comment a few years ago about how we could add this to existing guides, if it doesn't warrant one of its own.

**Comment by lucascaton** [comment]
Any news on this one?

**Comment by maryammouse** [comment]
I wish! Who should we be tagging to sort this out?

**Comment by maryammouse** [comment]
@fxn or @sgrif ?

**Comment by eloyesp** [comment]
May be the rails core team need to understand that _gender bias_ are **concern**, we might need to read something like:

> Evidence that gender bias exists in the field of computer science has emerged in the form of a new study examining acceptance rates of contributions from men and women in an open-source software community. The study’s findings indicated that women’s contributions were rejected more often, but only 
if their gender is identifiable. If, in fact, it is unclear whether the contributor is a man or a woman, women’s contributions tended to be accepted at a greater rate. [Source](https://www.digitaltrends.com/computing/github-gender-bias/)

So it seems that @maryammouse might have better luck after changing her profile image :disappointed: 

But that is a paper, it does not happens in the real world, this comic is just a coincidence:

[Have fun with this](http://rachelnabors.com/2012/04/of-github-and-pull-requests-and-comics/)

On the other hand, I were searching rails guides and missed a sections about concerns, thanks. :+1: .

**Comment by aegatlin** [comment]
Luckily this many-years-old PR has decent enough SEO at this point, so I was able to read the file and get the brief intro to it I needed. Thanks @maryammouse ! I hope it gets merged in eventually :D

**Comment by maryammouse** [comment]
I would still like to get feedback and get this merged in if possible - would be great to hear who I should reach out too! Posted a message on the IRC channel, just in case. :)

**Comment by ritchiea** [comment]
Hey @maryammouse I saw your post in IRC that you would like to see this merged. I am by no means an expert on what it takes to get something merged into a Rails guide but I have at times been unsure about the best use of concerns so I read your contribution out of curiosity and a desire to support you getting it merged.

IMO it is a bit sparse and doesn't go into the detail and depth of examples in the existing Rails guides and after reading it I didn't feel I had a better grasp on concerns than before I started it. Have you read some of the other Rails Guides that are a bit misc themselves like writing plugins for Rails? As well as the guides to writing API Documentation and Guides themselves that include suggestions like writing out meaningful code examples?

A guide to concerns could be very helpful but this does not feel thorough enough to be a strong addition to Rails Guides.

**Comment by maryammouse** [comment]
@ritchiea Thanks for your feedback, it's much appreciated! The original Guide that I wrote was actually quite a bit longer. If you examine the first few commits, you can see it contained actual code examples -- based on feedback given by the contributors years ago which you can see in the PR comments, they were struggling to find a place for this and were thinking it ought to be shortened and put in a section of an existing guide. I personally agree with you that a longer guide would be much more useful :) Would you mind taking a look at the first few commits, in case you have any suggestions on how they could be improved?

**Comment by eloyesp** [comment]
I agree that the first version makes more sense as a guide, including at least an example. Also I think there are two issues with those, on one hand it lacks information about the adventages of `Conserns` over normal `Modules`, so it should include details about the methods provided: `ìnclude` `included` and `class_methods`. ([source](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/concern.rb)).

The other issue I find is that the given example is too specific, most of the examples on the guides are from a blog application, an store, or social network, that are models well known by many developers and requires less context.

**Comment by fxn** [comment]
I am 👎 on a guide for concerns.

The things you drop in a `concerns` directory by convention are modules to factor stuff out from classes or modules. As you do with modules! That's it, there is not a lot to say. It is like wanting to have a guide for the `lib` directory, it is disproportioned.

Explaining the content of `concerns` directories in my mind belongs to a description of the project structure. Like `lib`.

Then, `ActiveSupport::Concern` provides a DSL to simplify what you'd do in `included` hooks. And despite the name, that feature is orthogonal to the so-called "concerns", it is just a generic utility you can plug in any module, and with a documented usage in the API module documentation.

**Comment by eloyesp** [comment]
Anyway, I saw that folder and searched for that in the rails guides, I think that extracting code from controllers and models are a pretty interesting subject (it's what most Rails books out there are about) and the concerns concept is the Rails way to solve it (I'm not sure if it is the best way, or [Trailblazer](http://trailblazer.to/) is a better approach), but the concept as a whole should be documented somewhere.

On the other hand, I think you are right that the API documentation of `ActiveSupport::Concern` is good, that doesn't need to be repeated on the guides, but a link would be appreciated.

**Comment by rafaelfranca** [comment]
Thank you for the pull request. Closing since it we don't want a guide only to explain concerns. I agree we could explain what the folder `concerns` means, but that should be in the project structure documentation

**Comment by maryammouse** [comment]
@rafaelfranca @fxn @eloyesp thank you all for your comments and feedback! :) I can understand if we don't want a whole guide, but in that case I'd love to help by adding at least a note in the project structure documentation - I do think there should be a Rails-official note about it, as the lack thereof was what inspired me to create this PR in the first place. I'll go ahead and see if such a thing has been added, and try to create a PR in the structure documentation if possible. 

Great to see a resolution and way forward on this after so long. Thanks again!

**Comment by kaspth** [comment]
@maryammouse your kindness is much appreciated! We did fail you in getting a response, but you didn’t lord it over us. Please do send that follow up PR, thanks 😄🙏

**Comment by tomharvey** [comment]
Thanks @maryammouse for this.

Sorry to comment in a closed PR. I get that you don't want a whole guide, but are the docstrings in https://github.com/rails/rails/blob/master/activesupport/lib/active_support/concern.rb the only canonical place for basic syntax for concerns?

**Comment by santib** [comment]
Hi @maryammouse thanks for your work on this PR.

I got here because of the conversation that happened in discourse: https://discuss.rubyonrails.org/t/helping-devs-understand-concerns-faster/74619/44 . I'd like to know if you are going to work on the follow up PR or if you'd prefer someone else to do it.

**Comment by maryammouse** [comment]
Hi @santib ! I have been meaning to get to it, but I got stuck due to the same thing you mentioned in that discussion link: I'm not sure where the "project structure documentation" is and haven't had much time to figure it out. It's a priority of mine, though, I've had a reminder going for a while and I'd very much like to write it up if we know where it can go :) Thanks for checking with me, I really appreciate your asking me first!

**Comment by maryammouse** [comment]
@kaspth Sorry for the delay - been thinking about these docs, but I had one blocking question and then life happened, as it often does. The particular question I had made me a bit apprehensive also, given how it was answered previously.

Where should the documentation go? - I know I was told to put it in the "project structure documentation" but I am honestly unclear about where specifically that is. :) 

My thought is that this might mean putting it in the [Getting Started guide](https://guides.rubyonrails.org/getting_started.html), since we actually do describe the project structure in detail there, though the guide goes beyond that also. Some suggestions (in the link Santiago mentioned) I have been given are that we could add sections into the [ActionController guide](https://guides.rubyonrails.org/action_controller_overview.html) and the [ActiveRecord guide](https://guides.rubyonrails.org/active_record_basics.html) - Should each guide have it’s own small “concerns” section? That seems like the most logical fit to me; there isn’t a clear spot for concerns in the sections that currently exist.

If we want to use existing sections, the ActionController Methods and Actions section could work, as well as the ActiveRecord’s Convention Over Configuration section. 

I hope we can figure this out soon - I am eager to make the PR! :)

**Pull request closed without merging**
