### PR TITLE
Avoid overflow-x on Welcome page

### PR DESCRIPTION
**Pull request by ixkaito**

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Thanks. How it is after this change?

**Comment by ixkaito** [comment]
Like this

**Comment by rafaelfranca** [comment]
For me it is more confusing. Looks like there is two more middlewares. Can we just change the output to use the class name instead of the instance name?

**Comment by ixkaito** [comment]
> For me it is more confusing. Looks like there is two more middlewares.

Yes, I'm also afraid of it.

> Can we just change the output to use the class name instead of the instance name?

Or, we can add more margin between each middleware.

**Comment by rafaelfranca** [comment]
I think the output change would be simpler. What is really important to show is the class of the middleware, so we should change the output to show that.

**Pull request closed without merging**
