### PR TITLE
Prevent `RangeError` for `FinderMethods#exists?`

### PR DESCRIPTION
**Pull request by kamipo**
`FinderMethods#exists?` should return a boolean rather than raising an exception.

### CODE REVIEW

**Comment by kamipo** [comment]
Related issues: #18134, #19688, #19717, #24238.

**Comment by sgrif** [comment]
Why did the uniqueness validator change from this commit? It seems unrelated to "Prevent `RangeError` for `FinderMethods#exists?`"

**Comment by kamipo** [comment]
https://github.com/rails/rails/pull/19688#issuecomment-90908759
> Rather than specifically handling the uniqueness validation, I wonder if it would make more sense to change `exists?` to always return false if it catches a `RangeError`.

`UniquenessValidator#build_relation` catches a `RangeError` because it includes type casting due to a string value truncation. But a string value truncation was removed at #23523 then type casting in `build_relation` is no longer necessary. aa06231 removes type casting in `build_relation` then a `RangeError` moves to `relation.exists?`.

https://github.com/kamipo/rails/blob/aa06231/activerecord/lib/active_record/validations/uniqueness.rb#L29-L35

```ruby
        if relation.exists?
          error_options = options.except(:case_sensitive, :scope, :conditions)
          error_options[:value] = value

          record.errors.add(attribute, :taken, error_options)
        end
      rescue RangeError
```

"Prevent `RangeError` for `FinderMethods#exists?`" will remove the catching a `RangeError`.

**Comment by sgrif** [comment]
Thanks for clarifying. Can you put that in the commit message?

**Comment by kamipo** [comment]
Updated the commit message!

**Pull request merged**
