### PR TITLE
Use is_a? instead of ===

### PR DESCRIPTION
**Pull request by p-mongo**
### Summary

Provide a general description of the code changes in your pull
request... were there any bugs you had fixed? If so, mention them. If
these bugs have open GitHub issues, be sure to tag them here as well,
to keep the conversation linked together.

### Other Information

If there's anything else that's important and relevant to your pull
request, mention that information here. This could include
benchmarks, or other information.

If you are updating any of the CHANGELOG files or are asked to update the
CHANGELOG files by reviewers, please add the CHANGELOG entry at the top of the file.

Finally, if your pull request affects documentation or any non-code
changes, guidelines for those changes are [available
here](http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#contributing-to-the-rails-documentation)

Thanks for contributing to Rails!

### CODE REVIEW

**Comment by danlo** [comment]
@kaspth This code alteration is due to how Mongoid (Mongoid::Document) proxy's it's objects.  The complete summery from mongodb is here: https://jira.mongodb.org/browse/MONGOID-4590  

Thank you,

Daniel Lo

**Comment by rafaelfranca** [comment]
We understand but Mongoid should not be doing that if it wants to implement GlobalID::Identification. Maybe mongoid should provide a way to add an interface in the proxy?

**Comment by rafaelfranca** [comment]
Another option is to mongoid implement `===` in the proxy that delegates to the object.

**Comment by p-mongo** [comment]
As explained in https://stackoverflow.com/questions/3528129/fooling-rubys-case-operator-with-proxy-objects#3528212 it is not possible to make === work with proxies, because it is not called on the proxy but on Class objects.

**Comment by rafaelfranca** [comment]
oh, that is true. Maybe we could get https://bugs.ruby-lang.org/issues/11505 reviewed by the ruby core and maybe in a future version of Ruby.

**Comment by p-mongo** [comment]
Seeing how the language change has no ETA, would you like me to make a PR against master to make it possible for users to use GlobalID with Mongoid?

**Comment by rafaelfranca** [comment]
I don't think we want to change Rails to support Proxy objects in Active Job, only because of Mongoid implementation details.

**Comment by p-mongo** [comment]
The patch in this PR is straightforward and gives globalid compatibility with any code using proxy objects, not just Mongoid. It also has no downsides/problems as far as I am aware.

**Comment by rafaelfranca** [comment]
It is not straightforward. This patch means that we can use case statements to check object classes anymore. I bet this is not the only place we need to change to accommodate proxy objects and we don't want to change all those places to do it.

I recommend mongoid to either remove the proxy object or let the proxy object also include `GlobalID::Serialization`

**Pull request closed without merging**
