### PR TITLE
Add 'rails restart' command.

### PR DESCRIPTION
**Pull request by ccallebs**
Adds `rails restart` command using infrastructure put in place by #22457. Also add deprecation warning to `rake restart`.

### CODE REVIEW

**Comment by ccallebs** [comment]
@kaspth Not sure how you want to do this. One PR per command?

**Comment by maclover7** [comment]
Created a master list of all rake tasks that need to be converted over at #22503. I'd say we should do one commit per task (can all be rolled up into one PR, I don't really care about that), just so it's easier to track changes (especially if something breaks later on).

**Comment by ccallebs** [comment]
@kaspth Should I close this PR? No biggie if so, just wanted to check!

**Comment by kaspth** [comment]
Yeah, let's hold off on this for now. Thanks!

**Pull request closed without merging**
