### PR TITLE
Skip delivery notification when perform_deliveries is false.

### PR DESCRIPTION
**Pull request by yskkin**
### Summary

If `perform_deliveries` is false, current master logs delivery of mail even if it is not delivered actually.
I think delivery notification should be skipped for this case.

### CODE REVIEW

**Comment by y-yagi** [comment]
This seems the expected behavior. Ref: https://github.com/rails/rails/issues/32754#issuecomment-385862666

**Comment by eugeneius** [comment]
How about logging a _different_ message when delivery is disabled, e.g.

> Skipped sending mail to test@email.com as `perform_deliveries` is false

**Comment by y-yagi** [comment]
Or how about including `perform_deliveries` in payload?
This will allow the user to deal with notificaiton when `perform_deliveries` is false.

**Comment by yskkin** [comment]
I think both of changing message and adding payload is required since user cannot detach LogScbscriber and LogScbscriber cannot know `perform_deriveries` without adding it to payload.
I'll update PR later unless I missed something.

**Comment by yskkin** [comment]
Thanks ❤️ 

By the way, as I added to the guide, if `perform_deliveries` is false, `AM::Base.deliveries` array will not be populated even if `delivery_method` is `:test`.

To me, it does not align well with https://github.com/rails/rails/issues/32754#issuecomment-385862666. Is this bug?

> the action of delivering the mail message is still performed and logged so people can for example see what is going to be delivered

**Comment by rafaelfranca** [comment]
No. The delivery is not made so we don't want to add the the `deliveries` array. But we wan to log it specially because in development delivery is disabled by default.

**Comment by yskkin** [comment]
I got it. Thank you for answer!

**Comment by DylanReile** [comment]
@yskkin @rafaelfranca 

In Rails 5 `ActionMailer::Base.deliveries` was populated by `deliver_later`, right? Do you know which commit made that change? 

Those of us not using Minitest (which works around this by calling `perform_enqueued_jobs`) after having this issue: https://stackoverflow.com/questions/57776074/rails-6-deliver-later-doesnt-affect-actionmailerbase-deliveries

**Pull request merged**
