### PR TITLE
Add missing routing tests for info controller

### PR DESCRIPTION
**Pull request by aditya-kapoor**

### CODE REVIEW

**Comment by eileencodes** [comment]
@aditya-kapoor thanks for the PR. :smile: I think the commit message should have more detail about why you added these tests - meaning explain what was missing that you wanted to add them.

**Comment by aditya-kapoor** [comment]
@eileencodes thanks for the review...
Should I change the commit message?

This is vaguely related to #21605 where I proposed to remove this `index` route but this was kept so I thought it made sense to add some tests regarding this.

**Comment by eileencodes** [comment]
Yes I'm just asking you to change the commit message. It's better for Rails in the long term to have commit messages that explain why we made changes.

**Comment by aditya-kapoor** [comment]
@eileencodes I have updated the commit message...:smiley:

**Comment by eileencodes** [comment]
By the way, I just noticed you had a typo in your test. Fixed in 0ce3b97

**Pull request merged**
