### PR TITLE
Added binstub to rails command in doc [ci skip]

### PR DESCRIPTION
**Pull request by yhirano55**
Added binstub to rails command in doc.

### CODE REVIEW

**Comment by georgeclaghorn** [comment]
The `rails` command executes the binstub when it’s invoked from inside a Rails app. We don’t need to do this.

**Comment by yhirano55** [comment]
@georgeclaghorn Thanks for the reviewing. I think that the rails command is different between rails and bin/rails. The rails depends on system global. On the other hand, the bin/rails depends on local app. Therefore, in the doc or the guide, each command should be described as different ones. What do you think about it?

**Comment by georgeclaghorn** [comment]
I don’t follow. My point is that it doesn’t matter whether you invoke the gem executable or the binstub. If you invoke the gem executable, the binstub is executed.

**Comment by yhirano55** [comment]
@georgeclaghorn Thanks for the reply. I understand your opinion. But many of `bin/rails` are described in guide ([search result](https://github.com/rails/rails/search?l=Markdown&q=bin%2Frails&type=&utf8=%E2%9C%93)). All of these would be better to be modified? (It might be cosmetic change)

**Pull request closed without merging**
