### PR TITLE
Various fixes in ActiveSupport::Notifications::Event

### PR DESCRIPTION
**Pull request by vishaltelangre**
##### Before

```ruby
ActiveSupport::Notifications.subscribe 'sleep' do |event|
  puts "Allocations: #{event.allocations}"
  puts "CPU time: #{event.cpu_time}"
  puts "idle time: #{event.idle_time}"
end

ActiveSupport::Notifications.instrument 'sleep' do
  sleep 1
end
```

prints

```
Allocations: 1
CPU time: 0.11399999999994748
idle time: 1001.9520000154749
```

But, calling `#cpu_time` doesn't work for an `ActiveSupport::Notifications::Fanout::Subscribers::Timed` subscriber.

```ruby
ActiveSupport::Notifications.subscribe 'sleep' do |*args|
  # Here, '*args' contains only 5 things, viz.
  # 'name', 'started', 'finished', 'unique_id' and 'data'.
  # Since the event is already finished somewhere,
  # there's no use of calling  '#start!' and '#finish!'
  # on the below event object in this block.
  event = ActiveSupport::Notifications::Event.new(*args)
  # Allocations haven't been computed for this event, so it becomes zero.
  puts "Allocations: #{event.allocations}"
  # Therefore, the 'cpu_time_start' and 'cpu_time_finish' will be 'nil'
  # for this event.
  # Calling '#cpu_time' doesn't work on this event and throws
  # "NoMethodError (undefined method `-' for nil:NilClass):" error.
  puts "CPU time: #{event.cpu_time}"
  # Calling '#idle_time' also breaks with same error
  # since it relies on `#cpu_time`.
  puts "idle time: #{event.idle_time}"
end

ActiveSupport::Notifications.instrument 'sleep' do
  sleep 1
end
```

prints

```
Allocations: 0
Traceback (most recent call last):
[...]
Users/vishaltelangre/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/rails-d1107f4d1e25/activesupport/lib/active_support/notifications/instrumenter.rb:99:in `cpu_time': undefined method `-' for nil:NilClass (NoMethodError)
```

##### After

With the fixes made in this PR, the above failing example now works and prints

```
Allocations: 0
CPU time: 0
idle time: 1003.7420000007842
```

#### 3. Removed `@duration` instance variable from `ActiveSupport::Notifications::Event`

Because
- If we call `#start!` and `#finish!` manually on the event object, then the memoized duration value is being returned instead of calculating duration based on the updated values of `@end` and `@time`.
- We do not have instance variables such as `@cpu_time`, `@idle_time` and `@allocations`, so having `@duration` is unnecessary since we already have a method to compute and return the duration. 
- Getting rid of the unnecessary `@duration` instance variable saves an allocation.
- Having @duration instance variable shows `@duration: nil` when the event object is inspected before calling the `#duration` method on that event object. This adds unnecessary confusion since `@time` and `@end` already have values.

### CODE REVIEW

**Review by jeremy — COMMENTED** [review]
Thanks @vishaltelangre. Test coverage demonstrating the expected behavior?

**Comment by vishaltelangre** [comment]
@jeremy I think the first case needs a test. Let me try to add that. The second and third case mentioned in PR's description seems already covered.

**Comment by vishaltelangre** [comment]
Added test coverage.

**Review by rafaelfranca — APPROVED** [review]

**Comment by jeremy** [comment]
```ruby
ActiveSupport::Notifications.subscribe 'sleep' do |*args|
  event = ActiveSupport::Notifications::Event.new(*args)
  event.cpu_time #=> boom
```

This case is expected, since `event.cpu_time` is meant to be called on an event that was explicitly started and finished then yielded to subscribers, not an event that was constructed from partial information.

However, calling these methods should definitely still work and not raise errors! But using `event.cpu_time` and `.allocations` is only intended to work when subscribing with a block taking a single `event` arg, rather than `*args`.

**Pull request merged**
