### PR TITLE
Puma is the only option used for the web server

### PR DESCRIPTION
**Pull request by dhh**
Doesn't make sense to remove the configuration needed as an option any more.

### CODE REVIEW

**Comment by abhaynikam** [comment]
@dhh `--skip-puma` option wasn't removed from the documentation -> `command_line.md` (https://github.com/rails/rails/blob/main/guides/source/command_line.md)

**Comment by dhh** [comment]
Fixed in https://github.com/rails/rails/commit/8d1b8e870c1c42859132c8d51ceff0ac72cbe34b 👍

**Comment by patleb** [comment]
Euh, I don't really mind removing puma by myself, but it's not true that Puma is the only web server. We are using Passenger for a good 10 years now and it's not going to get replaced by Puma anytime soon, since we have tools built around it. @dhh, I don't know if it was an oversight, but there is a business built around Passenger and this message might hurt them financially.

**Comment by dhh** [comment]
Passenger is great, even if it’s a niche offering in many ways. The “only option” was aimed at the previous situation where we had webrick, unicorn, etc on the open source side. Easy enough for folks to change from a puma default to passenger.

**Comment by patleb** [comment]
Ok, got it, thanks.

**Pull request merged**
