### PR TITLE
Array.second_to_last and Array.third_to_last access methods

### PR DESCRIPTION
**Pull request by brchristian**
Reading @dhh's [Rails Doctrine](http://rubyonrails.org/doctrine/) essay got me thinking a lot about Rails' `second` and `fifth` accessor methods, which I (like DHH) love so much.

One of the things that has occurred to me about once every month or two since I began working with Rails (back in 2008) is that it'd be nice to have similarly natural ways of accessing the end of an array or relation. We have `last`, but it ends there. It's slightly jarring (for me anyway) to go from `x.last` to `x[-2]`.

So, here's a proposal to add `penultimate` and `antepenultimate` as well. Partly for the delight factor, partly because I think it would actually be useful. (At least, it would to me.)

If `next_to_last` / `second_to_last` and `third_to_last` are more natural, we can easily use those instead, or make them aliases.

This is my first Rails PR, so I've tried to include everything (tests, documentation), but I'm happy to make alterations if I've missed anything.

### CODE REVIEW

**Comment by dhh** [comment]
Good thinking. I've wanted this as well! I'd prefer to go with second_to_last + third_to_last, though. penultimate and antepenultimate are both long, cumbersome, and little used words. Welcome to Rails contributions!

**Comment by brchristian** [comment]
Thank you! Yeah, `second_to_last` + `third_to_last` sound good to me too, and I've adjusted accordingly in e8aeda2ab39b5d416a72edfa74e0fb17721eb6f9.

**Comment by vipulnsward** [comment]
@brchristian this needs CHANGELOG entry.

**Comment by brchristian** [comment]
Thanks! Added activerecord and activesupport CHANGELOG entries in eaa1efe7d0b4e0f5682453b1ddfa186a292ddc86.

**Comment by jeremy** [comment]
Next up: `#the_end` and `#beginning_of_the_end` 😁

**Comment by kaspth** [comment]
@jeremy my 💸 is on `#apocalypse` and `#rapture` respectively.

**Comment by jeremy** [comment]
🤘

**Pull request merged**
