### PR TITLE
Pass wrapped class name to Sidekiq for logging purposes

### LINKED ISSUE #2248: show job class when using with activejob?
Is it possible to see the job's class name when using sidekiq with activejob? Before I switched to activejob, the logs displayed the job's class name, but now I just see this for every job:
```
2015-03-22T05:56:35.958Z 62398 TID-ouyejqm2o ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper JID-faa09ca86938646facc1b895 INFO: done: 116.916 sec
```
So I'm not sure which job just ran, unless I go look up the JID.

### PR DESCRIPTION
**Pull request by mperham**
Sidekiq logs the name of the job class being performed.  Because
ActiveJob wraps the class, this means currently every job logs as an AJ::JobWrapper
instead of the actual job name.

Will help fix mperham/sidekiq#2248

### CODE REVIEW

**Comment by mperham** [comment]
Any chance this can get in 4.2?  It's an active issue for all AJ users.

**Comment by rafaelfranca** [comment]
Backported at 94249d43f82601e8cc48473a131c748a203e9749

**Comment by rafaelfranca** [comment]
@mperham just did it.

**Comment by estum** [comment]
But it still logs the long AJWrapper name, doesn't it? I use a hook to replace it with the real job class name: https://gist.github.com/estum/dd67fc80bee60966672c.

**Comment by mperham** [comment]
Not on Sidekiq master. ;-)

**Comment by estum** [comment]
@mperham, yay, fresh commits! :-)

**Pull request merged**
