### PR TITLE
Use Thor for built-in tmp:cache:clear task

### PR DESCRIPTION
**Pull request by JuanVqz**
### Motivation / Background

This Pull Request has been created because I saw @p8 is moving some tasks to use Thor here #47610 thought I probably may help with it.

### Detail

This Pull Request migrates the `tmp:cache:clear` task to Thor

### Additional information

@p8 I hope this is okay with you, it will be nice to have a review or your opinion on this, thanks! 

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by p8** [comment]
@JuanVqz Ha, I just submitted https://github.com/rails/rails/pull/47698 😄 .
Usually the first PR has precedence.
Some editors hide `tmp` directories so I wanted to keep the `tmp` command name while using `temp` for the directory.

**Comment by JuanVqz** [comment]
> @JuanVqz Ha, I just submitted #47698 smile . Usually the first PR has precedence (in this case yours). Some editors hide `tmp` directories so I wanted to keep the `tmp` command name while using `temp` for the directory. I can add you as a co-author to my PR If you don't mind.

I already saw it, yours looks good.
Yup, that's fine to me, feel free to close mine.
 if there is a way I can still help you on moving the tasks will be awesome, I want to get used to the rails code :+1:

**Comment by p8** [comment]
@JuanVqz `statistics.rake` is probably an easy one to pick up.
You probably also want to take into account changes from the following PR, which also adds tests:
https://github.com/rails/rails/pull/47313.

If you remove the rake file you probably also want to remove it here:
https://github.com/rails/rails/blob/main/railties/lib/rails/tasks.rb#L14

**Comment by JuanVqz** [comment]
> @JuanVqz `statistics.rake` is probably an easy one to pick up. You probably also want to take into account changes from the following PR, which also adds tests: #47313.
> 
> If you remove the rake file you probably also want to remove it here: https://github.com/rails/rails/blob/main/railties/lib/rails/tasks.rb#L14

Gonna do it! if got stuck I'll let you know, thank you!

**Comment by JuanVqz** [comment]
Hey @p8, I'm migrating `statistics.rake` [here is the branch](https://github.com/rails/rails/compare/main...JuanVqz:rails:railties/thor-stats-task#diff-c6ad8bdf72ab828a07f4ffdf6c6e859291cbde16a3808fef4ba3b2efd2019119R16) but got several issues (or at least seems like that).

1. Moved the stats task to the commands folder and copied the [test case](https://github.com/rails/rails/pull/47313/files#diff-c6ad8bdf72ab828a07f4ffdf6c6e859291cbde16a3808fef4ba3b2efd2019119R10), I see the ` uninitialized constant` error.

```
➜  railties git:(railties/thor-stats-task) ✗ bin/test test/commands/statistics_test.rb
Run options: --seed 5790

# Running:

E

Error:
Rails::Command::StatisticsTest#test_`bin/rails_stats`_handles_non-existing_directories_added_by_third_parties:
RuntimeError: rails command failed (1): bin/rails stats 2>&1
rails aborted!
NameError: uninitialized constant STATS_DIRECTORIES

    ::STATS_DIRECTORIES << ["Non Existing", "app/non_existing"]
    ^^^^^^^^^^^^^^^^^^^
/home/ombu/code/ombu/rails/tmp/d20230319-952098-ddo7d7/app/lib/tasks/custom.rake:5:in `block (2 levels) in <top (required)>'
/home/ombu/code/ombu/rails/tmp/d20230319-952098-ddo7d7/app/bin/rails:4:in `<top (required)>'
Tasks: TOP => stats => custom:statsetup
(See full trace by running task with --trace)

    /home/ombu/code/ombu/rails/railties/test/isolation/abstract_unit.rb:391:in `rails'
    /home/ombu/code/ombu/rails/railties/test/commands/statistics_test.rb:22:in `block in <class:StatisticsTest>'


bin/test test/commands/statistics_test.rb:10



Finished in 0.313629s, 3.1885 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

2. Added a `debugger` to see what is happening when running the `assert rails "stats"` because seems the error comes from there. tried to use the generated app in the test in the `tmp/d20230319-number/app` running "manually" `rails stats` and got the following  error, fixed it changing the `config/application.rb`

```
rails aborted!
Unknown version "7.1"
/home/ombu/code/ombu/rails/tmp/d20230319-962217-egqm12/app/config/application.rb:12:in `<class:Application>'
/home/ombu/code/ombu/rails/tmp/d20230319-962217-egqm12/app/config/application.rb:11:in `<module:AppTemplate>'
/home/ombu/code/ombu/rails/tmp/d20230319-962217-egqm12/app/config/application.rb:9:in `<top (required)>'
/home/ombu/code/ombu/rails/tmp/d20230319-962217-egqm12/app/Rakefile:4:in `require_relative'
/home/ombu/code/ombu/rails/tmp/d20230319-962217-egqm12/app/Rakefile:4:in `<top (required)>'
<internal:/home/ombu/.asdf/installs/ruby/3.1.3/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:96:in `require'
<internal:/home/ombu/.asdf/installs/ruby/3.1.3/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:96:in `require'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)
```

3 Then tried again `rails stats` but got the following error, also solved it removing `ActionDispatch.deprecator.silence { match ':controller(/:action(/:id))(.:format)', via: :all }
` from `config/routes.rb`

```
➜  app git:(main) ✗ rails stats
rails aborted!
NoMethodError: undefined method `deprecator' for ActionDispatch:Module

ActionDispatch.deprecator.silence { match ':controller(/:action(/:id))(.:format)', via: :all }
              ^^^^^^^^^^^
Did you mean?  deprecate
/home/ombu/code/ombu/rails/tmp/d20230319-962217-egqm12/app/config/routes.rb:10:in `block in <top (required)>'
/home/ombu/code/ombu/rails/tmp/d20230319-962217-egqm12/app/config/routes.rb:1:in `<top (required)>'
/home/ombu/code/ombu/rails/tmp/d20230319-962217-egqm12/app/config/environment.rb:5:in `<top (required)>'
Tasks: TOP => stats => custom:statsetup => environment
(See full trace by running task with --trace)
```

4. got the same error at the beginning 

```
➜  app git:(main) ✗ rails stats
rails aborted!
Errno::ENOENT: No such file or directory @ dir_initialize - app/non_existing

Tasks: TOP => stats
(See full trace by running task with --trace)
```

**Comment by p8** [comment]
You are getting the `NameError: uninitialized constant STATS_DIRECTORIES` because that constant isn't loaded in the test.
You need to add the following to the test file:
```ruby
require "rails/command/statistics/statistics_command"
```

**Comment by p8** [comment]
Hmm, this one isn't as easy as I initially thought.
We might have some backwards compatibility issues with some people expecting this to be a rake task to extend.

**Comment by p8** [comment]
@JuanVqz I think it's probably easier if you create a PR.
That would allow others to comment as well.

**Comment by JuanVqz** [comment]
> @JuanVqz I think it's probably easier if you create a PR. That would allow others to comment as well.

Okay, doing it, I didn't create it because somewhere read we should create a PR until it is finished

**Pull request closed without merging**
