### PR TITLE
Load activestorage services after the config has been initialised

### PR DESCRIPTION
**Pull request by ghousemohamed**
### Summary

This PR makes sure the services and service for `ActiveStorage::Blob` are set after the rails application has finished initializing. I've made these changes since I noticed the module attributes for ActiveStorage as well are set after the rails application has finished initializing. And I found it confusing as to why class attributes of `ActiveStorage::Blob` are not following the same pattern here.

(Apologies, if this PR does not help to add anything. I had noticed this, thought it needed a PR 😅)

Thanks!

### CODE REVIEW

**Comment by ghousemohamed** [comment]
> The following test case is failing:
> 
> https://github.com/rails/rails/blob/b961af3345fe2f9e492ba1e5424c2ceb75ac6ead/activesupport/test/cache/behaviors/cache_store_behavior.rb#L408-L412
> 
> However, this PR does not touch anything related to this piece of code. Is this an issue with this test case being flaky?

I've addressed this issue in this PR https://github.com/rails/rails/pull/44386

Hope that's okay 😅

**Comment by p8** [comment]
Hey @ghousemohamed 👋 

I do see the pattern of nested callbacks used in the Active Record Railtie as well....
https://github.com/rails/rails/blob/a5b2b6155ceac1c073979272bb1c424fdf35cbc7/activerecord/lib/active_record/railtie.rb#L114-L115

But it seems this might unset ActiveStorage::Blob.service when ActiveStorage::Blob is loaded:
https://github.com/rails/rails/pull/30118
https://github.com/rails/rails/pull/32100

**Comment by ghiculescu** [comment]
> But, I am not sure about the change. I think this would break dealing with Active Storage services from Rails initializers?

I think so too. (I haven't tested yet, but based on reading the PR...) With this change, I don't think you'll be able to use `ActiveStorage::Blob.service` from inside `config/initializers`. But, this change lets you see `Rails.application.config.active_storage.service_configurations` inside an initializer. So it depends on what is desirable here. See https://github.com/rails/rails/pull/44996 for general discussion on the topic.

@ghousemohamed maybe it's worth adding a test to show what you are trying to fix here?

**Comment by jorgemanrubia** [comment]
Yeah I think breaking possible usages in initializers is a reason big enough to not do this unless there is a compelling reason 😅.

**Comment by jorgemanrubia** [comment]
Tentatively closing this one as per the discussion above.

**Pull request closed without merging**
