### PR TITLE
Route generator should be idempotent

### PR DESCRIPTION
**Pull request by ch1ago**
This commit demonstrates #22082

### CODE REVIEW

**Comment by thejamespinto** [comment]
the tests from the first commit point out the extra unwanted line from when invoking the command twice in a row.
https://travis-ci.org/rails/rails/jobs/87605507#L3530

screen shot 2015-10-27 at 3 55 32 pm

**Comment by brodock** [comment]
To illustrate the problem, check here: https://github.com/hello-gem/hello/commit/a387dd2f3b07ea1192db8a9e41fb16897a663c8a

This is a very welcome fix and will easy new users workflow.

please, LGTM!

**Comment by sadjow** [comment]
LGTM :green_heart: :yellow_heart: :heart:

**Comment by sadjow** [comment]
:shipit:

**Comment by rafaelfranca** [comment]
This is reverting https://github.com/rails/rails/commit/80838d9bd548d2b15f6692e84cbe30c697e54b4a I guess it is fine now that the comments on that file was removed.

**Comment by thejamespinto** [comment]
@rafaelfranca nice catch, and I do agree with @pixeltrix 's POV.
As you said maybe now routes.rb comes blank it will be possible.

**Comment by victorlcampos** [comment]
+1

**Comment by seuros** [comment]
+1 , could you squash your commits ?
Thank you for your contribution.

**Comment by thejamespinto** [comment]
@seuros squashed

**Comment by pixeltrix** [comment]
@thejamespinto sorry was on holiday for the first half of this week - can you rebase against master and I will merge. I'm not happy with either option but since Thor's `inject_into_file` doesn't allow us anymore subtlety and there's no longer the comments in the file then it's fine to flip the other way.

**Comment by thejamespinto** [comment]
@pixeltrix after reading your reasoning I can say I agree with you

**Comment by thejamespinto** [comment]
@rafaelfranca @seuros thank you guys for helping us here. :100:

**Comment by pixeltrix** [comment]
@thejamespinto thanks!

**Pull request merged**
