### PR TITLE
Update the sqlite db yaml template to match other templates and mention proper supported version

### PR DESCRIPTION
**Pull request by vipulnsward**

### CODE REVIEW

**Comment by kamipo** [comment]
Can you update `jdbcsqlite3.yml.tt` too?

https://github.com/rails/rails/blob/b2eb1d1c55a59fee1e6c4cba7030d8ceb524267c/railties/lib/rails/generators/rails/app/templates/config/databases/jdbcsqlite3.yml.tt#L1

**Comment by vipulnsward** [comment]
Done.

**Comment by yahonda** [comment]
Would you consider backport this change into 6-0-stable?
I should have change these files as #32923.

**Comment by yahonda** [comment]
Opened #36268 to `6-0-stable` branch.

**Pull request merged**
