### PR TITLE
Fix typo: change Punt to Print [ci skip]

### PR DESCRIPTION
**Pull request by hahmed**
### Summary

Fix typo: Change the word `Punt` to `Print` in application_command.rb

### CODE REVIEW

**Comment by eugeneius** [comment]
This isn't a typo; "punt" means to give up, change your approach, or try something else.

The best citation I could find is the fourth entry here: https://en.wiktionary.org/wiki/punt#Verb_2

**Comment by hahmed** [comment]
I looked for a definition and found some weird ones 😂 (https://www.lexico.com/definition/punt), thanks for the clarification!

**Comment by eugeneius** [comment]
Hey, this one's pretty good: https://en.wikipedia.org/wiki/Irish_pound 🇮🇪 😁

**Comment by hahmed** [comment]
TIL `Punt Éireannach` 🇮🇪🇮🇪🇮🇪

**Pull request closed without merging**
