### PR TITLE
Test unit (テスティングライブラリー毎に Adapter を用意して ActiveSupport::TestCase から呼ぶ形にしたい)

### PR DESCRIPTION
**Pull request by otegami**
### Motivation / Background

This Pull Request has been created because [REPLACE ME]

### Detail

This Pull Request changes [REPLACE ME]

### Checklist

Before submitting the PR make sure the following are checked:

* [ ] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [ ] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [ ] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by yahonda** [comment]
Please use English here so that everyone can understand what the subject means.

**Comment by otegami** [comment]
@yahonda 
I sincerely apologize. I mistakenly targeted the wrong destination when creating the Pull Request.

**Comment by yahonda** [comment]
Thanks for the update. You don't need to apologize.

**Comment by zzak** [comment]
This is actually a really interesting idea 🤔

**Pull request closed without merging**
