### PR TITLE
Arel::Nodes::UpdateStatement supports FROM

### PR DESCRIPTION
**Pull request by quentindemetz**
### Motivation / Background

In PostgreSQL, [UPDATE supports the **FROM** keyword](https://www.postgresql.org/docs/current/sql-update.html) but this isn't currently supported in Arel. Similar functionality is supported in MySQL but with different syntax ([ref](https://www.mysqltutorial.org/mysql-update-join/)). This PR adds supports for FROM:

in SQL
```SQL
UPDATE users
SET name = customers.name
FROM customers
WHERE users.id = customer.id
```

with Arel
```ruby
users = Arel::Table.new('users')
customers = Arel::Table.new('customers')

Arel::Nodes::UpdateStatement.new(users).tap do |us|
  us.values = [
    Arel::Nodes::Assignment.new(
      Arel::Nodes::UnqualifiedColumn.new(users[:name]),
      customers[:name],
   ),
  ]
  us.wheres = [users[:id].eq(customers[:id])]
  us.from = [customers]
end.to_sql
=> "UPDATE \"users\" SET \"name\" = \"customers\".\"name\" FROM \"customers\" WHERE \"users\".\"id\" = \"customers\".\"id\""
```

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by benedikt** [comment]
@quentindemetz Welcome to the club 👋😆 #46487 #47157

I guess this is a strong indicator that we need this? 😄

**Comment by quentindemetz** [comment]
Looks like I'm late to the party this morning (see https://github.com/rails/rails/pull/47187) - happy to see other people need this as well ❤️ .

I would also like UPDATE to support WITH so I can pass a ValuesList as CTE for all the fields I want to change. Should one of the above PRs add this or should I add it on my own once "FROM" is supported?

```SQL
WITH updates (id, name) AS (VALUES (1, "John"), (2, "Jack"))
UPDATE users
SET users.name = updates.name
WHERE users.id = updates.id
```

**Comment by benedikt** [comment]
@quentindemetz Yeah, agreed! I'm currently working on a PR to add `WITH` support to Insert/Update/Delete statements and managers.

**Comment by benedikt** [comment]
@quentindemetz There's now #47193 with attempts to add CTE support to `INSERT`/`UPDATE`/`DELETE` statements.

**Pull request closed without merging**
