### PR TITLE
Remove `ForeignKeys` module which was introduced at #32299

### PR DESCRIPTION
**Pull request by kamipo**
To solve the problem #32299, just enough to introduce
`fk_ignore_pattern` option.

I don't think there is a need to expose these constants.

What do you think? cc @davidstosik @guilleiguaran

### CODE REVIEW

**Review by kaspth — APPROVED** [review]

**Review by rafaelfranca — APPROVED** [review]

**Review by guilleiguaran — APPROVED** [review]

**Comment by davidstosik** [comment]
@kamipo Exposing `ActiveRecord::ForeignKeys::PREFIX` allowed applications that change `fk_ignore_pattern` not to hardcode the `fk_rails` prefix.

Before your change, I could write this in my application: 

```rb
ActiveRecord::SchemaDumper.fk_ignore_pattern = /^_*#{ActiveRecord::ForeignKeys::PREFIX}_[0-9a-f]{10}$/
```

Now, I need to write the following instead, and depend on the prefix not changing:

```rb
ActiveRecord::SchemaDumper.fk_ignore_pattern = /^_*fk_rails_[0-9a-f]{10}$/
```

**Comment by kamipo** [comment]
At least I feel that the pattern depends not only on the prefix but also on the length of `hashed_identifier` being 10. Exposing only `PREFIX` does not make sense to me.

https://github.com/rails/rails/blob/bdd42eeaf9e1858b10294764aeb99de18cfeef40/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb#L1322-L1329

**Comment by kaspth** [comment]
Another thing: Don't think we're wont to use constants to note public API, at least not commonly. `ActiveRecord::ForeignKeys::PREFIX` sounds obscure too.

**Comment by davidstosik** [comment]
@kamipo @kaspth Thanks for the extra justifications! It all makes sense.
Would you consider adding it back if it is more complete with better naming, or is it a no-no?

**Comment by kaspth** [comment]
Depends on what the code looks like. But I can't judge from this, so do submit a PR :)

**Pull request merged**
