### PR TITLE
Raise `NotImplementedError` by default instead of returning `nil`

### PR DESCRIPTION
**Pull request by kamipo**

### CODE REVIEW

**Comment by schneems** [comment]
Added by @jeremy in https://github.com/rails/rails/commit/15c077492029dcba477aad2e29339803377cc1f8 r? @jeremy

**Comment by kamipo** [comment]
FYI: `exec_query` has not been `undef_method`.

https://github.com/rails/rails/blob/v5.0.0.beta1/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb#L80-L81

**Comment by pixeltrix** [comment]
There's also `truncate` which raises `NotImplementedError`

**Comment by kamipo** [comment]
`select_rows` and `execute` methods should be implemented by every adapters because these methods are used in the internal. But `truncate` method is not necessarily to be implemented. For example, SQLite3 is not support `TRUNCATE` command.

**Comment by pixeltrix** [comment]
> For example, SQLite3 is not support TRUNCATE command

True, but it could be implemented as DROP TABLE and then CREATE TABLE, or even just a DELETE FROM - the idea is that you end up with the same results done in whatever manner is most efficient for that database.

**Comment by jeremy** [comment]
The upside of undef is that we can provide superclass RDoc without making subclasses respond to methods they haven't implemented yet.

We can revert, but we'd need to go back to raising an exception by default instead of returning nil.

**Comment by kamipo** [comment]
I added a commit for raising `NotImplementedError`.

**Comment by jeremy** [comment]
Merged @ https://github.com/rails/rails/commit/67f4994a0bdf3f0ea4e42dddc47f9c1e452d424d

**Pull request closed without merging**
