### PR TITLE
Faktory adapter

### PR DESCRIPTION
**Pull request by jagthedrummer**
### Summary

Adds an `ActiveJob` adapter for [Faktory](http://contribsys.com/faktory/).

### Other Information

[Faktory](http://contribsys.com/faktory/) is a language agnostic background job system. `faktory_worker_ruby` (<https://github.com/contribsys/faktory_worker_ruby>) provides a nice API for Ruby that is very similar to [Sidekiq](https://sidekiq.org/).

### CODE REVIEW

**Comment by jagthedrummer** [comment]
I see that the `aj:integration` tests are failing on Travis. I assume that's because the faktory server isn't running on the Travis instance running the test. I'm not sure how to fix that, but I'd be happy to take a shot if someone can point me in the right direction.

**Comment by jagthedrummer** [comment]
Oh, looks like `.travis.yml` is where I need to look. Trying to figure something out now.

**Comment by jagthedrummer** [comment]
Ok, got it figured out.

**Comment by y-yagi** [comment]
I think Faktory is a nice background job system.  

However, we have rejected it when there was a similar proposal about `SQS` before.  
https://github.com/rails/rails/pull/21406#issuecomment-138813484 
https://github.com/rails/rails/issues/23311#issuecomment-176275718 

Therefore, instead of putting it in Rails, I think that it is better to add support in those adapters(or gem).

**Comment by eileencodes** [comment]
Hey @jagthedrummer thanks for taking the time to open the PR. @y-yagi is right, we don't generally accept new adapters into AJ because it becomes a bigger overhead for us. It's better to add support in the adapter itself rather than into Rails. 

Thanks for understanding!

**Comment by jagthedrummer** [comment]
Oh, bummer.

**Pull request closed without merging**
