### PR TITLE
Add `readline-ext` that has been removed from Ruby 3.3.0dev

### PR DESCRIPTION
**Pull request by yahonda**
### Motivation / Background

This Pull Request addresses these Rails CI failures:
https://buildkite.com/rails/rails/builds/96301#01880117-acb1-4d77-935a-4a1de13c8609/1093-1101

### Detail

These Rails CI failures are due to Ruby 3.3.0dev removing ``readline-ext`.
Refer to https://bugs.ruby-lang.org/issues/19616
https://github.com/ruby/ruby/pull/7781

### Additional information
Here are the failures addressed by this pull request:

```ruby
$ ruby -v
ruby 3.3.0dev (2023-05-09T19:40:26Z master e1c84e8ee6) [x86_64-linux]
$ cd railties
$ bin/test test/application/console_test.rb
... snip ...

.F

Failure:
FullStackConsoleTest#test_environment_option_and_irb_option [/home/yahonda/src/github.com/rails/rails/railties/test/application/console_test.rb:133]:
"> " expected, but got:

Loading test environment (Rails 7.1.0.alpha)
Switch to inspect mode.
▽.
Expected # encoding: ASCII-8BIT
"Loading test environment (Rails 7.1.0.alpha)\r\nSwitch to inspect mode.\r\n\e[1G\xE2\x96\xBD\e[6n" to include "> ".

bin/test test/application/console_test.rb:167

^[[30;2RF

Failure:
FullStackConsoleTest#test_sandbox [/home/yahonda/src/github.com/rails/rails/railties/test/application/console_test.rb:133]:
"> " expected, but got:

Loading development environment in sandbox (Rails 7.1.0.alpha)
Any modifications you make will be rolled back on exit
▽.
Expected # encoding: ASCII-8BIT
"Loading development environment in sandbox (Rails 7.1.0.alpha)\r\nAny modifications you make will be rolled back on exit\r\n\e[1G\xE2\x96\xBD\e[6n" to include "> ".

bin/test test/application/console_test.rb:139

^[[30;2R......

Finished in 66.153595s, 0.1360 runs/s, 0.2872 assertions/s.
9 runs, 19 assertions, 2 failures, 0 errors, 0 skips
$
```

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [ ] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by yahonda** [comment]
It is green now https://buildkite.com/rails/rails/builds/96320#018802e4-8004-4eec-afc1-867e6ec3631b/1088

**Comment by casperisfine** [comment]
❤️

**Comment by yahonda** [comment]
Backported to the `7-0-stable` branch via https://github.com/rails/rails/commit/da309a582e04183a85340ec0e1ed59b2d69ca9c2

**Comment by st0012** [comment]
Hi there, I opened #48369 to make tests working with Reline instead. Let me know what you think 🙂

**Pull request merged**
