### PR TITLE
Show feedback for `bin/rails boot` command

### PR DESCRIPTION
**Pull request by p8**
### Motivation / Background
There currently is no feedback when `bin/rails boot` is successful.

### Detail
Print "Booting the application." before booting.
Print "All is good!" when boot was successful, similar to `bin/rails zeitwerk:check`.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
@fxn

**Comment by fxn** [comment]
Let me think about it!

The purpose of this command is not to verify the application boots, it is to boot the application and do anything else, so that you can benchmark, debug stuff, profile, etc.

**Comment by fxn** [comment]
For example, if you print traces, they would be mixed with these ones.

**Comment by fxn** [comment]
Yeah, I prefer to keep it silent, like the docs say: "boot and exit".

Being silent was a deliberate choice when I wrote the patch. It is like when you compile a file with `gcc`, for example. It doesn't print "Compiling... compiled!", it just silently compiles and leaves a file as a side-effect. You see stuff if things go wrong.

Thanks for the proposal anyway @p8!

**Pull request closed without merging**
