### PR TITLE
Update `Rails.configuration` documentation

### PR DESCRIPTION
**Pull request by maclover7**
### Summary

As reported via #26280, the differences between `config` and `config.x` are somewhat confusing, as further complicated by #21995. This PR aims to better explain the differences between these two options.

### CODE REVIEW

**Comment by guilleiguaran** [comment]
Thanks for fixing this <3

**Comment by juno** [comment]
Hi, @maclover7 

I think it's good to backport this PR to `5_0-stable` branch, what do you think?

That is because [current Rails Guide](http://guides.rubyonrails.org/configuring.html#custom-configuration)(not edgeguide) describes `config.payment_processing.schedule = :daily` style examples which raises `NoMethodError` on Rails 5.0.1.
This makes user confusing.

**Comment by rafaelfranca** [comment]
BAckported in d17f97ad3d

**Comment by juno** [comment]
@rafaelfranca Thank you 👍

**Pull request merged**
