### PR TITLE
ol - fix recognize_path for not being able to parse engine routes in …

### PR DESCRIPTION
**Pull request by orlandoAppfolio**
…main app

### CODE REVIEW

**Comment by orlandoAppfolio** [comment]
In the main_app, Rails.application.routes.recognize_path('path/in/engine') 
e.g. we have a Dummy engine and OccupancyYearsController
```
Rails.application.routes.recognize_path('dummy/occupancy_years')
```
will throw an exception 
```
ActionController::RoutingError: A route matches "/dummy/occupancy_years", but references missing controller: DummyController
from /Users/user_name/.rvm/gems/ruby-2.2.3/gems/actionpack-4.0.12/lib/action_dispatch/routing/route_set.rb:711:in `block in recognize_path'
```

though
```
Dummy::Engine.routes.recognize_path('occupancy_years')
```
 works just fine giving
 ``` {:action=>"index", :controller=>"dummy/occupancy_years"}```

recognize_path calls #recognize  https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/journey/router.rb#L57

where as normal request calls #serve https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/journey/router.rb#L28

Trying to make normal request and recognize_path#recognize consistent

**Comment by rafaelfranca** [comment]
`recognize_path` is private API and should not be used in applications.

**Comment by tolgap** [comment]
@rafaelfranca @tenderlove what is the workaround for this? I want to parse the `request.referer` into a route. I need to whitelist/blacklist certain URLs from being redirected to when signing in users.

If I were to store the redirect url on each request, this would not work when users go back in their browsers (as browsers dont send anything to the server when using the back button). So my only reliable option is to use `request.referer`.

**Pull request closed without merging**
