### PR TITLE
Reset Counter Cache Multiple

### PR DESCRIPTION
**Pull request by turlockmike**
Just a quick change to be able to update the counter cache on multiple records in one call.

### CODE REVIEW

**Comment by sgrif** [comment]
If we're going to reset the counters on multiple IDs, we should batch them up into a single SQL query per counter, rather than N queries.

**Comment by matthewd** [comment]
And please don't reformat other code; it's distracting, and interferes with blame

**Comment by turlockmike** [comment]
Ok, @sgrif . I'll try to combine it and I'll post some benchmarks and open again. Is that fine?

Sorry about the formatting. I won't do that again.

**Comment by turlockmike** [comment]
@sgrif Is there even a consistent way of updating multiple ids with different values without making some assumptions about sql? Seems like this has to be an N query unless we can assume that the count is coming directly the database (Not sure it's a safe assumption).

**Comment by sgrif** [comment]
I think assuming the count is coming from the database is a safe assumption
for master, supporting overriding the counter method isn't a use case we
need to support.

**Pull request closed without merging**
