### PR TITLE
Actionpack tests to cover #23624

### PR DESCRIPTION
**Pull request by rthbound**
- Rack 951:  https://github.com/rack/rack/issues/951
- Rack 1015: https://github.com/rack/rack/issues/1015

### CODE REVIEW

**Comment by rthbound** [comment]
The test is expected to fail until rack introduces a fix... https://github.com/rack/rack/issues/951#issuecomment-183475631

**Comment by maclover7** [comment]
Can you please find a location within the test directory for the `payload.json`?

**Comment by rthbound** [comment]
Intended to fail. Also, payload.json can be removed.

**Comment by maclover7** [comment]
If the intention of these tests is to fail, there is no reason to add them to the Action Pack -- this would cause the main build and all PR builds to fail for no reason. Feel free to open an issue to monitor this bug, but this doesn't warrant a PR.

**Comment by rthbound** [comment]
@maclover7 I think I may have answered your question wrong. The tests are intended to pass. They should pass, but they don't today because there's a bug. I think these tests belong here.

**Comment by maclover7** [comment]
Ok -- but what I said still stands. If there's a regression, and Action Pack can't do anything about it, there's no need to add tests that should **fail on purpose** to the suite.

**Comment by rthbound** [comment]
@maclover7 I don't understand, I would think these tests would only make rails more reliable. There's a plethora of tests asserting that parameters are handled properly in test cases, and none of them fail? If there is a defect (like information in a request body being lost), shouldn't the build fail?

How come the defect this test would protect against exists for ActionController::TestCase, but not when using ActionController::Metal?

**Pull request closed without merging**
