### PR TITLE
Add Solid Cache (and get ready for Solid Queue)

### PR DESCRIPTION
**Pull request by dhh**
Solid Cache will be the new default caching backend for production deployments out of the box in Rails 8. We're also going to add Solid Queue by default, and both solid options will be bundled behind the same `--skip-solid` flag.

### CODE REVIEW

**Comment by dhh** [comment]
@rafaelfranca Do you know why this test would be failing? It doesn't fail on main, just here. But I don't see what change brought it on:

image

**Comment by yahonda** [comment]
It looks like `uninitialized constant SolidCache::Store::Failsafe::ActiveRecord (NameError)`.

```ruby
$ bin/test test/generators/app_generator_test.rb:363
/home/yahonda/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/json-2.7.1/lib/json/common.rb:3: warning: ostruct was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add ostruct to your Gemfile or gemspec to silence this warning.
Run options: --seed 59852

# Running:

/home/yahonda/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/json-2.7.1/lib/json/common.rb:3: warning: ostruct was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add ostruct to your Gemfile or gemspec to silence this warning.
DEPRECATION WARNING: ActiveSupport::ProxyObject is deprecated and will be removed in Rails 8.0.
Use Ruby's built-in BasicObject instead.
 (called from initialize at /home/yahonda/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/jbuilder-2.11.5/lib/jbuilder/jbuilder.rb:1)
DEPRECATION WARNING: ActiveSupport::ProxyObject is deprecated and will be removed in Rails 8.0.
Use Ruby's built-in BasicObject instead.
 (called from <top (required)> at /home/yahonda/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/jbuilder-2.11.5/lib/jbuilder/jbuilder_template.rb:6)
/home/yahonda/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/solid_cache-1.0.3/lib/solid_cache/store/failsafe.rb:7:in `<module:Failsafe>': uninitialized constant SolidCache::Store::Failsafe::ActiveRecord (NameError)

        ActiveRecord::AdapterTimeout,
        ^^^^^^^^^^^^
	from /home/yahonda/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/solid_cache-1.0.3/lib/solid_cache/store/failsafe.rb:5:in `<class:Store>'
	from /home/yahonda/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/solid_cache-1.0.3/lib/solid_cache/store/failsafe.rb:4:in `<module:SolidCache>'
	from /home/yahonda/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/solid_cache-1.0.3/lib/solid_cache/store/failsafe.rb:3:in `<top (required)>'
	from /home/yahonda/.rbenv/versions/3.3.5/lib/ruby/3.3.0/bundled_gems.rb:75:in `require'
	from /home/yahonda/.rbenv/versions/3.3.5/lib/ruby/3.3.0/bundled_gems.rb:75:in `block (2 levels) in replace_require'
	from /home/yahonda/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:30:in `require'
	from /home/yahonda/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/solid_cache-1.0.3/lib/solid_cache/store.rb:5:in `<class:Store>'
	from /home/yahonda/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/solid_cache-1.0.3/lib/solid_cache/store.rb:4:in `<module:SolidCache>'
	from /home/yahonda/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/solid_cache-1.0.3/lib/solid_cache/store.rb:3:in `<top (required)>'
	from /home/yahonda/.rbenv/versions/3.3.5/lib/ruby/3.3.0/bundled_gems.rb:75:in `require'
	from /home/yahonda/.rbenv/versions/3.3.5/lib/ruby/3.3.0/bundled_gems.rb:75:in `block (2 levels) in replace_require'
	from /home/yahonda/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:30:in `require'
	from /home/yahonda/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/helpers.rb:135:in `const_get'
	from /home/yahonda/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/helpers.rb:135:in `cget'
	from /home/yahonda/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/eager_load.rb:182:in `block in actual_eager_load_dir'
	from /home/yahonda/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/helpers.rb:40:in `block in ls'
	from /home/yahonda/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/helpers.rb:25:in `each'
	from /home/yahonda/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/helpers.rb:25:in `ls'
	from /home/yahonda/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/eager_load.rb:170:in `actual_eager_load_dir'
	from /home/yahonda/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/eager_load.rb:17:in `block (2 levels) in eager_load'
	from /home/yahonda/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/eager_load.rb:16:in `each'
	from /home/yahonda/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/eager_load.rb:16:in `block in eager_load'
	from /home/yahonda/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/eager_load.rb:10:in `synchronize'
	from /home/yahonda/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.12/lib/zeitwerk/loader/eager_load.rb:10:in `eager_load'
	from /home/yahonda/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/solid_cache-1.0.3/lib/solid_cache.rb:16:in `<top (required)>'
	from <internal:/home/yahonda/.rbenv/versions/3.3.5/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/home/yahonda/.rbenv/versions/3.3.5/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /home/yahonda/.rbenv/versions/3.3.5/lib/ruby/3.3.0/bundled_gems.rb:75:in `block (2 levels) in replace_require'
	from /home/yahonda/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
	from /home/yahonda/.rbenv/versions/3.3.5/lib/ruby/3.3.0/bundler/runtime.rb:60:in `block (2 levels) in require'
	from /home/yahonda/.rbenv/versions/3.3.5/lib/ruby/3.3.0/bundler/runtime.rb:55:in `each'
	from /home/yahonda/.rbenv/versions/3.3.5/lib/ruby/3.3.0/bundler/runtime.rb:55:in `block in require'
	from /home/yahonda/.rbenv/versions/3.3.5/lib/ruby/3.3.0/bundler/runtime.rb:44:in `each'
	from /home/yahonda/.rbenv/versions/3.3.5/lib/ruby/3.3.0/bundler/runtime.rb:44:in `require'
	from /home/yahonda/.rbenv/versions/3.3.5/lib/ruby/3.3.0/bundler.rb:212:in `require'
	from /home/yahonda/src/github.com/rails/rails/railties/test/fixtures/tmp/config/application.rb:19:in `<top (required)>'
	from /home/yahonda/.rbenv/versions/3.3.5/lib/ruby/3.3.0/bundled_gems.rb:75:in `require'
	from /home/yahonda/.rbenv/versions/3.3.5/lib/ruby/3.3.0/bundled_gems.rb:75:in `block (2 levels) in replace_require'
	from /home/yahonda/src/github.com/rails/rails/railties/lib/rails/command/actions.rb:15:in `require_application!'
	from /home/yahonda/src/github.com/rails/rails/railties/lib/rails/commands/app/update_command.rb:24:in `configs'
	from /home/yahonda/src/github.com/rails/rails/railties/lib/rails/commands/app/update_command.rb:15:in `perform'
	from /home/yahonda/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/thor-1.3.0/lib/thor/command.rb:28:in `run'
	from /home/yahonda/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/thor-1.3.0/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/yahonda/src/github.com/rails/rails/railties/lib/rails/command/base.rb:178:in `invoke_command'
	from /home/yahonda/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/thor-1.3.0/lib/thor.rb:527:in `dispatch'
	from /home/yahonda/src/github.com/rails/rails/railties/lib/rails/command/base.rb:73:in `perform'
	from /home/yahonda/src/github.com/rails/rails/railties/lib/rails/command.rb:71:in `block in invoke'
	from /home/yahonda/src/github.com/rails/rails/railties/lib/rails/command.rb:149:in `with_argv'
	from /home/yahonda/src/github.com/rails/rails/railties/lib/rails/command.rb:69:in `invoke'
	from /home/yahonda/src/github.com/rails/rails/railties/lib/rails/commands.rb:18:in `<top (required)>'
	from /home/yahonda/.rbenv/versions/3.3.5/lib/ruby/3.3.0/bundled_gems.rb:75:in `require'
	from /home/yahonda/.rbenv/versions/3.3.5/lib/ruby/3.3.0/bundled_gems.rb:75:in `block (2 levels) in replace_require'
	from bin/rails:4:in `<main>'
E

Error:
AppGeneratorTest#test_app_update_does_not_generate_active_storage_contents_when_skip_active_record_is_given:
RuntimeError: Command failed with exit 1: bin/rails
    test/generators/generators_test_helper.rb:147:in `system'
    test/generators/generators_test_helper.rb:147:in `block in run_app_update'
    test/generators/generators_test_helper.rb:142:in `chdir'
    test/generators/generators_test_helper.rb:142:in `run_app_update'
    test/generators/app_generator_test.rb:365:in `test_app_update_does_not_generate_active_storage_contents_when_skip_active_record_is_given'


bin/test test/generators/app_generator_test.rb:363



Finished in 1.349000s, 0.7413 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
$
```

- How to show the internal error by removing quietly method

```ruby
$ git diff
diff --git a/railties/test/generators/generators_test_helper.rb b/railties/test/generators/generators_test_helper.rb
index e7c1dad456..639596e2fc 100644
--- a/railties/test/generators/generators_test_helper.rb
+++ b/railties/test/generators/generators_test_helper.rb
@@ -144,7 +144,7 @@ def run_app_update(app_root = destination_root, flags: "--force")
       gemfile_contents.sub!(/^(gem "rails").*/, "\\1, path: #{File.expand_path("../../..", __dir__).inspect}")
       File.write("Gemfile", gemfile_contents)

-      quietly { system({ "BUNDLE_GEMFILE" => "Gemfile" }, "bin/rails app:update #{flags}", exception: true) }
+      system({ "BUNDLE_GEMFILE" => "Gemfile" }, "bin/rails app:update #{flags}", exception: true)
     end
   end
```

**Comment by dhh** [comment]
Cc @djmb

**Comment by djmb** [comment]
https://github.com/rails/solid_cache/pull/207 will fix that.

**Comment by skipkayhil** [comment]
`test_app_update_does_not_generate_active_storage_contents_when_skip_active_record_is_given`

I think its failing because the test is for when an app has skipped Active Record. Should `--skip-active-record` imply `--skip-solid`?

**Comment by dhh** [comment]
Ah yes, of course --skip-active-record should def imply skip-solid. Will fix.

**Pull request merged**
