### PR TITLE
Convert (usec / 1.0e+6) to integer inorder to get a integerin return …

### PR DESCRIPTION
**Pull request by tanmay3011**
…instead of decimal from #seconds_since_midnight

### CODE REVIEW

**Comment by sgrif** [comment]
This feels less correct to me than what we had before. There were a fractional number of seconds that have passed

**Comment by sgrif** [comment]
Ah I misunderstood. We were returning a floating point finding error. Please make this more clear in your commit message. This kind of context is important.

**Comment by tanmay3011** [comment]
Comment floating point is just retuned because we are performing this (usec / 1.0e+6) operation which returns a floating point

**Comment by sgrif** [comment]
Returning a floating point because we track fractional seconds vs us dropping fractional seconds, but still having a rounding error are not the same thing.

**Comment by matthewd** [comment]
> There were a fractional number of seconds that have passed

Indeed. I don't see why the current value is incorrect.

**Comment by sgrif** [comment]
> Indeed. I don't see why the current value is incorrect.

Unless I'm reading wrong, we're truncating subsecond precision already, and the `.0001` from the test is just a rounding error.

**Comment by matthewd** [comment]
The line in question is passing an extra 10 usec -- that's what makes it different from https://github.com/rails/rails/pull/21864/files#diff-b234fae95a43f5c35e0041d50ff97474R16.

**Comment by sgrif** [comment]
I'm reading wrong then. Yeah the current behavior is correct.

**Pull request closed without merging**
