### PR TITLE
Add fetch and process multi to active support cache

### PR DESCRIPTION
**Pull request by astrauka**
Add fetch and process multi to active support cache.
Idea taken from http://www.justinweiss.com/articles/a-faster-way-to-cache-complicated-data-models/ .
Acts like https://github.com/rails/rails/blob/master/activesupport/lib/active_support/cache.rb#L368 but allows passing proc to calculate keys from ids and evaluates all ids in the block instead of a single id.

### CODE REVIEW

**Comment by astrauka** [comment]
@rafaelfranca I have written rspec tests in my project for this code, in rails I see minitest used, but could not find the place where to put the specs. Could you help me out on this?

**Comment by astrauka** [comment]
@dhh @maclover7 what do you think about this PR, is the functionality needed for active support cache?

**Comment by rafaelfranca** [comment]
I don't know. This is a complicated case that I don't see being used in a lot of applications. I prefer to not include it but since I don't use cache frequently I'll ask for more opinions.

@matthewd @jeremy

**Comment by dhh** [comment]
I sorta get the premise here, but I think it's too edge of a use case for AS::Cache. I think it'd make a great gem to wrap this pattern up, though.

Another approach to this issue of slow API requests is to cache the rendering, not the fetching. Then you can rely on lazy loading, don't need to use :include, and let the Russian-doll style carry you. That's what we do for Basecamp.

**Comment by astrauka** [comment]
Thanks for comments :)

**Pull request closed without merging**
