### PR TITLE
Add fetch_all method to Hash

### PR DESCRIPTION
**Pull request by pawurb**
How about adding this little method to Hash ? I find it useful when passing a hash of required options as an argument.

### CODE REVIEW

**Comment by edwardloveall** [comment]
This is almost exactly like `slice` except slice doesn't raise an exception. My first reaction would be to change `slice` instead.

**Comment by pawurb** [comment]
Making `slice` raise an exception would bring up a lot of backwards compatibility problems. `fetch_all` name is supposed to correspond to `fetch` ruby method that raises the same error if the given key is missing.

**Comment by simi** [comment]
1. You'll need to add tests if you want to get this merged.
2. I think this is not useful for majority of rails projects.

**Comment by sgrif** [comment]
Thank you for the patch, and for trying to improve the framework. We generally do not accept new features to Active Support, unless they show an overwhelmingly common use case, or an extreme improvement of the Rails codebase. I'd recommend submitting this as a feature to the Ruby language itself if you think it makes sense there. However, I do not think this is a feature we would like in Rails at this time.

**Pull request closed without merging**
