### PR TITLE
Fix the comment about attr_reader of headers [ci skip]

### PR DESCRIPTION
**Pull request by meinac**

### CODE REVIEW

**Comment by arthurnn** [comment]
Why we even need to comment.. `attr_reader :header` seems pretty obvious to me.

**Comment by meinac** [comment]
You are right we can remove it if you want.

**Comment by arthurnn** [comment]
:fire:

**Comment by arthurnn** [comment]
Actually, wait for it.
This is a doc and not just a comment. see https://github.com/rails/rails/commit/8603bc06ad54ef07e5d4bd073665d495d3561f98 .

**Comment by arthurnn** [comment]
make sense to only update it..
thanks

**Pull request merged**
