### PR TITLE
CI against Ruby 2.3.4

### PR DESCRIPTION
**Pull request by tricknotes**
### Summary

https://www.ruby-lang.org/en/news/2017/03/30/ruby-2-3-4-released/

### CODE REVIEW

**Comment by tricknotes** [comment]
Ouch!
Travis CI doesn't support Ruby 2.3.4 yet. https://travis-ci.org/rails/rails/jobs/216719008
I'll update this PR when Ruby 2.3.4 is available on Travis CI :<

**Comment by pixeltrix** [comment]
@tricknotes I think there's just no binary rvm build yet of 2.3.4 - as soon as there is one it will work, Travis CI doesn't need to do anything.

**Comment by tricknotes** [comment]
Thanks @pixeltrix !
That's right.

Now the binary of Ruby 2.3.4 exists, and all tests are passed on Travis CI.
- https://travis-ci.org/rails/rails/builds/216988211

So I removed "WIP" from this PR.
Can you review?

**Comment by pixeltrix** [comment]
@tricknotes thanks! 👍

**Pull request merged**
