### PR TITLE
add mysql and sqlite3 default test

### PR DESCRIPTION
**Pull request by kenjiszk**
### Summary

Extend database default value test for mysql and sqlite3.
### Other Information

MySQL text type cannot be assigned a default value. So it is skipped.
http://dev.mysql.com/doc/refman/5.6/en/data-type-defaults.html

### CODE REVIEW

**Comment by rafaelfranca** [comment]
MySQL tests are broken.

**Comment by kenjiszk** [comment]
It depends on test execution order. I think some test drop defaults table, so I will re-create defaults table in base_test.rb.

**Comment by kenjiszk** [comment]
@rafaelfranca 
I changed the order of base_test, then test recovered. Is there test execution order in active record test? or Am I doing some wrong cording?

**Comment by arthurnn** [comment]
can you also test if this works with: `bin/test -a mysql2`

**Comment by kenjiszk** [comment]
@arthurnn @rafaelfranca
Thank you for comment. I have revealed the cause issue. The test of "schema_dumper_test.rb" created and dropped a "defaults" table and it affect on test of "base_test.rb". So, it was succeeded when changing test order. I change table name of schema dump test from "defaults" to "dump_defaults". Could you please check this?

**Comment by arthurnn** [comment]
do you mind rebasing this, and I will give it a final look and 🍏  it

**Pull request closed without merging**
