### PR TITLE
change ActiveRecord::Base#defined_enums to a HashWithIndifferentAccess

### PR DESCRIPTION
**Pull request by george-carlin**

### CODE REVIEW

**Comment by claudiob** [comment]
Hello @georgemillo :grinning: 

Can you help me understand what is a use case for this change?

**Comment by sgrif** [comment]
We've moved away from using HWIDA in general for things like this. String keys are the expected usage, just about everywhere in AR that uses hashes. We'd need a pretty strong use case to accept this change.

**Comment by georgemillo** [comment]
Ah, okay. I was digging around inside this (rather complex) module looking for ways I can improve it and this looked like a low-hanging fruit, but it looks like I was wrong.

Out of curiosity though, what's the reason for favouring strings over symbol keys if you're not using HWIDA? My understanding was that symbols are faster and use less memory?

**Comment by sgrif** [comment]
Prior to 2.2, it was because of DDOS vulnerabilities with symbols. Now it's for backwards compat.

**Pull request closed without merging**
