### PR TITLE
Set error code to 1 if generator could not be found

### PR DESCRIPTION
**Pull request by coezbek**
Currently `rails g` will return exit code 0 even if the generator could not be found.

### Motivation / Background

Running `rails g` in shell scripts should fail in case a generator name was mistyped.

### Detail

This Pull Request changes the error case in when generators are invoked. 

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [-] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by MatheusRich** [comment]
@coezbek can you add a changelog entry?

**Comment by coezbek** [comment]
I added an entry to CHANGELOG.md in Railties. I also realized there were some tests which were failing due the additional call to exit. So I updated the tests to assert the new exit code.

**Review by MatheusRich — APPROVED** [review]

**Comment by guilleiguaran** [comment]
@coezbek please check the rubocop and changelog offenses.

**Comment by coezbek** [comment]
@guilleiguaran Done. All checks passing now.

**Review by guilleiguaran — APPROVED** [review]

**Pull request merged**
