### PR TITLE
Strip nils out of default translations. Fixes #19419

### LINKED ISSUE #19419: Rails 4.2.1 breaks if there is a nil and a string in the default translations
In rails 4.2.0 I could do this:

```ruby
    t(:"try_this", default: [:"how_about.this", nil, "Finally this")
```
and if `:"try_this"` and `:"how_about.this"` are not found in the locale file, then `"Finally this"` would be returned.

In Rails 4.2.1 I get:
```
     ActionView::Template::Error:
       translation missing: en.Finally this
```

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Is not `nil` a valid default? For what I could get the previous implementation was not removing it https://github.com/rails/rails/pull/18308/files#diff-cda406008ce3935156e8ba173b1e9837L106

**Comment by jcoyne** [comment]
rafaelfranca: nil's used to be ignored. In 4.2.1 they cause an error, but what's worse is they cause a misleading error.  They evaluate the following string as a translation and then raise an error when it is not found.

**Comment by jcoyne** [comment]
@rafaelfranca the test I added seems to pass prior to 362557e.

**Comment by rafaelfranca** [comment]
It was? The code doesn't show it being ignored, at least I can still see how it is kept on the defaults collection. Now we are removing them.

**Comment by jcoyne** [comment]
I believe it's because the conditional was changed from `remaining_defaults.first.kind_of? String` to `!remaining_defaults.first.kind_of?(Symbol)`.  `nil` is not a Symbol, but also not a string.

**Comment by jcoyne** [comment]
Another fix that works is to change the conditional to: `if has_default && !remaining_defaults.first.kind_of?(Symbol) && !remaining_defaults.first.nil?`

**Comment by rafaelfranca** [comment]
I mean, even before `362557e` and your original patch we were not striping `nil`. I just want to know why we need to do it now.

**Comment by jcoyne** [comment]
@rafaelfranca we didn't strip the nil before, but we made an unnecessary recursion through translate with `nil` as the key.

**Comment by rafaelfranca** [comment]
Got it. Could you add a CHANGELOG entry?

**Comment by jcoyne** [comment]
@rafaelfranca Added the CHANGELOG entry.

**Comment by rafaelfranca** [comment]
Fowardeported in 7815fe4 and backported at 1a91917

**Pull request merged**
