### PR TITLE
Update postgresql version to 9.4 for travis.

### PR DESCRIPTION
**Pull request by akshay-vishnoi**
Now available - https://docs.travis-ci.com/user/using-postgresql/

### CODE REVIEW

**Comment by matthewd** [comment]
Thanks, but I don't think we should do this until we specifically need to test a feature that requires the newer version.

Ultimately, I'd rather we were testing on the oldest version we support -- but that'd prevent us from covering our support for features only available in newer versions.

**Comment by akshay-vishnoi** [comment]
@matthewd - We have started mentioning support for postgres 9.4. Have a look
1. https://github.com/rails/rails/blob/master/activerecord/CHANGELOG.md L542
2. https://github.com/rails/rails/blob/master/guides/source/4_2_release_notes.md L734
3. https://github.com/rails/rails/blob/master/guides/source/active_record_postgresql.md L287, L402

**Comment by matthewd** [comment]
Are there tests that would be run with this change, which are not at the moment?

**Comment by akshay-vishnoi** [comment]
@matthewd  - Check here - https://github.com/rails/rails/pull/16220.
Support for jsonb which came with release of 9.4.
http://www.postgresql.org/docs/9.4/static/release-9-4.html

**Comment by matthewd** [comment]
Ah okay, thanks.

**Comment by akshay-vishnoi** [comment]
:smile:  No problem

**Pull request merged**
