### PR TITLE
Use Label Actions GitHub Action [ci-skip]

### PR DESCRIPTION
**Pull request by jonathanhefner**
This is an alternative to verba-sequentur.  It's a GitHub Action, not a Probot bot, so it's a bit heavier weight, but it works.

/cc @zzak

### CODE REVIEW

**Comment by zzak** [comment]
@jonathanhefner Thanks for picking this up!

I took a look at probot and couldn't find a better alternative. Is it that we're running our own bot that interfaces with GitHub Apps?

Since I couldn't find a bot that fit our needs (auto-respond by label) -- I think this is a good path forward.

**Review by 3zrv — APPROVED** [review]

**Comment by zzak** [comment]
@jonathanhefner If you remove the `[ci skip]` does this run on this PR? 🤔

**Comment by jonathanhefner** [comment]
@zzak If I understand what you mean, then no.  As far as I know, `[ci skip]` only affects Buildkite (see the [RuboCop run](https://github.com/rails/rails/pull/42690/checks?check_run_id=2980708292), for example).

I believe the only way to test drive this action is to merge the config into `main`.  I'll mark this PR as ready, and if someone from the core team is :+1:, we can give it a whirl.

**Comment by zzak** [comment]
@jonathanhefner How about adding it to a fork and showing how it works? That might help get this reviewed sooner. :pray:

**Comment by jonathanhefner** [comment]
@zzak  Sure thing.  The action will only pick up the config from the default branch, so I temporarily changed my fork's default branch to `github-action-label-actions`, and did the following:

* I created [this issue](https://github.com/jonathanhefner/rails/issues/1).
* I added the "support request" label.
* The action [ran using the branch's config file](https://github.com/jonathanhefner/rails/actions/runs/1045928614).
* The action added [this comment](https://github.com/jonathanhefner/rails/issues/1#issuecomment-882688625), and closed the issue.

**Comment by zzak** [comment]
@jonathanhefner Still want to try and move this forward, can you maybe try asking on campfire if we can get some more review?

**Pull request closed without merging**
