### PR TITLE
Fix rails-ujs auto start() in bundled environments

### LINKED ISSUE #49499: Undocumented breaking change for @rails/ujs
During the upgrade from 7.0 to 7.1 I had to change how @rails/ujs is getting initialized from

```js
import Rails from "@rails/ujs"
Rails.start()
```

to

```js
import "@rails/ujs";
```

The explicit import seems to now have side-effects as it complains about ujs already being initialized.
image

https://github.com/rails/rails/tree/main/actionview/app/javascript suggests that the previous usage is still correct.

I'm using esbuild to bundle my js, specifically with this command:
`esbuild app/typescript/*.* --target=es2022 --bundle --sourcemap --outdir=./public/build`

Is this a bug with my setup or in ujs itself?

### System configuration
**Rails version**: 7.1

**Ruby version**: 3.2.2

### PR DESCRIPTION
**Pull request by skipkayhil**
### Motivation / Background

An issue was recently raised that users were seeing an error when upgrading `@rails/ujs` to 7.1.0+:

```
Uncaught Error: rails-ujs has already been loaded!
```

Generally this issue appears due to the difference in how rails-ujs is expected to behave in a pure sprockets environment (js appending) vs a bundled environment (webpack, esbuild, etc.). The sprockets environment is supposed to call start() automatically, while the bundled environment is supposed to require users to import and call start() themselves.

As part of the transition from coffeescript to javascript, a condition was added that was intended to detect whether the current environment was a bundler so that it would only call start() when in sprockets. However, this condition is not working as expected, and I was able to reproduce the error appearing when using rails-ujs with importmaps and esbuild. Interestingly, the issue did not appear when using Webpack as a bundler.

### Detail

I believe the best fix here is to make the condition very explicit. Since sprockets users should not be using the esm version of rails-ujs, we can use the rollup replace plugin to explicitly opt the esm bundle out of _ever_ calling start() automatically. This works because terser will run after the replace plugin and remove the whole condition as dead code (since it sees true == false).

### Additional information

Fixes #49499
Closes #49606

I tested sprockets, importmaps, esbuild, and webpack using this app: https://github.com/skipkayhil/rails-ujs-app

cc @tricknotes I added you as a co-author for your work on this issue as well
cc @Earlopain I'd really appreciate if you'd be able to test this out

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by Earlopain** [comment]
Hi skipkayhil, thanks for working on this. I can confirm that this fixes the issue for me.

**Comment by nijikon** [comment]
I can confirm that this fixes the issue for me as well. When can we merge it and do a release?

**Comment by eileencodes** [comment]
This doesn't cherry-pick cleanly to 7-1-stable. @skipkayhil do you mind backporting this and cc/ing me on the PR?

**Comment by skipkayhil** [comment]
> This doesn't cherry-pick cleanly to 7-1-stable. @skipkayhil do you mind backporting this and cc/ing me on the PR?

👍

**Pull request merged**
