### PR TITLE
Fixing links in docs

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
And a minor fix in docs found through the new links.

### CODE REVIEW

**Comment by repinel** [comment]
It seems to me that those links are already working as expected. You can check the [Active Model README](http://edgeapi.rubyonrails.org/files/activemodel/README_rdoc.html).

Thanks for the PR :smiley:

**Comment by rafaelfranca** [comment]
These links were made to be read on the guides page not through GitHub. Thank you for the pull request.

**Comment by deivid-rodriguez** [comment]
Aaaaah I see... You can cherry pick the last commit though.

Thanks!

**Comment by deivid-rodriguez** [comment]
I opened a different PR: https://github.com/rails/rails/pull/21129/files

**Pull request closed without merging**
