### PR TITLE
Add Hash#delete_at

### PR DESCRIPTION
**Pull request by seanpdoyle**
Add `Hash#delete_at` to delete values from a list keyed by its
arguments. Mirrors the [Hash#values_at][] and [Array#delete_at][]
interfaces, and pairs nicely with multiple assignment.

```ruby
hash = { a: true, b: false, c: nil }
a, c = hash.delete_at(:a, :c) # => [ true, nil ]
hash # => { b: false }
```

[Array#delete_at]: https://ruby-doc.org/core-3.0.0/Array.html#method-i-delete_at
[Hash#values_at]: https://ruby-doc.org/core-3.0.0/Hash.html#method-i-values_at

### CODE REVIEW

**Comment by rafaelfranca** [comment]
I'm not sure we have a strong case to add a core extension. Where this can be used in the framework or in most web applications?

`delete_at` is a feature in Ruby. I think it is better to propose this directly to Ruby.

**Comment by seanpdoyle** [comment]
@rafaelfranca `Hash#delete_at` can be really useful in view helpers or partial locals that deal with `aria: {}` and `data: {}` hashes:

```ruby
def my_special_tag(text, data: {})
  controllers, actions = data.delete_at(:controller, :action)

  tag.button text, data: {
    controller: token_list("special", controllers),
    action: token_list("click->special#doSomething", actions),
    **data
  }
end
```

I always thought of ActiveSupport as a staging area for these types of extensions, but it never occurred to me to propose the feature directly to Ruby itself.

**Comment by rafaelfranca** [comment]
> I always thought of ActiveSupport as a staging area for these types of extensions

David sees that way. I prefer to see as "a quick way to get new Ruby features".

I'm fine for us to include this here, but I'd propose to Ruby as well.

**Comment by composerinteralia** [comment]
Might be worth thinking about `Hash.new(0).delete_at(:key)`. It currently returns `[nil]`, whereas `Hash.new(0).values_at(:key)` returns `[0`]

**Comment by seanpdoyle** [comment]
@composerinteralia thank you for calling that out! I've added some tests to cover different default value cases.

**Comment by composerinteralia** [comment]
@seanpdoyle if you want to explore adding this to ruby, it might look roughly like:

```diff
diff --git a/hash.c b/hash.c
index b34351aab3..0e171e2a26 100644
--- a/hash.c
+++ b/hash.c
@@ -2678,6 +2678,34 @@ rb_hash_values_at(int argc, VALUE *argv, VALUE hash)
     return result;
 }
 
+/*
+ *  call-seq:
+ *    hash.delete_at(*keys) -> new_array
+ *
+ *  Deletes entries at the specified keys, and returns a new \Array
+ *  containing values for the given +keys+:
+ *    h = {foo: 0, bar: 1, baz: 2}
+ *    h.delete_at(:baz, :foo) # => [2, 0]
+ *    h # => {bar: 1}
+ *
+ *  The {default values}[#class-Hash-label-Default+Values] are returned
+ *  for any keys that are not found:
+ *    h.delete_at(:hello, :bar) # => [nil, 1]
+ */
+VALUE
+rb_hash_delete_at(int argc, VALUE *argv, VALUE hash)
+{
+    VALUE result = rb_ary_new2(argc);
+    long i;
+
+    for (i=0; i<argc; i++) {
+       rb_ary_push(result, rb_hash_aref(hash, argv[i]));
+       rb_hash_delete(hash, argv[i]);
+    }
+    return result;
+}
+
+
 /*
  *  call-seq:
  *    hash.fetch_values(*keys) -> new_array
@@ -7029,6 +7057,7 @@ Init_Hash(void)
 
     rb_define_method(rb_cHash, "shift", rb_hash_shift, 0);
     rb_define_method(rb_cHash, "delete", rb_hash_delete_m, 1);
+    rb_define_method(rb_cHash, "delete_at", rb_hash_delete_at, -1);
     rb_define_method(rb_cHash, "delete_if", rb_hash_delete_if, 0);
     rb_define_method(rb_cHash, "keep_if", rb_hash_keep_if, 0);
     rb_define_method(rb_cHash, "select", rb_hash_select, 0);
```

**Comment by seanpdoyle** [comment]
Thank you for drafting that up @composerinteralia. I've opened https://github.com/ruby/ruby/pull/4193 and listed you as co-author.

**Comment by seanpdoyle** [comment]
Some feedback from the ruby/ruby PR:

> It seems inconsistent with Array#delete_at.
> It's questionable to return the default value for non-existent key.

In my usage prior to this PR, I had never called `#delete_at` on a Hash with a default (value/block), so I hadn't considered what the behavior should be.

Is it worth paring down this PR to ignore those cases?

```diff
diff --git a/activesupport/lib/active_support/core_ext/hash/delete_at.rb b/activesupport/lib/active_support/core_ext/hash/delete_at.rb
index 05ef0161fc..995bc63822 100644
--- a/activesupport/lib/active_support/core_ext/hash/delete_at.rb
+++ b/activesupport/lib/active_support/core_ext/hash/delete_at.rb
@@ -9,9 +9,7 @@ class Hash
   #   a, c = hash.delete_at(:a, :c) # => [ true, nil ]
   #   hash # => { b: false }
   #
-  def delete_at(*keys, &block)
-    block ||= default_proc
-
-    keys.map { |key| delete(key, &block) || default }
+  def delete_at(*keys)
+    keys.map { |key| delete(key) }
   end unless method_defined?(:delete_at)
 end
diff --git a/activesupport/test/core_ext/hash_ext_test.rb b/activesupport/test/core_ext/hash_ext_test.rb
index d717cbb6ff..06eb7d76d4 100644
--- a/activesupport/test/core_ext/hash_ext_test.rb
+++ b/activesupport/test/core_ext/hash_ext_test.rb
@@ -442,24 +442,17 @@ def test_delete_at
     assert_equal({ b: "b" }, original)
   end
 
-  def test_delete_at_with_block
-    original = {}
-
-    assert_equal [0], original.delete_at(:a) { 0 }
-    assert_empty original
-  end
-
   def test_delete_at_missing_key_with_default_value
     original = Hash.new(0)
 
-    assert_equal [0], original.delete_at(:a)
+    assert_equal [nil], original.delete_at(:a)
     assert_empty original
   end
 
   def test_delete_at_missing_key_with_default_block
     original = Hash.new { 0 }
 
-    assert_equal [0], original.delete_at(:a)
+    assert_equal [nil], original.delete_at(:a)
     assert_empty original
   end
 end

```

**Comment by zzak** [comment]
@seanpdoyle Were you able to open a feature proposal to r-l.o? I agree with RF here, it's probably better to at least get approval from ruby-core before we add this to Rails.

At this point, it's probably easier to upgrade your Ruby version than upgrading legacy Rails apps for `Hash#delete_at`. But this is just my feeling.

**Pull request closed without merging**
