### PR TITLE
AR::Relation#exists? doesn't have to query if the relation is loaded and no condition was given

### PR DESCRIPTION
**Pull request by amatsuda**
Here's a patch aiming to reduce unneeded DB queries.

### CODE REVIEW

**Comment by egilburg** [comment]
You could use `assert_queries(0)` to ensure your patch actually prevents a query.

But also a question - is there an intended API for guaranteed queries bypassing loading? For example `.count` is guaranteed to make a query, rather than convert to `size`, and sometimes is useful specifically when you need latest db count.

`exists` could in theory be used for same purpose - e.g. in multi threaded systems to reduce dirty reads.

**Comment by amatsuda** [comment]
> is there an intended API for guaranteed queries bypassing loaded data?

Semantically, the code should better be written like `Model.where(some_condition).exists?` rather than `existing_relation.exists?` in that case.
If an already existing relation was asked about the existence without any extra condition, that would just mean "do you hold any record?". To me the difference looks natural.

Or technically, you may be able to do something like `existing_relation.exists?(['1=1'])` (if you want to maintain such a puzzling code).

**Comment by amatsuda** [comment]
> You could use assert_queries(0) to ensure your patch actually prevents a query.

Thanks for the advice. Of course I knew the API, but I just refrained from specifying too much of an implementational detail in the test code. And instead, I only added some tests to ensure that the behavior does not change.
But if people think that not to query in this case should be explicitly stated as a specification, I have no reluctance to add `assert_no_queries`.

**Review by gmcgibbon — COMMENTED** [review]
Still relevant in Rails 6 (11581afc01927565d57dd0e0156e983f92f8c2e0). Approach looks good! If you're still interested in getting this merged, please rebase.

**Comment by bogdanvlviv** [comment]
I think `#exists?` always queries by design in order to be sure that at least one object, which satisfies some condition(if provided) exists, at execution time. If you want to omit query when the relation is loaded you should probably use `#any?` in that case.

**Pull request closed without merging**
