### PR TITLE
switch from load_database_yaml to database_configuration

### PR DESCRIPTION
**Pull request by vkalach**
### Motivation / Background

This Pull Request has been created because `load_database_yaml` doesn't work properly for database.yml that contains ruby code i.e. `<%= ENV %>` and also as we can see there is a comment for `load_database_yaml` method: "use database_configuration instead of load_database_yaml"

### Detail

This Pull Request changes the method we call: instead load_database_yaml we call database_configuration. Both returns hash with database settings.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [ ] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by eileencodes** [comment]
Hey @vkalach I need you to elaborate, I don't understand what you're trying to do. The `setup_initial_database_yaml` isn't called by prepare, it's only called [here](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/railties/databases.rake#L7) which is used to generate the task names like [this](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/railties/databases.rake#L35-L42).

**Comment by vkalach** [comment]
@eileencodes when we call `rails db:test:prepare` I receive an error `undefined method invoke for Nil` and if I use --trace to track - it points me on [this line](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/railties/databases.rake#L495) where we take databases that are set [there](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/railties/databases.rake#L7). And when I check - I can see the only stuff that is Nil - my URL that is set by ENV variable

**Comment by OnlyReFLeX** [comment]
I also have problem with "load_database_yaml" when i use `<%= ENV['DB_KEY'] %>:`, also here is message ["Do not use this method, use #database_configuration instead."](https://github.com/rails/rails/blob/539144d2d61770dab66c8643e744441e52538e09/railties/lib/rails/application/configuration.rb#L390)

I did monkey patching for fix that in my project
```ruby
module ActiveRecord
  module Tasks
    module DatabaseTasks
      def setup_initial_database_yaml # :nodoc:
        return {} unless defined?(Rails)

        Rails.application.config.database_configuration
      end
    end
  end
end
```

Otherwise "Rails couldn't infer whether you are using multiple databases from your database.yml and can't generate the tasks for the non-primary databases. If you'd like to use this feature, please simplify your ERB."

**Comment by eileencodes** [comment]
The "do not use this method" is a message for applications, not for Rails internals (I wrote the original feature). Calling `Rails.application.config.database_configuration` might not be a valid configuration if it depends on the environment being loaded (that's the whole point of using `load_database_yaml` over `database_configuration`, you can see it in the failing tests from this PR).

If someone can reproduce this and open an issue with that reproduction we can find a fix. But changing this to `database_configuration` is not the right way to fix this.

**Pull request closed without merging**
