### PR TITLE
Use double quotes in *.erb.tt and *.rb.tt templates

### PR DESCRIPTION
**Pull request by albertoalmagro**
### Summary

Currently we are mixing the use of single and double quotes in our `*.erb.tt` and `*.rb.tt` templates. As we decided to prefer double quotes over single quotes, this patch homogenizes this for these templates.

### CODE REVIEW

**Comment by pixeltrix** [comment]
@albertoalmagro thanks for the PR. Currently we don't enforce the style guidelines in the .tt and .erb files because rubocop doesn't support that. Therefore what we're planning to do is see if erb_lint can enforce it along with adding a railties test to generate an app and run rubocop/erb_lint against it as well. Therefore I'm going to close this PR since we'd prefer the cleanup to be part of that process rather than lots of little commits, but thanks again.

**Comment by albertoalmagro** [comment]
@pixeltrix appreciate that information. In my opinion this PR still has value: we would stop **now** generating code that sometimes is double quoted and sometimes single quoted. If we add a linter later (which will only affect `erb` files) it would be great, but I wouldn't throw away work that is already done and that goes in the direction we want to achieve 😉

**Comment by pixeltrix** [comment]
@albertoalmagro we wouldn't backport this change as we don't want to create unnecessary changes in apps that people are upgrading in point releases, only for a major release which will be a few months  yet and we'd also would want to extend it to .tt files which are erb files really.

**Comment by albertoalmagro** [comment]
Thanks @pixeltrix for the explanation. May I submit the PR that adds `erb-lint`?

**Comment by henrik** [comment]
I was slightly bothered by the mixed quote style and made a PR #36124 which turned out to be a subset of this PR.

For what it's worth, I also feel that it would be a win for Rails to generate more template files in new apps. I agree it'd be great if this could be enforced automatically, but I also see the risk of a "perfect the enemy of the good" situation. We could make this small improvement now and also add automatic enforcement some time in the future.

> only for a major release which will be a few months yet 

We're now getting close to the Rails 6 release, so the timing is perfect :)

**Pull request closed without merging**
