### PR TITLE
[Guides] Format css in line with normal style [ci skip]

### PR DESCRIPTION
**Pull request by Labern**
### Motivation / Background

Quickly brings the CSS here into line with the normal style — lowercase element-names (e.g. h1) and one element per line, as per the rest of the stylesheets.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by fatkodima** [comment]
Instead of pointless changes like this, try to solve any issue from the existing list - https://github.com/rails/rails/issues.

**Comment by Labern** [comment]
> Instead of pointless changes like this, try to solve any issue from the existing list - https://github.com/rails/rails/issues.

Why would I, with an attitude like that? I’ve seen a lot of “pointless changes” in the 90,000+ commits that change single things, standardise formatting, location, and so on.

I don’t think there’s anything pointless about logical structure — or politeness.

**Comment by skipkayhil** [comment]
I really appreciate the enthusiasm to contribute so let me qualify a bit. Spacing changes without a linter enforcing them are not ideal because its very easy to regress. Combine that with more than a few PRs opened that make 1-2 line changes in this area and it can come across as "spammy" because the time/effort to review multiple tiny PRs is larger (and its just a lot of noise).

If you find opportunities to improve the docs/guides whether visually or rhetorically (or even correctness) we would be more than happy to merge those PRs

**Comment by Labern** [comment]
Sure, that’s absolutely fine — I can understand that logic.

I was working through the documentation before digging into the code and getting used to the pull request system as a whole: I’m familiar with Ruby and Rails but less so with GitHub’s merging system. I did have a pull request merged for what I would consider something more trivial the other day, so not sure about the consistency here.

I do think changes to punctuation in documentation for human-readable docs do qualify as useful — I made sure to review the last hundred commits and saw a lot of “fix typo” with a single change in a comment nested deep inside a library/module, so I figured these were valuable contributions.

Anyway, apologies if multiple pull requests are not encouraged, I can certainly squash commits into one. Either way, I think it’s just counterproductive to call someone’s time and effort “pointless”. No one’s time and effort is worth more than anyone else’s on a voluntary project. It’s a brusque and inflammatory word that makes future contributions less likely to occur, and more disrespectful than I’d expect from the Rails — and Ruby — philosophy, specifically MINASWAN. 

I have no problem with closed pull requests, just being told what to do.

Similarly, inviting someone to work on issues that others have raised doesn’t, by itself, make sense. A contributor must surely be able to focus on their own interests, and be guided by their own skills. I come from a proofreading and writing background so I’m attuned to finding grammatical and punctuation errors and making things more consistent, readable, and logical. If this isn’t useful here then that’s absolutely fine, perhaps I misjudged the point of documentation and comments in the Rails source code.

I’ve actually got an issue that I created (adding a light mode/dark mode toggle on the guides) that no one has replied to. I haven’t worked on as I didn’t want to pour time into it without some advice first, so as not to infringe on the design principles of the guides.

Thank you for your reply and explanation of why multiple pull requests, minor changes, and why these pull requests were closed (although I still maintain there is at least some value in some of them). I appreciate the work you all do on making what is, in my opinion, the absolutely best software in the world today. I love Rails.

**Pull request closed without merging**
