### PR TITLE
Adding validates_instance_of method to check class of an attribute

### PR DESCRIPTION
**Pull request by mohitnatoo**
While working on one of the projects I'd come across a code like

```
class Order < ActiveRecord::Base
  has_one :approver
  attr_accessor :approver
  validates_presence_of :approver
end

class Moderator < User
end

class SuperAdmin < Moderator
end
```

Now if the logic is to say that approver can only be a `SuperAdmin`, we'd want to have a way to determine the validity of the record.

Added `validates_instance_of` method to check for such validation.

```
class Order < ActiveRecord::Base
  validates_instance_of :approver, is_a: SuperAdmin #This will validate if class is SuperAdmin
  validates_instance_of ::approver, in: [SuperAdmin, Moderator] will pass if approver is either of SuperAdmin or Moderator
```

### CODE REVIEW

**Comment by mohitnatoo** [comment]
@pixeltrix did you get a chance to review this? I was hoping to hear from you.

**Comment by vipulnsward** [comment]
Hi @mohitnatoo generally, the person assigned, or someone from the team reviews when they get time.
Its better to avoid pinging 😃

**Comment by rafaelfranca** [comment]
How would be this code used? Validations are for user input. I don't see how users would build a class of different type of what is programmed. For me this seems more a validation to protect from programming errors. Could you show an example where this validation would be useful?

**Comment by mohitnatoo** [comment]
Generally when validation would come into place, we'd have

```
if object.valid?
  # further processing
end
```

The aim here is to provide an additional option to the programmer to avoid the 'further processing' part for invalid records. The use of validations however is subject to the programmer.  
Also speaking of programming errors `validates_presence_of` is one of the most generic validations and would pass for any non blank value of the attribute(say attribute `my_attr`) the validation is applied on. Now say we have something like an `after_save` callback on a record that runs on `my_attr` we'd not want to wait till then to realise something had gone wrong. This one probably goes beyond simple`validates_presence_of` and can invalidate the record in the first place itself.

**Pull request closed without merging**
