### PR TITLE
Fix 7.1 load_defaults ordering [ci skip]

### PR DESCRIPTION
**Pull request by skipkayhil**
The list should be alphabetical, but belongs_to_required_... is in the wrong spot

### CODE REVIEW

**Comment by jonathanhefner** [comment]
Thank you, @skipkayhil! :abc:

**Comment by yahonda** [comment]
I was wondering if https://github.com/rails/rails/commit/e5d15140d2dfd25f33e306ab8522f7accd410dc3 intentionally makes order in activerecord/lib/active_record/railtie.rb and guides/source/configuring.md consistent like:

https://github.com/rails/rails/blob/698f12640049bc3cf7e1ad5a2e2deaff70e259f1/activerecord/lib/active_record/railtie.rb#L39-L40

**Comment by yahonda** [comment]
I am not familiar with the config order in `railties.rb and though so please disregard if it is acceptable.

**Comment by jonathanhefner** [comment]
@yahonda In the guide, it is alphabetical order to be easy to scan quickly.  But, in the railtie, I think another order is acceptable (e.g. grouped by concept, chronological order, etc). :+1:

**Comment by yahonda** [comment]
Understood. Thanks!

**Pull request merged**
