### PR TITLE
Polymorphic URL should default to HTTPS if force_ssl = true

### PR DESCRIPTION
**Pull request by johnnyshields**

### CODE REVIEW

**Comment by eileencodes** [comment]
Hey @johnnyshields looks like this broke a whole bunch of tests that don't have access to the `Rails` constant. Can you take a look at those?

**Comment by eileencodes** [comment]
Actually, we can't access the Rails configuration inside ActionPack which is why the tests are failing. Railties isn't (and shouldn't be) a dependency of AP, so this patch isn't going to work.

**Comment by johnnyshields** [comment]
One option is `if defined?(Rails) && Rails.config.force_ssl` but that seems like quite a hackish solution. Is there any other way I can access the config?

**Comment by matthewd** [comment]
Without looking closely, this sounds like the wrong place to do it: I'd expect this to be right next to something that's defaulting the host, and to only apply in that case. Maybe finding that place will hold a clue for getting the value, as well?

**Comment by johnnyshields** [comment]
@matthewd I think you're right, it should go at least near somewhere in the model-specific url helper and ideally in the part with the host. I'll take a closer look later.

**Pull request closed without merging**
