### PR TITLE
Add #not_exists? method in ActiveRecord::FinderMethods

### PR DESCRIPTION
**Pull request by guillaumebriday**
### Summary

Adding a convenient method that it the opposite of `ActiveRecord::FinderMethods#exists?`.

```ruby
!User.where(name: 'David').exists?

# same as

User.where(name: 'David').not_exists?
```

### Other Information

I can add more tests if needed but I use the `exists?` method that is already very well tested so I don't find think it's necessary, what do you think?

### CODE REVIEW

**Comment by simi** [comment]
If I understand ti well, you can do `User.where(name: 'David').reset.empty?` to ensure it is checked by query.

**Comment by guillaumebriday** [comment]
well @simi I did not know the method `#reset` to be honest. But yeah it seems to be pretty much the same!

**Comment by danielricecodes** [comment]
[ActiveRecord::Relation#none?](https://github.com/rails/rails/blob/83217025a171593547d1268651b446d3533e2019/activerecord/lib/active_record/relation.rb#L270) already provides this.  Its up to your ORM to issue the proper query.  

With `postgresql`:

```ruby
User.where(id: 1).none?
```

Issues an "Exists" type query (notice the Select clause):
```
  User Exists? (3.1ms)  SELECT 1 AS one FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
```

On a large database table, this is very, very fast.

**Comment by rafaelfranca** [comment]
Thank you for the pull request. I don't find `non_exists?` better than `!exists?` or even `none?`. I prefer to not increase the API surface of the framework.

**Comment by guillaumebriday** [comment]
Thanks @rafaelfranca for the feedback!

**Pull request closed without merging**
