### PR TITLE
sanitize empty and nil parameters to select #31059

### LINKED ISSUE #31059: Select(nil) and select(false) don't chain with more selects
### Steps to reproduce

Both `select(nil)` and `select(false)` work fine by themselves or chained with other query methods (in the sense that they're just ignored):
```
> User.select(nil).to_sql
 => "SELECT `users`.* FROM `users`" 
```
```
> User.select(false).where(username: 'foo').to_sql
 => "SELECT `users`.* FROM `users` WHERE `users`.`username` = 'foo'"
```
But they give an error when chained with another select:
```
> User.select(nil).select(:username).to_sql
Arel::Visitors::UnsupportedVisitError: Unsupported argument type: NilClass. Construct an Arel node instead.
```
This is inconsistent with the behavior of other query methods, like `joins` or `where`, which work fine with a similar pattern. 

The pattern is very useful for chaining conditional selects, like:
```
User.select(test && :full_name).select(:username)
```
This works fine if test is not false but fails with the above error if it's false.

### Expected behavior
```
> User.select(nil).select(:username).to_sql
=> "SELECT `users`.`username` FROM `users`"
```

### Actual behavior
```
> User.select(nil).select(:username).to_sql
Arel::Visitors::UnsupportedVisitError: Unsupported argument type: NilClass. Construct an Arel node instead.
```

### System configuration
**Rails version**: 5.1.4

**Ruby version**: 2.4.2

### PR DESCRIPTION
**Pull request by mohsen-alizadeh**
Fixes #31059

### CODE REVIEW

**Comment by kaspth** [comment]
Ref: https://github.com/rails/rails/issues/31059

r? @kamipo, this doesn't strike as the best solution to the problem, but perhaps you know something I don't.

**Comment by mohsen-alizadeh** [comment]
#31059

**Comment by octavpo** [comment]
I don't know what's the best solution, but I found another case that fails with `select(nil)` and is fixed by this PR (I checked):
```
User.select(nil).count
```
results in a query:
```
SELECT COUNT() FROM `users`
```
which raises a Mysql error (notice the missing '*' in count).

**Comment by matthewd** [comment]
If it's good enough for `where` (approximately) and `includes` (literally), it seems good enough for `select` too, to me.

@mohsen-alizadeh can you add a test as well?

**Comment by mohsen-alizadeh** [comment]
@matthewd   test added

**Pull request merged**
