### PR TITLE
Prefer `capture_io` in `AS::Deprecation` tests

### PR DESCRIPTION
**Pull request by jonathanhefner**
For these tests, `capture_io` is more performant than `ActiveSupport::Testing::Stream#capture`, and it eliminates one testing dependency.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Not sure this is a good justification. We really don't care that much about test performance, and well, that dependency is inside of the framework already. I don't think `out, err = capture_io` is better than `capture(:stderr)` in terms of readability, which I believe it is more important here.

**Comment by jonathanhefner** [comment]
My preference for `capture_io` is also based on it being a well known Minitest method (at least, to me).  When I was first going through these tests, I was not especially familiar with `capture`.  I wasn't sure if it operated on e.g. `STDERR` vs `$stderr`.  I also did not know that it was provided by `ActiveSupport::Testing::Stream`, and, because it is [`nodoc` / private](https://github.com/rails/rails/blob/a29a6ae95d126a514f8eb782dd5dba75bb7f5d9e/activesupport/lib/active_support/testing/stream.rb#L5-L23), I could not search for it in the API docs.

That said, I do not have an overwhelming preference, and I can revert this if you would like.

**Comment by rafaelfranca** [comment]
This is the Rails framework, not a Rails app. So the fact that something is nodoc or not has no relevance. nodoc code is made to be used inside Rails, otherwise it would not exist. Most things used to develop the Rails framework will not be in the API docs.

I get the point about `STDERR` vs `$stderr` though. I still think `capture` reads better than the pipeline assignment specially if we don't care about stdout. How about `assert_output` then? I think that would satisfy the yours and my requirements.

**Comment by jonathanhefner** [comment]
> This is the Rails framework, not a Rails app ... nodoc code is made to be used inside Rails, otherwise it would not exist

I do understand this.  What I was trying to say is that familiarity and / or discoverability go hand-in-hand with readability.

> How about `assert_output` then? I think that would satisfy the yours and my requirements.

I am not sure exactly what you have in mind, but if it is something like `assert_output(/pattern/) { print_output }`, I think it might make [multiple assertions](https://github.com/rails/rails/blob/514ae381a3b9f34a36837f0f0cb017074e8c50e7/activesupport/test/deprecation_test.rb#L124-L125) (including [positive and negative assertions](https://github.com/rails/rails/pull/46037/files#diff-8c6f12b264f783924d051da8485c3bf7c1a64f4575dcc2204e97906cc3fac0b5R123-R124)) more difficult.

Instead, I have switched back to `capture(:stderr)` in 6554cf67c93199f7faeb55b5ca7cebd00319db5d.

**Comment by rafaelfranca** [comment]
Ahh, right, we have more than one match per test. Good point.

**Pull request merged**
