### PR TITLE
Pass block to Relation#distinct and Relation#uniq

### PR DESCRIPTION
**Pull request by hwhelchel**
Observes `Array#uniq` semantics when passing a block to `distinct` or `uniq`. Loads an array of the relation and then uses the return value of the block to determine uniqueness.

See: https://github.com/rails/rails/issues/20189

### CODE REVIEW

**Comment by hwhelchel** [comment]
Looks like `Relation#distinct` started out as `Relation#uniq`. Because it didn't behave exactly like `Array#uniq` there was confusion so the method was renamed to `distinct` which reflects the existing SQL behavior. 

Today, `uniq` and `uniq!` are marked as silently deprecated and are aliases of `distinct` and `distinct!` respectively. I therefore updated `distinct` and emulated how the `select` method handles blocks.

**Comment by senny** [comment]
As you pointed out, we renamed `uniq` back to `distinct`. The `Relation` object is used to build SQL queries, I'd rather not add behavior that acts on the returned Ruby objects. If it's not something we can do on the database end I prefer to use the result array directly:

```ruby
relation.to_a.uniq {}
```

This clearly communicates that the queries is executed before the applying the uniqueness constraint.

I'm :-1: on this addition but let's get some more feedback before deciding.

/cc @rafaelfranca @carlosantoniodasilva @sgrif

**Comment by carlosantoniodasilva** [comment]
I think I'd rather leave the block out of this, and let users call `to_a` when they actually need an array back to work with. So I agree with @senny. Thanks for your contribution.

**Comment by rafaelfranca** [comment]
> Today, uniq and uniq! are marked as silently deprecated and are aliases of distinct and distinct! respectively.


> If it's not something we can do on the database end I prefer to use the result array directly:

So lets deprecate `uniq` or raise an argument error when block is passed. Right now it is hard to tell if we are using array method or relation method.

**Comment by hwhelchel** [comment]
@rafaelfranca 's recommendation is in line with the history of changes to this method. I think deprecating uniq would be best. Let me know if you all agree.

**Comment by senny** [comment]
@hwhelchel yup, seems reasonable. I introduced `distinct` as a clear successor to `uniq` but since `uniq` was pretty new I didn't hard deprecate it at the time.

I'll add in the `Relation#uniq` deprecations on `master` for Rails 5.

**Comment by senny** [comment]
@hwhelchel @rafaelfranca Added the discussed deprecation https://github.com/rails/rails/commit/adfab2dcf4003ca564d78d4425566dd2d9cd8b4f

Going to close this PR. Thanks for reporting :yellow_heart:

**Pull request closed without merging**
