### PR TITLE
Do not enable disabled elements for XHR redirects

### LINKED ISSUE #29473: rails-ujs prematurely enables disabled elements for XHR requests with redirects
### Steps to reproduce

```
rails new rails-ujs-test
```

```
# config/routes.rb

Rails.application.routes.draw do
  resources :users
end
```

```
# app/controllers/users_controller.rb

class UsersController < ApplicationController
  def index
    sleep 2
  end

  def new
  end

  def create
    sleep 2
    redirect_to users_path
  end
end
```

```
# app/views/users/new.html.erb

<h1>Users#new</h1>

<%= form_with url: users_path do |form| %>
  <%= form.submit "Create user", data: { disable_with: "Creating user..." } %>
<% end %>
```

```
# app/views/users/index.html.erb

<h1>Done!</h1>
```

Start the server, visit http://localhost:3000/users/new and click on the submit button.

### Expected behavior

When the form is submitted, the submit button should be disabled until the redirect action finishes. This is the behaviour which happens for non-XHR requests.

### Actual behavior

The submit button is disabled during the `create` action. But the `create` action redirects us to the `index` action and button is enabled again in the meantime.

This is caused by combination of rails-ujs and Turbolinks.

`redirect_to users_path` is automatically converted to

```
Turbolinks.clearCache()
Turbolinks.visit("http://localhost:3000/users", {"action":"replace"})
```

for XHR requests. This is a HTTP 200 reply and when rails-ujs receives it, then it enables the button again which allows users to click on it again. This is happening in our real world app even if the responses are pretty fast.

You can see it here:

ujs-test

I've reported this issue to the original rails-ujs repository some time ago. But it doesn't exist anymore and I can't reference the original report. However, I've tried to fix it, but I did not find a workable solution. It should be probably fixed in rails-ujs which shouldn't enable elements again if a response contains `Turbolinks.visit`.

### System configuration
**Rails version**: 5.1.1 and `master` branch

**Ruby version**: 2.4.1p111

**Turbolinks version**: 5.0.1

### PR DESCRIPTION
**Pull request by mrhead**
### Summary

Fixes #29473.
Depends on: https://github.com/turbolinks/turbolinks-rails/pull/28

### Before

27210987-8e142704-5256-11e7-812d-7c2b9a1b10df

### After

rails-ujs-redirect

### CODE REVIEW

**Comment by mrhead** [comment]
Related PR: https://github.com/turbolinks/turbolinks-rails/pull/28

**Comment by sgrif** [comment]
r? @rafaelfranca 

Sorry I have no clue who to assign to this. I am not the right person to review this.

**Comment by mrhead** [comment]
I've just updated this PR with tests for rails-ujs.

**Comment by mrhead** [comment]
@rafaelfranca I've added tests and updated the PR summary to better demonstrate the issue. Could you please review it? Thank you!

**Comment by mrhead** [comment]
@rafaelfranca Thank you!

**Comment by Laykou** [comment]
@mrhead Do you know when new release 5.2.2 is planned? This merge request fixes our issue and we'd like to use it. Currently we can install rails gem from `master` branch, but we find it very risk and only as temporary solution. If you happen to know planned date for 5.2.2 it would help us a lot in our planning. Thanks a lot!

**Comment by mxlje** [comment]
Am I correct in that this is actually _not_ part of 5.2.2 or 5.2.3? I just updated to 5.2.3 and I still see the old behavior.

**Comment by mrhead** [comment]
This should be released with Rails 6.

**Pull request merged**
