### PR TITLE
Fixed typos [ci skip]

### PR DESCRIPTION
**Pull request by equiamos**
Fixed typos and improved grammatical consistency

### CODE REVIEW

**Comment by zzak** [comment]
Can you please squash these commits?

**Comment by equiamos** [comment]
I'm researching how to do that now. Sorry, I'm new!

**Comment by equiamos** [comment]
Sorry--I'm afraid I may have screwed something up locally when I attempted to rebase and squash the commits. I can redo everything and only commit once if that would be easiest. What should I do? Please let me know, and sorry for the inconvenience!

**Comment by jonatack** [comment]
Hi @equiamos, I empathize. If you can, try `git rebase -i HEAD~5`, follow the instructions then save, followed by `git push -f`.

**Comment by equiamos** [comment]
Thank you @jonatack!! That's what I tried, but it changed my open terminal to vim(?) and then when I tried to make changes and save it only allowed me the option of saving it to desktop as "Terminal Saved Output". So I found the rebase-merge folder in Atom (the text editor I use), made the changes in the git-rebase-todo file there, saved them and closed out, but nothing opened in my text editor. (So then I tried a couple other things, hence the fear I screwed something up locally.) Sorry for being so clueless! I'm trying really hard to learn. Any suggestions, advice, or insight will be much appreciated!

**Comment by jonatack** [comment]
Edit your .gitconfig file to set the editor to be opened by git for operations like that. Some examples:

```
# ~/.gitconfig
editor = mate -wl1
editor = vi
editor = emacs
```

**Comment by equiamos** [comment]
Thank you @jonatack! I've set Atom as my default editor. Then I did `git rebase --abort`, and `git rebase -i HEAD~5`. This time it opened in my editor :). Then I followed the instructions, saved and closed out, but then nothing happened. Terminal still shows "sleep" and acts busy.

**Comment by equiamos** [comment]
Okay--I *think* I got it figured out @jonatack! Please disregard my last comment. It just uploaded something, so hopefully I did everything right. :\ Thank you SO much for your help!!!

**Comment by equiamos** [comment]
@zzak commits should be squashed. Please let me know if there are any issues. Thank you!

**Comment by jonatack** [comment]
You did it :+1:

**Comment by equiamos** [comment]
Yay! :) Thank you so much!!

**Comment by zzak** [comment]
@equiamos Great work! Thank you for your contribution and congrats!

@jonatack Thank you for your help as well!!

**Comment by equiamos** [comment]
Thank you!!!

**Pull request merged**
