### PR TITLE
Match pages with format if passed as option

### PR DESCRIPTION
**Pull request by alvarezloaiciga**
This solves issue: https://github.com/rails/rails/issues/19290

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Could you explain why and when this is needed?

**Comment by alvarezloaiciga** [comment]
Yeah, I added some examples there, it is to ignore the url format `(json, xml, ...)`, when you compare the urls on `current_page?`. If the format is added in the options passed, it will then check for the format.

**Comment by visualsayed** [comment]
@alvarezloaiciga, thanks

**Comment by cmrd-senya** [comment]
What is the status of this PR? Is it going to be merged?

**Pull request closed without merging**
