### PR TITLE
Unpin sprockets-rails

### LINKED ISSUE #52038: railties tests get NoMethodError: undefined method `deprecator' with sprockets-rails 3.5.0
Managed to reproduce CI failure at https://buildkite.com/rails/rails/builds/108070#018fee5d-8995-46f4-929a-fd4be5951ef4/1314-1322

### Steps to reproduce
```ruby
git clone https://github.com/rails/rails
cd rails/railties
bundle update sprockets-rails --conservative
git diff # to show which gems updated
bin/test test/application/test_runner_test.rb:509
```

### Expected behavior
It should pass.

### Actual behavior
It raises "undefined method `deprecator' ".

```ruby
$ bundle update sprockets-rails --conservative
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Using sprockets-rails 3.5.0 (was 3.4.2)
Bundle updated!
$ git diff
diff --git a/Gemfile.lock b/Gemfile.lock
index 97b682f4ef..281e3180a8 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -546,9 +546,9 @@ GEM
     sprockets (4.2.1)
       concurrent-ruby (~> 1.0)
       rack (>= 2.2.4, < 4)
-    sprockets-rails (3.4.2)
-      actionpack (>= 5.2)
-      activesupport (>= 5.2)
+    sprockets-rails (3.5.0)
+      actionpack (>= 6.1)
+      activesupport (>= 6.1)
       sprockets (>= 3.0.0)
     sqlite3 (2.0.0)
       mini_portile2 (~> 2.8.0)
$ bin/test test/application/test_runner_test.rb:509
Run options: --seed 56216

# Running:

F

Failure:
ApplicationTests::TestRunnerTest#test_multiple_tests_on_same_line [test/application/test_runner_test.rb:523]:
Expected /first/ to match "/home/yahonda/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/sprockets-rails-3.5.0/lib/sprockets/railtie.rb:129:in `block in <class:Railtie>': undefined method `deprecator' for module Sprockets::Rails (NoMethodError)\n\n      app.deprecators[:sprockets_rails] = Sprockets::Rails.deprecator if app.respond_to?(:deprecators)\n                                                          ^^^^^^^^^^^\nDid you mean?  deprecate\n\tfrom /home/yahonda/src/github.com/rails/rails/railties/lib/rails/initializable.rb:32:in `instance_exec'\n\tfrom /home/yahonda/src/github.com/rails/rails/railties/lib/rails/initializable.rb:32:in `run'\n\tfrom /home/yahonda/src/github.com/rails/rails/railties/lib/rails/initializable.rb:61:in `block in run_initializers'\n\tfrom /home/yahonda/.rbenv/versions/3.3.2/lib/ruby/3.3.0/tsort.rb:231:in `block in tsort_each'\n\tfrom /home/yahonda/.rbenv/versions/3.3.2/lib/ruby/3.3.0/tsort.rb:353:in `block (2 levels) in each_strongly_connected_component'\n\tfrom /home/yahonda/.rbenv/versions/3.3.2/lib/ruby/3.3.0/tsort.rb:434:in `each_strongly_connected_component_from'\n\tfrom /home/yahonda/.rbenv/versions/3.3.2/lib/ruby/3.3.0/tsort.rb:352:in `block in each_strongly_connected_component'\n\tfrom /home/yahonda/.rbenv/versions/3.3.2/lib/ruby/3.3.0/tsort.rb:350:in `each'\n\tfrom /home/yahonda/.rbenv/versions/3.3.2/lib/ruby/3.3.0/tsort.rb:350:in `call'\n\tfrom /home/yahonda/.rbenv/versions/3.3.2/lib/ruby/3.3.0/tsort.rb:350:in `each_strongly_connected_component'\n\tfrom /home/yahonda/.rbenv/versions/3.3.2/lib/ruby/3.3.0/tsort.rb:229:in `tsort_each'\n\tfrom /home/yahonda/.rbenv/versions/3.3.2/lib/ruby/3.3.0/tsort.rb:208:in `tsort_each'\n\tfrom /home/yahonda/src/github.com/rails/rails/railties/lib/rails/initializable.rb:60:in `run_initializers'\n\tfrom /home/yahonda/src/github.com/rails/rails/railties/lib/rails/application.rb:430:in `initialize!'\n\tfrom /home/yahonda/src/github.com/rails/rails/tmp/d20240607-53351-fbrlsw/app/config/environment.rb:5:in `<top (required)>'\n\tfrom /home/yahonda/src/github.com/rails/rails/tmp/d20240607-53351-fbrlsw/app/test/test_helper.rb:2:in `require_relative'\n\tfrom /home/yahonda/src/github.com/rails/rails/tmp/d20240607-53351-fbrlsw/app/test/test_helper.rb:2:in `<top (required)>'\n\tfrom /home/yahonda/.rbenv/versions/3.3.2/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'\n\tfrom /home/yahonda/.rbenv/versions/3.3.2/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'\n\tfrom /home/yahonda/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'\n\tfrom /home/yahonda/src/github.com/rails/rails/tmp/d20240607-53351-fbrlsw/app/test/models/account_test.rb:1:in `<top (required)>'\n\tfrom /home/yahonda/.rbenv/versions/3.3.2/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'\n\tfrom /home/yahonda/.rbenv/versions/3.3.2/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'\n\tfrom /home/yahonda/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'\n\tfrom /home/yahonda/src/github.com/rails/rails/railties/lib/rails/test_unit/runner.rb:61:in `block in load_tests'\n\tfrom /home/yahonda/src/github.com/rails/rails/railties/lib/rails/test_unit/runner.rb:60:in `each'\n\tfrom /home/yahonda/src/github.com/rails/rails/railties/lib/rails/test_unit/runner.rb:60:in `load_tests'\n\tfrom /home/yahonda/src/github.com/rails/rails/railties/lib/rails/test_unit/runner.rb:52:in `run'\n\tfrom /home/yahonda/src/github.com/rails/rails/railties/lib/rails/commands/test/test_command.rb:33:in `perform'\n\tfrom /home/yahonda/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/thor-1.3.0/lib/thor/command.rb:28:in `run'\n\tfrom /home/yahonda/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/thor-1.3.0/lib/thor/invocation.rb:127:in `invoke_command'\n\tfrom /home/yahonda/src/github.com/rails/rails/railties/lib/rails/command/base.rb:178:in `invoke_command'\n\tfrom /home/yahonda/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/thor-1.3.0/lib/thor.rb:527:in `dispatch'\n\tfrom /home/yahonda/src/github.com/rails/rails/railties/lib/rails/command/base.rb:73:in `perform'\n\tfrom /home/yahonda/src/github.com/rails/rails/railties/lib/rails/command.rb:71:in `block in invoke'\n\tfrom /home/yahonda/src/github.com/rails/rails/railties/lib/rails/command.rb:149:in `with_argv'\n\tfrom /home/yahonda/src/github.com/rails/rails/railties/lib/rails/command.rb:69:in `invoke'\n\tfrom /home/yahonda/src/github.com/rails/rails/railties/lib/rails/commands.rb:18:in `<top (required)>'\n\tfrom /home/yahonda/.rbenv/versions/3.3.2/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'\n\tfrom /home/yahonda/.rbenv/versions/3.3.2/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'\n\tfrom /home/yahonda/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'\n\tfrom bin/rails:4:in `<main>'\n".


bin/test test/application/test_runner_test.rb:509



Finished in 3.268812s, 0.3059 runs/s, 0.6118 assertions/s.
1 runs, 2 assertions, 1 failures, 0 errors, 0 skips
$
```

### System configuration
**Rails version**: main branch

**Ruby version**: ruby 3.3.2 (2024-05-30 revision e5a195edf6) [x86_64-linux]

### PR DESCRIPTION
**Pull request by casperisfine**
Ref: https://github.com/rails/sprockets-rails/issues/524
Fix: https://github.com/rails/rails/issues/52038

### CODE REVIEW

**Comment by casperisfine** [comment]
Ok, so it's failing with:
```
Could not find gem 'sprockets-rails' in locally installed gems.
Run `bundle install` to install missing gems.
Could not find gem 'sprockets-rails' in locally installed gems.
Run `bundle install` to install missing gems.
E
```

So I think it might just be because the gem is used as a git gem. I'll try cutting a 3.5.1 🤞 

cc @yahonda

**Review by zzak — COMMENTED** [review]
Looks like it worked, could you rebase out the other `Gemfile.lock` changes?
That way I think we can backport it easier.

**Comment by casperisfine** [comment]
It's just a bundle update, I can handle the stable branches.

**Comment by casperisfine** [comment]
Also stable branch don't need a fix cause they didn't update in the first place.

**Pull request merged**
