### PR TITLE
Update redis.rb

### PR DESCRIPTION
**Pull request by benglewis**
Add support for passwords to the default redis_connector.

### Summary

Provide a general description of the code changes in your pull
request... were there any bugs you had fixed? If so, mention them. If
these bugs have open GitHub issues, be sure to tag them here as well,
to keep the conversation linked together.

### Other Information

If there's anything else that's important and relevant to your pull
request, mention that information here. This could include
benchmarks, or other information.

If you are updating any of the CHANGELOG files or are asked to update the
CHANGELOG files by reviewers, please add the CHANGELOG entry at the top of the file.

Finally, if your pull request affects documentation or any non-code
changes, guidelines for those changes are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#contributing-to-the-rails-documentation)

Thanks for contributing to Rails!

### CODE REVIEW

**Comment by maclover7** [comment]
Hi @ukblewis! Are you able to provide some more information about why you are making this change? In your app, are you not able to include the password in the Redis url?

**Comment by ukblewis** [comment]
Whoops. Didn't mean to close this there.

Yes - we are using RedisLab's (the guys who maintain Redis itself) cloud Redis hosted on AWS and it appears that their password won't work in the URL. Quite frankly, I also think that it is an awful idea encoding the Redis password in the URL - it means that failures to connect successfully expose the password in the logs for example.

I spent a few hours trying to get an alternative `redis_connector` accessor to work, but failed, ultimately I ended up patching the `redis_connection` method instead, which I, of course, know isn't a great idea. But it seems like because the Redis subscription adapter isn't loaded until all of the rest of Rails dependencies and all the configuration is loaded, that one cannot actually set the accessor without doing so after Rails loads (which for example, I have no idea how to do in Sidekiq and can't see a neat way to do in Rails and ActionCable - the only solution that I found that work other than patching the `redis_connection` method was to assign `redis_connector` in the `config.ru` file loaded by the Rack application host (Puma).

I am very open to suggestions!

**Comment by ukblewis** [comment]
@maclover7 @matthewd Can you please review this?

**Comment by rafaelfranca** [comment]
Thank you for the pull request. a password can be provided in the url itself.

**Comment by ukblewis** [comment]
@rafaelfranca Excuse me?

I believe that it should be obvious to those who have any experience in security that storing a password in a URL is a bad idea. Especially once you consider that the URL is often put into the log output for debugging purposes, while no one would suggest that we should be logging our passwords.

I am extremely disappointed that after two months, a simple one line pull request that adds a feature that seems like it is of obvious benefit is rejected without a sane reason even after I gave explanation as to the need for it several times. Furthermore, if the `cattr_accessor` actually functioned, then this wouldn't even be essential, but Rails has written this feature in such a way that there is simply no convenient way in which to actually set this accessor (since initialize time is too late to set this accessor).

To give you context as to why I opened this pull request, currently we have the following monkey patch initializer in our code base:
```
require(Gem::Specification.find_by_name('actioncable').gem_dir +
        '/lib/action_cable/subscription_adapter/redis.rb')

module ActionCable
  module SubscriptionAdapter
    module ChangedConnection
      def redis_connection
        ::Redis.new({ url: @server.config.cable[:url], password: ENV['REDIS_PASSWORD'], network_timeout: 5 })
      end
    end
  end
end

ActionCable::SubscriptionAdapter::Redis.prepend ActionCable::SubscriptionAdapter::ChangedConnection
```

Yes it is awful. That is why I request that you reconsider this Pull Request.

@dhh Would you support this pull request?
(Considering that I see that you created the cattr_accessor initially.)
P.S. If you do see this, I love Rails, I've been writing code using Rails for more than 3 years now and it has taught me to love Ruby. I am not upset with Rails, but I am concerned if this is the way the Rails core team feels that it is OK to respond to pull requests with rejection without thorough review. Developers take time to open pull requests to contribute to open source projects because they care. If you act in this way, then you will push developers away.

**Pull request closed without merging**
