### PR TITLE
Bump the required Ruby version to 3.1.0

### PR DESCRIPTION
**Pull request by byroot**
Until now, Rails only droped compatibility with older rubies on new majors, but I propose to change this policy because it causes us to either keep compatibility with long EOLed rubies or to bump the Rails major more often, and to drop multiple Ruby versions at once when we bump the major.

In my opinion it's a bad alignments of incentives. And we'd be much better to just drop support in new minors whenever they go EOL (so 3 years).

Also Ruby being an upstream dependency, it's not even a semver violation AFAICT.

Since Rails 7.2 isn't planned before a few months, we can already drop Ruby 3.0 as it will be EOL in March.

FYI @matthewd since I think I remember you having opinions about this.

### CODE REVIEW

**Comment by zzak** [comment]
CI is failing because I think you missed the `rails.gemspec`:
https://github.com/byroot/rails/blob/bump-required-ruby/rails.gemspec#L12

Which is what we use to determine the minimum supported ruby version:
https://github.com/rails/buildkite-config/blob/main/pipeline-generate#L36C22-L36C23

This is where we select the images to use:
https://github.com/rails/buildkite-config/blob/main/pipeline-generate#L72

**Comment by matthewd** [comment]
Yeah, I agree we should do this. Once upon a time it was more disruptive, because Rubygems/Bundler couldn't account for ruby versions during resolution, and so could settle on a version of a gem that would then not work once installed. But that time is no more.

Dropping upstream-unsupported rubies regularly gives users a clearer upgrade path if doing a long catch-up, by better communicating a range of versions that the given Rails version actually spends most of its life running on. No-one should be running Rails 7.1 on now-EOL Ruby 2.7 today, let alone doing so with 7.2 when it's released.

> Since Rails 7.2 isn't planned before a few months, we can already drop Ruby 3.0 as it will be EOL in March.

I'm inclined to push one version further forward than that, even, and cut off any version that's in security-only mode at the time of our release (as a general policy, regardless of whether a specific version boundary gives us compelling syntax etc). That's what we've done previously when updating it in majors. But I do also feel less strongly about the _need_ to be that strict if we're revising our minimum more often than once every 2-3 years.

(My "that's unreasonable" floor, for comparison, is that any Rails release should support [the now-current patch release of] the version of Ruby that was the latest/current available 12 months earlier.)

**Comment by zzak** [comment]
Was looking at 6487836af8 for inspiration and also opened byroot/rails#2 to cover the version checker and other relevant docs. :pray:

**Comment by skipkayhil** [comment]
> to cover the version checker

I'm curious if we still need this. It feels like a remnant of having to address the problems with RubyGems/Bundler that Matthew mentioned above.

**Comment by zzak** [comment]
> > to cover the version checker
> 
> I'm curious if we still need this. It feels like a remnant of having to address the problems with RubyGems/Bundler that Matthew mentioned above.

I didn't actually look into the purpose of that file, just looking for the most recent ruby version bump last night. Now that you mention it though, that does seem like an accurate assessment: https://github.com/rails/rails/blame/391f2543c96a9b3de4e44f4ea6aeee2f53ad9e5c/railties/bin/rails#L5

**Comment by byroot** [comment]
> But I do also feel less strongly about the _need_ to be that strict if we're revising our minimum more often than once every 2-3 years.

Yeah, that's my whole point. If we drop more regularly we avoid the need to drop so many at once. Right now I don't see anything in 3.1 that would make our life harder, so I'm not very inclined to drop it. But we can always change our mind before the release if we run into something, it's much easier to drop compatibility than to restore it.

**Comment by byroot** [comment]
Alright, since Matthew has no objections, I'll merge now, might as well reduce CI load while we're at it :)

**Pull request merged**
