### PR TITLE
Delay asserting configured name and password options when Basic HTTP Authentication is conditionally configured

### LINKED ISSUE #45350: #http_basic_authenticate_with breaks in edge case with env vars
Hello! I've encountered an edge case with our basic auth setup after the latest Rails updade, specifically this change: https://github.com/rails/rails/commit/9ebfb149ed362697c042bb030bddcb3ba2fceb97 .

As you can see below in the script, we have a setup where basic auth is enabled via ENV variables (on staging, for example) but is also configurable on a per-controller, per-request basis in some subcontrollers.

The newly added check for the user/pass to be a String raises the exception `Expected name: to be a String, got NilClass` in some cases, like on production, as there is no user/pass. The check is good in principle but basically happening too early as it only becomes relevant in our case after the optional :if clause is applied.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
end

require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get "/" => "test#index"
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  http_basic_authenticate_with(
    name: ENV['HTTP_BASIC_AUTH_NAME'],
    password: ENV['HTTP_BASIC_AUTH_PASSWORD'],
    if: -> { auth_credentials_present? && !skip_http_basic_authentication? }
  )

  def index
    render plain: "Home"
  end

  private

  def auth_credentials_present?
    ENV['HTTP_BASIC_AUTH_NAME'].present? && ENV['HTTP_BASIC_AUTH_PASSWORD'].present?
  end

  # to be overwritten in subclasses
  def skip_http_basic_authentication?
    false
  end
end

require "minitest/autorun"
require "rack/test"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_returns_success
    get "/"
    assert last_response.ok?
  end

  private
    def app
      Rails.application
    end
end

```

### System configuration
**Rails version**: 7.0.3

**Ruby version**: 3.1.2

### PR DESCRIPTION
**Pull request by fatkodima**
Closes #45350.

cc @byroot since you implemented the changes mentioned in that bug report.

### CODE REVIEW

**Comment by byroot** [comment]
Hum, I'm not a fan of this. We introduced this check to catch mistakes early, it would be a bit bad to lose it.

I wonder if OP shouldn't just call `to_s` on these ENV variables to acknowledge that they might be missing.

cc @matthewd what do you think?

**Comment by skipkayhil** [comment]
I agree that pushing the error to runtime seems like an easy footgun.

I think the controller in the original issue could be modified to conditionally define `http_basic_authenticate_with`
```ruby
class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def self.auth_credentials_present?
    ENV['HTTP_BASIC_AUTH_NAME'].present? && ENV['HTTP_BASIC_AUTH_PASSWORD'].present?
  end

  http_basic_authenticate_with(
    name: ENV['HTTP_BASIC_AUTH_NAME'],
    password: ENV['HTTP_BASIC_AUTH_PASSWORD'],
    if: -> { !skip_http_basic_authentication? }
  ) if self.auth_credentials_present?

  def index
    render plain: "Home"
  end

  private

  # to be overwritten in subclasses
  def skip_http_basic_authentication?
    false
  end
end
```

**Comment by fatkodima** [comment]
The `to_s` approach is the way to go for OP, I think, despite it looks a tiny little bit hacky, from my POV.
Another approach works too in this case, but I think it will not work if authentication is dynamically decided via some feature flag, for example, because `if self.auth_credentials_present?` is executed only once.

> We introduced this check to catch mistakes early, it would be a bit bad to lose it.

I think it will not be "a bit bad", but disastrous to successfully deploy and restart the whole app and after the first request to find out that the env variable is missing. 😄 

Thank you guys, that was an oversight from my side 🙈 

@MGPalmer Will the suggestions work for you?

**Comment by MGPalmer** [comment]
@fatkodima Thank you and everyone and sorry for the late response. Your suggestions are much appreciated and no changes are needed I think. For posterity, this is what we now ended up with (we moved the whole thing to a concern, too):

```
module HttpBasicAuth
  extend ActiveSupport::Concern

  included do
    http_basic_authenticate_with(
      # Need to provide a fallback string as the method checks for nil
      name: basic_auth_name || 'bogus',
      password: basic_auth_password || 'bogus',
      if: -> { auth_credentials_present? && !skip_http_basic_authentication? }
    )
  end

  module ClassMethods
    def basic_auth_name
      ENV.fetch('HTTP_BASIC_AUTH_NAME', nil)
    end

    def basic_auth_password
      ENV.fetch('HTTP_BASIC_AUTH_PASSWORD', nil)
    end
  end

  private

  def auth_credentials_present?
    self.class.basic_auth_name.present? && self.class.basic_auth_password.present?
  end

  def skip_http_basic_authentication?
    false
  end
end
```

I still think the "fallback"/"to_s" approach is pretty ugly, adding bogus values when they are not needed doesn't feel clean to me.
But we first tried to move this part to class-level and that was fine - but it turns out that that is really hard to test programmatically as there is no good way to reload the controller during tests/specs AFAIK. So we went back to this which is good enough for me (tm). Thanks!

**Pull request closed without merging**
