### PR TITLE
Enhance add_reference on sqlite3 to create foreign keys

### PR DESCRIPTION
**Pull request by lostapathy**
Currently, add_reference on sqlite3 does not add the new column correctly to be a foreign key (failing test in first commit).  

SQLite is able to add foreign keys in a way that matches add_reference, so I've taken a shot at implementing that.  

There may be a better way to accomplish this, but I'll offer this as a working start.  Thanks!

### CODE REVIEW

**Comment by sgrif** [comment]
Thanks for the pull request! It looks like this implementation affects old versions as well. This pull request will need an addition to `migration/compatibiltiy.rb` to make sure it doesn't affect old versions. Was there any mention in the original commits/PRs for this feature as to why SQLite was excluded here?

**Comment by sgrif** [comment]
Also the test failures are definitely legitimate and will need to be addressed

**Comment by lostapathy** [comment]
Thanks @sgrif.  I couldn't find anything to explain why this wasn't done originally, or explain what I found on #31332 either.  I was surprised there don't seem to be any tests for `add_relation` with `foreign_key: true`

I am working on the test failures, will tpush those when I can and look at `migration/compatibiltiy.rb` as well.  Thanks for the tip on that.

**Comment by matthewd** [comment]
To save anyone some digging, relevant context is: #15606, 99a6f9e60ea55924b44f894a16f8de0162cf2702, #24743

**Comment by lostapathy** [comment]
Thanks @matthewd - if I'm parsing that correctly, it sounds like sqlite was known to be "a different beast" when foreign keys were added, and we just continue to chip away at implementing what we can. I'm hoping this PR continues that spirit.

@sgrif I have added a test in `migration/compatibility_test.rb` and added compatibility code to make it pass, but please review that carefully. I'm not 100% sure I understand the spirit of all that code.  Thanks for pointing that out.

**Pull request closed without merging**
