### PR TITLE
Provide a default Content Security Policy (CSP) that is lenient yet secure

### PR DESCRIPTION
**Pull request by oreoshake**
### Summary

This is not a new idea, ["Add Content Security Policy(CSP)"](https://github.com/rails/rails/pull/15777) has been proposed but seems to be stuck in analysis paralysis. Perfect being the enemy good, here's an alternate proposal solving a slightly different problem. Rather than a general solution, this PR proposes a generic CSP that may work for most applications.

Building on the concept of `default_headers`, it would be great if CSP was applied by default. This is mostly geared towards new applications. Unfortunately, making this "report only" will generate a warning in the console since the policy, understandably, lacks a report-uri value. Adding a default report-uri realistically would require adding a CSP reporting endpoint to rails by default. Perhaps it could use the [middleware @xuchu provided](https://github.com/rails/rails/pull/15777/files#diff-3415f63beb241431931eca170e854079).

**Because of these factors, applying the potentially breaking header probably better suited as part of a generator script for new applications but I don't know the cleanest way of accomplishing this.**

In past lives (e.g. Twitter scala applications), applying CSP by default had amazing returns. CSP adoption and awareness went from "wat"/"meh" to "this is useful". The suggested policy should work for most applications and the browser console literally tells you what modifications need to be made. Brand new applications do not produce any violations. Adding code that violates this policy could be caught early on and people can choose to work within the suggested boundaries or they can decide to modify the policy. Naturally, there will be those who disable the policy entirely. That is entirely up to them but at least some thought will be put into it.

This is a bit contentious, of course.
### Other Information

Needs tests, but I wanted to wait for a better integration point before I write tests I know I'm going to throw away.

[An Introduction to Content Security Policy](http://www.html5rocks.com/en/tutorials/security/content-security-policy/)
[GitHub's CSP Journey](http://githubengineering.com/githubs-csp-journey/)

> Thanks for contributing to Rails!

No, no, no. Thank _you_ Rails!

### CODE REVIEW

**Comment by rafaelfranca** [comment]
@sgrif lol. I was about to assign to me.

I like the idea and I agree we should not aim perfection. I'll review it.

**Comment by sgrif** [comment]
@rafaelfranca I'm in your head. ;)

:+1: on this proposal from me FWIW

**Comment by maclover7** [comment]
Can you add some documentation explaining CSP?

**Comment by oreoshake** [comment]
@maclover7 glad to. However, I'd prefer to hold off until we know where the application will end up as there may be different context available. e.g. an explanation in the `default_headers` context may be entirely different than where it lives in a generator. For now, I hope that the "Other Information" section will suffice for the purposes of moving this PR along.

**Comment by maclover7** [comment]
👍 

My recommendation is that we stick the CSP config in `config/environments/*.rb`, or in an initializer. If this/when this ships, there should definitely be a big red off button, in case people don't want it 😬  (opt-out, not opt-in -- Rails is providing good security protection here 😄)

**Comment by vipulnsward** [comment]
@maclover7 this can be achieved by removing the header, by specifying a custom one on `config.action_dispatch.default_headers`. AFAIK, this doesn't need to live in another config, just like `XSS-Protection` or  `Frame-Options` are our default, and not as options.

**Comment by oreoshake** [comment]
@vipulnsward I think making this a default header is probably a bad idea since it will break any application using risky behaviors. It should only be a default for *newly* generated applications.

Although introducing this as a breaking change for the next major version is an interesting idea...

**Comment by maclover7** [comment]
Unfortunately, the "breaking change boat" for 5.0 has left the dock, and we are in the feature freeze right for 5.0 (so no breaking changes 😢)

@vipulnsward I was more asking about whether, for example, we could have a nice API for configuring the `font-src` or `script-src` (or whatever) for end users through another application configuration option. Providing a hash of defaults is super helpful (and an awesome baseline of security protection for end users), but we have to provide (and document of course 😉) a nice way to change things around too (and an opt-out route too) 😬

**Comment by oreoshake** [comment]
> @oreoshake Unfortunately, the "breaking change boat" for 5.0 has left the dock, and we are in the feature freeze right for 5.0 (so no breaking changes 😢)

Yeah, that's what I figured. But rails 6.0 will be a thing! Maybe then it could be a `default_header`? But for the sake of not spamming this issue, that's the last I'll mention this idea 😸

**Comment by rafaelfranca** [comment]
@maclover7 @vipulnsward I recommend you to check https://github.com/rails/rails/pull/15777.

**Comment by rafaelfranca** [comment]
@chancancode @kaspth @jeremy mind to take a look in the idea? I'm positive to it as new default in generated applications.

**Comment by nateberkopec** [comment]
I don't think this moves forward on @chancancode's objection to the previous CSP PR (which I agree with):

> Regarding the API, I think application wide config.*is the wrong direction. Unlike HSTS which is a domain policy, CSP is a content policy. It could vary on different parts of your app and should differ for the content type.

Also second @maclover7 in that this particular PR's approach would be far too difficult to modify or turn off.

## Spitballing

IMO the ideal API looks more like how CSRF protection works today - it should live in ApplicationController, and have a scary-ish name that makes it clear that "if you comment this out, you are Doing Something Dangerous!" It should also use a Hash-based API for easy modification of just a few settings. 

```ruby
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  # Rails takes care of transforming this into a CSP policy string
  def content_security_policy
    {
      "default-src": %w[self https],
      "font-src": %w[self https data],
      "img-src": %w[self https data],
      "object-src": %w[none],
      "script-src": %w[self https],
      "style-src": %w[self https unsafe-inline]
    }
  end
end

class MyInsecureController < ApplicationController

  private

  def content_security_policy
    {
      "default-src": %w[self]
    }
  end
end

class MyControllerWithAdditionalTrustedOrigin < ApplicationController

  private

  # Append a trusted origin to all directives, not sure if this actually works but you get the idea
  def content_security_policy
    policy = super

    policy.each_with_object({}) do |memo, (k,ary)|
      ary << "*.mytrustedorigin.com"
      memo[k] = ary
    end
  end
end
```

`content_security_policy` should probably be an empty Hash by default, to make this backwards-compatible and only something added to newly generated Rails apps.

**Comment by jeremy** [comment]
I agree with the motivation and I'm sympathetic to the perfection-as-enemy-of-the-good perspective, but this is an arena that deserves a pretty high bar to introduce an important, far-reaching new concept to Rails users.

The approach is clear: per-resource policy. We're blocked on implementation interest & effort. Really, the major push is documentation and communication. Per-controller declarative policy is straightforward to implement in comparison to writing up a fantastic CSP guide.

https://github.com/rails/rails/pull/15777 has the essential implementation in place. It needs documentation and implementation polish, and default policy guidance for new apps.

**Comment by connorshea** [comment]
@jeremy I'd be happy to help out with the Content Security Policy guide if we're still willing to go forward with #15777. I've made a (admittedly non-comprehensive) [CSP writeup](https://gitlab.com/gitlab-org/gitlab-ce/issues/18231) when I pitched the addition of CSP headers for GitLab.

While the initial attempt to add the headers ran into some roadblocks I still fully intend to ship it in the next few months.

**Comment by kaspth** [comment]
@connorshea we need someone to kickstart a guide to move forward with #15777 — you seem like just the guy to do it! I skimmed your referenced write up, it seems like a fine place to open a pull request and discuss further. Do take a stab at it! ❤️

> Between us and the fantastic information GitHub, Twitter, and Dropbox have published about their experiences with CSP I'm sure we can put something very useful together :)

Concurred 🤘

**Comment by connorshea** [comment]
@kaspth Should I make a PR on top of #15777 or have it be separate?

**Comment by nateberkopec** [comment]
@connorshea happy to help with any revision/proofreading on that

**Comment by kaspth** [comment]
@connorshea let's try it separately. I'll petition the student who worked on the implementation to see if he wants to pick it up again.

**Comment by kaspth** [comment]
@connorshea @nateberkopec 👋, did any of you make some headway on a CSP guide? 😁

**Comment by connorshea** [comment]
@kaspth unfortunately I haven't had time recently.

**Comment by kaspth** [comment]
@connorshea no worries 😉

**Comment by bpo** [comment]
In #27583 it was proposed to merge secureheaders into core to address this. A few technical details got in the way:

* secureheaders does not have a very Rails-y API, and is not a great candidate for becoming a part of the core Rails codebase as it stands.
* secureheaders' license conflicts with the Rails MIT license.
* Effort was expended in 2014 toward cleanly implementing CSP support within ActionPack.

The first concern was addressed within the issue – @rafaelfranca [suggested](https://github.com/rails/rails/issues/27583#issuecomment-270770400) that the secureheaders gem become a part of the rails project, and generate the application with a call to that gem and a new initializer.

@oreoshake was nice enough to do the legwork to get [secureheaders re-licensed under MIT](https://github.com/twitter/secureheaders/pull/315), addressing the second concern.

As for the last concern, the effort in #15777 is not mutually exclusive with adding secureheaders to Rails. It may unstick this 2+ year process if the API (and docs) are developed alongside the other best-practices for security provided by secureheaders (HPKP, XFO, etc).

As it stands, someone who wants to secure a new Rails app *should* use secureheaders today – so why not make that the default starting point?

(I'd like to help with this if it seems like a reasonable approach.)

**Comment by kaspth** [comment]
Superseded by https://github.com/rails/rails/pull/31162

Thanks for the PR! ❤️

**Comment by oreoshake** [comment]
I have never been happier to see a PR of mine get closed unmerged :smile:

**Pull request closed without merging**
