### PR TITLE
[ci skip] Update Rails Guides reviewer's URL

### PR DESCRIPTION
**Pull request by yhirano55**
### Summary

I found wrong url exists in rails guide's reviewer's introduction. So I've fixed them. It seems http://www.actionrails.com is dead link, and I removed the anchor.

### CODE REVIEW

**Comment by kaspth** [comment]
Thanks!

@fxn how many of these are still valid to include though? Far as I know, there have been many other authors since and these haven't been active on guides in years.

Perhaps we should do an alumni section that's just names/links akin to the alumni section on http://rubyonrails.org/community/

Also, the credits link doesn't seem to work on http://edgeguides.rubyonrails.org. But perhaps that's intentional 😊

**Comment by fxn** [comment]
@kaspth I would prefer to delete this page, actually.

There are a few reasons, for example, a guide is written, but then also maintained, to be fair everyone should be mentioned there as a contributor and that is difficult to manage. But most importantly, to me there is no difference between contributing to the guides, to the API, or to the code. Everything is the same to me, we do not have a page like this for people writing patches with code.

I believe that Rails Contributors is our place to give credit to all contributors to the Rails code base, and their personal pages there show their work. If someone wants to know who wrote a guide, or who wrote file uploading, or Active Model attributes, `git log` is the suitable tool for that.

@vijaydev what do you think?

**Comment by kaspth** [comment]
@fxn 👍 on removing the page — I was surprised we even had one!

**Comment by yhirano55** [comment]
Opened #32429 instead of this PR.

**Pull request closed without merging**
