### PR TITLE
Add NOT NULL constraint by default for references

### PR DESCRIPTION
**Pull request by andreynering**
changes:

``` ruby
create_table :comments do |t|
  t.references :posts, index: true, foreign_key: true
end
```

to:

``` ruby
create_table :comments do |t|
  t.references :posts, index: true, foreign_key: true, null: false
end
```

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Thank you for the pull request.

If you want not null to be generated you have to use the `required` option.

**Comment by andreynering** [comment]
@rafaelfranca Note that the constraint would be added just for `references`, not all columns.

If index and foreign keys is being generated by default, why not `NOT NULL`? It is what people want in most cases.

**Comment by rafaelfranca** [comment]
If the references is required, yes make sense to add the `NOT NULL`.

This is why it already does when you use `author:references{required}`

**Comment by andreynering** [comment]
OK :+1:

**Pull request closed without merging**
