### PR TITLE
Remove dead test code for unsupported adapters

### PR DESCRIPTION
**Pull request by kamipo**
Related #15137.

Firebird related code is already removed in #15137.

We have two `current_adapter?(:DB2Adapter)` in tests, but the adapter is
no longer maintained (last release is November 15, 2012).

https://rubygems.org/gems/db2

Yet another (latest) DB2 adapter (`IBM_DBAdapter`) might support Rails
5.0.7, but apparently do not work for Rails 5.2.

https://rubygems.org/gems/ibm_db

We have few lines mention about DB2 in the doc, but now there is no
worth for almost all current users.

### CODE REVIEW

**Comment by eugeneius** [comment]
There's some support code in the repo for testing against the ibm_db gem:

https://github.com/rails/rails/blob/9176c362a66d2c9f3e6adce6fb7ffbaf93045002/Gemfile#L165-L166

https://github.com/rails/rails/blob/9176c362a66d2c9f3e6adce6fb7ffbaf93045002/activerecord/test/config.example.yml#L38-L50

https://github.com/rails/rails/blob/9176c362a66d2c9f3e6adce6fb7ffbaf93045002/activerecord/Rakefile#L50
https://github.com/rails/rails/blob/9176c362a66d2c9f3e6adce6fb7ffbaf93045002/activerecord/Rakefile#L53
https://github.com/rails/rails/blob/9176c362a66d2c9f3e6adce6fb7ffbaf93045002/activerecord/Rakefile#L66

Do you think it's worth keeping? It seems unlikely that the suite passes, given e.g. the case sensitivity test being touched here.

**Comment by kamipo** [comment]
Good catch. I'd like to remove generator support for frontbase and ibm_db too if there is no objection, since both adapters do not work for Rails 5.2, keeping those in Rails code base is mostly no worth for almost all current (and future) users.

**Review by eugeneius — APPROVED** [review]

**Comment by yahonda** [comment]
How about removing Arel code https://github.com/rails/rails/blob/master/activerecord/lib/arel/visitors/ibm_db.rb ?

**Comment by kamipo** [comment]
Good point. Currently we have some Arel visitors (dot, ibm_db, informix, and mssql) which are not used in the code base, I intentionally didn't touch Arel code since I'd like to disscuss about removing unused Arel visitors in a separate PR.

**Comment by yahonda** [comment]
Understood and agreed that discussing Arel visitors in another separate pull request.

**Review by rafaelfranca — APPROVED** [review]

**Pull request merged**
