### PR TITLE
Supports BMP file format and converts it into png for variants

### PR DESCRIPTION
**Pull request by zealot128**
### Summary

Currently, AS fails to generate variants for bmp files with a ActiveStorage::Invariable Exception. Imagemagick supports bmp right out of the box, so just adding it into the whitelist supported file type list seems to be enough. 

I've just taken the racecar.jpg and converted it into bmp for testing purposes.

### CODE REVIEW

**Comment by georgeclaghorn** [comment]
Is there a particular reason for converting to PNG? If not, we can add the BMP content types to [`ActiveStorage::Variant::WEB_IMAGE_CONTENT_TYPES`](https://github.com/rails/rails/blob/11581afc01927565d57dd0e0156e983f92f8c2e0/activestorage/app/models/active_storage/variant.rb#L56) to store and serve BMP variants.

**Comment by zealot128** [comment]
@georgeclaghorn locally, I've went with this first: also adding bmp to that array. But I found bmp to be a very inefficient file format and the variant files needlessly large as there is no compression at all. 
A png will get us "free" bandwidth, it's also lossless in standard settings. I can not think of a downside, why you would want to serve the user a bmp at all -> thus should be the default IMO. 

If the user want's to serve a bmp they can just pass a ``format: 'bmp'`` option to the variant call, right?

**Comment by georgeclaghorn** [comment]
On second thought, libvips doesn’t support BMP out of the box, so I’m not sure we should do this. You’re free to modify `config.active_storage.variable_content_types` in your app as you see fit.

**Comment by zealot128** [comment]
ok, in that case, we can close this PR.

For documentation and Googler's:

Adding to an initializer to enable Windows BMP variant generation:

```ruby
Rails.application.configure do
  config.active_storage.variable_content_types += %w[
      image/x-ms-bmp
      image/x-bmp
      image/bmp]
end
```

Variants will be converted by default to png. To force a conversion to another format (keeping bmp or jpg), either pass the format parameter to the variant:

```ruby
my_object.attachment.variant(resize: '200x200>', format: 'bmp')
```

Or add bmp to the list of "web safe" formats:

```ruby
ActiveStorage::Variant::WEB_IMAGE_CONTENT_TYPES+= %w[image/bmp image/x-bmp image/x-ms-bmp]
# this will generate a constant reassigned warning though...
```

**Pull request closed without merging**
