### PR TITLE
 [ci skip] Remove duplicate example.

### PR DESCRIPTION
**Pull request by aditya-kapoor**

### CODE REVIEW

**Comment by vipulnsward** [comment]
Thanks

**Comment by prathamesh-sonpatki** [comment]
They are not same  examples.

**Comment by vipulnsward** [comment]
They mean/work the same, but yes I agree both should exist.

**Comment by aditya-kapoor** [comment]
@vipulnsward where can i find the implementation of #select method for the `CollectionProxy` as my intention was to move it there...

I didn't had the intention to remove the doc stuff... 😢

**Comment by prathamesh-sonpatki** [comment]
It is removed in https://github.com/rails/rails/pull/25989

**Pull request merged**
