### PR TITLE
Doc: Specify using db:seed for all environments

### PR DESCRIPTION
**Pull request by bf4**

### CODE REVIEW

**Comment by claudiob** [comment]
Hello @bf4 !

I don't completely understand your change in the documentation.
Could you explain the nature of your change? 

Specifically, you say:

> Data in db/seeds.rb should be usable in all environments.

To clarify this, how is your new example:

```ruby
Brand.create(name: "OurBrand", slug: "our-brand")
```

better than the existing example?

```ruby
5.times do |i|
  Product.create(name: "Product ##{i}", description: "A product.")
end
```

**Comment by bf4** [comment]
@claudiob Thanks for the response. Do you have a feeling for the gist of it? If the PR should be 'never run db:seed in production', then I'll change it to that.

So, `5.times {|i| Product.create(name: "Product ##{i}", description: "A product.") }` is obviously dummy data.  So, I was trying to think of data that you'd want in every environment from my experience.  Here's a couple of examples:

- Cities
- GIS data e.g. from localeze
- Roles
- Permissions
- Positions
- Business regions
- Product Types
- Merchant Account / Gateway stuff (configured by env)
- Maybe certain user accounts for demo, business, qa, etc

or any other business-specific data that is always needed and doesn't really change.

**Comment by claudiob** [comment]
Ok, so I think you are touching on two different aspects here.

---

The first aspect is that you'd like to change the generic "Product" with something that is a more common case for seeding the database. For instance, in my personal apps, I commonly use db/seeds.rb to create a User or an Admin.

Is it worth changing the documentation? Maybe… however I don't think `Brand.create(name: "OurBrand", slug: "our-brand")` is much more common the current `Product.create`. So maybe we could find an even better example. Or eventually leave it as it is. Let me know if you can find a better example.

---

The second aspect is that you want to make clear that `rake db:seed` can be run in every environment. I don't think there's any confusion about that in the current documentation. The lines before your change say:

> However, Rails has a 'seeds' feature that should be used for seeding a database with initial data. It's a really simple feature: just fill up `db/seeds.rb` with some Ruby code, and run `rake db:seed`:

Since there is no mention of environment, I don't think it's confusing (and leading people to think they can only run this task in development).

**Comment by bf4** [comment]
I'm happy to update this PR with some more guidance on how the db:seeds docs could be improved.

**Comment by sgrif** [comment]
I agree with https://github.com/rails/rails/pull/20881#issuecomment-121755961 -- I don't think the current docs have any confusion about what environment this command can be run in.

**Comment by bf4** [comment]
Cc @qrush fwiw

Thanks for following up

B mobile phone

**Pull request closed without merging**
