### PR TITLE
[ci skip] Add class method route constraint doc

### PR DESCRIPTION
**Pull request by etdev**
Add an example of using a class method as an advanced route constraint to the routing docs.  This approach avoids instantiating a Constraint object every request, and looks a bit cleaner.

### CODE REVIEW

**Comment by senny** [comment]
I'm not sure this addition to the docs is necessary. In the end, all a constraint has to do is `respond_to?(:matches?)` it's up to the user what object to pass. The docs say:

> If you have a more advanced constraint, you can provide an object that responds to matches? that Rails should use.

**Comment by etdev** [comment]
@senny Thanks for your input, I definitely see your point.  What about just replacing the existing example with my simpler one?

**Comment by senny** [comment]
@etdev I don't think we should replace the example. As I see it, the instance caches the return of `Blacklist.retrieve_ips` which might be an expensive call. Using the instance that code executes only when the app boots up. With the class method approach it'll execute on every request.

**Comment by etdev** [comment]
@senny Alright, fair enough.  Thanks for the input!

**Pull request closed without merging**
