### PR TITLE
Add top level license

### PR DESCRIPTION
**Pull request by dharamgollapudi**
- Add top level license file so that github auto detects the license type
- and displays it in the repository overview section
- More info at https://github.com/blog/2252-license-now-displayed-on-repository-overview

### CODE REVIEW

**Comment by dharamgollapudi** [comment]
While adding the top level license file, I also noticed that all the sub gems included the non github standard license file `MIT-LICENSE` instead of standard file `LICENSE`. Let me know if I should rename those files as part of this pull request, I can update the PR accordingly.

**Comment by maclover7** [comment]
cc @dhh

**Comment by guilleiguaran** [comment]
> While adding the top level license file, I also noticed that all the sub gems included the non github standard license file MIT-LICENSE instead of standard file LICENSE. Let me know if I should rename those files as part of this pull request, I can update the PR accordingly.

I think they're fine as are and we wouldn't gain anything renaming them

**Comment by jeremy** [comment]
Note that `LICENSE` is not a GitHub standard. They use Licensee which attempts to detect the license based on community standards. `MIT-LICENSE` is [supported](https://github.com/benbalter/licensee/pull/16), among many others.

**Comment by dharamgollapudi** [comment]
I didn't know that MIT-LICENSE file naming is supported by `licensee` gem. Thanks for the pointer @jeremy.

In that case, I would propose to keep `MIT-LICENSE` naming through out for consistency, including the top level. Let me know what others think, I will update the PR accordingly.

**Comment by rafaelfranca** [comment]
I'm against to change our structure to please a vendor, even that the vendor is github. Why don't they detect the file insides the framework?

**Comment by jeremy** [comment]
Because components within the framework may be sub-licensed (e.g. a vendored library). Others have asked for a top level license just for full clarity that it applies to the whole git repos, not just the distributed RubyGems.

But… we've [rejected this multiple times before](https://github.com/rails/rails/search?q=license&type=Issues) and nothing's changed except GitHub elevating the license indicator a bit. Recently: #21959.

**Comment by matthewd** [comment]
@rafaelfranca probably for the same reason I'm thinking this could be a good idea: what's the license on the miscellaneous files outside the components? (Most notably, guides.)

The top-level readme states the license by name, so there's no *real* ambiguity, but it does seem avoidably unclear. 

IMO it might be best if we *only* had a file in the repo root, and then the gems arranged to obtain it from there during packaging. There are complications with that, as there so often are.. but to me it seems the neater choice, if we ignore how things currently are. Whether it's worth bothering to *change*, I have no strong opinion.

**Comment by jeremy** [comment]
> IMO it might be best if we only had a file in the repo root, and then the gems arranged to obtain it from there during packaging.

Dig that. 👍

I think it's worth changing even it's just because this is a repetitive "code/repos hygiene" magnet.

**Comment by rafaelfranca** [comment]
👍👍

**Comment by jeremy** [comment]
Up for giving that a shot, @dharamgollapudi? Switch to a single top-level MIT-LICENSE and reference that from the individual gemspecs.

**Comment by dharamgollapudi** [comment]
@jeremy I understood the first part "Switch to a single top-level MIT-LICENSE". Could you elaborate on the second part "reference that from the individual gemspecs."?

Something along the following lines? (from actionmailer.gemspec):

```
#Before:
s.files        = Dir["CHANGELOG.md", "README.rdoc", "MIT-LICENSE", "lib/**/*"]

#After:
license_file = File.expand_path("../../MIT-LICENSE", __FILE__)
s.files        = Dir["CHANGELOG.md", "README.rdoc", "lib/**/*"]
s.files << license_file
```

**Comment by jeremy** [comment]
Yep. RubyGems might be unhappy about referencing a file in a different root dir, though? Give it a shot!

**Comment by dharamgollapudi** [comment]
@jeremy I already looked into that. `rubygems` bundles the file with the whole absolute path directory structure. Not sure if `rubygems` exposes any api to reference files from parent directory. Looking into their documentation.

**Comment by dharamgollapudi** [comment]
@jeremy One option I could think of is copying the `MIT-LICENSE` from root to the sub directories as part of the `.gemspec` files as follows:

```
FileUtils.copy_file("../MIT-LICENSE", "MIT-LICENSE") if File.exist?("../MIT-LICENSE")
```

Then remove `MIT-LICENSE` files from the sub-directories and add them to the `.gitignore`. 

This way, `MIT-LICENSE` is available while building gems.

Let me know your thoughts.

**Comment by jeremy** [comment]
Copying to the subdirs doesn't sound great. Does a symlink work?

**Comment by dharamgollapudi** [comment]
@jeremy: Nope. `rubygems` bundles the symlink as symlink, not the symlinked file.

**Comment by jeremy** [comment]
Too bad. Sounds like this isn't gonna work. Duplicate files isn't really so bad…

**Comment by dharamgollapudi** [comment]
@jeremy we could keep the duplicate files in the sub directories, but this PR is to have a top level MIT-LICENSE so that github could recognize it and add the appropriate info to the overview page. I didn't realize that there were previous PRs regarding the same which got denied. 

Let me know the direction on this PR. Should you guys stand on not adhering to the vendor specifications, feel free to close the PR. Should you decide to have `MIT-LICENSE` just to be consistent with sub directories instead of `LICENSE`, I could update the PR.

**Comment by jeremy** [comment]
I'd like to just add the toplevel MIT-LICENSE and be done with it. @rafaelfranca cool with that? Then we can put this one to bed.

**Comment by dharamgollapudi** [comment]
@jeremy Renamed `LICENSE` to `MIT-LICENSE` for consistency and updated the PR. If @rafaelfranca is cool with the approach, then the PR could be merged.

**Comment by rafaelfranca** [comment]
Thanks!

**Pull request merged**
