### PR TITLE
Fix `Errno::ESPIPE` by `IO#rewind` in `Marshal.load`

### PR DESCRIPTION
**Pull request by aeroastro**
### Summary

Previously, when pipe objects were passed to `Marshal.load`,
`Errno::ESPIPE` were raised during autoloading constants.
This is due to calling `IO#rewind` for pipe objects which cannot be rewound.

Now original exceptions generated by `Marshal.load` are raised
instead of exceptions generated by `IO#rewind`.

This makes errors more developer-friendly.

Current code yields following error for the proposed test.
IMHO, this requires developers to dig into the `core_ext` to find out the
actual cause. If original exception is raised, it is easier for developers to
find out the cause and the workaround.

```
MarshalTest#test_that_Marshal#load_still_raises_original_exception_when_a_pipe_is_passed [/rails/activesupport/test/core_ext/marshal_test.rb:47]:
instead of Errno::ESPIPE.
[ArgumentError] exception expected, not
Class: <Errno::ESPIPE>
Message: <"Illegal seek">
---Backtrace---
/rails/activesupport/lib/active_support/core_ext/marshal.rb:15:in `rewind'
/rails/activesupport/lib/active_support/core_ext/marshal.rb:15:in `rescue in load'
/rails/activesupport/lib/active_support/core_ext/marshal.rb:6:in `load'
/rails/activesupport/test/core_ext/marshal_test.rb:48:in `block (3 levels) in <class:MarshalTest>'
---------------
```

### Other Information

The reason why I did not reimplement all the `Marshal.load` is as follows.

* Follow the similar code handling `Errno::ESPIPE` for `IO#rewind`
    * https://github.com/rails/rails/commit/db885e81b9dc918a75bd66b1631a13e10447d0ff
* Current patch still have a bug for IO-like object which consists of multiple Marshal chunks
    * Calling `IO#rewind` lost the information of previous `IO#pos`
    * I would like to keep the true implementation out of the scope of this patch.

```ruby
io = StringIO.new
Marshal.dump("foo", io)
Marshal.dump(Bar.new, io)
io.rewind

ActiveSupport::Dependencies.clear

foo = Marshal.load(io) # => foo
bar = Marshal.load(io) # => foo
```

### CODE REVIEW

**Comment by pixeltrix** [comment]
@fxn given the changes we're thinking of to autoloading in Rails 6 should we be looking at removing this code anyway? Also should we be looking to see whether we can stat the IO object and check for `pipe?` rather than rescuing and re-raising? I guess the re-raise will be okay since we're only talking about development - in production we shouldn't hit this code (should it be even installed in production?).

**Comment by aeroastro** [comment]
@pixeltrix @fxn
I would love to hear what I can help in my side for this Pull Request.

**Comment by pixeltrix** [comment]
@aeroastro have you tried out the new Zeitwerk autoloader in 6.0.0.beta2 and how that affects this issue? https://weblog.rubyonrails.org/2019/2/22/zeitwerk-integration-in-rails-6-beta-2/

**Comment by aeroastro** [comment]
OK! I will check it.

**Pull request closed without merging**
