### PR TITLE
show error message when error raised in rails runner

### PR DESCRIPTION
**Pull request by y-yagi**
Error message is no longer displays in #22938.
However, error message with help of error of the investigation I think.

### CODE REVIEW

**Comment by chuckd** [comment]
It would be brilliant if this could be merged y-yagi. Perhaps you could update to merge on master? I just got stumped by this error swallowing behaviour of the Rails 5 runner - my script had a NameError inside it (not the command itself) but all runner told me was

```
Please specify a valid ruby command or the path of a script to run

**Comment by y-yagi** [comment]
@chuckd Thanks for notice! I rebased with master.

**Comment by kaspth** [comment]
Thanks @y-yagi!

**Comment by kaspth** [comment]
5-0-stable: d8a08e9

**Comment by y-yagi** [comment]
Thanks!

**Pull request merged**
