### PR TITLE
When parent model has a scope, changing child attributes with has_many and accepts_nested_attributes_for causes parents not to be touch

### PR DESCRIPTION
**Pull request by wnm**
### Steps to reproduce
remove either scope or after_commit hook to get the test to pass

```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", "5.1.0.rc2"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users do |t|
    t.timestamps
  end

  create_table :posts do |t|
    t.references :user
    t.string :title
    t.timestamps
  end
end

class User < ActiveRecord::Base
  # remove either scope or after_commit hook to get the test to pass

  has_many :posts, -> { order("post.title ASC") }
  accepts_nested_attributes_for :posts

  after_commit { true }
  # after_rollback { true }
  # before_commit { true }
  # before_rollback { true }
end

class Post < ActiveRecord::Base
  belongs_to :user, :touch => true
end

class BugTest < Minitest::Test

  def setup
    User.destroy_all
    Post.destroy_all

    # create a user that was updated an hour ago
    user = User.create
    user.update_columns :created_at => 1.hour.ago, :updated_at => 1.hour.ago
  end

  def test_creating_post_via_has_many_helper_touches_user
    original_updated_at = User.first.updated_at
    puts original_updated_at
    User.first.posts.create! :title => 'Post title'

    refute_equal original_updated_at.to_i, User.first.updated_at.to_i
  end

  def test_creating_post_with_nested_attributes_touches_user
    original_updated_at = User.first.updated_at
    User.first.update! :posts_attributes => { '0' => { :title => 'Post title' } }

    refute_equal original_updated_at.to_i, User.first.updated_at.to_i
  end

end
```

### Expected behavior
Creating/updating/destroying a child that is set to touch the parent should do so via nested attributes whether or not the parent has a before_commit, after_commit, before_rollback or after_rollback hook set and a has_many relation with a scope.

### Actual behavior
Creating a before_commit, after_commit, before_rollback or after_rollback hook in combination with a scope in the has_many relation, causes nested attributes to NOT touch the parent, even though :touch => true is set.

### System configuration
**Rails version**: 5.0.0.1

**Ruby version**: 2.4.0

### Problem
When running before_committed callbacks in a transaction, [dublicate records are removed](https://github.com/rails/rails/blob/92ba89dbcc3fd22296434103503a28dbf6b63789/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb#L79), so it doesn't run the same callbacks multiple times. 

For (parent) models with a `has_many` child relation without a scope that works fine, because [`touch_later`](https://github.com/rails/rails/blob/29b3b5dd8eeb5d202bbd6987535539e1f26ae8b0/activerecord/lib/active_record/touch_later.rb#L10) [sets the instance variables](https://github.com/rails/rails/blob/29b3b5dd8eeb5d202bbd6987535539e1f26ae8b0/activerecord/lib/active_record/touch_later.rb#L18) it needs later on the same record object.

For models with a scope it stops working, though. The reason is, because when [`touch_record`](https://github.com/rails/rails/blob/95911db192cb60047fbfaa2ffed118807a414f2c/activerecord/lib/active_record/associations/builder/belongs_to.rb#L74) is called a [new record object](https://github.com/rails/rails/blob/95911db192cb60047fbfaa2ffed118807a414f2c/activerecord/lib/active_record/associations/builder/belongs_to.rb#L98) is created (where touch_later sets its needed instance variables, but which then gets filtered out later on). The reason why a new record object is created in `touch_record,` is because after a long chain of mehthods, finally [`can_find_inverse_of_automatically?`](https://github.com/rails/rails/blob/c5305f6fdfd46349a6f0646c3e599b9ed706f59a/activerecord/lib/active_record/reflection.rb#L649) returns **false** for [ everything with a scope](https://github.com/rails/rails/blob/c5305f6fdfd46349a6f0646c3e599b9ed706f59a/activerecord/lib/active_record/reflection.rb#L653).

### Solution (this PR)
In touch_later, we look for all records of the current transaction. If the records are identical to the current object, we add the needed instance variables for touch_later to the records for the current transaction, instead of adding a new transaction record.

### CODE REVIEW

**Comment by diegorv** [comment]
Yep, after an update my application from Rails 4.2.8 to Rails 5.0.x, same problem here.

**Comment by diegorv** [comment]
Hey @rafaelfranca, could you please help with this PR?

The problem with  `updated_at` and `accepts_nested_attributes_for` broken all my cache keys :~

**Comment by wnm** [comment]
Is there anything I can do to help fix this issue?

**Comment by rafaelfranca** [comment]
I feel we are fixing this problem in the wrong level. The problem is that an object that can't be automatically inversed doesn't work with `touch_later`. I feel like we should use normal touch for those case.

Maybe we need to change `belongs_to_touch_method` to return `touch` in the cases where `touch_later` can't work?

**Comment by aried3r** [comment]
I'm not sure, but could it be related to https://github.com/rails/rails/issues/25198? Since I'm facing both this and the other issue and you mentioned automatic inversion.

**Comment by wnm** [comment]
@aried3r could be. not sure. but I just tested it, and can confirm that manually setting `inverse_of` fixes this issue as well.

`has_many :posts, -> { order("post.title ASC") }, inverse_of: "user"`

**Pull request closed without merging**
