### PR TITLE
Fixes shellcheck SC2144, replace glob with find.

### PR DESCRIPTION
**Pull request by bopm**
### Motivation / Background

This Pull Request has been created because the current implementation doesn't pass shellcheck SC2144.

### Detail

This Pull Request changes that by implementing a check via a loop.

### Additional information

Details can be found [here](https://github.com/koalaman/shellcheck/wiki/SC2144).

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [ ] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Thank you for the pull request. We have no intention to pass abritary code linters. Let us know if the current code doesn't work and we will fix.

**Comment by bopm** [comment]
@rafaelfranca it's not about linter that told me about that. We can easily omit that information. It's about the fact, that the current code will fail to correctly detect `libjemalloc.so.2` presence if it'll be found in the glob path twice.

**Comment by rafaelfranca** [comment]
In the generated docker container that we do generate that isn't a possibility.

**Comment by bopm** [comment]
@rafaelfranca while that has crossed my mind, I have a strong counter-argument here. Rails was and always going to be a learning ground for many developers. Having faulty glob handling in its files sets a bad example, even if for a particular case it is currently impossible to get two copies of `libjemalloc.so.2` with current outputs of `apt install`.

**Comment by rafaelfranca** [comment]
That is a fair point, but I think that also teaches YAGNI. It isn't broken. It is the code that works with the current environment. We should not complicate the implementation to account for something that perhaps will never happen.

**Comment by rafaelfranca** [comment]
That is way better. Let's do that

**Comment by bopm** [comment]
@rafaelfranca done, and thanks for walking me through it.

**Pull request merged**
