### PR TITLE
`bin/setup` script to bootstrap applications.

### PR DESCRIPTION
**Pull request by senny**
This is a first draft to collect feedback.
### About

While this script does not perform much work out of the box, the idea is to have a starting point to add your own setup code. Having an automated way to bootstrap your application saves not only time but also serves as verifiable documentation. By default the script does:
- `bundle install`
- `bin/rake db:setup`

To encourage users to modify it, I included some suggestions what you might want to do.
### Example

[This Gist](https://gist.github.com/senny/0b7e5959341554c9a50b) shows the output of the script for a newly generated application. Database setup fails because there is no schema present.
### Work
- [ ] document, where should this convention be documented?

### CODE REVIEW

**Comment by DamirSvrtan** [comment]
The way bin/setup is now written, it creates a fresh start - at least for the database. If you pull new changes to a project you're already working on - you'll have your database droped, recreated and migrated all over again. You'll lose all development data.

**Wouldn't it be convenient to have the bin/setup just migrate your database if it already exists?
I would love a second opinion on this.**

I'm currently using the following code snippet although i guess there should be a better way to check if the database exists:

```ruby
system <<-SHELL
  bin/rake db:migrate:status > /dev/null
  if [ "$?" = "0" ]; then
    echo "\n== Migrating database =="
    bin/rake db:migrate
  else
    echo "\n== Preparing database =="
    bin/rake db:setup
  fi
SHELL
```

**Comment by pftg** [comment]
`bin/setup` should be changed by developers per each project and should not be swiss knife.
I think about `bin/setup` as example where you should put your setup code, but not as final solution. 

Some guys expected to run this once after `git clone` to do clean setup, some other expected to re-run on each `git pull` and update only missed parts.

P.S. there is a [google group](https://groups.google.com/forum/#!forum/rubyonrails-talk) where you can discuss such ideas or propositions

**Comment by dhh** [comment]
If you already have the database setup, then you already have the app
running, then bin/setup is not intended for you. We have rake db:migrate
and bundle to deal with those. I think bin/setup as "clean slate" is what
we're trying to achieve with this.

**Comment by DamirSvrtan** [comment]
Thank you David - I was looking for an explanation on this part - wether it should be used for a clean state setup or a continuos setup. We have devs that only do frontend/javascript work on our applications and know very little about Rails - that's why I was looking at `./bin/setup` and `rails s` to be the only commands they need to know to get up and going with their work.

**Comment by fxn** [comment]
@DamirSvrtan maybe a custom `bin/update` ad-hoc for your project could fit your workflow. That is, you throw your own thing custom-made for your team, and then document that's the way frontend people update the project.

**Comment by dhh** [comment]
I think that's a great idea, Xavier. That's how bin/setup started out for
us too.

**Pull request merged**
