### PR TITLE
Remove mocha from ActionPack tests

### PR DESCRIPTION
**Pull request by rodzyn**
This is the last part. /cc @kaspth

### CODE REVIEW

**Comment by rodzyn** [comment]
Travis CI is acting a bit because it's failing on AJ build with `Cannot run integration tests for backburner. To be able to run integration tests for backburner you need to install and start beanstalkd.` but this code does not touch anything in AJ. I think re-build may fix that.

**Comment by seuros** [comment]
i restarted the build.

**Comment by rodzyn** [comment]
@seuros Thanks! It looks like AJ tests are green now :)

**Comment by kaspth** [comment]
Sweet, thanks!

**Pull request merged**
