### PR TITLE
Please use Rails.root.join('path', 'to') instead.

### PR DESCRIPTION
**Pull request by jasonleonhard**
Please use Rails.root.join('path', 'to') instead.

### CODE REVIEW

**Comment by matthewd** [comment]
Why?

**Comment by jasonleonhard** [comment]
Based on the community Ruby style guide.

**Comment by jasonleonhard** [comment]
Also to avoid string interpolation whenever not in use.

**Comment by matthewd** [comment]
We don't follow whatever style guide is recommending that, and I don't see how string interpolation is relevant here.

Thanks anyway.

**Comment by jasonleonhard** [comment]
The Ruby style guide is Rubocop.

**Comment by jasonleonhard** [comment]
[example https://github.com/bbatsov/rubocop/blob/58fef693daabd9bcd9356f3d09b688cffdb9944d/lib/rubocop/cop/rails/file_path.rb](https://github.com/bbatsov/rubocop/blob/58fef693daabd9bcd9356f3d09b688cffdb9944d/lib/rubocop/cop/rails/file_path.rb)

**Comment by matthewd** [comment]
As I said, we don't follow that style guide.

**Pull request closed without merging**
