### PR TITLE
fix NoMethodError being raised when action is empty

### PR DESCRIPTION
**Pull request by y-yagi**
When action set in routes is empty, raised unexpeted `NoMethodError`.

``` ruby
Rails.application.routes.draw do
  get 'users/profile', controller: 'users', action: ''
end 
```

stacktrace is as follows:

``` ruby
NoMethodError (undefined method `empty?' for nil:NilClass):
  actionview (4.2.0) lib/action_view/lookup_context.rb:176:in `normalize_name'
  actionview (4.2.0) lib/action_view/lookup_context.rb:151:in `args_for_lookup'
  actionview (4.2.0) lib/action_view/lookup_context.rb:130:in `exists?'
  actionview (4.2.0) lib/action_view/view_paths.rb:13:in `template_exists?'
  actionpack (4.2.0) lib/action_controller/metal/implicit_render.rb:14:in `method_for_action'
  actionpack (4.2.0) lib/abstract_controller/base.rb:230:in `_find_action_name'
  actionpack (4.2.0) lib/abstract_controller/base.rb:131:in `process'
  actionview (4.2.0) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.0) lib/action_controller/metal.rb:195:in `dispatch'
  actionpack (4.2.0) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.0) lib/action_controller/metal.rb:236:in `block in action'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:42:in `serve'
  actionpack (4.2.0) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:802:in `call'
```

This PR fix it.

### CODE REVIEW

**Comment by arthurnn** [comment]
is this also happening on rails 4.1?

**Comment by arthurnn** [comment]
Also, I think we should add a test to `actionview/test/template/lookup_context_test.rb` file as we are changing its internals in this PR.

**Comment by y-yagi** [comment]
This is not happened on 4.1.  
4.1 checks action is blank or not. [code is here](https://github.com/rails/rails/blob/4-1-stable/actionpack/lib/action_dispatch/routing/mapper.rb#L241...L244).

**Comment by y-yagi** [comment]
And, I add a test to `actionview/test/template/lookup_context_test.rb`. Thanks for your reviews!

**Comment by arthurnn** [comment]
@pixeltrix thoughts?

**Comment by pixeltrix** [comment]
Why is action blank? Is it because of it's in a dynamic segment? i.e. `/:controller/:action` route or is it blank in the routes.rb file. It seems like this should be something caught sooner and not allowed to propagate this far down into the stack

**Comment by y-yagi** [comment]
OK, I see.  I added a check whether `:action` is empty when loading routes.rb.
But, I think that the correspondence of `lookup_context` is necessary when I consider a case to be used from any place other than `routes.rb`(e.g. `Metal.action` method), how about?

**Comment by y-yagi** [comment]
ping @pixeltrix

**Comment by International** [comment]
hi all, is there something else needed for this pull request to be merged?

**Comment by sgrif** [comment]
This changed because the code was refactored to not have this explicit check for each key. We should just change the new location of the check to match the old one. https://github.com/y-yagi/rails/blob/0081f0fb835650f50bc1e33cade3f4533ad42d88/actionpack/lib/action_dispatch/routing/mapper.rb#L276

**Comment by y-yagi** [comment]
Thanks for reviewing.
Since have deleted the original branch by mistake, I want to correspond with the new PR.

**Pull request closed without merging**
