### PR TITLE
Update CHANGELOG.md for readability

### PR DESCRIPTION
**Pull request by zachalewel**
Fixes some readability issues with CHANGELOG.md

### CODE REVIEW

**Comment by claudiob** [comment]
Hello @zachalewel – I believe `accept` is correct since it refers to two different subjects.

At that point, simply adding an `a` article to the CHANGELOG file might fall into the category of "cosmetic changes" that [do not add anything substantial to the stability, functionality, or testability of Rails will generally not be accepted](http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#write-your-code).

I invite you to keep contributing to Rails in the future. If you need a place to start, you might look at [methods that need documentation](http://www.docsdoctor.org/rails/rails) or [list of open issues](http://www.codetriage.com/rails/rails).

Thanks! :ribbon:

**Comment by eileencodes** [comment]
Grammatically, "accepts a" is correct and since this is a grammar correction it's ok. In the future, please add `[ci skip]` so travis doesn't run on changes like this.

**Comment by matthewd** [comment]
@eileencodes shouldn't this be "accept a"?

**Comment by eileencodes** [comment]
It doesn't read right to me as 'accept a' but I don't know. I don't think the original is correct though

**Comment by Fryguy** [comment]
I think the plural of accept is "accept".  So, I think "accept a" is correct

Oddly the 3rd person singular form is "accepts"

```
Singular           Plural
I accept           We accept
You accept         You accept
He/she/it accepts  They accept
```
[Source](http://www.writingenglish.com/cverbs/accept.htm)

**Comment by eileencodes** [comment]
Yea I think I was reading it as "a accepts y" and "b accepts y" so together "a and be accepts y" but then when I read it with literally any other sentence "you and i accept" I realize it's wrong. I had a long week :grin:

**Pull request merged**
