### PR TITLE
Fix a minor grammatical issue in the doc

### PR DESCRIPTION
**Pull request by Ecco**

### CODE REVIEW

**Comment by senny** [comment]
@Ecco thank you :yellow_heart:, for further documentation patches, please include `[ci skip]` in the commit message to prevent Travis CI from running needlessly.

**Comment by Ecco** [comment]
Thanks for merging!

By the way, the whole process of contributing to rails' doc isn't very well… documented :-) It took me a while to figure out that docrails wasn't were you were supposed to actually do stuff.

I'm really new to this, but off the top of my head, I think it could be improved by either :
* Actually giving write-access to docrails to anyone (this seemed to be the plan initially but it doesn't seem to be the case anymore). I guess this would fix the travis issue since CI could be simply disabled on that repository.
* Getting rid of docrails completely. (Maybe people currently trusted with push access to docrails could be given access to rails?)
* Linking to an up-to-date documentation (http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#contributing-to-the-rails-documentation) in the description of the docrails repo (since the blogpost that is linked seems a bit outdated)

It could also be a good idea to mention the [ci skip] thing in the contributing guide, let me know if you'd want a pull request for this :)

**Comment by senny** [comment]
@Ecco great to hear your thoughts.

There is a `NOTE:` section in the contribution guide about the `[ci skip]`:

screen shot 2015-04-23 at 16 12 36

Write-permissions to `docrails` used to be public but because of changes at GitHub, this is no longer possible. We still give anyone access to `docrails` who is interested in contributing documentation patches regularly. That's also the reason why we'd rather not give these permissions directly on the `rails/rails` repository. The patches from `docrails` are still reviewed when we bring them into `rails/rails`.

If you have improvements to make it easier for new contributors please, a pull request is very welcome!

**Comment by fxn** [comment]
Some history here http://weblog.rubyonrails.org/2013/6/14/docrails-back-to-the-roots/.

**Comment by Ecco** [comment]
Thanks guys, this is really insightful.

I guess the documentation is allright, I just read it too fast.

There is still something confusing though: the description of `rails/docrails` on GitHub.

It currently reads : "Rails branch for quick doc fixes, please DO NOT OPEN PULL REQUESTS IN HERE
http://weblog.rubyonrails.org/2013/6/14/docrails-back-to-the-roots/"

I believe this could be improved by:
 * Changing the description (Which is straight up misleading: the patch I just contributed was clearly a "quick doc fix" but wasn't supposed to be in docrails)
 * Adding all three URLs, in that order : 
http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#contributing-to-the-rails-documentation then
http://weblog.rubyonrails.org/2013/6/14/docrails-back-to-the-roots/ then
http://weblog.rubyonrails.org/2012/3/7/what-is-docrails/

Also, thanks @fxn for the link. I would have sworn that docrails pointed to http://weblog.rubyonrails.org/2012/3/7/what-is-docrails/
 just a few hours ago :)

**Pull request merged**
