### PR TITLE
Automate schema cache dumping after db:migrate

### PR DESCRIPTION
**Pull request by stefansundin**
### Summary

The `db/schema.rb` file is automatically updated after you run `db:migrate`. Having recently started using the schema cache, I would like the same thing to happen for the schema cache file.

### Other Information

I was pondering just reusing `dump_schema_after_migration` and putting the code inside the existing `if` block, instead of introducing a new variable. Let me know if that is preferred and I can change it to do that.

I don't know if the new test is working as intended. I tried running the tests locally but there were a lot of failures and I'm not sure if it's due to my setup or not.

Thanks, please let me know what I may have done incorrectly!

### CODE REVIEW

**Comment by rafaelfranca** [comment]
I'm a little bit confused. Why would we generate the schema cache in development but not in production if the schema cache was made to be used in production?

**Comment by stefansundin** [comment]
For the same reason you generate the `db/schema.rb` file in development. It should be the same.

So you generate it in development, and then bundle it when you deploy, and the schema file will be used by the production environment.

Unless I misunderstand something?

**Comment by rafaelfranca** [comment]
`db/schema.rb` is a file to be used only in development and test.

The schema cache is to be only used in production.

If you have the schema cache file in development Rails will not define the columns based on your database anymore, so if you have a server running and run migration to add a new column that column will only picked when the server is restarted. This is not the experience we want.

**Comment by stefansundin** [comment]
This PR doesn't change anything regarding when or how the schema cache is used. In my application I set `use_schema_cache_dump=false` in `config/environments/development.rb`, but I still generate the schema cache file in development so that it can be used in production.

The purpose of this code change is only to make the regeneration of the file simpler.

The reason the comment says that this variable should be false in production was because I assumed that most people were generating the schema cache file in development and simply bundling it when deploying into production. Generating the schema cache in production doesn't hurt anything, it's just that it should be an unnecessary operation. If that's not how most people do it, then we can of course change it.

**Pull request closed without merging**
