### PR TITLE
Remove sucker_punch ActiveJob::Queue adapter

### PR DESCRIPTION
**Pull request by dixpac**
Removes sucker_punch dependency.
SuckerPunch existed before ActiveJob, but ultimately uses similar code to `AsyncAdapter` under the covers.

Connected to #52929

### CODE REVIEW

**Comment by zzak** [comment]
This still needs a deprecation cycle

**Comment by dhh** [comment]
Don't think we need that for a major version. Fine just to tell people to use AsyncAdapter as the replacement. That's what Brandon himself is doing: https://github.com/brandonhilkert/sucker_punch?tab=readme-ov-file#faq

**Comment by zzak** [comment]
I disagree, the point of the major version isn't to introduce breaking changes. By using the deprecation cycle, we give users the chance to upgrade their applications **along side** bumping the version, so their apps are not stuck on an old version of Rails simply because they can't swap out AJ adapters so easily. Maybe they've bumped into an edge case, probably the likelihood is low but that is the contract we've given to our users and personally I would prefer to stick with it.

**Comment by dhh** [comment]
All depends on the case. Here we have a case where the author of a very little used adapter is recommending using something we already have in the box. And the potential for switching things out is straight forward. So I weigh the work to be done against all those factors, and this seems proportionate for a major version to me.

**Comment by zzak** [comment]
The amount of work depends on perspective, I suppose. It is less work for the user of `SuckerPunchAdapter` who wants to upgrade their version of Rails, but we have to support that code during deprecation. In general though, my point is regardless of major or minor the contract should be the same that public API will not suddenly disappear between versions. But not sure that is a hill worth dying on for a test dependency, no one is really using this in production right?

**Pull request merged**
