### PR TITLE
Debugging JRuby CI timeouts

### PR DESCRIPTION
**Pull request by bf4**
Follows: https://github.com/rails/rails/pull/23499#commitcomment-17153201

ref: https://twitter.com/tom_enebo/status/722432931579305984

### CODE REVIEW

**Comment by bf4** [comment]
@jeremy Have you seen this any more?

**Comment by jeremy** [comment]
I haven't been monitoring it. Please do debug further! I'm assuming this isn't specific to the CI environment…

**Comment by bf4** [comment]
Looks like JRuby CI has moved on quite a bit since this pr

**Pull request closed without merging**
