### PR TITLE
Fix missing parent in inverse associations building

### LINKED ISSUE #9157: Inverse instance should be set before attribute assignment when building through a relationship
As the title says ^

Consider:

``` ruby
class Child < ActiveRecord::Base
  belongs_to :parent, inverse_of: :children

  def first_name= value
    super.tap { self.name = "#{value} #{parent.last_name}" }
  end
end
```

``` ruby
class Parent < ActiveRecord::Base
  has_many :children, inverse_of: :parent
end
```

Now when I run the code:

``` ruby
child = Parent.new(first_name: 'John', last_name: 'Smith').children.build(first_name: 'Alex')
```

I'd expect it to give the child the parent object before assigning the attributes. Something like....

``` ruby
child.name #= Alex Smith
```

But it doesn't. In method `first_name=` parent is still `nil` !!!

### PR DESCRIPTION
**Pull request by leafac**
Fixes #9157.

### CODE REVIEW

**Comment by leafac** [comment]
I'm closing my own PR as stale.

**Comment by betesh** [comment]
@leafac Could you elaborate please?  Is there another PR that duplicates this one?  If so, linking it here would be helpful.  Thank you!

**Comment by dmitry** [comment]
I'm also interested in fixing this issue.

**Comment by leafac** [comment]
I'm sorry, but I don't know of any other PR that duplicates this one.

This PR was stale and didn't receive any comments saying what could be improved. It didn't even merge cleanly anymore. So I closed it to reduce clutter.

I'm willing to give it another try, as I see there's interest. Let me know how I can help.

**Comment by bendilley** [comment]
I'd like to see this issue fixed too. It's caught me out, and probably not for the last time.

**Comment by leafac** [comment]
Before proceeding to reopen the PR, I would appreciate some feedback from @rafaelfranca, which seems to have looked at it. This way I'll know what needs to be worked on and will reopen with better chances of being merged.

@rafaelfranca, if/when you have the time, please take a look. Thank you!

**Pull request closed without merging**
