### PR TITLE
Fix keyed defaults with root

### PR DESCRIPTION
**Pull request by chrisarcand**
### Summary

The merging of the 'defaults' option was moved up the stack in e852daa. This allows us to see where these options originate from the standard `HttpHelpers` (`get`, `post`, `patch`, `put`, `delete`)

Unfortunately this move didn't incorporate the 'root' method, which has always allowed the same 'defaults' option.

In short, these routes should be the same (Tested in Rails 3.2, 4.2, 5.0)

```
get "/", to: "something#show", defaults: { something: "something" }

root to: "something#show", defaults: { something: "something" } # defaults broken in 5.0
```

My thanks to @jrafanie for helping bisect this issue and find the regression!

### CODE REVIEW

**Comment by maclover7** [comment]
👍 Thank you for finding and submitting a PR to fix! Action Pack tests are passing here, but build is failing due to a Sprockets issue which should be resolved shortly.

**Comment by chrisarcand** [comment]
Tests are 💚 again.

**Comment by chrisarcand** [comment]
Whew, finally. Finally ready for a look, @rafaelfranca

**Comment by rafaelfranca** [comment]
Backported in ec07105

**Comment by chrisarcand** [comment]
❤️

**Pull request merged**
