### PR TITLE
Switch to rollup for activestorage npm module build

### PR DESCRIPTION
**Pull request by gauravtiwari**
### Summary

This PR switches from Webpack to Rollup, which produces smaller bundle and faster code execution using scope hoisting(16KB vs 20KB on disk). The way webpack works is that it wraps each module in a function, and creates a bundle that implements a loader and a module cache. At runtime, each of those module functions is evaluated in turn to populate the module cache, which lets us use advanced features like code-splitting and on-demand loading, which we don't need here since this is a library. 

Webpack 3 introduced scope hoisting, but the bundle the still going to be bigger due to above reasons. Rollup is better suited here because this is library and we are mostly writing it in ES6. More information: https://rollupjs.org/

Example output comparison: https://gist.github.com/Rich-Harris/79a02519fb00837e8d5a4b24355881c0

### CODE REVIEW

**Comment by javan** [comment]
Rollup is quite nice, but I went with Webpack because we're using it in Rails now via webpacker, and I'd rather not introduce yet another JavaScript bundler unless there's a compelling reason to.

It looks like your changes shrink `activestorage.js` from 18929 bytes to 15990 bytes. How much does it shrink if we introduce Webpack's `webpack.optimize.ModuleConcatenationPlugin()` (scope hoisting) plugin instead?

**Comment by matthewd** [comment]
Maybe related, maybe not.. can we get Active Storage into a situation more like the ACa/AV coffeescript, where only the source lives in the repository, and the compiled blob is just generated at release time?

**Comment by javan** [comment]
@matthewd, we *can*, but I'd prefer not to. Keeping the compiled `activestorage.js` in the repo allows the js module to be installed from npm or by pointing your `package.json` at github.

**Comment by rafaelfranca** [comment]
So can we change ACa/AV to use the same thing? I don't like to having two different solutions to the same problem in the repository.

**Comment by matthewd** [comment]
Can't the "point `package.json` at GitHub" flow be handled by the source version (with a requirement of the relevant transpiler, or whatever)?

Compiled blobs in version control make me very sad. (And permanently bloat the repository, surprisingly quickly.)

**Comment by javan** [comment]
I think we should treat Active Storage as a prototype for next generation (post asset pipeline) Rails engines+JavaScript modules. With the asset pipeline, JavaScript was easy to keep in sync and happened automatically with gem upgrades. We don't have a mechanism for keeping JavaScript modules in sync with gems yet.

Active Storage currently spans both worlds and can be installed via:
1. Gem from RubyGems + asset pipeline JS 
2. Gem from GitHub + asset pipeline JS two ways:
    - `//= require activestorage`
    -  `//= require src/activestorage`
3. Gem from RubyGems + JS module from npm
4. Gem from GitHub + JS module from GitHub

> Can't the "point `package.json` at GitHub" flow be handled by the source version (with a requirement of the relevant transpiler, or whatever)?

Yeah, that's worth exploring. It'd add more friction and opens the door to subtle bugs caused by different transpiler/compiler setups.

> So can we change AC/AV to use the same thing?

Yes, eventually. Let's let the dust settle first.

**Comment by matthewd** [comment]
Right.. ACa/AV currently support 1, 2a, and 3, but IIRC sacrificed 4 because it seemed too hard for CoffeeScript -- and is designed such that 2b doesn't exist.

I would've thought we could exert enough control over versions through dependencies... otherwise we're exposed to similar subtleties based on who last compiled the blob anyway. And even if we can't, that doesn't seem measurably different from people having different nodejs versions, or different ruby versions: it's a thing, but not likely to be a major one.

I want "point at GitHub" to work, but I'm willing to tolerate *some* friction: it's a comparatively rare use case.

**Comment by gauravtiwari** [comment]
@javan Agree, it's just that for our use case rollup fits better (AS being a library)
- smaller bundle size
- out of the box ES6 and tree shaking 
- and scope hoisting (i.e. code will be executed faster). 

Bundle comparision: https://gist.github.com/Rich-Harris/79a02519fb00837e8d5a4b24355881c0

Webpack is nice too, it's just that we get extra module wrapper around it, which increases the size and also makes execution slower (not a lot here though). I have tried `webpack.optimize.ModuleConcatenationPlugin()` but the bundle size remains the same, the only thing extra is the function definition is moved up so the execution can be faster.

**Comment by gauravtiwari** [comment]
We can also have multiple bundles down the line too i.e. esm module for Webpack etc.

**Comment by javan** [comment]
> Compiled blobs in version control make me very sad. (And permanently bloat the repository, surprisingly quickly.)

It's worth evaluating how sad you'd be / how much bloat there'd be for (hopefully) stable library code. AC, for example, has hardly changed. Had its compiled js been in version control there'd be very little bloat.

**Comment by javan** [comment]
While rollup may be a slightly better tool for the job, I'd like to keep our new build tooling and domain knowledge limited to webpack as we transition away from sprockets. Closing for now.

**Pull request closed without merging**
