### PR TITLE
Fix place of require 'rails_guides/markdown'

### PR DESCRIPTION
**Pull request by yui-knk**

### CODE REVIEW

**Comment by schneems** [comment]
Can you give me more info? Why should this change be merged?

**Comment by yui-knk** [comment]
@schneems   OK. `guides/rails_guides/generator.rb` should know it requires rails_guides/markdown, because it calls `RailsGuides::Markdown.new`. But `guides/rails_guides.rb` should not know `RailsGuides::Generator` uses `RailsGuides::Markdown`. So I will remove `require 'rails_guides/markdown' `

**Comment by schneems** [comment]
Is there a case when we load the generator without the guides? Is this allowing us to do something we couldn't before? We don't take refactoring pull requests. Only new features and bug fixes.

**Comment by yui-knk** [comment]
Sure, this PR dose not add new features.

> We don't take refactoring pull requests.

is a policy of all rails repositories ? or policy for only guide script?

rails code base accepts only refactoring PR (ex: https://github.com/rails/rails/commit/9530c5786e621bcafa68a2eab3021ccd9a930e52?diff=unified).

**Comment by schneems** [comment]
It's a rails wide policy, sometimes exceptions are made cc/ @rafaelfranca

**Comment by senny** [comment]
@yui-knk It's less refactoring PR's that we don't accept but cosmetic changes. Sometimes the line blurs between the two. The general rule is, a PR that does not add anything, fix anything or makes the code more clear, less brittle etc. is treated as a cosmetic change. (for example changing the hash syntax).

I'd say this change is very close to being cosmetic but I don't feel to strong about it.

**Comment by rafaelfranca** [comment]
I think this is not cosmetic since now we made the dependency clearer

**Pull request merged**
