### PR TITLE
Add ActiveRecord.schema_dump_formats

### PR DESCRIPTION
**Pull request by neroleung**
### Motivation / Background

This Pull Request has been created because our database contains triggers and functions which cannot be expressed in `db/schema.rb` so we have to use `db/structure.sql`. But then some of us appreciate the readability of `db/schema.rb`. So it'd be ideal for us if we can dump both files in our project.

### Detail

This optional setting allows multiple formats to be dumped if desired. For example:

```
config.active_record.schema_dump_formats = [:ruby, :sql]
```

### Checklist

Before submitting the PR make sure the following are checked:

* [ ] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [ ] There are no typos in commit messages and comments.
* [ ] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [ ] Feature branch is up-to-date with `main` (if not - rebase it).
* [ ] Pull request only contains one commit for bug fixes and small features. If it's a larger feature, multiple commits are permitted but must be descriptive.
* [ ] Tests are added if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.
* [ ] PR is not in a draft state.
* [ ] CI is passing.

### CODE REVIEW

**Comment by fschwahn** [comment]
We are doing exactly this thing manually right now:
```ruby
namespace :db do
  desc "Loads custom SQL functions"
  task :load_sql_functions do
    ActiveRecord::Tasks::DatabaseTasks.load_schema_current(:sql, "db/functions.sql")
  end

  task "test:load_sql_functions" do
    ActiveRecord::Tasks::DatabaseTasks.load_schema_current(:sql, "db/functions.sql", "test")
  end
end

Rake::Task["db:schema:load"].enhance ["db:load_sql_functions"] if Rake::Task.task_defined?("db:schema:load")
Rake::Task["db:test:load_schema"].enhance ["db:test:load_sql_functions"] if Rake::Task.task_defined?("db:test:load_schema")
```

While it's not a lot of code, it has broken a few times during rails upgrades. Would be great to see something like this natively supported 👍

**Comment by yahonda** [comment]
Thanks for opening a pull request. I understand there are some use cases that want to dump both schema.rb and structure.sql. 

Now https://github.com/rails/rails/pull/44834 has been merged to main, the next version of Rails 7.1 can dump both structure.sql and schema.rb
by setting SCHEMA_FORMAT environment variables as follows that should satisfy the use case explained in this pull request rather than implementing new configurations.


```
SCHEMA_FORMAT=sql rake db:schema:dump
SCHEMA_FORMAT=ruby rake db:schema:dump
```

**Comment by neroleung** [comment]
@yahonda thanks for letting me know about #44834. Totally didn't notice that and I agree it is a viable option. But using a rake task to dump both formats means developers will either have to remember to do it when they add a migration, or implement some sort of commit hook so that it becomes a standard process which is extra work (and time as well if their laptop is as slow as mine).

I believe, though, adding this new configuration can increase developer experience - we can simply set it in the config and no extra work would be required. I think it'd be especially useful if a developer has to manage multiple Rails projects. Hence I believe having a configuration for this is more developer-friendly than the rake task solution.

Could you please reconsider this PR from the developer experience's perspective? 🙏

**Comment by eileencodes** [comment]
Hey @neroleung I appreciate your explanation and the developer experience perspective but I think your use case isn't representative of what most apps are doing.

The schema.rb and structure.sql aren't meant to be used by users, but by the database. Since there is already a workaround for dumping both if you really want to I don't think we have a solid case for adding yet another way to dump both, especially since Rails will only use one to load the schema into the database. This feature adds complexity without benefitting the application.

Because of these reasons we're not going to accept this change. Thanks for the PR and understanding our perspective.

**Pull request closed without merging**
