### PR TITLE
Document know limitation about using `references` in conjunction with custom select clauses [ci skip]

### LINKED ISSUE #24314: as_json works differently for preload and eagerload
### Steps to reproduce
```
class Portfolio < ActiveRecord::Base
  has_many :tickets
end
class Ticket < ActiveRecord::Base
  belongs_to :portfolio
end

@tickets = Ticket.includes(:portfolio).select('tickets.*', 'SUBSTRING(tickets.title,1,4) as code')
@tickets.first.as_json
@tickets.references(:portfolio).first.as_json
```

### Expected behavior
`@tickets.first.as_json` should be equal to `@tickets.references(:portfolios).first.as_json`

### Actual behavior
`@tickets.first.as_json` includes the **code** (alias column defined in the `select`)
`@tickets.references(:portfolios).first.as_json` does not include the **code** (alias column defined in the `select`)

### Note
The problem arises only when `eager_load` is called by `includes`, `preload` works fine. More to that, using `joins` works fine aswell. 

### System configuration
**Rails version**: 4.2.6

**Ruby version**: 2.1.8

### PR DESCRIPTION
**Pull request by vipulnsward**
Fixes #24314 

r? @matthewd

### CODE REVIEW

**Comment by vipulnsward** [comment]
Related- https://github.com/rails/rails/issues/12423 and https://github.com/rails/rails/issues/15185
cc @sgrif

**Comment by sgrif** [comment]
The wording here is misleading. We still include the custom select clause (meaning it's available for things like `where` clauses), but it will not be placed on the parent record. This also isn't limited to `references`. I think we should focus on the cause, not the exact methods that lead to it. Something like:

> Note: If an association is eager loaded as part of a join, any fields from a custom select clause will not be on the loaded models. This is because it is ambiguous whether it should appear on the parent record, or the child.

**Comment by vipulnsward** [comment]
Slight wording change and updated.

**Comment by vipulnsward** [comment]
Made some slight changes. Thanks for the review, merging.

**Pull request merged**
