### PR TITLE
Allow using comparison operators on `Arel` `NodeExpression` objects and `Attribute` objects.

### PR DESCRIPTION
**Pull request by kddnewton**
We already have methods for all the basic arithmetic operators as well as bitwise operators, so I was surprised to find it didn't have comparison operators.

### CODE REVIEW

**Comment by kddeisz** [comment]
Rebased this in case there is any interest.

**Comment by kddeisz** [comment]
@kamipo Tagging you since you do a lot with ActiveRecord. Is there interest in this?

**Comment by kamipo** [comment]
No, just enough using `gt`, `lt`, etc. And `xxx > 10` not returning truthy/falsy value unlike `xxx == 10` is bit confusing to me.

**Comment by kaspth** [comment]
How far can we get these days endless, and soon with Ruby 2.7 beginless, ranges? I prefer just relying on `Post.where(created_at: 2.days.ago..)` and `Post.where(created_at: ..2.days.ago)` to exposing > and the other operators.

**Comment by kddeisz** [comment]
Fair enough! No worries.

**Pull request closed without merging**
