### PR TITLE
add render_and_return

### PR DESCRIPTION
**Pull request by hasandiwan**
Convenience method for render_and_return. Addresses concern adumbrated [here](https://blog.arkency.com/render-is-not-your-final-word-in-your-rails-controllers-action/)

### CODE REVIEW

**Comment by flavorjones** [comment]
@hasandiwan Thank you for submitting your first pull request to Rails! I'm going to ask you to do a bit more work to make it easier for the core team to review and give you feedback:

- Please make sure you've read the [contributor's guide](https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#open-a-pull-request)!
- It looks like you skipped the [pull request template](https://github.com/rails/rails/blob/main/.github/pull_request_template.md). Please read that, paste the [raw version](https://raw.githubusercontent.com/rails/rails/main/.github/pull_request_template.md) into this issue, and fill it out.
- Please provide enough context for the maintainers to understand why this change would be valuable!
- The pull request template will also remind you to include some test coverage for this method.

Thank you!

**Comment by hasandiwan** [comment]
@flavorjones To your points:

- I did read the contributors' guide.
- It's a 4-line change, whose logic is explained in the [blog post](https://blog.arkency.com/render-is-not-your-final-word-in-your-rails-controllers-action/) here. Would you like me to copy/paste the blogpost here?

**Comment by flavorjones** [comment]
@hasandiwan I'm happy to hear you read the contributors guide! Just to highlight a couple of relevant sections for you:

In the section ["Write your Code"](https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#write-your-code):
> - Include tests that fail without your code, and pass with it.
> - Update the (surrounding) documentation, examples elsewhere, and the guides: whatever is affected by your contribution.

In the section ["Issue a Pull Request"](https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#issue-a-pull-request):
> Fill in some details about your potential patch,using the pull request template provided.

In the section ["Updating the Documentation"](https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#updating-the-documentation):
> If your PR adds a new feature, or changes how an existing feature behaves, check the relevant documentation, and update it or add to it as necessary.

In the section ["Iterate as Necessary"](https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#iterate-as-necessary):
> It's entirely possible that the feedback you get will suggest changes. Don't get discouraged!

[The core team follows these guidelines, even for simple additions](https://github.com/rails/rails/commit/959d46ef8794cd01090d1a041dfc2f901391e33d), so even if you wouldn't require them for your project, please understand that these are our expectations of contributors on this project.

The pull request template is short, and adding some tests should be straightforward (though we'd be happy to help if you have questions about the kind of test that's appropriate!).

Please also add a bit more documentation to explain how others can use the feature! And kindly omit linking out to your blog post. Thank you!

**Comment by hasandiwan** [comment]
Mr Dalessio,


On Mon, 10 Oct 2022 at 18:18, Mike Dalessio ***@***.***>
wrote:

> @hasandiwan <https://github.com/hasandiwan> I'm happy to hear you read
> the contributors guide! Just to highlight a couple of relevant sections for
> you:
>
> In the section "Write your Code"
> <https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#write-your-code>
> :
>
>
>    - Include tests that fail without your code, and pass with it.
>
>
There are no tests, because, like I wrote "it is a 5-line patch".

> It's entirely possible that the feedback you get will suggest changes.
> Don't get discouraged!
>
>
The fact that I'm interacting with you on this should be taken as a sign
that I'm not getting discourged.

> omit linking out to your blog post.
>

It's not my blog post. Merely the post that inspired the patch. On said
blog post, one finds all the justification that's needed for the patch. My
blog is at https://www.prolificprogrammer.com and hasn't been updated since
July -- if you check it, you will find that you're a fairly lonely reader,
as I'm not the self-aggrandizing blowhard you want to paint me as.

-- 
OpenPGP: https://hasan.d8u.us/openpgp.asc
If you wish to request my time, please do so using
*bit.ly/hd1AppointmentRequest
<http://bit.ly/hd1AppointmentRequest>*.
Si vous voudrais faire connnaisance, allez a *bit.ly/hd1AppointmentRequest
<http://bit.ly/hd1AppointmentRequest>*.

<https://sks-keyservers.net/pks/lookup?op=get&search=0xFEBAD7FFD041BBA1>Sent
from my mobile device
Envoye de mon portable

**Comment by flavorjones** [comment]
@hasandiwan In our relationship -- you and me! -- where I'm a member of the Rails issues team and you are a first time contributor, we have obligations to each other. My obligation is to try to make you feel welcome, to teach you about the project's expectations, and to help you get your first commit merged. And your obligation is to be open-minded, curious, and unentitled.

I feel like I have fully honored my obligations. Now you have a decision to make: you can choose to respond to this feedback with curiosity and use it as a learning experience; or you can close this pull request. It's totally up to you.

Either way, I wish you luck on your open-source journey, and I genuinely hope in the future you find a way to gracefully accept help from people.

**Comment by hasandiwan** [comment]
> @hasandiwan In our relationship -- you and me! -- where I'm a member of the Rails issues team and you are a first time contributor, we have obligations to each other. My obligation is to try to make you feel welcome, to teach you about the project's expectations, and to help you get your first commit merged. And your obligation is to be open-minded, curious, and unentitled.

I'm not a first-time opensource contributor. I'm even not a first-time rails contributor. This is, however, my first time running across your good self. While you may feel your obligation is what you say, it doesn't matter how you feel you've fulfilled your obligations. 

> I feel like I have fully honored my obligations. Now you have a decision to make: you can choose to respond to this feedback with curiosity and use it as a learning experience; or you can close this pull request. It's totally up to you.

Further, telling me how to behave with you, who have mischaracterized my intention by linking to a blog post, misattributed said blog post to myself -- without apologizing for either of these slights. 

If you truly want to be helpful, you would focus on why buildkite is failing on a portion of the code which I have not touched rather than running me down, which, incidentally, has no effect on me as this is just text on a screen.

**Pull request closed without merging**
