### PR TITLE
Fix minor docs [ci skip]

### PR DESCRIPTION
**Pull request by amitsuroliya**

### CODE REVIEW

**Comment by arthurnn** [comment]
thanks

**Comment by amitsuroliya** [comment]
Thanks @arthurnn :heart:

**Comment by rafaelfranca** [comment]
@amitsuroliya I added you to docrails repository. For this kind of documentation change please commit directly on docrails repository.

**Comment by amitsuroliya** [comment]
Thanks @rafaelfranca :+1:

**Pull request merged**
