### PR TITLE
Convert enum values in read attribute

### PR DESCRIPTION
**Pull request by sachin004**
Fix for issue #16459 and issue #14017 
class Post < ActiveRecord::Base
  enum status: [:live, :inactive, :deleted]
end

post = Post.new(:status => :live)
post.status # => "live"

The following are some of the changes after fix
# Before:

<code>post.attributes = {"id"=>1, "post"=>nil, "status"=> 0}</code>
# After :

<code>post.attributes = {"id"=>1, "post"=>nil, "status"=> "live"}</code>
# Before:

<code>post[:status] = 0</code>
# After :

<code>post[:status] = "live"</code>
# Before:

<code>post["status"] = 0</code>
# After :

<code>post["status"] = "live"</code>
# Before:

<code>Post.first => Post id: 1, post: nil, status: 0,created_at: "2014-09-05 18:22:20", updated_at: "2014-09-05 18:22:20"</code>
# After:

<code>Post.first => Post id: 1, post: nil, status: "live" ,created_at: "2014-09-05 18:22:20", updated_at: "2014-09-05 18:22:20"</code>

### CODE REVIEW

**Comment by bxt** [comment]
So what's the status of this? I'd really love to see this changed. The other issues are not active anymore either.

**Comment by sachin004** [comment]
Even i'd like to see this changed but still waiting for response from admins.

**Comment by dhh** [comment]
After further consideration, I'd like to see what a complete string mapping actually looks like in performance across MySQL and PG. If someone wants to do the legwork on what the difference between, say, "0, 1, 2" and "active, archived, deleted" is across 10M rows, both in terms of table size and query speed, then we can reopen the discussion about whether we could just go with the string values. Then everything would Just Work.

**Comment by chancancode** [comment]
c51f9b6 fixed this via a different approach on master (Rails 5). Now enums are consistently represented as strings pretty much everywhere, so closing. The performance question from David is a separate issue and it's still a valid question, so feel free to open a new thread on the mailing list with the benchmark results!

**Pull request closed without merging**
