### PR TITLE
Add option ActiveStorage.browser_no_cache

### PR DESCRIPTION
**Pull request by randoum**
Fixing bug #34989 : in feature testing, when attachments records are created with the same id, the browser cache get populated with urls that may become invalid between tests.

Add option ActiveStorage.disable_cache_for_tests. Default to false.

When set to true, and only in test environment, BlobsController and RepresentationsController do not set browser cache for the redirect. As a result the redirect for blobs is sent to the browser with "Cache-Control" header set to "no-cache"

### CODE REVIEW

**Comment by eileencodes** [comment]
cc/ @georgeclaghorn how do you feel about this?

**Comment by georgeclaghorn** [comment]
Er, that won’t work, sorry. (`service_urls_expire_in` is used for other stuff.) Let’s go with a generic option that can be set to false in any environment, though your app will probably only set it in test.

**Comment by randoum** [comment]
Ok. then perhaps the name `disable_cache_for_tests` is not relevant anymore (I was not sure of the name anyhow). Any suggestion?

**Comment by randoum** [comment]
I went for `browser_no_cache`

**Comment by randoum** [comment]
@georgeclaghorn any thought, while it's fresh?

**Comment by randoum** [comment]
@eileencodes @georgeclaghorn Sorry to insist. Any idea if this is going to be pushed ?

**Comment by randoum** [comment]
@eileencodes  @georgeclaghorn  I'm making pancakes. You guys want pancakes ?

**Comment by jackkinsella** [comment]
This proposed feature would help with my integration testing practice (though with a caveat, mentioned below).

My testing suite fails tests not just for explicit assertion failures in `Capybara` specs but also for any JavaScript errors that happen to occur while the integration tests operate the website. This provides a useful smoke screen for lingering problems with front-end code. As it stands, however, ActiveStorage's caching – when used in conjunction with `cache-control: public` - causes the test browser to sporadically throw JavaScript errors like the following

```
http://localhost:10000/rails/active_storage/disk/eyJfcm.../1px-orange.png?
content_type=image%2Fpng&disposition=inline%3B+filename%3D%221px-
orange.png%22%3B+filename%2A%3DUTF-8%27%271px-orange.png -

 Failed to load resource: the server responded with a status of 404 (Not Found)
```

My dream solution would be a way to globally switch off all HTTP caching in, including but not limited to `ActiveStorage`. (i.e. I'd also like to switch off `ConditionalGet` etc.)

Right now I use a wrapper command to toggle HTTP cache headers:

```ruby
def cache_publicly
  if Rails.application.config.action_controller.perform_caching
    expires_in 1.day, public: true
  end
end

class PagesController
  def about_us
    cache_publicly 
     ...
  end
end
```

**Pull request closed without merging**
