### PR TITLE
Guides dark mode fixes

### PR DESCRIPTION
**Pull request by jathayde**
### Motivation / Background

Screenshot 2024-03-21 at 8 15 34 AM
(original, edge, proposed)

Initial feed back from @dhh, @MatheusRich (#51363, #51364, #51365), @iuhoay (#51368), and community members identified a some issues, including some AA contrast failures, in the new dark mode styles, as well as a preference to remove the hard contrast elements (e.g. white code blocks, etc). 

### Detail

This Pull Request changes the following items:

- Adds styling to scroll bars for `#guides` and `body`
- Reduces contrast between background  and `#subCol` background color
- Removes white code blocks and unifies dark code blocks and syntax highlighting between both light & dark mode
- Changes H1, H2 to white
- Moves link color to a much lighter red which passes AA contrast 4.54:1
- Softened background color and border on interstitial blocks (note, tip, et al) to 50% of their previous brightness
- Softened work-in-progress icon
- Removed SVG icon that was overriding old favicon
- improved contrast to 8.06:1 for inline code callouts
- Removed code callout highlights in tables and headlines
- Table headers no longer white
- Fixes Safari faux-bold in code blocks

### Additional information

Showing the new link colors and interstitial note:

Screenshot 2024-03-21 at 8 19 35 AM

### Checklist

Before submitting the PR make sure the following are checked:

* [X] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [X] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [X] Tests are added or updated if you fix a bug or add a feature.
* [X] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by MatheusRich** [comment]
@jathayde TY for the speedy fix!

**Comment by SleeplessByte** [comment]
I really like these changes. And thank you for softening the background color and border on interstitial blocks (note, tip, et al). This makes it way less jarring to read!

Here are a few things I've noticed.

## The scrollbars are probably not accessible

I generally use the work by people of [Adrian Roselli](https://adrianroselli.com/2019/01/baseline-rules-for-scrollbar-usability.html) as a baseline, and there it states two important components:

- contrast, needed for AA which we should aim for
- size, needed for AAA, which is in my opinion nice to have

Size would normally be exempt because it's a browser control, but overriding it makes it problematic, but alas. Let's ignore it.

Scrollbar and track in dark mode

The things we should check for are

- scrubber (scrollbar-thumb) (#5a090b through #a01013 / #a2a2a1), with the scroll track (scrollbar-track) (body is [#333232 **yields 1.11**](https://webaim.org/resources/contrastchecker/?fcolor=5A090B&bcolor=333232) / shadow is [#292929 **yields 1.02**](https://webaim.org/resources/contrastchecker/?fcolor=5A090B&bcolor=292929))
- scrubber with the page (floating element [#343434 **yields 1.14**](https://webaim.org/resources/contrastchecker/?fcolor=5A090B&bcolor=333232) and page background [#2e2e2e **yields 5.31**](https://webaim.org/resources/contrastchecker/?fcolor=A2A2A1&bcolor=2E2E2E))
- scroll track with the page (#343434 and #2e2e2e)

I recommend to increase the contrast of the _scrubber_ and the page/floating element to be _at least 3:1 at the top and bottom_. 

Personally, I strongly dislike the tiny width scrollbar because it becomes _really hard to grab_. Not every mouse has a scroll wheel!

## Because of the body padding the footer isn't full width

| Visual issue | Cause |
| ------------ | ----- |
| Footer isn't full width on large screens | CSS that causes this |

I _think_ the padding can be removed because the content is in columns, but I have not tested it extensively.

## The `<hr>` svg has not been updated for dark mode

I personally don't think this is a big issue, but you may want to update this for dark mode to be in-line with the link colour, so there are no two different reds. But if the intention is to have the Rails red here, that'd be fine too. White would work too.

| Visual inconsistency | Idea |
| -------------------- | ---- |
| Red hr divider is not the same color | White example |

---------------

@jathayde What does this line mean:

> IncludeMedia does not handle `prefers-color-scheme` at this time, so it was extracted.
Is it `@include media('>desktop')` these lines, meaning [this github repository](https://eduardoboucas.github.io/include-media/)?

Could you show me how it is not working correctly so I can avoid making the same mistake you ran into?

**Comment by jathayde** [comment]
@SleeplessByte Thanks! I'll take a stab at these as well - the footer is something I'll fix as I'm working on the layout for larger screens. 

On include media, it is that repository. It was not handling the `prefers-color-scheme` pitch into the @include method. Dark mode stuff is all in _dark.scss as overrides (which is imported and built into style.scss.

**Comment by AmandaPerino** [comment]
> On smaller screens (macbook air m1 screen) the guide is very narrow, below is a screenshot:
> 

Hi @JohnAnon9771 Hold tight, we are working on it.

**Comment by kissu** [comment]
Hey! 👋🏻
I do like the new redesign quite a lot, meanwhile I would like to be able to toggle it to my will.
Currently, it looks like the guide is properly following my `prefers-color-scheme` settings but I would like to have a given `dark` or `light` mode enforced at given times during the day (have something light during a lecture for a class for example).

A dirty solution would be to just use my Chrome devtools and let them open while I read/present the guides.
CleanShot 2025-02-12 at 21 04 22@2x

Or maybe download some kind of extension or have a shortcut to toggle it system-wide.
But none of those look good to know and I was wondering if we could maybe have a dark/light mode toggle? 🤗

**Comment by AmandaPerino** [comment]
Hi @kissu we will add it to the wishlist! This is not the first time this has been requested (I believe there is currently an open issue or discussion about it but I can't find it atm.) Thank you for the suggestion!

**Pull request merged**
