### PR TITLE
[ci skip] Instruct contributors to use 'ci skip' when submitting docs

### PR DESCRIPTION
**Pull request by adrianna-chang-shopify**
### Motivation / Background

Instruct contributors to use `[ci skip]` in pull request titles when submitting doc changes to avoid running the CI workflow when unnecessary.

### Checklist

Before submitting the PR make sure the following are checked:

* [X] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [X] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`

### CODE REVIEW

**Comment by skipkayhil** [comment]
It looks like this didn't run any of the Github actions either (like `mdl`)... I've noticed previously if you don't include `[ci skip]` in commit messages but _do_ include in the PR title that Github actions will run but not Buildkite. Maybe that's a better solution? Ex #48924

**Comment by adrianna-chang-shopify** [comment]
@skipkayhil thanks for flagging that -- we were trying to figure out where the `[ci skip]` was actually coming from (we were thinking [BuildKite](https://buildkite.com/docs/pipelines/skipping#ignore-a-commit)), but since all the actions are skipped, I think it's safe to assume it's from GH Actions instead (e.g. https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/).

What you're suggesting makes sense to me! I don't think we should be skipping _everything_, just the CI build 👍

**Comment by noahgibbs** [comment]
Ah, useful, I should be doing that. Thank you!

**Comment by zzak** [comment]
Adding this bit of context from Matthew a while back.

I was concerned that (eventually) when we use CI to build/deploy the docs, that we should avoid `ci skip`, but this was his response:

> Untrue (and probably should) -- we can opt out of its significance to Buildkite so the build always starts, then manually detect it during pipeline generation so we do the docs builds but skip all the rest

**Pull request merged**
