### PR TITLE
Fix: method name as per convention

### PR DESCRIPTION
**Pull request by priya-hinduja**
### Motivation / Background

This Pull Request has been created to improve Ruby on Rails guides documentation

### Detail

This Pull Request changes guides/source/active_record_callbacks.md

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [ ] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.
* [ ] CI is passing.

### CODE REVIEW

**Comment by priya-git-prog** [comment]
@jonathanhefner Please review

**Comment by priya-git-prog** [comment]
Please review

**Comment by jonathanhefner** [comment]
Thank you for opening a PR!  This looks like a purely cosmetic change, and the original seems fine to me.  We have a general policy of rejecting cosmetic changes.

Also, in the future, please refrain from pinging individual contributors for a review unless the contributor has already expressed interest in reviewing the change.  Thank you for understanding!

**Comment by priya-git-prog** [comment]
> Thank you for opening a PR! This looks like a purely cosmetic change, and the original seems fine to me. We have a general policy of rejecting cosmetic changes.
> 
> Also, in the future, please refrain from pinging individual contributors for a review unless the contributor has already expressed interest in reviewing the change. Thank you for understanding!

Thanks for your response & stating the policy & procedure. Hoping to contribute something substantial in future.

**Pull request closed without merging**
