### PR TITLE
Include the content of the flash in the auto-generated etag

### PR DESCRIPTION
**Pull request by dhh**
When you're using the flash, it's generally used as a conditional on the view. This means the content of the view depends on the flash. Which in turn means that the etag for a response should be computed with the content of the flash in mind. This does that by including the content of the flash as a component in the etag that's generated for a response.

### CODE REVIEW

**Comment by matthewd** [comment]
Could we just make it uncacheable? (Does the `etag` method have the ability to do that? Maybe it should.)

Doesn't seem worth keeping, vs likelihood of seeing a same-tagged request again.

**Comment by dhh** [comment]
I think it's fair that you can cache a flashed response. Lots of flashes are static confirmations that are likely to repeat.

**Comment by rafaelfranca** [comment]
Idea and implementation is fine to me. Tests are broken though, and the string quotes are not consistent. `rucobop -a actionpack/test/controller/flash_test.rb` to fix the style problem.

**Comment by claudiob** [comment]
I'm trying to understand the result of this commit.
Is the following interpretation correct?

If I see a page with a flash message, and I reload the page, then:

- if the page was cached, I still see the flash message
- if the page was not cached, I don't see the flash message

**Comment by matthewd** [comment]
@claudiob the flash will go away on refresh... the cached version (with the flash visible) will not be used for your second request (because the etag has changed)

**Comment by dhh** [comment]
@claudiob Here's the common issue this solves:

1. POST /messages
2. MessagesController#create adds redirect_to messages_url, notice: 'Message was added!'
3. User visits /messages/1
4. User goes back to /messages, and since the etag for that didn't consider the flash, it'll say that the page is "the same", even though on this visit we do not wish to display the flash. But the flash will be displayed because it was present in the version of /messages that was cached after step 2.

**Comment by claudiob** [comment]
@dhh Then that sounds great. 

What do you think about adding that example should be added to the CHANGELOG?
I think it might be helpful in writing the Release Notes for 5.1. Thanks!

**Comment by dhh** [comment]
Sure!

**Pull request merged**
