### PR TITLE
Add backend API doc for action text [ci skip]

### PR DESCRIPTION
**Pull request by fedeagripa**
### Summary

This is just a documentation pr improvement. It adds a brief explanation to point proper documentation for API developers wanting to use ActionText.

### CODE REVIEW

**Comment by st0012** [comment]
@fedeagripa thanks for the improvement 👍 Just to remind you that you should add `[ci skip]` in the  title for document-only PRs 😄

**Comment by fedeagripa** [comment]
@st0012 thanks a lot, I was looking for that as I read it somewhere but couldn't find it 🙌

**Review by javan — CHANGES_REQUESTED** [review]
I think this section can be clarified by outlining concrete steps rather than linking to Basecamp's API docs and a unit test.
1. Your API needs a separate endpoint for uploading files that creates an [`ActiveStorage::Blob`](https://github.com/rails/rails/blob/master/activestorage/app/models/active_storage/blob.rb) and returns its [`attachable_sgid`](https://github.com/rails/rails/blob/e10f01532e801174692f56175419e5fcbcdba36f/actiontext/lib/action_text/attachable.rb#L42-L44):

    ```json
    {
      "attachable_sgid": "BAh7CEkiCG…"
    }
    ```
2. Take that `attachable_sgid` and insert it in rich text content using an `<action-text-attachment>` tag:

    ```html
    <action-text-attachment sgid="BAh7CEkiCG…"></action-text-attachment>
    ```

**Comment by fedeagripa** [comment]
@javan fixed

**Pull request merged**
