### PR TITLE
test `include?`- fix typo

### PR DESCRIPTION
**Pull request by akshay-vishnoi**

### CODE REVIEW

**Comment by kaspth** [comment]
Thanks, but since it isn't documentation it's a cosmetic commit, which we don't accept.

**Comment by akshay-vishnoi** [comment]
@kaspth - I think its not cosmetic. Its a typo mistake. Wanna take a stab at it again?

**Comment by kaspth** [comment]
No thanks, we only accept typo fixes in documentation.

**Comment by rafaelfranca** [comment]
I'll reopen and merge but please :pray: focus on real problems not only typos.

**Pull request merged**
