### PR TITLE
Handle max_time edge cases for epoch times and add test

### PR DESCRIPTION
**Pull request by BlakeMesdag**
### Summary

Fixes the edge cases from #24520 as discussed with @fxn 
### Other Information

Benchmarks included in https://github.com/rails/rails/pull/24520#issuecomment-208979142 are approximately the same for this code (within 0.2x).

### CODE REVIEW

**Comment by fxn** [comment]
I had in mind something like this (untested):

```ruby
def max_mtime(paths)
  time_now  = Time.now
  max_mtime = nil

  paths.each do |path|
    mtime = File.mtime(path)

    # Ignore mtimes in the future.
    next if time_now.compare_without_coercion(mtime) < 0

    if max_mtime.nil? || max_time.compare_without_coercion(mtime) < 0
      max_mtime = mtime
    end
  end

  max_mtime
end
```

There are a number of details here:

* The implementation is still short and will return the max time for sure (or `nil`).
* The `next` line by itself emphasizes to the reader that we are filtering stuff out.
* In comparisons we put the (potential) left extreme to the left (receiver) and right extreme to the right, and adjust the comparison with 0 accordingly.
* Since the method is called `max_mtime` and it is dealing with mtimes, the variables have "mtime" in their name.

Guess it should run with comparable speed.

**Comment by fxn** [comment]
By the way, great catch over here.

Normally there won't be any times in the future, so the original code was going over the whole collection three times:

1. One loop to compute mtimes and build an array.
2. Another loop to reject (nothing) and build another array.
3. A third loop to compute the max.

And this method can be called with hundreds of paths in large apps.

Pheeww!!!

**Comment by BlakeMesdag** [comment]
Not much difference in performance, more readable too. Updated:
```bash
$ ruby map_reject_vs_memoized.rb 
Calculating -------------------------------------
         double_loop     6.015k i/100ms
     single_memoized     6.703k i/100ms
single_memoized_without_coercion
                        24.494k i/100ms
-------------------------------------------------
         double_loop     74.475k (±11.8%) i/s -    372.930k
     single_memoized     77.028k (±11.5%) i/s -    382.071k
single_memoized_without_coercion
                        469.834k (± 9.0%) i/s -      2.351M

Comparison:
single_memoized_without_coercion:   469834.4 i/s
     single_memoized:    77027.9 i/s - 6.10x slower
         double_loop:    74475.2 i/s - 6.31x slower
```

**Comment by fxn** [comment]
Excellent.

Now we can get rid of the first line as well I believe, the method returns `nil` for empty collections or collections whose mtimes are all in the future.

**Comment by BlakeMesdag** [comment]
Awesome, updated and should be good to go now.

**Comment by fxn** [comment]
Awesome, thanks Blake!

**Pull request merged**
