### PR TITLE
Add Composite Primary Keys guide to guides index

### PR DESCRIPTION
**Pull request by ghiculescu**
Adds https://github.com/rails/rails/pull/49205 to the index:

image
image

### CODE REVIEW

**Review by zzak — APPROVED** [review]
I thought it might make sense under "models" but that section is already considerably bigger than the other two parts of MVC.

**Comment by p8** [comment]
I think it's probably easier to scan if we rename some of these:
"Active Record Composite Primary Keys"
"Active Record Multiple Databases"

**Review by adrianna-chang-shopify — APPROVED** [review]
Thanks!

**Review by akhilgkrishnan — COMMENTED** [review]
This is great :)

**Comment by ghiculescu** [comment]
> I think it's probably easier to scan if we rename some of these: "Active Record Composite Primary Keys" "Active Record Multiple Databases"

Can do? Can you think of a shorter name for the Autoloading guide? Then I can make them all fit on one line.

**Comment by rafaelfranca** [comment]
Yes. Let's do that

**Comment by ghiculescu** [comment]
https://github.com/rails/rails/pull/49279

**Pull request merged**
