### PR TITLE
Fix typo in Active Record validations guide, chapter 2 — integer numbers (not integral)

### PR DESCRIPTION
**Pull request by jessevdp**
### Summary

I noticed the term 'integral number' in the validations guide. I'm assuming this was a typo? Tiny change 😁

### CODE REVIEW

**Comment by kamipo** [comment]
There is one more "integral" in the file. Can you fix it as well?

https://github.com/rails/rails/blob/4bbdad500cc6438141c668d5d8b8ad2534a46b5b/activemodel/lib/active_model/validations/numericality.rb#L163-L164

**Comment by kamipo** [comment]
hm... it seems the term "integral" meant "integer", but I'd say it is not very common in the codebase.
Replacing the term (and removing ", e.g. an integral value" part) is fine to me.

**Comment by jessevdp** [comment]
All good now? 😇

**Comment by kamipo** [comment]
Looks good to me. Can you squash the commits?
https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#squashing-commits

**Comment by jessevdp** [comment]
OK, the commits should be squashed. Let me know if you think the commit message is OK?

**Pull request merged**
