### PR TITLE
Support after_commit callbacks in transactional fixtures

### PR DESCRIPTION
**Pull request by brainopia**
Continuation of #18415 

Sorry, I've accidentally amended to a wrong commit. And then github wouldn't pickup any changes :sob:  
Had to create a new one.

This is a result of discussions with @arthurnn and @matthewd 
There is a question whether it's possible to merge `:joinable` and `:top_level` settings, but it can be discussed in a different request.  

cc @jeremy

### CODE REVIEW

**Comment by arthurnn** [comment]
Good job buddy!
:+1:

**Comment by arthurnn** [comment]
Interested to see what @jeremy things about this.

**Comment by jeremy** [comment]
Great simplification! :metal:

**Comment by san983** [comment]
:+1:

**Pull request merged**
