### PR TITLE
[FIX] Fix Activesupport json encode for hash with duplicate keys

### LINKED ISSUE #50481: Rails 7.1.0 has the inconsistency behavior for ActiveSupport::JSON.encode when encoding the Hash with symbols and strings of the same word as keys.
### Steps to reproduce

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", ENV['RAILS_VERSION']
end

require "active_support"

pp ActiveSupport::JSON.encode({ 'a' => 1, :a => 2 })
```

### Expected behavior

The result is `"{\"a\":2}"` when running the sample code with `RAILS_VERSION=7.0.8`.

### Actual behavior

The result is `"{\"a\":1,\"a\":2}"` when running the sample code with `RAILS_VERSION=7.1.0`.
This behavior is also the same with the current HEAD.

### Remarks

This inconsistency is introduced by ab01f9f3da837395550c0b20d3349aad9d314e38 contained in #48614, and this change is not recorded in the CHANGELOG.
However, the current behavior is consistent with the results of `JSON.dump` in Ruby itself.

```ruby
require 'json'
pp JSON.dump({ 'a' => 1, :a => 2 }) # => "{\"a\":1,\"a\":2}"
```

Therefore, I would like to know if this behavior should be corrected as an inconsistency or remain as a specification. If this is the current specification, I would be happy to see it described in the test.

### System configuration
**Rails version**: 7.1.0 

**Ruby version**: 3.3.0

### PR DESCRIPTION
**Pull request by maniSHarma7575**
Fix: #50481

### Motivation / Background

This Pull Request has been created because to fix #50481

The output for the hash is inconsistent when using `ActiveSupport::JSON.encode` with the duplicate key in `RAILS_VERSION=7.1.0`. Specifically, if we examine the result below, the key 'a' appears twice in the output JSON for the same key 'a'.

For `RAILS_VERSION=7.0.8`, it behaves as expected. Key is only once with later value.

For example:

```ruby
ActiveSupport::JSON.encode({ 'a' => 1, :a => 2 })
```

Result:

```json
"{\"a\":1,\"a\":2}"
```

This behavior is not observed in `RAILS_VERSION=7.0.8`.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #50481]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by maniSHarma7575** [comment]
cc: @byroot

**Comment by byroot** [comment]
Thanks, I backported it to 7-1-stable. We should fix it in flori/json too though.

**Comment by manishElitmus** [comment]
> Thanks, I backported it to 7-1-stable. We should fix it in flori/json too though.

Thanks for merging it @byroot T . This is my first contribution to rails. Looking forward to more.

Yeah, I'll do it in `flori/json` as well.

**Comment by maniSHarma7575** [comment]
> Thanks, I backported it to 7-1-stable. We should fix it in flori/json too though.

Thanks for merging it @byroot T . This is my first contribution to rails. Looking forward to more.

Yeah, I'll do it in `flori/json` as well.

**Comment by maniSHarma7575** [comment]
> Thanks, I backported it to 7-1-stable. We should fix it in flori/json too though.

@byroot I have fixed it in flori/json as well. Could you kindly review it? 

[https://github.com/flori/json/pull/564](https://github.com/flori/json/pull/564)

**Comment by jhawthorn** [comment]
Sorry I missed this change at the time, I don't think we should have merged this. At some point we have to have a limit on how much double checking Rails does of the user's input and I think this is well within the area we should be "garbage in/garbage out".

Being forced to support this really paints us into a corner in how we can implement this.

I'd also argue that I'd actually prefer `{ 'a' => 1, :a => 2 }` be turned into the questionably valid JSON as `"{\"a\":1,\"a\":2}"` rather than either `"{\"a\":1}"` or `"{\"a\":2}"` as it would allow me to see that there is an issue with my program rather than hiding the error and making an arbitrary choice.

**Comment by byroot** [comment]
Yeah feel free to revert.

**Pull request merged**
