### PR TITLE
converts UnknownAttributeError to kwargs

### PR DESCRIPTION
**Pull request by kyledecot**
I read that Rails 5 will have widespread use of keyword arguments so here's a small contribution

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Thank you but we don't accept this kind of pull request. Internal code will not be converted.

**Comment by kyledecot** [comment]
@dhh, @rafaelfranca  might I ask why the internal code won't be converted? I would think the *internal* parts of rails would benefit the most from keyword arguments as they're the most abstracted. Adding keyword arguments make it more intention revealing in my opinion.

**Comment by rafaelfranca** [comment]
Because there is no need to change the git history just to change syntax. It just make harder to see real changes and also find cause of bugs.

**Comment by yawboakye** [comment]
@rafaelfranca Where are the improvements supposed to happen if the internals won't change. By @dhh's tweet (https://twitter.com/dhh/status/548198789954023424) I supposed it was the Rails internals that were about to shift in favor of the new goodies in Ruby 2.2

**Comment by rafaelfranca** [comment]
@yawboakye mostly in public facing APIs like HTML helpers, test helpers, etc. See https://github.com/rails/rails/pull/18323 for an example.

**Comment by kyledecot** [comment]
Diving down the rabbit-hole and trying to debug the internals of Rails has always been a pain for me. I think that we should open to making the entire codebase as expressive and intention revealing as possible (this is ruby after all).

I think at the very least the idea should be open for discussion. Would you mind if I opened a thread on [Ruby on Rails: Core](https://groups.google.com/forum/#!forum/rubyonrails-core)?

**Comment by rafaelfranca** [comment]
I don't mind at all but I don't believe changing the syntax of the method will make a huge difference in the expressivity of Rails internals. For example, in your PR I could take the same information just looking the method definition that is in the same file.

**Comment by rafaelfranca** [comment]
Also there are a lot of things to consider before doing this kind of change. For example: when it is worth to change to use kwags?

In the end will be just matter of taste, and this fall in the cosmetic change category, and [we don't accept cosmetic changes](https://github.com/rails/rails/pull/13771#issuecomment-32746700).

**Comment by kyledecot** [comment]
I'll admit that my example might be a little simplistic but I just don't want it to set a precedent for using kwargs for *only* public APIs. 

It's true I could look at the definition of the method (in *this* case it happens to be in the same file) but just one more step down the rabbit hole that could be avoided.

**Comment by rafaelfranca** [comment]
Me neither, I just think that is not worth to change existing code to use
kwargs without a really strong reason given the downsides of having this
kind of cosmetic change in a large code base like Rails.

**Pull request closed without merging**
