### PR TITLE
If specify `strict: :default` explicitly, do not set sql_mode.

### PR DESCRIPTION
**Pull request by kamipo**
Related with https://github.com/rails/rails/issues/17370.

### CODE REVIEW

**Comment by kamipo** [comment]
I squashed this PR. This PR is no longer change the default behavior.

**Comment by chancancode** [comment]
I believe this needs a CHANGELOG entry, something like [this](https://github.com/rails/rails/issues/17370#issuecomment-106159323) would be very helpful to understand how it works! :)

**Comment by zzak** [comment]
Should this be backported?

/cc @rafaelfranca @matthewd

**Comment by rafaelfranca** [comment]
Is there any workaround? If so it is better to not backport.

**Pull request merged**
