### PR TITLE
rm unused require

### PR DESCRIPTION
**Pull request by vipulnsward**

### CODE REVIEW

**Comment by schneems** [comment]
Travis is failing.

Can you run this test by itself with the removed require?

**Comment by vipulnsward** [comment]
Yes. There were some DB test failures from this file, which have stopped failing now. 
https://travis-ci.org/rails/rails/builds/126799949
Need to check why railties tests are failing, but they are unrelated to this, and hard to reproduce.

**Comment by kbrock** [comment]
:+1: thanks. my bad

**Comment by jeremy** [comment]
Squashed 3458ad92a196983550f6d680ad1ae58bce386fde

**Pull request closed without merging**
