### PR TITLE
Run ActiveRecord -> ActiveJob integration tests in CI

### PR DESCRIPTION
**Pull request by ghiculescu**
In https://github.com/rails/rails/pull/42452#issuecomment-861283014, @smt116 pointed out that activerecord's Active Job integration tests are skipped in CI.

This PR moves them into the `test/cases` directory, so they are run. Originally I was going to add a new CI task but given they run pretty quickly I don't think that's worth the overhead.

### CODE REVIEW

**Comment by ghiculescu** [comment]
image
confirmed relevant tests are no longer skipped 👍

**Comment by rafaelfranca** [comment]
This PR is wrong. The Active Job tests on Active Record should not run int he same process as the regular Active Record tests.

**Comment by rafaelfranca** [comment]
Reverted

**Comment by ghiculescu** [comment]
@rafaelfranca should they run as a separate process? I can do a PR for that instead. Currently I don't think they are running at all.

**Comment by rafaelfranca** [comment]
They should be in a separated process, in the same way that the actionview:integration:active_record run.

**Comment by rafaelfranca** [comment]
It seems we only need to change the Rakefile like this: https://github.com/rails/rails/blob/main/actionview/Rakefile#L15

**Comment by rafaelfranca** [comment]
We also need to run the performance tests for encryption.

**Comment by ghiculescu** [comment]
Cool. I can have a go at that. Out of curiosity, what's wrong with the approach in this PR?

**Comment by rafaelfranca** [comment]
It will make the Active Job integration with Active Record to be loaded in the others Active Record tests, causing a leak depending in the orders the tests are run.

**Pull request merged**
