### PR TITLE
use `messages` instead of deprecated `ActiveModel::Errors#[]=` method [ci skip]

### PR DESCRIPTION
**Pull request by y-yagi**
refs: https://github.com/rails/rails/commit/3c750c4c6c4d3c2e67865bc43a99010fa8b6c7a6

### CODE REVIEW

**Comment by rafaelfranca** [comment]
We should use `add` instead message. Could you change it?

**Comment by rafaelfranca** [comment]
Fixed

**Comment by seuros** [comment]
sorry, i didn't see your message.

**Comment by y-yagi** [comment]
Oh sorry. And thanks for fixed!

**Pull request merged**
