### PR TITLE
Moving ActiveStorage routes into engine.rb and prepending them

### PR DESCRIPTION
**Pull request by GBH**
### Summary

We can't leave routes for ActiveStorage in `config/routes.rb` as they load after main application routes (or just randomly if you have more engines structured like that). Issue is, if I have a globbing route in my application like this: `get '*' => "foo#bar"` it will make ActiveStorage routes inaccessible. 

This problem is pretty obvious and visible with this: #30771 

It's similar to what we have happening with mailer previews. Those routes are correctly prepended via railtie (I had to fix that too in the past: #17896)

### CODE REVIEW

**Comment by georgeclaghorn** [comment]
Why do the routes have to be moved into `engine.rb`? Can we not prepend them from `routes.rb`?

**Comment by GBH** [comment]
@georgeclaghorn I'm not familiar with internals on how routing is getting constructed, but you can't replace `.draw` with `.prepend` or `.append` in `routes.rb` file. I'm guessing it has something to do with loading order.

**Comment by GBH** [comment]
Ok, I need input on this one. There's also `config.railties_order` that also controls routes loading order. However, that is global config. ActiveStorage is the only engine in Rails core that has its own routes.rb file. So without changing anything I'd have to do this in my app: 

```
config.railties_order = [ActiveStorage::Engine, :all, :main_app]
```

That seems like something I'd waste several days figuring out. This PR seems to fix the problem without re-engineering a lot of stuff.

**Comment by GBH** [comment]
Had to create new commit as i messed up merging with upstream. Codeclimate got confused, but it was passing before.

@rafaelfranca @georgeclaghorn do you mind taking a look at this PR? It's a showstopper for https://github.com/comfy/comfortable-mexican-sofa as it relies on globbing route and also needs ActiveStorage working.

**Comment by rafaelfranca** [comment]
I don't think we should merge this in. If you had any other engine that defines routes you would have the same problem, so you are chasing your own tail. I'd say that if your application make the engines routes to not be accessible you should change the railties order.

**Comment by GBH** [comment]
That's true about other engines. Can't control other engines other than with `railties_order`. Closing.

**Comment by joshjordan** [comment]
I suggest this be re-opened. Broken by default is not a good state to be in. This especially true since there is 0 documentation mentioning the `railties_order` fix, but a quick google will show hours and hours of frustration from people who haven't found this buried PR.

**Pull request closed without merging**
