### PR TITLE
Add down only and migrating helpers to migration

### PR DESCRIPTION
**Pull request by goulvench**
### Motivation / Background

In migrations, the `up_only` helper and the `reverting?` predicate allow constraining operations in either direction. Adding `down_only` and `migrating?` allows defining blocks that need to run when reverting, or running one-liners when migrating without using double negatives. Plus, you no longer need to remember which ones exist and which ones don't.

Fixes #48245 

### Detail

This Pull Request adds `down_only` and `migrating?`.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change.
* [x] Commit message has a detailed description of what changed and why.
* [x] Tests are added or updated if you fix a bug or add a feature. (Original methods are not tested)
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Review by eileencodes — CHANGES_REQUESTED** [review]
Hi @goulvench thanks for opening a PR. Since `down_only` is not using `migrating?` this is implementing two separate features and therefore should be split into 2 PRs. In addition, these new features need to have tests implemented. You can use the `activerecord/test/cases/invertible_migration_test.rb` file to implement tests. Thanks!

**Comment by goulvench** [comment]
Hi @eileencodes, I've simplified the code, added tests and merged into one changelog message. The commit now shows how both changes tie together I believe. Let me know if these should be split into separate PRs instead.

I'm looking into adding tests for `reverting?` and `migrating?`, but I couldn't find any for `reverting?`, does that mean that it was considered too low-level to warrant testing?

**Comment by jeromedalbert** [comment]
@goulvench Looks like you added all necessary tests. Are you still interested in moving this PR forward? If so, your best bet would be to make 2 separate PRs as Eileen asked. Also this current PR currently has conflicts.

**Comment by goulvench** [comment]
@jeromedalbert I'm still interested in this, the lack of symmetry between `up_only` and `reverting?` still feels a little un-railsy to me :-)
I added tests but got busy with client work while waiting for answers that didn't come, so this got pushed to the back-burner, until it eventually fell behind the stove.

I still feel that despite being separate methods, this is really one atomic change, fixing the symmetry to avoid double negations when a block needs to run when only when reverting, or a one-liner needs to happen only when migrating. 
- `up => up_only`
- `down => ??`
- `?? => reverting?`

**Comment by goulvench** [comment]
As requested, I'm closing this pull request in favor of two separate ones:
- #53209 
- #53210

**Pull request closed without merging**
