### PR TITLE
Consistently use named route parameters

### PR DESCRIPTION
**Pull request by Ecco**
### Summary

Restful routes support using a [custom parameter](https://guides.rubyonrails.org/routing.html#overriding-named-route-parameters). For instance:

```ruby
resources :videos, param: :identifier
```

Unfortunately, this parameter is then *completely ignored* when using the associated route helper:

```ruby
v = Video.create(identifier: "foobar")
app.video_path(v) # This would return "/videos/1"
```

This patch makes it consistent:
```ruby
app.video_path(v) # This now returns "/videos/foobar"
```

### Rationale

The recommended way to achieve this is by implementing the `to_param` method. I think this is broken for several reasons:

* The routing (which I think is sort of a "control" problem from an MVC standpoint) is mixed into the model. I think this is not a good separation of concerns.
* When a named param is used we still need to implement `to_param` even though Rails could make a smart guess (that's actually the case even in the [doc's example](https://guides.rubyonrails.org/routing.html#overriding-named-route-parameters), where the `to_param` wouldn't be needed at all with this patch).
* Using `to_param` simply prevents more complex routing since you cannot use two different routing strategies for one given model (since there'll be only one `to_param` method). For example, it's currently not possible to use routes such as `/videos/:title` and  `/admin/videos/:id` to manipulate the same Video model.

### CODE REVIEW

**Comment by Ecco** [comment]
Hi there! I don't know if anyone's reading this, but I'd love to have feedback on this! I think this PR would be a nice addition to rails, helping making custom-params routes a lot easier to handle 😄

**Comment by jonathanhefner** [comment]
This is an interesting idea.  It could potentially break existing apps though, so it would probably need to be behind a feature flag.  Also, I believe the param value must be a string, so this feature couldn't be used with numeric fields (e.g. alternative numerical IDs) unless we also add a `to_s`.

**Comment by Ecco** [comment]
> This is an interesting idea.

Thanks!

> It could potentially break existing apps though

It might indeed. That being said, in the suggested patch I didn't discard the [to_param](https://github.com/rails/rails/blob/60ef07093d9023568ccbbd34e862b40395ec02f4/actionpack/lib/action_dispatch/routing/route_set.rb#L234) call but kind of worked alongside it. So it's quite likely that existing apps, overriding `to_param` as recommended by the doc, wouldn't be impacted.

>  I believe the param value must be a string, so this feature couldn't be used with numeric fields, unless we also add a `to_s`.

Seems like you're right indeed! The [default to_param](https://github.com/rails/rails/blob/4fe1452534540851461e99b3d0fecaf27931ab93/activerecord/lib/active_record/integration.rb#L59) implementation makes sure to return a string, so I update the PR. Thanks!

**Comment by jonathanhefner** [comment]
> It might indeed. That being said, in the suggested patch I didn't discard the [to_param](https://github.com/rails/rails/blob/60ef07093d9023568ccbbd34e862b40395ec02f4/actionpack/lib/action_dispatch/routing/route_set.rb#L234) call but kind of worked alongside it. So it's quite likely that existing apps, overriding `to_param` as recommended by the doc, wouldn't be impacted.

Consider that existing apps may already use the `param` option, and that `model.to_param` may return something different than `model.send(param).to_s`.  For example:

```ruby
resources :places, param: :coordinates

class Place < ApplicationRecord
  def to_param
    coordinates.join(",")
  end
end

# BEFORE
place_path(Place.new(coordinates: [1, 2]))  # => "/places/1,2"

# AFTER
place_path(Place.new(coordinates: [1, 2]))  # => "/places/[1, 2]"
```

**Comment by Ecco** [comment]
That's a good point, thanks @jonathanhefner ! There are probably several ways to work around this:
* Don't make the new behavior the default, at least not upfront. That's probably what you meant by "feature flag".
* We probably could make `to_param` have higher precedence if it's been defined, since people aware of the new feature wouldn't have any reason to define `to_param` anyway.

That being said at this point I really wanted to have a discussion on the feature itself more than on the code. I'm convinced that'd be a great addition to Rails, and I was wondering if maintainers think that way too.

I hope they do, in which case I'd be happy to help make it happen!

**Comment by Ecco** [comment]
No, it's not stale. I'd really like to get some feedback on this though… 😢

**Comment by Ecco** [comment]
Still not stale, AFAIK.

**Pull request closed without merging**
