### PR TITLE
Default to creating git pre-commit

### PR DESCRIPTION
**Pull request by faqndo97**
Now that we have Rubocop by default, it's worth it to have a basic git pre-commit config by default for new rails apps unless it's created with `--skip-rubocop` flag.

### CODE REVIEW

**Comment by dhh** [comment]
Nice! This doesn't install on new app, though, and it doesn't seem to return the right exit code to stop the commit from happening if there are failures.

**Comment by faqndo97** [comment]
@dhh Thank you for noticing the omission of `exception: true` when running the command. Regarding the issue 'This doesn't install on new app', I have built the project locally and created a new Rails app using it. The project started with the correct code in `bin/setup`, and after running it, the pre-commit hook is working. What am I missing? Thanks.

**Comment by koic** [comment]
The execution of the rubocop command takes time proportional to the size of the source code. This could mean that constantly running `rubocop` command in pre-commit might slow down the development rhythm and could make the development experience less comfortable.

Alternatively, if using git hooks, setting it up for `pre-push` instead of `pre-commit` might be more suitable.

Personally, I think using the RuboCop built-in LSP introduced in RuboCop 1.53 for early offenses detection, and running `rubocop` command when it's convenient, seems to be a better approach:
https://docs.rubocop.org/rubocop/usage/lsp.html

This is just my personal view, but I think the trade-off with development rhythm is important.

**Comment by dhh** [comment]
Tried this yesterday and agree with @koic. It’s very nice to get early warnings but it’s too slow. Would be completely unusable on large codebases. I think it’s good enough to have this as part of CI. Thanks for exploring it though ✌️

**Comment by faqndo97** [comment]
@koic, thank you for the feedback. I agree that running Rubocop on large projects can be slow. However, even with editor integrations, I believe it's worth considering an alternative approach for a git-hook where rubocop runs only on the .rb files that have been changed. This method is usually fast. In cases where a developer is making substantial changes involving many .rb files, it can be skipped by adding the -n flag to the git commit command or to the git push to bypass the run. So, this approach should be effective for both pre-commit and pre-push scenarios. I'm open to either, but I do think it's a valuable additional check before running CI. @dhh, what are your thoughts?

**Comment by dhh** [comment]
That’s a good idea. Let’s try.

**Comment by ignatiusreza** [comment]
why not adopt existing community proven solution like [husky](https://www.npmjs.com/package/husky) and [lint-staged](https://www.npmjs.com/package/lint-staged)

**Comment by dhh** [comment]
@ignatiusreza Those are npm packages? Rails does not use npm by default, and it won't. Besides, not interested in adding dependencies for something this small. That's an npm habit 😄

**Comment by koic** [comment]
Using git hooks still results in a delay due to the time it takes to start the `rubocop` command process. Running the `rubocop` command without the server mode option requires initiating the `rubocop` process with each git commit, which is slow. To address this issue, RuboCop provides the server mode, but it has several weak points. 
Therefore, for editor integration, it is recommended to use the previously mentioned LSP mode for faster feedback.

**Comment by faqndo97** [comment]
@dhh Just updated the PR with the new hook implementation. That's an implementation for pre-commit. If we want a pre-push I need to make a few changes but most of it will preserve so it's a good starting point to discuss. Most of the code it's an extraction from https://github.com/sds/overcommit and simplified to have something minimal for new rails apps.

**Comment by koic** [comment]
I've given it some more thought. Additionally, as indicated in https://github.com/rails/rails/issues/50453, LSP is considered superior for modern development practices, so the concurrent use of git hooks might be redundant. LSP and CI are likely sufficient for most RuboCop (Linter and Formatter) use cases, suggesting that including git hooks as a default may not ideal for the development experience, IMHO.

**Comment by rafaelfranca** [comment]
Agree with @koic. With our work on devcontainers bringing the Ruby LSP by default and with #50453, running Rubocop on githooks will not only be redundant but an inferior developer experience and a bad default in my opinion. I think we should close this.

**Comment by dhh** [comment]
Aight, sounds good to me. Let's pursue this via the LSP, and we already now have the default GH action too.

**Pull request closed without merging**
