### PR TITLE
action mailer test cases protected method can be `# :nodoc:` [ci skip]

### PR DESCRIPTION
**Pull request by Gaurav2728**

### CODE REVIEW

**Comment by claudiob** [comment]
Hello @Gaurav2728 :grimacing: 

Would you mind clarifying what is the purpose of this PR? Thanks!

**Comment by Gaurav2728** [comment]
@claudiob  these methods may not require for `http://api.rubyonrails.org/`.  If you may not agree can you  explain how it can usefull for that.

**Comment by sgrif** [comment]
Seems reasonable. These don't appear to be part of the public test API, or if they are we should document their purpose. Please add `[ci skip]` to the commit message for doc only changes in the future.

**Comment by sgrif** [comment]
Hm. It looks like you did. I don't know why CI ran... :\

**Comment by sgrif** [comment]
Ah I see. You put it in the PR message. It needs to be in the commit message.

**Comment by Gaurav2728** [comment]
@sgrif Thanks :yellow_heart:   ...i want to merely get info about `# :nodoc:` will be send as PR or directly push into docrails.

**Pull request merged**
