### PR TITLE
Use default order of PathResolver::EXTENSIONS for sort templates

### LINKED ISSUE #37556: OptimizedFileSystemResolver doesn't sort views considering request format
### Steps to reproduce

1. Create a new rails 6 project: `rails new bug`
2. Generate a controller for users#index: `rails generate controller users index`
3. Add a json view for index: `echo "json.foo 'bar'" > app/views/users/index.json.jbuilder`
4. Run development server: `rails s`
5. Make a request for users with accepting json format:

  ```bash
    curl 'http://localhost:3000/users' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'X-Requested-With: XMLHttpRequest'
  ```
6. Confirm that response have the **html** content instead of **json** content.

### Expected behavior

The request should prioritize the format passed by `Accept: application/json, text/javascript, */*; q=0.01` header and render the `index.json.jbuilder` view.

### Actual behavior

The `index.html.erb` view is rendered.

### System configuration
**Rails version**:
6.0.0

**Ruby version**:
2.5.5

### Additional Information

With rails 5.2.3 it works perfectly. But [rails 6 uses faster globs for template resolving](https://github.com/rails/rails/pull/33860) which sorts files [without prioritizing format](https://github.com/rails/rails/pull/33860/files#diff-40f2a5bcf9edfd65a8efe42a05c53736R389).

### PR DESCRIPTION
**Pull request by iagopiimenta**
Fixes #37556

### CODE REVIEW

**Review by st0012 — APPROVED** [review]
Looks good 👍

**Comment by rafaelfranca** [comment]
Can you add a CHANGELOG entry?

**Comment by iagopiimenta** [comment]
> Can you add a CHANGELOG entry?

done!

**Comment by jhawthorn** [comment]
Thanks! Merged as https://github.com/rails/rails/commit/7abcba6909855e71853308825698e57a22d1238c

**Pull request closed without merging**
