### PR TITLE
Return uniform active support timezone name

### PR DESCRIPTION
**Pull request by sergioisidoro**
### Summary
**Disclaimer**: This is my first contribution to rails

In ActiveSupport::Timezone we have the following comment
```
# * Retrieve and display zones with a friendlier name
#   (e.g., "Eastern Time (US & Canada)" instead of "America/New_York").
```
however that is not the case, and the class returns whatever name it has been provided during the initialisation without any extra "friendliness"

I wrote this PR as a proposal, but the assumption that name should return either one or the other is spread around other tests, and most likely breaks some expected behaviours in gems.

The alternative could just be changing the documentation, and accept inconsistent output.

##### Expected behavior
```
helsinki_name = ActiveSupport::TimeZone["Helsinki"]
helsinki_tz = ActiveSupport::TimeZone["Europe/Helsinki"]
assert_equal helsinki_name.name, helsinki_tz.name  # --> Helsinki
```

##### Actual behavior
```
helsinki_name = ActiveSupport::TimeZone["Helsinki"] 
helsinki_tz = ActiveSupport::TimeZone["Europe/Helsinki"]
helsinki_name.name # --> "Helsinki"
helsinki_tz.name #  --> "Europe/Helsinki"
```

### Other Information

This issue can cause a lot of confusion.
When using https://github.com/kbaum/browser-timezone-rails for example, 

An ActiveRecord with a datetime field tz name will return different formats for the same value depending if it's being ran on the Console or in the browser
`record.time.time_zone.name`

### CODE REVIEW

**Review by albertoalmagro — APPROVED** [review]
@sergioisidoro I like it! Good catch! 👏 Thanks!

**Comment by pixeltrix** [comment]
Hmm, probably going to break someone's app but I guess doing it for Rails 6.0 will be okay. We could add a config option that ensures upgrading apps get the old behaviour until they change the setting and then remove that config option in 6.1 but I think that may be too much - do you agree @rafaelfranca ?

One additional thing, If we're going to always enforce the mapping then we should provide a convenience method to get the TZ id from the zone info, e.g:

``` ruby
def id
  tzinfo.name
end

tz = ActiveSupport::TimeZone["Helsinki"]
tz.id # => Europe/Helsinki
```

It's still my preference that all these mappings and friendly names should really be part of the locale but when we looked at it before the Rails boot process initialised locales after the mapping was required so wasn't really possible. May take another look at that for Rails 6.

@sergioisidoro can you please add the convenience method I outlined above along with a test for it and update the CHANGELOG, thanks. Once you've done that and squashed your commits I'll merge - thanks for the PR 👍

**Comment by sergioisidoro** [comment]
So, I've been doing some basic reading, and IANA calls the timezone **name** the following 

> Names normally have the form AREA/LOCATION, where AREA is the name of a continent or ocean, and LOCATION is the name of a specific location within that region. North and South America share the same area, 'America'. Typical names are 'Africa/Cairo', 'America/New_York', and 'Pacific/Honolulu'.

[From iana database](https://www.iana.org/time-zones) 

However, [Google maps API](https://developers.google.com/maps/documentation/timezone/intro) uses
> **timeZoneId:** a string containing the ID of the time zone, such as "America/Los_Angeles" or "Australia/Sydney". 

> **timeZoneName:** a string containing the long form name of the time zone. This field will be localized if the language parameter is set. eg. "Pacific Daylight Time" or "Australian Eastern Daylight Time"

The same as [timeanddate.com](https://www.timeanddate.com/time/zones/), using `name` for the long version.

[Java ICU](http://icu-project.org/apiref/icu4j/com/ibm/icu/util/TimeZone.html) Java library calls Europe/Helsinki the "canonical" name, and "Helsinki" the display name. So I guess either of the options is acceptable. 

I was wondering, however, since Ruby TZInfo has the `name` attribute according to the iana database, would it make more sense, for the sake of consistency, to have the following behaviour:

```
helsinki_name = ActiveSupport::TimeZone["Helsinki"]
helsinki_name.name # > "Europe/Helsinki"
helsinki_name.description # > "Helsinki"
```

**Comment by rafaelfranca** [comment]
I'm almost sure this would break shopify so a patch with configuration option is safer to me.

@JuanitoFatas since you worked recently on related things do you think this would break Shopify's behavior?

**Comment by JuanitoFatas** [comment]
At Shopify we are relying on `tzinfo.name`:

```ruby
ActiveSupport::TimeZone.all.map do |time_zone|
  time_zone.tzinfo.name
end.uniq
```

I think this Pull Request is a good step forward 👍

**Comment by sergioisidoro** [comment]
Haven't had much time to get this forward. Spent a couple of hours trying to understand how deprecation settings were made without much luck. 
I now got some help and I think I can move this forward. 
I'll try to push something this week.

**Comment by sergioisidoro** [comment]
Ok, this has stalled. I will try to get this forward during the holidays 🎅

**Comment by sergioisidoro** [comment]
Ok, this now has some way of retrieving the id of the timezone according to https://github.com/rails/rails/pull/34304#issuecomment-433794095 and https://github.com/rails/rails/pull/34304#issuecomment-434849594 as well as a deprecation warning. 

However I have no idea how to test deprecated behaviors alongside the new ones, and how to add a default to the configurations :/ If anyone could point me out where to start looking, I would be grateful.

**Pull request closed without merging**
