### PR TITLE
Use :git for specifying dependencies from github with https protocol

### PR DESCRIPTION
**Pull request by prathamesh-sonpatki**
### Summary
- This is required for bundler 1.13.0 because of which lot of specs are
  failing on Travis CI.
- Similar to https://travis-ci.org/rails/rails/jobs/158905576#L559

### CODE REVIEW

**Comment by prathamesh-sonpatki** [comment]
There is one more test failure happening for following test:

``` ruby
    def test_bin_setup_output
      Dir.chdir(app_path) do
        app_file "db/schema.rb", ""

        output = `bin/setup 2>&1`
        assert_match(<<-OUTPUT, output)
== Installing dependencies ==
Resolving dependencies...
The Gemfile's dependencies are satisfied

== Preparing database ==
Created database 'db/development.sqlite3'
Created database 'db/test.sqlite3'

== Removing old logs and tempfiles ==

== Restarting application server ==
        OUTPUT
      end
    end
```

``` 
 1) Failure:
ApplicationTests::BinSetupTest#test_bin_setup_output [test/application/bin_setup_test.rb:41]:
--- expected
+++ actual
@@ -1,4 +1,5 @@
 "== Installing dependencies ==
+Resolving dependencies...
 The Gemfile's dependencies are satisfied
 
 == Preparing database ==
```

Do we need to test output of `bin/setup`? cc @senny as you added this test.

**Comment by guilleiguaran** [comment]
Let's update the existing test for bin/setup output 👍

**Comment by kirs** [comment]
👍 this is the issue that causes other PRs to be red now.

**Comment by connorshea** [comment]
Plus the github helper uses HTTP rather than HTTPS, less than ideal.

**Comment by arthurnn** [comment]
Is this a bundler issue? or broken behavior of some sort?
cc @indirect

**Comment by arthurnn** [comment]
I merged https://github.com/rails/rails/pull/26450 which should fix the CI issue..
I wonder if bundler should use `https` when using the `github: ` option.
Thoughts @indirect , should I open an issue there?

Thanks @prathamesh-sonpatki

**Comment by connorshea** [comment]
@arthurnn there's an open issue for that, won't be fixed until Bundler 2.0 due to it being a breaking change.

**Comment by connorshea** [comment]
@arthurnn see https://github.com/bundler/bundler/pull/4109 among various other issues/PRs.

**Comment by prathamesh-sonpatki** [comment]
@arthurnn :+1: but I think this needs to be merged as well as locally if you upgrade to bundler 1.13 and run bundle install on master you will see following warning.

```
prathamesh ~/Projects/sources/rails 2.4.0 (prathamesh-sonpatki/rails) -> master
$ bundle -v
Bundler version 1.13.0

prathamesh ~/Projects/sources/rails 2.4.0 (prathamesh-sonpatki/rails) -> master
$ bundle
The git source `git://github.com/sass/sass.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
The git source `git://github.com/matthewd/rb-inotify.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
The git source `git://github.com/resque/resque.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
The git source `git://github.com/collectiveidea/delayed_job.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
The git source `git://github.com/QueueClassic/queue_classic.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
The git source `git://github.com/collectiveidea/delayed_job_active_record.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
Resolving dependencies...
```

**Comment by guilleiguaran** [comment]
@prathamesh-sonpatki I think you're right, this is useful as is for rails core devs.

**Comment by arthurnn** [comment]
👍  make sense.. thanks everyone

**Comment by vipulnsward** [comment]
@guilleiguaran this needs a backport.

**Comment by rafaelfranca** [comment]
Another way to fix this and the version I prefer is to override the github function. We can also set `github.https` config but this will not work for all machine. I'll revert this commit and fix it properly.

**Comment by rafaelfranca** [comment]
Fixed in 12d5c21

**Pull request merged**
