### PR TITLE
Added options for rails update task

### PR DESCRIPTION
**Pull request by sivagollapalli**
@carlosantoniodasilva Added options for `rails:update` rake task. If user executes `bundle exec rails:update skip_active_record=true` then it automatically comments active record related configuration while updating.

Ref discussion thread: https://groups.google.com/forum/#!topic/rubyonrails-core/VuC8ht0kaA8

### CODE REVIEW

**Comment by senny** [comment]
Doesn't this happen with every `--skip-XYZ` option out there? Would be nice to have a solution that works with all of them, not just `--skip-active-record`.

**Comment by sivagollapalli** [comment]
@senny Thanks for your reply. I would try to make it work with every option.

**Comment by sivagollapalli** [comment]
@senny I made changes as you specified. Now we can run `bundle exec rails:update -- --skip-active-record` or `bundle exec rails:update:configs -- --skip-active-record` to skip active related config. Could you please check and tell me whether am I right path or not? If yes, then I will continue to add remaining options as discussed.  Please let me know your comments.

**Comment by sivagollapalli** [comment]
@senny I think I have added all necessary options we need while updating rails version. Do let me know if I missed anything.

**Comment by senny** [comment]
Duplicating the option parsing logic doesn't seem like a maintainable way to approach this. This will lag behind the support options very quickly. I wonder if there is a good way to reuse the generator flags from `rails new`. @rafaelfranca does anything come to mind?

**Comment by rmacklin** [comment]
Should this PR be closed because https://github.com/rails/rails/pull/29645 has been merged?

**Pull request closed without merging**
