### PR TITLE
Credentials edit with config paths

### LINKED ISSUE #37631: credentials:edit/show commands ignores custom content_path and key_path
### Steps to reproduce
In `application.rb`, configure custom credentials content_path and key_path:
```
config.credentials.content_path = Rails.root.join('config', "credentials.custom.yml.enc")
config.credentials.key_path = Rails.root.join('config', "master.custom.key")
```

Rename your existing credentials files to the new names we've just configured.
`rails s` and `rails c` should work fine with your existing credentials.

### Expected behavior
`rails credentials:edit` and `rails credentials:show` should work with the custom paths, but it doesn't.

### Actual behavior
`rails credentials:edit` will generate new credentials files (`credentials.yml.enc` and `credentials.yml.enc`) instead of editing our current credentials with custom paths.

`rails credentials:show` also ignores custom paths.

### System configuration
**Rails version**: 6.0.0

**Ruby version**: 2.6.5

### PR DESCRIPTION
**Pull request by brianthoman**
### Summary
Fixes #37631

Documentation ([here](https://github.com/rails/rails/blob/8544c9c23687964ab754c06a7745215a5369a4e0/railties/lib/rails/commands/credentials/USAGE#L72-L73) and [here](https://github.com/rails/rails/blame/8544c9c23687964ab754c06a7745215a5369a4e0/guides/source/configuring.md#L144-L146)) states that the credentials content and key paths are configurable via `config.credentials.content_path` and `config.credentials.key_path`. While these config variables appear to be respected by the web application, they are not used by the `credentials:edit` or `credentials:show` commands.

#### Current behavior:
* credentials commands with no environment specified use 
  * `config/master.key` and `config/credentials.yml.enc`
* credentials commands with an environment option use 
  * `config/credentials/$environment.key` and `config/credentials/$environmnet.yml.enc`

#### This pull request aims to implement the following behavior:
* credentials commands with no environment specified use 
  * `key_path` and `content_path` configured in config/application.rb
  * `config/master.key` and `config/credentials.yml.enc`
* credentials commands with an environment option use 
  * `key_path` and `content_path` configured in config/environments/$environment.rb
  * `key_path` and `content_path` configured in config/application.rb
  * `config/credentials/$environment.key` and `config/credentials/$environmnet.yml.enc`

### CODE REVIEW

**Comment by xbri** [comment]
At the suggestion of the Contributing to Rails guide, I'm just nudging this a bit in the hopes of getting some feedback and preventing it from being closed for staleness.

**Comment by brianthoman** [comment]
At the suggestion of the Contributing to Rails guide, I'm just nudging this a bit in hope of getting some feedback and preventing it from being closed due to staleness.

**Comment by Goddesen** [comment]
I am currently experimenting with putting encrypted credentials in a separate rails engine. This would be of great help in editing those credentials.

**Comment by brianthoman** [comment]
Commenting to see if this will be re-opened.

**Pull request closed without merging**
