### PR TITLE
Add configuration option to reduce postgresql adapter memory bloat

### PR DESCRIPTION
**Pull request by mylake**
### Summary

The PR is provide the configuration option for my previous PR (https://github.com/rails/rails/pull/28369 500x memory reduction of 10k schemas for postgresql adapter)

Current query_conditions_for_initial_load will consume a lot of memories due to it collects records from multiple schemas and grows when numbers of schemas increase. The memory bloat issue should be fixed.

I use a active_record setting (config.active_record.excluded_pg_type_names) to let user could add exclusion for useless types.

This would allow people who know that every schema is identical to reduce their memory usage while by default using the current behaviour

### Other information

I use benchmark-memory gem to test on my local environments

I create two database environments

1. development (408 schemas)
2. big (10000 schemas)

I exclude all my tables on pg_type, 

```
config.active_record.excluded_pg_type_names = Dir['app/models/*.rb'].map {|f| "_#{File.basename(f, '.*')}s” }
```

```
Benchmark.memory do |x|
 x.report(:normal) do
   y.times do
     ActiveRecord::Base.establish_connection(:big).connection
     ActiveRecord::Base.establish_connection(:development).connection
   end
 end

 x.report(:patch) do
   require 'active_record_postgresql_adapter_ext'
   y.times do
     ActiveRecord::Base.establish_connection(:big).connection
     ActiveRecord::Base.establish_connection(:development).connection
   end
 end
x.compare!
end
```
result:
```
Calculating -------------------------------------
              normal   408.838M memsize (    90.936k retained)
                         3.510M objects (   908.000  retained)
                        50.000  strings (    50.000  retained)
               patch   884.509k memsize (    91.155k retained)
                         7.337k objects (   910.000  retained)
                        50.000  strings (    50.000  retained)

Comparison:
               patch:     884509 allocated
              normal:  408837567 allocated - 462.22x more
```

### CODE REVIEW

**Comment by maclover7** [comment]
@mylake Would you be able to show a before/after benchmark? Thanks!

**Comment by mylake** [comment]
@maclover7 

I use benchmark-memory gem to test on my local environments

I create two database environments

1. development (408 schemas)
2. big (10000 schemas)

```
Benchmark.memory do |x|
 x.report(:normal) do
   y.times do
     ActiveRecord::Base.establish_connection(:big).connection
     ActiveRecord::Base.establish_connection(:development).connection
   end
 end

 x.report(:patch) do
   require 'active_record_postgresql_adapter_ext'
   y.times do
     ActiveRecord::Base.establish_connection(:big).connection
     ActiveRecord::Base.establish_connection(:development).connection
   end
 end
x.compare!
end
```
result:
```
Calculating -------------------------------------
              normal   408.838M memsize (    90.936k retained)
                         3.510M objects (   908.000  retained)
                        50.000  strings (    50.000  retained)
               patch   884.509k memsize (    91.155k retained)
                         7.337k objects (   910.000  retained)
                        50.000  strings (    50.000  retained)

Comparison:
               patch:     884509 allocated
              normal:  408837567 allocated - 462.22x more
```

**Comment by ryudoawaru** [comment]
@tenderlove would you mind to take a look at this PR? thanks

**Comment by matthewd** [comment]
I don't think we need this config option... we can just refine the conditions on the query to load less rows by default (but without excluding them if they're explicitly needed).

Specifically, we seem to be loading arrays for composite types (even though we're *not* loading the composite types themselves). The `typinput` and `typelem` conditions are both selecting them: ISTM we want to refine those to only select arrays of non-composites.

**Comment by AvaelKross** [comment]
+1 on this. It would be very useful for everybody who uses Apartment and psql schemas. If you think anything else can be refined to get the same results, it would be very appreciated too.

**Comment by rafaelfranca** [comment]
@mylake can you work in Matthew's suggestion?

**Comment by Systho** [comment]
@mylake I know it's been a long time but can you continue your work on this PR or - if its mostly Apartment specific - make a PR to the Apartment gem ?

**Pull request closed without merging**
