### PR TITLE
Use Regexp#match? rather than Regexp#===

### PR DESCRIPTION
**Pull request by kamipo**
Follow up to 99cf7558000090668b137085bfe6bcc06c4571dc.

r? @fxn

### CODE REVIEW

**Comment by kaspth** [comment]
Think this might break the isolation tests unless we also add the `core_ext` require to each file. Other than that, I'll defer to @fxn.

**Comment by fxn** [comment]
@kamipo thanks for working on this, your systematic patches are awesome.

@kaspth is right, we'd need a require per file. But this has made me think that we should actually load the method in _rails.rb_. Let me work on it and we'll merge.

**Comment by kaspth** [comment]
> @kamipo thanks for working on this, your systematic patches are awesome.

Agreed! 👏

Shouldn't we just require it in `active_support.rb`? We have the requirement that any file must require the top level component to use any subcomponent in it, so that seems like the place to me.

**Comment by fxn** [comment]
@kaspth we have a place for these "globally available" extensions, which is [*active_support/rails.rb*](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/rails.rb).

But I need to remove the requires I added myself in previous passes.

**Comment by kaspth** [comment]
Ah, gotcha 👍

**Comment by fxn** [comment]
Done in 56832e791f3ec3e586cf049c6408c7a183fdd3a1.

**Comment by kaspth** [comment]
Nice 👏

**Pull request merged**
