### PR TITLE
Add *_previously_was attribute methods when dirty tracking

### PR DESCRIPTION
**Pull request by dhh**
Add *_previously_was attribute methods when dirty tracking. Example:

```ruby
pirate.update(catchphrase: "Ahoy!")
pirate.previous_changes["catchphrase"] # => ["Thar She Blows!", "Ahoy!"]
pirate.catchphrase_previously_was # => "Thar She Blows!"
```

### CODE REVIEW

**Comment by OlgaCoskun** [comment]
intresting!)

**Comment by mikker** [comment]
Just curious, feel free to ignore, @dhh: How do you use this in Basecamp (or that secret thing)? Like, _use this in a sentence_ in the Dictionary 😊

**Comment by kaspth** [comment]
@mikker something like `report_default_collections if collectable_id_previously_was.blank?` is one, `saved_change_to_status? && status_previously_was.inquiry.trashed? && active?` is another. All in `after_*` callbacks, of course. 😊

**Comment by mikker** [comment]
Thanks Casper! 🙏

**Comment by maxp-hover** [comment]
Um, so I know it's kinda late to bring this up, but why didn't we use `previous_value`? 

`attr_previously_was.blank?` sounds natural, but `old_attr = thing.attr_previously_was` just doesn't read like proper grammar, I expect an adjective after that. Meanwhile `previous_value` works in both cases.

**Pull request merged**
