### PR TITLE
development.rb file always exists so we don't need a check for it

### PR DESCRIPTION
**Pull request by prathamesh-sonpatki**
r? @arthurnn

### CODE REVIEW

**Comment by matthewd** [comment]
It might be a slightly unusual choice, but I don't see why someone couldn't remove/rename the development environment.

**Comment by prathamesh-sonpatki** [comment]
@matthewd I agree that one can rename the file but we add it again during the upgrade process - https://github.com/rails/rails/blob/master/railties/lib/rails/generators/rails/app/app_generator.rb#L85.

And it happens just before the check for development.rb - https://github.com/rails/rails/blob/master/railties/lib/rails/generators/rails/app/app_generator.rb#L100.

So even if somebody removes or renames the file the upgrade process ensures that it's added back.

**Comment by matthewd** [comment]
Ah, I see.

And even if we're creating it from scratch, we can't leave the "new" version, because the gem still won't be there.

**Comment by prathamesh-sonpatki** [comment]
Exactly :)

On Saturday 26 March 2016, Matthew Draper <notifications@github.com> wrote:

> Merged #24323 <https://github.com/rails/rails/pull/24323>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/rails/rails/pull/24323#event-603894672>
>


-- 
./prathamesh
 GITHUB <https://github.com/prathamesh-sonpatki> Blog
<http://prathamesh-sonpatki.github.com>

**Pull request merged**
