### PR TITLE
Add support to mysql parser attribute into schema dump - fix #42131

### LINKED ISSUE #42131: Schema and Migration file can't express parser option when using fulltext index
### Steps to reproduce
We can set parser options when add a fulltext index to mysql.
Default parser is white space, but we can choose a different parser.
[MySQL doc url](https://dev.mysql.com/doc/refman/5.7/en/fulltext-search-ngram.html)

Migration file example,
```RUBY
  def up
    create_table :items do |t|
      t.string  :name
      t.text    :description
      t.timestamps
    end
    execute 'CREATE FULLTEXT INDEX index_items_on_description ON items(description) WITH PARSER ngram'
  end
```

I think it's better expression in migration file when fulltext index with parser
```RUBY
  def up
    create_table :items do |t|
      t.string  :name
      t.text    :description
      t.timestamps
    end
    add_index :items, :description, type: :fulltext, parser: :ngram
  end
```

And Generated schema file can't express parser option about fulltext index.

### Expected behavior

```RUBY
  create_table "items", charset: "utf8mb4", collation: "utf8mb4_unicode_ci", force: :cascade do |t|
    t.string "name"
    t.text "description"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.index ["description"], name: "index_items_on_description", type: :fulltext, parser: :ngram
```
### Actual behavior

```RUBY
  create_table "items", charset: "utf8mb4", collation: "utf8mb4_unicode_ci", force: :cascade do |t|
    t.string "name"
    t.text "description"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.index ["description"], name: "index_items_on_description", type: :fulltext
```

### System configuration
**Rails version**: 6.1.3.1

**Ruby version**: 2.6.6

### PR DESCRIPTION
**Pull request by lfalcao**
Related to: https://github.com/rails/rails/issues/42131

### CODE REVIEW

**Comment by lfalcao** [comment]
I think the CI server is unstable as these tests passes in local... there's any way to rerun it, without having to commit again?

`W, [2021-05-10T19:19:01.466411 #21]  WARN -- : memcached:11211 failed (count: 0) Timeout::Error: execution expired`

**Review by lastthyme — APPROVED** [review]

**Comment by zzak** [comment]
@lfalcao This is a really nice patch, I especially liked `AR::SchemaDumper#check_parser`! Could you also add a changelog?

**Comment by lfalcao** [comment]
@zzak I'm not sure if it's worth merging this, as it's "database specific things" [1](https://github.com/rails/rails/pull/19165#issuecomment-76742525). But at the same time not having this can also lead to some problems too... 🤔 

What do you think? cc/ @byroot

**Comment by byroot** [comment]
I have the same opinion as last month: https://github.com/rails/rails/issues/42131#issuecomment-840725105

I think there is way too much of these kind of advanced SQL feature for `schema.rb` to support them. People relying to these should run `schema_format = :sql`.

But I'm no authority on the matter. @rafaelfranca @eileencodes thoughts?

**Comment by ghiculescu** [comment]
I don’t use MySQL so have no opinion on this specific PR, but in general am interested in that debate. schema.rb is so much better than structure.sql, it feels like it the community wants to contribute ways to have it support more common database features we should encourage that. (I have a vested interest - https://github.com/rails/rails/pull/41469)

**Comment by eileencodes** [comment]
> schema.rb is so much better than structure.sql

I'm curious to hear more about this since I generally lean towards structure.sql is better.

**Comment by ghiculescu** [comment]
We use both at Workforce - our monolith uses structure.sql (though if https://github.com/rails/rails/pull/41469 gets accepted it may not have to), all other repos use schema.rb. I prefer schema.rb because it is easier to read, tends to have less merge conflicts, and feels more like the Rails way. structure.sql is more extensible but for the majority of Rails apps I doubt that's a requirement, even for medium sized pushing on large ones like ours. Of the extensions we've made, I think only `add_read_rep_roles` might still be needed if we switched to schema.rb:

```ruby
# errors if using inconsistent postgres versions to avoid huge structure.sql diffs
Rake::Task["db:migrate"].enhance(["db:prevent_disparate_pg_dump_versions"])
Rake::Task["db:structure:dump"].enhance do
  # removes migration versions from structure.sql if the corresponding migration file was deleted
  Rake::Task["db:make_structure_sql_match_db_migrate_folder"].invoke
end
Rake::Task["db:structure:dump"].enhance do
  Rake::Task["db:remove_views_from_structure_sql"].invoke
end
Rake::Task["db:structure:dump"].enhance do
  # adds roles for the replica DB to structure.sql
  Rake::Task["db:add_read_rep_roles"].invoke
end

```

**Comment by byroot** [comment]
> tends to have less merge conflicts

I'd argue the opposite. The column alignent cause lines that didn't meaningfully changed to be edited which is a source of merge conflicts. The SQL dump on the other hand is very consistent for MySQL (unless of course users have different MySQL versions or configuration, which indeed can be a pain).

> it feels like it the community wants to contribute ways to have it support more common database features we should encourage that.

The problem is that there is a very long tail of rarely used SQL features. So it adds lots of complexity and maintenance burden for an extremely small fraction of the user base. Hence why I'm 👎 .

**Comment by ghiculescu** [comment]
> The column alignent cause lines that didn't meaningfully changed to be edited

I haven't come across this before, so thanks for the heads up. Is it something that could be fixed in Rails?

> The problem is that there is a very long tail of rarely used SQL features. So it adds lots of complexity and maintenance burden for an extremely small fraction of the user base.

The hard thing IMO is it's not clear where to draw the line. Should schema.rb only support features that work the same on every database? What about features that are conceptually, but not technically, the same? (eg https://github.com/rails/rails/pull/41469 - schema.rb works with mysql enums but not postgres ones). I get the feeling the original goal was you could use the file to change databases easily, but that ship has sailed now - for example, each database adapter supports lots of different and engine-specific types. Given that, I'd love more clarity around which features are in and which are out.

**Comment by byroot** [comment]
> Is it something that could be fixed in Rails?

It could, by simply removing the automatic alignent, but if it's there it's likely because some people like it.

> The hard thing IMO is it's not clear where to draw the line.

Exactly. My personal line is: is this feature used by more than ~1% of Rails users?

**Comment by ghiculescu** [comment]
> My personal line is: is this feature used by more than ~1% of Rails users?

I am 👍  on that. I don't know how you'd ever prove it, but I think that it gives a clear enough statement of intent.

**Comment by byroot** [comment]
> The column alignent cause lines that didn't meaningfully changed to be edited which is a source of merge conflicts.

Ok, so might bad this was removed several Rails versions ago (likely for this very reason).

**Comment by lfalcao** [comment]
Well, I agree with @byroot and the rule of ~1%...

**Pull request closed without merging**
