### PR TITLE
Fix `Enumerable#in_order_of` to preserve duplicates

### LINKED ISSUE #47803: in_order_of omit duplicate keys
### Steps to reproduce
If multiple items share the same key in_order_of omits them in results.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
end

require "active_support"
require "active_support/core_ext/enumerable"
require "minitest/autorun"

class BugTest < Minitest::Test
  def test_in_order_of_duplicate_items
    record1 = OpenStruct.new(name: "name1", id: 1)
    record2 = OpenStruct.new(name: "name2", id: 2)
    record3 = OpenStruct.new(name: "name1", id: 3)

    result = [record1, record2, record3].in_order_of(:name, %w(name1 name2))

    assert_equal [record1, record3, record2], result
  end
end

```

### Expected behavior
We should get 3 items. 

### Actual behavior
One item is missing from results. 

### System configuration
**Rails version**: main@33e1a89

**Ruby version**: 3.1.0p0

### PR DESCRIPTION
**Pull request by fatkodima**
Fixes #47803.

### CODE REVIEW

**Comment by miharekar** [comment]
Hey, I just tried edge Rails to see what breaks in my app, and this was the first thing that broke 😅 

I have a hash of hashes for which I use `in_order_of`, and since this change I don't get ordered array of hashes, but I get a longer array of flattened values.

The actual object:
```
{:closed=>{:value=>0, :status=>"Closed"},
 :opened=>{:value=>1, :status=>"Opened"},
 :temporarily_closed=>{:value=>2, :status=>"Temporarily closed"},
 :recommended=>{:value=>3, :status=>"Recommended"},
 :declined=>{:value=>4, :status=>"Declined"},
 :submitted=>{:value=>5, :status=>"Submitted"},
 :invited=>{:value=>6, :status=>"Invited"}}
```

Before:
```
irb(main):001:0> Cafe.symbolized_status_map.in_order_of(:first, [:opened, :submitted, :recommended, :invited, :temporarily_closed, :closed, :decline
d])
[[:opened, {:value=>1, :status=>"Opened"}],
 [:submitted, {:value=>5, :status=>"Submitted"}],
 [:recommended, {:value=>3, :status=>"Recommended"}],
 [:invited, {:value=>6, :status=>"Invited"}],
 [:temporarily_closed, {:value=>2, :status=>"Temporarily closed"}],
 [:closed, {:value=>0, :status=>"Closed"}],
 [:declined, {:value=>4, :status=>"Declined"}]]
```

Now:
```
irb(main):001:0> Cafe.symbolized_status_map.in_order_of(:first, [:opened, :submitted, :recommended, :invited, :temporarily_closed, :closed, :decline
d])
=>
[:opened,
 {:value=>1, :status=>"Opened"},
 :submitted,
 {:value=>5, :status=>"Submitted"},
 :recommended,
 {:value=>3, :status=>"Recommended"},
 :invited,
 {:value=>6, :status=>"Invited"},
 :temporarily_closed,
 {:value=>2, :status=>"Temporarily closed"},
 :closed,
 {:value=>0, :status=>"Closed"},
 :declined,
 {:value=>4, :status=>"Declined"}]
 ```

And it broke, because I'm using it like so:
```
<% Cafe.symbolized_status_map.in_order_of(:first, [:opened, :submitted, :recommended, :invited, :temporarily_closed, :closed, :declined]).each do |sym, info| %>
```
and now of course the `info` is `nil` 😅 

So my question is: is this a breaking change and I'm not supposed to use `#in_order_of` in this way, or does this need fixing?

If latter I can provide a PR with a test.

**Comment by tiegz** [comment]
I'm curious if this change was really ideal based on the history:

2/2021: `Enumerable#in_order_of` was extracted from the `find` method: https://github.com/rails/rails/pull/41333
4/2021: `ActiveRecord#in_order_of` was added to complement `Enumerable#in_order_of`: https://github.com/rails/rails/pull/42061
1/2022: `ActiveRecord#in_order_of` added filtering to limit results to the listed values, to match `Enumerable#in_order_of`: https://github.com/rails/rails/pull/44097
3/2023: `Enumerable#in_order_of` diverges and includes duplicate matches in this PR

It seems like the idea was to mirror the two `in_order_of` methods, but this change makes them act differently:

```
> User.in_order_of(:id, [5,4,2,4]).map(&:id)
=> [5, 4, 2]
> User.all.to_a.in_order_of(:id, [5,4,2,4]).map(&:id)
  User Load (1.8ms)  SELECT "users".* FROM "users"
=> [5, 4, 2, 4]
```

I don't think we can preserve duplicates in `Enumerable#in_order_of` either, since that would change `find`.

**Comment by skipkayhil** [comment]
> `> User.in_order_of(:id, [5,4,2,4]).map(&:id)`

Can you explain what you would expect the return value of this to be? How can something with id 4 be ordered both before and after the things with id 2?

The issue with duplicates resolved here is about multiple objects with the same order key:
```
[Person.new("a"), Person.new("a"), Person.new("b")].in_order_of(:name, ["b", "a"]).map(&:name)

# before
# => ["b", "a"]

# after
# => ["b", "a", "a"]
```

**Comment by tiegz** [comment]
> Can you explain what you would expect the return value of this to be? 

If the result of `User.all.to_a` only returns 3 records, I'd be surprised to 4 records back, so I'd expect `[5, 4, 2]` (or conversely, I'd expect the AR version to also add a 4th record)

> How can something with id 4 be ordered both before and after the things with id 2?

Programmer error or edge case (e.g. if the 2nd argument was dynamically generated and not uniq'ed), but even in that case I'd expect the method to not change the size of the original list.

> The issue with duplicates resolved here is about multiple objects with the same order key:

You're right! I think I have an issue with the original implementation. Thanks for the feedback anyway.

**Pull request merged**
