### PR TITLE
Removed usage of key_generator

### PR DESCRIPTION
**Pull request by shefig007**

### CODE REVIEW

**Comment by kaspth** [comment]
@tenderlove this sounds related to the work you did yesterday, can you take a look? :smile:

**Comment by rafaelfranca** [comment]
This one is correct. We need to check it.

**Comment by rafaelfranca** [comment]
Thank you for the pull request.

**Comment by shefig** [comment]
@rafaelfranca May I know the reason why did you close the pull request please?

**Comment by matthewd** [comment]
@shefig Rafael said: "This one is correct. We need to check it."

Perhaps this conversation would go better if you gave a reason that you *opened* the pull request?

**Pull request closed without merging**
