### PR TITLE
Improve guides [ci skip]

### PR DESCRIPTION
**Pull request by teeceepee**
The code has been chaged from `:'data-confirm'` to `:data`, modify the documentation.

### CODE REVIEW

**Comment by eileencodes** [comment]
Thanks for the pull request @teeceepee! :smile: I don't know if this is the best change though. The option is `method:`  not `method: :delete`. If I was a brand new Rails developer reading this I'd think the only counterpart to `method:` is `:delete`, you know what I mean?

I do think an example could be good here though, but it should be below the main explanation. Can you update your pull request? Thanks!

**Comment by teeceepee** [comment]
@eileencodes Just change `:'data-confirm'` to `:data`, OK?

**Comment by eileencodes** [comment]
@teeceepee ah I see. I'm sorry I didn't look at the surrounding documentation. Your change does make sense in that context so no need to do the changes I asked for. 

 But while we're editing this paragraph can you change the last 2 sentences to say:
> This is done via the JavaScript file `jquery_ujs` which is automatically included in your application's layout (`app/views/layouts/application.html.erb`) when you generated the application. Without this file, the confirmation dialog box won't appear.

It just changed "into" to "in" and "wouldn't" to "won't" for a better sounding sentence. Thank you!

**Comment by teeceepee** [comment]
@eileencodes I have changed the guide as what you said.

**Comment by eileencodes** [comment]
Thanks @teeceepee!

**Comment by teeceepee** [comment]
@eileencodes You collaborators are so fast!

**Pull request merged**
