### PR TITLE
implement ActiveRecord::Base#pretty_print

### PR DESCRIPTION
**Pull request by notEthan**
AR::B has long been lacking pretty print support. I submitted this patch some years ago (pre-github), attempting again. 

before:

```
pp topic

#<Topic id: 1, title: "The First Topic", author_name: "David", author_email_address: "david@loudthinking.com", written_on: "2003-07-16 14:28:11", bonus_time: "2000-01-01 14:28:00", last_read: "2004-04-15", content: "Have a nice day", important: nil, approved: false, replies_count: 1, unique_replies_count: 0, parent_id: nil, parent_title: nil, type: nil, group: nil, created_at: "2014-05-18 21:33:26", updated_at: "2014-05-18 21:33:26">
```

(same as #inspect)

now: 

```
pp topic

#<Topic:0x007fb93696bcb0
 id: 1,
 title: "The First Topic",
 author_name: "David",
 author_email_address: "david@loudthinking.com",
 written_on: 2003-07-16 14:28:11 UTC,
 bonus_time: 2000-01-01 14:28:00 UTC,
 last_read: Thu, 15 Apr 2004,
 content: "Have a nice day",
 important: nil,
 approved: false,
 replies_count: 1,
 unique_replies_count: 0,
 parent_id: nil,
 parent_title: nil,
 type: nil,
 group: nil,
 created_at: 2014-05-18 21:31:53 UTC,
 updated_at: 2014-05-18 21:31:53 UTC>
```

### CODE REVIEW

**Comment by mwesigwa** [comment]
I recently submitted #18353 and have finally tracked down the cause of this issue to this commit. It turns out that while this feature is actually awesome, it also breaks some expected Ruby behavior in ActiveRecord classes. The inspect method in all ActiveRecord models is now effectively ignored in Rails 4.2 going forward.

Here is an example:
```ruby
class Foo < ActiveRecord::Base
 def initialize(a=1,b=2)
    @a = a
    @b = b
  end
end
Rails(4.1) Foo.new                  #=> "#<Foo:0x0300c868 a: 1, b: 2 >"
Rails(4.2) Foo.new                  #=> 
"#<Foo:0x0300c868 
    a: 1
    b: 2>"
```
This is when the feature looks great and works as expected.

However consider this case:

```ruby
class Foo < ActiveRecord::Base
  def initialize(a=1,b=2)
    @a = a
    @b = b
  end
  def inspect
     "Foo is awesome"
  end
end
Rails(4.1) Foo.new                  #=> "Foo is awesome"
Rails(4.2) Foo.new                  #=> 
"#<Foo:0x0300c868 
    a: 1
    b: 2>"
```
Here the user defined inspect method is completely ignored! Which IMO is undesirable. What do you guys think?

**Comment by notEthan** [comment]
this appears to have been addressed as expected pry behavior (that it uses PP) over on https://github.com/pry/pry/issues/1337

**Comment by mwesigwa** [comment]
Yes, pry uses PP. But it first of all looks at the object's inspect method. Which is the expected [Ruby behavior](https://github.com/ruby/ruby/blob/trunk/lib/pp.rb#L308-316). With this change, we completely ignore the user defined inspect methods. 

It seems to me that instead of defining pretty_print, you should be overriding the [pp_object](https://github.com/ruby/ruby/blob/trunk/lib/pp.rb#L255) method which is the failsafe in Ruby in order to achieve both cases. This is my 2 cents.

And FYI, I'm the one that opened pry/pry#1337 and we concluded that this is a Rails issue.

**Comment by notEthan** [comment]
defining #pretty_print is the standard and intended way of implementing pretty-print capability. pp_object is not related to anything here. 

> pry uses PP. But it first of all looks at the object's inspect method

this is not correct, per the discussion at pry/pry#1337 : "PP preferentially uses pretty_print over inspect"

> we concluded that this is a Rails issue

I don't see anything over there that suggests this. rf- says "If you want to customize the output for your models, you can either `undef pretty_print` or write your own implementation of it." which is true.

**Comment by mwesigwa** [comment]
I think you are completely missing my point. The Ruby language uses the [inspect](http://ruby-doc.org/core-2.1.1/Object.html#method-i-inspect) method to "make better representation of user defined classes". It's a Ruby fundamental. The ```pretty_inspect``` method definition in Ruby itself first looks at the ```Object.inspect``` method [here](https://github.com/ruby/ruby/blob/trunk/lib/pp.rb#L308-316).

With this current implementation, you completely ignore the ```inspect``` method. This becomes a huge problem.

Consider an ActiveRecord model with 2000 attributes. If I only care about one attribute, then I would define that model's inspect method. Currently, with this implementation, you are forcing the user to see every single attribute whether they care about seeing it or not without any regard for the already defined inspect methods.

Hope this makes my point clear.

**Comment by notEthan** [comment]
although pretty-print does fall back to inspect for objects that do not define their own pretty-printing, the implementations of inspect and pp are separate, and no other implementation of pretty printing has anything to do with #inspect (that I am aware of or have ever seen). 

activerecord's pretty print implementation could in theory check if a subclass of AR::B has overridden #inspect and use that instead of its own pretty-print if so, but it seems questionable to me that this is better behavior. if PP is being used (as pry does), then a pretty-printed representation is what should be returned - not the more concise result of #inspect. 

it's worth noting that this is not an issue particular to activerecord: if you subclass any other class, apart from Object, that implements pretty-printing - such as Array, Hash, many other core classes, as well as many third party libraries - pry (and anything else that uses pp) will ignore your inspect method:

```
[3] pry(main)> class Bar < Array
[3] pry(main)*   def inspect
[3] pry(main)*     join '+'
[3] pry(main)*   end  
[3] pry(main)* end  
=> nil
[4] pry(main)> Bar.new << 'a' << 'b'
=> ["a", "b"]
[5] pry(main)> (Bar.new << 'a' << 'b').inspect
=> "a+b"
```

**Comment by matthewd** [comment]
> if PP is being used (as pry does), then a pretty-printed representation is what should be returned - not the more concise result of #inspect

FWIW, I think I disagree: I can't think of any instance where PP intends to be more informative than the corresponding `inspect` -- only better formatted.

I'd thus consider the custom-`inspect`-on-Array-subclass behaviour you demonstrated to be an unfortunate shortcoming in pry's logic.

> activerecord's pretty print implementation could in theory check if a subclass of AR::B has overridden #inspect

I think we should do this: enhance our own `inspect`'s presentation, but not fight with a custom one. IMO, this seems more likely to be what more people are going to expect -- and visually consistent with our previous behaviour.

**Comment by notEthan** [comment]
> FWIW, I think I disagree: I can't think of any instance where PP intends to be more informative than the corresponding `inspect` -- only better formatted.

true

if that is the way to go, it looks like it is simple enough to implement 

```ruby
  def pretty_print(pp)
    if self.class.instance_method(:inspect).owner < ActiveRecord::Base
      pp.text inspect
    else
      [current implementation]
    end
  end
```

**Comment by notEthan** [comment]
hm, that won't work if an included module of a subclass redefines inspect. maybe 
`self.class.instance_method(:inspect).owner != ActiveRecord::Base.instance_method(:inspect).owner`

**Pull request merged**
