### PR TITLE
Get rid of platform-specific versions of nokogiri in Gemfile.lock

### PR DESCRIPTION
**Pull request by olefriis**
### Motivation / Background

When creating a new DevContainer, as described in [the contribution guide](https://github.com/rails/rails/blob/main/guides/source/contributing_to_ruby_on_rails.md#using-vs-code-remote-containers), the following papercut happens when e.g. running the ActiveRecord tests:

```
$ cd activerecord
$ bundle install
$ bundle exec rake test:sqlite3_mem
Could not find nokogiri-1.13.3-x86_64-linux in locally installed gems
Run `bundle install` to install missing gems.
```

You can continue this loop for as long as you want 😄 (And in fact, this error also happens during the creation of the DevContainer, since it's doing a `bundle exec` on the very last line in `.devcontainer/boot.sh`.)

### Detail

Doing `bundle update nokogiri` from within the DevContainer removes the platform-specific versions of nokogiri, so I've done that and opened this PR with the result of the operation.

### Additional information

I have no idea if this breaks the workflow of Rails contributors. I am sorry if that is the case, and if so, let's dismiss this PR. It's just that using DevContainers is a really nice way to get a development environment up and running quickly, so it's a little sad that it doesn't work currently. I suppose Codespaces is broken in a similar way, since that is based on DevContainers.

Also, I don't know much about these platform-specific gems, so what I've done may be the completely wrong thing...

### Checklist

Before submitting the PR make sure the following are checked:

* [X] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [X] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [ ] ~Tests are added or updated if you fix a bug or add a feature.~
* [ ] ~CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.~

### CODE REVIEW

**Comment by olefriis** [comment]
Just tried spinning up a Codespace on `main`. Interestingly it doesn't fail when starting the container (or I just don't know where to look for the error), but still, when trying to do anything with `bundle exec`, stuff fails as described above.

**Comment by rafaelfranca** [comment]
That is interesting. I was the one that added those lines, and I only develop inside a devcontainer. I just created a new one and can't seem to reproduce this error.

How can I reproduce it?

**Comment by rafaelfranca** [comment]
Can you provide the result of `uname --all` inside the dev container?

```
$ uname --all
Linux 37c2d7ecb27b 5.15.49-linuxkit #1 SMP PREEMPT Tue Sep 13 07:51:32 UTC 2022 aarch64 GNU/Linux
```

**Comment by rafaelfranca** [comment]
Ah, it is because of the Ruby 3.2 version of nokogiri isn't developed yet. I'll merge this and them update all the gems.

**Comment by zzak** [comment]
Personally, I always just delete this file when developing locally on 3.2+, usually ruby-trunk. 🤷

**Pull request merged**
