### PR TITLE
respect attribute default value as a block

### PR DESCRIPTION
**Pull request by Sen-Zhang**
A propositional fix to issue https://github.com/rails/rails/issues/24249

### CODE REVIEW

**Comment by maclover7** [comment]
Hmm, this seems like more of a feature request than a bug report...

**Comment by Sen-Zhang** [comment]
Oops, should I close this pull request for now?

**Comment by sgrif** [comment]
I'm not a fan of this implementation. The solution is too far removed from the problem. I'd prefer to keep the handling of procs isolated to the area where it already occurs.

**Comment by Sen-Zhang** [comment]
The new fix https://github.com/rails/rails/pull/24306 is just for tag helpers.

**Pull request closed without merging**
