### PR TITLE
Fix namespace in TaggedLogging

### PR DESCRIPTION
**Pull request by 5minpause**
### Motivation / Background

This Pull Request has been created because I received a `NameError: uninitialized constant ActiveSupport::TaggedLogging::Formatter::IsolatedExecutionState`. This PR changes how the class is referenced with explicit namespacing.

I am trying to update the gem https://github.com/davidwinter/sensible_logging to use ActiveSupport >= v7.0. This is where I get the error when accessing `@logger.tagged` method.

### Detail

This Pull Request changes how the class `ActiveSupport::IsolatedExecutionState` is referenced and uses an explicit top-level namespace.

### Additional information

My Rails 7 update branch https://github.com/5minpause/sensible_logging/tree/rails-7

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by skipkayhil** [comment]
Hey @5minpause, thank you for opening a PR! To use individual components of Active Support you must first `require "active_support"`, which I am not seeing in the `sensible_logging` gem. Can you try adding and seeing if the error goes away?

**Comment by 5minpause** [comment]
@skipkayhil does this line qualify?
https://github.com/davidwinter/sensible_logging/blob/7f9e4a090cdc67aa6231c4a9f7aec8c61b04c2bb/lib/sensible_logging/middlewares/tagged_logger.rb#L4
It requires the `tagged_logger` class individually.

**Comment by 5minpause** [comment]
@skipkayhil of course, you are absolutely right. So there is no way to use individual components without using the whole gem. I understand. That's a design decision I suppose?

**Comment by 5minpause** [comment]
I updated the code of the PR in question and your proposed solution works. Let's close this here. Thanks for your help @skipkayhil

**Comment by skipkayhil** [comment]
(Copying the comment I left on the linked PR)

> To clarify a bit, require "active_support" does not load everything. However it does set up autoloads for a number of "core" classes that are used in many of the individual components (like IsolatedExecutionState):
>
> https://github.com/rails/rails/blob/355fd5929058ee3a73032c5f62de3d8819550482/activesupport/lib/active_support.rb

**Pull request closed without merging**
