### PR TITLE
remove config that are no longer needed in sprockets-rails 3

### PR DESCRIPTION
**Pull request by y-yagi**
`config.assets.raise_runtime_errors` and `config.assets.digest` are enabled
by default in sprockets-rails 3.

### CODE REVIEW

**Comment by maclover7** [comment]
cc @schneems

**Comment by bquorning** [comment]
Shouldn’t Rails then change it dependency on sprockets-rails from `>= 2` to `>= 3`?

**Comment by schneems** [comment]
The `rails new` command doesn't generate a `sprockets-rails` dependency in your Gemfile instead it adds `sass-rails` which in turn depends on `sprockets-rails`. Unfortunately

```
    sass-rails (5.0.5)
      railties (>= 4.0.0, < 6)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
```

**Comment by rafaelfranca** [comment]
> Shouldn’t Rails then change it dependency on sprockets-rails from >= 2 to >= 3

It still works with sprockets-rails 2, it just don't generates the config for it.

@schneems sprockets-rails is a direct dependency of rails https://github.com/rails/rails/blob/master/rails.gemspec#L32

**Comment by schneems** [comment]
@rafaelfranca thanks TIL.

I think @bquorning is worried about the case where someone already has sprockets-rails ~2.x installed as the latest version on the machine from another project. Then they go to run `$ rails new` to build a new project, the config won't be auto generated and they'll be using an older version of sprockets-rails (the one already on their system that satisfies the dependencies) that doesn't default to this feature being on by default.

**Comment by rafaelfranca** [comment]
Oh, got it. The problem with changing the requirement is that we will force people to upgrade sprockets-rails while upgrading rails and this may make things harder. Maybe we should add sprockets-rails to the Gemfile for new applications?

**Pull request merged**
