### PR TITLE
refactor HashWithIndifferentAccess#to_hash

### PR DESCRIPTION
**Pull request by kwstannard**
### Motivation / Background

Some minor refactoring because I felt like it to simplify the to_hash method. It also improves the performance a tiny bit.

### Detail

No functionality changes expected.

### Additional information

Benchmarking:

```
require "bundler/inline"
gemfile(true) do
  source "https://rubygems.org"

  gem "activesupport", path: '.'
  gem 'benchmark-ips'
  gem 'benchmark-memory'
end

require "active_support"
require "active_support/core_ext/hash/indifferent_access"
require 'benchmark/ips'

x=HashWithIndifferentAccess.new(
  a: 1,
  'b' => 2,
  4 => {
    x: 1,
    'y': 2
  }
)

Benchmark.ips { _1
  .report("original") { x.to_hash_ }
  .report("refactor") { x.to_hash }
}

require 'benchmark/memory'

Benchmark.memory {
  _1.report("original") { x.to_hash_ }
  _1.report("refactor") { x.to_hash }
}
```

```
ruby 3.3.3 (2024-06-12 revision f1c7b6f435) [arm64-darwin23]
Warming up --------------------------------------
            original   137.136k i/100ms
            refactor   154.557k i/100ms
Calculating -------------------------------------
            original      1.372M (± 1.1%) i/s -      6.994M in   5.099867s
            refactor      1.525M (± 1.8%) i/s -      7.728M in   5.070216s
Calculating -------------------------------------
            original   320.000  memsize (     0.000  retained)
                         2.000  objects (     0.000  retained)
                         0.000  strings (     0.000  retained)
            refactor   320.000  memsize (     0.000  retained)
                         2.000  objects (     0.000  retained)
                         0.000  strings (     0.000  retained)
```

### CODE REVIEW

**Comment by fatkodima** [comment]
This is a cosmetic change (we don't generally accept cosmetic changes), which also made the code more complex, imo.

**Comment by kwstannard** [comment]
Hi @fatkodima, thank you for your time. Is there a threshold on performance improvements?

**Comment by fatkodima** [comment]
I would also suggest to update benchmarks with `.compare` call to better see the difference.
 
That performance improvement falls within an error imo and this method is probably not called in a tight loop in the real code?

**Comment by kwstannard** [comment]
Okay, I forgot about compare, thanks. I do not know if this is used in a tight loop anywhere. There is a speed up depending on how long a hash is. Thanks again for your time.

```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "activesupport", path: '.'
  gem 'benchmark-ips'
  gem 'benchmark-memory'
end

require "active_support"
require "active_support/core_ext/hash/indifferent_access"
require 'benchmark/ips'

flat = Hash[(1..9).to_a.product([1])].with_indifferent_access

long_flat = Hash[(1..100).to_a.product([1])].with_indifferent_access

deep = flat.dup.with_indifferent_access
3.times.reduce(deep) { |deep, _| deep[:deep] = flat.dup.with_indifferent_access }

Benchmark.ips { _1
  .report("original flat") { flat.to_hash_ }
  .report("refactor flat") { flat.to_hash }
  .compare!
}
Benchmark.ips { _1
  .report("original long flat") { long_flat.to_hash_ }
  .report("refactor long flat") { long_flat.to_hash }
  .compare!
}
Benchmark.ips { _1
  .report("original deep") { deep.to_hash_ }
  .report("refactor deep") { deep.to_hash }
  .compare!
}
```

```
Comparison:
       refactor flat:  1297439.9 i/s
       original flat:   971625.3 i/s - 1.34x  slower

Comparison:
  refactor long flat:   158008.9 i/s
  original long flat:   109795.5 i/s - 1.44x  slower

Comparison:
       refactor deep:   315918.7 i/s
       original deep:   274962.0 i/s - 1.15x  slower
```

**Comment by byroot** [comment]
The `new_hash = Hash.new; each { |k,v| new_hash[key] = value }` is indeed very inefficient, and gets worse as the hash gets bigger because the hash starts empty hand then has to be reallocated multiple times when it gets full, and when it's reallocated, all keys have to be re-hashed. See: https://bugs.ruby-lang.org/issues/19236

So generally in favor of this, but the implementation in this PR can be improved a bit further.

**Comment by byroot** [comment]
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "activesupport", path: '.'
  gem 'benchmark-ips'
  gem 'benchmark-memory'
end

require "active_support"
require "active_support/core_ext/hash/indifferent_access"
require 'benchmark/ips'

module ActiveSupport
  class KwstannardHWIA < HashWithIndifferentAccess
    def to_hash
      Hash[self]
        .transform_values! { |v| convert_value(v, conversion: :to_hash) }
        .tap { |h| set_defaults(h) }
    end
  end

  class ByrootHWIA < HashWithIndifferentAccess
    def to_hash
      copy = Hash[self]
      copy.transform_values! { |v| convert_value_to_hash(v) }
      set_defaults(copy)
      copy
    end

    private

    def convert_value_to_hash(value)
      if value.is_a? Hash
        value.to_hash
      elsif value.is_a?(Array)
        value.map { |e| convert_value_to_hash(e) }
      else
        value
      end
    end
  end
end

flat = Hash[(1..9).to_a.product([1])]
flat_baseline = ActiveSupport::HashWithIndifferentAccess.new(flat)
flat_k = ActiveSupport::KwstannardHWIA.new(flat)
flat_b = ActiveSupport::ByrootHWIA.new(flat)

Benchmark.ips do |x|
  x.report("original") { flat_baseline.to_hash }
  x.report("kwstannard") { flat_k.to_hash }
  x.report("byroot") { flat_b.to_hash }
  x.compare!(order: :baseline)
end

long_flat = Hash[(1..100).to_a.product([1])]
long_flat_baseline = ActiveSupport::HashWithIndifferentAccess.new(long_flat)
long_flat_k = ActiveSupport::KwstannardHWIA.new(long_flat)
long_flat_b = ActiveSupport::ByrootHWIA.new(long_flat)

Benchmark.ips do |x|
  x.report("original") { long_flat_baseline.to_hash }
  x.report("kwstannard") { long_flat_k.to_hash }
  x.report("byroot") { long_flat_b.to_hash }
  x.compare!(order: :baseline)
end


deep_baseline = ActiveSupport::HashWithIndifferentAccess.new(flat.dup)
3.times.reduce(deep_baseline) { |deep, _| deep[:deep] = ActiveSupport::HashWithIndifferentAccess.new(flat.dup) }

deep_k = ActiveSupport::KwstannardHWIA.new(flat.dup)
3.times.reduce(deep_k) { |deep, _| deep[:deep] = ActiveSupport::KwstannardHWIA.new(flat.dup) }

deep_b = ActiveSupport::ByrootHWIA.new(flat.dup)
3.times.reduce(deep_b) { |deep, _| deep[:deep] = ActiveSupport::ByrootHWIA.new(flat.dup) }

Benchmark.ips do |x|
  x.report("original") { deep_baseline.to_hash }
  x.report("kwstannard") { deep_k.to_hash }
  x.report("byroot") { deep_b.to_hash }
  x.compare!(order: :baseline)
end

```

```
$ ruby /tmp/to_hash.rb 
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
ruby 3.3.1 (2024-04-23 revision c56cd86388) [arm64-darwin23]
Warming up --------------------------------------
            original    92.830k i/100ms
          kwstannard   125.443k i/100ms
              byroot   139.810k i/100ms
Calculating -------------------------------------
            original    968.200k (± 2.9%) i/s -      4.920M in   5.086600s
          kwstannard      1.268M (± 2.9%) i/s -      6.398M in   5.049545s
              byroot      1.397M (± 2.9%) i/s -      6.990M in   5.008404s

Comparison:
            original:   968200.3 i/s
              byroot:  1397069.4 i/s - 1.44x  faster
          kwstannard:  1268207.5 i/s - 1.31x  faster

ruby 3.3.1 (2024-04-23 revision c56cd86388) [arm64-darwin23]
Warming up --------------------------------------
            original    11.051k i/100ms
          kwstannard    15.865k i/100ms
              byroot    17.778k i/100ms
Calculating -------------------------------------
            original    109.059k (± 5.1%) i/s -    552.550k in   5.082820s
          kwstannard    157.499k (± 7.4%) i/s -    793.250k in   5.072103s
              byroot    177.066k (± 7.2%) i/s -    888.900k in   5.052601s

Comparison:
            original:   109059.1 i/s
              byroot:   177065.9 i/s - 1.62x  faster
          kwstannard:   157499.0 i/s - 1.44x  faster

ruby 3.3.1 (2024-04-23 revision c56cd86388) [arm64-darwin23]
Warming up --------------------------------------
            original    22.249k i/100ms
          kwstannard    30.132k i/100ms
              byroot    34.116k i/100ms
Calculating -------------------------------------
            original    224.127k (± 1.7%) i/s -      1.135M in   5.064253s
          kwstannard    295.912k (± 5.9%) i/s -      1.476M in   5.007324s
              byroot    343.225k (± 1.7%) i/s -      1.740M in   5.070715s

Comparison:
            original:   224127.0 i/s
              byroot:   343224.6 i/s - 1.53x  faster
          kwstannard:   295912.4 i/s - 1.32x  faster
```

**Comment by kwstannard** [comment]
Works for me. Thanks @byroot @fatkodima

**Comment by kwstannard** [comment]
And thanks for finding further improvements

**Pull request merged**
