### PR TITLE
Use a more conservative `const_get` over `constantize`

### PR DESCRIPTION
**Pull request by tamird**
@jeremy

### CODE REVIEW

**Comment by arthurnn** [comment]
As far as I remember, `constantize` encapsulate a few naming errors, and give better messages. If we change the code we would be losing that. Is that ok?

**Comment by arthurnn** [comment]
thanks @tamird

**Comment by tamird** [comment]
thanks @arthurnn

**Comment by jeremy** [comment]
Nice move. Makes it clear that it's a `ActiveJob::QueueAdapters` factory responsibility, even. We can extract it to a method over there, e.g.:
```ruby
class << ActiveJob::QueueAdapters
  def instance(name, *adapter_args, &block)
    lookup(name).new(*adapter_args, &block)
  end

  def lookup(name)
    const_get(name.to_s.camelize + 'Adapter')
  end
end
```

**Comment by rafaelfranca** [comment]
:+1: for @jeremy's comment.

**Comment by tamird** [comment]
SGTM, I'll make that change

**Pull request merged**
