### PR TITLE
Show that requests to Rails::Rack::Logger middleware trip an UnknownHttpMethod exception

### PR DESCRIPTION
**Pull request by tim-evans**
This shows that requests with unknown HTTP methods never get down to the ActionDispatch::DebugException middleware and return a 405.

Background for this: We have machines hitting our rails app looking for vulnerabilities and end up with a bunch of notifications in our error service about these requests. There aren't a ton of them, but it adds noise to our actual problems in production.

We're not sure what the best way is to solve this, but wanted to provide a failing test case to document that this is an issue.

Related to https://github.com/rails/rails/pull/10299.

### CODE REVIEW

**Comment by arthurnn** [comment]
right @tim-evans , I will take a look. Fell free also to send a PR, if you have a code-fix in mind.
thanks

**Comment by maclover7** [comment]
Please rebase.

**Comment by tim-evans** [comment]
Rebased, but it seemed to disconnect here. Will try to fix.

**Comment by tim-evans** [comment]
Sorry, looks like I accidentally closed this.

**Comment by tim-evans** [comment]
Hey @arthurnn, just a friendly poke on this. 😄

**Pull request closed without merging**
