### PR TITLE
Use size == 1 instead of one? to check hashes count in HashWithIndifferentAccess#update

### PR DESCRIPTION
**Pull request by krzysiek1507**
### Summary

[`one?`](https://ruby-doc.org/core-2.7.1/Enumerable.html#method-i-one-3F) checks is there is only one true element in the enumerable. Since we need to check the number of elements in `other_hashes` we need to check if `size == 1`.

### CODE REVIEW

**Comment by kamipo** [comment]
Can you add a test case which is fixed by this PR?

**Comment by krzysiek1507** [comment]
Hard to find a test case because only hashes are valid except that `one?` is not meant for this usage. There is performance issue though.

```ruby
Testing: [{}]
ips benchmark:

Warming up --------------------------------------
                one?   252.504k i/100ms
           size == 1   264.195k i/100ms
Calculating -------------------------------------
                one?     11.653M (± 3.7%) i/s -     58.328M in   5.013256s
           size == 1     15.181M (± 3.0%) i/s -     75.824M in   4.999859s

Comparison:
           size == 1: 15181397.7 i/s
                one?: 11652726.5 i/s - 1.30x  slower


Testing: [{}, {}]
ips benchmark:

Warming up --------------------------------------
                one?   251.583k i/100ms
           size == 1   269.362k i/100ms
Calculating -------------------------------------
                one?     11.667M (± 2.5%) i/s -     58.367M in   5.006002s
           size == 1     15.214M (± 2.5%) i/s -     76.229M in   5.014025s

Comparison:
           size == 1: 15213600.8 i/s
                one?: 11667262.7 i/s - 1.30x  slower


Testing: [{}, {}, {}]
ips benchmark:

Warming up --------------------------------------
                one?   249.158k i/100ms
           size == 1   262.143k i/100ms
Calculating -------------------------------------
                one?     11.566M (± 4.5%) i/s -     57.805M in   5.010614s
           size == 1     15.131M (± 4.0%) i/s -     75.759M in   5.016508s

Comparison:
           size == 1: 15131200.5 i/s
                one?: 11565752.4 i/s - 1.31x  slower
```

**Comment by krzysiek1507** [comment]
@kamipo do you think if it's worth to merge or should I close it?

**Comment by kamipo** [comment]
Do you think we should not use `.one?`, and should replace that all to `.size == 1`? There is not the only place to use `.one?`.

If we should not use `.one?`, I think it should be enforced by RuboCop since we sometimes use (prefer) `.one?` over `.size == 1` for Rubyish style.

**Comment by kaspth** [comment]
I’m quite surprised that’s how one? works. Do other Enumerable predicates expect a literal true as well? Is this something we can file on Ruby Core?

**Comment by krzysiek1507** [comment]
The purpose for `.one?` w/o block is to check if only one element in the collection is truthy.
```ruby
:001 > [nil, {}, nil].one?
 => true
```

```ruby
:002 > [nil, {}, nil].size == 1
 => false
```

Of course `HashWithIndifferentAccess#update` fails when non-hash arguments provided so it works without issues.

I cannot see any RuboCop rules for it but it makes sense since the results of `.one?` and `.size == 1` are equal only when a collection has only one element and the element is truthy but their purposes are completely different.
If we wanted to check `[false].one?` (false) it would return a different result than `[false].size == 1` (true).

**Comment by krzysiek1507** [comment]
> I’m quite surprised that’s how one? works.

I was surprised too but I think it makes sense. 
`any?` w/o block checks if any of the elements is truthy.
`all?` w/o block checks if none of the elements is falsy.
`none?` w/o block checks if all of the elements are falsy.

**Comment by kaspth** [comment]
Ah, so it does work on truthy values too. From the documentation it seemed like it was only `true` that’d do it.

**Comment by kaspth** [comment]
Why do we even have the extra if branch? Is it for speed? Wonder if we could fix this via the method signature, if we do need this extra logic.

**Comment by krzysiek1507** [comment]
The tests are more precise: https://github.com/ruby/ruby/blob/826f44834fe11f3f9c52343443a15b6c83466889/spec/ruby/core/enumerable/one_spec.rb#L33-L50



> Why do we even have the extra if branch? Is it for speed? Wonder if we could fix this via the method signature, if we do need this extra logic.

Good point. It looks like it can just iterate over the `other_hashes`.

**Comment by kamipo** [comment]
Yes, it is for speed. Ref https://github.com/rails/rails/pull/36880#issuecomment-519184555.

possible variant is e.g. using `other_hashes.empty?`:

```diff
diff --git a/activesupport/lib/active_support/hash_with_indifferent_access.rb b/activesupport/lib/active_support/hash_with_indifferent_access.rb
index a92bfa5c2b..1764a467e7 100644
--- a/activesupport/lib/active_support/hash_with_indifferent_access.rb
+++ b/activesupport/lib/active_support/hash_with_indifferent_access.rb
@@ -124,14 +124,13 @@ def []=(key, value)
     #   hash_1[:key] = 10
     #   hash_2['key'] = 12
     #   hash_1.update(hash_2) { |key, old, new| old + new } # => {"key"=>22}
-    def update(*other_hashes, &block)
-      if other_hashes.one?
-        update_with_single_argument(other_hashes.first, block)
-      else
-        other_hashes.each do |other_hash|
-          update_with_single_argument(other_hash, block)
-        end
-      end
+    def update(other_hash, *other_hashes, &block)
+      update_with_single_argument(other_hash, block)
+
+      other_hashes.each do |hash|
+        update_with_single_argument(hash, block)
+      end unless other_hashes.empty?
+
       self
     end
 
```

**Comment by eugeneius** [comment]
That isn't entirely compatible with the default implementation:

```ruby
$ irb
irb(main):001:0> {}.update
=> {}
```

There's a Ruby spec that covers this case:

https://github.com/ruby/ruby/blob/86431f5075d0495783776b0d7f162df387e7cde6/spec/ruby/core/hash/shared/update.rb#L73-L76

I don't think it's worth breaking an edge case for a micro-optimisation.

**Comment by krzysiek1507** [comment]
Some benchmarks:
```ruby
# frozen_string_literal: true

require 'benchmark/ips'
require 'benchmark/memory'

begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'activesupport', git: 'https://github.com/rails/rails'
end

require 'active_support/hash_with_indifferent_access'

class WithSize < ActiveSupport::HashWithIndifferentAccess
  def update(*other_hashes, &block)
    if other_hashes.size == 1
      update_with_single_argument(other_hashes.first, block)
    else
      other_hashes.each do |other_hash|
        update_with_single_argument(other_hash, block)
      end
    end
    self
  end
end

class Iterate < ActiveSupport::HashWithIndifferentAccess
  def update(*other_hashes, &block)
    other_hashes.each do |other_hash|
      update_with_single_argument(other_hash, block)
    end

    self
  end
end

tests = [
  [],
  [{}],
  [{ a: 1 }, { b: 2 }]
]

tests.each do |test|
  puts "Testing: #{test.inspect}\n"

  [:ips].each do |type|
    puts "#{type} benchmark:"
    puts

    Benchmark.public_send(type) do |x|
      x.report('Original') { ActiveSupport::HashWithIndifferentAccess.new.update *test }
      x.report('WithSize') { WithSize.new.update *test }
      x.report('Iterate') { Iterate.new.update *test }

      x.compare!
    end

    puts
  end
end

```

```ruby
Testing: []
ips benchmark:

Warming up --------------------------------------
            Original    74.678k i/100ms
            WithSize    76.642k i/100ms
             Iterate    74.608k i/100ms
Calculating -------------------------------------
            Original      1.006M (± 5.4%) i/s -      5.078M in   5.062762s
            WithSize      1.051M (± 7.3%) i/s -      5.288M in   5.063724s
             Iterate    990.313k (± 5.0%) i/s -      4.999M in   5.060798s

Comparison:
            WithSize:  1050912.5 i/s
            Original:  1006071.5 i/s - same-ish: difference falls within error
             Iterate:   990313.1 i/s - same-ish: difference falls within error


Testing: [{}]
ips benchmark:

Warming up --------------------------------------
            Original    63.717k i/100ms
            WithSize    68.466k i/100ms
             Iterate    63.137k i/100ms
Calculating -------------------------------------
            Original    872.207k (± 4.9%) i/s -      4.396M in   5.053836s
            WithSize    912.436k (± 4.3%) i/s -      4.587M in   5.037112s
             Iterate    813.308k (± 4.9%) i/s -      4.104M in   5.059172s

Comparison:
            WithSize:   912435.7 i/s
            Original:   872206.9 i/s - same-ish: difference falls within error
             Iterate:   813308.1 i/s - 1.12x  slower


Testing: [{:a=>1}, {:b=>2}]
ips benchmark:

Warming up --------------------------------------
            Original    31.533k i/100ms
            WithSize    33.266k i/100ms
             Iterate    32.317k i/100ms
Calculating -------------------------------------
            Original    361.729k (± 9.2%) i/s -      1.797M in   5.014629s
            WithSize    387.445k (± 4.6%) i/s -      1.963M in   5.077633s
             Iterate    379.590k (± 7.9%) i/s -      1.907M in   5.058915s

Comparison:
            WithSize:   387445.0 i/s
             Iterate:   379589.7 i/s - same-ish: difference falls within error
            Original:   361729.4 i/s - same-ish: difference falls within error
```

**Comment by krzysiek1507** [comment]
Is it going to be merge or should I close it?

**Comment by eugeneius** [comment]
This patch makes a reasonably hot path marginally faster, so I'm happy to merge it. We can't enforce this usage with RuboCop in general since it depends on the contents of the enumerable.

**Pull request merged**
