### PR TITLE
Don't accidentally lose includes in serialization

### PR DESCRIPTION
**Pull request by mmangino**
### Summary

We had a major production bug caused by an includes change that looks like this:

```
  includes: [:user,
                   :account,
                   templates: {only: :id},
                   addresses: {only: id}]
```

In this case, the last include is a single hash with two keys instead of two hashes with a single value. ActiveModel throws away all but the first key in this case, silently ignoring a passed option. This was tricky to find since it looks like addresses is provided, but you don't get addresses back.

This change will include all keys from a passed hash.

### CODE REVIEW

**Comment by tenderlove** [comment]
@mmangino is this a regression?  If so, when was the last known working version?

**Comment by mmangino** [comment]
I don't think it is a regression. We just got bit by the behavior. It seems odd to allow a hash but to silently discard parts of it. 

That said, I understand if you don't want to change this behavior.

**Comment by mmangino** [comment]
@tenderlove @maclover7 is there anything I should do for this? Would you prefer it raise a usage exception? I just want to have a way to catch this failure so it doesn't bight somebody like it bit us.

**Comment by mmangino** [comment]
@maclover7 Anything you want me to do with this?

**Comment by kamipo** [comment]
Multiple `:includes` with options in serialization was supported since #3295.
But #3295 takes first one only in `:includes` which has options.
Taking all `:includes` with options is reasonable, it looks fine to me.

**Pull request merged**
