### PR TITLE
Adds support for migrating databases on projects that configures two or more connections.

### PR DESCRIPTION
**Pull request by rafael-pl07c3**
Just run `$ rake db:create db:migrate` command with the environment variable `RAILS_NAMESPACE` that migration in the folder `db/[namespace]` will be executed.
In the `Engines` the generation of migration in projects are automatically created in the folder with the engine name (namespace) and without dot (.) followed by the engine name.

### CODE REVIEW

**Comment by maclover7** [comment]
Can you take a look at how you created this branch? Looks like you have pulled into 250+ commits...

**Comment by rplaurindo** [comment]
So sorry, i created by the branch "master".
How should do to bring all these commits that are not mine?

**Comment by rafaelfranca** [comment]
No need to be sorry, it happens. Seems you master branch were outdated with the current master. You can fix it rebasing.

**Comment by rplaurindo** [comment]
OK my friend. Should do the ```git rebase``` and create a new pull request?

**Comment by kaspth** [comment]
@rplaurindo using git rebase will fix this pull request, no need for another one 😁

**Comment by rplaurindo** [comment]
@kaspth I started all over again after reading the guideline RR to make rebase. Thanks.

**Pull request closed without merging**
