### PR TITLE
Fix rounding problem for PostgreSQL timestamp column

### PR DESCRIPTION
**Pull request by kamipo**
If timestamp column have the precision, it need to format according to
the precision of timestamp column.

### CODE REVIEW

**Comment by kaspth** [comment]
Can you show a before and after example?

**Comment by kamipo** [comment]
Related to https://github.com/rails/rails/issues/17239, https://github.com/rails/rails/pull/18067.

If extra fractional seconds was sent when timestamp column have the precision, it's caused rounding behavior.

```ruby
create_table(:foos, force: true) do |t|
  t.datetime :created_at, precision: 0
  t.datetime :updated_at, precision: 4
end
date = ::Time.utc(2014, 8, 17, 12, 30, 0, 999999)
Foo.create!(created_at: date, updated_at: date)
foo = Foo.take
assert_equal date.to_s, foo.created_at.to_s
assert_equal date.to_s, foo.updated_at.to_s
```
```
# before
Expected: "2014-08-17 12:30:00 UTC"
  Actual: "2014-08-17 12:30:01 UTC"

# after
success!
```

**Comment by pixeltrix** [comment]
@kaspth it's generalising #18067 to apply to PostgreSQL as well so I think we're good to merge once it's rebased - can you do that @kamipo, thanks.

**Comment by kamipo** [comment]
Rebased on master!

**Comment by pixeltrix** [comment]
@kamipo thanks - just waiting for Travis to finish

**Comment by pixeltrix** [comment]
Backported to 4-2-stable in 03b304c

**Comment by sgrif** [comment]
Why does this only have a test for PG when it modifies the behavior of all four adapters?

**Comment by pixeltrix** [comment]
Because the test is already there for MySQL from #18067 - this also applies the rounding fix from there to PostgreSQL.

**Pull request merged**
