### PR TITLE
Optimize enumerable methods for collection associations

### PR DESCRIPTION
**Pull request by vitalikdanchenko**
Optimize `none?` and `one?` methods for `CollectionAssociation` class to prevent of loading the entire records into memory when no block given. And of course tests.

### CODE REVIEW

**Comment by kirs** [comment]
:+1:

**Comment by rafaelfranca** [comment]
Could you add a CHANGELOG entry and squash your commits?

**Comment by vitalikdanchenko** [comment]
@rafaelfranca, done

**Comment by matthewd** [comment]
This was already done in #12670; your tests pass on master.

**Comment by rafaelfranca** [comment]
Oh!!! Thank you for reviewing again.

**Pull request closed without merging**
