### PR TITLE
Add methods [days, weeks, months, years]_between

### PR DESCRIPTION
**Pull request by bogdanvlviv**
I think it might be useful, so i decided to make this PR.

Added methods:
  `#days_between`
  returns the number of days to given date, default to +Date.current+.

  `#weeks_between`
  returns the number of weeks to given date, default to +Date.current+.

  `#months_between`
  returns the number of months to given date, default to +Date.current+.

  `#years_between`
  returns the number of years to given date, default to +Date.current+.

Your thoughts guys?

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Thank you so much for the pull request but we avoid adding new methods to active record core extension unless it is useful for the framework or many web applications.

**Comment by bogdanvlviv** [comment]
how to know does it useful for many web application?
I see a lot of info on queries in Google:
["rails days beetwen dates"](https://www.google.com.ua/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=rails+days+beetwen+dates)
["rails month beetwen dates"](https://www.google.com.ua/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=rails+month+beetwen+dates)
["rails years between dates'](https://www.google.com.ua/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=rails+years+between+dates)

**Comment by chrisarcand** [comment]
I agree with @rafaelfranca. Please keep in mind that if it's really common enough for your frequent use, it needn't be a part of ActiveSupport and seems like a great idea for a simple gem. (I just found https://github.com/abhidsm/time_diff as such an example)

**Comment by bogdanvlviv** [comment]
@chrisarcand i agree, thanks for explanation!

**Pull request closed without merging**
