### PR TITLE
[Rails4 regression] prevent thin and puma cause error in Non ASCII URL on Windows

### PR DESCRIPTION
**Pull request by marutosi**
- https://github.com/rails/rails/issues/19187
- https://github.com/rails/rails/pull/19533
- https://github.com/macournoyer/thin/issues/268

These are serious Rails 4 regression for Redmine Bitnami Windows users.

https://community.bitnami.com/t/problems-with-3-0-1-installation-see-report-inside/30195/

It is not caused on webrick users.

Related:
- https://github.com/rack/rack/issues/732#issuecomment-67677272
- https://github.com/phusion/passenger/issues/1328

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Could you please squash your commits?

**Comment by marutosi** [comment]
Which revisions?

**Comment by rafaelfranca** [comment]
The gemfile changes can be grouped in one commit and the last two commits also.

**Comment by rafaelfranca** [comment]
BTW, awesome work :heart:

**Comment by marutosi** [comment]
> Could you please squash your commits?

Done.

**Comment by rafaelfranca** [comment]
Merged at bfe6507f59426153c1991bf9de740c0393d08873

**Comment by rafaelfranca** [comment]
Backported as 4df216c

**Comment by rafaelfranca** [comment]
@marutosi thank you so much for the fix

**Pull request closed without merging**
