### PR TITLE
Allow escaping of literal colons in ActionRecord::Sanitization#replace_named_bind_variables

### LINKED ISSUE #37779: ActionRecord::Sanitization, replace_named_bind_variables raises exception if timestamp format text present
### Steps to reproduce

1. Have any database that is supported by Rails and has time formatting functions. (Postgres' `to_timestamp(text, text)` for example)
2. Connect to rails console and execute the following:

```ruby
raw_sql = "SELECT TO_TIMESTAMP(:date_str, 'YYYY/MM/DD HH12:MI:SS');"
ActiveRecord::Base.sanitize_sql([raw_sql, date_str: '2017/08/02 10:59:00'])
```

### Expected behavior

It should return, if given some form of escaping strategy (ie `::` or `\:`):

```ruby
"SELECT TO_TIMESTAMP('2017/08/02 10:59:00', 'YYYY/MM/DD HH12:MI:SS');"
```

### Actual behavior

Raises the following exception:

```ruby
ActiveRecord::PreparedStatementInvalid: missing value for :MI in SELECT TO_TIMESTAMP(:date_str, 'YYYY/MM/DD HH12:MI:SS');
from /Users/justin/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/sanitization.rb:198:in `block in replace_named_bind_variables'
```

### System configuration
**Rails version**: 5.2.2.1, 6.0.1

**Ruby version**: 2.5.5, 2.6.5

### Discussion

The issue at hand is due to [`replace_named_bind_variables`](https://github.com/rails/rails/blob/v6.0.1/activerecord/lib/active_record/sanitization.rb#L182-L192) providing no mechanism to escape the `:` character when it is not intended to be a named bind variable placeholder.

One workaround is to use non-named parameter binding (rely on `?`). This is a non-starter in my opinion as it doesn't take many variables for this to get confusing. Especially if you're using the same parameter multiple times throughout a large SQL query.

### Solution

I propose an escape character to indicate that a `:` is intended to be literal and not a placeholder for a variable.

For example:

```ruby
raw_sql = "SELECT TO_TIMESTAMP(:date_str, 'YYYY/MM/DD HH12\\:MI\\:SS');"
ActiveRecord::Base.sanitize_sql([raw_sql, date_str: '2017/08/02 10:59:00'])
# => "SELECT TO_TIMESTAMP('2017/08/02 10:59:00', 'YYYY/MM/DD HH12:MI:SS');"
```

Or, alternatively

```ruby
raw_sql = "SELECT TO_TIMESTAMP(:date_str, 'YYYY/MM/DD HH12::MI::SS');"
ActiveRecord::Base.sanitize_sql([raw_sql, date_str: '2017/08/02 10:59:00'])
# => "SELECT TO_TIMESTAMP('2017/08/02 10:59:00', 'YYYY/MM/DD HH12:MI:SS');"
```

### PR DESCRIPTION
**Pull request by f3ndot**
### Summary

Fixes #37779.

This PR simply allows the ability to escape literal colons in SQL when using named bind params. See the above issue for a detailed description of the problem.

### Other Information

If this proposal is accepted, I would love to also backport to 5.x as well.

### CODE REVIEW

**Comment by dmitrytrager** [comment]
Can we update this one?

**Comment by victorlcampos** [comment]
Hi guys,
some news about this issue?

**Comment by ferrucc-io** [comment]
Would be great to update this one!

**Comment by nickurban** [comment]
This is still a problem...

**Comment by skipkayhil** [comment]
I'm unable to reopen because the PR is pointing at the `master` branch which no longer exists, so I would recommend opening a new PR

**Comment by f3ndot** [comment]
Hiya @skipkayhil, I've recreated the PR against `rails/main` here: https://github.com/rails/rails/pull/48852

**Pull request closed without merging**
