### PR TITLE
Optimize dangerous_attribute_method?

### PR DESCRIPTION
**Pull request by casperisfine**
Profiling our application boot shows this method at 1.3% of boot time:

```
ActiveRecord::AttributeMethods::ClassMethods#dangerous_attribute_method? (/tmp/bundle/ruby/2.7.0/bundler/gems/rails-4919b459d946/activerecord/lib/active_record/attribute_methods.rb:100)
  samples:     5 self (0.0%)  /    866 total (1.3%)
  callers:
     866  (  100.0%)  ActiveRecord::AttributeMethods::PrimaryKey::ClassMethods#dangerous_attribute_method?
  callees (861 total):
     861  (  100.0%)  ActiveRecord::AttributeMethods::ClassMethods#method_defined_within?
```

[A quick benchmark](https://gist.github.com/casperisfine/0ce1161253ab643f5f15ff63e901b818) shows that we can make it 2 to 3 times faster by precomputing the list of dangerous methods, and doing a simple set lookup.

Of course this isn't strictly equivalent, as it's no longer dynamic, so if you include a module in `AR::Base` after the list was computed, new dangerous methods won't be considered. But at the same time, if the list was already computed, it means you defined attribute methods before AR::Base was fully initialized.

`dangerous_class_method?` is pretty much invisible on profiles, but I applied the same optimization to it for consistency's sake.

cc @rafaelfranca @etiennebarrie @Edouard-chin

### CODE REVIEW

**Comment by kaspth** [comment]
I’m curious what the cost of now retaining this memory is on your app?

**Comment by casperisfine** [comment]
Right I should have mentioned the memory tradeoff.

```ruby
>> DeepMemsize.memsize_of(ActiveRecord::Base.instance_variable_get(:@dangerous_attribute_methods))
=> 33381
DeepMemsize.memsize_of(ActiveRecord::Base.instance_variable_get(:@dangerous_class_methods))
=> 56668
```

So that's `87.9 KiB`. Or only `32.6 KB` if we only cache the attribute methods. Maybe the tradeoff isn't worth it for the class_methods as it is much more rarely called.

Also these figure are not specific to our app, as the cache is defined by methods in Active Record itself and not by the application code.

**Comment by casperisfine** [comment]
Actually wait, my memory figures are all wrong because the cached string come from symbols, so they are already in memory. Let me correct these numbers.

**Comment by casperisfine** [comment]
```
>> set = ActiveRecord::Base.instance_variable_get(:@dangerous_attribute_methods); nil
>> ObjectSpace.memsize_of(set) + ObjectSpace.memsize_of(set.instance_variable_get(:@hash))
=> 14472
>> set = (ActiveRecord::Base.methods + ActiveRecord::Base.private_methods - Object.methods - Object.private_methods).map { |m| -m.to_s }.to_set.freeze; nil
>> ObjectSpace.memsize_of(set) + ObjectSpace.memsize_of(set.instance_variable_get(:@hash))
=> 28808
```

So `14.1KiB` (attributes) and `28.1 KiB` (class) for a total of `42.3 KiB`.

NB: this relies on `ObjectSpace.memsize_of`, which isn't guaranteed to be correct, but should give a decent idea.

My previous remark remain, I'm not sure `dangerous_class_methods?` justify this extra retained memory as it's very rarely called.

**Comment by kaspth** [comment]
Got it. Maybe there's some extra readability/maintainability gain if we compute both of these eagerly? Something ala:

```ruby
def dangerous_attribute_method?(name) # :nodoc:
  self != Base ? Base.dangerous_attribute_method?(name) : dangerous_methods[:attribute].include?(name.to_sym)
end

def dangerous_class_method?(name)
  self != Base ? Base.dangerous_class_method?(name) : dangerous_methods[:class].include?(name.to_sym)
end

def dangerous_methods
  @dangerous_methods ||= {
    attribute: instance_methods + private_instance_methods - superclass.instance_methods - superclass.private_instance_methods,
    class: methods + private_methods - Object.methods - Object.private_methods + RESTRICTED_CLASS_METHODS
  }.transform_values { |value| value.map(:-@).to_set.freeze }
end
```

I used symbols for storage since I don't think quite understand why we'd need to use strings these days?

**Comment by casperisfine** [comment]
Yes that's one possibility. We could also define that as a singleton on `AttributeMethods` so that we don't have to delegate to `Base`.

Also based on the numbers above, I don't think caching `dangerous_class_method?` is worth it.

**Comment by kaspth** [comment]
Got it. Happy to see a version of that 🤘

Not sure if there’s threading concerns from having it at the class level, but we’ll see.

**Comment by casperisfine** [comment]
> Not sure if there’s threading concerns from having it at the class level

Well, AFAIK it's called from attribute definition that already synchronize a mutex. But regardless, even if you hit a race and compute it twice, well, the result should be consistent, so I guess it's fine.

**Comment by casperisfine** [comment]
I updated the PR based on our discussion. Only `dangerous_attribute_methods?` is cached, and it's cached inside `AttributeMethods`.

**Comment by kaspth** [comment]
Dig that we just reference Base at definition time and then don’t have to check it in the caller.

**Comment by casperisfine** [comment]
Thanks @kaspth!

**Comment by kaspth** [comment]
I forgot, did we think about a case where someone’s dynamically included a module on Base, like in an app initializer? Or with a after_initialize callback?

**Comment by casperisfine** [comment]
Yes it's in the PR description:

> Of course this isn't strictly equivalent, as it's no longer dynamic, so if you include a module in AR::Base after the list was computed, new dangerous methods won't be considered. But at the same time, if the list was already computed, it means you defined attribute methods before AR::Base was fully initialized.

**Pull request merged**
