### PR TITLE
ActionMailer will now accept config settings for delivery methods.

### LINKED ISSUE #35416: Unable to configure ActionMailer custom delivery methods
### Steps to reproduce

1. `git clone git@github.com:Benjamin-Dobell/actionmailer-delivery-gem-test.git`
2. `cd actionmailer-delivery-gem-test`
3. `bundle`

#### Option A

4. `rails console`
5. Enter `ActionMailer::Base.delivery_method`

#### Option B

4. `rails server`
5. Visit `http://localhost:3000`

#### Option A
Expect to see `:foo` printed.

#### Option B
Expect error `Not a real mailer` - which is intentionally raised when our test FooMailer gem is used.

### Actual behavior

> NoMethodError (undefined method `foo_settings=' for ActionMailer::Base:Class)

is raised. Refer to "More details" below for an explanation.

### System configuration
**Rails version**:
5.2.2 (down to at least 3)

**Ruby version**:
2.6.1

### More details

The ActionMailer railtie looks at `config.action_mailer` and assigns these options to `ActionMailer::Base`. However, it was does so as soon as `ActionMailer` is loaded (`ActiveSupport.on_load(:action_mailer)`).

However, `ActionMailer` (and its config) is explicitly designed to be extensible, specifically ActionMailer allows third-party gems to register additional "delivery methods".

Delivery methods can be registered with third-party Railtie by using:

```ruby
class Railtie < ::Rails::Railtie
  initializer "foomailer.add_delivery_method" do
    ActiveSupport.on_load(:action_mailer) do
      add_delivery_method :foo, FooMailer
    end
  end
end
```

`add_delivery_method` adds support for `ActionMailer::Base.foo_settings` (and therefore support for `config.action_mailer.foo_settings`) - https://github.com/rails/rails/blob/master/actionmailer/lib/action_mailer/delivery_methods.rb#L51.

However, calling `add_delivery_method` requires `ActionMailer` to be loaded, therefore the config has already have been assigned on `ActionMailer::Base`, so there's no opportunity to add:

```ruby
config.action_mailer.foo_settings = {
  prop_test: true
}
```

If you are to put the above directly in your environment config, you get an error because when the `ActionMailer` is loaded (error is within the `actionmailer` railtie). This is because third-party gems haven't run their initializers so `undefined method 'foo_settings=' for ActionMailer::Base:Class` is raised (e.g. https://github.com/mailgun/mailgun-ruby/issues/104).

Instead, if you were to move your logic into `app/initializers/foomailer.rb`:

```ruby
ActiveSupport.on_load(:action_mailer) do
  Rails.application.config do
    config.action_mailer.delivery_method = :foo
    config.action_mailer.foo_settings = {
        prop_test: true
    }
  end
end
```

**Note**: Checkout the `delayed_config` branch and repeat steps 4-5)

This _silently_ fails, because we're assigning the config _after_ `ActionMailer` has been loaded (and the config copied across), so although we've set the config it is never used and out of sync with `ActionMailer::Base`, which for example still returns `:smtp` for `ActionMailer::Base.delivery_method`, even though `Rails.application.config.action_mailer.delivery_method` correctly returns `:foo`.

### PR DESCRIPTION
**Pull request by Benjamin-Dobell**
> ActionMailer::Base.add_delivery_method can only be called after
ActionMailer::Base has loaded, in which case the actionmailer
railtie has already loaded the  config from `config.action_mailer`.
> 
> However, we want to accept `config.action_mailer.foo_settings` in
our application config (for some such :foo delivery method). Thus
we must be able to accept settings for delivery methods which are
yet to be added.

Closes https://github.com/rails/rails/issues/35416

Please refer to #35416 for full details of the underlying problem, example reproduction project and a branch using a forked `actionmailer` with this commit (cherry-picked against 5.2.2) i.e. example of this fix in place.

### Summary

`ActionMailer` now dynamically handles method calls matching `(.+)_settings=`.

This ensures configs with custom settings e.g. `config.action_mailer.foo_settings = {}` will be correctly assigned to `ActionMailer::Base.foo_settings`. Then when we proceed to register a delivery method (e.g. `add_delivery_method :foo, defaults`), the config settings (if they exist) are merged over the top of the defaults i.e. User settings take precedence.

### Other Information

This commit can be cleanly cherry-picked on the 5.2 line, as this is a bug fix, I would appreciate it if it could be cherry-picked.

### CODE REVIEW

**Comment by Benjamin-Dobell** [comment]
As is indicated by the issues references this one, this is affecting other users in addition to myself; and there have been several releases since I submitted this PR.

I would really appreciate if someone could review this.

**Comment by Benjamin-Dobell** [comment]
This went 10 months without review, or any feedback from the Rails team, and has now been automatically closed. Say I did want this reviewed and ideally merged, how would I go about that?

**Comment by grantkayes** [comment]
I'm also experiencing this error and would be interested in getting it merged!

**Comment by spjsschl** [comment]
we have experienced the same problem

**Comment by Benjamin-Dobell** [comment]
@grantkayes, @spjsschl I'm not sure how much attention the Rails team pay to closed PRs.

I'd suggest instead commenting on #35416, asking for this PR to be re-opened.

**Comment by SanjanaB** [comment]
We have the same problem as well. Can this PR be merged??

**Pull request closed without merging**
