### PR TITLE
PostgreSQL: Type cast via ruby-pg

### PR DESCRIPTION
**Pull request by larskanis**
This pull request moves type casts for several data types into the scope of ruby-pg. This is done in three parts:
1. As generic type casts of common Ruby classes for database inputs and PostgreSQL outputs. This is similar to the type casting of mysql2 and sqlite3 gems.
2. As cached type maps alongside the prepared query statement.
3. As explicit type en/decoder for more complex data types like Array types.

This simple benchmark should get a speedup of 50%: https://gist.github.com/larskanis/aec0a74cb3454f696b08

### CODE REVIEW

**Comment by larskanis** [comment]
I've done a rebase to master and added much better descriptions to the single commits. This hopefully give a better understanding of why these changes should be done. The commits are also rearranged, so that the least controvertible comes first (according to my understanding of course). I made sure, that each single commit passes the activerecord test suite, in case you don't like all of them.

The performance improvements are still equal to that of [November (column all queries cached)](https://github.com/rails/rails/pull/17650#issuecomment-63980686) . That means 5% for the first 5 commits and another 5% for the CountedStatementPool implementation measured with the Discourse benchmark.

**Comment by sgrif** [comment]
@larskanis Thank you for your hard work on this. I'll give it a deeper look today.

**Comment by SamSaffron** [comment]
I am super excited about these changes! awesome work

**Comment by larskanis** [comment]
I think, it's more the hard work of Sean and Yves to continuously cleanup and revamp the type system since the days of rails-4.0. The type cast optimizations wouldn't be possible without that.

**Comment by sgrif** [comment]
@larskanis If you want to go ahead and rebase this, I merged all of the commits that were good to go, and commented on the ones that weren't.

**Comment by sgrif** [comment]
I'm going to close this due to inactivity. The biggest pieces of this were merged in isolation. If you or someone else wants to take the reigns on picking the other pieces back up, feel free to open new PRs (the remaining commits have comments on what would need to be changed, and they should each be able to be a separate PR)

**Pull request closed without merging**
