### PR TITLE
Support mysql2 0.4.x and 0.5.x

### LINKED ISSUE #31636: Upcoming release: mysql2 gem 0.5.0
Hello! When I last released a new "major" version of the mysql2 gem, there was some widespread grumbling as users were able to update their gems locally without constraints, but at runtime received errors because the gem version is specific in the mysql2 adapter https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb#L6 

I am planning a mysql2 0.5 release this quarter. It will be fully compatible with 0.4.x. Is there something I can do to help avoid the user pain this time around? Would calling the new version 1.0.0 help by allowing you to drop the requirement from within the adapter and instead put it into a gemspec, as seen at https://github.com/rails/rails/blob/master/Gemfile#L131 ?

Or is this simply an understood-enough situation that is common to all of the connection adapters, as seen by the gem versioning in many of https://github.com/rails/rails/tree/master/activerecord/lib/active_record/connection_adapters and I shouldn't worry about it.

Could I nudge Rails 5.2.0 to ship with `gem "mysql2", "~> 0.5.0"` at the appropriate time?

### PR DESCRIPTION
**Pull request by sodabrew**
Resolves #31636 following release of mysql2 0.5.0 today.

### CODE REVIEW

**Comment by matthewd** [comment]
You probably want to change this too: https://github.com/rails/rails/blob/89bcca59e91fa9da941de890012872e8288e77b0/railties/lib/rails/generators/app_base.rb#L302

I guess this diff tells me you at least read my comment, so that's nice 🤷‍♂️

**Comment by sodabrew** [comment]
Thanks I will add that change, too!

**Comment by Edouard-chin** [comment]
Should this be backported to 5-2-stable? Otherwise mysql2 0.5.0 will be only usable on Rails 6.0

**Comment by kamipo** [comment]
Yeah, I will do that.

**Comment by rafaelfranca** [comment]
And 5-1-stable too

**Comment by kamipo** [comment]
Backported in 6965f2afeda01f7afe8baffe3e95d52e829259be and 6a11d833ec64ef6662fa17286e521b1c1ba749fc.

**Comment by pixeltrix** [comment]
@kamipo doesn't 6965f2a need to be in 5-2-stable? It's currently in 5-2-0 only (@rafaelfranca what's the policy here - backport to 5-2-stable and then cherry-pick what we want in 5-2-0 or backport to 5-2-0 and then that'll be merged into 5-2-stable at some point?)

**Comment by matthewd** [comment]
5-2-0 will merge to 5-2-stable on release, so yeah seems fine to backport straight to there if we know it's post-rc-worthy

**Comment by kamipo** [comment]
Yeah, I supposed that 5-2-0 will be merged to 5-2-stable since db7edd81062648281d1e50c8ff9ebfafac5a9c3d is missing in 5-2-stable yet, and I needed the commit to add CHANGELOG entry 3eadd23a8a59e4c88190c2b2c4443b85b11d3724.

**Comment by hkdnet** [comment]
It looks that 5-0-stable also needs this patch, right?
The head of 5-0-stable does not pass the ci.
https://travis-ci.org/rails/rails/builds/357081953

**Comment by jaredbeck** [comment]
> And 5-1-stable too

Thanks for backporting :heart:

> It looks that 5-0-stable also needs this patch, right?

If I understand correctly, 5.0 only receives security patches now (2018-03-23), and as soon as 5.2 is released, 5.0 will be EoL.

**Comment by pixeltrix** [comment]
I've backported this and the dalli fix to 5-0-stable and 4-2-stable just to be on the safe side - they're still used in a lot of apps so we at least want the build to be green should the worst happen and we have to release new gems for a major security issue.

**Pull request merged**
