### PR TITLE
Make polymorphic associations joinable by specifying its classes

### PR DESCRIPTION
**Pull request by ghost**
Polymorphic associations have not been join-able and therefore were
not very memory efficient or fast when alot of data had to be processed
that was associated by a polymorphic.

Since it is also not possible to guess at application boot time which
models might be associated, a good way is to let the developer specify
the associated models that he wants to join eventually.

The join is processed by left outer joining the polymorphic tables.
Inner joins do not work, since they are mutually exclusive on belongs_to
associations and the resultset would therefore be empty.

Example:
  class Treasure < ActiveRecord::Base
    belongs_to :looter, :polymorphic => true, :poly_classes => [Parrot, Pirate]
  end

  Ship.joins(:treasures => :looter).where(:parrots => { :name => Mona })

### CODE REVIEW

**Comment by egilburg** [comment]
Could this done dynamically by checking the other side of the association? (`has_one :treasure, as: :looter`)

**Comment by matthias-geier** [comment]
The opposite side is not automatically associated, so you'd have to check all loaded models for an association that might fit as opposite and even then you'd have to match assoc chains.

I pondered about it a while back, how to autodetect the opposite models, but either you build an auto-register mechanic at load-time or you scan through all models every single time you use a join. Neither is too appealing to me. When I write associations, I know which models I am dealing with, and putting them into a list for the benefit of being able to join them is worth it.

**Comment by egilburg** [comment]
Rails uses an auto-register pattern with `inverse_of` - see http://apidock.com/rails/ActiveRecord/Reflection/AssociationReflection/automatic_inverse_of

**Comment by matthias-geier** [comment]
I can look at it tomorrow and check whether inverse_of will be accessible when the JoinDependecy is created. If it is, I can refactor the code to use it instead of the configuration

**Comment by matthias-geier** [comment]
It was worth looking into, but `reflections.rb` tells me these

```ruby
  VALID_AUTOMATIC_INVERSE_MACROS = [:has_many, :has_one, :belongs_to]
  INVALID_AUTOMATIC_INVERSE_OPTIONS = [:conditions, :through, :polymorphic, :foreign_key]
```

After browsing some more code, inverse_of, as I understand it, is the reason that you can call `Ship.reflections["treasures"].klass` for the opposite klass, but with a polymorphic that cannot work (and does not: `Treasure.reflections["looter"].klass` produces an error while `Treasure.reflections["ship"].klass` works). `klass` would return a list of klasses instead.

So far I'd have to stick with the configuration of the classes.

**Comment by kmerz** [comment]
:+1: Would like to have it!!

**Comment by arthurnn** [comment]
As far as I understand, this new option is for `memory` space optimization.
Can you post a few stats of before and after, and what this is really saving.

thanks

**Comment by matthias-geier** [comment]
Actually the main benefit is speed by removing unnecessary queries on the database and still use AR like always.

Assume you want to get all the treasure ships with a looting parrot called Mona and also those with looting pirate called Jack. Right now you have to

   ids = Parrot.joins(:treasures).where(:name => "Mona").pluck("treasures.id") + 
    Pirate.joins(:treasures).where(:name => "Jack").pluck("treasures.id")
  Ship.where(:id => ids)

It's 3 queries (that are already optimized, other people may still use each loops for this) and quite some code. It is possible to do it in one even now, but it is ugly and alot of code. This change will make it happen by using rails and with one query.

As for your question about memory... If you are doing it 'right' by using pluck, you will not save much. If you use a loop, then you will save the memory for every treasure you instance.

Does this help you?

**Pull request closed without merging**
