### PR TITLE
Update Migration number to ensure consistency on the document [ci skip]

### PR DESCRIPTION
**Pull request by davidauza-engineer**
### Summary

Hi 

I did update the guide called 'Active Record Associations' on the document called 'associations_basics.md' to: 

- [x] Ensure consistency on the document as there were cases where Migration did show 5.0 and other cases where it did show 5.2

- [x] Keep the documentation updated with the cutting edge versions of the rails products.

- [x] Ensure newcomer readers have consistent and up to date documentation that prevents them from being confused.

### Other Information

Thank you, please let me know your comments.

Kind regards from Colombia,

[David Auza](https://github.com/davidauza-engineer)

### CODE REVIEW

**Comment by vipulnsward** [comment]
There is one more occurrence in https://github.com/rails/rails/blob/db1ae8cbb4a0f2aad9053af551dde08ec0a8db2b/guides/source/active_record_basics.md#L369  can you update that as well?

**Comment by davidauza-engineer** [comment]
Sure thing @vipulnsward , it will be ready in a few minutes :)

**Comment by davidauza-engineer** [comment]
Hi @vipulnsward. The suggested change has been made :)

**Comment by vipulnsward** [comment]
Thanks, can you squash the commits?

**Comment by davidauza-engineer** [comment]
Hi @vipulnswardBoth commits were squashed as suggested :white_check_mark:

**Comment by davidauza-engineer** [comment]
Hi @vipulnsward

Both commits were squashed as suggested :white_check_mark:

**Comment by vipulnsward** [comment]
Thanks!

**Comment by davidauza-engineer** [comment]
Thank you very much for the merge @vipulnsward.

**Comment by davidauza-engineer** [comment]
Thank you very much for the merge @vipulnsward.

Best regards from Colombia.

**Pull request merged**
