### PR TITLE
Fix error in 'Action Mailer Basics' guide. [ci-skip]

### PR DESCRIPTION
**Pull request by Alamoz**
In the 'Action Mailer Basics' guide, '/bin/rails generate ...' should be 'rails generate ...'.

### CODE REVIEW

**Comment by seuros** [comment]
`rails generate` will use last version  installed.
`bin/rails`  will use the version defined in Gemfile.

**Comment by Alamoz** [comment]
bin/rails does nothing when I try running it.

**Comment by seuros** [comment]
delete that file and run `rake rails:update:bin `

**Comment by Alamoz** [comment]
Will try that. Thanks.

**Pull request closed without merging**
