### PR TITLE
added docs for ActionDispatch::Request::Session#create

### PR DESCRIPTION
**Pull request by treble37**

### CODE REVIEW

**Comment by schneems** [comment]
Get rid of the newline between the doc and the method please.

**Comment by rafaelfranca** [comment]
All this class is private. But we can always use some documentation.

**Comment by schneems** [comment]
Agreed, it can help developers who are looking to contribute directly to Rails itself.

@treble37 in the future, try not to add any whitespace to your commits. You had a bunch of spaces on line 12. Also rebase your commits so they're only one commit, check out the `git rebase -i` command with the squash option. You can also use `[CI Skip]` to skip documentation commits from triggering CI.

**Comment by treble37** [comment]
Will do, thank you for the tips @schneems!

**Pull request merged**
