### PR TITLE
 `SetupAndTeardown` has few caveats that breaks libraries

### PR DESCRIPTION
**Pull request by Edouard-chin**
- In #32472 I introduced a fix in order for all `after_teardown` method provided by libraries and Rails to run, even if the application's `teardown` method raised an error (That's the default minitest behavior). However this change wasn't enough and doesn't take in consideration the ancestors chain.
  If a library's module containing an `after_teardown` method get included after the `SetupAndTeardown` module (one example is the [ActiveRecord::TestFixtures module](https://github.com/rails/rails/blob/7d2400ab61c8e3ed95e14d03ba3844e8ba2e36e4/activerecord/lib/active_record/fixtures.rb#L855-L856), then the ancestors of the test class would look something like
  ```ruby
    class MyTest < ActiveSupport::TestCase
    end

    puts MyTest.ancestors # [MyTest, ActiveSupport::TestCase, ActiveRecord::TestFixtures, ActiveSupport::Testing::SetupAndTeardown]
  ```
  Any class/module in the ancestors chain that are **before** the `ActiveSupport::Testing::SetupAndTeardown` will behave incorrectly:
    - Their `before_setup` method will get called **after** all regular setup method
    - Their `after_teardown` method won't even get called in case an exception is raised inside a regular's test `teardown`

  A simple reproduction script of the problem here https://gist.github.com/Edouard-chin/70705542a59a8593f619b02e1c0a188c

- One solution to this problem is to have the `AS::SetupAndTeardown` module be the very first in the ancestors chain. By doing that we ensure that no `before_setup` / `after_teardown` get executed prior to running the teardown callbacks

### CODE REVIEW

**Comment by Edouard-chin** [comment]
Lot of tests are failing because we call `def setup` without calling `super`, so `SetupAndTeardown#setup` doesn't get picked up. 

Before fixing those (there is a lot), I'd like your opinion on this approach

**Comment by eugeneius** [comment]
Do the failures in the Rails test suite indicate a problem that will also affect applications? In other words, does this change make it mandatory to call `super` in your test case's `setup` and `teardown` methods?

**Comment by Edouard-chin** [comment]
@eugeneius 👋 

Yes indeed, tests that uses the vanilla `def setup` without calling `super` will stop working.
I'm not sure what minitest recommendation is on using `def setup` (are we supposed to call `super` inside it?), it's very inconsistent even in minitest's tests :D

**Comment by eugeneius** [comment]
@Edouard-chin hi. 😄 

I suspect Minitest itself doesn't care if you call `super`, since the implementation it provides [is empty](https://github.com/seattlerb/minitest/blob/2362e328883ff133140fd8bea5e9ec9a714a7999/lib/minitest/test.rb#L158). If you (as a direct user of Minitest) create test subclasses, you get to decide whether to call `super` or not - you might have a legitimate reason to skip the superclass' setup. I don't think it's reasonable for Rails to make that decision on behalf of applications, though.

To propose an alternative fix: what if we did exactly the same thing [as Minitest does](https://github.com/seattlerb/minitest/blob/2362e328883ff133140fd8bea5e9ec9a714a7999/lib/minitest/test.rb#L102-L104), i.e. [add exceptions in teardown callbacks as test failures](https://github.com/seattlerb/minitest/blob/2362e328883ff133140fd8bea5e9ec9a714a7999/lib/minitest/test.rb#L201) that will be reported to the user instead of re-raising them?

**Comment by Edouard-chin** [comment]
> you might have a legitimate reason to skip the superclass' setup

Agree.

The solution I proposed is not the correct one then. I amended my commit for another approach.

> 
To propose an alternative fix: what if we did exactly the same thing as Minitest does, i.e. add exceptions in teardown callbacks as test failures that will be reported to the user instead of re-raising them?

It's a good idea, however it will only solve part of the problem:
✅ It will solve the issue where other `after_teardown` defined in module whom have a higher priority in the ancestors chain as `AS::SetupAndTeardown` doesn't get called. Since we are no longer raising an exception but let minitest report the error only at the very end,

❌  It won't solve the issue where other `before_setup` defined in module whom have a higher priority in the ancestors chain as `AS::SetupAndTeardown` gets called after regular `setup` method.


The new commit, basically put the `SetupAndTeardown` module at the very beginning of the ancestors chain so we are sure it's `before_setup` / `after_teardown` get called first

**Pull request merged**
