### PR TITLE
Fix trilogy builds

### PR DESCRIPTION
**Pull request by eileencodes**
I found out we weren't running trilogy in CI (or locally) because I messed up the config. This PR aims to fix it.

[Fix database configuration and generation](https://github.com/rails/rails/commit/5e5300aca2029e0da64d49ad5a7359833e78eda3) 

I tried using the same config for mysql2 and trilogy but instead it
eneded up breaking the trilogy tests - they were only running in mysql2
mode. I wanted to do this so that the rake tasks for trilogy wouldn't
need to be duplicated but since that didn't work out quite right, I've
decide to duplicate the calls and add if exists / if not exists where
applicable. The configs should be the same but this will make sure that
if they do deviate, the dbs are always created/dropped.

[Raise an error if the connection name doesn't match the adapter](https://github.com/rails/rails/commit/d284d6fd22d49c4632b7390f1c2855c83d8910f6) 

This will prevent us from accidentally running mysql2 tests against
trilogy adapter as we currently are doing.

[Bump trilogy to fix connection error translation](https://github.com/rails/rails/pull/47993/commits/124298bd3f99291df7a21f5c49fb086859004273) 

Until we do a new release we need to run against main on trilogy to get
the latest changes from https://github.com/github/trilogy/pull/69

### CODE REVIEW

**Comment by eileencodes** [comment]
I'm not sure why trilogy tests are failing so badly on CI, they pass fine locally now.

**Comment by eileencodes** [comment]
Fixed in https://github.com/rails/rails/pull/48007

**Comment by byroot** [comment]
Uh, actually I didn't merge it 😅, I thought you'd include the commit in your PR.

**Comment by eileencodes** [comment]
Oh ok I'll reopen the PR in a new one.

**Pull request closed without merging**
