### PR TITLE
Extract `primary_key` to `AbstractReflection`

### PR DESCRIPTION
**Pull request by kamipo**

### CODE REVIEW

**Comment by matthewd** [comment]
Hmm.. I'm not sure what I think of this. On one hand, it avoids a duplicated method... but on the other, it adds that method to a bunch of classes for which it doesn't make sense. 🤔

**Comment by kamipo** [comment]
Should create new PR?

**Comment by kamipo** [comment]
I've created new PR #30209 and removed the commit that remove duplicated method in this PR.

**Comment by rafaelfranca** [comment]
I think if the method doesn't make sense in other classes we should not add it to the superclass even if it removed duplication. Unless it is a private utility method. If it is public, better to keep the duplication, or extract it to a module. In this case, the duplication is just fine in my opinion.

**Comment by kamipo** [comment]
Actually the `primary_key` is a private utility method that is used in `association_primary_key` and `active_record_primary_key` (by the way, `association_primary_key` has a bug #27609).
So I placed the method at bottom of private methods in `AbstractReflection`.

**Pull request merged**
