### PR TITLE
Add actioncable to list of release frameworks [ci skip]

### PR DESCRIPTION
**Pull request by arunagw**

### CODE REVIEW

**Comment by kaspth** [comment]
Ah, wups! Didn't notice the ci skip there. @arunagw why did you add this here? :)

**Comment by arunagw** [comment]
We don't need CI run I think for this task. Do we?

**Comment by kaspth** [comment]
Hm, well, I usually like to run CI of any code is changed, but I guess we'll if we're home free 🤓

**Comment by arunagw** [comment]
Ahh.. may be I will remove `skip ci` from here https://github.com/rails/rails/pull/22637 :-)

**Pull request merged**
