### PR TITLE
Lock sneakers version to v2.11.0 not to downgrade rake from 13 to 12

### PR DESCRIPTION
**Pull request by yahonda**
### Motivation / Background

This pull request addresses Rails CI failure against Ruby 3.2.0dev Managed to fix CI failure at https://buildkite.com/rails/rails/builds/91656#018510f2-6767-492e-bc79-d6c8bfcebc4a

### Detail

- Steps to reproduce

```ruby
git clone https://github.com/rails/rails
cd rails/railties
rm ../Gemfile.lock
bundle install # bundle update does not update sneakers to v2.12.0
bin/test test/application/bin_setup_test.rb:51 
```
- This commit fix this failure
```ruby
$ bin/test test/application/bin_setup_test.rb:51
... snip ...

F

Failure:
ApplicationTests::BinSetupTest#test_bin_setup_output [/home/yahonda/src/github.com/rails/rails/railties/test/application/bin_setup_test.rb:51]:
--- expected
+++ actual
@@ -6,6 +6,15 @@
 Created database 'app_test'

 == Removing old logs and tempfiles ==
+rails aborted!
+ArgumentError: wrong number of arguments (given 2, expected 1)

-== Restarting application server ==
+Tasks: TOP => tmp:clear => tmp:cache:clear
+(See full trace by running task with --trace)
+bin/setup:8:in `system': Command failed with exit 1: bin/rails (RuntimeError)
+\tfrom bin/setup:8:in `system!'
+\tfrom bin/setup:29:in `block in <main>'
+\tfrom /home/yahonda/.rbenv/versions/trunk/lib/ruby/3.2.0+3/fileutils.rb:244:in `chdir'
+\tfrom /home/yahonda/.rbenv/versions/trunk/lib/ruby/3.2.0+3/fileutils.rb:244:in `cd'
+\tfrom bin/setup:11:in `<main>'
 "

bin/test test/application/bin_setup_test.rb:30

Finished in 4.518178s, 0.2213 runs/s, 0.2213 assertions/s.
1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
$
```

### Additional information

It is likely due to `sneakers` v2.12.0 downgrades Rake version from 13.0.6 to 12.3.3 as `gem.add_development_dependency 'rake', '~> 12.3'` via https://github.com/jondot/sneakers/commit/591d2131b3b9d099e5b4401a0921335886ed9a2f

I'll open an issue to https://github.com/jondot/sneakers later.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [ ] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by eileencodes** [comment]
Oh I missed this when I was debugging this and opened an issue to https://github.com/rubygems/rubygems/issues/6129. 

Do you understand why sneakers causes Rake to get downgraded on only bundler 2.4.0.dev? I think it's a bug, but I don't understand why Sneakers + Bundler 2.4.0.dev downgrades Rake, but bundler 2.3.x does not.

**Comment by eileencodes** [comment]
Looks like this is confirmed to be a bug https://github.com/rubygems/rubygems/issues/6129#issuecomment-1351907137 and we should have a fix soon.

**Comment by yahonda** [comment]
Thanks for the useful info. Let's see how https://github.com/rubygems/rubygems/issues/6129 and https://github.com/rubygems/rubygems/pull/6131 go.

**Comment by yahonda** [comment]
Closing this pull request because this commit should not be merged anyway.
Technically, CI issues have been addressed via https://github.com/rails/rails/pull/46736 and the root cause will be addressed via https://github.com/rubygems/rubygems/pull/6131 once it gets merged.

**Pull request closed without merging**
