### PR TITLE
Remove unintentional differences in behaviour of SafeBuffer and String

### PR DESCRIPTION
**Pull request by semaperepelitsa**
See #22947 

It makes sense that SafeBuffer should behave like String unless there is a good reason not to. Implicit type coercion was never documented. There was a single test case involving a string-like class with `to_s` method and I believe it was a mistake. Ruby's String uses `to_str` internally to support duck typing but not allow implicit type casts - method `to_s` is defined for all objects and `to_str` is not. 

String interpolation does implicit type coercion so we keep it in SafeBuffer too.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
This patch introduces subtle change in the behaviour that would be hard to track. See the changes in Action View Helpers. I believe it is a good path forward but that may break a lot of applications. @matthewd @jeremy @tenderlove WDYT about this one?

**Comment by semaperepelitsa** [comment]
I'm not sure what you mean by "hard to track". This exposes a very common error in Ruby development - working with nil value when nil is unexpected. It will give a clear error message "no implicit conversion of nil into String (TypeError)" with a direct pointer to the troubling line of code.

I see that it may break some apps or gems. So I'm suggesting this fix for the next major release where people expect to make minor fixes and updates to their code.

**Comment by semaperepelitsa** [comment]
Any news?

**Comment by schneems** [comment]
Can we close this?

**Comment by rafaelfranca** [comment]
I don't think we can raise in code that was working before. If we want to change this behavior we first need to deprecate it and only in the next release start to raise.

**Pull request closed without merging**
