### PR TITLE
Add ability to add specify column null and default values from cli

### PR DESCRIPTION
**Pull request by TheSmartnik**
This PR adds ability to specify null and default values when generating migrations from command 
line.

I've implemented syntax like in a code below, using #15583 issue as a reference

```bash
rails g migration createPosts title:string{null=false} comments_count:integer{null=false,default=0}:index type:integer{1,default=1} 
```

P.S. I also removed note from ruby guides, but there are probably other API docs I need to change

### CODE REVIEW

**Comment by TheSmartnik** [comment]
@pixeltrix Hi, could you please check the pr? I've tested the code on test app and It all works great. Would love to hear any feedback from you

**Comment by TheSmartnik** [comment]
@pixeltrix ping

**Comment by TheSmartnik** [comment]
@pixeltrix ping

**Comment by TheSmartnik** [comment]
@rafaelfranca could you, please, check that one out? I do think that a feature is a good and worth having

**Comment by pixeltrix** [comment]
Sorry for not looking at this sooner.

Personally I don't think this is worth adding, I already virtually never add columns in a migration generator command other than to generate something for repro-ing Rails bugs and adding this makes an already long CLI command into one that IMO is way over the top.

I'd much prefer to see an option that opened the migration in your default `$EDITOR` as that's what I currently do pretty much all the time.

Thanks for the PR, sorry that we can't merge it.

**Comment by TheSmartnik** [comment]
@pixeltrix thank you for a reply

> I'd much prefer to see an option that opened the migration in your default $EDITOR as that's what I currently do pretty much all the time.

Sounds like a great feature

**Comment by matthewd** [comment]
Previously: https://github.com/rails/rails/pull/8553

If you or someone else is up for picking up that work, I'd love to have that feature too.

**Comment by rp-pedraza** [comment]
It's unfortunate that this was closed. This could have allowed migrations to be stored in a script and run in another rails setup.

**Comment by duleorlovic** [comment]
Now I I'm using https://github.com/rails/rails/pull/38870 in my scripts.
So first enable `EDITOR_FOR_GENERATOR`
```
# config/application.rb
    # https://github.com/rails/rails/pull/38870#issuecomment-609018444
    config.generators.after_generate do |files|
      if ENV["EDITOR_FOR_GENERATOR"]
        files.each do |file|
          system("#{ENV["EDITOR_FOR_GENERATOR"]} #{file}")
        end
      end
    end
```
When I want to create a migration with index (index is supported on command line using `:index`) and not null constrains for `jti` and `exp` columns I would use
```
# replace jti and exp with your column names
EDITOR_FOR_GENERATOR='sed -i "" -r -e "/^[[:space:]]*t.*(jti|exp)$/ s/$/, null: false/"' rails g migration CreateJwtDenylist jti:index exp:datetime:index
```
which adds `, null: false` to those two `t.` lines:
```
# db/migrate/20230121091319_create_jwt_denylist.rb
class CreateJwtDenylist < ActiveRecord::Migration[7.0]
  def change
    create_table :jwt_denylists do |t|
      t.string :jti, null: false
      t.datetime :exp, null: false

      t.timestamps
    end
    add_index :jwt_denylists, :jti
    add_index :jwt_denylists, :exp
  end
end
```

**Pull request closed without merging**
