### PR TITLE
[ci skip] Update docs for Validation helpers- acceptance

### PR DESCRIPTION
**Pull request by sachinmittal93**
Refer [here](https://github.com/rails/rails/blob/master/activemodel/lib/active_model/validations/acceptance.rb#L95)

### CODE REVIEW

**Comment by sgrif** [comment]
Thanks, but I don't think this is an improvement. I find the wording you've added confusing, and I'm not entirely sure what it's recommending. Are you implying that the defaults do not work?

**Comment by sachinvinsol** [comment]
yes the default do not work.it only works for virtual attribute.

**Comment by sgrif** [comment]
Why would you have a database column for this, when there's a validation that says the record cannot be saved unless it has exactly one value? There's no point in persisting that.

**Comment by sachinvinsol** [comment]
Yes, you are right. We should not support this validation for database column. 
I think that we should remove this [line](https://github.com/rails/rails/blob/master/activemodel/lib/active_model/validations/acceptance.rb#L95) as the docs are inconsistent and really confuse the reader.

**Comment by sachinvinsol** [comment]
@sgrif - Any update here? Should I update [this line](https://github.com/rails/rails/blob/master/activemodel/lib/active_model/validations/acceptance.rb#L95).

**Pull request closed without merging**
