### PR TITLE
Fix locale in pluralize

### PR DESCRIPTION
**Pull request by maxime-carbonneau**

### CODE REVIEW

**Comment by eileencodes** [comment]
Hey @maxime-carbonneau thanks for the PR. Do you have more information about what you're fixing? If the code is throwing an error can you tell me what the error is? I think this also needs a test so prevent regressions.

**Comment by maxime-carbonneau** [comment]
The method ActionView::Helpers::TextHelper#pluralize was misusing String#pluralize. It send locale to the first parameter will it should be send as the second parameter.

**Comment by maxime-carbonneau** [comment]
Nerver mind, I misunderstand how I18n is bind with this method.
Sorry. I'm still learning.

**Comment by eileencodes** [comment]
No worries @maxime-carbonneau!

**Pull request closed without merging**
