### PR TITLE
Allowing IE to save local cookies 

### PR DESCRIPTION
**Pull request by MMercieca**
### Summary

Fix for https://github.com/rails/rails/issues/28376

Not sending `domain=;` when domain is blank for cookies.  This will let IE save the cookie.  No other browsers should be impacted.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Do you know what is setting the domain to be a blank string in your application?

**Comment by rafaelfranca** [comment]
Do you have any configuration for your cookie store that specify the domain?

**Comment by MMercieca** [comment]
I was looking for the bit that set the domain to be an empty string instead of `nil` but I can't find it right now. I'll comb through Devise and the CSRF code to see if it's there.  I found this problem by looking at the effect and I saw the blank `domain=;` through Fiddler in IE.

I'll see if I can replicate the CI failure locally.

**Comment by mbhnyc** [comment]
just ran into this with our internal experimentation framework, what an annoying bug! @MMercieca @rafaelfranca seems low-risk to get this in?

**Comment by MMercieca** [comment]
I resolved the conflict via github's tool.  You can try out the patch locally.  If CI passes I think it's good.

**Pull request closed without merging**
