### PR TITLE
Use the HOST environment variable for rails server #25677

### PR DESCRIPTION
**Pull request by mahnunchik**
### Summary

Allow the server host to be set with the HOST environment variable.

### CODE REVIEW

**Comment by matthewd** [comment]
Could you expand a bit on *why* we want this?

**Comment by mahnunchik** [comment]
Hi @matthewd @maclover7 

It allows us to have control of listening port and host by environment variables. So the following variants will be similar:
```bash
$ rails server -p 8080 -b 0.0.0.0
$ HOST=0.0.0.0 PORT=8080 rails server
```

### My case
Application inside docker container should listen external ip address. So I have to set `0.0.0.0:8080` as address to bind by server.

`HOST` environment variable in addition to `PORT` variable will add uniformity to configuration process.

**Comment by guilleiguaran** [comment]
I like this ❤️

**Comment by guilleiguaran** [comment]
I merged this after of do some researching and expecting this to no cause much conflicts with other existing services/servers using the `HOST` env variable, if someone thinks this can cause problems please let me know here

**Comment by kirs** [comment]
Turns out that on some platforms `$HOST` is set by system and equals to `$HOSTNAME`. As a result `rails server` with no arguments would listen on public hostname instead of `localhost` (https://github.com/rails/rails/issues/29516). This is a security concern because the development server becomes available from the outside.

Any thoughts on how we can fix it?

**Comment by kirs** [comment]
@mahnunchik do you use this feature in development or in production?

**Comment by mahnunchik** [comment]
@kirs I use this feature in both environment, especially inside Docker containers.

**Pull request merged**
