### PR TITLE
Add webp as a default to active_storage.web_image_content_types

### PR DESCRIPTION
**Pull request by lewispb**
### Motivation / Background

Customers are uploading webp images to our app, and expect them to be rendered just like other images, instead of being converted to the fallback PNG format.

### Detail

Follows https://github.com/rails/rails/pull/38918 and https://github.com/rails/rails/pull/38988. At the time, webp browser support was limited. Now 96% of browsers support webp: https://caniuse.com/?search=webp

This PR adds webp as a default image type.

### Additional information

I think this is a sensible default in 2024, but alternatively each Rails app may choose:

```
Rails.application.configure do
  config.active_storage.web_image_content_types << "image/webp"
end
```

**Changelog**

I've not added a changelog entry in line with https://github.com/rails/rails/pull/38918#discussion_r410527726, but I'd be happy to add one if it's felt useful now.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

cc @jeremy

### CODE REVIEW

**Review by jeremy — COMMENTED** [review]
Agree that WebP should be treated as universally available. Images embedded in emails and such are a trickier spot with much thinner support, but this is targeting browsers.

Existing apps may be using imagemagick/libvips built without WebP support, so this change needs to be introduced as a new framework default.

**Comment by lewispb** [comment]
Good call on the new framework default @jeremy. Smooths the upgrade.

**Comment by guilleiguaran** [comment]
@lewispb sorry for the delay reviewing this, looks like it needs to be rebased again.

**Review by guilleiguaran — APPROVED** [review]

**Comment by rafaelfranca** [comment]
Merged in https://github.com/rails/rails/commit/fdc5ec228e8f4b776a3143a83fee8959b5cc547e

**Pull request closed without merging**
