### PR TITLE
Add total_record_limit option for find_in_batches

### PR DESCRIPTION
**Pull request by softwaregravy**
Discussion from: https://github.com/rails/rails/issues/5502

This change will actually make it possible to divide up your record space across workers.

### CODE REVIEW

**Comment by jmehnle** [comment]
@tmikoss, this approach was exactly the idea I had when I just ran into this use case. Would you still be up for posting a pull request?

**Comment by skatenerd** [comment]
FWIW I just got burned by changing:

```
MyModel.some_scope.limit(VERY_LARGE).each do |x| ... end
```
to
```
MyModel.some_scope.limit(VERY_LARGE).find_each do |x| ... end
```

It's a little scary that composing these ideas works _most of the time_, but can occasionally burn you and result in some instructions being completely ignored, without warning.

**Comment by mahemoff** [comment]
I don't think limit is an edge case for `find_in_batches`. I've had various needs for it when using Rails. One important use case for limits is dev/debug/testing, ie to quickly start some background jobs and check if they run okay, but without blasting through the entire table.

**Comment by AntonTkachov** [comment]
@mahemoff I've also faced a situation when I need max_record option to be passed to find_in_batches. I would describe my case as a limitation logic (like 10000 messages history in slack for free account, it's loaded in batches of 100. I know that in case of slack I would use offset and limit, but it's still a good sample IMO). So I am sure max_records should be definitely supported

**Comment by pcerioli-gpsw** [comment]
I am also on the same boat. I need to process a million of AR objects, each with a slow process. Anyway, since nobody has mentioned it, one possible workaround is to 'break' from the loop when you reach your 'limit'. Assuming that your limit = 1000. Not elegant, but it will work ok.
```
  batch_size = 100
  max_batches = limit / batch_size 

  Post.all.find_in_batches(batch_size: batch_size) do |batch|
    count +=1
    batch.each do |b|
      #do something with 'b'
    end
    break if max_batches == count
  end 
```

**Comment by pcerioli-gpsw** [comment]
A possible workaround to make that happens:
```
    batchsize = 25
    limit = 100000
    batchsize = limit if batchsize > limit
   
    batch_count = 0
    max_batches = (limit / batchsize.to_f).ceil

    Post.all.find_in_batches(batch_size: batchsize) do |batch|
      batch_count +=1
      batch.each do |post|
        # do something with 'post'
      end

      break if max_batches == batch_count   
    end
```

**Pull request closed without merging**
