### PR TITLE
Fixes tests in master

### PR DESCRIPTION
**Pull request by pftg**
Restores environments before testing their settings

### CODE REVIEW

**Comment by pftg** [comment]
@rafaelfranca please check

**Comment by rafaelfranca** [comment]
This change makes no sense to me. No config is being changed, so why do we need to restore?

**Comment by pftg** [comment]
by default, there is no `config/environments' in the `app_path`, but in order to verify https://github.com/rails/rails/commit/73079940111e8b85bf87953e5ef9fafeece5b5da#diff-0a1a3158ff1c2956f5e096a250c11a66R1586 we need to load `config/environments/production.rb`, that's why I assume better to restore `config/environments` from `config/__environments__`.

There are similar tests with this trick

**Comment by rafaelfranca** [comment]
Oh, yeah, just saw that. Thanks.

**Pull request merged**
