### PR TITLE
Allow ActiveStorage::Attachment creation with no record attachments

### LINKED ISSUE #51882: `ActiveStorage::Attachment` - Unhandled case where `named_variants` can be `nil`
In `ActiveStorage::Attachment`, the private method [named_variants](https://github.com/rails/rails/blob/main/activestorage/app/models/active_storage/attachment.rb#L158-L160) can return `nil`, but [callers](https://github.com/rails/rails/blob/main/activestorage/app/models/active_storage/attachment.rb#L135) of this method do not guard against a `nil` value being returned.
 https://github.com/rails/rails/blob/bd04126e79f1b7224a2b2822c7512b194bf3ba03/activestorage/app/models/active_storage/attachment.rb#L158-L160

https://github.com/rails/rails/blob/bd04126e79f1b7224a2b2822c7512b194bf3ba03/activestorage/app/models/active_storage/attachment.rb#L135

### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  gem "rails"
  gem "sqlite3", "~> 1.4"
  gem "debug"
end

require "active_record/railtie"
require "active_storage/engine"
require "tmpdir"

class TestApp < Rails::Application
  config.load_defaults Rails::VERSION::STRING.to_f

  config.root = __dir__
  config.hosts << "example.org"
  config.eager_load = false
  config.session_store :cookie_store, key: "cookie_store_key"
  config.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  config.active_storage.service = :local
  config.active_storage.service_configurations = {
    local: {
      root: Dir.tmpdir,
      service: "Disk",
    },
  }
end

ENV["DATABASE_URL"] = "sqlite3::memory:"

Rails.application.initialize!

require ActiveStorage::Engine.root.join("db/migrate/20170806125915_create_active_storage_tables.rb").to_s

ActiveRecord::Schema.define do
  CreateActiveStorageTables.new.change

  create_table :uploads, force: true do |t|
    t.bigint "blob_id", null: false
    t.index ["blob_id"], name: "index_uploads_on_blob_id"
  end
end

class Upload < ActiveRecord::Base
  belongs_to :blob, class_name: "ActiveStorage::Blob"
end

require "minitest/autorun"

class BugTest < Minitest::Test
  def test_no_named_variants
    blob = ActiveStorage::Blob.create(checksum: 0, byte_size: 0, filename: "example", content_type: "image/png")
    record = Upload.create(blob_id: blob.id)
    attachment = ActiveStorage::Attachment.create(blob:, record:, name: "attachment_example")

    assert_equal true, true
  end
end

```

### Expected behavior
No exception should get raised if there are no named variants.

### Actual behavior
`eval error: undefined method 'each' for nil`

### System configuration
**Rails version**:
`Rails 7.1.3.3`

**Ruby version**:
`ruby 3.3.1 (2024-04-23 revision c56cd86388) [arm64-darwin23]`

### PR DESCRIPTION
**Pull request by justinko**
FIxes #51882

Allow the creation of `ActiveStorage::Attachment` records without the `record` having any attachment associations. 

This is such an unlikely scenario that I don't think a test case is warranted. 

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
If there is an issue, and we need to fix, so we need a test. The issue existing and we wanting to fix is proof enough that it isn't a unlikely scenario.

If there isn't any valid use case where that method will return `nil`, we should just close that issue

**Comment by justinko** [comment]
I think the biggest reason for this change, which I discovered when writing the test, is `ActiveStorage::Attachment#variant`, `ActiveStorage::Attachment#preview`,  and `ActiveStorage::Attachment#representation` will raise `undefined method 'fetch' for nil` rather than the [intended error message](https://github.com/rails/rails/blob/80a6291d7f1b9266ea7b393d5a90e00b9b6a56b1/activestorage/app/models/active_storage/attachment.rb#L168).

**Comment by zzak** [comment]
Please remember to [squash your commits](https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#squashing-commits) and rebase next time :bow:

**Comment by alecslupu** [comment]
Is there any chance this could be backported to rails 7.1 ?

**Pull request merged**
