### PR TITLE
No blade on jruby

### PR DESCRIPTION
**Pull request by headius**
### Summary

The `blade` library has a transitive dependency on `curses` which is not installable on JRuby. This patch masks it out.

### CODE REVIEW

**Comment by maclover7** [comment]
Looks like some changes to Active Support got rolled up in here 😬

**Comment by headius** [comment]
Yeah, sorry about that. Too many PRs in flight.

**Comment by headius** [comment]
BTW, I wasn't sure whether to PR against 5-0-stable or master. If it's easier for your process I can go against master.

**Comment by maclover7** [comment]
Will need to be forward-ported to master

**Comment by maclover7** [comment]
Was just about to say, is easier if PRs are submitted to master (5.1) than 5-0-stable (5.0)

**Comment by headius** [comment]
Ok, I'll do that going forward.

**Pull request merged**
