### PR TITLE
Fix usage of word alternatively in docs [ci skip]

### PR DESCRIPTION
**Pull request by abhishekjain16**
Alternately means switching between two alternatives, alternatively means doing something different.

### CODE REVIEW

**Comment by kaspth** [comment]
Looked in the dictionary and found this under `alternate`s adjective definition:

> 2 chiefly N. Amer. taking the place of; alternative: the rerouted traffic takes a variety of alternate routes.

It seems to me the adverb form fits just fine :smile:

**Comment by abhishekjain16** [comment]
Please refer this
http://grammarist.com/usage/alternate-alternative/

An alternate is something or someone that serves in place of another. An alternative is a second option that does not replace the first. For example, when a road undergoing maintenance is closed to traffic, you have to take an 'alternate' route. But when an under-construction road is still accessible to traffic, you might choose to take an 'alternative' route to avoid congestion. The first option is still there, and the alternative gives you a choice.

Seems the doc changes shows alternative instead of alternate :)

**Comment by kaspth** [comment]
Ah, nice! In the future feel free to submit such info when you submit the pull request :smile:

**Comment by abhishekjain16** [comment]
:+1: Sure. I will keep in mind.

**Pull request merged**
