### PR TITLE
Add case_sensitive option for confirmation validation

### PR DESCRIPTION
**Pull request by akshat-sharma**
```
Case :- 1. In case of email confirmation one needs case insensitive comparison
        2. In case of password confirmation one needs case sensitive comparison
```

### CODE REVIEW

**Comment by pramod-sharma** [comment]
@rafaelfranca  Any Update on this?

**Comment by rafaelfranca** [comment]
Could you please squash your commits? r? @rafaelfranca

**Comment by akshat-sharma** [comment]
@rafaelfranca Please review. Commits have been squashed

**Comment by rafaelfranca** [comment]
Sorry, forgot to ask about the CHANGELOG. Could you add it?

**Comment by akshat-sharma** [comment]
@rafaelfranca Please review, updated changelog

**Comment by cmhokej** [comment]
Ok

**Comment by pwnall** [comment]
Shouldn't there have been an extra test for this?

**Comment by pramod-sharma** [comment]
Thanks for this

**Pull request merged**
