### PR TITLE
Provide support for SQL Server connections with dbconsole using sqsh

### PR DESCRIPTION
**Pull request by jipumarino**

### CODE REVIEW

**Comment by BenKanouse** [comment]
@rafaelfranca @jipumarino This seems to work for me for Rails 4.0. Could this be back ported to 4.0 and 4.1?

Thanks!

**Comment by rafaelfranca** [comment]
No. Both 4.0 and 4.1 are not supported anymore.

**Comment by BenKanouse** [comment]
@rafaelfranca Thanks for the info and quick response! That was extremely helpful to know.

**Comment by Abinash04** [comment]
Is there a way to use rails dbconsole for MS SQL server as **sqsh** cant be installed as the formula is no longer available in MacOS.
Below is the error when we run: rails dbconsole
Couldn't find database client: sqsh. Check your $PATH and try again.

**Comment by nertzy** [comment]
We have been experimenting with aliasing `sqsh` to `sqlcmd` to see if that can work. We haven't gotten it working yet, though.

It would be great if someone refactored the code for `rails dbconsole` to make it easier for adapter gems to add support for different shells.

**Comment by nertzy** [comment]
I opened https://github.com/rails/rails/issues/40611 to suggest that Rails moves from `sqsh` to `sqlcmd`, which Microsoft offers on Windows, Mac, and Linux.

**Comment by tahsin352** [comment]
I created this PR https://github.com/rails/rails/pull/40612 for it.

**Pull request merged**
