### PR TITLE
Backport #45722 to 7-0-stable

### PR DESCRIPTION
**Pull request by ghiculescu**
Backports to https://github.com/rails/rails/pull/45722 to `7-0-stable`

### CODE REVIEW

**Comment by byroot** [comment]
The error seem legit but unrelated to your change. 

```
Failure:
CalculationsTest#test_should_return_float_average_if_db_returns_such [/rails/activerecord/test/cases/calculations_test.rb:77]:
Expected: Infinity
  Actual: nil
 
rails test rails/activerecord/test/cases/calculations_test.rb:66
```

**Comment by byroot** [comment]
It's specific to sqlite3 and sqlite3 had a release 3 days ago, might be why.

**Comment by yahonda** [comment]
Would you rebase be the 7-0-stable branch that includes https://github.com/rails/rails/commit/56e78ab6a8f1b2d6290217c9430b166ea06daaec ? 

`guides` failures are known, so IMO these failures can be ignored. It only reproduces against the 7-0-stable.

**Comment by yahonda** [comment]
Nevermind.

**Comment by ghiculescu** [comment]
> The error seem legit but unrelated to your change.
> 
> ```
> Failure:
> CalculationsTest#test_should_return_float_average_if_db_returns_such [/rails/activerecord/test/cases/calculations_test.rb:77]:
> Expected: Infinity
>   Actual: nil
>  
> rails test rails/activerecord/test/cases/calculations_test.rb:66
> ```

https://github.com/sparklemotion/sqlite3-ruby/issues/396

**Pull request merged**
