### PR TITLE
Allow Capybara 3.x

### PR DESCRIPTION
**Pull request by twalpole**
### Summary

Capybara 3.0.0.rc1 has been released, and contains no changes that affect how Rails system tests integrate with it. 

This PR allows Rails users to use Capybara 3.x.  Would be great to have it backported to Rails 5.1 and 5.2 too

### CODE REVIEW

**Comment by jeremy** [comment]
https://github.com/teamcapybara/capybara/blob/master/History.md#version-300rc1 for reference

**Comment by rafaelfranca** [comment]
We also need to update the Gemfiles.

**Comment by twalpole** [comment]
@rafaelfranca Technically the Gemfiles dont need to be updated - It's only this file that would prevent a user from changing the restriction in their projects Gemfile to allow Capybara 3.x.

**Comment by jeremy** [comment]
If we upgrade the version of Capybara we allow, then we test against it also. Technically :)

**Comment by twalpole** [comment]
@jeremy Then wouldn't it be required to test against multiple versions?  The rails test suite doesn't appear to be set up to do that.

**Comment by rafaelfranca** [comment]
No. We will only test with the latest released version version. We also need to update the generated Gemfile otherwise new apps will not allow Capybara 3.0 by default.

**Comment by twalpole** [comment]
@jeremy Will you backport these changes to 5.1_stable and 5.2_stable or do I need to file separate PRs against those branches?

**Comment by jeremy** [comment]
Backported to 5-2-stable @ db5a15901a411a2d23d312718d8f5c7e58a8e039 since it's still a release candidate. (Stable branches only get [bugfixes and security patches](http://guides.rubyonrails.org/maintenance_policy.html), otherwise.)

**Comment by twalpole** [comment]
@jeremy I understand the policy with regards to 5.1 stable - however I think it may need to be reconsidered for Capybara.  The benefit of system testing is to ensure compatibility with browsers, and with most browsers now auto-updating that means compatibility with the latest version of browsers. This means this will be the first gem rails depends on that loses functionality over time because a rails 5.1 app developer won't be able to upgrade Capybara (without upgrading rails) and will lose the ability to test with the latest versions of browsers. 

IMHO this would have been much better if the  line in ctionpack/lib/action_dispatch/system_test_case.rb was just

    gem "capybara"

and the version restriction was enforced through the Gemfiles since then an end user could at least override it if necessary, however that was shot down previously.

**Comment by vipulnsward** [comment]
Facing this issue right now. I have an App recently migrated to 5.1.  Upgrading to 5.2 is big task due to many changes involved.

Not being able to have 3.x capybara, holds back on using headless chrome, etc in a proper way without having to have workarounds.

**Comment by twalpole** [comment]
@vipulnsward This was added to 5.1 in April -https://github.com/rails/rails/commit/b1b0a334b8fe3a3fb363d6a4b8a35272231fc4f3 - but there hasn't been a 5.1.x release that includes it yet -- You can use Rails from the 5-1-stable branch if you need the fix today.

**Comment by ericboehs** [comment]
It would be nice if we had semi-annual releases of supported Rails versions.

**Pull request merged**
