### PR TITLE
Fix year in 4.2.1 CHANGELOG files

### PR DESCRIPTION
**Pull request by olivierlacan**
Noticed via http://weblog.rubyonrails.org/2015/3/19/Rails-4-2-1-and-4-1-10-have-been-released/#comment-1920298034

I'm the change log nerd over here so I thought I'd give it a try. :stuck_out_tongue:

### CODE REVIEW

**Comment by rafaelfranca** [comment]
I already did at 4-2-stable branch, but I can't change the tag

**Comment by olivierlacan** [comment]
Whoops. Never mind. This PR is a catastrophe. My bad.

**Comment by olivierlacan** [comment]
@rafaelfranca No way to `git tag -d v4.2.1` and then make a new one?

**Comment by rafaelfranca** [comment]
recreating a already released tag is no a good idea

**Pull request closed without merging**
