### PR TITLE
Add custom RuboCop for `assert_not` over `refute`

### PR DESCRIPTION
**Pull request by composerinteralia**
Since at least cf4afc4 we have preferred `assert_not` methods over `refute`
methods in our tests. I have seen plenty of comments in PRs about this, and we have
tried to fix it a few times (5294ad8, e45f176, 8910f12, 41f50be,
d4cfd54, 48a183e, and 211adb4), but the `refute` methods keep sneaking back in.

This custom RuboCop will take care of enforcing this preference, so we
don't have to think about it again. I suspect there are other similar
stylistic preferences that could be solved with some custom RuboCops, so
I will definitely keep my eyes open. `assert_not` over `assert !` might
be a good candidate, for example.

I wasn't totally sure if `ci/custom_cops` was the best place to put
this, but nothing else seemed quite right. At one point I had it set up
as a gem, but I think custom cops like this would have limited value
in another context.

~~I want to see how code climate handles the new cops before
autocorrecting the existing violations. If things go as expected, I will
push another commit with those corrections.~~
Failed the build as expected. `rubocop -a` fixed all the new violations, so hopefully code climate is happy this time.

### CODE REVIEW

**Comment by sikachu** [comment]
>we have preferred refute methods over assert_not
methods in our tests.

Did you actually meant to write "we have preferred *assert_not* over *refute*"?

**Comment by composerinteralia** [comment]
Yes! ACK!

**Comment by matthewd** [comment]
cc @toshimaru

**Comment by koic** [comment]
I think this cop has a useful opportunity in Rails applications. Therefore I will export this cop and open PR to RuboCop. It will also reduce dependency from Rails.

**Pull request merged**
