### PR TITLE
Backport #29233 + Silence the warning `method redefined; discarding o…

### PR DESCRIPTION
**Pull request by meetme2meat**
Backport https://github.com/rails/rails/pull/29233  for the following issue https://github.com/rails/rails/issues/32422.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
How it fix #32422 if it is not being used in the default_scope_attribute= method?

**Comment by meetme2meat** [comment]
@rafaelfranca I understand that but is there any other way we can get around this. We are dealing with a production issue which is resolved in 5-0-stable (this one https://github.com/rails/rails/pull/14938). Trying to upgrade to 5-1-stable result in https://github.com/rails/rails/issues/32422.

At the current time, we can just update to 5-1-stable until the driver(JDBC) support for 5-2-stable is ready.

**Comment by eugeneius** [comment]
Could we backport just the changes to `class/attribute.rb`? The rest are unrelated to https://github.com/rails/rails/issues/32422.

**Comment by meetme2meat** [comment]
@eugeneius If the question for me. I think that would do as well.

**Comment by eugeneius** [comment]
My suggestion was in response to @rafaelfranca's comment:

> Unfortunately this backport is too big for a [stable] version

A smaller patch is more likely (but still not guaranteed) to be acceptable to backport to 5-1-stable.

**Comment by meetme2meat** [comment]
@matthewd Any thought?

**Comment by oniofchaos** [comment]
👍 if this still needs to be backported into 5.1

**Comment by bonghab** [comment]
slides-symbol-flat-600x600-737b93a8e63602872bbb8041832d8faccfb828cdeee282fd79646fa76cce1a14
Z

**Comment by bonghab** [comment]
[6668a1f6986742109c00a581ce704605-f6c882b6ae18bde42dcf6fdb751aae93495a2275.zip](https://github.com/rails/rails/files/2636741/6668a1f6986742109c00a581ce704605-f6c882b6ae18bde42dcf6fdb751aae93495a2275.zip)

**Comment by bonghab** [comment]
[LRPN_136-Final-For-Web.pdf](https://github.com/rails/rails/files/2636743/LRPN_136-Final-For-Web.pdf)o

**Comment by bonghab** [comment]
__zp

**Comment by eugeneius** [comment]
[5.1.7 was the final release in the 5.1 series](https://weblog.rubyonrails.org/2019/3/22/Rails-5-1-7-rc1-has-been-released/), so even if this was merged it would never be published. I'm going to close this since there's nothing more we can do here.

**Pull request closed without merging**
