### PR TITLE
Display a more helpful error message when an ERB template has a Ruby syntax error.

### LINKED ISSUE #34995: Calling methods in .erb files can cause a confusing error when a parenthesis is missing
This issue is about the error message that you see when you write an html.erb template with a helper call that is missing a parenthesis, something like this:

```
<%= render(
  'test_partial',
   locals: {
    foo: 1,
    bar: 2,
   },
%>
```

Here the `render` call is missing a parenthesis. This is a real bug that afflicted me during development, leading to much confusion. I thought others might have encountered this before.

### Steps to reproduce
I've created a minimal example here (https://github.com/erose/rails-render-partial-gives-confusing-error-when-parenthesis-is-missing).

1. Clone the repository.
2. Run `rails s`.
3. Visit `localhost:3000/`. You should see the error screen.

### Expected behavior
Because the error is in code that I wrote, I'd expect to see an error message referring to the line that is missing a parenthesis, perhaps telling me where it expected to find the parenthesis.

### Actual behavior
Instead, I see the following error screen:

image

While now that I know what the issue is, I can see why this screen would have been generated, at the time it was very confusing because 1) it refers to line 10 of `index.html.erb`, but that file only has 7 lines, and 2) it refers to `ensure`, but that's nowhere in the code I wrote.

### System configuration
**Rails version**:
Rails 5.2.2

**Ruby version**:
Ruby 2.5.1

I'm happy to work on a fix for this issue -- first I'd like to understand which project it should belong in. At first blush it seems like this might be in the domain of [erubi](https://github.com/jeremyevans/erubi), Rails's ERB engine, but that project doesn't appear to do any kind of error handling so I had a feeling it would be considered out of scope there. (I thought I might get more attention with this issue by asking it here, rather than there.)

Any guidance would be appreciated!

### PR DESCRIPTION
**Pull request by erose**
### Summary

Currently, if code that is intended to be interpolated into a template has a syntax error (e.g. `<%= foo( %>`), Rails displays (what I find to be) a confusing error message. The error message refers to a syntax error in code the user hasn't written, and references an unrelated line of the template.

This PR is an attempt to resolve this issue.

Resolves https://github.com/rails/rails/issues/34995. (My own issue.)

### Other Information

This is my first time contributing to Rails, so I would certainly appreciate critiques of my coding style and/or my overall approach.

I wasn't able to achieve my ideal user experience; that would be displaying the offending line in context in the "extracted source" box, rather than displaying a blank box, as occurs both before and after my change.

I couldn't see a way to accomplish this without refactors (because `ActionDispatch::ExceptionWrapper#source_extracts` relies on parsing the backtrace in order to display the correct context, and our backtrace is polluted with generated code), and felt I would probably make significant errors in refactoring a codebase I was totally new to. But if there is a way to accomplish it, I would love to know.

In the end I decided to go with this approach as it seemed like an improvement on the status quo; it might give the user more hints as to what is happening.

Below I've attached screenshots of the user experience in the case where the user has made a Ruby syntax error in an ERB template and visits the page in development mode.

#### Before:
image

#### After:
image

### CODE REVIEW

**Comment by erose** [comment]
Anything else I can do to help with this?

Tagging @sikachu as you commented on the original issue I filed.

**Review by sikachu — APPROVED** [review]
I think the code looks good. Thanks!

**Comment by erose** [comment]
Thanks for the review, @sikachu !

**Comment by matthewd** [comment]
I like the idea of improving this error, but does dumping the entire view source into the message really achieve that? It looks nice for a one-line-view example, but for a more realistic-size view it seems like it's going to be at least as much of an imposing mess as the old one.

**Comment by sikachu** [comment]
@matthewd so you mean .. we could just show

```
Encountered a syntax error while rendering template around line 10

[ source code block ]
```

and that would be enough?

**Comment by erose** [comment]
@matthewd Thanks for the feedback! I agree this might be an issue, although I'm not yet convinced that in that situation the error message after this change would be worse than the error message was before this change.

What would be a good example case to try this on? Perhaps some multi-line call like:

```
<%= render('test_partial', locals: {
  foo: 1,
  bar: [
    :a, :b, :c
  ],
%>
```

?

**Comment by matthewd** [comment]
Ideally, the source code block would contain the view source around the line of interest (does it currently? the screenshot looks like it's empty), but otherwise yeah.

(Though in the reported case, where a paren has been left open, the line of actual interest is the one where that happened, but the line Ruby will consider interesting is the outside-of-template `end`. Nothing we can do about that, and it's no different to an equivalent error in any other source file.)

@erose I'm thinking of an error of that form, inserted into the middle of a view file that looks more like https://github.com/discourse/discourse/blob/master/app/views/layouts/application.html.erb.

**Comment by erose** [comment]
You're right -- with my change, this file:

```
<!DOCTYPE html>
<html lang="<%= html_lang %>" class="<%= html_classes %>">
  <head>
    <meta charset="utf-8">
    <title><%= content_for?(:title) ? yield(:title) : SiteSetting.title %></title>
    <meta name="description" content="<%= @description_meta || SiteSetting.site_description %>">
    <meta name="discourse_theme_ids" content="<%= theme_ids&.join(",") %>">
    <meta name="discourse_current_homepage" content="<%= current_homepage %>">
  </head>

  <body>
    <%= render(
      'test_partial',
       locals: {
        foo: 1,
        bar: 2,
       },
    %>
  </body>
</html>
```

yields an error screen like this

image

which I think is worse than the situation beforehand.

In that light, I'd like to revert this change. How can that be achieved?

**Comment by erose** [comment]
Thank you so much for pointing this out!

**Comment by matthewd** [comment]
I'd be keen to roll forward, rather than back, if you're interested: to me the substance of your change is "maybe we should actually consider how this error looks", which I'm 10/10 on board for.

Is `source_fragment` breaking because of more complex issues with the backtrace, or is it just empty because it's trying to show lines 8-12 of a 7 line file?

**Comment by erose** [comment]
I took another look at this today -- it seems to me this issue has been addressed since I was last here. Thanks to whomever did this work!

**Pull request merged**
