### PR TITLE
Type::Decimal casting raises exceptions on ruby 2.4.0-rc1

### PR DESCRIPTION
**Pull request by jhawthorn**
### Summary

Our `active_model` numeric types accept "slightly invalid" strings like `"1ignore"` (cast to `1`) and `"bad"` (cast to `0`). This is desirable. Users input these values, and they shouldn't result in error pages.

Under ruby `2.4.0-rc1`, entering `"bad"` into a decimal attribute will raise `ArgumentError: invalid value for BigDecimal():`.

In Ruby 2.4, `BigDecimal()`, as used by the Decimal cast, was changed so that it will raise `ArgumentError` when passed an invalid string, in order to be more consistent with `Integer()`, `Float()`, etc. The other numeric types use ex. `to_i` and `to_f`.

Unfortunately, we can't simply change `BigDecimal()` to `to_d`. `String#to_d` raises errors like `BigDecimal()`, unlike all the other `to_*` methods ([I have filed this as a bug in ruby](https://bugs.ruby-lang.org/issues/13062)).

In the first commit of this PR, I've added tests to test the casting of these "invalid" strings to `Type::Integer`, `Type::Float`, and `Type::Decimal`. All of these tests pass on ruby 2.3.3 and before. On ruby 2.4.0-rc1, the new `Type::Decimal` test fails. [You can see this in a Travis run of just the first commit on ruby 2.4.0-rc1](https://travis-ci.org/rails/rails/jobs/185947970).

In the second commit I've reproduced the existing behaviour and the behaviour of the other `to_*` methods by finding a numeric string at the start of the passed in value, and parsing that using `BigDecimal()`. This might be too slow, it's certainly not the nicest solution, but I wanted to get something to show the desired behaviour.

### Other Information

``` ruby
# ruby 2.3.3 or ruby 2.4.0preview3
> BigDecimal.new('')
=> #<BigDecimal:5642adf04ec0,'0.0',9(9)>
> ''.to_d
=> #<BigDecimal:5642adda7640,'0.0',9(9)>
```

``` ruby
# ruby 2.4.0-rc1
> BigDecimal.new('')
ArgumentError: invalid value for BigDecimal(): ""
> ''.to_d
ArgumentError: invalid value for BigDecimal(): ""
```

On [Solidus](https://github.com/solidusio/solidus), where I discovered this:

``` ruby
# ruby 2.3.3 or ruby 2.4.0preview3
> Spree::Variant.new(weight: 'heavy')
=> #<Spree::Variant:0x00562c17fb5060 id: nil, ..., weight: BigDecimal(0.0), ...>
```
``` ruby
# ruby 2.4.0-rc1
> Spree::Variant.new(weight: 'heavy')
ArgumentError: invalid value for BigDecimal(): ""
```

## See also

https://bugs.ruby-lang.org/issues/10286
https://bugs.ruby-lang.org/issues/13062
https://github.com/ruby/bigdecimal/commit/3081a627cebdc1fc119425c7a9f009dbb6bec8e8

EDIT: I originally filed this with the incorrect assumption that `BigDecimal("1ignore")` would fail in the same way that `Integer("1ignore")` does, but `BigDecimal` does not error in that case.

### CODE REVIEW

**Comment by matthewrudy** [comment]
I hit this on Ruby 2.4.0 too.

Just from a simple `decimal` column

```
# set it to a string
>> model.decimal_column = 'abc'

# ruby 2.3.3
=> 0.0

# ruby 2.4.0
ArgumentError: invalid value for BigDecimal(): "abc"
```

**Comment by sgrif** [comment]
First off, this is probably a bug in Ruby, not Rails. `SomeClass.new` or `value.to_sc` are usually meant to be weak. The fact that the error message mentions the strict method name makes me think this was an unintentional change, or at least one that should have emitted a warning. I'd like to hold off on any changes in Rails until after an issue is opened and discussed on Ruby itself.

The rest of this comment assumes a future situation where an issue has been opened on MRI and the Ruby core team decided that they wanted to continue with this breaking change and not fix it in 2.4.1.

Your statement:

> and "bad" (cast to 0). This is desirable.

misses the point. The reason that occurs is because we try to follow Ruby's semantics (and `Integer` specifically was that way due to some historical problems involving bad things happening when `WHERE id = NULL` was given to older MySQL versions).

For error cases we typically return `nil`. I'd like to continue to do that here. I'd prefer that the implementation looked like `value.to_d rescue nil`. I'd prefer to match Ruby's semantics over trying to be consistent across Ruby versions.

**Comment by sgrif** [comment]
Ah, I see you have already opened an issue to Ruby.

**Comment by sgrif** [comment]
After reading through https://bugs.ruby-lang.org/issues/10286 and https://bugs.ruby-lang.org/issues/13062, I'm convinced that this is definitely a bug in Ruby itself, not Rails. I'm fine with throwing on the `rescue nil` as a short term fix regardless of the Ruby issue's status.

**Comment by jhawthorn** [comment]
@sgrif Thanks for your reply.

It looks to me like the change to `BigDecimal(str)` is intentional. It seems like a reasonable change (ignoring collateral damage). Assuming it is intentional, this is a bug in rails, since rails currently uses `BigDecimal(str)`.

We are in agreement that `to_d` changing as well is a bug in ruby, and I don't think this was intentional. This is not a rails bug itself, but it does make writing a clean patch to the former bug difficult, hence this PR's implementation.

> Your statement:
> 
> and "bad" (cast to 0). This is desirable.
> misses the point. The reason that occurs is because we try to follow Ruby's semantics [...]

If you read the next sentence I am referring to not raising errors. I am indifferent to what value is set when it is fed garbage, but it cannot error.

That said...

> For error cases we typically return `nil`. I'd like to continue to do that here. I'd prefer that the implementation looked like `value.to_d rescue nil`. I'd prefer to match Ruby's semantics over trying to be consistent across Ruby versions.

If we're looking to match ruby's semantics, should we not return `BigDecimal(0)`? If we're looking to use a `rescue` as a short term fix until ruby fixes the `to_d` implementation, we are effectively emulating the "fixed" behaviour we expect ruby to have. I have to imagine that the eventual behaviour for `String#to_d` will be to return `BigDecimal(0)` to match both the existing behaviour and the behaviour of all other `to_*` Numeric methods.

I have changed the implementation to `value.to_d rescue BigDecimal(0)`. I really do think `0` is the right value to use. Please let me know if I am wrong and I can replace it with `nil`.

**Comment by matthewrudy** [comment]
In my project I added a shim return `0.0.to_d` as the rescue

Works for me, and preserves behaviour between 2.3.3 and 2.4.0

```
# config/initializers/_ruby.2.4.0.rb
require 'active_model/type/decimal'

module DecimalCastRescueRuby24
  def cast_value(value)
    if value.is_a?(::String)
      begin
        super(value)
      rescue ArgumentError
        0.0.to_d # preserve ruby 2.3.3 behaviour
      end
    else
      super(value)
    end
  end
end

ActiveModel::Type::Decimal.prepend DecimalCastRescueRuby24
```

**Comment by sgrif** [comment]
Ah you are right I thought we were calling `.to_d`. If I recall the reason that we're using `BigDecimal()` form is that some types accept an argument to `.to_d` but not others. I'm pretty sure `String` took an argument. If not `BigDecimal.new` is fine as well, but we need to continue passing the precision. `rescue nil` is the right thing to do here, whether we actually *hit* that rescue is up to Ruby.

**Comment by jhawthorn** [comment]
@sgrif sorry for the delay. The last commit I pushed returns nil. There's a conflict now which I can easily merge or rebase away, but I thought it best to hold of for ease of review.

`String#to_d` does not take a precision argument. Only `Float#to_d` and `Rational#to_d` do.

I'm not sure whether we need to specify a precision when converting a string.

Both `BigDecimal()` and `#to_d` will use enough precision to represent all digits of the string provided. Specifying a smaller precision than the digits in the string has no effect. Specifying a larger precision increases the second precision value "maximum number of significant digits" (I don't know whether or not this is important).

Some quick examples for illustration:

``` ruby
BigDecimal.new('1').precs #=> [9, 18]
BigDecimal.new('1', 1).precs #=> [9, 18]
BigDecimal.new('1', 100).precs #=> [9, 108]
BigDecimal.new('1', 10000).precs #=> [9, 10008]

BigDecimal.new('1'*10, 1).precs #=> [18, 27]
BigDecimal.new('1'*10, 100).precs #=> [18, 108]
BigDecimal.new('1'*1000, 100).precs #=> [1008, 1017]
```

The second value from `precs` is the ["maximum number of significant digits"](https://ruby-doc.org/stdlib-1.9.3/libdoc/bigdecimal/rdoc/BigDecimal.html#method-i-precs), but afaict BigDecimal are immutable, so I'm not sure there's a purpose of this.

So I don't think specifying a precision for strings is necessary. Does that seem okay?

**Comment by sgrif** [comment]
Going to pass this off since I'm on parental leave for the next few months.

r? @matthewd 

Can you handle this or assign to someone else?

**Comment by rafaelfranca** [comment]
Merged in bf8f42b2fe, backported in 696f176614

**Comment by matthewrudy** [comment]
That's great, thanks @rafaelfranca.

I'll remove my shim when we hit 5.1.0

**Comment by abezzub-upstart** [comment]
Is there any chance this fix makes it into Rails 4.2? I still get this issue with ruby 2.4.1 and Rails 4.2.8

**Comment by sevenseacat** [comment]
Only Rails 5.0.x gets bugfixes now. See: http://rubyonrails.org/maintenance/

**Comment by abezzub-upstart** [comment]
I see, thanks.

**Comment by pixeltrix** [comment]
@abezzub-upstart there's a version 1.3.2 of the bigdecimal gem that fixes the problem with `"".to_d` - that may help you with Ruby 2.4.1 and Rails 4.2.8.

**Comment by feist** [comment]
This fix causes in issue if the user types in "1." (a number following by a decimal). Instead of getting "1" like the user would expect, they get 0.

**Pull request closed without merging**
