### PR TITLE
AS::Dependencies do not record required paths

### PR DESCRIPTION
**Pull request by casperisfine**
While doing some memory profiling, I noticed that `ActiveSupport:::Dependencies` was holding onto a lot of unique strings.

It makes sense for `AS::Dependencies` to keep a list of loaded files as to avoid double loading them, as well as to know what to unload.

However once `mechanism = :require`, Ruby's `$LOADED_FEATURES` will provide the same safety.

In theory having a second reference on these strings wouldn't be too bad, the problem is that `AS::D` keep them extension free (`/foo/bar` for `/foo/bar.rb`)
 whereas `$LOADED_FEATURES` keeps the realpath `/foo/bar.rb`. As a result we keep lots of useless strings in memory.

cc @fxn (I know you are more into Zeitwerk, but this seems tangential)

cc @rafaelfranca @Edouard-chin @csfrancis

### CODE REVIEW

**Comment by fxn** [comment]
`EBACKLOGOVERFLOW` 😄, let me /cc @matthewd in case he can have a look.

**Review by rafaelfranca — APPROVED** [review]

**Comment by fxn** [comment]
Let me throw in just in case that when eager loading we autoload too. I am not sure the refactor is equivalent, but had only a superficial read of the code, maybe it is in practice.

**Comment by casperisfine** [comment]
> Let me throw in just in case that when eager loading we autoload too.

Absolutely. However this isn't really about `eager_loading`, but more about `cache_classes`, e.g. not wether we autoload, but wether we'll reload.

> I am not sure the refactor is equivalent

It's totally equivalent except we skip adding paths to the 3 sets if `mechanism == :require`.

**Comment by fxn** [comment]
While the mechanism strictly depends on `config.cache_classes`, in practice the main use case is that you use `load` when you want to reload, and `require` when you want to eager load. And it is very important to take into account that when applications eager load and the mechanism is `:require`, you still autoload. So, any metadata that is important for autoloading logic must be in place. That was my point.

From a formal point of view, there are a few things that make me think the refactor is not equivalent on paper.

One is that the original code does some housekeeping _regardless_ of the mechanism.

Another one is that the proposed patch keeps this in two places having `:require` as mechanism.

```ruby
return if loaded.include?(expanded)
```

and at the same time it does not maintain `loaded`.

Another one is that if the patches are equivalent, the refactor could probably have at the top

```ruby
return require file_name unless load?
```

I am not saying the patch is not correct, eh? Also not saying my remarks may not have counterarguments. It is only a formal comparison comparing both listings without doing a proper analysis.

It is just that there are a few things that strike me, sharing them so that Matthew and/or Aaron may have them in mind while reviewing.

**Comment by casperisfine** [comment]
> sharing them so that Matthew and/or Aaron may have them in mind while reviewing.

Sure, then I'll answer for the other reviewers.

> So, any metadata that is important for autoloading logic must be in place.

Yes, and these sets are not important for autoloading, when the mechanism is `:require`.

> One is that the original code does some housekeeping regardless of the mechanism.

Yes, that's precisely what I want to change here. I believe it's unnecessary.

> Another one is that if the patches are equivalent, the refactor could probably have at the top
> 
> return require file_name unless load?

Unfortunately no I don't think it can. The reason I left this checks is that since `mechanism` defaults to `:load`, it's fairly possible that some constants were autoloaded using `load` prior to `mechanism` being set to `:require`, hence absolutely need not to be required, otherwise they'll be double loaded.

Quick pseudo code snippet:

```ruby
Pricing.foo = :bar # Triggers a load('app/models/pricing.rb'), and the path is added to `loaded` set.

ActiveSupport::Dependencies.mechanism = :require # probably set by the init process via cache_classes = true

require_dependency 'pricing' # If we don't check `loaded.include?()` and directly defer to require, we'll double load.
```

The alternative would be to merged the `loaded` set into `$LOADED_FEATURES` like I do in https://github.com/rails/rails/pull/35745 so that MRI itself will prevent double loading.

Now I feel I kinda forgot to list a few assumptions, here they are:

  - `loaded` and `history` are for internal use only. I couldn't find any other part of Rails using them. Maybe some gems do? Hence I assume it's fine to no longer populate them once we disable reloading.

  - Setting `mechanism = :require` is final. If somehow I'm wrong and we expect people to switch back to `:load` then double loading can happen.

  - In this implementation I take care of keeping backward compatibility as much as possible. But if we consider that the double loading issues I describe, that are currently prevented, shouldn't be supported we can indeed directly delegate to `require`.

**Comment by fxn** [comment]
Hey, this is an optimization and `classic` mode is entering a frozen status in my mind. I prefer not to touch it. Thanks for the patch anyway Jean, as always. ❤️

**Pull request closed without merging**
