### PR TITLE
add rubymine auto gen dir to git ignore file

### PR DESCRIPTION
**Pull request by hechen0**
### Summary

add RubyMine IDE auto generate dir .idea to .gitignore file

### CODE REVIEW

**Comment by maclover7** [comment]
Hmm, I'm :-1: about this -- what if another editor comes along and asks for their auto generated directory to be ignored? Don't want any editor to get special treatment :fearful:

**Comment by matthewd** [comment]
Yeah, this is more appropriately placed in your machine's global git ignore list.

**Comment by prathamesh-sonpatki** [comment]
@hechen0 Generally we configure such things in global `.gitignore` file.

**Comment by hechen0** [comment]
Cool one lesson to git newbies like me :p

**Pull request closed without merging**
