### PR TITLE
Allow to pass a string value to size option in `image_tag` and `video_tag`

### PR DESCRIPTION
**Pull request by mehlah**
Before, passing `image_tag("foo.png", size: 120)` was silently ignored, because `120` wasn't a `String`.
As we can set a width and height with numerical values: `image_tag("foo.png", width: 120, height: 120)`, this makes it more consistent for `size` option too.

Same thing for `video_tag`.

For reference, the `size` option has been introduced at https://github.com/rails/rails/pull/7754

### CODE REVIEW

**Comment by georgeclaghorn** [comment]
Looks good! How about documenting this usage in the examples for `image_tag` and `video_tag`?

**Comment by senny** [comment]
@mehlah can you add a test-case to prevent regressions and an entry in the CHANGELOG?

**Comment by mehlah** [comment]
@senny I already updated the tests with [2 assertions](https://github.com/rails/rails/pull/18949/files#diff-60bdcf1e1954ec56d41fc4c7bd8d3e39R183) with an integer `size`.
I just added a CHANGELOG entry.

@georgeclaghorn The existing usage examples for `width` or `height` options shows only "string" values. I think it does not worth mentioning this explicitly in the docs only for `size`.

Thanks!

**Comment by senny** [comment]
@mehlah sorry, I mistakenly thought these were documentation changes :sweat:. This is looking good :yellow_heart:

**Comment by yeah** [comment]
This should read "Allow to pass AN INTEGER value [...]", right?

**Comment by senny** [comment]
@yeah you're totally right: https://github.com/rails/rails/commit/0ba10301e5d44b1b16a5045006e133fa62b81fad

**Pull request merged**
