### PR TITLE
Skip ActiveStorage migrations if ActiveStorage tables don't exist

### PR DESCRIPTION
**Pull request by tbuehl**
### Summary

On a legacy Rails app where ActiveStorage hasn't been activated/installed, `rails app:update` still copies ActiveStorage update migrations.

Therefore running `rake db:migrate` afterwards will fail with:

```
== 20200203173757 AddServiceNameToActiveStorageBlobs: migrating ===============
-- column_exists?(:active_storage_blobs, :service_name)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedTable: ERROR:  relation "active_storage_blobs" does not exist
LINE 8:  WHERE a.attrelid = '"active_storage_blobs"'::regclass
                            ^
/Users/tb/app_name/db/migrate/20200203173757_add_service_name_to_active_storage_blobs.active_storage.rb:4:in `up'
```

To fix this, each migration checks if the `active_storage_blobs` table exists. If not, the migration is skipped.

In general I think the migrations shouldn't be copied over in the first place, but that seems harder to fix.

### CODE REVIEW

**Review by gmcgibbon — COMMENTED** [review]
https://github.com/rails/rails/blob/d4a536d8f41d81e1dbcab509ced46803d33f514d/railties/lib/rails/app_updater.rb#L26

The updater should already be skipping Active Storage if you don't have it loaded. Are you including Active Storage in your application via `rails/all`?

**Comment by tbuehl** [comment]
Yes, I include `rails/all`. But I would say that's how most applications are configured.

When a pre Active Storage app gets updated, the install script for Active Storage won't be run, but the update migrations are copied over. This leaves the app in a broken state.

That's why I would say the easiest fix is to only run the migrations if the necessary tables exist.

**Comment by jonathanhefner** [comment]
To clarify: Legacy applications were generated with `require "rails/all"` before Active Storage existed.  Those applications have not opted in to Active Storage (via `rails active_storage:install`), but they now automatically load it (i.e. `ActiveStorage::Engine`) anyway.  So `skip_active_storage` is set to `false`, and `rails app:update` generates update migrations for a tables that do not exist.

Is that correct, @tbuehl?

See #35620 for a similar fix.

**Comment by tbuehl** [comment]
@jonathanhefner Yes, that's on point! 😄

**Comment by rmacklin** [comment]
I just ran into a `Could not find table 'active_storage_blobs'` error from [this ActiveStorage migration](https://github.com/rails/rails/blob/v6.1.3.1/activestorage/db/update_migrate/20190112182829_add_service_name_to_active_storage_blobs.rb#L4) when I ran `bin/setup` after upgrading an app from rails 6 to 6.1. I was going to make a similar PR before I found this one.

It looks like the more general solution that @jonathanhefner proposed in https://github.com/rails/rails/pull/39498#issuecomment-638464893 hasn't landed either, so I'm wondering if there's any desire to revive this PR and land it into `6-1-stable`. That way we could at least provide a solution for this specific issue for those upgrading to 6.1.

If that's not desirable, perhaps we could mention this issue in the [upgrade notes](https://github.com/rails/rails/blob/9a263e9a0ffb82faa6d3153fd1f35b814a366cd5/guides/source/upgrading_ruby_on_rails.md#upgrading-from-rails-60-to-rails-61)? I'd be happy to open a PR for that if we don't want to conditionally skip the migrations. But I'm curious what we should recommend for those affected... maybe the simplest thing is to tell them to delete the ActiveStorage migrations added by the `app:update` task if they do not use ActiveStorage. Does that seem appropriate?

**Comment by ghiculescu** [comment]
> maybe the simplest thing is to tell them to delete the ActiveStorage migrations added by the app:update task if they do not use ActiveStorage. Does that seem appropriate?

That might be simpler and would probably be easier to get merged.

**Comment by ceritium** [comment]
I did the following experiment:

```
rails _6.1.4.1_ new rails6141
cd rails6141
rails db:migrate
git add .
git commit -am "fc"

# Replace rails 6.1.4 with 7.0.0.alpha2

bundle update rails

rails app:update
# Copied migration 20210922074150_add_service_name_to_active_storage_blobs.active_storage.rb from active_storage
# Copied migration 20210922074151_create_active_storage_variant_records.active_storage.rb from active_storage

rails db:migrate

> == 20210922074150 AddServiceNameToActiveStorageBlobs: migrating ===============
> -- column_exists?(:active_storage_blobs, :service_name)
> rails aborted!
> StandardError: An error has occurred, this and all later migrations canceled:
>
> Could not find table 'active_storage_blobs'
> /Users/jose.galisteo/RAILSTEST/rails6141/db/migrate/20210922074150_add_service_name_to_active_storage_blobs.active_storage.rb:4:in `up'
>
> Caused by:
> ActiveRecord::StatementInvalid: Could not find table 'active_storage_blobs'
> /Users/jose.galisteo/RAILSTEST/rails6141/db/migrate/20210922074150_add_service_name_to_active_storage_blobs.active_storage.rb:4:in `up'
> Tasks: TOP => db:migrate
> (See full trace by running task with --trace)
```

I created a new rails _6.1.4.1_ app. As you know, it doesn't generate any migration.

Then I upgraded to rails 7.0.0.alpha2, and triggered `rails app:update`, which generated two migrations.

Those migrations failed, as this PR describes.

I think that checking if the table and column exist in the migration is the most straightforward mechanism. Because `ActiveStorage::Engine` can be defined but not installed (migrations generated), like in my example.

My only concern is that every update will generate a couple of useless migrations, but the developer can delete them. It at least doesn't raise an exception.

**Review by ceritium — APPROVED** [review]
I think that it is a good enough approach. I tested the `app:update` task and migrations with a new rails 6.1.4 app, which works like a charm.

**Pull request closed without merging**
