### PR TITLE
Add a missing require to ActiveSupport::NumericWithFormat

### LINKED ISSUE #22805: Undefined method 'deprecate' for ActiveSupport::NumericWithFormat:Module
Undefined method 'deprecate' for ActiveSupport::NumericWithFormat:Module

Steps to reproduce:
 1. Using repo https://github.com/jasnow/photish5 (with .rvmrc's Ruby
    set to 2.3.0 and Rails 5 (beta1), run "bundle" then run "rake" and you get this:
```
       ".../.rvm/gems/ruby-2.3.0@ruby2.3.0-rails4.2/gems/
       activesupport-5.0.0.beta1/lib/active_support/core_ext/
       numeric/conversions.rb:127:in `<module:NumericWithFormat>':
       undefined method `deprecate' for
       ActiveSupport::NumericWithFormat:Module (NoMethodError)
       Did you mean?  deprecate_constant
         delegate
       from .../.rvm/gems/ruby-2.3.0@ruby2.3.0-rails4.2/gems/
       activesupport-5.0.0.beta1/lib/active_support/core_ext/
       numeric/conversions.rb:4:in `<top (required)>'
       from /home/jasnow/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/
       rubygems/core_ext/kernel_require.rb:55:in `require'
```
 2. When you can change .rvmrc from 2.3.0 to 2.2.4 and Rails 5 (beta1) and repeat step 1, "rake" works (no error).

### PR DESCRIPTION
**Pull request by maclover7**
Fixes #22805.

### CODE REVIEW

**Comment by schneems** [comment]
Thanks!

**Comment by schneems** [comment]
We could add some integration tests that verify requiring individual files does not result in an error. It would have caught this failure. Sprockets does this.

**Comment by rafaelfranca** [comment]
Rails does too. activesupport:isolation does that

**Comment by schneems** [comment]
@maclover7 could you look into adding a test for requiring this file or if one exists why it wasn't failing before?

**Comment by maclover7** [comment]
Yep, looks like `ActiveSupport::NumericWithFormat` has no test coverage checking the deprecated `to_formatted_s` method. Will send in a PR to add test coverage here. :-)

**Pull request merged**
