### PR TITLE
Support password in ActionCable redis configuration

### PR DESCRIPTION
**Pull request by will-in-wi**
### Summary

Redis supports being configured to require a password. Redis-rb supports this parameter. All that remains is passing it through.

### Other Information

This is one of my first patches, so please let me know how I can improve it. It looks like there are no Redis specific tests, so I'm not sure how you would like me to proceed on that front.

Thanks!

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Is not the password supported as part of the url?

**Comment by will-in-wi** [comment]
Indeed it is. Although it is nice to be able to just pass an additional parameter instead of having to insert it into the URL. Your call.

Thanks!

**Comment by will-in-wi** [comment]
I must admit that I spent 30-ish minutes trying to make this work before making and uploading the patch, then finally figuring out the URL trick. So I'm happy if you want to chalk this up to an ignorant user and close it.

**Comment by matrix9180** [comment]
I like the idea of this patch but it's going to need tests covering the changes. Check [`ActionCable::Server::WithIndependentConfig`](https://github.com/rails/rails/blob/master/actioncable/test/subscription_adapter/channel_prefix.rb#L3-L9) to see how I went about testing multiple AC configs.

**Comment by will-in-wi** [comment]
I'm struggling to figure out the preferred way to test this. I can easily test that the config is passed through, but that's not particularly useful. However, I'm not seeing a reasonable way to get the Redis class instance back from ActionCable in order to check for the password. Finally, I don't see a straightforward way of having a Redis server to test against which requires a password only for this test.

Am I missing something, or could someone point me in the right direction?

Thanks!

**Comment by padi** [comment]
@matthewd This is resolved since https://github.com/rails/rails/pull/29528 was merged 👍

**Pull request closed without merging**
