### PR TITLE
More detailed docs on singular routing + `form_with`

### PR DESCRIPTION
**Pull request by ghiculescu**
Updates docs in 3 places:

- https://api.rubyonrails.org/classes/ActionDispatch/Routing/Mapper/Resources.html#method-i-resource
- https://guides.rubyonrails.org/form_helpers.html#relying-on-record-identification
- https://guides.rubyonrails.org/routing.html#singular-resources

To consistently explain how singular routes using `resources` should be set up, so they can work with `form_with`, `redirect_to`, and anything else that uses record identification.

(There's lots of comments below because my original suggestion was to remove the call to `resolve` from the docs, when it turns out it is necessary.)

### CODE REVIEW

**Comment by kaspth** [comment]
The resolve is there such that when you do `form_with model:` for this particular resource, it'll resolve to the right route, iirc. cc @pixeltrix

If that works without the resolve then we can remove it.

**Comment by ghiculescu** [comment]
@kaspth I think that's useful for the polymorphism section: https://guides.rubyonrails.org/routing.html#using-resolve

I'm not sure it's necessary for the singular resource section, which seems unrelated to polymorphism: https://guides.rubyonrails.org/routing.html#singular-resources

**Comment by pixeltrix** [comment]
I think including it without more context does look confusing, but it's still useful to bring up in that section since people can use polymorphic routes without realising they are. Perhaps splitting it out into a separate note within that section would be better?

**Comment by ghiculescu** [comment]
Maybe I'm missing something. Is `resource :geocoder` a polymorphic route? It doesn't look like it to me, and the `Geocoder` model doesn't feel like a polymorphic thing.

Nothing in this section https://guides.rubyonrails.org/routing.html#singular-resources seems to have anything to do with polymorphism, *except* the call to `resolve` (which is why I want to remove it).

**Comment by pixeltrix** [comment]
> Maybe I'm missing something. Is `resource :geocoder` a polymorphic route? It doesn't look like it to me, and the `Geocoder` model doesn't feel like a polymorphic thing.

The classic example is a `Basket` model used with `form_with`:

``` ruby
resource :basket
```
``` erb
<%= form_with model: @basket %>
<!-- update basket form here -->
<% end %>
```

Here you are using `polymorphic_url` implicitly by passing it to `form_with` - without a `resolve` it will try to generate `baskets_url` if the basket is not yet saved, or if it is saved then it will generate `/baskets.1`assuming 1 is the basket record id (it gets treated as a format parameter from the optional segment). This is the reason I think it still needs a note in this section as you may not realise you're using polymorphic urls and not find the documentation.

Does that make things clearer?

**Comment by ghiculescu** [comment]
Ahhh yep, I had to [prove it to myself](https://github.com/ghiculescu/singular-routes-demo/commit/4c75cee94a361371e974a2614c261ee4fd41eaa2) but now I'm with you. Thanks for bearing with me.

It still seems confusing to me why the fact we're calling `resource` (not `resources`) can't implicitly say the same thing. Is there a classic example for `resource` *without* `resolve`? (I realise I'm now proposing a code change rather than a docs change. Happy to investigate it further.)

**Comment by pixeltrix** [comment]
@ghiculescu I suggest you read #1769 and then come back to me if you still have questions

**Comment by ghiculescu** [comment]
@pixeltrix thanks very much for bearing with me.

I've made a few edits here with suggestions on how to make the docs clearer. Would love to hear any feedback on them.

**Comment by ghiculescu** [comment]
@pixeltrix any more thoughts on this one?

**Review by pixeltrix — APPROVED** [review]

**Comment by pixeltrix** [comment]
@ghiculescu thanks for your improvements to the documentation 👍🏻

**Pull request merged**
