### PR TITLE
Add aliases for polymorphic associations

### PR DESCRIPTION
**Pull request by mansakondo**
### Summary
As with [delegated types](https://edgeapi.rubyonrails.org/classes/ActiveRecord/DelegatedType.html#method-i-delegated_type), I'd like to define polymorphic associations like this:
```ruby
# app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :reviewable, polymorphic: true, types: %w( Album Restaurant )
end

# app/models/album.rb
class Album < ActiveRecord::Base
  has_many :reviews, as: :reviewable
end

# app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews, as: :reviewable
end
```
And access them this way:
```ruby
Review#album
Review#album=
Review#reload_album

Review#restaurant
Review#restaurant=
Review#reload_restaurant
```
I'll be waiting for your feedback to improve the code. Here's the initial issue: #42868.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
I'm not sure if this feature is worth all this complexity. You could define those alias yourself using `alias` for example. Of course that would mean that you could have the object returning the same result for `album` and `restaurant` even though the object is a `Restaurant` for example, but adding a new `method_missing` hook that would slow down other `method_missing` hooks in `ActiveRecord::Base` to avoid `album` to return a `Restaurant` doesn't seems worth.

Of course there are other ways to implement this feature, but I'm not convinced it is needed.

**Comment by mansakondo** [comment]
> I'm not sure if this feature is worth all this complexity. You could define those alias yourself using `alias` for example. Of course that would mean that you could have the object returning the same result for `album` and `restaurant` even though the object is a `Restaurant` for example, but adding a new `method_missing` hook that would slow down other `method_missing` hooks in `ActiveRecord::Base` to avoid `album` to return a `Restaurant` doesn't seems worth.
> 
> Of course there are other ways to implement this feature, but I'm not convinced it is needed.

Yep agreed. That's not the best solution and this feature isn't critical either. I just think it would be nice regarding the fact that delegated types already does that.

**Comment by mansakondo** [comment]
I'd like to have a solution as simple as this piece of code from [delegated_types](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/delegated_type.rb#L197):
```ruby
def define_delegated_type_methods(role, types:, options:)
        primary_key = options[:primary_key] || "id"
        role_type = "#{role}_type"
        role_id   = options[:foreign_key] || "#{role}_id"

        define_method "#{role}_class" do
          public_send("#{role}_type").constantize
        end

        define_method "#{role}_name" do
          public_send("#{role}_class").model_name.singular.inquiry
        end

        types.each do |type|
          scope_name = type.tableize.tr("/", "_")
          singular   = scope_name.singularize
          query      = "#{singular}?"

          scope scope_name, -> { where(role_type => type) }

          define_method query do
            public_send(role_type) == type
          end

          define_method singular do
            public_send(role) if public_send(query)
          end

          define_method "#{singular}_#{primary_key}" do
            public_send(role_id) if public_send(query)
          enddef define_delegated_type_methods(role, types:, options:)
        primary_key = options[:primary_key] || "id"
        role_type = "#{role}_type"
        role_id   = options[:foreign_key] || "#{role}_id"

        define_method "#{role}_class" do
          public_send("#{role}_type").constantize
        end

        define_method "#{role}_name" do
          public_send("#{role}_class").model_name.singular.inquiry
        end

        types.each do |type|
          scope_name = type.tableize.tr("/", "_")
          singular   = scope_name.singularize
          query      = "#{singular}?"

          scope scope_name, -> { where(role_type => type) }

          define_method query do
            public_send(role_type) == type
          end

          define_method singular do
            public_send(role) if public_send(query)
          end

          define_method "#{singular}_#{primary_key}" do
            public_send(role_id) if public_send(query)
          end
        end
        end
```

**Comment by rafaelfranca** [comment]
We can generate those methods when defining the association, like we already do with the `reviewable` in that case. I think if we want to merge this, this is the direction we should take.

**Comment by mansakondo** [comment]
> We can generate those methods when defining the association, like we already do with the `reviewable` in that case. I think if we want to merge this, this is the direction we should take.

Alright then I'll iterate to this to present a viable solution.

**Comment by mansakondo** [comment]
@rafaelfranca Here's the updated code.

**Pull request closed without merging**
