### PR TITLE
WIP: Enable UUID primary keys for ActiveStorage

### PR DESCRIPTION
**Pull request by Schwad**
### Summary

Current ActiveStorage configurations preclude usage of UUID primary keys with the interface.
This PR will allow users to specify a UUID option:
`rails active_storage:install[uuid]`

### Other Information

This is a first pass to attempt implementing the options functionality and also running the migration. I am looking for feedback on the best place to store this migration and best practices with accepting user arguments.

General commentary welcome as well. :) 

After we get this working, I will also update READMEs to show this accepted argument.

### CODE REVIEW

**Comment by Schwad** [comment]
@rafaelfranca 

Thank you so much for your prompt thoughts on this and your kind review. 

We have been using ActiveStorage since 5.2.0.alpha, practically day one, on our greenfield projects. It is robust enough now that we are looking to migrate it over to past existing projects as well. 

However, the process of manually going in and digging around with the migration file every time to make it comply with our (common) configuration was the only part of the interaction which felt unnatural. The best part of ActiveStorage and the reason we are so happy that @dhh led the charge to build it is that every component of the developer experience is *slick* and *intuitive*. 

Instead of writing an issue asking for someone else to address this issue (as we are still on rc2 and ActiveStorage is soon to get its big unveil), we decided to start putting together a PR to show our appreciation and contribute. 

As noted in the title this is still a WIP: I will be looking to wrap up a functioning set of code to this spec and then will kindly ask for your review and thoughts one more time. 

Also, if anyone comes upon this PR and has further thoughts and feedback on what I'm trying to accomplish, feel free to chip in.

**Comment by rafaelfranca** [comment]
I still think this is not common enough to justify this code in the framework. You only need to do this once and most application will use bigint as primary keys, not uuid.

We optimize the framework to be intuitive and slick to the 80% of the project. We never aim 20%. For those 20% the convention is not enough and they will have to configure. I believe that is the case here. I don't see why to complicate the framework with two different sets of migrations.

I'm more inclined to something like making this migrations respect the `primary_key_type` of the generators.

**Comment by Schwad** [comment]
Thanks for the syntax commit, @xjlin0 ! Will definitely continue this and keep in touch with you as we proceed forward. 

I am thinking hard on @rafaelfranca 's points here about how I can maintain this without doing 'two different sets' of migrations... 

Further I am digging into the Rails internals to grok how I may access properly the `primary_key_type` and enforce ActiveStorage respecting them instead of going for int. For example, wouldn't it be great if this PR worked not just for our `UUID` cases but for bigint and others as well? 

Since I am not a frequent or well-versed Rails core committer, please bear with me as I get familiar with certain parts of this functionality.

**Comment by rafaelfranca** [comment]
You could use a subclass of the migration generator to generate those migrations. The migration generator already have support to `primary_key_type`. So given you app has `primary_key_type` set to uuid, the active storage migration generator would respect that.

**Comment by Schwad** [comment]
Update, I have been working on moving this to the best form to respect the `primary_key_type` directly as suggested by @rafaelfranca . Thanks again for the feedback!

**Comment by Schwad** [comment]
@xjlin0 @georgeclaghorn 

I am currently going to close this specific PR, for two reasons.

1. The approach I started with, after @rafaelfranca 's feedback, I've decided is wrong. It should be an 'intuitive' pull of `primary_key_type` so that any developer firing up active storage for the first time doesn't run into a wall if their primary key type isn't an integer. That warrants a new PR specifying that. Further, I have not been able to 'figure out' how to dynamically access `primary_key_type` from within the generators.

2. Leaving this PR open adds to Rails-core 'PR-load' and sends a signal that I am actively working on this. Alternatively, leaving it open a long time without updates makes it appear that I don't care (which I do). If anyone with more Rails-core knowledge than me has insight on the best way to 'take a stab' at this I would be grateful for feedback, or if they had a PR they wanted to attempt. 

It is my intent to revisit this in the future with the new approach, and when I do I will fire up a new PR properly and reference this one for documentation purposes from within. 

Thank you all for your thoughts and feedback, I really hope this is something I am able to put together at some point in the future when I have more knowledge around the Rails-core development environment and the time to do this the right way. Cheers! ❤️

**Comment by Schwad** [comment]
Hi @kylefox ! 👋 

I don't know if there's an official 'best practice' but myself and colleagues have just updated our migrations as indicated by Randy Burgess here: https://www.wrburgess.com/posts/2018-02-03-1.html

Even though I've hung up my hat (for now) on out-of-the-box-uuid-support-attempts, I think you raise a much more poignant issue. If I'm using uuid primary keys and fire up ActiveStorage, I am going to have a silently broken system. 

I think it is reasonable to expect a raised error for this. We could also maybe have a verbose error that let developers know they ought to change their migrations.

I have had a little peek through some of the ActiveStorage codebase- I think if we could get something simple together quick there might be a prayer for packaging in the Rails 6 release. Otherwise maybe a future patch version. What do you think?

**Comment by kylefox** [comment]
@Schwad Cool, thanks for the link. Definitely a good resource.

What you proposed sounds totally reasonable! Even though it was _totally_ my fault for not anticipating the problems my UUIDs would cause ActiveStorage, it felt very un-Railsy to have it be silently broken (in a very severe way). An error would've got my attention 😅

But thinking about it more, is this more broadly an issue with _all_ polymorphic references? 🤔 

All polymorphic associations make an assumption about the associated record's PK data type, so this same issue could appear in internal code, gems, engines, etc.

I know it's a wider scope, but do you think it's worth considering validation of polymorphic FK/PK data types at the ActiveRecord level?

**Comment by ziaulrehman40** [comment]
The issue @kylefox mentioned bit me for days since i landed here, worst part is that my records were randomly getting files populated and randomly loosing attachments even though I could see insertion in active_storage tables.

This is definitely a bug, even if rails don't want to support different kind of primary keys in active storage for now, there should be no silent failures like this. And some notes on this within the generated migration indeed(like devise shows lot of comments in migration) to make it clear that what is supported and what is not so users can properly go about using things.

**Comment by asmrtfm** [comment]
```rb
# Rails version 7.2.2.2
# Ruby version 3.2.4

> User.all

[ #<User id: "57c76dd3-5f17-4674-a44e-f5ab8787e181", ...,
 #<User id: "b3669168-0012-4250-95ed-2be1250b8bb2", ... ]


>  ActiveStorage::Attachment.where(record_type: "User")

[#<ActiveStorage::Attachment:0x00007cfd8f0fa640 id: 1407, name: "picture", record_type: "User", record_id: 57, blob_id: 1407, created_at: "2025-11-09 02:19:19.002199000 +0000">,
 #<ActiveStorage::Attachment:0x00007cfd8f0f7440 id: 1409, name: "picture", record_type: "User", record_id: 0, blob_id: 1409, created_at: "2025-11-09 02:21:00.976084000 +0000">]
```

My users has_one :attachment called 'picture'
Somehow, the first user I attach an image to works fine, and the above shows it somehow gets a record_id of 57.
However, all subsequent users fail to attach an image.
No errors are thrown and the logs are identical to the one which succeeded.
The only difference is that they all get a record_id of 0.

I have experimented with altering the create_active_storage_tables migration as follows:
```rb
      create_table :active_storage_attachments, id: primary_key_type do |t|
        t.string     :name,     null: false
        # t.references :record,   null: false, polymorphic: true, index: false, type: foreign_key_type
        t.references :record,   null: true, polymorphic: true, index: false
        t.references :blob,     null: false, type: foreign_key_type
        ...
```

Nothing seems to change.
However, before running my altered migration, if I tried to manually update the attachment's record_id to be the user's actual id, I would get errors about a not null constraint.  This is why I also set `null: true` in the migration.
After recreating active storage tables with my altered migration, I do not get that error, but the record_id is still set to nil.

I assume this is the result of a validation somewhere but I can not find any documentation on the matter, so I am still trying to hunt it down. That being said, if I'm correct, then couldn't that validation be adjusted to check the actual id class of the record model no differently than normal polymorphic behavior; that, or just be removed entirely?

**Comment by gregmolnar** [comment]
Just don't use UUIDS for primary keys. They rarely bring any benefits but usually comes with a extra complexity.

**Comment by asmrtfm** [comment]
> Just don't use UUIDS for primary keys. They rarely bring any benefits but usually comes with a extra complexity.

I mean I tend to agree with you, but there are definitely scenarios where they are "required". (emphasis on tend to agree, lol)
And besides, not using them might not be a decision we are free to make.

**Comment by asmrtfm** [comment]
In order to use active storage with **both** :bigint and :uuid types, you could create a through-table whose primary_key column type is :bigint and give it a polymorphic belongs_to with a <>_type of :uuid for the associated tables that have UUID.

For example, imagine you had some core tables, ostensibly whatever your app is about, whose data rarely changes and is for the most part just seed data - they all use normal integer IDs.  Perhaps some of those tables have a pictures attribute.  

Perhaps your users table uses :uuid and are also supposed to have pictures.

*Disclaimer* I am an authority on nothing and have very little experience... however, the following seems to work well enough.

```rb
class CreatePhotoAlbums < ActiveRecord::Migration[7.2]
  def change
    create_table :photo_albums do |t|
      t.belongs_to :subject, polymorphic: true, null: false, type: :uuid

      t.timestamps
    end
  end
end
```
This has the benefit of not requiring any modification to active_storage tables.


Let it has_one or has_many of your active_storage attachments:
```rb
class PhotoAlbum < ApplicationRecord
  belongs_to :subject, polymorphic: true

  # has_many :pictures do |attachable|
  has_one_attached :picture do |attachable|
    attachable.variant :thumb,
    resize_to_limit: [ 150, 150 ]
  end
  # ...
end
```


```rb
module Picturable

  module HasBigintAndOnePicture
    extend ActiveSupport::Concern
    included do
      has_one_attached :picture do |attachable|
        attachable.variant :thumb,
        resize_to_limit: [ 150, 150 ],
        preprocessed: true
      end
    end
  end


  module HasUuidAndOnePicture
    extend ActiveSupport::Concern

    included do
      def self.subject_type = name

       has_one :photo_album, class_name: "PhotoAlbum", as: :subject, inverse_of: :subject, foreign_key: :subject_id
      delegate :picture, :thumbnail, to: :photo_album, allow_nil: true

      after_create :create_photo_album
    end

    def subject_id = self.id
    def subject_type = self.class.name

    def create_photo_album(**photo_album_attributes)
         PhotoAlbum.create(**photo_album_attributes.merge(subject_type:, subject_id:))
    end

    def update_picture(p)
      if photo_album.blank?
        create_photo_album(picture: p)
      else
        # ...
      end
    end
  end


  def self.included(base)
    if (base.columns_hash["id"]&.type == :integer)
      base.include(HasBigintAndOnePicture)
    else
      base.include(HasUuidAndOnePicture)
    end
    base.include(Pictures) # shared picture methods
  end

end
```

```rb
class User < ApplicationRecord
  include Picturable
end
```

```rb
class Product < ApplicationRecord
   include Picturable
end
```

---
```rb
(3.2.4) >  User.first.picture

#<ActiveStorage::Attached::One:0x00007480641dde50
 @name="picture",
 @record=
  #<PhotoAlbum:0x0000748065723918
   id: 3,
   subject_type: "User",
   subject_id: "5b4ae6ee-3af4-42af-8baf-c58841135489",
   ...

(3.2.4) >  Product.first.picture
#<ActiveStorage::Attached::One:0x00007480623a5410
 @name="picture",
 @record=
  #<Product:0x00007480623c5170
   id: 1,
   category_id: 3,
   subcategory_id: 16,
   tertiary_category_id: 20,
   brand_id: 1,
   name: "Walnut Brown Ale",
   ...
   ```

**Pull request closed without merging**
