### PR TITLE
Fix reverting remove_foreign_key

### LINKED ISSUE #33515: remove_foreign_key is not reversible
### Steps to reproduce

1. Add a migration with
```
  def change
    remove_foreign_key :sms_routes, column: :client_id, to_table: :clients, on_delete: :restrict
  end
```
2. migrate
```
== 20180802081908 SetCascadeForeignKeyOnSMSRoutes: migrating ==================
-- remove_foreign_key(:sms_routes, {:column=>:client_id, :to_table=>:clients, :on_delete=>:restrict})
   -> 0.0058s
== 20180802081908 SetCascadeForeignKeyOnSMSRoutes: migrated (0.0059s) =========
```

3. rollback
```
2018-08-02T13:25:17.917606+04:00 rake/db:rollback 1EQPbu4U INFO - Migrating to SetCascadeForeignKeyOnSMSRoutes (20180802081908)
2018-08-02T13:25:17.921855+04:00 rake/db:rollback 1EQPbu4U DEBUG -  (0.2ms)  BEGIN /*application:StaffControl*/
== 20180802081908 SetCascadeForeignKeyOnSMSRoutes: reverting ==================
2018-08-02T13:25:17.927181+04:00 rake/db:rollback 1EQPbu4U DEBUG -  (0.2ms)  ROLLBACK /*application:StaffControl*/
2018-08-02T13:25:17.927496+04:00 rake/db:rollback 1EQPbu4U FATAL - StandardError: An error has occurred, this and all later migrations canceled:    remove_foreign_key is only reversible if given a second table
```

It's  `def remove_foreign_key(from_table, options_or_to_table = {})`
either second table or options for reversal, without options it'll be irreversible too.

### Expected behavior
Consistent method prototype for migrate and rollback.

### Actual behavior
Mismatch in arguments, it's either works down or up, but not both.

### System configuration
**Rails version**:
Rails 5.2.0
**Ruby version**:
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]

### PR DESCRIPTION
**Pull request by n-epifanov**
### Summary

Closes #33515

### CODE REVIEW

**Review by sikachu — CHANGES_REQUESTED** [review]
Thank you for your patch!

* I think we need to support both setting `to_table` and grabbing the second argument from the options list (per the old code)
* Do you mind adding a new test for support `:to_table` option while keeping the old test inact?
* Do you mind changing the base merge branch to `master`? Core team will be the one to decide if they want to backport a patch for 5.2.x series.

Thank you very much!

**Comment by nicktime** [comment]
Sorry, can't do, it looks like there have to be a more involving rework to get API right and a fix to command_recorder.rb is not enough.

**Comment by jychen7** [comment]
@nicktime do you mind I help to improve the fix? https://github.com/rails/rails/pull/33530 is a continuing PR which rebase on master a2b9768792a81e474a8b70d3950cd14ffd491207

@sikachu fyi

**Comment by nicktime** [comment]
@jychen7 Sure, go ahead!

**Pull request closed without merging**
