### PR TITLE
Make AR::Attributes independent of AR::ModelSchema

### LINKED ISSUE #38293: (Object doesn't support #inspect) for singleton_class of model instance
I will preface this by saying this is pretty much a non issue, but I am neurotically pedantic.

### Steps to reproduce
- Have a table with at least one entry, and a associated model (For sake of example, the model will be `User`)
- Run rails console
- Inside the rails console, get an instance of a model (`u = User.first`)
- As long as `u` is not nil, run `u.singleton_class`
- Alternatively, run `u.singleton_class.inspect`

### Expected behavior
For the command `u.singleton_class` to output
```#<Class:#<MODEL_NAME:ADDRESS>>```
to the console
(for example `#<Class:#<User:0x000055ff2311e9c8>>`)

And for `u.singleton_class.inspect` to output the string of the same thing

### Actual behavior
The console outputs
```
2.6.5 :019 > u.singleton_class
(Object doesn't support #inspect)
```

```
2.6.5 :020 > u.singleton_class.inspect
Traceback (most recent call last):
        1: from (irb):20
NoMethodError (undefined method `synchronize' for nil:NilClass)
```

With a bit of further probing, it seems that the function in question is at
`activerecord-5.2.3/lib/active_record/model_schema.rb:456`
Though I could be wrong

### System configuration
**Rails version**: ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]

**Ruby version**: Rails 5.2.3

### PR DESCRIPTION
**Pull request by jonathanhefner**
This refactor is a step towards porting more modules from Active Record to Active Model.  `ActiveRecord::Attributes` no longer depends on `ActiveRecord::ModelSchema`.  Likewise, `ActiveRecord::AttributeDecorators` no longer depends on `ActiveRecord::ModelSchema`, and now depends on `ActiveRecord::Attributes` instead.

An overview of the changes:

* Move `_default_attributes` and `attribute_types` from `ModelSchema` to `Attributes`.
* Replace `ModelSchema::reload_schema_from_cache` with `Attributes::reset_attributes`.
* Replace calls to `Attributes::define_attribute` with calls to `Attributes::add_attribute_to_attribute_set`, which does not mutate global state.  (The original method was not removed because it is publicly documented.)
* Replace `ModelSchema::load_schema!` with `Attributes::add_deferred_to_attribute_set`, which does not mutate global state.
* Define `Attributes::_default_attributes` as the point of entry for `Attributes::add_deferred_to_attribute_set`, and ensure neither are part of a circular call tree.
* Remove the `Monitor` from `ModelSchema::load_schema`, which now only calls `Attributes::_default_attributes`, which itself only writes one piece of global state, atomically.
* Remove now-redundant calls to `ModelSchema::load_schema`.

Coincidentally, fixes #38293.

### CODE REVIEW

**Comment by jonathanhefner** [comment]
@casperisfine Would this PR be of any interest to you?  I noticed you had some issues with `load_schema` that were worked around in #37288.

Also, I know you've done several optimizations to improve application boot performance.  I'm curious if removing the `Monitor` (and two `class_attribute`s) affects any performance characteristics in your benchmark.

**Comment by casperisfine** [comment]
> Would this PR be of any interest to you? I noticed you had some issues with `load_schema` that were worked around in #37288.

Well, the issue I had is that there are several things during attribute definition that requires to access `Base#connection`, which tries to connect to the database.

The main one being `connection.schema_cache`, but there's also `connection.lookup_cast_type_from_column`. From what I understand of your PR, none of that is solved.

TBH I'm having a bit of a hard time to understand this PR (not your fault), so it's hard for me to say wether it goes in what I think is the good direction or not. But I'll continue exploring it.

>  I'm curious if removing the Monitor (and two class_attributes) affects any performance characteristics in your benchmark.

So while trying to answer this, I realized my benchmark had a blindspot (because of the connection problem explained above). I'll be fixing it and will come back to you once I have more accurate benchmarks.

**Comment by casperisfine** [comment]
> I'll be fixing it and will come back to you once I have more accurate benchmarks.

Ok, so I'm afraid I'll have to give up for now on that one. I've been fighting with AR for the last 3 hours and defining attributes without connecting to the DB is terribly hard, even with ugly monkey patches.

**Comment by jonathanhefner** [comment]
@casperisfine 

> TBH I'm having a bit of a hard time to understand this PR

Thank you for your feedback!  I realized I needed to do a better job of explaining this PR.  I hope I've done that now, but I would be appreciative of further critique.

> The main one being `connection.schema_cache`, but there's also `connection.lookup_cast_type_from_column`. From what I understand of your PR, none of that is solved.

I can't say for sure if this PR will help, because I haven't had to face those problems, but here's what happens now (in this PR):
 
* `ModelSchema::columns_hash` sets `@columns_hash`, but only if `connection.schema_cache.columns_hash(table_name)` is successfully called.
* All attribute types and decorations (e.g. [`serialize`](https://github.com/rails/rails/blob/130513d039e9855e0aeddd7a075650a644a10c1e/activerecord/lib/active_record/attribute_methods/serialization.rb#L72)) are "loaded" as a single unit, atomically.  If `ModelSchema::columns_hash` or any `connection.lookup_cast_type_from_column` calls raise an error, the load will be prevented and the error will bubble up.

**Comment by casperisfine** [comment]
> * raise an error, the load will be prevented and the error will bubble up.

I see. That's indeed is a bit cleaner than the way we unload on error currently. But that doesn't really solve the root cause IMO (doesn't mean this isn't worth it, I just can't say).

**Pull request closed without merging**
