### PR TITLE
fixed to ruby 1.9 hash syntax

### PR DESCRIPTION
**Pull request by askl56**
I have fixed all of the Ruby hash syntax in the entire project to the 1.9 spec. Rubocop should calm down now :P

### CODE REVIEW

**Comment by arunagw** [comment]
Thanks for your effort. But sorry we do not accept cosmetic change.

See https://github.com/rails/rails/pull/13771#issuecomment-32746700

These changes make back porting a feature really hard.

**Comment by askl56** [comment]
So Rails itself doesn't follow Ruby best practices?

**Comment by kaspth** [comment]
As an aside we don't really care what Rubocop says, and it's not a goal for us to adhere to its guidelines. So if that's the reason given for opening a pull request it will be closed :heart:

**Comment by kaspth** [comment]
Rails itself has been around for a while, and there could be useful info in git blame which your change makes it harder to look at.
But we do also have the standard that any new code should use 1.9 syntax regardless of what the rest of the file does.

**Comment by askl56** [comment]
I just figured I was helping out that's all. All I've done is fix the hash syntax and as far as I can tell the code should still work except if stuff is still dependent on Ruby 1.8. However I bow to your superior experience.

**Comment by kaspth** [comment]
We're requiring Ruby 2.2 and I'm sure the code works, but that's not why we don't want to merge this. Read the link @arunagw provided for more info: https://github.com/rails/rails/pull/13771#issuecomment-32746700

**Comment by askl56** [comment]
I did. Like I said, apologies for wasting time.

**Comment by kaspth** [comment]
Don’t worry about it :heart:

> Den 12/06/2015 kl. 11.35 skrev Andrew Scott <notifications@github.com>:
> 
> I did. Like I said, apologies for wasting time.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/rails/rails/pull/20532#issuecomment-111429413>.
> 

--
Kasper

**Pull request closed without merging**
