### PR TITLE
Added doc [ci skip]

### PR DESCRIPTION
**Pull request by sivsushruth**
Documented the method filtered_location and linked it to its usage guide.

### CODE REVIEW

**Comment by arthurnn** [comment]
Seems like most of this class is private. I wonder if that method should be nodoc too or not?
@rafaelfranca always know how to answer those questions.

**Comment by sivsushruth** [comment]
It was a bit confusing when I had a look at it. I had to search for all instances of filtered_redirect and then somehow reached the guides explaining its usage.
This might be handy, I think.

**Comment by kaspth** [comment]
I'm :+1: on nodoc'ing it. The only place I found it used was internally here: https://github.com/rails/rails/blob/2d743b528cf8ee2a8dc016a5dd0d54bf7cbc34e4/actionpack/lib/action_controller/metal/instrumentation.rb#L66

**Comment by seuros** [comment]
I think we should nodoc it.

**Comment by seuros** [comment]
@sivsushruth  could you make this change ?

**Comment by sivsushruth** [comment]
@seuros  Yes, doing that

**Comment by kaspth** [comment]
Please change the commit to say something like "nodoc filtered_location" too :smile:

**Comment by sivsushruth** [comment]
Done

**Comment by kaspth** [comment]
Thanks :wink:

**Pull request merged**
