### PR TITLE
Don't reap connections that have already been reassigned

### LINKED ISSUE #25585: ActiveRecord::ActiveRecordError: Cannot lease connection, it is already in use by a different thread
### Steps to reproduce
* rails new my_app
* export DISABLE_SPRING=true
* rails g scaffold post title:string body:text
* echo "gem 'pg'" >> Gemfile & bundle
* set up database.yml
```yml
development: &DEVELOPMENT
  adapter: postgresql
  database: myapp_development
  username: <username>
  password: <password>
  host: localhost
  pool: 5
  timeout: 5000

test: &TEST
  <<: *DEVELOPMENT
  database: myapp_test
  min_messages: warning
```
* rake db:create db:migrate
* Change models/post.rb to:
```Ruby
 def self.update_body(title)
    post = Post.find_by(title: title)
    post.update_attributes(body: 'body body')
  end
```

* Change test/models/post_test.rb to:
```Ruby
require 'test_helper'

class PostTest < ActiveSupport::TestCase

  test "something" do
    post = Post.create(body: 'some body', title: 'some title')
    assert_equal 'some body', post.body
  end

  uses_transaction :test_update_body_atomically
  def test_update_body_atomically
    Post.create(body: 'some body', title: 'some title')

    25.times do
      Array.new(4) do
        Thread.new { Post.update_body('some title')}
      end.each(&:join)
    end
    assert_equal 'body body', Post.find_by(title: 'some title').body
  ensure
    Post.delete_all
  end
end
```
* Run `rails test test/models/post_test.rb` until you see the error (Should be less than 20 times.. so may be write a script for it :stuck_out_tongue: )

### Expected behavior
Test should have passed

### Actual behavior
```
message type 0x54 arrived from server while idle
message type 0x44 arrived from server while idle
message type 0x43 arrived from server while idle
message type 0x5a arrived from server while idle
message type 0x54 arrived from server while idle
message type 0x44 arrived from server while idle
message type 0x43 arrived from server while idle
message type 0x5a arrived from server while idle
E

Error:
PostTest#test_update_body_atomically:
ActiveRecord::ActiveRecordError: Cannot lease connection, it is already in use by a different thread: #<Thread:0x00000004a24f78>. Current thread: #<Thread:0x00000003f03018>.
    app/models/post.rb:4:in `update_body'
    test/models/post_test.rb:16:in `block (3 levels) in test_update_body_atomically'
```

### System configuration
**Rails version**:
5.0.0.rc2
**Ruby version**:
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

**pg gem version**
0.18.4
**postgres version**
9.4.7

I won't be able the explain the logicality of the test or that function. I am just trying to mimic what I am doing in my real app. If you would rather see the real build failure you can check it out [here](https://travis-ci.org/rubygems/rubygems.org/jobs/140831890#L1126). 
I am sorry but I don't have much to provide other than "this was not an issue on rails 4.2.6". Let me know how I can help debug this.

EDIT: Simplified method and removed cases where the error was not reproduceable.

### PR DESCRIPTION
**Pull request by matthewd**
Fixes #25585 

@thedarkone any brilliant ideas for testing this?

So far my only thoughts are to either Mock Everything, or blindly hammer it in a loop and hope for the best/worst. The latter is how I manually proved it locally, but for a proper test, neither sounds particularly exciting. :confused:

### CODE REVIEW

**Comment by thedarkone** [comment]
> any brilliant ideas for testing this?

Nope, testing races is an ugly business, it is usually done via concurrent torture test suites. They are heavyweight and I don't think we have a capacity to implement them right now (and keep running them on CI).

PS: that is a mindbogglingly sloppy race in my code, sorry.

**Comment by sonalkr132** [comment]
This works :blush: Thanks @matthewd 
Any idea which release it will go in?

**Comment by matthewd** [comment]
> Nope, testing races is an ugly business

Yeah, I don't see any way to inject latches to force the worst-case sequencing. I guess I'll just go with the increased runtime assertions.

> PS: that is a mindbogglingly sloppy race in my code, sorry.

I think the phrase you're looking for is "I can't believe I wrote that", in which case... [well...](https://github.com/rails/rails/blame/3a62dacd7118032905148d88e89370a32d863e1e/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L556) 😳 

Your reduction of locking obviously made it much more likely to occur, but I think the race was present (in an actual, possible-to-manifest, way) in 4.2 too: the `acquire_connection` reaps couldn't overlap because they were covered by the large `checkout` synchronize, but one could have occurred in the middle of a scheduled reap (*if* the scheduled reaper had been enabled). So, pretty definitely my fault. 😁

**Comment by jrafanie** [comment]
@thedarkone @matthewd thanks for your work on these race conditions.  It sounds horrible to diagnose and debug, and incredibly simple once you propose the solution.  I have no idea how much time you must have racked your brain trying to recreate it!

**Comment by matthewd** [comment]
Backported as 2537d08c1670aaa9422afdd07df648541c5588d2

**Pull request merged**
