### PR TITLE
Support prerelease rubies in Gemfile template

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
### Motivation / Background

Recent Bundler versions are more strict (and more correct IMO) when matching the versionof the `ruby` Gemfile DSL and now prereleases like `Ruby 3.2.0.preview2` will no longer match Gemfiles specifying exact constraints on released versions like `ruby "3.2.0"`.

### Detail

I think that's the intention here, but unfortunately `RUBY_VERSION` outputs a release string that's not prerelease aware. For the default Gemfile to support prerelease rubies, it needs to use an exact constraint that considers prereleases, for example, with `Gem.ruby_version`. Alternatively, the requirement could be relaxed, but I believe the intention here is to restrict the Gemfile to the exact Ruby version generating it.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] There are no typos in commit messages and comments.
* [ ] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Feature branch is up-to-date with `main` (if not - rebase it).
* [x] Pull request only contains one commit for bug fixes and small features. If it's a larger feature, multiple commits are permitted but must be descriptive.
* [ ] Tests are added if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.
* [x] PR is not in a draft state.
* [x] CI is passing.

### CODE REVIEW

**Comment by yahonda** [comment]
Do you know if the recent change of bundler via https://github.com/rubygems/rubygems/pull/5766 affects how `.ruby-version` works? This questions should be related to rbenv or similar tools, not related to bundler though. 

Because rails new generates `.ruby-version` file.

https://github.com/rails/rails/pull/33152
https://github.com/rails/rails/pull/30016

**Comment by deivid-rodriguez** [comment]
@yahonda  I think Ruby version managers should not be affected by this because I don't think they use any RubyGems logic to select Rubies.

@rafaelfranca Thanks for merging!

**Comment by rafaelfranca** [comment]
This is now generating `ruby "3.1.2.20"` for released versions and I'm getting
```
Your Ruby version is 3.1.2, but your Gemfile specified
3.1.2.20
```

Is that expected?

**Comment by deivid-rodriguez** [comment]
Oh indeed 😬. `Gem.ruby_version` is sometimes incorrect like that, I forgot. I think that will happen if you're using Bundler older than 2.3.12 and RubyGems older than 3.3.12. Is that your case? I think we need to do a bit more work to make sure this still does the right thing on older versions, I can work on it.

**Comment by rafaelfranca** [comment]
Bundle 2.3.7.

**Comment by ghiculescu** [comment]
@deivid-rodriguez I got a similar issue to @rafaelfranca 

```
Your Ruby version is 3.1.2, but your Gemfile specified 3.1.2.20
```

This is with `bundle --version` = 2.3.19

**Comment by deivid-rodriguez** [comment]
Totally forgot about his, sorry!

Your case looks unexpected according to what I investigated at the time. I'try have another look at this.

**Comment by ghiculescu** [comment]
Let me know if there's any more info I can send to help with investigation - I updated comment above with some more things I tried ❤️

**Comment by deivid-rodriguez** [comment]
@ghiculescu I investigated. I think as soon as this PR is backported and included in a release and you install the Rails release including it, this should work fine.

**Pull request merged**
