### PR TITLE
Rename authentication generator template files

### PR DESCRIPTION
**Pull request by seanpdoyle**
### Motivation / Background

Prior to this commit, Authentication generator calls to [Thor::Actions#template][] were passing a second optional argument to specify the full filename of the destination.

This was necessary because the template files were nested within `lib/rails/generators/rails/authentication/templates` in a way that did not reflect their final destinations. For example, the `user.rb` file was declared in
`lib/rails/generators/rails/authentication/templates/models/user.rb` instead of
`lib/rails/generators/rails/authentication/templates/app/models/user.rb` (i.e. `templates/models/user.rb` instead of
`templates/app/models/user.rb`).

This commit nests the files within the `template/` directory under `app/` when appropriate, which makes the second argument to `Thor::Actions#template` optional and able to be omitted.

### Additional information

In addition to the file structure changes, this commit utilizes the [Thor::Actions#inject_into_class][] helper instead of a call to [Thor::Actions#gsub_file][].

[Thor::Actions#template]: https://www.rubydoc.info/gems/thor/Thor/Actions#template-instance_method
[Thor::Actions#inject_into_class]: https://www.rubydoc.info/gems/thor/Thor%2FActions:inject_into_class
[Thor::Actions#gsub_file]: https://www.rubydoc.info/gems/thor/Thor%2FActions:gsub_file

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by jeromedalbert** [comment]
This is breaking authentication generation for tailwind Rails apps:

Steps to repro:

```
rails new myapp --main --css tailwind; cd myapp
bin/rails generate authentication
      invoke  tailwindcss
Could not find "app/views/passwords/new.html.erb" in any of your source paths. Your current source paths are:
/Users/jerome/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/tailwindcss-rails-2.7.6-arm64-darwin/lib/generators/tailwindcss/authentication/templates
```

FYI:

- erb path: `rails/railties/lib/rails/generators/erb/authentication/templates/app/views/passwords/new.html.erb`
- tailwind path: `lib/generators/tailwindcss/authentication/templates/views/passwords/new.html.erb`

**Comment by jeromedalbert** [comment]
At first I submitted a [PR](https://github.com/rails/rails/pull/53103) that moved authentication templates from `authentication/templates/app/views/` to `authentication/templates/views/`, which is the path [expected](https://github.com/rails/tailwindcss-rails/blob/main/lib/generators/tailwindcss/authentication/templates/views/passwords/new.html.erb) by tailwindcss-rails. Then I got some legit [CI failures](https://buildkite.com/rails/rails/builds/111969#01923fee-735e-44fc-be27-a7d1efc37736) that made me realize that this was not the right fix. Indeed, `app/view` is the correct destination.

We could fix tailwindcss-rails similarly to this PR to fix the issue. I don't believe any other gem is relying on paths like `views/passwords/new.html.erb` anyways.

Alternatively we could revert this PR. After all, after reading the [Rails guides](https://guides.rubyonrails.org/generators.html#overriding-rails-generator-templates) about overriding templates, gems that need to override scaffold view templates [need](https://github.com/rails/rails/tree/main/railties/lib/rails/generators/erb/scaffold/templates) to use paths like `lib/templates/erb/scaffold/new.html.erb.tt` to override Rails's default `railties/lib/rails/generators/erb/scaffold/templates/new.html.erb.tt` path, and this path does not contain `app/views/` in it, so there is a precedent for templates paths not fully/necessarily matching destination paths.

What do you think @seanpdoyle? /cc @byroot

**Comment by seanpdoyle** [comment]
@jeromedalbert Thank you for catching this.

> there is a precedent for templates paths not fully and necessarily matching destination paths

I do not have the context necessary to weigh in here. I'm happy to revert https://github.com/rails/rails/pull/53098, but I've also opened https://github.com/rails/tailwindcss-rails/pull/407 and listed you as a co-author. I defer the ultimate decision to Core.

**Comment by byroot** [comment]
I'm not very well versed into this either, but seeing https://github.com/rails/tailwindcss-rails/pull/407 has been merged, seems like it's the way to go.

**Pull request merged**
