### PR TITLE
safe_constantize - Added Object scoped missing test cases

### PR DESCRIPTION
**Pull request by ronakjangir47**
For more details please see #15570

Closes #15570

### CODE REVIEW

**Comment by pixeltrix** [comment]
@ronakjangir47 was #15570 merged in another PR somewhere? Your tests are passing but it seems like they should fail according to the discussion in the ticket.

**Comment by ronakjangir47** [comment]
Hey @pixeltrix, @aditya-kapoor did some work long ago on this PR but seems like the code has been fixed but the test cases have not added till now for those cases.

**Comment by senny** [comment]
@ronakjangir47 is there a reason to add so many assertions which seem to showcase the same behavior over and over? Isn't it enough to add two cases as explored in #21274 ?

**Comment by ronakjangir47** [comment]
@senny  I removed those test cases which I thought are unnecessary.  Please have a look and let me know if anything

**Comment by senny** [comment]
@ronakjangir47 thank you :yellow_heart:

**Comment by ronakjangir47** [comment]
Thanks @senny

**Pull request merged**
