### PR TITLE
Update the "Configuring Rails Applications" guide [ci skip]

### PR DESCRIPTION
**Pull request by bogdanvlviv**
Add section "Results of `load_defaults`" to the guide.

<strike>
We should talk about the default values of configurations in
the context of a newly generated rails app on the specific version.
New rails apps are generated with config.load_defaults 6.0 in config/application.rb,
so `config.active_job.return_false_on_aborted_enqueue` is set to `true`.
Related to https://github.com/rails/rails/commit/884310fdd031ed8121944f9ea07c8b7723c4e6b6#r31819118, https://github.com/rails/rails/pull/33172#discussion_r196960655

Similar case https://github.com/rails/rails/commit/c8a22bb9eef2654c87a0fdb9139d868caf482ec0

Also, I think it isn't a good idea to talk about previous Rails versions
in the current guide since we use versions for guides and if users want to
know how something works on a previous version of Rails, they should read
the guides of the specific version.
</strike>

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Sorry but I disagree. We should talk about the default value of the configuration when no railtie code is applied. So the current documentation is correct. If we tell that the default is `true` for `config.action_controller.default_protect_from_forgery` and the user see that config being set to `true` in the application they will think it is safe to remove when it is not.

We could talk which configs are applied when the version defaults are set but each individual config should have its default value not depending on the `load_defaults` call.

Let's change this PR to specify the defaults in each rails version up to 6.0.

**Comment by bogdanvlviv** [comment]
> Let's change this PR to specify the defaults in each rails version up to 6.0.

@rafaelfranca Do you want me to apply this change only, right?:
```diff
diff --git a/guides/source/configuring.md b/guides/source/configuring.md
index 3b21197ae4..6bb5a1e03b 100644
--- a/guides/source/configuring.md
+++ b/guides/source/configuring.md
@@ -805,7 +805,7 @@ There are a few configuration options available in Active Support:

 * `config.active_job.custom_serializers` allows to set custom argument serializers. Defaults to `[]`.

-* `config.active_job.return_false_on_aborted_enqueue` change the return value of `#enqueue` to false instead of the job instance when the enqueuing is aborted. Defaults to `false`.
+* `config.active_job.return_false_on_aborted_enqueue` change the return value of `#enqueue` to false instead of the job instance when the enqueuing is aborted. Defaults to `false` up to Rails 6.0.
```

**Comment by rafaelfranca** [comment]
I'd prefer to remove those versions specifics from the config and add a new section like:

```
# Results of `load_defaults`

## With '6.0':

* `config.active_job.return_false_on_aborted_enqueue`: false
* `config.foo.bar`: true
```

**Comment by bogdanvlviv** [comment]
> Sorry but I disagree. We should talk about the default value of the configuration when no railtie code is applied. So the current documentation is correct. If we tell that the default is true for config.action_controller.default_protect_from_forgery and the user see that config being set to true in the application they will think it is safe to remove when it is not.

Thanks for the explanation, that’s a point.
> I'd prefer to remove those versions specifics from the config and add a new section like:

Good idea. I just amended this PR.

**Pull request merged**
