### PR TITLE
Remove the Amazon SES ingress

### PR DESCRIPTION
**Pull request by georgeclaghorn**
It's unusable (see #35704) and not ready to ship in Rails 6.0. We'll rewrite it for 6.1.

### CODE REVIEW

**Comment by omarish** [comment]
Hi @georgeclaghorn - any word as to whether SES ingress is going to be part of 6.1, or any future release? I ended up writing something as part of a rails project that added this support and would be happy to contribute/help if there's interest in re-adding SES support.

**Comment by georgeclaghorn** [comment]
I don’t have any immediate plans to work on it. PRs welcome.

**Comment by mullermp** [comment]
Hi @georgeclaghorn - I am on the AWS Ruby SDK team :) I actually didn't know this feature existed before! I was investigating implementing such a feature for use in [aws-sdk-rails](https://github.com/aws/aws-sdk-rails). I'm sad to see this was deleted, but I understand there were some underlying issues. In general, does the Rails team prefer to have AWS integrations directly into the Rails gem or through third party packages such as aws-sdk-rails? Some time last year, I created [this PR](https://github.com/rails/rails/pull/37409) to start moving functionality into the rails gem and out of our aws-sdk-rails gem, but there was some customer sentiment to not do so, and so I ended up closing the PR. In any case, we're happy to implement this one way or another.

@omarish I'm glad to see you were able to get SES ingress working! Do you have any code samples or design anywhere? We're happy to take official support of such a feature if you wanted to help get that started.

**Comment by omarish** [comment]
Hi @mullermp, absolutely. Here's roughly what I added for `app/controllers/action_mailbox/ingresses/amazon/inbound_emails_controller.rb`. I'll preface the code by saying this was a while back, so I'd treat this as prototype code at best:

```ruby
# frozen_string_literal: true

module ActionMailbox
  # Ingests inbound emails from Amazon's Simple Email Service (SES).
  #
  # Requires the full RFC 822 message in the +content+ parameter. Authenticates requests by validating their signatures.
  #
  # Returns:
  #
  # - <tt>204 No Content</tt> if an inbound email is successfully recorded and enqueued for routing to the appropriate mailbox
  # - <tt>401 Unauthorized</tt> if the request's signature could not be validated
  # - <tt>404 Not Found</tt> if Action Mailbox is not configured to accept inbound emails from SES
  # - <tt>422 Unprocessable Entity</tt> if the request is missing the required +content+ parameter
  # - <tt>500 Server Error</tt> if one of the Active Record database, the Active Storage service, or
  #   the Active Job backend is misconfigured or unavailable
  #
  # == Usage
  #
  # 1. Install the {aws-sdk-sns}[https://rubygems.org/gems/aws-sdk-sns] gem:
  #
  #        # Gemfile
  #        gem "aws-sdk-sns", ">= 1.9.0", require: false
  #
  # 2. Tell Action Mailbox to accept emails from SES:
  #
  #        # config/environments/production.rb
  #        config.action_mailbox.ingress = :amazon
  #
  # 3. {Configure SES}[https://docs.aws.amazon.com/ses/latest/DeveloperGuide/receiving-email-notifications.html]
  #    to deliver emails to your application via POST requests to +/rails/action_mailbox/amazon/inbound_emails+.
  #    If your application lived at <tt>https://example.com</tt>, you would specify the fully-qualified URL
  #    <tt>https://example.com/rails/action_mailbox/amazon/inbound_emails</tt>.
  class Ingresses::Amazon::InboundEmailsController < BaseController
    before_action :authenticate
    cattr_accessor :verifier

    def self.prepare
      self.verifier ||= begin
        Aws::SNS::MessageVerifier.new
      end
    end

    def create
      if @body["Type"] == "SubscriptionConfirmation"
        Faraday.get(@body["SubscribeURL"])
      elsif @body["notificationType"] == "Received"
        email = Base64.decode64(@body.dig("content"))
        ActionMailbox::InboundEmail.create_and_extract_message_id!(email)
      end
    end

    private

    def authenticate
      request.body.rewind
      @content = request.body.read
      verifier = Aws::SNS::MessageVerifier.new

      begin
        @body = JSON.parse(@content).with_indifferent_access
      rescue StandardError
        return head :bad_request
      end

      # return head :unauthorized unless verifier.authentic?(content)
    end
  end
end
```

**Comment by georgeclaghorn** [comment]
Hi @mullermp, happy to see AWS interest. :smile: There’s an ongoing effort to add this back in #39364 which I’m long overdue in reviewing. I’ll get to it when I can, but in the meantime, I’d appreciate if you could look it over.

**Comment by mullermp** [comment]
I would be happy to and I will definitely take a look soon! re:Invent is approaching and there's a lot to do on our side for the service teams.

quick question, do you know if the receiving email feature in SES needs to be enabled for it to work? If I recall, I need access to a domain to use that.

**Comment by bobf** [comment]
In case anybody stumbles across this PR - please feel free to add your support to this PR: https://github.com/rails/rails/pull/39364

I'm maintaining a separate gem for this but I would much rather this came as an included battery in Rails so people could get off the ground with SES integration more easily. Unfortunately  @georgeclaghorn is still overdue looking at the PR so, at this stage, I fear it may be a lost cause.

**Pull request merged**
