### PR TITLE
ActionCable client ensures subscribe command is confirmed.

### LINKED ISSUE #38668: ActionCable: Sporadically not receiving confirmation for (re)subscription to same channel
I've been playing around with ActionCable and ran into a strange phenomenon. From time to time, the js triggers depending on action cable would suddenly stop. In my setup, I create a subscription ( `consumer.subscriptions.create`) in a Stimulus controller during `Controller::connect()` and unsubscribe (`subscription.unsubscribe`) in `Controller::disconnect()`. One of the websocket messages reloads the page (via Turbolinks). Turbolinks replaces parts of the DOM, thus recreating the Stimulus controller, which in turn leads to the resubscription to the same channel.

After a long debugging session, I finally noticed that sometimes the subscription would not get confirmed. Turns out that resubscribing (i.e. unsubscribe quickly followed by subscribe) to the same channel sometimes results in the server not confirming the subscription. Screenshots from Chrome WS Messages in Network tab.

Normal behavior in (confirmation received):

image

Unexpected behavior (no confirmation received):

image

I digged deeper into the ActionCable source, added some debug messages and it seems that in those "subscription losing" cases the two messages get handled by different threads  at the same time, and the `subscribe` message gets handled before the `unsubscribe` message. This is problematic since https://github.com/rails/rails/blob/b2eb1d1c55a59fee1e6c4cba7030d8ceb524267c/actioncable/lib/action_cable/connection/subscriptions.rb#L31 is  preventing the creation of a new subscription, so the `subscribe` message is practically ignored. Meanwhile, a tiny bit later, the `unsubscribe` message will remove the only existing subscription. 

So this race condition leads to an unexpected "loss of subscription". And it seems that even the ~40ms delay between unsubscribe and subscribe (see previous screenshot) can cause such a loss in unfortunate circumstances. I encountered this on Rails 5.2.4 with the aforementioned Stimulus+Turbolinks setup, and recreated this issue in a fresh new Rails app with 6.0.2.1, using this [piece of code](https://gist.github.com/stevschmid/e2c8b9474535c1085c8a56ddad2276a2) to automatically resubscribe until `connected()` would not get called anymore (i.e. in case of lack of confirmation). Setting the `DELAY_RESUBSCRIBE` in the Gist example to `0` causes the problem to appear nearly instantly for me. But even with a value of `10`, such a loss occurs after a couple of minutes.

image

Culprit seems to be [this return](https://github.com/rails/rails/blob/b2eb1d1c55a59fee1e6c4cba7030d8ceb524267c/actioncable/lib/action_cable/connection/subscriptions.rb#L31), which according to blame has its origin in another race condition addressing PR #26547. Removing this line solves the issue for me, since `subscribe` simply creates a second subscription for the same channel, whereas the subsequent `unsubscribe` pops on of those, leaving me with one subscription. So in that case the order of the handling does not matter. I didn't have time yet to dig into PR #26547 and find out why that `return` is necessary. 

### Steps to reproduce

`unsubscribe` and quickly (re)`subscribe` to the same ActionCable channel. See [Gist](https://gist.github.com/stevschmid/e2c8b9474535c1085c8a56ddad2276a2) 

### Expected behavior

Resubscription is always confirmed

image

### Actual behavior

Resubscription is sporadically not getting confirmed

image

### System configuration
**Rails version**: Tested 5.2.4 and 6.0.2.1

**Ruby version**: ruby 2.6.1p33

### PR DESCRIPTION
**Pull request by spinosa**
### Summary

A SubscriptionGuarantor maintains a set of pending subscriptions,
resending the subscribe command unless and until the subscription
is confirmed or rejected by the server or cancelled client-side.

A race condition in the ActionCable server - where an unsubscribe
is sent, followed rapidly by a subscribe, but handled in the reverse
order - necessitates this enhancement.  Indeed, the subscriptions created
and torn down by Turbo Streams amplifies the existence of this race
condition.

### Other Information

The effects of the race condition have also been documented in https://github.com/rails/rails/issues/38668

Fixes #38668

### CODE REVIEW

**Comment by zzak** [comment]
@spinosa It seems CI is [failing](https://buildkite.com/rails/rails/builds/77171#e9eb0e33-2e6e-472a-89da-6e8333d441b7), can you take a look? :bow:

```

{
--
&nbsp; | "message": "TypeError: _this.subscriptions.subscribe is not a function\nat test/javascript/compiled/test.js:545:11\n\nretrySubscribing/this.retryTimeout&lt;/&lt;@test/javascript/compiled/test.js:545:11\nretrySubscribing/this.retryTimeout&lt;@test/javascript/compiled/test.js:543:9\n",
&nbsp; | "str": "TypeError: _this.subscriptions.subscribe is not a function\nat test/javascript/compiled/test.js:545:11\n\nretrySubscribing/this.retryTimeout&lt;/&lt;@test/javascript/compiled/test.js:545:11\nretrySubscribing/this.retryTimeout&lt;@test/javascript/compiled/test.js:543:9\n"
&nbsp; | }
```

**Comment by spinosa** [comment]
@zzak I can, and I will.

FWIW, the code works and I'm open to any comments.  I never stood up the Rails test suite and figured I'd come back to the tests if there was any other interest =)

**Comment by spinosa** [comment]
Updated PR with type checking to prevent the errors seen in CI.

Tests pass locally, but they always did.  They're not the same as the tests run in CI, where the JS test suite is executed on older browsers via saucelabs.

**Comment by spinosa** [comment]
@zzak CI still [failing](https://buildkite.com/rails/rails/builds/77852#0afcd7ce-1711-4517-bec7-d4cf5a053c91/2175), but apparently due to timeouts, and not in actionable..?

Please advise

**Comment by zzak** [comment]
@spinosa Yes, sorry I haven't had time to check on this recently.

Maybe doing a fresh rebase will help clear some of those up?

**Comment by spinosa** [comment]
@zzak Good call, buildkite CI passed this go around.

Waiting on the Linters to run w/ approval from maintainer...

**Comment by spinosa** [comment]
I'm happy to resolve the new conflicts if there's some hope of getting this merged.

@zzak can you help, or point me in a good direction?

Thanks!

**Comment by dhh** [comment]
I'd like to see this merged. Please do resolve conflicts and I'll help get this in. Thanks for working on it!

**Comment by dhh** [comment]
Awesome, @spinosa. Will get this validated in one of our apps.

**Review by jeremy — APPROVED** [review]
Nice work @spinosa!

**Comment by jeremy** [comment]
@spinosa Up for doing a backport to 6-1-stable as well?

**Pull request merged**
