### PR TITLE
[ci skip] Fix to `a, b and c` format

### PR DESCRIPTION
**Pull request by yui-knk**
I fixed `uninterpreted representations in HTML` by this https://github.com/rails/docrails/commit/f9015ada7e414a1a296499d5c92463016ba200ef

### CODE REVIEW

**Comment by robin850** [comment]
Thanks for the patch @yui-knk! Any reason to send the patch here instead of applying it to docrails directly ? If not, please push the change directly here ; the change is really subtle and if merge conflicts can be avoided, that's better!

Also please, try to gather related changes in the future to keep the history clean. Thanks for your nice documentation patches so far! :-)

**Comment by yui-knk** [comment]
@robin850 thanks for your review. I'm not sure if this PR is correct.
Before this PR
docs is

> ... replace the HTML input characters &, ", <, > by their ...

After this

> ... replace the HTML input characters &, ", < and > by their ...

I feel later is hard to read little :(
I can not infer `&, ", <, >` is intended or not, so I created PR to rails/rails.

By the way, is it better to update?

> 「&」, 「"」, 「<」 and 「>」...

I will push the change directly to docrails !

**Comment by yui-knk** [comment]
Pushed to docrails https://github.com/rails/docrails/commit/33a72824b8e355b5f2666816fb62573b5bebc1ae .

**Comment by robin850** [comment]
Thanks! :+1:

**Pull request closed without merging**
