### PR TITLE
Enable logging of remote IP addresses behind local proxies in the application log

### PR DESCRIPTION
**Pull request by ghost**
If Rails is behind a proxy server, the log will show the IP address of the proxy for each request, rather than the remote IP address. I feel that this information is rarely if ever useful.

My change makes the logger use request.remote_ip, which makes a smart guess at the remote IP address by considering CLIENT_IP / X_FORWARDED_FOR and checking against the list of trusted proxies.

### CODE REVIEW

**Comment by maclover7** [comment]
Can you add a test for this new behavior?

**Comment by norc** [comment]
Test added for the new behaviour.

**Comment by rafaelfranca** [comment]
@norc could you squash your commits?

**Comment by norc** [comment]
Done. Travis kept failing on 2 random builds (seems like some glitch), just wanted one clean pass before I squash back again.

**Comment by norc** [comment]
Any opinions on this?

**Comment by jeremy** [comment]
Moving the log tagging middleware means our exception handling middleware won't have log tags. No good.

We could move the RemoteIp middleware earlier instead, but we'd also need to ensure it's failure-safe.

**Comment by shaneog** [comment]
If this is going into 5.0.1 would it be possible to also include https://github.com/rails/rails/pull/15568?

**Comment by tinbka** [comment]
That's odd but even with this patch in place, having
```ruby
request.headers['HTTP_X_FORWARDED_FOR'] #=> "5.228.180.22, 172.68.11.61"
request.ip #=> "172.68.11.61"
request.remote_ip #=> "5.228.180.22"
```
The logger logs the request like
```
Started GET "/" for 172.68.11.61 at 2017-06-08 23:18:03 +0000
```

`172.64.0.0/13` is a trusted proxy range, so #remote_ip works.

Ruby 2.3.1 & Rails 5.0.3

I've taken a monkey patch from https://github.com/rails/rails/issues/5223#issuecomment-263778719 :   
```ruby
# config/application.rb
    config.middleware.insert_before(Rails::Rack::Logger,
                                      ActionDispatch::RemoteIp,
                                      true,
                                      config.action_dispatch.trusted_proxies)
# config/initializers/action_dispatch.rb
module TrustedProxyMonkeyPatch
  def ip
    @ip ||= (get_header("action_dispatch.remote_ip") || super).to_s
  end
end
ActionDispatch::Request.send :include, TrustedProxyMonkeyPatch
```

so now it works just as expected.

**Comment by jschneiderhan** [comment]
Looks like the `RemoteIp` middleware was moved earlier in https://github.com/rails/rails/pull/27515, so the only necessary change for this PR now is the `request.id` -> `request.remote_ip`

**Comment by rohitpbhore** [comment]
Please check if this can help
https://stackoverflow.com/questions/20124292/how-to-log-real-client-ip-in-rails-log-when-behind-proxy-like-nginx#51440551

**Comment by sikachu** [comment]
It's been 2 years since this PR was opened!

is this issue still exist on `master`? If so, would you mind rebase and leave only `logger.rb` and test changes in this PR?

**Comment by sikachu** [comment]
(alternatively, if someone would like to take this patch and reopen another PR with the changes and update it against master we can credit both you and the PROP 🙇)

**Pull request closed without merging**
