### PR TITLE
Move ApplicationCable::Channel section of readme

### PR DESCRIPTION
**Pull request by dkniffin**
I believe the paragraph starting with "This relies" belongs with the one above it.

### CODE REVIEW

**Comment by maclover7** [comment]
:+1: Thank you for your contribution!

**Comment by maclover7** [comment]
In the future, please append `[ci skip]` to any commits which only change documentation.

**Comment by dkniffin** [comment]
:+1: will do. sorry about that.

**Comment by maclover7** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
