### PR TITLE
Change wrong usage in documentation about autoload_paths [ci skip]

### PR DESCRIPTION
**Pull request by meinac**
We can't use this configuration outside of the application.rb

### CODE REVIEW

**Comment by kaspth** [comment]
Is that true, @fxn?

**Comment by meinac** [comment]
@kaspth you can try it by yourself. Just try to add new path to the autoload_paths in environment specific initialiser(it does not matter which environment you use) it will raise error while booting the application.

**Comment by zzak** [comment]
I believe this is because the paths get frozen after the app boots.

**Comment by meinac** [comment]
Yes, this is why we can't use it in environment specific initializer. Also freezing this makes sense because even if you change the autocad_paths it does not effect on the loaded paths.

**Pull request merged**
