### PR TITLE
Fixes a bug in the new application generator for --css bootstrap

### PR DESCRIPTION
**Pull request by Peredery**
When initializing an application without specifying the -j flag and with specifying --css bootstrap, esbuild should be used instead of importmap

### Motivation / Background

This Pull Request has been created because of this issue: https://github.com/rails/rails/issues/50671

### Detail

This Pull Request changes:

Fixes a bug in the new application generator.

When initializing an application without specifying the -j flag and with specifying --css bootstrap, esbuild should be used instead of importmap 

### Checklist

Before submitting the PR make sure the following are checked:

* [X] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [X] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [X] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by skipkayhil** [comment]
It looks like this basically reverts #47689

I think a better option would be to fix whatever is adding bootstrap to application.js so that its compatible with importmap.

**Comment by Peredery** [comment]
> It looks like this basically reverts #47689
> 
> I think a better option would be to fix whatever is adding bootstrap to application.js so that its compatible with importmap.

hmm it seems it was wrong to add this behavior with the bug in the first place, many of the guides have a 'rails new app --css bootstrap' settings because they were written over a year ago, at that time esbuild was enforced. 

As I understand the expected behavior should be:
If we specify only --css bootstrap we should add it via importmaps?

**Comment by skipkayhil** [comment]
> hmm it seems it was wrong to add this behavior with the bug in the first place, many of the guides have a `rails new app --css=bootstrap` settings because they were written over a year ago, at that time esbuild was enforced.

I'm not sure we can say for sure it wasn't working at that time. Since this process involves multiple libraries across two languages there are many things that could have broken it in the meantime.

> As I understand the expected behavior should be:
If we specify only --css bootstrap we should add it via importmaps?

:+1:

**Comment by skipkayhil** [comment]
> "./bin/importmap pin bootstrap" doesn't work for some reason, I don't understand if this is expected behavior or not? Also "./bin/importmap pin bootstrap-icons" but this is expected since it's a style set (?).

Is this happening inside an app or when trying to change the generator?

When I try running that in a freshly generated app it works:

```
$ bin/importmap pin bootstrap
Pinning "bootstrap" to vendor/javascript/bootstrap.js via download from https://ga.jspm.io/npm:bootstrap@5.3.2/dist/js/bootstrap.esm.js
Pinning "@popperjs/core" to vendor/javascript/@popperjs/core.js via download from https://ga.jspm.io/npm:@popperjs/core@2.11.8/lib/index.js
```

**Comment by Peredery** [comment]
> $ bin/importmap pin bootstrap

it's give me this error: https://github.com/rails/importmap-rails/issues/65#issue-1045881831

**Comment by Peredery** [comment]
It doesn't seem to be possible to do this through importmap. I found many tickets in importmap-rails that are related to bootstrap and the fact that it doesn't work out of the box. And also the fact that importmaps are only for JS, css/etc will not be loaded

Looks like there is only one is to use bootstrap gem (recently added the ability to use dartsass-rails this is in the master branch but not released yet) + dartsass-rails

**Pull request closed without merging**
