### PR TITLE
Allow any allowed host with port

### LINKED ISSUE #43870: Local development, puma-dev host no longer working after 6.0.4.2 + 6.0.4.3
### Steps to reproduce

1. `rails new _6.0.4.3_ host`
2. Add this line to `config/environments/development.rb`: config.hosts << "host.test"
3. Point `host.test` to `127.0.0.1` using your favourite method (ours is by using `puma-dev link .`)
4. Attempt to access `host.test`, or `host.test:3000`

### Expected behavior

Rails application loads successfully.

### Actual behavior

image

### System configuration

**Rails version**: 6.0.4.3
**Ruby version**: 2.7.something

### PR DESCRIPTION
**Pull request by rafaelfranca**
Allow any allowed host with port
    
All allowed host should be allowed if they are being accessed using a port.
    
Fixes #43870.

### CODE REVIEW

**Review by RaminDadou — COMMENTED** [review]
Host authorization

**Comment by radar** [comment]
@tenderlove this should be applied to the 6-0-stable branch too!

**Comment by rafaelfranca** [comment]
Right. I'll apply to all releases and make a new release as soon as https://github.com/rails/rails/pull/43882 is merged

**Comment by rafaelfranca** [comment]
6.0.4.4 and 6.1.4.4 were released with the fixes

**Comment by radar** [comment]
image

Looking good, thanks @rafaelfranca for your work :heart:

**Comment by jcrisp** [comment]
Thank you @rafaelfranca! Much appreciated. I can confirm it works beautifully on 6.1.4.4.

**Pull request merged**
