### PR TITLE
implement ActiveRecord-like attributes API for ActiveModel

### PR DESCRIPTION
**Pull request by Azdaroth**
Attributes API for ActiveRecord is absolutely great, I was wondering what would it take to make something similiar available for ActiveModel, so I wrote minimal implementation to handle the most essential features. Is it something that you think should be available in ActiveModel? If yes, should it be initially a minimal implementation that would evolve into something more sophisticated (that would mimic parts like ActiveRecord::Attribute) or should it be like that from the start? 

Let me know if this feature makes sense, will add some docs and Changelog note if it's something desired.

### CODE REVIEW

**Comment by Azdaroth** [comment]
@sgrif Thoughts?

**Comment by sgrif** [comment]
This is the direction that I'd eventually like to go, but I think this jumps the shark a bit, and the final Active Model integration needs to be a bit more... integrated. For example, I'd expect this API to properly interface with `ActiveModel::Dirty`, which probably requires deprecating the existing form of `ActiveModel::AttributeMethods` and `ActiveModel::AttributeAssignment` in favor of this one.

**Comment by Azdaroth** [comment]
@sgrif Yeah, it definitely makes sense to make it work properly with the rest of the parts of ActiveModel. So if it worked with `ActiveModel::Dirty` then this implementation would be just fine? How would you expect the interface to look like to be more integrated? Something like this?:

```
include ActiveModel::Dirty
attribute :name, :string

define_attribute_methods :name

def name=(val)
  name_will_change! unless val == @name
  # I guess this is the problematic part as this should assign deserialized value, not the passed value
  super
end
```

I would be happy to extend it, I think this feature is really awesome and plenty of people could benefit from it, if you could provide some more details how the integration would ideally look like and what else should be added here, it would be totally aweome. Thanks for looking into it!

**Comment by sgrif** [comment]
Basically the integration would mean moving most of the code from `ActiveRecord::Dirty` and `ActiveRecord::AttributeAssignment` up to active model. If you look at dirty in particular, there's a lot of duplication because I've been slowly in the process of pushing more behavior into `Attribute`, `AttributeSet`, and `MutationTracker`. Those changes haven't been able to live on active model though because `Attribute` and `AttributeSet` don't live there. So I would like to remove the setting of ivars entirely on Active Model, so that more of that behavior can be shared. It's especially tricky, because we need to go through some sort of deprecation cycle, but it's impossible to detect if someone is relying on the old behavior.

**Comment by Azdaroth** [comment]
Thanks for the overview. No idea for now how the deprecations could be handled nicely, but I'll check the logic in ActiveRecord and see what could be moved to ActiveModel.

**Comment by Azdaroth** [comment]
I should find some time next week to check it further, if anyone is interested in having it in the app, I've just released it as a gem: https://github.com/Azdaroth/active_model_attributes .

**Comment by sgrif** [comment]
Glad to hear it. As mentioned, I think the implementation internally will need to be a good bit more involved than that, but I think having that gem is an excellent idea in the short to medium term. I'm going to close this, as I don't think we'll be moving forward with this implementation internally, but I appreciate the work you've done, as well as packaging it as a gem.

**Comment by jrochkind** [comment]
I wrote something with some relation to this functionality, but specifically focused on embedding typed ActiveModel instances in a serialized json column in an ActiveRecord model -- including complex nested/compounded object graphs, basically a json(b) column as a simple document/object store.  

Currently an in progress experiment, but it seems to working out well -- thanks so much @sgrif for the excellent foundation in ActiveModel::Type and related API that made it feasible to keep going in the direction I did. 

https://github.com/jrochkind/json_attribute

I think it takes this idea closer to being something that could eventually be an internal implementation upstream here, although to keep myself sane I kept a focus on my specific use cases involving json serialization -- it was confusingly abstract enough even with that focus. But I think some of the pieces are in the right direction, if anyone's curious. 

Would love some peer-review/feedback (and what the name should be; I don't feel right using the 'active' prefix without it being a rails team effort, but there aren't a lot of good names left!

**Comment by jrochkind** [comment]
@sgrif has an attributes-typing API made it into ActiveModel in 5.2?

**Comment by kaspth** [comment]
@jrochkind this might be of interest https://github.com/rails/rails/pull/30985 😄

**Comment by jrochkind** [comment]
Thanks @kaspth that's exactly what I was looking for. Indeed in all 5.2.0 pre releases, which I check by looking at the github UI divorced from the PR: https://github.com/rails/rails/commit/c3675f50d2e59b7fc173d7b332860c4b1a24a726

**Pull request closed without merging**
