### PR TITLE
Support custom autocomplete for hidden fields

### PR DESCRIPTION
**Pull request by zzak**
See:

* https://github.com/rails/rails/issues/46405#issuecomment-1472365329
* https://github.com/rails/rails/pull/43280
* https://github.com/rails/rails/issues/46470

### CODE REVIEW

**Comment by byroot** [comment]
I'm not sure this is quite enough because some other helpers will call `hidden_field_tag` under the hood (might be mistaken, I haven't done much frontend work in a long time).

Perhaps a better solution would be a config option on `Action View`? If people care more about generation valid HTML than to avoid this Firefox bug, we can turn the workaround off globally.

**Comment by byroot** [comment]
But before doing that it would be best to try to reproduce on the latest firefox, perhaps the bug was fixed after all?

**Comment by brendon** [comment]
This does need fixing. Perhaps you could just use `reverse_merge` instead so that incoming options have priority in these cases?

**Comment by byroot** [comment]
Not intending on merging this anymore?

For the Firefox bug, apparently it's still a thing, so we probably ought to keep this work around for now.

**Comment by zzak** [comment]
> Not intending on merging this anymore?
> 
> For the Firefox bug, apparently it's still a thing, so we probably ought to keep this work around for now.

I thought it was fixed by #53512

**Pull request closed without merging**
