### PR TITLE
Add a new-line to the end of route method generated code.

### LINKED ISSUE #19316: 4.2.1.rc4: `route` generator action gobbles up trailing newline, breaks 3rd-party generators
**tl;dr –** In 4.2.1.rc4 `route "resources :people"` no longer appends a newline after the inserted route, which breaks the routes file. This breaks third-party generators like devise. It is a regression from 4.2.0 due to the fix for #15913.

--

Assuming a `routes.rb` that starts out like this:

```ruby
Rails.application.routes.draw do
  root 'welcome#index'
end
```

In Rails 4.2.0, `rails g scaffold foo` produces:

```ruby
Rails.application.routes.draw do
  resources :foos

  root 'welcome#index'
end
```

In Rails 4.2.1 (note the missing newline):

```ruby
Rails.application.routes.draw do
  resources :foos
  root 'welcome#index'
end
```

In terms of the scaffold generator, this is not a problem (the code still works, it is just whitespace that has changed). The reason the code works is because the scaffold generator includes an extra trailing newline when it calls the `route` generator action.

However, the [documentation](http://guides.rubyonrails.org/generators.html#route) for the `route` generator action does not specify that a trailing newline is necessary. The example given in the docs is:

```ruby
route "resources :people"
```

However in 4.2.1 this would produce:

```ruby
Rails.application.routes.draw do
  resources :people  root 'welcome#index'
end
```

No newline separates the new route from existing routes; this causes routing code to break.

This regression is due to the fix for #15913.

Due to the way Thor's `inject_into_file` works, I haven't been able to figure out a fix this regression without reintroducing #15913. My suggestion would be to revert the fix for #15913, since the regression will break third-party generators (I've verified that devise is broken).

### PR DESCRIPTION
**Pull request by arthurnn**
Fix regression on route method that was added by
bac812a7ef2660a2fe2ab00822e5e66228379822. The regression was that when
calling the `route` method, we were not appending a \n anymore.

[fixes #19316]

review @rafaelfranca @pixeltrix

### CODE REVIEW

**Comment by rafaelfranca** [comment]
:shipit:

**Comment by mattbrictson** [comment]
This fixes the bug, but it still means that there is a slight (inconsequential?) difference in behavior from 4.2.0. The scaffold generator used to add an extra newline; now it does not.

4.2.0 after running `rails g scaffold` for user and post:

```ruby
Rails.application.routes.draw do
  resources :users

  resources :posts

end
```

4.2.1:

```ruby
Rails.application.routes.draw do
  resources :users
  resources :posts
end
```

Again, this is just a whitespace difference. No big deal? (I think I actually prefer the new behavior.)

**Comment by sevenseacat** [comment]
:thumbsup:

**Comment by carlosantoniodasilva** [comment]
Sounds :+1:

**Comment by arthurnn** [comment]
Merged to master.
Backported to 4-2-stable: https://github.com/rails/rails/commit/ab4fa1fe4b8d0e6903a9264b047981882fe670d0
and 4-2-1: https://github.com/rails/rails/commit/b42f3fcd089677f0c99827cb79e0f583d36acf78

**Comment by pixeltrix** [comment]
Thanks for doing this @arthurnn - been slammed at work for the past few days

**Comment by arthurnn** [comment]
this was backported to 4-1-stable too https://github.com/rails/rails/commit/836d1fdbf88861fb9d57200227d032e7b86392cc , and it is on the 4.1.10 release.

@pixeltrix no worries bro.

**Pull request merged**
