### PR TITLE
TEXT and BLOB limit is byte length, not character length.

### PR DESCRIPTION
**Pull request by kamipo**
https://dev.mysql.com/doc/refman/5.6/en/storage-requirements.html

### CODE REVIEW

**Comment by jeremy** [comment]
+1. There are a handful of other spots where we refer to characters, also.

**Comment by rafaelfranca** [comment]
@kamipo could you take a look in the other spots?

**Comment by kamipo** [comment]
It looks like not found the other spots.

```
% git grep -n character lib/active_record/connection_adapters
lib/active_record/connection_adapters/abstract/quoting.rb:78:      # characters.
lib/active_record/connection_adapters/abstract/schema_definitions.rb:239:      #   Requests a maximum column length. This is number of characters for <tt>:string</tt> and
lib/active_record/connection_adapters/abstract/schema_statements.rb:731:      # +identifier+ is a 10 character long string which is deterministically generated from the
lib/active_record/connection_adapters/abstract/schema_statements.rb:979:          raise ArgumentError, "Index name '#{index_name}' on table '#{table_name}' is too long; the limit is #{max_index_length} characters"
lib/active_record/connection_adapters/abstract/schema_statements.rb:1078:          raise ArgumentError, "Index name '#{new_name}' on table '#{table_name}' is too long; the limit is #{allowed_index_name_length} characters"
lib/active_record/connection_adapters/abstract_mysql_adapter.rb:513:      # Returns the database character set.
lib/active_record/connection_adapters/abstract_mysql_adapter.rb:515:        show_variable 'character_set_database'
lib/active_record/connection_adapters/mysql_adapter.rb:226:          "select @@character_set_client",
lib/active_record/connection_adapters/postgresql/schema_statements.rb:426:            # cast the default to the columns type, which leaves us with a default like "default NULL::character varying".
lib/active_record/connection_adapters/postgresql_adapter.rb:80:        string:      { name: "character varying" },
lib/active_record/connection_adapters/postgresql_adapter.rb:665:        # connected server's characteristics.
lib/active_record/connection_adapters/sqlite3_adapter.rb:155:      # characters. The rest is used by rails internally to perform
```

`git grep -n character lib/active_record/` and `git grep -n character test/` are also.

**Comment by rafaelfranca** [comment]
:+1:

**Comment by jeremy** [comment]
These in particular:
```
lib/active_record/connection_adapters/abstract/schema_statements.rb
974:          raise ArgumentError, "Index name '#{index_name}' on table '#{table_name}' is too long; the limit is #{max_index_length} characters"
1073:          raise ArgumentError, "Index name '#{new_name}' on table '#{table_name}' is too long; the limit is #{allowed_index_name_length} characters"

lib/active_record/connection_adapters/abstract/schema_definitions.rb
239:      #   Requests a maximum column length. This is number of characters for <tt>:string</tt> and
```
They aren't MySQL-specific, but they are incorrect for MySQL.

**Comment by kamipo** [comment]
Indeed, the doc of the limit option in `abstract/schema_definitions.rb` is incorrect for MySQL.

    * <tt>:limit</tt> -
      Requests a maximum column length. This is number of characters for <tt>:string</tt> and
      <tt>:text</tt> columns and number of bytes for <tt>:binary</tt> and <tt>:integer</tt> columns.

But the error messages of index name length in `abstract/schema_statements.rb` is correct.

```ruby
if index_name.length > max_index_length
  raise ArgumentError, "Index name '#{index_name}' on table '#{table_name}' is too long; the limit is #{max_index_length} characters"
end
```

```ruby
if new_name.length > allowed_index_name_length
  raise ArgumentError, "Index name '#{new_name}' on table '#{table_name}' is too long; the limit is #{allowed_index_name_length} characters"
end
```

**Pull request merged**
