### PR TITLE
 Add RabbitMQ as pubsub adapter.

### PR DESCRIPTION
**Pull request by piecehealth**
### Summary

 Add RabbitMQ as pubsub adapter (actioncable/CHANGELOG.md)

### CODE REVIEW

**Comment by piecehealth** [comment]
Hi there,
I saw there are no RabbitMQ services available on test container with the default configuration, so the test failed.

May I know whether there is any correct RabbitMQ services configuration available for testing?

**Comment by piecehealth** [comment]
I also see `sneakers adapter test` (which is depended on RabbitMQ too) bypassed the CI test, could I bypass the CI test too?
https://github.com/rails/rails/blob/master/activejob/test/support/integration/adapters/sneakers.rb#L19-L23

**Comment by kaspth** [comment]
Thanks for working on this, I think the Redis and Postgres adapters are about what we want to ship built in for Action Cable. This is a fine fit for an actioncable-rabbitmq gem though. ✌️

**Comment by igorwiese** [comment]
Comment from GITHUB_TOKEN user

**Comment by igorwiese** [comment]
Comment from GITHUB_TOKEN user

**Comment by igorwiese** [comment]
Comment from GITHUB_TOKEN user

**Comment by igorwiese** [comment]
Comment from GITHUB_TOKEN user

**Comment by igorwiese** [comment]
Comment from GITHUB_TOKEN user

**Comment by igorwiese** [comment]
Comment from GITHUB_TOKEN user

**Comment by igorwiese** [comment]
Comment from GITHUB_TOKEN user

**Comment by igorwiese** [comment]
Comment from GITHUB_TOKEN user

**Comment by igorwiese** [comment]
Comment from GITHUB_TOKEN user

**Pull request closed without merging**
