### PR TITLE
Removed magic comments # encoding: utf-8 , since its default from ruby 2 onwards

### PR DESCRIPTION
**Pull request by vipulnsward**
Removed magic comments # encoding: utf-8 , since its default from ruby 2 onwards.
This is a cleanup of AM, to get feedback about this change, before cleaning up at all places

### CODE REVIEW

**Comment by chancancode** [comment]
Seems good! @rafaelfranca are you okay accepting this? (In one commit, for the rest of the project too)

**Comment by carlosantoniodasilva** [comment]
A single commit across the entire project sounds fine by me.

**Comment by jeremy** [comment]
Consider that people can change their default source encoding. Keeping the
magic comment ensures consistent behavior in any Ruby environment.

**Comment by rafaelfranca** [comment]
Agree. I think it is better to keep it.

**Comment by carlosantoniodasilva** [comment]
Thinking about that, I wonder if we don't have any places that might be
missing the magic comment and would blow up, then. :+1:

On Tue, Feb 3, 2015 at 11:18 AM, Rafael Mendonça França <
notifications@github.com> wrote:

> Agree. I think it is better to keep it.
>
> On Tue, Feb 3, 2015, 10:45 Jeremy Kemper <notifications@github.com>
> wrote:
>
> > Consider that people can change their default source encoding. Keeping
> the
> > magic comment ensures consistent behavior in any Ruby environment.
> > On Tue, Feb 3, 2015 at 02:36 Carlos Antonio da Silva <
> > notifications@github.com> wrote:
> >
> > > A single commit across the entire project sounds fine by me.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/rails/rails/pull/18795#issuecomment-72620201>.
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/rails/rails/pull/18795#issuecomment-72644253>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rails/rails/pull/18795#issuecomment-72648158>.
>



-- 
At.
Carlos Antonio

**Comment by simi** [comment]
Also I wonder if all current magic comments are needed.

**Comment by rafaelfranca** [comment]
We could review them, but is it worth?

**Comment by vipulnsward** [comment]
It would be hard to figure out whats required and whats not, there are more than 80+ occurrences of magic comments. As mentioned above this might blow up. The only places I can think about removing this is in our tests.

**Comment by carlosantoniodasilva** [comment]
Nope, imho, unless there's someone actually using another default source
encoding that ends up finding the issue.

On Tue, Feb 3, 2015 at 11:48 AM, Rafael Mendonça França <
notifications@github.com> wrote:

> We could review them, but is it worth?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rails/rails/pull/18795#issuecomment-72652605>.
>



-- 
At.
Carlos Antonio

**Comment by vipulnsward** [comment]
Let me know your thoughts about cleaning up tests. Else this issues is good to close.

**Comment by jeremy** [comment]
:+1: to remove from tests

**Comment by vipulnsward** [comment]
Updated to remove only from tests.

**Pull request merged**
