### PR TITLE
[WIP] Enum maps values to string in the database from symbol array

### PR DESCRIPTION
**Pull request by albertoalmagro**
### Summary

This PR implements the proposal discussed in Ruby on Rails: Core Google Group https://groups.google.com/forum/#!topic/rubyonrails-core/HfTKqlHTWz8

It allows you to map string enums directly from a symbol array in the following manner:
```ruby
class Book < ApplicationRecord
  enum cover: [ :hard, :soft ]
end

# book.update! cover: "hard"
book.hard!
book.hard? # => true
book.cover # => "hard"

# book.update! cover: "soft"
book.soft!
book.soft? # => true
book.cover # => "soft"

# book.cover = "hard"
book.cover = "hard"

book.cover = nil
book.cover.nil? # => true
book.cover      # => nil
```
 Of course you can also provide a hash to explicitly map the relation between attribute and database string:

```ruby
class Book < ApplicationRecord
   enum cover: { hard: "strong", soft: "weak" }
end
```

I hope you like it.

Thanks in advance for your reviews! ❤️

### CODE REVIEW

**Comment by albertoalmagro** [comment]
I set this to WIP as CI is failing, will check tomorrow.

**Comment by kamipo** [comment]
Duplicate of #32241.

**Comment by albertoalmagro** [comment]
@kamipo nobody told me anything when I opened the issue in the Rails Group and I didn't also see this, on the other side, it seems to be without work since months, shall I continue this?

**Comment by zinovyev** [comment]
@albertoalmagro I've added your documentation commit to my PR by cherry-picking it from your branch, so the commit message will still reference to your profile (hop' you don't mind). And I've also added your name as a contributor to my commit  message.

**Comment by albertoalmagro** [comment]
Great @zinovyev of course I don't mind, I didn't see your PR first, glad to see that you are continuing work there. @kamipo I will close this PR then.

**Pull request closed without merging**
