### PR TITLE
Added ActiveSupport::TimeZone#strptime.

### PR DESCRIPTION
**Pull request by pjungwir**
In Rails there is no easy way to parse a user-submitted date/time string,
interpreting it as from a given time zone (for instance from the user's preference).
This seems like a natural and common thing to do, and there are several StackOverflow questions about it (with flaky and/or wrong answers):

http://stackoverflow.com/questions/4262550/how-do-i-get-ruby-to-parse-time-as-if-it-were-in-a-different-time-zone

http://stackoverflow.com/questions/6615463/how-can-i-use-ruby-to-parse-a-time-as-though-it-is-in-a-time-zone-i-specify-wit

http://stackoverflow.com/questions/5074238/how-to-get-rails-to-interpret-a-time-as-being-in-a-specific-time-zone

First, some attempted answers. Suppose the user entered the string `2010-02-05 13:00:01` and has a time zone of `Eastern Time (US & Canada)`. This first attempt comes from StackOverflow, and can also be found suggested frequently elsewhere:

```
str = '2010-02-05 13:00:01'
tz = ActiveSupport::TimeZone['Eastern Time (US & Canada)']
ActiveSupport::TimeZone['UTC'].parse(str).in_time_zone(tz)
```

This fails because `in_time_zone` does not change the "instant" the time represents,
but the perspective on that instant.
In other words, the result is not 13:00:01 EST, but 8:00:01 EST
(which on Feb 5 is the same instant as 13:00:01 UTC).

Another suggestion is to append a time zone to the user-submitted string before parsing it,
e.g. `str += " PDT"`. But this is not great, because:
- You may not know whether or not the string already has a timezone abbreviation.
- The correct abbreviation may vary depending on time of year, e.g. PDT vs PST, and that requires first parsing the string.

One more suggestion is to say `Time.use_zone(tz) { Time.strptime(str, spec) }`,
but that is not effective because `use_zone` does not change the behavior of `Time.strptime`.

A final solution is to use `tz.parse` instead of `strptime`,
but you may not want a heuristic-based approach
and might need to parse the string according to a given format,
which requires `strptime`.

So this patch adds a `strptime` method to `TimeZone` objects,
which parses the given string as though it comes from the time zone
represented by the method receiver.
In other words `tz.strptime("1:00", "%H:%M")` means 1:00 in the timezone `tz`.
If the arguments contain an explicit timezone, e.g. with `%Z`,
then that is used instead,
and then the time is converted to the time zone of `tz`.
This is the same behavior as `TimeZone#parse`.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
cc @pixeltrix

**Comment by sgrif** [comment]
http://api.rubyonrails.org/classes/String.html#method-i-in_time_zone

```ruby
str = '2010-02-05 13:00:01'
tz = ActiveSupport::TimeZone['Eastern Time (US & Canada)']
str.in_time_zone(tz) # => Fri, 05 Feb 2010 13:00:01 EST -05:00
```

**Comment by sgrif** [comment]
Sorry, I misunderstood the issue. Please ignore me.

**Comment by pixeltrix** [comment]
@pjungwir Does this not do what you want?

``` irb
>> '2010-02-05 13:00:01'.in_time_zone('Eastern Time (US & Canada)')
=> Fri, 05 Feb 2010 13:00:01 EST -05:00
```

This even works with just time values, e.g:

```
>> '13:00:01'.in_time_zone('Eastern Time (US & Canada)')
=> Tue, 07 Apr 2015 13:00:01 EDT -04:00
```

**Comment by pixeltrix** [comment]
It also works with timezone information in the string:

```
>> '13:00:01 UTC'.in_time_zone('Eastern Time (US & Canada)')
=> Tue, 07 Apr 2015 09:00:01 EDT -04:00
```

**Comment by pjungwir** [comment]
Hi @pixeltrix, thanks for your question! I could also do your examples with `tz.parse(str)`, but this PR's idea is to accept a spec like `strptime` in case you need to parse strings that `#parse` can't figure out.

**Comment by pixeltrix** [comment]
@pjungwir in that case if you want custom formats then can you modify the PR to use `DateTime_strptime` to generate a hash and then extract the `parse` method behaviour into a private method and share it with `strptime` - how does that sound?

**Comment by pixeltrix** [comment]
@pjungwir are you able to make the change to the PR or do you want me to do it?

**Comment by pjungwir** [comment]
I'm traveling for the next week, so if you're able feel free. Otherwise
I'll do it when I'm back in front of a computer. Sorry for the delay!

**Comment by pjungwir** [comment]
@pixeltrix revisiting this I noticed my changes plus your refactor have been applied, so I think this PR can be closed, right?

**Comment by pixeltrix** [comment]
Yep, I pulled the branch and did it myself - closing. Thanks for your work @pjungwir

**Pull request closed without merging**
