### PR TITLE
[Docs] backport #47054 to 7-0-stable branch [ci-skip]

### PR DESCRIPTION
**Pull request by hachi8833**
### Motivation / Background

This Pull Request has been created because I think https://github.com/rails/rails/pull/47054 that has been merged to main branch deserves to backport to 7-0-stable branch as well.

cc: @zzak 

### Detail

This Pull Request just applies the update https://github.com/rails/rails/pull/47054 to 7-0-stable branch.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`

### CODE REVIEW

**Comment by hachi8833** [comment]
Looks like the following CI error comes from an unmatched setup for running `misspell` tool on 7-0-stable branch. 
(indeed, https://github.com/rails/rails/pull/47958 got no errors on main branch)
I'd be glad if someone'd look into it. 🙏

```
Run git ls-files --empty-directory | xargs ./misspell -i 'aircrafts,devels,invertions' -error
xargs: ./misspell: No such file or directory
Error: Process completed with exit code 127.
```

**Comment by skipkayhil** [comment]
Hey @hachi8833, can you use the steps outlined [here](https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#backporting) to backport the commit? This ensures the original author gets credit

**Comment by yahonda** [comment]
#47965 has been merged to the 7-0-stable branch. Then the next CI should not raise Lint-related errors.

please cherry-pick the merge commit so that the original author gets the credit as @skipkayhil suggested.

```
git cherry-pick -m1 f0ffc0b
```

**Comment by hachi8833** [comment]
Thank you for the suggestions!
I close this PR and retry.

**Pull request closed without merging**
