### PR TITLE
Update rails-html-sanitizer version to  v1.0.3

### PR DESCRIPTION
**Pull request by kelhusseiny**
rails-html-sanitizer 1.0.2 is vulnerable: https://groups.google.com/d/msg/rubyonrails-security/uh--W4TDwmI/m_CVZtdbFQAJ

### CODE REVIEW

**Comment by kaspth** [comment]
Thanks so much!

**Comment by rafaelfranca** [comment]
We don't need to change Rails. I'll revert this change.

**Comment by rafaelfranca** [comment]
Ee know 1.0.2 is vulnerable but doesn't make sense to have to release a new version of Rails because one of the gems it depends is vulnerable. It is application concern to make sure it is using the right version. 1.0.2 still work with Rails so we don't need to change the version requirement.

**Comment by kaspth** [comment]
Right, yes 👍

**Comment by Azzurrio** [comment]
@rafaelfranca So how can we update the `rails-html-sanitizer` version to `1.0.3` in the upcoming release of Rails?

**Comment by rafaelfranca** [comment]
There is no need to. It is the application responsibility to do it.

**Pull request merged**
