### PR TITLE
Enhance Named Scope documentation to specify, how we can begin scope method calls

### LINKED ISSUE #21943: Misleading documentation: "Class methods on your model are automatically available on scopes"
The documentation at http://apidock.com/rails/ActiveRecord/NamedScope/ClassMethods/scope states, near the bottom, that **"Class methods on your model are automatically available on scopes,"** and provides a couple examples.

While this technically works as written, it has one extremely subtle difference from previous versions of the same document, a deal-breaking difference that I think should be called out more clearly.

[v4.2.4 official doc](http://api.rubyonrails.org/classes/ActiveRecord/Scoping/Named/ClassMethods.html)

```
class Article < ActiveRecord::Base
  scope :published, -> { where(published: true) }
  scope :featured, -> { where(featured: true) }

  def self.latest_article
    order('published_at desc').first
  end

  def self.titles
    pluck(:title)
  end
end

Article.published.featured.latest_article
Article.featured.titles
```

vs [v3.1.0 unofficial apidock older version of doc](http://apidock.com/rails/v3.1.0/ActiveRecord/NamedScope/ClassMethods/scope) which is nearly identical except with `map(&:title)` instead of `pluck(:title)`.

This matters greatly, because although the feature descriptions are identical, if you attempt to use `map(&:title)` in **activerecord 4.1.4** you will receive the following error:

```
     NoMethodError:
       undefined method `map' for #<Class:0xb5535150>
```

Since every other aspect of this feature description is identical between versions, anyone reading both would reasonably assume that both `map(&:title)` and `pluck(:title)` are equally valid examples of the feature, and that both should work.

This may not have worked in Rails v3 either, judging from a StackOverflow post from [2 years ago for v3.1.3](http://stackoverflow.com/questions/14195591/how-did-the-class-method-call-on-activerecordrelation-takes-a-context).

In another StackOverflow post [more recently](http://stackoverflow.com/questions/31155085/rails-model-class-method-for-collection-of-objects), the same issue is seen again, although here a workaround is suggested -- **using `all.map(&:title)` instead of simple `map(&:title)` will make the chaining feature work as desired & documented.**

In my opinion, the next steps should be:
* update the current doc to call out this unexpected error when chaining with `map`, and to suggest the `all.map` workaround
* consider whether this `undefined method 'map'` error is desired, and whether this behavior itself should be fixed to work in the same manner that `pluck` does

### PR DESCRIPTION
**Pull request by vipulnsward**
Enhance Named Scope documentation to specify,we can begin scope method calls only using class methods, else it will raise an error

Fixes #21943

r? @rafaelfranca

### CODE REVIEW

**Comment by vipulnsward** [comment]
For reference, the original fix was done in https://github.com/rails/rails/issues/8804

**Comment by egilburg** [comment]
Is this recommended usage of `scope`? 

I thought semantically `scope` is recommended usage when the returned value is a Relation (and thus can be chained with other scopes and is not eagerly loaded making it safe to pass around whether it needs to run or not), while returning something other than a a Relation is better done is a class method.

**Comment by vipulnsward** [comment]
@egilburg true. In this case it documents a gotcha, if used this way.

**Comment by kaspth** [comment]
I think the existing documentation is sufficient when it says "Class methods are automatically made available for use" therein it implies that instance methods are not available. Thanks!

**Comment by vipulnsward** [comment]
@kaspth this was actually to address https://github.com/rails/rails/issues/21943

**Comment by vipulnsward** [comment]
I think if its sufficiently clear we can close - https://github.com/rails/rails/issues/21943

**Comment by kaspth** [comment]
Closed it, thanks!

**Pull request closed without merging**
