### PR TITLE
Update to TZInfo v2.0.0

### PR DESCRIPTION
**Pull request by philr**
I've just released [TZInfo v2.0.0](https://github.com/tzinfo/tzinfo/releases/tag/v2.0.0). The most significant change is that TZInfo now returns local times with the appropriate offset instead of always using UTC (for compatibility with older Ruby versions). The new version also swaps out the deprecated thread_safe dependency for concurrent-ruby.

This pull request updates the Active Support dependency to `~> 2.0`.

There are a few changes in TZInfo v2.0.0 that required modifications to Active Support:

* `TZInfo::TimezonePeriod#to_local` and `TZInfo::TimezonePeriod#to_utc` have been removed.
* `TZInfo::TimezoneOffset#abbreviation` and `TZInfo::TimezonePeriod#zone_identifier` now return strings instead of symbols.
* `TZInfo::Timezone.new` can no longer be used to lookup a time zone.
* `TZInfo::Timezone#period_for_local` will now return subclasses of `TZInfo::TimezonePeriod`.
* `TZInfo::Timezone#utc_to_local` will now return a `Time` with a non-zero `utc_offset`.

This pull request includes one change to the interface of `TimeZone`/`TimeWithZone`. `TimeZone#utc_to_local` will now return local times with the appropriate UTC offset (instead of returning local times as UTC). For example, before this change:

```ruby
zone = ActiveSupport::TimeZone["Eastern Time (US & Canada)"]
zone.utc_to_local(Time.utc(2000, 1))
#=> 1999-12-31 19:00:00 UTC
```

After this change:

```ruby
zone = ActiveSupport::TimeZone["Eastern Time (US & Canada)"]
zone.utc_to_local(Time.utc(2000, 1))
#=> 1999-12-31 19:00:00 -0500
```

### CODE REVIEW

**Comment by matthewd** [comment]
@pixeltrix how do you feel about us doing a hard bump here, forcing people to upgrade tzinfo at the same time as Rails itself?

My default is to lean away from that -- and prefer to have some version of the upstream library that works with both the Rails releases -- but here I think I'm inclined to assume most people won't be using it directly, and would thus be unaffected.

**Comment by pixeltrix** [comment]
@matthewd I think the dependency bump will probably be okay since as you point out most people won't have it as a direct dependency. However the `utc_to_local` change should really go through a deprecation since the return values are not the same time with a different offset but actually different UTC times. I think it's probably a case where we need to do a config that switches depending on whether it's a new or upgraded app - as much as I'm loathe to do that for something that's probably not used much at all.

On the plus side not having to drag in the thread_safe gem is a 👍

**Comment by ashmaroli** [comment]
@matthewd How about just relaxing the version constraint to allow tzinfo-2.0 if necessary..?
```diff
- s.add_dependency "tzinfo",  "~> 1.1"
+ s.add_dependency "tzinfo",  ">= 1.1.0", "< 3.0"

**Comment by jasl** [comment]
Any update here? It maybe the best chance before 6.0 released

**Comment by rafaelfranca** [comment]
There is no chance of this being in 6.0. It is already feature complete.

**Comment by AlexWayfer** [comment]
> There is no chance of this being in 6.0. It is already feature complete.

Is an updated dependency a feature?

**Comment by ashmaroli** [comment]
@AlexWayfer When the bump involves a change in the major-version, there's always *some breaking-changes*. In the case of `tzinfo-2.0`, there was a li'l more.
You may want to look at the broken CI in #35368 for insights.

**Comment by jaredbeck** [comment]
> .. the utc_to_local change should really go through a deprecation ..

So, 6.1 would deprecate and 6.2 would update `tzinfo`? Sounds good, want help with implementing the deprecation warning, Phil?

**Comment by philr** [comment]
@jaredbeck I think @pixeltrix was suggesting that tzinfo gets updated to v2, but that `TimeZone#utc_to_local` gets modified so that it behaves differently based on a configuration option. This would initially default to modifying the tzinfo v2 results to return local times as UTC (zero offset). In a future Rails release it could then be changed so the default is returning local times with the correct local offset directly from tzinfo.

I don't have the time to work on this at the moment, so I've got no problem if you or someone else wants to pick this up.

**Comment by AlexWayfer** [comment]
Oh no!

**Comment by anthonyhaussman** [comment]
Any news about it?

**Comment by kaspth** [comment]
Resolved in bf34c808f9

**Comment by kaspth** [comment]
Thanks for releasing 2.0 @philr, and bringing this to our attention. It took some rounds of review and changes, but I think we got it. Rails 6.1 ships with TZInfo 2.0 🙌

**Pull request closed without merging**
