### PR TITLE
Revert "Add config for validating migration timestamps"

### PR DESCRIPTION
**Pull request by adrianna-chang-shopify**
Reverts rails/rails#50205

Those changes break copied engine migrations, see https://github.com/rails/rails/pull/50205#issuecomment-1835416318.

We'll revisit adding validation to migration timestamps, but there are a couple of possible ways forward, so we'll revert for now, and add a regression test to cover the case of copied migrations.

Some possible options that @eileencodes and I discussed:
1) Validate only the year, month and date for a migration timestamp
2) Change the way migration copying works: rather than treating timestamps as integers and adding "1", add one second to the timestamp, so that we maintain valid timestamps on copied migrations. If we chose to do this, we should disable the config for existing applications, as we don't want existing applications with copied engine migrations to start encountering this error.

### CODE REVIEW

**Comment by fxn** [comment]
I believe `active_record.config.timestamped_migrations` and what @bensheldon reported is not consistent.

Wouldn't you think it is the number generator the one to be fixed? If `timestamped_migrations` is true, there is no way Rails should generate a prefix that is not a timestamp.

/cc @matthewd

**Comment by natematykiewicz** [comment]
> If we chose to do this, we should disable the config for existing applications, as we don't want existing applications with copied engine migrations to start encountering this error

The Strong Migrations Ruby gem has a `start_after` setting that takes an integer of a migration timestamp, so that the gem only validates the safety of migrations created going forward. Something like this could be a good way to enable validation going forward instead of just leaving many year old applications out of luck due to old migrations that are long since irrelevant as they've been live for years and will not be rolled back at this point.

https://github.com/ankane/strong_migrations#existing-migrations

**Comment by adrianna-chang-shopify** [comment]
> Wouldn't you think it is the number generator the one to be fixed? If timestamped_migrations is true, there is no way Rails should generate a prefix that is not a timestamp.

I think this is where @eileencodes and I had landed:
> Change the way migration copying works: rather than treating timestamps as integers and adding "1", add one second to the timestamp, so that we maintain valid timestamps on copied migrations.

@natematykiewicz ah, that's neat, thanks for linking that! That certainly seems beneficial for existing applications; otherwise, any app with an invalid migration is going to have to either delete that migration file (and the entry in the `schema_migrations` table) or opt out.

I'll start with a PR to ensure copied migrations maintain valid timestamps, and follow that up with a PR to bring timestamp validation back. I'll experiment with a `start_after` config too.

**Comment by natematykiewicz** [comment]
Awesome, I look forward to seeing what you come up with!

**Comment by fxn** [comment]
@adrianna-chang-shopify Maybe we have the same thing in mind, but let me elaborate just to make sure.

> Change the way migration copying works

That is too centered on one particular use case. I believe the approach is more fundamental: If `timestamped_migrations` is true, then Rails cannot generate invalid timestamps as prefixes.

Period. That is the root property to ensure it holds. The name clashing could come from copying migrations, or from a script that automates migration generation, or, .... Does not matter. If there is a name clash for whatever reason, the way to resolve it is to generate the next available valid timestamp.

**Comment by matthewd** [comment]
I guess I've never seen migration timestamps as being... timestamps. To me it's only a user-friendlier [and less conflict prone] way to generate a "next" value, without any further assumptions about value-reasonableness after generation.

In that vein, I see the `+ 1` leading into "invalid" times as a feature: it gives catch-up padding, allowing a series of generated migrations to avoid getting too far ahead of the current time (which would in turn cause more generations to need to use future times, which is a problem for user friendliness).

Is there value in ensuring that all migration numbers parse as valid times? If the risk is that a hand-edited timestamp might be "wrong", I would imagine that a typo that "validly" jumps the next-migration number into 2032 would be worse than one that claims to have been written on November 31st. I kinda feel like we'd better retain future date-ness by [optionally] rejecting any migration number that's greater than the number we'd generate for `7.days.from_now` or something.

(I don't have strong feelings about _not_ validating for valid dates... mostly I gently dislike it because it implies people can assume all migration stamps _are_ valid dates, which implies people can _parse_ them as valid dates, which will lead to people ascribing _meaning_ to those parsed values which I don't think is reasonable.)

**Comment by fxn** [comment]
@matthewd I have also that concern, manual editing can introduce valid timestamps too. So this may represent _some_ prevention, but just partial.

My remark goes under the assumption that this is something that is wanted (the patch was merged), but we think alike as in your last paragraph, really.

**Comment by adrianna-chang-shopify** [comment]
@fxn yes agreed that we'd need Rails to generate valid timestamps as prefixes any time it produces a migration (... if we decide on this approach). Engine migrations is an obvious example of behaviour that currently breaks that assumption, but if there are other places we ought to fix them too.

Ultimately though I think we're all on the same page -- manual editing of timestamps doesn't mean the timestamp is going to be invalid, so using timestamp validation as a way to dissuade manipulation isn't really foolproof 😕 @matthewd the two problematic types of edits we've seen are either a) a year / month that is in the future or that doesn't exist (e.g. we've seen `20232515151236`, `2025....`) or b) extra digits added to the timestamp (e.g. `2023111314533800` -- 16 instead of 14), which wouldn't pass the `7.days.from_now` test but would still end up being problematic because `Migration#current_version` uses `.max`.

Perhaps a middle ground is to validate YEAR / MONTH / DAY, and enforce a length of 14 digits? That way we could preserve the `+ 1` while still catching the hand-edit cases that are actually problematic...

**Comment by matthewd** [comment]
`2023111314533800` is [substantially] greater than `20231214151430`, so I think the 7 day check would still cover it.

That is, I'm suggesting that we generate the correct [14 digit] stamp for now+7, as an integer, then compare that to the value we're validating. I'm pretty sure that would make it impossible to accidentally forward-date a migration [by more than a few days, which is a potential inconvenience but no long term implications]. It'd still be possible to back-date a migration, including into a clearly non-date value, but I don't think that has any negative implications beyond looking odd -- it's only future values that cause trouble for future migration generation.

**Comment by adrianna-chang-shopify** [comment]
Ah, yep you're right. I'm happy with that, it's simple and covers all of the cases we care about. Likely we'll want to drop the regression test added in this PR as well, since we're no longer converting prefixes into real timestamps.

@matthewd do you feel strongly on opting for `7.days` over a smaller duration like `1.day`? The consequences of a migration dated 7 days in the future are limited, agreed, but a period of even `1.day` would still allow a large number of generated migrations to be dated into the future, while being a bit stricter in terms of what we allow.

**Comment by fxn** [comment]
> @fxn yes agreed that we'd need Rails to generate valid timestamps as prefixes any time it produces a migration (... if we decide on this approach). Engine migrations is an obvious example of behaviour that currently breaks that assumption, but if there are other places we ought to fix them too.

@adrianna-chang-shopify my idea was that we need to revise the method that generates next migration numbers. It does not matter why is it called.

**Comment by matthewd** [comment]
Nope; I originally reached for 7 days partly on a belief that migration timestamps used local time rather than UTC (implying that 25-ish hours of future would be expected even within "now"), but @eileencodes pointed out that's not the case while we were chatting earlier.

I'd still aim to give enough leeway that e.g. someone hand-crafting a timestamp and using local time wouldn't get an error, but one day seems fine for that. (And also sufficient to allow for an all-9s time, say, with the current date -- which I have no specific use case for, but seems like something someone might want to do to make a particular migration stand out, or something. 🤷🏻‍♂️)

**Comment by adrianna-chang-shopify** [comment]
@fxn Yep, I'm not disagreeing that we'd have (hypothetically) taken a general approach :) I was only using copying engine migrations as an example of existing behaviour that breaks the "timestamped_migrations produces valid timestamp prefixes" assumption, but obviously the solution would not be migration-copying nor engine specific.

Thanks Matthew, I'll get a PR up !

**Comment by matthewd** [comment]
> my idea was that we need to revise the method that generates next migration numbers. It does not matter why is it called

@fxn the `+ 1` is currently happening in the caller. If we were to change it, we _would_ need to consider each caller individually. (Though presumably unifying them into a suitably timestamp-aware incrementing method.)

https://github.com/rails/rails/blob/745992e93e5e0a308fcdb9dc0488396b7cd6475e/activerecord/lib/active_record/migration.rb#L1091


---

@adrianna-chang-shopify I think this existing behaviour is departing from my expectations in a way we might need to fix / might be the source of some of the inconsistency & difficulties currently created by wrongly-futureful migrations:

https://github.com/rails/rails/blob/745992e93e5e0a308fcdb9dc0488396b7cd6475e/activerecord/lib/active_record/migration.rb#L1120

(specifically the fact it's doing a string-based max rather than a numeric one)

... which actually sounds quite familiar. Ah: #43604. 😅

**Comment by fxn** [comment]
@matthewd exactly, I tried to reword my comment to avoid talking about the method, but did not succeed :). Just like you said, if the migration generator is supposed to generate timestamps as prefix, refactor as needed to make that happen.

**Comment by adrianna-chang-shopify** [comment]
> @fxn the + 1 is currently happening in the caller

Yeah, as an alternative I'd considered tweaking `ActiveRecord::Migration#next_migration_number` to handle wrapping at timestamp boundaries (e.g. have `20231201101060` wrap to `20231201101100`) to avoid having to touch the callers. This is easy to do since methods like `Time#strptime` can handle conversions around boundaries, but it does assume that the only values passed in to `next_migration_number` are valid timestamps OR timestamps at a boundary edge.

--- 

@matthewd I think that even though `#next_migration_number` is using a string-based max,[ `#current_version`](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/migration.rb#L1302-L1305) uses a numeric-based max (we had a similar issue to what Daniel described in https://github.com/rails/rails/pull/43604, but instead of new migration timestamps being created based off the wrong version, `db:rollback` was rolling back the wrong migration version because `current_version` was returning an older 15-digit migration). Makes sense to align these two, but seems like there will be issues no matter which way we go?

**Comment by adrianna-chang-shopify** [comment]
But maybe the answer is to always opt for numeric-based maxes, and push applications with existing problematic migrations to rename those migrations...

**Pull request merged**
