### PR TITLE
Mention JS Runtime dependency in dev dependencies guide [ci skip].

### PR DESCRIPTION
**Pull request by utilum**
Follows #27347 .

### CODE REVIEW

**Review by maclover7 — APPROVED** [review]
👍 seems reasonable

**Comment by maclover7** [comment]
:+1: Thank you for your contribution!

:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by utilum** [comment]
@maclover7 when do the edge guides get regenerated? I notice that several recent commits are in `/guides/source` but not in http://edgeguides.rubyonrails.org

**Comment by maclover7** [comment]
@utilum I believe they are regenerated on commits to Rails master, but I am not positive. @fxn would know better.

**Comment by utilum** [comment]
@maclover7 @fxn It seems that edge guides are not generated on commits to rails master. The last commit generated was f7d54c4247df39ee79de241b9f10f3b06ea0f565 from October 28.

**Comment by fxn** [comment]
@maclover7 is right, edge docs are generated after every push to master. There is a webhook that triggers that process.

But there was a stale lock file and that halted the generation. Lock files are removed in an `ensure` block, this may be caused by a machine crash of some sort. A last line of defense to prevent that [has been added](https://github.com/rails/rails-docs-server/commit/1e16e4891df82bc269b072597b8801dede9f879c) and the docs are up to date now.

Thanks for bring this to our attention @utilum.

**Comment by utilum** [comment]
@fxn I think the lock may have gone stale again

**Comment by fxn** [comment]
The site was not in sync, but locks were fine. `bundle install` was failing to update Nokogiri. For some mysterious reason it worked after upgrading Bundler. I see a number of issues in the repo of Nokogiri, not sure exactly which one we have hit, but in any case generation is back.

**Comment by utilum** [comment]
thank you, @fxn.

**Comment by gerrywastaken** [comment]
@fxn Is the build process for edgeguides public? There are merged changes that are now showing up, so I'm curious as to the cause. https://github.com/rails/rails/commit/c14da7be2216e59cca788f3c40843a91624b3762

**Comment by fxn** [comment]
@gerrywastaken you're right, last rendered commit was eb51286. Thanks for the ping, I'll have a look.

The generation of the guides and API is public. The tasks themselves are in the Rails repository, and the actual publication and server layout can be found in https://github.com/rails/rails-docs-server.

**Comment by eugeneius** [comment]
I don't believe the build output is public, but running `rake guides:generate` locally reproduced the problem in this case. I just fixed it in https://github.com/rails/rails/commit/c0ea4321b963970192f43a372906aa1fa8b85e72, and the edge guides have been generated successfully.

**Comment by gerrywastaken** [comment]
Ah man, my mistake! Thank you for fixing that @eugeneius!

**Comment by fxn** [comment]
This was fixed by c0ea4321b963970192f43a372906aa1fa8b85e72, and edge guides are up to date now.

**Pull request merged**
