### PR TITLE
MySQL 5.6  Fractional Seconds

### PR DESCRIPTION
**Pull request by arthurnn**
Adding microseconds support for mysql 5.6
This should not affect mysql 5.5 so IMO we dont need a version check.

this is PR #8240 + tests and Changelog entry.

review @rafaelfranca @jeremy @tenderlove

### CODE REVIEW

**Comment by MaxGabriel** [comment]
@jeremy This is breaking our tests on Rails 4.2 like how you described. An `INSERT` is done with `created_at` 2015-01-02 23:23:17.716890, then a `SELECT` is done for rows with `created_at BETWEEN '2014-12-26 23:23:17.829018' AND '2015-01-02 23:23:17.829087'`.

On paper this looks like it should work, but MySQL stores the 23:23:17.xxxxxx as 23:23:18, so the `SELECT` doesn't find the row that was just inserted.

We're on MySQL 5.6.16, but the column isn't set to store fractional seconds.

**Comment by rafaelfranca** [comment]
@MaxGabriel I believe I just fixed this issue. Could you check 4-2-stable?

**Comment by MaxGabriel** [comment]
@rafaelfranca That fixes it! Thanks very much :+1:

**Comment by arthurnn** [comment]
:heart:

**Comment by trobrock** [comment]
@rafaelfranca we are upgrading our app to 4.2.0 right now and are experiencing the issue that @MaxGabriel was seeing, our db doesnt store the microseconds, but the query generated looks like

```sql
SELECT `orders`.* FROM `orders` WHERE (`orders`.`charged_on` BETWEEN '2015-02-20 18:35:44.376956' AND '2015-02-20 18:35:44.376957')
```

which causes test failures for us.

**Comment by rafaelfranca** [comment]
@trobrock have you checked 4-2-stable?

**Comment by trobrock** [comment]
@rafaelfranca I saw your PR in the changelog at the 4.2.0 tag so I assumed it was in there, let me try the branch.

**Comment by trobrock** [comment]
@rafaelfranca looks like 4-2-stable fixed it, but according to this https://github.com/rails/rails/blob/v4.2.0/activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb#L77 the fix should be in 4.2.0 that is on rubygems correct?

**Comment by rafaelfranca** [comment]
Not really. The fix was in another place.

**Comment by trobrock** [comment]
@rafaelfranca ahh, do you have a link to that fix so I can track when it makes it to the gem? Until then I'll use 4-2-stable, thanks for the help.

**Comment by rafaelfranca** [comment]
No, I don't have it. It will make into the gem in 4.2.1

**Comment by miyagawa** [comment]
@trobrock i believe the fix is #14359 18067

**Comment by miyagawa** [comment]
@trobrock I believe the fix is #18067

**Comment by trobrock** [comment]
@rafaelfranca @miyagawa thanks for the help.

**Comment by sodabrew** [comment]
You will also need mysql2 gem >= 0.3.12 for DATETIME and >= 0.3.18 for TIME fields. (A bug in argument count caused us to fail to select milliseconds from a TIME field into Ruby Time object prior to the 0.3.18 release).
https://github.com/brianmario/mysql2/releases/tag/0.3.18

**Pull request merged**
