### PR TITLE
rails/application: allow passing an env to config_for

### PR DESCRIPTION
**Pull request by sirupsen**
Would make it easier to write tests to sanity check configuration files for other environments.

@rafaelfranca @byroot

### CODE REVIEW

**Comment by byroot** [comment]
:+1:

**Comment by rafaelfranca** [comment]
hmmmm, I has hoping to use the second argument as a default value when the config file is not found but I guess I can still use the block version for that. See https://groups.google.com/d/msg/rubyonrails-core/3kCxt2wr8XM/80K_54f8DAAJ.

**Comment by byroot** [comment]
Or maybe it could be a named argument?

**Comment by Sirupsen** [comment]
:+1: to named argument if those are used in Rails core now.

**Comment by rafaelfranca** [comment]
Yes, they are. :shipit:

**Comment by Sirupsen** [comment]
Updated to use a named argument

**Comment by rafaelfranca** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
