### PR TITLE
Add metadata value for presence of video channel in video blobs

### PR DESCRIPTION
**Pull request by brenogazzola**
### Summary
Complement to https://github.com/rails/rails/pull/42392
Related to https://github.com/rails/marcel/issues/57

While building video editing capabilities in our app, we've stumbled on a bit of an edge case. Android's voice recorder saves files as `m4a` but encodes with 3GP (ftyp3gp4), which is a container for both audio and video. Marcel recognizes it as video, and this ends up breaking our pipeline, which is expecting to be able to use video filters on any video file.

This PR adds `video` boolean entry to the video analyzer, to indicate whether the file has a video channel or not.

### Other Information
If you believe this PR makes sense, it might be better for me to close it and add the code to https://github.com/rails/rails/pull/42392. I've only separated it because I was not sure it would be approved.

While `audio` felt like a good key for presence/absence of audio channel, I'm not so sure about a `video` key in a video file. Might be better them to `video_channel` and `audio_channel` I think (or maybe `_stream`).

### CODE REVIEW

**Review by lfalcao — APPROVED** [review]

**Comment by rafaelfranca** [comment]
Hey @lfalcao. Why are you approving PRs in this repository?

**Comment by rafaelfranca** [comment]
@brenogazzola can you rebase this PR?

**Comment by lfalcao** [comment]
> Hey @lfalcao. Why are you approving PRs in this repository?

Hi, I thought that reviewing merges would help both core members and contributors. If that's not being helpful I stop, no problem :bow:

**Comment by rafaelfranca** [comment]
Ah, sorry, that is fine, it is actually why I asked. It is helpful but I could not distinguish between a real user activity and a bot activity.

**Comment by brenogazzola** [comment]
@rafaelfranca Done

**Review by zzak — APPROVED** [review]

**Review by pixeltrix — APPROVED** [review]

**Comment by pixeltrix** [comment]
@brenogazzola thanks 👍🏻

**Pull request merged**
