### PR TITLE
Fix links for the ActiveRecord readme [ci-skip]

### PR DESCRIPTION
**Pull request by laicuRoot**
### Motivation / Background

While I was reading the documentation of ActiveRecord I noticed that the links are not working.

### Detail

This PR addresses that issue and changes the links to the right page of the API documentation.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [ ] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Review by dorianmarie — COMMENTED** [review]
The `link:` protocol is supposed to link to the version on rails that is being read on the repo. But there is no helper to transform the `link:` into rails specific versions links.

So I think this is a good pull request, we might as well always link to the latest documentation

**Review by adrianna-chang-shopify — APPROVED** [review]

**Review by jonathanhefner — COMMENTED** [review]
Thank you for the pull request!  These links were actually meant to be viewed at api.rubyonrails.org and edgeapi.rubyonrails.org, not GitHub.  Relative URLs were used to allow the links to be properly versioned.

For example, the first "Learn more" link at https://api.rubyonrails.org/v7.0.0/files/activerecord/README_rdoc.html should point to https://api.rubyonrails.org/v7.0.0/classes/ActiveRecord/Base.html, not https://api.rubyonrails.org/classes/ActiveRecord/Base.html.

See https://guides.rubyonrails.org/v7.1/api_documentation_guidelines.html#links for more information.

However, I see how this can be surprising, so I submitted https://github.com/rails/sdoc/pull/345.  In the upcoming version of SDoc ([which Rails `main` now uses](https://github.com/rails/rails/commit/3cac3c3397d4dff6d25244b3bebc7e47aa3ddce6)), absolute URLs to `https://api.rubyonrails.org/` will be versioned as well.

As such, I have also submitted #50062, which converts the URLs for `activemodel/README.rdoc` (and fixes the [odd v6.1.0 URL in this PR](https://github.com/rails/rails/pull/49995/files#diff-9a767a4e05fa7c6f2ccfa3ceb15ad75674cd8ece0c8e137486d2fbc81d6698fdR160)).

Note, though, that `7-1-stable` still uses the old SDoc (and will for the foreseeable future), so I have reverted a9bc4ac8fe97b45868177e577eac61efb033f3a2 in e077025c86b4d20ac84298e3da708a32abc61adf.

**Comment by laicuRoot** [comment]
Hello @jonathanhefner, thank you for the explanation. That makes sense 👍

**Comment by adrianna-chang-shopify** [comment]
Ah, thanks @jonathanhefner ! ❤️ I'll make note of this for next time 🙇‍♀️

**Comment by jonathanhefner** [comment]
> although should that section in the API doc guidelines be changed now that we _do_ support versioning with `api.rubyonrails.org` URLS? (And that would be the preferred way going forward since it'll render in GitHub?)

I was on the fence about that.  I think `link:` is still the preferred way to write URLs in RDoc comments because it is more concise and because there is no benefit to using absolute URLs since such comments aren't rendered the way `README.rdoc` files are.  Ultimately, I don't think the `README.rdoc` files are edited often enough to add a caveat to that section.

**Pull request merged**
