### PR TITLE
Publish the Rails Testing Guide

### PR DESCRIPTION
**Pull request by zzak**
/cc @senny 

[Todo on basecamp](https://basecamp.com/1755757/projects/6741427/todos/145662327)

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Could you create a TODO list at the issue description to explain what is missing? This way other people can try to help.

**Comment by kirs** [comment]
@zzak @rafaelfranca I found few things in the guide I could improve, is it possible to get a commit right for `docrails`?

**Comment by zzak** [comment]
@kirs Can you submit a PR against this branch?

**Comment by dhh** [comment]
Reading this reminds me that `assert_template` is way too much of a "test the internals" kind of method. We should deprecate it. The same goes for `assigns(:whatever)`. That's akin to testing the internal ivars of models. You'd never want to use instance_var_get in a model test, why are we encouraging it in controllers?

Secondly, `assert_generates` and `assert_recognizes` are about testing the internals of the routing declaration. Doesn't make sense to me. Request the path through an integration test, verify the output.

`assert_redirected_to` should focus exclusively on named urls and polymorphic lookup. Not the parameter generation. We should deprecate that too.

**Comment by dhh** [comment]
The controller HTTP methods are also a prime candidate for kwargs. `post url, nil, { y: 'x' }` is just nasty. Rather go full explicit: `post url, params: { y: x }, session: { a: b }`.

**Comment by dhh** [comment]
Allowing you to test the flash and the session are actually also both internals. I don't think either are a good idea. Testing cookies is the only part that is a direct output of a controller, so we should focus just on that and kill the rest.

**Comment by dhh** [comment]
The `teardown` explanation should use a real case, lest people think that while it's not "necessary" it might be a good idea to nil-assign ivars (which of course is nonsense).

**Comment by kirs** [comment]
@zzak @rafaelfranca just added me to docrails team. It's pushed now :rocket:

**Comment by dhh** [comment]
We have an `assert_emails` helper to explain under functional testing of mailers.

**Comment by kirs** [comment]
> The controller HTTP methods are also a prime candidate for kwargs. 
@dhh @zzak done: https://github.com/rails/rails/pull/18323

**Comment by zzak** [comment]
@senny ping! how do you feel about this in its current state?

**Comment by senny** [comment]
@zzak This is going in the right direction. I haven't had the time to read through the whole guide. However while skimming it I don't think these points have been addressed:

> The section "Unit Testing your Models" talks about unit testing. The folder for model tests was renamed from "units" to "models" so I guess we should stick to the term "Model Testing".

> The section "Available Assertions" no longer lists all the assertions but refers to the Minitest documentation. I'd rather see this reverted to the full list of available assertions. While this is duplicating some docs, it's an invaluable resource for beginners. On top, we change all the `refute_X` methods to `assert_not` which certainly warrants that we document them as well.

> "Other popular testing approaches and plugins." should not be part of the "in this guide you'll learn" section. These are only a couple references at the bottom of the guide, which are not updated frequently. In my opinion they should not be the focus of this guide.

**Comment by kirs** [comment]
@senny what do you think about mentioning the new test runner in the guide? Is it too early?

**Comment by senny** [comment]
@kirs no, I don't think it's too early. The main interface of the test runner is pretty stable: `bin/rails test <file or directory>`. As we won't publish the guide before 5.0 it's good to start incorporating the runner.

**Comment by prakashmurthy** [comment]
I think this commit should be merged even while the document is being updated with the new information. 

Setting `work_in_progress: true`  only makes it not show up in the `Guides Index`, the page itself is still visible to the public. I've been finding the Rails Testing Guide page by googling for `rails testing`; I guess most other long timers are doing the same. 

Newcomers arriving at the testing page from the Guides Index too are likely to find value in the current content.

**Comment by kirs** [comment]
:+1: on @prakashmurthy's opinion

**Comment by rafaelfranca** [comment]
Work in progress guides are work in progress. Even it is still visible to the public we are explicit saying "This guide is Work in progress" if we remove it we are saying, "this guide is ready" and I don't think we should say that until it is really ready.

If our team think it is not ready yet, there is a reason. Maybe newcomers will find incorrect information there and got frustrated, or the information is right but missing a lot of explanation. I believe saying newcomers that the information is ready without being ready can be less helpful than hiding work in progress page from the index.

**Comment by prakashmurthy** [comment]
Thanks @rafaelfranca for the clarification. I did not see the `Work in progress` banner being displayed on the main page - http://guides.rubyonrails.org - for each of the documents undergoing change. 

Would it be a good idea to have a similar banner shown on the page itself? Right now there is nothing on http://guides.rubyonrails.org/testing.html that says it is a work in progress. 

If yes, I will work on a pull request for the change.

**Comment by rafaelfranca** [comment]
@prakashmurthy seems good to me.

**Comment by maclover7** [comment]
@zzak, do we still want to go ahead with this?

**Comment by vipulnsward** [comment]
I did a pass through the testing guide, most of the comments above seem to be addressed- better titles, Test Runner, etc.

:+1: for publishing, if there's anything missing please post here, so it can be taken care of for Rails 5.

**Comment by vipulnsward** [comment]
Whats missing now is testing Action Cable.

**Comment by connorshea** [comment]
@vipulnsward Is Testing Action Cable ready yet?

**Comment by jeremy** [comment]
Think we can publish this along with Rails 5.0 release?

We don't need to cover Action Cable since we don't have testing practices in place for it yet.

**Comment by vipulnsward** [comment]
We should go ahead and publish this targeted at 5.0.
With all the new changes that have made in, it makes sense to have it with the release.

**Comment by jeremy** [comment]
This needn't block 5.0.0 release candidate, but we will want it to coincide with 5.0 release. Removing milestone.

**Comment by vipulnsward** [comment]
http://guides.rubyonrails.org/testing.html 💚

**Pull request closed without merging**
