### PR TITLE
Make ActionDispatch::Resquest#xml_http_request? actually return a boolean.

### PR DESCRIPTION
**Pull request by lukelex**
This improves method naming and value parity convention

### CODE REVIEW

**Comment by matthewd** [comment]
Thanks, but that's not our documented convention.

**Comment by lukelex** [comment]
@matthewd can you link me to that section? I couldn't find any reference in the [Contributing to Rails](http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html) guide.

Thanks

**Comment by pixeltrix** [comment]
@lukelex we've had very thorough discussion of this before in #5329 - I don't think we need to re-visit it.

**Comment by matthewd** [comment]
http://guides.rubyonrails.org/api_documentation_guidelines.html#booleans

**Comment by lukelex** [comment]
@pixeltrix @matthewd Thanks :+1:

**Pull request closed without merging**
