### PR TITLE
Always discard mysql multi-statement results

### PR DESCRIPTION
**Pull request by jhawthorn**
We never want to connect or reconnect here, we just need to drop any results from a multi-statement query and that only makes sense to do on the same connection we'd already used for the query.

Previously when a query was run which hit the query cache on a fresh, non-sticky connection, the connection would perform its `verfiy!` before calling next_result, resulting in a network round trip.

https://gist.github.com/jhawthorn/a7210ff40d947b5f6c776045a2a8c59c

cc @byroot @matthewd

### CODE REVIEW

**Comment by byroot** [comment]
So that makes sense however:

  - Don't we have a race condition by re-acquiring the lock
  - Don't we have an issue with Async queries?

This makes me think we should instead pass some sort of parameter to `select`, so that it is the one that calls `next_result` with the lock etc.

**Comment by composerinteralia** [comment]
> which may or may not have its own async worries

Indeed https://github.com/rails/rails/commit/ec7f5a11932b10ccd5c18e4a53d99afdc7eaf867

**Comment by jhawthorn** [comment]
> Hmmm... is there actually any time we _wouldn't_ want to drain `more_results_exist?`/similar? 🤔

I can't find any, so let's try that as that solves both this and the two existing issues Jean points out.

**Review by byroot — APPROVED** [review]

**Comment by jhawthorn** [comment]
Backported to 7-2-stable as 229308da7d524ca7719374b6854995f61e114549

**Pull request merged**
