### PR TITLE
Handle the highest priority exceptions in the cause chain

### LINKED ISSUE #29739: Which is the proper order to handle exception.cause  in ActiveSupport::Rescuable#rescue_from ?
### Summary

Since Rails 5.0, the order in which handler is applied for exceptions including cause has been changed.
It looks like a deliberate change as written in the #25018 comment, but I think there are at least the following problems.

### Probrem

```ruby
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from StandardError, with: :handle_500
  rescue_from ActiveRecord::RecordNotFound, with: :handle_404

  private

  def handle_500(error)
    render 'errors/error', status: 500
  end

  def handle_404(error)
    render 'errors/error', status: 404
  end
end
```

```erb
<%= Article.find(10) %>
```

if Article with `id==10` does not exist, handle_ 404 was executed in Rails 4.2.8,
Since Rails 5.0.0, handle_ 500 is now executed.

Errors occurring in view are wrapped in ActionView::Template::Error.
In Rails 4.2.8, when error has cause, It looked for a handler that matched `exception.cause`.
For Rails 5.0.0 and later, the `exception.cause` check is done only if the wrapping error does not match any handler.

I think the behavior before 4.2.8 is preferable in the above case.

I know that shouldn't do `rescue_from StandardError` be listed in RailsGuide.
This may not be an appropriate example.
However, I think that we always encounter this problem when we need to reference cause and want to deal with special errors and generic errors in order.

### Solution
How about restoring the logic of #24158 to activesupport/lib/active_support/rescuable.rb ?

### System configuration
**Rails version**:
4.2.8, 5.0.0, 5.1.2

**Ruby version**:
2.3.1

### PR DESCRIPTION
**Pull request by rinmu**
Change to handle the highest priority exception in the exception cause chain.
`rescue_from` handler that are defined later have higher priority.
The priority does not depend on outside or inside of composition relation by `Exception#cause`.

Fixes #29739

### CODE REVIEW

**Comment by eileencodes** [comment]
cc/ @matthewd since you commented on the original issue.

**Review by matthewd — CHANGES_REQUESTED** [review]
As I stated in [my comment](https://github.com/rails/rails/issues/29739#issuecomment-319606824), the change was deliberate. 

I also described a change I think we should make. This is not that.

**Comment by rinmu** [comment]
@matthewd I'm sorry, I seem to misunderstood your comment.
I have understood that the change was intentional.

Does that mean that we should continue to put a patch like @TurtleKitty commented on #29739 in the future?
Or is there a way to solve our problem while keeping the change intention?
Unfortunately I have no idea.
If I got that suggestion, I will change this PR.

**Comment by matthewd** [comment]
> in the specific case of ActionView::Template::Error [..] we do want different something different:
> * If the application has explicitly defined a handler for ActionView::Template::Error, that should of course be invoked.
> * But otherwise, it should hit a specific handler inside the framework, which will unwrap and focus on the cause.

**Comment by rinmu** [comment]
Because the change contents are greatly different, I made another PR #30613.

**Pull request closed without merging**
