### PR TITLE
Use html-based edge badge instead of image

### PR DESCRIPTION
**Pull request by kerolloz**
### Summary

I used a simple HTML-and-CSS-based approach to achieve the look of the edge badge.

* Delete edge_badge.png
* Update layout.html.erb
* Update main.css

image

As you can see here when you zoom in, no more pixeled-image. 

image
 

### Other Information

If there are any issues with the colors, I can easily fix it.

### CODE REVIEW

**Comment by vipulnsward** [comment]
Might need visual changes, but this looks nice! Helps us to piggy-back and probably also visually display release based documentations like 6-0, 5-0, etc. or similar cc @fxn

**Comment by kerolloz** [comment]
Thank you @vipulnsward. Gread idea "displaying release based documentation info". Let me know what changes you would like to see.

**Comment by p8** [comment]
Nice! @kerolloz I think it's easier to get this merged if it looks more like the original. Color change discussions can be done later. Suggested changes:
- Keeping the banner red like the original (if possible with a gradient)
- Use a box-shadow for the banner to keep the floating look (for example: 2px 2px 2px 2px #1209096e)
- Use italic for the font.
- Use a text-shadow (for example: 2px 2px 4px #5400007d)

image

**Comment by kerolloz** [comment]
Thank you @p8! What do you think now?
I tried to use a simple gradient.
 image
(the HTML one is on the right)
image
image

**Comment by p8** [comment]
That looks very nice!

**Comment by fxn** [comment]
This is cool, thanks!

**Pull request merged**
