### PR TITLE
ActiveRecord::Querying::QUERYING_METHODS << :sample

### PR DESCRIPTION
**Pull request by thoran**
### Summary
`Model.sample` seems reasonable, since I am able to do `Model.pluck(:column_name)`, `Model.all.sample` and `Model.all.pluck(:column_name)`.  Filling in the gap of something which surprised me didn't work.

### CODE REVIEW

**Comment by katafrakt** [comment]
FWIW I would expect `Model.sample` to be much more efficient, without looking at the code. Getting all ids into an array and then sampling them will be bad for performance with few million of records and this cost will be hidden from the user. Getting random record from relational database is a pretty complex operation and depends on data that exists in the database, that's why it's probably wise to leave implementation to the programmer.

**Comment by rafaelfranca** [comment]
Thank you for the PR request. I see no production usage for this method so I prefer to not add.

**Comment by thoran** [comment]
I don't follow when you say that it should be much more efficient than what you haven't looked at. If rather you were meaning that it should adhere to a certain standard of efficiency, then OK. What standard is that?  I never claimed it would be efficient, but by virtue of the appearance of the method AR::Relation::Calculations#ids?, which I'd implemented nearly a decade ago for personal use, but never offered it up for inclusion for the very reason that it would suffer these kinds of criticisms. Hence, are we in fact arguing that we should be getting rid of AR::Relation::Calculations#ids?

**Comment by thoran** [comment]
Insofar as there being no "production usage", does this also mean that we should also be considering getting rid of AR::FinderMethods#forty_two?

**Comment by katafrakt** [comment]
> Hence, are we in fact arguing that we should be getting rid of AR::Relation::Calculations#ids?

I would like to see `.ids` gone, but no, we are not arguing about that.

With intention of `.ids` method ("give me all ids") it's clear what the cost is - if you have millions of records you'll get an array with millions of integers. With `.sample` the intention is "give me one random record" and it well hidden that intermediate array with millions of elements will be created. That is the difference.

**Pull request closed without merging**
