### PR TITLE
Fix autosave associations with validations added on `:base` of the associated objects

### LINKED ISSUE #48408: "base" included in errors.full_messages for autosave'd models
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :people, force: true do |t|
    t.text :name
  end

  create_table :pets do |t|
    t.text :name
    t.boolean :dog
    t.boolean :cat
    t.integer :person_id
  end
end

class Person < ActiveRecord::Base
  has_many :pets, autosave: true, dependent: :destroy
  validates :name, { presence: true }
end

class Pet < ActiveRecord::Base
  belongs_to :person
  validates :name, { presence: true }
  validate :not_both_dog_and_cat

  protected

  def not_both_dog_and_cat
    if dog? && cat?
      errors.add(:base, "must be either dog or cat")
    end
  end
end

class BugTest < Minitest::Test
  def test_base_error_message
    person = Person.new(name: 'John')
    person.pets.build(name: 'Paws', dog: true, cat: true)
    refute person.save
    assert_equal 1, person.errors.size
    error_message = person.errors.full_messages.first
    assert_equal "Pets must be either dog or cat", error_message
  end
end
```

### Expected behavior

`errors.full_messages` shouldn't include "base" in the error messages for `has_many autosave`'d relationships. Though I'm admittedly unsure what the message should be, the word "base" is an expression that holds meaning for the developer but not the user.

### Actual behavior

`errors.full_messages` returns things like "Pets base must be either dog or cat".

### System configuration
**Rails version**: 7.0.5

**Ruby version**: 3.0.4

### PR DESCRIPTION
**Pull request by fatkodima**
Fixes #48408.

### CODE REVIEW

**Comment by yahonda** [comment]
Backported to the 7-0-stable branch via https://github.com/rails/rails/commit/b809a6171ac1535b454d7a1a9522262ebf945cdd

**Comment by kamil-gwozdz** [comment]
Hi @fatkodima, I noticed that this changed caused the following behaviour and I'm not sure if that's a bug or a feature.

```ruby
class User
  has_one :avatar
end

class Avatar
  attr_attribute :file

  before_save :validate_file

  def validate_file
    errors.add(:base, "file not present") if file.nil?
  end
end

user = User.new(avatar: Avatar.new)
user.avatar.file = nil

refute integration.save
refute integration.valid?

# before your change this assertion would work
assert integration.errors[:"hook.base"].any?

# after that change `integration.errors[:"hook.base"]` is `nil` but and i have to use access my error via `[:hook]` instead
assert integration.errors[:hook].any?
```

**Comment by espen** [comment]
I can confirm this results in a breaking change when adding errors to base. I do not understand why this was changed and why expected behaviour should be not to return any explicitly set errors.

**Comment by rafaelfranca** [comment]
@espen before the message generated would be `Avatar Base File not present`. And the error would be a added to `user.errors[:"avatar.base"]`. That `base` should not be there. It is a mistake. The message should be `Avatar File not present` and the error should be in `user.errors[:"avatar"]`.

Those explicit set error are being returned, it is just that now they are in the correct place.

**Comment by espen** [comment]
True, but why should it be differently on the associated object than the core object? I couldn't find anything in the documentation. The docs however to specify an example of where base is returned:

```
attribute should be set to :base if the error is not directly associated with a single attribute.

person.errors.add(:base, :name_or_email_blank,
  message: "either name or email must be present")
person.errors.messages
# => {:base=>["either name or email must be present"]}
person.errors.details
# => {:base=>[{error: :name_or_email_blank}]}
```

**Comment by Edouard-chin** [comment]
👋 I think this changes introduced a small regression when using a custom I18n format:

<details>
<summary> Bug report </summary>

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", '7.0.6'
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

I18n.backend.store_translations(
  :en,
  activerecord: {
    errors: {
      models: {
        :"post/comments" => {
          format: "%{message}"
        }
      }
    }
  }
)

ActiveModel::Error.i18n_customize_full_message = true

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
    t.text :title
  end
end

class Post < ActiveRecord::Base
  has_many :comments, autosave: true
end

class Comment < ActiveRecord::Base
  belongs_to :post

  validate ->() { errors.add(:base, "Not allowed") }
  validate ->() { errors.add(:title, "Not allowed") }
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!
    post.comments << Comment.new

    assert_predicate(post, :invalid?)
    assert_equal(["Not allowed", "Not allowed"], post.errors.full_messages)
    # Assertion fails with ["Comments Not allowed", "Not allowed"]
  end
end

```
</details>

Related code is here https://github.com/rails/rails/blob/e18791c0bf2e03d3e6380f69b44e946564c6f873/activemodel/lib/active_model/error.rb#L23-L25

Previously the `namespace` would always be `post/comment` and the `attribute_name` would be `base`.

Now, the namespace changes depending on the attribute the error was set to. The namespace can either be `post/comment` or just `post`.

**Pull request merged**
