### PR TITLE
PostgreSQL, Fix change detection caused by superfluous bytea unescaping

### PR DESCRIPTION
**Pull request by larskanis**
and fix compatibility with pg-0.18.0.

This showed up when running BinaryTest#test_load_save with the more restrictive input string handling of pg-0.18.0.pre20141117110243.gem . It raises a `ArgumentError: string contains null byte` 

This also extends a test so that it shows this bug, independently of the pg version.

The same issue is present in 4.0 and 4.1 branch. It is solved in #17650, since that makes use of the ruby-pg en-/decoder capabilities.

### CODE REVIEW

**Comment by daniel-rikowski** [comment]
This also fixes a problem with serialized binary columns where the unnecessary unescaping could yield invalid YAML, i.e. serializing a string like `\/` was impossible before this patch.

I was about to create a bug report, but I noticed that it already had been fixed by 429d1bb 
This would have been my self-contained sample: http://git.io/mHvj8A

**Comment by jlecour** [comment]
Hi,

I have just upgraded Rails to `4.2.1` and pg to `0.18.1` but I still have the `ArgumentError: string contains null byte` error.

What can I provide to help figure out if I did something wrong or if another edge case is not fixed?

Thanks.

**Comment by larskanis** [comment]
@jlecour pg-0.18 added null byte checks at many other places for security reasons - not just at unescape_bytea. Could you please post your exception stack trace in a gist and some description of your use case?

**Comment by jlecour** [comment]
Here is a backtrace :

```
activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:602→ exec_prepared
activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:602→ block in exec_cache
activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:466→ block in log
activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20→ instrument
activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:460→ log
activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:601→ exec_cache
activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:585→ execute_and_clear
activerecord-4.2.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:173→ exec_delete
activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:114→ update
activerecord-4.2.0/lib/active_record/connection_adapters/abstract/query_cache.rb:14→ update
activerecord-4.2.0/lib/active_record/relation.rb:88→ _update_record
activerecord-4.2.0/lib/active_record/persistence.rb:512→ _update_record
activerecord-4.2.0/lib/active_record/locking/optimistic.rb:70→ _update_record
activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:123→ _update_record
activerecord-4.2.0/lib/active_record/callbacks.rb:310→ block in _update_record
activesupport-4.2.0/lib/active_support/callbacks.rb:88→ call
activesupport-4.2.0/lib/active_support/callbacks.rb:88→ _run_callbacks
activesupport-4.2.0/lib/active_support/callbacks.rb:734→ _run_update_callbacks
activerecord-4.2.0/lib/active_record/callbacks.rb:310→ _update_record
activerecord-4.2.0/lib/active_record/timestamp.rb:70→ _update_record
activerecord-4.2.0/lib/active_record/persistence.rb:501→ create_or_update
activerecord-4.2.0/lib/active_record/callbacks.rb:302→ block in create_or_update
activesupport-4.2.0/lib/active_support/callbacks.rb:117→ call
activesupport-4.2.0/lib/active_support/callbacks.rb:117→ call
activesupport-4.2.0/lib/active_support/callbacks.rb:169→ block in halting
activesupport-4.2.0/lib/active_support/callbacks.rb:169→ call
activesupport-4.2.0/lib/active_support/callbacks.rb:169→ block in halting
activesupport-4.2.0/lib/active_support/callbacks.rb:219→ call
activesupport-4.2.0/lib/active_support/callbacks.rb:219→ block in halting_and_conditional
activesupport-4.2.0/lib/active_support/callbacks.rb:92→ call
activesupport-4.2.0/lib/active_support/callbacks.rb:92→ _run_callbacks
activesupport-4.2.0/lib/active_support/callbacks.rb:734→ _run_save_callbacks
activerecord-4.2.0/lib/active_record/callbacks.rb:302→ create_or_update
activerecord-4.2.0/lib/active_record/persistence.rb:142→ save!
activerecord-4.2.0/lib/active_record/validations.rb:43→ save!
activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:29→ save!
activerecord-4.2.0/lib/active_record/transactions.rb:291→ block in save!
activerecord-4.2.0/lib/active_record/transactions.rb:347→ block in with_transaction_returning_status
activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:211→ transaction
activerecord-4.2.0/lib/active_record/transactions.rb:220→ transaction
activerecord-4.2.0/lib/active_record/transactions.rb:344→ with_transaction_returning_status
activerecord-4.2.0/lib/active_record/transactions.rb:291→ save!
activerecord-4.2.0/lib/active_record/persistence.rb:263→ block in update!
activerecord-4.2.0/lib/active_record/transactions.rb:347→ block in with_transaction_returning_status
activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213→ block in transaction
activerecord-4.2.0/lib/active_record/connection_adapters/abstract/transaction.rb:188→ within_new_transaction
activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213→ transaction
activerecord-4.2.0/lib/active_record/transactions.rb:220→ transaction
activerecord-4.2.0/lib/active_record/transactions.rb:344→ with_transaction_returning_status
activerecord-4.2.0/lib/active_record/persistence.rb:261→ update!
lib/tasks/import.rake:34→ block (4 levels) in <top (required)>
lib/tasks/import.rake:27→ each
lib/tasks/import.rake:27→ block (3 levels) in <top (required)>
mail-2.6.3/lib/mail/network/retriever_methods/imap.rb:130→ block in connection
mail-2.6.3/lib/mail/network/retriever_methods/imap.rb:165→ start
mail-2.6.3/lib/mail/network/retriever_methods/imap.rb:129→ connection
mail-2.6.3/lib/mail/mail.rb:191→ connection
lib/tasks/import.rake:20→ block (2 levels) in <top (required)>
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:240→ call
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:240→ block in execute
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:235→ each
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:235→ execute
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:179→ block in invoke_with_call_chain
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/monitor.rb:211→ mon_synchronize
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:172→ invoke_with_call_chain
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:165→ invoke
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:150→ invoke_task
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:106→ block (2 levels) in top_level
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:106→ each
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:106→ block in top_level
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:115→ run_with_threads
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:100→ top_level
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:78→ block in run
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:176→ standard_exception_handling
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:75→ run
/home/rails/.rbenv/versions/2.2.1/bin/rake:33→ <main>
```

**Comment by jlecour** [comment]
Here is a backtrace :

```
activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:602→ exec_prepared
activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:602→ block in exec_cache
activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:466→ block in log
activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20→ instrument
activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:460→ log
activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:601→ exec_cache
activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:585→ execute_and_clear
activerecord-4.2.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:173→ exec_delete
activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:114→ update
activerecord-4.2.0/lib/active_record/connection_adapters/abstract/query_cache.rb:14→ update
activerecord-4.2.0/lib/active_record/relation.rb:88→ _update_record
activerecord-4.2.0/lib/active_record/persistence.rb:512→ _update_record
activerecord-4.2.0/lib/active_record/locking/optimistic.rb:70→ _update_record
activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:123→ _update_record
activerecord-4.2.0/lib/active_record/callbacks.rb:310→ block in _update_record
activesupport-4.2.0/lib/active_support/callbacks.rb:88→ call
activesupport-4.2.0/lib/active_support/callbacks.rb:88→ _run_callbacks
activesupport-4.2.0/lib/active_support/callbacks.rb:734→ _run_update_callbacks
activerecord-4.2.0/lib/active_record/callbacks.rb:310→ _update_record
activerecord-4.2.0/lib/active_record/timestamp.rb:70→ _update_record
activerecord-4.2.0/lib/active_record/persistence.rb:501→ create_or_update
activerecord-4.2.0/lib/active_record/callbacks.rb:302→ block in create_or_update
activesupport-4.2.0/lib/active_support/callbacks.rb:117→ call
activesupport-4.2.0/lib/active_support/callbacks.rb:117→ call
activesupport-4.2.0/lib/active_support/callbacks.rb:169→ block in halting
activesupport-4.2.0/lib/active_support/callbacks.rb:169→ call
activesupport-4.2.0/lib/active_support/callbacks.rb:169→ block in halting
activesupport-4.2.0/lib/active_support/callbacks.rb:219→ call
activesupport-4.2.0/lib/active_support/callbacks.rb:219→ block in halting_and_conditional
activesupport-4.2.0/lib/active_support/callbacks.rb:92→ call
activesupport-4.2.0/lib/active_support/callbacks.rb:92→ _run_callbacks
activesupport-4.2.0/lib/active_support/callbacks.rb:734→ _run_save_callbacks
activerecord-4.2.0/lib/active_record/callbacks.rb:302→ create_or_update
activerecord-4.2.0/lib/active_record/persistence.rb:142→ save!
activerecord-4.2.0/lib/active_record/validations.rb:43→ save!
activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:29→ save!
activerecord-4.2.0/lib/active_record/transactions.rb:291→ block in save!
activerecord-4.2.0/lib/active_record/transactions.rb:347→ block in with_transaction_returning_status
activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:211→ transaction
activerecord-4.2.0/lib/active_record/transactions.rb:220→ transaction
activerecord-4.2.0/lib/active_record/transactions.rb:344→ with_transaction_returning_status
activerecord-4.2.0/lib/active_record/transactions.rb:291→ save!
activerecord-4.2.0/lib/active_record/persistence.rb:263→ block in update!
activerecord-4.2.0/lib/active_record/transactions.rb:347→ block in with_transaction_returning_status
activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213→ block in transaction
activerecord-4.2.0/lib/active_record/connection_adapters/abstract/transaction.rb:188→ within_new_transaction
activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213→ transaction
activerecord-4.2.0/lib/active_record/transactions.rb:220→ transaction
activerecord-4.2.0/lib/active_record/transactions.rb:344→ with_transaction_returning_status
activerecord-4.2.0/lib/active_record/persistence.rb:261→ update!
lib/tasks/import.rake:34→ block (4 levels) in <top (required)>
lib/tasks/import.rake:27→ each
lib/tasks/import.rake:27→ block (3 levels) in <top (required)>
mail-2.6.3/lib/mail/network/retriever_methods/imap.rb:130→ block in connection
mail-2.6.3/lib/mail/network/retriever_methods/imap.rb:165→ start
mail-2.6.3/lib/mail/network/retriever_methods/imap.rb:129→ connection
mail-2.6.3/lib/mail/mail.rb:191→ connection
lib/tasks/import.rake:20→ block (2 levels) in <top (required)>
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:240→ call
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:240→ block in execute
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:235→ each
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:235→ execute
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:179→ block in invoke_with_call_chain
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/monitor.rb:211→ mon_synchronize
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:172→ invoke_with_call_chain
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:165→ invoke
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:150→ invoke_task
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:106→ block (2 levels) in top_level
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:106→ each
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:106→ block in top_level
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:115→ run_with_threads
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:100→ top_level
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:78→ block in run
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:176→ standard_exception_handling
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:75→ run
/home/rails/.rbenv/versions/2.2.1/bin/rake:33→ <main>
```

**Comment by jlecour** [comment]
Here is a backtrace :

```
activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:602→ exec_prepared
activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:602→ block in exec_cache
activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:466→ block in log
activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20→ instrument
activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:460→ log
activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:601→ exec_cache
activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:585→ execute_and_clear
activerecord-4.2.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:173→ exec_delete
activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:114→ update
activerecord-4.2.0/lib/active_record/connection_adapters/abstract/query_cache.rb:14→ update
activerecord-4.2.0/lib/active_record/relation.rb:88→ _update_record
activerecord-4.2.0/lib/active_record/persistence.rb:512→ _update_record
activerecord-4.2.0/lib/active_record/locking/optimistic.rb:70→ _update_record
activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:123→ _update_record
activerecord-4.2.0/lib/active_record/callbacks.rb:310→ block in _update_record
activesupport-4.2.0/lib/active_support/callbacks.rb:88→ call
activesupport-4.2.0/lib/active_support/callbacks.rb:88→ _run_callbacks
activesupport-4.2.0/lib/active_support/callbacks.rb:734→ _run_update_callbacks
activerecord-4.2.0/lib/active_record/callbacks.rb:310→ _update_record
activerecord-4.2.0/lib/active_record/timestamp.rb:70→ _update_record
activerecord-4.2.0/lib/active_record/persistence.rb:501→ create_or_update
activerecord-4.2.0/lib/active_record/callbacks.rb:302→ block in create_or_update
activesupport-4.2.0/lib/active_support/callbacks.rb:117→ call
activesupport-4.2.0/lib/active_support/callbacks.rb:117→ call
activesupport-4.2.0/lib/active_support/callbacks.rb:169→ block in halting
activesupport-4.2.0/lib/active_support/callbacks.rb:169→ call
activesupport-4.2.0/lib/active_support/callbacks.rb:169→ block in halting
activesupport-4.2.0/lib/active_support/callbacks.rb:219→ call
activesupport-4.2.0/lib/active_support/callbacks.rb:219→ block in halting_and_conditional
activesupport-4.2.0/lib/active_support/callbacks.rb:92→ call
activesupport-4.2.0/lib/active_support/callbacks.rb:92→ _run_callbacks
activesupport-4.2.0/lib/active_support/callbacks.rb:734→ _run_save_callbacks
activerecord-4.2.0/lib/active_record/callbacks.rb:302→ create_or_update
activerecord-4.2.0/lib/active_record/persistence.rb:142→ save!
activerecord-4.2.0/lib/active_record/validations.rb:43→ save!
activerecord-4.2.0/lib/active_record/attribute_methods/dirty.rb:29→ save!
activerecord-4.2.0/lib/active_record/transactions.rb:291→ block in save!
activerecord-4.2.0/lib/active_record/transactions.rb:347→ block in with_transaction_returning_status
activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:211→ transaction
activerecord-4.2.0/lib/active_record/transactions.rb:220→ transaction
activerecord-4.2.0/lib/active_record/transactions.rb:344→ with_transaction_returning_status
activerecord-4.2.0/lib/active_record/transactions.rb:291→ save!
activerecord-4.2.0/lib/active_record/persistence.rb:263→ block in update!
activerecord-4.2.0/lib/active_record/transactions.rb:347→ block in with_transaction_returning_status
activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213→ block in transaction
activerecord-4.2.0/lib/active_record/connection_adapters/abstract/transaction.rb:188→ within_new_transaction
activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:213→ transaction
activerecord-4.2.0/lib/active_record/transactions.rb:220→ transaction
activerecord-4.2.0/lib/active_record/transactions.rb:344→ with_transaction_returning_status
activerecord-4.2.0/lib/active_record/persistence.rb:261→ update!
lib/tasks/import.rake:34→ block (4 levels) in <top (required)>
lib/tasks/import.rake:27→ each
lib/tasks/import.rake:27→ block (3 levels) in <top (required)>
mail-2.6.3/lib/mail/network/retriever_methods/imap.rb:130→ block in connection
mail-2.6.3/lib/mail/network/retriever_methods/imap.rb:165→ start
mail-2.6.3/lib/mail/network/retriever_methods/imap.rb:129→ connection
mail-2.6.3/lib/mail/mail.rb:191→ connection
lib/tasks/import.rake:20→ block (2 levels) in <top (required)>
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:240→ call
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:240→ block in execute
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:235→ each
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:235→ execute
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:179→ block in invoke_with_call_chain
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/monitor.rb:211→ mon_synchronize
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:172→ invoke_with_call_chain
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/task.rb:165→ invoke
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:150→ invoke_task
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:106→ block (2 levels) in top_level
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:106→ each
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:106→ block in top_level
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:115→ run_with_threads
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:100→ top_level
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:78→ block in run
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:176→ standard_exception_handling
/home/rails/.rbenv/versions/2.2.1/lib/ruby/2.2.0/rake/application.rb:75→ run
/home/rails/.rbenv/versions/2.2.1/bin/rake:33→ <main>
```

**Comment by matthewd** [comment]
@jlecour are you trying to store a null-byte-containing string into a bytea, or into some other (text / varchar) type? Because the above is the expected and correct behaviour for the latter.

**Comment by jlecour** [comment]
@matthewd There is definitely something wrong in my code.

I am storing email parts, and somehow I was trying to store some PNG binary in a `text` field, instead of the html part of the e-mail.

Thanks for the pointer.

**Comment by doviende** [comment]
For future reference, we ran into this on Rails 4.2.11 / pg 0.20, using a bytea column to store binary data. If we build a new object (with a null byte inside the binary field) and save, then `dup` will raise `ArgumentError` as mentioned above. During the dup, as it is trying to clear the timestamp fields, we notice that the attribute `value` and `value_before_type_cast` are both already unescaped and both strings, so the given fix of checking for `Type::Binary::Data` doesn't apply, and it tries to unescape a second time. Doing a `.reload` prevents the problem. Setting the `created_at` and `updated_at` to nil before duping also prevents the problem, at least in the specific case of dup.

adding this seems to fix it, by trying to detect whether the string is unescaped before sending it to unescape_bytea:
 
             return value.to_s if value.is_a?(Type::Binary::Data)
             return value unless value.slice(0,2) == "\\x"
             PGconn.unescape_bytea(super)

(not sure if that's the most general solution, and it doesn't address the cause of why the data is already unescaped, but I figured I'd convey the information for whoever may need it)

problem is gone in Rails 5+

**Pull request merged**
