### PR TITLE
Allow filtering of non-Global ID ActiveJob args

### PR DESCRIPTION
**Pull request by monfresh**
**Why**:
In some cases, a job might include sensitive information as one of the arguments, and there might not be an easy way to prevent those arguments from being passed.

For example, Devise sends the raw `reset_password_token` as an argument to their mailer. This results in the token being exposed in Active Job logs. Modifying the Devise code to prevent the token from being passed is not trivial.

**How**:
Provide an option to remove all non-Global ID arguments from the logs, by setting `Rails.application.config.active_job.log_all_arguments = false`.

When the option is set to `true` (default setting), the Active Job logs are formatted as they were before, i.e. all arguments are exposed. When set to `false`, all arguments that don't respond to `to_global_id` are removed. If the job is an `ActionMailer::DeliveryJob`, then the arguments also include the mailer class name, method, and `deliver_now`.

### CODE REVIEW

**Comment by jeremy** [comment]
Feels like a big hammer, out of proportion to the problem and the alternatives available. How about wrapping the Devise mailer in your own job instead of calling `#deliver_later` and relying on the default args passing? Or even doing a PR to Devise to grab sensitive info within the mailer rather than passing as args.

**Comment by aripollak** [comment]
IMHO it feels oddly specific for a problem that would crop up in many scenarios. For web requests there's a key blacklist, and it would be nice to have something similar here. If there's no way to programmatically get specific argument names in #perform, maybe you could turn off parameter logging for a particular job?

**Comment by dijonkitchen** [comment]
Is this still relevant or should it be closed? 

Specific parameters can be filtered in the logs already: http://guides.rubyonrails.org/action_controller_overview.html#log-filtering

It won't be a whitelist, but as @jeremy said, that might be too broad a use.

**Comment by flynfish** [comment]
@aripollak being able to turn off parameter logging for a particular job would be great, or even having a key blacklist similar to web requests. 

I wasn't aware of the automatic parameter logging until I was looking through them and noticed there is sensitive information being logged which I'd like to get rid of. As it currently is, I think I'm going to have to override the args_info method in an initializer which I really don't want to do.

**Comment by flynfish** [comment]
@dijonkitchen I did a test and it doesn't look like the log filtering works with active job:

```ruby
 TestWorker.perform_later(password: "123")
Enqueued TestWorker (Job ID: 3a5fea58-a4f0-40c8-bb55-99d631095cd3) to Resque(high_queue) with arguments: {:password=>"123"}
```

**Comment by rafaelfranca** [comment]
Closed by ce085f62d440534fada343e708d8864c0d55c03b. Thank you for the pull request

**Pull request closed without merging**
