### PR TITLE
use prepend instead of extending every instance

### PR DESCRIPTION
**Pull request by grosser**
initialize with prepend seems like a hack that was added before prepend was supported,
let's stop doing that ...

### CODE REVIEW

**Comment by grosser** [comment]
ok, should be green now ... had some random error ...

**Comment by kaspth** [comment]
Please add some more details to your commit message. Why can we safely replace the extend in initialize in with `prepend`, for instance?

**Comment by grosser** [comment]
better ?

**Comment by kaspth** [comment]
Way better, thanks 😁

**Pull request merged**
