### PR TITLE
Remove redundant assignment

### PR DESCRIPTION
**Pull request by ka8725**

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Thank you for the pull request but that assignment is not redundant. It is there to avoid race conditional when two threads are setting a pool for the same class.

**Comment by ka8725** [comment]
@rafaelfranca could you explain this magic? I tried to reproduce solving race conditions on simplified code with this approach and looks like it doesn't work: https://gist.github.com/ka8725/3a3673b23447deef15cf

I'm I wrong somewhere?

And it's interestingly that the removal of the line didn't break the tests. Lack of tests?

Thanks!

**Comment by thedarkone** [comment]
@rafaelfranca I think @ka8725 is correct here, that code shape looks to be a relic of @jonleighton's perf experiments while deciding between `fetch` and `[]=` in https://github.com/rails/rails/commit/e96558f8138d01ea64096f152f32c480af0861e6#diff-7735c67f539e7d1e2908a4d5d8909c24R568.

**Comment by ka8725** [comment]
Please don't merge it. I will try to simplify the code more.

**Comment by ka8725** [comment]
Interestingly the recursion's version is a little bit faster than `unit`. Tested in the [connection_handler_test.rb](https://github.com/rails/rails/blob/master/activerecord/test/cases/connection_adapters/connection_handler_test.rb) this way:

```ruby
def test_benchmark
  require 'benchmark/ips'
  Benchmark.ips do |x|
    x.report('until') { @handler.retrieve_connection_pool(@subklass) }
    x.report('recursion') { @handler.retrieve_connection_pool2(@subklass) }
  end
end
```
Results:

```
Calculating -------------------------------------
               until    46.527k i/100ms
           recursion    48.438k i/100ms
-------------------------------------------------
               until      1.201M (± 4.2%) i/s -      6.002M
           recursion      1.163M (± 3.6%) i/s -      5.813M
```

I know that recursion is not a good way to solve issues in Ruby. But here it looks much better and also faster.

**Comment by ka8725** [comment]
The comments are removed because they are not relevant more. We can't to use `fetch` in favor to `||=` and also the benchmark looks not [actual yet](https://gist.github.com/jonleighton/3552829#gistcomment-1660138).

**Comment by thedarkone** [comment]
@ka8725 not sure if your PR is going to be accepted as it is starting to devolve into "cosmetic change/refactor" territory.

I would like to point out that your benchmark is probably flawed and ends up measuring something irrelevant. The expected use case is that `retrieve_connection_pool(klass)` is to be called, lets say, 1 million times during application lifetime (before the app is restarted), and only the first call would be hitting the recursive or iterative section of the code you attempt to improve. The rest of the 999999 calls will only hit `class_to_pool[klass.name]`.

Are you sure that one 1 call in a million, when converted from a while loop to a recursive function, will result in a 5 % perf improvement?

Perhaps what you are measuring is:
```ruby
def foo
  @hash[:foo] ||= compute
end

def compute
  # lots of code
  baz
  baz
  baz
  baz
  baz
end
```

vs

```ruby
def bar
  @hash[:foo] ||= begin
    # lots of code
    baz
    baz
    baz
    baz
    baz
  end
end
```
?

**Comment by ka8725** [comment]
@thedarkone you are right. I agree with you 100%, the performance is not significant here. The main question is only in readability. And here every developer has his own preferences, somebody prefers recursion, somebody prefers loops. In my mind the code:

```ruby
def pool_for_class(klass)
  pool = pool_for(klass)

  return pool if pool
  return unless klass <= Base

  pool_for_class(klass.superclass)
end

class_to_pool[klass.name] ||= pool_for_class(klass)
```
looks more readable and clear than:

```ruby
class_to_pool[klass.name] ||= begin
  until pool = pool_for(klass)
    klass = klass.superclass
    break unless klass <= Base
  end

  pool
end
```

Besides of the readability Ruby complaints on the assignment in the conditional place:

```
~  ruby -e "until x = 1; end"
-e:1: warning: found = in conditional, should be ==
~  ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
```
But the decision is up to you accept it or not.

**Comment by matthewd** [comment]
> the performance is not significant here. The main question is only in readability

**Pull request closed without merging**
