### PR TITLE
Remove legacy default media=screen from stylesheet_link_tag

### LINKED ISSUE #41213: Remove legacy media=screen default from stylesheet_include_tag
Let's fix this:

```ruby
      # For historical reasons, the 'media' attribute will always be present and defaults
      # to "screen", so you must explicitly set it to "all" for the stylesheet(s) to
      # apply to all media types.

      #   stylesheet_link_tag "http://www.example.com/style.css"
      #   # => <link href="http://www.example.com/style.css" media="screen" rel="stylesheet" />
```

We can add a `config.assets.stylesheets.media_default`, or something like that, and have it default to "screen" for existing apps, but nothing for new apps. Then remove the media: "all" overwrite from the scaffold templates.

### PR DESCRIPTION
**Pull request by andrehjr**
### Summary 

If the media attribute is omitted, the default for web browsers is "all", meaning that by default links apply to all media.

Closes  #41213

Before:

```ruby
> stylesheet_link_tag "style"
=> <link href="/assets/style.css" media="screen" rel="stylesheet" />
```

After:

```ruby
> stylesheet_link_tag "style"
=> <link href="/assets/style.css" rel="stylesheet" />

```

The current behavior is not going to change for existing applications.

For new applications, the media attribute is not going to be added by default. Which can also be configured using the following:

```ruby
Rails.application.config.action_view.stylesheet_media_default = false|true
```

### Other Information

I've tried to update all references I could find, not sure If I missed something. I followed the implementation from other flags that did something close to this one. 

Additionally, on 2fafcd8 I also removed media=all from generators templates per instructions on the issue. I can move this to another PR if needed.

### CODE REVIEW

**Comment by dhh** [comment]
Great work @andrehjr 👏. I'll let @rafaelfranca take a quick look if anything is astray on the implementation side, but from my look, it's solid.

**Comment by dhh** [comment]
It's good with the change to the generators staying in this PR 👍

**Comment by glaszig** [comment]
how about `stylesheet_media_default` be an actual string value for the `media` attribute instead of just boolean?

**Comment by dhh** [comment]
Thought about that too but don’t want to encourage it’s use. This is a legacy accommodation. Not meant for ongoing use.

**Pull request merged**
