### PR TITLE
Update bundle binstub in application template

### PR DESCRIPTION
**Pull request by yhirano55**
### Summary

* Update bundle binstub that generated by `bundle binstub bundler` with bundler v1.16.1

### Refs

* https://github.com/bundler/bundler/pull/5878

cc / @rafaelfranca

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Not sure if we should have this file in the repository. How about calling the bundle command to generate? This way we always have updated code.

**Comment by yhirano55** [comment]
I see. Today, when I executed `bin/rails app:update`, I thought odd that bundle binstub (generated by `app:update`) is different from original binstub (generated by `bundle binstub`).

**Comment by yhirano55** [comment]
But this change may be not necessary. I'll close this. Thanks for the comment.

**Comment by rafaelfranca** [comment]
I think it is necessary. We should remove this binstub from the application template and call `bundle binstub bundle` when generating the app. Want to take a stab on fixing that?

**Comment by yhirano55** [comment]
Sure. I try to fix this, and open an another pull request. Thanks for your advices.

**Pull request closed without merging**
