### PR TITLE
Upgrade to Ruby 2.2.2

### PR DESCRIPTION
**Pull request by jonatack**
and fix the grammar in the ruby_version_check.rb user message.

### CODE REVIEW

**Comment by matthewd** [comment]
Err, why bump the dependency?

It's a security release, so there aren't many good reasons for someone to want to run 2.2.1... but we're not the Version Police. :-1:

**Comment by morgoth** [comment]
I believe this bump will be required for https://github.com/rails/rails/pull/19752

**Comment by kaspth** [comment]
@matthewd We've deprecated `alias_method_chain` in favor of prepend, but there was bug when calling super which means we wouldn't be able to follow through with the recommendation. So, we update the version.

**Comment by matthewd** [comment]
@kaspth that's why we required 2.2.1, not 2.2.2, though.. right?

**Comment by matthewd** [comment]
(or was that a different bug?)

**Comment by kaspth** [comment]
No, 2.2.1 caused a segmentation fault with some form of keyword arguments (right, @eileencodes?).

**Comment by eileencodes** [comment]
Yea 2.2.1 was causing a segmentation fault

**Comment by jonatack** [comment]
[http://svn.ruby-lang.org/repos/ruby/tags/v2_2_2/ChangeLog](http://svn.ruby-lang.org/repos/ruby/tags/v2_2_2/ChangeLog)

```
Mon Apr 13 00:16:32 2015  Nobuyoshi Nakada  <nobu@ruby-lang.org>
	* vm_eval.c (vm_call_super): search next super class from the
	  original class, to get rid of infinite recursion with
	  prepending.  a patch by Seiei Higa <hanachin AT gmail.com> at
	  [ruby-core:68434].  [ruby-core:68093] [Bug #10847]

Mon Apr 13 00:09:48 2015  Koichi Sasada  <ko1@atdot.net>
	* class.c (rb_prepend_module): need a WB for klass -> origin.
```

**Comment by jonatack** [comment]
[https://bugs.ruby-lang.org/issues/10847](https://bugs.ruby-lang.org/issues/10847)

**Comment by jonatack** [comment]
The bugfix appears have been backported to the `ruby_2_2` and `ruby_2_1` branches.

**Comment by matthewd** [comment]
:+1:, if we're actually depending on the newer version / about to depend on the newer version, this is fine. My issue was that the PR originally presented as "hey there's a new version, let's require it" with no justification / explanation.

**Pull request merged**
