### PR TITLE
Fix migration compatibility for default precision value on datetime columns

### PR DESCRIPTION
**Pull request by robertomiranda**
## Background

I have made a mistake on https://github.com/rails/rails/pull/42297, the definitions for add_column and column were put under the wrong class 
https://github.com/rails/rails/blob/246bac42a090524e5386912a4b955c327c6a4ba9/activerecord/lib/active_record/migration/compatibility.rb#L286-L335

As you can notice above they are in the V4_2 class when they should be in V6_1, in https://github.com/rails/rails/pull/42606/commits/9b9d9c7bf9437f498ac4e925de0594920cf4baa9 I could verify this by changing the versions of the migrations from 4.2 to 6.1, please the errors here  https://buildkite.com/rails/rails/builds/78711#d5c2b003-4552-4173-afc9-61e46d8b4fde

## Solution

Move the definitions to v6_1 and tweak V5_0 to add support older than 5.0 365acb6

cc @guilleiguaran @zzak @ghiculescu

### CODE REVIEW

**Comment by Tonkpils** [comment]
👋  @robertomiranda @guilleiguaran this seems to have broken some migrations in our application when using `create_table`

```ruby
class AddColumnWorks < ActiveRecord::Migration[4.2]
  def change
    add_column :my_table, :some_column, :datetime, default: -> { "NOW()" }, null: false
  end
end
```

works  but 

```ruby
class AddColumnWorks < ActiveRecord::Migration[4.2]
  def change
    create_table :my_table do |t|
      t.datetime :some_column, default: -> { "NOW()" }, null: false
    end
  end
end
```

fails with `Invalid default value for 'some_column'`

**Comment by robertomiranda** [comment]
@tonkpils interesting, it would be good a test case, which RDMS are you using?

**Comment by Tonkpils** [comment]
> which RDMS are you using?

mysql

**Comment by ghiculescu** [comment]
@Tonkpils is the issue specific to `ActiveRecord::Migration[4.2]` or does it happen on newer ones too?

**Comment by Tonkpils** [comment]
> is the issue specific to `ActiveRecord::Migration[4.2]` or does it happen on newer ones too?

looks like it's broken 4.2 and 5.0. 

6.1+ seems to fix the issue

**Comment by robertomiranda** [comment]
Looks like they are broken from 4.2 to 6.0 I'm working on a fix here https://github.com/rails/rails/pull/42606#issuecomment-869779286

**Comment by Tonkpils** [comment]
> Looks like they are broken from 4.2 to 6.0 I'm working on a fix here [#42606 (comment)](https://github.com/rails/rails/pull/42606#issuecomment-869779286)

For added context and in case it helps @robertomiranda , looks like the query generated when on this PR looks like

```
t.datetime :mycolumn, default: -> { "NOW()" }
`mycolumn` datetime(6) DEFAULT NOW()
```
because the precision is added (not sure how), the `NOW()` default would require this same precision. I'm not sure if the same is true when using `default: Time.now`

**Comment by robertomiranda** [comment]
> because the precision is added (not sure how), the NOW() default would require this same precision. I'm not sure if the same is true when using default: Time.now

In theory the `compatibility.rb` should prevent the introduction of this behaviour to Rails version previous to 7.0

**Pull request merged**
