### PR TITLE
`restrict_with_error` message will now respect owner’s human name 

### PR DESCRIPTION
**Pull request by ronakjangir47**
in any locale. [kuboon & Ronak Jangir]
Closes #10787

### CODE REVIEW

**Comment by senny** [comment]
@ronakjangir47 since this is based on previous work we should give credits to the original author as well. You can do so by adding `[kuboon & Ronak Jangir]` to the commit message.

**Comment by ronakjangir47** [comment]
@senny Updated commit message. Thanks for tip will keep in mind in future.

**Comment by kuboon** [comment]
@ronakjangir47 thanks a lot!

**Comment by senny** [comment]
@ronakjangir47 @kuboon thank you :yellow_heart:

**Pull request merged**
