### PR TITLE
Raises NameError exception on invalid attribute name when using #alias_attribute

### PR DESCRIPTION
**Pull request by eliasjpr**
### Summary

Currently #alias_attribute does not raise a NameError exception when creating attributes with invalid name.
- [x]  Added one public method called `#valid_attribute?(attr_name)` that takes a attribute name 
  and validates it against regular expression match valid ruby variables names. 
- [x]  Added `#invalid_attribute(attr_name, stack)` that raises a NameError for the passed in
  attribute when called.
- [x]  Added a line on the `#alias_attribute` method that checks if the `new_name` is a valid name attribute.
### Other Information

Gist with test case https://gist.github.com/eliasjpr/905a9ece5534cac57b90
Issue https://github.com/rails/rails/issues/24208
### Example

**Example**

``` Ruby
class Widget
  attr_accessor :active
  alias_attribute :active?, :active
end

# Output
# => syntax error, unexpected '?', expecting ';' or '\n'
#    def active??; self.active?; end
```

Should raise NameError as #attr_accessor would do.

**Expected**

``` Ruby
class Widget
  attr_accessor :active?
end

# Output
# => NameError: invalid attribute name `active?'
```

### CODE REVIEW

**Comment by kaspth** [comment]
Which version did you see that error? Far as I can tell on master we're taking some care here: https://github.com/eliasjpr/rails/blob/67ce41f26d0cab37a3a299ee65488ad84cbe12f6/activemodel/lib/active_model/attribute_methods.rb#L373

**Comment by georgemillo** [comment]
@kaspth I can't speak for @eliasjpr, but in my original issue which sparked this PR (#24208), I was using 5.0.0.beta3

**Comment by eliasjpr** [comment]
@kaspth @georgemillo are you guys happy with the addition. Is there anything stylistic, code, or performance wise that I should change?

**Comment by georgemillo** [comment]
No objections from from me, but I'm just a nobody, one of the Rails team should chime in ;)

**Comment by kaspth** [comment]
Veering into too defensive for my taste. `alias_attribute` relies on Rails (albeit a bit implicit) convention of an attribute consisting of a reader, writer and predicate method. So checking that the method name wasn't written as a predicate betrays that.

Happy to reconsider, but that's my current opinion. Thanks! :heart:

**Comment by georgemillo** [comment]
> So checking that the method name wasn't written as a predicate betrays that.

The point is that `alias_attribute` *already* raises an error if you pass it a predicate method. All this PR does is make the error more helpful - as I described in my original issue, it makes no sense for a line like `alias_attribute :something?, :something` to raise a SyntaxError when it's perfectly valid Ruby syntax.

I wasted a lot of time when I originally came across this error and I think this small PR could potentially save other people a lot of headaches.

**Pull request closed without merging**
