### PR TITLE
Hide test_unit generators when using other test framework

### PR DESCRIPTION
**Pull request by eval**
### Motivation / Background

When using test_unit and running `rails generate`, then the following test_unit generators show:

```
TestUnit:
  test_unit:authentication
  test_unit:channel
  test_unit:generator
  test_unit:mailbox
  test_unit:plugin
 ```

When using another framework (rspec, minitest), even more test_unit generators are visible:

```
TestUnit:
  test_unit:authentication
  test_unit:channel
  test_unit:controller
  test_unit:generator
  test_unit:helper
  test_unit:integration
  test_unit:job
  test_unit:mailbox
  test_unit:mailer
  test_unit:model
  test_unit:plugin
  test_unit:scaffold
  test_unit:system 
```

This PR hides all of test_unit for the latter case.

### Checklist

Before submitting the PR make sure the following are checked:

* [X] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [X] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [X] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by eval** [comment]
Any thoughts on this one @byroot @kamipo ? Seems an easy way to prevent confusion when seeing what generators are available.

**Comment by zzak** [comment]
I think #52238 proposed to remove these all together. /cc @skipkayhil

**Comment by eval** [comment]
Thanks for looking into this @zzak Is the other PR not just concerned with removing the `test_unit:plugin` generator?

**Comment by zzak** [comment]
@eval Hey, sorry for the wait.

> just concerned with removing the test_unit:plugin generator

Yes, sorry that was my misunderstanding.

I was able to pair with @skipkayhil last week and we discussed this, so I just want to add some notes from our discussion.

First, we found 743d77f405a16cd1cf1d4bbccd6b512463e10a43 which seems to confirm that these generators are not meant to be shown in the help.

However, we are seeking feedback on what the team currently thinks about this but for now it seems like your proposed patch restores this behavior and that seems good.

We talked about wanting test coverage for this, and to help prevent future updates introduce regressions -- and I've opened #53586.

It is weird that all you have to do is add `rspec-rails` to your Gemfile to observe the extra `test_unit` generators being added to the help. I'm also currently thinking that if you do install a gem which changes the `test_framework` that you don't want to see the generators for the default in help.

**Comment by eval** [comment]
Thanks @zzak for the update.

I came across the same commits while digging through the Git history to create this PR. It confirmed that I've been indeed seeing this since forever in my (rspec) Rails apps when running `rails g` (meanwhile always thinking it was a misconfiguration on my part... :)

It is possible though to solve it using some config:
```ruby
# config/application.rb

    config.generators do |g|
      g.hide_namespace "test_unit"
    end
```

**Comment by eval** [comment]
@byroot that PR fixed something else. If this PR needs a rebase, let me know.

**Comment by byroot** [comment]
I don't know, I never use generators, so I don't know what all of this is for. So no idea if I should merge this or not.

**Comment by eval** [comment]
Thanks :)
I made a template that hopefully helps.

```
rails new foo --skip-test -m https://gist.githubusercontent.com/eval/fdbb24af5eb953aa7fd2d12db0e2b27e/raw/aad79c3ac06b827a3d07b827bd05db4d049dcbdf/pr_53384_rails_with_rspec.rb

cd foo

# show generators
rails g

# this shows rspec _and_ test-unit generators
# and way more than when actually using test-unit as hiding doesn't work correctly when using rspec (or another test-framework)
```

Re-running the above steps with this PR should not show the test_unit generators.

**Pull request merged**
