### PR TITLE
Add workaround fix for AttachmentUpload load progress

### PR DESCRIPTION
**Pull request by zzak**
This pulls the workaround patch from #42228, but I'm not sure how to test it so open to ideas :bow:

### CODE REVIEW

**Comment by pixeltrix** [comment]
This doesn't feel like the right fix to me - ideally the user should be prevented from submitting the form until the load event has occurred. I've not used Action Text so will need to investigate it further first before coming up with the correct fix.

**Comment by pixeltrix** [comment]
A quick scout through the code shows that the progress bar is disappearing due to [this CSS]: 

```
    &[value="100"] {
      opacity: 0;
    }
```

Feels like this should be fixed in Trix rather than in Rails - possibly by the addition of a `setUploadComplete` callback that adds a CSS class that explicitly hides the progress. Seems like the workaround could also be tweaked to achieve this.

[1]: https://github.com/basecamp/trix/blob/7940a9a/assets/trix/stylesheets/attachments.scss#L59-L61

**Comment by zzak** [comment]
@pixeltrix I also found this PR in trix: https://github.com/basecamp/trix/pull/445

It looks like they had reverted a change similar to what you proposed by handling this in the callback https://github.com/basecamp/trix/commit/b6b8f5d1828e77e7557d417958060b9030e941b7

**Comment by jeremy** [comment]
Revisited in #55157

**Pull request closed without merging**
