### PR TITLE
[ci skip] Add ImageMagick to ActiveStorage dependencies

### PR DESCRIPTION
**Pull request by ghost**
### Summary
In order to run ActiveStorage's tests successfully, you need imagemagick

### CODE REVIEW

**Comment by mroutis** [comment]
@georgeclaghorn, I missed a new line and it looks horrible



iirc, the contribution guides says that they won't accept "cosmetic" changes, should I send another PR with the new line?

**Comment by georgeclaghorn** [comment]
I just added the missing newline in 14ecf58.

**Comment by mroutis** [comment]
thanks! :)

**Comment by rafaelfranca** [comment]
Can you please add to the Brewfile too? https://github.com/rails/rails/blob/master/Brewfile

**Comment by mroutis** [comment]
sure, @rafaelfranca! https://github.com/rails/rails/pull/33682

**Pull request merged**
