### PR TITLE
Mention "rake" less in guides

### PR DESCRIPTION
**Pull request by ghiculescu**
[This blog post](https://dev.to/youngbloodcyb/rake-junior-rails-review-13cc) is about the confusion between `bin/rake` and `bin/rails` commands. The two have mostly [been aliases since Rails 5](https://github.com/rails/rails/commit/3d252a02ae7f17f94401fe206f4ffc1922610d6f#diff-f5ff9aa07f44111a79d56c09ec37d774b462d97aff68f32490c2e56e74c95783R162), but this means there's all sorts of advice floating around the internet about which command to use. Is `rake db:migrate` the same as `bin/rails db:migrate`? I know that it is, but I can see why it's confusing for a first timer.

The blog post's suggestion was to have a section in the guides that introduces rake and talks about this distinction. I'm not sure about this. I think if we take up too much space too early in the guide discussing this, it risks confusing people even earlier. But if the advice is hidden away too much, nobody will find it.

Something I think we should do, though, is mention `rake` as little as possible in the guides. Mentions in upgrade guides and release notes are fine, but elsewhere we should avoid using it in places where `bin/rails` does an equivalent job. This PR removes a few `rake` mentions from the guides. Before doing this, I was expecting there to be a lot more, so this PR turned out to be a bit smaller than expected. Still, every little bit helps I think.

cc @youngbloodcyb

### CODE REVIEW

**Comment by matthewd** [comment]
Agree the mentions of builtins should all use `bin/rails` and not mention `rake`.

For custom tasks, though, IMO `rake` remains the right choice. For a start, the end-user has to define them, so they clearly need to understand that they are rake tasks, and any way that we suggest or imply the usual Rake documentation doesn't apply is a disservice (and/or transfers documentation burden to us).

I don't think we have a discussed-and-established endgame policy, but at least in my head, the long-term goal would be to separate the two commands again. I see the "try for a rake task" fallback behaviour of `bin/rails` as a transitional mechanism until we eventually get all the built-ins promoted to Rails Commands (which we want, among other things, for the improved ability to take flags and arguments)... after that, I envision a deprecation of the fallback, and ultimately removal.

**Review by matthewd — APPROVED** [review]

**Comment by p8** [comment]
> I see the "try for a rake task" fallback behaviour of `bin/rails` as a transitional mechanism until we eventually get all the built-ins promoted to Rails Commands (which we want, among other things, for the improved ability to take flags and arguments)...

I agree we should migrate the built-ins to Thor.
I've created PRs for some of the simpler Rake tasks.

And I gather I can close: https://github.com/rails/rails/pull/47589 ?

**Comment by p8** [comment]
> I like this PR too.

But if we want to have a clear seperation between Rails commands and Rake tasks, is it still beneficial?

**Comment by ghiculescu** [comment]
Oh, right. Maybe that should be reworded, I'll make a suggestion.

**Comment by ghiculescu** [comment]
@matthewd is this fine to get merged?

**Pull request merged**
