### PR TITLE
Add missing module namespacing wrapper

### LINKED ISSUE #28011: test_unit integration tests generator is missing the namespace wrapper
Not sure how important this is, but it seems inconsistent with everything else.

See https://github.com/rails/rails/blob/master/railties/lib/rails/generators/test_unit/integration/templates/integration_test.rb

...vs...

https://github.com/rails/rails/blob/master/railties/lib/rails/generators/test_unit/model/templates/unit_test.rb#L3

### PR DESCRIPTION
**Pull request by iguchi1124**
close #28011

### Summary
Fix to add missing module_namespacing clause

cc: @chancancode

### CODE REVIEW

**Comment by chancancode** [comment]
Thanks @iguchi1124, can you add (or modify) a test for this? #27605 has some good examples

**Comment by iguchi1124** [comment]
updated integration test generator tests! https://github.com/rails/rails/pull/28013/commits/6affdbee2fbef912542930a79f49545a4bffb063

**Comment by iguchi1124** [comment]
@chancancode Thanks to teach me helpful example! and modified integration test generator tests 6affdbe

**Comment by chancancode** [comment]
@iguchi1134 thank you!

**Pull request merged**
