### PR TITLE
Exercise `connected_to` and `connects_to` methods

### PR DESCRIPTION
**Pull request by bogdanvlviv**
Since both methods are public API I think it makes sense to add these tests in order to prevent any regression in the behavior of those methods after the 6.0 release.

Exercise `connected_to`
  - Ensure that the method raises with both `database` and `role` arguments
  - Ensure that the method raises without `database` and `role`

Exercise `connects_to`
  - Ensure that the method returns an array of established connections(as mentioned in the docs of the method https://github.com/eileencodes/rails/blob/31021a8c85bb80300deb01db96876858ff417f4a/activerecord/lib/active_record/connection_handling.rb#L67)

Related to #34052

### CODE REVIEW

**Review by eileencodes — APPROVED** [review]
Can you squash your commits? Thanks!

**Comment by bogdanvlviv** [comment]
I just squashed the commits into one. Thank you for the review!

**Review by gmcgibbon — APPROVED** [review]

**Review by albertoalmagro — APPROVED** [review]
👏 @bogdanvlviv

**Pull request merged**
