### PR TITLE
`InternalMetadata` accepts all unicode charsets like utf8mb4 for MySQL

### PR DESCRIPTION
**Pull request by kamipo**
It is necessary for avoiding the index length problem.

### CODE REVIEW

**Comment by schneems** [comment]
Not sure what limit you're talking about. Can you give me an example app that reproduces the problem?

The InternalMetadata table should only be used by Rails core developers on new features, that's why we named it internal. I would only ever expect a handful of keys (like 5-10 maybe?) so the index will be pretty small. It won't store arbitrary keys, only values used by rails core and all characters are UTF8. If even this is somehow a problem I would rather have a list of whitelist keys we can check when inserting into the database.

SchemaMigration is a different story, I haven't touched that and it remains basically the same for a very long time. Why is this just a problem now?

**Comment by kamipo** [comment]
This is one of InnoDB Limitations. By default, an index key for a single-column index can be up to 767 bytes.

http://dev.mysql.com/doc/refman/5.7/en/innodb-restrictions.html

If a database was created as encoding utf8mb4, can not create indexes to `varchar(255)`. ref https://github.com/rails/rails/pull/17601#issuecomment-65387148.

How to reproduce:

https://github.com/kamipo/rails-pr-23009

```
$ rails new ~/work/foo --edge -d mysql

(snip)

$ cd ~/work/foo

# modify to `encoding: utf8mb4`
$ vi config/database.yml

$ rake db:create db:migrate
rake aborted!
ActiveRecord::StatementInvalid: Mysql2::Error: Specified key was too long; max key length is 767 bytes: CREATE UNIQUE INDEX `unique_active_record_internal_metadatas`  ON `active_record_internal_metadatas` (`key`) 
/Users/kamipo/work/foo/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.2/lib/mysql2/client.rb:107:in `_query'
/Users/kamipo/work/foo/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.2/lib/mysql2/client.rb:107:in `block in query'
/Users/kamipo/work/foo/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.2/lib/mysql2/client.rb:106:in `handle_interrupt'
/Users/kamipo/work/foo/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.2/lib/mysql2/client.rb:106:in `query'
/Users/kamipo/work/foo/vendor/bundle/ruby/2.3.0/bundler/gems/rails-dbf67b3a6f54/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:316:in `block in execute'
/Users/kamipo/work/foo/vendor/bundle/ruby/2.3.0/bundler/gems/rails-dbf67b3a6f54/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:534:in `block in log'
/Users/kamipo/work/foo/vendor/bundle/ruby/2.3.0/bundler/gems/rails-dbf67b3a6f54/activesupport/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/kamipo/work/foo/vendor/bundle/ruby/2.3.0/bundler/gems/rails-dbf67b3a6f54/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:528:in `log'
/Users/kamipo/work/foo/vendor/bundle/ruby/2.3.0/bundler/gems/rails-dbf67b3a6f54/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:316:in `execute'
/Users/kamipo/work/foo/vendor/bundle/ruby/2.3.0/bundler/gems/rails-dbf67b3a6f54/activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb:128:in `execute'
/Users/kamipo/work/foo/vendor/bundle/ruby/2.3.0/bundler/gems/rails-dbf67b3a6f54/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:593:in `add_index'
/Users/kamipo/work/foo/vendor/bundle/ruby/2.3.0/bundler/gems/rails-dbf67b3a6f54/activerecord/lib/active_record/internal_metadata.rb:42:in `create_table'
/Users/kamipo/work/foo/vendor/bundle/ruby/2.3.0/bundler/gems/rails-dbf67b3a6f54/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb:972:in `initialize_internal_metadata_table'
/Users/kamipo/work/foo/vendor/bundle/ruby/2.3.0/bundler/gems/rails-dbf67b3a6f54/activerecord/lib/active_record/migration.rb:1115:in `initialize'
/Users/kamipo/work/foo/vendor/bundle/ruby/2.3.0/bundler/gems/rails-dbf67b3a6f54/activerecord/lib/active_record/migration.rb:1011:in `new'
/Users/kamipo/work/foo/vendor/bundle/ruby/2.3.0/bundler/gems/rails-dbf67b3a6f54/activerecord/lib/active_record/migration.rb:1011:in `up'
/Users/kamipo/work/foo/vendor/bundle/ruby/2.3.0/bundler/gems/rails-dbf67b3a6f54/activerecord/lib/active_record/migration.rb:989:in `migrate'
/Users/kamipo/work/foo/vendor/bundle/ruby/2.3.0/bundler/gems/rails-dbf67b3a6f54/activerecord/lib/active_record/tasks/database_tasks.rb:155:in `migrate'
/Users/kamipo/work/foo/vendor/bundle/ruby/2.3.0/bundler/gems/rails-dbf67b3a6f54/activerecord/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
Mysql2::Error: Specified key was too long; max key length is 767 bytes
/Users/kamipo/work/foo/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.2/lib/mysql2/client.rb:107:in `_query'
/Users/kamipo/work/foo/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.2/lib/mysql2/client.rb:107:in `block in query'
/Users/kamipo/work/foo/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.2/lib/mysql2/client.rb:106:in `handle_interrupt'
/Users/kamipo/work/foo/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.2/lib/mysql2/client.rb:106:in `query'
/Users/kamipo/work/foo/vendor/bundle/ruby/2.3.0/bundler/gems/rails-dbf67b3a6f54/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:316:in `block in execute'
/Users/kamipo/work/foo/vendor/bundle/ruby/2.3.0/bundler/gems/rails-dbf67b3a6f54/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:534:in `block in log'
/Users/kamipo/work/foo/vendor/bundle/ruby/2.3.0/bundler/gems/rails-dbf67b3a6f54/activesupport/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/kamipo/work/foo/vendor/bundle/ruby/2.3.0/bundler/gems/rails-dbf67b3a6f54/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:528:in `log'
/Users/kamipo/work/foo/vendor/bundle/ruby/2.3.0/bundler/gems/rails-dbf67b3a6f54/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:316:in `execute'
/Users/kamipo/work/foo/vendor/bundle/ruby/2.3.0/bundler/gems/rails-dbf67b3a6f54/activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb:128:in `execute'
/Users/kamipo/work/foo/vendor/bundle/ruby/2.3.0/bundler/gems/rails-dbf67b3a6f54/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:593:in `add_index'
/Users/kamipo/work/foo/vendor/bundle/ruby/2.3.0/bundler/gems/rails-dbf67b3a6f54/activerecord/lib/active_record/internal_metadata.rb:42:in `create_table'
/Users/kamipo/work/foo/vendor/bundle/ruby/2.3.0/bundler/gems/rails-dbf67b3a6f54/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb:972:in `initialize_internal_metadata_table'
/Users/kamipo/work/foo/vendor/bundle/ruby/2.3.0/bundler/gems/rails-dbf67b3a6f54/activerecord/lib/active_record/migration.rb:1115:in `initialize'
/Users/kamipo/work/foo/vendor/bundle/ruby/2.3.0/bundler/gems/rails-dbf67b3a6f54/activerecord/lib/active_record/migration.rb:1011:in `new'
/Users/kamipo/work/foo/vendor/bundle/ruby/2.3.0/bundler/gems/rails-dbf67b3a6f54/activerecord/lib/active_record/migration.rb:1011:in `up'
/Users/kamipo/work/foo/vendor/bundle/ruby/2.3.0/bundler/gems/rails-dbf67b3a6f54/activerecord/lib/active_record/migration.rb:989:in `migrate'
/Users/kamipo/work/foo/vendor/bundle/ruby/2.3.0/bundler/gems/rails-dbf67b3a6f54/activerecord/lib/active_record/tasks/database_tasks.rb:155:in `migrate'
/Users/kamipo/work/foo/vendor/bundle/ruby/2.3.0/bundler/gems/rails-dbf67b3a6f54/activerecord/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

```
root@localhost [foo_development] > show tables;
+----------------------------------+
| Tables_in_foo_development        |
+----------------------------------+
| active_record_internal_metadatas |
| schema_migrations                |
+----------------------------------+
2 rows in set (0.00 sec)

root@localhost [foo_development] > show create table schema_migrations\G
*************************** 1. row ***************************
       Table: schema_migrations
Create Table: CREATE TABLE `schema_migrations` (
  `version` varchar(191) NOT NULL,
  UNIQUE KEY `unique_schema_migrations` (`version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
1 row in set (0.00 sec)

root@localhost [foo_development] > show create table active_record_internal_metadatas\G
*************************** 1. row ***************************
       Table: active_record_internal_metadatas
Create Table: CREATE TABLE `active_record_internal_metadatas` (
  `key` varchar(255) DEFAULT NULL,
  `value` varchar(255) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
1 row in set (0.00 sec)
```

**Comment by schneems** [comment]
I didn't get an error when I ran that command.
Encoding set correctly:

```
mysql>  SHOW CREATE TABLE active_record_internal_metadatas;
+----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table                            | Create Table                                                                                                                                                                                                                                                                                         |
+----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| active_record_internal_metadatas | CREATE TABLE `active_record_internal_metadatas` (
  `key` varchar(255) DEFAULT NULL,
  `value` varchar(255) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  UNIQUE KEY `unique_active_record_internal_metadatas` (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 |
+----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)
```

All elements on the table and the index worked correctly

```
mysql> SHOW COLUMNS FROM active_record_internal_metadatas;
+------------+--------------+------+-----+---------+-------+
| Field      | Type         | Null | Key | Default | Extra |
+------------+--------------+------+-----+---------+-------+
| key        | varchar(255) | YES  | UNI | NULL    |       |
| value      | varchar(255) | YES  |     | NULL    |       |
| created_at | datetime     | NO   |     | NULL    |       |
| updated_at | datetime     | NO   |     | NULL    |       |
+------------+--------------+------+-----+---------+-------+
4 rows in set (0.01 sec)

mysql> SHOW INDEX FROM active_record_internal_metadatas;
+----------------------------------+------------+-----------------------------------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| Table                            | Non_unique | Key_name                                | Seq_in_index | Column_name | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment |
+----------------------------------+------------+-----------------------------------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| active_record_internal_metadatas |          0 | unique_active_record_internal_metadatas |            1 | key         | A         |           1 |     NULL | NULL   | YES  | BTREE      |         |               |
+----------------------------------+------------+-----------------------------------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
1 row in set (0.00 sec)
```

**Comment by kamipo** [comment]
Looks like that your MySQL is 5.7.9 or higher, `innodb_large_prefix = ON`, and `innodb_default_row_format = DYNAMIC`. If not so, row_format that created table is `COMPACT`. The row_format `COMPACT` is affected by the index length problem.

https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_large_prefix
https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_default_row_format

```
root@localhost [foo_development] > show variables like 'version';
+---------------+------------+
| Variable_name | Value      |
+---------------+------------+
| version       | 5.6.26-log |
+---------------+------------+
1 row in set (0.00 sec)

root@localhost [foo_development] > show variables like 'innodb_large_prefix';
+---------------------+-------+
| Variable_name       | Value |
+---------------------+-------+
| innodb_large_prefix | OFF   |
+---------------------+-------+
1 row in set (0.00 sec)

root@localhost [foo_development] > select * from information_schema.tables where table_name = 'active_record_internal_metadatas' and table_schema = database()\G
*************************** 1. row ***************************
  TABLE_CATALOG: def
   TABLE_SCHEMA: foo_development
     TABLE_NAME: active_record_internal_metadatas
     TABLE_TYPE: BASE TABLE
         ENGINE: InnoDB
        VERSION: 10
     ROW_FORMAT: Compact
     TABLE_ROWS: 0
 AVG_ROW_LENGTH: 0
    DATA_LENGTH: 16384
MAX_DATA_LENGTH: 0
   INDEX_LENGTH: 0
      DATA_FREE: 0
 AUTO_INCREMENT: NULL
    CREATE_TIME: 2016-01-13 08:18:42
    UPDATE_TIME: NULL
     CHECK_TIME: NULL
TABLE_COLLATION: utf8mb4_general_ci
       CHECKSUM: NULL
 CREATE_OPTIONS: 
  TABLE_COMMENT: 
1 row in set (0.01 sec)
```

**Comment by schneems** [comment]
Mine isn't set to Compact, you're correct. 

```
*************************** 1. row ***************************
  TABLE_CATALOG: def
   TABLE_SCHEMA: foo_development
     TABLE_NAME: active_record_internal_metadatas
     TABLE_TYPE: BASE TABLE
         ENGINE: InnoDB
        VERSION: 10
     ROW_FORMAT: Dynamic
     TABLE_ROWS: 1
 AVG_ROW_LENGTH: 16384
    DATA_LENGTH: 16384
MAX_DATA_LENGTH: 0
   INDEX_LENGTH: 0
      DATA_FREE: 0
 AUTO_INCREMENT: NULL
    CREATE_TIME: 2016-01-12 14:18:30
    UPDATE_TIME: 2016-01-12 14:18:30
     CHECK_TIME: NULL
TABLE_COLLATION: utf8mb4_general_ci
       CHECKSUM: NULL
 CREATE_OPTIONS:
  TABLE_COMMENT:
1 row in set (0.00 sec)
```

**Comment by jeremy** [comment]
```ruby
$ cat config/initializers/mysql_modern_column_type_defaults.rb
require 'active_record/connection_adapters/abstract_mysql_adapter'

ActiveRecord::ConnectionAdapters::AbstractMysqlAdapter::NATIVE_DATABASE_TYPES.tap do |defaults|
  # Decrease default string length from 255 -> 191 chars so *_type columns
  # can be indexed with utf8mb4 without blowing 767 byte max key length.
  defaults[:string][:limit] = 191

  # Use microsecond precision for all timestamps. High-precision times are
  # first available in MySQL 5.6, but default to second precision for
  # backward compatibility.
  defaults[:datetime][:limit] = 6
  defaults[:time][:limit] = 6
end
```
😑

**Comment by schneems** [comment]
I took a walk and here's what i'm thinking. Since we can't make keys over 191 characters and have them work across ALL databases, let's put a database limit on all InternalMetadata tables regardless of database backend. Yes, it's coupling, however that coupling buys us less mess and more predictability. 191 characters is pretty long for a key anyway. How does that sound?

**Comment by matthewd** [comment]
> 191 characters

:+1:. As it's only going to be used for framework-internal strings, it doesn't make much sense to permit ones that won't fit on some databases.

(We can't just override the default collation for that column, can we?)

**Comment by schneems** [comment]
@kamipo can you give me either a new PR, or modify this PR to use a default limit on InternalMetadata?

Something like this:

```ruby
KEY_LIMIT = ActiveRecord::ConnectionAdapters::Mysql2Adapter::MAX_INDEX_LENGTH_FOR_CHARSETS_OF_4BYTES_MAXLEN

#...

t.column :key,   :string, null: false, limit: KEY_LIMIT
```

If you update this PR please squash to 1 commit and let me know when you're done (github doesn't send notifications)

You have some other unrelated changes that clean up the code. I would rather they didn't go in at the same time but I do like them. Can you put those other changes in another PR and squash to 1 commit?

**Comment by aantix** [comment]
:+1: I just ran into this issue last night.

**Comment by kamipo** [comment]
@schneems Do you mean the below?

```ruby
  class InternalMetadata < ActiveRecord::Base # :nodoc:
    class << self

      #...

      KEY_LIMIT = ActiveRecord::ConnectionAdapters::Mysql2Adapter::MAX_INDEX_LENGTH_FOR_CHARSETS_OF_4BYTES_MAXLEN

      # Creates an internal metadata table with columns +key+ and +value+
      def create_table
        unless table_exists?
          connection.create_table(table_name, id: false) do |t| 
            t.column :key,   :string, null: false, limit: KEY_LIMIT
            t.column :value, :string
            t.timestamps
            t.index  :key, unique: true, name: index_name
          end

          connection.add_index table_name, :key, unique: true, name: index_name
        end
      end
    end
  end
```

BTW, I changed this PR implementation to override the `collation` instead of the `limit` and extracted `internal_metadata_options_for_primary_key`. What do you think about it? If you prefer it, I update this PR to squash without #23065.

**Comment by schneems** [comment]
I merged in the other PR you'll need to rebase this one against master. 

I don't love over-writting a method in the mysql adapter and I don't love schema_migration model calling a method called `internal_metadata_options_for_primary_key`. I'm also not fond of adding yet another method to `ActiveRecord::Base.connection`. My personal preference would be to set a character limit and be done with it.

**Pull request closed without merging**
