### PR TITLE
Use symbols instead of strings while calling respond_to?/(public_)send methods

### PR DESCRIPTION
**Pull request by deepj**

### CODE REVIEW

**Comment by kaspth** [comment]
We need a benchmark to evaluate this change properly. Saying allocations are reduced doesn't cut it :smile:

**Comment by chancancode** [comment]
Like Kasper mentioned, there are [guidelines](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#write-your-code) around submitting cosmetic/performance changes, but I'll do it for you this time (since I was wondering about that in e6f9468) :grin:

```
>> require "benchmark/ips"
=> true
>> Benchmark.ips do |x|
?>   x.report("string +ve") { String.respond_to?("name") }
>>   x.report("string -ve") { String.respond_to?("zomg") }
>>   x.report("sym +ve")    { String.respond_to?(:name) }
>>   x.report("sym -ve")    { String.respond_to?(:zomg) }
>> end
Calculating -------------------------------------
          string +ve    78.997k i/100ms
          string -ve    73.676k i/100ms
             sym +ve   102.993k i/100ms
             sym -ve    96.832k i/100ms
-------------------------------------------------
          string +ve      2.923M (± 6.4%) i/s -     14.535M
          string -ve      2.637M (± 6.6%) i/s -     13.114M
             sym +ve      5.348M (± 5.6%) i/s -     26.675M
             sym -ve      4.346M (± 6.3%) i/s -     21.690M
>> Benchmark.ips do |x|
?>   x.report("string +ve") { String.send("name") }
>>   x.report("sym +ve")    { String.send(:name) }
>> end
Calculating -------------------------------------
          string +ve    75.036k i/100ms
             sym +ve    84.309k i/100ms
-------------------------------------------------
          string +ve      2.510M (± 8.2%) i/s -     12.456M
             sym +ve      4.020M (± 6.7%) i/s -     19.981M
```

The real world difference is probably negligible, but since it's also stylistically preferrable, I think it's fair if we do it in a single commit. Can you grep the codebase for `/(respond_to\?|send)\(["']/` in the lib/guides files (I don't think we care about the tests, so just leave them the way they are in there) and change all of them in one go? Please copy the benchmark into the commit message too :smile: 

Thanks! :grin:

**Comment by deepj** [comment]
@chancancode Thanks for the comment. I've changed it as you requested it. Please, you or someone else take a look. There are other places where I can use this approach. For example for calling `define_method`, `instance_get_variable` and some others. I can do it in this PR or do another one for that changes.

**Comment by chancancode** [comment]
Actually, I lied! My original benchmark doesn't involve a dynamic string like the one you are changing:

```
>> p = "name"; n = "zomg"
=> "zomg"
>> Benchmark.ips do |x|
?>   x.report("string +ve") { String.respond_to?("#{p}") }
>>   x.report("string -ve") { String.respond_to?("#{n}") }
>>   x.report("sym +ve")    { String.respond_to?(:"#{p}") }
>>   x.report("sym -ve")    { String.respond_to?(:"#{n}") }
>> end
Calculating -------------------------------------
          string +ve    77.937k i/100ms
          string -ve    73.041k i/100ms
             sym +ve    77.161k i/100ms
             sym -ve    74.748k i/100ms
-------------------------------------------------
          string +ve      2.866M (± 6.6%) i/s -     14.262M
          string -ve      2.599M (± 7.0%) i/s -     12.928M
             sym +ve      2.840M (± 8.2%) i/s -     14.120M
             sym -ve      2.587M (± 6.9%) i/s -     12.857M
```

So.. ignore what I said earlier. There's no real reason to change them :P

If you found any static string cases for `respond_to?/send/etc`, feel free to open a new PR (but please keep all of them in a single commit) :grin:

**Comment by deepj** [comment]
The problem I have tried to resolved is that reduces string allocation. This is not so bad benefit under heavy load. GC does not need spend so many time on garbage collecting + memory usage is a bit slower. Of course, these changes don't make some heavy reduction of that, but better than nothing though...

In my original change it changed allocation as follows:

Before
```
{["/active_model/attribute_assignment.rb",
  45]=>[10006, 0, 9982, 0, 1, 360400],
 ["/active_model/attribute_assignment.rb",
  46]=>[10006, 0, 9982, 0, 1, 360400]}
```

After:
```
{["active_model/attribute_assignment.rb",
  45]=>[10000, 0, 6677, 0, 1, 275680],
 ["active_model/attribute_assignment.rb",
  46]=>[10000, 0, 6678, 0, 1, 275680]}
```

Testing code:

```ruby
unless File.exist?('Gemfile')
  File.write('Gemfile', <<-GEMFILE)
    source 'https://rubygems.org'
    gem 'rails', github: 'rails/rails'
    gem 'arel', github: 'rails/arel'
    gem 'sqlite3'
    gem 'allocation_tracer'
  GEMFILE

  system 'bundle'
end

require 'bundler'
Bundler.setup(:default)

require 'active_record'
require 'allocation_tracer'
require 'pp'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :title
    t.string :body
  end
end

class Post < ActiveRecord::Base
end

result = ObjectSpace::AllocationTracer.trace do
  5_000.times{
    post = Post.new
    post.attributes = { title: 'A new post', body: 'Something' }
  }
end

pp result.select { |res| res[0].include?('active_model/attribute_assignment.rb') }
```

**Comment by rafaelfranca** [comment]
> Of course, these changes don't make some heavy reduction of that, but better than nothing though...

We disagree. This will same some memory and we know it may decrease the GC count but it also make code uglier and harder to maintain. We prefer to take a more data driven approach and only change what is hotspot and what make a lot of difference.

See https://github.com/rails/rails/pull/12879

Thank you for the pull request.

**Comment by deepj** [comment]
> We disagree. This will same some memory and we know it may decrease the GC count but it also make code uglier and harder to maintain.

Are you sure this change make code uglier and harder to maintain? `"#{k}"` vs `:"#{k}"`. Plus these changes keep consistence with already written code.  The same code style is in already codebase...

https://github.com/rails/rails/blob/master/actionmailer/lib/action_mailer/delivery_methods.rb#L53
https://github.com/rails/rails/blob/master/actionmailer/lib/action_mailer/delivery_methods.rb#L54
https://github.com/rails/rails/blob/master/actionmailer/lib/action_mailer/delivery_methods.rb#L67
https://github.com/rails/rails/blob/master/activemodel/lib/active_model/attribute_methods.rb#L380
https://github.com/rails/rails/blob/master/activejob/test/support/delayed_job/delayed/backend/test.rb#L29
https://github.com/rails/rails/blob/master/activejob/test/support/delayed_job/delayed/backend/test.rb#L87

**Comment by rafaelfranca** [comment]
This change doesn't make the code harder to maintain but its motivation does. If we are introducing this to allocate less objects and just because that we would have to ask people to always do so, and maybe some people will forget about it and introduce another call using string.

But if this change is just to follow code style it is a cosmetic change and we don't accept it.

**Comment by deepj** [comment]
OK, as you wish. Just one thing. Why is SO important to do small changes everyday before big changes sometimes.

**Pull request closed without merging**
