### PR TITLE
Remove unnecessary require in active model test

### PR DESCRIPTION
**Pull request by Gaurav2728**
Person and Topic models are using in test cases but at various place we should use either because one models is enough to test that condition. It also make test faster and DRY

### CODE REVIEW

**Comment by pixeltrix** [comment]
Whilst I'm generally against these due to the amount of git history churn that it causes the affected files all have low number of commits so I'm ¯\_(ツ)_/¯

**Comment by senny** [comment]
I'm skeptical about the value of changes like these. From my point of view, the benefit is very minor. The review effort is high and it creates unnecessary git churn. There's also the chance that we miss something and completely change the meaning of one of the tests. For these reasons I feel like this is a cosmetic refactoring.

**Comment by Gaurav2728** [comment]
@senny @pixeltrix cool . I understand your concern here. PR updated.

**Comment by rafaelfranca** [comment]
Yeah, agree with both @pixeltrix and @senny

**Comment by Gaurav2728** [comment]
@rafaelfranca  after PR updated, these are also cosmetic refactoring.  :flushed:  , Why we require these files :bowtie:  !!

**Pull request closed without merging**
