### PR TITLE
Set memory store to be default in development mode

### PR DESCRIPTION
**Pull request by dhh**
Otherwise our new rate limit feature won't be testable out-of-the-box in development mode.

### CODE REVIEW

**Comment by Earlopain** [comment]
Doesn't this change kind of defeat the purpose of `dev:cache`? While I don't see rate limiting as part of caching, when I do something with `Rails.cache` myself it more often that not will be.

Personally, I always enable caching in dev except for the cache control header.

**Comment by dhh** [comment]
No, dev:cache mainly controls the Action Controller perform caching flag, which is used by fragment caching etc.

**Comment by Earlopain** [comment]
That's how it is now, yes. But before rails used no caching at all by default (in development). I have nothing against `Rails.cache` actually doing something in development, it's closer to how it would behave in prod which I would say is a good thing.

I just don't particularly like how it is now more complicated to explain how rails caching behaves in dev. These need to be updated:
* https://guides.rubyonrails.org/caching_with_rails.html#basic-caching
* https://guides.rubyonrails.org/caching_with_rails.html#caching-in-development
* The comment in `development.rb` describing `dev:cache`. Overall that command isn't nicely named anymore for what it does I think.

Hope that makes sense.

**Comment by Earlopain** [comment]
Openend an issue instead, I couldn't come up with something satisfactory.

**Pull request merged**
