### PR TITLE
More consistent quotes in template files

### PR DESCRIPTION
**Pull request by henrik**
Just upgraded an app from 6.0 to 6.1 and ran `bin/rails app:update`. Noticed the files in `bin` mostly changed to double quotes but had some single-quote stragglers. This fixes those.

### CODE REVIEW

**Comment by henrik** [comment]
Related to #41080 (despite its title it's currently just about quotes), though there's no overlap in the files it changes and the ones this PR does.

**Comment by rafaelfranca** [comment]
Some tests are broken after this change. Can you update?

**Comment by henrik** [comment]
Thank you, @rafaelfranca! ❤️  I assume 

> ActionDispatch::ExceptionWrapperTest#test_#framework_trace_returns_traces_outside_the_application > 
> [/rails/actionpack/test/dispatch/exception_wrapper_test.rb:81]:

is a flaky test? Didn't seem obviously related to these changes.

**Comment by kamipo** [comment]
That failure will be fixed by https://github.com/ruby/ruby/pull/4237.

**Pull request merged**
