### PR TITLE
activesupport require a json decoder

### PR DESCRIPTION
**Pull request by waghanza**
**rails** (throught `activesupport`) requires a `json`

### CODE REVIEW

**Comment by maclover7** [comment]
Hmm, can you provide more information about why need to add the `json` gem as a dependency? I think `json` ships with Ruby's standard library... If there's an error you are seeing because this isn't a dependency, can you please post it? Thanks! :)

**Comment by waghanza** [comment]
@maclover7 I have made an issue here 
https://github.com/rails/rails/issues/25676

perhaps, `json` is not **provided** by default in **ruby** `2.3.1`

**Comment by rafaelfranca** [comment]
It is, but some Linux distributions decided to remove it. In my opinion this is a bug in the Linux distribution that wants to ship their own Ruby implementation.

**Comment by waghanza** [comment]
@rafaelfranca could you be more precise on which distribution in use ?

PS : My version is a **compiled** ruby

**Comment by rafaelfranca** [comment]
I know that fedora does this. json is included in Ruby 2.3.1 as you can see here https://github.com/ruby/ruby/tree/v2_3_1/ext/json. If it is a compiled version either rvm is not compiling ruby with json or there was a bug in the compilation.

**Pull request closed without merging**
