### PR TITLE
Support testing recursively enqueued jobs

### PR DESCRIPTION
**Pull request by rchekaluk**
### Summary

These changes were driven by encountering "SystemStackError: stack level too deep", when using `perform_enqueued_jobs` to test application jobs that recursively requeued themselves.
#### Active Job test_adapter
- test_adapter is a more accurate simulation of a typical adapter by actually enqueuing jobs prior to performing them
- this permits using `assert_enqueued_jobs` within the `perform_enqueued_jobs` block
  - `test_perform_enqueued_jobs`
- this expands the semantics of `perform_enqueued_jobs` to perform any previously-queued jobs in addition to those queued from within its block
  - `test_perform_enqueued_jobs_performs_previously_queued_jobs`
#### Active Job test_helper
- `perform_enqueued_jobs` should not trigger `SystemStackError: stack level too deep` when performing jobs that requeue themselves.
  - `test_perform_enqueued_jobs_that_requeue`
  - `test_perform_enqueued_jobs_that_requeue_wait`
- `perform_enqueued_jobs` block is now optional
  - `test_perform_enqueued_jobs_with_no_block`

### CODE REVIEW

**Comment by jeremy** [comment]
Very nice work! Thank you for contributing, @rchekaluk.

Could you take a swing at a changelog message? Something succinct that communicates the change in terms relevant to Rails users, like
```
Testing: `assert_enqueued_jobs` and `perform_enqueued_jobs` support recursively enqueued jobs.
```

> this expands the semantics of perform_enqueued_jobs to perform any previously-queued jobs in addition to those queued from within its block

This break compatibility and will seem surprising. Why use block syntax if job performance isn't limited to those enqueued within the block?

**Comment by rchekaluk** [comment]
If I understand the question, I agree that with the expanded semantics there may be no need to provide a block to `perform_enqueued_jobs`. However, the block construct was the original form, and so it remains for compatibility.

I would argue that having a name of `perform_enqueued_jobs` implies that all enqueued jobs will be performed (whether queued previously or queued from within the block). Following this argument, the expanded semantics are more intuitive and more correct.

Moreover, these expanded semantics are a necessary side effect of having test_adapter actually queue jobs; and having test_adapter actually queue jobs is required in order to perform jobs that recursively requeue themselves.

I'll add appropriate CHANGELOG entries as a final step when the discussion in this PR is concluded.

**Comment by jeremy** [comment]
It's a fair argument, and it certainly does make sense when it's called without a block, but this is meant for scoping and filtering (the `only:` option) the jobs we want to perform and make assertions about. It's meant to ignore other jobs.

**Comment by rchekaluk** [comment]
OK I've made adjustments to preserve the original scoped semantics when a block is given to `perform_enqueued_jobs`, but adopt expanded semantics when no block is given; this is implemented by temporarily using an alternate queue for the duration of the block.

If this is acceptable, I'll make a final entry in the CHANGELOG.

**Comment by rchekaluk** [comment]
Hi @jeremy, friendly ping that I'm waiting on a thumbs-up that the above changes are AOK. If so, I'll add a final CHANGELOG entry so that this PR can be merged.

**Comment by rchekaluk** [comment]
@jeremy Status on this PR?

**Comment by rchekaluk** [comment]
@jeremy @y-yagi @fxn @rafaelfranca Can anyone assist with moving this PR along?

**Comment by rchekaluk** [comment]
This PR is significantly aged, but is still of interest. What is needed to move this PR along?

**Pull request closed without merging**
