### PR TITLE
Require correctly when requiring core_ext

### PR DESCRIPTION
**Pull request by brancz**
This is a followup on #22137 

In addition to the described problem the proxy_wrappers.rb has to load deprecation therefore the extra commit. But for backporting in 4.2.5 only e1c7809 has to be cherry-picked.

### CODE REVIEW

**Comment by pixeltrix** [comment]
@flower-pot are you sure that change to `proxy_wrappers.rb` is correct? The `deprecation.rb` file has a comment about circular warnings and then requires the various files, one of which is `proxy_wrappers.rb`. Is the reason you're adding this commit because of `load_error.rb` requiring `proxy_wrappers.rb`? If so, then I think the correct fix is for `load_error.rb` to require `deprecation.rb` instead.

**Comment by flower-pot** [comment]
@pixeltrix just read through that comment and I agree, so I moved the require to the `load_error.rb` file. Hope it's now good :smiley:

**Comment by rafaelfranca** [comment]
You need to require `active_support` before requiring `active_support/core_ext`. See http://guides.rubyonrails.org/active_support_core_extensions.html#stand-alone-active-support.

Doing that is this patch still required?

**Comment by flower-pot** [comment]
@rafaelfranca I see. Doing that it works without the patch. I did not notice that. It has worked in earlier versions. I started this because it caused one of my applications to fail which I wanted to upgrade from `4.1.13` to `4.2.4`. I thought it was a breaking change that went by unnoticed. Thanks for the notice. I am going to close this.

**Comment by pixeltrix** [comment]
@rafaelfranca in that case I don't think that `load_error.rb` should be requiring `proxy_wrappers.rb` should it?

**Comment by rafaelfranca** [comment]
Yeah, I don't think it should

**Comment by pixeltrix** [comment]
@flower-pot if you want to amend your commit to remove that require we can still merge your PR :smile:

**Comment by flower-pot** [comment]
You mean we just keep the first commit to at least have the compatibility in `4.2.4` ?

**Comment by pixeltrix** [comment]
@flower-pot no, as @rafaelfranca pointed out you shouldn't be requiring core extensions without first doing `require 'active_support'` which will load `ActiveSupport::Autoload` and fix the problem that you reported in #22137. However `load_error.rb` requires `proxy_wrappers.rb` which should be loaded automatically when `ActiveSupport::Deprecation` is referenced at the bottom of the `load_error.rb` file.

**Pull request closed without merging**
