### PR TITLE
[ci skip] Capitalize sentence of first char in AS guide

### PR DESCRIPTION
**Pull request by yhirano55**
### Summary

I found grammer mistake.

### CODE REVIEW

**Comment by pixeltrix** [comment]
@yhirano55 thanks! 👍

**Comment by fxn** [comment]
:-1: on this edit.

We use this often, the point is a listing is not a paragraph separator.

The structure of tha text is:

> Thus, after a simple require like [listing], objects do not even respond [...]

That is one sentence, cannot be broken. In mathematics you would put the comma after the formula, as in the template above. In programming docs the punctuation is conventionally omitted and introducing colons more common.

**Comment by yhirano55** [comment]
@fxn Oh, sorry. I understood. please revert this change.

**Comment by pixeltrix** [comment]
Reverted in f4680e492331ccf205ca6cc77d9cdf12d315deb0

**Comment by yhirano55** [comment]
Thanks. I'll be more careful.

**Comment by fxn** [comment]
Awesome!

**Pull request merged**
