### PR TITLE
Fix broken `puma.rb` in new apps on edge

### PR DESCRIPTION
**Pull request by smitssjors**
### Motivation / Background

When a new app is generated with the `--edge` option the command `RAILS_ENV=production rails server` fails as `worker_count` is undefined in line 25. This change fixes the variable name.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [ ] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by zzak** [comment]
Does this only affect `7-1-stable`? Could you open the PR to main first otherwise? Then we will backport it from there.

**Comment by smitssjors** [comment]
@zzak This does not affect main. I also checked `7-0-stable` and `7-2-stable` and these are also not affected.

**Comment by yahonda** [comment]
Would you use the `processor_count` here as main and 7-2-branch do?

https://github.com/rails/rails/commit/9dab3e4184765c86ddd1abb0cd420080c70017db

**Comment by yahonda** [comment]
This typo has been introduced via https://github.com/rails/rails/commit/379d7951f1ea92b925d2fab44b3e7e0245456c74 that's why it only exists at 7-1-stable.

**Pull request merged**
