### PR TITLE
Allow ability to ignore tables in database.yml when dump format is sq…

### PR DESCRIPTION
**Pull request by mlainez**
### Summary

When schema format is set to sql, it's not possible to tell pg_dump to ignore some tables. This PR makes it possible to give a list of tables to ignore in database.yml

### CODE REVIEW

**Comment by solojavier** [comment]
@chancancode is there anything we could do to move this PR forward?

**Comment by rafaelfranca** [comment]
Why is this needed? Is it possible to do the same thing with the dump format is ruby?

**Comment by rustygeldmacher** [comment]
@rafaelfranca This is needed because there are times when you are forced to use SQL dump format, but at the same time you need the schema dumper to ignore some tables. We are stuck in this very situation right now...

**Comment by mlainez** [comment]
Hi @solojavier, to be clear, this pr originated from a SO question that I answered a while ago (http://stackoverflow.com/questions/36749936/rails-keep-a-table-out-of-structure-sql-during-migrations/36823943#36823943). Turns out I got in the same situation as @rustygeldmacher some time after I wrote the answer. As it's quite dated, I'm happy to put some extra work into it if needed.

**Comment by yawboakye** [comment]
@rafaelfranca The tables to be ignored wouldn't have been generated by any migration or internal Rails tasks. In my experience these are tables that you quickly jump into the database to create but since `pg_dump` has no way to determine which tables were as a results of migrations (good tables to dump) it can't be selective. That said, I'm not sure this is needed.

**Comment by rustygeldmacher** [comment]
@yawboakye @rafaelfranca The use case for this is the same as the use case that justifies `ActiceRecord::SchemaDumper.ignore_tables` in the first place... For our particular case, we use Amazon's Database Migration Service (DMS) to continually stream updates into Redshift -- in order to operate, DMS creates a couple tables that it manages on its own, so we need to make sure those don't show up in our structure dumps.

**Comment by rustygeldmacher** [comment]
@rafaelfranca @mlainez @yawboakye -- I opened a new pull for this (https://github.com/rails/rails/pull/29060) that uses the list supplied in `ActiveRecord::SchemaDumper.ignore_tables` instead of a list from database.yml -- that way we get parity with how the Ruby schema dumper is set up (so you can, for instance, do a structure dump manually, which is sometimes useful).

**Comment by kamipo** [comment]
Closing this in favor of #29077.

**Pull request closed without merging**
