### PR TITLE
Make parts of ActiveSupport::Inflector reusable

### PR DESCRIPTION
**Pull request by exterm**

### CODE REVIEW

**Comment by exterm** [comment]
too early

**Comment by kaspth** [comment]
Just a heads up, we aren't necessarily keen on modularization for modularizations sake. There'd have to be a compelling use case; maybe we don't want to support the extra modules. And if it's a big change we'd want benchmarks too.

**Comment by exterm** [comment]
I will not change granularity of modules (yet), so I don't think there's anything to be concerned about, but thanks for the heads up. I will submit a more complete version of the changeset after Shopify hack days are over (early next week).

**Comment by kaspth** [comment]
Cool cool, maybe brief @rafaelfranca about the overall idea too? 😊 (Unless he's already involved, cool with it and I just don't know)

**Comment by exterm** [comment]
👍

**Pull request closed without merging**
