### PR TITLE
fix `where` query with the range where the begin and end are equal

### PR DESCRIPTION
**Pull request by a5-stable**
### Motivation / Background

this aims to optimize SQL query generated by Model.where(id: 2..2) in ActiveRecord. 
```
# before
 SELECT `tables`.* FROM `tables` WHERE `tables`.`id` BETWEEN 2 AND 2

# after
 SELECT `tables`.* FROM `tables` WHERE `tables`.`id`=2

```

### Detail
By using a direct equality comparison, leading to a little faster retrieval of the desired records as far as I executed `explain analyzed` with mysql.

```
conn = ActiveRecord::Base.connection
conn.select_one("explain analyze SELECT * FROM tables WHERE id BETWEEN 5000000 AND 5000000")
#=> {"EXPLAIN"=>
  "-> Filter: (tables.id between 5000000 and 5000000)  (cost=0.35 rows=1) (actual time=0.744..0.744 rows=0 loops=1)\n    -> Index lookup on tables using PRIMARY (id=5000000)  (cost=0.35 rows=1) (actual time=0.744..0.744 rows=0 loops=1)\n"}


conn.select_one("explain analyze SELECT * FROM tables WHERE id = 5000000")
#=> {"EXPLAIN"=>"-> Index lookup on tables using PRIMARY (id=5000000)  (cost=0.35 rows=1) (actual time=0.612..0.612 rows=0 loops=1)\n"}
```

### Checklist

Before submitting the PR make sure the following are checked:

* [ ] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [ ] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [ ] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by fatkodima** [comment]
There was a similar PR quite a while ago - https://github.com/rails/rails/pull/31556 😄

**Comment by guilleiguaran** [comment]
@fatkodima sorry! just noticed it

**Comment by fatkodima** [comment]
No problems, just mentioned.

**Comment by a5-stable** [comment]
oh, I'm sorry @fatkodima !　
I didn't notice 🙇‍♀

**Pull request merged**
