### PR TITLE
Rails 3.2: Wrap AS::TestCase to prevent errors when an application doesn't use test-unit

### PR DESCRIPTION
**Pull request by cmckni3**

### CODE REVIEW

**Comment by matthewd** [comment]
Thanks, but 3.2 is only receiving severe security fixes at this point.

**Comment by cmckni3** [comment]
Ok, I'll just add test-unit to my Gemfile then.

**Comment by cmckni3** [comment]
@matthewd Is it still the case that 3.2 doesn't receive fixes? I see commits with some pedantic changes.

I ended up biting the bullet and upgrading to 4.1 but I thought I would bring it up in case someone else runs into the issues this caused.

**Comment by rafaelfranca** [comment]
Yes, it is still the case.

**Pull request closed without merging**
