### PR TITLE
Add clarification about `first` and `last` behavior when using `order` [ci skip]

### PR DESCRIPTION
**Pull request by RochesterinNYC**
Addresses #22438

### CODE REVIEW

**Comment by matthewd** [comment]
This doesn't seem to be addressing the behaviour described in #22438

**Comment by RochesterinNYC** [comment]
@matthewd Sorry, should have been more explicit and said 'related' or something of the sort. This addition to the guides are meant to address one of the multiple points raised by the issue reporter. Specifically, the guides for `first` are a bit misleading because it seems to indicate that the `first` method will always/only return the `first record ordered by the primary key`.

**Comment by RochesterinNYC** [comment]
Still currently thinking through what can be done and posting in that issue thread.

**Comment by maclover7** [comment]
Not directly related to #22438, but am going to merge this in because it helps to clarify `first`/`last` behavior.

**Pull request merged**
