### PR TITLE
ar connection pool: lazy start, eager quit of reaper thread

### PR DESCRIPTION
**Pull request by skull-squadron**
Puma and likely other cluster forking apps don't like threads dangling around.

Tests added.

### CODE REVIEW

**Comment by steakknife** [comment]
@matthewd AR always fires up a thread for reaping connections, which breaks forking Rails servers and similar app. https://blog.phusion.nl/2017/10/13/why-ruby-app-servers-break-on-macos-high-sierra-and-what-can-be-done-about-it/

**Comment by matthewd** [comment]
> This sort of behavior is risky generally

This still sounds like "threads are scary and bad". 😕 

The linked article is about an issue that was [addressed upstream](https://bugs.ruby-lang.org/issues/14009), so we needn't worry about that: their fix will be widely distributed well before any change we make.

Avoiding the puma warning seems desirable, but I'm reluctant to take on the work of possibly stopping or re-starting the thread every time connections change.

**Comment by tgxworld** [comment]
We noticed this at Discourse as well but I think the right fix should be to break out of the loop in the Reaper's thread when the connection pool is removed from the process. I've opened a PR in https://github.com/rails/rails/pull/33094

**Comment by steakknife** [comment]
Closing: too much LoC and `Thread` bouncing.

**Pull request closed without merging**
