### PR TITLE
Eliminate ActiveRecord::AttributeDecorators

### PR DESCRIPTION
**Pull request by jonathanhefner**
This is an alternate take on #39882, based on top of #38871.

/cc @kamipo 
/cc @eugeneius 

---

Sidenote: The "Prevent double decoration" commit should probably be its own PR based directly on top of master.  I would be happy to do that unless you would prefer to, Ryuta?

### CODE REVIEW

**Comment by kamipo** [comment]
> Sidenote: The "Prevent double decoration" commit should probably be its own PR based directly on top of master. I would be happy to do that unless you would prefer to, Ryuta?

Why? it is already done in e0366022f6651a0e53af690394fb1957d3a5bcbc.

**Comment by eugeneius** [comment]
Other than the fact that it gets https://github.com/rails/rails/pull/38871 out of review hell (😩), what's the advantage of this implementation over https://github.com/rails/rails/pull/39882?

**Comment by jonathanhefner** [comment]
@kamipo 

> Why? it is already done in [e036602](https://github.com/rails/rails/commit/e0366022f6651a0e53af690394fb1957d3a5bcbc).

My thinking was to add it as a regression test in an independent PR, but I suppose it does not really matter.

**Comment by jonathanhefner** [comment]
@eugeneius 

> Other than the fact that it gets #38871 out of review hell (weary), what's the advantage of this implementation over #39882?

It is largely similar to #39882.  The main difference is it acts through the `add_attribute_to_attribute_set` method added in #38871, rather than the `define_attribute` method.  In #38871, `add_attribute_to_attribute_set` becomes the primary way to "define" attributes because it avoids mutating global state.

**Comment by eugeneius** [comment]
Got it. I am interested by https://github.com/rails/rails/pull/38871 in principle, but I think https://github.com/rails/rails/pull/39882 is much easier to review than this - I'm still unsure about removing the schema load mutex, for example. I'll try to get back to this soon, but for now I think we should merge https://github.com/rails/rails/pull/39882.

**Pull request closed without merging**
