### PR TITLE
Guides: adding tip about AR-Session-Store [ci skip]

### PR DESCRIPTION
**Pull request by andreynering**

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Thank you for the pull request but we don't link to gem in our guides.

**Comment by andreynering** [comment]
@rafaelfranca No problem, but why?

There are links to others gems. Example:

- The User Management section links to Devise and Authlogic.

- The File Upload section links to attachment_fu.

- In an previous PR, I linked to jquery_ujs in CSRF.

**Comment by rafaelfranca** [comment]
We avoid links to any external resource. They usually get outdated, need to be curated and may be broken.

About these three cases:

* I don't know when we added these but I think it was before we set this guideline.
* Same about this.
* `jquery_ujs` is a integral part of Rails itself. It may be in other repository but it is included in all Rails applications, this one is fine to documento.

**Comment by andreynering** [comment]
I thought it would be fine to link to ARStore because it is a "official" gem.

But no problem, thank you for your patience. :+1:

**Comment by rafaelfranca** [comment]
It is official but not part of the default stack.

**Pull request closed without merging**
