### PR TITLE
Added possibility to check on `:priority` in test helper methods

### PR DESCRIPTION
**Pull request by morgoth**
Retrying https://github.com/rails/rails/pull/26698

### CODE REVIEW

**Comment by morgoth** [comment]
This is still valid PR. I rebased to resolve conflicts

**Comment by morgoth** [comment]
This is still valid

**Review by eugeneius — APPROVED** [review]
This looks good to me, would you mind resolving the conflict?

**Comment by morgoth** [comment]
@eugenebolshakov rebased.

**Comment by eugeneius** [comment]
Thanks!

**Pull request merged**
