### PR TITLE
Modify unscoped usage guide to include chaining [ci skip]

### PR DESCRIPTION
**Pull request by jeffminnear**

### CODE REVIEW

**Comment by eileencodes** [comment]
Hi @jeffminnear thanks for the PR! Here are a couple of changes I think would make this better: 

1) Add the SQL for the examples you added
2) Put the note about how `unscoped` and `scope` don't work together so you need to use a block. The change you made doesn't make it clear that you use a block when you need to scope and unscope.
3) Add `[ci skip]` to your commit message (for guides and documentation PR's) so that travis doesn't run.

Thanks!

**Comment by jeffminnear** [comment]
>2) Put the note about how unscoped and scope don't work together so you need to use a block. The change you made doesn't make it clear that you use a block when you need to scope and unscope.

It actually seems that they do work together now. I have tested it in the Rails console written as both a scope and a class method, and it appears to be working fine.

**Comment by eliotsykes** [comment]
Confirmed `unscoped` chained with a named scope working, e.g.
```ruby
# Seen working
Subscription.expired.unscoped
Subscription.unscoped.expired
```

**Comment by eileencodes** [comment]
Ok, thanks for checking the scoping! Can you squash your commits into one?

**Pull request merged**
