### PR TITLE
Add test case to verify structurally_compatible? method on relations using joins

### PR DESCRIPTION
**Pull request by taha-husain**
### Summary

1. Fix example in ActiveRecord::Relation#structurally_compatible? rdoc.

  ```Post.joins(:comments).structurally_compatible?(Post.where("id = 1"))``` 
returns true(and does not raise ArgumentError when called with **and** or **or**). 
When left and right relations are reversed then structurally_compatible? returns false.   

2. Adds test case to verify `structurally_compatible?` method on relations using joins.

### CODE REVIEW

**Comment by eugeneius** [comment]
> When left and right relations are reversed then `structurally_compatible?` returns `false`.

Is this sensible behaviour? Why does the order matter?

**Comment by taha-husain** [comment]
@eugeneius It seems the order matters when we use `or` or `and` methods between two relations.

```
Post.joins(:comments).structurally_compatible?(Post.where("id = 1"))
=> true

# Following will apply `or` successfully and returns a relation.

Post.joins(:comments).or(Post.where("id = 1"))
=> [ #<Post:0x00007ffd70c5daa8 .. ]
```

```
Post.where("id = 1").structurally_compatible?(Post.joins(:comments))
=> false

# Following will raise ArgumentError.

Post.where("id = 1").or(Post.joins(:comments))
=> Relation passed to #or must be structurally compatible. Incompatible values: [:joins] (ArgumentError)
```

**Comment by eugeneius** [comment]
Right. I'm asking whether that behaviour is intentional and useful, or just a bug. If it's the latter, we should fix the implementation, not the documentation.

**Comment by eileencodes** [comment]
cc/ @kddnewton - can you confirm whether the documentation is wrong or there is an implementation bug. https://github.com/rails/rails/pull/41841 is the PR that introduced this functionality.

**Comment by taha-husain** [comment]
@eugeneius The return value of `#structurally_compatible?` should always be consistent regardless of the order of receiver and argument. This also affects `or` and `and` behaviour. With this logic, it looks like a bug. Please let me know if you have suggestions on implementation changes, I can give it a shot.

**Comment by kddnewton** [comment]
The query method just calls through to [structurally_incompatible_values_for](https://github.com/rails/rails/blob/5e8a26d70559c0b3183e81a5d2775d19146b0c04/activerecord/lib/active_record/relation/query_methods.rb#L1661-L1672), where this behavior is really defined.

I don't really think this is a bug. The order definitely matters according to the code. The receiver can have any kind of query values on it that it wants, provided none of them conflict with the argument.

I suppose we could change this behavior if we wanted to make it more permissive, but it would mean patching `and!` and `or!` to make them `|=` other values as well.

**Comment by intrip** [comment]
> Right. I'm asking whether that behaviour is intentional and useful, or just a bug. If it's the latter, we should fix the implementation, not the documentation.

On a first sight this looked unexpected to me as well, but looks like it's on line with the current behaviour of `and/or` which is just focused on combining where clauses.
For example to do a quick check I've temporary disabled `structurary_incompatible?` check and ran:

```ruby
Post.joins(:comments).and(Post.where(id: 1)).to_sql
=> SELECT "posts".* FROM "posts" INNER JOIN "comments" ON "comments"."post_id" = "posts"."id" WHERE "posts"."id" = 1
```

vs

```ruby
Post.where(id: 1).and(Post.joins(:comments)).to_sql
=> SELECT "posts".* FROM "posts" WHERE "posts"."id" = 1
```

Whilst the first is ok the second one ignores the `joins` values (as expected by and/or behaviour). I think it's correct to consider the second example as structurally incompatible. 
Am I overlooking at something? 🤔

**Comment by taha-husain** [comment]
@eugeneius Could you please take a look at above example and let me know if we still need to change the implementation.

**Comment by taha-husain** [comment]
cc @eileencodes 

> @eugeneius Could you please take a look at above example and let me know if we still need to change the implementation.

**Pull request closed without merging**
