### PR TITLE
Load Action Cable with Zeitwerk

### PR DESCRIPTION
**Pull request by fxn**
Title says it all.

### CODE REVIEW

**Review by byroot — APPROVED** [review]
I think the diff stats say it all 👍

**Comment by byroot** [comment]
Looks like the generators might need some special handling:

```
uninitialized constant Rails::Generators::NamedBase (NameError)\n\tfrom /rails/actioncable/lib/rails/generators/channel/channel_generator.rb:4:in `<module:Rails>'\n\tfrom 
```

**Comment by fxn** [comment]
@casperisfine oh right, was so focused on looking at the `ActionCable` namespace that totally missed `lib/rails` existed :).

Since generators are required and that directory contains assorted things, I believe we can just ignore it all:

```
vagrant@rails-dev-box:~/acg$ bin/rails g channel foo
      invoke  test_unit
      create    test/channels/foo_channel_test.rb
   identical  app/channels/application_cable/channel.rb
   identical  app/channels/application_cable/connection.rb
      create  app/channels/foo_channel.rb
      create  app/javascript/channels/index.js
      create  app/javascript/channels/consumer.js
      append  app/javascript/application.js
      append  config/importmap.rb
      create  app/javascript/channels/foo_channel.js
        gsub  app/javascript/channels/foo_channel.js
      append  app/javascript/channels/index.js
```

**Comment by fxn** [comment]
Have also removed

```ruby
config.eager_load_namespaces << ActionCable
```

This patch removes the method `ActionCable.eager_load!` (which was defined as a side-effect of using `ActiveSupport::Autoload`). But I believe that is an internal method, not in the API. Rails eager loads whatever is in `config.eager_load_namespaces`, and those contents are not public.

**Comment by fxn** [comment]
OK, I think we are good and we've learned a few things for other components, let's merge.

**Pull request merged**
