### PR TITLE
Use frozen string literal in Active Storage

### PR DESCRIPTION
**Pull request by koic**
### Summary
Extends Style/FrozenStringLiteralComment RuboCop rule to activestorage/.

I also fixed that the "can not modify frozen String" error does not occur in rails/activestorage tests.

Related PR #29897.

/Cc @kirs

### Other Information

There is the following Performance/UnfreezeString cop recently merged into RuboCop.

bbatsov/rubocop#4586

It seems that `String#+@` is superior to `String#dup`, but this PR does not using it because support target can not be limited to Ruby 2.3 or higher.

### CODE REVIEW

**Comment by kirs** [comment]
LGTM. Thanks for adding the rule for ActiveStorage!

I'm thinking that maybe now in `.rubocop.yml` we should use `Exclude` components that are not frozen string ready yet, instead of listing them under `Include`.

**Comment by rafaelfranca** [comment]
:+1: to @kirs idea of flipping the whitelist to a blacklist. Could you do that?

**Comment by koic** [comment]
Thanks for your review and advise! I fixed it at 1822e04.

**Comment by matthewd** [comment]
That's not quite what @kirs meant.. we should end up with something more like:

```
Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always
  Exclude:
    - 'railties/**/*'
    - 'actionview/test/**/*.builder'
    - 'actionview/test/**/*.ruby'
    - 'actionpack/test/**/*.builder'
    - 'actionpack/test/**/*.ruby'
```

(because AFAICS, `railties` is the only component not currently listed in the Include section)

**Comment by koic** [comment]
Oops! I was misunderstanding. Thanks @matthewd.

I reverted 1822e04.

Besides `railties`, top level components such as `guides`, `tools`, `tasks`, and `Gemfile`... also require string literal freezing. I'd like to do it by another PR because the target becomes wider. What do you think?

**Comment by kirs** [comment]
Let's do it in the separate PR as you suggest.

**Comment by koic** [comment]
Thank you, all!

**Pull request merged**
