### PR TITLE
feat(rubocop): Add new cops

### PR DESCRIPTION
**Pull request by KapilSachdev**
[Style/RedundantRegexpEscape](https://docs.rubocop.org/rubocop/cops_style.html#styleredundantregexpescape): This cop will help in removing unnecessary escaping inside Regexp literals.

### CODE REVIEW

**Review by jonathanhefner — APPROVED** [review]
Thank you for picking this back up! :pray:

**Comment by KapilSachdev** [comment]
@jonathanhefner I'm not sure how to approach addition of cops, should we discuss all in this PR? _It would create noise though_. 
Or do we have a understanding of which cops we are NOT interested.

Like `Layout/EmptyLinesAroundAccessModifier` and similar, we could have added `Layout/EmptyLines` that could cut :scissors:  53 instances where extra line has been given between methods. But this hasn't been added of which i do not know the reason, maybe missed?
https://github.com/rails/rails/blob/dfb5a82b259e134eac89784ac4ace0c44d1b4aee/activestorage/app/models/active_storage/preview.rb#L102-L109

Similarly, inversion could be fixed with `Style/InverseMethods` (12 instances) that could help, like using `!=` rather negating `!(some==some)` or using `none?` rather `!any?`
https://github.com/rails/rails/blob/dfb5a82b259e134eac89784ac4ace0c44d1b4aee/actionpack/lib/action_dispatch/http/request.rb#L188
https://github.com/rails/rails/blob/dfb5a82b259e134eac89784ac4ace0c44d1b4aee/activesupport/lib/active_support/dependencies.rb#L563-L564
_There is also an extra space between ! and its argument for which rubocop has `Layout/SpaceAfterNot`_

Or `Style/RedundantCondition` , though there just one instance in rails code as of now.
`max_pk ? max_pk : minvalue` to `max_pk || minvalue`
https://github.com/rails/rails/blob/dfb5a82b259e134eac89784ac4ace0c44d1b4aee/activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb#L298

These are cops before `0.82` (the version we bumped from) and i haven't looked into newer ones except the `Style/RedundantRegexpEscape` and `Lint/DeprecatedOpenSSLConstant` (which is already under discussion)

**Comment by kamipo** [comment]
Escaping metacaracters (e.g. `\.`, `\?`, `\(`, etc) are redundant for some context, but I feel that is mostly for readability.
Is it worth not allowing it at all?

And also, we sometimes copy&paste the result of `inspect` (which escaped double qoutes `\"`) in regexp for tests, isn't it a bit inconvenient to not allow that at all?

**Comment by kamipo** [comment]
> Like `Layout/EmptyLinesAroundAccessModifier` and similar, we could have added `Layout/EmptyLines` that could cut :scissors:  53 instances where extra line has been given between methods. But this hasn't been added of which i do not know the reason, maybe missed?
https://github.com/rails/rails/blob/dfb5a82b259e134eac89784ac4ace0c44d1b4aee/activestorage/app/models/active_storage/preview.rb#L102-L109

It is intentional. Double blank lines are used as grouping by Basecamp guys.

**Comment by jonathanhefner** [comment]
I was typing up a longer response, but Ryuta beat me to it!  Here's the gist of what I was going to say:

I think it's probably best to enable and discuss them one at a time, like this PR.  I would look for rules that **always** produce better code (as objectively as possible).  We want to avoid rules that could *possibly* prevent code from being written in an ideal way.

For example, probably all of the lines caught by `Layout/EmptyLines` are intentional, there to make the structure of the code more clear.  Any rule that could interfere with writing code in the clearest way possible is a no-go, even if the style in question is used sparingly.

You'll probably have more luck with `Lint` and `Performance` cops, since they're more objective by nature.

**Comment by kamipo** [comment]
Honestly, I'd not like to spend time arguing about whether or not we should follow for each cops.

As I said at https://github.com/rails/rails/pull/39527#issuecomment-687916283, I tend to value whether or not it reduces review costs.

**Comment by KapilSachdev** [comment]
Thanks for the quick feedback.
>For example, probably all of the lines caught by Layout/EmptyLines are intentional, there to make the structure of the code more clear. Any rule that could interfere with writing code in the clearest way possible is a no-go, even if the style in question is used sparingly.

I understand what is being conveyed, but the rationale behind this is kind of an unsaid rule in the repository that some are familiar with (not sure though, might be many). Also not adding this will ignore all and the reviewer needs to take care of that, which the cop could have saved us from.  
That said I found its addition here #26077  and removal here https://github.com/rails/rails/commit/b76f4e47e842d4f6e4519046461e1a3da99ccf82#diff-11a0d7906801d9dea0eccb85667ad811

>You'll probably have more luck with Lint and Performance cops, since they're more objective by nature.

Will look into those then, as `Style` and `Layout` are too subjective. 

> As I said at [#39527 (comment)](https://github.com/rails/rails/pull/39527#issuecomment-687916283), I tend to value whether or not it reduces review costs.

_review costs_ are subjective. I mentioned `Style/InverseMethods` for the same reason as I have seen many reviewers asking to remove negating of negation.
I understand your point, and that's why already asked if we have some understanding in the community about the cop which i'm not aware, of which @jonathanhefner has asked to try the luck of `Lint` and `Performance` cops.
For now I will not look into `Style` and `Layout` cops unless I feel it can help in _review costs_.

**Pull request closed without merging**
