### PR TITLE
add quick fix for auto disconnect when cable client offline

### PR DESCRIPTION
**Pull request by isamankumara**
### Summary

in the production environment on ubuntu server, when disconnect from client side, it's keeping as connected. after adding these code it's checking 5 pins and disconnect  the connection if those 5 pins failed.

### Other Information
-

### CODE REVIEW

**Comment by isamankumara** [comment]
@kaspth can you get action for this ?

**Comment by kaspth** [comment]
Looks like there's lots of other commits in here. Can you explain the problem you're seeing some more? I'm not too happy with the idea of merging a "quick fix", we try not to do those on Rails.

**Review by sikachu — COMMENTED** [review]
Seems like there is a merge problem in this PR. Do you mind rebasing your PR against the current master?

**Comment by isamankumara** [comment]
@kaspth - I have done only few changes (https://github.com/rails/rails/pull/32828/commits/6317949d3733a457e1011ae982e1bf5e000fc0e4)
but I merged my repo with master on rails 

@sikachu  - It can't see any conflicts with the base branch. Yes I can merge my code with current rails master branch. Is that what you asking right ?

**Comment by kaspth** [comment]
@isamankumara sure! But your PR shows 37 commits, so please get rid of the other 36 😄

**Comment by isamankumara** [comment]
@kaspth , @sikachu  can you check now please ?

**Comment by isamankumara** [comment]
@kaspth  hope now all okay 😄

**Comment by kaspth** [comment]
That fixed the extra commits! Now there's the rest of my questions. I'm generally averse to the idea of merging something titled a "quick fix", so we'd need this to be a better fix.

Can you describe the problem you were seeing in more detail? I haven't really worked with web socket connections, so if you want me to merge this, I'll have to understand it through you 😉

**Comment by isamankumara** [comment]
Hi @kaspth 

On rails action cable connection will not disconnect when client lost the network connection. This should be disconnect and `disconnect` method on connection class need to fire. 

e.g.: Assume you are connecting to server and client(phone) using action cable and when you turn off your data still server doesn’t know as connection lost and application trying to broadcast messages. 

Disconnect method fire time will be depend with servers. 
e.g. Mac os -> less than 1 minutes 
     Linus server -> 15 minutes later

So what I did was, 

When socket checking the beat (on base.rb class) I am sending pin message and checking the response (If socket is connected with client response should be pong) If we didn't get response getting the ping times. If it is 5 then calling the `client_gone` method. It will call  `disconnect` method.  If we get the response resetting the ping times variable. (It means socket connection will disconnect if client connection fails 5 times continuously)

**Comment by isamankumara** [comment]
@kaspth any update ?

**Comment by kaspth** [comment]
Sounds like this is what you're describing: https://github.com/rails/rails/issues/24908

If we're going to replace the app-level ping with the protocol one, we'd need to have it a lot more robust to accept this change. I'd look to @jeremy's comments in the issue for guidance on what we're looking for 😊

**Comment by isamankumara** [comment]
@kaspth any update regarding this?

**Comment by kaspth** [comment]
Well, you haven’t changed your code one bit since my last comment, so no 😄

I’d rather have a proper fix for the issue I referenced. So unless someone does that, it’s not happening. Thanks!

**Pull request closed without merging**
