### PR TITLE
Hash#to_struct

### PR DESCRIPTION
**Pull request by dorianmariecom**
### Summary

Add Hash#to_struct for a safer way to access objects coming from a JSON api or objects passed to views,

OpenStruct often hides the typos and other mistakes we can make when calling methods on it

I used it at a previous company and on my side-project

I will add an entry to the changelog if it's accepted in general

Also this sounds like it could be part of ruby itself but could live in rails meanwhile.

See also: https://stackoverflow.com/q/11962192/12544391

- [x] test pass locally
- [ ] test pass on CI

### CODE REVIEW

**Comment by pocke** [comment]
Just FYI, be careful about the memory DoS. related: https://bugs.ruby-lang.org/issues/16986#note-36

> Because method-name symbols are never GC'ed, so converting arbitrary external input to anonymous Struct is vulnerable against Symbol DoS.

**Comment by dorianmariefr** [comment]
wouldn’t it affect open struct then?

**Comment by intrip** [comment]
@dorianmariefr `OpenStruct` works in a different way and it will be GCed.

**Comment by pocke** [comment]
> @dorianmariefr AFAIK `OpenStruct` works in a different way and it will be GCed hence is not affected by this issue.

Yes, it was previously correct.
But recently OpenStruct changed the structure, so OpenStruct v0.3.0+, which is bundled with Ruby 3.0+, has the same memory DoS issue.
It is documented here: https://github.com/ruby/ostruct/blob/v0.3.1/lib/ostruct.rb#L79-L81
related tickets: https://bugs.ruby-lang.org/issues/15409 and https://github.com/ruby/ostruct/pull/15

**Comment by dorianmariefr** [comment]
The issue can and will be handled b by Ruby, we can still add this helper I think

**Comment by dorianmariefr** [comment]
made it into a gem https://github.com/dorianmariefr/to_struct

**Pull request closed without merging**
