### PR TITLE
Provide a way `decorate_attribute` for attribute type decoration

### PR DESCRIPTION
**Pull request by kamipo**
Just an implementation for https://github.com/rails/rails/pull/41139#discussion_r565752925.

cc @kaspth

### CODE REVIEW

**Review by kaspth — APPROVED** [review]
Nice! Are there any other ramifications we'd need to be aware of with this? If not, then we're just missing a CHANGELOG entry.

**Comment by kamipo** [comment]
I'd say no, it is just a wrapper for `attribute(:attr_name) { |subtype| Type.lookup(:type_name, subtype: subtype) }`.

I'll add a CHANGELOG entry later before merging this.

**Comment by kaspth** [comment]
Cool, let's go for it 👍

**Comment by rafaelfranca** [comment]
I think we should have a `decorate_attrubute` but I don't think `attribute` behavior should be a decoration. It should be a override without knowledge of the type in the superclass.

**Comment by kamipo** [comment]
I don't intend to expose the internal `attribute` behavior that `enum` and `serialize` depend on in the doc, like https://github.com/rails/rails/pull/28640#discussion_r112368222 (e8cb53b7a5a3dbcf9b050fd8d5b8dd3c2c39cfc0).

If we prefer to entirely avoid the internal behavior in `attribute`, I would try that.

**Review by rafaelfranca — APPROVED** [review]

**Comment by zzak** [comment]
Go away @rails-bot /cc @kamipo

**Comment by kamipo** [comment]
Closing in favor of #44665.

**Pull request closed without merging**
