### PR TITLE
Ability to test activejobs with relative delay

### PR DESCRIPTION
**Pull request by vlado**
`assert_enqueued_with` and `assert_performed_with` were not able to
properly test jobs with relative delay. `:at` option was asserted for
equality and test will always fail cause small fraction of time will
pass between job call and assertion.

This commit fixes that by asserting `:at` with 0.5 delta. This gives
enough time for tests with relative delay to pass and expects no one is
crazy enough to pass absolute time half a second in the future :)

Before: 

``` ruby
# This will pass
assert_enqueued_with(job: MyJob, at: Date.tomorrow.noon) do
  MyJob.set(wait_until: Date.tomorrow.noon).perform_later
end

# This will fail
assert_enqueued_with(job: MyJob, at: 5.minutes.from_now) do
  MyJob.set(wait: 5.minutes).perform_later
end

# To make it pass we need something like this
job = assert_enqueued_with(job: MyJob) do
  MyJob.set(wait: 5.minutes).perform_later
end
assert_in_delta 5.minutes.from_now, job.scheduled_at, 1
```

After:

``` ruby
# This will pass
assert_enqueued_with(job: MyJob, at: Date.tomorrow.noon) do
  MyJob.set(wait_until: Date.tomorrow.noon).perform_later
end

# This will also pass
assert_enqueued_with(job: MyJob, at: 5.minutes.from_now) do
  MyJob.set(wait: 5.minutes).perform_later
end
```

At first I wanted to implement this by replacing `:at`option with `:wait` and `:wait_until` options (`:wait_until` would be checked for equality and `:wait` with `assert_in_delta`)

``` ruby
assert_enqueued_with(job: MyJob, wait_until: Date.tomorrow.noon) do
  MyJob.set(wait_until: Date.tomorrow.noon).perform_later
end

assert_enqueued_with(job: MyJob, wait: 5.minutes) do
  MyJob.set(wait: 5.minutes).perform_later
end
```

but I think this (keeping `:at` option) is a better implementation cause API stays the same.

### CODE REVIEW

**Comment by kaspth** [comment]
Don't feel particularly strongly about this. So if somebody else wants to jump in, please do :grin:

(@rafaelfranca how can I get @rails-bot to spin the wheels again?)

**Comment by kaspth** [comment]
@seuros can you take a look at this? (I'd be happy to reassign this to you too) :smile:

**Comment by edwardmp** [comment]
This actually seems like a neat feature, I was looking for such a thing today and noticed it isn't currently possible. @kaspth how can I help to get this merged in?

**Comment by vlado** [comment]
@kaspth @seuros I needed this again recently. Any chance that this could get merged soon 🙏 

I'll be happy to update this and resolve conflicts.

**Comment by rafaelfranca** [comment]
Can you rebase? I'll take a look

**Comment by vlado** [comment]
> Can you rebase? I'll take a look

Hi @rafaelfranca, I had trouble rebasing (I followed contributing guide but looks like I did something wrong) so I opened new PR here https://github.com/rails/rails/pull/36767 and will close this one. Thanks for looking at it and sorry for the trouble.

**Pull request closed without merging**
