### PR TITLE
ActiveCable clients do not receive update about state of a subscription.

### PR DESCRIPTION
**Pull request by wpp**
### Summary

ActionCable's `ClientSocket` is open and receives a subscription message, which is
discarded since the socket is not in the desired `@ready_state` at that point.

This leaves both server and client in a stalled state. The client is waiting for
a subscription update, the server for a subscription message.

The patch idea is fairly simple: Don't discard received messages, but rather buffer
them and process upon opening.

### Other Information

I originally assumed this might be related to #24874 and applied the WIP patch by
@maclover7. This did not solve the problem.

While debugging this issue I've documented my findings in this
[project](https://github.com/wpp/action-cable-debugging), which contains a Rails
app & the required scripts to reproduce the problem. Please see the README for
more information.

As far as the patch goes:

Please note that **this is the first and simplest solution** I came up with. I would
love to get some feedback and help with a more robust solution. I'd also appreciate
if someone could reproduce the original problem.

- It might make more sense to move the message buffer from connection to the
- client socket?

Thanks for your time,
Have a great day

* Edits: Formatting and typo.

### CODE REVIEW

**Comment by wpp** [comment]
Hi,

Another option would be to delay the transmission of the `respond_to_successful_request ([ -1, {}, [] ])`, until the `WebSocket::Driver` actually declares the socket as open. AFAIU the current implementation doesn't wait until the driver has emitted the open event.

I have a first version of that approach running locally as well and will update my repository with my findings. However, the delay mechanism I'm using feels flaky. I could share that solution, perhaps someone can help improving that delay?

Let me know if I can help with more details.

**Comment by wpp** [comment]
Hello!

It's been a while since I've submitted this and haven't gotten any feedback yet.
I totally understand if you need more time, just wondering if there is something I could do from my side. (Were you able to reproduce the issue? Are my instructions unclear?)

Cheers

**Comment by palkan** [comment]
Hi, @wpp!

The problem you're trying to solve is caused not by Action Cable itself but by [Action Cable client](https://github.com/NullVoxPopuli/action_cable_client) you use: client must consider a connection to be ready/open only after receiving "welcome" message (and not WebSocket OPEN event). Thus you should not send any message before that. Sending messages after receiving "welcome" from server guarantees that the socket is OPEN (from the server point of view). 

Hence the client doesn't implement Action Cable protocol correctly.

Take a look, for example, at Action Cable js client to see how it should be implemented.

**Comment by wpp** [comment]
Thanks so much for looking into this. As far as I recall we started using that specific client because we had the same issue with the Action Cable JS client. I'll look into this in the next couple of days and report back.

**Comment by wpp** [comment]
Hi @palkan!

Thanks again for taking a look at this. Took a while for me to respond, sorry about that.
I could not reproduce the behaviour with the official ActionCable JavaScript client. It was in fact a different third party android library where we originally noticed this error.

As far as the ruby client goes, I've submitted the following patch:
https://github.com/NullVoxPopuli/action_cable_client/pull/24

Thanks again for clearing this up!

**Pull request closed without merging**
