### PR TITLE
Gemfiles are not limited for :test, :development we can enhance it, remo...

### PR DESCRIPTION
**Pull request by Gaurav2728**
...ved spacing that make intend code

### CODE REVIEW

**Comment by matthewd** [comment]
That isn't a sentence.

**Comment by Gaurav2728** [comment]
@matthewd please can you assist for that.

**Comment by matthewd** [comment]
@Gaurav2728 I think it's fine as is.

**Comment by Gaurav2728** [comment]
@matthewd  cool.....what about `stylesheet_link_tag :white_medium_square: 'application'` spaces that distract that indentation and generate for every app :warning:

**Comment by matthewd** [comment]
They seem to be there to align the parameters to `stylesheet_link_tag` and `javascript_include_tag`

**Pull request closed without merging**
