### PR TITLE
Update routing.md

### PR DESCRIPTION
**Pull request by thiagoaugusto**

### CODE REVIEW

**Comment by schneems** [comment]
Thanks! :heart: In the future of your change is documentation only you can ass "vi skip" to the commit message so our CI doesn't have to run.

**Comment by yui-knk** [comment]
@schneems  Do you mean "ci skip"?

**Comment by akshay-vishnoi** [comment]
Yes. You should add `[ci skip]` to your commit message when you add documentation changes only. Travis (CI tool) skips the documentation PR.

**Comment by thiagoaugusto** [comment]
Thank's @schneems.

**Pull request merged**
