### PR TITLE
chore: fix grammar, spelling and minor whitespace fix

### PR DESCRIPTION
**Pull request by jbampton**
### Summary

Fixed grammar in 3 Markdown files.

Fixed spelling.

### CODE REVIEW

**Comment by zzak** [comment]
Hi @jbampton, I was just about to approve this PR but saw you pushed again.

In the future, would you be able to send smaller PRs that focus on a single file and start with a [Draft PR](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-stage-of-a-pull-request) until you are ready for review. Maybe this would help making review -> merge cycle faster and reduce the number of unnecessary CI cycles. :pray:

**Comment by jbampton** [comment]
Hey @zzak more PRs is fine and that means I move up faster too 👍 

https://contributors.rubyonrails.org/contributors/john-bampton/commits

**Comment by rafaelfranca** [comment]
3 smaller PRs is better than 1 big PR, but 20+ smaller PRs is harder to review specially for changes like typos and whitespaces correction.

**Review by zzak — APPROVED** [review]

**Comment by zzak** [comment]
@jbampton 👍 to what Rafael wrote, I'd add that by "small" I didn't necessarily mean by lines of change -- but small in terms of scope. For example, if you find yourself wanting to add more and more changes to a PR it's better to send a second one than keep adding to the same PR. That way as a reviewer, I know the finite scope of the PR and can review it much easier.

**Pull request merged**
