### PR TITLE
Update Rails welcome image in guides

### PR DESCRIPTION
**Pull request by ghiculescu**
ref: https://github.com/rails/rails/pull/47550#issuecomment-1452756945

cc @yahonda

### CODE REVIEW

**Comment by yahonda** [comment]
Looks good to me. 

@zzak Do you have some opinion? I recall you have opened some pull request to reduce image file size, I do not recall the pull request # though.

**Comment by yahonda** [comment]
Lint offenses will be addressed via https://github.com/rails/rails/pull/47568

**Review by zzak — APPROVED** [review]
LGTM! If you want to run it through ImageOptim go for it, but it already looks fairly optimized, it's double the pixels and half the bytes??? 👏

**Comment by yahonda** [comment]
Thanks!

**Comment by ghiculescu** [comment]
> LGTM! If you want to run it through ImageOptim go for it, but it already looks fairly optimized, it's double the pixels and half the bytes??? 👏

I ran it through ImageOptim :)

**Pull request merged**
