### PR TITLE
Add --skip-coffee generating option

### PR DESCRIPTION
**Pull request by bluesh55**
### Usage

`rails new awesome-project --skip-coffee`

### CODE REVIEW

**Comment by maclover7** [comment]
cc @prathamesh-sonpatki, this might be related to some of the Action Cable CoffeeScript vs. JavaScript you've been doing

**Comment by jasonfb** [comment]
for a good laugh, I still go back and read this about once a year https://github.com/rails/rails/compare/9333ca7...23aa7da

**Comment by bluesh55** [comment]
Hi @maclover7

It just comments out Gemfile.

Moreover, this is an option flag. not default.

Please tell me whether any part can be problem.

Thanks!

**Comment by mjhoy** [comment]
@maclover7 Are you saying we couldn't skip coffeescript because of Action Cable? In that case why is `coffee-rails` not a hard dependency of rails?

**Comment by rafaelfranca** [comment]
Why do we need an option to remove a gem from the Gemfile? Can't just people remove it from the Gemfile after the application is generated?

**Comment by matthewd** [comment]
@rafaelfranca I think this is a fair complement to skip-turbolinks; restores an ability that we briefly had between 10565895805887d4faf004a6f71219da177f78b7 and bf17c8a531bc8059d50ad731398002a3e7162a7d.

It also encourages people to use the option to remove it immediately, instead of after they notice it's present and they don't want it. That's desirable, because the gem's presence can influence other generators (e.g., Action Cable).

**Comment by rafaelfranca** [comment]
:+1:. I still prefer `--skip-gems` since the number of skippers is only growing.

**Pull request merged**
