### PR TITLE
[ci skip] show the correct example to demonstrate inflections.

### LINKED ISSUE #31008: ActiveSupport::Inflector.parameterize differs from doc because of special dash and underscore behavior
### Steps to reproduce
Direct call to `ActiveSupport::Inflector.parameterize` or `String#parameterize`

### Expected behavior
Parameterize should replace any group of nonalphanumeric chars with the separator.
Example [from the documentation](http://api.rubyonrails.org/classes/ActiveSupport/Inflector.html#method-i-parameterize):
```ruby
ActiveSupport::Inflector.parameterize("^trés|Jolie-- ", separator: '_')
=> "tres_jolie"
```
Using the default separator (`-`):
```ruby
ActiveSupport::Inflector.parameterize('aa______b')
=> "aa-b"
```
### Actual behavior
Running this code on the latest Rails version doesn't replace dashes:
```ruby
ActiveSupport::Inflector.parameterize("^trés|Jolie-- ", separator: '_')
=> "tres_jolie--"
```
It also doesn't replace underscores when using the default separator (`-`):
```ruby
ActiveSupport::Inflector.parameterize('aa______b')
=> "aa______b"
```

### More info
`parameterize` always had special behavior for dashes and underscores, [there are even tests for that](https://github.com/rails/rails/blob/8479b79a0a4dad21a36e69a4502ff7414c250949/activesupport/test/inflector_test_cases.rb#L212-L222). It removes all special chars except for dashes and underscores. This behavior is present since Rails 4.

Technically the doc should be updated to explain this special case, but IMO the special case should be removed - it is counter-intuitive and doesn't seem to be useful.

### System configuration
**Rails version**:
5.1.4
**Ruby version**:
2.4.2p198

### PR DESCRIPTION
**Pull request by aditya-kapoor**
Show the correct example as mentioned in #31008.

Closes #31008

### CODE REVIEW

**Comment by PHedkvist** [comment]
Line 84 and 74 still have the unwanted example.

**Comment by aditya-kapoor** [comment]
@PHedkvist In #31008 I think we are looking at incorrect test case, because the test case in question has `dash` instead of `underscore` and the test case specifies the `separator` as `_` instead of `-`. The other examples specified I think are correct and would work with default value of `separator` as `-`. 

```
ActiveSupport::Inflector.parameterize("^trés|Jolie--") 
# => "tres_jolie"
ActiveSupport::Inflector.parameterize("^trés|Jolie-- ", preserve_case: true) 
# => "tres-Jolie"
ActiveSupport::Inflector.parameterize("^trés|Jolie--", separator: "_") 
# => "tres_jolie--"

```

**Comment by peagha** [comment]
I find it important to document the special dash and underscore behavior, wdyt of:
```ruby
# It preserves dashes and underscores unless they are used as separators:
#
#  parameterize("^trés|Jolie__ ")                 # => "tres-jolie__"
#  parameterize("^trés|Jolie-- ", separator: "_") # => "tres_jolie--"
#  parameterize("^trés_Jolie-- ", separator: ".") # => "tres_jolie--"
```
It took me a long time to find out that `parameterize` had this behavior, so I expect this info to help other programmers in the future

**Comment by rafaelfranca** [comment]
:+1: for @peagha suggestion

**Comment by aditya-kapoor** [comment]
@peagha @rafaelfranca Done!

**Pull request merged**
