### PR TITLE
Don't marshal ActiveSupport::Cache::Entry objects twice

### PR DESCRIPTION
**Pull request by sgrif**
When upgrading to Rails 5.2 we're seeing
`ActiveSupport::Cache::Entry#compress` and
`ActiveSupport::Cache::Entry#should_compress?` as the highest usage of
our CPU. At least some part of this is coming from the fact that objects
are being marshaled multiple times. This memoizes the marshaled value to
eliminate half the problem.

### CODE REVIEW

**Review by rafaelfranca — APPROVED** [review]

**Review by jeremy — APPROVED** [review]
+++ 🚀

**Comment by jeremy** [comment]
Backport to 5-2-stable as well?

**Comment by rafaelfranca** [comment]
Backported in 6bca334c98

**Comment by sgrif** [comment]
Sorry -- I had backported but I guess I forgot `git push` >_>

**Pull request merged**
