### PR TITLE
TimeZone offset can take DST into consideration

### PR DESCRIPTION
**Pull request by kv109**
Solution for #21501, #7297 and maybe #21942 in the future.

### CODE REVIEW

**Comment by kaspth** [comment]
Gonna hand this off, to @pixeltrix :smile:

r? @pixeltrix

**Comment by kv109** [comment]
Anything I can do to help with closing/merging this?

**Comment by kv109** [comment]
@pixeltrix: After Christmas ping :)

**Comment by avit** [comment]
Any listing of time zones is always given as the Standard offset, without DST:

https://en.wikipedia.org/wiki/List_of_UTC_time_offsets

I think it's potentially confusing that a method like `time_zone.to_s` should have different output based on the current system time. What if you're selecting times other than "now", when the DST offsets are different...

My understanding of what you need is always relative to a given time so it might make more sense to have this as a method on TimeWithZone instead of TimeZone, something like this?

```
tz = ActiveSupport::TimeZone['Europe/Amsterdam']
time = tz.now # + 6.months

def time.formatted_offset_name
  "(GMT#{formatted_offset}) #{time_zone.name}"
end

time.formatted_offset_name
#=> "(GMT+02:00) Europe/Amsterdam"
```

**Comment by pixeltrix** [comment]
Closing as the original issues were closed.

**Comment by dan-higgins** [comment]
Sorry to resurrect this, but this issue has come up many times over the years, and will continue to.

Why not just add a `ActiveSupport::TimeZone#current_utc_offset` method, that does a `self.now.dst?` and adds an hour if needed? This is essentially what all users of the `TimeZone` class (including myself) have to do in our own code anyway.

It would return the exact same value as `#utc_offset` during non-DST times of the year for the given zone. And it's a one-liner that would prevent this issue from coming up and biting future users of your class.

**Comment by avit** [comment]
What you're looking for is just `TimeZone.now.utc_offset`?

> does a `self.now.dst?` and adds an hour if needed

Why do it this way? Zones don't necessarily use 1 hour difference for DST.

**Comment by dan-higgins** [comment]
Sorry I did not say it right. If I do `ActiveSupport::TimeZone.new("US/Central").utc_offset` I get `-21600` no matter what time of year it is. I realize this is functioning as designed, but it has misled many developers in the past, and will continue to do so, as in the summer I expect to get -18000.

My suggestion is to add something like `ActiveSupport::TimeZone.new("US/Central").current_utc_offset` which accounts for the current time of year, rather than continuing to close issues and pull requests related to this issue as they come up.

**Comment by avit** [comment]
Yes I get it, `ActiveSupport::TimeZone.new("US/Central").now.utc_offset` works correctly right now.

What you're suggesting is just an alias for `.current_utc_offset` to `.now.utc_offset`. 

TimeZone would then have two methods:

* `tz.utc_offset` (base offset)
* `tz.current_utc_offset` (dependent on current time)

If the existence of the second method makes things clearer, I'm not opposed to that.

**Comment by dan-higgins** [comment]
Thanks. It's nice the way you have spelled it out.

Most folks will quickly learn that `.current_utc_offset` in the `TimeZone` object should return the same value as `.now.utc_offset`. And the `TimeZone#utc_offset` method has the same spelling but not the same meaning as the `TimeWithZone#utc_offset` method.

**Pull request closed without merging**
