### PR TITLE
[WIP] Recommend Puma as the app server

### PR DESCRIPTION
**Pull request by zzak**
We should probably also update equivalent docs for the existing unicorn guides c/d?

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Hmmm, not sure if we should change this. I can't recommend something that I don't use. I also know that Basecamp don't use it. We already rejected this same change before because of this reason. After all this gemfile is still a set of gems recommended by the Rails core team, not of popular gems used widely, neither gems that seems more modern.

**Comment by rafaelfranca** [comment]
See https://github.com/rails/rails/pull/19620. 

cc @dhh @jeremy

**Comment by EduardoBautista** [comment]
Heroku started recommending Puma instead of Unicorn back in January.  It seems that more and more projects are making the switch as well.

**Comment by rafaelfranca** [comment]
BTW, I remember we had a discussion about this at Campfire and @evanphx prompted to answer questions about puma but I don't remember how it ended. Maybe it is worth to check that discussion

**Pull request closed without merging**
