### PR TITLE
Support infinity in PostgreSQL date columns

### PR DESCRIPTION
**Pull request by mrnugget**
This adds support for the special input string values `infinity` and `-infinity` stored in PostgreSQL date columns.

When reading from the database the PostgreSQL adapter now returns `Float::INFINITY` when the stored value equals `infinity` and `-Float::INFINITY` when it equals `-infinity`.

Until now Rails only had support for Infinity in `float` and `datetime` columns. We need this since we have start and end dates in our project. The end date can be infinity.

Please let me know if this change is okay or if I should add something. I tried to use the same code as in `OID::DateTime`.

### CODE REVIEW

**Comment by mrnugget** [comment]
Is there anything I can do to get this merged? Is the `Float::INFINITY` solution not good enough? Should I rebase the branch again?

**Comment by joevandyk** [comment]
Can `Float::INFINITY` be compared with dates and times?

```
irb(main):005:0> (1.0/0) < Time.now
ArgumentError: comparison of Float with Time failed
	from (irb):5:in `<'
	from (irb):5
	from /usr/local/bin/irb:11:in `<main>'
```

**Comment by joevandyk** [comment]
See https://github.com/rails/rails/pull/3457 and https://github.com/rails/rails/pull/7350 for my previous attempts at fixing this a few years ago.

**Comment by mrnugget** [comment]
No, it's not comparable with dates and time. We handle it as a special case in our application. In the same way we use "infinity" in datetime columns, [which are already supported](https://github.com/rails/rails/blob/7b75551a1a4539876f878f37a2439cd02f89d961/activerecord/lib/active_record/connection_adapters/postgresql/oid/date_time.rb) like this.

There is `Date::Infinity` in the standard library though:

```ruby
irb(main):020:0> Date.today < Date::Infinity.new
=> true
irb(main):025:0> Time.now < Date::Infinity.new
=> true
```

**Comment by sgrif** [comment]
It looks like `Date::Infinity` is internal to Ruby, not intended for public use. I personally don't think there's a good way to handle this. `Float::INFINITY` is the only reasonable value that we can use in Ruby to represent this, but I feel that returning that is too unexpected for us to perform that behavior in Rails by default.

In Rails 5, we're introducing a public API which would allow you to add support for infinite dates specifically to your application if you need this behavior and want to use `Float::INFINITY` to do so. Because it is possible to handle on a per-application basis, and I don't think there's a good enough generic solution for us to include in Rails proper, I think the best answer is for Rails to simply not support infinite dates out of the box.

**Comment by mrnugget** [comment]
Alright, thanks a lot for the feedback! And let me just add, that I was proposing this solution, since the support for `infinity` in datetime columns is already [in Rails](https://github.com/rails/rails/blob/5ff08055194963394c24742ae89f69e4e43567a4/activerecord/lib/active_record/connection_adapters/postgresql/oid/date_time.rb#L9-L10).

**Comment by sgrif** [comment]
Yeah, we're reviewing a lot of those behaviors, and that might end up getting deprecated. That's also why I want to be conservative with solutions that don't feel quite right, as they're very hard to change later.

**Comment by aried3r** [comment]
@sgrif Sorry for grave digging, but I could not find such an API in Rails 5, could you point me to it, if implemented?

**Comment by bolshakov** [comment]
@aried3r I think Sean was talking about this Attributes API https://github.com/rails/rails/blob/v4.2.1/activerecord/lib/active_record/type/value.rb
You con see a lot of examples in the same folder. To implement your oun attribute type, inherit form `Type::Value` and override couple of methods.

For example here I've implemented an array which is always sorted and contains only uniq elements

```ruby
class OrderedArrayWithUniqElements < ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Array
  def type_cast_from_user(value)
    super(value).sort.uniq
  end
end
```

And usage:

```ruby
class PriceList < ActiveRecord::Base
    attribute :tags, OrderedArrayWithUniqElements.new(ActiveRecord::Type::String.new)
end
```

**Comment by justinoue** [comment]
Out of the box rails still does not seem to support postgres's 'infinity' value. I can't figure out from all the different issues what the expected behavior is, but if you google, this PR is what shows up. Trying to insert 'infinity' gets treated as nil/null. Trying to retrieve 'infinity' gets treated as nil.

To fix this I have created a custom type as follows:
```
# config/initializers/types.rb
class InfiniteDateType < ActiveRecord::Type::Date
  def cast(value)
    if value.kind_of?(String) && value == 'infinity'
      value
    elsif value.kind_of?(DateTime::Infinity)
      'infinity'
    else
      super
    end
  end

  def deserialize(value)
    if value.kind_of?(String) && value == 'infinity'
      DateTime::Infinity.new
    else
      super
    end
  end
end
ActiveRecord::Type.register(:infinite_date, InfiniteDateType)
```

and putting the following in my model
```
attribute :my_date, :infinite_date
```

**Pull request closed without merging**
