### PR TITLE
[ci skip] Fix Typos and Punctuation in Guides: Upgrading

### PR DESCRIPTION
**Pull request by alexcameron89**

### CODE REVIEW

**Comment by vipulnsward** [comment]
Thanks!

**Comment by vipulnsward** [comment]
cc @eileencodes @rafaelfranca

**Comment by rafaelfranca** [comment]
Backported to 5-0-stable in 98e124c. I'll let @eileencodes decides if this is going to be applied in 5-0-0 because she may already have created the tag.

**Comment by eileencodes** [comment]
I haven't created the tag yet so backported in 66ea16

**Pull request merged**
