### PR TITLE
Fix judgment spelling [ci skip]

### PR DESCRIPTION
**Pull request by csgavino**
As @maclover7 has kindly mentioned in #25239 `judgment` is the spelling that we're going with.

### CODE REVIEW

**Comment by pixeltrix** [comment]
@csgavino the comment by @maclover7 says "judgement is the correct spelling 😬"

https://github.com/rails/rails/pull/25239#r65365048

**Comment by csgavino** [comment]
@pixeltrix I need to get more sleep. Weirdly enough there was another `judgment` in the doc.

**Comment by pixeltrix** [comment]
Though having said that 'judgment' is the [preferred form in Merriam-Webster][1] and we usually follow en-us spelling and not en-gb :smile:

[1]: https://www.merriam-webster.com/dictionary/judgement

**Comment by csgavino** [comment]
I've changed it to `judgment` @pixeltrix 😬

**Comment by pixeltrix** [comment]
@csgavino since there were two different spellings in the same document I had to make a judgement call to use 'judgment' since that's the US spelling. 😂

**Comment by csgavino** [comment]
\*Groans\*

**Pull request merged**
