### PR TITLE
Update changelog to explain the fix of #35114 [ci skip] 

### PR DESCRIPTION
**Pull request by st0012**
Update changelog about https://github.com/rails/rails/pull/35114 's fix

### CODE REVIEW

**Comment by st0012** [comment]
cc @matthewd

**Review by sikachu — APPROVED** [review]

**Comment by st0012** [comment]
@sikachu thank you!

**Comment by eileencodes** [comment]
Updated your comment to be the correct PR because I was really confused at first 😅

**Comment by st0012** [comment]
@eileencodes ah sorry 😅 thanks for merging

**Pull request merged**
