### PR TITLE
Prevent relation builder from generating NULL for array of ranges

### PR DESCRIPTION
**Pull request by dmitry**
It's updated version of pull-request #9179 and partial fix of issue #9171. Additionally I've added test coverage of the array handler.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
@sgrif have you checked it? If so lets backport to 4.1

**Comment by sgrif** [comment]
Will do.

**Comment by vipulnsward** [comment]
Verified that this has been fixed on master. 
Keeping open for backport.
r? @sgrif

**Comment by kamipo** [comment]
This has already been fixed in #15350. Closing.

**Pull request closed without merging**
