### PR TITLE
Fixes ActiveStorage proxy downloads of files over 5mb in S3-like storages

### PR DESCRIPTION
**Pull request by feliperaul**
### Summary

This PR fixes the issue described in another PR (#44679), that makes it impossible to download files larger than 5mb stored in S3-like services using the proxy mode. The proposed PR in #44679 didn't solve the issue for me, so this is why I'm opening a new one. 

As described in greater detail in my comment [here](https://github.com/rails/rails/pull/44679#issuecomment-1126960722), Rails's `ActiveStorage::Blobs::ProxyController` uses `#send_blob_stream`, which in turn uses `#send_stream`, which is provided by the `ActionController::Live` concern.

`ActiveStorage::Blobs::ProxyController` doesn't include `ActionController::Live` directly; it does however include `ActiveStorage::Streaming`, which in turns includes `ActionController::Live`, so that's how `#send_blob_stream` can use  `#send_stream`.

However, downloads over 5mb in size were being truncated at ~ 5mb, and/or halting, when using S3-like storage services.

The cause is that `ActiveStorage::Streaming` is a regular module, and not a Rails concern. So even tough it includes `ActionController::Live`, the fact it is not a concern made so that `ActionController::Live`'s `module ClassMethods` was not being extended, and that's essential to wrap the response in a `Live::Response` instance that makes the streaming response > 5mb work without a glitch.

Btw, the fact that `ActiveStorage::Streaming` is located in a `/concerns` subfolder and it's not a concern is also telling that the intention was to make it a concern.

This PR is a one-liner that makes `ActiveStorage::Streaming` a concern, so it has proper concern dependency resolution, making so that `ActionController::Live` that it includes has it's class method installed. 

In the PR #44679, it was proposed to remove the `Content-Length` header, but as per my [comment](https://github.com/rails/rails/pull/44679#issuecomment-1126796327) in that issue, that didn't solve the issues for me, while this does.

### CODE REVIEW

**Comment by byroot** [comment]
Thanks for the patch.

Any way you could add a regression test for this?

Also please squash your commits into one.

**Comment by feliperaul** [comment]
@byroot Thank you for the quick feedback.

I force-pushed squashing, and I added a simple test in the proxy_controller_test for a 6 megabyte file.

However, I need help to make that test fail, because it's still green before this fix. I couldn't find a difference in the response.body or response.headers to build a failing test.

Any idea how to assert that the response was property delivered by a `Live::Response`? 

I can confirm with a debugger that before this fix the `Live::Response` is not being used, and it is being used after the fix, but I have no idea how I could assert for that in the end response; this is my first interaction with `ActionController::Live` internals and I'm not familiar enough with it to go further.

**Comment by byroot** [comment]
It may not be possible, because it test mode some classes are entirely stubbed. I'd recommend checking the class of `response` in the test, It's probably a `TestResponse` of some sort.

You may have more luck trying to test `AC::Live` itself, e.g. https://github.com/rails/rails/blob/a8f3f0df0ad26c3b6f614af896538982dcf329f0/actionpack/test/controller/streaming_test.rb

Note that this is only broad direction, I don't know what would be best here and I unfortunately won't have time to dig this myself before a week or so. If you can't figure out a good way to test this, I'll try to remember to come back to it in a week. (if I forget, ping me back 😉 )

**Comment by byroot** [comment]
Oh, and I'm asking for a test mostly to avoid future regressions.

**Comment by feliperaul** [comment]
Thanks for your pointers @byroot. 

Unfortunately I spent a couple more hours on this and honestly couldn't figure out a way 😐 

As you said, response is a `TestResponse` made from a `Rack::MockResponse`, and I couldn't find any possible way to assert it came from a `Live::Response`. There's loss of information. 

I also took a dive at `actionpack/test/controller/live_stream_test.rb` but couldn't see a path to test it there, because it's deeply related to the `ActiveStorage::Blobs::ProxyController` (the fact that `ActiveStorage::Streaming` isn't a concern). 

Since the test I had started wasn't actually asserting anything useful (it uploaded and then download a 6mb file, but worked with or without this fix, so it was useless as it was), I force pushed this PR removing the test if by any chance you decide to merge this. I don't know how to proceed here, and I totally understand if this should be closed without the regression test.

In the meantime, for any future googlers, you can fix this by doing a monkey patch in Rails proxy controller in an initializer like this:

```rb
class ActiveStorage::Blobs::ProxyController
  include ActionController::Live
end
```

Or if you wrote your own `ProxyController` (for authentication, like I did), just `include ActionController::Live` before your `include ActiveStorage::Streaming` and it will work.

**Comment by byroot** [comment]
> Unfortunately I spent a couple more hours on this and honestly couldn't figure out a way 😐

No worries, thank you for trying.

**Comment by casperisfine** [comment]
I found a few minutes to look at it. We can unit test it like this:

```diff
diff --git a/activestorage/test/controllers/blobs/proxy_controller_test.rb b/activestorage/test/controllers/blobs/proxy_controller_test.rb
index 443539aded3..4f2279938c5 100644
--- a/activestorage/test/controllers/blobs/proxy_controller_test.rb
+++ b/activestorage/test/controllers/blobs/proxy_controller_test.rb
@@ -85,6 +85,11 @@ class ActiveStorage::Blobs::ProxyControllerTest < ActionDispatch::IntegrationTes
       )
     end
   end
+
+  test "uses a Live::Response" do
+    request = ActionController::TestRequest.create({})
+    assert_instance_of ActionController::Live::Response, ActiveStorage::Blobs::ProxyController.make_response!(request)
+  end
 end
 
 class ActiveStorage::Blobs::ExpiringProxyControllerTest < ActionDispatch::IntegrationTest
```

It's a bit weird to unit test from a controller test, and it's a bit implementation defined, but I'd rather have this than nothing.

**Comment by feliperaul** [comment]
@casperisfine I agree.

I've pushed with a test and a comment with the reasoning, pointing us to this issue.

**Comment by arpu** [comment]
could this be merged in 7.0 plz?

**Comment by byroot** [comment]
> could this be merged in 7.0 plz?

Done.

**Comment by arpu** [comment]
@byroot sorry for the ping but should i open a new bug report for this?

**Comment by byroot** [comment]
If you have a repro for it yes please open an issue. If not you can open an issue too, but it's much less likely to be addressed.

**Pull request merged**
