### PR TITLE
Use HTTP code 503 when health check is down

### PR DESCRIPTION
**Pull request by Spone**
### Motivation / Background

Following up on this https://github.com/rails/rails/pull/46936/files#r1081774747, 503 seems to be a more appropriate HTTP response code than 500.

See https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503

### Detail

This Pull Request changes `500` to `503` (or `:service_unavailable` in the controller to be more descriptive).

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by skipkayhil** [comment]
Can you update the guides and HealthController documentation as well? Both reference 500 being the status returned

**Comment by Spone** [comment]
> Can you update the guides and HealthController documentation as well? Both reference 500 being the status returned

Done in [1bdfb1b](https://github.com/rails/rails/pull/47061/commits/1bdfb1bc14babf86b9db1f0c984625da93a4d310)

**Comment by skipkayhil** [comment]
> Done in [1bdfb1b](https://github.com/rails/rails/pull/47061/commits/1bdfb1bc14babf86b9db1f0c984625da93a4d310)

Perfect. Can you squash your commits? After that I can I mark this ready for review from a committer

**Review by zzak — APPROVED** [review]

**Comment by Spone** [comment]
> Can you squash your commits?

Done!

**Comment by dhh** [comment]
Hmmm. I don't actually agree with this. 503 is for "overloaded" or "service is not yet ready". That's not why we're failing here. We're failing because there's an internal server error that's causing an exception to be raised at the basic level. This might be a wrong master key, a bad configuration of other sorts, or something third. But it's not planned and it's not due to load.

I think 500 Internal Server Error remains correct.

**Pull request closed without merging**
