### PR TITLE
Backport to fix duplicate console logging in Rails 4-2-stable

### PR DESCRIPTION
**Pull request by bmulvihill**
### Summary

Backport to prevent duplicate logging to the console in Rails 4 branch
Based on this PR which fixed the issue in master:
https://github.com/rails/rails/pull/22933

### CODE REVIEW

**Comment by schneems** [comment]
I wrote this commit on master. I'm fine with this being backported.

**Comment by grosser** [comment]
@schneems this can be closed now since I think nobody will merge that :(

**Comment by rafaelfranca** [comment]
😄

**Comment by jmgarnier** [comment]
I am curious, @bmulvihill Why didn't you also backport the fix on `Rails::Server` ? 

image

Screenshot from https://github.com/rails/rails/pull/22933/files#diff-df74380653b76916147b7ad1f036fe41

Shall I give a try to my first PR after 10 years of Rails 😳 to backport it?

PS: Funny, wherever I look, I always end up crossing @grosser path 😃

**Pull request merged**
