### PR TITLE
Use public_send in value_for_collection

### PR DESCRIPTION
**Pull request by Ana06**
Deprecate use of private methods in view's helpers. We should start calling `public_send` in `value_for_collection` instead of `send` to void exposing private methods in view's helpers. :bowtie: 

Fixes https://github.com/rails/rails/issues/33546

### CODE REVIEW

**Comment by matthewd** [comment]
Hi!

I agree we should change this. (And the other `send` I spotted a few lines above.)

If it's worth fixing, it's worth keeping fixed, so we should add a test too.

My big question-mark, however, is whether we need a deprecation. Much as `public_send` is a far more sensible choice, it seems likely _someone_ is currently, perhaps inadvertently, relying on the fact we call private methods. @rafaelfranca?

**Comment by rafaelfranca** [comment]
Agree. It is safer if we deprecate it.

**Comment by rafaelfranca** [comment]
Agree. It is safer if we deprecate it.

**Comment by Ana06** [comment]
@matthewd 

> And the other send I spotted a few lines above.

:+1: 

> If it's worth fixing, it's worth keeping fixed, so we should add a test too.

I'll add it :wink: 


@matthewd @rafaelfranca regarding the deprecation, I guess you mean showing a message in case that the method used is private and not to deprecate the method itself, right?

**Comment by matthewd** [comment]
Right. I think we'd do it something like this:

```ruby
begin
  item.public_send(value)
rescue NoMethodError
  if item.respond_to?(value, true) && !item.respond_to?(value)
    ActiveSupport::Deprecation "Hey don't do that"
    item.send(value)
  else
    raise
  end
end

**Comment by Ana06** [comment]
I think at least d71345e should be rebased into 87b6e6a, but I left it like that following @rails-bot instructions:

> If any changes to this PR are deemed necessary, please add them as extra commits.

**Comment by Ana06** [comment]
I think at least 31ed4f0 should be rebased into 87b6e6a, but I left it like that following @rails-bot instructions:

> If any changes to this PR are deemed necessary, please add them as extra commits.

**Comment by Ana06** [comment]
I think at least 0c62e14 should be rebased into 87b6e6a, but I left it like that following @rails-bot instructions:

> If any changes to this PR are deemed necessary, please add them as extra commits.

**Comment by Ana06** [comment]
@matthewd @rafaelfranca I think the changes are addressed, please take a look. Do we need to test other view's helpers or is it enough with testing `options_from_collection_for_select`? :thinking:

**Comment by Ana06** [comment]
@matthewd something else to change? :thinking:

**Comment by matthewd** [comment]
Nope, this is great, thanks! :heart:

I made a few of tweaks in the merge commit, FYI: 047a893da7a43b8e115b854c73735b9e6475838e (changelog formatting, and I added the name of the called private method to the deprecation message)

**Comment by Ana06** [comment]
@matthewd 

> I made a few of tweaks in the merge commit, FYI: 047a893 (changelog formatting, and I added the name of the called private method to the deprecation message)

I could have made the changes, now my name is not in the commit anymore and you are the only author :sob: :sob: :sob:

**Comment by matthewd** [comment]
@Ana06 all your commits are in there: https://contributors.rubyonrails.org/contributors/ana-maria-martinez-gomez/commits (Oops.. if I'd seen there were so many I should've gotten you to squash. Oh well. 🤷🏻‍♂️)

**Comment by Ana06** [comment]
@matthewd 

> @Ana06 all your commits are in there: https://contributors.rubyonrails.org/contributors/ana-maria-martinez-gomez/commits (Oops.. if I'd seen there were so many I should've gotten you to squash. Oh well. 🤷🏻‍♂️)

you are right, sorry :see_no_evil: I though you squashed the commits, because they needed to be squashed and I didn't see them in the commits history. It seems it is a different way to merge things :eyes: 

Thanks for merging it :wink:

**Comment by Ana06** [comment]
@matthewd @rafaelfranca I spoke about this PR in my talk at EuRuKo (in front of around ~550 people), maybe you want to watch it: https://youtu.be/jUc8InwoA-E?t=2m54s :wink: 

The part where I speak about this is almost as the end, but I am not sure if it is possible to follow without watching the whole talk. :thinking:

**Pull request merged**
