### PR TITLE
Autosave changes disappearing and speed improvement

### LINKED ISSUE #28491: previous_changes is empty if two models have autosave: true for each other
I have a code where `previous_changes` are used in `after_commit` callback. But it shows empty `previous_changes` when it shouldn't, so I created a test case to reproduce this.

I think this can be fixed in a way similar as in `nested_records_changed_for_autosave?`, i.e. adding special variable to avoid modifying "root" record.

### Steps to reproduce

https://gist.github.com/s-mage/20ebc5af616c340abade206f9d4670ca

Some explanations are provided in the gist.

### Expected behavior

`previous_changes` should not be empty

### Actual behavior

`previous_changes` is empty

### System configuration
**Rails version**:
4.2.7.1, 5.0.0, 5.1.0rc1 (tested on these versions, I'm almost sure older versions affected too)
**Ruby version**:
2.3.0

### PR DESCRIPTION
**Pull request by malomalo**
### Motivation / Background

When `autosave: true` is set on both ends of a relation `save` and/or `valid?` can be called more than once removing the changes that just happened during the current `save` and making `previous_changes` and empty hash.

Additionally when there is a lot of records in memory save on a sub record can be called a significant amount of times. It seem that the child models are saved and validated in every permutation possible. This PR results in every record being called at most 1 time and can significantly reduce CPU usage and time to save in this situations.

### Detail

This PR adds `memory` to ensure that each record only gets saved and/or validated only once while traversing the autosave tree, ensuring the changes are available after saving via the `previous_changes` method.

Fixes #28491.

#28491 suggested adding a variable to avoid clearing the changes on the root record which worked; but would not fix the issue if the two models with the autosave true are related to another separate model that is being saved or updated.

Fixes #46438.

This PR also supplants #46438 and enhances it by being able to work across connections and increase speed by only allowing autosaved child models to be saved or validated only once.

### Checklist

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.
* [ ] CI is passing.

### CODE REVIEW

**Review by rafaelfranca — CHANGES_REQUESTED** [review]
The size of this patch and the complexity of it points to me that this issue is being solved in the wrong layer. It seems like we are missing a better abstraction than passing a hash around and checking it everywhere.

**Comment by malomalo** [comment]
This solution solves both of those and still allow people to call save in `after_save` and `after_validation` callbacks. 😱. In the [past PR](#46438) I've tried it on a connection variable but that is also not the right place. This is my ~4ish iteration on this issue, either because of changes that disappear or significant resources spent traversing the autosave tree. We've been running this as a monkey patch for this for the last few months and the previous PR for years.

I'm open to ideas on how to improve it, I assume you mean adding another module similar to `ActiveRecord::Validations`?

**Comment by rafaelfranca** [comment]
It is hard to provide ideas on how to improve because this is reaching for too much. Passing this hash around for so many methods in Rails is a no go. I don't have right now another suggestion, but I just want to make it clear that a solution like this would never be merged.

All that complexity added to `save`, `save!` and `valid?` even if it was moved to a different module is file isn't good. We should not need to have an exposed cache like this one.

There are many avenues to try here. Maybe there is an abstraction that is missing (see as example `AttributeSet`). Maybe there are other ways than caching objects id to know if validation were run on not.

**Comment by rafaelfranca** [comment]
Actually. I'll close the PR since we will not merge this one. In the case you are interested on building a good solution for the problem, we can open new ones. I really appreciate you spending time trying to fix this issue, but this isn't a good solution.

**Comment by malomalo** [comment]
Leaving this [gist](https://gist.github.com/malomalo/269bda0439b1402e432acdb1fcabd910)  here for anyone who has the same issue or think they might. You can just add this to an `ext` folder in your Rails app and require it.

**Comment by malomalo** [comment]
The gist in the previous comment has been updated for Rails 8.0 ^

**Pull request closed without merging**
