### PR TITLE
Wrap EM::Hiredis.connect in a EM.run block to avoid "eventmachine not initialized: evma_connect_to_server" error

### PR DESCRIPTION
**Pull request by vipulnsward**
Ref:https://travis-ci.org/rails/rails/jobs/124388035

### CODE REVIEW

**Comment by matthewd** [comment]
I'm pretty sure you're not supposed to use EM.run like that. And this change is nowhere near any of the code in the linked backtrace.

More importantly, this shouldn't be necessary: `em_redis_connector` is called from `redis_connection_for_subscriptions`, *after* it calls `ensure_reactor_running`. :confused:

**Comment by vipulnsward** [comment]
Let me investigate.

**Comment by vipulnsward** [comment]
I tried investigating this and looks like we are not handling `:failed` state on redis(and try to reconnect redis, if it has `:failed` previously).
We are just handling `:reconnect_failed`
https://github.com/rails/rails/blob/265b7572c9bff39e3d122266dfc693f74ff44664/actioncable/lib/action_cable/subscription_adapter/evented_redis.rb#L53-L55

Something like: 
```ruby
on(:failed) do 
  #reconnect :em_redis_connector
end
```

**Comment by vipulnsward** [comment]
Closing, this is not a solution.

**Pull request closed without merging**
