### PR TITLE
Update #6791 "AR::Migrator.bulk_migration option"

### PR DESCRIPTION
**Pull request by Empact**
This update #6791 and integrates it with the `disable_ddl_transaction!` option that was added since the PR was first opened.

Could probably use some additional testing to handle the interplay between these two features.

### CODE REVIEW

**Comment by jfelchner** [comment]
@tamird I feel this is definitely something that Rails should support.  When you're deploying your app and you have 10 migrations to run, if it fails halfway through (there are lots of things that could fail on a deploy even if you pull the production DB down and run it locally) now you have a DB in a bad state which means that you can't rollback your code.

During development having each migration run in an atomic transaction is fine, but when deploying it's a potential nightmare.

Currently we have to resort to an awful process where we back the DB up, run the migrations, if the rake task fails, we have to drop the DB and then restore it from the backup.  This is not a good solution when the DB supports the exact feature which would solve this problem.

**Comment by jfelchner** [comment]
@senny you did #9507 what is your opinion on this feature?

**Comment by bogdan** [comment]
+1, @Empact thanks for renewing this one

**Comment by pingortle** [comment]
Does anyone have plans to follow up on this? If not, perhaps we should close the issue.

**Pull request closed without merging**
