### PR TITLE
Add "initializers" and "middleware" pages to the conductor

### PR DESCRIPTION
**Pull request by prathamesh-sonpatki**
cc @dhh

### CODE REVIEW

**Comment by prathamesh-sonpatki** [comment]
This is how it looks:

Rails Conductor 2019-03-13 09-05-23
Rails Conductor: Initializers 2019-03-13 09-05-32
Rails Conductor: Middlewares 2019-03-13 09-05-42

There is duplication of code in the command/rake task and conductor for running the initializers and middleware commands which I would like to remove. But I opened this PR just to get an idea if we want something like this.

**Comment by dhh** [comment]
Don't know if those lists are all that helpful, actually. At least not to
be exposed at a top level in the conductor.

**Comment by prathamesh-sonpatki** [comment]
I based this PR on https://3.basecamp.com/3076981/buckets/24956/todos/142270064#__recording_142720048 

We already have routes, notes and stats. Should we add something more?

**Comment by dhh** [comment]
I guess there's no harm in exposing them. It's more about how they're promoted. The crude index puts everything at an even order. I would very much like an interface to deal with migrations next. Full index with the option to run individual migrations up/down, etc.

**Pull request closed without merging**
