### PR TITLE
Bump license years for 2018

### PR DESCRIPTION
**Pull request by yhirano55**
### Summary

- Bump license years for 2018

### CODE REVIEW

**Comment by arunagw** [comment]
thanks :-) 

Happy new year!

**Comment by redtachyons** [comment]
https://github.com/rails/rails/blob/master/activerecord/lib/active_record.rb missing here

**Comment by kamipo** [comment]
Fixed 5e4b70461dfd869c7d96b2528e666a9dd8e29183. Thanks!

**Comment by shime** [comment]
How about putting it to `2004-present` like how Facebook does it? [Here](https://github.com/facebook/react/blob/master/LICENSE#L3) is an example.

**Pull request merged**
