### PR TITLE
Document Attached::Model#attachment_changes [ci skip]

### PR DESCRIPTION
**Pull request by tsvallender**
### Motivation / Background

Adds documentation for the `attachment_changes` method of Active Storage.

### Checklist

Before submitting the PR make sure the following are checked:

* [X] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [X] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [ ] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by Earlopain** [comment]
Having this as part of public API would be very nice. However there is at least one gotcha with this that I'm aware of:
The `attachment_changes` are cleared in an `after_commit` hook here https://github.com/rails/rails/blob/68eade83c87ae309191add6dfa4959d7d7e07464/activestorage/lib/active_storage/attached/model.rb#L140
https://github.com/rails/rails/blob/68eade83c87ae309191add6dfa4959d7d7e07464/activestorage/lib/active_storage/attached/model.rb#L240

It's not immediatly obvious why the changes would be empty in your own `after_commit` just because you defined your callback after (or before depending on `run_after_transaction_callbacks_in_order_defined`) `has_one_attached`/`has_many_attached`.

**Comment by tsvallender** [comment]
> Having this as part of public API would be very nice. However there is at least one gotcha with this that I'm aware of: The `attachment_changes` are cleared in an `after_commit` hook here
> 
> https://github.com/rails/rails/blob/68eade83c87ae309191add6dfa4959d7d7e07464/activestorage/lib/active_storage/attached/model.rb#L140
> 
> https://github.com/rails/rails/blob/68eade83c87ae309191add6dfa4959d7d7e07464/activestorage/lib/active_storage/attached/model.rb#L240
> 
> It's not immediatly obvious why the changes would be empty in your own `after_commit` just because you defined your callback after (or before depending on `run_after_transaction_callbacks_in_order_defined`) `has_one_attached`/`has_many_attached`.

I’m not sure I follow sorry, would that not be as expected? Surely after the commit, there _are_ no unsaved attachment changes, so you would expect `attachment_changes` to be empty.

**Comment by Earlopain** [comment]
> I’m not sure I follow sorry, would that not be as expected? Surely after the commit, there _are_ no unsaved attachment changes, so you would expect `attachment_changes` to be empty.

Maybe you're right. If you map this over to [changes](https://api.rubyonrails.org/classes/ActiveModel/Dirty.html#method-i-changes) from `ActiveModel::Dirty` then my expectation would be wrong.

**Comment by rafaelfranca** [comment]
Sorry, this isn't only adding documentation, it is exposing it to the public API. Why should we do that? Is there any capability of Active Storage that isn't possible today that would be if this was public API?

**Comment by tsvallender** [comment]
The reason I initially found and used this was to act on attachment changes prior to them being persisted, specifically to scan attachments for viruses. Is there another way to do this using the public API?

**Comment by Earlopain** [comment]
I have some Job I need to enqueue only if the attachment has been changed to send some info to an external service. For that I access it in an after_commit hook. `attachment_changes` is used as a solution in a few StackOverflow questions for similar questions and I'm not sure how I would do this without using the private API.

Basically:

```rb
class File < ApplicationRecord
  after_save_commit :post_process
  # This adds framework after_commit hooks which must run after
  # the one above for attachment_changes to not be erased
  has_one_attached :my_file

  def post_process
    return if attachment_changes["my_file"].blank?

    PostProcessingJob.perform_later(self)
  end
end
```

**Comment by zzak** [comment]
This feels similar to #51814 and that has been more or less accepted, so I wonder if that would solve your needs.

**Comment by Earlopain** [comment]
That PR looks promising. The callbacks operate inside of transactions I think which wouldn't be exactly what I want but #51426 should make that work.

**Comment by zzak** [comment]
> act on attachment changes prior to them being persisted
Why not just use `before_save`?

**Pull request closed without merging**
