### PR TITLE
Prefix Module#parent, Module#parents, and Module#parent_name with module

### PR DESCRIPTION
**Pull request by gmcgibbon**
### Summary

Adds `module_` prefix to `Module#parent`, `Module#parents`, and `Module#parent_name`.

As discussed in https://github.com/rails/rails/pull/20901, `parents` isn't a blacklisted class attribute for model scopes. Using a `parents` scope will result in a `SystemStackError `.

An alternate approach would be to disallow `parents` as a valid scope name, or find a better prefix than `module_` because it can include classes which are technically modules but could be better represented.

I'll look into fixing call sites once we decide what the best course of action is.

r? @rafaelfranca 

/cc @dhh, @sgrif

### CODE REVIEW

**Comment by dhh** [comment]
I like this approach 👍

**Comment by cars10** [comment]
I upgraded my rails `5.2.2` app to `6.0.0.beta2` and every controller actions spams multiple of the following deprecation warnings:

```
.DEPRECATION WARNING: `Module#parent` has been renamed to `module_parent`. `parent` is deprecated and will be removed in Rails 6.1. (called from block in <class:ApplicationController> at /my/app/app/controllers/application_controller.rb:6)
```

What is the recommended way to fix these?

**Comment by kaspth** [comment]
Reading the deprecation message it sounds like you have a `parent` call on line 6 of your ApplicationController that need to be renamed to `module_parent`.

**Comment by cars10** [comment]
I do not have any calls to `parent` in my entire project. Line 6 in my ApplicationController:

```
render json: {errors: 'Unauthorized'}, status: 401
```

**Comment by pjforde1978** [comment]
The `marco-polo` gem is also impacted by this deprecation. I created a fork that patches the function naming so as to suppress the warnings in console until such time as the upstream is updated.

[https://github.com/pjforde1978/marco-polo.git](https://github.com/pjforde1978/marco-polo.git)

**Pull request merged**
