### PR TITLE
Remove unjustified use of class variables in actionpack

### PR DESCRIPTION
**Pull request by casperisfine**
I feel that in many cases, `cattr_accessor` / `mattr_accessor` is used even though a class instance variable would work just as well. 

Class variables have two downsides:
  - They are generally slower (sometimes way slower). [Assuming Eileen's and Aaron's patch](https://bugs.ruby-lang.org/issues/17763) is merged, that might no longer hold on ruby 3.1, but that's a long way out.
  - In many cases instance accessors are leaked even though they aren't useful.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
This makes sense to me.

**Comment by casperisfine** [comment]
> what is missing to be a PR ready to review?

I'm having second though on various things:

  - Compatibility issue: what if some user code inherits from these constants and rely on the cache variables semantics
  - Pertinence: while I'm certain `cattr_accessor` is overused in Rails, and that instance variables are simpler, is the change justified?

Also from my benchmarking, the performance difference only matters for class with over 10 or 15 ancestors. So it's a big deal in say `ActiveRecord::Base`, but no so much elsewhere.

**Comment by rafaelfranca** [comment]
Hmmm, we avoid optimization unless they are justified. In those classes we don't have a lot of ancestors so maybe it is better to not apply those changes?

**Comment by casperisfine** [comment]
Agreed. I'll have a look at `cattr_` in Active Record / Active Model though.

**Pull request closed without merging**
