### PR TITLE
Prevent exception of loading database yaml with blank config file

### LINKED ISSUE #36661: Rails 6.0.0.rc1: NoMethodError: undefined method `each_pair' for false:FalseClass
### Steps to reproduce
When trying to run tests on my CI service (SemaphoreCI) I get a `NoMethodError`. It works locally for me. This started happening to me after upgrading to Rails 6.  

### Expected behavior
It should run the test suite.

### Actual behavior
It exits at the `rails db:setup` step. This is the error I get:
```

bundle exec rails db:setup
--
  | rails aborted!
  | NoMethodError: undefined method `each_pair' for false:FalseClass
  | /home/semaphore/new-world/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.0.rc1/lib/active_record/database_configurations.rb:107:in `build_configs'
  | /home/semaphore/new-world/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.0.rc1/lib/active_record/database_configurations.rb:16:in `initialize'
  | /home/semaphore/new-world/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.0.rc1/lib/active_record/tasks/database_tasks.rb:148:in `new'
  | /home/semaphore/new-world/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.0.rc1/lib/active_record/tasks/database_tasks.rb:148:in `for_each'
  | /home/semaphore/new-world/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.0.rc1/lib/active_record/railties/databases.rake:26:in `block (2 levels) in <top (required)>'
  | /home/semaphore/new-world/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.0.rc1/lib/active_record/railties/databases.rake:21:in `block in <top (required)>'
  | /home/semaphore/new-world/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.0.rc1/lib/active_record/railties/databases.rake:5:in `<top (required)>'
  | /home/semaphore/new-world/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:296:in `load'
  | /home/semaphore/new-world/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:296:in `block in load'
  | /home/semaphore/new-world/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:268:in `load_dependency'
  | /home/semaphore/new-world/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.0.rc1/lib/active_support/dependencies.rb:296:in `load'
  | /home/semaphore/new-world/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.0.rc1/lib/active_record/railtie.rb:49:in `block in <class:Railtie>'
  | /home/semaphore/new-world/vendor/bundle/ruby/2.6.0/gems/railties-6.0.0.rc1/lib/rails/railtie.rb:246:in `instance_exec'
  | /home/semaphore/new-world/vendor/bundle/ruby/2.6.0/gems/railties-6.0.0.rc1/lib/rails/railtie.rb:246:in `block in run_tasks_blocks'
  | /home/semaphore/new-world/vendor/bundle/ruby/2.6.0/gems/railties-6.0.0.rc1/lib/rails/railtie.rb:255:in `each'
  | /home/semaphore/new-world/vendor/bundle/ruby/2.6.0/gems/railties-6.0.0.rc1/lib/rails/railtie.rb:255:in `each_registered_block'
  | /home/semaphore/new-world/vendor/bundle/ruby/2.6.0/gems/railties-6.0.0.rc1/lib/rails/railtie.rb:246:in `run_tasks_blocks'
  | /home/semaphore/new-world/vendor/bundle/ruby/2.6.0/gems/railties-6.0.0.rc1/lib/rails/application.rb:508:in `block in run_tasks_blocks'
  | /home/semaphore/new-world/vendor/bundle/ruby/2.6.0/gems/railties-6.0.0.rc1/lib/rails/engine/railties.rb:15:in `each'
  | /home/semaphore/new-world/vendor/bundle/ruby/2.6.0/gems/railties-6.0.0.rc1/lib/rails/engine/railties.rb:15:in `each'
  | /home/semaphore/new-world/vendor/bundle/ruby/2.6.0/gems/railties-6.0.0.rc1/lib/rails/application.rb:508:in `run_tasks_blocks'
  | /home/semaphore/new-world/vendor/bundle/ruby/2.6.0/gems/railties-6.0.0.rc1/lib/rails/engine.rb:459:in `load_tasks'
  | /home/semaphore/new-world/Rakefile:9:in `<top (required)>'
  | /home/semaphore/new-world/vendor/bundle/ruby/2.6.0/gems/railties-6.0.0.rc1/lib/rails/commands/rake/rake_command.rb:22:in `block in perform'
  | /home/semaphore/new-world/vendor/bundle/ruby/2.6.0/gems/railties-6.0.0.rc1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
  | /home/semaphore/new-world/vendor/bundle/ruby/2.6.0/gems/railties-6.0.0.rc1/lib/rails/command.rb:48:in `invoke'
  | /home/semaphore/new-world/vendor/bundle/ruby/2.6.0/gems/railties-6.0.0.rc1/lib/rails/commands.rb:18:in `<top (required)>'
  | /home/semaphore/new-world/bin/rails:11:in `require'
  | /home/semaphore/new-world/bin/rails:11:in `<top (required)>'
  | /home/semaphore/new-world/vendor/bundle/ruby/2.6.0/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
  | /home/semaphore/new-world/vendor/bundle/ruby/2.6.0/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
  | /home/semaphore/new-world/vendor/bundle/ruby/2.6.0/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
  | /home/semaphore/new-world/vendor/bundle/ruby/2.6.0/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
  | /home/semaphore/new-world/vendor/bundle/ruby/2.6.0/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
  | /home/semaphore/new-world/vendor/bundle/ruby/2.6.0/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
  | /home/semaphore/new-world/vendor/bundle/ruby/2.6.0/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
  | /home/semaphore/new-world/bin/spring:16:in `require'
  | /home/semaphore/new-world/bin/spring:16:in `<top (required)>'
  | bin/rails:5:in `load'
  | bin/rails:5:in `<main>'
  | (See full trace by running task with --trace)
  | exit code: 1 duration: 2s
  | export SEMAPHORE_JOB_RESULT=failed
  | exit code: 0 duration: 0s
  | Job Finished


```

### System configuration
**Rails version**: 6.0.0.rc1

**Ruby version**: 2.6.2

### PR DESCRIPTION
**Pull request by igor04**
closes:  #36661

### CODE REVIEW

**Review by gmcgibbon — COMMENTED** [review]
This fixes the problem on 6.0.0.rc1+. Can you add a changelog? Also @andersklenke can you confirm this fixes your issue?

**Comment by andersklenke** [comment]
@igor04  @gmcgibbon
I can confirm that this works! Good job! 👏🏼

**Comment by igor04** [comment]
@gmcgibbon I'm not sure about changelog because there is no new functionality added, only fix of existed

**Comment by eileencodes** [comment]
This didn't need a changelog entry. I've backported it to 6.0. Thanks for the report and fix @igor04!

**Comment by gmcgibbon** [comment]
👍 Thanks for merging and backporting @eileencodes!

**Pull request merged**
