### PR TITLE
Don't return references from cache

### PR DESCRIPTION
**Pull request by mkarnebeek**
When using MemoryStore, it is possible to manipulate data in cache through reference

``` Ruby
irb(main):001:0> store = ActiveSupport::Cache::MemoryStore.new
=> <#ActiveSupport::Cache::MemoryStore entries=0, size=0, options={}>
irb(main):002:0> store.write("key", "value")
=> true
irb(main):003:0> store.read("key").object_id
=> 70092492456600
irb(main):004:0> store.read("key").object_id
=> 70092492456600
irb(main):005:0> a = store.read("key")
=> "value"
irb(main):006:0> a.upcase!
=> "VALUE"
irb(main):007:0> store.read("key")
=> "VALUE"
```

Please backport to 4.2.x branch

### CODE REVIEW

**Comment by rafaelfranca** [comment]
This broke the tests. Could you take a look?

**Comment by mkarnebeek** [comment]
Took a look at a few approaches:
- Have implementations return duped values instead of instances of `Entry`
 - Didn't like because it requires refactoring.
- Have `Cache` always call dup_value! on entries when returning values
 - Don't like this. Probably hits performance of other backends.
- Have `MemoryCache` return a entry from cache, but with a new requires_dup attribute, which `Cache` then checkes and does the dup if it's set.
 - Uhg.. Ugly. Besides: `Entry` gets serialised.
- Have `MemoryStore` return an entry with duped value (call `dup_value!`)
  - Doesn't work: Returned value is still a reference to an entry in cache. You're manipulating cache when calling `dup_value!` on an `Entry` stored in cache
- Have `MemoryStore` return a duped entry
  - Like it, as long as there are no reasons why an instance of `Entry` can't be duped.
  - Also requires a call to `dup_values!` after duping `Entry` since `entry.value.object_id == entry.dup.value.object_id`

I've implemented the last in this PR. Also tests should run successfully now.

**Comment by jeremy** [comment]
I think the safety of preventing (hiding, really) inadvertent mutation won't be worth the tradeoff of slowing down the hot path.

I'm sympathetic to the motivation here—you can accidentally mutate cache values—but this would put a big dent in performance. The memory cache is used as a first-level cache for other cache stores. Now we'd Marshal.dump/load for every cache hit in many cases.

I'm afraid there isn't a great alternative. We can dup+freeze on write, but that causes surprises with cached objects that have memoized methods. They'd blow up if you call them after retrieving from cache.

**Comment by gtmax** [comment]
Perhaps `MemoryStore` should be able to instantiate in 2 distinct modes: "safe" mode that always performs Marshal.dump/load'ing on both write_entry and read_entry, and "direct" mode that stores object references and thus is susceptible to mutation? Direct mode would be the default, for backwards compatibility.

**Comment by sgrif** [comment]
I think a shallow freeze on write seems like a reasonable thing to do -- It'll catch 99% of problems without the performance hit. I think a clone on write is unnecessary, the cache takes ownership on assignment, and strong references shouldn't be kept (or at least should not be assuming that mutations are reflected in the cache)

**Comment by alpaca-tc** [comment]
I had found a similar one at `NullStore`. 😟 

```
Rails.configuration.cache_store = :file_store

hash = {}
Rails.cache.write("name", hash)
hash.merge!('name' => 'value')

assert_equal({}, @cache.read("name")) # Failed
```

**Comment by kamipo** [comment]
Closing in favor of #37210.

**Pull request closed without merging**
