### PR TITLE
use rails command in routes task

### PR DESCRIPTION
**Pull request by y-yagi**
For other task has become to use the rails command at doc and test,
I think that routes task also it is better to use the rails command.

### CODE REVIEW

**Comment by maclover7** [comment]
:+1: Would you be willing to go through all of the other guides to update `rake` --> `rails` as well, as apart of this PR?

**Comment by y-yagi** [comment]
Yes. Because in this PR includes a modification of the code, for the other guide would like to apart of this PR. How about that? 
(I think probably it's almost corrected in 352a889)

**Comment by prathamesh-sonpatki** [comment]
@y-yagi Correct. This PR and https://github.com/rails/rails/commit/352a8892fde37ae0b985ac4b8ff510edad40481d covers all guides. LGTM

**Comment by kaspth** [comment]
Doh! Thanks for catching this :)

**Comment by y-yagi** [comment]
Thanks guys :)

**Pull request merged**
