### PR TITLE
Small fixes [ci skip]

### PR DESCRIPTION
**Pull request by piton4eg**

### CODE REVIEW

**Comment by senny** [comment]
PR just says small fixes but what exactly did you fix? The diff is quite big and it's hard to change what changes you made besides reformatting.

**Comment by piton4eg** [comment]
@senny i just added hyphen between lists titles and descriptions. It were like here: http://screencast.com/t/HjdFcxVvA (without delimeter)

**Comment by senny** [comment]
I agree that the current formatting can be improved. What do you think about a bold header name followed by a colon? Something along the lines of:

```
**X-Frame-Options:** 'SAMEORIGIN' in Rails by default - allow framing on same domain. Set it to 'DENY' to deny framing at all or 'ALLOWALL' if you want to allow framing for all website.
**X-XSS-Protection:** '1; mode=block' in Rails by default - use XSS Auditor and block page if XSS attack is detected. Set it to '0;' if you want to switch XSS Auditor off(useful if response contents scripts from request parameters)
```

**Comment by piton4eg** [comment]
@senny yep, fixed

**Comment by senny** [comment]
@piton4eg thank you :yellow_heart:

**Pull request merged**
