### PR TITLE
Unlock minitest for Rails' test suite

### PR DESCRIPTION
**Pull request by kaspth**
Rails, the repo, is stuck on minitest 5.3.4 but we'd like to get on the latest. We're blocked because our suite doesn't yet run order independently in some cases.

Note: Rails' internal minitest version doesn't affect end-user apps and they can run with the minitest version they please.

### Wanna help? You can!

1. Reproduce a random test failure locally, rerun the test or many however you can with minitest-bisect to consistently reproduce the failure locally with a given `--seed`.
1. Submit a pull request to the unlock-minitest branch with the reproduction case, so we can locally verify it.

E.g. you can reproduce this failure locally with:

```
cd activerecord
bin/test test/cases/some_active_record_test.rb --seed 1234
```

If it fails consistently, say running your command 3-5 times in a row, and pulling your change down consistently fixes it, then we'll merge!

This might be for you, @alexcameron89 @bogdanvlviv @maclover7 @prathamesh-sonpatki @y-yagi (in username alphabetical order)

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Now that the branch is public avoid rebase and force push. Also use `minitest-bisect` when you find a seed that fails that it will tell you which tests are responsible for that order dependent failure.

**Comment by alexcameron89** [comment]
Here are a few I've noticed that pass/fail sporadically even on the same seeds:

 - **AssociationProxyTest#test_first!_works_on_loaded_associations**
 - **PersistenceTest::SaveTest#test_save_touch_false**
```ActiveModel::UnknownAttributeError: unknown attribute 'name' for #<Class:0x007fede5180b20>.```
 - **ActiveRecord::ConnectionAdapters::PostgreSQLAdapterTest#test_only_reload_type_map_once_for_every_unknown_type** 
```
1 instead of 2 queries were executed.
Queries:
SELECT NULL::anyelement.
Expected: 2
  Actual: 1
```
 - **ActiveRecord::DatabaseTasksUtilsTask#test_raises_an_error_when_called_with_protected_environment**
```ActiveRecord::NoEnvironmentInSchemaError```
 - **ActiveRecord::RecordNotUnique: PG::UniqueViolations** 
```
1) Error: TestDefaultAutosaveAssociationOnNewRecord#test_autosave_new_record_on_has_many_can_be_disabled_per_relationship:
2) Error: TestDefaultAutosaveAssociationOnNewRecord#test_autosave_new_record_on_belongs_to_can_be_disabled_per_relationship:
3) Error: TestDefaultAutosaveAssociationOnNewRecord#test_autosave_new_record_on_has_one_can_be_disabled_per_relationship:
```
 - **SerializedAttributeTest#test_serialized_attribute_works_under_concurrent_initial_access**
``` 
Expected: [1, 1, 1, 1]
  Actual: ["1", 1, 1, 1]
```

**Comment by matthewd** [comment]
> **SerializedAttributeTest#test_serialized_attribute_works_under_concurrent_initial_access**
> ```
> Expected: [1, 1, 1, 1]
>   Actual: ["1", 1, 1, 1]
> ```

This one's intermittently failing on master (since I added it in #29216). It needs to be addressed, but isn't a worry for this particular effort.

**Comment by zenspider** [comment]
This is *FANTASTIC*. I've done this several times in the past on rails but never got it fully cleaned up.

If you see a problem but can't fix it, PLEASE post the command and especially the seed (@alexcameron89) so that it can be reproduced by others.

**Comment by alexcameron89** [comment]
Here are a few I've been able to bisect. I'll continue to work on them, but feel free to also tackle them if you'd like:
```
ARCONN=mysql2 bin/test --seed 25364 test/cases/*test.rb -n \
"/^(?:PrimaryKeyIntegerTest#(?:test_primary_key_with_serial_integer_are_automatically_numbered)|PersistenceTest::SaveTest#(?:test_save_touch_false))$/"
```

```
ARCONN=postgresql bin/test --seed 43618 test/cases/*test.rb -n \
"/^(?:FixturesResetPkSequenceTest#(?:test_resets_to_min_pk_with_default_pk_and_sequence)|DatabaseStatementsTest#(?:test_create_should_return_the_inserted_id|test_exec_insert|test_insert_should_return_the_inserted_id))$/"
```

```
bin/test --seed 61689 test/cases/*test.rb -n \
"/^(?:InheritanceComputeTypeTest#(?:test_inheritance_new_with_subclass_as_default)|CalculationsTest#(?:test_pluck_loaded_relation))$/"
```

**Comment by yahonda** [comment]
Opened #29331 for this failure I have not fixed yet but found which tests conflicts with it.

* ActiveRecord::ConnectionAdapters::PostgreSQLAdapterTest#test_only_reload_type_map_once_for_every_unknown_type, seed: 46798
```
1 instead of 2 queries were executed.
Queries:
SELECT NULL::anyelement.
Expected: 2
  Actual: 1
```

**Comment by yahonda** [comment]
#29332 has been opened to address #29331

**Comment by kaspth** [comment]
What's the latest on this? Anybody got PRs I need to look into?

I just pushed 3 commits, so there should be new builds to look for failures on 😊

**Comment by yahonda** [comment]
#29380 needs reviews.

**Comment by y-yagi** [comment]
@kaspth Can you give an opinion on #29354? It is related to the failure of railties's test.

**Comment by y-yagi** [comment]
@kaspth Would you please merge with master?(Because the test failed due to the correspondence effect of Arel 9.0.0.alpha).

**Comment by alexcameron89** [comment]
I've reworked https://github.com/rails/rails/pull/29375 a bit to make it a little more clean.

**Comment by rafaelfranca** [comment]
@y-yagi done

**Comment by y-yagi** [comment]
@rafaelfranca Thanks!

**Comment by kaspth** [comment]
Looks like the build is green! I'll rebuild a couple times just to check.

**Comment by kaspth** [comment]
Twice green! Running it again.

**Comment by kaspth** [comment]
Green 3 times in a row: let's try it out! Thanks for all the help here ❤️

**Comment by yahonda** [comment]
Great! 

@kaspth Do you think we will need `minitest-bisect` after merging `unlock-minitest` to `master`?
I think it was added to help us to find order dependent test cases but I believe we have fixed them.

Ref: https://github.com/rails/rails/commit/142195051268abd6d5f38c17eaf1acd72a5b058d

**Comment by kaspth** [comment]
I've been thinking we should keep a bit for now. So it's already bundled in case there's a failure we need to debug.

On the other hand maybe we shouldn't ever remove it. If an order dependent test failure accidentally got introduced (say it starts to trigger after a PR is merged), the first thing we'd have to reach for is reproducing with minitest-bisect.

**Comment by yahonda** [comment]
Understood. Let's keep it for a while and will see if it gets some order dependent test case appears.

**Pull request merged**
