### PR TITLE
Change assert interface to add explicit message

### PR DESCRIPTION
**Pull request by gmalette**
This PR is probably unfinished. I just want to know if this is something that would be considered. 
I think that the `assert predicate, message` interface is less than ideal, for the very simple reason that it's the same interface as `assert_equal x, y`. I believe that interfaces should be designed to prevent programmers from making mistakes, especially as easy to oversee as these. 

This is a backport of a patch we made in our codebase on the [`assert`](https://github.com/rails/rails/compare/master...gmalette:add-message-to-assert#diff-cbef10f252bdfb6975e32c5b9c32a84bR88) method.  It replaces the 2nd parameter by an explicit `message` kwarg. When I applied the patch in our codebase, I found a lot `assert` that really wanted to be `assert_equal`, many of which caused failing tests. 

Rails fared better, and only had a [single occurence](https://github.com/rails/rails/compare/master...gmalette:add-message-to-assert#diff-f88fb76eaf514ad473e66c250b95b6c4R1031) of `assert` wanting to be an `assert_equal`. Well, I'm not sure if it was supposed to be or not; the test name isn't descriptive, and changing it to an `assert_equal` makes the test fail.

### CODE REVIEW

**Comment by gmalette** [comment]
@arthurnn

**Comment by rafaelfranca** [comment]
I agree with it but can we try to get it on minitest first?

**Comment by rafaelfranca** [comment]
@zenspider care to give us your input about it?

**Comment by blowmage** [comment]
Can you imagine all the existing tests that this will break? Is it so inconceivable that regular folks write tests with custom messages?

```ruby
def test_user_has_a_profile
  admin = users(:admin)
  assert admin.profile, "Something is wrong with the fixtures. The admin user record should have a profile record."
end
```

Every assert method (except for `assert_raises`) has an optional `msg` argument. This is the contract made with the users. This change will break every existing test that uses custom messages (as most well written asserts should).

Some will say that this is a problem only because those who wrote the tests did not make sure it fails before it passes. I am sympathetic to that thinking, and yet you have demonstrated some real world examples where well meaning folks have run into this. However, I think there must be a better solution than changing the optional `msg` argument from an object to a hash.

**Comment by gmalette** [comment]
> Is it so inconceivable that regular folks write tests with custom messages

I'm sure they do, but I also know that they write `assert ExpectedClass.name, ActualClass.name` thinking their fingers wrote `assert_equal`

> I think there must be a better solution than changing the optional msg argument from an object to a hash

I'm very open to suggestions, but I can't think of one that will both prevent mistakes and not break syntax.

**Comment by zenspider** [comment]
(copied from seattlerb/minitest#553):

I think that's a backwards-incompatible change for a very very small edge case and not much improvement overall. I'm not willing to accept it into minitest and I think accepting this into rails (or anything else) is a _very bad idea_. The size of your diff is, I believe, proof of how bad an idea this is. You're asking _every_ rails app that uses minitest to change their tests.

Instead, why not scan for the case you're trying to prevent?

**Comment by zenspider** [comment]
(Quick & Dirty) example of such a scanner: https://gist.github.com/zenspider/e4251e90cd908696682d

This points out the single occurance in rails (which @tenderlove just deleted in response, btw). I assume it'll have similar impact on the codebase that stimulated this PR. There might be some noise and adjustments to be made in the two consts to reduce the noise.

I can release this as a gem.

**Comment by gmalette** [comment]
@arthurnn it was your idea to backport this. Minitest will not accept it, what now?

**Comment by rafaelfranca** [comment]
A scanner job on CI would catch our problems too, and I prefer that over patching a core library, but I'm only few weeks working on that codebase so I'm sure I know nothing.

Rails already have a lot of customizations on top of minitest and we are trying to reduce that since they already gave us a lot of trouble when upgrading versions of the lib. Also I don't want to have a dialect that only works on Rails (besides the `assert_not`, that I also don't like). That said I don't want to accept this here.

Thank you for working on this and let me know if you think it is a good idea to use the scanner and want help with it.

**Comment by zenspider** [comment]
Sooo... I _should_ release this as a gem?

Can we get a couple people to use this on their codebases and report back what sort of results they got? and how the experience was for them?

**Comment by rafaelfranca** [comment]
In our application it will not point anything now because we are already using the `message: 'foo'` API. And even if we stop to use it we will not have any case where it is being incorrectly used, so I'd say that there is no need to release this as a gem. Thanks! :heart:

**Comment by zenspider** [comment]
You could run it on the revision prior to your PR?

**Comment by gmalette** [comment]
(pasting part of my comments on minitest)

> You could run it on the revision prior to your PR?

I did; it found 86 issues but I have no way to know how they intersect with the actual problems other than spelunking over a significant amount of PRs, which quite frankly I will not do.

> I can release this as a gem.

Feel free to do so, but keep in mind that it should run inline when running the tests for a single file, otherwise you're just slowing down devs.

as @rafaelfranca mentioned, it's very unlikely that we'll change our codebase, so don't do it for us

**Comment by arthurnn** [comment]
> I did; it found 86 issues but I have no way to know how they intersect with the actual problems other than spelunking over a significant amount of PRs, which quite frankly I will not do.

Really good point @gmalette, I've ran this on GitHub sourecode, and found a bunch of cases, but lots of those are things like, ` assert person.save, person.errors.full_messages.to_s` . So that would still be caught by the script, but they are valid. 
So, indeed it is a bit harder then we think to identify those problems.

Honestly, I like the `message:` api better, because it is more explicit.

**Comment by zenspider** [comment]
No, more explicit (and DRY) is to write assert_save

**Pull request closed without merging**
