### PR TITLE
Fixed bug in basic auth credential decoding when password contains colon

### PR DESCRIPTION
**Pull request by denisenkom**

### CODE REVIEW

**Comment by repinel** [comment]
@denisenkom Could you add a test? Thanks

**Comment by denisenkom** [comment]
Sure, will add.

**Comment by denisenkom** [comment]
I was wrong, split(':', 2) does work correctly, closing this request.
Sorry about that, should have created test from the very beginning.

**Comment by repinel** [comment]
@denisenkom Maybe we should have a test for this case anyway.

**Comment by denisenkom** [comment]
Yeah, that is a good idea, will add

**Pull request closed without merging**
