### PR TITLE
[ci skip] Doc: Using Models in Your Migrations

### PR DESCRIPTION
**Pull request by vaibhavatul47**
Documentation: Using Models in Your Migrations

Rails Guides till version 4.1, had a documentation on how to safely use Models
in migration files. Such documentation should be preserved as they help in
knowing what is the recommended way of solving a particular problem.

To quote Rails guide @ version 4.1 ( [link](https://guides.rubyonrails.org/v4.1/migrations.html#using-models-in-your-migrations) )

> When creating or updating data in a migration it is often tempting to use one
> of your models. After all, they exist to provide easy access to the underlying
> data. This can be done, but some caution should be observed.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Thank you for the pull request but we removed that section before 4.2 exactly because we don't recommend using models in migrations.

**Comment by rafaelfranca** [comment]
See https://github.com/rails/rails/pull/19746#issuecomment-93567859

**Comment by RKushnir** [comment]
> we don't recommend using models in migrations.

@rafaelfranca  Do you mean it's not recommended to use models in migrations at all, or not recommended to define local model classes(as per old guide)?

**Comment by rafaelfranca** [comment]
it's not recommended to use models in migrations at al

**Pull request closed without merging**
