### PR TITLE
Remove unused Arel visitors in the code base

### PR DESCRIPTION
**Pull request by kamipo**
This removes ibm_db, informix, mssql, oracle, and oracle12 Arel visitors
which are not used in the code base.

Actually oracle and oracle12 visitors are used at oracle-enhanced
adapter, but now I think that those visitors should be in the adapter's
repo like sqlserver adapter and the dedicated Arel visitor
(https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/master/lib/arel/visitors/sqlserver.rb),
otherwise it is hard to find a bug and review PRs for the oracle
visitors (e.g. #35838, #37646), since we don't have knowledge and
environment enough for Oracle.

cc @yahonda

### CODE REVIEW

**Review by rafaelfranca — APPROVED** [review]
Arel is private API, but I think this needs a changelog entry, so the adapter developers know about that.

**Comment by simi** [comment]
I understand and welcome this change, but it would be really nice to actually get in sync with adapter authors and ensure they could prepare new release including visitor before this is released as well on Rails side. Also temporarily it would be developer friendly to raise error on request to use one of those removed visitors.

**Comment by rafaelfranca** [comment]
It is good to alert the adapters authors but I don't think we should be waiting them to respond. Even more that we don't know all of them. This is a project decision, like any other API we provide. Specially arel as it is private API.

I don't think an error is necessary if all actually maintained adapters change their code, which will be required anyway.

We already alerted the oracle adapter maintainers, now we need to alert the mssql adapter https://github.com/rails-sqlserver/activerecord-sqlserver-adapter

**Comment by kamipo** [comment]
Note that sqlserver adapter is not using Arel bundled mssql visiter but using its own visitor.

https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/master/lib/arel/visitors/sqlserver.rb

**Comment by yahonda** [comment]
I am fine this change, actually, I need some time to migrate Arel code into Oracle enhanced adapter. It may take couple of weeks.

**Comment by simi** [comment]
Anyone any idea about ibm_db and informix usage?

**Comment by simi** [comment]
I have opened issues at both informix and ibm_db related repos I found.

https://github.com/ibmdb/ruby-ibmdb/issues/98
https://github.com/santana/activerecord-informix-adapter/issues/6

**Review by simi — APPROVED** [review]

**Comment by yahonda** [comment]
FYI Oracle enhanced adapter supports this change https://github.com/rsim/oracle-enhanced/pull/2002

**Pull request merged**
