### PR TITLE
Add "Testing View Partials" section to the Testing Guides

### PR DESCRIPTION
**Pull request by seanpdoyle**
### Motivation / Background

While the `ActionView::TestCase` class isn't marked with a `:nodoc:` comment to indicate that it's internal to Rails, there isn't much content in the guides that explains how to test view partials.

Libraries like [view_component](https://github.com/ViewComponent/view_component/) have [built-in support for testing](https://viewcomponent.org/guide/testing.html), including Capybara integration.

While `ActionView::TestCase` already integrates with `rails-dom-testing`, that integration could be better documented. Additionally, it wouldn't take much for consuming applications to mimic the ViewComponent testing experience for their Action View Partials.

### Detail

First, link to the "Testing Rails Applications" page from the `ActionView::TestCase` class documentation.

Next, add a "Testing View Partials" section to the guides that expands upon the variety of tooling available to tests that inherit from `ActionView::TestCase`. In that section, cover topics like:

* the `render` helper method
* the `rendered` helper attribute reader
* calls to `assert_select` with attribute placeholders
* the `document_root_element` helper method
* integration with Ruby's Pattern Matching
* opportunities to integrate with Capybara

### Additional information

Additionally, add test coverage that exercise the examples shared in the new section, including:

* Calls to `assert_select` that utilize attribute placeholders
* Ruby 3.0's Pattern Matching
* Integration with Capybara

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by seanpdoyle** [comment]
@skipkayhil if you're available, I would appreciate some review on these changes.

**Comment by seanpdoyle** [comment]
@zzak since they're largely documentation based, would you be interested in reviewing these changes?

**Review by adrianna-chang-shopify — APPROVED** [review]
Doc changes look good on my end!

**Comment by seanpdoyle** [comment]
@adrianna-chang-shopify thank you for the review! If you're interested, https://github.com/rails/rails/pull/49194 is related and in need of review.

**Comment by zzak** [comment]
@seanpdoyle I'm not always able to read every notification from GitHub, in the future you can ping me on discord/slack/email :pray:

**Pull request merged**
