### PR TITLE
Include ActiveModel::Naming instead of extend

### PR DESCRIPTION
**Pull request by amiel**
This is basically #15889, but incorporating the feedback from @rafaelfranca.

### CODE REVIEW

**Comment by magikid** [comment]
@amiel it looks like this has already been merged in. Is that the case?

**Comment by rafaelfranca** [comment]
@magikid Just part of it.

@amiel this needs a rebase now that #15889 was merged.

**Comment by amiel** [comment]
I'm sorry, I think I should have closed this one after #15889 was merged. Is this still desired?

**Comment by rafaelfranca** [comment]
Yeah, I guess it is fine without it

**Comment by amiel** [comment]
Sorry for not cleaning up after myself :)

**Pull request closed without merging**
