### PR TITLE
make calling simple methods on collection proxies fast

### PR DESCRIPTION
**Pull request by grosser**
I understand that this is a horrible PR, but it unblocks our rails upgrade ... hopefully kicks of a move/discussion in a better direction ...

basically what I'm seeing is a massive slowdown upgrading from rails 3.2 to 4.2 / 5.0 for included or pre-loaded associations

```
GC.enable; GC.disable; x = Array.new(100).map { Ticket.all.to_a }.flatten; Benchmark.realtime { x.each{ |t| t.ticket_field_entries.to_a; nil } } # 2600 AR objects total

3.2: 0.23s
4.2: 1.12s
```

which I dug down into and found to be the `loaded?` call which only delegates to `@association.loaded?` taking up all the time since the association already includes :ticket_field_entries ... to make this faster I made the merge lazy ... which is ugly ... but brings us back down to 0.3s for this usecase ... leaving this here in case anyone has a better idea how to improve this ...

### CODE REVIEW

**Comment by maclover7** [comment]
Can you do a bisect and see where the slowness was introduced?

**Comment by kamipo** [comment]
This is a known issue. https://github.com/rails/rails/commit/c86a32d7451c5d901620ac58630460915292f88b#commitcomment-5384529

**Comment by grosser** [comment]
... and no known fix ?

**Comment by grosser** [comment]
FYI monkey-patch when using rails 4 + deprecated finders:

```Ruby
  # https://github.com/rails/rails/pull/25789
  ActiveRecord::Associations::CollectionProxy.class_eval do
    def initialize(klass, association) #:nodoc:
      @association = association
      super klass, klass.arel_table
      @merged = false
    end

    needs_merge = ActiveRecord::Relation.instance_methods - Array.instance_methods - ActiveRecord::Associations::CollectionProxy.instance_methods(false)
    needs_merge.each do |m|
      define_method(m) do |*args, &block|
        unless @merged
          @merged = true
          merge! @association.scope(nullify: false)
        end
        super(*args, &block)
      end
    end
  end

  # once deprecated finders are removed, move this up into the class_eval
  ActiveRecord::Associations::CollectionProxy::InterceptDynamicInstantiators.prepend(Module.new do
    # methods might be defined on the association ... so get them
    def method_missing(name, *args, &block)
      if @merged
        super
      else
        @merged = true
        merge! @association.scope(nullify: false)
        send(name, *args, &block)
      end
    end
  end)
```

**Comment by grosser** [comment]
FYI @tenderlove @arthurnn @jonleighton ... https://github.com/rails/rails/issues/14033

**Comment by matthewd** [comment]
We should do something about this.

I don't think it was always the case, but certainly now, most methods (as demonstrated by `to_a` here) do *not* need the merge... so we're now often paying its cost when we otherwise would not do it at all.

**Comment by grosser** [comment]
simplified the change a bit

**Comment by grosser** [comment]
updated the patch to be more selective and only patch the methods the merger actually changes

**Comment by grosser** [comment]
previous iteration only left `:uniq_value, :substitute_values, :joined_includes_values, :reordering_value, :reverse_order_value, :instance_values` not overwritten and was a lot more complicated + needed to be updated on every change to merged ... this should be better ... and reduces overhead for all other methods

**Comment by grosser** [comment]
so yeah all kind of hacky and ideal solution is to undo the `< Relation` and make it delegate to the relation on demand ...

**Comment by kamipo** [comment]
Closing in favor of #25877.

**Pull request closed without merging**
