### PR TITLE
Explicitly require AS/HWIA

### PR DESCRIPTION
**Pull request by yui-knk**
This file depends on AS/HWIA, so add `require`.

### CODE REVIEW

**Comment by yui-knk** [comment]
I am not sure why sometimes there are **not** `require` in files which depends on other Rails components? I think `require` on file which use components, is there any manner to handling dependency?

**Comment by arthurnn** [comment]
Theoretically, files should be self-contained and have all dependencies they need. But in reality thats not what we have right now, and TBH, would cause lots of noise/work I would say to make sure we require all dependencies needed in each file.
That said, my rule, is usually, if you can import that file by itself, it should have the dependencies needed, that happens mostly for AS things. So you can require only `active_support/hash_with_indifferent_access` and that should work!

Did you find this problem because you tried to include the enum file by itself and it failed?

**Comment by yui-knk** [comment]
I agree with that 

> files should be self-contained and have all dependencies they need

I find this problem, when I read the enum file. I did not try to include the file by itself.

If make to require all dependencies is best, let's make it happen :)
But it is too noisy and treated as cosmetic changes, we should not do until require is needed.

I think your rule, most AS should have the dependencies needed and other many file (AR, AC) etc not,  is reasonable.

BTW it is better to write some guidelines to [rails guide](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#write-your-code).

**Comment by arthurnn** [comment]
@yui-knk yeah, honestly AR kinda requires AS a lot, so I dont think someone would be requiring the enum file, so I think this is , indeed, somehow cosmetic. 
About the rails guide, I am not sure if we should add it, TBH thats the first time I encounter this, so maybe adding there for 1% cases would just be noise. 
Also, the rule might even be something else that I am not aware. @rafaelfranca @fxn might know better.

**Comment by rafaelfranca** [comment]
No, we should not require all dependencies in the files. We setup the common dependencies of the frameworks on its top files like `https://github.com/rails/rails/blob/master/activerecord/lib/active_record.rb`. If you want to use one specific file of Active Record you need to require `active_record` first. It is the same even with Active Support.

For this specific case HWIA is already require at `activerecord/lib/active_record/core.rb` and Enum is included there so we don't need to require it again.

**Pull request closed without merging**
