### PR TITLE
Remove invalid :size option from ActionText migration

### LINKED ISSUE #46232: Action Text Migration is broken in branch main
### Steps to reproduce
```bash
 rails new test_app
 # modify the Gemfile, set Rails to `gem "rails", github: 'rails/rails'`
 rails action_text:install
 rails db:mirgate
```

### Expected behavior
No errors

### Actual behavior
```
Unknown key: :size. Valid keys are: :limit, :precision, :scale, :default, :null, :collation, :comment, :primary_key, :if_exists, :if_not_exists
.../test_app/db/migrate/20221013084208_create_action_text_tables.action_text.rb:9:in `block in change'
.../test_app/db/migrate/20221013084208_create_action_text_tables.action_text.rb:7:in `change'
```

### System configuration
**Rails version**:
 Edge Rails
**Ruby version**:
3.1.2

### PR DESCRIPTION
**Pull request by andrewn617**
Resolves https://github.com/rails/rails/issues/46232

### Motivation / Background

Recently [a change was introduced on main](https://github.com/rails/rails/pull/46178) to raise an error if a migration is run with invalid column options. This is causing `CreateActionTextTables` to error because it is using an invalid `:size` option.

### Detail

I removed the invalid option from the migration.

### Additional information

To replicate the issue:

```
rails new test_app
# modify the Gemfile, set Rails to `gem "rails", github: 'rails/rails'`
rails action_text:install
rails db:mirgate
```

The issue is fixed if you run these steps but point the gemfile at this branch.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] There are no typos in commit messages and comments.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Feature branch is up-to-date with `main` (if not - rebase it).
* [x] Pull request only contains one commit for bug fixes and small features. If it's a larger feature, multiple commits are permitted but must be descriptive.
* [ ] Tests are added if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.
* [x] PR is not in a draft state.
* [ ] CI is passing.

### CODE REVIEW

**Comment by hmcguire-shopify** [comment]
I'm not that removing the option completely is correct. `size:` was added specifically in 1745e905a314754b65eabc5fa28671c80796f09f and appears to be a valid option for mysql. Is the issue just with sqlite3?

**Comment by andrewn617** [comment]
@hmcguire-shopify That is something I started wondering about too. The work to add these validations doesn't seem to be aware of what adapter is being used, and just looks to me like it has a hard coded list. You are right different adapters can have different options, so maybe the issue is with the validation.

**Comment by rubyrider** [comment]
I think this pr will break the purpose for mysql to use the limit which @hmcguire-shopify already mentioned about this: https://github.com/rails/rails/commit/1745e905a314754b65eabc5fa28671c80796f09f

**Comment by yahonda** [comment]
Thanks for opening a pull request. The original issue #46232 has been closed via #46241 .

**Pull request closed without merging**
