### PR TITLE
Define `sanitize_sql_for_order` for AR and use it inside `preprocess_…

### PR DESCRIPTION
**Pull request by yui-knk**
…order_args`

This commit follows up of 6a6dbb4c51fb0c58ba1a810eaa552774167b758a.

### CODE REVIEW

**Comment by pixeltrix** [comment]
@yui-knk please can you add a CHANGELOG entry since we are adding a method to the public API for Active Record.

**Comment by yui-knk** [comment]
Is it better to define `sanitize_sql_for_order` as public API?
I do not intend to add this method as public API because the purpose of this commit is only refactoring.

**Comment by pixeltrix** [comment]
I think it's okay to add to the sanitization API since we have them for conditions passed to `where` so it makes sense.

**Comment by yui-knk** [comment]
@pixeltrix Added CHANGELOG!

**Comment by pixeltrix** [comment]
@yui-knk thanks!

**Comment by yui-knk** [comment]
@pixeltrix Thanks for your review :yellow_heart:

**Pull request merged**
