### PR TITLE
Update gem bug report templates to 7.1

### PR DESCRIPTION
**Pull request by skipkayhil**

### CODE REVIEW

**Review by zzak — APPROVED** [review]
What do you think about setting the `load_defaults` to 7.1 in these as well?

**Comment by skipkayhil** [comment]
> What do you think about setting the `load_defaults` to 7.1 in these as well?

I definitely think it's a good idea, although it's interesting because some of these templates don't configure a Rails app at all. Maybe they should all be doing that?

**Comment by zzak** [comment]
It's hard to say for sure because not every bug will need to initialize an app, but there are definitely bugs hiding in the seams there.

**Comment by yahonda** [comment]
Backport to the `7-1-stable` branch via https://github.com/rails/rails/commit/eae36727756466769a52d0b71d80cce5120e4bf5 .

**Pull request merged**
