### PR TITLE
Allow DebugExceptions interceptors to abort default backtrace error log

### LINKED ISSUE #31502: Rails 5.1 ActionDispatch::DebugExceptions inappropriate fatal logging for RoutingError
Hi,

When a routing error occurs our logs are getting filled with 4x FATAL errors for each actual Routing error that occurs. These errors are not actually fatal and I don't believe flagging them as such is appropriate.

### Expected behavior
- Single log entry per error (like in Rails 4.2):
```
[2017-12-16 01:23:00] FATAL   ActionController::RoutingError (No route matches [GET] "/foo"): actionpack (4.2.8) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
```
- Change level of the routing error, it isn't fatal if the application still lives after it happens.

### Actual behavior
```
F, [2017-12-15T09:44:39.181709 #4658] FATAL -- :
F, [2017-12-15T09:44:39.181820 #4658] FATAL -- : ActionController::RoutingError (No route matches [GET] "/foo"):
F, [2017-12-15T09:44:39.181847 #4658] FATAL -- :
F, [2017-12-15T09:44:39.181874 #4658] FATAL -- : actionpack (5.1.4) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
```

### System configuration
**Rails version**: 5.1.4

**Ruby version**: 2.4.2

### PR DESCRIPTION
**Pull request by wjordan**
### Summary

`DebugExceptions` interceptors were recently added in #23868, which allow callbacks to be attached to errors returned by the middleware, to support adding extra error-logging hooks.

This PR extends these interceptors to support aborting the default error-logging implementation when desired by throwing `:abort`.

Prior to this PR, the only way to prevent backtrace logging of application exceptions and routing errors (which are converted to `ActionController::RoutingError` "No route matches [GET]" by this middleware), without affecting other aspects of the error-page rendering behavior, was to monkey-patch the `DebugExceptions` middleware directly (see roidrage/lograge#252 for my best effort at this).

This PR makes it easier to `throw :abort` from a registered interceptor to disable the default backtrace logger directly:

```ruby
ActionDispatch::DebugExceptions.register_interceptor do |request, exception|
  [ ... custom error logging ... ]
  throw :abort # Disable default error logging
end
```

### Other Information

- Fixes #31502 (or at least provides an acceptable public-API workaround for the issue).

- My own use-case for this PR is a need to reduce the size of Rails application log by disabling the default backtrace logs written by application/routing errors.

- The implementation includes (`ActiveSupport::Callbacks`) and wraps the default error-logging in a `log_exception` callback, which is what supplies the `:abort`-catching logic.

- This PR also fixes a related bug where an exception thrown by an interceptor caused the original error backtrace to be logged multiple times (see the provided "bad interceptors doesn't duplicate log error" test which fails without this PR and passes with it).

### CODE REVIEW

**Comment by gsamokovarov** [comment]
@wjordan I don't think we should stop the interceptors. They are not logging hooks, but plugin hooks.

Say you have a custom interceptor running before the raven gem interceptor. If you are to stop the interceptors, no errors will be sent to the error tracker. Every interceptor should have a say and do what's it intended to do, otherwise, no plugin author will trust the interceptors API and we'll be back to monkey patching.

**Comment by lucaong** [comment]
One example of why this would be very useful is the following:

Currently, the error logging logic is handled by the private `log_error` method in `ActionDispatch::DebugExceptions`. The default implementation calls the logger several times:

```ruby
logger.fatal "  "
logger.fatal "#{exception.class} (#{exception.message}):"
log_array logger, exception.annoted_source_code if exception.respond_to?(:annoted_source_code)
logger.fatal "  "
log_array logger, trace
```

In some applications, one might have a custom logger that formats and reports logs to some service, say as JSON objects. In this case it would be much better to log the error name and the stack trace as one single call to `logger.fatal`, so that the external service receives one error single event with all the information. One actual example of such services is Stackdriver, the default logger application on the Google Cloud: https://cloud.google.com/error-reporting/docs/formatting-error-messages

Currently (correct me if I am missing something), the only available option to achieve this is to patch `ActionDispatch::DebugExceptions` re-implementing the private method `log_error`, which is definitely not desirable.

Ideally, one should be able to configure how an unhandled exception gets logged, or to intercept the exception and prevent the default logging behavior.

**Comment by antoniobg** [comment]
Any update on this?

**Comment by maknahar** [comment]
Any plan to support this?

**Comment by gsamokovarov** [comment]
The interceptors shouldn't be stopped, because they are to be used by plugins which need to act on the exception and everyone should get their turn to dispatch their action. That's the contract.

As for the logging, I don't have a strong opinion, but if you need to override it, introducing the whole Active Support Callbacks machinery is an overkill.

**Comment by rafaelfranca** [comment]
Closing because like @gsamokovarov said we don't want the interceptors to be stoped. About the disabling of logging you can configure exceptions you want to silence now 238d36715ede0952a227c8ec7b6e6e086c1f19d1.

**Pull request closed without merging**
