### PR TITLE
Support for composite foreign key

### LINKED ISSUE #49135: Broken composite foreign key support
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, id: false, force: true do |t|
    t.string :author
    t.integer :number
  end

  create_table :comments, force: true do |t|
    t.string :post_author
    t.integer :post_number
  end
end

class Post < ActiveRecord::Base
  self.primary_key = [:author, :number]
  has_many :comments, foreign_key: [:post_author, :post_number]
end

class Comment < ActiveRecord::Base
  belongs_to :post, foreign_key: [:post_author, :post_number]
end

class BugTest < Minitest::Test
  def test_composite_fk_association
    post = Post.create!(author: 'John Doe', number: 1)
    post.comments << Comment.create!

    assert_equal 1, post.comments.count
    assert_equal 1, Comment.count
    assert_equal post.author, Comment.first.post_author
    assert_equal post.number, Comment.first.post_number
  end
end

```

### Expected behavior
A Comment should be created, that belongs to the created Post, using the composite foreign key of the former to reference the composite primary key of the latter.

### Actual behavior
An exception is triggered:
ActiveRecord::CompositePrimaryKeyMismatchError: Association Post#comments primary key ["author", "number"] doesn't match with foreign key [:post_author, :post_number]. Please specify query_constraints, or primary_key and foreign_key values.

### System configuration
**Rails version**: edge 7.1.0-alpha

**Ruby version**: 3.2.2

### PR DESCRIPTION
**Pull request by brunoenten**
### Motivation / Background

This Pull Request fixes #49135 

When adding an association to a model with a composite primary key, it's currently impossible to use an array with the foreign_key parameter.
The resulting exception suggests using the query_constraints parameter to specifies the foreign keys.

### Detail

The value of the foreign_key parameter was turned into a string by calling .to_s on it. This PR detects if the value is an array, and  treat it the same way as the query_constraints parameter.
The result is that composite foreign key can be specified using the foreign_key parameter, which seems more rational.

### Additional information

I've looked at all tests covering composite primary key (CPK) and it seems some code could be refactored. I'd like to sync with the main maintainer of this feature before writing tests covering this PR.

### Checklist

Before submitting the PR make sure the following are checked:

* [X] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [X] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [ ] Tests are added or updated if you fix a bug or add a feature.
* [X] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by brunoenten** [comment]
@nvasilevski @gmcgibbon what do you think?

**Comment by eileencodes** [comment]
Hi @brunoenten thanks for the PR!

The way the feature was designed is intentional, you must use the `query_constraints` argument rather than passing an array to `foreign_key`. It wasn't accidental that we didn't allow an array for the foreign key option. I'm going to close this since Rails is behaving as intended.

**Comment by nvasilevski** [comment]
Hey @brunoenten, I wanted to provide some context to why we end up using `query_constraints:` option instead of extending `foreign_key`

`foreign_key:` and `query_constraints:` are indeed very similar options and behind the scenes configure the same property of the association but:
- `query_constraints` is always-an-array value so it provides better maintainability behind the scenes
Presence of `query_constraint` s option serves as a boolean flag and indicates that the association is ready to use `query_constraints` feature. (options[:foreign_key].is_a?(Array) could also be used as a boolean flag but we are trying to get rid of `is_a?` checks)

We definitely don't want both `foreign_key` and `query_constraints` to both accept composite identifiers since it will create ambiguity on which one to use. While now we can say that `query_constraints` should be used to define a composite foreign key

Eventually Rails may end up combining `foreign_key` and `query_constraints` into a single option but only when the feature becomes more mature and we have more context on how the feature is being used by applications.

One more argument in favor of `query_constraints` is that we anticipate tenant-based application to utilize it to scope queries per tenant key and configuration like `query_constraints: [:tenant_key, :associated_object_id]` will make more sense than `foregin_key: [:tenant_key, :associated_object_id]`

But as I pointed out, I do see API evolving over the time, we just don't see now as the best time to do it

**Comment by brunoenten** [comment]
Hey @nvasilevski
Thank you so much for the detailed explanation. Much appreciated.
Background: Senior Postgresql developer.

I understand the reasoning behind query_constraints / foreign_key.
Speaking of experience, the main reason to use composite keys is in situation where there is no need for an additional id column.

Example, from an open source accouting software I'm currently working on, there's an account table like this:

```sql
CREATE TABLE accounting.accounts (
    tenant_id uuid,
    number integer,
    label text,    
) PRIMARY KEY (tenant_id , number)
```

And the ledger using these accounts:

```sql
CREATE TABLE accounting.ledger_entries (
    tenant_id uuid,
    ledger_entry_id uuid,
    account_number integer,
    ...
) FOREIGN KEY (account_number, tenant_id )
  REFERENCES accounting.accounts ("number", tenant_id)
```

Clearly there's no need to add a separate id column to accounts. `(tenant_id, number)` tuple is unique and makes for a perfect identity.

> One more argument in favor of query_constraints is that we anticipate tenant-based application to utilize it to scope queries per tenant key and configuration like query_constraints: [:tenant_key, :associated_object_id] will make more sense than foregin_key: [:tenant_key, :associated_object_id]

I can tell that most tests focus on this use case. But if `associated_object_id` is already unique, adding tenant_key won't accomplish much. It will merely enforce some security scoping, but with consequences on performances due to bad schema design.

Last commit gets the same result without using is_a?. Again, all existing tests pass with this modification.

Let me know if you're interested in discussing this further. I certainly don't want to impose my views and I could just move that to a gem.

**Comment by eileencodes** [comment]
Using `query_constraints` options is equivalent to us implementing `foreign_key` to take an array (which would then mean having 2 ways to do the same thing in Active Record).

It's just a public API difference, it doesn't break the use case that you're talking about. For what it's worth, most of the time Rails will try to guess the query constraints so you don't even need to set either the foreign key or query constraints options unless they don't match what Rails expects by default. 

At this time we're not open to changing the API, but if you find a bug in the current `query_constraints` option, we're happy to take a look and try to fix it.

**Comment by brunoenten** [comment]
Ok thank you for the clear position. I'll just move that to a gem then.

**Pull request closed without merging**
