### PR TITLE
Move assets precompile (and version) to an initializer

### PR DESCRIPTION
**Pull request by matthewd**
sprockets-rails 2.1 (since rails/sprockets-rails#84) needs the precompile list to be available in all environments.

I've left a comment behind in the old location, because:
- this is a common thing to change, so people will look in the old location through habit
- indicates a sensible course of action during `rake rails:upgrade`

### CODE REVIEW

**Comment by pranas** [comment]
@matthewd, sorry to bother a year later, but can you tell what was the reasoning to make this an initializer versus moving the config to ``application.rb``?

**Comment by matthewd** [comment]
@pranas [application.rb#L25](https://github.com/rails/rails/blob/master/railties/lib/rails/generators/rails/app/templates/config/application.rb#L25)

**Comment by pranas** [comment]
@matthewd ok, it wasn't your decision, but still do you have an idea why Rails suggests to use initializers instead of ``application.rb``?

**Comment by rafaelfranca** [comment]
@pranas because these configurations are not likely to change and we save application.rb to things we find that are important.

**Pull request merged**
