### PR TITLE
use `bin/test` in plugins guide [ci skip]

### PR DESCRIPTION
**Pull request by y-yagi**
`bin/test` can use the same API as the `bin/rails test`, since it is possible to run a flexible test than rake,
I think better to use a guide even `bin/test`.

### CODE REVIEW

**Comment by kaspth** [comment]
Thanks! I want to hold off a bit on this, because after reading this I find the inline reporting I added is pretty useless.

What do you think, @arthurnn @senny?

**Comment by senny** [comment]
@kaspth I agree about the inline reporting. It's pretty weird at the moment.

**Comment by kaspth** [comment]
I guess we could just enrich Minitest's existing output to make it appear inline and then have a rerun command.

**Comment by arthurnn** [comment]
Are you talking about the extra spaces ?

**Comment by kaspth** [comment]
@arthurnn I think this:

```
Error:
CoreExtTest#test_to_squawk_prepends_the_word_squawk:
NoMethodError: undefined method `to_squawk' for "Hello World":String
/path/to/yaffle/test/core_ext_test.rb:5:in `test_to_squawk_prepends_the_word_squawk'
```

is much more helpful than:

```
NoMethodError: undefined method `to_squawk' for "Hello World":String


bin/test /path/to/yaffle/test/core_ext_test.rb:4
```

:grin:

**Comment by arthurnn** [comment]
i see, yeah for sure. This current output is not ideal.

**Comment by kaspth** [comment]
Waiting on the output design changes in #22698 :grin:

**Comment by y-yagi** [comment]
I was reflecting the updates of #22698

**Comment by senny** [comment]
@y-yagi thank you :yellow_heart:

**Comment by y-yagi** [comment]
Thanks!

**Pull request merged**
