### PR TITLE
Correctly show deprecation warning for incompatible migrations

### PR DESCRIPTION
**Pull request by prathamesh-sonpatki**
r? @matthewd

### CODE REVIEW

**Comment by prathamesh-sonpatki** [comment]
@matthewd This will show the warning correctly, but only problem is it's driven by `AS::Deprecation.behavior`. So in development, it's emitted in `develoment.log`. Do you think we should just `puts` it like other migration methods?

**Comment by vipulnsward** [comment]
@prathamesh-sonpatki I think, we should. We should also add a test for this behaviour. It was missed.

**Comment by prathamesh-sonpatki** [comment]
Added test case.

On Tue, Feb 2, 2016 at 12:26 PM, Vipul A M <notifications@github.com> wrote:

> @prathamesh-sonpatki <https://github.com/prathamesh-sonpatki> I think, we
> should. We should also add a test for this behaviour. It was missed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rails/rails/pull/23419#issuecomment-178411065>.
>



-- 
./prathamesh
 GITHUB <https://github.com/prathamesh-sonpatki> Blog
<http://prathamesh-sonpatki.github.com>

**Comment by prathamesh-sonpatki** [comment]
@matthewd Fixed failing tests. Please review.

**Pull request merged**
