### PR TITLE
fix docs for Engines

### PR DESCRIPTION
**Pull request by kuldeepaggarwal**

### CODE REVIEW

**Comment by senny** [comment]
@kuldeepaggarwal why these changes? It shouldn't be adding a `.blorgh` part. I just checked with latest `master` and it didn't for me...

**Comment by kuldeepaggarwal** [comment]
@senny 

I created a fresh engine and new rails app inside the rails application(local rails folder) using the following command:

STEPS TO CREATE ENGINE:

```shell
$ rails plugin new test-engine --mountable --skip-bundle
$ cd test-engine
```

change the Gemfile and test-engine.gemspec file as:

# Gemfile
```ruby
source 'https://rubygems.org'

# Declare your gem's dependencies in test-engine.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gem 'arel', github: 'rails/arel', branch: 'master'
gem 'rails', path: '../'
gemspec

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use a debugger
# gem 'byebug', group: [:development, :test]
```

# test-engine.gemspec
```ruby
# commented the below line in the gemspec file.
# s.add_dependency "rails", "~> 5.0.0.alpha"
```

and execute 
```shell
$ bundle install
$ rails g model User name
```

STEPS TO CREATE TEST APP USING Engine

```shell
rails new test_app --skip-bundle
```

modify the Gemfile

```ruby
source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'arel', github: 'rails/arel', branch: 'master'
gem 'rails', path: '../'
gem 'test-engine', path: '../'
# gem 'rails', '5.0.0.alpha'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end
```

now executed:
```shell
$ bundle
$ rake railties:install:migrations
```

I got the output from the above command:

```
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from rescue in <class:Exception> at /Users/kuldeepaggarwal/.rvm/gems/ruby-2.2.2/gems/web-console-2.1.2/lib/web_console/integration/cruby.rb:37)
Copied migration 20150531130821_create_test_users.test_engine.rb from test_engine
```


Please let me know if I have done anything wrong.

**Comment by senny** [comment]
@kuldeepaggarwal my bad, I was running the wrong task :sweat:. I still feel the output is kinda weird. I'll have a look tomorrow.

**Comment by senny** [comment]
@kuldeepaggarwal double checked the behavior. Everything seems fine. Thanks for the edits :yellow_heart:

**Pull request merged**
