### PR TITLE
ActiveStorage merges env specific services with root ones

### PR DESCRIPTION
**Pull request by santib**
### Summary

I recently upgraded our app to Rails 6.1 and was surprised that if I defined a `config/storage/production.yml` my `config/storage.yml` wasn't being loaded at all.

I think I find it surprising because the behavior of `config/environments/[env].rb` is more like "augmenting" default values set in `config/application.rb`, so I was expecting something similar for ActiveStorage.
Moreover, the wording in the guides say
> Configuration files that are environment-specific will take precedence

But with take precedence I understand that it has higher priority but not that it will completely discard configs declared in `config/storage.yml`

So yeah, let me know your thoughts on this @georgeclaghorn 😄

### CODE REVIEW

**Comment by georgeclaghorn** [comment]
What’s the case where you have services you use in multiple environments? IIRC, the reason we didn’t bother with merging was because I couldn’t think of a case where it was needed—we don’t use development services in production, for example.

**Comment by santib** [comment]
> What’s the case where you have services you use in multiple environments? IIRC, the reason we didn’t bother with merging was because I couldn’t think of a case where it was needed—we don’t use development services in production, for example.

By default we use S3 for prod and disk for dev, but we can optionally use in dev a specific S3 bucket for development by changing an ENV VAR. The thing is that we use staging data in our dev envs, so if we want to get the latest attachments it's easier to use a clone of the staging S3 bucket than to download the staging S3 bucket + transform all the files (because of the directory structure of the DiskService). Furthermore, sometimes we might want to check things in dev env with a more realistic storage system than the disk, for example to make sure that the bucket is configured correctly for CORS (direct uploads).

**Comment by zzak** [comment]
@santib I think this makes sense, but you could also just copy the parts from `config/storage` you need to a separate environment right? Is there a reasonable workaround here?

**Comment by santib** [comment]
> @santib I think this makes sense, but you could also just copy the parts from `config/storage` you need to a separate environment right? Is there a reasonable workaround here?

@zzak Yes, copy/pasting the config in the different environment works, it's just that I think it would be more maintainable if I can have the shared definitions in `config/storage.yml` and only use `config/storage/[env].yml` for specific services. 

In any case it's not such big of a deal I guess. It was a bit surprising at the beginning when doing the Rails upgrade on our app, but you aren't usually changing these files so..

**Comment by zzak** [comment]
@santib In this case, I'm partial to just documenting the current behavior. I realize its surprising but maybe we can consider removing the docs and prioritize changing the behavior until later.

**Pull request closed without merging**
