### PR TITLE
ActionView 4.2 changelog: 'precidence' -> 'precedence'

### PR DESCRIPTION
**Pull request by jonatack**
[skip ci]

### CODE REVIEW

**Comment by kaspth** [comment]
Thanks. In the future please add the skip to the commit message otherwise Travis will run the merge commit I think.

**Comment by jonatack** [comment]
Thanks! The skip was in the commit message body; I believe Travis did not run.

**Comment by jonatack** [comment]
I didn't mean to add it to the comment, which probably caused the confusion :smile:

**Comment by kaspth** [comment]
Ah right, didn't catch that. All good then :smile:

**Comment by kaspth** [comment]
It seems travis did run: https://travis-ci.org/rails/rails/builds/54980071. I usually just prepend [ci skip] to the commit message so it's guaranteed to be in the title.

**Comment by jonatack** [comment]
Wow! :neckbeard: Thanks for the info, I'll keep that in mind :)

**Pull request merged**
