### PR TITLE
Changed welcome#index page overall look and feel

### PR DESCRIPTION
**Pull request by wazery**
I re-created a new pull request because I mistakenly force pushed to my master branch. Here is the closed old PR, for a reference https://github.com/rails/rails/pull/17813.

### CODE REVIEW

**Comment by wazery** [comment]
Can this PR merged now as Rails 5 development is started?

**Comment by arthurnn** [comment]
can you post a screenshot of the new page in here? also rebase this against latest master?
thanks

**Comment by wazery** [comment]
@arthurnn Will do ASAP.

**Comment by wazery** [comment]
Here is a screenshot for the new page:
screen shot 2015-04-28 at 3 42 41 pm

I rebased against latest master, thanks @arthurnn for taking the time to review and merge.

**Comment by rafaelfranca** [comment]
It doesn't feel right to me to have the same layout as the rails guides for the info page. I believe it was not made for that page. For me the guides layout is to heavy to the info page.

@dhh what do you think about this one?

**Comment by dhh** [comment]
Yeah, I appreciate the effort, but I don't think it's worth it either.

**Comment by Davidslv** [comment]
How is that layout so heavy? He added a few lines of css and html and looks good.
In my opinion is way better than having this, I don't even bother to read because it's **ugly**

screen shot 2015-05-07 at 10 19 20

**Comment by dhh** [comment]
Guess we all have different aesthetics.

**Pull request closed without merging**
