### PR TITLE
Don't clear view cache during concurrent requests

### LINKED ISSUE #40613: ActionView is raising errors in the test environment after upgrading to Rails 6 (ActionView::Template::Error: undefined method `_app_views_xxxxx)
### Expected behavior

ActionView template compilation is reliably executed in test and dev environments.

### Actual behavior

Tests (and sometimes the dev server) fail intermittently with exceptions like

```
Exception: ActionView::Template::Error: undefined method `_app_views_layouts__dmca_html_slim___3627166963330339270_108200' for #<#<Class:0x00007fac1acfaa58>:0x00007fac1ecec170>
Did you mean?  _app_views_layouts__header_nav_html_slim__4252095906685398667_109480
```

In our existing Rails app that we recently upgraded from 5.2.4 to 6.0.3.4, we're consistently facing build failures with the described exception. Rerunning a few times will sometimes make the issue go away.

### System configuration
**Rails version**:
Rails 6.0.3.4

**Ruby version**:
ruby 2.7.2p137

---

Unfortunately, I can't figure out steps to reproduce this on a new app :(, but I have done some diving into the ActionView code to try to figure out what's going on. 

I'm running a file with controller tests, and when I run the tests with a particular seed, I'm able to consistently reproduce the error.  Using pry-debugger and `puts`, I've worked out that ActionView template compilation seems to be the issue. For whatever reason, the `ActionView::Template` for the file has the `@compiled` flag set to `true`, but the `method_name` generated by the template has not been defined on the `view`.

When I step through the code here, https://github.com/rails/rails/blob/master/actionview/lib/action_view/template.rb#L152-L154 , I get to a state that I don't understand:

```ruby
    def render(view, locals, buffer = ActionView::OutputBuffer.new, add_to_stack: true, &block)
      instrument_render_template do
        compile!(view)
       # At this point, the template should have been compiled, and @compiled is set to true. But `view.respond_to?(method_name)` returns `false`. ??????
        view._run(method_name, self, locals, buffer, add_to_stack: add_to_stack, &block)
      end
    rescue => e
      handle_render_error(view, e)
    end
```
I've found two things that seem to stop the error.

First is adding a line before the `compile!` call above:

```ruby
    def render(view, locals, buffer = ActionView::OutputBuffer.new, add_to_stack: true, &block)
      instrument_render_template do
        @compiled = false
        compile!(view)
        view._run(method_name, self, locals, buffer, add_to_stack: add_to_stack, &block)
```

For obvious reasons, this forces ActionView to (re)compile the template, and this prevents the error from being raised.

Second, I've found that slowing down our first call to `render` seems to stop the issue from happening. In the controller test I mentioned above, I'm testing `FoosController#show`. `FoosController#show` explicitly calls `render "show"` (for unrelated reasons). If I insert a `sleep(0.1)` call right before the `render "show"` line, the issue disappears. If I then change that `sleep` call to `sleep(0.0)`, the error returns. I don't know what that means, but it seems like a race condition.

@jhawthorn , I know you were working on the template compilation recently. Do you have any ideas what could be happening here?

### PR DESCRIPTION
**Pull request by jhawthorn**
This is an attempt to fix https://github.com/rails/rails/issues/40613, where when there are concurrent requests and reloading is enabled it's possible for the template cache to be cleared at the same time that a request is running. 

This PR updates `ActionView::CacheExpiry` to hold a lock while inside the executor (ie. inside a request) and to only clear caches when that is done.

This is done using `Concurrent::ReadWriteLock`. This allows any number of parallel requests to hold the read lock, but once we detect a change and begin to acquire the write lock, all future requests will be blocked.

I don't know that this is safe to do 😓 (though it at least doesn't affect production environments). If there was for example a long running request this could block future requests when reloading occurs until that request finished, but I don't know what guarantees we expect to provide developers w/r/t that. If this isn't acceptable, the lock could maybe be somewhere more granular, but it would be ideal if it worked here.

cc @fxn @matthewd for reloading/concurrency advice 🙇‍♂️

### CODE REVIEW

**Comment by fxn** [comment]
Hey John! @matthewd implemented the [RW lock in AS](https://github.com/rails/rails/blob/main/activesupport/lib/active_support/concurrency/share_lock.rb) used by the [this higher level API](https://github.com/rails/rails/blob/main/activesupport/lib/active_support/dependencies/interlock.rb) and related framework logic. He has the vision, let's see if he has feedback, otherwise I'll gladly dig into it.

**Comment by matthewd** [comment]
I kinda wish this could lean on the "main" reloader, both from a cleanliness/single-point-of-responsibility sense, and out of general concern around duelling locks*. But forcing a full class reload in response to a view change is unnecessary, and that API isn't currently set up to support partial/segmented reloads. 

Setting aside that nested-locks consideration, the general notion of blocking future requests is fair to me: that's what the reloader does. I guess the only interesting distinction is that -- unlike the case of class reloading -- it's pretty reasonable for a given request to never touch the view cache, making it possibly-unfortunate for such a request to be blocked (or indeed, to be blocking).

Is it reasonable for Action Cable connections to survive across a purge of the view cache? My first thought is that could well be a feature, but I wonder how hard someone would have to try to be unpleasantly surprised there (which I guess means manually resolving a view path -- or pre-rendering a view? -- and storing the result in an instance variable).


\* at minimum, all the lock acquisitions here should `permit_concurrent_loads` -- the easy way for that to otherwise fail is two requests, first one in the read lock, second one blocking on the write lock [because of a view change in between], and then the first request blocks on the load lock [which is unavailable because the second request holds read on the loading interlock]. I don't have failure modes for the other acquisitions (which admittedly only conflict with short-running blocks) in my head right now, but I'd still hedge toward assuming it's possible.

(Using c-r's ReadWriteLock is a fine and good thing -- the class reloader has specialised requirements that [last I checked] make it infeasible; while I split AS::C::ShareLock from AS::D::Interlock to make it easier to reason about the abstract implementation, I don't think there's any advantage to preferring it over the external alternative in other locations, especially given c-r is already a universal dependency.)

**Comment by jhawthorn** [comment]
Thanks Matthew. That all makes sense.

> I kinda wish this could lean on the "main" reloader

Agree. Would love to revisit this in the future and investigate making the reloader more granular.

> the general notion of blocking future requests is fair to me: that's what the reloader does

😌

As for only some requests needing the view cache, I feel that's _probably_ okay. This only happens in dev mode and I think folks are usually going to render views after changing views. I wouldn't want to add logic within the render calls themselves for fear of slowing them down. Maybe in the future we'll have some sort of "render context" that could lock/clear cache.

> at minimum, all the lock acquisitions here should permit_concurrent_loads -- the easy way for that to otherwise fail is two requests, first one in the read lock, second one blocking on the write lock [because of a view change in between], and then the first request blocks on the load lock [which is unavailable because the second request holds read on the loading interlock]. I don't have failure modes for the other acquisitions (which admittedly only conflict with short-running blocks) in my head right now, but I'd still hedge toward assuming it's possible.

👍 I've wrapped the entire check/clear procedure in `permit_concurrent_loads`, which should cover all lock acquisitions.

**Review by kaspth — APPROVED** [review]
Looks ok to me, but I'm not in all the details that @matthewd is.

**Comment by yjukaku** [comment]
Thanks for your work on this, @jhawthorn ! 🎉  🚀

**Pull request merged**
