### PR TITLE
Mailer preview now uses `url_for` to fix links to emails for apps runnin...

### LINKED ISSUE #19092: ActionMailer Preview doesn't generate correct links on Rails apps loaded on subdirectories.
Currently, an app that runs on `localhost/app1`, doesn't generate correct mailer preview urls for `localhost/app1/rails/mailer` since the URLs are hard-coded to the root path, ie: `localhost/rails/mailer`

I would expect to see the URLs use relative paths and know about the correct root of the Rails app.

### PR DESCRIPTION
**Pull request by remomueller**
...g on a subdirectory, closes #19092.

### CODE REVIEW

**Comment by pixeltrix** [comment]
Looks like the build was affected by the bug @eileencodes mentioned in https://twitter.com/eileencodes/status/572047555875479552

**Comment by pixeltrix** [comment]
Wonder whether we should add named routes for this with an `_` prefix?

**Comment by remomueller** [comment]
If named routes fixes the urls, that'd be fine too, I'm however not sure if it is needed for this as Rails favors convention over configuration. Not sure if there's a present need or use case for making it a named route. Thoughts?

**Comment by remomueller** [comment]
Anything else needed for this? It'd be great to see this in Rails as I've had a solution ready for [almost a year now](https://github.com/rails/rails/pull/14663) to get this fixed. Thanks!

**Comment by remomueller** [comment]
Hi all, I rebased the code so that it can be automatically merged, it looks like it's failing due to an unrelated bug in rails at the moment though.

**Comment by rafaelfranca** [comment]
Backported as 037e1f0 and 3e9b34e

**Pull request merged**
