### PR TITLE
Only select known attributes on a model

### LINKED ISSUE #33793: Possible bug with `ActiveRecord::AttributeMethods#attributes` and new columns
### Steps to reproduce

1. Launch a rails console
2. In another process run a migration to add a column to an existing table
3. Back in the console, inspect the output of `ActiveRecord::AttributeMethods#attributes`

[Script](https://gist.github.com/BrentWheeldon/023cfb846d327e4c52d74b83c8fd1f9b)

### Expected behavior
It does not include the new column (since including the new column makes `add_column` non-zero-downtime-safe)

### Actual behavior
The new column is included

### System configuration
**Rails version**: master

**Ruby version**: 2.5.1p57

### More context

I'm not sure if this is desired behaviour, or a bug. I'd be happy to work on a PR to fix this if folks agree that there is an issue here.

We noticed this issue during a deploy which added a new column to an existing table. We migrate the DB and still have all of our processes running the old version of the code and then do a rolling restart on our processes once the migrations are complete. As soon as the new column was added we started seeing errors because we have code that essentially does `ModelClass.new(model_instance.attributes.except(:id, :foo))` to duplicate records.

### PR DESCRIPTION
**Pull request by BrentWheeldon**
### Summary

This fixes an issue where `add_column` becomes non-zero-downtime safe. If you have a deploy process that runs migrations before reloading the rails processes you’ll temporarily be in a state where the database table has extra columns that the model doesn’t know about yet. During this window in time doing something like `Computer.new(Computer.last.attributes.except(:id))` will fail with an `ActiveModel::UnknownAttributeError` because `#attributes` would include the new column, but the model’s column cache doesn’t know about it.

Fixes #33793

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Thank you for the pull request. We can't always use the columns that we know because it is slower than `SELECT *`. See #33616.

**Comment by rafaelfranca** [comment]
Sorry, pressed the wrong button, should not have close yet.

**Comment by BrentWheeldon** [comment]
@rafaelfranca thanks for the extra context! I've taken an alternative approach here - does this seem more acceptable? If we do see a way forward here I'll clean up the PR description and squash the commits down.

And if this still isn't a good solution, I'm happy to take this in whatever direction necessary.

**Comment by matthewd** [comment]
Yeah, that doesn't work either: it's a documented behaviour that you can select additional columns and they'll show up as attributes on the model.

I'm not sure I see a general problem to solve here... the specific case you've described sounds like you want `dup`.

**Comment by BrentWheeldon** [comment]
> it's a documented behaviour that you can select additional columns and they'll show up as attributes on the model.

Ah I messed up my test case when I was trying to validate that and incorrectly assumed it just didn't work that way.

I agree that we should be using `dup` here rather than passing `attributes` around, and we're starting to tidy things up in that direction, but I was surprised when we started seeing the errors during a deploy since I knew that there is column metadata caching going on.

Happy to close this out since it seems there's not a fix here that's compatible with the broader workings of things.

Thanks for the quick feedback!

**Pull request closed without merging**
