### PR TITLE
doc: replace build method with create

### PR DESCRIPTION
**Pull request by mjh-sakh**
### Summary

Seems that method `@article.comments.build` is equivalent to `@article.comments.build` in the context so the proposal is to use the `create` method as it makes it clear why we have the `create` method in `comments_controller` with a call of `comments.create`. This `build` method confuses.

### CODE REVIEW

**Comment by p8** [comment]
Calling `create` here is a bit unexpected, as it will save an empty comment to the database.
So every time you visit this page a new empty comment is saved.
The `create` method in the `CommentsController` is only called when the form is submitted.
`@article.comments.build` will instantiate a new `Comment`.

When you create a form with the following:
```
    <%= form_with model: [ @article, @article.comments.build ] do |form| %>
```
it will create something like:
```
<form action="/articles/1/comments" accept-charset="UTF-8" method="post">
```
When the form is submitted it will be handled by `CommentsController#create`.

**Comment by mjh-sakh** [comment]
Hi @p8, thank you for the details! Really appreciate it. May I clarify the described behavior: 
> every time you visit this page a new empty comment is saved

I naturally tried out the proposed change before creating this PR and I did not observe that empty comments were created. Probably there is some protection? 

I understood the logic: `form_with model` calls out `build` when a new form is generated, although we don't define `build` method in the controller, unlike `new` for the article controller. Btw, why? This has created my struggle as I was not able to find that `build` method associated. And then HTTP POST is associated with and invokes `create` method of the controller.

**Comment by p8** [comment]
Hi @mjh-sakh,
The `build` method is unrelated to the controller methods.
It's defined on the association: https://api.rubyonrails.org/classes/ActiveRecord/Associations/CollectionProxy.html#method-i-build
`build` is also aliased to `new` so you could do:
```
<%= form_with model: [ @article, @article.comments.new ] do |form| %>
```

But in this form there is need for having the article set on the comment.
It would be a lot clearer if we just use `Comment.new` instead:
```
<%= form_with model: [ @article, Comment.new ] do |form| %>
```
This is also what is used on the RubyOnRails homepage video:
image

Does this make sense?
Can you change the PR to use `Comment.new`?

**Comment by mjh-sakh** [comment]
@p8, yes, let me give it another try. But before I proceed: with the `Comment.new` approach, will it be a call to the controller method and therefore such should be created?

**Comment by p8** [comment]
@mjh-sakh 

The `Comment.new` approach will end up the create action of the CommentsController.

For example, I can do the following in the console:
```
   article = Article.create(title: "Hi")
   app.url_for(article, Comment.new)
   # => "http://www.example.com/articles/1/comments"
```
When a form POSTs to that URL it will end up in the create action.

If you do a GET request to http://www.example.com/articles/1/comments/new
you could show a form to create a new comment. But that is outside the scope
of the "Getting Started" guide.

**Pull request closed without merging**
