### PR TITLE
Add missing extend in docs

### PR DESCRIPTION
**Pull request by deivid-rodriguez**

### CODE REVIEW

**Comment by arunagw** [comment]
I think this example works without extending this.

Have you tried?

**Comment by deivid-rodriguez** [comment]
No, I didn't, I just read this: https://github.com/rails/rails/blob/master/activemodel/lib/active_model/errors.rb#L17

Shall I remove that line instead?

**Comment by rafaelfranca** [comment]
Both are right. The documentation on the class is saying it is required because we depends on `human_attribute_name`. The README is defining `human_attribute_name` so there is no need for `Naming`

**Comment by deivid-rodriguez** [comment]
Thanks and sorry for the noise.

**Pull request closed without merging**
