### PR TITLE
Fix race condition in websocket stream write

### PR DESCRIPTION
**Pull request by tinco**
### Summary

It is not safe to write to a socket from two threads at the same time. If multiple threads are spawned that perform `ActionCable.server.broadcast` there is a chance their calls to `ActionCable::Connection::Stream` will overlap and their data gets mingled and corrupted. This will usually result in an InvalidUTF8 exception in the browser, which will subsequently kill the websocket connection.

This patch simply puts a write lock around the socket so it can never be called concurrently. I don't expect this will not have any significant performance overhead.

I also put the lock around stream_send, though I'm not 100% certain this is also necessary.

Do you require tests for concurrency problems like this?

To reproduce the error, clone this repository: https://github.com/phusion/actioncable-slow-client, run it in Passenger using `passenger start --min-instances=1 --max-pool-size=2` and visit `localhost:3000`. In the inspector you will see the connection dying every few frames.

p.s.: really sorry that we started performance tests so late, I actually started this on Tuesday thinking I'd make sure Passenger works correctly with Rails 5rc2 but we didn't figure out what was going on until today.

### CODE REVIEW

**Comment by tinco** [comment]
Alright, so I was a little curious why this happens so I browsed through ruby/ruby's `io.c` to find out what `IO#write` does exactly, and it's a straight up single call to `write(2)`. The `write(2)` manpage says that its atomic only for *regular* files, so not for sockets. There's a SO page here: [Is it safe to issue blocking write calls on the same tcp socket from multiple threads?](http://stackoverflow.com/questions/1457256/is-it-safe-to-issue-blocking-write-calls-on-the-same-tcp-socket-from-multiple) in which someone explains Linux *tries* to do atomic writes but fails in certain circumstances, and OSX and BSD don't guarantee anything. 

I'm not sure why this particular test I did makes it break so reliably, but there you have it.

I guess it might be up to discussion whether Rails should allow ActionCable.server.transmit to be called from different threads, is that something you guys are opinionated about?

**Comment by tinco** [comment]
Just a small aside, on MRI if you set `io.sync = true` it will also make it have a mutex and be thread safe, but that behavior isn't documented so we can't know for sure JRuby or Rubinius etc do this.

**Comment by matthewd** [comment]
Backported in 7340459cdb4edbd70f2b86fcd6015a2b182cc529

**Comment by raggi** [comment]
"I'm not sure why this particular test I did makes it break so reliably, but there you have it."

It wrote more than pipe buf.

**Pull request merged**
