### PR TITLE
Update guides/source/engines.md [ci skip]

### PR DESCRIPTION
**Pull request by yhirano55**
### Summary

- Inserted system_test ones into scaffolding logs

### CODE REVIEW

**Comment by kamipo** [comment]
Is this only place that missing system test logs?
We have many `bin/rails generate` lines in the guides.

```
% git grep -n 'bin/rails generate' guides
guides/source/action_mailer_basics.md:38:$ bin/rails generate mailer UserMailer
guides/source/action_mailer_basics.md:172:$ bin/rails generate scaffold user name email login
guides/source/action_view_overview.md:32:$ bin/rails generate scaffold article
guides/source/active_job_basics.md:53:$ bin/rails generate job guests_cleanup
guides/source/active_job_basics.md:62:$ bin/rails generate job guests_cleanup --queue urgent
guides/source/active_record_migrations.md:126:$ bin/rails generate migration AddPartNumberToProducts
guides/source/action_mailer_basics.md:38:$ bin/rails generate mailer UserMailer
guides/source/action_mailer_basics.md:172:$ bin/rails generate scaffold user name email login
guides/source/action_view_overview.md:32:$ bin/rails generate scaffold article
guides/source/active_job_basics.md:53:$ bin/rails generate job guests_cleanup
guides/source/active_job_basics.md:62:$ bin/rails generate job guests_cleanup --queue urgent
guides/source/active_record_migrations.md:126:$ bin/rails generate migration AddPartNumberToProducts
guides/source/active_record_migrations.md:143:$ bin/rails generate migration AddPartNumberToProducts part_number:string
guides/source/active_record_migrations.md:159:$ bin/rails generate migration AddPartNumberToProducts part_number:string:index
guides/source/active_record_migrations.md:177:$ bin/rails generate migration RemovePartNumberFromProducts part_number:string
guides/source/active_record_migrations.md:193:$ bin/rails generate migration AddDetailsToProducts part_number:string price:decimal
guides/source/active_record_migrations.md:212:$ bin/rails generate migration CreateProducts name:string part_number:string
guides/source/active_record_migrations.md:236:$ bin/rails generate migration AddUserRefToProducts user:references
guides/source/active_record_migrations.md:279:$ bin/rails generate model Product name:string description:text
guides/source/active_record_migrations.md:307:$ bin/rails generate migration AddDetailsToProducts 'price:decimal{5,2}' supplier:references{polymorphic}
guides/source/command_line.md:95:$ bin/rails generate
guides/source/command_line.md:121:$ bin/rails generate controller
guides/source/command_line.md:147:$ bin/rails generate controller Greetings hello
guides/source/command_line.md:197:$ bin/rails generate model
guides/source/command_line.md:220:$ bin/rails generate scaffold HighScore game:string score:integer
guides/source/command_line.md:365:$ bin/rails generate model Oops
guides/source/command_line.md:553:`bin/rails generate task` command.
guides/source/engines.md:322:$ bin/rails generate scaffold article title:string text:text
guides/source/engines.md:469:$ bin/rails generate model Comment article_id:integer text:text
guides/source/generators.md:29:$ bin/rails generate
guides/source/generators.md:35:$ bin/rails generate helper --help
guides/source/generators.md:60:$ bin/rails generate initializer
guides/source/generators.md:66:$ bin/rails generate initializer --help
guides/source/generators.md:88:$ bin/rails generate generator initializer
guides/source/generators.md:108:$ bin/rails generate initializer --help
guides/source/generators.md:136:$ bin/rails generate initializer core_extensions
guides/source/generators.md:175:$ bin/rails generate scaffold User name:string
guides/source/generators.md:236:$ bin/rails generate generator rails/my_helper
guides/source/generators.md:263:$ bin/rails generate my_helper products
guides/source/generators.md:291:$ bin/rails generate scaffold Article body:text
guides/source/generators.md:393:$ bin/rails generate scaffold Comment body:text
guides/source/getting_started.md:257:$ bin/rails generate controller Welcome index
guides/source/getting_started.md:330:controller generator (`bin/rails generate controller Welcome index`).
guides/source/getting_started.md:410:$ bin/rails generate controller Articles
guides/source/getting_started.md:655:$ bin/rails generate model Article title:string text:text
guides/source/getting_started.md:674:As we've just seen, `bin/rails generate model` created a _database migration_ file
guides/source/getting_started.md:1523:$ bin/rails generate model Comment commenter:string body:text article:references
guides/source/getting_started.md:1650:$ bin/rails generate controller Comments
guides/source/plugins.md:241:$ bin/rails generate model Hickwall last_squawk:string
guides/source/plugins.md:242:$ bin/rails generate model Wickwall last_squawk:string last_tweet:string
guides/source/testing.md:73:$ bin/rails generate model article title:string body:text
guides/source/testing.md:597:$ bin/rails generate test_unit:model article title:string body:text
guides/source/testing.md:614:$ bin/rails generate system_test users
guides/source/testing.md:704:$ bin/rails generate system_test articles
guides/source/testing.md:788:$ bin/rails generate integration_test user_flows
guides/source/testing.md:824:$ bin/rails generate integration_test blog_flow
guides/source/testing.md:912:$ bin/rails generate scaffold_controller article title:string body:text
guides/source/testing.md:928:$ bin/rails generate test_unit:scaffold article
```

**Comment by yhirano55** [comment]
@kamipo This one.
> guides/source/engines.md:322:$ bin/rails generate scaffold article title:string text:text

**Comment by yhirano55** [comment]
This is actual logs (in mountable engine dir).

```
$ bin/rails g scaffold article title:string text:text
      invoke  active_record
      create    db/migrate/20170815112555_create_blorgh_articles.rb
      create    app/models/blorgh/article.rb
      invoke    test_unit
      create      test/models/blorgh/article_test.rb
      create      test/fixtures/blorgh/articles.yml
      invoke  resource_route
       route    resources :articles
      invoke  scaffold_controller
      create    app/controllers/blorgh/articles_controller.rb
      invoke    erb
      create      app/views/blorgh/articles
      create      app/views/blorgh/articles/index.html.erb
      create      app/views/blorgh/articles/edit.html.erb
      create      app/views/blorgh/articles/show.html.erb
      create      app/views/blorgh/articles/new.html.erb
      create      app/views/blorgh/articles/_form.html.erb
      invoke    test_unit
      create      test/controllers/blorgh/articles_controller_test.rb
      invoke    helper
      create      app/helpers/blorgh/articles_helper.rb
      invoke      test_unit
      invoke  test_unit
      create    test/application_system_test_case.rb
      create    test/system/articles_test.rb
      invoke  assets
      invoke    js
      create      app/assets/javascripts/blorgh/articles.js
      invoke    css
      create      app/assets/stylesheets/blorgh/articles.css
      invoke  css
      create    app/assets/stylesheets/scaffold.css
```

**Comment by kamipo** [comment]
I meant that you've included similar change in #30246, so I suspect that we have missing logs in another places (at least I've found it in https://github.com/rails/rails/blob/master/guides/source/generators.md).

**Comment by yhirano55** [comment]
Oh, I see. I'll pick up.

**Comment by yhirano55** [comment]
I've checked these contents, and fixed it.

- [x] guides/source/action_view_overview.md:32:$ bin/rails generate scaffold article
- [x] guides/source/action_mailer_basics.md:172:$ bin/rails generate scaffold user name email login
- [x] guides/source/command_line.md:220:$ bin/rails generate scaffold HighScore game:string score:integer
- [x] guides/source/engines.md:322:$ bin/rails generate scaffold article title:string text:text
- [x] guides/source/generators.md:175:$ bin/rails generate scaffold User name:string
- [x] guides/source/generators.md:291:$ bin/rails generate scaffold Article body:text
- [x] guides/source/generators.md:393:$ bin/rails generate scaffold Comment body:text
- [x] guides/source/testing.md:912:$ bin/rails generate scaffold_controller article title:string body:text

**Pull request merged**
