### PR TITLE
Get travis build passing

### PR DESCRIPTION
**Pull request by composerinteralia**
~Just messing around with travis at the moment to see if I can sort out the failing railties suite~

Hoping for lots of green dots

### CODE REVIEW

**Comment by composerinteralia** [comment]
With this change we end up using the pre-installed bundler 1.16.0. I think `av:ujs` and `railties` will now pass, but `guides` failed.

**Comment by composerinteralia** [comment]
I think skipping the bundler cache solved it. Going to squash this into one commit now.

**Comment by rafaelfranca** [comment]
I don't think we want to disable the bundler cache. The builds are already slow, I'm not excited to make all builds slower.

**Comment by composerinteralia** [comment]
Yeah, I hear you there.

Removing these
```
  - "travis_retry gem update --system"
  - "travis_retry gem install bundler"
```
got everything passing except `guides`.

**Comment by composerinteralia** [comment]
https://github.com/travis-ci/travis-ci/issues/9062

**Comment by composerinteralia** [comment]
Ah, it looks like `guides` fails when we don't update bundler because there is a problem with bundler 1.16.0. https://github.com/rails/rails/pull/31023 https://github.com/bundler/bundler/issues/6072 https://github.com/travis-ci/travis-ci/issues/8969

**Comment by eileencodes** [comment]
@composerinteralia yea it's not an accident that we've locked bundler on the travis builds. We did it because the guides test scripts don't pass and until bundler releases a fix for the bug that caused that we can't use it, unfortunately.  I'm going to close this for now and we'll keep an eye on bundler. Thanks for the PR.

**Comment by composerinteralia** [comment]
@eileencodes any other suggestions for getting the travis build passing?

**Comment by composerinteralia** [comment]
@y-yagi it looks like you were also digging into this. Did you come up with anything? Happy to help if I can!

**Comment by y-yagi** [comment]
I suspect this is Travis's bug. So I'm waiting for a response from Travis.

**Pull request closed without merging**
