### PR TITLE
Fix for Issue #17547

### PR DESCRIPTION
**Pull request by nengxu**
ActiveModel built-in validators should use the custom message passed in as :message option

### CODE REVIEW

**Comment by zamith** [comment]
@nengxu @egilburg Any news on this?

**Comment by nengxu** [comment]
@zamith It may require refactoring of validation / i18n. Sort of risky to do now. So I just used proc, not lambda, to bypass parameter number checking. So this pull request can be abandoned.

**Comment by zamith** [comment]
Ok. Thanks.

**Comment by arthurnn** [comment]
As far as I can tell. this is not a bug.
from @rafaelfranca response to the source issue https://github.com/rails/rails/issues/17547#issuecomment-71066698 , i think we should close this.

Thanks anyways for the contribution.

**Pull request closed without merging**
