### PR TITLE
Backport #25771 to 5-0-stable

### PR DESCRIPTION
**Pull request by kaspth**
#25771

### CODE REVIEW

**Comment by kaspth** [comment]
Stand back, @rails-bot ✋

I know what I'm doing 😎

**Comment by kaspth** [comment]
@rafaelfranca didn't even spot you merged this. Thanks! ❤️

**Comment by rafaelfranca** [comment]
I'm like a spy, quick and silent.

**Comment by kaspth** [comment]
lol!

**Pull request merged**
