### PR TITLE
Add missing `delegate :extending, to: :all`

### PR DESCRIPTION
**Pull request by kamipo**

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Should this be backported? Is it fixing any bug?

**Comment by kamipo** [comment]
If without this fix, `extending` in `scope` raises `NoMethodError` because the receiver in a scope is `klass`, not `relation`.

https://github.com/rails/rails/blob/v5.1.1/activerecord/lib/active_record/scoping/named.rb#L159

I think it is a strange because the receiver in `default_scope` and a scope on association is `relation`.

https://github.com/rails/rails/blob/v5.1.1/activerecord/lib/active_record/scoping/default.rb#L119
https://github.com/rails/rails/blob/v5.1.1/activerecord/lib/active_record/associations/association_scope.rb#L164

I feel like that the receiver in a scope should be `relation`, not `klass`.

```
% ARCONN=sqlite3 be ruby -w -Itest test/cases/scoping/named_scoping_test.rb -n test_model_class_should_respond_to_extending
Using sqlite3
Run options: -n test_model_class_should_respond_to_extending --seed 26816

# Running:

F

Finished in 0.047049s, 21.2544 runs/s, 21.2544 assertions/s.

  1) Failure:
NamedScopingTest#test_model_class_should_respond_to_extending [test/cases/scoping/named_scoping_test.rb:555]:
[OopsError] exception expected, not
Class: <NoMethodError>
Message: <"undefined method `extending' for #<Class:0x007fa342134718>\nDid you mean?  extend\n               extended">
---Backtrace---
/Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/dynamic_matchers.rb:20:in `method_missing'
/Users/kamipo/src/github.com/rails/rails/activerecord/test/models/comment.rb:32:in `block in <class:Comment>'
/Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/scoping/named.rb:163:in `instance_exec'
/Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/scoping/named.rb:163:in `block (2 levels) in scope'
/Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/relation.rb:337:in `scoping'
/Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/scoping/named.rb:163:in `block in scope'
/Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/relation/delegation.rb:92:in `public_send'
/Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/relation/delegation.rb:92:in `block in method_missing'
/Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/relation.rb:337:in `scoping'
/Users/kamipo/src/github.com/rails/rails/activerecord/lib/active_record/relation/delegation.rb:92:in `method_missing'
test/cases/scoping/named_scoping_test.rb:556:in `block in test_model_class_should_respond_to_extending'
---------------

1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
```

**Comment by rafaelfranca** [comment]
Thanks! I think it should be backported to 5.1

**Comment by rafaelfranca** [comment]
Backported in 0e1928a9a9

**Pull request merged**
