### PR TITLE
CSRF protection from cross-origin <script> tags

### PR DESCRIPTION
**Pull request by jeremy**
Extend `protect_from_forgery` to cover GET requests with JavaScript responses, protecting apps from cross-origin `<script>` embedding that may leak sensitive data.

TODO
- [x] Changelog
- [x] Update Security guide
- [x] Test actions that use `Accept` rather than an explicit format
- [x] Test actions that had neither .format nor `Accept`

### CODE REVIEW

**Comment by masonforest** [comment]
@harmdewit did you ever figure this out? I'm having the same issue.

**Comment by harmdewit** [comment]
I'm not sure what the issue was after this long time but putting this into our ApplicationController seemed to fix it

```ruby
+  def non_xhr_javascript_response?
+    unless request.get?
+      content_type =~ %r(\Atext/javascript) && !request.xhr?
+    end
+  end
```

**Comment by masonforest** [comment]
Thanks @harmdewit! :smiley:

**Comment by masonforest** [comment]
I'm not sure what is requesting format=\*/\* either.

Another solution I came up with is to reorder the `respond_to` formats:

So I changed this:

````ruby
respond_to do |format|
     format.js do
       ...
     end
     format.html
end
````

to this:

````ruby
respond_to do |format|
     format.html
     format.js do
       ...
     end
end
````

That way format=\*/\* will return html.

**Pull request merged**
