### PR TITLE
make UrlGenerationError message more generic (fixes #26470).

### LINKED ISSUE #26470: Misleading error when failing to match a routing constraint
### Steps to reproduce

1) Create a `resources` block with a a constraint on the named segment, for example:
```ruby
resources :reports, only: [:new, :create, :show], param: :reference, reference: /\d+/

```

2) Use a generate URL path helper, and provide a value for the named segment which fails to match the constraint:
```ruby
report_path(reference: "ABC123")
```

3) Receive a helpfully named error, but with a misleading piece of text saying that a required key is missing:
```plain
ActionController::UrlGenerationError: No route matches {:action=>"show", :controller=>"reports", :reference=>"ABC123"} missing required keys: [:reference]
```

### Expected behavior
The error message should state the route matches, but the value for the required key fails to match any constraints.

### Actual behavior
The error states that the key is missing, when it has been provided with a non-matching value.

### System configuration
**Rails version**: `Rails 4.2.7.1`
**Ruby version**: `ruby 2.3.0p0`

### PR DESCRIPTION
**Pull request by utilum**
This is the minimal solution. Would be nice to distinguish between missing keys and values that do not match constraints some day.

### CODE REVIEW

**Comment by utilum** [comment]
Hm... this last commit message referenced the pull request instead of the issue. Sorry. Should read: fixes #26470.

**Comment by pixeltrix** [comment]
Competing with #26555 - which approach do we want to take?

**Comment by utilum** [comment]
#26555 approach is more informative and addresses the ticket more fully.

**Comment by senny** [comment]
I'm closing this as #26555 was merged.

@utilum thanks for your time 💛

**Pull request closed without merging**
