### PR TITLE
Add syntax sugar as inverted exists? method

### PR DESCRIPTION
**Pull request by loqimean**
### Motivation / Background

This Pull Request has been created because we have so many syntax sugar, like for `present?` method we have `blank?`, and so on, so, that's would be really nice to add opposite method for a `exists?` instead of writing always `!`, or using unless

### Detail

This Pull Request changes adds just an inverted `exists?` method called `missing?`. So, it's really simple, but powerful change

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [ ] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by loqimean** [comment]
I'll update the changelog when you'll give me approve. So, that would be really cool!

**Comment by p8** [comment]
@loqimean You can add a test here: https://github.com/rails/rails/blob/6ca6aba66c23414db2fc17bab62e3cecda025f6d/activerecord/test/cases/finder_test.rb#L190

**Comment by loqimean** [comment]
> Why only in the encrypted relation? Also, there is no test, and please don't submit incomplete PR. There is a checklist because we want to see everything there ready before you submit the PR.

Oh, okay, sure, sorry, this PR is in progress and because of that's my first good PR, I need help with what and where I need to do. So I got you with this points and complete them. Thanks!

**Comment by rafaelfranca** [comment]
The feature makes sense to me as a general feature on relations. What was hard to understand in the PR is if that is what you are proposing or just as a feature on encrypted relations, which in this case I could not accept

**Comment by loqimean** [comment]
> The feature makes sense to me as a general feature on relations. What was hard to understand in the PR is if that is what you are proposing or just as a feature on encrypted relations, which in this case I could not accept

yeah, I propose this feature as a general feature on relations. So, I'll write specs and tag you when it's done

**Comment by loqimean** [comment]
@rafaelfranca Hi, I close this PR to provide a more clear PR with all required changes, check it please, thanks!
new PR #51203

**Pull request closed without merging**
