### PR TITLE
Address `warning: mismatched indentations` at test_factory_invalid_formatter

### PR DESCRIPTION
**Pull request by yahonda**
### Motivation / Background

This commit addresses the `warning: mismatched indentations` below.

```ruby
$ bundle exec ruby -w -Itest test/cases/query_logs_formatter_test.rb -n test_factory_invalid_formatter
test/cases/query_logs_formatter_test.rb:10: warning: mismatched indentations at 'end' with 'def' at 6
Using sqlite3
Run options: -n test_factory_invalid_formatter --seed 48904

.

Finished in 0.008743s, 114.3776 runs/s, 114.3776 assertions/s.
1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
$
```

### Detail

Follow-up #45081

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [ ] There are no typos in commit messages and comments.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Feature branch is up-to-date with `main` (if not - rebase it).
* [x] Pull request only contains one commit for bug fixes and small features. If it's a larger feature, multiple commits are permitted but must be descriptive.
* [ ] Tests are added if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.
* [x] PR is not in a draft state.
* [x] CI is passing.

### CODE REVIEW

**Review by byroot — APPROVED** [review]
👍 

I made some similar mistakes recently, I think we should raise on warnings in the test suite, e.g.: https://github.com/redis-rb/redis-client/blob/9fb715fb1a3e1caf91d9b7fa921532085d47c707/test/support/raise_warnings.rb

I'll likely open a PR for that later today.

**Comment by yahonda** [comment]
Thanks for the review and comment. Rails CI already runs Ruby runtime with -w option, the warning appeared. Catching this kind of warning is good idea. However, one of the problem is that Rails depend on other gems which also show warnings then aborting CI if any warning appears is too aggressive.

https://buildkite.com/rails/rails/builds/89900#018380e4-4332-4e31-9eb1-964c5fdb7b88/1066-1069

**Comment by byroot** [comment]
Yeah I know, but that's easily addressed by keeping a list of known unactionable warnings.

**Comment by byroot** [comment]
> Rails CI already runs Ruby runtime with -w option

Yeah, but that's not the case when you run tests locally, that how I introduced two warnings recently without even noticing.

Generally speaking nobody look at the CI output unless there is a failed test, so IMO soft-warnings on CI are rarely seen before merge.

**Comment by yahonda** [comment]
> Generally speaking nobody look at the CI output unless there is a failed test, so IMO soft-warnings on CI are rarely seen before merge.

Agreed. If there are some ways to skip known warnings, that should be good.

**Pull request merged**
