### PR TITLE
Remove .DS_Store

### PR DESCRIPTION
**Pull request by sachin21**
I found needless `.DS_Store` in this commit: https://github.com/rails/rails/commit/c640b2c2511153a248a943334255240e320a9413

### CODE REVIEW

**Comment by guilleiguaran** [comment]
good catch!!!

**Comment by sachin21** [comment]
Thank you for the quick response :smile:

**Comment by yui-knk** [comment]
Is it better to add `.DS_Store` to `.gitignore` ?

**Comment by sachin21** [comment]
@guilleiguaran @yui-knk How about this? https://github.com/rails/rails/pull/22696

**Comment by jeremy** [comment]
`.DS_Store` and other OS/editor-specific ignores belong in users' global `~/.gitignore` rather than duplicating them in every repository.

**Comment by sachin21** [comment]
I see. I will close that PR :smile:

**Comment by jeremy** [comment]
❤️

**Pull request merged**
