### PR TITLE
PostgreSQL/MySQL: Quote Arrays

### PR DESCRIPTION
**Pull request by WoH**
# Summary

Related issue: #35925 

Currently, AR does not support quoting (nested) arrays. This means queries such as 

```
Article.where('(title, text) IN (?)', [['title1', 'text1'], ['title2','text2']])
```

and similar queries where the argument contains more arrays will [throw a `TypeError`.](https://github.com/rails/rails/blob/1da9a7e410f15859939eb4158421846638a41e71/activerecord/lib/active_record/connection_adapters/abstract/quoting.rb#L178, "can't quote #{value.class.name}")

This PR introduces a way to allow Arrays to be quoted as a  by collecting the quoted entries into a Pair when using the Postgres Adapter. 

```
SELECT "articles".* FROM "articles" WHERE ((title, text) IN (('title1','text1'),('title2','text2'))) LIMIT $1
```

As far as I'm aware, this kind of query will only work with postgres, therefore sqlite and mysql should still raise.

I thought about matching Enumerable instead of Array, but the behavior with Hashes i.e. would be confusing:

`Article.where('(title, text) IN (?)', [{title1: "text1", title2: "text2"}])` would result in `SELECT "articles".* FROM "articles" WHERE ((title, text) IN ((('title1','text1'),('title2','text2')))) LIMIT $1`, notice the extra pair of brackets resulting in the generation of an invalid statement.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
I believe MySQL also support this kind of query can you try to implement it? Since we are changing the way we quote array values, does this affect in any way how serialized values are handled?

**Comment by WoH** [comment]
I moved the array quoting up to the AbstractAdapter.
Since SQLite3 does not support this kind of query I am throwing the TypeError there.
There should not be any effects on serialization as far as I'm aware since we quote each of the entries as before which should be handled.

Should I add some more tests for functionality?

**Review by jeremycole — COMMENTED** [review]
As @rafaelfranca mentioned, this construct does work just fine with MySQL. Your PR description is now a bit outdated and would be worth updating for that.

In MySQL, this is called a [row constructor](https://dev.mysql.com/doc/refman/8.0/en/row-subqueries.html) (Postgres [seems to follow the same convention](https://www.postgresql.org/docs/9.0/functions-comparisons.html#ROW-WISE-COMPARISON)) mainly because of their use with subqueries. (There is also extra syntactic sugar of `ROW(a, b)` instead of just `(a, b)`.) They are valid in a bunch of contexts, so this is IMHO a generally useful patch for Rails.

For consistency sake, it might make sense to support Array as a hash key in the hash parametered version of `.where` to accept this syntax as well:

```ruby
Article.where({ [:title, :text] => [['title1', 'text1'], ['title2', 'text2']] })
```

**Comment by matthewd** [comment]
I'd really prefer not to support this: our current behaviour isn't going away any time soon, but doubling down on the idea that arrays are treated as an arbitrary comma separated list feels like a misstep when PostgreSQL has first-class arrays that we need a way to represent (and other DBs without native array types will generally at least have a JSON-ish version).

I'm also vaguely uneasy about introducing new SQL-level syntax constructs in response to changes in the shape of potentially-user-supplied data. This being able to introduce parentheses (to potentially be interpreted as a function call, given a preceding bareword) reopens questions about the safety of other mechanisms, for example.

**Comment by WoH** [comment]
Thank you for raising these concerns @matthewd.
Is there any case when we would want to quote arrays to be a PostgreSQL array (something like `{title1, text1}` or `ARRAY[title1, text1]` I suppose) in this context?

If there is a way to move forward I am happy to address your concerns and explore possible ways to deal with them, however, if there is no way this will be supportable any time soon I'd prefer to close it early :beers:

**Comment by rafaelfranca** [comment]
@matthewd how about `Article.where({ [:title, :text] => [['title1', 'text1'], ['title2', 'text2']] })`? In that case you need to be explicit about the row constructor and it not only arbitrary adding commas in potentially-user-supplied data.

**Comment by paulRbr** [comment]
:wave: Hello, sorry to dig this one out of the closed PRs but the #40273 issue has yet to be solved. Is there any way we could more forward with this?

@WoH you've closed the PR but I think this should be supported in some way in Active Record. For now the only possible way of doing tuple conditions in an SQL query is by building [pure string condition](https://guides.rubyonrails.org/active_record_querying.html#pure-string-conditions) (as the one mentioned in [this stackoverflow example](https://stackoverflow.com/a/31485318/3442487)).

Happy to help moving this forward, should we re-open this PR (or a new dedicated PR?) cc @rafaelfranca

**Comment by njakobsen** [comment]
Just ended up wanting this today. @jeremycole's syntax suggestion (https://github.com/rails/rails/pull/36003#pullrequestreview-272874410) seems to make sense as it very closely matches the look of the underlying query it's intended to generate, while avoiding ambiguity in how the array should be interpreted.

**Pull request closed without merging**
