### PR TITLE
Ensure options is a hash before symbolizing its keys

### LINKED ISSUE #21645: Rails 4.2 not symbolizing string keys when using params in url helper
```ruby
# produces http://localhost:3000/blog/post?action=index&controller=blog/post&published=true
blog_post_path(params.merge(published: 'true')) 

# produces http://localhost:3000/blog/post?published=true
blog_post_path(params.merge(published: 'true').symbolize_keys) 
blog_post_path(params.merge(published: 'true').to_h)
```

Looking at the code [here](https://github.com/rails/rails/blob/4-2-stable/actionpack/lib/action_dispatch/routing/route_set.rb#L313) I realized that `options` is clearly **required** to be a `Hash`, which is **not** when the client is passing `params` directly in a url helper.

That happens because `params` returns `ActionController::Parameters` which internally uses `HashWithIndifferentAccess`. 

The solution is to use either `params.to_h` or `params.symbolize_keys`. The latter would also _hide_ any deprecation warnings.

I do not know whether this is [intended or not](https://github.com/rails/rails/issues/20353#issuecomment-106652511) but it would surely make everyone's life easier to just make sure that `options` is a `Hash` before symbolizing its keys [here](https://github.com/rails/rails/blob/4-2-stable/actionpack/lib/action_dispatch/routing/route_set.rb#L320), because right now when you pass `params` in a url helper, it **does not work neither does it throw a warning/error**.

I suggest we change the [line](https://github.com/rails/rails/blob/4-2-stable/actionpack/lib/action_dispatch/routing/route_set.rb#L313):

```ruby
# from
options ||= {}

# to
options = options ? options.to_h : {}
```

Related to:
https://github.com/rails/rails/issues/20353
https://github.com/rails/rails/pull/17743#issuecomment-102393355

### PR DESCRIPTION
**Pull request by anthonyfalzetti**
Ensures options is a hash

[Fixes #21645]

### CODE REVIEW

**Comment by anthonyfalzetti** [comment]
I did the PR on 4.2 since I couldn’t find the deprecate_string_options method at all in Master therefore, I conclude it has been fixed in master.

**Comment by eileencodes** [comment]
@anthonyfalzetti Thanks for the PR! :smile:

If it's been fixed on master, do you mind bisecting and finding the commit that fixed it? If it was fixed we would prefer to backport (cherry-pick to 4-2) the fix rather than write a new commit. Let me know if you're not sure how to use git bisect.

**Comment by eileencodes** [comment]
Actually I didn't see how minor the change was before I wrote the above. I'd still like to know when/where it was fixed on master first.

**Comment by matthewd** [comment]
I guess it's just gone on master because the deprecation has occurred... but I'm intrigued what the non-hash in question is, though. :confused:

**Comment by jasonnoble** [comment]
This was fixed in master by 34e380764edede47f7ebe0c7671d6f9c9dc7e809

**Comment by jasonnoble** [comment]
Looks like `nil.to_h` is a Ruby 2.0+ thing, which is causing https://travis-ci.org/rails/rails/jobs/80698494 to fail.

@anthonyfalzetti Can you change it to the code @jfragoulis suggested?

    # from
    options ||= {}

    # to
    options = options ? options.to_h : {}

@eileencodes Is the code above the suggested™ way of fixing this?

**Comment by agis-** [comment]
@matthewd as mentioned in #21645, it's a `ActionController::Parameters`.

@eileencodes This PR is specific to 4.2 indeed. For the background see #16958, #20353, https://github.com/rails/rails/pull/17743#issuecomment-102393355 & #18175.

@anthonyfalzetti I believe this badly needs some tests :)

**Comment by jfragoulis** [comment]
So... the whole _keys need to be symbols_ thing is dropped in rails 5.0? I guess it could be cherry picked but as @agis- said it definitely needs more tests.

**Comment by matthewd** [comment]
Ah, okay.

I was getting very confused because we're trying to "ensure it's a hash".. when it *is* a hash.

So I think I've finally caught up: the problem is that [the intended symbolification](https://github.com/rails/rails/blob/82854d56631864208971e1da8465eb2d467188a4/actionpack/lib/action_dispatch/routing/route_set.rb#L320) doesn't work, because when `options` is [an AC::Params which is] a HWIA, it re-stringifies the key during the assignment.

Can we throw in a `# Make sure it's not a HWIA`? As is, it sounds like it's trying to handle a *non*-hash, which would really be the caller's problem.

**Comment by jfragoulis** [comment]
Yes, this is a possible solution indeed. However, it would break everyone's code (everyone who is passing `params`), in which case it would force everyone to update their code to call `params#to_h` or `params#symbolize_keys`.

We decided to bypass the bug and (looking forward to a 5.0 upgrade) to use `params#symbolize_keys` instead.

**Comment by eileencodes** [comment]
As @jfragoulis said, this is totally different in Rails 5 (I didn't follow the change at first, but now I do) so we definitely can't backport the changes to ActionController::Parameters.

Let's not look at how master behaves now because it returns an object and backporting changes to ActionController::Parameters is not an option because it's a breaking change. 

What was the behavior/code before since it's implied this was introduced in 4.2? Did this work as you expected in Rails 4.0? Or Rails 3? Adding some tests would help with showing expected and actual behavior.

**Comment by arunagw** [comment]
@anthonyfalzetti did you get a chance to write test for this PR?

**Comment by maclover7** [comment]
@anthonyfalzetti - Can you please add a few tests per @arunagw and @eileencodes to properly test this out? Also, it appears as though there are a few tests failing currently.

**Pull request closed without merging**
