### PR TITLE
Add webpacker install instruction to guide

### LINKED ISSUE #38954: Rails 6 : rails guides documentation / setup of rails via CLI
### Steps to reproduce

Follow the https://guides.rubyonrails.org/getting_started.html
At `rails serve` step, missing steps lead to complaint regarding webpacker.yml

### Expected behavior

The guide should instruct the user to `npm install -g yarn` if yarn is not already installed.

Following this `rails webpacker:install` should be run, and if possible a link to `rake -T webpacker` or that might cause confusion `rails -T webpacker` should be indicated as a place to get more information, or use to setup different frontend framework support.

### Actual behavior

Quite confusing error

```
traceback
,rvm/gems/webpacker-4.2.2/lib/webpacker/configuration.rb:92 in `read': No such file or directory @ rb_sysopen - /home/lewis/projects/rails-blog/config/webpacker.yml (Errno:ENOENT)
```

### System configuration
**Rails version**:

6.0.2.2 (`rails --version`)

**Ruby version**:

ruby-2.7.1 (`rvm current`)

I'm running npm through nvm at v12.16.2 (`nvm current`) with yarn 1.22.4 (`yarn --version`)

I would be happy to contribute if someone might signpost me, either to docs, or to a place I can script the calls as part of the `rails new rails-blog` command (I know the name rails-blog seems redundant and differs from the guides. I have tried the verbatim name blog and as suspected it produced the same error within the ~/projects/blog folder)

### PR DESCRIPTION
**Pull request by Lewiscowles1986**
### Summary

Adds section for webpacker install to guides, with signposting to explore further webpacker tasks.

Fixes #38954

### Other Information

I have been told #38954 is duplicate. I'd agree if it were not for the still missing commands. This has been an issue for at least 10 months [reddit post](https://www.reddit.com/r/rails/comments/by5b24/error_while_starting_rails_server_v600/)

I've personally never run into this before a recent error making a new rails app. It may be because team-mates had already helped me by performing this step, or that I was not making new rails applications often enough to remember.

Thank you for all the hard work making the framework.

### CODE REVIEW

**Comment by jonathanhefner** [comment]
`rails new` should [automatically run](https://github.com/rails/rails/blob/cf1abb775ef3949ea89f50e7ac939eb8230c4379/railties/lib/rails/generators/app_base.rb#L419) `webpacker:install` unless the `--skip-javascript` or `--skip-webpack-install` options are specified.  If that's not working, we should definitely fix it.

If Node.js and Yarn are both installed and you run `rails new`, do you find you still need to run `webpacker:install` manually?

**Comment by Lewiscowles1986** [comment]
I did yes. I had both yarn and node via nvm installed locally and it did not run for `rails new {appname}` no arguments using debian buster ruby 2.7.2 via rvm

**Comment by jonathanhefner** [comment]
@Lewiscowles1986  I'm having trouble reproducing locally.  Would you mind posting the output of the following commands:

```bash
rails -v

node -v

yarn -v

cat ~/.railsrc

rails new myapp
```

**Comment by vipulnsward** [comment]
> I've personally never run into this before a recent error making a new rails app. It may be because team-mates had already helped me by performing this step, or that I was not making new rails applications often enough to remember.

You are still able to reproduce it? From your post it seems you did not face this issue.

Reading https://www.reddit.com/r/rails/comments/by5b24/error_while_starting_rails_server_v600/ it seems they might have done an upgrade. No mention of a new Application which the "Getting Started" guide relates to.

So unless we find issues on fresh Application for webpack(which if we do should be fixed), this new addition will be confusing.

**Comment by Lewiscowles1986** [comment]
`rails -v`

Rails 6.0.2.2

`node -v`

v12.16.2

`yarn -v`

1.22.4

`cat ~/.railsrc`

No such file or directory

`rails new myapp`

<details>
<summary>Output</summary>

```
coming from PC with rails on it
```

</details>

**Comment by Lewiscowles1986** [comment]
it is returning a non-zero code, but no error messages other than the warnings. Perhaps this is why I'm needing to install webpacker.

**Comment by jonathanhefner** [comment]
Unfortunately, I am at a loss.  I have installed those exact versions, running on Ubuntu 18.04, and I cannot reproduce the issue.  If you would like to debug further, you might try editing `/home/lewis/.rvm/gems/ruby-2.7.1/gems/railties-6.0.2.2/lib/rails/generators/app_base.rb` to sprinkle a few `STDERR.puts("HERE")` in the [`run_webpack` method on line 411](https://github.com/rails/rails/blob/v6.0.2.2/railties/lib/rails/generators/app_base.rb#L411-L416).

**Comment by Lewiscowles1986** [comment]
I mean, just running these commands I get webpacker which is the part that crashes.

Feel free to close. At this point I'm done.

**Comment by vipulnsward** [comment]
Thanks for the work @Lewiscowles1986 ! 
Will wait to see if anyone else is able to reproduce it and merge after.

**Pull request closed without merging**
