### PR TITLE
Document the fact that Action Cable does not require a multi-threaded app server

### PR DESCRIPTION
**Pull request by FooBarWidget**
The Action Cable README says that a multithreaded app server, like Puma, is required. This is not true because Action Cable takes over connections through the Rack socket hijacking API, and manages those connections internally, bypassing the app server. This pull request updates the documentation accordingly.

I've confirmed that Action Cable 5.0.0 beta 2 works with Unicorn and with Passenger.

### CODE REVIEW

**Comment by maclover7** [comment]
Looks good to me. Can you add a little note in here saying that WEBrick will not work?

**Comment by maclover7** [comment]
Also, in the future, please try to add `[ci skip]` to any commits that involve changing the documentation, to avoid running the entire Rails test suite.

**Comment by FooBarWidget** [comment]
All right. But are you sure it's `[ci skip]` and not `[ci:skip]`?

**Comment by vipulnsward** [comment]
@FooBarWidget https://docs.travis-ci.com/user/customizing-the-build/#Skipping-a-build

**Comment by FooBarWidget** [comment]
Documentation updated according to your suggestions.

**Comment by kayakyakr** [comment]
@FooBarWidget what attachment method are you using? Are you using the standalone config.ru or are you using the routes.rb method?

**Comment by maclover7** [comment]
:+1: Thank you for your contribution!

**Comment by maclover7** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by FooBarWidget** [comment]
@kayakyakr standalone method. Both work, but the attachment method requires a bit more Passenger configuration.

**Comment by kayakyakr** [comment]
That's an important distinction, as the method most projects will start out with is through routes.rb, not config.ru.

**Comment by FooBarWidget** [comment]
Yep, I discussed that with the Rails core team a couple of hours ago. I'll update the Passenger docs accordingly with proper Action Cable integration instructions.

**Comment by Eric-Guo** [comment]
@FooBarWidget I don't found any document about deploy Action Cable in Passenger after google, would be nice if you could point out a reference link?

**Comment by FooBarWidget** [comment]
@Eric-Guo We're working on official documentation, but for now this is a good third party guide: [Deploying ActionCable and Rails 5 to Production with Passenger](https://gorails.com/episodes/deploy-actioncable-and-rails-5)

**Comment by bobzhen** [comment]
👏

**Pull request merged**
