### PR TITLE
Backport TooManyOrTest to fix pq crash on stable

### PR DESCRIPTION
**Pull request by zzak**
This backports part of #47510 to fix this failing build:
https://buildkite.com/rails/rails/builds/96360#01880ded-cecb-4a71-9e9f-35db4f5bbce7/1069-1084

### CODE REVIEW

**Comment by yahonda** [comment]
I understand this addresses the CI failure at the 7-0-stable branch, but I wanted to find the root cause of this error and address it permanently.

Also, it's too early to come to a conclusion, I found the latest pull request that changes something about llvm, so let me report it to https://github.com/docker-library/postgres.

https://github.com/docker-library/postgres/commit/a3b0bb68faed03c6edd3978b8dd34ca67881f7c7

**Comment by yahonda** [comment]
Opened an issue here https://github.com/docker-library/postgres/issues/1080

**Comment by matthewd** [comment]
Yeah, arguably it's `main` that's at fault for _not_ failing here (which is, broadly, something we considered when reducing the number of OR branches in https://github.com/rails/rails/pull/47510)...

It's a pretty arbitrary distinction as far as we're concerned, though -- presumably only one of the queries is stepping over some upstream-Postgres defined numeric threshold, but that's not something that we're supposed to need to care about.

Given that, if it seemed likely to stay broken for longer, I think we could consider this backport (it hides, rather than fixing, the problem... but it's not our problem to begin with) -- however it sounds like it's sorted now (https://github.com/docker-library/postgres/issues/1080#issuecomment-1546523568, https://buildkite.com/rails/rails/builds/96406), so I think we can leave things as they are.

**Comment by zzak** [comment]
Thanks for taking a look and reporting it upstream!

**Pull request closed without merging**
