### PR TITLE
Remove obsolete yarn.lock files and check in root yarn.lock file

### LINKED ISSUE #34587: Now that we use Yarn Workspaces, we should check in the top-level yarn.lock and remove the other yarn.lock files from child directories
### Steps to reproduce
```
cd actioncable
yarn add --dev left-pad
```

### Expected behavior
There should be changes to `yarn.lock` that are tracked by git.

### Actual behavior
There are only changes to `package.json` tracked by git - no changes to `yarn.lock` tracked by git

### System configuration
**Rails version**: N/A

**Ruby version**: N/A

## Analysis

This seems to be because the repository is now using [Yarn Workspaces](https://yarnpkg.com/lang/en/docs/workspaces/) (added in https://github.com/rails/rails/pull/33079):

https://github.com/rails/rails/blob/a429b29425027006f2bbd4d267928dde1dc2c31a/.yarnrc#L1-L2
https://github.com/rails/rails/blob/a429b29425027006f2bbd4d267928dde1dc2c31a/package.json#L3-L10

This makes the `yarn.lock` files inside the `actioncable` and `activestorage` directories obsolete. Now the only `yarn.lock` that matters is in the repository root. However, that file is currently in the `.gitignore`:
https://github.com/rails/rails/blob/a429b29425027006f2bbd4d267928dde1dc2c31a/.gitignore#L19

This seems undesirable. If you have a stale `yarn.lock` in the root, it won't be modified to add new packages when you `git pull`, even if new dependencies have been added in one of the workspaces. This means that when you run `yarn install`, you won't have all the dependencies installed. You have to first run `rm yarn.lock` to remove your stale lockfile, and then run `yarn install` to get everything installed. Since the root `yarn.lock` is currently in the `.gitignore`, it's easy to miss that you have this file locally, so it's not obvious that you should run `rm yarn.lock` before `yarn install`.

I think we should remove `/yarn.lock` from the `.gitignore` and check in the root `yarn.lock` like we check in [the root `Gemfile.lock`](https://github.com/rails/rails/blob/a429b29425027006f2bbd4d267928dde1dc2c31a/Gemfile.lock).

Related thread: https://github.com/rails/rails/pull/34370#issuecomment-443449106

### PR DESCRIPTION
**Pull request by rmacklin**
Resolves #34587 

<details>
<summary>Issue description</summary>

> ### Steps to reproduce
> ```
> cd actioncable
> yarn add --dev left-pad
> ```
> 
> ### Expected behavior
> There should be changes to `yarn.lock` that are tracked by git.
> 
> ### Actual behavior
> There are only changes to `package.json` tracked by git - no changes to `yarn.lock` tracked by git
> 
> ### System configuration
> **Rails version**: N/A
> 
> **Ruby version**: N/A
> 
> ## Analysis
> 
> This seems to be because the repository is now using [Yarn Workspaces](https://yarnpkg.com/lang/en/docs/workspaces/) (added in https://github.com/rails/rails/pull/33079):
> 
> https://github.com/rails/rails/blob/a429b29425027006f2bbd4d267928dde1dc2c31a/.yarnrc#L1-L2
> https://github.com/rails/rails/blob/a429b29425027006f2bbd4d267928dde1dc2c31a/package.json#L3-L10
> 
> This makes the `yarn.lock` files inside the `actioncable` and `activestorage` directories obsolete. Now the only `yarn.lock` that matters is in the repository root. However, that file is currently in the `.gitignore`:
> https://github.com/rails/rails/blob/a429b29425027006f2bbd4d267928dde1dc2c31a/.gitignore#L19
> 
> This seems undesirable. If you have a stale `yarn.lock` in the root, it won't be modified to add new packages when you `git pull`, even if new dependencies have been added in one of the workspaces. This means that when you run `yarn install`, you won't have all the dependencies installed. You have to first run `rm yarn.lock` to remove your stale lockfile, and then run `yarn install` to get everything installed. Since the root `yarn.lock` is currently in the `.gitignore`, it's easy to miss that you have this file locally, so it's not obvious that you should run `rm yarn.lock` before `yarn install`.
> 
> I think we should remove `/yarn.lock` from the `.gitignore` and check in the root `yarn.lock` like we check in [the root `Gemfile.lock`](https://github.com/rails/rails/blob/a429b29425027006f2bbd4d267928dde1dc2c31a/Gemfile.lock).
> 
> Related thread: https://github.com/rails/rails/pull/34370#issuecomment-443449106
</details>

### CODE REVIEW

**Comment by javan** [comment]
👌 This is the correct way to use Yarn Workspaces, AFAIK. We have the same setup for https://github.com/stimulusjs/stimulus: a single `yarn.lock` at the root, and individual `package.json`s for each workspace.

**Comment by rmacklin** [comment]
https://github.com/rails/rails/pull/34370 didn't add any dependencies, so there are no changes when I rebase and run `yarn install`. Do you want me to push that anyway?

**Comment by javan** [comment]
Yes, please. I want to make sure actioncable's tests still pass on CI. Can't hurt to rebase.

**Comment by rmacklin** [comment]
Hmm, do you know what these entries are for in the workspaces configuration:
https://github.com/rails/rails/blob/aa1ba9cb244b1e03d36aaa941ae4e91c6713b77e/package.json#L7-L9
After running
```
rm -r tmp/templates/app_template railties/test/fixtures/tmp
```
to delete those directories and rerunning `yarn install`, I get a diff as well (wasn't able to get a diff before doing that).

It seems like these directories are also untracked by git which means that you could have stale files in there which cause the root `yarn.lock` to be generated differently. I'm inclined to think they shouldn't be configured as workspaces, but I don't have all the context to know for sure.

For now, I'll push the `yarn.lock` that was generated after removing those directories.

**Comment by rmacklin** [comment]
It seems to have originated from this commit:
https://github.com/lsylvester/rails/commit/b801b0817ddaf20f28fbc3dec2fb9a3f867e7d36 (part of https://github.com/rails/rails/pull/33640, a sub-PR of the larger https://github.com/rails/rails/pull/33079).

@lsylvester commented in https://github.com/rails/rails/pull/33640#issuecomment-422645699 about some tests potentially requiring the workspaces configuration, but I'm not sure if that included these lines https://github.com/rails/rails/blob/aa1ba9cb244b1e03d36aaa941ae4e91c6713b77e/package.json#L7-L9
or if https://github.com/rails/rails/blob/aa1ba9cb244b1e03d36aaa941ae4e91c6713b77e/package.json#L4-L6
is sufficient.

@lsylvester, if you're able to provide more context that'd be great. Otherwise, I would suggest we try removing the `tmp` directories from the workspaces configuration and see if the tests pass.

**Comment by javan** [comment]
+1 for removing those entries. Test / tmp directories shouldn't be workspaces.

**Comment by rmacklin** [comment]
Thanks a bunch for the context! Given that: 

> Since then, the version of the packages that is required was relaxed ([fbd4597](https://github.com/rails/rails/commit/fbd45978effd8d83a29f95493c59e3e715ceca76)) to include published versions. This was done after a discussion about the differences in the versioning schemes between npm and ruby gems where `Rails::VERSION::STRING` could not be directly used.

it seems like you agree that we can remove the tmp directories from the workspaces. I opened a PR to do that here: https://github.com/rails/rails/pull/34630

I agree  that the workspaces should provide value when ActionText is merged, so I did _not_ remove the workspaces configuration for the real `actioncable`, `actionview`, and `activestorage` packages.

**Pull request merged**
