### PR TITLE
Clarify i18n active[model/record] key differences

### PR DESCRIPTION
**Pull request by jcoleman**
I spent a decent amount of time the other day trying to figure out why my active model including class wasn't generating the properly localized validation messages, and a note like this would have saved me a lot of time.

### CODE REVIEW

**Comment by eileencodes** [comment]
Hi @jcoleman thanks for the PR!

I'm not sure this is the right place. I wonder if this would be better higher up where we first mention `activerecord`. What do you think?

**Comment by jcoleman** [comment]
@eileencodes: Perhaps at the end of the first section under the header Translations for Active Record Models?

**Comment by eileencodes** [comment]
Sorry! I forgot to respond to this. Yes I think that's a better place for this note. Can you update?

**Comment by jcoleman** [comment]
@eileencodes Done!

**Comment by eileencodes** [comment]
Thanks! Can you squash your commits into one?

**Comment by jcoleman** [comment]
@eileencodes: Done!

**Comment by eileencodes** [comment]
Thanks! I should have caught this before, in the future add `[ci skip]` to commits that only change documentation so travis CI doesn't need to run :smile:

**Pull request merged**
