### PR TITLE
Add docs for  Router::Utils.unescape_uri method. [ci skip]

### PR DESCRIPTION
**Pull request by dixpac**
Add docs for `ActionDispatch::Journey::Router::Utils.unescape_uri` method.

### CODE REVIEW

**Review by maclover7 — APPROVED** [review]

**Comment by maclover7** [comment]
:+1: Thank you for your contribution!

:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by kamipo** [comment]
Is this needed? `Router::Utils` is a `:nodoc:` class.

**Comment by maclover7** [comment]
@kamipo There are other documented methods in the class

**Comment by kamipo** [comment]
I see.

**Comment by pixeltrix** [comment]
@maclover7 not worth reverting this but next time think whether the docs are adding any value - pretty obvious what `unescape_uri` would do and doesn't appear in API docs so no benefit to the audience that will see it. Only really worth adding docs to nodoc/private methods where they're explaining why something works the way it does or referencing something like a RFC where it explains why the code is needed.

If you look at the pre-existing docs it's documenting one method which is pretty dense and then another comment that's referencing the relevant RFC about URIs. The other methods like `escape_fragment` aren't documented.

**Pull request merged**
