### PR TITLE
Remove skipped JRuby tests that are passing on 9.0.3.0.

### PR DESCRIPTION
**Pull request by tgxworld**
@rafaelfranca The tests are passing on my local machine I'll try this on travis

### CODE REVIEW

**Comment by spastorino** [comment]
what's the deal with `enable-jruby` branch? why not adding this to master?

**Comment by tgxworld** [comment]
This branch has JRuby tests enabled and I don't think we're ready to re-enable it on master yet.

**Comment by rafaelfranca** [comment]
@tgxworld I think we should push the fixes to master and just rebase my branch to check if it is working. A long standing branch is not good for something in the size of Rails. I'll merge in this branch and backport to master.

**Comment by tgxworld** [comment]
@rafaelfranca Got it :+1:

**Pull request merged**
