### PR TITLE
Add tests for rendering with variants

### PR DESCRIPTION
**Pull request by st0012**
I think that render tests in `ActionView` should also test rendering template/partial with variants option?

### CODE REVIEW

**Review by maclover7 — APPROVED** [review]
Seems reasonable to me 👍 👍

**Comment by kaspth** [comment]
@st0012 I'll let it pass this time, but please don't just reassign members when there's been no activity. We're all often busy.

**Comment by st0012** [comment]
@kaspth Sorry, I won't do that anymore 😢

**Pull request merged**
