### PR TITLE
Target Ruby 2.2.1 in gemspecs

### PR DESCRIPTION
**Pull request by splattael**
This is a follow-up to #19257

### CODE REVIEW

**Comment by senny** [comment]
:+1:  @splattael thank you.

**Comment by jvanbaarsen** [comment]
@splattael Thanks :) I did not look further :(

**Comment by shunsukeaida** [comment]
I wonder how much manual labors are ever needed for just one TEENY version bump, and if we can't make them entirely automatic, it's still worth figuring out what we (should) have edited per bump.

I'm aware of at least one more part to be upgraded, but any more?
https://github.com/rails/rails/blob/master/guides/source/command_line.md#rails-server
```
[2013-08-07 02:00:01] INFO  ruby 2.0.0 (2013-06-27) [x86_64-darwin11.2.0]
```

**Comment by simi** [comment]
What about to introduce `RUBY_VERSION` file next to `RAILS_VERSION` and use it in gemspecs like:

```ruby
ruby_version = File.read(File.expand_path('../../RUBY_VERSION', __FILE__)).strip
#...
s.required_ruby_version = ruby_version
```

:question:

@shunsukeaida I think guides are not needed to be strictly upgraded since linux users will see different output anyway.

**Comment by rafaelfranca** [comment]
I don't think we need to worry about this. It doesn't happen often.

**Pull request merged**
