### PR TITLE
Fix digesting templates with mixed formats

### LINKED ISSUE #28503: Fragment cache digest is blank when HTML partial is rendered inside JS view
### Steps to reproduce

1. `git clone https://github.com/thomasfedb/rails-cache-test.git`
2. `touch tmp/caching-dev.txt`
3. Run `rails s` and open in browser. Note that the paragraph is **red**.
4. Click the link to reload partial over JS. The paragraph is still **red**.
5. `git checkout blue` but **do not** restart Rails server.
6. Reload browser. Note that the paragraph is **blue**.
7. Click the link to reload partial over JS. The paragraph changes back to **red**.

When you review the logs from `rails s` you'll find that the following:

**Loading red partial via `index.html.erb`**
```
Started GET "/" for ::1 at 2017-03-21 21:05:30 +0800
Processing by HomeController#index as HTML
  Rendering home/index.html.erb within layouts/application
Read fragment views/x.dev.localhost//a8f265d1f73f3dafd91c3d947bbaac43 (0.0ms)
Write fragment views/x.dev.localhost//a8f265d1f73f3dafd91c3d947bbaac43 (0.0ms)
```

**Loading red partial via `index.js.erb`**
```
Started GET "/" for ::1 at 2017-03-21 21:05:54 +0800
Processing by HomeController#index as JS
  Rendering home/index.js.erb
  'home/_partial' file doesn't exist, so no dependencies
  Couldn't find template for digesting: home/_partial
Read fragment views/x.dev.localhost// (0.1ms)
Write fragment views/x.dev.localhost// (0.1ms)
```

**Loading blue partial via `index.html.erb`**
```
Started GET "/" for 127.0.0.1 at 2017-03-21 21:06:23 +0800
Processing by HomeController#index as HTML
  Rendering home/index.html.erb within layouts/application
Read fragment views/x.dev.localhost//2338c21dccfbc4347d872c453af9f072 (0.1ms)
Write fragment views/x.dev.localhost//2338c21dccfbc4347d872c453af9f072 (0.1ms)
```

**Loading blue partial via `index.js.erb`**
```
Started GET "/" for ::1 at 2017-03-21 21:06:24 +0800
Processing by HomeController#index as JS
  Rendering home/index.js.erb
  'home/_partial' file doesn't exist, so no dependencies
  Couldn't find template for digesting: home/_partial
Read fragment views/x.dev.localhost// (0.1ms)
```

### Expected behavior
The cache digest should be calculated correctly when rendering an HTML partial inside a JS view.

### Actual behavior
When rendering a HTML partial inside a JS view, the cache digest is blank. When the partial source changes, the key does not change, leading to the wrong content being displayed.

The issue seems to stem from [this line](https://github.com/rails/rails/blob/4d6feef79248a63c4cefde3f9ceb2242925e8d8d/actionview/lib/action_view/digestor.rb#L48) in `ActionView::Digestor`:
```
options[:formats] = [finder.rendered_format] if finder.rendered_format
```

Which, [as seen here](https://github.com/rails/rails/blob/fc2aa53f875b12df93b0d07932e3ab563b89152c/actionview/lib/action_view/renderer/template_renderer.rb#L12), will take only the first format (in this case `:js`) when it should probably take all formats (which would be `[:js, :html]`):
```
@lookup_context.rendered_format ||= (template.formats.first || formats.first)
```

### System configuration
**Rails version**: 5.0.2
**Ruby version**: 2.4.0

### PR DESCRIPTION
**Pull request by javan**
Fixes #28503
Follow up to: #25411

### CODE REVIEW

**Comment by thomasfedb** [comment]
I've tested this against the repro I created when I reported #28503 and this PR resolves the issue. I've been unable to immediately test this against the production app where I first noticed this issue as the app doesn't play nice with rails master presently. Hopefully this can be backported against 5.1 and 5.2 - which I'm happy to help with.

**Comment by thomasfedb** [comment]
Having now backported the fix to 5.1 stable I can confirm that this fixes the issue I was experiencing.

**Review by kaspth — APPROVED** [review]
Nice! Feel free to backport to 5-2-stable and 5-1-stable.

**Comment by javan** [comment]
I think I've found a better solution that aligns more closely with the behavior of rendering: https://github.com/rails/rails/pull/32282/commits/052a6d51d82ec7fa730ea401648f4cb522f67e56

By setting `finder.formats`, we avoid the need to find with a `:formats` options. And when it's set to `[:js]`, we automatically get an `:html` fallback:
https://github.com/rails/rails/blob/d9736e50d8d6fc9fad32e16ebdc8dcd0a0a3ec61/actionview/lib/action_view/lookup_context.rb#L245-L255

Rendering a request works similarly: https://github.com/rails/rails/blob/d9736e50d8d6fc9fad32e16ebdc8dcd0a0a3ec61/actionview/lib/action_view/rendering.rb#L106-L111

@thomasfedb, mind trying once more with my latest commit? If it doesn't pan out I'll use my first approach.

@kaspth, if you have any other ideas, please do let me know! It's a jungle in there.

**Comment by thomasfedb** [comment]
@javan would that break if I, for example, tried to render a `.txt` partial inside a `.js` partial? Or some other cross-format combination?

**Comment by javan** [comment]
I think that will work, but please do investigate.

**Comment by thomasfedb** [comment]
@javan I'll give it a try

**Comment by thomasfedb** [comment]
@javan new fix definitely solves the issue when using HTML partials inside JS views as with the previous fix.

There is an issue, however, when you render a partial with a particular format, e.g. `partial: 'partial2', formats: :text, collection: [1], cached: true` which results in a `Couldn't find template for digesting: home/_partial2` message, and a blank cache key is used (and therefore old cache is still used when partial is updated).

**Comment by thomasfedb** [comment]
The above happens inside both JS and HTML views, as you'd expect.

**Comment by thomasfedb** [comment]
Sorry, should make it clear that this issue with rendering with specified format appears only to occur with the new fix, and was not a problem with the initial fix.

With initial fix:
```
Processing by HomeController#index as HTML
  Rendering home/index.html.erb within layouts/application
Read fragment views/home/_partial2:140b891b4a188473f1a3d632568d6824/localhost:3000/ (0.0ms)
Write fragment views/home/_partial2:140b891b4a188473f1a3d632568d6824/localhost:3000/ (0.0ms)
  Rendered collection of home/_partial2.text.erb [0 / 1 cache hits] (1.8ms)
  Rendered home/index.html.erb within layouts/application (14.6ms)
Completed 200 OK in 1053ms (Views: 1051.9ms | ActiveRecord: 0.0ms)
```

With new fix:
```
Processing by HomeController#index as HTML
  Rendering home/index.html.erb within layouts/application
  Couldn't find template for digesting: home/_partial2
Read fragment views/home/_partial2/localhost:3000/ (0.1ms)
Write fragment views/home/_partial2/localhost:3000/ (0.1ms)
  Rendered collection of home/_partial2.text.erb [0 / 1 cache hits] (1.6ms)
  Rendered home/index.html.erb within layouts/application (14.4ms)
Completed 200 OK in 1037ms (Views: 1036.6ms | ActiveRecord: 0.0ms)
```

Let me know if you need further info @javan

**Comment by javan** [comment]
Thanks @thomasfedb! It looks like [`DependencyTracker`](https://github.com/rails/rails/blob/master/actionview/lib/action_view/dependency_tracker.rb) doesn't parse the `:formats` option currently. So my initial fix happens to work correctly, but would probably fail if you had more than one `_partial2` template. If you had `_partial2.text.erb` and `_partial2.html.erb` it would always digest the `html` template.

**Comment by thomasfedb** [comment]
@javan right, there was only `_partial2.text.erb` in my test, no other partial called `partial2`. I'd be happy to go with either of your fixes for now, and then subsequently address parsing `:formats`, what do you think?

**Comment by javan** [comment]
Went with the 2nd approach. Thanks for all your help @thomasfedb!

**Comment by javan** [comment]
Backported to 5-2 0b53f5711ac9b26b8bc899caaf35de913ff4905f and 5-1 eb309757459a45128ae358e2bfa3314f04c40795

**Comment by thomasfedb** [comment]
Thanks @javan, and clue as to when the next 5.1.x will be cut?

**Comment by javan** [comment]
I'm not sure about the 5-1 release schedule. Maybe @rafaelfranca knows? You can always point your Gemfile at the Rails branch or sha.

**Comment by thomasfedb** [comment]
Using the branch now in dev, but would prefer to have an official release before I deploy to prod.

**Comment by rafaelfranca** [comment]
It may takes months. We usually release every 6 weeks, but given 5.2 is going to be the official release, it may take more time.

**Comment by erikthiem** [comment]
> Thanks @thomasfedb! It looks like [`DependencyTracker`](https://github.com/rails/rails/blob/master/actionview/lib/action_view/dependency_tracker.rb) doesn't parse the `:formats` option currently. So my initial fix happens to work correctly, but would probably fail if you had more than one `_partial2` template. If you had `_partial2.text.erb` and `_partial2.html.erb` it would always digest the `html` template.

@javan This PR broke a project I'm working on because I had, to use your example, more than one `_partial2` template. Do you know if there is a fix to get the code change from this PR working when you have multiple templates with the same name but different format endings?

**Comment by thomasfedb** [comment]
@erikthiem I think you'd need to make `DependencyTracker` aware of `:format` to avoid that issue.

**Pull request merged**
