### PR TITLE
permit_all! to permit all attributes in a given key.

### PR DESCRIPTION
**Pull request by alvarezloaiciga**

### CODE REVIEW

**Comment by AlexCppns** [comment]
@senny I just tried what's in the documentation with little success. My current fix is to not use permit... I wish there were a way to arbitrary json/hash in a model attribute, postgresql supports json as a data format after all.

**Comment by senny** [comment]
@AlexCppns sorry but you need to provide more context. What is not working with:

```ruby
params.require(:product).permit(:name).tap do |whitelisted|
  whitelisted[:data] = params[:product][:data]
end
```

**Comment by AlexCppns** [comment]
@senny What I saw in the documentation link you provided was:

```
def product_params
  params.require(:product).permit(:name, data: params[:product][:data].try(:keys))
end
```

I will try your solution, what is the syntax when you have several attributes, half are json and the others are regular attributes?

**Comment by senny** [comment]
@AlexCppns the one in the docs should work for flat json documents. If you have arbitrary json you can use the snippet I provided above. There is no special syntax for these attributes, it's just regular ruby, effectively by-passing the strong-parameters api by directly assigning the attributes:

```ruby
JSON_ATTRS = [:payload, :data]

params.require(:product).permit(:name).tap do |whitelisted|
  JSON_ATTRS.each do |attr|
    whitelisted[attr] = params[attr]
  end
end
```

**Comment by AlexCppns** [comment]
Oh I see, sorry I was misreading it.

**Comment by joelpresence** [comment]
Can we reopen this issue please?  I'm trying to pass in a serialized Hash with arbitrary keys and the current implementation of strong parameters just doesn't work in this case ... This is a pretty common use case actually.  :-)

Thanks!

**Comment by senny** [comment]
@joelpresence I think the exact scenario you describe is listed in our guides. See http://guides.rubyonrails.org/action_controller_overview.html#outside-the-scope-of-strong-parameters

**Comment by rhymes** [comment]
@senny that works only with flat JSON, if you have hashes nested in hashes for now the only way to bypass is:

```ruby
        params.require(:device).permit(:name).tap do |whitelisted|
          whitelisted[:data] = params[:device][:data] if params[:device][:data]
        end

**Comment by andersodt** [comment]
@senny @rhymes this whitelist approach works in Rails 4, but upon upgrading to the Rails 5 beta, I seem to lose this functionality.

**Comment by senny** [comment]
@andersodt could you be a bit more specific. What is no longer working?

```
irb(main):006:0> Rails.version
=> "5.0.0.beta2"
irb(main):007:0> params.require(:person).permit(:first_name, payload: params[:person][:payload].try(:keys))
=> {"first_name"=>"Bob", "payload"=>{"one"=>"One", "two"=>"Two"}}
```

**Comment by andersodt** [comment]
I have a Question model with a JSON type that stores different information about its possible answers. Depending on the question_type, a different structure might get thrown into the data column. Multiple choice, for instance, would look something like this:
```
{
    "question" => {
        "data" => {
            "0" => {
                "question_data_text" => "abc"
            }, "1" => {
                "question_data_text" => "one two three"
            }
        }, "prompt" => "question_prompt", "question_type" => "multiple_choice", "folder_id" => "1"
    }, "id" => ""
}
```
Neither of these approaches saves the "data" 

```
params.require(:question).permit(:questoin_type, :folder_id, :prompt).tap do |whitelisted|
  whitelisted[:data] = params[:question][:data] if params[:question][:data]
end
```

```
params.require(:question).permit(:question_type, :folder_id, :prompt, params[:question][:data].try(:keys))
```
In Rails 4, I was using the whitelisted approach and it worked great, but haven't had any success since upgrading to the beta.

**Comment by senny** [comment]
@andersodt can you provide an excerpt from a Rails console session that showcases your issue? I get:

```ruby
=> {"question"=>{"data"=>{"0"=>{"question_data_text"=>"abc"}, "1"=>{"question_data_text"=>"one two three"}}, "prompt"=>"question_prompt", "question_type"=>"multiple_choice", "folder_id"=>"1"}, "id"=>""}
irb(main):026:0> params = ActionController::Parameters.new(params_hash)
=> {"question"=>{"data"=>{"0"=>{"question_data_text"=>"abc"}, "1"=>{"question_data_text"=>"one two three"}}, "prompt"=>"question_prompt", "question_type"=>"multiple_choice", "folder_id"=>"1"}, "id"=>""}
irb(main):027:0> params.require(:question).tap { |w| w[:data] = params[:question][:data] if params[:question][:data] }
=> {"data"=>{"0"=>{"question_data_text"=>"abc"}, "1"=>{"question_data_text"=>"one two three"}}, "prompt"=>"question_prompt", "question_type"=>"multiple_choice", "folder_id"=>"1"}
irb(main):028:0> Rails.version
=> "5.0.0.beta2"
```

**Comment by senny** [comment]
@andersodt what about:

```ruby
params.require(:question).permit(:prompt, :question_type, :folder_id).tap { |w| w[:data] = params[:question][:data].to_unsafe_h if params[:question][:data] }
```

Note the `.to_unsafe_h` to make sure there are no restrictions when accessing `:data`.

**Comment by andersodt** [comment]
That did it. The "unpermitted data" notice still appears on the console but the data hash is being properly saved. 

Thanks!

**Comment by senny** [comment]
@andersodt yes, the unpermitted parameter notice is printed by the `permit` call. That is the same pre 5.0 though.

**Pull request closed without merging**
