### PR TITLE
Ensure that assets are enabled back after the test that tests assets are disabled

### PR DESCRIPTION
**Pull request by prathamesh-sonpatki**

### CODE REVIEW

**Comment by kaspth** [comment]
I'd prefer capturing the old value and setting it back in ensure :)

**Comment by prathamesh-sonpatki** [comment]
oh makes sense. Thanks Kaspter. updating it.

**Comment by prathamesh-sonpatki** [comment]
@kaspth Done :)

**Comment by kaspth** [comment]
Neat!

**Pull request merged**
