### PR TITLE
test demonstrating touching others when touched

### PR DESCRIPTION
**Pull request by arenoir**
Issue #18929 

There should be a better way than adding sleep(1).  In my rails app I used rspec should_receive but not sure how to do that with minitest.

### CODE REVIEW

**Comment by egilburg** [comment]
Try using `travel`.

http://api.rubyonrails.org/classes/ActiveSupport/Testing/TimeHelpers.html#method-i-travel

**Comment by georgeclaghorn** [comment]
The existing behavior isn't documented, but I believe it's appropriate. The intent of the `:touch` option is to touch an object's owners when it changes. If an object's `updated_at` timestamp is changed, it is itself changed, and its owners need to be touched. I think the docs are wrong in this case, not the implementation.

**Comment by maclover7** [comment]
Can you rebase? Also, it looks like tests are failing on Travis CI.

**Review by varyonic — COMMENTED** [review]
I verified this test actually fails because it asserts updated_at does not change.

**Comment by varyonic** [comment]
I believe this can be closed as it is covered by test_belongs_to_with_touch_option_on_touch_without_updated_at_attributes which shows the parent updated_at modified (even if the child has no updated_at attribute).

**Pull request closed without merging**
