### PR TITLE
Support proc as default value for Attributes API

### PR DESCRIPTION
**Pull request by kirs**
Example:

```
attribute :year, :integer, default: -> { Time.now.year }
```

/cc @sgrif

### CODE REVIEW

**Comment by arthurnn** [comment]
:cool: :+1:

**Comment by sgrif** [comment]
Is there an equivalent of this possible prior to the attributes API?

**Comment by sgrif** [comment]
It also occurs to me that this could interact with dirty checking in unexpected ways

**Comment by egilburg** [comment]
Will this be evaluated in context of instance? Can you do something like this?

```ruby
attribute :full_name, :string, default: -> { "#{first_name}" #{last_name}" }
```

If not, would be nice to pass instance to the proc so one can do:

```ruby
attribute :full_name, :string, default: -> { |obj| "#{instance.first_name}" #{instance.last_name}" }
```

**Comment by kirs** [comment]
@egilburg I was thinking about it, but now the proc is before other attributes are assigned. I will work on it.

> Is there an equivalent of this possible prior to the attributes API?

@sgrif only possible using the `before_validate` callback.
Do you think we can merge if I add more tests concerning dirty checking?

**Comment by sgrif** [comment]
I'm working on a different API to compose multiple values, I'd rather not overcomplicate it here by passing the instance. I'm not sure that the problem is too little test coverage, if we wrote a test for the edge case, it wouldnt be unexpected. ^_^

I think this is probably fine, I just want to be conservative about changes that could increase the complexity here.

**Comment by sgrif** [comment]
The current implementation will call the proc once at definition time, not every time we need a default value.

**Comment by kirs** [comment]
@sgrif fixed!

**Comment by kirs** [comment]
@sgrif updated.

**Comment by kirs** [comment]
ping @sgrif

**Comment by chancancode** [comment]
In the context of an AR model, when would this proc be evaluated?

**Comment by printercu** [comment]
Seems like it affects not only default values: `user.name = -> { generate_name }` will call the proc to get the value.

**Comment by printercu** [comment]
I've missed, this one is not merged.

**Comment by sgrif** [comment]
The merged version of this feature will only affect defaults, not assignment. That was a consideration in the implementation.

**Comment by printercu** [comment]
Yeah, cool :+1:

**Comment by chancancode** [comment]
My question remains: at what point is the proc evaluated/resolved? Only once at init time? Only once on first access? Only once on save? Everytime when accessed?

This /seems/ important, but the answer is unclear to me from the proposal and the tests. It is not immediately obvious to me which of these is most "correct" (most useful) either. (1 is probably correct; 2 & 3 seems somewhat plausible but problematic in practice; pretty sure 4 be completely useless) Are there more background discussion about this?

I have a feeling that this is going to come back to bite us if we don't think it through. Personally I feel that I need to see more real use cases to understand why this is actually needed and how it will actually be used.

Even if we are immediately convinced once of the options are correct, we should probably add an "integration" test for it.

**Comment by chancancode** [comment]
(and document it)

**Comment by tiegz** [comment]
(@sgrif per your first question, there was a method that was removed in 3.2 -- I'm personally excited for this to be available again: https://github.com/rails/rails/blob/3-1-stable/activesupport/lib/active_support/core_ext/module/attr_accessor_with_default.rb#L22)

**Comment by sgrif** [comment]
Yeah, that comment roughly sums up my initial reaction as well. The same can be accomplished with overriding initialize or an after_initialize hook. I think @chancancode raises some excellent points, that might be worth rethinking the feature. I'm pretty much nights and weekends right now so I'll give this some more thought on Saturday.

**Pull request closed without merging**
