### PR TITLE
Fix typo in Configuration Guide

### PR DESCRIPTION
**Pull request by Erol**
### Summary

Fix typo in Configuring Rails Applications Guide.

### CODE REVIEW

**Comment by maclover7** [comment]
:+1: Thank you for your contribution!

**Comment by vipulnsward** [comment]
This looks like already fixed on docrails.

**Comment by maclover7** [comment]
@vipulnsward @rafaelfranca Who is in charge of syncing the `docrails` repo, seems to be getting pretty out of sync lately with the main `rails` repo... If there's a script or something, I can run it weekly or something

**Comment by schneems** [comment]
@senny would know

**Comment by rafaelfranca** [comment]
It is @vijaydev

**Comment by vijaydev** [comment]
The docrails repo is synced now. Closing this.

**Comment by Erol** [comment]
Sorry, didn't see that this was already corrected on `docrails`. Thanks everyone.

**Pull request closed without merging**
