### PR TITLE
Remove legacy mysql adapter

### PR DESCRIPTION
**Pull request by seuros**
Fixes #16891

### CODE REVIEW

**Comment by fillman** [comment]
tumblr_inline_nr7ry9rea21sh9sko_400

**Comment by fillman** [comment]
Cudos to all the contributors of this gem.

**Comment by maclover7** [comment]
Is this a dup of #16891?

**Comment by guilleiguaran** [comment]
is this going to be extracted to a separated gem?

**Comment by matthewd** [comment]
@guilleiguaran yes... I believe the plan is that we'll extract it in a working form, then hand it over to someone who actually uses `mysql`.

**Pull request merged**
