### PR TITLE
Refactor ActiveRecord::QueryLogs context API

### PR DESCRIPTION
**Pull request by casperisfine**
This remove the null object as proposed in https://github.com/rails/rails/commit/8af78700d244c9e2e6403ce704326ef45ecbe288 (cc @rafaelfranca @jhawthorn @kaspth). 

Since it pretends to be nil but acts as thruthy in boolean context it cause more confusion than it cleans code.

Also `update_context` is removed in favor of `set_context` without a block.

Also cc @keeran

### CODE REVIEW

**Comment by rafaelfranca** [comment]
@matthewd got my suggestion. If you set two context values we should execute the tagging code for both contexts.

**Comment by rafaelfranca** [comment]
Are you going to implement that or should I?

**Comment by byroot** [comment]
I have a bunch on my plate already, so feel free to implement it. Otherwise I can probably get to it later this week.

**Comment by rafaelfranca** [comment]
Not sure if it is worth. Between the dynamic tags and direct context access adding per-context tagging code will just make the API  and the implementation more confusing. I made peace with those occasional exceptions when tagging queries. I wish it didn't fail the entire request though. Maybe we can notify the exception when we had the error notification API and silent it.

**Pull request merged**
