### PR TITLE
Enable query log tags by default on development env

### PR DESCRIPTION
**Pull request by MatheusRich**
### Motivation / Background

This can be used to trace troublesome SQL statements back to the application code that generated these statements. I feel like this is a good default value that helps with debugging and code discovery.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by MatheusRich** [comment]
@rafaelfranca thoughts? If this is approved, I can add tests and a CHANGELOG entry.

**Comment by rafaelfranca** [comment]
We already have another feature doing the same in development `verbose_query_logs` with this one pointing to the exact line of code that generated the query. Why do we need both?

**Comment by MatheusRich** [comment]
@rafaelfranca `verbose_query_logs` might point to a model scope or method (that might be called inside a view), so it might not be evident which controller **or job** generated that query. It is also useful when using multiple databases because the query logs can identify which db is being used.

**Comment by rafaelfranca** [comment]
Sounds good let's get this finished up.

As a general direction, don't open draft PRs, they are just ignored, and I would actually go as far as automatically closing draft PRs. Either the PR is ready to be reviewed or send a message in the Rails forum. Our attention spam is very small, so if we see a draft PR we will just close the tab since it isn't ready and never come back.

**Comment by MatheusRich** [comment]
@rafaelfranca Thanks for letting me know! I think this is finished now.

Side note: should we add the guideline to not open draft PRs in the contributing docs?

**Comment by skipkayhil** [comment]
How do query logs interact with prepared statements? My understanding was the two were not compatible and all db adapters except MySQL will use prepared statements by default.

**Comment by zzak** [comment]
> How do query logs interact with prepared statements? My understanding was the two were not compatible and all db adapters except MySQL will use prepared statements by default.

@skipkayhil They don't. See: #48631

**Comment by MatheusRich** [comment]
@rafaelfranca this is probably good to go

**Pull request merged**
