### PR TITLE
Rename `Middleware#remove` to `Middleware#delete!`

### LINKED ISSUE #42862: Clarify difference between Middleware#remove and Middleware#delete
PR https://github.com/rails/rails/pull/42821 added `Middleware#remove`.
But as @morgoth commented https://github.com/rails/rails/pull/42821#issuecomment-885666634,
it's unclear how `#remove` differs from `#delete`.

We should document these methods and clarify the difference.
Maybe also add an example to the guides? https://github.com/rails/rails/pull/42821#issuecomment-883625511
Also renaming `#remove` to `#delete!` could make things clearer.

### PR DESCRIPTION
**Pull request by dixpac**
Renames the method for clearer API and adds the NOTE to the guides.

Fixes #42862 

r? @p8

### CODE REVIEW

**Comment by marivaldo** [comment]
this is the same #42867

**Comment by dixpac** [comment]
Alright! I'm closing mine since it is @sato11 's first PR 🎉

**Comment by p8** [comment]
Thanks @dixpac 🙏

**Comment by sato11** [comment]
Thanks for letting me take a chance on this @dixpac. I appreciate it! ❤️

**Pull request closed without merging**
