### PR TITLE
Add base62 method to SecureRandom

### PR DESCRIPTION
**Pull request by valenciaj**
Add base62 method to SecureRandom

### CODE REVIEW

**Comment by skipkayhil** [comment]
Hey @valenciaj, thanks for opening a PR! Is this something that would be useful internally to Rails? We generally don't add new core extension when this is not the case.

**Comment by p8** [comment]
Thanks @valenciaj !
In Ruby 3.3 this can be easily implemented (as is shown is this PR as well), so I don't think we want to implement this for every base*:
```ruby
SecureRandom.alphanumeric(n, chars: BASE62_ALPHABET)
```

**Comment by valenciaj** [comment]
> Hola @valenciaj, gracias por abrir un PR! ¿Es esto algo que sería útil internamente para Rails? Generalmente no agregamos una nueva extensión de núcleo cuando este no es el caso.

Hi, I do monkeypaching to do this in every project I start, and IMHO I think can be util. No performance penalty.

**Comment by valenciaj** [comment]
> Gracias @valenciaj ¡por contribuir a Rails! En Ruby 3.3 esto se puede implementar fácilmente (como se muestra es este PR también), así que no creo que queramos implementar esto para cada base:
> 
> ```ruby
> SeguroRandom.alfanumérico(n, chars: CUSTOM_ALFABETO)
> ```

Ok, I know, but why base58 and not base62?

**Comment by p8** [comment]
> Ok, I know, but why base58 and not base62?

Base58 removes characters from Base64 that look very similar like `0` and `O`.
It allows generating random string that can be typed by a human.
What is the use case for Base62 that can't be solved by Base64 or Base58?
The difference in security between Base58 and Base62 are probably neglible and can be fixed by incrementing n by 1 character.

**Comment by valenciaj** [comment]
> > Ok, I know, but why base58 and not base62?
> 
> Base58 removes characters from Base64 that look very similar like `0` and `O`. It allows generating random string that can be typed by a human. What is the use case for Base62 that can't be solved by Base64 or Base58? The difference in security between Base58 and Base62 are probably neglible and can be fixed by incrementing n by 1 character.

It's, but you can do the same with base58 and base64.

**Comment by p8** [comment]
Hey @valenciaj 

As we [generally reject changes to Active Support core extensions](https://github.com/rails/rails/blob/f4b08457a4ab40418da9aa2155880fea32caf0fe/CONTRIBUTING.md?plain=1#L42) I'm closing this PR.
I'm not seeing a common usecase for adding `#base62`.
If the changes in Ruby 3.3 were already present, Rails would probably not have added the `#base64` method either.
Thanks for your contribution ❤️

**Pull request closed without merging**
