### PR TITLE
Refactor test to use Enumerable#one?

### PR DESCRIPTION
**Pull request by tcopeland**
### Summary

Provide a general description of the code changes in your pull
request... were there any bugs you had fixed? If so, mention them. If
these bugs have open GitHub issues, be sure to tag them here as well,
to keep the conversation linked together.
### Other Information

If there's anything else that's important and relevant to your pull
request, mention that information here. This could include
benchmarks, or other information.

Finally, if your pull request affects documentation or any non-code
changes, guidelines for those changes are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#contributing-to-the-rails-documentation)

Thanks for contributing to Rails!

### CODE REVIEW

**Comment by kaspth** [comment]
Thanks, but this is a cosmetic commit which we don't accept 😁

**Comment by tcopeland** [comment]
Oops ok sounds good sorry for the noise!

**Comment by dideler** [comment]
> Thanks, but this is a cosmetic commit which we don't accept 😁

Should this be explicitly stated in the [CONTRIBUTING.md](https://github.com/rails/rails/blob/master/CONTRIBUTING.md)?

**Comment by prathamesh-sonpatki** [comment]
It's mentioned here http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#write-your-code :)

**Comment by jonatack** [comment]
In [CONTRIBUTING.md](https://github.com/rails/rails/blob/master/CONTRIBUTING.md):

"Before submitting, please read the [Contributing to Ruby on Rails](http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html) guide to know more about coding conventions and benchmarks."

**Comment by dideler** [comment]
Fair enough, though I do think that a simple "We do not accept cosmetic changes." in the more noticeable CONTRIBUTING.md will prevent a lot of drive-by PRs and reduce effort by the Rails team.

At the moment there seems to be [over 300 PRs](https://github.com/rails/rails/pulls?q=is%3Apr+cosmetic+is%3Aclosed) that were closed due to cosmetic changes.

**Comment by sgrif** [comment]
The same could be said for just about any single thing in the contributing guide. At the end of the day, most of the people who are opening them aren't looking at CONTRIBUTING.md.

**Pull request closed without merging**
