### PR TITLE
Clarify accessor API for CSP

### PR DESCRIPTION
**Pull request by spdawson**
### Summary

Calling any of the "directive" methods (e.g. `script_src`) of `ActionDispatch::ContentSecurityPolicy` without an argument will clear the associated directive in the CSP. This seems a clear violation of the principle of least surprise in the CSP API.

This change rationalises the directives API so that an explicit `false` argument is required in order to clear the directive associated with each method. Calling a "directive" method without arguments acquires thereby the ordinary semantic of an accessor.

### CODE REVIEW

**Comment by pixeltrix** [comment]
Hmm, not sure about this - if we're changing `p.script-src` to act like a getter then wouldn't it make more sense to change to a standard setter method? e.g.

``` ruby
p.script_src = [:self, :https]
```

The reason I went with `p.script_src` is that you're effectively setting an empty policy whereas `p.script_src false` seems to suggest that `Content-Security-Header: script-src false;` is a thing that prevents scripts being loaded via `<script src="">`.

@jeremy @rafaelfranca any strong opinions?

**Comment by spdawson** [comment]
> wouldn't it make more sense to change to a standard setter method?

Personally, I think this would make for a far clearer API; though of course it would rather spoil the DSL-style of the `content_security_policy` blocks...

> The reason I went with `p.script_src` is that you're effectively setting an empty policy

To my mind though, the trouble is that this doesn't _read_ as "set an empty policy". Perhaps explicitly setting an empty array, to clear the directive, is an acceptable compromise?

**Comment by rafaelfranca** [comment]
I'd prefer to raise an exception when no argument is provided.

```
p.script_src []
```

and

```
p.script_src nil
```

make sense as setting that config to an empty value, but

```
p.script_src
```

looks like a programmer error.

@dhh any opinion on this?

**Comment by dhh** [comment]
How about using a specific symbol for a default policy, like `p.script_src :default` or something like that. Not liking the magic ness of nil or empty array.

**Comment by rafaelfranca** [comment]
`p.script_src :default` seems good to me, but there is an chance of matching a valid CSP config in the future. I think `nil` is safer on those cases.

**Comment by dhh** [comment]
We can go even more explicit and unlikely-to-future clash with something
like :clear_directive or whatever. But nil feels like a magic number,
something that requires a lookup in the docs to understand.

**Pull request closed without merging**
