### PR TITLE
Add puma app server to Gemfile in order to start test/dummy

### PR DESCRIPTION
**Pull request by donapieppo**
### Summary

Without an app server in engine's Gemfile (like puma/unicorn/webrick)
the test/dummy application can not be started with ./bin/rails server
as indicatred in the guide. Running ./bin/rails server returns
the error Could not find server ''.

### CODE REVIEW

**Comment by skipkayhil** [comment]
Hey @donapieppo, thanks for the PR! I'm wondering if we should just put a web server in the Gemfile for engines so that things just work without any extra steps 🤔

**Comment by donapieppo** [comment]
> I'm wondering if we should just put a web server in the Gemfile for engines so that things just work without any extra steps thinking

It would certainly simplify, but while you can change the web server from your application Gemfile, you would have always the web server defined in the engine without the possibility to remove it. I think it would be overkill.

**Review by rafaelfranca — CHANGES_REQUESTED** [review]
We should just add puma to the engine's gemfile. This stoped work after webrick was removed from Ruby core, but people should not have to configure anything else. Things should just work.

**Comment by rafaelfranca** [comment]
Why @donapieppo. Are you interested in adding the line to the Gemfile entry?

**Comment by donapieppo** [comment]
@rafaelfranca 
[98b7b5e](https://github.com/rails/rails/pull/45950/commits/98b7b5e9ca7855ec6e4c37959b6b740d11a2cd15) should solve the issue.

**Comment by fedeagripa** [comment]
> 

Still having this error too when I just created an engine with `7.0.4.1`.
Needed to add `puma` as dev dependency to run the dummy app

**Pull request merged**
