### PR TITLE
Fix zero-byte files upload in #33630

### PR DESCRIPTION
**Pull request by marceloperini**
### Summary
* Solve the problem described in #33630;
* Fix bad range definition when try to upload a zero byte file;

### CODE REVIEW

**Comment by eileencodes** [comment]
@marceloperini can you add a test?

**Comment by marceloperini** [comment]
Sure @eileencodes, I'll make this today.

**Comment by rafaelfranca** [comment]
@marceloperini is this ready? You added WIP in the title but it looks ready to me.

**Comment by marceloperini** [comment]
@rafaelfranca it is not ready. I've created the test block "direct upload a zero byte file" in `activestorage/test/service/s3_service_test.rb` that tests an direcly upload to an s3 bucket, but for some reason this block are not passing through the method `ActiveStorage::Blob::Identifiable#download_identifiable_chunk`. Consequently you are not testing the use of this method. I'll study more about the active storage structure and fix the test case.

**Comment by georgeclaghorn** [comment]
You’ll need to attach the directly-uploaded blob to a record to trigger content type identification.

**Comment by marceloperini** [comment]
@georgeclaghorn got it! Thanks.

**Comment by marceloperini** [comment]
@georgeclaghorn, @rafaelfranca, @eileencodes I think it's done.

**Comment by zhouchunyu** [comment]
@marceloperini when I just run bin/test test/service/s3_service_test.rb.Your test case will fail because this file didn't require database/setup.I think it's better to move this test case to one_test.rb like this
```
one_test.rb 
test "attaching an empty blob to an existing record" do
    blob = directly_upload_file_blob filename: "empty_file.txt", content_type: nil
    user = User.create! name: "DHH", avatar: blob
    assert_equal user.avatar.blob, blob
  end
```

**Comment by marceloperini** [comment]
Great idea @zhouchunyu. Thanks, I'll make this change and open another PR.

**Comment by marceloperini** [comment]
@zhouchunyu I think this can be solved if adding "require 'database/setup'" in s3_service_test.rb what do you think? I opened this PR (#34585) check it out.

**Pull request merged**
