### PR TITLE
Fixing the active record has many association test which is failing w…

### PR DESCRIPTION
**Pull request by Karunakar**
### Summary

Test failed when run bundle exec rake test:sqlite3. So I thought just fix it.

Please let me know more information  on this
### Other Information

but working fine when i ran single file

### CODE REVIEW

**Comment by rafaelfranca** [comment]
This is what travis does and there is no broken test there. Could you show how the failure message looks like?

**Comment by Karunakar** [comment]
Yes Please.. Here is the failure message

  1) Failure:
HasManyAssociationsTest#test_do_not_call_callbacks_for_delete_all [/home/shashi/saraswathi/rails/rails-1/activerecord/test/cases/associations/has_many_associations_test.rb:248]:
bulbs should have been deleted using :delete_all strategy.
Expected: 0
  Actual: 1

**Comment by yahonda** [comment]
I see this failure when I test using rails-dev-box.

* At host 
```
> git clone https://github.com/rails/rails-dev-box
> vagrant up
> vagrant ssh
```

* At guest ( git config --global url."https://".insteadOf git:// needs to be done in my network environment )
```
vagrant@rails-dev-box:~$ git clone http://github.com/rails/rails.git

vagrant@rails-dev-box:~$ cd rails/activerecord/

vagrant@rails-dev-box:~/rails/activerecord$ git config --global url."https://".insteadOf git://

vagrant@rails-dev-box:~/rails$ bundle

vagrant@rails-dev-box:~/rails/activerecord$ bundle exec rake test
```
You can see full output here https://gist.github.com/yahonda/ae8c335d9db193a43494480639f7c295

**Comment by rafaelfranca** [comment]
Hmmm. May it be a sqlite3 version problem? Maybe we should match the same version on travis and see.

**Comment by yahonda** [comment]
This failure reproduces with all bundled adapters - sqlite, mysql2 and postgresql. then sqlite3 version may not be the only reason. Let me take a look at this since I just reproduce them using rails-dev-box, not locally.

**Comment by yahonda** [comment]
Here is a minimum case to reproduce this failure for all bundled adapters.
```ruby
for i in sqlite3 mysql2 postgresql
do
ARCONN=$i bundle exec ruby -w -I"lib:test" -I"/var/lib/gems/2.3.0/gems/rake-11.1.2/lib" "/var/lib/gems/2.3.0/gems/rake-11.1.2/lib/rake/rake_test_loader.rb" "test/cases/fixtures_test.rb" "test/cases/associations/has_many_associations_test.rb" 
done
```

* Result
```ruby
$ for i in sqlite3 mysql2 postgresql
> do
> ARCONN=$i bundle exec ruby -w -I"lib:test" -I"/var/lib/gems/2.3.0/gems/rake-11.1.2/lib" "/var/lib/gems/2.3.0/gems/rake-11.1.2/lib/rake/rake_test_loader.rb" "test/cases/fixtures_test.rb" "test/cases/associations/has_many_associations_test.rb" 
> done
Using sqlite3
Run options: --seed 17880

# Running:

..................................................................................................................................F........................................................................................................................................................................................................................

Finished in 4.263544s, 81.3877 runs/s, 345.0181 assertions/s.

  1) Failure:
HasManyAssociationsTest#test_do_not_call_callbacks_for_delete_all [/home/vagrant/rails/activerecord/test/cases/associations/has_many_associations_test.rb:248]:
bulbs should have been deleted using :delete_all strategy.
Expected: 0
  Actual: 1

347 runs, 1471 assertions, 1 failures, 0 errors, 0 skips
Using mysql2
Run options: --seed 60421

# Running:

........................................................................................................................................................................................F..................................................................................................................................................................

Finished in 5.694053s, 60.9408 runs/s, 258.3397 assertions/s.

  1) Failure:
HasManyAssociationsTest#test_do_not_call_callbacks_for_delete_all [/home/vagrant/rails/activerecord/test/cases/associations/has_many_associations_test.rb:248]:
bulbs should have been deleted using :delete_all strategy.
Expected: 0
  Actual: 1

347 runs, 1471 assertions, 1 failures, 0 errors, 0 skips
Using postgresql
Run options: --seed 27789

# Running:

.........................................................................................................................................F....................................................................................................................................................................................................................

Finished in 6.974502s, 50.1828 runs/s, 212.2015 assertions/s.

  1) Failure:
HasManyAssociationsTest#test_do_not_call_callbacks_for_delete_all [/home/vagrant/rails/activerecord/test/cases/associations/has_many_associations_test.rb:248]:
bulbs should have been deleted using :delete_all strategy.
Expected: 0
  Actual: 1

350 runs, 1480 assertions, 1 failures, 0 errors, 0 skips
vagrant@rails-dev-box:~/rails/activerecord$
```
* Software version
```
Welcome to Ubuntu 15.10 (GNU/Linux 4.2.0-38-generic x86_64)
```
```
vagrant@rails-dev-box:~/rails/activerecord$ sqlite3 --version
3.8.11.1 2015-07-29 20:00:57 cf538e2783e468bbc25e7cb2a9ee64d3e0e80b2f
```
```
vagrant@rails-dev-box:~/rails/activerecord$ mysql --version
mysql  Ver 14.14 Distrib 5.6.30, for debian-linux-gnu (x86_64) using  EditLine wrapper
```
```
vagrant@rails-dev-box:~/rails/activerecord$ psql --version
psql (PostgreSQL) 9.4.8
```

**Comment by yahonda** [comment]
Switching the order of two _test.rb files changes the result.

* Always get failures
```ruby
for i in sqlite3 mysql2 postgresql
do
ARCONN=$i bundle exec ruby -w -I"lib:test" -I"/var/lib/gems/2.3.0/gems/rake-11.1.2/lib" "/var/lib/gems/2.3.0/gems/rake-11.1.2/lib/rake/rake_test_loader.rb" "test/cases/fixtures_test.rb" "test/cases/associations/has_many_associations_test.rb" 
done
```

* No failures
```ruby
for i in sqlite3 mysql2 postgresql
do
ARCONN=$i bundle exec ruby -w -I"lib:test" -I"/var/lib/gems/2.3.0/gems/rake-11.1.2/lib" "/var/lib/gems/2.3.0/gems/rake-11.1.2/lib/rake/rake_test_loader.rb" "test/cases/associations/has_many_associations_test.rb" "test/cases/fixtures_test.rb" 
done
```

**Comment by Karunakar** [comment]
**I am running these tests in my local ubuntu 16.04**  


**bundle exec ruby -w -I"lib:test" -I"/root/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib" "/root/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/rake_test_loader.rb"  "test/cases/fixtures_test.rb" "test/cases/associations/has_many_associations_test.rb"
Using sqlite3**


  1) Failure:
HasManyAssociationsTest#test_do_not_call_callbacks_for_delete_all [/home/shashi/saraswathi/rails/rails-1/activerecord/test/cases/associations/has_many_associations_test.rb:248]:
bulbs should have been deleted using :delete_all strategy.
Expected: 0
  Actual: 1

**# ARCONN=mysql2 bundle exec ruby -w -I"lib:test" -I"/root/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib" "/root/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/rake_test_loader.rb"  "test/cases/fixtures_test.rb" "test/cases/associations/has_many_associations_test.rb"**
Using mysql2
Run options: --seed 31653


  1) Failure:
HasManyAssociationsTest#test_do_not_call_callbacks_for_delete_all [/home/shashi/saraswathi/rails/rails-1/activerecord/test/cases/associations/has_many_associations_test.rb:248]:
bulbs should have been deleted using :delete_all strategy.
Expected: 0
  Actual: 1

****# ARCONN=postgresql bundle exec ruby -w -I"lib:test" -I"/root/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib" "/root/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/rake_test_loader.rb"  "test/cases/fixtures_test.rb" "test/cases/associations/has_many_associations_test.rb"
 Using postgresql**


  1) Failure:
HasManyAssociationsTest#test_do_not_call_callbacks_for_delete_all [/home/shashi/saraswathi/rails/rails-1/activerecord/test/cases/associations/has_many_associations_test.rb:248]:
bulbs should have been deleted using :delete_all strategy.
Expected: 0
  Actual: 1

As per my idea This test failed because test/cases/fixtures_test.rb  bulb fixtures are loading in FixturesWithDefaultScopeTest line number 940 and 941  and same bulb fixtures are persists in the associations/has_many_associations_test.rb
Default Bulb.count  is 1

**Comment by yahonda** [comment]
I believe this has been already addressed by #25828.

**Comment by bogdanvlviv** [comment]
It already fixed. Could you please close this PR?

**Comment by eileencodes** [comment]
Thanks for the update @bogdanvlviv

**Pull request closed without merging**
