### PR TITLE
Fix context of *_through association scope

### PR DESCRIPTION
**Pull request by pftg**
Rebase of #12725

/cc @maclover7

### CODE REVIEW

**Comment by pftg** [comment]
working on fixing tests

**Comment by pftg** [comment]
@matthewd fixed broken code after rebase. Pls queue this PR for your review.

P.S. Failed tests are not connected with current changes. They are the same as master.

**Comment by askel4dd** [comment]
Experienced problem because of this bug.

With these relations:
```
class Children
has_many :families
has_many :parents, -> { order('families.position') }, through: :families
end
```
Code `Children.includes(:parents).first.parents` will raise exception with SQL error `Unknown column 'families.position'

Solved by adding separate association without ordering as temporary solution.

**Comment by kamipo** [comment]
Fixed by a26cff3c1235c61cd0135bed4ef63d7be452b458.

**Pull request closed without merging**
