### PR TITLE
[ci skip] Update what methods `Migration#change` can reverse

### PR DESCRIPTION
**Pull request by yui-knk**

### CODE REVIEW

**Comment by kaspth** [comment]
Hey, @yui-knk, you've sent a lot of pull requests which is great. But you almost never add a description to help give us reviewers some background on why your changes should be merged. A sentence or two is all that's needed :)

So what made the current documentstion stale here?

**Comment by yui-knk** [comment]
@kaspth thanks for your comments.
This PR's has two backgrounds.

* Documentations and comments about what methods `Migration#change` can reverse is out of date. For example `change_column_default` is now reversible by this [commit](https://github.com/rails/rails/pull/20018).

* Comments about `CommandRecorder` dose not match with Rails Guide. For example `add_foreign_key` is listed only on Rails Guide.

**Comment by sgrif** [comment]
It'd be great to have that context in the commit message. :)

**Comment by yui-knk** [comment]
@sgrif Can I amend commit to include that context to commit message. And `push -f` the commit?

**Comment by sgrif** [comment]
Yes

**Comment by yui-knk** [comment]
Done :+1:

**Comment by sgrif** [comment]
Thanks.

**Pull request merged**
