### PR TITLE
Fix activesupport files by requiring missing dependencies

### LINKED ISSUE #49709: active_support/core_ext/array/conversions raises when required
### Steps to reproduce

found via cocoapods, running `pod` blows up:

```
5549 % ruby -ractive_support/core_ext/array/conversions -e 0
/private/tmp/xxx/gems/activesupport-7.1.1/lib/active_support/core_ext/array/conversions.rb:108:in `<class:Array>': undefined method `deprecator' for ActiveSupport:Module (NoMethodError)

  deprecate to_default_s: :to_s, deprecator: ActiveSupport.deprecator
                                                          ^^^^^^^^^^^
Did you mean?  deprecate_constant
	from /private/tmp/xxx/gems/activesupport-7.1.1/lib/active_support/core_ext/array/conversions.rb:8:in `<top (required)>'
	from <internal:/Users/ryan/.rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:159:in `require'
	from <internal:/Users/ryan/.rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:159:in `rescue in require'
	from <internal:/Users/ryan/.rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:39:in `require'
<internal:/Users/ryan/.rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- active_support/core_ext/array/conversions (LoadError)
	from <internal:/Users/ryan/.rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
```

### Expected behavior

requiring any file in rails shouldn't raise

### Actual behavior

see above

### System configuration
**Rails version**: 7.1.1

**Ruby version**: 3.2.2

### PR DESCRIPTION
**Pull request by zenspider**
Fixes #49709 by adding needed requires

### CODE REVIEW

**Comment by zenspider** [comment]
Found more via:

```
for F in lib/active_support/core_ext/*/conversions.rb ; do ruby -I.:lib -r$F -e 0; done
```

amending my commit w/ extra requires

**Comment by zenspider** [comment]
Found even more more via:

```
for F in lib/active_support/**.rb ; do echo $F; ruby -I.:lib:../railties/lib -r$F -e 0; done
```

**Comment by rafaelfranca** [comment]
This isn't the right fix. The right fix is cocoa pods do the right thing and require `active_support` before doing anything with it like it is documented.

**Comment by rafaelfranca** [comment]
Reverting.

**Pull request merged**
