### PR TITLE
Improve casing in encryption guide headings [ci-skip]

### PR DESCRIPTION
**Pull request by p8**
### Summary

Update the guide to use the casing as defined in the contribution guide.
https://guides.rubyonrails.org/ruby_on_rails_guides_guidelines.html#headings

### CODE REVIEW

**Review by jonathanhefner — COMMENTED** [review]
I'm a bit confused by the casing on some of these.  Perhaps the result of an incomplete regexp find / replace?  I commented on a few to illustrate what I mean.

**Review by jonathanhefner — COMMENTED** [review]
My previous suggestions weren't an exhaustive list, but I've added suggestions for the remaining few.  Thank you for working on this, @p8! :raised_hands:

**Comment by jonathanhefner** [comment]
It's possible that I will be unavailable for the next several days, so I went ahead and force-pushed a commit to capitalize "when".  Thank you again, @p8!  :smiley:

**Comment by p8** [comment]
Thanks for the quick review and fix @jonathanhefner! 😄

**Pull request merged**
