### PR TITLE
remove noise from AM tests

### PR DESCRIPTION
**Pull request by aditya-kapoor**

### CODE REVIEW

**Comment by vipulnsward** [comment]
Would be good to merge post https://github.com/rails/rails/pull/18526

**Comment by aditya-kapoor** [comment]
:cool: makes sense..

**Comment by rafaelfranca** [comment]
Could you rebase it?

**Comment by arthurnn** [comment]
You can `include ActiveSupport::Testing::Stream` now to use the method.

**Comment by aditya-kapoor** [comment]
:cool: will do the rebase by tonight...

**Comment by aditya-kapoor** [comment]
@rafaelfranca done...

**Pull request merged**
