### PR TITLE
Cleaning actionpack tests

### PR DESCRIPTION
**Pull request by thiagopradi**
Hi Folks,

This PR removes a few unused / old code from actionpack tests.

Thiago

### CODE REVIEW

**Comment by arthurnn** [comment]
Do you mind squashing your commits in one ? thanks

**Comment by spastorino** [comment]
@arthurnn I'd just merge I think @tchandy splitted the things that have different semantics

**Comment by rafaelfranca** [comment]
@spastorino :shipit:

**Comment by arthurnn** [comment]
:+1:

**Comment by tchandy** [comment]
@arthurnn @rafaelfranca @spastorino thanks :+1: :+1: :+1:

**Pull request merged**
