### PR TITLE
Silence DebugExceptions template render logs during exceptions

### PR DESCRIPTION
**Pull request by gsamokovarov**
When an exception is raised, those Action View rendering logs are just
noise for the end developer. I recently silenced those from Web Console,
as we do use Action View rendering in it as well. It used created a half
a screen of rendering logs. I think we can save those in this recent
push for cleaner development logs.

The silencing is a bit hacky and we have a bunch of it now, so we
can also invest in turning off the logs directly from Action View
objects instead of silencing off the logging streams.

### CODE REVIEW

**Comment by gsamokovarov** [comment]
Before

```
RuntimeError ():

app/controllers/home_controller.rb:4:in `index'
  Rendering /Users/genadi/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-f9a39e0d5140/actionpack/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout
  Rendering /Users/genadi/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-f9a39e0d5140/actionpack/lib/action_dispatch/middleware/templates/rescues/_source.html.erb
  Rendered /Users/genadi/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-f9a39e0d5140/actionpack/lib/action_dispatch/middleware/templates/rescues/_source.html.erb (4.5ms)
  Rendering /Users/genadi/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-f9a39e0d5140/actionpack/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb
  Rendered /Users/genadi/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-f9a39e0d5140/actionpack/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.6ms)
  Rendering /Users/genadi/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-f9a39e0d5140/actionpack/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb
  Rendered /Users/genadi/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-f9a39e0d5140/actionpack/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.4ms)
  Rendered /Users/genadi/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/rails-f9a39e0d5140/actionpack/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (129.7ms)
```

After:

```
RuntimeError ():

app/controllers/home_controller.rb:4:in `index'
```

**Comment by vipulnsward** [comment]
Nice, I was going to handle this in https://github.com/rails/rails/pull/25222 but it can go separately as well.
r? @dhh

**Comment by dhh** [comment]
Like the result, will let others comment on the implementation. But cleaning up the backtrace noise is 👌

**Comment by matthewd** [comment]
Committed as 40fc3874f0ea720c0780b2eae72f48c0879f325e, with a test in 1c7a3230ba28c578835d52c5b6d086c3b38f1b20

**Comment by gsamokovarov** [comment]
Thanks @matthewd!

**Pull request closed without merging**
