### PR TITLE
Fix 4.2-stable build - Cherry pick "use correct Gemfile in `bin/setup` test"

### PR DESCRIPTION
**Pull request by prathamesh-sonpatki**
### Summary

Currently, `bin/setup` test uses Gemfile of Rails. But this Gemfile is not a
file to be used in Rails application.
Add a Gemfile to Rails application that is created for test, it has been
modified to use the Gemfile.

### CODE REVIEW

**Comment by prathamesh-sonpatki** [comment]
Now railties tests are fixed but queue_classic tests are failing. Working on them.

**Comment by prathamesh-sonpatki** [comment]
r? @matthewd 

As per your suggestion, updated bundler for 1.9.3 but faced issues with random behavior in builds for 2.0 and 2.1 as well for queue_classic gem like https://travis-ci.org/rails/rails/jobs/163622079#L294 and https://travis-ci.org/rails/rails/jobs/163622078#L294

So I tried updating bundler version of these two versions as well and it worked.

**Comment by matthewd** [comment]
Oh, the gem update is way faster than I was expecting. Let's just do it on all the versions, then. 👍🏻

I was worried it'd add something like 30 seconds per job. At this speed, maybe we should just apply this across the board on the current branches too.

**Comment by prathamesh-sonpatki** [comment]
@matthewd Done. Will send PR for current branches later.

**Comment by prathamesh-sonpatki** [comment]
@guilleiguaran I see your merge commit in this PR. Did you add it because it was not merging cleanly with 4-2-stable?

**Comment by guilleiguaran** [comment]
@prathamesh-sonpatki yes, github said that the branch weren't updated with 4-2-stable

**Comment by prathamesh-sonpatki** [comment]
Thanks :smile:

**Comment by guilleiguaran** [comment]
thank you!!!

**Pull request merged**
