### PR TITLE
Make possible to pass proc as group_method in option_groups_from_collection_for_select

### PR DESCRIPTION
**Pull request by Azdaroth**
I needed to do some filtering of child objects but didn't want to add a method for it in a model so I thought about using lambda in this case. This PR makes it possible to do so.

### CODE REVIEW

**Comment by Azdaroth** [comment]
What do you think about this enhancement? Another usecase for that would be using helper method taking multiple arguments to do proper filtering, which is currently impossible to do, would be great if it was merged to Rails and be available without monkeypatching.

**Comment by yuki24** [comment]
:-1: on this. This would lead people to write more logic in views.

**Comment by Azdaroth** [comment]
@yuki24 That may be a valid point but how would you handle the following usecase? Imagine we've got Categories and Products, and we want to display in input products grouped by categories. In "normal" situation we could just pass symbol ```:products``` and we would get products for each category. But what if we need to eg. show products that were not bought by `current_user`? That would require passing additional argument to the method, ```current_user```, and would look like ```-> (category) { category.products_not_bought_by_user(current_user)  }```, it can also get trickier sometimes and you may need to pass more arguments. If we can only pass a symbol, I believe it's impossible to achieve the same result.

**Comment by yuki24** [comment]
@Azdaroth do that in the controller action that renders the view.

**Comment by yuki24** [comment]
@Azdaroth Also, I don't think I understand what `products_not_bought_by_user(current_user)` is. I guess `Product.includes(:category).group_by(&:category)` would work for you.

**Comment by Azdaroth** [comment]
@yuki24 Basically I would like to do some additional filtering that would involve passing some arguments to the method. In that usecase I don't want to display all products for given category, but only the specific group products which requires some fltering.

**Comment by yuki24** [comment]
@yuki24 again, you can do that in the controller action that renders the view.

**Comment by Azdaroth** [comment]
@yuki24 Hmm, not sure if I got it right. The only way I can imagine doing it in controller would be like that: Start with ```@category = Category.all```. Then we would add ```attr_accessor``` to ```Category``` model, eg. ``` attr_accessor :products_for_user ``` and then iterate over each category and write that attribute in controller:
```
@category.each { |category| category.products_for_user = category.products_not_bought_by_user(current_user) }
```
but that's a terrible idea and rather an antipattern. But it would be possible to pass symbol ```:products_for_user``` and that would work. The lambda approach looks cleaner I believe.

**Comment by yuki24** [comment]
@Azdaroth I would rather do:

```ruby
@products_by_category = Product.some_scope.not_bought_by_user(current_user).group_by(&:category)
```

**Comment by Azdaroth** [comment]
@yuki24  Ok, so we would now have the products we actually want to deal with, but no sure how to use it with that helper method, within ```collection.map do |group|``` (taken from the code of  ``` option_groups_from_collection_for_select```), the ```group``` would be array of two elements: first the category, and the second the array of products.

**Comment by Azdaroth** [comment]
@yuki24 Hmm, but I think we could use ```merge``` method from ActiveRecord and do like 
``` 
Category.joins(:products).merge(Product.some_scope.not_bought_by_user(current_user))
```

**Comment by yuki24** [comment]
@Azdaroth you've got a simpler answer! Maybe we can close this issue?

**Comment by Azdaroth** [comment]
@yuki24 That solves my usecase at least, but still thinking about any other it would be useful... But would be nice for consistency, if you look at eg. ```options_from_collection_for_select``` you can also pass a lambda for ```value_method``` and ```text_method```.

**Comment by Azdaroth** [comment]
@yuki24 Well, actually it doesn't solve my real usecase, the example with category and products was totally made up for simpler demonstration, in the real app it's different and much more complex. To illustrate with the same example (categories and products) it should be the following: still grouping products by category, but product can belong to many categories (many-to-many relation) and, that's going to be a bit contrived, but still a demonstration purpose, we keep track of the category the product was selected from (so we would need to add another input for selecting just category, and by selecting category the products would be filtered out by JS and showed according to selected category, but that's probably not really important, just giving a bigger picture). So if Product X belongs to Category A and Category B, but was bought from category A we only want to display it under category B. But we must consider also the case when we update the selected product from Category A and want to choose Product Y instead. So in that case we need to show this Product X under Category A when editing.
I hope you get the idea... It's something that can't be done using ```merge``` as it uses more custom logic and depending on various conditions (like if we are doing a new selection or updating the existing one)  it would return different products.

**Comment by Azdaroth** [comment]
@yuki24 Update: Or it would be possible in the demonstrated case with ```merge``` and using different sql query, depending on the state of selection (new or persisted), but that would be more complex than simply passing the lambda in views if there would be even more conditons.

**Comment by yuki24** [comment]
Then you can use `#scoping`:

```erb
<% # Do this without #joins or #includes %>
<% Product.some_scope.not_bought_by(current_user).scoping do %>
  <%= options_from_collection_for_select(@categories, :products, ...) %>
<% end %>
```

You can either do the same in controller:

```ruby
Product.not_bought_by(current_user).scoping do
  @categories = Category.all.each{|c| c.products.some_scope.load }
end
```

If performance would be an issue, the example below that implements a destructive method should help:

```ruby
@categories = Category
    .joins(:products)
    .merge(Product.some_scope)
    .each {|c| c.reject_products_bought_by!(current_user) }
```

There are already many ways of solving your issue and related. If the issue was a little different, other solutions would probably exist.

**Comment by Azdaroth** [comment]
@yuki24 Ok, thanks, I''ll play with some other ways and see what works without lambda.

**Comment by Azdaroth** [comment]
Ok, all similar problems were eventually solved with addition of ajax anyway, so I guess it's not neccessary. PR can be closed.

**Pull request closed without merging**
