### PR TITLE
substitute sass-rails gem by sassc-rails

### PR DESCRIPTION
**Pull request by utilum**
"Ruby Sass Has Reached End-of-Life"
http://sass.logdown.com/posts/7828841

"Ruby Sass should no longer be used, and will no longer be receiving any
updates. See the Sass blog, and consider switching to the sassc gem."
https://github.com/sass/ruby-sass

### CODE REVIEW

**Comment by bogdanvlviv** [comment]
I guess it we should use `gem "sass-rails"`, see https://github.com/rails/sass-rails/pull/424

**Comment by utilum** [comment]
I guess you are right :)
Thank you. Closing.

**Comment by deivid-rodriguez** [comment]
I asked about this in https://github.com/rails/rails/issues/32896#issuecomment-490430775.

The way I see it, the wrapper gem is great for a painless upgrade, but internally and for new apps, `sassc-rails` should be used since it's where all the development is happening. Adding the `sass-rails` dummy dependency to new applications seems like an unnecessary and misleading indirection to me.

**Comment by markets** [comment]
I agree with @deivid-rodriguez here. The point of making a new release as a wrapper to allow a smooth upgrade, is totally fine, but for newer apps/gems, why adding 1 layer more? ¯\_(ツ)_/¯

**Pull request closed without merging**
