### PR TITLE
Allow generating plugins for API applications

### PR DESCRIPTION
**Pull request by robin850**
Hello,

This pull requests adds a `--api` option in order to generate plugins that can be added inside API applications. It is split into several commits to ease the review process but once everything is fine, I can squash them.

Cross-refs #19832 and [the todo on Basecamp](https://basecamp.com/1755757/projects/6741427/todos/183482259#comment_294960031).

Have a nice day.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Is the dummy app API only already?

**Comment by robin850** [comment]
@rafaelfranca : Thanks for merging! I'm not sure to understand your question though  ; the dummy app has been made API-only in https://github.com/robin850/rails/commit/ce32c9da962a9dd7a894c9a4457db9dd5f5a5a1f.

**Comment by spastorino** [comment]
@robin850 :+1:, looks good from what I see. Will review properly next week.

**Comment by rafaelfranca** [comment]
@spastorino it is already merged :smile:

@robin850 I see, thank you for pointing.

**Comment by spastorino** [comment]
@rafaelfranca I know but a couple of more eyes taking a look at it wouldn't hurt :)

**Comment by jmbejar** [comment]
@robin850 @rafaelfranca @spastorino I found a little issue related with this PR.

Let's say you have a fresh only api application (created with `rails new --api`) that is the host application. Then you create an engine with `--api` option and some stuff using the scaffold generator.

Once you mount the engine and try the new routes in the host application, you get an `undefined method `new' for nil:NilClass` error in [this line into AMS](https://github.com/rails-api/active_model_serializers/blob/0-10-stable/lib/active_model/serializer/array_serializer.rb#L16).

The problem happens because AMS is not present when the resources are created in the engine, so serializers classes are not created (in fact, AMS does not seem to work in the context of an engine, adding this gem to the engine project is not enough). However, since AMS is added by default to a new rails api-only app, the exception will happen.

Removing AMS from the host application solves the problem, but I'm concerned because this is not the default setup.

This is probably material for a separate issue ticket, since I don't have a clear solution yet.

**Comment by rafaelfranca** [comment]
Yeah, a separate issue would be better.

**Pull request merged**
