### PR TITLE
Correct error message in Standard American english and add a test cas…

### PR DESCRIPTION
**Pull request by prakashlaxkar**
…e for the same.

### CODE REVIEW

**Comment by senny** [comment]
I moved the test-case to the other test-cases related to `.preload` (https://github.com/rails/rails/commit/57498e6f5753ac1d092e1623bed4ee0fdac50480).

Thank you.

**Comment by fxn** [comment]
:+1: on the spelling, could someone else check if the test should go to some existing file?

**Comment by senny** [comment]
@fxn I moved the test.

**Comment by fxn** [comment]
Saw it :).

**Pull request merged**
