### PR TITLE
Fix exception raised from template should not show compiled code

### LINKED ISSUE #51090: Exceptions raised from templates should show template code not compiled methods
Seems like we've regressed on exceptions raised from within ERB templates. They're showing the backtrace of the compiled method instead of the underlying template. That's not very helpful.

CleanShot 2024-02-14 at 08 36 52@2x

### PR DESCRIPTION
**Pull request by nikhilbhatt**
### Motivation / Background

Fixes #51090 

This Pull Request has been created to fix exceptions raised from template shows the compiled code.

### Detail

This Pull Request changes `activesupport/lib/active_support/core_ext/erb/util.rb`

### Additional information
1. In this tokenize method we are not handling the text present after `%>` 
2. Updated that method to handle text present at end.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by nikhilbhatt** [comment]
cc: @rafaelfranca

**Comment by nikhilbhatt** [comment]
@byroot could you review this?

**Comment by zzak** [comment]
Reminder: https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#get-some-feedback

**Comment by byroot** [comment]
I'm not super familiair with this code, but the test does repro an error and the patch does fix it so that's good for me. I just rebased it and made a minor change to avoid compiling a regexp every time.

**Pull request merged**
