### PR TITLE
Pass options to the test runner for test:{all,system,generators}

### LINKED ISSUE #41976: `rails test:system` and `rails test:all` don't support `rails test` arguments like verbose or seed
### Steps to reproduce

Run `rails test:system` with options like `rails test:system -v`, `rails test:system --seed=1234` or `rails test:system -p`.

### Expected behavior

Command should handle the arguments like `rails test` does, to be able to run system tests with a given seed or with a verbose output for debugging.

### Actual behavior

- Some arguments are ignored (like `-v`)
- Some arguments produce an `OptionParser::MissingArgument` exception (like `-p`)
- Some arguments just shows an `invalid option` error (like `--seed=1234`)
- Some arguments respond with an incorrect output (like `-h`, display the `rails` command help instead)

My current workaround is to do `rails test -v -p test/system/` or `rails test -v --seed=1234 test/` (to mimic `test:all`)

#### Some research

I understand that the problem is here https://github.com/rails/rails/blob/main/railties/lib/rails/commands/rake/rake_command.rb#L19

Args are handled as arguments for the `rails` command instead of arguments for the task (that's why -h displays the rails help and --seed shows an invalid option and -p expect the value).

Another issue is that the rake task is not sending the arguments to the rake_run command here https://github.com/rails/rails/blob/f95c0b7e96eb36bc3efc0c5beffbb9e84ea664e4/railties/lib/rails/test_unit/testing.rake#L57

Changing it to:

```ruby
Rails::TestUnit::Runner.rake_run(["test/system", *ARGV])
```
makes `rails test:system -v` work.

I assume that makes all the arguments work if only the code would reach that point (with `-p` or `--seed` it fails before this call at `rake_command.rb#19`).

I'd be happy to make a PR if somebody can point me in the right direction. I understand that the problem is how to get `rake_command.rb#19` to use the args for the rake task and not for the rails command.

### System configuration
**Rails version**:
Latest commit in the main branch. But can be reproduced with other versions (tried with 6.0.1 too).

**Ruby version**:
Ruby 2.7.2 right now, but happens with any Ruby version (tried with 2.6.6 too)

### PR DESCRIPTION
**Pull request by etiennebarrie**
### Summary

In #44106 I forgot to pass the options for all the commands, only those based on folders, so `test:system`, `test:all` and `test:generators` don't accept options like `--verbose`.

Fixes #41976

### Other Information

~~The error message is also not great, I'll take a look and see if I can fix it as part of this.~~ 

Actually taking and passing the arguments fixes the error message, minitest handles it.

### CODE REVIEW

**Comment by eileencodes** [comment]
I was going to ask to you to add a test for this and then realized this is entirely untested 🤦🏼‍♀️ Do you want to try to take a stab at adding a test file for these?

**Comment by etiennebarrie** [comment]
I was able to find a test file testing all of this.

**Comment by skipkayhil** [comment]
It looks like the metaprogrammed methods implicitly pass on the arguments and now these are doing it explicitly, would it be worth being consistent about it either way? (`(*)` vs `(*args)`)

**Comment by etiennebarrie** [comment]
Oh great point, thanks. I used the same approach of modifying `args` on the command object.

I took some time to figure out why we're not looking at the actual arguments passed to the method, and instead using the ones saved on the instance. It comes from the [initial implementation of commands using Thor](https://github.com/rails/rails/commit/6813edc7d926965e5644cd8befaf229a35b9d8ca). Thor classes can have arguments at the class level (it's used for generators for example), and the arguments passed to the method are stripped of those: https://github.com/rails/thor/blob/v1.2.1/lib/thor.rb#L390-L392

We don't have arguments on the test command, so we could use directly the arguments passed to the method, so maybe we should do that, it would be simpler. But at this stage `perform` ignores its arguments and just uses `args` on the object, so I'll continue to do that.

**Pull request merged**
