### PR TITLE
Ensure that AR::Relation#exists? allows only permitted params

### PR DESCRIPTION
**Pull request by bogdanvlviv**
Clarify changelog entry
Related to #34891

### CODE REVIEW

**Comment by rafaelfranca** [comment]
The PR was open for 7 days, why didn't you comment on it?

**Comment by bogdanvlviv** [comment]
Well, It is not possible to see all the changes before they are merged. Usually, I try not to skip significant changes even if they are merged. But sometimes, when I have time, I [do code review](https://github.com/rails/rails/pull/34794) as well. Is something wrong with this PR?

**Comment by rafaelfranca** [comment]
No. The changes itself are fine, it is just that a lot of your PRs are follow-up of other changes and sometimes it looks like you are cleaning after us and that may cause a bad feeling in the original contributor. Even if you find something that needs to be improved after the PR is merged I'd still comment on the PR and give the original author the chance of making the contribution itself. Of course this would means you are making more commits, but I think your contributions are in a level where it would not be hard to you to find some other contribution to make.

**Comment by bogdanvlviv** [comment]
@rafaelfranca I'll try to follow this approach next time.

**Pull request merged**
