### PR TITLE
Array#any? is slower and not the inverse of Array#empty?

### PR DESCRIPTION
**Pull request by byroot**
```
empty_array = []
small_array = [1] * 30
bigger_array = [1] * 300

Benchmark.ips do |x|
  x.report('empty !empty?') { !empty_array.empty? }
  x.report('small !empty?') { !small_array.empty? }
  x.report('bigger !empty?') { !bigger_array.empty? }

  x.report('empty any?') { empty_array.any? }
  x.report('small any?') { small_array.any? }
  x.report('bigger any?') { bigger_array.any? }
end
```

```
Calculating -------------------------------------
       empty !empty?   132.059k i/100ms
       small !empty?   133.974k i/100ms
      bigger !empty?   133.848k i/100ms
          empty any?   106.924k i/100ms
          small any?    85.525k i/100ms
         bigger any?    86.663k i/100ms
-------------------------------------------------
       empty !empty?      8.522M (± 7.9%) i/s -     42.391M
       small !empty?      8.501M (± 8.5%) i/s -     42.202M
      bigger !empty?      8.434M (± 8.6%) i/s -     41.894M
          empty any?      4.161M (± 8.3%) i/s -     20.743M
          small any?      2.654M (± 5.2%) i/s -     13.256M
         bigger any?      2.642M (± 6.4%) i/s -     13.173M
```

Ref: https://github.com/rails/rails/pull/21057#discussion_r35902468

@schneems for review please.

### CODE REVIEW

**Comment by byroot** [comment]
I did a quick grep over the codebase, and it seems there is quite a lot of occurrences of `.any?` without a block passed.

Some of them might be legit, and most of them not in actual hotspots, but I wonder if you'd be interested in a PR to convert them.

**Comment by rafaelfranca** [comment]
If they are not in hotspots there is no reason to change them, but if they are please send a PR.

**Comment by schneems** [comment]
I agree, with @rafaelfranca. The `!empty?` is not as nice to work with, and should only be used for performance sensitive areas. 

If you wanted to tackle this, take a look at my methodology on the last PR. You could get hotpots with some metaprogramming

```

class Array
  def any?(&block)
  end
end

**Comment by cmaitchison** [comment]
`!empty?` differs to `any?` when the array contains only `nil` objects

```
irb(main):001:0> [nil].any?
=> false
irb(main):002:0> [nil].empty?
=> false
```

Swapping these two lines in Ruby itself should bring the performance of `empty any?` in line with `empty !empty?` without side-effect - https://github.com/ruby/ruby/blob/95c84eac49064986bfd877ccf4d7e91e9929e833/array.c#L5524-L5526

**Comment by rafaelfranca** [comment]
@cmaitchison seems you found a good patch for ruby/ruby. :shipit:

**Comment by cmaitchison** [comment]
@rafaelfranca Yeah, there are a few more marginal gains to be had in even just that file. Just familiarising myself with the contribution process now... seems relatively heavyweight :P

**Comment by schneems** [comment]
I actually tried already, when I compiled it helps but it's still slower. It looks like `empty? ` gets a further optimization here: https://github.com/ruby/ruby/blob/95c84eac49064986bfd877ccf4d7e91e9929e833/insns.def#L1964-L2000 (maybe?)

@cmaitchison let me know if you have questions with compiling or contributing. I don't know much, but happy to share what I do know.

**Comment by byroot** [comment]
Even if theoretically `.any?` should be as fast as `!empty?` on empty arrays, it will always be slower on non empty array since it must ensure at least one value of the array is truthy.

`any?` is intended to be the "inverse" of `all?` not of `empty?`.

**Pull request merged**
