### PR TITLE
[WIP] Fix Ruby 2.4 #to_time incompatibility rough design

### PR DESCRIPTION
**Pull request by yui-knk**
ref: https://github.com/rails/rails/issues/24617

### CODE REVIEW

**Comment by yui-knk** [comment]
Points of this PR are

* For Ruby 2.3 compatibility, changes to utc and then `getlocal`. `Time#getlocal` uses system tz.
* For Ruby 2.4 compatibility, emulates Ruby 2.4 behavior with Ruby codes.

**Comment by jeremy** [comment]
Thank you @yui-knk.

We could add some global configuration like `ActiveSupport.to_time_preserves_timezone = false` by default, then have new apps and upgrading apps opt in to `true`.

**Comment by pixeltrix** [comment]
Closing because it was fixed in c9c5788a527b70d7f983e2b4b47e3afd863d9f48.

@yui-knk sorry about not using your PR - it was just too different from what I needed it to be. Thanks for looking at it though.

**Comment by yui-knk** [comment]
No problem, Thanks 😄

**Pull request closed without merging**
