### PR TITLE
Bump minitest to 5.25.1 and clean up hacks.

### PR DESCRIPTION
**Pull request by zenspider**

### CODE REVIEW

**Comment by tenderlove** [comment]
@zenspider I think we're calling a method internal to minitest here. AFAICT, it was to [support minitest-hooks](https://github.com/rails/rails/commit/758ba117a008b6ea2d3b92c53b6a7a8d7ccbca69).

I'd rather we're not calling an internal method, but clearly if we remove this call it will break `minitest-hooks`.

Is there a path forward where we can either remove this method call, or call a public / supported method so that you're free to change internals?

cc @jeremyevans

**Comment by jeremyevans** [comment]
The `with_info_handler` method in question is public, but nodoc. I would definitely like to switch to a supported approach, as I mentioned in https://github.com/minitest/minitest/issues/1007#issuecomment-2289997101.   The supported approach needs to provide a way to not run expensive after/before/around all code for Minitest::Test subclasses that have all test methods filtered out.

**Comment by tenderlove** [comment]
I'm just spitballing, but would something like this work for you @jeremyevans ?  https://github.com/minitest/minitest/pull/1011

**Comment by tenderlove** [comment]
I _think_ the draft PR I sent means we could delete this call in Rails (but I'm not 100% sure yet)

**Comment by tenderlove** [comment]
Just something I've been thinking about: this "minitest-hooks support code" was added for the case where Rails is doing parallel testing. Parallel tests are run in sub processes and the subprocesses are fed via a queue. Meaning any particular test class could possibly have its methods run in multiple child processes.

Presumably people using minitest-hooks want these hooks to run for each class in each of their respective processes (IOW if `FooTest` is run in two processes, it should have its minitest-hooks executed once in each of these processes).  I think that's why the original patch called [`klass.with_info_handler` *for every test method*](https://github.com/rails/rails/commit/758ba117a008b6ea2d3b92c53b6a7a8d7ccbca69) even though upstream Minitest would have called the class level `with_info_handler` only once.

The `run_all_methods` PR I proposed doesn't really handle the case we want to solve for in Rails. We'd still need to ensure that a class run in two different processes would trigger the `minitest-hooks` code in each of those processes and `run_all_methods` assumes all test methods are known in advance (as it wants the test names in an array vs popping from a queue).

I'm really not sure how to solve this problem for real. It seems like Rails should keep track of the classes it has seen in each process, then trigger lifecycle hooks on the class the first time it sees it.  Since minitest doesn't really have the concept of class level life cycle hooks I'm not sure where that leaves us (as not all Rails uses are also `minitest-hooks` users). 🥲

Maybe Rails should monkey patch minitest with no-op class level lifecycle hooks then `minitest-hooks` can integrate there?  idk

**Comment by jeremyevans** [comment]
In minitest-parallel_fork, I handle this by not splitting suites.  Each of the worker processes processes suites, not individual test methods.  This behavior is less granular, so there are cases where it does not parallelize as well.  Whether it parallelizes better or worse depends on the amount of work done in the class level lifecycle hooks, the number of test methods per suite, the total number of test methods, and number of parallel workers.  In my experience, as long as the application has a sufficient number of suites, the parallelization still works OK (not near optimal as it currently does not use feedback from previous runs to estimate completion time of suites).

Ideally, minitest itself would support class-level lifecycle hooks and there would be no need for minitest-hooks, but my understanding is there are philosophical objections to doing that.

I am against having minitest-hooks depend on Rails.  However, I expect if you added such hooks to Rails, a rails-minitest-hooks or similar library would pop up to integrate minitest-hooks and Rails.

If you think there are benefits to having class-level hooks, you may want to consider having Rails depend on minitest-hooks, handling the integration inside Rails, and making those benefits available to all Rails users by default.

**Comment by tenderlove** [comment]
We could probably make the work queuing system understand whether a test class has a "per class" hook and basically downgrade that specific class to not get parallelization. Unfortunately, that would mean that Rails needs to know about per class hooks.

If minitest won't support per-class hooks, I guess we'd probably have to add it as a feature in Rails, or depend on `minitest-hooks` (or just call `with_info_handler` in perpetuity I guess).

I'll merge this PR for now, but I'd really like to see a better solution.

**Pull request merged**
