### PR TITLE
Move `require "models/post"` before `require "models/comment"`

### PR DESCRIPTION
**Pull request by yahonda**
### Summary

This pull request addresses #26368.

Here are two minimum test cases:
- Testcase 1 "test/cases/relation/where_test.rb" "test/cases/base_test.rb"

``` ruby
for i in sqlite3 mysql2 postgresql
do
ARCONN=$i bundle exec ruby -w -I"lib:test" -I"/home/yahonda/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib" "/home/yahonda/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/rake_test_loader.rb" \
"test/cases/relation/where_test.rb" "test/cases/base_test.rb"
done
```

``` ruby
Using sqlite3
Run options: --seed 42128

# Running:

.............................................................................................................................................F............................S................

Finished in 1.433237s, 130.4739 runs/s, 286.0657 assertions/s.

  1) Failure:
BasicsTest#test_readonly_attributes [/home/yahonda/git/rails/activerecord/test/cases/base_test.rb:642]:
--- expected
+++ actual
@@ -1 +1 @@
-#<Set: {"title", "comments_count"}>
+#<Set: {"title"}>


187 runs, 410 assertions, 1 failures, 0 errors, 1 skips

You have skipped tests. Run with --verbose for details.
Using mysql2
Run options: --seed 2204

# Running:

.......................................................................................................................F...........................................S........................

Finished in 2.111748s, 89.0258 runs/s, 194.6255 assertions/s.

  1) Failure:
BasicsTest#test_readonly_attributes [/home/yahonda/git/rails/activerecord/test/cases/base_test.rb:642]:
--- expected
+++ actual
@@ -1 +1 @@
-#<Set: {"title", "comments_count"}>
+#<Set: {"title"}>


188 runs, 411 assertions, 1 failures, 0 errors, 1 skips

You have skipped tests. Run with --verbose for details.
Using postgresql
Run options: --seed 20170

# Running:

.......................................................F..................................................................................................................................

Finished in 2.641518s, 70.4141 runs/s, 156.7281 assertions/s.

  1) Failure:
BasicsTest#test_readonly_attributes [/home/yahonda/git/rails/activerecord/test/cases/base_test.rb:642]:
--- expected
+++ actual
@@ -1 +1 @@
-#<Set: {"title", "comments_count"}>
+#<Set: {"title"}>


186 runs, 414 assertions, 1 failures, 0 errors, 0 skips
$
```
- Testcase 2 "test/cases/autosave_association_test.rb" and "test/cases/base_test.rb"

``` ruby
for i in sqlite3 mysql2 postgresql
do
ARCONN=$i bundle exec ruby -w -I"lib:test" -I"/home/yahonda/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib" "/home/yahonda/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/rake_test_loader.rb" "test/cases/autosave_association_test.rb" "t
est/cases/base_test.rb"
done
```

``` ruby
Using sqlite3
Run options: --seed 20992

# Running:

..........................................................................................................................................................................................S................F................................................................................................................

Finished in 4.864530s, 64.9600 runs/s, 165.8947 assertions/s.

  1) Failure:
BasicsTest#test_readonly_attributes [/home/yahonda/git/rails/activerecord/test/cases/base_test.rb:642]:
--- expected
+++ actual
@@ -1 +1 @@
-#<Set: {"title", "comments_count"}>
+#<Set: {"title"}>


316 runs, 807 assertions, 1 failures, 0 errors, 1 skips

You have skipped tests. Run with --verbose for details.
Using mysql2
Run options: --seed 48388

# Running:

...................................................................................................................................................................................................S.........................................F...............................................................................

Finished in 7.794468s, 40.6699 runs/s, 103.6633 assertions/s.

  1) Failure:
BasicsTest#test_readonly_attributes [/home/yahonda/git/rails/activerecord/test/cases/base_test.rb:642]:
--- expected
+++ actual
@@ -1 +1 @@
-#<Set: {"title", "comments_count"}>
+#<Set: {"title"}>


317 runs, 808 assertions, 1 failures, 0 errors, 1 skips

You have skipped tests. Run with --verbose for details.
Using postgresql
Run options: --seed 53624

# Running:

.........................................................................................................................................................................................................................................F.................................................................................

Finished in 8.795197s, 35.8150 runs/s, 92.2094 assertions/s.

  1) Failure:
BasicsTest#test_readonly_attributes [/home/yahonda/git/rails/activerecord/test/cases/base_test.rb:642]:
--- expected
+++ actual
@@ -1 +1 @@
-#<Set: {"title", "comments_count"}>
+#<Set: {"title"}>


315 runs, 811 assertions, 1 failures, 0 errors, 0 skips
$
```
### Other Information

It reproduces only when both of these conditions are satisfied:
- Other test files `autosave_association_test.rb` or `where_test.rb`
  which executes `require "models/comment"` then `require "models/post"`
- When `autosave_association_test.rb` or `where_test.rb` executed before `base_test.rb`

### CODE REVIEW

**Comment by prathamesh-sonpatki** [comment]
@yahonda Did you figure out why changing the order of model fixes the problem?

**Comment by yahonda** [comment]
@prathamesh-sonpatki Actually I do not know why. Just got to know how to address them based on your suggestions. Let me take some more look at this.

**Comment by vipulnsward** [comment]
Some history.
https://github.com/vipulnsward/rails/commit/a841cd2503e26d4af908b2ff49592973eabcac46
https://rails.lighthouseapp.com/projects/8994/tickets/2550-fix-models-load-order-in-activerecords-tests

The fix is 👍

**Comment by pixeltrix** [comment]
@yahonda thanks! 👍

**Pull request merged**
