### PR TITLE
Call methods with .method_name not ::method_name

### PR DESCRIPTION
**Pull request by utilum**
Found several instances.

Follow up on 63d530c5e68a8cf53603744789f53ccbc7ac1a0e

### CODE REVIEW

**Review by sikachu — COMMENTED** [review]
Hmm ... I don't think we accept a PR which change just a code style. I think we can change those if we work on something around it eventually.

However, I'll let @rafaelfranca make the call.

r? @rafaelfranca

**Comment by sikachu** [comment]
Our policy is here: https://github.com/rails/rails/blob/master/CONTRIBUTING.md#did-you-fix-whitespace-format-code-or-make-a-purely-cosmetic-patch

**Comment by utilum** [comment]
I'm sorry, I did not mean to generate noise and pollute the git history, just stumbled upon 63d530c and ran a `grep`.

**Comment by pixeltrix** [comment]
@utilum @sikachu whilst generally I agree with not merging style changes I think this one is fine as the files are low impact in terms of git history.

**Comment by sikachu** [comment]
Ah, that's fine with me. I wasn't really concern with git history littering anything at all, only concerned if this fell into cosmetic change or not. I'm also not the one who make the call, just a suggester. 😅

**Comment by pixeltrix** [comment]
Well, since we have rubocop installed now I guess we're over the rubicon when it comes to cosmetic changes - added a cop to prevent future violations in 9c0c90979a759a41628e0cd9d73821b0b34d03fc 👮

**Pull request merged**
