### PR TITLE
Checked in changes to Gemfile.lock on latest master

### PR DESCRIPTION
**Pull request by prathamesh-sonpatki**
- Eventmachine version gets updated when `bundle` is run locally.

r? @rafaelfranca

### CODE REVIEW

**Comment by prathamesh-sonpatki** [comment]
Looks like this version also fixes few issues related to installing EM on windows https://github.com/eventmachine/eventmachine/blob/master/CHANGELOG.md#109-january-13-2016 & https://github.com/eventmachine/eventmachine/blob/master/CHANGELOG.md#1091-january-14-2016

**Comment by spastorino** [comment]
That's not the output of a simple bundle run. I guess you refer to bundle update eventmachine.
Anyway ... merging ...

**Comment by prathamesh-sonpatki** [comment]
@spastorino nope, I just did bundle install.

Also verified by removing `eventmachine` completly and then `bundle install` in rails repo, but got same result.

I think it's happening because https://github.com/prathamesh-sonpatki/rails/blob/master/Gemfile.lock#L145

**Comment by spastorino** [comment]
yep, you're right. I had eventmachine installed so it wasn't updating.

**Comment by prathamesh-sonpatki** [comment]
I can confirm that it started happening after our latest change related to removing dependency on celluloid - https://github.com/rails/rails/commit/01c320001bcce617196270f3d398d48a89a6ea2a

**Pull request merged**
