### PR TITLE
Add backticks to `ActiveRecord::Base.where`

### PR DESCRIPTION
**Pull request by maclover7**
[ci skip]

I'm going to open backport PRs to move this to `5-0-0` and `5-0-stable` as well.

---

EDIT: The 5.0 release notes are a bit out of date on `5-0-stable`, I'm assuming that needs a PR to be updated, and then this change can be backported. 😬

### CODE REVIEW

**Comment by vipulnsward** [comment]
@maclover7 tag the PR's that need to be backported as 5-0 release, @rafaelfranca will do the backport.

**Comment by maclover7** [comment]
👍

**Comment by vipulnsward** [comment]
Looks good.

**Pull request merged**
