### PR TITLE
[WIP] ActiveStorage: Add remote_url option

### PR DESCRIPTION
**Pull request by MatthiasRMS**
### Allow uploads from remote urls

By passing a url through the remote_url option, it is possible to attach a remote file. 
Feedback would be greatly appreciated. 

I have 2 questions:
- should I make a dedicated class for remote files ? (will be useful to extend it in the future) 
- where should I define error classes ? I at least need a DownloadError class.

### CODE REVIEW

**Comment by lunks** [comment]
It'd be better if we did it using ActiveJob if present, otherwise we're blocking the current thread, or at least make an option available to do so.

**Comment by MatthiasRMS** [comment]
@lunks thanks for the feedback. Shouldn't this be an ActiveStorage option instead of an option for this particular feature ? 
Uploading a regular file (e.g not from a remote url) is also blocking the current thread, so I guess it'd be more useful to offer this as a standard option for any ActiveStorage upload.

**Comment by georgeclaghorn** [comment]
Thanks for the PR, but we’re going to pass on this feature for now. It’s not terribly difficult to download a file for storage as needed, and I’d prefer to avoid muddying Active Storage’s API.

**Comment by marckohlbrugge** [comment]
It's been 2.5 years since the decision was made to pass on the feature. I'm curious if it's worth reconsideration?

It seems like a popular request leading to quite a few duplicate issues of people asking about it. There's also a growing list of blog posts explaining different ways to do this. Personally I'm not sure what the most secure and efficient approach is. An official, built-in method would be appreciated.

Additionally, I think a [Shrine-like implementation](https://github.com/shrinerb/shrine/blob/master/lib/shrine/plugins/remote_url.rb) where one can set a `remote_image_url` attribute (where `image` is the attachment name) is non-trivial to implement yourself.

Related posts around the web:

- https://github.com/rails/rails/pull/31947
- https://blog.eq8.eu/til/upload-remote-file-from-url-with-activestorage-rails.html
- https://www.reddit.com/r/rails/comments/8ezozi/active_storage_attachment_download_from_a_url/
- https://stackoverflow.com/questions/51027995/how-to-save-an-image-from-a-url-with-rails-active-storage
- https://stackoverflow.com/questions/51095202/how-store-an-image-from-url-with-active-storage

**Pull request closed without merging**
