### PR TITLE
Cache: warning if `expires_in` is given an incorrect value

### PR DESCRIPTION
**Pull request by ghiculescu**
In Rails 7, if you do `Rails.cache.write(key, value, expires_in: 1.minute.from_now)`, it will work. The actual expiration will be much more than a minute away, but it won't raise. (The correct code is `expires_in: 1.minute` or `expires_at: 1.minute.from_now`.)

Since https://github.com/rails/rails/pull/45892 the same code will error with:

```
NoMethodError: undefined method `negative?' for 2008-04-24 00:01:00 -0600:Time
    /Users/alex/Code/rails/activesupport/lib/active_support/cache.rb:743:in `merged_options'
    /Users/alex/Code/rails/activesupport/lib/active_support/cache.rb:551:in `write'
```

To make it a bit easier to upgrade to Rails 7.1, this PR introduces a better warning if you pass a `Time` object to `expires_in:`

```
ArgumentError: expires_in parameter should not be a Time. Did you mean to use expires_at? Got: 2023-04-07 14:47:45 -0600
    /Users/alex/Code/rails/activesupport/lib/active_support/cache.rb:765:in `handle_invalid_expires_in'
    /Users/alex/Code/rails/activesupport/lib/active_support/cache.rb:745:in `merged_options'
    /Users/alex/Code/rails/activesupport/lib/active_support/cache.rb:551:in `write'
```

cc @trevorturk @byroot

### CODE REVIEW

**Comment by byroot** [comment]
I'm not sure we really need a feature flag for this given that it was obviously a bug. I think we can raise straight away.

**Comment by byroot** [comment]
In other word, I'm open to the clearer error, but no so much about making it a warning.

**Comment by trevorturk** [comment]
Nice catch. Thank you for the detailed explanation and PR. I'm sorry you ran into this issue, but I'm glad to see the new config option is operating (mostly) as intended by helping uncover sneaky bugs in existing apps!

I don't have a strong opinion on it, but I like the the PR as-is. I think it's in keeping with the spirit of #45892, where we introduce logging by default for existing apps to avoid "breaking" people's apps if they haven't opted-into the more strict config option.

**Comment by ghiculescu** [comment]
> where we introduce logging by default for existing apps to avoid "breaking" people's apps if they haven't opted-into the more strict config option.

Yeah, this is what I was thinking too. Previous versions of Rails didn't raise with this code, so I don't think Rails 7.1 should either, unless you enable the configuration telling it to.

@byroot happy to change it if you disagree.

**Comment by byroot** [comment]
> Previous versions of Rails didn't raise with this code, so I don't think Rails 7.1 should either

Yes, but they were bugged either way. The thing we do with new configs and new default is for sunsetting deprecated features, this wasn't a feature, we can directly raise.

**Comment by ghiculescu** [comment]
Okay, I updated the PR to always raise.

**Pull request merged**
