### PR TITLE
[ActiveStorage] Add ability to use pre-defined variants

### PR DESCRIPTION
**Pull request by fatkodima**
[Related discussion](https://discuss.rubyonrails.org/t/activestorage-pre-defined-variants/73378)

```ruby
 class User < ActiveRecord::Base
   has_one_attached :avatar do |attachable|
     attachable.variant :thumb, resize: "100x100"
     attachable.variant :medium, resize: "300x300", monochrome: true
   end
 end

 class Gallery < ActiveRecord::Base
   has_many_attached :photos do |attachable|
     attachable.variant :thumb, resize: "100x100"
     attachable.variant :medium, resize: "300x300", monochrome: true
   end
 end

 <%= image_tag user.avatar.variant(:thumb) %>
 ```

### CODE REVIEW

**Comment by kaspth** [comment]
Let's yield an actual object (yes, no `instance_eval` either) that you can call variant on:

```ruby
class User < ActiveRecord::Base
  has_one_attached :avatar do |blob|
    blob.variant  :thumb, resize: "100x100"
    blob.variant :medium, resize: "300x300", monochrome: true
  end
end

class Gallery < ActiveRecord::Base
  has_many_attached :photos do |blob|
    blob.variant  :thumb, resize: "100x100"
    blob.variant :medium, resize: "300x300", monochrome: true
  end
end
```

Note: there's a potential reading of this API version that makes it look like we're eagerly computing the variants, so whatever ideas you'd have to clarify that are welcome. (Perhaps renaming the yielded variable to `attachable` in docs would do it?)

**Comment by fatkodima** [comment]
@kaspth Updated using the block syntax.

**Comment by sedubois** [comment]
I’d be interested in such a feature.

**Comment by fatkodima** [comment]
@georgeclaghorn @kaspth 
Any chance to get this into the next release?

**Comment by mshibuya** [comment]
I definitely need this feature, would be great if this can be a part of the next release.

**Comment by guillaumebriday** [comment]
Hey guys, That would be awesome to see this feature merged!

How could we help @fatkodima @rafaelfranca?

🙏

**Comment by kaspth** [comment]
@fatkodima nice job! Sorry for the delay on my end 🙏

**Comment by yfxie** [comment]
@fatkodima Thanks for your contribution. I referred to this PR and created a gem supporting Rails 6 projects to have this nice feature.
https://github.com/yfxie/active_storage_variantt

**Comment by SylarRuby** [comment]
Am i missing something? Im getting `ArgumentError (unknown keyword: :variants)`

**Comment by fatkodima** [comment]
@SylarRuby PR description is outdated. Look at the code changes and changelog.

**Comment by jmarsh24** [comment]
> Am i missing something? Im getting `ArgumentError (unknown keyword: :variants)`

I'm also experiencing this error.

**Comment by dwightwatson** [comment]
@jmarsh24 like above, look at the PR code and the changelog to see how to use variants.

I wonder if there's any hope of using these with attachment previews too.

**Pull request merged**
