### PR TITLE
fix #23779 fixing to use raw post data correctly on test_case

### LINKED ISSUE #23779: Test case use RAW_POST_DATA but it is not used anywhere
Hello guys,

Using rspec-rails on my project, I noticed a strange behavior, 

When I make a post sending a hash object like:

`{id: 1}`

the number 1 will be converted to String.

It doesnt happens with Minitest only on RSpec.

please consider this script:

[https://gist.github.com/leonardoprg/d667920604659294b42f](https://gist.github.com/leonardoprg/d667920604659294b42f)

If you guys take a look on the line 50, when using .to_json and sending a string as parameter to post method, it will works correctly.

Swimming in the code I noted that:

1. The problem is at `actionpack/lib/test_case.rb`
2. RSpec use the method post at [test_case.rb#L519](https://github.com/rails/rails/blob/4-2-stable/actionpack/lib/action_controller/test_case.rb#L519)

3. minitest doesn't use it.

The problem here is 
[test_case.rb#L598](https://github.com/rails/rails/blob/4-2-stable/actionpack/lib/action_controller/test_case.rb#L598
)

If RSpec try to send a string, it assume it will be a raw data (like an json object)  and set it to request env `RAW_POST_DATA`, Which is correctly.
but, the code that take care with this env var, is a middleware at:
[params_parser.rb#L42](https://github.com/rails/rails/blob/4-2-stable/actionpack/lib/action_dispatch/middleware/params_parser.rb#L42)

and it is never called, because the method on test_case just call the controller method as an plain object.

I will open a PR to correct this behaviour.

Regards,

### PR DESCRIPTION
**Pull request by leonardoprg**
This PR, is releated to
#23779

Regards,

### CODE REVIEW

**Comment by leonardoprg** [comment]
@rafaelfranca  
@eileencodes 

Opened PR to master,

Guys, one question,

[here](https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/test_case.rb#L462)

it's new on Rails 5, so my question is, 
this fix will only work when `kwarg_request?(args)` return true, otherwise, `format` var will be nil,

is it right?

I mean, the other way we will ignore if the user send something like that:

`post :create, {id: 1}, format: :json`

ps: example that works

`post :create, body: {id: 1}.to_json, format: :son`

Regards,

**Comment by eileencodes** [comment]
Did you happen to find where this change was introduced? I think this might have been intentional because the browser will never send a `1` but will always send a `"1"`. I believe this is the commit that changed https://github.com/rails/rails/commit/394b7be this behavior

**Comment by leonardoprg** [comment]
@eileencodes 
Not sure, 

but you can see my explanation [here](https://github.com/rails/rails/issues/23779)

Yeah, I know the browser will never send Integer, but when send through json, it need to send as Intenger (if I wanna).

Please follow the link and let me know if have you any question.

Thanks :)

**Comment by leonardoprg** [comment]
@eileencodes 

Also, just to clarify, but the problem (as related on the issue), is

```
If RSpec try to send a string,  it will be set a raw data (like an json object) and set it to request env RAW_POST_DATA, Which is correctly.
but, the code that take care with this env var, is a middleware at:
params_parser.rb#L42

and it is never called, because the method on test_case just call the controller method as an plain object.
```

**Comment by meinac** [comment]
Did you try to set mime type of your request's payload as `application/json`? If you don't set it as json then expecting from Rails to parse "strings which look like integers" as integer does not make sense. Because Rails can't know what did sender intended while sending it if the content type is `application/x-www-form-urlencoded`.
Basically If you try to make a POST request like
```ruby
post '/', { id: 1 }.to_json, 'CONTENT_TYPE' => 'application/json'
```
Then you can see that id is parsed as integer.

**Comment by leonardoprg** [comment]
@meinac 
Yes, I tried,

it works well with Minitest, 
but with Rspec if you send a String on the body (like a json), it ignore all body, and params will be blank.

It happens why 

***
The problem is at actionpack/lib/test_case.rb
RSpec use the method post at test_case.rb#L519

minitest doesn't use it.

The problem here is 
test_case.rb#L598

If RSpec try to send a string, it assume it will be a raw data (like an json object) and set it to request env RAW_POST_DATA, Which is correctly.
but, the code that take care with this env var, is a middleware at:
params_parser.rb#L42

***


More details [here](https://github.com/rails/rails/issues/23779)


Regards

**Comment by meinac** [comment]
Its really interesting. The documentation says:

> The HTTP parameters. This may be +nil+, a hash, or a string that is appropriately encoded (+application/x-www-form-urlencoded+or +multipart/form-data+)

What I understand from here is, you can use this method to test only if you are getting interaction with `urlencoded` and `multipart` payloads. But if I send a post request with `:format` parameter like:
```ruby
post :foo, { int_place_holder: 1, format: :json }
```
then it works even if `Content-Type` is `nil`! I've looked around the `RSpec` issues and saw that there are plenty issues points this problem and all responses are just workarounds which tries to hack this API. I've also looked at my old applications and saw that I had used `format: :json` way many times :scream:

At this point I'm paying more attention to warning inside of the doc which says:

> Note that the request method is not verified. The different methods are available to make the tests more expressive.

After considering this note I've made a quick research and found that there is a module which name is `ActionDispatch::Integration`. As its name suggest, it is a module for integration testing. You can try it from your Rails console!

```ruby
application = Rails.application
session     = ActionDispatch::Integration::Session.new(application)

params  = { foo: 1, bar: true, zoo: nil }.to_json
headers = { 'Content-Type' => 'application/json' }
uri     = 'http://localhost:3000/path'

session.post(uri, params, headers) # Will do what we need! Inside of the controller, params will return { "foo" => 1, "bar" => true, "zoo" => nil, ... }
```

As you see `ActionDispatch::Integration` API works as expected and `ActionController::TestCase` API is not designed for what we want to do.
IMHO the problem with this API is only lack of documentation.

**Comment by diego-silva** [comment]
@meinac not sure I followed what you just said. Are you suggesting we use the `ActionDispatch::Integration` inside our controller tests? This seems a little weird to me, since it's not an 'Integration' test...

And if so, why would the [`actionpack/lib/action_controller/test_case.rb`](https://github.com/rails/rails/blob/98ed722039f19639b014a9d9d229e0da2926946f/actionpack/lib/action_controller/test_case.rb#L478-L480) set the `RAW_POST_DATA` header if it's not used anywhere during the test? (it's only consume by a middleware that does not get called during controller tests)

**Comment by eileencodes** [comment]
We soft-deprecated (just removed documentation) `ActionController::TestCase` in Rails 5. Going forward new controller tests should be written using `ActionDispatch::Integration`. See https://github.com/rails/rails/issues/22496 for more details.

**Comment by meinac** [comment]
> Are you suggesting we use the ActionDispatch::Integration inside our controller tests? This seems a little weird to me, since it's not an 'Integration' test

@diego-silva IMO if you are expecting exact same results with real world cases then you have to make integrations tests. And also I point that this API is not for what we want to do as documentation says.

**Comment by leonardoprg** [comment]
OK, once it will be removed in rails 5, may I reopen my older PR about that
to rails 4.2?
Em 20/02/2016 14:08, "Mehmet Emin İNAÇ" <notifications@github.com> escreveu:

**Pull request closed without merging**
