### PR TITLE
Fix rubocop offence Layout/CommentIndentation [ci skip]

### PR DESCRIPTION
**Pull request by yhirano55**
### Summary

Fixed LayoutCommentIndentation in ActiveStorage

### CODE REVIEW

**Comment by y-yagi** [comment]
Duplicate of #30210

**Comment by yhirano55** [comment]
@y-yagi Oh..., Is it better to close this request?

**Comment by y-yagi** [comment]
I think so ;)

**Comment by yhirano55** [comment]
@y-yagi thanks

**Pull request closed without merging**
