### PR TITLE
Better Client Side Debugging for Javascript Server Responses

### PR DESCRIPTION
**Pull request by aantix**
## Better Client Side Debugging for Javascript Server Responses

Better Output
### Current Behavior

When a javascript server response is eval'ed by jQuery, if the generated javascript contains an error, the eval fails silently.

_Here's an obvious error in the .js template_:
Obvious Error

_And the response fails silently_:
Silent Failure

This lack of error reporting is confusing when debugging javascript responses and isn't very productive for the developer.
### Improved Behavior

Now when there's a javascript error, the user is not only notified of the exception that occurred, but is also shown the corresponding .js template for where the error occurred (and if the error is in .js partial, the user will be shown that as well).

_Obvious error in js template_:
Error in Template

_Error reported for the javascript request_:
Error reported by browser

_Obvious error in js partial source (rendered from create.js.erb)_:
Error in Partial

_Error reported for the javascript request_:
Error reported by browser

The problematic line of code is also displayed.

Displaying the problematic template/partial along coupled with the browsers stacktrace goes a long way to quickly diagnosing problematic server side javascript.  

This debugging functionality can be toggled via the debug_js flag.  I have enabled it for development.

Tested w/ Chrome and Safari

### CODE REVIEW

**Comment by rafaelfranca** [comment]
I like the concept but I don't use server side JS responses too much to judge this feature. @dhh @jeremy WDYT?

**Comment by simi** [comment]
@aantix Is there any chance to move javascript into separated js file?

**Comment by aantix** [comment]
@simi For the separation of logic and data, dynamically apply the partial/template source meta data (source_info, partial_infos) to the body attribute and then have the js_debug.js read from that attribute?  

js_debug.js would then have to be included on every development request, regardless of whether the page contains any ajax logic.

The inline approach that I've developed probably reads better (since the data is generated inline relative to the logic) but results in a heavier javascript payload per .js request. 

Thoughts?

**Comment by glaucocustodio** [comment]
Merge please, it's very useful :smile_cat:

**Comment by sgrif** [comment]
@dhh @jeremy Ping! Any thoughts on this feature?

@aantix This seems like it could easily start its life as a gem, rather than in Rails core itself. How do you feel about trying it out in that context, first? It would certainly help to work out any issues that might crop up with other browsers, and see how big of a problem this is in the wild.

**Comment by jeremy** [comment]
This is a pretty common issue. Check out the comments @ http://www.alfajango.com/blog/rails-js-erb-remote-response-not-executing/

I dig the concept, but the implementation is invasive. It requires partial template tracking and embedding a bunch of source info within every response, possibly at great perf cost. A simpler try/catch would be a good start.

Our RJS support used to provide this with `config.action_view.debug_rjs = true`. It was deprecated in Rails 3.1, [extracted to prototype-rails](https://github.com/rails/prototype-rails/blob/1d715b7e7db96f71e22afea7fdc0cf81cd931480/lib/action_view/helpers/prototype_helper.rb#L238-L242). It'd definitely be generally useful for any server-side javascript responses. Maybe possible to implement as a dev .js layout, even.

**Comment by aantix** [comment]
As @jeremy pointed out, the debugging of JS responses is definitely an issue and one of the many reasons I've seen junior devs shy away from the approach.  @sgrif I'm constrained for time, so I'd rather this make it into Rails core or nothing at all.

The stack trace info is the biggest source where browser differences could come into play.  Are there any formal Rails guidelines as to which browsers would have to be supported in a development context?

**Comment by dhh** [comment]
Jim, if it works in latest Chrome, Safari, Firefox, that's fine.

**Comment by carlosramireziii** [comment]
Hey all! I'm following up on this feature...

I created a gem called `better_sjr` which wraps any server-generated JS templates in a simple try-catch block when the `BetterSJR.debug_sjr` config option is enabled. 

https://github.com/carlosramireziii/better_sjr

Any caught exceptions will simply print the error message to the console, like so

Example error in console

As per @sgrif, I think we'll be better served by having this functionality live in a separate gem at first.

Debugging SJR can totally be a pain and probably causes a lot of developers (especially newbies) to shy away from the technique. In addition to the try-catch, I'm hoping to also add warnings for unescaped JavaScript, which is another common GOTCHA with SJR. 

Thanks to @aantix for getting the ball rolling on this. 

Should we close this PR in favor of the gem (for now)?

**Pull request closed without merging**
