### PR TITLE
Dynamically show available sql types [ci skip]

### PR DESCRIPTION
**Pull request by meinac**
Dynamically list available sql data types based on current database adapter.
While I was working on another issue I've noticed that there are some missing data types `bigint`, `numeric` and `timestamp`. This datatypes are available in abstract adapter so they are available for sqlite3, mysql2 and postgresql adapters. After adding this types into the list I thought that in case if I use postgresql as database adapter the help message wont show all available postgresql datatypes like `money`, `inet` etc. It would be great to see all available data types for current adapter in help message and I've prepared this pr for this purpose.

### CODE REVIEW

**Comment by arthurnn** [comment]
thanks

**Comment by rafaelfranca** [comment]
Travis seems to agree https://travis-ci.org/rails/rails/jobs/171518037#L1849

**Comment by arthurnn** [comment]
Didn't think about that.. great catch @rafaelfranca

**Comment by kaspth** [comment]
Also ci shouldn't be skipped when introducing code or touching a template 😉

**Pull request merged**
