### PR TITLE
Add missing time zone definitions for Russian Federation

### PR DESCRIPTION
**Pull request by Envek**
Today I've noticed that Rails' time zone mapping is missing next russian time zones completely:
- UTC+02 Kaliningrad
- UTC+04 Samara
- UTC+11 Srednekolymsk

Also I noticed that currently mapping points Volgograd to `Europe/Moscow` but in `zones.tab` from current tzdata (2014j) there is explicit `Europe/Volgograd` timezone exists. Changed it.

And last thing: I added mapping for all russian timezones from tzdata (such that Simferopol, Novokuznetsk, and Chita), but all of them duplicates main timezones (Moscow, Novosibirsk, and Irkutsk respectively), and these entries in `zones.tab` looks actual. Please tell me should I include such entries in this PR or not.

For more info see file `zones.tab` from [tzdata](http://www.iana.org/time-zones), rows 329 to 349 and [Wikipedia article about time in Russia](http://en.wikipedia.org/wiki/Time_in_Russia). Please note that there were two large time zone changes in last years in Russia.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
cc @pixeltrix

**Comment by pixeltrix** [comment]
@Envek the mappings list is not meant to be an exhaustive list but I'm happy for the correction to Volgograd to be merged. The list is for broad worldwide audience but if you need all possible timezones I suggest rolling your own UX because present a massive drop drown isn't a great experience.

**Comment by Envek** [comment]
OK, removed entries that duplicated existing ones with same UTC offset. 

But I think entries for Kaliningrad, Samara and Srednekolymsk should be added as there is currently no russian time zones with that offsets are present in mapping.

So, with this PR merged, list of russian time zones will be as follows:
```
(GMT+02:00) Kaliningrad (NEW)
(GMT+03:00) Moscow
(GMT+03:00) St. Petersburg
(GMT+03:00) Volgograd (CHANGED)
(GMT+04:00) Samara (NEW)
(GMT+05:00) Ekaterinburg
(GMT+06:00) Novosibirsk
(GMT+07:00) Krasnoyarsk
(GMT+08:00) Irkutsk
(GMT+09:00) Yakutsk
(GMT+10:00) Magadan
(GMT+10:00) Vladivostok
(GMT+11:00) Srednekolymsk (NEW)
(GMT+12:00) Kamchatka
```

For better UX I already created initializer like that: https://gist.github.com/Envek/cda8a367764dc2cacbc0

**Comment by pixeltrix** [comment]
Okay, I can understand that - thanks for the PR :+1:

**Comment by Envek** [comment]
Thanks for review! Can it be also backported to 4.2?

**Comment by pixeltrix** [comment]
Backported to 4.2 (12a40a8) and 4.1 (b25efc0)

**Pull request merged**
