### PR TITLE
Fix association with scope including joins

### LINKED ISSUE #28324: Cannot Eager Load has_many :through Relationships Defined by a Scope With Joins
### Steps to reproduce

```rb
# Stolen from @adamlogic on #26780
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "http://rubygems.org"
  gem "activerecord"#, "5.0.0"
  gem "sqlite3"
  gem "pry"
end

require "pry"
require "active_record"
require "minitest/autorun"
require "logger"

Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :deals, force: true do |t|
  end

  create_table :deal_areas, force: true do |t|
    t.integer :deal_id
    t.integer :area_id
  end

  create_table :areas, force: true do |t|
    t.boolean :deleted
    t.integer :owner_id
  end

  create_table :owners, force: true do |t|
    t.boolean :admin
  end
end

class Deal < ActiveRecord::Base
  has_many :deal_areas
  has_many :failing_areas, -> { with_admin }, through: :deal_areas, class_name: "Area", source: :area
  has_many :working_areas, -> { not_deleted }, through: :deal_areas, class_name: "Area", source: :area
end

class DealArea < ActiveRecord::Base
  belongs_to :deal
  belongs_to :area
end

class Owner < ActiveRecord::Base
  has_many :areas
end

class Area < ActiveRecord::Base
  belongs_to :owner

  scope :with_admin, -> { joins(:owner).where(owner: { admin: true }) }
  scope :not_deleted, -> { where(deleted: false) }
end

class BugTest < Minitest::Test
  def setup
    owner = Owner.create!(admin: true)
    @deal = Deal.create!
    @deal.failing_areas.create!(owner: owner)
  end

  def teardown
    @deal.destroy
  end

  def test_through_with_scope_no_joins
    assert_equal [@deal.id], Deal.includes(:working_areas).references(:working_areas).map(&:id)
  end

  def test_through_with_scope_with_joins
    assert_equal [@deal.id], Deal.includes(:failing_areas).references(:failing_areas).map(&:id)
  end
end
```
### Expected behavior

The failing areas relationship should be eager loaded

### Actual behavior

An SQL error is raised because the join in the scope is not included in the query.
This is a variant of the bug fixed by 91e3dab804fffe0b1daebb438091418faa1fa256.

### System configuration
**ActiveRecord version**:  5.0.2

**Ruby version**: 2.3.0p0

### PR DESCRIPTION
**Pull request by kamipo**
Fixes #28324.

### CODE REVIEW

**Comment by dnl** [comment]
I was going to set up a new issue then found this, so I have some extra test cases:

```
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  # gem "rails", github: "rails/rails"
  gem "rails", github: "kamipo/rails", branch: "fix_association_with_scope_including_joins"
  gem "arel", github: "rails/arel"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
    t.integer :author_id
  end

  create_table :likes, force: true do |t|
    t.integer :comment_id
    t.integer :author_id
  end

  create_table :authors, force: true do |t|
    t.boolean :verified
  end
end

class Post < ActiveRecord::Base
  has_many :comments
  has_many :likes, through: :comments
  has_many :likes_workaround, -> { joins(:author) }, through: :comments, source: :likes, class_name: 'Like'
  # `has_many :likes, -> { joins(:author) }, through: :comments` is all that would be necessary if I didn't rename it
end

class Comment < ActiveRecord::Base
  belongs_to :post
  has_many :likes, -> { verified }
end

class Like < ActiveRecord::Base
  belongs_to :comment
  belongs_to :author
  scope :verified, -> { joins(:author).where(authors: { verified: true }) }
end

class Author < ActiveRecord::Base
  has_many :likes
end

class BugTest < Minitest::Test
  def setup
    @post = Post.create!
    @comment = Comment.create!(post: @post)
    @author = Author.create!(verified: true)
    @like = Like.create!(author: @author, comment: @comment)
    @post_relation = Post.where(id: @post.id)
  end

  def test_stuff_that_should_work
    assert_equal 1, @post.comments.count
    assert_equal 1, @comment.likes.count
    # breaking out `includes` into `preload` and `eager_load` because they work differently, a.k.a: "includes sometimes works."
    assert_equal [@post], @post_relation.preload(:likes).to_a # works because it's a separate query
    assert_equal 1, @post.likes_workaround.count # works because we repeated the join in the has_many through
    assert_equal 1, @post.likes.joins(:author).count # works because we repeated the join here.
  end

  def test_has_many_through_eager_load_the_join_scope_too
    # passes in master, fails on your branch
    assert_equal [@post], @post_relation.eager_load(likes: :author).to_a
  end

  def test_has_many_through_count_with_a_join_scope
    # fails in your branch & master
    assert_equal 1, @post.likes.count # the authors joins in the scope gets lost.
  end

  def test_has_many_through_eager_load_with_a_join_scope
    # passes in your branch, fails in master
    assert_equal [@post], @post_relation.eager_load(:likes).to_a # the authors joins in the scope gets lost
  end

  def test_has_many_through_eager_load_with_a_repeated_join_scope
    # passes in your branch, fails in master
    assert_equal [@post], @post_relation.eager_load(:likes_workaround).to_a # even the repeated join in the has_many through is forgotten
  end
end
```

**Comment by dnl** [comment]
These all look like the same issue: 
https://github.com/rails/rails/issues/28703
https://github.com/rails/rails/issues/28440
https://github.com/rails/rails/issues/26780
https://github.com/rails/rails/issues/22538
https://github.com/rails/rails/issues/14110

**Comment by rafaelfranca** [comment]
Could rebase this and add a CHANGELOG entry?

**Comment by kamipo** [comment]
@dnl Thank you for your testing. I investigated the failures.

About `test_has_many_through_eager_load_the_join_scope_too`. The test will only pass for sqlite3 adapter because SQLite3 don't care JOIN tables order. It seems that most adapters doesn't pass the test even if master branch (at least mysql2 and postgresql adapters failed). The failure on this PR is due to join scope includes the same table with main relation and constructing join scope doesn't care the join table list in main relation. It is hard to fix for now.

About `test_has_many_through_count_with_a_join_scope`. In this PR, `Post.preload(:likes).first.likes.to_a` and `Post.eager_load(:likes).first.likes.to_a` will work, but `Post.first.likes.to_a` doesn't work. It seems an issue on `AssociationScope`. I'll fix the issue at first. After that, I'll revisit this PR.

**Comment by kamipo** [comment]
Rebased and added a CHANGELOG entry.

**Comment by joelvh** [comment]
@rafaelfranca will this be released in 5.1.x or wait for 5.2.0?

**Pull request merged**
