### PR TITLE
[ci skip] Fix block parameter of assert_no_difference

### PR DESCRIPTION
**Pull request by s3ymd**

### CODE REVIEW

**Comment by meinac** [comment]
Thank you for improving rails. Please use [ci skip] in your commit message to skip build of travis for new pull requests.
http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#contributing-to-the-rails-documentation

**Comment by spastorino** [comment]
Please squash this into just one commit. Thanks.

**Comment by s3ymd** [comment]
Could you please help me? 
I want to squash my old commit as you taught me.
First I used `git log'. It shows:

--
commit 0948c2b3da1ac584bebdefa679e3abcd895c26c5
Merge: ad22de6 f6a90bc
Author: Hiromichi Yamada <h-yamada@3sss.co.jp>
Date:   Wed May 27 21:49:28 2015 +0900

    Merge branch 'master' of https://github.com/s3ymd/rails

commit ad22de6febb8ef91653ceb75ea4df296f262c43d
Author: Hiromichi Yamada <h-yamada@3sss.co.jp>
Date:   Wed May 27 21:09:06 2015 +0900

    [ci skip] Fix block parameter of assert_no_difference

commit f6a90bc7fff72d4c5b6245fd034ab77111f0a4c4
Author: Hiromichi Yamada <h-yamada@3sss.co.jp>
Date:   Wed May 27 21:09:06 2015 +0900

    Fix block parameter of assert_no_difference

commit 852460852cf1635af3f2861847253e8b5677acc0
Merge: 8887449 4194d05
Author: Yves Senn <yves.senn@gmail.com>
Date:   Wed May 27 09:14:19 2015 +0200

    Merge pull request #20262 from arunagw/aa-remove-broken-unused-release-task

    Remove broken and unused release task
--

Next, I used rebase command.

$ git rebase -i HEAD~2

This shows these lines in vi editor.

--
pick ad22de6 [ci skip] Fix block parameter of assert_no_difference
pick f6a90bc Fix block parameter of assert_no_difference
--

So, I updated line without [ci skip] to squash it.

--
pick ad22de6 [ci skip] Fix block parameter of assert_no_difference
squash f6a90bc Fix block parameter of assert_no_difference
--

After saved it, Git shows next lines:

--
# This is a combination of 2 commits.
# The first commit's message is:

[ci skip] Fix block parameter of assert_no_difference

# This is the 2nd commit message:

Fix block parameter of assert_no_difference

# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
--

So I commented out old commit messages.

--
# This is a combination of 2 commits.
# The first commit's message is:

[ci skip] Fix block parameter of assert_no_difference

# This is the 2nd commit message:

# Fix block parameter of assert_no_difference

# Please enter the commit message for your changes. Lines starting
--

And save it, quit editor. To confirm them, I use `git log' again.

--
commit 2c64dc0533e738ed9074b358c4447be4fe391886
Author: Hiromichi Yamada <h-yamada@3sss.co.jp>
Date:   Wed May 27 21:09:06 2015 +0900

    [ci skip] Fix block parameter of assert_no_difference

commit 852460852cf1635af3f2861847253e8b5677acc0
Merge: 8887449 4194d05
Author: Yves Senn <yves.senn@gmail.com>
Date:   Wed May 27 09:14:19 2015 +0200

    Merge pull request #20262 from arunagw/aa-remove-broken-unused-release-task

    Remove broken and unused release task
--

It seems correctly squashed, so I want to push it.

--
$ git push
To https://github.com/s3ymd/rails.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/s3ymd/rails.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
--

It seems to use `git pull', so I type it, then editor starts and shows
these lines:

--
Merge branch 'master' of https://github.com/s3ymd/rails

# Please enter a commit message to explain why this merge is necessary,
# especially if it merges an updated upstream into a topic branch.
#
# Lines starting with '#' will be ignored, and an empty message aborts
# the commit.
--

After I just saved it and exit the editor, I use `git log' again. It shows:

--
commit 421bdae6a4d1f5df43ae175f8e2f21322bd61a92
Merge: 2c64dc0 0948c2b
Author: Hiromichi Yamada <h-yamada@3sss.co.jp>
Date:   Thu May 28 00:07:35 2015 +0900

    Merge branch 'master' of https://github.com/s3ymd/rails

commit 2c64dc0533e738ed9074b358c4447be4fe391886
Author: Hiromichi Yamada <h-yamada@3sss.co.jp>
Date:   Wed May 27 21:09:06 2015 +0900

    [ci skip] Fix block parameter of assert_no_difference

commit 0948c2b3da1ac584bebdefa679e3abcd895c26c5
Merge: ad22de6 f6a90bc
Author: Hiromichi Yamada <h-yamada@3sss.co.jp>
Date:   Wed May 27 21:49:28 2015 +0900

    Merge branch 'master' of https://github.com/s3ymd/rails

commit ad22de6febb8ef91653ceb75ea4df296f262c43d
Author: Hiromichi Yamada <h-yamada@3sss.co.jp>
Date:   Wed May 27 21:09:06 2015 +0900

    [ci skip] Fix block parameter of assert_no_difference

commit f6a90bc7fff72d4c5b6245fd034ab77111f0a4c4
Author: Hiromichi Yamada <h-yamada@3sss.co.jp>
Date:   Wed May 27 21:09:06 2015 +0900

    Fix block parameter of assert_no_difference

commit 852460852cf1635af3f2861847253e8b5677acc0
Merge: 8887449 4194d05
Author: Yves Senn <yves.senn@gmail.com>
Date:   Wed May 27 09:14:19 2015 +0200

    Merge pull request #20262 from arunagw/aa-remove-broken-unused-release-task

    Remove broken and unused release task
--

Is this ok to do `git push' ?  Thanks.

**Comment by s3ymd** [comment]
Or should I just recreate a new pull request that contains [ci skip] in the commit message?

**Comment by spastorino** [comment]
Your local master branch should map exactly the rails/rails master branch and then you should cherry-pick your commit on top.
One horrible but quick way to fix it is
`git reset --hard <sha_of_one_master_commit_before_the_mess>; git pull origin master; git cherry-pick ad22de6febb8ef91653ceb75ea4df296f262c43d; git push -f <your_remote> master`

When you do git push -f the PR will automatically fix the issue.

If something like this doesn't work close the PR and open a new one.

**Comment by s3ymd** [comment]
@spastorino and @meinac, Thank you very much for your advice !!!

**Comment by arthurnn** [comment]
thanks @s3ymd for the patch.
and thanks @spastorino and @meinac for helping him too.

**Comment by s3ymd** [comment]
Thank you too, @arthurnn!

**Pull request merged**
