### PR TITLE
Remove sass-rails in favour of sassc-rails

### PR DESCRIPTION
**Pull request by rheasunshine**
### Summary

The `sass-rails` 6.0 release moved the rails sass implementation to `sassc-rails`, and is now only a wrapper around it. This was done to make transition to Rails 6 easier. No further development will be done on `sass-rails` and the recommended dependency for new rails apps is `sassc-rails`. 
This PR changes the default for rails generators to be the recommended `sassc-rails` rather than the wrapper `sass-rails`.

### CODE REVIEW

**Comment by kaspth** [comment]
Hey, thanks for working on this! This is an area that's in a bit of an upheaval at the moment, see for instance https://discuss.rubyonrails.org/t/transition-to-the-sass-npm-gem/76566

My current understanding is that we'd like to keep sass-rails and make that a wrapper around dart-sass instead of switching to sassc-rails. @rafaelfranca is that aim for now?

**Comment by rafaelfranca** [comment]
> My current understanding is that we'd like to keep sass-rails and make that a wrapper around dart-sass instead of switching to sassc-rails. @rafaelfranca is that aim for now?

Yes. I think it doesn't make sense for us to rename gems so many times if we have control over it because the underlaying implementation changed.

**Comment by rheasunshine** [comment]
@guilleiguaran @rafaelfranca @kaspth Thanks for the link. I will close this PR and follow the discussion.

**Comment by kaspth** [comment]
@rheasunshine sounds good, and you're welcome to contribute anything else of course 😄🙏

**Pull request closed without merging**
