### PR TITLE
ActiveSupport::Deprecation fallback to singleton disallowed_behavior

### PR DESCRIPTION
**Pull request by grncdr**
### Summary

This addresses the issue described in https://github.com/rails/rails/issues/44553 by causing custom ActiveSupport::Deprecation instances to fall back to the `disallowed_behavior` of the global singleton instance if they don't have their own explicitly configured `disallowed_behavior`.

I feel like this approach gives developers the least-surprising results: any global configuration of deprecation behavior behavior will automatically be respected, but can still be explicitly overridden on a per-deprecator basis (and there are tests for that).

### CODE REVIEW

**Comment by grncdr** [comment]
Test failure appears to be unrelated:

```


W, [2022-03-26T18:44:48.868951 #22]  WARN -- : memcached:11211 failed (count: 0) Timeout::Error: execution expired
--


rails test rails/activesupport/test/cache/behaviors/cache_store_behavior.rb:416
```

**Comment by ghiculescu** [comment]
Could you add a note to the changelog for this?

**Comment by grncdr** [comment]
@ghiculescu sorry for taking so long to get around to this. I've rebased and added an entry to the changelog.

**Review by jonathanhefner — COMMENTED** [review]
I agree the behavior is wonky.  Essentially, library code is expected to create new `ActiveSupport::Deprecation` instances to specify a `gem_name` and `deprecation_horizon`, *but* application code is expected to configure the behavior of those instances.

The same concern also applies to [`debug`](https://github.com/rails/rails/blob/d66441f39127c284c2fc7ac9bfe3e8270b115033/activesupport/lib/active_support/deprecation/behaviors.rb#L63).  Incidentally, the default behaviors *only* support `ActiveSupport::Deprecation.debug`, *not* `ActiveSupport::Deprecation#debug`, due to the scope of the `debug` reference [here, for example](https://github.com/rails/rails/blob/d66441f39127c284c2fc7ac9bfe3e8270b115033/activesupport/lib/active_support/deprecation/behaviors.rb#L22).

And the same concern applies to [`silenced`](https://github.com/rails/rails/blob/d66441f39127c284c2fc7ac9bfe3e8270b115033/activesupport/lib/active_support/deprecation/reporting.rb#L9).  Incidentally, [`ActiveSupport::Deprecation.silence` blocks](https://github.com/rails/rails/blob/d66441f39127c284c2fc7ac9bfe3e8270b115033/activesupport/lib/active_support/deprecation/reporting.rb#L33-L38) do not currently affect other `ActiveSupport::Deprecation` instances.  For example, the warning in the following code would not be silenced:

```ruby
ActiveSupport::Deprecation.silence do
  # several layers...
    # deep into the...
      # call stack...
        deprecation_instance_for_some_library.warn(...)
end
```

From an API standpoint, that difference might be more understandable because `deprecation_instance_for_some_library` has its own `silence(&block)` method?  Still, it likely does not match the user's expectation.

And likewise with [`ActiveSupport::Deprecation.allow` blocks](https://github.com/rails/rails/blob/d66441f39127c284c2fc7ac9bfe3e8270b115033/activesupport/lib/active_support/deprecation/reporting.rb#L60-L70)...

I feel like most of these methods and attributes would be better implemented directly on the `ActiveSupport::Deprecation` class, but we would need to go through a deprecation cycle for the instance methods, or at least for the instance attribute setters.  And we would need to change the [way we delegate methods](https://github.com/rails/rails/blob/d66441f39127c284c2fc7ac9bfe3e8270b115033/activesupport/lib/active_support/deprecation/instance_delegator.rb#L15-L22).

Towards a more class-oriented approach, I've pushed a commit (725a4972cfdac85f0cd5bdf1e05e78d76b7c7be9) that changes the relevant attributes to fall back to `self.class.*`.  And, where we would normally set defaults for the class attributes, I've [set default values on the singleton instance](https://github.com/rails/rails/pull/44772/files#diff-2bfc6058d43af77dca7dbdd80a1e0cba368f7019ae493e615f9f5a70805738b7R35-R42) instead.  That prevents infinite recursion in the getters, while avoiding having to check `self == Deprecation.instance`.  Though things got a little finicky with the [`ThreadLocalVar` attributes](https://github.com/rails/rails/pull/44772/files#diff-2bfc6058d43af77dca7dbdd80a1e0cba368f7019ae493e615f9f5a70805738b7R57-R58).

I still need to add more tests, but first I want to verify whether we should go this direction (or just deprecate the instance methods altogether).

**Comment by grncdr** [comment]
> I feel like most of these methods and attributes would be better implemented directly on the `ActiveSupport::Deprecation` class...

Definitely agree

> but we would need to go through a deprecation cycle for the instance methods, or at least for the instance attribute setters.

Sure, I also don't think it hurts much.

> And we would need to change the [way we delegate methods](https://github.com/rails/rails/blob/d66441f39127c284c2fc7ac9bfe3e8270b115033/activesupport/lib/active_support/deprecation/instance_delegator.rb#L15-L22).

IMO the API is not so large that it requires this level of meta-programming, an explicit `delegate ..., to: :singleton` would be totally adequate.

> Towards a more class-oriented approach, I've pushed a commit ([725a497](https://github.com/rails/rails/commit/725a4972cfdac85f0cd5bdf1e05e78d76b7c7be9)) that changes the relevant attributes to fall back to `self.class.*`. And, where we would normally set defaults for the class attributes, I've [set default values on the singleton instance](https://github.com/rails/rails/pull/44772/files#diff-2bfc6058d43af77dca7dbdd80a1e0cba368f7019ae493e615f9f5a70805738b7R35-R42) instead.

Looks good to me

> I still need to add more tests, but first I want to verify whether we should go this direction (or just deprecate the instance methods altogether).

AFAICT there isn't really a clear owner for this bit of ActiveSupport. The original author appears to have moved on, Rafael Franca has responded to the few issues, but I believe Shopify uses their own deprecation framework. I think these changes are good, but that doesn't count for much. 😆

**Comment by rafaelfranca** [comment]
In my opinion I don't think we should push this behavior to the class level. To me we should get rid of the singleton and just push the deprecation instance we today use in the singleton to the sub-framework railties. As a library author I'd not way the silencing of the deprecations of the Rails framework to also silence the deprecations of my library.

We should push to a direction where libraries can register deprecation instances to the Rails application, and the Rails application can silence, or allow deprecations of all libraries, or just a few.

Pushing this to class methods goes against that, and just create more confusion.

About owner of the code. All the core team members are owner of the entire framework.

**Comment by grncdr** [comment]
> To me we should get rid of the singleton and just push the deprecation instance we today use in the singleton to the sub-framework's railties.

100% agree, and I really like the proposed API. The intent with my [original commit](https://github.com/rails/rails/pull/44772/commits/e743ee649296441604b4d64292fa127fb40c502b) was to make a somewhat precise change to the specific edge cases I discovered in #44553 and not modify the public API surface.

Now we seem to have crossed that particular Rubicon anyways, I'm happy to take a stab at implementing the API you've outlined above.

> About owner of the code. All the core team members are owner of the entire framework.

Understood, my previous comment is better stated as: I know this isn't the most high-profile framework in Rails, so I don't expect it to get the same attention as a similar issue in e.g. ActiveRecord. I greatly appreciate the time and thought you put into your responses here (and _everywhere_).

**Comment by rafaelfranca** [comment]
> so I don't expect it to get the same attention as a similar issue in e.g. ActiveRecord.

I actually love this part of the framework, so I'm happy to give it some attention. I was just MIA for a few months and didn't have time to pay attention to Rails.

**Comment by skipkayhil** [comment]
@jonathanhefner #46049 addresses this, right?

**Comment by jonathanhefner** [comment]
@skipkayhil Yes, there is still some follow-up work to be done (which I will get to soon), but I think this can be closed.

Thank you, @grncdr! :pray:

**Pull request closed without merging**
