### PR TITLE
Add test case for interpolation with passing of data along with record

### PR DESCRIPTION
**Pull request by vipulnsward**
Follow-up of https://github.com/rails/rails/pull/24119

r? @rafaelfranca

### CODE REVIEW

**Comment by vipulnsward** [comment]
@rafaelfranca @prathamesh-sonpatki https://github.com/rails/rails/pull/24119 is kind of a breaking change, before that we returned "activemodel.errors.models.topic.attributes.title.blank" as first key in this example (as documented here- https://github.com/rails/rails/pull/22427/ it's newly documented though), and now we return object.

**Comment by prathamesh-sonpatki** [comment]
That's true. Because here - https://github.com/svenfuchs/i18n/blob/aee7b3f6072fba3f54798a280bd6007536b039cd/lib/i18n/backend/base.rb#L120-L121

We check for presence of object in options first and if not we pass the key (activemodel.errors.models.topic.attributes.title.blank) passed from Rails to the proc.

After #24119, the options[:object] will always be not null so key won't be passed to proc. 

Can a key be used in the proc?  The example in https://github.com/rails/rails/pull/22427 didn't use it.

**Comment by rafaelfranca** [comment]
Urgh. Lets change the example added in #22427 to match this new API and add a CHANGELOG entry about it.

**Comment by prathamesh-sonpatki** [comment]
Ok. Will take care of it.

**Pull request merged**
