### PR TITLE
Fix ActiveJob Test adapter not respecting retry attempts:

### LINKED ISSUE #38391: ActiveJob TestHelper retries jobs indefinitely, doesn't call #deserialize on jobs
👋 I noticed this issue when testing against a job with custom deserialization logic. I'm happy to work on a PR to fix it if that would be helpful.

### Steps to reproduce

_Note: This test demonstrates jobs getting run indefinitely, so this test will not exit on its own._
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
 source "https://rubygems.org"

 git_source(:github) { |repo| "https://github.com/#{repo}.git" }

 gem "rails", github: "rails/rails"
end

require "active_job"
require "minitest/autorun"

class BuggyJob < ActiveJob::Base
  retry_on(Exception,  attempts: 2)

  def perform
    raise "error"
  end
end

class BuggyJobTest < ActiveJob::TestCase
  def test_job_infinitely_loops
    BuggyJob.perform_later
    perform_enqueued_jobs
  end
end
```
### Expected behavior
Retry-able jobs that raise an exception in test should be retried normally – their retry limits should be respected and the test should stop running the job when the job hits its retry attempts limit.

Additionally, jobs that override the `deserialize` method should have that method exercised in the test environment.

### Actual behavior
The retry limit is not respected, jobs are retried indefinitely. This appears to be due to jobs not going through a serialization round-trip, which results in both endless retries and custom deserialization logic not being exercised in tests.

This bug is specific to running `perform_enqueued_jobs` _after_ jobs have already been enqueued and it attempts to flush the queue. The test behavior works as expected if `perform_later` is called using the block syntax:

```ruby
perform_enqueued_jobs { BuggyJob.perform_later }
```
### System configuration
**Rails version**: master

**Ruby version**: `ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin18]`

### PR DESCRIPTION
**Pull request by Edouard-chin**
Fix ActiveJob Test adapter not respecting retry attempts:

- ### Problem

  Given the below example the test adapter will retry the job
  indefinitely:

  ```ruby
    class BuggyJob < ActiveJob::Base
      retry_on(Exception,  attempts: 2)

      def perform
        raise "error"
      end
    end

    BuggyJob.perform_later
    perform_enqueued_jobs
  ```

  The problem is that when the job get retried, the
  `exception_executions` variable is not serialized/deserialized,
  resulting in ActiveJob to not be able to determine how many time
  this job was retried.

  The solution in this PR is to deserialize the whole job in the test
  adapter, and reserialize it before retrying.

  Fix #38391

### CODE REVIEW

**Comment by eileencodes** [comment]
Backported to 6-0-stable

**Comment by Edouard-chin** [comment]
Thanks ! ❤️

**Comment by Gasparila** [comment]
This appears to be a breaking change:
tiny example:
```rb
it "sample test" do
  MyJob.perform_later
  perform_enqueued_jobs
end
```
6.0.2.2: works
6.0.3.1: fails with 
```
     NoMethodError:
       undefined method `constantize' for nil:NilClass
     # /Users/kevinmiller/.rvm/gems/ruby-2.6.2/gems/activejob-6.0.3.1/lib/active_job/core.rb:51:in `deserialize'
     # /Users/kevinmiller/.rvm/gems/ruby-2.6.2/gems/activejob-6.0.3.1/lib/active_job/test_helper.rb:686:in `instantiate_job'
```

Since `job_class` does not exist

**Comment by rafaelfranca** [comment]
If you are having an issue can you reproduce the problem in a script like this and open an issue https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_job_gem.rb?

**Pull request merged**
