### PR TITLE
Added an example to show how common secrets can be shared

### PR DESCRIPTION
**Pull request by prathamesh-sonpatki**
Reverts rails/rails#22008

### CODE REVIEW

**Comment by prathamesh-sonpatki** [comment]
That failure was different :smile:. I will fix the build.

**Comment by sgrif** [comment]
I think this example should be in the guides rather than in `secrets.yml` directly.

**Comment by rafaelfranca** [comment]
:+1: to not add tho the `secrets.yml` file. Also it is a YAML file, is not obvious what that comment is showing?

**Comment by prathamesh-sonpatki** [comment]
Okey. Thanks for the feedback.

**Pull request closed without merging**
