### PR TITLE
WIP: Prototype using Rack upgrade.websocket

### PR DESCRIPTION
**Pull request by evanphx**
This is a prototype of native Rack websocket support. This is not available in any released webserver yet, I have opened this PR to serve as a discussion point for the Rails community about utilizing this potential new support.

Puma does have experimental support for this and is available at https://github.com/puma/puma/pull/1054.

I'd love to get the input from Rails devs on this as well as input on the API for this nascent upgrade.websocket support.

Thanks! 😘

### CODE REVIEW

**Comment by mperham** [comment]
Bro, just use Elixir. 😆

**Comment by evanphx** [comment]
@mperham 😹

**Comment by maclover7** [comment]
cc @tenderlove @matthewd

**Comment by boazsegev** [comment]
The [iodine server](https://github.com/boazsegev/iodine) (released as a gem) also provides support for the proposed `upgrade.websocket` specification... the API should be considered unstable, since the specification might change through community input.

**Comment by schneems** [comment]
What else might be needed here? Where did this end up Evan?

**Comment by boazsegev** [comment]
Wow, I totally forgot this one was still out there... I submitted a similar PR #33295 ...

Any chance we could get this reviewed?

**Comment by evanphx** [comment]
@schneems The upgrade.websocket API needs to be agreed upon before we could consider this again, I'd think.

**Pull request closed without merging**
