### PR TITLE
Updated the Rails gem version to rc2 in the bug report template

### PR DESCRIPTION
**Pull request by abhaynikam**
Similar to: https://github.com/rails/rails/commit/fb4268401575b5af3d5d2566fd37fc75f34bb93b

Since regression issues are raised I thought it would be better to update the bug report gem version.

### CODE REVIEW

**Comment by kamipo** [comment]
Related https://github.com/rails/rails/pull/32513#issuecomment-379988813.

**Comment by abhaynikam** [comment]
@kamipo : Is it valid to change `6.0.0.rc1` to `6.0.0` and remove `rc1` as per this comment https://github.com/rails/rails/pull/32513#issuecomment-380183797??

**Comment by kamipo** [comment]
Yeah, that is valid to me. Are you interested to open a PR?

**Comment by abhaynikam** [comment]
Yep. I'll open a PR for change.

**Pull request closed without merging**
