### PR TITLE
Add a configuration `explicit_select_column_names` for fixing `PreparedStatementCacheExpired` errors when adding new columns

### PR DESCRIPTION
**Pull request by Kevinrob**
### Summary

We have some ActiveRecord::PreparedStatementCacheExpired errors when adding new column in a migration.
After some research, we found [this article](https://flexport.engineering/avoiding-activerecord-preparedstatementcacheexpired-errors-4499a4f961cf) that explain in details why we get this.

The issue is that `SELECT *` will raise a `ActiveRecord::PreparedStatementCacheExpired` if a column is added. In a transaction, this error will stop and raise.
One solution is to generate explicit `SELECT ..., ..., ...`.

We do not want to use the `self.ignored_columns = [:__fake_column__]`-hack, we find it better to have a configuration for that.

### CODE REVIEW

**Comment by ghiculescu** [comment]
Can you add this to https://guides.rubyonrails.org/configuring.html ?

**Comment by Kevinrob** [comment]
> Can you add this to https://guides.rubyonrails.org/configuring.html ?

Yes! I added an entry to `guides/source/configuring.md`.

**Comment by ghiculescu** [comment]
Is this PR intentionally targeting `6-1-stable`? I think it should target `main`.

**Comment by ghiculescu** [comment]
Yes please - all new PRs should go to `main`, then if necessary (usually just for big bugs/security patches) they are backported to a `stable` branch.

**Comment by Kevinrob** [comment]
@ghiculescu When I started to cherry-pick my commits on `main` branch, I see that what I want to do is already done.
https://github.com/rails/rails/pull/41718

I will wait for the next release 😅

**Pull request closed without merging**
