### PR TITLE
adjust #:nodoc: style

### PR DESCRIPTION
**Pull request by takakuda**
### Summary

I adjust #:nodoc: style. in activerecord/lib/active_record/migration.rb file
I thought style id better to have a unified. so I change it.

### CODE REVIEW

**Comment by yahonda** [comment]
Looks like some of these corrections can be addressed by `Layout/SpaceBeforeComment` cop.

```diff
$ git diff
diff --git a/.rubocop.yml b/.rubocop.yml
index 54dcaf80f9..b4d4284555 100644
--- a/.rubocop.yml
+++ b/.rubocop.yml
@@ -116,6 +116,9 @@ Layout/SpaceAroundOperators:
 Layout/SpaceBeforeComma:
   Enabled: true

+Layout/SpaceBeforeComment:
+  Enabled: true
+
 Layout/SpaceBeforeFirstArg:
   Enabled: true
```


```ruby
$ bundle exec rubocop activerecord/lib/active_record/migration.rb
Inspecting 1 file
C

Offenses:

activerecord/lib/active_record/migration.rb:9:43: C: Layout/SpaceBeforeComment: Put a space before an end-of-line comment.
  class MigrationError < ActiveRecordError#:nodoc:
                                          ^^^^^^^^
activerecord/lib/active_record/migration.rb:90:56: C: Layout/SpaceBeforeComment: Put a space before an end-of-line comment.
  class DuplicateMigrationVersionError < MigrationError#:nodoc:
                                                       ^^^^^^^^
activerecord/lib/active_record/migration.rb:100:53: C: Layout/SpaceBeforeComment: Put a space before an end-of-line comment.
  class DuplicateMigrationNameError < MigrationError#:nodoc:
                                                    ^^^^^^^^
activerecord/lib/active_record/migration.rb:120:51: C: Layout/SpaceBeforeComment: Put a space before an end-of-line comment.
  class IllegalMigrationNameError < MigrationError#:nodoc:
                                                  ^^^^^^^^
activerecord/lib/active_record/migration.rb:130:47: C: Layout/SpaceBeforeComment: Put a space before an end-of-line comment.
  class PendingMigrationError < MigrationError#:nodoc:
                                              ^^^^^^^^

1 file inspected, 5 offenses detected
$
```

**Comment by rafaelfranca** [comment]
👍 for enabling the cop. @takakuda can you do that?

**Comment by takakuda** [comment]
@yahonda 
I don`t know `Layout/SpaceBeforeComment` cop …
thank you! I will add this cop!

**Comment by takakuda** [comment]
@rafaelfranca 
yes! I pushed!

**Pull request merged**
