### PR TITLE
Fix boolean casting for False

### PR DESCRIPTION
**Pull request by ionut998**
### Summary
Include `False` in the list of rules for coercion of user input.
Casting the string `false` or `FALSE` to boolean results in a `false` value but casting `False` to boolean results in `true`

Before:
```
ActiveRecord::Type::Boolean.new.cast("False")
=> true
```

After
```
ActiveRecord::Type::Boolean.new.cast("False")
=> false
```

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Thank you for the pull request but this is a huge change of behavior and we don't need to do it. Make sure the case of your string is consistent before passing to this method.

**Comment by ionut998** [comment]
I still think it would be useful to have this in the framework. I know that there is an easy way around it and I understand that not all the permutations of lower and uppercase should be taken care of but `False` (in this casing) is quite a common one.

**Comment by rodolfobandeira** [comment]
+1 in favour to accept this PR. The behaviour of the class is broken. I'd actually go with `value.downcase` which would fix all cases: ie: `falSE`

@rafaelfranca @ionut998

**Comment by rafaelfranca** [comment]
https://github.com/rails/rails/pull/40606#issuecomment-725702912

**Pull request closed without merging**
