### PR TITLE
Performance regression in CollectionAssocation#build

### PR DESCRIPTION
**Pull request by ghiculescu**
https://github.com/rails/rails/pull/40379 caused a big regression in one of our apps when upgrading to Rails 6.1. If you have an association with *lots* of records and you call `build` on it, the `build` method takes a long time because it has to iterate over every object on the `target` to check for duplicates.

This is necessary because of how `has_many_inversing` works, but could be implemented to run more quickly. I've attempted to do that in this PR, by keeping a separate cache of records that were added to the target through `has_many_inversing` and only searching for the matching record in that case.

Replication script for the bug, this fails against Rails 6.1 and `main`, passes against Rails 6, passes when run against this branch:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", "~> 6.1.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :authors, force: true do |t|
  end
  create_table :posts, force: true do |t|
    t.references :author
  end
end

class Author < ActiveRecord::Base
  has_many :posts
end

class Post < ActiveRecord::Base
  belongs_to :author
end

class BugTest < Minitest::Test
  def test_association_stuff
    author = Author.create!

    posts = 100_000.times.map { |n| { author_id: author.id } }
    Post.insert_all(posts)

    author = Author.find(author.id)
    author.posts.load_target

    5000.times do |n|
      time = Benchmark.ms { author.posts.build }
      assert time < 30, "iteration #{n}: #{time}" # takes about 200ms in Rails 6.1
    end
  end
end
```

### CODE REVIEW

**Comment by ghiculescu** [comment]
@gmcgibbon @dmitry could I get your  👀  on this please?

**Comment by rafaelfranca** [comment]
Looks good to me, but can you should some time with benchmark/ips just so we know how better it got?

**Comment by ghiculescu** [comment]
I couldn't work out how to run the changes side by side in the same benchmark script, so I just opted to run it twice. Here is the script: https://gist.github.com/ghiculescu/0eff2eb56254aa62bd10bf997cfc1d0f (I toggled both comments between runs).

Here's the output against `main`:

```
Warming up --------------------------------------
         main branch     1.000  i/100ms
Calculating -------------------------------------
         main branch      6.859  (± 0.0%) i/s -     35.000  in   5.103560s
```

And against this branch:

```
Warming up --------------------------------------
           my branch     1.217k i/100ms
Calculating -------------------------------------
           my branch     12.558k (±12.3%) i/s -     62.067k in   5.040604s
```

If you create 100 records (instead of 100_000) the improvements still seem pretty good:

main:

```
Warming up --------------------------------------
         main branch   155.000  i/100ms
Calculating -------------------------------------
         main branch    439.016  (±22.8%) i/s -      2.170k in   5.203504s
```

my branch:

```
Warming up --------------------------------------
           my branch     1.176k i/100ms
Calculating -------------------------------------
           my branch     11.164k (±13.3%) i/s -     56.448k in   5.171713s
```

**Comment by Tonkpils** [comment]
@ghiculescu it seems this patch may have introduced an unintended change in behavior. The gist is 

```ruby
class Foo < ApplicationRecord

  has_many :bars

  before_save :create_bars

  def create_bars
    self.bars = bars.build
  end
end

foo = Foo.new
foo.save

foo.bars
=> #<ActiveRecord::Associations::CollectionProxy [#<Bar id: 1>, #<Bar id: 1>]>
```

The records in the collection have the same object ID so it seems that they are not being deduped? I can investigate a bit further and write up a replication script on Monday but just wanted to give you a heads up 🙇

**Pull request merged**
