### PR TITLE
Clarify behavior for ActiveSupport's String#first, String#last when limit is negative

### PR DESCRIPTION
**Pull request by etdev**
### Summary

I propose we more clearly define the behavior of ActiveSupport's `String#first` and `String#last` methods when passed a negative limit value.

Here's the current (seemingly untested/documented) behavior:

```ruby
str = "hello"
str.first(-1)
# => "hell"
str.last(-2)
# => "llo"
```
I found this a little surprising, but is this the intended behavior?  If so I feel we should at least add [tests for these cases](https://github.com/rails/rails/blob/master/activesupport/test/core_ext/string_ext_test.rb#L379-L413).

If not, I propose that when passed a negative number we either return a blank string:
```ruby
str.first(-1)
# => ""
str.last(-2)
# => ""
```

or raise an ArgumentError:
```ruby
str.first(-1)
# => ArgumentError: limit must be a positive integer
str.last(-2)
# => ArgumentError: limit must be a positive integer
```

This PR implements **the second strategy** above.  

Any thoughts?

### CODE REVIEW

**Comment by lugray** [comment]
My inclination would be that `string.first(n)` should give the same result as `string.each_char.first(n).join`.  Which is to say that I like your second strategy: raising an argument error for negative values.  I especially like this strategy since if someone is using the undocumented current behaviour, it's better that it not start failing *silently*.

**Comment by Edouard-chin** [comment]
Raising an `ArgumentError` seems consistent with bare ruby `first` on array, so 👍  for me

```
irb(main):018:0> [1, 2, 3, 4].first(-2)
ArgumentError: negative array size
	from (irb):18:in `first'
	from (irb):18
	from /opt/rubies/2.3.3/bin/irb:11:in `<main>'
```

**Comment by matthewd** [comment]
Agree an exception is the way to go if we're going to change it.

We should add tests, but having declared negative values to be out-of-range inputs, I don't think it's necessary to describe that behaviour in the API documentation.

I do think a deprecation cycle is necessary, however.

**Comment by oniofchaos** [comment]
@etdev definitely think this is worth trying to get merged in to clarify how these methods work! Can you merge in latest master and see if that helps fix the one failing spec?

**Comment by rafaelfranca** [comment]
Also needs to change the PR to raise an exception.

**Comment by etdev** [comment]
Alright I'll update it to raise an exception instead as discussed, and pull in the recent changes from master.

**Comment by etdev** [comment]
@rafaelfranca @oniofchaos I updated the implementation to throw an ArgumentError, so could you please take another look? Thanks!

**Comment by rafaelfranca** [comment]
Sorry, I forgot to tell that we need to deprecate it first like @matthewd commented:

> I do think a deprecation cycle is necessary, however.

We should return that is being returned now but show a deprecation message. In Rails 6.1 we cam raise the exception.

**Comment by Edouard-chin** [comment]
Can we cherry-pick the commit from #33058 in this PR

**Comment by rafaelfranca** [comment]
I can merge that PR and give everyone credits.

**Pull request closed without merging**
