### PR TITLE
[Fix #48685] Make the encryptor agnostic of the type of data to decrypt

### LINKED ISSUE #48685: Make ActiveRecord Encryptor agnostic of the type of serialized data to be decrypted
### Steps to reproduce

I am using [ActiveRecord Encryption](https://guides.rubyonrails.org/active_record_encryption.html) with latest Rails `7.0.*`, and a custom serializer instead of the default one.

This custom serializer outputs binary values that are stored in a `bytea` column in PostgreSQL, instead of a JSON value in a `text` column, as the default MessageSerializer would do.

It works pretty well except that the `ActiveRecord::Encryption::Encryptor#deserialize_message` prevents `ActiveModel::Type::Binary::Data` objects to be passed to the custom serializer for decryption. (Note: we get this type of data for user inputs subsequently decrypted, e.g. during attribute validation).

I would expect the `Encryptor` to be agnostic about the type of values to decrypt, and let the underlying serializer assert the actual types that it supports.

Note that the default `MessageSerializer` is already able to reject any input which is not a `String`:

1. A  `TypeError` is raised by `JSON.parse` (not caught here)
https://github.com/rails/rails/blob/a5fc471b3f4bbd02e6be38dae023526a49e7d049/activerecord/lib/active_record/encryption/message_serializer.rb#L24-L29
2. The `TypeError` is caught and replaced by an `Encoding` error:
https://github.com/rails/rails/blob/a5fc471b3f4bbd02e6be38dae023526a49e7d049/activerecord/lib/active_record/encryption/encryptor.rb#L102-L107
3. And finally caught again and replaced by  a `Decryption` error:
https://github.com/rails/rails/blob/a5fc471b3f4bbd02e6be38dae023526a49e7d049/activerecord/lib/active_record/encryption/encryptor.rb#L52-L59

So there is no need for this duplicate preventive check at `Encryptor` level in step 2.:

https://github.com/rails/rails/blob/a5fc471b3f4bbd02e6be38dae023526a49e7d049/activerecord/lib/active_record/encryption/encryptor.rb#L103

When I remove that duplicate check, the behavior is unchanged when using the default `MessageSerializer`, but I am able to use a custom serializer too.

### Expected behavior

I would expect the `Encryptor` to be agnostic about the type of values to decrypt, and let the underlying serializer assert the actual types that it supports.

### Actual behavior

The `Encryptor` assumes that the input to be deserialized/decrypted is always a `String` when it could be something else. This unnecessarily prevents the use of custom serializers.

### System configuration

**Rails version**: 7.0.6 / 7.1

**Ruby version**: 3.2.2

### PR DESCRIPTION
**Pull request by maximerety**
### Motivation / Background

This Pull Request has been created to fix https://github.com/rails/rails/issues/48685.

### Detail

[Fix #48685] Make the encryptor agnostic of the type of data to decrypt
    
The default message serializer will raise a `TypeError` when invoking `JSON.parse` on any non-`String` input. This error will subsequently be translated into an `ActiveRecord::Encryption::Errors::Encoding` error and then a `ActiveRecord::Encryption::Errors::Decryption` error by the encryptor, which does not change the current behavior at the encryptor level.

This change clarifies that it is the role of the underlying serializer to accept or reject the data to decrypt depending on its type. This behavior mirrors what is done at encryption, where the serializer asserts that the input is an `ActiveRecord::Encryption::Message`.

This change is a no-op when using the default `MessageSerializer` class, but it enables the use a wider variety of custom serializers.

By being agnostic of the type of data to decrypt at the encryptor level, it is now possible to serialize and store messages in a binary format (e.g. in a `bytea` column in PostgreSQL). A custom message serializer is now able to decrypt binary values coming from the database (`String`) or from user input (`ActiveModel::Type::Binary::Data`) without having an exception raised at the encryptor level because the type is not `String`.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Review by jorgemanrubia — COMMENTED** [review]
This change makes sense @maximerety, thanks for working on it 👍.

Could you please also update [this note in the docs](https://guides.rubyonrails.org/active_record_encryption.html#supported-types), to include a reference to the default `message_serializer`. For example, instead of:

> ...but they must be serializable as strings

We could say something like:

> ...but, unless using a custom `message_serializer`, they must be serializable as strings

I think this should include an Active Record's CHANGELOG entry.

**Comment by maximerety** [comment]
Thank you @jorgemanrubia for your feedback.

While I agree that the note in the docs would be useful, I think it's a bit premature.

At this point, there are still other things to be taken care of if you use a message serializer that does not emit strings.

I started to write a long description of the problem here, and then thought I might aswell make it a separate "bug report" (can be seen as a bug or a feature request, please pardon me if I posted in the wrong place 🙏) : https://github.com/rails/rails/issues/48689.

Whatever the reception of this other ticket, I don't think it detracts from the validity of the present modification.

Nevertheless, I guess we should not advertise new use cases until they are fully supported.

What do you think?

**Comment by jorgemanrubia** [comment]
Thanks for context @maximerety. I followed up in #48689.

**Review by jorgemanrubia — APPROVED** [review]
This change makes sense @maximerety. Thanks!

**Comment by zzak** [comment]
@maximerety Could you rebase and [squash your commits](https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#squashing-commits) please? :bow:

**Comment by maximerety** [comment]
@jorgemanrubia Thank you for your feedback.

@zzak Commits squashed and rebased as requested.

**Comment by jorgemanrubia** [comment]
@eileencodes @rafaelfranca I'd appreciate it if you can merge this one 🙏

**Comment by eileencodes** [comment]
I fixed the conflict on the command line and merged this manually in 4470ad78d1062c923ef3401760b96a3ab4de6eee so I'm going to close this. Thanks!

**Pull request closed without merging**
