### PR TITLE
Remove attributes_protected_by_default reference

### PR DESCRIPTION
**Pull request by robertomiranda**
Remove attributes_protected_by_default reference, since MassAssignmentSecurity was removed from ActiveModel f8c9a4d3e88181

### CODE REVIEW

**Comment by robertomiranda** [comment]
@carlosantoniodasilva @guilleiguaran can we get this merged considering that Rails 4.1 and 4.2 have been released?

**Comment by carlosantoniodasilva** [comment]
We can, but I'd prefer to merge a single PR removing all references. Would you want to work on that or can I go ahead and do it? :)

**Comment by robertomiranda** [comment]
@carlosantoniodasilva I would like too, but I'll leave you the decision on your hands :smile:

**Comment by guilleiguaran** [comment]
iirc, that's the unique place where we have references about `attributes_protected_by_default`, I removed all others during StrongParameters merge :smile:

**Comment by guilleiguaran** [comment]
ack confirms:

```
~/src/rails[master] % ack attributes_protected_by_default
activemodel/lib/active_model/secure_password.rb
82:        if respond_to?(:attributes_protected_by_default)
83:          def self.attributes_protected_by_default #:nodoc:
```

**Comment by robertomiranda** [comment]
@guilleiguaran :+1:

**Comment by carlosantoniodasilva** [comment]
I meant `protected_attributes` in general :smile: 

```
$ ack protected_attributes
activemodel/lib/active_model/secure_password.rb
81:        # This code is necessary as long as the protected_attributes gem is supported.

activerecord/lib/active_record/core.rb
284:      # +options+ argument is only needed to make protected_attributes gem easier to hook.
560:    # This method is needed to make protected_attributes gem easier to hook.

activerecord/test/cases/associations/has_many_associations_test.rb
1759:  def test_load_target_respects_protected_attributes
```

I'll clean those ones. Thanks <3

**Pull request merged**
