### PR TITLE
Enforce frozen string in Rubocop

### PR DESCRIPTION
**Pull request by kirs**
As discussed in https://github.com/rails/rails/pull/29506#issuecomment-309945640, we should be able to enable `Style/FrozenStringLiteralComment` rule in Rubocop and add the magic comment to all files.

@matthewd @rafaelfranca @pat

### CODE REVIEW

**Comment by pat** [comment]
Thanks for sorting this out @kirs! 👏

**Comment by kirs** [comment]
ping @rafaelfranca - I rebased it against master.

**Comment by esparta** [comment]
Although I really like to see this as reality I'm pretty sure this should be done on waves, by packages or sections, not as a single PR. There's enough time to plan and organize what comes first or later.
I'm not part of the maintainers group and my opinion should be taken as just as the point of view more.

**Comment by matthewd** [comment]
Reverted because I got ahead of myself; #29506 wasn't enough to make this green.

**Comment by kirs** [comment]
I'll work on fixing those failures.

**Pull request merged**
