### PR TITLE
Extract #table_exists? to InformationSchemaStatements

### PR DESCRIPTION
**Pull request by maclover7**
### Summary

First PR in a series of PRs I will be opening to use `information_schema` to get database metadata, in order to consolidate previously customized code.

### CODE REVIEW

**Comment by sgrif** [comment]
If you want to have it in a module that's fine, but let's include it on the abstract adapter. The only backends which *don't* implement information_schema are SQLite, Oracle, and DB2. It should be opt-out not opt-in

**Comment by yahonda** [comment]
Agreed to put this into AbstractAdapter as a maintainer of one of database adapter not supporting information schema.

**Comment by maclover7** [comment]
@sgrif @yahonda I didn't put it in `AbstractAdapter` because it already has [an implementation](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb#L54-L56) of this method 😬

**Comment by rafaelfranca** [comment]
@maclover7 could you rebase the PR? Also please implement the complete refactor in the same PR. It is easier to review design choices.

**Comment by maclover7** [comment]
@rafaelfranca ok, I'll rebase and complete the refactor. I originally didn't do the whole thing in one PR because 1) figured it was too much code to review, and 2) afraid it would be denied 😬

**Pull request closed without merging**
