### PR TITLE
Guard clause for id_kind in generator

### PR DESCRIPTION
**Pull request by jmccartie**
Per feedback here: https://github.com/rails/rails/commit/fb42c492a7eff58f45867ea50440d938648cdb48#commitcomment-13917075

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Hmm, the original PR has more problems that this one. I'll point what needed to be changed:

1. this `id_kind` method should be only at the Active Record migration generator.
2. `id_kind` should be renamed to `primary_key_type`.
3. Generators has their own options, we should not couple generators to application/framework options. The problem you are fixing here is just a side effect of doing this coupling. To fix this we should use the generators configuration. In this case it would be `options[:orm][:primary_key_type]` that would be configured with:

```ruby
config.generators do |g|
  g.orm :active_record, primary_key_type: :uuid
end
```

To see more about generators configuration look for https://github.com/rails/rails/blob/2828cfd137416b963f766ff1bda7a2c879e80f9e/railties/lib/rails/engine/configuration.rb#L17-L33

**Comment by jmccartie** [comment]
@rafaelfranca Roger that. I'll make the change today.

**Comment by jmccartie** [comment]
@rafaelfranca Can you explain your first point a bit? Should it not be in this file?

**Comment by rafaelfranca** [comment]
Sure! The only ORM that implements this right now is Active Record, and one hint for that is the template where it is being used is at `activerecord` directory. So, it is better to move it closer to where it is being used, and in this case it is this file https://github.com/rails/rails/blob/master/activerecord/lib/rails/generators/active_record/migration.rb.

Apart for that, others ORM like mongoid may not need a primary_key_type so that option being in the generic migration generator may be unnecessary.

**Comment by jmccartie** [comment]
@rafaelfranca I see. But if I move the method to that file, then this file blows up in the tests:

https://github.com/rails/rails/blob/master/activerecord/lib/rails/generators/active_record/migration/templates/create_table_migration.rb  (undefined method)

Thoughts?

**Comment by rafaelfranca** [comment]
That is weird because that file is evaluated in the context of https://github.com/rails/rails/blob/master/activerecord/lib/rails/generators/active_record/migration/migration_generator.rb that inherit from https://github.com/rails/rails/blob/master/activerecord/lib/rails/generators/active_record.rb that includes https://github.com/rails/rails/blob/master/activerecord/lib/rails/generators/active_record/migration.rb.

Try to define directly in https://github.com/rails/rails/blob/master/activerecord/lib/rails/generators/active_record/migration/migration_generator.rb

**Comment by jmccartie** [comment]
@rafaelfranca Built a sample app and added the following to `application.rb`

```ruby
config.generators do |g|
  g.orm :active_record, primary_key_type: :uuid
end
```

Tried to run migration (`rails g model Book`).

If I have the method in `rails/generator/migration.rb`, then `options` does not have the value:

```
From: /Users/jmccartie/Code/rails/railties/lib/rails/generators/migration.rb @ line 71 Rails::Generators::Migration#primary_key_type:

    70: def primary_key_type
 => 71:   binding.pry
    72:   return unless options[:orm]
    73:   raise "Options = #{options.inspect}"
    74:   key_type = options[:orm][:primary_key_type]
    75:   ", id: :#{key_type}" if key_type
    76: end

[1] pry(#<ActiveRecord::Generators::ModelGenerator>)> options
=> {"skip_namespace"=>false,
 "migration"=>true,
 "timestamps"=>true,
 "indexes"=>true,
 "test_framework"=>:test_unit,
 "force"=>true}
```

and if I place the method in `generators/active_record/migration.rb`, I received a `no method error` . Also `options` is not defined in that class.

Any thoughts?  (thanks again for your help here -- I'm obviously still learning this file structure)

**Comment by rafaelfranca** [comment]
Try `self.class.options`

**Comment by jmccartie** [comment]
@rafaelfranca Thanks. I agree it probably belongs in activerecord/lib/generators/active_record.rb, and the method gets properly called from there. And although `options` is available to me there, it does not include `primary_key` if I set it. 

I'm digging around, trying to see if there's some sort of whitelist that I need to add the attr to ...

**Comment by jmccartie** [comment]
@rafaelfranca This is my best shot so far. Anybody know how to get these options?

```ruby
def primary_key_type
  key_type = Rails::Generators.options[:active_record][:primary_key_type]
  ", id: :#{key_type}" if key_type
end
```

**Comment by rafaelfranca** [comment]
Oh, `options[:active_record]` is the right namespace. Did `self.class.options[:active_record]` works?

**Comment by jmccartie** [comment]
@rafaelfranca Unfortunately, neither work here:

```
From: /Users/jmccartie/Code/rails/activerecord/lib/rails/generators/active_record.rb @ line 18 ActiveRecord::Generators::Base#primary_key_type:

    17: def primary_key_type
 => 18:   binding.pry
    19:   key_type = Rails::Generators.options[:active_record][:primary_key_type]
    20:   ", id: :#{key_type}" if key_type
    21: end

[1] pry(#<ActiveRecord::Generators::ModelGenerator>)> options[:active_record]
=> nil
[2] pry(#<ActiveRecord::Generators::ModelGenerator>)> self.class.options[:active_record]
NoMethodError: undefined method `options' for ActiveRecord::Generators::ModelGenerator:Class
from (pry):2:in `primary_key_type'
[3] pry(#<ActiveRecord::Generators::ModelGenerator>)>
```

**Comment by rafaelfranca** [comment]
Maybe it is missing https://github.com/rails/rails/blob/master/activerecord/lib/rails/generators/active_record/model/model_generator.rb#L10

**Comment by jmccartie** [comment]
@rafaelfranca Good call.  Adding `class_option :primary_key_type, :type => :string` to that section makes options[:primary_key_type] available.  Works great in sample app.

Next issue is the test. If I set that value, it's not available in the test for some reason:

```
def test_add_uuid_to_create_table_migration
    Rails::Generators.options[:active_record][:primary_key_type] = :uuid
...
```

then

```
➜  railties git:(jm/uuid_nil) ✗ bundle exec ruby -Itest test/generators/migration_generator_test.rb
  1) Error:
MigrationGeneratorTest#test_create_table_migration_with_singular_table_name:
RuntimeError: ===> Key type:
    /Users/jmccartie/Code/rails/activerecord/lib/rails/generators/active_record.rb:18:in `primary_key_type'
```

Since it works in my sample app, I'm guessing this is just a test setup issue. I'll keep plugging away at it tonight unless you know some quick way to solve this.

**Comment by rafaelfranca** [comment]
Tests should be like this https://github.com/rails/rails/blob/master/railties/test/generators/model_generator_test.rb#L357-L365. Passing primary_key_type as argument in the command line.

**Comment by jmccartie** [comment]
Thanks @rafaelfranca 

None of following work. Am I close? :) 

```
run_generator ["create_books", "--primary-key-type uuid", "primary_key_type:uuid", "--primary_key_type uuid"]
```

```
Options available int est: ======== {:rails=>{:api=>false, :assets=>true, :force_plural=>false, :helper=>true, 
:integration_tool=>:test_unit, :javascripts=>true, :javascript_engine=>:js, :orm=>:active_record, 
:resource_controller=>:controller, :resource_route=>true, :scaffold_controller=>:scaffold_controller, 
:stylesheets=>true, :stylesheet_engine=>:css, :scaffold_stylesheet=>true, :test_framework=>:test_unit, 
:template_engine=>:erb}, :active_record=>{:migration=>true, :timestamps=>true}, :test_unit=>
{:fixture=>true, :fixture_replacement=>nil}}
```

**Comment by rafaelfranca** [comment]
Thank you for the pull request. I merged it in https://github.com/rails/rails/compare/f94e328cf801...5a47639aac45 and made the adjusts to work properly with generators options.

**Comment by jmccartie** [comment]
Thanks @rafaelfranca !

**Pull request closed without merging**
