### PR TITLE
Refactor Chars#reverse and Chars#grapheme_length

### PR DESCRIPTION
**Pull request by frodsan**
Use \X meta character directly to get grapheme clusters.

Thanks to @mtsmfm for the tip:
https://github.com/rails/rails/pull/34123#issuecomment-429028878

r? @jeremy

### CODE REVIEW

**Review by jeremy — APPROVED** [review]
👨‍❤️‍👨

**Comment by mtsmfm** [comment]
FYI: 
Since Ruby 2.5, we can use `String#grapheme_clusters` instead of `str.scan(/\X/)`
https://docs.ruby-lang.org/en/2.5.0/String.html#method-i-grapheme_clusters

Rails 6 supports Ruby 2.4 though.

**Comment by jeremy** [comment]
Wonderful, @mtsmfm. Let's prefer that method when available!

**Comment by frodsan** [comment]
@jeremy Can we deprecate `Unicode#unpack_graphemes` and `Unicode#pack_graphemes` now that they are not used in `Chars` or other parts of the code? I made a search around GitHub and most results are projects that vendor AS: https://github.com/search?q=unpack_graphemes&type=Code

**Comment by jeremy** [comment]
@frodsan I believe so! Let's do it.

**Pull request merged**
