### PR TITLE
Better ActionText plain text output for nested lists

### PR DESCRIPTION
**Pull request by swanson**
### Summary

When using `to_plain_text` on action text content, nested lists are not rendering in an expected way. Out of the box, the rich text editor allows arbitrary nesting of lists using the "Increase" and "Decrease Level" buttons.

Basic case with one nested item:

```ruby
ActionText::Content.new("<ul><li>Item 1<ul><li>Item a</li></ul></li></ul>").to_plain_text

=> "• Item 1• Item a"
```

Expected:

```
• Item 1
  • Item a
```

Complex case with multi-level nested and mixed list types:

```ruby
ActionText::Content.new("<ul><li>Item 0</li><li>Item 1<ul><li>Item A<ol><li>Item i</li><li>Item ii</li></ol></li><li>Item B<ul><li>Item i</li></ul></li></ul></li><li>Item 2</li></ul>").to_plain_text

=> "• Item 0
• Item 1• Item A1. Item i
2. Item ii
• Item B• Item i
• Item 2"
```

Expected:

```
• Item 0
• Item 1
  • Item A
    1. Item i
    2. Item ii
  • Item B
    • Item i
• Item 2
```

### Other Information

This PR adds two-space indentation per nested level for `ul` and `ol` when using `to_plain_text` on action text content.

Test case included. All tests passing locally.

### CODE REVIEW

**Comment by swanson** [comment]
@javan @sstephenson anything I can do to help move this along?

**Comment by swanson** [comment]
:wave: is anyone up for reviewing/giving feedback? Happy to put in more work on this as I still need it for a project and have it monkey-patched at the moment. @kaspth

**Comment by kaspth** [comment]
Hey, we've refit Action Text's internals a bunch for a product we're working on, so this code is fairly different. That work is scheduled to go public, but I don't have any details yet. Let's revisit then.

I'll throw it on the milestone for the next major, so we eventually make a call about this. No guarantees as to what the call will be, sorry 😄

**Comment by swanson** [comment]
Still a valid issue IMO, but seems like it's still pending ActionText internals change?

**Comment by swanson** [comment]
@dhh are you able to share any plans about upstreaming the ["refit ActionText internals"](https://github.com/rails/rails/pull/37976#issuecomment-605503076) from HEY? This issue is still relevant but was pending those potential changes.

**Pull request merged**
