### PR TITLE
Enable `Style/IfInsideElse` cop

### PR DESCRIPTION
**Pull request by kamipo**
It enforces c8a84603e2fa97822407bf4a1c8ac0308a899163.

### CODE REVIEW

**Comment by kaspth** [comment]
This doesn’t seem to have that much benefit to me. Some of the cases read better with the tailing if to match a railing if on the line above.

**Comment by kamipo** [comment]
Yeah, I agree that warning the tailing if is too strict, it is preferable to add new enforced style that allowing the tailing if first in the RuboCop side.

**Comment by koic** [comment]
I opened a PR to rubocop-hq/rubocop#7150 based on the conversation.

**Comment by koic** [comment]
rubocop-hq/rubocop#7150 has been merged. It can be obtained by adding the following setting in the next RuboCop release.

```yaml
Style/IfInsideElse:
  Enabled: true
  AllowIfModifier: true
```

**Comment by kaspth** [comment]
Did another read. I don't think we need to enforce this. Thanks for bringing it up and taking a look both of you ❤️

**Pull request closed without merging**
