### PR TITLE
Add note about step needed to get tests to pass if you implemented basic auth [ci skip]

### PR DESCRIPTION
**Pull request by JessRudder**
Addresses #22862

Added note about needing to add additional code to the setup block to get the tests to pass if you've implemented basic authorization.

[ci skip]

cc @cllns

### CODE REVIEW

**Review by maclover7 — APPROVED** [review]

**Comment by maclover7** [comment]
:+1: Thank you for your contribution!

:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by cllns** [comment]
💕 thank you!

**Comment by maclover7** [comment]
👏 Congrats on your first PR to Rails, @JessRudder!!

**Comment by matthewd** [comment]
👋🏻

**Pull request merged**
