### PR TITLE
Add test for Gemfile.lock after 'bundle install' finishes

### PR DESCRIPTION
**Pull request by zzak**
This test produces the following output (but passes) on my local machine:

```
/Users/zzak/.rubies/ruby-3.3.0/lib/ruby/3.3.0+0/bundler/resolver.rb:293:in `raise_not_found!': Could not find gem 'rails (~> 7.1.0.alpha)' in locally installed gems. (Bundler::GemNotFound)
	from /Users/zzak/.rubies/ruby-3.3.0/lib/ruby/3.3.0+0/bundler/resolver.rb:346:in `block in prepare_dependencies'
	from /Users/zzak/.rubies/ruby-3.3.0/lib/ruby/3.3.0+0/bundler/resolver.rb:331:in `each'
	from /Users/zzak/.rubies/ruby-3.3.0/lib/ruby/3.3.0+0/bundler/resolver.rb:331:in `map'
	from /Users/zzak/.rubies/ruby-3.3.0/lib/ruby/3.3.0+0/bundler/resolver.rb:331:in `prepare_dependencies'
	from /Users/zzak/.rubies/ruby-3.3.0/lib/ruby/3.3.0+0/bundler/resolver.rb:51:in `setup_solver'
	from /Users/zzak/.rubies/ruby-3.3.0/lib/ruby/3.3.0+0/bundler/resolver.rb:28:in `start'
	from /Users/zzak/.rubies/ruby-3.3.0/lib/ruby/3.3.0+0/bundler/definition.rb:554:in `start_resolution'
	from /Users/zzak/.rubies/ruby-3.3.0/lib/ruby/3.3.0+0/bundler/definition.rb:289:in `resolve'
	from /Users/zzak/.rubies/ruby-3.3.0/lib/ruby/3.3.0+0/bundler/definition.rb:507:in `materialize'
	from /Users/zzak/.rubies/ruby-3.3.0/lib/ruby/3.3.0+0/bundler/definition.rb:197:in `specs'
	from /Users/zzak/.rubies/ruby-3.3.0/lib/ruby/3.3.0+0/bundler/definition.rb:254:in `specs_for'
	from /Users/zzak/.rubies/ruby-3.3.0/lib/ruby/3.3.0+0/bundler/runtime.rb:18:in `setup'
	from /Users/zzak/.rubies/ruby-3.3.0/lib/ruby/3.3.0+0/bundler.rb:170:in `setup'
	from /Users/zzak/.rubies/ruby-3.3.0/lib/ruby/3.3.0+0/bundler/setup.rb:20:in `block in <top (required)>'
	from /Users/zzak/.rubies/ruby-3.3.0/lib/ruby/3.3.0+0/bundler/ui/shell.rb:159:in `with_level'
	from /Users/zzak/.rubies/ruby-3.3.0/lib/ruby/3.3.0+0/bundler/ui/shell.rb:111:in `silence'
	from /Users/zzak/.rubies/ruby-3.3.0/lib/ruby/3.3.0+0/bundler/setup.rb:20:in `<top (required)>'
	from <internal:/Users/zzak/.rubies/ruby-3.3.0/lib/ruby/3.3.0+0/rubygems/core_ext/kernel_require.rb>:88:in `require'
	from <internal:/Users/zzak/.rubies/ruby-3.3.0/lib/ruby/3.3.0+0/rubygems/core_ext/kernel_require.rb>:88:in `require'
```

I'd like to verify bundle install finishes in CI.

### CODE REVIEW

**Comment by zzak** [comment]
🔴 

```
Failure:
--
  | AppGeneratorTest#test_generation_runs_bundle_install [test/generators/app_generator_test.rb:694]:
  | Expected file "/rails/railties/test/fixtures/tmp/Gemfile.lock" to exist, but does not

```

**Comment by zzak** [comment]
Would love to know why this test is failing 🤔

**Comment by skipkayhil** [comment]
I think for `bundle install` to actually work we would need to change the test like #46478

**Comment by zzak** [comment]
FWIW I did try `run_generator_and_bundler` but couldn't get it to work /cc @jonathanhefner

**Comment by jonathanhefner** [comment]
The reason the assertion fails is because `run_generator_instance` does not run Bundler (for performance reasons).  Instead, it stubs `bundle_command` and tracks Bundler invocations in `@bundle_commands`:

https://github.com/rails/rails/blob/4d171a4bde5317c9bb6a6f178597458fed84037f/railties/test/generators/shared_generator_tests.rb#L337-L344

I'm not sure why the assertion passes for you locally.  Maybe you have a `Gemfile.lock` from another source that didn't get cleared?

> FWIW I did try `run_generator_and_bundler` but couldn't get it to work

How so?  What did not work?

Keep in mind, though, that we should only run Bundler when necessary (for performance reasons).  Asserting that `Gemfile.lock` exists is essentially testing Bundler's behavior, which *should be* unnecessary.  Asserting that we've called Bundler properly *should be* enough.

**Pull request closed without merging**
