### PR TITLE
Added a test around `NO_AUTO_VALUE_ON_ZERO`:

### PR DESCRIPTION
**Pull request by Edouard-chin**
Added a test around `NO_AUTO_VALUE_ON_ZERO`:

- The mysql `NO_AUTO_VALUE_ON_ZERO` mode should be disabled when inserting fixtures in bulk, this PR adds a test to make sure we don't remove it by mistake
- If we live this mode enabled, a statement like this wouldn't work and a `Duplicate entry '0' for key 'PRIMARY'` error will be raised. That's because `DEFAULT` on auto_increment will return 0

```sql
INSERT INTO `aircraft` (`id`, `name`, `wheels_count`) VALUES (DEFAULT, 'first', 2), (DEFAULT, 'second', 3)
```

### CODE REVIEW

**Comment by sgrif** [comment]
`NO_AUTO_ON_ZERO` shouldn't affect `DEFAULT`, only an explicit value of `0` being given.

**Comment by sgrif** [comment]
I suspect this is there due to some applications using the value of `0` in their fixtures. I'm in favor of this change, but I'm not sure if we need a deprecation cycle (nor do I know how we would go about adding one)

**Comment by Edouard-chin** [comment]
Thanks for looking @kamipo ! 

We probably shouldn't get rid of it then, that's why @kirs added it. Unless objection I will modify this PR to just add a test that covers this case

**Comment by rafaelfranca** [comment]
👍  to add the test

**Comment by Edouard-chin** [comment]
Added the test, travis is having a hard time since yesterday but the failures aren't related

**Pull request merged**
