### PR TITLE
Documentation: Add touch_all to callbacks and validations guides [ci skip]

### PR DESCRIPTION
**Pull request by santib**
### Summary

Just a minor change, but I noticed in the guides it wasn't mentioned the `touch_all` behavior regarding callbacks and validations.

### CODE REVIEW

**Comment by jonathanhefner** [comment]
Good catch!  What do you think about changing the [`touch_all` method doc](https://github.com/rails/rails/blob/596d4dbb336d29d9b13487624b99657cd4161c6c/activerecord/lib/active_record/relation.rb#L511-L515) as well to indicate that it (unlike `touch`) does not trigger callbacks?

**Comment by santib** [comment]
sure @jonathanhefner, would something like that work? I'm ok if you'd like some other wording

**Comment by jonathanhefner** [comment]
> The comparison with `touch` doesn't convince me since `touch` doesn't trigger validations and only `after_touch` callback is ran.

Right, I was just mentioning `touch` as reason for adding the note to the `touch_all` method doc.  (Compared to, say, the `update_counters` method doc, which also doesn't have that note, but probably doesn't need it.)

I was thinking the note could follow the first sentence with a minor modification:

`Touches all records in the current relation, setting the +updated_at+/+updated_on+ attributes to the current time or the time specified. It does not instantiate the involved models, and it does not trigger Active Record callbacks or validations.`

**Comment by santib** [comment]
That sounds good to me 💯

**Comment by jonathanhefner** [comment]
Great!  Thank you @santib!

**Pull request merged**
