### PR TITLE
Add info about ActionText, ActionMailbox and planned timeline

### PR DESCRIPTION
**Pull request by mikkovedru**
Adding general info to those interested.

### CODE REVIEW

**Review by bogdanvlviv — APPROVED** [review]

**Comment by mikkovedru** [comment]
> Guides aren't really meant to have a timeline in them. They're a record of what has happened, not what is going to be happen.

When I type "rails 6" in Google, the link https://edgeguides.rubyonrails.org/6_0_release_notes.html is second in a list. The article is linked from many other Rails 6 articles. The point is that this is not an obscure text somewhere on The Dark Web - it is a text that many people read in order to see details about Rails 6. I was one of those people. And I was totally confused by the information presented. Imagine the typical confusions of a normal person (who is not active in Rails development/community):
- "Why so little info? Oh, apparently Rails 6 is not released yet... So why can't this article clearly say on the very top of the page that Rails 6 and this documentation are a work-in-progress? It's irritating having to Google separately for this info!"
- "Ok, the Rails 6 is a work in progress, the list of features is not yet complete - I understand all that. But why can't this article have at least something - even some simple mentions on what is upcoming, on what features were already decided to be included?"
- "Rails 6 is work in progress. But why isn't here any info about the timeline in the main document that describes this milestone? Until the release, info about the dates are the most important info one needs (the need for features/compatibility documentation comes after the need for a timeline; everything else becomes important even later on). Do I really have to be an active part of the Rails development community in order to get a simple answer? Do I really need to start reading blogs just to see some glimpses and guestimations about the possible release dates? Looks totally excessive... I wish this important info was right here and there would be a volunteer, who would bother to make such changes..."


Rails 6 will be one of the biggest releases yet. Cool changes to Rails should be actively promoted (it's not like Rails has been winning the Web competition even against Python). The documentation page is an essential part of Rails's marketing. It should be used to the fullest, even if the info written is there only temporarily and will be deleted after the release. The fact that this info will be there for a year, informing the very people interested in the release, is more than enough to make an effort to make proposed changes worth it.

If you still disagree, then [this page](https://edgeguides.rubyonrails.org/6_0_release_notes.html) should be closed from public view. I would prefer not to, but for the sake of consistency this must be done. The link should start working publicly only after the release since the article should tell only about stuff that has already happened. If I will make this suggestion can I count on your approval/support?


> Let's wait for Action Text and Action Mailbox to be merged into Rails before we write about them. 
The decision to include both was already made:
- https://weblog.rubyonrails.org/2018/10/3/introducing-action-text-for-rails-6/
- https://weblog.rubyonrails.org/2018/12/13/introducing-action-mailbox-for-rails-6/
Both posts were written by the DHH himself, on Rails's official web site. This is as close to the actual merge as one gets.

The Release Notes page for Rails 6 are 'Work in progress'. So why isn't work on it allowed?


So why to wait? Why to leave things until the last moment? Why to leave it until the crunch time? I am sure that during the release window there will be plenty of other important things to do (admittedly much more technically difficult than what I am doing here; so why not let competent people do the difficult stuff, while I am helping with this kind of important "minutiae"). Why can't I help a little bit, now that I have time and motivation, to help other people (here and now) that are searching for the relevant information?

Marketing = selling ideas to people. This usually means having to go where the people/customers are. Rails is in a very fortunate situation that it has people who come to the aforementioned page in order to be "sold" (the idea that Rails 6 will be an awesome release, that Rails is in good hands and is a viable option for development). This opportunity is not used. I had a modest proposal of at least closing the most glaring hole and getting at least some kind of benefit from all the current visitors (who at this moment and until the release will simply waste their time visiting the page and learn absolutely nothing about the main topic of the article).


I sincerely hope that you will reconsider your decision.

Regardless, please do have a nice day! :-)

**Comment by kaspth** [comment]
Thanks for elaborating! I did not expect "to those interested" would be expanded to all that and I definitely didn't anticipate your Google search results point, good idea! 😄

This sparked a discussion in Core and we're looking into doing something to leverage this, as you've suggested. Most of us want something other than to add this info wholesale into this guide, so that still hasn't changed.

We've discussing the release timeline internally and we hope to announce that on the blog when it's ready. So that'll be our immediate fix. Once that's out, feel free to chime in with the search results status on your end too! Thanks again 😊

**Comment by mikkovedru** [comment]
@kaspth 
I guess [this link](https://weblog.rubyonrails.org/2018/12/20/timeline-for-the-release-of-Rails-6-0/) is what you meant? Thank you for having a separate post about the timeline of Rails! Now my only request would be to put this link at the top of the documentation page. :-)

Almost 3 weeks have passed, but this timeline link is not on the first page of Google search results ("rails 6"). I am sure that it could be somewhat easily found by changing the search query, but that doesn't really change my overall points:
1. This would require more work from the user. If something can be done to improve "usability" (generally speaking), it should be done.
2. (all the stuff I already wrote about the importance of marketing and use of opportunities like when "the customer" is already here to consume relevant information)
3. Internet is a linked system. Without links the main purpose of Internet/pages is defeated. One should link important pages with each other. This not only improves the "usability" of the web page (those who are interested, can go and read more), but also improves the standing in search engines (a link from the major Rails 6 page would make not only the specific Rails 6 Timeline post more visible and relevant, but would improve the overall standing of the whole Rails blog).

Could you please put a link to the Timeline blog post at the top of the documentation page (with a short mention that Rails 6 has not been release yet)? That would really improve the informational value of the documentation page!

**Comment by kaspth** [comment]
Thanks, I'll pass on working on this 👍

**Comment by rafaelfranca** [comment]
The documentation page is tied to releases. Even if we add a link for the post in the documentation it would be only accessible and easy to find in a Google search at the time that Rails 6 is released, so doing that would not help much.

I just tried a good search with "rails 6" on google and that post was the first result. For the future, the timeline will be always the same, always releasing on April. I plan to write a documentation page about our general release engineering some time before the rails 6 release.

**Pull request closed without merging**
