### PR TITLE
Add fixture use case to testing.md.

### PR DESCRIPTION
**Pull request by bunneyster**
I think people would find it useful to know that you can pass in multiple fixture names to get an array of all the fixtures. I've found this useful in my own app. It looks like there already a test case that supports this feature (https://github.com/rails/rails/blob/master/activerecord/test/cases/fixtures_test.rb#L398), but it's just not documented here.

I look forward to your feedback!

### CODE REVIEW

**Comment by zzak** [comment]
Good catch!

**Comment by NingningShang** [comment]
Thanks!  :+1:

**Comment by NingningShang** [comment]
And thank you for being the author of Hibaby, where Victor met the dear beautiful girl for the first time, please write more if you like <3 <3 <3

**Comment by NingningShang** [comment]
Thanks for writing code for my birthday every year, and updating the Herokuapp blog on my birthday and our anniversary and help me to develop the love flower idea, Victor <3 <3 <3 Also thanks for answering my questions on your twitter, quora and google plus account.

**Comment by NingningShang** [comment]
Thank you for giving me so many test advices, I will follow your instruction. And thanks for sharing the information on research gate, love you, Victor <3 <3 <3 The Edison Cup project is awesome, thanks for the updates <3 <3 <3

**Comment by NingningShang** [comment]
Thank you Victor for your help <3 <3 <3

**Pull request merged**
