### PR TITLE
Backport "save attributes changed by callbacks after update_attribute"

### PR DESCRIPTION
**Pull request by tarebyte**
This backports https://github.com/rails/rails/pull/27780 to the 5.0.x series.

/cc @eileencodes & @tenderlove

### CODE REVIEW

**Comment by chrismhilton** [comment]
Any reason this commit didn't make it into the 5.0.7.1 (november 2018) or 5.0.7.2 (march 2019) release? Sorry if this isn't the right place to ask this question.

**Comment by eileencodes** [comment]
Those are security releases @chrismhilton so we don't add bug fixes or improvements to those versions.

**Comment by chrismhilton** [comment]
Thanks for the quick answer @eileencodes so do you happen to know why there hasn't been a 5.0.8 release?

**Comment by eileencodes** [comment]
Because it's no longer supported. If you're still using 5.0.8 you should upgrade as currently only 5.2 and 6.0 are supported for security releases, and 6.0 for bug fixes. 

You can see our maintenance policy here https://guides.rubyonrails.org/maintenance_policy.html

**Pull request merged**
