### PR TITLE
[ActiveModel] Improve the performance of mass assignments

### PR DESCRIPTION
**Pull request by shotat**
### Summary

Improve the performance of ActiveModel initializer with removing duplicated string object generation.

### Other Information

simple benchmarks for `ActiveModel::new`

1.2x faster than the current implementation.

```
before     31.132k (± 5.2%) i/s -    157.781k in   5.083369s
after      37.170k (± 4.7%) i/s -    185.614k in   5.006230s
```

### CODE REVIEW

**Comment by jonathanhefner** [comment]
Although I honestly enjoy micro-optimizing, this change will probably have no effect outside of a microbenchmark.  Have you tested it in a larger context?

Also, String#freeze would be more idiomatic.

**Comment by shotat** [comment]
@jonathanhefner 
Thanks. I agree with your opinion. There might be no effect on a typical Rails app.

However, `ActiveModel` is used in various contexts independent of Rails.
This change benefits on batch processing like data format conversions using `ActiveModel`.

**Comment by rafaelfranca** [comment]
Thank for the pull request but could you just put `# frozen_string_literal: true` to the top of the file? Or the performance improvement come from avoiding to do the interpolation twice?

**Comment by kaspth** [comment]
What's the diff if we use quoted symbols `:#{k}=`?

**Comment by shotat** [comment]
@rafaelfranca 
Thanks, I just put `# frozen_string_literal: true`.
The problem was unnecessary repeated string interpolations as you mentioned.

@kaspth 
Thanks. I noticed that quoted symbols are better as a whole.
Following reflection methods(`respond_to?` and `public_send`) handles symbols faster than strings.

```
 after     40.172k (± 2.6%) i/s -    203.149k in   5.060347s
before     32.679k (± 4.0%) i/s -    163.929k in   5.025078s
```

**Comment by twalpole** [comment]
If this performance improvement is worth doing, I'm curious why not just skip the `respond_to?` and instead rescue the NoMethodError.  It about 20% faster where the attribute exists (when the setter isn't actually doing anything) which is the path here that would be worth the performance improvement

**Pull request merged**
