### PR TITLE
Document `NOTE`, `TIP` and `WARNING` guidelines [ci-skip]

### PR DESCRIPTION
**Pull request by p8**
### Motivation / Background

It's currently unclear when to use `NOTE`, `TIP` or `WARNING`.
This tries to document it's usage.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Review by skipkayhil — APPROVED** [review]
This is really great 👍

**Review by akhilgkrishnan — APPROVED** [review]

**Comment by p8** [comment]
I reworded everything a bit.

**Review by MatheusRich — APPROVED** [review]
Very good! TY

**Comment by p8** [comment]
Thanks @skipkayhil @akhilgkrishnan @MatheusRich  !

**Pull request merged**
