### PR TITLE
Attributes created by store_accessor can be casted with cast_type (#3…

### PR DESCRIPTION
**Pull request by FX-HAO**
#33767

### CODE REVIEW

**Comment by vmaxv** [comment]
@sgrif would you have any chance to look at this please?

**Comment by silverdr** [comment]
Is there a chance that someone from the Rails team could give this one a look?

**Comment by vmaxv** [comment]
@sgrif @rafaelfranca Would you mind giving it a chance?

**Comment by rafaelfranca** [comment]
We gave it a chance in https://github.com/byroot/activerecord-typedstore. We could integrate that gem into Rails, but this PR doesn't do what needs to be done to properly support `store_accessor`'s accessor do define proper types.

**Pull request closed without merging**
