### PR TITLE
Correct method documentation

### PR DESCRIPTION
**Pull request by fragoulis**
Method documentation update to reflect changes after #28800.

### CODE REVIEW

**Comment by y-yagi** [comment]
Can you change the base branch to `master`? After merging, I will backport to `5-2-stable`.

**Comment by jfragoulis** [comment]
Done.

**Comment by y-yagi** [comment]
Thanks!

**Comment by y-yagi** [comment]
Backported: https://github.com/rails/rails/commit/191851382ba71147a9f2a40a25b6c0a7399b503f

**Pull request merged**
