### PR TITLE
Update upsert_all documentation [ci skip]

### PR DESCRIPTION
**Pull request by sharang-d**
Changes from https://github.com/rails/rails/pull/35531/files#r263997083.

cc @kamipo

### CODE REVIEW

**Comment by kamipo** [comment]
Can you also change the code format? This looks odd to me.

https://github.com/rails/rails/blob/5754d69117a68bbc742bc468374b3d0a36070b04/activerecord/lib/active_record/persistence.rb#L255-L256

**Comment by sharang-d** [comment]
Pushed the change.

**Comment by kamipo** [comment]
Can you squash your commits?

**Comment by sharang-d** [comment]
Done :)

**Pull request merged**
