### PR TITLE
refactor ActiveRecord::Type::Serialized by removing not needed code

### PR DESCRIPTION
**Pull request by dcrec1**
Removed not needed processing.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
cc @sgrif

**Comment by sgrif** [comment]
@dcrec1 This is now the fourth place in which I've said we will not accept this change. When a pull request is closed, it is not appropriate to open an almost identical pull request calling it a "refactoring".

**Comment by dcrec1** [comment]
@sgrif What change? This commit simplifies the code and in some cases improves performance, which is the problem?

**Comment by matthewd** [comment]
@dcrec1 this looks an awful lot like the change in #20521.

I think Sean's been pretty clear so far that any change in how we persist values would be a breaking change, and has further explained why we're not interested in making such a breaking change in this area.

If you've found another hole in our test coverage, we'll gladly fill it (65cd9f7694a4791b9b8515073b9b1623c0970e79)... but that doesn't change the fact that **we are not going to change this behaviour**.

In that PR, many comments ago, you said:

> I'm helping you, not fighting against you.

I would strongly encourage you to re-evaluate that position, over the last 24 hours of back-and-forth.

I don't know how to say it any more clearly: this change is not welcome. Further obstinance will not be well received.

**Comment by dcrec1** [comment]
@matthewd the commit you referenced includes some behaviour changes and part of the refactor of this commit, this commit just includes a refactor. The referenced commit will not pass the tests anymore after @sgrif's commit, but this commit will because no behaviour is being changed. 

Sorry if my english is bad, but this commit doesn't change any behaviour, just simplifies the code and improves performance in some cases.

For me it's pretty clear that you think that this commit is changing some behaviour and I'm just trying to help you understand that it doesn't.

**Comment by matthewd** [comment]
``` ruby
% be irb -ractive_record
> ActiveRecord::Type::Serialized.new(
*    ActiveRecord::Type::Text.new,
*    ActiveRecord::Coders::YAMLColumn.new(Hash)
> ).serialize({})
=> nil

% hub merge https://github.com/rails/rails/pull/20536

% be irb -ractive_record
> ActiveRecord::Type::Serialized.new(
*    ActiveRecord::Type::Text.new,
*    ActiveRecord::Coders::YAMLColumn.new(Hash)
> ).serialize({})
=> "--- {}\n"
```

That is both a behavioural change, and an absolutely enormous coincidence -- by some chance, it happens to be *exactly* the change you were so persistently arguing for yesterday.

Walk away.

**Comment by dcrec1** [comment]
Oh yes, this changes the behaviour of `#serialize`, but I meant it doesn't change the persistence behaviour because cause of some internals the `nil` value is never passed to this method. What I mean is that `{}` and `[]` will still persist to `nil`.

If this is the problem, I changed the code to include this conditional dcrec1@a832f85 .

That said, as @dhh said, I understand Rails is omakase and that you don't need any reason to pull my request neither have any obligation. I'm just answering your accusations that this commit breaks some Rails code because it doesn't. If you don't like people arguing against your thoughts, please just ignore me.

**Pull request closed without merging**
