### PR TITLE
option to disable all methods that ActiveRecord.enum generates

### PR DESCRIPTION
**Pull request by alfie-max**
### Motivation / Background

This Pull Request has been created because of a use cases where these methods generated by enum are conflicting and most of the times not all methods are required. 

### Detail

This Pull Request add one more option passed into enum declaration where user can opt to not have the default methods generated

### Checklist

Before submitting the PR make sure the following are checked:

* [ ] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [ ] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [ ] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.
* [ ] CI is passing.

### CODE REVIEW

**Comment by alfie-max** [comment]
i agree.. i too was a bit iffy on the naming.. `instance_accessor` might be closer to what it is.. but not really `class_variable` also there are other class variables too so that might be misleading..

**Comment by skipkayhil** [comment]
Related: #46495

**Comment by alfie-max** [comment]
Looks related.. but that one’s specifically for customising the scopes generated for each enum value.. right?

**Comment by rafaelfranca** [comment]
`instance_methods` maybe?

**Comment by alfie-max** [comment]
isn't `instance_methods` a reserved keyword?

**Comment by rafaelfranca** [comment]
Not that I know.

```
?> def foo(instance_methods: "a")
?>   puts instance_methods
>> end
=> :foo
>> foo(instance_methods: 2)
2
=> nil 
```

**Comment by alfie-max** [comment]
let me give it a try..

**Comment by alfie-max** [comment]
@rafaelfranca I've made the recommended change..

**Comment by johnnyshields** [comment]
`instance_methods` should become `false` by default in Rails 8...

**Comment by goalaleo** [comment]
Are there any plans to merge this to any Rails 7 release?

**Comment by rafaelfranca** [comment]
It is already. Rails 7.1 will have this feature.

**Pull request merged**
