### PR TITLE
Add `String#words` and `NilClass#words`

### PR DESCRIPTION
**Pull request by seanpdoyle**
### Summary

Implement `String#words` to split out words from a String, and
`NilClass#words` to return `[]`.

```ruby
"Hello, world!".words # => ["Hello", "world"]
nil.words             # => []
```

### CODE REVIEW

**Comment by henrik** [comment]
What’s the intended use case, please?

I know from linguistics and NLP at university that splitting into “words” is not trivial to do well, and what constitutes a “word” is not straightforward either. Perhaps calling this “tokens” would be more accurate - I believe this might be closer to [tokenisation](https://en.wikipedia.org/wiki/Lexical_analysis#Tokenization).

From a quick look it would not handle words/tokens like “e.g.” like one may expect. But again, knowing the use case would help determine a good name for it and how accurate it needs to be :)

**Comment by seanpdoyle** [comment]
Great call question @henrik. My use case is actually token splitting from DOMToenList attributes, so tokens might be a better name. With that in mind, I'm not sure about how to handle something like e.g. but maybe a renaming would better communicate intent, and avoid situations where that combination of characters is likely.

**Comment by henrik** [comment]
Thank you for clarifying! DOMTokenList [seems to always be space-separated](https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList) so perhaps just String#split would do for that?

**Comment by seanpdoyle** [comment]
HTML allows for new line breaks as well, which is what I was hoping to support with /\s+/

**Comment by henrik** [comment]
#split does that :)

``` ruby
"1 2\n3\n 4 5\n".split
# => ["1", "2", "3", "4", "5"]
```

**Pull request closed without merging**
