### PR TITLE
Fix reverse of record_state after rollback

### PR DESCRIPTION
**Pull request by iantropov**
Fix reverse of record_state(new_record and id) after rollback.
Fix #7807

### CODE REVIEW

**Comment by rafaelfranca** [comment]
cc @arthurnn

**Comment by repinel** [comment]
If you follow #7807 and eval `@new_record`, you will get a non-accurate value. By calling `new_record?` instead of, you would allow the record to sync its state with the transaction and return the expected `true`. It works on `4-2-stable` and `master`.

@rafaelfranca #7807 is already closed based on https://github.com/rails/rails/issues/8577#issuecomment-42496613 and maybe this one should be too.

**Comment by repinel** [comment]
I take it back. The state of the record should probably be fully restored. This PR needs some work since the code base has change considerably.

@iantropov Would you mind if I give it a shot?

**Comment by arthurnn** [comment]
Is this fixing this case too https://github.com/rails/rails/issues/20730 ?

**Pull request closed without merging**
