### PR TITLE
No new apps should be started with sprockets

### PR DESCRIPTION
**Pull request by dhh**
So remove the -a option and all generated code for sprockets. Sprockets will remain an option for existing applications, though.

### CODE REVIEW

**Comment by dhh** [comment]
Would be great if anyone is interested in carrying this to completion with whatever test updates it needs.

**Comment by andrewn617** [comment]
@dhh I have a few commits that I think fix the test issues. I can't push to this repo tho so I can't push on your branch.

https://github.com/rails/rails/compare/propshaft-only-for-new-apps...Shopify:rails:propshaft-only-for-new-apps

Feel free to cherry pick them, or if you'd rather I do it I can open a new from my fork.

**Comment by dhh** [comment]
Thanks @andrewn617. Just made a PR and merged in 👍

**Comment by andrewn617** [comment]
Looks like my change causes a lot of `assets_test.rb` to fail since it has sprockets behaviour tested, maybe some others too. I can try to take a look at that later.

**Comment by zzak** [comment]
:wave: I was spiking to get the build green over [here](https://github.com/rails/rails/compare/rm-sprockets), but wasn't going to ping until it was fixed.

**Pull request merged**
