### PR TITLE
insert newlines into code samples in Upgrading section of Asset Pipeline doc

### PR DESCRIPTION
**Pull request by alxndr**
I noticed some odd-looking code samples when reading over [the Asset Pipeline doc on RailsGuides](http://guides.rubyonrails.org/asset_pipeline.html); thought I'd try to fix it up.

### CODE REVIEW

**Comment by maclover7** [comment]
Please add `[ci skip]` to the commit message for documentation only changes in the future.

**Comment by alxndr** [comment]
Whoops, thanks @maclover7! (my first Rails pr...)

**Comment by maclover7** [comment]
No problem! If you'd like to, you can rebase or amend your commit and add `ci skip` so that way I can merge your PR faster! :)

**Comment by alxndr** [comment]
Shall do!

**Comment by maclover7** [comment]
:+1: Thank you for your contribution!

**Comment by maclover7** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by alxndr** [comment]
Glad to help!

**Pull request merged**
