### PR TITLE
Properly append preload / includes args on Merger (4-2-stable)

### PR DESCRIPTION
**Pull request by huoxito**
same as https://github.com/rails/rails/pull/20196 but for 4-2-stable

### CODE REVIEW

**Comment by arthurnn** [comment]
thoughts @rafaelfranca , as you merged the main PR.

**Comment by huoxito** [comment]
ops should have asked earlier forgot about this, @rafaelfranca any chance this could still get on 4.2.3?

**Comment by rafaelfranca** [comment]
I don't want to release a new RC for 4.2.3 since I was just releasing the final version. I'll release a new version on July 25, so maybe it is fine to wait?

**Comment by huoxito** [comment]
sure no worries thanks!

**Pull request merged**
