### PR TITLE
Fixes rubocop errors

### PR DESCRIPTION
**Pull request by ghousemohamed**
### Motivation / Background

I was running tests in Github Codespaces, and noticed that there were some rubocop errors. This PR just simply fixes them. 

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [ ] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by ghousemohamed** [comment]
@rafaelfranca Would it be a good idea to have pre-commit hooks so that these are avoided?

**Comment by zzak** [comment]
Were these not caught in CI?

**Comment by rafaelfranca** [comment]
Yes, they were got on CI. No pre-commit hooks. We don't want to slow down every commit for those. It is fine to push red builds from time to time. Thank you for offering.

**Comment by zzak** [comment]
Ahh ok, I found the failing build:
https://github.com/rails/rails/actions/runs/3943185221/jobs/6747728418

Still figuring out how actions and buildkite works :joy:

**Pull request merged**
