### PR TITLE
Fix nested tests in `insert_all_test.rb`

### PR DESCRIPTION
**Pull request by byroot**
The subtle mistake was introduced in https://github.com/rails/rails/pull/51826

### CODE REVIEW

**Comment by byroot** [comment]
I went over that other PR diff to see if I could spot another issue. I couldn't see any, but it's very hard to check, it's pretty easy to understand how this wasn't noticed.

**Comment by Earlopain** [comment]
There's a RuboCop rule `Lint/NestedMethodDefinition` for this and there are no other instances. Could be nice to enable, 12 current offenses after this, but a few are false positives (`class_methods`, `on_load`, `extending`, could be configured) and other are not so trivial to "fix", or don't need to.

Anyways, all that to say you didn't miss any.

**Comment by Earlopain** [comment]
I think it makes sense to have this [configure `AllowedMethods`](https://docs.rubocop.org/rubocop/1.69/cops_lint.html#allowedmethods_-__-_default_-lintnestedmethoddefinition) by default with `rubocop-rails`, will see about a PR for that there. Maybe some of those disables will just disappear in the future.

You also got some valid test failures now :wink:

**Comment by byroot** [comment]
Interestingly, it doesn't complain about cases such as this one: https://github.com/rails/rails/blob/d3a689d0abf4ce1040c62cae62bde5af88ca4e9f/actionview/test/template/log_subscriber_test.rb#L51-L52

Ultimately, if it didn't complain about `local_var.something` I think it would be better. But I think this is good enough for now.

**Comment by Earlopain** [comment]
Those have been explicitly allowed since https://github.com/rubocop/rubocop/pull/12961. When you write `local_var.something`, you probably mean `def model.to_key() [1] end` for example? It's supposed to already ignore local variables but here it's a method. I think that should also be fine to ignore by RuboCop? Maybe? In this specific case there's hardly any difference.

**Comment by byroot** [comment]
> When you write `local_var.something`, you probably mean `def model.to_key() [1] end` for example?

Yes.

> but here it's a method.

Ah right. I'd think it shouldn't make any difference in practice. 

But I'm bad at ASTs and such, so I'm not a big rubocop contributor.

**Pull request merged**
