### PR TITLE
Fix has_one autosaving for CPK associations

### PR DESCRIPTION
**Pull request by gmcgibbon**
### Motivation / Background

This Pull Request has been created because autosaving `has_one` relations with composite primary keys is currently broken.

### Detail

This Pull Request changes the Active Record autosave method that saves `has_one` associations (`save_has_one_association`) to support CPK associations.

### Additional information

This applies to any model with a `has_one` association with query constraints of more than one column.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by eileencodes** [comment]
Can you take a look at the test failures?

**Comment by gmcgibbon** [comment]
The ID column no longer auto increments because we have multiple primary keys. The SQL generated for the `cpk_orders` table is `"CREATE TABLE `cpk_orders` (`shop_id` int, `id` int, `status` varchar(255), PRIMARY KEY (`shop_id`, `id`))"`. Do we assign IDs manually, or is there a different way around this?

**Review by nvasilevski — APPROVED** [review]
👍 

Thank you!

**Comment by eileencodes** [comment]
Ok tests are passing now but we have conflicts. Can you fix these and then I'll merge? Thanks!

**Comment by gmcgibbon** [comment]
Ah, it is caused by i18n. Seems like it will be fixed by https://github.com/ruby-i18n/i18n/pull/662. I think we can merge in the interim.

**Comment by eileencodes** [comment]
Thanks @gmcgibbon!

**Pull request merged**
