### PR TITLE
Updated MySQL documentation link to MySQL latest version 5.7 everywhe…

### PR DESCRIPTION
**Pull request by amitsuroliya**
…re [ci skip]

### CODE REVIEW

**Comment by arunagw** [comment]
Is MySQL 5.7 is Generally Available ? or it's in RC?

**Comment by amitsuroliya** [comment]
@arunagw can you please check this - http://dev.mysql.com/doc/relnotes/mysql/5.7/en/.

**Comment by arunagw** [comment]
@amitsuroliya I can still see on this page that latest Generally available release is 5.6 http://dev.mysql.com/downloads/mysql/

And 5.7 is a development release. May be going to come out in a while? Is all the links you changed are working fine?

**Comment by amitsuroliya** [comment]
@arunagw Yes, all links working fine. I already tested out that.

**Comment by arunagw** [comment]
I think we can wait till 5.7 gets in generally available. Because normally people will not have this in their machine until it's generally available.

**Pull request closed without merging**
