### PR TITLE
Remove RAILS_DEV_PATH constant from Ruby 1.8.7

### PR DESCRIPTION
**Pull request by claudiob**

### CODE REVIEW

**Comment by arthurnn** [comment]
As far as I can tell this is a internal constant, however not private. People could be using it, but they shouldnt. So I think it is safe to remove it on rails 5.
I hate the `../../../../..` tho, but I guess it is better to have it in the file we used instead of in a constant somewhere else.
Also, is that even correct? because on `app_generator.rb` we were 3 levels more deep.

**Comment by zzak** [comment]
https://github.com/search?q=RAILS_DEV_PATH&type=Code&utf8=✓

**Comment by rafaelfranca** [comment]
@zzak almost all the entries on that search are form the vendored railties gem, so I think we are fine on removing it.

**Comment by claudiob** [comment]
I’m sorry, I didn't think about these consequences :sweat: 
I’m closing this, since it’s not a big deal.

**Pull request closed without merging**
