### PR TITLE
[ci skip] fix typo still -> will

### PR DESCRIPTION
**Pull request by thegcat**
I think the typo was previously miscorrected. Or it should read "This still causeS…".

### CODE REVIEW

**Comment by seuros** [comment]
i think 'this still causes' is the correct form

**Comment by spastorino** [comment]
`still causes` :+1: please fix the commit and I will merge

**Comment by arthurnn** [comment]
also this change code itself, so it should not have `[skip ci]`

**Comment by thegcat** [comment]
@spastorino it took me some time but I think I now understand what the warning means and why "still causes" is correct. If this bugs me too much I'll submit another patch to improve the wording, but for the moment I have updated my pull request.

Thanks!

**Pull request merged**
