### PR TITLE
Add render_if method

### PR DESCRIPTION
**Pull request by OmkarPatil2510**
### Summary

Add render_if method in PartialRenderer class. This method renders partial if condition is true else returns nil.
### Usage

<%= render_if user.admin?, 'admin_links',  admin: user %>

### CODE REVIEW

**Comment by sgrif** [comment]
Thank you for the pull request, and for trying to add this feature and improve the framework. Given how easy this is to do without the method, I don't think this is something we'd like to add to Rails proper at this time. Maybe consider making it a separate gem?

**Comment by EdDeAlmeidaJr** [comment]
Sorry, @sgrif, but I disagree. This would make it possible to shorten code eliminating some IFs. I respect your decision, but this could be really useful. I hope @OmkarPatil2510 will really make it a gem.

**Comment by gregmolnar** [comment]
@EdDeAlmeidaJr it wouldn't eliminate any if statement, just would execute them somewhere else.

**Comment by EdDeAlmeidaJr** [comment]
Okay, @gregmolnar. Thanks for clarifying this point.

**Comment by jakehockey10** [comment]
@gregmolnar , I've always written my render statements that were conditional with the `if ...` after the render call as you have it in your second example above.  I think that with the whole line in view, it reads very well.  In contrast, the suggested change here has the question being asked first, which does read as well with the pause in the middle of the statement (i.e. "render what I'm about to tell you about if [...]" vs. "render this thing if [...]").

One thing that I've always thought about though, is this: despite it reading better (for me), having the conditional hanging off the end of the statement always seemed like I was breaking some sort of "best practice."

General question: What is ruby / ruby on rails' stance on these types of conditionals?  Is it the ruby on rails way to tack on the conditional at the end of the statement more so than creating a conditional block of code between `if` and `end`?

**Comment by gregmolnar** [comment]
@jakehockey10 I think since ruby allows you to have a one liner condition with this syntax, it is ok to put the conditional at the end of the line.

**Comment by jakehockey10** [comment]
Yea, I agree with that.  I really think it is a useful syntax for sure.  Thanks :)

**Pull request closed without merging**
