### PR TITLE
Allow specify actionpack rack version via env var

### PR DESCRIPTION
**Pull request by zzak**
This should be a no-op until rails/buildkite-config#32 is merged

### CODE REVIEW

**Comment by skipkayhil** [comment]
I think we should be controlling the tested version in the Gemfile, something like this:
https://github.com/rails/rails/blob/5a16eadbc31b8d7ab0f1fecb9aee581fc1d97327/Gemfile#L6-L10

**Comment by zzak** [comment]
@skipkayhil How does that work for a gem dependency like actionpack? Since it's a self-contained gem that can be installed independently?

I'm happy to make adjustments, now that I know how this thing works but wasn't sure the best bundler setup (it's been a while).

**Comment by skipkayhil** [comment]
> In that case, should `actionpack.gemspec` be `">= 2.2.4, < 4"` so that we can test both?

Yeah that will be necessary to allow 3.x.

Then the Gemfile could have something like:
```Gemfile
if ENV["RACK"] == "3"
  gem "rack", ">= 3"
else
  gem "rack", "< 3"
end
```

**Comment by zzak** [comment]
> I suppose a potential downside to this approach would be apps running off main could pull in Rack 3 before we're actually ready for it 🤔 maybe the gemspec conditional is actually better?

This is exactly what I was trying to avoid, thank you for coming to that same conclusion :joy:

**Review by rafaelfranca — CHANGES_REQUESTED** [review]
We should not be doing this in the gemspec. We should be doing in the Gemfile. The gemspec should be static.

**Comment by zzak** [comment]
@rafaelfranca Thanks for your reply! That was an alternative that I considered, but want to avoid the situation we discussed above where fresh installs will default to Rack 3. Is that something we should be concerned with?

For example,

```
# gemspec
gem "rack", "> 2.2.4", "< 4"
```

```
# Gemfile
gem "rack", ENV["RACK"]
```

```
RACK="~> 2" bundle install
# this should install rack 2.x
```

```
RACK="~> 3" bundle install
# this should install rack 3.x
```

But, when someone tries to install gem directly, without `gem "rack"` in their Gemfile:

```
gem install actionpack
# Should install Rack 3, maybe unexpected
```

If they already have rack in their Gemfile.lock, I'm not sure the behavior, maybe it stays the same?

The point I'm trying to avoid is unexpectedly bump to Rack version which could have other side-effects.

Maybe because this is only going to be in main, and next Rails version, I shouldn't worry?

**Comment by zzak** [comment]
I've opened #47133 as an alternative which takes the suggested path above.

**Pull request closed without merging**
