### PR TITLE
Add reload! as a IRB::HelperMethod so it can be combined with other calls in a single statement. Fixes rails/rails#52982

### PR DESCRIPTION
**Pull request by pbhogan**
It is useful to iterate and test in the console by reloading and executing something in a single line command. Something like:

reload!; Post.find(123).test_a_thing

This makes it easy to quickly switch to the console, hit up and enter to re-execute after a code change.

This restores functionality that used to work until a few months ago.

### CODE REVIEW

**Comment by jeduardo824** [comment]
I think one of the tests breaking is related to this change. @pbhogan could you take a look at it?

**Comment by zzak** [comment]
Tests are failing for unrelated reasons.

I've confirmed the reload command is broken in 7.2 when used like that, but works fine in 7.1.
@stanhu Do you mind taking a look at this? :bow:

Would be good to add a test so it doesn't happen again.

**Comment by stanhu** [comment]
@zzak Did you mean to ping @st0012? 😄

**Comment by st0012** [comment]
Sorry for the delay in response. `reload!; Post.find(123).test_a_thing` feels like a result that an IRB implementation detail unexpectedly (from the maintainers' perspective) becoming a feature.
So I'm in support of restoring the behaviour and sorry for breaking it in the first place. That said, I don't think it makes sense to have it both a command and a helper method. I think the command should be removed since this PR has been merged.

**Pull request merged**
