### PR TITLE
reestablish current environment connection after creating all databases

### LINKED ISSUE #24813: `rails db:drop:all db:create:all db:migrate` w/ postgresql adapter runs db:migrate for production database
### Steps to reproduce

$ rails new --edge test_app -d postgresql
$ cd test_app
$ bundle exec rails db:drop:all db:create:all db:migrate ; echo '\d+' | rails dbconsole

> No relations found.
### Expected behavior

development DB is migrated
### Actual behavior

production DB is migrated

With sqlite3 adapter rails correctly migrates development DB.

### PR DESCRIPTION
**Pull request by y-yagi**
### Summary

Using `db:create:all` with `db:drop:all`, connection pool is last to have
information of the processing was carried out environment is held,
it may not match the environment for now processing.
In case of default `databases.yml`, it is probably left connection pool for
production environment.

Therefore, instead of reusing the connection pool, it fixes to perform reestablish
for current environment.

Fixes #24813

### CODE REVIEW

**Comment by matthewd** [comment]
Isn't that what this code was already intending to do? Can you add a test that shows the problem?

r? @arthurnn

**Comment by y-yagi** [comment]
> Isn't that what this code was already intending to do?

No. Management of connection pool does not have a care for the environment.
Therefore, because the same specification name in a different environment is used, it can not be used as a specification name. 

> Can you add a test that shows the problem? 

Sure! 
We already have a test for confirmation. 
https://github.com/rails/rails/blob/master/railties/test/application/test_runner_test.rb#L513..L524 

However, this test pass in SQLite, but it does not pass in MySQL and PostgresSQL.  Because MySQL and PostgreSQL are esatablish of connection at the time of drop.   https://github.com/rails/rails/blob/master/activerecord/lib/active_record/tasks/mysql_database_tasks.rb#L39 
https://github.com/rails/rails/blob/master/activerecord/lib/active_record/tasks/postgresql_database_tasks.rb#L28 

In this case, I think good to run the same test in the MySQL and PostgresSQL. 
What may be added to the set to use MySQL and PostgreSQL in railties's test?

**Comment by rafaelfranca** [comment]
I think you can change the gemfile and config/database.yml from the generated app, or you can set `DATABASE_URL` environment variable.

**Comment by y-yagi** [comment]
Thanks! It worked as expected after changing the `config/database.yml`.  I added the tests.

**Comment by ojab** [comment]
ping?

**Comment by arthurnn** [comment]
> In case of default databases.yml, it is probably left connection pool for
production environment.

What do you mean?
How could that be possible?

**Comment by kamipo** [comment]
Since #32274, this test cases are no longer failed.

**Pull request closed without merging**
