### PR TITLE
[ci skip] Remove `,`

### PR DESCRIPTION
**Pull request by yui-knk**

### CODE REVIEW

**Comment by vipulnsward** [comment]
@yui-knk I think you can make such changes directly on docrails. Do you have commit bit to https://github.com/rails/docrails ? If not, someone from rails team can add you.

**Comment by yui-knk** [comment]
@vipulnsward Thanks I do not have commit right to Rails (rails/rails and rails/docrails). I am not familiar with rails/docrails, is [it](http://weblog.rubyonrails.org/2013/6/14/docrails-back-to-the-roots/) a best document how rails core team use rails/docrails ?

**Comment by yui-knk** [comment]
@vipulnsward  Can you add me a commit bit to rails/docrails ?

**Comment by vipulnsward** [comment]
cc @rafaelfranca @fxn

**Comment by yui-knk** [comment]
@vipulnsward @rafaelfranca  Thanks!

**Pull request merged**
