### PR TITLE
Added `_scope_prefix` and `_scope_suffix` options for `enum`.

### PR DESCRIPTION
**Pull request by huacnlee**
Use for avoid the `scope` name conflicts with Ruby syntax, when using the dangerous keywords like `private / public / protected` as the enum value.

For fix issue #34129

### CODE REVIEW

**Comment by gregmolnar** [comment]
@huacnlee Did you see this comment on the linked issue? https://github.com/rails/rails/issues/34129#issuecomment-428068478

**Comment by huacnlee** [comment]
@greenbigfrog No, that can't solve my problem.

when I use `_prefix` option, it will change to:

```rb
repository.privacy_private!
repository.privacy_private?
repository.privacy_public!
repository.privacy_public?
# But I want
repository.private!
repository.private?
repository.public!
repository.public?
```

**Comment by greenbigfrog** [comment]
@huacnlee I think you meant to mention @gregmolnar

**Comment by rafaelfranca** [comment]
Thank you for the pull request but we prefer to not complicate `enum` with more options.

If you want:

```
repository.private!
repository.private?
repository.public!
repository.public?
```

You can define those methods yourself in your model.

**Pull request closed without merging**
