### PR TITLE
Add full set of MySQL CLI options to support SSL authentication when using db:structure dump and load

### PR DESCRIPTION
**Pull request by drcapulet**

### CODE REVIEW

**Comment by strzalek** [comment]
LGTM :+1:

**Comment by rafaelfranca** [comment]
Could you add a CHANGELOG entry?

**Comment by jkingdon** [comment]
Looks about right, similar to what we do in https://github.com/rails/rails/blob/master/railties/lib/rails/commands/dbconsole.rb#L59 (but then again I'm biased because "needfeed authored on Sep 10, 2012" was me).

**Comment by drcapulet** [comment]
Updated @rafaelfranca, thanks!

**Pull request merged**
