### PR TITLE
url -> URL in Action Cable guide [ci skip]

### PR DESCRIPTION
**Pull request by sharang-d**
Refer https://github.com/rails/rails/pull/35579.

### CODE REVIEW

**Comment by kamipo** [comment]
What is the motivation for this change?
Here is not only place using url and this looks a cosmetic change.

**Comment by sharang-d** [comment]
> What is the motivation for this change?

`URL` is an abbreviation so having it in all caps is the right way of writing it according to me.

> Here is not only place using url

From what I can see URL is the way most docs are written in the project.

The version with lowercase 'url' is used in code:
Monosnap 2019-04-01 12-19-45

The version with uppercase 'URL' is used in docs(plain English):
Monosnap 2019-04-01 12-20-36

I'd say that if there ARE some places in the docs(guides/comments/not-code) which are using the lower case version then those should be changed as well.

**Comment by fxn** [comment]
Have not grepped the project, but "URL" is definitely what we want to have in the code base.

If there are more occurrences, though, would be nice to have them in one PR as long as it is not a monster patch.

**Comment by sharang-d** [comment]
@fxn, I agree URL should be all caps when appropriate.

I found a lot of occurrences. Take a look at this: https://github.com/rails/rails/commit/cbd44583030703ae9018e77dab0fdc5359cfb597.
I stopped making changes after that as there were too many and still had many more to go. Would it be ok if me/someone else does that separately from this PR and treat this as only a follow up PR to the Action Cable commit?

**Comment by fxn** [comment]
@sharang-d thanks.

To avoid a monster patch, we could group say 2 or 3 Rails components in one PR, and do a few PRs to cover the code base. Please /cc me if you'd like to do that.

**Comment by sharang-d** [comment]
Yes, I'd like to do that. I'll cc you in the PR @fxn.

**Comment by kamipo** [comment]
> What is the motivation for this change?

I agree with this change itself is not a cosmetic change. My point is similar with https://github.com/rails/rails/pull/34966#issuecomment-455335287, most changes of you guys are follow-up of other changes, it makes me feel change for change's sake, it is why asking you for a more detailed explanation.

Basically I'd not prefer replacing a word one by one, we could find all words by `git grep` easily (e.g. #35552, I've found all replacing list by `git grep`).

**Pull request merged**
