### PR TITLE
Remove `BackburnerAdapter`

### PR DESCRIPTION
**Pull request by dixpac**
`ActiveJob::QueueAdapters::BackburnerAdapter` is moved from Rails into the `backburner` gem [and it will be released with the new version](https://github.com/nesquena/backburner/pull/180#issuecomment-2374561639).

Associated with #52929

### CODE REVIEW

**Comment by guilleiguaran** [comment]
@dixpac please let us know when a new version of the gem is published so we can merge this.

P.D: Please remove the trailing space in the changelog entry (see buildkite failure)

**Comment by Earlopain** [comment]
This should be deprecated instead. See https://github.com/rails/rails/pull/52990 and https://github.com/rails/rails/pull/53058

**Comment by dixpac** [comment]
Alright, I will convert to deprecation

**Comment by dixpac** [comment]
Closed in favour of https://github.com/rails/rails/pull/53334

**Pull request closed without merging**
