### PR TITLE
Change session host to  application default url options host

### PR DESCRIPTION
**Pull request by DerekCrosson**
### Summary

In the rails console app `sess.host!` was equal to `"www.example.com"`. When making a request like `app.get '/'` in the console after `Rails.application.routes.default_url_options[:host]` was set a HTTP `403` response was returned. This fix makes `sess.host!` equal to `Rails.application.routes.default_url_options[:host]` if it is set or default to `www.example.com`, now the request should return a HTTP `200` status with the correct application URL.

### Other Information
See details in this issue: https://github.com/rails/rails/issues/43357

Screenshot 2021-10-03 at 03 20 51

### CODE REVIEW

**Comment by DerekCrosson** [comment]
I see that the same tests are failing in https://buildkite.com/rails/rails/builds/81495 so I don't think the failures have anything to do with the change I made

**Comment by ceritium** [comment]
Hi @DerekCrosson, you are right, there are some tests failing currently on master. 

Apart from that, would you consider adding a test covering your change? I think that `railties/test/application/console_test.rb` is a good candidate. Maybe you can copy `test_app_can_access_path_helper_method` and test the url helper with and without `default_url_options[:host]`.

**Comment by DerekCrosson** [comment]
> Hi @DerekCrosson, you are right, there are some tests failing currently on master.
> 
> Apart from that, would you consider adding a test covering your change? I think that `railties/test/application/console_test.rb` is a good candidate. Maybe you can copy `test_app_can_access_path_helper_method` and test the url helper with and without `default_url_options[:host]`.

Sure thing, I can get to it in a couple of hours 🙂

**Review by ceritium — APPROVED** [review]
It looks good to me. Maybe you would like to squash the commits to keep the history clean.

**Pull request closed without merging**
