### PR TITLE
Adds a code of conduct

### PR DESCRIPTION
**Pull request by CoralineAda**
An easy way to begin addressing the problem of inclusivity is to be overt in our
openness, welcoming all people to contribute, and pledging in return to
value them as human beings and to foster an atmosphere of kindness,
cooperation, and understanding.

A code of conduct is  one way to express these values. It lets us pledge
our respect and appreciation for contributors and participants to the
project.

### CODE REVIEW

**Comment by gtcarlos** [comment]
:+1:

**Comment by nslater** [comment]
:+1:

**Comment by johnmarc** [comment]
:+1:

**Comment by aliciasedlock** [comment]
:+1:

**Comment by danny-sullivan** [comment]
:+1:

**Comment by pwnela** [comment]
:+1:

**Comment by einarj** [comment]
:+1:

**Comment by jordanekay** [comment]
:+1:

**Comment by LindseyB** [comment]
:+1:

**Comment by vipulnsward** [comment]
Should be a great addition, with the trolling we see frequently.

**Comment by rafaelfranca** [comment]
Hey! I'm positive to add a code of conduct, but :+1: comments doesn't help. We will review and apply it, but please, don't add more :+1: comments.

**Comment by rafaelfranca** [comment]
The text looks good to me. Let me see what the others core members thinks about it.

**Comment by jah2488** [comment]
:+1:

**Comment by fis-spencer1248** [comment]
:+1:

**Comment by niklas** [comment]
:+1:

**Comment by qrush** [comment]
I'd just like to say we added a CoC for rubygems.org recently:

https://github.com/rubygems/rubygems.org/blob/master/CONDUCT.md

That is directly based off the Contributor Covenant. My only feedback is that it's nice to have a private, direct way of reporting incidents. We are doing that by an email address, but other ways (a form?) might be nice too.

:+1: :100:

**Comment by tenderlove** [comment]
LGTM, though maybe we should add a part about comments that only consist of :+1:s. :wink:

**Comment by rafaelfranca** [comment]
@qrush good idea about the direct way of reporting incidents.

**Comment by tenderlove** [comment]
@rafaelfranca @qrush agree about adding an email. I volunteer to be added. :)

**Comment by miah** [comment]
:+1:

**Comment by meltheadorable** [comment]
Code of Conduct is a great move, and I support it 100%. I'm wondering if it should be mentioned in CONTRIBUTING and/or in the contributor guides on the website and/or in the README as well, to make sure those expectations are visible to people who want to contribute.

**Comment by juanplopes** [comment]
@rafaelfranca I'm sure when mra trolls find out about this, the :+1: comments will be the last of your problems. :)

**Comment by GeekOnCoffee** [comment]
I want to second @meltheadorable's suggestion of adding it to the contributors guides

**Comment by timendez** [comment]
:+1:

**Comment by rafaelfranca** [comment]
@meltheadorable @GeekOnCoffee yeah, as soon we merge this it should become first class citizen in our documentation. Website, guides and this repository should make explicit that there is a code of conduct.

**Comment by CoralineAda** [comment]
Yep, that's the right way to do it Rafael!

**Comment by maclover7** [comment]
@CoralineAda @rafaelfranca Assuming we want this same code of conduct to apply to Rails' many sub-projects (e.g. Turbolinks, Sprockets, etc.)? Should I open PRs to add a line to the READMEs that link back to this main COC?

**Comment by GeekOnCoffee** [comment]
@maclover7 probably wait until it's merged, keep the discussion in one place.

**Comment by maclover7** [comment]
@GeekOnCoffee Yep, I mean once the COC is "adopted" / merged in -- want to make sure same rules apply

**Comment by viniciushana** [comment]
:+1:

**Comment by ryandotsmith** [comment]
LGTM

**Comment by jonatack** [comment]
Just a thought. It might be good to write this in a way that includes, understands and tolerates the many cultures and countries out there in the world which have different values and meaning attached to various words.

For instance, the meaning of "sexualized language", and when it is okay and not okay should be clear (and I'm not sure that it can be in all-encompassing document like this). Otherwise, it could become a heavy-handed, intolerant policy rather than a reassuring one. The way this is currently written, for example, certain swear words at RailsConf presentations would have drastic consequences.

Of course, it depends how this is applied: strictly, or as a general guideline. And that choice should perhaps be explicit.

Cheers.

**Comment by krainboltgreene** [comment]
I can't think of any swear words that would be allowed at RailsConf that would be in violation of the coc.

Unless you're talking about slurs or sexualized language, in which case no great loss.

**Comment by pixeltrix** [comment]
@jonatack FYI - the Rails team are not responsible for RailsConf which is a [Ruby Central][1] production and they have their own [code of conduct][2].

[1]: http://rubycentral.org
[2]: http://www.railsconf.com/policies#policies

**Comment by meltheadorable** [comment]
@pixeltrix Yep, I was just typing that out. RailsConf has its own code of conduct. The contributor covenant is really optimized for online project spaces, not for events/gatherings.

**Comment by dominic** [comment]
:+1:

**Comment by jonatack** [comment]
@pixeltrix @meltheadorable Agreed. Yet the way it is written ("public spaces"), it appears to encompass events/gatherings, and this code of conduct entails different consequences than those of the RailsConf one. Anyway, I expressed my concerns. Back to coding ;)

**Comment by leobalter** [comment]
> I'm wondering if it should be mentioned in CONTRIBUTING and/or in the contributor guides on the website and/or in the README as well, to make sure those expectations are visible to people who want to contribute.

++ to add a link on all of these, including one at the top screen on the home site.

Also, the draft includes both *ethnicity* and *nationality*. IMHO, I believe the second might be redundant and I would drop nationality, only if this is not a harm the inclusiveness, which is the main goal.

Regarding the inclusiveness, I believe it's good to add a "technology choices" on this list, as in http://confcodeofconduct.com/, this might prevent anything like "win vs *nix", "vim vs emacs", or even trollings based on languages and frameworks.

This might validate my final emoji. Thank you, @CoralineAda!

:+1:

**Comment by CoralineAda** [comment]
Nationality does not necessarily equate to ethnicity.

Also, technology choices aren't really an area where underrepresented people are impacted. Language and framework discussions can be derailing but are, I believe, outside of the scope of a code of conduct.

**Comment by leobalter** [comment]
@CoralineAda:

I understand and agree the main goal is to allow the inclusiveness for underrepresented people. I just wanted to mention the tech choices topic in case it becomes a theme for a trolling and harassment. Although, this shouldn't prevent the project owners to adopt the CoC. As it is now, the document is already excellent.

**Comment by nusco** [comment]
:+1:

**Comment by trosborn** [comment]
RubyCentral has a CoC but considering what happened this year at RailsConf I don't think they know how to actually enforce it. Would it be possible to apply this to organizations representing the community as well as individuals? e.g., if RubyCentral drops the ball on enforcing their CoC again, we deny them the use of the Rails logo until they properly train their staff to deal with CoC violations?

**Comment by dhh** [comment]
💪

**Comment by strand** [comment]
:heart:

**Comment by Ovid** [comment]
As an aside, could it be called a Standard of Conduct instead? I get tired of juvenile "CoC" jokes at conferences.

**Comment by tzs** [comment]
That's a pretty good CoC, except for one big unclear section: "This code of conduct applies both within project spaces and in public spaces when an individual is representing the project or its community".

What does "representing the project or its community mean"? For example, suppose X has their resume on their website and lists there that they are a contributor to the project. Suppose also on their website they have copies of their erotic Harry Potter fan fiction, which contains sexualized language.

OK, or violation?

I think you'll save yourself a lot of drama in the future if you add a sentence clarifying this. Personally, I'd recommend saying that merely listing your contributions to or membership in the project as part of biographical information (such as a resume, a LinkedIn profile, a personal Facebook or Twitter or similar profile, etc.) is not representing the project, but if you want to go the other way and make all those count, fine. The important thing is to make it clear which it is.

**Comment by dhh** [comment]
That would not be representing the project in my definition of the term.
Representing the project would be speaking at a conference, hosting a user
group, managing a mailing list, mentoring students, or any such involvement
that's connected to the project.

If you want to write erotic Harry Potter fan fiction in addition to your
Rails contributions, knock yourself out.

It's all on a sliding scale, though. If you want to be a raging neo nazi
who's also chairing a sub-reddit on the topic of hate, well, then that
might be your hobby, but I don't think it's compatible with being in polite
company of Rails contributors.

Now, the world is rarely that black and white. Shades of grey will be
interpreted by the Rails core group, as the designated project maintainers,
in the spirit of this CoC.

**Comment by emilio2gb** [comment]
:-1:

**Comment by emilio2gb** [comment]
:-1:

**Comment by McFinigan** [comment]
👎

**Pull request merged**
