### PR TITLE
Add frozen to dangerous methods

### PR DESCRIPTION
**Pull request by dsusviela**
### Motivation / Background
Resolution of rails/rails#46247

This PR adds `frozen?` to the dangerous method list, right now adding an enum with `frozen` with a possible value may override the `frozen?` method silently, which can lead to errors or unexpected code.

### Detail

This Pull Request changes the dangerous method list to add the `frozen?` method.

### Additional information

I think this could use a refactor as the list of "unsafe" methods is now kinda arbitrary, and if we forget some, we have to keep on updating this manually which is less than ideal. Food for thought maybe?

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [ ] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] ~CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature.~ Minor bug fixes and documentation changes should not be included. 
* [x] CI is passing.

### CODE REVIEW

**Review by byroot — APPROVED** [review]
Please squash your commits into one. Other than that looks good to me.

**Comment by dsusviela** [comment]
@byroot Sorry for the ping, but can I do something for the ci?

**Comment by byroot** [comment]
It's all good. You just had very bad luck on that CI run.

**Comment by byroot** [comment]
Thanks!

**Comment by dsusviela** [comment]
my pleasure!

**Pull request merged**
