### PR TITLE
[ci skip] Deep indent is better than markdown code block style

### PR DESCRIPTION
**Pull request by yui-knk**

### CODE REVIEW

**Comment by edwardloveall** [comment]
Why is deep indent better? The code block fences can show the language but indent can't.

**Comment by sgrif** [comment]
Yeah, I see no reason not to use the code fence style

**Comment by yui-knk** [comment]
@sgrif @edwardloveall  I think many code example in CHANGELOG.md are not fenced with code block, so deep indent is better for keeping consistency.

**Comment by sgrif** [comment]
I don't think it matters.

**Comment by yui-knk** [comment]
OK thanks.

**Pull request closed without merging**
