### PR TITLE
add support for rubinius in gemfile template

### PR DESCRIPTION
**Pull request by stakach**

### CODE REVIEW

**Comment by rafaelfranca** [comment]
I don't think we should put something about rubinius in our default Gemfile right now. Our tests are not even passing with rubinus.

So if people chose to use rubinius I believe they know exactly what they have to include in their Gemfiles.

**Comment by rafaelfranca** [comment]
Oops, I didn't wanted to close it, sorry

**Comment by rafaelfranca** [comment]
cc @dhh

**Comment by dhh** [comment]
Agree. It doesn't seem proportional at the moment. When we aren't even passing tests, it seems a little early to make accommodations like this.

**Pull request closed without merging**
