### PR TITLE
extract ActionDispatch::IntegrationTest::Behavior

### PR DESCRIPTION
**Pull request by bronson**
Similar to 176fbfd6, this makes it possible for other test
frameworks to hook into Rails integration test facilities.

Also similar to d588bbd43 and 8e583b69e

### CODE REVIEW

**Comment by bronson** [comment]
Here is the rspec-rails pull request that would use this feature: https://github.com/rspec/rspec-rails/pull/1560

**Comment by rafaelfranca** [comment]
This looks good but tests are borken.

**Comment by bronson** [comment]
Interesting...  something about `@@app` vs. `ActiveSupport::Concern` on very recent rubies.  I'll look tomorrow.

**Comment by bronson** [comment]
Still not ready...  I need to figure out the interaction between class variables and AS::Concern.

**Comment by bronson** [comment]
@rafaelfranca, rebased against master and everything went green.  Magic!  Maybe some commit in the past week fixed it.

Anything more I can do on this patch?

**Comment by bronson** [comment]
Rebased, fixed conflict, green again.

**Pull request merged**
