### PR TITLE
Add test coverage for ActiveSupport::NumericWithFormat#to_formatted_s

### PR DESCRIPTION
**Pull request by maclover7**
related to #22822.

cc @schneems @rafaelfranca

### CODE REVIEW

**Comment by schneems** [comment]
I'm :+1:  on this test. Would it have failed before your previous PR or would it need to be tested somewhere else?

**Comment by maclover7** [comment]
Could be wrong, but I'm thinking it would have failed, because this is directly testing the `deprecated`-ness of the code. Happy to update if there's a better way to go about this. :-)

**Comment by schneems** [comment]
Got it, nothing was calling the method so the error saying the constant hadn't been defined would not have been raised. I was thinking this was a require time error but I guess it only happens when called.

**Comment by maclover7** [comment]
:+1: ready to merge then?

**Comment by senny** [comment]
@maclover7 thank you :yellow_heart:

**Comment by maclover7** [comment]
:+1:

**Pull request merged**
