### PR TITLE
Fix Rails 3-2-stable on Ruby 2.3.1

### PR DESCRIPTION
**Pull request by pixeltrix**
Opening a PR to discuss whether we want to merge this.

### CODE REVIEW

**Comment by arthurnn** [comment]
❤️  This will definitely be useful for use cc @tenderlove .

**Comment by shakycode** [comment]
In for this too. Still on 3-2 stable on a legacy project

**Review by rafaelfranca — COMMENTED** [review]
In my opinion this pass the wrong message that old versions will be supported forever. New are in Rails 5 now. 3.2 should not even be released anymore. But I know @tenderlove and @arthurnn are maintaining because they have interest of it, so it is their call.

**Comment by pixeltrix** [comment]
@rafaelfranca I have some sympathy for that but unfortunately BlueBox, the hosting company have told my client that their (and everyone else's) servers will be switched off come the end of the month so I don't have time to upgrade the application. Even if I did the site has been EOL'ed so it wouldn't be worth the investment - it just needs to keep running for another year until the replacement is ready.

**Comment by arthurnn** [comment]
cc @vmg

**Review by rafaelfranca — APPROVED** [review]
@pixeltrix if you need it and is willing to release a new version feel free to make the call.

**Comment by pjg** [comment]
Cool stuff! Thanks @pixeltrix!

**Pull request merged**
