### PR TITLE
Remove #select_one from Mysql2Adapter

### PR DESCRIPTION
**Pull request by bquorning**
This is a follow-up to #25487, where I tried to change Mysql2Adapter’s `#select_one` to work around [a subtle bug](https://github.com/rails/rails/pull/25487#discussion_r68246109) which I unfortunately cannot reliably reproduce. Reproducible or not, I think Mysql2Adapter’s existing `#select_one` implementation is pretty confusing (why does the connection need to know—before executing the query—how the result should be mapped?) and in this PR I will attempt to remove it completely.

Mysql2Adapter’s override of `#select_one` was introduced in #22803, to “Avoid instanciate `ActiveRecord::Result` and calling `ActiveRecord::Result#hash_rows` for the performance”.

The performance problem of calling `hash_rows` when you really only need the first element can perhaps be solved by adding a `ActiveRecord::Result#first` method, optimized for that use case.

`ActiveRecord::Result#last` was introduced back in 40ce68204808f9905413fe15843a7cc0f1c56988, but I’m not sure who uses it. I changed it works identical to the new `#first` method.

Considerations:
- Rails moved away from `Hash[a.zip(b)]` back in ba0568e46d890d57cfef2ea86745bdeb879fefa7 – do we need that optimization here, when it’s not inside a loop?
- `#hash_rows` freezes the column keys (introduced in 3aef5ce9b35a4659379201eb6bb1dba355a83ba4, 2068d300917ed95a82e7377ee77b397fc4084a61, da400fbb0ba6a130237d17cdd58c860be02294ad) for performance reasons. Again, `#first` and `#last` aren’t looping, so do we need to optimize for performance here?
- I considered checking for `defined?(@hash_rows) ? @hash_rows.first : …` but thought it a premature optimization. What do you think?

I’ve run `rake test_mysql2` with [test/config.yml’s `prepared_statements` set to both `true` and `false`](https://github.com/rails/rails/pull/25487#discussion_r68242837), and everything looks fine.

cc/ @kamipo

### CODE REVIEW

**Comment by kamipo** [comment]
https://github.com/rails/rails/pull/25487#discussion_r68246109
> Actually, it's a bug fix. But I cannot reliably reproduce the bug. Sometimes '#select_one` would return an array instead of a hash, but with this patch, I get a hash every time.

Could you share a reproduction script? It does not matter if can not reliably reproduced.
For example, https://github.com/brianmario/mysql2/issues/694 and https://github.com/brianmario/mysql2/pull/741 does not cause by only once.
I'd like to clarify the root cause.

Removing `select_one` is fine to me. Actually this `select_one` was implemented for removing outdated comments in #22803 and `select_one` is not performance hotspot in AR internal. I prefer less code.

**Comment by bquorning** [comment]
> Could you share a reproduction script? It does not matter if can not reliably reproduced.

I wish I could, but I've only seen the bug on our staging environment. All my efforts at replicating in development/test environment have been fruitless.

It resembles a threading issue (two threads sharing the `@connection` object, one of them changing `query_options[:as]` back to `:array` before the other thread does its DB call), but I’m using a single-threaded server (Unicorn) so that can’t be the case. Right?

**Comment by bquorning** [comment]
cc/ @rafaelfranca Would you please take a look at this PR?

**Comment by rafaelfranca** [comment]
This looks good to me.

**Comment by rafaelfranca** [comment]
Backported in 1e58ffd

**Comment by bf4** [comment]
ref https://github.com/rails/rails/pull/23461

**Pull request merged**
