### PR TITLE
Fix tests breakage in #17351

### PR DESCRIPTION
**Pull request by pwnall**
PR #17351 didn't have new tests, and broke existing tests.

This PR fixes the existing tests for me.

### CODE REVIEW

**Comment by pwnall** [comment]
The CI breakage in `guides` references the wrong commit. My commit SHA1 is 1c4679b063fff6d6b73b3cdc7cccc5f29057fd29. Perhaps `guides` uses master instead of the new commit?

**Comment by carlosantoniodasilva** [comment]
Sorry, I've just merged #21443 and committed the same fix for the tests on 8ce0fdb5c412a5083dff3ecb863e86c1853651d7 before seeing your PR, otherwise I'd have merged yours. Thanks for your contribution.

**Comment by pwnall** [comment]
As long as things are fixed, everything is good! Any chance of prodding the broken PR's author to actually write tests for it?

**Comment by carlosantoniodasilva** [comment]
We could/should yeah, but if you want to try and add a test, that'd be cool too :).

**Comment by pwnall** [comment]
Done in #21449 :)

**Pull request closed without merging**
