### PR TITLE
Make `ActiveRecord::Base` object to preparable for predicate builder

### PR DESCRIPTION
**Pull request by kamipo**
``` ruby
  # Before
  Post.where(author_id: author).to_a
  # => SELECT "posts".* FROM "posts" WHERE "posts"."author_id" = 1

  # After
  Post.where(author_id: author).to_a
  # => SELECT "posts".* FROM "posts" WHERE "posts"."author_id" = ?  [["author_id", 1]]
```

### CODE REVIEW

**Comment by matthewd** [comment]
This is continuing to exacerbate a hack, instead of pushing back against it.

Instead of killing off more handler classes, it seems we need to teach handlers how to interact with bind values.

**Comment by arthurnn** [comment]
@matthewd should we close this?

**Comment by kamipo** [comment]
I think that `value = value.id if value.is_a?(Base)` is preprocess. This preprocess is processed in array handler.
https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation/predicate_builder/array_handler.rb#L9

However, array handler's preprocess is insufficient and have a issue #26541.

I think that `ActiveRecord::Base`, `Class`, and `Array` should be processed like `Hash` for preparable.
https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation/predicate_builder.rb#L91-L95

Preparable predicate builder can be used in the building statement cache (actually #26612's predicate builder can be used in #26213).

**Comment by matthewd** [comment]
It feels like we should be able to unify some of these things. As @kamipo noted, the array handler already tries to implement some value-mapping itself... and does a bad (well, incomplete) job of it.

To me, it feels like the array predicate builder could be more "purely" leaning back on the main predicate builder to handle the array elements.

Concretely, I believe I'm arguing that the `case` inside `create_binds_for_hash` should be implemented on the predicate handler classes instead.

**Pull request closed without merging**
