### PR TITLE
Document that @rails/ujs is deprecated

### PR DESCRIPTION
**Pull request by dhh**
Recommended replacements: Turbo + Stimulus. Will want to add some standard library stimulus controllers to replicate confirm/disable_with – or perhaps even add the latter to Turbo? Either way, rails/ujs was a grab bag of stuff, it doesn't work well with Turbo because there's overlap, and we shouldn't be recommending it going forward.

But this is a soft deprecation. Lots of apps have used this all over. Not going to nag them to remove it. It'll just fade into the sunset.

### CODE REVIEW

**Comment by ParamagicDev** [comment]
@dhh will the `config.action_view.form_with_generates_remote_forms = true` continue to be maintained as part of Rails 7 or will this option eventually go away?

**Comment by leastbad** [comment]
@dhh please **don't** remove `config.action_view.form_with_generates_remote_forms = true`.

`rails-ujs` might be deprecated, but remote forms are alive and well in `mrujs`. UJS-the-concept is yet another tech innovation birthed in Rails but has left the nest. No need to burn the fields it grazes in.

**Comment by dhh** [comment]
Nothing will be removed in Rails 7, but mrujs should still implement its own approach to this long term. Not going to keep remnants of UJS around forever, long after it's been removed/spun out of the core framework.

**Comment by leastbad** [comment]
That's reasonable enough. Thanks for clarifying.

**Pull request merged**
