### PR TITLE
Add base image args to default Dockerfile

### PR DESCRIPTION
**Pull request by juliusrickert**
### Motivation / Background

This Pull Request has been created because the current default Dockerfile uses the default container registry, which is usually `docker.io`, which does not support IPv6. I took this opportunity to make the base image fully configurable and set `registry.docker.com`, which supports dual stack, as the default registry.

### Detail

This Pull Request changes the Dockerfile template to add `ARG` options for configuring the base image.
The repository and tag can be set individually (using `BASE_IMAGE_REPOSITORY` and `BASE_IMAGE_TAG`, respectively) or be completely overwritten (using `BASE_IMAGE`).

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Review by zzak — COMMENTED** [review]
Sounds good to me, can you please [squash your commits](https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#squashing-commits)?

/cc @dhh @rubys

**Comment by dhh** [comment]
Appreciate this, but I don't think it's worth the extra complexity. I'd be happy to see this documented in a guide, though. How to specialize and tailor the Dockerfile. But for now, we should not consider this file to be a black box. It's a seed file, intended for manual maintenance. Thus it needs to be as simple as we can make it to be approachable. Not cover all edge cases.

**Comment by juliusrickert** [comment]
I think your concerns are very valid, @dhh.

I'd still appreciate IPv6 support by default. Thus, I've opened #47888, which just sets the fully qualified reference name.

**Comment by rubys** [comment]
This change would fit in well with [dockerfile-rails](https://github.com/rubys/dockerfile-rails) where options are supported and expected.  If you are inclined to create a pull request, it would likely be merged.  Particularly if the default when no options are provided tracks closely to what Rails 7.1 produces.

**Pull request closed without merging**
