### PR TITLE
Fix 3-2-stable 1.8 compatibility.

### LINKED ISSUE #23248: Rails 3.2.22.1 actionpack-3.2.22.1/lib/action_view/template/resolver.rb:113 syntax error, unexpected ':', expecting kEND
This error comes up when I attempt to run: rails s
So, to troubleshoot, I created a brand new blank app. Yes, it starts up just fine. Next step was to create a controller and a view. So I added the hello_controller.rb with the index method. Yes, I did put the proper route in the routes file.
Now it generates the following error when I attempt to access that hello index method.
Is there something I need to change in my apps?
Thanks

programmer@dev01:~/programming/BloggerApp$ rails s -p 3002
=> Booting WEBrick
=> Rails 3.2.22.1 application starting in development on http://0.0.0.0:3002
=> Call with -d to detach
=> Ctrl-C to shutdown server
[2016-01-25 14:39:33] INFO  WEBrick 1.3.1
[2016-01-25 14:39:33] INFO  ruby 1.8.7 (2014-01-28) [x86_64-linux]
[2016-01-25 14:39:33] INFO  WEBrick::HTTPServer#start: pid=4931 port=3002
[2016-01-25 14:39:39] ERROR SyntaxError: /home/programmer/.rvm/gems/ruby-1.8.7-head@rails3/gems/actionpack-3.2.22.1/lib/action_view/template/resolver.rb:113: syntax error, unexpected ':', expecting kEND
...ternal_files, instance_reader: false, instance_writer: false
                              ^
/home/programmer/.rvm/gems/ruby-1.8.7-head@rails3/gems/actionpack-3.2.22.1/lib/action_view/template/resolver.rb:113: Can't assign to false
...files, instance_reader: false, instance_writer: false
                              ^
/home/programmer/.rvm/gems/ruby-1.8.7-head@rails3/gems/actionpack-3.2.22.1/lib/action_view/template/resolver.rb:113: syntax error, unexpected ':', expecting '='
...eader: false, instance_writer: false
                              ^
	/home/programmer/.rvm/gems/ruby-1.8.7-head@rails3/gems/actionpack-3.2.22.1/lib/action_view/railtie.rb:50
	/home/programmer/.rvm/gems/ruby-1.8.7-head@rails3/gems/activesupport-3.2.22.1/lib/active_support/lazy_load_hooks.rb:36:in `instance_eval'
	/home/programmer/.rvm/gems/ruby-1.8.7-head@rails3/gems/activesupport-3.2.22.1/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
	/home/programmer/.rvm/gems/ruby-1.8.7-head@rails3/gems/activesupport-3.2.22.1/lib/active_support/lazy_load_hooks.rb:43:in `run_load_hooks'
	/home/programmer/.rvm/gems/ruby-1.8.7-head@rails3/gems/activesupport-3.2.22.1/lib/active_support/lazy_load_hooks.rb:42:in `each'
	/home/programmer/.rvm/gems/ruby-1.8.7-head@rails3/gems/activesupport-3.2.22.1/lib/active_support/lazy_load_hooks.rb:42:in `run_load_hooks'
	/home/programmer/.rvm/gems/ruby-1.8.7-head@rails3/gems/actionpack-3.2.22.1/lib/action_view/base.rb:218
	/home/programmer/.rvm/gems/ruby-1.8.7-head@rails3/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:251:in `require'
	/home/programmer/.rvm/gems/ruby-1.8.7-head@rails3/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:251:in `require'
	/home/programmer/.rvm/gems/ruby-1.8.7-head@rails3/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:236:in `load_dependency'
	/home/programmer/.rvm/gems/ruby-1.8.7-head@rails3/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:251:in `require'
	/home/programmer/.rvm/gems/ruby-1.8.7-head@rails3/gems/actionpack-3.2.22.1/lib/abstract_controller/view_paths.rb:1
	/home/programmer/.rvm/gems/ruby-1.8.7-head@rails3/gems/actionpack-3.2.22.1/lib/abstract_controller/rendering.rb:35
	/home/programmer/.rvm/gems/ruby-1.8.7-head@rails3/gems/actionpack-3.2.22.1/lib/abstract_controller/layouts.rb:195
	/home/programmer/.rvm/gems/ruby-1.8.7-head@rails3/gems/actionpack-3.2.22.1/lib/action_controller/base.rb:183
	/home/programmer/.rvm/gems/ruby-1.8.7-head@rails3/gems/actionpack-3.2.22.1/lib/action_dispatch/middleware/static.rb:32:in `ext'
	/home/programmer/.rvm/gems/ruby-1.8.7-head@rails3/gems/actionpack-3.2.22.1/lib/action_dispatch/middleware/static.rb:16:in `match?'
	/home/programmer/.rvm/gems/ruby-1.8.7-head@rails3/gems/actionpack-3.2.22.1/lib/action_dispatch/middleware/static.rb:77:in `call'
	/home/programmer/.rvm/gems/ruby-1.8.7-head@rails3/gems/railties-3.2.22.1/lib/rails/engine.rb:484:in `call'
	/home/programmer/.rvm/gems/ruby-1.8.7-head@rails3/gems/railties-3.2.22.1/lib/rails/application.rb:231:in `call'
	/home/programmer/.rvm/gems/ruby-1.8.7-head@rails3/gems/rack-1.4.7/lib/rack/content_length.rb:14:in `call'
	/home/programmer/.rvm/gems/ruby-1.8.7-head@rails3/gems/railties-3.2.22.1/lib/rails/rack/log_tailer.rb:17:in `call'
	/home/programmer/.rvm/gems/ruby-1.8.7-head@rails3/gems/rack-1.4.7/lib/rack/handler/webrick.rb:59:in `service'
	/home/programmer/.rvm/rubies/ruby-1.8.7-head/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
	/home/programmer/.rvm/rubies/ruby-1.8.7-head/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
	/home/programmer/.rvm/rubies/ruby-1.8.7-head/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
	/home/programmer/.rvm/rubies/ruby-1.8.7-head/lib/ruby/1.8/webrick/server.rb:162:in `start'
	/home/programmer/.rvm/rubies/ruby-1.8.7-head/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
	/home/programmer/.rvm/rubies/ruby-1.8.7-head/lib/ruby/1.8/webrick/server.rb:95:in `start'
	/home/programmer/.rvm/rubies/ruby-1.8.7-head/lib/ruby/1.8/webrick/server.rb:92:in `each'
	/home/programmer/.rvm/rubies/ruby-1.8.7-head/lib/ruby/1.8/webrick/server.rb:92:in `start'
	/home/programmer/.rvm/rubies/ruby-1.8.7-head/lib/ruby/1.8/webrick/server.rb:23:in `start'
	/home/programmer/.rvm/rubies/ruby-1.8.7-head/lib/ruby/1.8/webrick/server.rb:82:in `start'
	/home/programmer/.rvm/gems/ruby-1.8.7-head@rails3/gems/rack-1.4.7/lib/rack/handler/webrick.rb:13:in `run'
	/home/programmer/.rvm/gems/ruby-1.8.7-head@rails3/gems/rack-1.4.7/lib/rack/server.rb:268:in `start'
	/home/programmer/.rvm/gems/ruby-1.8.7-head@rails3/gems/railties-3.2.22.1/lib/rails/commands/server.rb:70:in `start'
	/home/programmer/.rvm/gems/ruby-1.8.7-head@rails3/gems/railties-3.2.22.1/lib/rails/commands.rb:55
	/home/programmer/.rvm/gems/ruby-1.8.7-head@rails3/gems/railties-3.2.22.1/lib/rails/commands.rb:50:in `tap'
	/home/programmer/.rvm/gems/ruby-1.8.7-head@rails3/gems/railties-3.2.22.1/lib/rails/commands.rb:50
	script/rails:6:in `require'
	script/rails:6

### PR DESCRIPTION
**Pull request by simi**
fixes #23248

/cc @tenderlove

### CODE REVIEW

**Comment by maclover7** [comment]
Thanks so much for this @simi!!

**Comment by marutosi** [comment]
Please release 3.2.22.2.
http://www.redmine.org/builds/logs/build_2.6-stable_postgresql_ruby-1.8.7-p358_110.html

**Comment by maclover7** [comment]
@marutosi - There are other bug fixes that need to be merged into 4-1-stable, 4-2-stable, and master, before that can happen.

**Comment by arthurnn** [comment]
thanks all

**Comment by nateberkopec** [comment]
:clap: cheers @simi

**Comment by mislav** [comment]
Thanks @simi and @tenderlove for the quick turnaround! :clap:

**Pull request merged**
