### PR TITLE
Use optimized subclass of StringInquirer for Rails.env

### LINKED ISSUE #37803: StringInquirer for Rails.env is unnecessarily heavy
### Steps to reproduce
Call `Rails.env.development?` from any code.

### Expected behavior
It should not have to dispatch through `method_missing`.

### Actual behavior
It dispatches through `method_missing`

### System configuration
**Rails version**: 5+

**Ruby version**: all

In order to allow using `Rails.env.development?` instead of `Rails.env == 'development'`, the env string is currently forced into a StringInquirer instance:

https://github.com/rails/rails/blob/1ccc407e9dc95bda4d404c192bbb9ce2b8bb7424/railties/lib/rails.rb#L67-L81

StringInquirer in turn uses `method_missing` to turn the `development?` call into `self == "development"` by cropping off the `?`.

https://github.com/rails/rails/blob/1ccc407e9dc95bda4d404c192bbb9ce2b8bb7424/activesupport/lib/active_support/string_inquirer.rb

This is unnecessarily heavy:

* Dispatching through method_missing is generally more expensive than calling a simple method.
* A new string object must be constructed for each call.

This is also doing work for each call that is unnecessary; the content of the string does not change over time, so performing the check once would be sufficient.

In the application I was benchmarking, Redmine, this call was made at least once per request, and multiple times in some cases. I have heard anecdotal evidence from others that their apps may use `production?` and `test?` heavily to allow minor behavioral diffferences in those environments.

I believe this env string should instead use a subclass of String that defines proper methods for at least the standard three environments (development, test, and production), and if possible it should define such methods for all configurable environments in the boot configs.

```
class EnvironmentString < StringInquirer
  def initialize(env)
    @development = env == 'development'
    @test = env == 'test'
    @production = env == 'production'
  end

  def development?; @development; end
  def test?; @test; end
  def production?; @production; end
end
```

A more aggressive optimization would define these as singleton methods specific to the incoming env string; this would only be done once at env-setting time and therefore the singleton would not be any more significant in memory than having a specific named class for this purpose.

### PR DESCRIPTION
**Pull request by headius**
This adds a StringInquirer subclass EnvironmentInquirer that predefines the three default environments as query methods, in order to avoid dispatching through `method_missing` for every call to those methods. The original StringInquirer was not modified due to the side effects of having new env-related methods on it. This new class was not implemented using lazy method definition to avoid the open-ended possibility of defining a new method for all query calls. The three default environments should cover a high percentage of real-world uses, and users with custom environments could add their own to this class.

Fixes #37803.

This is a follow-up to #37808 which seemed to be missing a require, causing CI to fail once it was merged (though I thought that PR was green at some point. 🤔

### CODE REVIEW

**Comment by headius** [comment]
Ok I'm stumped. I added a require of environment_inquirer right next to the sole require of string_inquirer and for some reason the class still isn't visible to some test runs.

**Comment by eugeneius** [comment]
There's an autoload for `StringInquirer`:

https://github.com/rails/rails/blob/9a5bc246d75595ae320a72c63a1df44ce6f63717/activesupport/lib/active_support.rb#L72

Adding one for `EnvironmentInquirer` should fix the problem.

**Comment by headius** [comment]
@eugeneius Aha, I should have known! I did not expect such a small utility class would be autoload.

**Comment by headius** [comment]
Is it preferred to squash minor changes to what should be a single-commit patch, or is this something Rails Core would prefer to decide at merge time?

**Comment by eugeneius** [comment]
Please squash / amend the existing commit 👍

**Comment by rafaelfranca** [comment]
@headius do you plan to make more changes? This looks good to me.

**Comment by headius** [comment]
Nope, I was just waiting for CI. Have at it!

**Pull request merged**
