### PR TITLE
Added warning on coding engine controllers

### PR DESCRIPTION
**Pull request by claudix**
@fxn , I've updated the Rails guide on Engines as discussed in #22098. Hope everything is OK!

### CODE REVIEW

**Comment by pixeltrix** [comment]
@claudix the problem is that Ruby finds the `ApplicationController` constant via the `Object` ancestor and doesn't trigger `const_missing` which is how Rails implements autoloading - I don't think the warning you've written explains this properly since it places the blame on how Rails loads the controllers which isn't the correct reason. I suggest something along these lines may be better:

    NOTE: Because of the way that Ruby does constant lookup you may run into a situation
    where your engine controller is inheriting from the main application controller and
    not your engine's application controller. Ruby will look in the ancestor chain for
    constants and every class has `Object` as an ancestor, meaning that if the global
    `ApplicationController` is loaded Ruby will return that and not call `const_missing`
    and trigger the Rails autoloading mechanism. The best way to prevent this from
    happening is to use `require_dependency` to ensure that the engine's application
    controller is loaded. For example:
    
    ``` ruby
    # app/controllers/blorgh/articles_controller.rb:
    require_dependency "blorgh/application_controller"
    
    module Blorgh
      class ArticlesController < ApplicationController
    	...
      end
    end
    ```
    
    WARNING: Don't use `require` because it will break the automatic reloading of classes
    in the development environment - using `require_dependency` ensures that classes are
    loaded and unloaded in the correct manner.

**Comment by Michaelbrich** [comment]
This is so true and I will create dependency injection by withholding methods of 
Supplement 
Michael 

-----Original Message-----

**Comment by claudix** [comment]
@pixeltrix, thank you very much for your reply. I'm not an expert on how Ruby internals work and I was actually looking for a better explanation of what I faced with. If you don't mind I'll take your words as-is to update this branch.

**Comment by fxn** [comment]
I am on my mobile, what about a shorter warning that links to this gotcha in the autoloading guide?

**Comment by fxn** [comment]
The patch looks good to me. Only one remark:

> Ruby will look in the ancestor chain for constants and every class has `Object` as an ancestor, meaning that if the global `ApplicationController` is loaded Ruby will return that and not call `const_missing` and trigger the Rails autoloading mechanism.

On one hand it is not the case that every class has `Object` as an ancestor, because a Ruby class may inherit from `BasicObject` without inheriting from `Object`. And some do, indeed. The autoloading guide [has a section](http://guides.rubyonrails.org/autoloading_and_reloading_constants.html#autoloading-in-basicobject) about it.

Also, in that spot `ApplicationController` is not looked up in the ancestor chain of the engine controller, precisely at that point the ancestor chain is being defined. Rather, the nesting to look up that constant is `[Blorgh]`. Since `ApplicationController` is a relative constant, the module is checked, it does not exist there (hypothesis), and Ruby then tries `Object` by hand even if it does not belong to its ancestor chain because [modules have that special rule](http://guides.rubyonrails.org/autoloading_and_reloading_constants.html#resolution-algorithms).

You can test this for example this way:

```ruby
class BasicObject
  class D < Object
  end
end
```

In that example `BasicObject::D` is a regular class, it does *not* inherit from `BasicObject`, but Ruby raises "uninitialized constant BasicObject::Object (NameError)" because it tries to resolve `Object` with nesting `[BasicObject]` regardless of the nature of `D`.

I think this would work:

> Ruby is able to resolve the `ApplicationController` constant, and therefore the autoloading mechanism is not triggered. See the section [When Constants Aren't Missed](http://guides.rubyonrails.org/autoloading_and_reloading_constants.html#when-constants-aren-t-missed) of the [Autoloading and Reloading Constants](http://guides.rubyonrails.org/autoloading_and_reloading_constants.html) guide for further details.

**Comment by claudix** [comment]
Thanks @fxn for your assessment!

**Comment by fxn** [comment]
Thanks!

**Pull request merged**
