### PR TITLE
got rid of exsessive code

### PR DESCRIPTION
**Pull request by lakesare**
unless endpoint or @endpoint are false, they will have the same value table.

### CODE REVIEW

**Comment by schneems** [comment]
We don't take refactoring pull requests. It screws up git blame. Sorry.

**Comment by tubbo** [comment]
@schneems please update the guide on contributing to reflect this point, if it is indeed true: http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html

The following line reads as though you *can* submit refactoring pull requests:

> Refactorings and documentation changes generally should not go to the CHANGELOG.

**Comment by rafaelfranca** [comment]
@tubbo it is there:

> Changes that are cosmetic in nature and do not add anything substantial to the stability, functionality, or testability of Rails will generally not be accepted (read more about our rationales behind this decision).

**Comment by schneems** [comment]
Thanks for the PR even if we aren't merging, it will make another really easy. Check out http:/:www.docs doctor.org or http://www.codetriage.com to help find other places to contribute. We want you as a contributor and thankful for your effort

**Pull request closed without merging**
