### PR TITLE
Attempt to fix travis failures

### PR DESCRIPTION
**Pull request by sgrif**
Opening a PR because I'm not sure this works with container based
infrastructures

### CODE REVIEW

**Comment by rafaelfranca** [comment]
This seems to keep it broken because the newest sqlite3 version on the linux distribution that is running on travis still have the bug. One option is using a different channel to get the package.

**Comment by sgrif** [comment]
I don't think we can do that on the container based infrastructure though, since we don't have `sudo`, and can only use whitelisted packages.

**Comment by rafaelfranca** [comment]
:cry: So I think we will have to enable failures for SQLite3 or skip just this test.

**Comment by sgrif** [comment]
Yeah, I think I just need to change the check to return a boolean, and skip if it's true with the same message. I can fix it tonight unless you want to take care of it before that.

**Pull request closed without merging**
