### PR TITLE
Mirror the API of Ruby stdlib for #prev_day, #next_day, #prev_month, #next_month, #prev_year, #next_year

### PR DESCRIPTION
**Pull request by bogdanvlviv**
Add same method signature for `Time#prev_day`, `Time#next_day`, `Time#prev_month`, `Time#next_month`, `Time#prev_year`, `Time#next_year` in accordance with  `Date#prev_day`, `Date#next_day`, `Date#prev_month`, `Date#next_month`, `Date#prev_year`, `Date#next_year`.

Allows pass argument for `Time#prev_day`, `Time#next_day`, `Time#prev_month`, `Time#next_month`, `Time#prev_year`, `Time#next_year`.

Before:
```
Time.new(2017, 9, 16, 17, 0).prev_day    # => 2017-09-15 17:00:00 +0300
Time.new(2017, 9, 16, 17, 0).prev_day(1)
# => ArgumentError: wrong number of arguments (given 1, expected 

Time.new(2017, 9, 16, 17, 0).next_day    # => 2017-09-17 17:00:00 +0300
Time.new(2017, 9, 16, 17, 0).next_day(1)
# => ArgumentError: wrong number of arguments (given 1, expected 0)

Time.new(2017, 9, 16, 17, 0).prev_month    # => 2017-08-16 17:00:00 +0300
Time.new(2017, 9, 16, 17, 0).prev_month(1)
# => ArgumentError: wrong number of arguments (given 1, expected 0)

Time.new(2017, 9, 16, 17, 0).next_month    # => 2017-10-16 17:00:00 +0300
Time.new(2017, 9, 16, 17, 0).next_month(1)
# => ArgumentError: wrong number of arguments (given 1, expected 0)

Time.new(2017, 9, 16, 17, 0).prev_year    # => 2016-09-16 17:00:00 +0300
Time.new(2017, 9, 16, 17, 0).prev_year(1)
# => ArgumentError: wrong number of arguments (given 1, expected 0)

Time.new(2017, 9, 16, 17, 0).next_year    # => 2018-09-16 17:00:00 +0300
Time.new(2017, 9, 16, 17, 0).next_year(1)
# => ArgumentError: wrong number of arguments (given 1, expected 0)
```

After:
```
Time.new(2017, 9, 16, 17, 0).prev_day    # => 2017-09-15 17:00:00 +0300
Time.new(2017, 9, 16, 17, 0).prev_day(1) # => 2017-09-15 17:00:00 +0300

Time.new(2017, 9, 16, 17, 0).next_day    # => 2017-09-17 17:00:00 +0300
Time.new(2017, 9, 16, 17, 0).next_day(1) # => 2017-09-17 17:00:00 +0300

Time.new(2017, 9, 16, 17, 0).prev_month    # => 2017-08-16 17:00:00 +0300
Time.new(2017, 9, 16, 17, 0).prev_month(1) # => 2017-08-16 17:00:00 +0300

Time.new(2017, 9, 16, 17, 0).next_month    # => 2017-10-16 17:00:00 +0300
Time.new(2017, 9, 16, 17, 0).next_month(1) # => 2017-10-16 17:00:00 +0300

Time.new(2017, 9, 16, 17, 0).prev_year    # => 2016-09-16 17:00:00 +0300
Time.new(2017, 9, 16, 17, 0).prev_year(1) # => 2016-09-16 17:00:00 +0300

Time.new(2017, 9, 16, 17, 0).next_year    # => 2018-09-16 17:00:00 +0300
Time.new(2017, 9, 16, 17, 0).next_year(1) # => 2018-09-16 17:00:00 +0300
```

### CODE REVIEW

**Comment by tenderlove** [comment]
> Mirror the API of Ruby stdlib for #prev_day, #next_day, #prev_month, #next_month, #prev_year, #next_year

I'm confused. Are these methods actually in Ruby stdlib?  They don't seem to work for me:

```
irb(main):003:0> Time.new(2017, 9, 16, 17, 0).prev_month
NoMethodError: undefined method `prev_month' for 2017-09-16 17:00:00 -0700:Time
	from (irb):3
	from /Users/aaron/.rbenv/versions/ruby-trunk/bin/irb:15:in `<main>'
irb(main):004:0>
```

**Comment by bogdanvlviv** [comment]
They are in Ruby stdlib but only for `Date` and `DateTime`.
ActiveSupport provides these methods for `Time`.
This PR sets the same api of methods as Ruby stdlib has.

We've had discussion about it at Campfire
/cc @sgrif

**Comment by pixeltrix** [comment]
FYI, the methods were adding to `Time` back in 2005 and pre-date the addition of the methods to the Ruby date stdlib in 1.9.3, which is why they have a subtly different method signature. Don't see any reason why it shouldn't be merged, but then I've never seemed to have needed the functionality either on `Date` or `Time`.

Arguably it could warrant some tests going both ways across DST boundaries in both spring and autumn but since the methods are implemented in terms of `advance` which has pretty good coverage I don't think it's really necessary.

**Comment by bogdanvlviv** [comment]
@pixeltrix I'm sure that `advance` has a good coverage. Do you want me to remove introduced changes in the tests? (I would like to leave them.)

**Comment by bogdanvlviv** [comment]
Can we make any decision on this PR?

**Comment by pixeltrix** [comment]
@bogdanvlviv thanks for the PR - sorry for the delayed response.

**Comment by bogdanvlviv** [comment]
@pixeltrix Thanks for the review!

**Pull request merged**
