### PR TITLE
Removed not needed includes, As record_tag_helper is moved to a gem we..

### PR DESCRIPTION
**Pull request by ankit8898**
are not testing it completely here now. `RenderErbUtils` and `AM::Conversion` are not used.

### CODE REVIEW

**Comment by senny** [comment]
Honestly, I don't think those tests are worth maintaining. When the functionality was extracted to a gem #18411 the responsibility was moved out of `rails/rails`. I'd rather just delete them.

@rafaelfranca you merged the extraction, do you see a reason to keep them around?

**Comment by ankit8898** [comment]
@senny yeah, the only reason it's hanging there is for testing the exception.

**Comment by carlosantoniodasilva** [comment]
I think we can remove them when we get rid of the methods themselves - which just raise for now if I'm not wrong.

**Comment by arthurnn** [comment]
Right.. we can actual remove the file once we remove the method `content_tag_for`.

**Comment by arthurnn** [comment]
thanks .

**Pull request merged**
