### PR TITLE
Use 'public_send' over '__send__' for model's attribute methods.

### PR DESCRIPTION
**Pull request by mechanicles**
Use `public_send` over `__send__` for model's attribute methods as they are
always **public** methods.

### CODE REVIEW

**Comment by vipulnsward** [comment]
We need __send__ here to support attributes named as "send" which may clash.

Instead we should add spec for this.

**Comment by mechanicles** [comment]
@vipulnsward `public_send` works same as `__send__` method but only allows public methods to pass on. If an object has its own `send` method defined then `public_send` method works fine on it too.

Not getting which spec you are mentioning here.

**Comment by vipulnsward** [comment]
`public_send`, `send` both have same issues, 

`define_attribute_methods :send, :public_send`

won't work. But then so does `__send__`, which is rare. See also: https://github.com/vipulnsward/rails/commit/c3ff04b05db1da913640481b79f75e51e804ed11

**Comment by mechanicles** [comment]
In that case or similar case, nothing will work properly. 

Added `public_send` because here we interact with object's attributes only which are public. I think it would be good if we use `send` or `__send__` only for the private methods.

Tried to look up about which one is preferable in the Rails conventions guide but didn't get any, so added this change.

**Comment by maclover7** [comment]
:+1: - agree with @vipulnsward -- the commit linked above demonstrates why `__send__` (while slightly unconventional) is used over `public_send`, or similar. Rails should be consistent about how it routes methods in special cases, so I'd say that the current behavior is fine the way it is now.

**Comment by jeremy** [comment]
Believe this is simpler than name collisions. We allow private attributes, so public_send wouldn't work. We do prefer public_send elsewhere.

**Comment by mechanicles** [comment]
@vipulnsward @maclover7 @jeremy Got it. No worries :)

**Pull request closed without merging**
