### PR TITLE
Introduce a guide to choosing an app server [ci skip]

### PR DESCRIPTION
**Pull request by CamJN**
### Summary

Introduces a beginner friendly guide to choosing an app server to use in production. The only "code" changes are the addition of a comment in the Rails app template's Gemfile referring to the new guide.

### Other Information
❤️ from Phusion.
[ci skip]

### CODE REVIEW

**Comment by CamJN** [comment]
Hi @matthewd, I wrote this guide based on the understanding that it was okay with @dhh: https://github.com/rails/rails/pull/17981#issuecomment-66306214. Could you maybe explain why you closed it? Thanks!

**Comment by dhh** [comment]
Hey @CamJN, I think @matthewd got a little eager on the close button due to the commercial pitch nature of this write-up. I think there's some good 101 stuff in this guide that could be worth using, but it also needs a lot of work to be suitable for merging.

The biggest problems as I see them:

1. Pitching a commercial product a guide is written by its maker isn't appropriate. However fair and balanced you intend to be, it's like having legislation written by lobbyists. Doesn't mean the legislation is defacto bad, but it means someone is going to be incredibly skeptical about it! So we'd have to narrow this down to exclusively mention Passenger, and then you can do an up-sell on your own site.
1. Lots of mentions and focus on non-MRI runtimes that haven't otherwise been introduced. I think this guide should exclusively focus on MRI and the options there. If someone wants to run non-MRI, picking a different app server isn't likely to be the bulk of the work. Those topics deserve full attention elsewhere.
1. It doesn't actually succinctly answer the question it sets out to answer. Perhaps because we've framed that question in the wrong way. If we start from the baseline that everyone is going to use Puma EXCEPT in the following circumstances. And then list those circumstances and the arguments for picking something else there. Like needing specific monitoring or otherwise features. I don't think the final feature comparison chart is helpful.
1. No need to talk about legacy servers like WEBrick. This isn't a history lesson, but a guide.

Even with all these changes, I'm still not sure we'll arrive at a guide that carries its own weight and is worth merging. But if you're interested in giving it a shot none the less, please do have at it!

**Comment by nateberkopec** [comment]
I'll add that it doesn't seem like anyone's opinions have changed on [introducing caveats to the default Rails Gemfile](https://github.com/rails/rails/pull/17981#issuecomment-66293010) either.

I agree with @matthewd's reasoning:

> But as a general principle, "you might want to use this, but note it doesn't work The Rails Way" is never going to belong in the default generated app, by definition.

FWIW I'm not sure of the purpose of this guide, as written. If you've got an MRI Rails application, I don't think there are many meaningful trade-offs between application servers. You just pick the one you think is best and go with it, in prod and dev. Since there are no meaningful tradeoffs, any guide will *always* have to advance a thesis that "you should pick this one because it is best". As a Rails user, I expect that choice has already been made for me, so a guide telling me that it *hasn't* is a bit strange.

**Comment by dhh** [comment]
I wouldn't go so far, @nateberkopec. I think there may well be different circumstances that welcome a change from the default. But those reasons need to be argued clearly and they haven't been here. With Puma as the default, we should proceed from the understanding that Puma is going to be what most people will use and they'll only change under THESE SPECIFIC CIRCUMSTANCES AND REASONS. And those need to be more compelling than hand-wavy "designed for ease of use" kinds of things.

**Comment by matthewd** [comment]
Yeah, sorry I handled this poorly, @CamJN. What @dhh said.

---

We've generally avoided trying to present a break down of all the possible options for X because they change, are hard to write and maintain with low bias, and even the question of whether a given obscure alternative should be included (e.g., "I just wrote this last week, and it sorta works. It should definitely be covered by the guide.") can create recurring, protracted discussions and/or animosity.\*

Note that even where we ship AR and AJ adapters in-tree, for example, we avoid taking on the burden of contrasting the available options, beyond stating which features the respective *adapters* provide, in the case of AJ.

\* Passenger is of course the antithesis of "too obscure", and I don't mean to imply otherwise... but not everything is so black and white.

**Comment by CamJN** [comment]
Thanks everyone for the feedback, I appreciate it.

**Pull request closed without merging**
