### PR TITLE
Collection input propagates input's id to the label's for attribute.

### PR DESCRIPTION
**Pull request by nashby**
Fixes https://github.com/plataformatec/simple_form/issues/1263

### CODE REVIEW

**Comment by sgrif** [comment]
This was merged

**Comment by rafaelfranca** [comment]
Was it?

**Comment by sgrif** [comment]
Yes. See https://github.com/rails/rails/commit/c2ad51a2d037b709f4475cf115d89432ec56caac in master

**Comment by rafaelfranca** [comment]
:+1:

**Comment by rafaelfranca** [comment]
I was just looking for the link since GitHub didn't create the link to close the Simple Form issue. Thanks

**Pull request closed without merging**
