### PR TITLE
[ci skip] Use ApplicationRecord instead of ActiveRecord::Base

### PR DESCRIPTION
**Pull request by abhishekjain16**
Using ApplicationRecord instead of ActiveRecord::Base

### CODE REVIEW

**Comment by maclover7** [comment]
I'm not sure if we want to just assume that people have a `ApplicationRecord`, I'd say sticking with `ActiveRecord::Base` is a better idea.

**Comment by abhishekjain16** [comment]
@maclover7 
Agreed. They might not use it.
But by default, we generate model with `ApplicationRecord`.
So, we might want to stick with default behaviour in guides/docs. Wdyt?

**Comment by kaspth** [comment]
I think we might have rejected a change like this before. @abhishekjain16 what does a search through GitHub issues say?

**Comment by abhishekjain16** [comment]
@kaspth 
The original PR also made same changes https://github.com/rails/rails/pull/12177
We have accepted
- https://github.com/rails/rails/pull/23110
- https://github.com/rails/rails/pull/22626

Rejected
- https://github.com/rails/rails/pull/22628 - But this was due to change done in upgrade guides. [here](https://github.com/rails/rails/pull/22628#discussion_r47902590)

**Comment by kaspth** [comment]
Thanks! Those changes all seem to change the guides and not individual source docs. These read fine as `ActiveRecord::Base` to me. :heart:

**Comment by abhishekjain16** [comment]
:+1:

**Pull request closed without merging**
