### PR TITLE
Give authentication methods the ability to customize response message.

### PR DESCRIPTION
**Pull request by kbrock**
Digest allowed the messages to be customized.

Add the same feature to basic and token

### CODE REVIEW

**Comment by okay44** [comment]
Yah

Sent via the ASUS PadFone X mini, an AT&T 4G LTE smartphone

-------- Original Message --------

**Comment by matthewd** [comment]
I had written up a long comment claiming this was a bad idea -- given its limitations, it seems easier for the caller to fall back to using the separate `authenticate_with_` and `request_` methods directly... even though we don't really offer what I'd want in that situation: a method that builds and sets `WWW-Authenticate`, while holding no designs on the rest of the response content.

But then I re-read, and that time, I actually read your first sentence :sweat_smile:  that Digest already

**Comment by kbrock** [comment]
@matthewd I was planning on calling this with `render_to_string("file")`.
Found a way around needing this.

You want me to remove the  `authenticate_or_request_with_*`?

That would work for me.

**Comment by rafaelfranca** [comment]
> Digest allowed the messages to be customized.

Does it? It seems that your PR is also changing Digest to accept the message, so how is it allowing?

**Comment by kbrock** [comment]
@rafaelfranca / @matthewd Didn't mean to mislead.
I was saying `request_http_basic_authentication` had it.
I will remove from `authenticate_or_request_with`

**Comment by rafaelfranca** [comment]
Ah, got it. If `request_http_basic_authentication` have it I don't see why `authenticate_or_request_with_` should not have. I didn't look the `request_http_digest_authentication` before, sorry.

Lets keep your previous patch.

**Comment by kbrock** [comment]
lol. put it back in. its all good.

**Comment by rafaelfranca** [comment]
:smile:, sorry

**Comment by matthewd** [comment]
> I was planning on calling this with `render_to_string("file")`

Yeah.. that sounds pretty expensive: rendering the entire "you need to log in" response on every request, before you check whether they already have. :confused:

**Pull request merged**
