### PR TITLE
Run all our tests in random order

### PR DESCRIPTION
**Pull request by matthewd**
My recollection is that this was mostly working, but we were seeing just enough failures that we didn't want to leave it enabled while branching for release.

Let's see whether that's (still) true.

See also #19217.

/cc @tgxworld

### CODE REVIEW

**Comment by senny** [comment]
@matthewd does that work for AR? I suspect there is still work left to do before those pass at a reasonable rate.

**Comment by jeremy** [comment]
:metal:

**Comment by tgxworld** [comment]
@senny, @amatsuda was the last one working on. If I remember correctly, failures came from AR.

**Comment by amatsuda** [comment]
Yeah, as far as I remember, there remains some sporadic fails in AR suites, about which nobody cares at all while we're running tests in `:sorted` order.
I'm still willing to track the CI failures on AR, so I add  :+1: from me. Thanks @matthewd for reminding the issue.

**Comment by rafaelfranca** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by tgxworld** [comment]
:+1:

**Pull request merged**
