### PR TITLE
Update deprecation.rails guides [ci skip]

### PR DESCRIPTION
**Pull request by keegnotrub**
### Motivation / Background

Both `:gem_name` and `:deprecation_horizon` were added to the `deprecation.rails` event some time ago in Rails 5.2.0. See Changelog entry "Pass gem name and deprecation horizon to deprecation notifications.".

https://github.com/rails/rails/blob/5-2-stable/activesupport/CHANGELOG.md#rails-520-april-09-2018

### Detail

This was added to be documented in the Rails Guides roughly a year ago, however, it was not back ported to previous Rails Guides versions (such as 6.1 here).

https://github.com/rails/rails/pull/47305/files

### Additional information

We ran into this while upgrading an existing Rails 6.1.x application. We are unsure if a PR against the `6-1-stable` branch is the way to properly update the Rails 6.1 Edge Guides, so please advise if not.  Also, please let us know if the Rails 6.0 and Rails 5.2 Guides should also have this back ported.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [ ] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [ ] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

Co-authored-by: Stefanni Brasil <stefannibrasil@gmail.com>

### CODE REVIEW

**Comment by skipkayhil** [comment]
Thank you for the pull request, but `6-1-stable` is not accepting bug fixes or documentation changes

**Comment by stefannibrasil** [comment]
Ah, got it, thanks for the context, @skipkayhil Does that apply to [Rails 7.0 docs](https://guides.rubyonrails.org/v7.0/active_support_instrumentation.html#rails) as well?

**Comment by skipkayhil** [comment]
(I'm not 100% sure 😅) but I'll go ahead and backport the referenced commit and credit you both 😄

**Comment by stefannibrasil** [comment]
Oh, great, thank you! We weren't sure about old versions docs so thanks for taking the time to share the context with us.

**Pull request closed without merging**
