### PR TITLE
Specify Turbolinks version in Gemfile

### PR DESCRIPTION
**Pull request by walterdavis**
Added a version dependency to turbolinks

### CODE REVIEW

**Comment by walterdavis** [comment]
Issue #21268 has details.

**Comment by matthewd** [comment]
I can't imagine why you'd ever be doing something involving the Rails Gemfile on a locked-down server.

But even ignoring the fact that you're changing the wrong file, this seems to be an application concern: if your application requires a particular version of turbolinks, then your application's Gemfile should reflect that.

**Comment by walterdavis** [comment]
Rails 4.2 will not work correctly with Turbolinks < 2. We are talking about the Rails Gemfile here, which is intended to specify a particular version of the gems needed by Rails... As to the locked server, we have a "blessed" version of everything, and individual developers are not allowed to install other versions. Our case is strange, I will admit, but when testing an update from 4.1 to 4.2, we discovered this bug.

**Comment by rafaelfranca** [comment]
This Gemfile doesn't affects applications. Like @matthewd said, if you need a particular versions of turbolinks you should put in your application's Gemfile the requirement

**Pull request closed without merging**
