### PR TITLE
Fix custom primary keys when calling `Relation#where`

### PR DESCRIPTION
**Pull request by RickCSong**
See https://github.com/rails/rails/issues/23327

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Could you create a PR against the master branch? We will backport if we think it is needed. Thank you.

**Comment by RickCSong** [comment]
@rafaelfranca It does not appear that Master is affected by this bug (5.0+, 4.2+).  However, 4.1.12+ is affected by this.  Upon inspection, it seems that 4.2 has fixed it a similar way.  

See: 

```
    def self.expand(klass, table, column, value)
      queries = []

      # Find the foreign key when using queries such as:
      # Post.where(author: author)
      #
      # For polymorphic relationships, find the foreign key and type:
      # PriceEstimate.where(estimate_of: treasure)
      if klass && reflection = klass._reflect_on_association(column)
        base_class = polymorphic_base_class_from_value(value)

        if reflection.polymorphic? && base_class
          queries << build(table[reflection.foreign_type], base_class)
        end

        column = reflection.foreign_key

        if base_class
          primary_key = reflection.association_primary_key(base_class)
          value = convert_value_to_association_ids(value, primary_key)
        end
      end

      queries << build(table[column], value)
      queries
    end
```

from 4.2.5.1

**Comment by rafaelfranca** [comment]
Awesome. I'll merge them.

**Comment by RickCSong** [comment]
Thank you!!  @rafaelfranca :+1:

**Pull request merged**
