### PR TITLE
Mention that layout can call a Proc [ci skip]

### PR DESCRIPTION
**Pull request by ojab**
Also list all accepted return values for Proc/method

### CODE REVIEW

**Comment by sgrif** [comment]
Just saying "false, true, or nil" doesn't convey what returning that does.

**Comment by ojab** [comment]
Yeah, but their meaning described in the surrounding comments, I assume that reader will get it.

**Comment by sgrif** [comment]
I would not assume that. I'd prefer to mention that it behaves the same as
using the return value directly.

**Comment by ojab** [comment]
Pushed version with different wording, hope that it's decent this time.

**Comment by rafaelfranca** [comment]
Merged in b077052. Thanks

**Pull request merged**
