### PR TITLE
Linter fixes

### PR DESCRIPTION
**Pull request by zmariscal**
### Motivation / Background
This Pull Request has been created because I want to fix a small amount of linter violations.

### Detail

This Pull Request changes various rubocop failures/violations

### Additional information
Most of these changes are auto fixes via `standardbred --fix <path>`

### CODE REVIEW

**Comment by zmariscal** [comment]
I fixed a number of the rubocop failures, but there are still two lingering ones I decided not to fix. I was thinking incremental and scoped changes first.

**Comment by skipkayhil** [comment]
Hey @zmariscal, thanks for opening a PR!

Is there a reason for these changes other than style preference? We don't accept [cosmetic changes](https://github.com/rails/rails/pull/13771#issuecomment-32746700) so I don't think this PR will be accepted.

(As an aside, it looks like the rubocop job is failing as well which would need to be fixed)

**Comment by zmariscal** [comment]
I see https://github.com/rails/rails/blob/9294a5518774baa162d8d35175c8638b7d696ccb/CONTRIBUTING.md?plain=1#L34 now too. Thanks for pointing it out!

**Comment by zmariscal** [comment]
> Hey @zmariscal, thanks for opening a PR!
> 
> 
> 
> Is there a reason for these changes other than style preference? We don't accept [cosmetic changes](https://github.com/rails/rails/pull/13771#issuecomment-32746700) so I don't think this PR will be accepted.

I was wondering if there's an opportunity to link the contributing.md in the PR template. I would have read it if it were linked ☺️

**Pull request closed without merging**
