### PR TITLE
Update getting_started.md [ci skip]

### PR DESCRIPTION
**Pull request by tyrollins**
Update "ActiveRecord::Migration[5.0]" to "ActiveRecord::Migration[5.1]"

### Summary
Update "ActiveRecord::Migration[5.0]" to "ActiveRecord::Migration[5.1]"

### Other Information
Provides consistency.

If you are updating any of the CHANGELOG files or are asked to update the
CHANGELOG files by reviewers, please add the CHANGELOG entry at the top of the file.

Finally, if your pull request affects documentation or any non-code
changes, guidelines for those changes are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#contributing-to-the-rails-documentation)

Thanks for contributing to Rails!

### CODE REVIEW

**Comment by eugeneius** [comment]
This change was previously proposed, and rejected, in https://github.com/rails/rails/pull/29311 and https://github.com/rails/rails/pull/29335.

**Comment by schneems** [comment]
Thanks for the PR! I'm going to close for now. I appreciate the thought though even if we aren't merging. Also thanks to @eugeneius for linking to related issues.

**Comment by eugeneius** [comment]
When reading @schneems' comment I realised that mine was pretty curt... thanks for the pull request @tyrollins, and I hope you'll consider contributing again if you see anything else that needs fixing 😊

**Comment by tyrollins** [comment]
@schneems @eugeneius thanks for taking the time to respond! Definitely looking forward to contributing in the future. A welcoming community, very much appreciated!

**Pull request closed without merging**
