### PR TITLE
Tidy up the error pages

### PR DESCRIPTION
**Pull request by seanmitchell**
Error page markup and style updates.

Screenshot 2024-09-26 at 10 46 56 AM

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Thank you Sean! I merged and fixed the tests.

**Comment by ciembor** [comment]
Why is this the only 4** file that breaks the naming convention? All the others follow the 4**.html naming convention. Is this intentional or a mistake?

**Comment by rafaelfranca** [comment]
Intentional. 406 is more broad than 406-unsupported-browser

**Comment by brendon** [comment]
I'm wanting to add some extra error pages and wondered what font was used to create the SVG parts of the error message. Would it be possible to get access to the design file so we can make more combinations?

**Comment by zzak** [comment]
@brendon I think the folks who designed the error pages also worked on the [website](https://github.com/rails/website) so there might be some more details in there if you want to go digging.

**Comment by brendon** [comment]
Thanks @zzak :) I see the font used there is Calibre.

**Pull request merged**
