### PR TITLE
Adjust to indifferent access around some ActiveModel::Errors methods

### PR DESCRIPTION
**Pull request by kachick**
Adjusted to https://github.com/rails/rails/blob/6f8f2a2017e09d8d94c70761c70007ce72b984e7/activemodel/test/cases/errors_test.rb#L100-L105

### CODE REVIEW

**Comment by arthurnn** [comment]
I am not sure I understand what is the main purpose of this change. Can you elaborate? 

thanks

**Comment by rafaelfranca** [comment]
I got the reason. Some methods on errors has indifferent access and some not. He is adding indifferent access to those methods. Could you rebase, add a changelog entry and squash your commits?

**Comment by kachick** [comment]
Thanks to catch the reason 🙇 

I have finished following tasks.

* Rebased to current master.
* Adjusted coding style to current master.
* Added a simple changelog entry.
* Added some code around `#delete` too.
* Squashed commits.

**Comment by kachick** [comment]
Thank you!

**Pull request merged**
