### PR TITLE
Action Cable JS Unit Tests

### PR DESCRIPTION
**Pull request by maclover7**

### CODE REVIEW

**Comment by vipulnsward** [comment]
@jeremy should these tests actually be the integration tests from https://github.com/rails/rails/issues/24878 , or just have these?
Else we are having two different set of tests.

**Comment by maclover7** [comment]
I think there's room for two types of tests -- unit and integration tests (I believe that similar Turbolinks and Trix libraries both have these). I'm happy to focus on the unit tests if you want to work on the integration tests -- whatever's easiest. :-)

**Comment by javan** [comment]
Nice! I actually kicked off some tests today too using [Blade](https://github.com/javan/blade) (the toolkit we use to build and test Trix and Turbolinks). I mocked `WebSocket` with https://github.com/thoov/mock-socket, which gets us pretty close to integration testing without needing a running cable server. I'll push something soon and maybe we can tag team writing tests for the outline you started?

**Comment by maclover7** [comment]
Yup! I wanted to at least outline all of the unit tests we wanted to have, get mocha + chai up and running, and then we can split up the work of actually filling out the suite, and parallelize the process. :-)

**Comment by javan** [comment]
@maclover7 Here's the branch I started: https://github.com/rails/rails/compare/master...javan:actioncable-javascript-tests. Run `rake test:javascript` to bring up the test console. The tests automatically restart when any source or tests files change. (Sorry, Blade is totally undocumented. I'm working on it. 😁 )

**Comment by javan** [comment]
Opened a PR: https://github.com/rails/rails/pull/24935

**Comment by rafaelfranca** [comment]
Closing since #24935 was merged.

**Pull request closed without merging**
