### PR TITLE
Allows for other common redis options to be in cable.yml, by default

### PR DESCRIPTION
**Pull request by padi**
### Summary

Previously, the redis adapter for ActionCable accepts only a `:url` as an option. While we can follow the [redis url scheme](https://www.iana.org/assignments/uri-schemes/prov/redis), it is not documented well enough in the Rails Guides.

This allows for an alternative setup (that is as common as the previous one) for the [redis gem](https://github.com/redis/redis-rb#getting-started), so people don't occasionally trip up [like](https://github.com/rails/rails/pull/28702) [these](https://github.com/rails/rails/pull/28843). Check the commit message for more technical details.

### Other Information

There are other options that can be passed to the Redis gem (See: https://github.com/redis/redis-rb/blob/master/lib/redis/client.rb#L8), but did not include them because:
1.  it might clash with other keys already used in `#cable_config` in different context (e.g. `driver`),  
2. the problem of how to test them is non-trivial (at least on top of my head, e.g. `path`).
3. they are uncommon enough that they may warrant changing `redis_connector` on intialization, i.e. `ActionCable::SubscriptionAdapter::Redis.redis_connector =  ->() { initialization_code }`

Also, I'm not as familiar with setting up `.travis.yml` properly, you may want to check if what I did was right. I removed instances of the Travis' internal `redis` service. Instead, I used `redis-server` using the default settings + password in the `before_script`. The tests now pass though.

Let me know if there's anything else I can do @pixeltrix

### CODE REVIEW

**Comment by rafaelfranca** [comment]
@padi avoid to change the assignment of a PR. We use automatic assigns exactly to avoid to load only one person with all the PRs in the organization (that is a lot). If you assign it again to someone just because you see that person is more active you are overloading that person again.

**Review by rafaelfranca — CHANGES_REQUESTED** [review]
Could you add a CHANGELOG entry?

**Comment by ukblewis** [comment]
@padi This PR looks to fulfill the needs that I had in my pull request. Can I add the CHANGELOG for you?

**Comment by padi** [comment]
@rafaelfranca genuinely sorry about that. I didn't think that one through. :coffee: for you should we get to meet in any of the ruby conferences. 

@ukblewis glad to help. 👍

**Review by rafaelfranca — APPROVED** [review]

**Comment by rafaelfranca** [comment]
Thank you!

**Pull request merged**
