### PR TITLE
Remove unused `DepthFirst` visitor

### PR DESCRIPTION
**Pull request by kamipo**
We only use `ToSQL` visitors in the our codebase, do not use
`DepthFirst` and `Dot` visitors.

The `DepthFirst` visitor (which was introduced at c86c37e5f) is used to
traverse an Arel (partial) ast with depth first.

Is there any worth to keep that undocumented feature with much code and
test cases.

This removes that unused `DepthFirst` code and test cases.

cc @tenderlove (as the author of the commit c86c37e5f)

### CODE REVIEW

**Review by rafaelfranca — APPROVED** [review]

**Comment by vipulnsward** [comment]
I think this existed for visualizations?

**Comment by kamipo** [comment]
I am a person who most touching Arel recently (https://github.com/rails/rails/commits/master/activerecord/lib/arel), `DepthFirst` is hard to use it for visualizations and debugging.

Can you provide an example usage?

**Comment by oyeanuj** [comment]
@kamipo @rafaelfranca This was being used here in the `rgeo` library: 

https://github.com/rgeo/rgeo-activerecord/blob/8d939494220e03c32c1badbf111b36f237d4632e/lib/rgeo/active_record/arel_spatial_queries.rb#L89-L92

This is now breaking as mentioned [here](https://github.com/rgeo/rgeo-activerecord/issues/54)

What should be used instead?

cc: @teeparham

**Comment by Hugo-Hache** [comment]
Just for information I'm working on adding a `joined_tables` method to `ActiveRecord::Relation`, in order to be able to join a table only if it's not already joined.

I plan to do that by gathering the name of all `Arel::Table` nodes in the AST of each of the `joins_values`. I was looking for a way to walk the Arel AST and found this now removed `DepthFirst` visitor. The `each`  method is a perfect way for me to iterate on AST nodes and gather. As usual @tenderlove you rocked 💌

I hope this comment would answer, with a nice 2 years delay, what could be the usage of this lonely visitor.

PS: I'm an Arel noob, so if you see a better way to list joined tables than manually walking the AST please let me know

**Comment by tiegz** [comment]
I also had a use-case for the `each` method (static analysis of the SQL query) and just discovered it's gone, so I extracted this removed code into a gem, in case anyone needs it in 6.1+: https://rubygems.org/gems/activerecord-arel_depth_first/

**Comment by imdario** [comment]
Just for the record: if somebody used any `Enumerable` method (`#each`, `#include?`) on a `Arel::Nodes::Node`, this PR removed that possibility.

I tested my use-case using @tiegz (the repository is missing but not the gem, BTW) and it works again.

Probably it's a really minority use-case, but for those seeking for help when they face an error like `undefined method include?' for #<Arel::Nodes::Sum:0x00007f42f6bcedb0...>`, you can (responsibly) monkey-patch it adding a source like this inside your app/ (so it autoloads):

```ruby
module EnumerableNode
  include Enumerable

  def each(&block)
    return enum_for(:each) unless block_given?

    yield self
  end
end

ActiveSupport.on_load :active_record do
  Arel::Nodes::Node.prepend(EnumerableNode)
end
```

**Comment by tiegz** [comment]
@imdario thanks, that repo is now public: https://github.com/tidelift/activerecord-arel_depth_first 

Also, just a headsup that we've come across a rare `SystemStackError: stack level too deep` exception with this in Rails 6.1 while using this patch, when loading a big query that combines a few thousand `or()` queries, but I haven't been able to dig into it yet.

**Comment by imdario** [comment]
Thanks @tiegz! Fortunately we don't have such a query but we take note.

**Pull request merged**
