### PR TITLE
[Action Cable] Add parameter filtering to logging

### LINKED ISSUE #25088: [ActionCable] No way to filter out any sensitive data which may be passed as an argument to the remote procedure over ws protocol..
### Steps to reproduce

Just followed the action cable demo from DHH on [rails homepage](http://rubyonrails.org/).

You would notice that whenever the RoomChannel#speak is invoked over websocket protocol, the server logs show the arguments which are passed.  

```
RoomChannel#speak({"message"=>"test"})
```

For HTTP requests, we have `filter_parameters` to filter out any sensitive data from the logs.
However, for these RPCs, I could not find any way to filter out any sensitive data which may be passed as an argument to the remote procedure.
### Expected behavior

I expected some mechanism to filter out logs for any arbitrary arguments which are passed over ws protocol.
### Actual behavior

I could not find a way to filter out logs for data transmitted over ws protocol.
**Please advise** if this behavior is on purpose.

Below is the related code which I am referring to

``` ruby
#actioncable-5.0.0.rc1/lib/action_cable/channel/base.rb
def dispatch_action(action, data)
  # What if we do not want this to be logged.
  logger.info action_signature(action, data)

  if method(action).arity == 1
    public_send action, data
  else
    public_send action
  end
end

def action_signature(action, data)
  "#{self.class.name}##{action}".tap do |signature|
    if (arguments = data.except('action')).any?
      signature << "(#{arguments.inspect})"
    end
  end
end
```
### System configuration

**Rails version**: 5.0.0.rc1

**Ruby version**: ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux]

### PR DESCRIPTION
**Pull request by maclover7**
- Reuses most of the architecture that Action Pack uses :)
- Fixes #25088

### CODE REVIEW

**Comment by michaeldever** [comment]
This would be useful to have

**Comment by maclover7** [comment]
Sorry for my delay here -- updated my PR, and build should be passing now 👍

**Comment by maclover7** [comment]
👍 Build is passing

**Comment by siegy22** [comment]
@maclover7 That's what I was looking for, do you think this is going to be merged in?

@rafaelfranca cascasca 🍷 :joy:

**Review by rafaelfranca — CHANGES_REQUESTED** [review]
I like the idea but I think a better direction is to make the ActionDispatch parameter filter generic enough to not need to not use the env object and headers so we don't need this data wrapper class.

A good design would have a object that given a hash and a list of keys to be filtered return the filtered hash.

**Comment by arthurdandrea** [comment]
```ruby
```

**Comment by arthurdandrea** [comment]
Facing an issue similiar to #25088, I came up with a solution using `ActionDispatch::Http::ParameterFilter` instead of `ActionDispatch::Http::FilterParameters`, all the code I implemented on my `ApplicationCable::Channel` class. 
```ruby
module ApplicationCable
  class Channel < ActionCable::Channel::Base
    def action_signature(action, data)
      signature = "#{self.class.name}##{action}"
      if (arguments = data.except('action')).any?
        filter = ActionDispatch::Http::ParameterFilter.new(Rails.application.config.filter_parameters)
        signature += "(#{filter.filter(arguments).inspect})"
      end
      signature
    end
  end
end
```

**Comment by Anuragjain89** [comment]
@rafaelfranca 

cc: @maclover7 @arthurdandrea 

Do you agree with @arthurdandrea 's [approach](https://github.com/rails/rails/pull/25090#issuecomment-271274675) to addressing #25088 ?
If so, please advise so that @maclover7 / @arthurdandrea can submit a PR with the suggested changes.

**I will be happy to volunteer / submit a PR for the same.**

Thanks.

**Comment by Schwad** [comment]
Howdy all :) do we have any thoughts on this on moving forward with the PR?

**Comment by ukblewis** [comment]
What is the status of this PR? Rails has had ActionCable for a year now, but it still doesn't support filtering.

**Comment by helpse** [comment]
Any update as of January 10th, 2018 ?

**Comment by oniofchaos** [comment]
Hi @maclover7 I realize this is old, but the first step to potentially getting this merged is cleaning up the merge conflicts so this can be viewed against latest master and discussed. Thanks for the PR 💝

**Comment by cmichelQT** [comment]
Would love to see an update on this!

**Comment by rafaelfranca** [comment]
Feel free to take over this PR and implement it. Now we are a generic parameter filter at `ActiveSupport::ParameterFilter`.

**Comment by rafaelfranca** [comment]
I'm closing this since it is not going to be updated.

**Comment by calebkeene** [comment]
@rafaelfranca Is this worth re-submitting? seems to still be an issue

**Comment by rafaelfranca** [comment]
https://github.com/rails/rails/pull/25090#issuecomment-442641807

**Pull request closed without merging**
