### PR TITLE
[ci skip] Replace `;` with `:`

### PR DESCRIPTION
**Pull request by yui-knk**
I feel `;` is typo of `:` .

### CODE REVIEW

**Comment by vipulnsward** [comment]
The original version looks intentional, and sounds correct.

**Comment by yui-knk** [comment]
For example, `:` is used these context

```
Our Rubyist instinct quickly sees some redundancy in there: If classes were
defined in files matching their name, ...
```

I feel `:` in this sentence and `;` in my PR sentence have same role. Isn' t it ?

**Comment by senny** [comment]
`;` seems correct to me. /cc @fxn

**Comment by fxn** [comment]
I believe the original semicolon is fine. Thanks anyway!

**Comment by yui-knk** [comment]
Thanks for your reviews ! :ok_hand:

**Pull request closed without merging**
