### PR TITLE
Remove needless `ActiveSupport::Deprecation.silence`

### PR DESCRIPTION
**Pull request by kamipo**

### CODE REVIEW

**Comment by kaspth** [comment]
Why is it needless? There's going to be more deprecations eventually.

**Comment by kamipo** [comment]
`require_application_and_environment!` is called from some places but only wrapped it in `rake_command.rb`. I didn't know why this is necessary.

```
% git grep -n require_application_and_environment
lib/rails/command/actions.rb:12:        def require_application_and_environment!
lib/rails/command/actions.rb:27:        def require_application_and_environment!
lib/rails/commands/console/console_command.rb:84:        require_application_and_environment!
lib/rails/commands/destroy/destroy_command.rb:14:        require_application_and_environment!
lib/rails/commands/generate/generate_command.rb:14:        require_application_and_environment!
lib/rails/commands/rake/rake_command.rb:32:              require_application_and_environment!
lib/rails/commands/runner/runner_command.rb:25:        require_application_and_environment!
```

**Comment by matthewd** [comment]
@kaspth why was it there in the first place?

At a glance, it sounds like it's suppressing warnings caused by application code. :confused:

**Comment by kaspth** [comment]
Ah yeah true, let's kill it 👍

**Pull request merged**
