### PR TITLE
FIX: tt.eclosure is not needed for the GTG

### PR DESCRIPTION
**Pull request by utilum**

### CODE REVIEW

**Comment by sikachu** [comment]
Given this is Journey:

r? @tenderlove

**Comment by utilum** [comment]
@pixeltrix ? It's your code and comment from 56fee39c

**Comment by eugeneius** [comment]
https://github.com/rails/rails/commit/56fee39c392788314c44a575b3fd66e16a50c8b5 just merged existing code from https://github.com/rails/journey into this repository; the comment actually originated in https://github.com/rails/journey/commit/a806beb098d807b42bcc997645673abfb944ba96.

**Comment by utilum** [comment]
Oh wow... thank you, a peek into _archived_ history :)

**Comment by utilum** [comment]
I'd be delighted to just remove the FIXME, got a delicious commit message.

**Comment by rafaelfranca** [comment]
Let's go with only the removal of the note.

**Comment by utilum** [comment]
Done.

**Pull request merged**
