### PR TITLE
We need stricter locking before we can unload

### PR DESCRIPTION
**Pull request by matthewd**
Specifically, the "loose upgrades" behaviour that allows us to obtain an exclusive right to load things while other requests are in progress (but waiting on the exclusive lock for themselves) prevents us from using the same lock for both load & unload: new things appearing is fine, but they do _not_ expect previously-present constants to vanish.

We can still use loose upgrades for unloading -- once someone has decided to unload, they don't really care if someone else gets there first -- it just needs to be tracked separately.

Follow-on from #17102.

### CODE REVIEW

**Comment by matthewd** [comment]
I just realised this seemed necessary... can I please get some eyes-on, to confirm 1) I'm describing an actual issue with the current implementation, and 2) this adequately addresses it?

@tenderlove @fxn @thedarkone

**Comment by thedarkone** [comment]
1) yes, 2) yes.

Although, because we now have 2 locks, there is naturally a possibility of a deadlock: 2 threads (`A` and `B`) in app-space, thread `A` tries to `Interlock.unloading` goes to sleep waiting for thread `B` to leave app-space, thread `B` tries to `Interlock.loading` and goes to sleep as well.

The deadlock situation requires user to manually call `interlock.unloading` or `Dependencies.clear`, this of course can't happen during normal Rails usage (Rails itself uses polling via `attempt_unloading`, so it won't ever deadlock on its own).

I think we can fix the deadlock by only ever sleeping on `@load_lock` like this:

```ruby
# in ActiveSupport::Dependencies::Interlock
def unloading
  while true
    @unload_lock.exclusive(true) do
      return yield
    end
    # to avoid deadlocking @unload_lock vs. @load_lock, we're
    # only allowed to sleep on @load_lock
    @load_lock.exclusive {}
  end
end
```

PS: I still think a thread going into `@cv.wait_while` loop in `ShareLock#exclusive` should block any new `shared` readers, thus avoiding `unloading`/`loading` starvation.

**Comment by matthewd** [comment]
> because we now have 2 locks, there is naturally a possibility of a deadlock

Yeah, I'd somehow convinced myself that the layering prevented that, but it is of course not true.

> I think we can fix the deadlock by only ever sleeping on @load_lock like this

I believe that will livelock against itself: assuming both participants already hold both share locks, one can only continue when the other yields its (shared unload) lock during a wait.

----

I've switched to a different, single lock, implementation. For comparison, the previous one was matthewd/rails@2d0bb3906a95808692c4981255e5457e68d82fa8.

The two-lock version has the merit of not touching the ShareLock primitive... this one takes a rather different approach, but still seems to remain somewhat convincingly generic-ish.

> PS: I still think a thread going into @cv.wait_while loop in ShareLock#exclusive should block any new shared readers, thus avoiding unloading/loading starvation.

Yes, I'm still wavering on that point.

The other one I'm considering is that after A and B sync up while blocking on a load, A gets to do the load, then B is stuck waiting while A resumes running. It seems more fair for both A & B to be allowed to load (in turn) before we lose "control" again.

**Comment by thedarkone** [comment]
I don't think this is doable with 2 locks, so the tweaked `ShareLock` is the right way forward (btw gj keeping it "generic-ish" :+1:).

> The other one I'm considering is that after A and B sync up while blocking on a load, A gets to do the load, then B is stuck waiting while A resumes running. It seems more fair for both A & B to be allowed to load (in turn) before we lose "control" again.

Re-pausing A for B to do its loading as well feels somehow weird/wrong, yet I can't articulate whats wrong with it.

----

I wrote basic tests for `ShareLock` at thedarkone/rails@9c4da24, though I needed to make 2 small fixes at thedarkone/rails@b3d78e8c2 to get everything passing. Please cherry-pick the test commit into your branch, so I don't have to do a separate PR for it.

**Comment by matthewd** [comment]
> I wrote basic tests for `ShareLock`

Thank you **so** much! :heart_eyes: 

I've made some changes to your expectations in 649d8173c31ab0b74ef359e692eadf46b5da911d and 4c54b2a9a012296709de5283eada03470d581dc9 (in the process, reverting both changes from b3d78e8c23e3cbd5325719474efb9f7ee4168f72 :grin:) -- hopefully the comments cover my reasoning; any counter-thoughts you have will again be deeply appreciated.

---

> Re-pausing A for B to do its loading as well feels somehow weird/wrong, yet I can't articulate whats wrong with it.

Yeah... at the simplest, "I am happy for operations of type X to occur before I acquire the lock" doesn't necessarily translate to "I am happy for operations of type X to occur after I return the lock" in the general case. Maybe if we exposed it as a separate compatibility list, that would simultaneously allow an advanced usage to consider such a non-commutative yield, and make it explicitly opt-in.

I realised it's currently even slightly more unfair than I was originally picturing: A blocks when it needs to load, then when B reaches the load, it's *B* that gets the lock and is allowed to continue. With the bonus irony that it's quite possible A is now waiting for permission to load the very thing B just did!

So, while I'm doubtful that it's a reasonable default, even for some other purposeful/yielding ShareLock use case, I do think it's sound to apply to loading in particular: for the caller that matters, whether we yield to another thread before or after the load is indistinguishable... they don't control the code that runs while we're holding the lock.

**Comment by thedarkone** [comment]
> in the process, reverting both changes from from b3d78e8 :grin:

I "fix" your code so that my code (tests) is working, now you're changing my code so that your code is working, are you trying to beat me at the passive aggressive game :stuck_out_tongue_closed_eyes:?

> I realised it's currently even slightly more unfair than I was originally picturing: A blocks when it needs to load, then when B reaches the load, it's B that gets the lock and is allowed to continue. With the bonus irony that it's quite possible A is now waiting for permission to load the very thing B just did!

rofl.

I'm also wondering if there might be some issue with `Dependencies`' const loading not being a cleanly idempotent operation (especially if the attempted load errors out because of syntax error in `.rb` file or something like that).

> hopefully the comments cover my reasoning; any counter-thoughts you have will again be deeply appreciated.

Yes, you explained your design decisions very well.

I've added another test and removed the non-upgrading path from `test_exclusive_ordering`: f8c696a6f.

PS: I like how `ShareLock` now has assertions about its assertions<sup>TM</sup>.

**Comment by mperham** [comment]
I'm seeing lockups when integrating the Interlock into Sidekiq.  Is this due to this issue?

Commit here: https://github.com/mperham/sidekiq/commit/be2d12912ebe7aa074afbbd7e16f60259848ec91

**Comment by thedarkone** [comment]
> I'm seeing lockups when integrating the Interlock into Sidekiq. Is this due to this issue?

No, I don't think so. This PR should solve really horrible const loading/unloading errors (ie for example it was possible for a thread, after having detected a change in a `.rb` file, to unload the whole app while the other thread was busy processing a request).

Your usage of `ActiveSupport::Dependencies.interlock` seems to be correct, don't know why it deadlocks for you.

**Comment by mperham** [comment]
@matthewd Repro steps here: https://gist.github.com/mperham/fd838473c267f538f117

**Comment by mperham** [comment]
@matthewd Repro steps here: https://gist.github.com/mperham/fd838473c267f538f117

**Comment by mperham** [comment]
Using JRuby + Sidekiq with those steps above should be a pretty rock solid real world test of the Interlock.  I'm seeing the lockup on MRI but I would verify on JRuby too for obvious reasons.

**Comment by thedarkone** [comment]
@mperham thanks for the straightforward repro script! Here's what happens:

 * app loads fine,
 * workers are spawned,
 * they enter "app space" (section of code that expects to have consts magically autoloaded by Rails) via `interlock.start_running` (to be exact at least 2 of the Threads to enter the shared section),
 * one of the threads during its execution gets to `Sidekiq.redis` in `Processor#stats`, then asks `connection_pool` for a connection, `connection_pool` grabs a mutex in `ConnectionPool::TimedStack#pop` and attempts to load `redis/connection/ruby`, to load a file it needs to have an "exclusive" lock, it can't get it, because other threads are still in shared section, when they proceed with their execution and get to the `ConnectionPool::TimedStack#pop` they deadlock.

In other words the deadlock occurs because `sidekiq` wraps const. loading in an internal mutex (via `connection_pool`), while `Dependencies.interlock` works like this: when a thread wants to load a new const, it either:
 * must be the only thread in "app space" (shared lock),
 * it must wait for other threads to leave "app space" or also want to load a new const, then all but one thread is paused and const loading is performed (in a single thread at a time).

The problem with `sidekiq` is that multiple threads enter "app space", one of them (lets call it "thread A") grabs `ConnectionPool::TimedStack`'s mutex and wants to load a const, and then goes to sleep waiting for other threads to leave "app space" or also get to the point where they want to load a const, but they can't get the point of loading a const, because that is wrapped in a `ConnectionPool::TimedStack` that is still held by the thread A.

This is a very bad `interlock`/`connection_pool` interplay.

**Comment by matthewd** [comment]
For future reference, as we're not currently testing the high level behaviour of the reloader, the problem this PR fixes is:

```ruby
x = User    # load User
_ = Company # yield our lock; some other thread completes and does an unload
y = User    # unload removed it; load User again

x      # => User
y      # => User
x == y # => false
```

**Pull request merged**
