### PR TITLE
Add test for 'ActiveSupport::Inflector.transliterate'

### PR DESCRIPTION
**Pull request by sharang-d**
I went through #35571 and it looked like the change required specs so I added one.

cc @KaanOzkan, @rafaelfranca

### CODE REVIEW

**Comment by sharang-d** [comment]
Do these two methods need similar tests too?

https://github.com/rails/rails/pull/35571/files#diff-9c7c8274426cb68629b863c3ddf57b2aR195
https://github.com/rails/rails/pull/35571/files#diff-91d80f26deadb8d40a0f8599782d0f1aR91

**Comment by kaspth** [comment]
Let's add tests for those too, I think `parameterize` with a locale is broken.

**Comment by sharang-d** [comment]
Saw your comment on the PR, I'll try to debug/fix it.

**Comment by sharang-d** [comment]
I've pushed new tests. I see that the original change does not have a changelog entry. Does it need one and should I add it?

**Comment by kaspth** [comment]
Doh! Yes, we should add a changelog entry too.

**Comment by sharang-d** [comment]
I'll add it.

**Pull request merged**
