### PR TITLE
[ci skip] Update Rails version in guide

### PR DESCRIPTION
**Pull request by yhirano55**
### Summary

* Updated `bin/rails server` stdout.
* Updated Rails version.

### CODE REVIEW

**Comment by sikachu** [comment]
Thank you for your patch. There're two things though:

1. I'm not sure if they needed to be changed and update to the latest version. If it does, that actually means that every time core team release a new version we also have to go over guide to update the version number just to be consistent. Given this does not improve the content (but just give the reader the idea that the content is up-to-date) ... I'm not really sure if this is a good idea.
2. `master` is targeting 6.0. If it's okay to update this guide, that means all the example output will have to mention 6.0.0 in it instead of 5.1.x or 5.2.x.

I'm going to defer the final judgment to someone else though.

r? @matthewd

**Comment by yhirano55** [comment]
@sikachu I perfectly agree with you👍 I thought better to close this PR. But I'll wait the comment from core member.

**Comment by rafaelfranca** [comment]
Yes. In the past we were avoiding to change the version exactly because of those reasons. Thank you for the PR.

**Comment by yagudaev** [comment]
> Given this does not improve the content (but just give the reader the idea that the content is up-to-date) ... I'm not really sure if this is a good idea.

This reminds me the argument often used not to improve the visual design of a system. Giving the feeling the content is up-to-date generates trust in the reader. Thus, it improves their engagement with the content and it is worthwhile to spend an extra 5 mins to update the guides.

> master is targeting 6.0. If it's okay to update this guide, that means all the example output will have to mention 6.0.0 in it instead of 5.1.x or 5.2.x.

That makes sense too.
-------------

The only reason I noticed the older version is because I was trying to give a JR developer some reference material. Shouldn't newcomers always start with the latest and greatest? They don't need to know the baggage of older versions, just newest.

**Pull request closed without merging**
