### PR TITLE
Fix URL for TIP about database permission problems in Testing Guides [ci-skip]

### PR DESCRIPTION
**Pull request by ytjmt**
### Detail

[Testing Guides](https://edgeguides.rubyonrails.org/testing.html#fixtures-in-action) has a dead link: http://blog.endpoint.com/2012/10/postgres-system-triggers-error.html
As described [here](https://www.endpointdev.com/blog/2021/10/moving-to-endpointdev-dot-com/), the post has been moved to https://www.endpointdev.com/blog/2012/10/postgres-system-triggers-error/

The original content is archived: 
https://web.archive.org/web/20170910195345/http://blog.endpoint.com:80/2012/10/postgres-system-triggers-error.html

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.
* [x] CI is passing.

### CODE REVIEW

**Comment by eileencodes** [comment]
Do you know if there is a more recent resource that explains this? I think it'd be better to link directly to the Postgres documentation instead of a relatively old blog post.

**Comment by ytjmt** [comment]
Thanks for the comment. Is this suitable?
https://www.postgresql.org/docs/current/sql-altertable.html

> - Description
>   - DISABLE/ENABLE [ REPLICA | ALWAYS ] TRIGGER
>     - Disabling or enabling internally generated constraint triggers requires superuser privileges; it should be done with caution since of course the integrity of the constraint cannot be guaranteed if the triggers are not executed.
> - Parameters
>   - ALL
>     - Disable or enable all triggers belonging to the table. (This requires superuser privilege if any of the triggers are internally generated constraint triggers such as those that are used to implement foreign key constraints or deferrable uniqueness and exclusion constraints.)

**Comment by eileencodes** [comment]
Yup, that link looks good!

**Comment by ytjmt** [comment]
@eileencodes Thanks, I updated the link!

**Pull request merged**
