### PR TITLE
Fix dockerfile syntax version

### PR DESCRIPTION
**Pull request by iuhoay**
### Motivation / Background

`COPY --link` is add in `docker/dockerfile:1.4`

https://docs.docker.com/engine/reference/builder/#copy---link

### CODE REVIEW

**Comment by yahonda** [comment]
Closing this pull request because `docker/dockerfile:1` can use `COPY --link` as explained.
Thank you for your pull request. I am looking forward to future contributions.

**Comment by iuhoay** [comment]
```
ERROR (SSHKit::Command::Failed): docker exit status: 256
docker stdout: Nothing written
docker stderr: #1 [internal] load .dockerignore
#1 transferring context: 756B done
#1 DONE 0.0s

#2 [internal] load build definition from Dockerfile
#2 transferring dockerfile: 1.85kB done
#2 DONE 0.0s

#3 resolve image config for docker.io/docker/dockerfile:1
#3 DONE 0.0s

#4 docker-image://docker.io/docker/dockerfile:1
#4 CACHED
Dockerfile:25
--------------------
  23 |
  24 |     # Install application gems
  25 | >>> COPY --link Gemfile Gemfile.lock ./
  26 |     RUN bundle install && \
  27 |         rm -rf ~/.bundle/ "${BUNDLE_PATH}"/ruby/*/cache "${BUNDLE_PATH}"/ruby/*/bundler/gems/*/.git && \
--------------------
ERROR: failed to solve: dockerfile parse error on line 25: unknown flag: link
```

Yes, I agree that `docker/dockerfile:1` is correct.

But when I build the image on my own machine, it's not correct.

@yahonda

**Comment by iuhoay** [comment]
I found the reason.
Docker mirror cached the old version for `docker/dockerfile:1`.
It's running right now.

**Comment by rubys** [comment]
FYI:

In Rails, there is a pull request to revert the `--link` change: https://github.com/rails/rails/pull/47546

In [dockerfile-rails](https://github.com/rubys/dockerfile-rails#readme), `--no-link` is an option.

**Pull request closed without merging**
