### PR TITLE
Document string database values as supported by ActiveRecord::Enum

### PR DESCRIPTION
**Pull request by jrochkind**
Many people would like to use ActiveRecord::Enum, but with string values in the database instead of integers. You get all the API of Enum (restricted values, automatically generated query methods and scopes), but with more human-readable database values, and hypothetically some tradeoff in somewhat decreased performance and increased disk storage. Many would like to make that trade-off, you can find various StackOverflow questions over the years, etc. 

Interestingly, this already seems to work just fine in ActiveRecord::Enum, and there are even test cases for it since 67c1719012 (in releases since Rails 5.0.0.beta2).  

But it's un-doc'd. 

This PR adds it to the docs, and by implication 'offiically' supports it. 

Interestingly, in my tests, this also works fine as a cover for a Postgres Enumerated Type (and probably any other database in which ActiveRecord adapter exposes the enumerated type equivalent as if it were a string).   This is actually pretty useful, and part of what motivates this. The Postgres Guide says  "Currently there is no special support for enumerated types. They are mapped as normal text columns." -- which is true technically, but in fact you can use an ActiveRecord::Enum (mapping to string db values) on the top too if it's API is useful to you. But I did not mention that in the doc PR, it would require more analysis and testing. One step at a time.

### CODE REVIEW

**Comment by sgrif** [comment]
This is left out of the documentation because while it happens to work, this isn't something that we want to explicitly support, and reserve the right to break in the future.

**Comment by jrochkind** [comment]
I didn't have the chance to write out my case for it before you closed it, wish I had, but probably wouldn't have convinced you anyway. 

This doesn't make a lot of sense to me, especially since there are in fact test cases for it. 

Interestingly, it also works with backend database type defined as a postgres enumerated type, which is awfully useful. 

I don't really understand why you would not want to commit to supporting this, when it is so useful and works just fine. 

But okeydoke, you're the committers!

**Comment by maschwenk** [comment]
@jrochkind one thing I've noticed is that in certain situations, using the string implementation is actually broken. For instance:

```
class User < ActiveRecord::Base
  enum privilege: { admin: 'admin', viewer: 'viewer', guy: 'guy' }
  scope :not_admin, lambda {
      where(privilege:
           privilege.values_at(:guy, :viewer)
       )
  }
end
....

listOfUsers  = User.not_admin
newGuy = listOfUsers.new  # ArgumentError: '["guy", "viewer"]' is not a valid privilege 5.0.0.1/lib/active_record/enum.rb:137:in `assert_valid_value'
```

**Comment by jrochkind** [comment]
@maschwenk does that work with integer values?  Are you sure it's related to the string values?

**Comment by maschwenk** [comment]
@jrochkind Apologies, I think it's actually an issue with integers as well...not sure why

**Comment by dnasseri** [comment]
@sgrif In my humble opinion, it seems a little strange that this was a feature discussed in the original PR which introduced support for enums, and seemed to have support: https://github.com/rails/rails/commit/db41eb8a6ea88b854bf5cd11070ea4245e1639c5#commitcomment-4496449.

Later in this PR: https://github.com/rails/rails/pull/12747 the functionality was added possibly as a "side effect", but I think this functionality is really quite useful for two reasons.

1. It improves searchability/discoverability as previously mentioned.2
2. It makes the migration path from code that looks like this:

```
ANIMAL_ENUM  = ['COW', 'CAT', 'DOG']

validates :animal,
  inclusion: { in: Proc.new{ |_| ANIMAL_ENUM } },
  allow_blank: true
```

to using enums really straight forward. Apologies if this is not the correct place for this request, but would you consider making this a first class feature? We would like to use this functionality in our application, but do not want to expose ourselves to what might be a significant breaking change.

Thanks so much.

**Comment by alassek** [comment]
@jrochkind @dnasseri I decided to take matters into my own hands. Feedback welcome.

https://github.com/alassek/activerecord-pg_enum

**Pull request closed without merging**
