### PR TITLE
user form with instead of form for in scaffold generator

### PR DESCRIPTION
**Pull request by chukitow**
According to this http://weblog.rubyonrails.org/releases/#unify-form_tagform_for-with-form_with form_tag & form_for were unified in form_with, but the scaffold generator is still using form_for so I modified the template to use form_with 😬

### CODE REVIEW

**Comment by y-yagi** [comment]
:+1:

However, in the present code, I think that processing in case of error in the form will not work properly. 
This is because `form_with` defaults to `remote: true`, but now the scaffold code does not correspond to remote processing.

**Comment by chukitow** [comment]
You are right, I just disable remote submits.

**Comment by kaspth** [comment]
Rocking! Thanks!

**Comment by rafaelfranca** [comment]
Backported to 5-1-stable at d3b798b087

**Pull request merged**
