### PR TITLE
Bust ActiveSupport::TimeZone.all cache

### LINKED ISSUE #7245: Inconsistent output from ActiveSupport::TimeZone.all
Due to caching, `ActiveSupport::TimeZone.all` returns different results if a non-ActiveSupport-supported zone was looked up first. 

```
ActiveSupport::TimeZone.all
# not in ActiveSupport::TimeZone::MAPPING, but still a valid zone
chicago = ActiveSupport::TimeZone['America/Chicago']
ActiveSupport::TimeZone.all.include?(chicago)
=> false
```

```
chicago = ActiveSupport::TimeZone['America/Chicago']
ActiveSupport::TimeZone.all.include?(chicago)
=> true
```

This affects `time_zone_options_for_select`, in that the `selected` arg of that function is a string matched to the names of zones in `ActiveSupport::TimeZone.all`. If your app stores timezones in TZInfo format, the helper may not generate an option tag for a recognized zone.

I see two ways around this:
1. Change the helper to recognize TZInfo identifiers
2. Update the zones cache when lazy-loading time zones.

Changing the helper might unintentionally change your data ("America/Chicago" would get converted to "Central Time"). It seems like Rails is opinionated about what zones it wants to use, so that might not be a big deal. The second approach avoids that problem, but still requires you to look up the alternate zone before it shows up in the list.

Thoughts?

### PR DESCRIPTION
**Pull request by composerinteralia**
Fixes #7245 as discussed in #22651.

### CODE REVIEW

**Comment by composerinteralia** [comment]
@maclover7 any thoughts? Also feel free to use any part of this on your branch if you prefer. I am poking around in lots of issues just to get more familiar with the codebase, but I know you had already come up with a possible solution.

**Review by rafaelfranca — APPROVED** [review]
Could you add a CHANGELOG entry?

**Comment by composerinteralia** [comment]
[ci skip]

**Comment by composerinteralia** [comment]
@rafaelfranca done!

**Comment by jeremy** [comment]
This is weird behavior too. Is AS::TimeZone.all really a cache of all timezones that have every been looked up? Or is it a stable collection of the AS timezones in MAPPING?

**Comment by jeremy** [comment]
Alternatively,
```ruby
def all
  @all ||= MAPPING.transform_values { |tz_identifier| find_tzinfo tz_identifier }
end
```

**Comment by rafaelfranca** [comment]
> Is AS::TimeZone.all really a cache of all timezones that have every been looked up? Or is it a stable collection of the AS timezones in MAPPING?

This is a good question. Historically it is being a cache of all timezones in MAPPING and the timezone at tzinfo database that were being looked up. Making it a stable collection of timezones in MAPPING seems to be a better behavior but since the [Action View helpers make use of `.all`](https://github.com/rails/rails/blob/92703a9ea5d8b96f30e0b706b801c9185ef14f0e/actionview/lib/action_view/helpers/form_options_helper.rb#L572) people will always want to change MAPPING.

We may need to think in a way to extend this MAPPING.

**Comment by composerinteralia** [comment]
https://github.com/rails/rails/pull/31176

**Pull request closed without merging**
