### PR TITLE
[ci skip] Fix database.yml example in multiple databases Rails Guide

### PR DESCRIPTION
**Pull request by ryu39**
### Summary

I studied Rails multiple databases feature by following [Multiple Databases with Active Record Rails Guide](https://guides.rubyonrails.org/active_record_multiple_databases.html).
For working multiple databases in my local environment, some fixes are required in `database.yml`.
So I created this PR.

Here is the changes.

* Fix the key name `:user` to `:username`. This is a required fix.
* Add `*default` reference and `:password`.
  * These configuration are copied from default `database.yml` generated by `rails new` command.
  * `:password` is almost required.
  * `*default` reference is also better to be added because it has `:pool` and `:encoding` configurations.
* Add `:host`.
  * This is not required, but in most cases, `:host` are different from each databases. So I added.

If unnecessary changes are included in this PR, I'll fix or remove it.

#### Before

image

image

#### After

image

image

### CODE REVIEW

**Review by eileencodes — CHANGES_REQUESTED** [review]
Can you remove `host` and `default`? If everything is included in the example it will be harder for someone to determine what is required to make a config work for multiple databases. In this case those requirements are `username` and `replica`.

**Comment by ryu39** [comment]
@eileencodes Thank you for reviewing.

I removed `default` reference and `:host`. Please review again.

Here is the result after changes.

image

**Comment by eileencodes** [comment]
There was a conflict so I fixed it and merged manually on the command line in fc20050ea69ba3b8d8bc90171d2dcbf93e9a1dae. Backported  to 6-1-stable in 860b0970add4b3e7336aa9c7c2c5bd23c3760277

**Comment by ryu39** [comment]
I understand this issue was fixed in another commit.
Thank you for fixing this issue!!

**Pull request closed without merging**
