### PR TITLE
Improve Action Cable reconnection reliability

### PR DESCRIPTION
**Pull request by lifo**
There three improvements here:
1. Treat "closing" state as "closed" when attempting to reconnect from the client side. We had tons of issues where websocket connections somehow get stuck in the "closing" state, which would prevent automatic reconnection and require a reload.
2. Add client side logging to make it easier to debug client side connection issues. This is turned off by default, but can be turned on with calling `ActionCable.startDebugging()` from inside your application's javascript.
3. Makes sure the client side `ActionCable.ConnectionMonitor#connected()` gets called upon successful websocket connection.

### CODE REVIEW

**Comment by maclover7** [comment]
Can you try to squash down your commits?

**Comment by lifo** [comment]
What's the benefit of squashing the commits?

**Comment by jeremy** [comment]
No need to squash so long as the commits are atomic changes that can be independently reverted.

Would rebase out the faye-websocket switch+revert and the master merge. Keep the git history free of merge loops where we can.

**Comment by lifo** [comment]
@jeremy Yeah, I thought about removing those faye-websocket switch+revert commits. But it can be useful in case we want to revert that change in the master branch. The previous revert commit was very out of date. But I can swing either ways.

**Comment by rafaelfranca** [comment]
This looks good to me but I agree with rebasing to remove those three commits.

**Pull request merged**
