### PR TITLE
Do not enable disabled elements during Turbolinks redirects

### LINKED ISSUE #29473: rails-ujs prematurely enables disabled elements for XHR requests with redirects
### Steps to reproduce

```
rails new rails-ujs-test
```

```
# config/routes.rb

Rails.application.routes.draw do
  resources :users
end
```

```
# app/controllers/users_controller.rb

class UsersController < ApplicationController
  def index
    sleep 2
  end

  def new
  end

  def create
    sleep 2
    redirect_to users_path
  end
end
```

```
# app/views/users/new.html.erb

<h1>Users#new</h1>

<%= form_with url: users_path do |form| %>
  <%= form.submit "Create user", data: { disable_with: "Creating user..." } %>
<% end %>
```

```
# app/views/users/index.html.erb

<h1>Done!</h1>
```

Start the server, visit http://localhost:3000/users/new and click on the submit button.

### Expected behavior

When the form is submitted, the submit button should be disabled until the redirect action finishes. This is the behaviour which happens for non-XHR requests.

### Actual behavior

The submit button is disabled during the `create` action. But the `create` action redirects us to the `index` action and button is enabled again in the meantime.

This is caused by combination of rails-ujs and Turbolinks.

`redirect_to users_path` is automatically converted to

```
Turbolinks.clearCache()
Turbolinks.visit("http://localhost:3000/users", {"action":"replace"})
```

for XHR requests. This is a HTTP 200 reply and when rails-ujs receives it, then it enables the button again which allows users to click on it again. This is happening in our real world app even if the responses are pretty fast.

You can see it here:

ujs-test

I've reported this issue to the original rails-ujs repository some time ago. But it doesn't exist anymore and I can't reference the original report. However, I've tried to fix it, but I did not find a workable solution. It should be probably fixed in rails-ujs which shouldn't enable elements again if a response contains `Turbolinks.visit`.

### System configuration
**Rails version**: 5.1.1 and `master` branch

**Ruby version**: 2.4.1p111

**Turbolinks version**: 5.0.1

### PR DESCRIPTION
**Pull request by mrhead**
Fixes: #29473.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
I don't think rails-ujs should know that Turbolinks exists. I'm fine with rails-ujs providing hooks so turbolinks can use, but if something needs to know about turbolinks is turbolinks itself. Could you investigate how to solve this at turbolinks side?

**Comment by mrhead** [comment]
That makes sense. I'll try to play with it later.

**Comment by mrhead** [comment]
I've just added rails-ujs tests.

**Comment by mrhead** [comment]
Closed in favour of: https://github.com/rails/rails/pull/31441.

**Pull request closed without merging**
