### PR TITLE
Implemented #cache_version conventional method

### PR DESCRIPTION
**Pull request by bogdan**
Implemented `#cache_version` conventional method for the default cache `version` option value.

Examples:

``` ruby
Rails.cache.fetch(["post_preview", post])
Rails.cache.fetch(["post_preview", post, post.author]) 

class Post
  def cache_key
     "posts/#{id}"
  end
  def cache_version
    updated_at
  end
end
```

### CODE REVIEW

**Comment by dhh** [comment]
To flesh this out, you'll need to consider backwards compatibility with the keys generated by the cache and what to do about the fact that cache_key currently includes the updated_at version for ARs.

**Comment by dhh** [comment]
If we make the presence of the #cache_version method the trigger for #cache_key only returning the stable key, then we avoid the backwards incompatibility problem. Want to take a stab at that?

**Comment by kaspth** [comment]
@bogdan you still want to pursue this version further or is the merged version better now? 😊

**Comment by bogdan** [comment]
Merged has all the ideas from here.

**Pull request closed without merging**
