### PR TITLE
Fix `NoMethodError` when testing content_type of `nil`

### PR DESCRIPTION
**Pull request by rubendinho**
### Motivation / Background

This Pull Request has been created because if a test case sets `request.content_type = nil`, the test will raise an unexpected `NoMethodError` since the `when nil` case is not reachable.

### Detail

This Pull Request changes the `content_type` check in `GET` requests. 

### Additional information

I did not see relevant tests for this functionality, but I'm not sure if they're needed given what this is touching. 

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [ ] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by zzak** [comment]
I'm definitely probably missing some context here, but not seeing any tests explicitly for `assign_parameters` and it looks like this class might be deprecated in the future:
https://github.com/rails/rails/blob/99096b88ae7a7c9019f2cbcf867e29ba42768e65/actionpack/lib/action_controller/test_case.rb#L32-L33

> ActionController::TestCase will be deprecated and moved to a gem in the future.

RE: relevant tests, this might be one place to look:
https://github.com/rails/rails/blob/main/actionpack/test/controller/test_case_test.rb

**Comment by jeromedalbert** [comment]
@rubendinho Is this still an issue? If so, can you provide some reproduction steps? https://github.com/rails/rails/blob/main/guides/bug_report_templates/action_controller.rb

**Comment by rubendinho** [comment]
> @rubendinho Can you confirm this is still an issue? If so, can you provide a reproduction script so I can easily repro? https://github.com/rails/rails/blob/main/guides/bug_report_templates/action_controller.rb

@jeromedalbert here you go: 

```rb
require 'rails_helper'

RSpec.describe API::BaseController, type: :controller do
  controller do
    def action
      render :ok
    end
  end

  before do
    routes.draw do
      post :action, to: 'api/base#action'
    end
  end

  describe 'content-type header check' do
    let(:action) { post :action }

    context 'with Content-Type: nil' do
      before { request.content_type = nil }

      it { expect { post :action }.not_to raise_error }
    end
  end
end
```

Also note that `.to_sym` cannot return `nil`, so the `nil` branch in the conditional is unreachable: https://github.com/rails/rails/pull/47598/files#diff-830266b353d76aacab4b00ae785f171b94dc1f9370202aa173ba386b502b6991R108-R109

**Comment by jeromedalbert** [comment]
Here is a self-contained reproduction script based on Ruben's code snippet.

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'rails'
  gem 'rspec-rails'
end

require 'rails'
require 'action_controller/railtie'
require 'rspec/rails'

class MyApp < Rails::Application
  config.eager_load = false

  routes.append { post :create, to: 'test#create' }
end

RSpec.configure { |config| config.full_backtrace = true }

MyApp.initialize!

class TestController < ActionController::Base
  def create
    head :created
  end
end

describe TestController, type: :controller do
  describe '#create' do
    before do
      request.content_type = nil

      post :create
    end

    it { expect(response).to have_http_status(:created) }
  end
end

RSpec::Core::Runner.run([$__FILE__])
```

I can repro the error with the following backtrace:

```
Failure/Error: post :create

NoMethodError:
  undefined method `to_sym' for nil
# /Users/jerome/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/actionpack-7.2.1/lib/action_controller/test_case.rb:109:in `assign_parameters'
# /Users/jerome/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/actionpack-7.2.1/lib/action_controller/test_case.rb:602:in `setup_request'
# /Users/jerome/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/actionpack-7.2.1/lib/action_controller/test_case.rb:540:in `process'
# /Users/jerome/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/actionpack-7.2.1/lib/action_controller/test_case.rb:438:in `post'
# repro.rb:35:in `block (3 levels) in <main>'
...
```

The error comes from `ActionController::TestCase#assign_parameters`. For context, rspec-rails controller tests [include](https://github.com/rspec/rspec-rails/blob/01704c50c146f720db914724c25681781ecefb23/lib/rspec/rails/example/controller_example_group.rb#L13) `ActionController::TestCase::Behavior` which has methods like [`post`](https://github.com/rails/rails/blob/3997ed6ae4e65cc092d68c8316e06a082dc9026c/actionpack/lib/action_controller/test_case.rb#L439) which ultimately [create](https://github.com/rails/rails/blob/3997ed6ae4e65cc092d68c8316e06a082dc9026c/actionpack/lib/action_controller/test_case.rb#L520) the `TestRequest` object.

This PR changes the `TestRequest` object by using `content_mime_type&.to_sym`. When I run the self-contained script with Ruben's PR changes on my local (`gem 'rails', path: '~/path_to_my_local_rails'`), it goes past this error and now raises the following:

```
Failure/Error: post :create

RuntimeError:
  Unknown Content-Type:
# /Users/jerome/c/rails/actionpack/lib/action_controller/test_case.rb:113:in `assign_parameters'
# /Users/jerome/c/rails/actionpack/lib/action_controller/test_case.rb:604:in `setup_request'
# /Users/jerome/c/rails/actionpack/lib/action_controller/test_case.rb:542:in `process'
# /Users/jerome/c/rails/actionpack/lib/action_controller/test_case.rb:440:in `post'
# repro.rb:35:in `block (3 levels) in <main>'
...
```

Is this what you are expecting @rubendinho? Trading an obscure `undefined method `to_sym' for nil` error for a clearer `Unknown Content-Type:` error?

**Comment by jeromedalbert** [comment]
PS: this is only an issue with `ActionController::TestCase` and rspec-rails controller tests.

If I do the following Rails integration/functional test, there is no error:

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'rails'
end

require 'rails'
require 'action_controller/railtie'
require 'minitest/autorun'
ENV['RAILS_ENV'] = 'test'

class MyApp < Rails::Application
  config.eager_load = false

  routes.append { post 'create', to: 'test#create' }
end

MyApp.initialize!

class TestController < ActionController::Base
  def create
    head :created
  end
end

class TestControllerTest < ActionDispatch::IntegrationTest
  def test_create
    post '/create', headers: { 'Content-Type': nil }

    assert_response :created
  end
end
```

Presumably the header gets ignored or something. If I explicitly set `'Content-Type': ''` then I get a `<406: Not Acceptable>` error. Makes sense.

**Comment by rubendinho** [comment]
> Is this what you are expecting with this PR @rubendinho? Trading a slightly obscure undefined method 'to_sym' for nil error for a clearer Unknown Content-Type: error?

This is not an issue for us anymore but I think this is what I expect Rails to do in this scenario

**Comment by jeromedalbert** [comment]
Ok, if you want to complete this PR I think a unit test is needed. Would copy/pasting a test like this work, but using `nil` instead of `""`?

https://github.com/rails/rails/blob/15ddce90583bdf169ae69449b42db10be9f714c9/actionpack/test/controller/test_case_test.rb#L610-L615

**Comment by rubendinho** [comment]
> Ok, if you want to complete this PR I think a unit test is needed. Would copy/pasting a test like this work, but using `nil` instead of `""`?
> 
> 
> 
> https://github.com/rails/rails/blob/15ddce90583bdf169ae69449b42db10be9f714c9/actionpack/test/controller/test_case_test.rb#L610-L615

Yeah I think that makes sense. I am not going to be able to work on this for the next few weeks though, so if someone can pick this up, that would be amazing.

**Comment by jeromedalbert** [comment]
> so if someone can pick this up, that would be amazing.

I opened PR https://github.com/rails/rails/pull/53325.

**Pull request closed without merging**
