### PR TITLE
[ci skip] Add link with full list of options for S3-compatible services

### PR DESCRIPTION
**Pull request by ceritium**
### Summary

Add a link with a full list of options for S3-compatible services.

It was a bit hard for me to find the proper configuration for "minio" (S3-compatible), so I guess it would help others.

### CODE REVIEW

**Comment by ghiculescu** [comment]
Does this work with Active Storage out of the box? I don't see `minio` as an included service: https://github.com/rails/rails/tree/main/activestorage/lib/active_storage/service

**Comment by zzak** [comment]
I think we should not add documentation for services that are not officially supported 🤔 but I could be missing some context here as I also have no idea what minio is..

**Comment by ceritium** [comment]
[minio](https://min.io) is a storage service compatible with S3 with a community edition. I thought that it was more popular. Some teams use it on production, of course, but also for development.

Maybe the problem is on the [AWS documentation](https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/setup-config.html) (linked in the guides), for me was not clear what options can I use until I found this [yard documentation](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Client.html#initialize-instance_method).

Since "minio" is just another s3 compatible service and the API can change, maybe it would make sense to point to the yard documentation and remove the "minio" example. I will push a more generic proposal later.

**Comment by ghiculescu** [comment]
@ceritium I think it would be better if this was updated in the AWS documentation directly. Do they accept PRs?

**Comment by ceritium** [comment]
@ghiculescu they accept PRs. I can try to improve their docs too. But in any case, I think that this PR can help to rails devs experience.

I just pushed a new approach. Let me know what do you think.

**Comment by ghiculescu** [comment]
Yep, I like that much better 👍

**Comment by zzak** [comment]
@ceritium Could you [squash your commits](https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#squashing-commits) please? :bow:

**Comment by ceritium** [comment]
> ould you [squash your commits](https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#squashing-commits) please? 🙇

I kept both commits to allow the review with all the context. I already squashed them and rephrased the commit. Thanks!

**Pull request merged**
