### PR TITLE
Require Ruby 2.2.3 due to broken Symbol GC in 2.2.2

### PR DESCRIPTION
**Pull request by deepj**
According to @ko1 (see his presentation on RubyConf Portugal 2015 — http://www.atdot.net/~ko1/activities/2015_RubyConfPortgual.pdf) Ruby 2.2.2 contains a bug in Symbol GC. Ruby 2.2.3 fixes the problem. Rails 5 would use non-broken version of Ruby 2.2.x when it relies on Symbol GC.

### CODE REVIEW

**Comment by matthewd** [comment]
[The issue in question](https://redmine.ruby-lang.org/issues/10933) sounds like a garden-variety bug to me.

Our advice is always going to be to run the latest patch release, but I don't see why this particular bug warrants us specifically refusing to run on 2.2.2.

**Comment by deepj** [comment]
@matthewd Because Rails 5 targets to Ruby 2.2+ and it also relies on Symbol GC (see https://twitter.com/dhh/status/548198789954023424). And in Ruby 2.2.2 there is obviously a bug in Symbol GC. If there is a change to crash Rails application due to the bug so (for me at least) it is a major problem to not use Ruby 2.2.2. But I can be wrong though.

**Comment by rafaelfranca** [comment]
We don't rely on Symbol GC. We don't have any code that expects Symbol GC to exist. We do force Ruby 2.2 because it avoids a whole class of security issue so we are forcing people to upgrade to Ruby 2.2, but that doesn't means that if Symbol GC has a bug Rails will not work.

That said I think we don't need to bump the requirement.

**Comment by deepj** [comment]
@rafaelfranca `We don't rely on Symbol GC.` Please Mr. Franca, can you please explain these @dhh tweets? Thank you.
screen shot 2015-09-15 at 00 00 26
screen shot 2015-09-15 at 00 01 18

**Comment by rafaelfranca** [comment]
Like I said: "We do force Ruby 2.2 because it avoids a whole class of security issue so we are forcing people to upgrade to Ruby 2.2, but that doesn't means that if Symbol GC has a bug Rails will not work."

Rails itself don't rely on it (ie. there is no `to_sym` calls in Rails code), but we want to applications to rely if they want to.

**Comment by deepj** [comment]
https://github.com/rails/rails/search?utf8=%E2%9C%93&q=to_sym

**Comment by rafaelfranca** [comment]
ie. there is no `to_sym` calls on user input in Rails code

**Comment by matthewd** [comment]
@deepj I read the issue. It is a *bug* in symbol GC, not a leak... and only affects a process when it's shutting down. So even if we were relying on symbol GC, that would not be a cause for concern.

There will always be bugs in older versions of Ruby (like any software) -- that's why the newer versions get released.

**Comment by deepj** [comment]
@rafaelfranca 
> ie. there is no to_sym calls on user input in Rails code
And what `cookies` for example? In Rails Cookie code is used `symbolize_keys` if I'm not wrong.

Then some people report issues with `Ruby 2.2.2` and `Rails 4.x`
https://redmine.ruby-lang.org/issues/11168
https://redmine.ruby-lang.org/issues/10968

Related bugs with Symbol GC. Of course, the problem is not caused by Rails itself. But combination Ruby 2.2.2, Rails, something else. It's better to force to use `Ruby 2.2.3` because it _would_ be without the Symbol GC bug.

@matthewd Thank you for the argument. Accepted.

**Pull request closed without merging**
