### PR TITLE
Reset the values of virtual columns when making a dup of a record

### PR DESCRIPTION
**Pull request by asok**
This change makes sense for adapters which support "virtual" columns. That means
it only applies to MySQL adapter at the moment.

### Summary

Currently on MySQL if virtual column has a value, when we dup the corresponding record the value is not reset. That will cause an error to be raised when we try to save the clone.
In my PR there's a test example that demonstrates that.

I'm not familiar with the codebase good enough to judge if `ActiveRecord::Core#initialize_dup` is the right place to put such change. If it's not, then this PR might serve as a bug report.

### CODE REVIEW

**Review by Tomy0498 — APPROVED** [review]

**Comment by jonathanhefner** [comment]
Although `record.dup.id == nil` (and likewise for timestamps), I think it may be surprising if `record.some_field != record.dup.some_field`.

Another way to handle this might be to filter out virtual columns in [`attributes_for_create`](https://github.com/rails/rails/blob/09ff877610a09d930ca84a94113f678d4e79e100/activerecord/lib/active_record/attribute_methods.rb#L394).  Although, as a consequence, there would be no error from trying to assign a value to a virtual column on creation.

@kamipo What do you think about this?

**Comment by asok** [comment]
> Although record.dup.id == nil (and likewise for timestamps), I think it may be surprising if record.some_field != record.dup.some_field.

Indeed, I haven't thought about it. The only improvement I can think of is to update the docs for `initialize_dup` method.

> Another way to handle this might be to filter out virtual columns in attributes_for_create. Although, as a consequence, there would be no error from trying to assign a value to a virtual column on creation.

Actually I think that's a better approach. Not having error when assigning a virtual column on creation, from mine, "user" perspective seems fine.

**Comment by kamipo** [comment]
> Another way to handle this might be to filter out virtual columns in [`attributes_for_create`](https://github.com/rails/rails/blob/09ff877610a09d930ca84a94113f678d4e79e100/activerecord/lib/active_record/attribute_methods.rb#L394).  Although, as a consequence, there would be no error from trying to assign a value to a virtual column on creation.

Yeah, it is fine to me.

**Comment by timkrins** [comment]
Fixed via the `attributes_for_create` and `attributes_for_update` method in https://github.com/rails/rails/pull/43263

**Pull request closed without merging**
