### PR TITLE
Backports ruby 3.2 compatibility fixes for rails 6.1

### PR DESCRIPTION
**Pull request by javiyu**
Fixes https://github.com/rails/rails/issues/46883

### Motivation / Background

Ruby 3.2 deals with kwargs differently than previous versions, that causes some rails code paths trigger errors like:

```
ArgumentError: wrong number of arguments (given 1, expected 0; required keyword: user)
``` 

Those problems are fixed in rails 7, this PR aims to backport those changes to rails 6.1.
[This](https://github.com/rails/rails/pull/44850) is the original PR where these changes were introduced.

### CODE REVIEW

**Comment by skipkayhil** [comment]
This breaks tests for Ruby 2.5 and Ruby 2.6 which don't have ruby2_keywords or ... delegation. For ruby2_keywords you'll need to add a respond_to check, and you won't be able to use ...

**Comment by javiyu** [comment]
> This breaks tests for Ruby 2.5 and Ruby 2.6 which don't have ruby2_keywords or ... delegation. For ruby2_keywords you'll need to add a respond_to check, and you won't be able to use ...

I have made it compatible with older versions of ruby, code is a bit verbose but I think it is the easiest way to identify on upcoming releases the patches introduced for older ruby versions. Happy to solve it in another way if you think there is any better one.

**Comment by yahonda** [comment]
Rails 6.1.Z only provides security issue fixes, so I do not think we can backport Ruby 3.2 support to the 6-1-stable branch. https://guides.rubyonrails.org/maintenance_policy.html#security-issues

**Comment by eileencodes** [comment]
@yahonda we discussed this on the issue. We're not going to do a release but we will do backports to fix Ruby version related bugs if someone is willing to do the work.

In addition, CI is failing so it's a good idea to backport this so that CI is passing when we need to do a security release.

**Comment by eileencodes** [comment]
Thank you @javiyu!

**Comment by zzak** [comment]
> In addition, CI is failing so it's a good idea to backport this so that CI is passing when we need to do a security release.

After seeing the discussion in discord I spent a few hours yesterday to try and get `6-1-stable` running but gave up. It's really important that maintained branches are green to ensure a security release goes smoothly IMO.

I was excited to see all the activity on this branch but it looks like the branch is still [failing](https://buildkite.com/rails/rails/builds?branch=6-1-stable) :(

**Comment by yahonda** [comment]
Understood. Thanks for the explanation.

**Comment by eileencodes** [comment]
> I was excited to see all the activity on this branch but it looks like the branch is still [failing](https://buildkite.com/rails/rails/builds?branch=6-1-stable) :(

@zzak I am working on it, this is fixing just one type of the many failures. Let's not clog up this PR with discussion of those since it's unrelated.

**Comment by gregg-platogo** [comment]
> > I was excited to see all the activity on this branch but it looks like the branch is still [failing](https://buildkite.com/rails/rails/builds?branch=6-1-stable) :(
> 
> @zzak I am working on it, this is fixing just one type of the many failures. Let's not clog up this PR with discussion of those since it's unrelated.

@eileencodes @rafaelfranca I'm a bit confused with what happened to this backport. I know as of September Rails 6.1.X is no longer supported for bug fixes. It was originally backported to Rails 7 in April. Why didn't you backport it to 6.1 then?

In the end the question is if  you're going to release that as `Rails 6.1.8`?

**Comment by eileencodes** [comment]
> Why didn't you backport it to 6.1 then?

Because we weren't supporting 6.1 for bug fixes and Ruby 3.2 wasn't out yet. But as Rafael [said on the issue](https://github.com/rails/rails/issues/46883#issuecomment-1371325906) if folks are willing to do the work to backport we will consider merging if it's adding support for a Ruby version.

> In the end the question is if you're going to release that as Rails 6.1.8?

No we are not going to release a 6.1.8, you can point your application at the 6-1-stable branch or upgrade to 7.0.x.

**Comment by gregg-platogo** [comment]
> No we are not going to release a 6.1.8, you can point your application at the 6-1-stable branch or upgrade to 7.0.x.

Fair enough! Thanks for the answer

**Comment by suhasg** [comment]
@eileencodes does Rails 6-1-stable supported with security patches going ahead? 
And what would be the EOL date for the 6-1-stable? These decisions are critical for the current release of our project.
Thank you.

**Comment by eileencodes** [comment]
Our security policy is on the website https://guides.rubyonrails.org/maintenance_policy.html#security-issues

6.1 is not getting anymore releases unless it's a severe vulnerability and will be EOL next June. I probably wouldn't write a new application on 6.1 at this point.

**Comment by tsukasaoishi** [comment]
@eileencodes 

> will be EOL next June

Is it certain that Rails 6.1 will reach EOL (end of life) next June?

> 6.1 is not getting anymore releases unless it's a severe vulnerability

Until the release of Rails 8, it's correct to assume that Severe Security Issues for Rails 6.1 will still be addressed, right?

**Pull request merged**
