### PR TITLE
Implement ActiveRecord::Base.destroy_later

### PR DESCRIPTION
**Pull request by adrianna-chang-shopify**
### Summary

An updated implementation of https://github.com/rails/rails/pull/34901, with the changes from https://github.com/rails/rails/pull/39149 incorporated, as well as additional feedback from the latter included.

More information in [this issue](https://github.com/rails/actionmailbox/issues/16) pertaining to the concept of managing ActiveRecord object lifetimes.

`ActiveRecord::Base.destroy_later` allows records to be destroyed after a specified amount of time. Records are destroyed via an async job enqueued in an `after_commit` callback. A condition to be met in order to schedule the destruction of the record can be specified via a lambda in `if:` ; additionally, a condition that must be met at destroy time can be specified via `ensuring:`.

A follow up PR will be submitted to incorporate the remaining changes from https://github.com/rails/rails/pull/39149, which pertain to using `destroy_later` to perform association deletions asynchronously.

### CODE REVIEW

**Review by yoelblum — COMMENTED** [review]
Great work! Just in case you weren't aware, similar PR (WIP) here: https://github.com/rails/rails/pull/37025/files. The main difference I saw between them is the second one allows for association destroy.

**Comment by adrianna-chang-shopify** [comment]
Hey @yoelblum ! This PR is actually an updated implementation of https://github.com/rails/rails/pull/34901, which was an updated version of the PR you mentioned. An updated version of the rest of https://github.com/rails/rails/pull/34901 (the async association destroy part) is coming soon 😄

**Comment by gwincr11** [comment]
Thanks for moving this forward, if I can help in anyway let me know. ❤️

**Comment by adrianna-chang-shopify** [comment]
cc @rafaelfranca

**Comment by rafaelfranca** [comment]
Closing this PR since we decided to not implement the class level `destroy_later`. `dependent: :destroy_async` was implemented in #40157.

**Pull request closed without merging**
