### PR TITLE
Allow assert_recognizes and recognize_path to support url redirects from...

### PR DESCRIPTION
**Pull request by andrewferk**
Currently, there is no way to unit test the Redirection module in ActionDispatch::Routing. Also, redirects are not recognized as paths using `recognize_path`. These problems lead to a potential false positive. If you have this routing:

``` ruby
get 'help' => redirect('http://help.example.org/')
get 'help' => 'help#index'
```

and this test:

``` ruby
test "should recognize /help as help#index" do
  assert_recognizes({:controller => 'help', :action => 'index'}, '/help')
end
```

the test passes, but actually, it should recognize /help as a redirect.

With this commit, it fixes the false negative and allows for url redirection:

``` ruby
get 'help' => redirect("http://example.org/")
assert_recognizes("http://example.org/", "/help")
```

This is just a start to fix this issue, as the Redirection module offers much more than just external url redirection. Would definitely be willing to discuss other ways to unit test redirection; however, i think it is a bug that assert_recognizes does not recognize redirection routes.

More referenced <a href="https://github.com/rails/rails/issues/2488">here</a>.

### CODE REVIEW

**Comment by mrageh** [comment]
@pixeltrix and @rafaelfranca any updates on this PR, do we still want it in Rails 5?

**Comment by jcoyne** [comment]
@mrageh I would really like it. (I'm not sure if that counts) Looks like this PR won't merge cleanly.

**Comment by maclover7** [comment]
@andrewferk are you interested in following up with this? I can try to rebase and move this forward if you would like :)

**Comment by oniofchaos** [comment]
@andrewferk there's been a couple major versions since you made this PR, is this still a needed feature?

**Pull request closed without merging**
