### PR TITLE
Patch verb

### PR DESCRIPTION
**Pull request by dlee**
_Update: as ncreuschling points out, there was a typo in the pull request message that said "HTML verb" instead of "HTTP verb"._

_Updated: update forms default to PUT instead of PATCH for current apps. Defaults to PATCH for new apps._

PATCH is the correct HTTP verb to map to the #update action. The semantics for
PATCH allows for partial updates, whereas PUT requires a complete replacement.

Changes:
- adds the #patch verb to routes to detect PATCH requests
- adds #patch? to Request
- adds the PATCH -> update mapping in the #resource(s) routes.
- changes default form helpers to prefer :patch instead of :put for updates _only for new apps_
- changes documentation and comments to indicate the preference for PATCH

This change tries to maintain complete backwards compatibility by keeping the
original PUT -> update mapping. Users using the #resource(s) routes should not
notice a change in behavior since both PUT and PATCH requests get mapped to
update.

### CODE REVIEW

**Comment by nextofsearch** [comment]
Hi @bf4,

Your patch doesn't work with my app. Rails 3.2.22.5

It crashes when running the web server with the following error:

> .rvm/gems/ruby-1.9.3-p551@rails3.2/gems/actionpack-3.2.22.5/lib/action_dispatch/routing/mapper.rb:178:in `default_controller_and_action': missing :action (ArgumentError)

When running 'rake routes'

> rake aborted!
ArgumentError: missing :action
/Users/danolee/.rvm/gems/ruby-1.9.3-p551@rails3.2/gems/actionpack-3.2.22.5/lib/action_dispatch/routing/mapper.rb:178:in `default_controller_and_action'

Any help will be greatly appreciated.

**Comment by nextofsearch** [comment]
@bf4. Never mind. I used the gist of @razum2um instead of your original one. Your gist works just fine. Thank you!

**Comment by SuShu19** [comment]
> Hi @bf4,
> 
> Your patch doesn't work with my app. Rails 3.2.22.5
> 
> It crashes when running the web server with the following error:
> 
> > .rvm/gems/ruby-1.9.3-p551@rails3.2/gems/actionpack-3.2.22.5/lib/action_dispatch/routing/mapper.rb:178:in `default_controller_and_action': missing :action (ArgumentError)
> 
> When running 'rake routes'
> 
> > rake aborted!
> > ArgumentError: missing :action
> > /Users/danolee/.rvm/gems/ruby-1.9.3-p551@rails3.2/gems/actionpack-3.2.22.5/lib/action_dispatch/routing/mapper.rb:178:in `default_controller_and_action'
> 
> Any help will be greatly appreciated.

A

**Comment by SuShu19** [comment]
> fwiw, I backported the HTTP PATCH verb work for Rails 3.2 https://gist.github.com/bf4/8940203

a

**Pull request closed without merging**
