### PR TITLE
Preserve collation when changing column in MySQL

### LINKED ISSUE #45742: `change_column_null` resets collation
`change_column_null` changes the column's collation to the table's default collation.

This bug is visible when changing a column whose collation differs from the table's default collation.

Tested with MySQL.

### Steps to reproduce
Run this migration:
```
class TestCase < ActiveRecord::Migration[7.0]
  def change
    create_table :utf8_table, id: :integer, charset: :utf8mb4, collation: :utf8mb4_unicode_ci do |t|
      t.string :utf8_col_1, collation: :utf8mb4_unicode_ci, null: false
      t.string :utf8_col_2, collation: :utf8mb4_unicode_ci, null: true
      t.string :ascii_col_1, collation: :ascii_general_ci, null: false
      t.string :ascii_col_2, collation: :ascii_general_ci, null: true
    end

    change_column_null :utf8_table, :utf8_col_2, false
    change_column_null :utf8_table, :ascii_col_2, false

    create_table :ascii_table, id: :integer, charset: :ascii, collation: :ascii_general_ci do |t|
      t.string :utf8_col_1, collation: :utf8mb4_unicode_ci, null: false
      t.string :utf8_col_2, collation: :utf8mb4_unicode_ci, null: true
      t.string :ascii_col_1, collation: :ascii_general_ci, null: false
      t.string :ascii_col_2, collation: :ascii_general_ci, null: true
    end

    change_column_null :ascii_table, :utf8_col_2, false
    change_column_null :ascii_table, :ascii_col_2, false
  end
end
```

The end result is that all columns should be NOT NULL. The `_col_1` columns are set to `NOT NULL` in `create_table`, and the `_col_2`  columns are changed later with `change_column_null`.

### Expected behavior
`change_column_null` should preserve the column's collation, so that the `_col_1` and `_col_2` definitions are identical even though the null-ness on `_col_2` columns was changed after the initial `create_table`.

The the table should look like this, so that `utf8_col_1` and `utf8_col_2` are defined identically in each table, and likewise for `ascii_col_1`/`ascii_col_2`:
```
CREATE TABLE `ascii_table` (
  `id` int NOT NULL AUTO_INCREMENT,
  `utf8_col_1` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `utf8_col_2` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `ascii_col_1` varchar(255) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
  `ascii_col_2` varchar(255) CHARACTER SET ascii COLLATE ascii_general_ci NOT ,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=ascii;

CREATE TABLE `utf8_table` (
  `id` int NOT NULL AUTO_INCREMENT,
  `utf8_col_1` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `utf8_col_2` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `ascii_col_1` varchar(255) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
  `ascii_col_2` varchar(255) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

### Actual behavior
The special `CHARACTER SET` and `COLLATE` directives are missing from the columns whose collation differs from the table default column.
```
CREATE TABLE `ascii_table` (
  `id` int NOT NULL AUTO_INCREMENT,
  `utf8_col_1` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `utf8_col_2` varchar(255) NOT NULL,
  `ascii_col_1` varchar(255) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
  `ascii_col_2` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=ascii;

CREATE TABLE `utf8_table` (
  `id` int NOT NULL AUTO_INCREMENT,
  `utf8_col_1` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `utf8_col_2` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `ascii_col_1` varchar(255) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
  `ascii_col_2` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

### System configuration
**Rails version**:
7.0.3

**Ruby version**:
3.1.2p20

### PR DESCRIPTION
**Pull request by fatkodima**
Fixes #45742.

### CODE REVIEW

**Review by byroot — APPROVED** [review]
LGTM. CI is super spotty today though, I restarted it.

**Comment by simi** [comment]
:muscle:

**Comment by byroot** [comment]
Backported to `7-0-stable` as d60d0587c3c10c891b717299ed052ded5658c20d

**Comment by ahoglund** [comment]
I'm getting this error:

```
COLLATION 'utf8_general_ci' is not valid for CHARACTER SET 'binary'
```

When the `change_column` is converting from a string type to binary type:

```ruby
def up
  change_column :column_name, :path, :binary, limit: 1024
end

def down
  change_column :column_name, :path, :string
end
```

This is because the collation is being preserved when in this case it shouldn't be. According to the [MySQL docs](https://dev.mysql.com/doc/refman/5.7/en/charset-binary-set.html) the `binary` type has only one collation also named `binary`.

I am not sure if there are other special cases that need to be considered like this for column changes. But it seems to me this should be accounted for in code so that migrations don't need to be updated to pass in the `collation: "binary"` arg to get this working.

**Pull request merged**
