### PR TITLE
Placing all ActiveRecord error classes within the same file structure rather than scattered

### PR DESCRIPTION
**Pull request by ch1ago**
WIP

@rafaelfranca 

common_errors.rb will still contain 15 errors 

I am also proposing dropping NestedAttributes::TooManyRecords in favor of a new un-nested TooManyNestedRecords

This is all still WIP and I have NOT completely formalized the commit or this text yet.

No errors or warnings were added.

``` ruby
class ActiveRecordError < StandardError
  class RecordInvalid
  class SubclassNotFound
  class SerializationTypeMismatch
  class AdapterNotSpecified
  class AdapterNotFound
  class ConnectionNotEstablished
  class RecordNotFound
  class RecordNotSaved
  class RecordNotDestroyed
  class StaleObjectError
  class ReadOnlyRecord
  class Rollback
  class ImmutableRelation
  class TransactionIsolationError
  class TransactionSerializationError
  class IrreversibleOrderError
  # module NestedAttributes
  #   class TooManyRecords
  class TooManyNestedRecords


  class UnknownAttributeError < ActiveModel::UnknownAttributeError
  class AttributeError
    class DangerousAttributeError < AttributeError
    class AttributeAssignmentError < AttributeError
    class MultiparameterAssignmentErrors < AttributeError
    class UnknownPrimaryKey < AttributeError



  class StatementInvalid
    class WrappedDatabaseException < StatementInvalid
    class RecordNotUnique < WrappedDatabaseException
    class InvalidForeignKey < WrappedDatabaseException
    class ValueTooLong < StatementInvalid
    class PreparedStatementInvalid
    class NoDatabaseError < StatementInvalid
    class PreparedStatementCacheExpired < StatementInvalid




  class MigrationError
    class IrreversibleMigration < MigrationError
    class DuplicateMigrationVersionError < MigrationError
    class DuplicateMigrationNameError < MigrationError
    class UnknownMigrationVersionError < MigrationError
    class IllegalMigrationNameError < MigrationError
    class PendingMigrationError < MigrationError
    class ConcurrentMigrationError < MigrationError
    class NoEnvironmentInSchemaError < MigrationError
    class ProtectedEnvironmentError < MigrationError
    class EnvironmentMismatchError < MigrationError



  class AssociationError
    class AssociationTypeMismatch < AssociationError
    class ConfigurationError < AssociationError
    class AssociationNotFoundError < AssociationError
    class InverseOfAssociationNotFoundError < AssociationError
    class HasManyThroughAssociationNotFoundError < AssociationError
    class HasManyThroughAssociationPolymorphicSourceError < AssociationError
    class HasManyThroughAssociationPolymorphicThroughError < AssociationError
    class HasManyThroughAssociationPointlessSourceTypeError < AssociationError
    class HasOneThroughCantAssociateThroughCollection < AssociationError
    class HasOneAssociationPolymorphicThroughError < AssociationError
    class HasManyThroughSourceAssociationNotFoundError < AssociationError
    class ThroughCantAssociateThroughHasOneOrManyReflection < AssociationError
    class HasManyThroughCantAssociateThroughHasOneOrManyReflection < ThroughCantAssociateThroughHasOneOrManyReflection
    class HasOneThroughCantAssociateThroughHasOneOrManyReflection < ThroughCantAssociateThroughHasOneOrManyReflection
    class HasManyThroughCantAssociateNewRecords < AssociationError
    class HasManyThroughCantDissociateNewRecords < AssociationError
    class ThroughNestedAssociationsAreReadonly < AssociationError
    class HasManyThroughNestedAssociationsAreReadonly < ThroughNestedAssociationsAreReadonly
    class HasOneThroughNestedAssociationsAreReadonly < ThroughNestedAssociationsAreReadonly
    class EagerLoadPolymorphicError < AssociationError
    class ReadOnlyAssociation < AssociationError
    class DeleteRestrictionError < AssociationError
```

### CODE REVIEW

**Comment by maclover7** [comment]
This seems like a very cosmetic change 😬

**Comment by thejamespinto** [comment]
@maclover7 ,
Rafael and I spoke about these changes so we're only going to merge if it actually proves benefiting to ActiveRecord.

**Comment by maxjacobson** [comment]
Apologies for the codeclimate errors on this branch -- it looks like this branch has been open since before rails added its [.codeclimate.yml](https://github.com/rails/rails/blob/master/.codeclimate.yml), so we're trying to perform more analysis than necessary and something is going wrong. While we look into that, feel free to copy that file into your branch (or rebase on top of master) to resolve those failures.

**Comment by thejamespinto** [comment]
@maxehmookau thanks for caring to stop by ❤️

**Comment by thejamespinto** [comment]
Hey @rafaelfranca, travis isn't running. Am I missing anything important?

**Comment by maxehmookau** [comment]
Pinged the wrong person @thejamespinto ?

**Pull request closed without merging**
