### PR TITLE
Fix STI in available_records causing new instances of records to be loaded from database

### PR DESCRIPTION
**Pull request by octatone**
### Summary

Fixes bug in  ActiveRecord::Associations::Preloader causing unnecessary refetching of records by removing grouping by available_record class names.

### CODE REVIEW

**Review by akenneth — APPROVED** [review]
Nice change! 

Left 1 question I am unsure about, other than that lgtm!

**Review by eileencodes — COMMENTED** [review]
This looks good, can you squash your commits into one and make sure the one commit explains the change?

**Comment by zzak** [comment]
@octatone Was there an associated issue with this PR or just something you picked up on and posted a patch?

**Comment by eileencodes** [comment]
There's no public issue, this was found in the GitHub app @zzak.

**Pull request merged**
