### PR TITLE
fix in retrieving key in file_cache

### PR DESCRIPTION
**Pull request by madej**
fix for issue #21576

### CODE REVIEW

**Comment by arthurnn** [comment]
Can you add a regression test for the fix?

thanks for the PR

**Comment by madej** [comment]
Test added.

**Comment by madej** [comment]
@arthurnn , is there a problem with this pr? I see new rc is released, but without this patch cleanup in file_store will not work and generate exceptions in new version as well.

**Comment by arthurnn** [comment]
My concern here is that we are changing the keys schema. So once someone update to a Rails version that includes this fix, it will invalidate the file cache as now the keys are different. 
cc @jeremy

**Comment by madej** [comment]
No, we don't. This change only fixes 'recreating' a key from a path. We don't change anything in generating keys.

**Comment by bnymn** [comment]
What is the latest status of this patch? In rails 4.2.7 and 4.2.10, I am still getting this error message.

**Comment by kamipo** [comment]
Closing this since `FileStore#cleanup` has already been fixed by #30789.

**Pull request closed without merging**
