### PR TITLE
Include CoffeeScript and SCSS extensions in SourceAnnotationExtractor by default

### PR DESCRIPTION
**Pull request by mattkirman**
As CoffeeScript and SCSS have been part of the default Rails install since 3.1, add .scss and .coffee to the default SourceAnnotationExtractor extensions. This now means that tags in CoffeeScript and SCSS files are included in `rake notes` by default.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
we should add sass too

**Comment by guilleiguaran** [comment]
This should be done on plugins adding the API that we added for it, example:

```
config.annotations.register_extensions("scss", "sass")
```

**Comment by rafaelfranca** [comment]
True

**Comment by guilleiguaran** [comment]
Actually this is done already in sass-rails:

https://github.com/rails/sass-rails/blob/master/lib/sass/rails/railtie.rb#L28-L30

**Comment by rafaelfranca** [comment]
And coffee-rails:

https://github.com/rails/coffee-rails/blob/master/lib/coffee/rails/engine.rb#L9

So we can close this one.

Thanks you so much for the PR.

**Comment by mattkirman** [comment]
No worries. The extensions aren't being added correctly in my default Rails 4.2.0 install so assumed that this was the reason. I'll debug a little further.

Thanks for your feedback.

**Comment by rafaelfranca** [comment]
Maybe rake notes is not loading the environment, so it will not detect external extensions.

**Pull request closed without merging**
