### PR TITLE
Build fix for 4-2-stable

### PR DESCRIPTION
**Pull request by arunagw**
Trying to get build fix with 4-2-stable for ActiveJob Integration tests

### CODE REVIEW

**Comment by arunagw** [comment]
It's started failing on other integration.

Is it make sense to not run these on travis as we are doing in master?

**Comment by cristianbica** [comment]
It's failing now because it uses queue_classic >=3 and the API changed inside QC. As I wrote the initial version it makes no sense for me to ditch them for the stable branch :). For the master where is high amount of refactoring it makes sense. The integration tests are pretty sensitive (gems / dependencies might change the API) so it will require some maintenance.

**Comment by senny** [comment]
@arunagw I updated the QC setup on `4-2-stable` to work with changes to the QC API. Tests passed on my machine so you may want to give this PR another update.

For reference https://github.com/rails/rails/compare/7081c95a3b38...5450e724fb07

**Comment by arunagw** [comment]
@senny I have updated the PR and removed DB creation. Its seems to green on most of the ruby and failing on 2.1. May be because of timeout? I have restarted the build one more time to see

**Comment by arunagw** [comment]
Closing this in favour of 6a100783bca3c7f06ee721f0074e7de52698a855

**Pull request closed without merging**
