### PR TITLE
Address remaining known issues in Interlock

### LINKED ISSUE #21006: Under concurrent load Dependencies.interlock might miss file changes
While helping @mperham in #20989 I realized that the current code (under concurrent load) is broken.

The problem arises if there are multiple threads in app space region of `Dependencies.interlock`, then an `.rb` file is changed. Next thread arrives at `ActionDispatch::Reloader` middleware, it invokes `reloaders` to check if any of the files have changed, and indeed there is a change, the thread attempts to grab an exclusive `Dependencies.interlock` (via poll) does not succeed (because of those other threads in app space) and proceeds on.

However `reloaders` report a change in `.rb` file only once, subsequent calls to `updated?` return `false`, this is because since the last time `updated?` has been invoked nothing has changed, so if an exclusive grab of `Dependencies.interlock` was not successful a change to `.rb` file is "lost".

Additionally, if a typical use case of `sidekiq` is somewhat similar to @mperham's example in https://github.com/rails/rails/pull/20928#issuecomment-123876079, I'm fairly confident that even if the "lost" `.rb` change issue is fixed, unless `unloading` is blocking (and an attempt to obtain an exclusive lock blocks out new readers), then update is going to be probably "starved" anyways.

/cc @matthewd

### PR DESCRIPTION
**Pull request by matthewd**
Fixes #21006

### CODE REVIEW

**Comment by matthewd** [comment]
@thedarkone so it only took me six months to get around to dealing with this :pensive:

I ended up implementing the "everyone gets a go" thing, because that feels particularly relevant if you have different sets of code entering the 'running' block for measurably different amounts of time (as I suspect we will once I get Action Cable wired up). Other than that, this should cover your suggestions in #21006. That's the plan, anyway. :smile:

**Comment by mperham** [comment]
I was able to enable live code reloading in Sidekiq and watch it work, processing thousands of jobs, with 5.0beta2.  Nice job!

**Comment by thedarkone** [comment]
@matthewd awesome job, I love how `ShareLock` is still just a few concise loc.

Do you have future plans for `after_compatible:`? Since right now `options[:compatible] == options[:after_compatible] # => true`.

**Comment by matthewd** [comment]
No specific plans.. it just felt intuitively unreasonable, in the "generic" class, to assume that everything allowed to run before is also allowed to run after. (That is, it forces the caller to separately opt-in to the "yield lock after running" behaviour, over and above their acceptance of "yield lock before running".)

I was actually surprised they ended up symmetrical in both of load and unload... though I suppose that's technically untrue: unload doesn't *object* to a load following it, but in practice that can never happen, because a blocked load would not have permitted the unload to run. Something can only usefully appear in `after_compatible` if it itself claims to be `compatible` with the current `purpose`.

**Pull request merged**
