### PR TITLE
Fix an issue where `ActiveSupport::Reloader.reload!` would cause `to_prepare` callbacks to be called twice

### PR DESCRIPTION
**Pull request by f1sherman**
See https://github.com/rails/rails/issues/28108 for details

### CODE REVIEW

**Comment by rafaelfranca** [comment]
I don't think it is an issue. It was deliberately made that way since we have tests to assert this behavior. But I'll let r? @matthewd decide.

**Comment by f1sherman** [comment]
@rafaelfranca sure thing! It seemed suboptimal to me and I wasn't able to think of a reason why it would be desirable, so I submitted this patch. Looks like I have a test failure I need to look into as well...

**Comment by f1sherman** [comment]
@matthewd sorry to bother you, would you mind weighing in on this PR? I'd be perfectly happy if this PR gets closed with an explanation of why this is expected behavior if that's the case. Thanks!

**Comment by f1sherman** [comment]
@rafaelfranca it looks like @matthewd may not be available to look at this, any chance someone else could be assigned?

**Comment by matthewd** [comment]
We do prepare at application boot, so after a reload, it should occur again -- *after* the complete, which has potentially "cleaned up" things that it had prepared. `reload!` is obliged to leave the application in approximately the same state as when it booted, ready to handle anything that might come next.

We already call prepare a thoroughly variable number of times -- if your prepare handler isn't idempotent, you're going to have a bad time.

**Comment by f1sherman** [comment]
@matthewd sounds good, thanks for the explanation!

**Comment by matthewd** [comment]
Further detail I've just remembered... I'm pretty sure in 4.2 the order was `complete; prepare`. So it's the *leading* `prepare` that is the new wart here... and then the "well it really has to be idempotent anyway" argument is why I didn't find a long way around avoiding that.

**Pull request closed without merging**
