### PR TITLE
Avoid "comparison of Gem::Version..." error in Ruby < 3.1

### PR DESCRIPTION
**Pull request by lorint**
### Motivation / Background

Commit [185f2d7](https://github.com/rails/rails/commit/185f2d718d4) errors out with Ruby < 3.1 in this way:
```
/activerecord/lib/active_record/coders/yaml_column.rb:14:in `>=': comparison of Gem::Version with String failed (ArgumentError)
```

This Pull Request has been created to update the Psych gem version check in `activerecord/lib/active_record/coders/yaml_column.rb` in order to remedy this issue.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by yahonda** [comment]
I was wondering why Rails CI did not catch this exception and found it depends on RubyGem version.

Rails CI updates RubyGem version to 3.4.7.
https://github.com/rails/buildkite-config/blob/11b476f6cbafdef3dc7dbfc7530418d084e47c55/Dockerfile#L7
https://buildkite.com/rails/rails/builds/94114#01867d60-58a9-4f90-bd91-a99ddad89dce/133-142

There must be some changes between RubyGems 3.2.33 and 3.4.7 to allow the current comparison.

- Ruby 3.0.5 and RubyGems 3.2.33

```ruby
% ruby -v
ruby 3.0.5p211 (2022-11-24 revision ba5cf0f7c5) [arm64-darwin22]
% gem -v
3.2.33
% irb
irb(main):001:0> require 'psych'
=> true
irb(main):002:0> Psych::VERSION
=> "3.3.2"
irb(main):003:0> Gem::Version.new(Psych::VERSION) >= "5.1"
(irb):3:in `>=': comparison of Gem::Version with String failed (ArgumentError)
	from (irb):3:in `<main>'
	from /Users/yahonda/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/irb-1.3.5/exe/irb:11:in `<top (required)>'
	from /Users/yahonda/.rbenv/versions/3.0.5/bin/irb:23:in `load'
	from /Users/yahonda/.rbenv/versions/3.0.5/bin/irb:23:in `<main>'
irb(main):004:0> Gem::Version.new(Psych::VERSION) >= Gem::Version.new("5.1")
=> false
irb(main):005:0>
```

- Ruby 3.0.5 and RubyGems 3.4.7

```ruby
% ruby -v
ruby 3.0.5p211 (2022-11-24 revision ba5cf0f7c5) [arm64-darwin22]
% ruby -v
% gem update --system
gem -v
3.4.7
% irb
irb(main):001:0> require 'psych'
=> true
irb(main):002:0> Psych::VERSION
=> "3.3.2"
irb(main):003:0> Gem::Version.new(Psych::VERSION) >= "5.1"
=> false
irb(main):004:0> Gem::Version.new(Psych::VERSION) >= Gem::Version.new("5.1")
=> false
irb(main):005:0>
```

**Comment by lorint** [comment]
> There must be some changes between RubyGems 3.2.33 and 3.4.7 to allow the current comparison

Cool sleuthing!  Thank you for tracking this down and sharing the details.

**Comment by skipkayhil** [comment]
> [rubygems/rubygems#5275](https://github.com/rubygems/rubygems/pull/5275) has been merged and available since RubyGems 3.4.0

I saw this and wanted to make sure that we could use `<=>` with `Gem.ruby_version` in Railties, since the rubygems requirement in Railties is 3.3.13.

I found that the first rubygems version including that change was actually [3.3.6](https://github.com/rubygems/rubygems/blob/master/CHANGELOG.md#336--2022-01-26), so its fine to continue doing String comparison in Railties.

**Comment by yahonda** [comment]
> I found that the first rubygems version including that change was actually [3.3.6](https://github.com/rubygems/rubygems/blob/master/CHANGELOG.md#336--2022-01-26), so its fine to continue doing String comparison in Railties.

I was overlooking the backport commit https://github.com/rubygems/rubygems/commit/8d4cfb06d231483bba0d422613598bdc87460811


> Maybe we should add the required_rubygems_version to all of the frameworks?

I assume this pull request has been opened to address this CI error.

https://github.com/github/activerecord-trilogy-adapter/actions/runs/4248503714/jobs/7387746518

I'm not sure if this change tells activerecord-trilogy-adapter CI that Rails main branch requires RubyGems 3.3.13.

**Comment by lorint** [comment]
> this pull request has been opened to address this (activerecord-trilogy-adapter) CI error

Indeed, @yahonda -- I had put this PR together after discovering that specific ARTA failure, so would expect that similar edge rails use cases with Ruby < 3.1 could also end up in the same boat.

**Comment by yahonda** [comment]
I assume If any of 3rd party tools like `activerecord-trilogy-adapter` that depends on the part of `rails` like `activerecord`, `s.required_rubygems_version` in the `rails.gemspec` is not considered.

https://github.com/github/activerecord-trilogy-adapter/blob/7199f2dddb8be6caef0afeec384ac7719a3ffd3a/activerecord-trilogy-adapter.gemspec#L22

https://github.com/rails/rails/blob/7b5e2f3d2cc59fc4001226ed1053a61456525853/rails.gemspec#L13

Let me validate my assumption later.

**Comment by yahonda** [comment]
> I assume If any of 3rd party tools like activerecord-trilogy-adapter that depends on the part of rails like activerecord, s.required_rubygems_version in the rails.gemspec is not considered.

Opened https://github.com/rails/rails/pull/47511 because my assumption is correct.

**Pull request merged**
