### PR TITLE
[ci skip] Add CHANGELOG for #22300 (817c1825c15013fd0180762ac5c05a2e0…

### PR DESCRIPTION
**Pull request by yui-knk**
…24a640d)

### CODE REVIEW

**Comment by yui-knk** [comment]
:bow: :bow: :bow:

**Comment by yui-knk** [comment]
@pixeltrix  I'm really sorry....

**Comment by pixeltrix** [comment]
@yui-knk no worries I fixed it in 32a8cd961eec840f31e6d60948756070d188c2b4

**Comment by yui-knk** [comment]
:heart_eyes: :heart_eyes_cat:  :tada:

**Pull request closed without merging**
