### PR TITLE
Rails Guides - set "cursor: pointer" and on hover "color: #005cc5" css to copy code button [ci-skip]

### PR DESCRIPTION
**Pull request by sampatbadhe**
### Detail

Rails Guides - set `cursor: pointer` and on hover `color: #005cc5` css to copy code button

**Before**

https://user-images.githubusercontent.com/5279284/200154406-6570684e-6ec3-48ad-9c2b-edc13fa47c46.mov

**After**

https://user-images.githubusercontent.com/5279284/200722524-527ab2fc-b9ba-4f96-84d2-fa691a26f116.mov

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [ ] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.
* [x] CI is passing.

### CODE REVIEW

**Comment by p8** [comment]
Thanks @sampatbadhe !

**Review by jonathanhefner — COMMENTED** [review]
Nice demos! :smile:  For a bit of extra affordance, could we also change the color on mouse over?  I see that we currently [change the background color on `:active`](https://github.com/rails/rails/blob/45eceb2744ce141d9251ba2ca57c3a667b009247/guides/assets/stylesheets/main.css#L258-L260), so perhaps we can change the text color on `:hover` to something like `#005cc5`?  (I copied that color from some of our syntax highlighting.)  Or we could swap those behaviors, i.e. change the background color on `:hover` and the text color on `:active`.  @p8, what do you think?

(Sidenote: There are [several](https://ux.stackexchange.com/questions/105024/why-dont-button-html-elements-have-a-css-cursor-pointer-by-default/105027#105027) [answers](https://ux.stackexchange.com/questions/3788/default-cursor-on-mouse-over-of-a-button-is-not-a-hand-pointer/3834#3834) on Stack Exchange and [this popular blog post](https://medium.com/simple-human/buttons-shouldnt-have-a-hand-cursor-b11e99ca374b) that suggest non-link buttons should not use a pointer cursor.  However, UI trends may be changing.  For example, I notice that GitHub's non-link buttons use a cursor pointer.)

**Comment by sampatbadhe** [comment]
Thank you for review @p8 and @jonathanhefner, I have applied the text color to `#005cc5` on hover, could you please take a look at updated demo.

**Comment by p8** [comment]
@jonathanhefner @sampatbadhe  This looks great to me!

> (Sidenote: There are [several](https://ux.stackexchange.com/questions/105024/why-dont-button-html-elements-have-a-css-cursor-pointer-by-default/105027#105027) [answers](https://ux.stackexchange.com/questions/3788/default-cursor-on-mouse-over-of-a-button-is-not-a-hand-pointer/3834#3834) on Stack Exchange and [this popular blog post](https://medium.com/simple-human/buttons-shouldnt-have-a-hand-cursor-b11e99ca374b) that suggest non-link buttons should not use a pointer cursor. However, UI trends may be changing. For example, I notice that GitHub's non-link buttons use a cursor pointer.)

Hmm, now I'm not sure about the pointer. Maybe the hover color is good enough. 🤔 
The pointer does seem to get used for non-link buttons for some of the apps I tried (Discord, Twitter, Basecamp, Teams)...

**Review by jonathanhefner — APPROVED** [review]

**Comment by jonathanhefner** [comment]
> On the other hand, the pointer does seem to get used for non-link buttons for some of the apps I tried (Discord, Twitter, Basecamp, Teams)...

Let's embrace the future!

Thank you, @sampatbadhe! :smile:  And thank you, @p8! :rocket:

**Pull request merged**
