### PR TITLE
fixes a javascript bug in ActiveStorage that broke direct uploads in IE11

### LINKED ISSUE #32378: ActiveStorage direct_upload failing in IE11 - Assignment to read-only properties is not allowed in strict mode
## Steps to reproduce
Using Active Storage, along with direct upload, upload a file directly to a service (tested with S3) using Internet Explorer 11.

## Expected behavior
The file should be properly uploaded via javascript directly to the service.

## Actual behavior
IE throws an error when the file upload is complete to S3 and the form submits:
```
Assignment to read-only properties is not allowed in strict mode
File: activestorage.self-*.js, Line: 1, Column: 3274
```
Which I tracked down to this line of code:

https://github.com/rails/rails/blob/f9ec3e5cc3753b7a46cc1a34d57ca941e4cf7211/activestorage/app/javascript/activestorage/ujs.js#L62

I'm still wrapping my head around this code but it seems to me as though the form is being modified after it's submitted, and IE doesn't like it. I'm happy to help correct it if someone can point me in the direction.

**System configuration**
Rails version:
5.2.0rc2

**Ruby version**:
ruby 2.5.0

### PR DESCRIPTION
**Pull request by kylekeesling**
### Summary

Direct upload was throwing an error after the assets were uploaded to a service, specifically when attempting to set the css style to none.

More background and info is outlined in #32378 and my first attempt at a PR #32454 

Fixes #32378

### CODE REVIEW

**Comment by kylekeesling** [comment]
FYI @javan

**Comment by javan** [comment]
Can you update your rails fork with rails master, please? I believe your compiled `activestorage.js` is missing the most recent changes to the src files.

**Comment by kylekeesling** [comment]
OK - I think I did what you needed. Thanks for bearing with me, I'm out of my element with some of this git stuff :)

**Comment by javan** [comment]
All good! We're back in the same boat with your commits needing squashing again. Want to practice? http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#iterate-as-necessary

**Comment by javan** [comment]
The goal is to have a single commit with your fix both in `src/` and the compiled `activestorage.js`.

**Comment by kylekeesling** [comment]
Woo boy was that fun.... ;)

I think that I got it all figured out. It looks like the source line is updated and the compiled `activestorage.js` contains the updated command `e.style.display="none"` as opposed to the old `e.style="display:none"`

I know this is a small tweak but the has been pretty cool for as it's my first PR to Rails. Thanks for the help!

**Comment by javan** [comment]
Great job! Thank you for fixing this and congrats on landing your first Rails commit!

**Pull request merged**
