### PR TITLE
Rubocop passing

### PR DESCRIPTION
**Pull request by bogdanvlviv**
I know about [comment](https://github.com/rails/rails/pull/13771#issuecomment-32746700), but now we have RuboCop and this pull request destroy dirty/hard code.
hard code examples: [has_many_association.rb](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations/has_many_association.rb#L83), [capture_helper.rb](https://github.com/rails/rails/blob/master/actionview/lib/action_view/helpers/capture_helper.rb#L40), and [cookies.rb](https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/middleware/cookies.rb#L375)

 In any case we should to destroy dirty/hard code in RuboCop opinion.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Nothing changed related to cosmetic changes

**Comment by fxn** [comment]
Thanks!

We are running an internal style task force, but as per cosmetic changes via PRs what @rafaelfranca said.

**Comment by bogdanvlviv** [comment]
@rafaelfranca, @fxn  thanks.
Tip: "Please see [this code](https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/middleware/cookies.rb#L375), maybe there is something wrong."

**Comment by fxn** [comment]
@bogdanvlviv thanks, precisely I deferred applying this particular cop because the resulting patch has to be carefully revised. Too much attention needed to be included with the previous massive bulk edits, which needed revision themselves.

**Pull request closed without merging**
