### PR TITLE
Fix NoMethod "flash" on ActionDispatch::Request error

### PR DESCRIPTION
**Pull request by kwstannard**
### Summary

Steps to reproduce:

- Load rails in api_only mode. This will not load the flash middleware
  and the flash request mixin.
- Create a POST route/action that is protected with null_session.
- Run the post action. You should get the NoMethodError "flash" on Request.

This repo contains a single example route that causes the error as well: https://github.com/kwstannard/rails-bug

### Other Information

I split the change into two more reviewable commits.

I don't know how to test this change and it appears that the tests that exist for null session are "No error occurred" type tests and don't check any of the null session code is run. I can add some tests if someone can point me toward something I can put expectations on.

### CODE REVIEW

**Comment by Edouard-chin** [comment]
I don't think this change make sense because the CRSF protection isn't an attack vector when your application is in API only. To be precise, it's not an attack vector when the authentication method isn't based on cookies, which is what API mode kind of implies.

The RequestForgeryProtection module isn't added to the `ActionController::API` class (the one that your ApplicationController inherited when you generated your Rails app using `--api-only`).
Maybe you modified the `config.api_mode` after having generated your application normally but forgot to follow those steps https://github.com/rails/rails/blob/0a5839fdfd7b7f52634c0425769be8a6bfd95ff9/guides/source/api_app.md#changing-an-existing-application

**Comment by kwstannard** [comment]
Yes, I understand that if you run Rails in a sane way that you won't run into this error, but not everyone has the luxury of a sane Rails deployment.

This error shouldn't be happening in insane Rails deployments either because the issue is that the abstraction was leaky.

**Comment by Edouard-chin** [comment]
This make sense to me, there is one possible way where things would break in a legitimate way is if someone decides to remove the Flash Middleware from the middleware stack (as mentioned here https://github.com/rails/rails/blob/53fd8bddf8706547827f1906559344d5b31c9249/railties/lib/rails/application/default_middleware_stack.rb#L64)

> I don't know how to test this change

I'd try to write a test that builds an app, remove the flash middleware from the stack, make a request where with a wrong CSRF token and see if nothing breaks

**Comment by kwstannard** [comment]
Great feedback, thanks!

**Comment by kwstannard** [comment]
> I'd try to write a test that builds an app, remove the flash middleware from the stack, make a request where with a wrong CSRF token and see if nothing breaks.

Do you happen to have a good way to un-mixin the Flash RequestMethods module?

**Comment by Edouard-chin** [comment]
Hmm, it's going to be tricky.

I had open https://github.com/rails/rails/pull/44588 yesterday in anticipation of this PR because right now we can't un-patch , even if we delete the Flash Middleware. We won't merge that fix as is though and we decided that we need to delete the middleware (you can read in the PR details why). 

I think another way to test would be to create a metal controller and just include the RequestForgeryProtection module and see if everything work. Something like:

```ruby
class TestBareController < ActionController::Metal
  include ActionController::RequestForgeryProtection
  include AbstractController::Callbacks
 
  protect_from_forgery with: :null_session  

  def create
    head(:ok)
  end
end
```

**Comment by kwstannard** [comment]
Just a heads up, I don't really know how the action dispatch tests are organized or how exactly they work right now. So I both need to figure out where a test would go and also how to write it. It might be a while.

**Comment by kwstannard** [comment]
Closing in favor of https://github.com/rails/rails/pull/44588

**Pull request closed without merging**
