### PR TITLE
remove unecessary comments [ci skip]

### PR DESCRIPTION
**Pull request by y-yagi**
These comments were removed in 8b69f1e.

### CODE REVIEW

**Comment by maclover7** [comment]
:+1: Thank you for your contribution!

:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by maclover7** [comment]
@y-yagi Would you be willing to open up PRs to backport this commit to `5-0-stable` and `5-0-0`?

**Comment by y-yagi** [comment]
Sure! I will do.

**Comment by y-yagi** [comment]
Opened #25531 and #25532.

**Comment by maclover7** [comment]
Thanks @y-yagi!

**Pull request merged**
