### PR TITLE
Fix Ruby 2.7 keyword arguments warning

### PR DESCRIPTION
**Pull request by jonathanhefner**
Partially addresses #39227.

### CODE REVIEW

**Comment by kamipo** [comment]
Can you demonstrate to show a warning (in 2.7) / an error (in ruby-master)? I tried that for a few hours, but I haven't found a reproduction case.

**Comment by jonathanhefner** [comment]
@kamipo I did not try, but because `ActionDispatch::Routing::UrlFor#initialize` can delegate to user code via `super`, `ruby2_keywords` seems appropriate.

**Comment by kamipo** [comment]
Okey I've finaly found the reproduction case.

https://github.com/rails/rails/compare/master...kamipo:fix_kwargs_warnings

Can you pick the test case?

**Comment by jonathanhefner** [comment]
@kamipo  Added!  Thank you!

**Comment by jonathanhefner** [comment]
Backported to `6-0-stable` in 04d0fa7e5f210ca49b758f4678d0fe3d3da4d7b5.

**Pull request merged**
