### PR TITLE
Remove redundant Puma configuration settings

### PR DESCRIPTION
**Pull request by dhh**
1. Puma automatically sets its environment from RAILS_ENV
2. preload_app! is automatically set when in cluster mode
3. WEB_CONCURRENCY is automatically used and is now parsed directly so can't be extended with "auto" here.
4. worker_timeout is a cluster mode feature, and we don't run that in dev.

### CODE REVIEW

**Comment by dhh** [comment]
Unrelated errors.

**Comment by joshuay03** [comment]
>     2. preload_app! is automatically set when in cluster mode

Unfortunately, this is not true when using the config DSL. See:
- https://github.com/puma/puma/issues/3044
- https://github.com/puma/puma/pull/3297

**Comment by dhh** [comment]
Are you saying that if you start Rails with `WEB_CONCURRENCY=2 bin/rails s -e production`, you will not get preloading? Or that you will? WEB_CONCURRENCY is the way we intend to have people control the number of workers being used.

**Comment by joshuay03** [comment]
> Are you saying that if you start Rails with `WEB_CONCURRENCY=2 bin/rails s -e production`, you will not get preloading? Or that you will?

You will.

You won't get preloading by default when you do:

```
# config/puma.rb

workers 2
```

So having `preload_app!` in the default config ensured that users who aren't aware of this discrepancy will have preloading enabled with their new app regardless of whether they use the env var or the DSL method.

> WEB_CONCURRENCY is the way we intend to have people control the number of workers being used.

Cool, this can be ignored in that case. Hopefully it'll be fixed in Puma 7 anyway.

**Comment by schneems** [comment]
> preload_app! is automatically set when in cluster mode

This is now true with Puma 7.0+. I recommend 7.0.4+. Thanks to @joshuay03 who made the change https://github.com/puma/puma/pull/3297

**Pull request merged**
