### PR TITLE
Simplify nested source reflection lookup

### PR DESCRIPTION
**Pull request by maclover7**
- Removes protected method used in only one place
- Removes poorly named protected method :(

cc @jeremy

### CODE REVIEW

**Comment by jeremy** [comment]
Same comment re. following longer chains of source reflections: https://github.com/rails/rails/pull/24585/files#r59975577

**Comment by maclover7** [comment]
Hmm, yeah -- I don't think this would continue iterating through a giant stack of source reflections. Do we still want to do that?

**Comment by jeremy** [comment]
> Do we still want to do that?

Do we? Why are we doing it?

**Comment by maclover7** [comment]
Hmm, I think this is now more a question of what level of source reflection nesting ActiveRecord::Reflection itself supports... It looks like we only have test coverage for about two levels of nesting...

thoughts @tenderlove?

**Comment by jeremy** [comment]
Why is "# of levels to support" a question here when the implementation is evidently supporting _any_ chain of source reflections?

How would you write a test to demonstrate that arbitrary reflection chains are supported? `1.upto(Infinity) { |i| assert_source_reflection_chain_depth_works i } # nailed it` :grin:

All we need to do here is rename the method to something that better captures the intent and purpose of recursing through source reflections to find the "final" reflection, or punt and remove the FIXME comment.

**Comment by maclover7** [comment]
Why can't we just leave the `source_reflection.source_reflection` in the `association_primary_key` method itself? It's only used once, not sure we need to create a separate method for it.

**Comment by jeremy** [comment]
@maclover7 Think "recursion" and "hm:t association through another hm:t association through another …" to arbitrary depth.

Spend some time with this to understand _why_ we're calling this method on a reflection, which calls it on another reflection, which calls it … Then look at how `#scope_chain` does the same thing, recursively building a scope chain.

Dwell in it. Stop just looking at the code. Make some examples. Do many different hm:t association depths. Use a debugger to step through the code as the scope chain is built.

_Satisfy yourself that you understand_ and you're well on your way to getting to the root of any coding mystery 😊

**Pull request closed without merging**
