### PR TITLE
Delete needless newlines in upgrading guide [ci skip]

### PR DESCRIPTION
**Pull request by yasulab**
Newlines added in a sentence make difficult to translate because it breaks segments (a.k.a. [Translation Memory](https://en.wikipedia.org/wiki/Translation_memory)). RailsGuides can be efficiently translated if no such newlines, for example, translating into [Japanese](https://railsguides.jp/).

### CODE REVIEW

**Comment by matthewd** [comment]
I think it would be better to teach the Translation Memory system to ignore word-wrapping that markdown doesn't care about -- or apply an automatic re-wrap in the pipeline before the translation system sees the source content.

All our new or modified documentation is wrapped. A global policy change would need to balance ease of working with the original content against what makes things easier for translation tools.

(The upgrading guide doesn't seem the most relevant example to me, anyway -- with rare exceptions, it only gets entirely-new content added for each version.)

**Comment by yasulab** [comment]
Thanks for your quick response and advice. :)

> apply an automatic re-wrap in the pipeline before the translation system sees the source content.

Japanese RailsGuides don't have this kind of system yet, but we can insert this into the pipeline. So, if newlines are comfortable for writing contents, we will respect the way of writing in the original guides.

**Comment by rafaelfranca** [comment]
We definitely want to add newlines to write content. Like @matthewd said Markdown ignore them so it should be possible to the the translation memory system do that.

I'm closing this since we don't want to change our policy about newlines in documentation.

**Comment by yasulab** [comment]
Thanks for your review and feedback. I opened the issue in Japanese RailsGuides to implement the following function in our side.  https://github.com/yasslab/railsguides.jp/issues/315

> Markdown ignore them so it should be possible to the the translation memory system do that.

**Pull request closed without merging**
