### PR TITLE
Simplify implementation of `MySQLDatabaseTasks`

### PR DESCRIPTION
**Pull request by bogdanvlviv**
Raise error if unsupported charset for mysql

`blog$ bin/rails db:create`

Before:
```
Couldn't create database for {"adapter"=>"mysql2", "encoding"=>"utf42", "pool"=>5,
"username"=>"root", "password"=>nil, "socket"=>"/var/run/mysqld/mysqld.sock",
"database"=>"blog_development"}, {:charset=>"utf42"}
(If you set the charset manually, make sure you have a matching collation)
Created database 'blog_development'
Couldn't create database for {"adapter"=>"mysql2", "encoding"=>"utf42", "pool"=>5,
"username"=>"root", "password"=>nil, "socket"=>"/var/run/mysqld/mysqld.sock",
"database"=>"blog_test"}, {:charset=>"utf42"}
(If you set the charset manually, make sure you have a matching collation)
Created database 'blog_test'
```

After:
```
Unsupported charset: '"utf42"'
Couldn't create database for {"adapter"=>"mysql2", "encoding"=>"utf42", "pool"=>5,
"username"=>"root", "password"=>nil, "socket"=>"/var/run/mysqld/mysqld.sock",
"database"=>"blog_development"}
rails aborted!
Mysql2::Error: Unsupported charset: '"utf42"'
...
(stack trace)
...
bin/rails:4:in `<main>'
Tasks: TOP => db:create
(See full trace by running task with --trace)
```

Closes #29683
Related to #27398

<hr>

Simplify implementation of `MySQLDatabaseTasks`

Don't process MySQL ERROR 1045, raise error instead

Make behavior of `MySQLDatabaseTasks` more consistent with behavior of `PostgreSQLDatabaseTasks`

### CODE REVIEW

**Comment by bogdanvlviv** [comment]
Please review

**Comment by bogdanvlviv** [comment]
What do you think about it?

(I'm not sure about `Simplify implementation of MySQLDatabaseTasks` commit. If we need this I'll remove this commit)

**Comment by rafaelfranca** [comment]
I think it is fine for now. If this cause any problem we can revert of fix forward.

**Comment by bogdanvlviv** [comment]
@rafaelfranca Thanks for the review! I think https://github.com/rails/rails/issues/27398 can be closed since I can't reproduce it on `master`.

**Comment by koukou73gr** [comment]
With this PR Rails no longer asks for a root database password for MySQL in order to create its database user if one is not there, or does not have the privileges to create the DB. Was this the intended behavior? I couldn't find a comment anywhere...

If so, what is the recommended way to create a new user and DB with MySQL for a new application now? Go through MySQL command line?

**Comment by bogdanvlviv** [comment]
Yes, it was changed intentionally. We don't want to allow Rails handle this case by modifying a MySQL user configuration. I think that it is a responsibility of developers to create and configure a MySQL user.
The same we do if use PostgreSQL.

> If so, what is the recommended way to create a new user and DB with MySQL for a new application now? Go through MySQL command line?

In order to create DD with MySQL, you should have a MySQL user with privilege to create DBs,
then configure your app http://edgeguides.rubyonrails.org/configuring.html#configuring-a-mysql-or-mariadb-database. After you can create DB via `rails db:create`. It should create DB with name you specified in configurations.

Please let me know if you have any other issues related to this PR.

**Pull request merged**
