### PR TITLE
better docs for ActiveRecord::PredicateBuilder::BaseHandler#initialize

### PR DESCRIPTION
**Pull request by abhaynikam**
### Summary

Added a Rdoc to ignore the initialize method from seeing

### CODE REVIEW

**Comment by pixeltrix** [comment]
@abhaynikam I don't see this method appearing in api.rubyonrails.org or edgeapi.rubyonrails.org - why is it needed?

**Comment by abhaynikam** [comment]
@pixeltrix: I think it's better to have good documentation everywhere.

**Comment by pixeltrix** [comment]
@abhaynikam that doesn't answer the question - this method is undocumented so adding `:notnew:` will not make any difference at best or at worst cause this single method to be come documented and expose an internal class as public API.

**Comment by abhaynikam** [comment]
@pixeltrix: Ok. That make sense. Closing the PR.

**Pull request closed without merging**
