### PR TITLE
Add bin/install-dev to ease release validation

### PR DESCRIPTION
**Pull request by dhh**
Add bin to install all gems locally before a big release to make sure we got it right.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
`rake install` does that.

**Comment by rafaelfranca** [comment]
https://github.com/rails/rails/blob/59f1e1783136a6a5a6deca60dc25bf3925e8cde9/Rakefile#L57-L58

**Comment by rafaelfranca** [comment]
I included documentation about that command in the releasing guide in my PR changing the release process.

https://github.com/rails/rails/pull/52962/files#diff-b7822651022f149b018fb6179198e83e132d7e6c8ccc317d7d2b8f7d43d4ea06R59-R61

**Comment by dhh** [comment]
Ha! I went looking for that, but didn't find it. That's better. Thanks!

**Comment by rafaelfranca** [comment]
Btw, we have `rake verify` which also creates an app and boot it. I removed because none of the people releasing were using it. Do you want me to keep? It isn't hard to keep

**Comment by rafaelfranca** [comment]
https://github.com/rails/rails/pull/52962/commits/7bfe7d05ab2d12dd9504c525207ddb05e6eca606

**Comment by rafaelfranca** [comment]
I also try to keep `rake -T` clean for Rails. Only release tasks are in the list. We have a few useful ones:

```
rake build                       # Build gem files for all projects
rake create_release              # Create GitHub release
rake default                     # Run all tests by default
rake install                     # Install gems for all projects
rake prep_release                # Prepare the release
rake preview_docs                # Generate documentation for previewing
rake publish_docs                # Publishes docs, run this AFTER a new stable tag has been pushed
rake push                        # Push the gem to rubygems.org and the npm package to npmjs.com
rake rdoc                        # Generate documentation for the Rails framework
rake release                     # Release all gems and create a tag
rake smoke[frameworks,isolated]  # Smoke-test all projects
rake test                        # Run test task for all projects
rake test:isolated               # Run test:isolated task for all projects
```

**Pull request closed without merging**
