### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by crifat**
A very minor change of comma usage.

### CODE REVIEW

**Comment by kamipo** [comment]
Thank you but we don't accept cosmetic changes.
https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#write-your-code

**Comment by LemonAndroid** [comment]
@dhh 

Also this :D.


How stupidly is this project managed.

**Comment by sikachu** [comment]
@kamipo this looks like a documentation change to fix grammar and not cosmetic change, so I'm going to open and merge this. Sorry for reverting your action.

**Comment by dhh** [comment]
@LemonAndroid You’re in violation of the Code of Conduct for Rails. This is your final warning to follow the CoC and behave respectfully towards everyone working on this project. If you fail to do so again, you will be banned from participating on this repository.

**Comment by dhh** [comment]
@LemonAndroid I see that other community members have already given you a 3-day timeout. Good. Take the break to read the CoC and return with an appropriate style of engagement if you wish to participate in Rails development. But the warning otherwise stands. The next ban is permanent.

**Pull request merged**
