### PR TITLE
Add Enumerable#single

### PR DESCRIPTION
**Pull request by dnagir**
### Summary

This is inspired by other languages and frameworks, such as LINQ's [Single](https://msdn.microsoft.com/en-us/library/bb155325%28v=vs.110%29.aspx) (pardon from MSDN reference), which has very big distinction between `first` and `single` element of a
collection.
- `first` normally returns the top element, and the developer assumes
  there could be many;
- `single` returns one and only one element, and it is an error if there
  are none or more than one.

We, in Ruby world, very often write `Account.where(name: 'foo').first`
assuming there's only one element that can be returned there.

But in majority of the cases, we really want a `single` element.

The problems with using `first` in this case:
- developer needs to explicitly double check the result isn't `nil`
- in case of corrupted data (more than one item returned), it will never
  be noticed

`Enumerable#single` addresses those problems in a very strong and
specific way that may save the world by simply switching from `first` to
`single`.

Also, we have the answer to universe - `fourty_two`, may as well save the
world with a `single` before waiting for that answer :)
### Other information

We may come with a better internal implementation (than `self.map`), but happy to discuss and fix. `self.map` seems to be pragmatic, performant enough for the typical use case. So may not be an issue at all.

### CODE REVIEW

**Comment by matthewd** [comment]
Possible alternative implementation.. I think I prefer this because it sticks more directly to the "pure" `each` at the root of the enumerable. What do you think?

```ruby
def single
  it = nil
  found = false

  each do |entry|
    raise SingleItemExpectedError, ... if found

    it = entry
    found = true
  end

  raise SingleItemExpectedError, ... unless found

  it
end
```

---

I'm also vacillating on the name... `one` feels like a declarative partner to `one?`; I also rather like `only`.

---

More generally: I like the balance of.. safe optimism, perhaps, that this method allows. It's not hard to find places that can use it in an application, but have you looked into how widely this would be useful inside Rails itself?

**Comment by dnagir** [comment]
Hey @matthewd, yeah it definitely makes sense to only rely on a very generic `each` rather others, such as `map`.
Updated the implementation in cd989227bfb0fe952c17de49d837f81d60487cd0


As for naming. I really don't think `one` is the right name.
Consider: `first`, `second`, `last` and `one`.
Vs: `first`, `second`, `last` and `single`.
However, `only` sounds ok alongside the `first`, `second`, `last`.

RE how useful it would be in rails, pretty much as per the PR description. I see it most useful in the context of `Account.where(name: 'foo').single` where `name` should essentially be unique constraint. But exactly the same applies to any other ORMs (such as Mongoid) so providing a unified way of doing it via `single` makes a lot of sense to me.

I don't know Rails deep enough to tell how useful it will be inside of it. But consider something like:

```
controller.execute_action
response.write result.first
```

vs

```
```

**Comment by dnagir** [comment]
@matthewd also what I found very useful is being able to return a default value only and only if there are no elements in the collection.
So maybe we could also add this implementation here too: `items.single { calculate_deault_value }`?

For example:

```
Account.where(name: 'Foo').single { Account.default }
most_expensive_order = Order.order_by_price.most_recent.limit(1).single { Order.new(price: 0) }
# etc
```

**Comment by dnagir** [comment]
I've added the "default value" in 268c18e93a6a148104797c656cd3f32967585ac7. That should allow some pragmatic flexibility when necessary.

**Comment by mcmire** [comment]
I'd like to offer my input on this.

> We, in Ruby world, very often write `Account.where(name: 'foo').first`
> assuming there's only one element that can be returned there.

First, the code you've provided is Rails code, not Ruby code. `first` may be borrowed from Array#first, but it's not the same thing. It seems odd that you would add this to Enumerable if the problem as you see it has to do with ActiveRecord.

Second, I don't think the statement you've made is true. I think it's very common that there's more than one record present in the database, and it is much less common for there to be just one. I think the problem here is *not* that people assume there is only one record present when there's actually more than one, but that they assume that `first` will really return the first record that's listed in the table (after filtering by conditions, of course).

**Comment by dnagir** [comment]
@mcmire thanks, all good points. The ActiveRecord was just used as an example.
Certainly there are more use cases in plain Ruby.

The scenario you described with `first` is usually such that you want the first entry out of a set. Which implies the set always has to be ordered and you want a top/bottom element. That's a very valid scenario.

But if you only expect one and only one entry in the set, you'll have to do something like:

```
raise 'Should have only one element, but having more than one' if items.size > 1
item = items.first || raise('Should have one element but have none')
```

The above can simply be written as `items.single` (maybe it should be a _bang_ method?).

A small example:

```ruby
view_to_render = all_views
  .select { |v| v.match_format?(format) }
  .select { |v| v.match_processor?(processor) }
  .single # only 1 view that can be rendered
```

So the `single` is an _easy_ way to fail-early if we expect nothing else but a single element.
I found that in the absence of it, it is too easy to just use `first` and forget about doing the one-and-only-one checks.


The use of `first` in this case (without the validation for "one-and-only-one") would technically be incorrect because it may hide the issue of having potentially 2+ views that satisfy the criteria and would be hiding a bigger problem. `single` will help finding the problem much earlier.

`single` is a safer `first`, somewhat like `try!` is a safer `try`.

**Comment by mcmire** [comment]
Okay, I better understand the reference to ActiveRecord's `where(...).first` that you gave in your original comments now. `single!`, it seems, would be sort of the equivalent of `find_by!` (except without the ability to filter).

To be honest I've been doing Rails for a long time and this kind of thing hasn't come up very much in my code. Usually if I want the first match and there is the possibility that nothing matched, raising an exception isn't quite what I want to do; I'll handle that in a more meaningful way instead (such as using the null pattern).

That's my two cents, but perhaps other people can weigh in here.

**Review by davelooi — APPROVED** [review]

**Comment by jeremy** [comment]
Could you propose to upstream Ruby? https://bugs.ruby-lang.org/projects/ruby-trunk/issues

**Comment by dnagir** [comment]
@jeremy done https://bugs.ruby-lang.org/issues/13683.

Would we still consider merging it into AS if Ruby itself isn't going to accept it, just like `fourty_two`? 😉

**Comment by esparta** [comment]
I didn't see the issue as rejected (in upstream). What I see is they are just trying to make it better for more audience. Even nobu gave opinion yesterday.

**Pull request closed without merging**
