### PR TITLE
Document `session.clear` in Action Controller guide

### PR DESCRIPTION
**Pull request by vassilevsky**
Hello 👻

I spent considerable time today before I found this handy method to clear the session so I decided to document it.

Hope this helps!

### CODE REVIEW

**Comment by prathamesh-sonpatki** [comment]
Does `reset_session` not help which is explained as the last option in the same section - http://edgeguides.rubyonrails.org/action_controller_overview.html#accessing-the-session

The `clear` method that you added is not part of public API -- https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/request/session.rb#L6

**Comment by arthurnn** [comment]
can you add a `[skip ci]` comment in the commit message next time? So we don't run CI for doc changes.
Thanks

**Comment by vassilevsky** [comment]
`reset_session` destroys the session and creates a new one.

`session.clear` removes session contents but keeps the session and keeps the session id. I believe that this method is public:

https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/request/session.rb#L119

**Comment by vassilevsky** [comment]
I will [skip ci] the next time. It's a pity that Travis does not (yet?) support ignoring files by globs :(

**Comment by prathamesh-sonpatki** [comment]
> I believe that this method is public:

Please check http://edgeguides.rubyonrails.org/api_documentation_guidelines.html#method-visibility. 

The whole `Session` class is [nodoc'd](https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/request/session.rb#L6)

**Comment by vassilevsky** [comment]
Thank you for the link. I had no idea! Now I do.

**Pull request closed without merging**
