### PR TITLE
[ci skip] Adds Dark Mode for Rails Guides

### PR DESCRIPTION
**Pull request by mgodwin**
### Summary

Adds a dark mode to the rails guides 🌙 .  I went the route of using the media query `prefers-color-scheme`, but if there's interest in making a toggle between light/dark I'm game for making that possible.

### Other Information

I'm not a professional designer so feedback is welcome 🙇 !

There are a few outstanding issues/questions that need to be addressed:

1. Iconography assumes a white background and needs to be updated.  Is there openness to using a font/icon library?  (Are images used because of ebook format or just because the guides have been around for a while?)
2. Are the colors that I picked OK?
3. Did I break anything with the kindle ebook format?
4. The callouts (note, info, code, warning) need a bit of design help to retain their visual prominence - any suggestions?

If there's not a lot of appetite for this with rails guides, let me know!  I thought it could be a nice addition for those of us that find it easier to read in dark mode.

Want to give it a try?  Checkout this branch and run `rake guides:generate:html` from within the `guides` directory.

Thanks!

### Screenshots
image

image

image
☝️ Still need to figure out what to do with the callout section iconography... 🤔

### CODE REVIEW

**Comment by p8** [comment]
Nice! 😄

**Comment by tarellel** [comment]
This looks great, awesome work!

**Review by tarellel — APPROVED** [review]

**Comment by mgodwin** [comment]
Thanks for the approval!  I’m thinking I should get the iconography updated a little bit before merging?  Or do y’all think we should do that in a separate PR?

**Comment by mgodwin** [comment]
I went ahead and added in some icons that are compatible with the darker background.  I used https://heroicons.dev/ which is [MIT Licensed](https://github.com/tailwindlabs/heroicons#license).  Hopefully they seem alright to you all as well!

Here's some screenshots with the updated icons:

|screenshot|||
|----|---|---|
|image|image|image
|image|image

Let me know what you think!  I'll do a little bit of research on the kindle ebook format to make sure I didn't mess anything up there.

Thanks.

**Review by marivaldo — APPROVED** [review]

**Review by zzak — APPROVED** [review]
@mgodwin This is a great first step, I'd like to merge this as-is and iterate on the design to flesh out any quirks and add a toggle once we're feeling good about it.

**Comment by zzak** [comment]
@mgodwin @p8 It'd be great to add the same styles to [sdoc](https://github.com/zzak/sdoc) so the API docs can use dark mode as well <3

**Comment by vipulnsward** [comment]
Started seeing this some time back. Would be good if we allowed a "toggle" for the modes instead of always picking the system preference.

Can be annoying at times.

**Comment by laptopmutia** [comment]
where is the toggle for this?

**Comment by p8** [comment]
@laptopmutia There is no toggle. It depends on you browser settings.

**Pull request merged**
