### PR TITLE
[ci skip] Revise adding articles section in Getting Started guide

### PR DESCRIPTION
**Pull request by tlatsas**
This is the second Pull Request which updates the Getting Started guide as discussed in issue #39920 and a follow up of  #40039.

### CODE REVIEW

**Comment by KapilSachdev** [comment]
Shouldn't the guides be skipping build process with [ci skip]?

**Comment by tlatsas** [comment]
> Shouldn't the guides be skipping build process with [ci skip]?

Could this be some kind of "conflict" with the Co-Authored-By lines?

**Comment by KapilSachdev** [comment]
Till you are adding two newlines before the Co-Authored-By lines, i think that would be fine.
Is this what you meant? or i misunderstood?

**Comment by tlatsas** [comment]
It seems that I need to add `[ci skip]` in the 1st line of the commit and not further down as I did here, sorry for this.

**Comment by KapilSachdev** [comment]
Oh i do misunderstood one part. i just only saw the PR not having the `[ci skip]` and running the build.
The commits do have [ci skip] but they are not working and thats what you meant by "conflict with Co-authored-by:".
Yes, adding in the first line would resolve for sure


Wouldn't it be better if the PR title is updated with [ci skip] (build failure doesn't look good on guide only PR :) )?
And maybe even commits force-pushed?

**Pull request closed without merging**
