### PR TITLE
Make the order of Hash#reverse_merge! consistent with HashWithIndifferentAccess

### PR DESCRIPTION
**Pull request by Erol**
### Summary

Currently, the result of `Hash#reverse_merge!` deviates from the ordering of similar methods:

```
ab = {a: 1, b: 2}
c = {c: 3}

indifferent_ab = HashWithIndifferentAccess.new(a: 1, b: 2)
indifferent_c = HashWithIndifferentAccess.new(c: 3)

ab.reverse_merge(c) #=> {c: 3, a: 1, b: 2}
ab.reverse_merge!(c) #=> {a: 1, b: 2, c: 3}
indifferent_ab.reverse_merge(c) #=> {c: 3, a: 1, b: 2}
indifferent_ab.reverse_merge!(c) #=> {c: 3, a: 1, b: 2}
```

This PR aims to make the element order consistent across the 4 methods such that:

```
ab.reverse_merge!(c) #=> {c: 3, a: 1, b: 2}
```

### CODE REVIEW

**Comment by al2o3cr** [comment]
Probably not a concern in any realistic use cases for this function, but this change does make an extra copy of the original `Hash` compared to the previous implementation.

**Comment by Erol** [comment]
That's true. What I also haven't done yet is run a benchmark to see the impact.

It does make the implementation simpler to maintain, since it's the same as `HashWithIndifferentAccess`:

https://github.com/rails/rails/blob/71da39097b67114329be6d8db7fe6911124531af/activesupport/lib/active_support/hash_with_indifferent_access.rb#L230

A further improvement could be to remove the method definition there, since it inherits from `Hash`.

**Comment by Erol** [comment]
What do you think of this change @sgrif?

**Comment by Erol** [comment]
Hi @maclover7, anyone I can consult this with?

**Comment by Erol** [comment]
Hi @rafaelfranca just wanted to consult with you about this change. If this is something that can be merged, I can have the PR rebased

**Comment by Erol** [comment]
Just saw this, thanks @sgrif

**Pull request merged**
