### PR TITLE
Set up a Docker environment for Rails development

### PR DESCRIPTION
**Pull request by hovsater**
### Summary

I've contributed to Rails a couple of times in the past, and always set up the project locally. However, things would fail, dependencies were added/removed and the whole process became very inconsistent.

The [Development Dependencies Install](https://edgeguides.rubyonrails.org/development_dependencies_install.html) page recommends using the official [rails development box](https://github.com/rails/rails-dev-box) but I'm not a big fan of Vagrant. Docker has increased in popularity, and is many developers tool of choice (including myself) for managing development environments.

My goal with this pull request is to introduce a development environment, based on Docker, that seamlessly (or close to) integrates with the current setup, without requiring any major changes.

This is a first iteration, so I welcome anyone interested in setting it up, trying it out, and giving feedback. Given I'm not super familiar with the codebase, I might have missed important parts of the environment. Feel free to point those out. 🙂 

The easiest way to get going is to [install Docker](https://www.docker.com/get-started), checkout this branch, and run the following commands:

```console
$ docker-compose build
$ docker-compose run --rm rails
```

All set, rock on!

### Other Information
- Currently running Ruby 2.6.6 in the container. Not sure whether or not you want the latest version of Ruby or not.
- I was unsure about documentation. Should it be added to [Development Dependencies Install](https://guides.rubyonrails.org/development_dependencies_install.html)?
- I've tried to run as many tests as possible but there seem to be a few that are flaky (passing sometimes). The tests for MySQL, PostgreSQL and Sqlite3 all seem to be pass. Some tests are failing and I'm not sure whether or not it's due to my environment or not. Would love some help debugging that if possible.
- Environment variables needed by docker are currently set in a `.env` file in the root of the project. Docker automatically pick those up when you spin up a container. If the `.env` file is an issue, we can set those values explicitly in the `docker-compose.yml` file instead, or use another file (less generic) via [env_file](https://docs.docker.com/compose/compose-file/#env_file).

### CODE REVIEW

**Comment by KevinSjoberg** [comment]
@eileencodes I'm not sure who to reach out to, but I'd love some feedback on this. Could you help me out or point me in the right direction? 😊

**Comment by rafaelfranca** [comment]
Thank you for the pull request but we don't want to maintain a docker infrastructure in our repository. Maybe you should open a PR against https://github.com/rails/rails-dev-box

**Comment by KevinSjoberg** [comment]
@rafaelfranca in case they're not interested in keeping the Docker environment adjacent to the Vagrant environment, would it be possible to have this in its own repo such as `rails/rails-dev-docker`?

**Comment by rafaelfranca** [comment]
Not really because we would have to maintain something that we don't use, and we already learned the lesson that this doesn't work very well. If we setup a docker environment someone from the core team needs to use.

**Comment by KevinSjoberg** [comment]
I'd be happy maintain it. What doesn't work well? I'm genuinely interested in what's not working for you and why having a Docker setup is a bad idea?

I never expected you or anyone else of the core team to commit in maintaining this forever and ever. 

I think it would be nice to have the ability to choose between Vagrant and Docker.

**Comment by rafaelfranca** [comment]
> I'd be happy maintain it. What doesn't work well? 

You are free to maintain in your own repository, but to be part of the rails org and documentation the core team needs to want to maintain it.

> I'm genuinely interested in what's not working for you and why having a Docker setup is a bad idea?

Everything is working fine to me. I don't use docker or either Vagrant and I do think that is a better setup to me. I don't think it is a bad idea, I just don't think we should maintain that setup. To maintain, someone from the core needs to be willing to do. This is why I asked to open an issue on the rails-dev-box since a member of the core team that uses that setup could be also willing to use Docker for it instead of Vagrant.

**Comment by KevinSjoberg** [comment]
That makes sense. Thanks for taking the time to clarify. 🙂

**Pull request closed without merging**
