### PR TITLE
Add the webpacker guide to index page.

### PR DESCRIPTION
**Pull request by morgoth**
Follow up to https://github.com/rails/rails/pull/40817

[CI skip]

### CODE REVIEW

**Comment by morgoth** [comment]
@fxn as promised

**Comment by kamipo** [comment]
Duplicate with #41161.

**Comment by fxn** [comment]
Merged the other one, because it was first and had a slightly better description.

@morgoth should be online soon.

**Comment by morgoth** [comment]
Thanks and sorry - I didn't check open pull requests before opening this one.

**Pull request closed without merging**
