### PR TITLE
Protect against invalid validate option on remove_check_constraint

### PR DESCRIPTION
**Pull request by shayonj**
### Motivation / Background

When you have a `remove_check_constraint` with `validate: false`, the Rails migration can fail, producing the error: `raise(ArgumentError, "Table '#{table_name}' has no check constraint for #{expression || options}")`.

```ruby
remove_check_constraint(
  :diagram_notes,
  "width IS NOT NULL",
  name: "diagram_notes_width_null",
  validate: false,
)
```

This occurs because `remove_check_constraint` calls `check_constraint_for!`, which filters out any validations of constraints that may have `validate: false`. Since `validate` is an acceptable option on `add_check_constraint` but not on `remove_check_constraint`.

### Detail

In this PR - I am proposing to ensure that migrations do not fail with an unrelated or hard-to-understand exception when `validate: false` is accidentally passed to `remove_check_constraint`. We are simply dropping that attribute. 

### Additional information

Have followed it up with a spec as well. 

### Checklist

Before submitting the PR make sure the following are checked:

* [X] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [X] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [X] Tests are added or updated if you fix a bug or add a feature.
* [X] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by jeromedalbert** [comment]
There is no attached issue for this PR so let's validate the underlying issue first.

If I understand correctly, the `:validate` option only makes sense for [`add_check_constraint`](https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-add_check_constraint), and only makes sense for Postgres, as explicitly documented. But it does not make sense for [`remove_check_constraint`](https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-remove_check_constraint) and is therefore not documented.

The issue apparently happens if you provide `validate: false` to `remove_check_constraint`. Providing `validate: false` would make sense to keep `remove_check_constraint` [reversible](https://guides.rubyonrails.org/active_record_migrations.html#using-the-change-method) with original options (including `validate: false`) inside a migration `change` method.

@shayonj:

- Can you provide steps to reproduce the issue? Ideally with a minimal postgres example app? Also, to maximize changes of merging this PR, you could follow [contributing guide](https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report) by make a separate issue first, and then linking it to this PR.
- This PR should be rebased as it currently has conflicts.

**Comment by fatkodima** [comment]
This PR is invalid, because `remove_check_constraint` actually accepts a `:validate` option (postgres only), even though it is not documented. It basically means - "remove this check constraint only if it is (in)valid". The same for foreign keys helpers.

**Comment by jeromedalbert** [comment]
Maybe this PR can be closed then

**Comment by shayonj** [comment]
Another thought - Deleting the attribute in this PR made no other specs fail, so I wonder if that behavior has enough test coverage too  🤔

**Comment by fatkodima** [comment]
Docs and tests PR welcome 👍

**Pull request closed without merging**
