### PR TITLE
fix railties tests

### PR DESCRIPTION
**Pull request by meinac**

### CODE REVIEW

**Comment by meinac** [comment]
This pr fixes failing railties tests.

**Comment by kaspth** [comment]
Duh, I should have noticed the original PR shouldn't have had [ci skip] before I merged. Guess I'm great at breaking Rails :sweat_smile:

LGTM.

**Comment by meinac** [comment]
@kaspth It was my fault sorry about that :pensive:

**Comment by eileencodes** [comment]
Thanks @meinac!

**Comment by kaspth** [comment]
@meinac No worries :heart:

**Pull request merged**
