### PR TITLE
Add `ruby` back into generated Gemfile

### PR DESCRIPTION
**Pull request by mattbrictson**
### Motivation / Background

The Gemfile generated by `rails new` should contain a `ruby` declaration. It was temporarily removed in commit 75d5308f81. This PR adds it back.

### Detail

The `ruby` declaration was removed from the Gemfile template temporarily in commit 75d5308f81 (Feb 2024). The reasoning, as I understand it, was that the devcontainer images were not yet being published with patch-level tags. As a result, the `ruby` declaration would "over-specify" the version number, which would be incompatible with the devcontainer image.

Now that the devcontainer images have patch-level Ruby tags (see 5fcbc2c421a), it should be safe to add the `ruby` declaration back into the Gemfile.

This will also unblock #49360, which was previously reverted.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
It wasn't temporary. It was permanent. Putting the Ruby version in the Gemfile is a bad practice in our opinion.

See discussion here https://github.com/rails/rails/issues/51089#issuecomment-1944836860

**Comment by mattbrictson** [comment]
Thanks, I missed that discussion. It seems like Heroku still requires the `ruby` declaration, so Heroku users will need to add the declaration manually before deploying, else they will get a Ruby version they don't expect.

> If your Gemfile doesn’t contain a `ruby` entry, you get MRI 3.1.6.
We highly recommend specifying a Ruby version in your Gemfile and not relying on the default Ruby version.

https://devcenter.heroku.com/articles/ruby-support#ruby-versions

Hopefully Heroku follows the lead of other platforms like Render, which use `BUNDLED WITH` in the lock file or use the `.ruby-version` file: <https://docs.render.com/ruby-version>.

Do you know of a way to make Heroku aware of this issue?

**Comment by skipkayhil** [comment]
cc @schneems anything we can do to help with that?

**Comment by schneems** [comment]
Heroku needs it to be in the Gemfile.lock. That’s all.

> and I'm pretty sure we can teach Heroku to read it.

Add a line in the Gemfile that reads in the .ruby-version and case closed. The reason Heroku doesn’t support .ruby-version is that it has no way to declare jruby or another engine but Bundler does.

As long as your Ruby version ends up in your Gemfile.lock Heroku will give you the right thing.

Does “rails new” on main give you a Ruby version in the Gemfile.lock? If not, that seems like a bug.

**Comment by skipkayhil** [comment]
> Does “rails new” on main give you a Ruby version in the Gemfile.lock? If not, that seems like a bug.

It does not, the `ruby` line was updated to `ruby file: ".ruby-version"` in #49360 and then later removed completely in 707b5cb / 75d5308f81ad5e45cd05ccf1132cc780481b9c04

Discussion in #51089

**Comment by schneems** [comment]
Ahh, changing well established standards for no gain and likely inconsistencies and fragmenting in the ecosystem 👍🏼

I’m on vacation now. But I left a comment over there. Can someone open an issue about rails new not updating the Ruby version in the Gemfile.lock?

**Pull request closed without merging**
