### PR TITLE
`ActiveRecord::PredicateBuilder#expand` to be private

### PR DESCRIPTION
**Pull request by yui-knk**
This method is not touched from outside.

### CODE REVIEW

**Comment by kaspth** [comment]
True the `PredicateBuilder` is marked as `:nodoc` so we could move this method. I think that's more of a cosmetic commit though, so I'm going to leave this be. Thanks for the pull request!

**Comment by yui-knk** [comment]
Thanks for your review, I know this class is `nodoc`. But I think correcting the visibility of method is not cosmetic, because the visibility of method defines which methods would be called from instances of other classes.

**Comment by kaspth** [comment]
@yui-knk alright, you won me over. Thanks!

**Comment by yui-knk** [comment]
😍 😍

**Pull request merged**
