### PR TITLE
Concurrent load interlock (rm Rack::Lock)

### PR DESCRIPTION
**Pull request by matthewd**
Instead of forcing `Rack::Lock` when `eager_load` and `cache_classes` aren't on, just prevent actual conflicts.

We achieve this by means of a (reentrant) shared-exclusive lock: multiple running concurrent requests are fine, but any load activity must be performed in isolation.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
@matthewd are you thinking in moving this forward? I believe this is the best time to do it.

**Comment by fxn** [comment]
:+1: makes sense for 5.0.

**Comment by thedarkone** [comment]
I'm thinking - this will not work if user decides to spin up his own threads (because we will not be able to track whether they have entered "app space"). Also, how would this work with background jobs?

**Comment by matthewd** [comment]
For background jobs: the job-runner would wrap the job-doing code just as ActionDispatch does for requests. (And as it presumably already does for the AR conn pool, for example.)

If the user spins up their own thread (and doesn't opt in to the interlock), however... yeah, they're going to be in danger of seeing a half-loaded constant. Avoiding that sounds expensive. :confused:

**Comment by mperham** [comment]
This is so awesome.  I think we can modify Sidekiq to reload job code in development mode now!

**Pull request merged**
