### PR TITLE
Fix possible memory leak of ConnectionHandler

### LINKED ISSUE #35296: ConnectionHandler never gets GC'd
### Steps to reproduce

```rb
require 'active_record'
ActiveRecord::ConnectionAdapters::ConnectionHandler.new
GC.start
p ObjectSpace.each_object(ActiveRecord::ConnectionAdapters::ConnectionHandler).to_a
```

### Expected behavior

The unnamed instance of `ActiveRecord::ConnectionAdapters::ConnectionHandler` is GC'ed and it prints `[]`

### Actual behavior

It shows that the instance is still alive

```rb
[#<ActiveRecord::ConnectionAdapters::ConnectionHandler:0x00007fbcfd1eab88 @owner_to_pool=#<Concurrent::Map:0x00007fbcfd1eab38 entries=0 default_proc=#<Proc:0x00007fbcfd1ea9a8@a.rb:8>>>]
```

### System configuration
**Rails version**: 5.2.0, 6.0.0.beta1, git master 

It does not happen with 5.1.6.1.

**Ruby version**: 2.5.3

### PR DESCRIPTION
**Pull request by yhara**
### Summary

This PR fixes #35296.

### CODE REVIEW

**Comment by kamipo** [comment]
Thanks you guys for taking the time! @yhara @nobu

**Comment by matthewd** [comment]
How does this change anything? If it's only being retained by the machine stack, I don't see how that's a real problem.

If there's real retention, #35296 sounds more like #33094 to me.

**Comment by kamipo** [comment]
We've disscussed about the usage of the `ObjectSpace.define_finalizer` in the thread https://twitter.com/yhara/status/1096765718698192896.

As @yhara described at https://github.com/rails/rails/issues/35296#issuecomment-464319765, the default proc in the `@owner_to_pool` has a reference to the handler as the implcit `self`, so the finalizer proc which has a reference to the `@owner_to_pool` is not right usage to pass `ObjectSpace.define_finalizer`.

That is noted the doc in Japanese https://docs.ruby-lang.org/ja/latest/method/ObjectSpace/m/define_finalizer.html (not in English though https://ruby-doc.org/core-2.6.1/ObjectSpace.html#method-c-define_finalizer)

Do you mean that there is no reason to touch the code unless that is a real world problem?

**Comment by matthewd** [comment]
Ah okay, I didn't read that comment closely because it seemed to be in between several other theories, and because its last line suggested it was already disproven.

Beyond the fact this PR wasn't clear in describing the reason for a very subtle change, my remaining concern would be that we don't have anything to prevent a future change from breaking it again (and unlike `unowned_pool_finalizer`, it's less obvious even for a reviewer familiar with the special needs of finalizers).

(The new method should also be `:nodoc:`, and the "the above early discard" comment probably needs rephrasing... and finally, looking at the set of four methods, I get the feeling a different arrangement of responsibilities might be clearer)

---

A true leak is definitely worth fixing; I just didn't read closely enough to confirm that the machine stack theory was eliminated (and _that_ would not be a true leak).

**Pull request merged**
