### PR TITLE
Fix namespaced nested routes

### PR DESCRIPTION
**Pull request by germanescobar**
I have the following namespace with nested resources (the models are namespaced with `admin` as well):

```
namespace :admin do
  resources :categories do
    resources :products
  end
end
```

However, when I generate a path such as `[@category, @product]` I get an:

> undefined method `admin_category_admin_product_path` ...
> Did you mean?  `admin_category_product_path`
>                            `admin_category_products_path`

I fixed this with monkey patching in my project but thought that this change could benefit others.

**Note:** I know that this can be solved using `use_relative_model_naming?` and a scope instead of a namespace, but this PR provides a valid option for people that want to use the namespace.

### CODE REVIEW

**Comment by senny** [comment]
If the path is namespaced routes can be generated using a symbol:

```ruby
[:admin, @category, @product]
```

**Comment by rafaelfranca** [comment]
Yes, that is the way you generate namespaced paths. @germanescobar is not that working for you?

**Comment by germanescobar** [comment]
@senny @rafaelfranca not if the models are namespaced as well. `[:admin, @category, @product]` will produce: `admin_admin_category_admin_product_path` which is not correct.

**Comment by germanescobar** [comment]
So, the problem is with the namespaced models. I realized that we can define
```
def self.use_relative_model_naming?
  true
end
``` 
 in the module or the models, and then do `[:admin, @category, @product]`.

This PR would allow us to do `[@category, @product]` (no need to define the `self.use_relative_model_naming?` method) and get `admin_category_product_path` if the models are also namespaced with `admin`.

**Comment by senny** [comment]
@germanescobar what is wrong with using `use_relative_model_naming?`? I also think that we should stay consistent and always pass the symbol for route generators with a prefix.

**Pull request closed without merging**
