### PR TITLE
Fix inherited controller model partial issue

### PR DESCRIPTION
**Pull request by savroff**
### Summary

We can see that in issue https://github.com/rails/rails/issues/29468 we have problems when we want to use controller inheritance. Nested controller model partials should follow same rules as views and not model related partials. Plus I changed all test controllers to inherit from `ApplicationController`, because right now they inherit directly from `ActionController::Base`, but we even force people to have some sort of application controller in our documentation [here](http://api.rubyonrails.org/classes/ActionController/Base.html)

I also suggest to fully deprecate logic around `prefix_partial_path_with_controller_namespace` in next major release.
By default, a model should follow the model path and if you want to change it you should just send path as param:

```
<%= render partial: "different_path/article", collection: @articles %>
```

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Please don't change the assignment. The bot assign to people randomly exactly to alleviate the work of the maintainers. It is not because someone is more active that they need to review all the PRs.

**Comment by savroff** [comment]
@rafaelfranca got it.

**Comment by savroff** [comment]
Should I close this one?)

**Pull request closed without merging**
