### PR TITLE
ignore reverse_order when finding in batches

### PR DESCRIPTION
**Pull request by robertjlooby**
Fixes https://github.com/rails/rails/issues/17854

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Thank you for the pull request. Does this happen on master and 4.2.X? If so please open a pull request against master branch.

**Comment by robertjlooby** [comment]
Yes it doesn't happen in 4.2/master since reordering after a reverse drops the reverse

**Comment by rafaelfranca** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by ffloyd** [comment]
Why just ignoring? Why not exception?

Ordering, limiting - it may be sensitive part of business logic. Even warning is not enough, imho, only exception.

**Comment by rafaelfranca** [comment]
Feel free to open a PR.

**Pull request merged**
