### PR TITLE
Add `rake initializer`

### PR DESCRIPTION
**Pull request by naoty**
This task prints out initializers for an application. It is useful to
develop a rubygem which involves the initialization process.

### CODE REVIEW

**Comment by chancancode** [comment]
Should this be `rake initializers`? ( <--> `rake routes`)

**Comment by rafaelfranca** [comment]
We have `rake middleware` :cry:

**Comment by chancancode** [comment]
Hmm true. But in that case it's going to disagree with either one of them anyway, so might as well go with whatever we think is "better" :stuck_out_tongue:

There's also `rake annotations`, so my vote is for plural!

**Comment by rafaelfranca** [comment]
:+1:

**Comment by chancancode** [comment]
Committed 9e80c29cd5f82359730e7e7474c24b8ab844549d :smiley:

**Comment by andrewhr** [comment]
`rake middleware` could be read like "Give me our middleware stack". I like to imagine that's why it's in the singular :bike: :art:

**Comment by naoty** [comment]
I'm also agree with `rake initializers`. :ok_hand:

**Pull request merged**
