### PR TITLE
[RFC] JSON API mapping of camelCase *request* params to snake_case

### PR DESCRIPTION
**Pull request by eliotsykes**
Request for comments on how to reduce the complexity of providing an API that uses JSON-conventional camelCase naming and lives in harmony with Rails-conventional snake_case.

This is so param-handling code like below can be written in an API controller using snake_case, even though the password_confirmation param was submitted with the camelCase name passwordConfirmation:

``` ruby
  def registration_params
    # password_confirmation param was submitted as passwordConfirmation
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
```
#### Rails 4.2 support via initializer currently requires this:

``` ruby
Rails.application.config.middleware.swap(
  ::ActionDispatch::ParamsParser, ::ActionDispatch::ParamsParser,
  ::Mime::JSON => Proc.new { |raw_post|
    # Borrowed from action_dispatch/middleware/params_parser.rb except for
    # data.deep_transform_keys!(&:underscore) :
    data = ::ActiveSupport::JSON.decode(raw_post)
    data = {:_json => data} unless data.is_a?(::Hash)
    data = ::ActionDispatch::Request::Utils.deep_munge(data)
    data.deep_transform_keys!(&:underscore)
    data.with_indifferent_access
  }
)
```
#### Becomes this initializer if ParamsParser accepted param_key_transform arg

``` ruby
Rails.application.config.middleware.swap(
  ::ActionDispatch::ParamsParser, ::ActionDispatch::ParamsParser, {}, :underscore
)
```

### CODE REVIEW

**Comment by eliotsykes** [comment]
Might be of interest to @uberllama, saw your related contributions here: https://github.com/rails/rails/pull/19832#issuecomment-104674321

**Comment by michelaungthein** [comment]
please.please.the best of regard to me. please

**Comment by eliotsykes** [comment]
Closing and reopening PR to trigger a new CI build

**Comment by uberllama** [comment]
Sorry was out of town last week. Definite thumbs up, tho it would be great to abstract out the configure instead of directly swapping middleware. PR link?

**Comment by eliotsykes** [comment]
Thanks for the responase @uberllama - agreed about a config option being an improvement over recreating the middleware. 

Here's the changes made so far for this PR: https://github.com/rails/rails/pull/20389/files if that's what you mean for the PR link.

There's no config option yet so suggestions welcome.

**Comment by uberllama** [comment]
Rack::Sendfile can use a value set via config.action_dispatch.x_sendfile_header. There are a couple other middlewares that do the same. So given that precedent we should be able to define something along the lines of config.action_dispatch.accept_camelcase_params and conditionally act on that within the ParamsParser middleware instead of having to do the swap business.

**Comment by uberllama** [comment]
Okay, here's what I'm thinking:

actionpack/action_dispatch/railtie.rb: Add a new config:

```ruby
require "action_dispatch"

module ActionDispatch
  class Railtie < Rails::Railtie # :nodoc:
    config.action_dispatch.accept_camelcase_params = false
    ..
    initializer "action_dispatch.configure" do |app|
      ActionDispatch::ParamsParser.accept_camelcase_params = app.config.action_dispatch.accept_camelcase_params
```

Then within `ActionDispatch::ParamsParser`:

```ruby
mattr_accessor :accept_camelcase_params
...
def parse_formatted_parameters(env)
   case strategy
       ...
        when :json
          data = ActiveSupport::JSON.decode(request.raw_post)
          data = {:_json => data} unless data.is_a?(Hash)
          data = Request::Utils.deep_munge(data)
          data.deep_transform_keys!(&:underscore) if accept_camelcase_params
          data.with_indifferent_access
          ...
```

Then within application.rb you can just put `config.action_dispatch.accept_camelcase_params`.

Haven't tested this but looks reasonable. Let me know if you want mew to put together a different PR or if you're comfortable trying this out.

**Comment by eliotsykes** [comment]
@uberllama Sorry for the delay in responding. I'm hoping we'll get some other voices in here who can tell us yes this is something welcome for Rails or otherwise so as not to spend too much time on it.

I like the idea of having a dedicated config, though I'm not sure about the `accept_camelcase_params`  name. 

The param keys are transformed and in a controller it'd not be possible to use camel-case to access the parameters, you'd have to use snake-case, but the `accept_camelcase_params` sounds like you could use the camel-case names in a controller.

Something along the lines of `config.action_dispatch.transform_camel_params_to_snake` perhaps.

**Comment by uberllama** [comment]
We can name it `.ride_my_little_ponies` for all I care. :) I just want it! As far as returning params as camelCase goes, there's a single line Jbuilder config that does just that. So combined you have a fully standard camelCase JSON API.

As I said, I'm happy to submit a new PR following my comments above if you like.

**Comment by eliotsykes** [comment]
Good to know about jbuilder's option. +1 for your config name suggestion, but in case that doesn't go down well with rails core, I'm quoting the jbuilder docs on `camelize` as it may be helpful when coming up with a config name:

> Keys can be auto formatted using key_format!, this can be used to convert keynames from the standard ruby_format to camelCase:
```
json.key_format! camelize: :lower
json.first_name 'David'

# => { "firstName": "David" }
```
> You can set this globally with the class method key_format (from inside your environment.rb for example):
```
Jbuilder.key_format camelize: :lower
```

If you're up for submitting a PR, please go ahead. I've no idea if anything on this will be accepted but I sure hope it is.

**Comment by uberllama** [comment]
K, I'll try to get something in this week, children willing. :)

**Comment by uberllama** [comment]
As an aside, we should also transform `query_parameters` or provide config options for both. I'm hoping to have something this week still after testing locally.

**Comment by jachenry** [comment]
ParamsParser was recently moved as part of this [commit](https://github.com/rails/rails/commit/38d2bf5fd1f3e014f2397898d371c339baa627b1) for milestone 5.0. @tenderlove could you suggest an alternative method now that parsing is handled by the request.

**Comment by maclover7** [comment]
Please rebase.

**Comment by eliotsykes** [comment]
@maclover7 any suggestions on what the rebase outcome ought to be. 

I think the ParamsParser changes suggest (assuming I'm reading them right) mapping param keys camel-case to snake-case is now reduced to a Proc config like:

```ruby
ActionDispatch::Request.parameter_parsers[Mime[:json]] = lambda { |raw_post|
  data = ActiveSupport::JSON.decode(raw_post)
  data = {:_json => data} unless data.is_a?(Hash)
  data.deep_transform_keys!(&:underscore)
}
```

**Comment by bf4** [comment]
fwiw, JSON API uses kebab case, which we may want to support when JSON API is integrated in Rails. ref: https://github.com/rails/rails/pull/20389

**Comment by rafaelfranca** [comment]
I'll postpone this change to when we are working in a better integration to the JSON API. For now I'm going to close this PR but thanks for working on this.

**Comment by jachenry** [comment]
If you used @eliotsykes solution from above, you'll need to reference the mime type symbol when upgrading to 5.0.0 beta 3.

```
# File: config/initializers/json_param_key_transform.rb
ActionDispatch::Request.parameter_parsers[Mime[:json].symbol] = lambda { |raw_post|
  data = ActiveSupport::JSON.decode(raw_post)
  data = {:_json => data} unless data.is_a?(Hash)
  data.deep_transform_keys!(&:underscore)
}
```

**Comment by vladra** [comment]
Is there any way to do same transformation for GET request?

**Comment by alan-pie** [comment]
Was this configuration ever implemented or is the initializer in [jachenry's comment](https://github.com/rails/rails/pull/20389#issuecomment-198759230) still the best solution?

**Pull request closed without merging**
