### PR TITLE
Add BOOTSNAP_READONLY to Dockerfile template for production

### PR DESCRIPTION
**Pull request by technicalpickles**
### Motivation / Background

This was added in back in bootsnap 1.15.0 (https://github.com/Shopify/bootsnap/pull/428). This can save extra work and IO when the cache won't be changed, like is the case for docker containers

### Detail

This Pull Request changes the Dockerfile template used when creating a new application to add `BOOTSNAP_READONLY=1`

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [ ] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [ ] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by byroot** [comment]
This shouldn't make much of a difference in this context, Docker preserve mtime so bootsnap shouldn't have anything to update.

But actually, would need to measure, but I suspect this is actually harmful because you set it before `rake assets:precompile`, so I suspect Bootsnap won't be able to persist its load path cache, marking the final image boot slower.

**Comment by technicalpickles** [comment]
Someone pointed out that the ENV would need to go into final image 😅 I think that would mitigate the concern about precompile since it wouldn't be read-only until the image is run.

**Comment by byroot** [comment]
> do you have any thoughts on how to measure the impact on this?

Yeah, just need `time bin/rails runner 1` in production mode.

You can also set `BOOTSNAP_LOG=1` to see if there is cache misses.

**Comment by n-rodriguez** [comment]
I've tested it and it drastically changes application boot time: down from near 2mn to 30s 😃

**Comment by byroot** [comment]
> I've tested it and it drastically changes application boot time: down from near 2mn to 30s 😃
> 
> Edit: the app runs in Docker, on HDD drives

That's in "too good to be true" territory. Can you try just disabling Bootsnap to compare?

**Pull request closed without merging**
