### PR TITLE
Serve unminified activestorage.js version

### PR DESCRIPTION
**Pull request by dixpac**
I'm having problems debugging `activestorage.js` in development because it's served as a minified version.
This PR serves unminified version and leaves this process to sprockets or webpack. Not sure if this is the smartest solution to approach this problem since acticestorage js is implemented with webpack.

r? @javan

### CODE REVIEW

**Comment by javan** [comment]
I'm open to distributing an unminified version, but the default non-prodcution webpack build is a bit too noisy. Would a source map be useful for you in debugging?

**Comment by dixpac** [comment]
@javan I agree! 
Source-maps would be even better...I've fixed PR to use source-maps. WDYT?

**Comment by javan** [comment]
Nice! I think we should add `"app/assets/javascripts/*.js.map"` to:
https://github.com/rails/rails/blob/ffd9902b4464719bd92d49db709d1cf8865337e3/activestorage/package.json#L6-L8
(`*.js` would work as-is, but I'd prefer to be explicit)

**Comment by javan** [comment]
@matthewd, you're not going to like this, are you? :)

**Comment by rafaelfranca** [comment]
Since we are already adding the minified version of the file in the repository I don't see why not add the source maps

**Comment by javan** [comment]
I only hesitate because of the file size. `activestorage.js` weighs in at a reasonable ~18 KB, but `activestorage.js.map` is significantly larger at ~116 KB.

**Comment by sgrif** [comment]
The repo (on my machine) is 3.31GB. I don't think 116K is a huge concern.

**Comment by matthewd** [comment]
Indeed I am not :confused:

I really wish we were building them both at release time. Can't we (say) rely on webpacker to serve it when working from git?

@sgrif my checkout is 100 MB, plus 170 MB in `.git`. When that's 116 KB that'll change completely in response to any change in the source, it's going to quickly account for a nontrivial portion of total repo weight.

**Comment by dixpac** [comment]
@javan  I've added explicit `"app/assets/javascripts/*.js.map"` into the files arrays!

Re: size, there is one more option. I could try to convert js from webpack implementation to coffee script and implement it directly inside engine assets

**Comment by dixpac** [comment]
Guys, can I do anything on my side to move this forward? 😃

**Comment by javan** [comment]
@dixpac, no, sorry, we'll sort this out and make a call. Thank you!

> I really wish we were building them both at release time

@matthewd, me too, but that would mean you can't run off master.

> Can't we (say) rely on webpacker to serve it when working from git?

Not really.. You can point your app's `package.json` at a GitHub repo, but only if that repo has *its* `package.json` in the root. It worked when activestorage was its own gem (`rails/activestorage`). Doesn't work now that it's in `rails/rails/activestorage`.

You *can* run off master now using the asset pipeline because we have a compiled `activestorage.js` in git.

**Comment by matthewd** [comment]
> You can point your app's package.json at a GitHub repo, but only if that repo has its package.json in the root

Ah, so for webpack you can't use the git repo at all, so it doesn't matter what's precompiled-for-commit vs compiled-for-release?

If it's just about Sprockets, that seems surmountable: we force the coffeescript compile for Action Cable. If necessary (this build requires webpack, right?), it seems like we should be able to throw together a sprockets processor that invokes webpack to build this on demand. (Plenty of 'real' sprockets handlers boil down to "run this external command")

**Comment by javan** [comment]
I feel like the best middle ground at this point would be making `activestorage.js` unminified as this PR originally did. We'll get more meaningful diffs for the compiled file in git (instead of diffs like https://github.com/rails/rails/commit/f17137b0a1903203b09301b8141b5baf54561ef0), and the need for a source map mostly goes away.

@matthewd, feel free to "throw together" a sprockets processor if that interests you.

**Comment by dixpac** [comment]
IMO source maps solution is nicer to work with and makes more sense for what we are trying to accomplish. But, serving unminified js will also work I can revert to the original commit :)

**Comment by javan** [comment]
@dixpac hold tight until we reach some sort of consensus, please.

**Comment by javan** [comment]
Thank you! Ended up going in a slightly different direction.

**Pull request closed without merging**
