### PR TITLE
Don't hide underlying test failure in ActiveRecord::TestCase#assert_sql

### PR DESCRIPTION
**Pull request by drcapulet**
If a test case raises an error that prevents a query from being executed, the `ensure` block will override that failure which hampers debugging efforts when writing test cases.

### CODE REVIEW

**Comment by SkipKayhil** [comment]
Instead of wrapping in `unless $!`, couldn't you remove `ensure`?

**Comment by byroot** [comment]
Look like this one was missed in https://github.com/rails/rails/pull/37313

The best solution would be to use `_assert_nothing_raised_or_warn`, see: https://github.com/rails/rails/commit/4b42beb3b842f6fb94c6fe1b1f7fd12d03f78821

**Comment by drcapulet** [comment]
Yeah, I can definitely simplify this - just the result of staring at this code too long. I'm a bit confused as to the use of `_assert_nothing_raised_or_warn`? Or is that just to have the underlying exception warn?

**Comment by byroot** [comment]
> Or is that just to have the underlying exception warn?

Yes.

**Comment by drcapulet** [comment]
Ah gotcha - the case I was actually originally having issues wasn't necessarily an expectation failure, just a normal exception. Is there a reason the assertions are stuffed into the `ensure` block and not just: 

```ruby
def assert_sql(*patterns_to_match, &block)
  capture_sql(&block)

  failed_patterns = []

  patterns_to_match.each do |pattern|
     failed_patterns << pattern unless SQLCounter.log_all.any? { |sql| pattern === sql }
  end

  assert failed_patterns.empty?, "Query pattern(s) #{failed_patterns.map(&:inspect).join(', ')} not found.#{SQLCounter.log.size == 0 ? '' : "\nQueries:\n#{SQLCounter.log.join("\n")}"}"
end
```

**Comment by byroot** [comment]
> the case I was actually originally having issues wasn't necessarily an expectation failure

Yes. `_assert_nothing_raised_or_warn` is not for assertion failures, but for regular app errors.

> Is there a reason the assertions are stuffed into the ensure block and not just:

It was likely for the same reason `_assert_nothing_raised_or_warn` was introduced, just not well done.

**Comment by byroot** [comment]
Fixed in https://github.com/rails/rails/pull/44484. I gave you co-authorship for bringing up the issue.

Thanks!

**Comment by drcapulet** [comment]
@byroot Thanks!

**Pull request closed without merging**
