### PR TITLE
Could not delete a record that is not in default scope

### PR DESCRIPTION
**Pull request by chumakoff**
### Summary

If a model has a default scope set, it is not possible to remove an instantiated record with `delete` method which is not in the default scope.
### Other Information

Example:

```
class Article < ApplicationRecord
  default_scope { where(published: true) }
end

a = Article.unscoped.where(published: false).first
a.persisted? # true
a.published # false
a.delete
a.persisted? # false
Article.unscoped.find_by(id: a.id) # returns the article that was removed, expected nil
```

### CODE REVIEW

**Comment by som4ik** [comment]
I have had this problem in a project on Rails 4.2.4. Spent a lot of time trying to understand why comments come back to life after I successfully '@comment.delete' them. Using 'destroy' instead of 'delete' solved the problem however.

**Comment by jdanielnd** [comment]
Your main intent is to allow deleting instances that aren't in the default_scope. It makes total sense, since you are specifying the instance you want to delete.

However, this creates the side-effect of also allowing you to delete objects that aren't in the default_scope if you provide `Model.delete([1, 2, 3])` an array of ids. Is this also desirable?

```
  def test_delete_multiple_records_that_are_not_in_default_scope
    comment_id_1 = CommentWithDefaultScopePostId.create!(post_id: 2, body: 'Test 1').id
    comment_id_2 = CommentWithDefaultScopePostId.create!(post_id: 2, body: 'Test 2').id
    
    CommentWithDefaultScopePostId.delete([comment_id_1, comment_id_2])
    
    assert_not_nil CommentWithDefaultScopePostId.unscoped.find_by(id: comment_id_1)
    assert_not_nil CommentWithDefaultScopePostId.unscoped.find_by(id: comment_id_2)
  end
```

**Comment by chumakoff** [comment]
@jdanielnd You are absolutely right. This is not desirable. Besides, `Model.destroy([1,2,3])` does not allow to remove objects that are not in default_scope, so `Model.delete([1,2,3])` must not allow that too. 

Thank you for your suggestion! I edited the PR

**Comment by qinmingyuan** [comment]
The same issue. any problem for the PR opening?

**Comment by kamipo** [comment]
Closing in favor of #29816.

**Pull request closed without merging**
