### PR TITLE
Add days_in_year method to Time class

### PR DESCRIPTION
**Pull request by pacso**
Adds a `days_in_year` method to the `Time` class.

Returns `365` for common years and `366` for leap years.

### CODE REVIEW

**Comment by pixeltrix** [comment]
@pacso can you add a CHANGELOG entry please - thanks

**Comment by pacso** [comment]
@pixeltrix - Have added an entry to the activesupport CHANGELOG now.

Cheers,
Jon

**Comment by pixeltrix** [comment]
@pacso sorry to be a pain, but could you please squash them into a single commit - thanks

**Comment by pacso** [comment]
@pixeltrix no problem at all. Should already be done.

**Comment by pixeltrix** [comment]
@pacso thanks for your contribution!

**Pull request merged**
