### PR TITLE
Instrument unhandled errors in ActiveJob

### PR DESCRIPTION
**Pull request by kjlape**
### Summary

Add instrumentation for unhandled Active Job errors. Subscribers on `unhandled_error.active_job` will receive an event whenever an error occurs that isn't already handled by `rescue_from` (i.e. `retry_on` and `discard_on`).

### Other Information

Today I am aware of a couple ways to accomplish this:
1) Subscribe to `(perform|enqueue).active_job` and check for `exception_object` in the payload.
2) Roll your own instrumentation in a base class or module.

The first technique actually yields every error including exceptions handled by `rescue_from`, so it doesn't completely meet the criteria for this PR. The second technique leads to many implementations, which makes codebases less approachable and more challenging for general purpose tooling based on this kind of instrumentation.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Thank you for the pull request. Can you explain why you need this instrumentation? Non-handled errors are going to be reported to the exception trackers and to the job runners. Are not those sufficient?

**Comment by pingortle** [comment]
> Thank you for the pull request. Can you explain why you need this instrumentation? Non-handled errors are going to be reported to the exception trackers and to the job runners. Are not those sufficient?

Hi @rafaelfranca, the purpose of this instrumentation is to augment normal exception tracking.

As you mentioned, we do have a system in place for monitoring exceptions in our background jobs. We also have a couple different data viz and monitoring services that we use to create custom dashboards and alerts more tailored to specific needs of a team or individual.

We are trying to leverage Active Job's built-in instrumentation as much as possible. Through this process we noticed that "unhandled errors" is one of the few hooks we've needed that isn't provided out of the box in Rails 6. We thought it would be a nice complement to the existing instrumentation hooks.

**Comment by rafaelfranca** [comment]
Can you rebase this PR?

**Comment by pingortle** [comment]
> Can you rebase this PR?

@rafaelfranca Done.

**Pull request closed without merging**
