### PR TITLE
Mailer preview request model

### PR DESCRIPTION
**Pull request by equivalent**
Alternative to my other PR https://github.com/rails/rails/pull/20608  (please have a look first)

passing request model instead of params

feature (in compare to my  other RP) gives developer the opportunity to extend `Rails::MailersController` and override the `request_model` => more protecting Preview class 

``` ruby
# config/initializer/mailer_preview.rb

# upon rails/mailers/my_mailer/good_news?user_id:123&client_id:345
module OverrideRequestModel
  def self.prepended(base)
     base.before_action :authenticate! 
  end

  def request_model
     OpenStruct.new(user: current_user, client_id: params[:client_id])
  end

  def current_user
    User.find session[:current_user_id]
  end

  def authenticate!
     raise "not authenticated" unless current_user.admin?
  end
end

Rails::MailersController.prepend OverrideRequestModel
```

This way In MyMailerPreview I can 

``` ruby
class MyMailerPreview < ActionMailer::Preview 

  def good_news
    do_some_stuff_with_user_object
    MyMailer.good_news(client)
  end

  private
     def do_some_stuff_with_user_object
        request_model.user.do_some_stuff
     end

     def client
        Client.find(request_model.client_id) 
     end
end
```

### CODE REVIEW

**Comment by equivalent** [comment]
re-triggering travis ci

**Comment by tom-lord** [comment]
+1

**Comment by zdfs** [comment]
+1

**Comment by equivalent** [comment]
PR 11 days ago, common anyone have any opinions on this ? negative/positive just no silence  :)

**Comment by jboonstra** [comment]
This would be handy for me when developing email with various iterations (as I'm doing right now). I believe the alternatives are to create a separate previewer method for each possible variant, or to continually tweak the parameters in the source code (and remember not to commit them).

**Comment by equivalent** [comment]
I've manage to create a mail preview for every individual user / status change / language with this (people in my company can edit mail content and the interpolation and after that they want to review before they are sent)

I definitely see why original developer didn't introduced this from beginning (trust your app code and tests + this suppose to be just for development purpose)  but by allowing passing params or request model you can use this to do lot of cool production stuff too.

**Comment by hungryzi** [comment]
+1

**Comment by pixeltrix** [comment]
@equivalent you shouldn't use this in production - that's not intended use case for this feature. You can call your mailers without a `deliver-*` method to get a mail object and process it however you need it to be done.

I'm still not convinced by this or #20608 - are there enough variants of emails to warrant this? You can just create multiple preview methods if you need to show different variants and this is more discoverable than manually tweaking params.

Can anyone suggest a use case that's a little more detailed?

**Comment by equivalent** [comment]
> ... you shouldn't use this in production ...

yep you shouldn't. The way how the original intention was proposed, this was just development tool. Yet you pass authentication object(Pundit) and params to it and "Yes we can" :) . I'm planing to write an article on full explanation how this is possible as son as this is actually merged. If you want I can write a scrap article in next few days and you will see that it's no security problem at all

I'm not trying to make this a built in "Rails production ready" solution for everyone. Just enabling more flexibility for those who know what they are doing. 

> I'm still not convinced by this or #20608 - are there enough variants of emails to warrant this?

we have 6 clients, each has 12 tempates and some have multiple languages (betwen 1 - 3 languages) so around 50 combination ?. I'm working on another code change that will add  6 more templates so 25 more combinations. The problem is that we do content interpolation (like you have "20 days left, or logo url) 

Paranoid content managers gave me a task that they want  to see every possible email (even if theoretically it's the same thing) . 

I see your point of scepticism on whether this feature is needed, but in cases where you have dynamic emails templates and you need support all possible previews, they are just way too much work for developer to generate every preview on every content change.

**Comment by equivalent** [comment]
look the main  point is that originally previews allows to do previews only  on specific object you pass **in  the code** and it's awesome feature.

But if you want to construct the object with controller params there is no way to do that. Please ignore the production bit I was talking about, I actually read people complaining they wanted to do this kind of stuff in development and they couldn't.

**Comment by equivalent** [comment]
I'm sorry everyone I've manage to screw up this PR when re-basing latest branch Upstream :( 

here is the new PR https://github.com/rails/rails/pull/21702

**Comment by equivalent** [comment]
meanwhile I've created patch-gem that is achieving this functionality if anyone is interested https://github.com/equivalent/mailer_preview_request_model   (I'm using it in one application)

**Pull request closed without merging**
