### PR TITLE
Fix reversed exp/act args for assert_equal

### PR DESCRIPTION
**Pull request by shouichi**

### CODE REVIEW

**Comment by matthewd** [comment]
Should we enable https://www.rubydoc.info/gems/rubocop-minitest/RuboCop/Cop/Minitest/LiteralAsActualArgument ?

**Comment by shouichi** [comment]
Cool, I didn't know that. I'm going to open a PR to enable the rubocop rule. Thank you!

**Comment by shouichi** [comment]
Opened https://github.com/rails/rails/pull/49236.

**Comment by rafaelfranca** [comment]
Closing in favor of https://github.com/rails/rails/pull/49236

**Pull request closed without merging**
