### PR TITLE
Add support for busting cache fragments containing asset URLs

### PR DESCRIPTION
**Pull request by mgwidmann**
An example cache block with an asset URL string included within:

```
<% cache :my_key do %>
  <%= link_to image_path('my_image.png') %>
<% end %>
```

We have had a problem where we did `bundle update sprockets` and when we deployed all our images which were contained within `cache` blocks responded with 404. The only solution at this point is to manually flush the `Rails.cache` or wait until the cache expires.

This PR adds support for doing the following instead:

```
<% cache :my_key, assets: true do %>
  <%= link_to image_path('my_image.png') %>
<% end %>
```

This will modify the cache key to add in `Rails.application.assets.version` (not to be confused with `Rails.application.config.assets.version`) so that the cache gets properly busted when either `Rails.env` (however unlikely), `Rails.application.config.assets.version`, or `Sprockets::VERSION` change.

This puts the ownership of busting the cache on the developer to know when to add `assets: true` and when to bump `Rails.application.config.assets.version` in order to both regenerate a new thumbprint as well as bust the caches which contain assets.

### CODE REVIEW

**Comment by bernabas** [comment]
:+1:

**Comment by americos** [comment]
+1

**Comment by richessler** [comment]
:+1:

**Comment by prosanelli** [comment]
:+1:

**Comment by rafaelfranca** [comment]
I think this solution will not work. Rails application.assets is not
present at production environment when you disable the assets compilation
(that is the default)

**Comment by mgwidmann** [comment]
@rafaelfranca would it work to replace it with the equivalent `"#{Rails.env}-#{Rails.application.config.assets.version}-#{Sprockets::VERSION}"` even though I don't like the idea...

**Comment by mgwidmann** [comment]
Ah I see, if I use `--skip-sprockets` to generate a new app and `RAILS_ENV=production rails c` it is nil like you say.

Previously before I submitted this I had something like this instead:

```
asset_version = Rails.application.assets.try(:version) || "#{Rails.env}-#{Rails.application.config.assets.version}"
```

**Comment by mgwidmann** [comment]
rebased and pushed...

**Comment by jeremy** [comment]
This would blow fragment caches every time your assets change – no good. Even if it's opt-in config.

It'd be great if we could track asset digests as part of template digesting. It'd only work for static references like `image_path 'foo'` where we could look up the digest for that logical path.

Also, we're missing a simple way to add your own cross-cutting keys to all frag cache keys. Then Rails could, by default, include things like Sprockets version, and you could add your own sub-keys.

Here's a workaround path to doing that today. In your controller, inject a global template dependency:
```ruby
# Tell the template digestor that this template is a global dependency.
# When it changes, all template digests change, and hence all fragment cache keys change.
view_cache_dependency { 'shared/cache_dependencies' }
```
And in `app/views/shared/cache_dependencies.text.erb`:
```text
Global fragment cache dependencies
WARNING: Changing this file in any way will expire all fragment caches!

Assets version: v1
Sprockets version: 4.0
…
```
Then all your template digests, and hence your frag cache keys, will change when this one template changes.

**Comment by mgwidmann** [comment]
@jeremy It wouldn't blow all fragments, only the ones marked with `assets: true`, which is the desired behavior since they *should* contain asset URLs within them. Cache blocks without `asset: true` would not contain the appended key and so therefore would remain cached. I don't see the harm in that since the thumbprints will have changed so you would want the cache to stay sync'd with it.

**Comment by jeremy** [comment]
@mgwidmann Right, but ultimately that's the majority of your fragment caches. You lose any granularity.

Plus, marking specific caches with a special flag means you'll end up missing caches with asset urls within them, e.g. from a helper method you didn't notice.

We have two routes here. We can take either or both, depending on the root problem you're solving:
1. Track asset references in template and include the assets' digests in the template digest. Updating an asset will update the digest of any template that directly references it and hence expire its frag caches.
2. Inject global cache keys so we can declare global expiry rules, like Sprockets upgrades, and bake some sensible defaults in to sprockets-rails.

I think 2. is the appropriate solution for the problem you encountered: needing to expire fragment caches globally due to a Sprockets version change.

**Comment by mgwidmann** [comment]
Just wanted to point out that it may or may not be a majority of the fragment caches depending upon your application since CSS images are unaffected by this. Since JavaScript and CSS would likely be in the head (and likely uncached) we are mostly talking about image tags which are use less and less frequently every day in favor of CSS. Icons for example would not be affected by this.

Just expiring caches when sprockets changes won't fully solve the problem. If `config.assets.version` is bumped, I need a way to target and expire my fragments which use assets (such as shown in the example) in an atomic manner so that no user receives a 404 image.

The only case where this approach is heavy handed is when for example I modified **one** image asset which the URL is included in **one** fragment. Ideally, we'd like to expire just that fragment. Perhaps rather than accepting just a boolean, `true` or a list of asset names could be supplied to the option to add in the thumbprint of that asset to the key, expiring just the caches that need to be expired.

**Comment by mgwidmann** [comment]
@jeremy If you want to do number 2, could you point me at a few places where you think you'd start? This is a bit larger of a change than I was anticipating...

**Pull request closed without merging**
