### PR TITLE
Fix connection left open after Application.initialize!

### PR DESCRIPTION
**Pull request by jkuchta**
This addresses the issue I found (https://github.com/rails/rails/issues/18953)

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Rails 3 is not supported anymore. If you find this same problem with Rails 4.1+ please open a PR against the master branch.

**Comment by jkuchta** [comment]
I know rails 3 is no longer supported, but I thought 3-2-stable still received severe bug fixes. Is a connection connection leak too minor of an issue?

**Comment by rafaelfranca** [comment]
Only severe security fixes. This issue is not security related as I see.

**Comment by jkuchta** [comment]
Yes, probably not directly related. Maybe in an obscure or application layer attack but probably not severe for security.

**Pull request closed without merging**
