### PR TITLE
Make Yarn the default, drop default vendor/asset directories

### PR DESCRIPTION
**Pull request by dhh**
Yarn is good. Yarn works.

### CODE REVIEW

**Comment by airhorns** [comment]
FWIW we had some issues with yarn at Shopify where they shipped a few fully broken releases and rolled back production versions in the last couple weeks. We had to pin the version at 0.16 and are carefully testing the newest one to make sure it doesn't break on us before rolling it out to all developers. 0.17 perhaps was just an anomaly, but it might make sense to wait a month or two to let it stabilize a bit before endorsing it for the whole Rails community. 

Waiting two more months will _double_ the time it's been in the wild and it doesn't seem like there is much urgency.

**Comment by guilleiguaran** [comment]
@airhorns I think we will have plenty time to test this between now and the first betas of Rails 5.1, I don't think we have a ETA for 5.1 beta now but I'm pretty sure it won't be released in the next 3 o 4 months.

**Comment by chirag7jain** [comment]
if configuration bit could be in rails app config itself and assets precompile could indirectly run yarn that would be great

**Comment by bogdan** [comment]
Why is it `./vendor/package.json` but not `./package.json`? It looks like the thing of the same kind as `Gemfile` and should probably be placed at root too.

**Comment by nateberkopec** [comment]
@bogdan That was hashed out on a separate issue/thread. @dhh mentioned he thought Gemfile could eventually be moved to /vendor as well.

**Comment by rafaelfranca** [comment]
👏

**Pull request merged**
