### PR TITLE
[ci skip] change sentence about reporting bugs in contributing guide

### PR DESCRIPTION
**Pull request by mcfiredrill**
I think I know what this sentence is trying to say, but the sentence
didn't really make sense, bugs don't fix things! How about this take on
it? :sweat_smile:

### CODE REVIEW

**Comment by jvanbaarsen** [comment]
😆I think your new line is way better! :+1:

**Comment by fxn** [comment]
Good catch!

The reword still doesn't quite click to me, because a "behaviour" does not "behave" itself. Indeed the existing behaviour is the bug, not caused by it.

Almost there, but let's refine!

**Comment by mcfiredrill** [comment]
@fxn I agree, saying that a "behaviour" "behaves" is a bit redundant and kind of awkward. 

How about if I change the verb "behave" to "work"?  I pushed a commit with the change.

Or maybe "function" instead of "works"?

Or maybe even "malfunction" ? :sweat:

**Comment by fxn** [comment]
The key, I believe, is that the behaviour *is* incorrect.

**Comment by mcfiredrill** [comment]
Ah, I got it now:

```
Generally, a feature is anything that adds new behavior, while a bug is anything that causes incorrect behavior.
```

**Comment by fxn** [comment]
There :). Thanks!!!

**Pull request merged**
