### PR TITLE
Add .gitignore to "files & purpose" list - getting started docs

### PR DESCRIPTION
**Pull request by kjellberg**
### Summary

The .gitignore-file is also created by default :)

### CODE REVIEW

**Comment by maclover7** [comment]
@kjellberg Thanks for the PR! Can you just squash down your commits to one, and then we should be good to merge.

**Comment by kjellberg** [comment]
Cool, done @maclover7 ! 
Thanks :) 👍

**Comment by maclover7** [comment]
Thanks for updating! Missed in my first comment, would you be able to change the `https://help.github.com/articles/ignoring-files` link to proper Markdown syntax (`[text](url)`). After that, _then_ we should be good to go. :)

**Comment by maclover7** [comment]
:+1: Thank you for updating (again)!

:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Pull request merged**
