### PR TITLE
Cache file read for `config_for` method.

### PR DESCRIPTION
**Pull request by morgoth**
When `Rails.application.config_for(:my_config)` called multiple times, now it only reads the file from disk once.

I didn't want to cache ERB evaluation and YAML loading in case someone would use some dynamic value there. Not really a common scenario, but it would break it.

/cc @rosa @mberlanda as you're working closely on https://github.com/rails/rails/pull/33882

### CODE REVIEW

**Comment by mberlanda** [comment]
hey @morgoth I just rebased #33882 on master and squashed the commits. Don't know yet when it will be reviewed but this looks like a nice finding

**Review by albertoalmagro — COMMENTED** [review]
Nice @morgoth , would you add a test to actually check if it is cached?

**Comment by morgoth** [comment]
@albertoalmagro Do you have an idea how such test could look like? One idea would be to read value, change file and check if the value is the same, but that would be actually testing side effect so I would say it's not a good way.

**Comment by albertoalmagro** [comment]
@morgoth I meant something like expecting not to receive `yaml.read` twice. Let me check it after work.

**Comment by rafaelfranca** [comment]
I considered this cache when I first implemented this method and I decided to not go for it since this method is not supposed to be called more than once with the same argument. This method is to load configs from a file and store inside Rails configuration object. You only do that once at load time so I prefer to not complicate the implementation by adding memoization.

Thank you for the pull request.

**Comment by morgoth** [comment]
@rafaelfranca There are many cases where it could be run multiple times. Very often configuration looks like:
```ruby
SomeService.configure do |config|
  config.username = Rails.application.config_for(:some_service).username
  config.secret_key = Rails.application.config_for(:some_service).secret_key
end
```
Sure you can memoize it in local variable (or constant) before, but one would have to know that there is a penalty hidden by not writing it this way.
Also such services are not always configured only once on a load time. I think it can be very specific to app use cases.

I thought that having multi env credentials altogether with config_for could be a fine combo to replace deprecated approach with secrets, by having unified API for configuring different envs and I was missing this one small thing ;-)

**Comment by kaspth** [comment]
> Sure you can memoize it in local variable (or constant) before, but one would have to know that there is a penalty hidden by not writing it this way.

So it gets hit twice in an initializer that's only run on load. Doesn't seem like a big deal to me.

> Also such services are not always configured only once on a load time.

If it is indeed so common that we should add this, where are the examples of such services?

> I think it can be very specific to app use cases.

Lots of things are specific to potential app use cases, and we can certainly dream up all kinds all day long, but that's not how Rails gets meaningful contributions. We need actual cases that you've actually experienced.

**Comment by morgoth** [comment]
Maybe I expressed it in a little wrong way - not the services itself but how they are used.
Let's have an example of sending notifications through AWS:
```ruby
client = Aws::SNS::Client.new(region: region) # Where region can by dynamic like "eu-west-1"
arn = Rails.application.config_for(:aws)["sns_#{platform}_arn"] # Where platform can be android, ios, etc.
client.create_platform_endpoint(platform_application_arn: arn, token: token)
```
So in such examples, `config_for` is not only called on boot time (in initializer) but in runtime.
I could memoize this config in some top level constant (to not read file from disk on every call), but then it looses the nicety of its usage

**Comment by morgoth** [comment]
It looks nice, I agree and there are definitely lot of ways to workaround it. 
The only thing is that one have to be aware about it and avoid writing straightforward inline code (like it used to be with `Rails.application.secrets` and even with `Rails.application.credentials`).

Thanks for your time

**Pull request closed without merging**
