### PR TITLE
Use Puma 5.2

### PR DESCRIPTION
**Pull request by robertomiranda**
### Summary

Puma 5.3.2 was released recently https://github.com/puma/puma/releases/tag/v5.3.2

### CODE REVIEW

**Comment by eugeneius** [comment]
We don't need to make this change to support the latest version, and Rails still works fine with Puma 5.0.

**Comment by p8** [comment]
@eugeneius 5.3.1 is a security release, so I think that should be the minimum.
https://github.com/puma/puma/blob/master/History.md#531--2021-05-11

**Comment by zzak** [comment]
What are the risks if we do force an upgrade for Rails? I can see the risk of a new rails app being vulnerable to that security bug if we don't do this however.

**Comment by robertomiranda** [comment]
> What are the risks if we do force an upgrade for Rails? I can see the risk of a new rails app being vulnerable to that security bug if we don't do this however.

@zzak @eugeneius It's interesting as well that actionpack tests has failed https://buildkite.com/rails/rails/builds/77962#e16553c6-0d83-4e85-a40b-e06ba6f658b9, IMHO, rails should be up to date with the rack web server which recommends using

**Comment by p8** [comment]
@robertomiranda Strange that the tests fails with an upgrade of puma, and only on Ruby 3.0.

**Comment by zzak** [comment]
My guess is this test is just flakey, but I don't have a good reason other than "its parallel" 🤷

**Comment by eugeneius** [comment]
Whether Rails should bump its dependencies for security releases has been litigated previously:

https://github.com/rails/rails/pull/30905#issuecomment-337092330

> Users' Gemfiles are the appropriate place for version upgrades, dependency locking, and security auditing.

https://github.com/rails/rails/pull/27814#issuecomment-275722286

> This is a concern of the application. Rails should not bump their dependencies when security releases are made.

Arguably this is a slightly different case, since it concerns the generated application Gemfile rather than Rails' gemspecs, but IMO the principle still applies: Rails declares the dependencies with which it is compatible, and it's then the user's responsibility to bump those dependencies in response to security releases (just like they have to do for all of their other dependencies).

---

That test has been flaky for a long time; I investigated it before but couldn't find a satisfactory way to fix it. From memory, I think it happens when `permitted` has the same `hash` value both before and after it's mutated here:

https://github.com/rails/rails/blob/5c09cfd96fadd6080dd2e57ee761f2ccfdbc7d42/actionpack/test/controller/parameters/parameters_permit_test.rb#L252

**Comment by robertomiranda** [comment]
thanks all for your feedback 🙇 👍

**Pull request closed without merging**
