### PR TITLE
Followup of changes done to `error_on_ignored_order`

### PR DESCRIPTION
**Pull request by prathamesh-sonpatki**
r? @fxn

### CODE REVIEW

**Comment by fxn** [comment]
Thanks!

**Comment by fxn** [comment]
The module accessor was left on purpose, it is in a border line as public interface and client code could be reading the attribute.

The config guide does need the edit.

**Comment by fxn** [comment]
Could you please implement reader code with deprecations? To be honest I don't know if it is worthwhile, but given the choice I prefer to err on keeping compatibility with a deprecation cycle.

**Comment by prathamesh-sonpatki** [comment]
@fxn Done!

**Comment by fxn** [comment]
Thanks!

**Pull request merged**
