### PR TITLE
 [ci skip] Document render options

### LINKED ISSUE #28484: Improve API documentation to include more details about `render`
I'd like to see more details about `render` on the API documentation. For example: what are the available options that can be passed? IMO, the current copy is lacking:

c7hwg9sxwaccnbk

I'll try to write something up if I find the time this week.

### PR DESCRIPTION
**Pull request by al3rez**
Fixes #28484 - Complete renderer documentation

### CODE REVIEW

**Comment by azbshiri** [comment]
@schneems

**Comment by schneems** [comment]
Thanks for the docs!

**Comment by bogdanvlviv** [comment]
Since this PR is merged - https://github.com/rails/rails/pull/28784, and https://github.com/rails/rails/pull/30745 can be closed.

**Comment by ttanimichi** [comment]
@schneems Is this doc on the correct place? It seems that @rafaelfranca said it should be `ActionController::Rendering#render`. https://github.com/rails/rails/pull/28784#discussion_r112267599

**Pull request merged**
