### PR TITLE
Add notable changes to railities [ci skip]

### PR DESCRIPTION
**Pull request by apoorv1316**
### Detail

This Pull Request adds few missing notable changes to railities

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by p8** [comment]
Thanks @apoorv1316  These are all documented in the [7.2 release notes](https://github.com/rails/rails/blob/7-2-stable/railties/CHANGELOG.md).
So I think this is good to go.

**Review by akhilgkrishnan — COMMENTED** [review]
@apoorv1316  The changes are LGTM, can you [squash your commits](https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#squashing-commits).

**Comment by apoorv1316** [comment]
@p8 Some of the changes are missing in release notes that are part of release notes. I think they can go in "Notable changes".

**Comment by rafaelfranca** [comment]
The notable changes don't need to match the entire changelog. I left those by design, I don't think they are notable changes.

**Pull request closed without merging**
