### PR TITLE
Add migration generator for drop table action

### PR DESCRIPTION
**Pull request by knagode**
### Motivation / Background

Prior this change `rails generate migration drop_users` generated migration file with empty `def change` body. [A lot of users are surprised](https://stackoverflow.com/questions/4020131/rails-db-migration-how-to-drop-a-table) about this not yet being implemented. 

```
class DropUsers< ActiveRecord::Migration[7.0]
  def change
  end
end
```

### Details

This PR improve codebase in order to generate proper drop migration:
```
class DropUsers< ActiveRecord::Migration[7.0]
  def change
     drop_table :users
  end
end
```

Note: Implementation does not contain tests because there is no base code for migration generators yet - it would require quite some efforts to add this. If someone knows how test for such a thing should be written, please give me some hints.

### Checklist
 Before submitting the PR make sure the following are checked:
 
 * [x]  This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
 * [x]  Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
 * [ ]  Tests are added or updated if you fix a bug or add a feature.
 * [ ]  CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by yahonda** [comment]
Thank you for opening this pull request.

Could you provide some use cases why `drop_table` needs to have its own template? As far as I understand, users create tables using the `create_table` method and if they need to drop_tables, they can rollback the migration. Also, dropping tables should not happen as often as creating tables.

**Comment by knagode** [comment]
@yahonda Thank you for the review. 

One of the main benefits of having schema.rb is the ability to delete old migrations one day. If team consist of hundreds of developers it is hard to ask all of them to roll back specific migration. Drop migration is useful and [>500 people on stackoverflow](https://stackoverflow.com/questions/4020131/rails-db-migration-how-to-drop-a-table) are "officially" wondering why such migration can not be generated automatically by Rails. 

I created separate template because I wanted to follow the same pattern as migration for `create table`. I didn't want to add more clutter into migration.rb.tt (we could move logic from create_table_migration.rb.tt there too, however it feels like code is easier to maintain & understant if we keep different actions separately. I wanted to continue this practice and lean toward [Single-responsibility principle](https://en.wikipedia.org/wiki/Single-responsibility_principle)). 

I also think that someone could extend this PR in order to create reversible migration (this is possible but requires more code/work).

**Comment by yahonda** [comment]
Thanks for the update. Would you add a changelog entry for this change?

**Comment by knagode** [comment]
@yahonda done

**Comment by matthewd** [comment]
I'm not a fan of trivial migration generators, because of exactly the confusion linked upthread: the correct way to create migrations is to write them, as code, in the file. We provide some generators for convenience, but it seems like the more we accomodate the feeling that every possible migration _should_ have a secret you-just-have-to-guess-it name pattern that will write out the line of code for you, the worse that perception becomes.

This part does seem interesting to me, though: 
> I also think that someone could extend this PR in order to create reversible migration (this is possible but requires more code/work).

IMO that would present a much more compelling argument for why it's helpful to have a generator here.

**Comment by knagode** [comment]
@matthewd if we want to have something complex, we should start with something simple. Something simple will probably solve 90% of use cases and that is why I created this PR. We are not talking about anything special. I just wanted that basic table operations are somehow supported as many people are surprised that simplest table operations are not supported out of the box. 

I also think it is dangerous to put more magic into this generator as it is possible that migration can interfere with each other: 

[Teemu Leisti](https://stackoverflow.com/questions/4020131/rails-db-migration-how-to-drop-a-table) had good comments regarding down migration: 

> Sure, writing the up part is simple -- just call drop_table -- but the down part, generating the table again, might not always be so simple, especially if the schema of the table in question has been changed by migrations after its initial creation. Maybe someone should suggest to the developers of Rails that adding such an option would be a good idea. –

**Comment by rafaelfranca** [comment]
Implementing a generator for drop that would be useful (meaning support to revert the migration) would require that the generators know about the current schema of the database, which isn't a complexity that I'm willing to maintain in the framework.

As it is, this generator isn't doing much, in fact is generating a irreversible migration that will do more harm than good, and since generating a reversible would require complexity in the framework that we are not willing to maintain, I don't think it makes sense to introduce this feature.

Thank you for the pull request.

**Pull request closed without merging**
