### PR TITLE
Overriding find_by_* methods causes error

### LINKED ISSUE #15288: Overriding find_by_* methods causes error
I'm currently working on upgrading an app from 3.2.18 to 4.0.4 (and eventually 4.1.X).  We ran across an interesting bug, but I'm not sure if it is a bug, or simply something to be aware of when upgrading.

Background:
We have an AR model that has a column named mac_address.  We have created a class method that normalizes the data before searching for the record.

``` ruby
class Device
  def self.find_by_mac_address(address)
    super(MacAddress.new(address).normalized)
  end
end
```

The `MacAddress.normalized` method simply converts the address to a standard format:

```
MacAddress.new('ABCDEF').normalized     # => abcdef
MacAddress.new('AB:CD:EF').normalized   # => abcdef
MacAddress.new('ab cd ef').normalized   # => abcdef
```

Issue:
In Rails 3.2.18, this worked fine (same command ran twice):

```
Device.find_by_mac_address('ab cd ef')  # Finds the device with address abcdef
Device.find_by_mac_address('ab cd ef')  # Finds the device with address abcdef
```

In Rails 4.0.4, this breaks:

```
Device.find_by_mac_address('ab cd ef')  # Finds the device with address abcdef
Device.find_by_mac_address('ab cd ef')  # nil (it no longer normalizes the address)
```

It appears the problem is with `activerecord/lib/active_record/dynamic_matchers.rb` line 63.  This code is called by the `method_missing` logic in this file.  

I'm guessing the issue is that lines 63-69 defines the "missing" method on the class it was called on.  i.e. our `Device#find_by_mac_address` method is over written once we call `super`.

Further debugging (suggested offline by @cschneid):

``` ruby
>> m1 = Device.method(:find_by_mac_address)
>> Device.find_by_mac_address("ab cd ef")
>> m2 = Device.method(:find_by_mac_address)
>> Device.find_by_mac_address("ab cd ef")
>> puts m1.source_location
app/models/device.rb
1121
=> nil
>> puts m2.source_location
/usr/local/rvm/gems/ruby-2.1.2@rails4.0/gems/activerecord-4.0.4/lib/active_record/dynamic_matchers.rb
65
=> nil
>>
```

Workaround (suggested by @diminish7):

For anyone who runs into this issue, we're currently using a workaround:

``` ruby
def self.find_by_mac_address(address)
    where(mac_address: MacAddress.new(address).normalized).first
end
```

So our question is, is this expected behavior?  Is there a better way to do what we're trying to do?

### PR DESCRIPTION
**Pull request by vp993**
Hi! I fixed #15288 issue. I didn't found test model for this case, because I create it myself. Please, review my code.

### CODE REVIEW

**Comment by JonRowe** [comment]
Is this still an issue on 4.2? Looks like it could use a rebase :)

**Comment by Snuff** [comment]
@JonRowe done!

**Comment by robertjlooby** [comment]
It's worth noting that because you send the `find_by_*` back to the model to be delegated after you define the anonymous module, the model's finder will be executed twice the first time it is called which could have unintended side effects

**Comment by eileencodes** [comment]
Is it possible to do this without adding a new model to the tests? I think this override of `find_by_` could be used in most of the other models instead. There are already so many models, we try to only add new ones when absolutely necessary. What do you think @Snuff? 

Otherwise I think this is looking good, thanks for working on this :smile:

**Comment by kaspth** [comment]
Unfortunately, it's been way too long for a reviewed fix to make it in. At this point you'd have to update all the way to Rails 5.2 to even get the fix. That coupled with the fact that we'd likely to deprecate this anyway means we're closing the issue. I'm sorry about that, and I hope this doesn't discourage you from contributing again! Ref: https://github.com/rails/rails/pull/32999#issuecomment-406707716

**Pull request closed without merging**
