### PR TITLE
Use delete_if instead of each; delete(key)

### PR DESCRIPTION
**Pull request by rodzyn**
Inspired by 22f592401444a83b7b2d3c2165ac666d69955d08 (@schneems)

### CODE REVIEW

**Comment by schneems** [comment]
Did you benchmark this?

When I run my app i'm getting these values for those two variables:

```
inner_options = {}
path_params   = [:full_name]
```

Which means that the `each` never even gets called. Take a look:

```ruby
inner_options = {}
path_params   = [:full_name]

require 'benchmark/ips'

Benchmark.ips do |x|
  x.report("each; delete") {
    inner = inner_options.dup
    path  = path_params.dup
    inner.each do |key, _|
      path.delete(key)
    end
  }
  x.report("delete_if") {
    inner = inner_options.dup
    path  = path_params.dup
    path.delete_if do |key, _|
      inner.include?(key)
    end
  }
end
```

So the `delete_if` method way is actually slower:

```
Calculating -------------------------------------
        each; delete    81.307k i/100ms
           delete_if    74.648k i/100ms
-------------------------------------------------
        each; delete      1.877M (± 7.4%) i/s -      9.350M
           delete_if      1.502M (± 7.0%) i/s -      7.539M
```

I believe this is a pretty common case where `inner_options` is an empty hash. So while `delete_if` might generally be faster, in this specific case it would be slower.

**Comment by rodzyn** [comment]
@schneems It seems I didn't anticipat that `inner_options` might be usually empty, thanks for a quick feedback - fair enough :)

**Comment by schneems** [comment]
No worries, I really appreciate this PR. Since I made that large change we've had a few performance patches come up that all add up. If it wasn't for people like you looking for missed opportunities, we wouldn't ever get faster. My big lesson learned from performance work, is to always set up a benchmark. Try to get a real world example app and get data from that so your benchmark is kinda representative of the real world. There were a few patches I originally had in my PR that reduced object allocation but actually increased runtime. Basically not everything I touch "just works" the first time and I had to delete several of my "performance optimizations" when they turned out to not help. It's normal and part of the process.

So, I hope you're not discouraged, but rather I hope you can find some more patches and play around with some benchmark methods. Thanks again for your contribution.

**Comment by rodzyn** [comment]
@schneems I really appreciate your feedback, thanks a lot for this detailed explanation, encouragement and useful tips about the process. I'm gonna keep looking for sure.

**Pull request closed without merging**
