### PR TITLE
Add support for que name to Que adapter.

### LINKED ISSUE #266: Named queues don't work in ActiveJob
I'm trying to integrate Que with Rails' ActiveJob, and it seems to be working fine with the exception of the queue name. I found on [this comment](https://github.com/que-rb/que/issues/179#issuecomment-284004802) that named queue support was removed from ActiveJob. My infrastructure has workers listening on different queues, and I use the queue name to determine which workers will process the job. The lack of support for named queues in ActiveJob is critically important to me, so I cannot use the ActiveJob integration.

Are there any plans to support named queues in ActiveJob?

### PR DESCRIPTION
**Pull request by morgoth**
This rebases and fixes https://github.com/rails/rails/pull/32157 (should preserve original author as co-author)
Also resolves https://github.com/que-rb/que/issues/266

/cc @eileencodes as you asked for rebase some time ago

### CODE REVIEW

**Comment by eileencodes** [comment]
Can you fix the Rubocop build?

```
activejob/test/support/integration/adapters/que.rb:28:23: C: Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
        Que::Job.work('integration_tests')
                      ^^^^^^^^^^^^^^^^^^^
```

**Comment by morgoth** [comment]
@eileencodes Rubocop is fixed. The test failures look like unrelated to this changes

**Comment by eileencodes** [comment]
Thanks @morgoth!

**Comment by morgoth** [comment]
Thanks. Can we have a backport to 6-0-stable please?

**Comment by eileencodes** [comment]
Done!

**Pull request merged**
