### PR TITLE
Add support for Minitest 5.11

### PR DESCRIPTION
**Pull request by y-yagi**

### CODE REVIEW

**Comment by zenspider** [comment]
Also see my proposed changes in https://github.com/seattlerb/minitest/issues/730

**Review by rafaelfranca — APPROVED** [review]

**Review by kaspth — APPROVED** [review]

**Comment by zenspider** [comment]
Bump. I'd like to see this merged so I don't have to add a nasty monkeypatch on `method` to minitest.

**Comment by jm3** [comment]
Any ETA for a new minor Rails release including this fix for the Minitest exception-on-failing-test? Currently it seems like everyone running current Rails is going to encounter this crash, right?, especially if they keep their gems current, as I know many do.

I understand that I could switch to running Edge Rails to get the fix, but that opens up a whole can of worms that I'd prefer to avoid :) Looks like the last release was a month ago. Consider this an encouragement bump and a raised hand to help test, if that's useful.

**Comment by rafaelfranca** [comment]
You can point to the 5-1-stable branch and get this commit without going to edge.

**Comment by jm3** [comment]
Ah, great idea — thanks, done!

**Comment by rhuanbarreto** [comment]
Please add this fix to Rails 5.0 also.

**Pull request merged**
