### PR TITLE
Respond to PUT/PATCH API request with :ok

### PR DESCRIPTION
**Pull request by claudiob**
This commits changes the behavior of `respond_to` for successful PUT/PATCH
requests on format associated with APIs, such as :xml and :json.

Previously, `respond_to` would just return :no_content (204) and no body.
After this commit, it returns :ok (200) and the entire updated object as
the response body.

The rationale behind this commit is that a PUT, POST or PATCH call may make
modifications to fields of the underlying resource that weren't part of the
provided parameters (for example: created_at or updated_at timestamps).

This commit prevents an API consumer from having to hit the API again for an
updated representation. Rails already provides the created representation after
a POST, so it is coherent to have the same behavior on PUT and PATCH.

See discussion at https://github.com/rails/rails/issues/12096

### CODE REVIEW

**Comment by mecampbellsoup** [comment]
Could someone (@dhh ?) elaborate on *why* using class-level `respond_to` is a bad practice? You mentioned API hiding but I'm still a bit unclear...

**Comment by jhubert** [comment]
@dhh I'm in the same boat as @mecampbellsoup. Can you clarify what bad vs good behavior looks like in regards to respond_with / respond_to?

**Comment by plicjo** [comment]
@mecampbellsoup @jhubert Looking at the controller doesn't tell you whether you are returning HTML, XML, JS, or JSON. You'd have to go to the view layer and see what format the controller is responding with.

If I see `respond_with @models`, I have no idea what format the controller is responding with.

If I see:

```
respond_to do |format|
  format.xml { render xml: @model }
  format.json { render json: @model }
end
```
then I am immediately aware of what format the response will be in.

**Comment by novohispano** [comment]
@plicjo I believe that you can see the format that the controller is responding with if you look at the class level `respond_to`.

I think the complexity arises when mixing machine-readable controllers (JSON, XML) with human-readable controllers (HTML), by using single-responsibility controllers, this can be avoided, IMO.

**Comment by hron84** [comment]
@plicjo This response is not exactly correct.

If I see:

```ruby
class FooController < ApplicationController
  respond_to :json, :html

  def show
    @foo = Foo.find params[:id]
    respond_with(@foo)
  end
end
```

Then I have to scroll only to the top of the controller to check what responses are available in the controller. However

```ruby
  def index
    @foos = Foo.all
    respond_to do |format|
      format.html
      format.json { render json: @foos }
   end
  end

  def show
    @foo = Foo.find params[:id]
    respond_to do |format|
      format.html
      format.json { render json: @foo }
   end
  end
```

is nothing just a spaghetti, copy-paste code with potential traps. This is what I call unreadable and try to avoid it anyway.

**Comment by sharvy** [comment]
I see most of the people didn't even understand @plicjo 's comment!

From seeing the below contoller:
```
class FooController < ApplicationController
  respond_to :json, :html
  ...
  def show
    @foo = Foo.find params[:id]
    respond_with(@foo)
  end
  ...
end
```
You can never tell the return type of `show` - whether that's returning `html`, `json`, or both.

IMO, If you have different kinds of actions (some responding with JSON, and some with HTML) in the same controller, better not to use the responder to avoid unnecessary confusion. If you have different sets of controllers for `html`, `json` or `xml`, I would recommend the responder.

**Pull request closed without merging**
