### PR TITLE
Use selected_migrations if block_given?

### PR DESCRIPTION
**Pull request by utilum**
This appears to have slipped in as part of a2827ec. The pope is infallible, why isn't @eileencodes ?

### CODE REVIEW

**Comment by eileencodes** [comment]
Hey can you update the commit message to remove my handle? Any time someone pushes this commit to their branch I'll get a notification 😄  Thanks for fixing this!

**Comment by kamipo** [comment]
Migration with block isn't tested?

**Comment by eileencodes** [comment]
It is tested here https://github.com/rails/rails/blob/master/railties/test/application/rake/migrations_test.rb#L17-L38

SCOPE sets it so that only bukkits migrations run. I think we don't see a failure because down is ignoring that users was never created

**Comment by eileencodes** [comment]
Ah I figured out how to test this. I cherry-picked this commit in to master and added a test in e0ad907ade3bca1c57a32c1987c4080305019845.

Thanks @utilum

**Comment by utilum** [comment]
Thank YOU. 
I amended the commit and pushed it to my branch. Doesn't look like it's changed anything here :(

**Pull request closed without merging**
