### PR TITLE
Fix assets precompile example [ci skip]

### PR DESCRIPTION
**Pull request by shartep**
Fix error in example of executing assets:precompile task

### CODE REVIEW

**Comment by matthewd** [comment]
Thanks, but it's correct as is.

**Comment by shartep** [comment]
Hello,

I'm sorry, maybe I'm wrong but here is the result of executing command from example:

```
ALexs-iMac:threatrate shartep$ RAILS_ENV=production bin/rails assets:precompile
Error: Command 'assets:precompile' not recognized
Did you mean: `$ rake assets:precompile` ?

Usage: rails COMMAND [ARGS]

The most common rails commands are:
 generate    Generate new code (short-cut alias: "g")
 console     Start the Rails console (short-cut alias: "c")
 server      Start the Rails server (short-cut alias: "s")
 dbconsole   Start a console for the database specified in config/database.yml
             (short-cut alias: "db")
 new         Create a new Rails application. "rails new my_app" creates a
             new application called MyApp in "./my_app"

In addition to those, there are:
 application  Generate the Rails application code
 destroy      Undo code generated with "generate" (short-cut alias: "d")
 plugin new   Generates skeleton for developing a Rails plugin
 runner       Run a piece of code in the application environment (short-cut alias: "r")

All commands can be run with -h (or --help) for more information.

```
Also the description is says:  "The task is:" and I do not here about Rails tasks, but know about Rake tasks ;)

In this case can you pls, explain why I'm wrong.

Thanks

**Comment by robin850** [comment]
@shartep : Are you using an older version that Ruby on Rails 5 ? The guides are released per version and are currently valid for Rails 5.1. You can find the asset pipeline guide for 4.2 [here](http://guides.rubyonrails.org/v4.2/asset_pipeline.html).

**Comment by shartep** [comment]
ok, I understand, sorry for wasting your time

**Comment by robin850** [comment]
Hey, no problem ! :-)

**Pull request closed without merging**
