### PR TITLE
add missing `as` to request kwargs of `ActionDispatch::IntegrationTest`

### PR DESCRIPTION
**Pull request by y-yagi**
Follow up to #21671

### CODE REVIEW

**Comment by kaspth** [comment]
Thanks! I take it this fixes deprecation warnings being printed for:

```ruby
get articles_url, as: :json
```

👍

**Comment by y-yagi** [comment]
Thanks!

**Comment by jeremy** [comment]
Needs backport to 5-0-stable

**Comment by kaspth** [comment]
@jeremy already done, but forgot the link. Here it is on 5-0-stable: https://github.com/rails/rails/commit/3e45dd988cad539fe2cbc79b505fde99a44472e8

**Pull request merged**
