### PR TITLE
Change AS::Testing::TimeHelpers#travel_to to also stub DateTime.now

### PR DESCRIPTION
**Pull request by yuki24**
I had a case where I wanted `travel_to` to stub `DateTime.now` as well as `Time.now` and `Date.today`.

### CODE REVIEW

**Comment by carlosantoniodasilva** [comment]
Can you add a changelog entry as well? Thanks.

**Comment by yuki24** [comment]
added a changelog entry. Thanks for your time @carlosantoniodasilva !

**Comment by tomasv** [comment]
@carlosantoniodasilva are there any plans on having this backported to Rails 4.2? It's keeping me from fully migrating from Timecop.

Thanks in advance, you're doing an amazing job! :+1:

**Comment by yuki24** [comment]
@tomasv you can use the module below for now.

```ruby
module TimeHelpers
  # We can remove this helper method when we upgrade Rails to 5.0.
  # also see: https://github.com/rails/rails/pull/18758
  def travel_to(time)
    # ActiveSupport::Testing::TimeHelpers only stubs Date and Time classes.
    # Also stub DateTime class so it behaves exactly like Timecop.
    # TODO: Remove this after Rails adds native support for studding DateTime.
    if time.is_a?(Date) && !time.is_a?(DateTime)
      simple_stubs.stub_object(DateTime, :now, time.midnight.to_datetime)
    else
      simple_stubs.stub_object(DateTime, :now, time.to_datetime)
    end

    super
  end

  def freeze(time = Time.now, &block)
    block_given? ? travel_to(time, &block) : travel_to(time)
  end
end
```

**Comment by concept47** [comment]
@yuki24 looking at [this commit](https://github.com/rails/rails/commit/a57ddc58ac4e7a8b058cdaa0179cd897c2960c83) whats the purpose of doing `simple_stubs.stub_object(DateTime, :now, time.midnight.to_datetime)`

**Pull request merged**
