### PR TITLE
Refactor active_support/core_ext/hash/keys.rb

### PR DESCRIPTION
**Pull request by meinac**

### CODE REVIEW

**Comment by carlosantoniodasilva** [comment]
I have to say I'm all in for `each_with_object`, but can you tell if we aren't introducing performance regressions with these changes? Key/value transformations (stringify/symbolize keys for example) are used everywhere inside Rails and in applications, so I'd prefer to avoid any regression. Can you provide a bench with before/after codes? Thanks for your work.

**Comment by meinac** [comment]
Good point @carlosantoniodasilva , here is the benchmark results(orig is the original implementation and new is the new one);
```
Calculating -------------------------------------
 transform_keys orig    86.227k i/100ms
  transform_keys new    86.279k i/100ms
-------------------------------------------------
 transform_keys orig      2.266M (± 5.6%) i/s -     11.296M
  transform_keys new      2.312M (± 6.1%) i/s -     11.475M

Comparison:
  transform_keys new:  2311773.1 i/s
 transform_keys orig:  2265769.0 i/s - 1.02x slower
```

```
Calculating -------------------------------------
transform_keys! orig    87.138k i/100ms
 transform_keys! new    86.571k i/100ms
-------------------------------------------------
transform_keys! orig      2.283M (± 5.5%) i/s -     11.415M
 transform_keys! new      2.315M (± 5.4%) i/s -     11.514M

Comparison:
 transform_keys! new:  2315292.7 i/s
transform_keys! orig:  2283033.2 i/s - 1.01x slower
```

**Comment by meinac** [comment]
@matthewd Please give a reason while closing pull requests otherwise we can't see what is wrong with the pr. 
Thanks.

**Comment by matthewd** [comment]
@meinac Please give a description when opening pull requests.
Thanks.

This increases allocations, for a trivial cosmetic improvement inside AS. That's not a trade-off we're interested in making.

**Pull request closed without merging**
