### PR TITLE
Restore ActiveJob serialization for String subclasses without custom serializers

### PR DESCRIPTION
**Pull request by octokatherine**
### Motivation / Background

This Pull Request has been created because https://github.com/rails/rails/pull/50090 broke serialization of String subclasses that don't have serializers, like ActiveSupport::SafeBuffer. 

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by jhawthorn** [comment]
cc @fatkodima @byroot 

This fixes serialization for String subclasses which don't have serializers. I think this will be pretty common for `SafeBuffer`, but likely also other strings we don't know about.

Possibly we could deprecate this and remove it in a future version, but we would have to do so very carefully. If we want to make a serializer for `SafeBuffer`, it needs to be enable-able by a flag just as we do for BigDecimal so that it can be deployed safely.

I'm also not fully convinced we should deprecate serializing string subclasses, we currently allow serializing Hash and Array subclasses, and it would probably be best to be consistent.

**Comment by byroot** [comment]
Works for me. As long as they are serialized as bare strings, I have no concerns.

**Comment by jarenas9539** [comment]
Can't previous if statement `argument.class == String` be removed as it's already scoped on the rescue clause? 🤔

**Comment by northeastprince** [comment]
@jhawthorn could this be backported?

**Comment by byroot** [comment]
The bug it is fixing wasn't present on 7.1 in the first place. Unless I'm missing something?

So no reason to backport it.

**Comment by northeastprince** [comment]
@byroot [`SafeBuffer`s aren't getting serialized in 7.1.2](https://github.com/sidekiq/sidekiq/issues/6122).

**Comment by byroot** [comment]
So it's https://github.com/rails/rails/pull/50090 you want backported?

**Comment by northeastprince** [comment]
Yeah

**Pull request merged**
