### PR TITLE
Allow custom schema dumpers

### PR DESCRIPTION
**Pull request by kddnewton**
Per this conversation: https://groups.google.com/forum/#!topic/rubyonrails-core/h6q8nGFzGKs, allows for setting a class that responds to #dump to allow for customizing the schema dump.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Could you tell when this is useful? That discussion talks only about a problem that can be solved in various way.

**Comment by kddeisz** [comment]
The usefulness is flexibility. I can't currently control what is dumped other than which tables. For instance right now all of our mysql views get dumped out as full tables, so we ended up patching and having to rebuild the views. It's also convenient to be able to put app-specific database configuration into the schema.rb file (for instance we have some mysql stored procedures). Since this kind of stuff shouldn't be resting in the SchemaDumper (don't want to pollute the rails core) I figured this would be a way to say - if you want it write your own dumper.

**Comment by rafaelfranca** [comment]
But why you would use the schema dump if you are needing to dump views and stored procedures? For this case the recommended format is the structure dump.

**Comment by kddeisz** [comment]
Because it's faster the use the schema dump and it allows you to manipulate things in the ruby space as opposed to structure.sql.

**Comment by kddeisz** [comment]
(All this being said I can see arguments for both and can withdraw if it's not a desired addition, it just felt like a small enough configuration option to not cost much.)

**Comment by rafaelfranca** [comment]
Is the schema dump faster than the database specific tool? It is hard to believe on that.

Our general guideline is: if people need things specific of the database they should use the structure.

I don't think we should allow people to control how the schema is dumped. This may make harder to them upgrade their application for a newer version of Rails, just to point one problem.

I'll ask more people opinion before making any call about it. @sgrif @senny @chancancode @matthewd @jeremy

**Comment by kddeisz** [comment]
Definitely might be specific to this application I'm working on - it has a couple eccentricities.

**Comment by matthewd** [comment]
I've previously pondered the idea of doing something like this -- allowing an application to paper over the weird corners in its schema, while still enjoying the more pleasant format.

My main concern, however, is the API exposure it creates. Sure... it's just one trivial `dump` method. But realistically, the only way someone could usefully create their own, would be to subclass `AR::SchemaDumper`, and start depending on its internals. Suddenly, this is a much larger change -- possibly too large for its benefits?

@kddeisz I think I'd suggest that you just monkey-patch `AR::SchemaDumper.dump` to instantiate your subclass instead. It's not quite a config option, but it's a pretty surgical replacement. And because you're off the beaten track, it remains obvious that you're leaning on unstable method signatures.

**Comment by kddeisz** [comment]
@matthewd - Yeah, that makes sense. I guess I was thinking of people that would do strange enough things that they wouldn't subclass. As you said, off the beaten track a bit. Happy to withdraw.

**Pull request closed without merging**
