### PR TITLE
[Feature] Support customize HTTP Method for direct upload

### PR DESCRIPTION
**Pull request by songjiz**
Since some services do not support users to config **CORS** and only support **POST** method, let's provide a way to cover the shortage.

### CODE REVIEW

**Comment by georgeclaghorn** [comment]
Which service requires POST?

Having three `*_for_direct_upload` methods in the Service API is smelly. I think we ought to combine them into a single `direct_upload` method that returns a `DirectUpload` object. The default implementation can call `url_for_direct_upload` and `headers_for_direct_upload` for backward compatibility:

```ruby
class ActiveStorage::DirectUpload
  attr_reader :method, :url, :headers

  def initialize(method:, url:, headers:)
    @method, @url, @headers = method, url, headers
  end

  def as_json(*)
    { method: method, url: url, headers: headers }
  end
end

class ActiveStorage::Service
  def direct_upload(key)
    ActiveStorage::DirectUpload.new method: "PUT", url: url_for_direct_upload(key), headers: headers_for_direct_upload(key)
  end
end

class ActiveStorage::Blob < ActiveRecord::Base
  def direct_upload
    service.direct_upload(key)
  end
end

class ActiveStorage::DirectUploadsController < ActiveStorage::BaseController
  def create
    blob = ActiveStorage::Blob.create_before_direct_upload!(blob_params)
    render json: blob.as_json(root: false, methods: [ :signed_id, :direct_upload ])
  end
end
```

We’d deprecate the `*_for_direct_upload` methods in Rails 6.0 and remove them in 6.1.

**Comment by songjiz** [comment]
@georgeclaghorn Thank you for your suggestion!
I'm sorry I didn't say it clearly. In china, we use the Qiniu Cloud Storage, 
as I mentioned, it does not support users to config the **CORS** and only support **POST** method for direct upload request.
You are right this way is smelly.

**Comment by qinmingyuan** [comment]
@songjiz 
does this issue has any progress?
If not, I can continue working on this by @georgeclaghorn 's suggestion~

**Comment by qinmingyuan** [comment]
why closed this PR?

**Pull request closed without merging**
