### PR TITLE
Fixed "fake" nested transactions swallowing manual rollbacks.

### PR DESCRIPTION
**Pull request by tgxworld**
Implements https://github.com/rails/rails/pull/15017 with all the tests passing

### CODE REVIEW

**Comment by tgxworld** [comment]
WIP because I managed to add new failing tests.

**Comment by tgxworld** [comment]
@chancancode I know it has been years but I just wanted to let you know I copied most of [your previous PR](https://github.com/rails/rails/pull/15017) here. Only thing I did was to add two more tests and got the test suite to pass :grin: I've added you as a co-author but do let me know if you're OK with that.

**Comment by tgxworld** [comment]
Just realized that this might be a backwards incompatible change if people are relying on the fact that raising in a nested transaction does not rollback the parent transaction. Will think about this more next week.

**Comment by tgxworld** [comment]
@eugeneius May I check if there is interest from the Rails team to fix this at some point? I'm wondering if this should be kept opened now that it has been marked as stale.

**Comment by chancancode** [comment]
Speaking as a community member, I would love to see this finally fixed! However, I don't know if I am in a good position to personally review and merge this 😅

I personally do believe it is fixing a bug, and a rather important and subtle one, and the code generally looks good to me. But as it has been around for so long and baked pretty deep, someone who actively maintains the Active Record code should probably review this, and check that it interacts with the newer Active Record features (like multiple connections) properly.

Happy to provide any context though there is not a whole lot of those left in my head 😄

**Pull request closed without merging**
