### PR TITLE
Rake task to restart spring

### PR DESCRIPTION
**Pull request by lxsameer**
Restart task added to railties rake tasks in order to address #18876 , #18874 and #18878 issues without expanding spring watchlist.

### CODE REVIEW

**Comment by lxsameer** [comment]
Also an alternative to #18965

**Comment by senny** [comment]
We should go down the path of expanding the default watchlist. If the user does `touch tmp/restart.txt` it's  a good idea to restart spring as well.

**Comment by lxsameer** [comment]
@senny do we have the path expandation code right now ?

**Comment by senny** [comment]
@lxsameer nope, #18874 was tagged with openacademy so I guess a student will be working on it in the near future.

**Comment by lxsameer** [comment]
@senny cool.  Where can I find more information about this `openacademy` ?

**Comment by senny** [comment]
@lxsameer I'm not sure. [here](https://www.facebook.com/OpenAcademyProgram) maybe.

@matthewd @pixeltrix @tenderlove will know where to look.

**Comment by lxsameer** [comment]
thanks

**Comment by senny** [comment]
I'm closing this in favor of #18874

**Pull request closed without merging**
