### PR TITLE
Exit with error when rails is called with invalid arguments from wrong directory

### LINKED ISSUE #42607: Rails exits with zero code if launched with invalid parameters in command-line outside of project directory
I noticed this problem while configuring CI. I called `rails db:migrate` from incorrect folder. It passed: it rendered usage instructions without returning any error code.

### Steps to reproduce

When called outside of project directory
```bash
rails some-invalid-argument
```

### Expected behavior
Renders usage instructions and return a non-zero exit code

### Actual behavior
Renders usage instructions and returns a zero exit code as if there is no error.

### System configuration
**Rails version**:
7.0.0.alpha

**Ruby version**:
2.7.3

### PR DESCRIPTION
**Pull request by endenis**
### Summary

This PR fixes the problem I had with rails command-line tool: rails exits with zero code if launched with invalid parameters in command-line outside of project directory https://github.com/rails/rails/issues/42607

I simply added `exit(1)` for situations when there is an argument that is replaced by `--help`.

### CODE REVIEW

**Comment by zzak** [comment]
Could you add a test?

**Comment by p8** [comment]
I think we should check for this earlier in these conditionals:
https://github.com/rails/rails/blob/main/railties/lib/rails/cli.rb#L14-L19

**Comment by p8** [comment]
This is also somewhat related to: https://github.com/rails/rails/pull/41425

**Comment by endenis** [comment]
@zzak thank you for your comment. I added a [test](https://github.com/rails/rails/pull/42608/files#diff-b6213cc19b50b6be70ef19410e6ddb509514a3351ebc9431f727fb843d17c61eR23).

**Comment by endenis** [comment]
@p8 interesting point, thank you 🙂 

I expanded the logic from cli.rb to handle invalid arguments and moved it to a [method](https://github.com/rails/rails/pull/42608/files#diff-daec7e54d156bdfe6dbad4f8f16481556469a2b2441d317499a83b9ba3ea5d70R92) of the Command class.

I also moved the logic of `--version` out of the `ARGVScrubber` class because in my opinion rendering version information should not be responsibility of that class.

**Pull request closed without merging**
