### PR TITLE
Remove test_unit plugin_generator

### PR DESCRIPTION
**Pull request by skipkayhil**
### Motivation / Background

While looking for templates using the `.rb` extension instead of `.rb.tt`, my search ended up finding this `test_helper.rb` file. (The other two are fixed in #52239)

```
$ fd | rg "/templates/.*\.rb$"
./actioncable/lib/rails/generators/channel/templates/application_cable/channel.rb
./actioncable/lib/rails/generators/channel/templates/application_cable/connection.rb
./railties/lib/rails/generators/test_unit/plugin/templates/test_helper.rb
```

### Detail

Instead of correcting the extension, I opted to remove it because the `test_unit:plugin` generator appears to be unused.

### Additional information

Am I right in thinking this is unused? The only tests that fail are related to generator namespace fallbacks, but that seems like a side effect of the specific class no longer existing instead of any external behavior changing. I can try updating the tests if we agree it should be removed.

### Checklist

Before submitting the PR make sure the following are checked:

* [ ] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [ ] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [ ] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by zzak** [comment]
I have a new `--dev` app, and when I run `bin/rails g` these are showing up:

```
TestUnit:
  test_unit:channel
  test_unit:generator
  test_unit:install
  test_unit:mailbox
  test_unit:plugin
```

I haven't investigated further though :pray:

**Comment by skipkayhil** [comment]
Yeah, my thinking is that this was an early part/implementation of generating test infrastructure for plugins, but now the `test_helper.rb` file it generates hasn't been kept up to date with the one inside the `plugin_generator`.

**Comment by zzak** [comment]
I looked into this a bit.

First, rspec has no plugin generator: 
https://github.com/rspec/rspec-rails/tree/main/lib/generators/rspec

This is the closest I could come up with a use-case:

1. `bundle exec railties/exe/rails new ../apps/TestApp --dev`
2. `bin/rails g plugin vendor/MyPlugin --skip-test --skip-git`
3. Fix up `vendor/MyPlugin/my_plugin.gemspec` (remove TODO, etc)
4. `bin/rails g test_unit:plugin vendor/MyPlugin`

```
       exist  test
      create  test/my_plugin_test.rb
    conflict  test/test_helper.rb
```

This results in trying to overwrite the existing application's test files (because `.`).

If you use `rails plugin new` to generate a clean plugin, there is no `rails` command (different from the `bin/rails` cli) available to load the `test_unit` generators. (`bundle exec rails` only provides `new` and `plugin new` commands).

Since these files really don't do anything, and I couldn't find a direct dependency either, I think they are safe to remove.

**Comment by rafaelfranca** [comment]
It was for the old style of plugins.

**Comment by rafaelfranca** [comment]
Tests are failing

**Pull request merged**
