### PR TITLE
Opt-in to ActionCable

### PR DESCRIPTION
**Pull request by jcoyne**
Rather than having ActionCable be opt-out, make it opt-in.
This saves a lot of unnecessary dependencies if ActionCable is not used.

### CODE REVIEW

**Comment by jvanbaarsen** [comment]
Would it be possible with this approach to easily add it later on?

**Comment by jcoyne** [comment]
@jvanbaarsen It wouldn't be terribly difficult. It might be a nice next step, to have a generator for `action_cable:install`.

**Comment by jvanbaarsen** [comment]
@jcoyne I think that should be part of this PR, although I'm not sure what the core team thinks about it :P

**Comment by jcoyne** [comment]
@jvanbaarsen I have limited time to devote to rails, so I'm unlikely to get to that.   I'm going to concentrate on getting this limited change working first.  If you'd like to help out, please feel free to improve this PR.

**Comment by nateberkopec** [comment]
A similar change has already been rejected: https://github.com/rails/rails/pull/22714

I believe the Rails core position here is that EventMachine/Redis should/can be removed from the current implementation of ActionCable, but ActionCable is not optional.

**Comment by jcoyne** [comment]
@nateberkopec Thanks for that. I thought this what @rafaelfranca  was insinuating via conversation on #22907

**Pull request closed without merging**
