### PR TITLE
Update Action Cable README.md - typo fix

### PR DESCRIPTION
**Pull request by HarryCollins**
Fixing a typo in the Action Cable ReadMe.md file.

### CODE REVIEW

**Comment by kamipo** [comment]
Thanks!

In the future, please add `[ci skip]` to any commits that involve changing the documentation, to avoid running the entire Rails test suite.

**Comment by y-yagi** [comment]
If my understanding is correct, `find_verified_user` is not a comparison, it is checking whether the `user_id` set in the cookie is correct, and processing for setting that user. Therefore, I think the original code is correct.

**Comment by kaspth** [comment]
@y-yagi is right and I've reverted this in b242796. Thanks!

**Comment by kamipo** [comment]
Ah... Probably assigning local variable named `current_user` in the condition is confusing. I'll create a PR that rename the local variable name.

**Comment by kaspth** [comment]
@kamipo sure, `verified_user` seems apt :)

**Comment by kamipo** [comment]
Created #28570.

**Pull request merged**
