### PR TITLE
[ci skip] Fix hours to minutes in `select_minute`

### PR DESCRIPTION
**Pull request by yui-knk**

### CODE REVIEW

**Comment by claudiob** [comment]
@yui-knk Hello! 

I'm not sure this commit _fixes_ something, could you elaborate on that?

As I see it, the `+ 6.hours` is just there to mimic the documentation of `select_hour` below.
It's just as an example as valid as the one you suggest.

**Comment by yui-knk** [comment]
Example of `select_date` is `my_date = Time.now + 6.days`, `select_hour` is `my_time = Time.now + 6.hours`, `select_day` is `my_date = Time.now + 2.days`.
So `my_time = Time.now + 10.minutes` is suitable example of `select_minute` I feel.

**Comment by zzak** [comment]
> So my_time = Time.now + 10.minutes is suitable example of select_minute I feel.

Agreed. Since we're talking about minutes here, this makes sense to me.

**Comment by yui-knk** [comment]
Thanks! I feel `select_second` has same mismatch. So I will fix it in docrails.

**Pull request merged**
