### PR TITLE
Add HORO_CANONICAL_URL to api docs generator

### PR DESCRIPTION
**Pull request by zzak**
We want to be able to generate a meta tag for the canonical link header. (Re: #45880 and zzak/sdoc#190).

This enables SDoc generator to read this variable and insert it in the HTML tags. It's not perfect, but I think it's the simplest option.

### CODE REVIEW

**Comment by p8** [comment]
@zzak this looks good to me, but shouldn't we first add support in sdoc?

**Comment by skipkayhil** [comment]
I may be not understanding the purpose of canonical URLs, but my interpretation of #45880 was that the goal was to elevate "versionless" pages over potentially outdated pages (versioned) in search results. Wouldn't including a version or `edge` in a canonical url continue to make it difficult for search engines to prioritize the most up to date docs (the non-edge and versionless ones)?

**Comment by zzak** [comment]
That's why I'm opening this for discussion, it's less-likely anyone will notice the issue on sdoc.

I'm not entirely sure what the best value here is, and I don't pretend to be an SEO expert 😂 

Should it be `https://api.rubyonrails.org/`? Or `edgeapi` for main and leave off the versions for stable?

My gut tells me for main it should be `https://edgeapi.rubyonrails.org` and `https://api.rubyonrails.org` for everything else, no version suffix.

Then on SDoc we can strip the version tag, this won't be an issue until 7.1 is release however. Since the rdoc is generated from the stable branch, unless we backport it. And finally print the meta tag in the head.

**Comment by p8** [comment]
I think most of the time we'd want `https://api.rubyonrails.org/` as `https://edgeapi.rubyonrails.org/` contains documentation for unreleased versions. So I think edge should point to main as well.

**Comment by zzak** [comment]
Roger, I will fix this to just set the base domain for `api.ror.org` and then hook it up to SDoc.

Thanks for the feedback! :bow:

**Comment by zzak** [comment]
Tested this with zzak/sdoc#200 locally and works fine, going to merge so we can keep building more stuff into sdoc 🙏

**Comment by zzak** [comment]
Can see a demo of them working together here:
https://deploy-preview-201--nervous-roentgen-6c1877.netlify.app/

**Pull request merged**
