### PR TITLE
Deprecating update_attribute by cherry-picking b081f6b59fb3f15d12043072a...

### PR DESCRIPTION
**Pull request by amutz**
Hello,

I believe the ActiveRecord::Base method update_attribute was intended to be deprecated in 4.0.  As you can see from the discussion here:

https://groups.google.com/forum/#!topic/rubyonrails-core/BWPUTK7WvYA/discussion
and
https://github.com/rails/rails/commit/b081f6b59fb3f15d12043072ad9b331ffd2bc56e

it was originally deprecated in 3.2 and removed in 4.0.  After that, I believe these changes were reverted so as to not deprecate functionality in patch releases:

https://github.com/rails/rails/commit/81542f95d25825a7d3eff87d6f706661bf553b18

However, I think the intent was still to have it deprecated in 4.0.

This pull request adds that deprecation.  Please let me know if this is indeed desired, and if so if any changes are needed.

Likely interested parties: @fxn and @steveklabnik

Thanks!
Andrew

### CODE REVIEW

**Comment by davidwparker** [comment]
@rafaelfranca - quick question: I understand `update_column` is different from `update_attribute`, but shouldn't one of the two public API methods be changed to reflect that they're different? E.g. Changed to `update_attributes` and `update_column`? This seemed like it was going to fix it: https://github.com/rails/rails/pull/6739

It seems I have to Google the difference every 6 months after I forget which is which.

Thanks!

**Comment by rafaelfranca** [comment]
What do you mean with changed?

**Comment by davidwparker** [comment]
This change that @steveklabnik did https://github.com/rails/rails/pull/6739/files seemed to be what I was after. It makes it clear that they're different, issues a warning about deprecation, and sets people on the right path for the future. As the API currently stands, it's confusing because just reading `updating_attribute` and `update_attributes` without looking at the source, people would think they'd do the same thing, just a single attribute vs multiple.

**Comment by rafaelfranca** [comment]
It is documented, so yeah, people will have to look at the documentation, and no, this is not a problem.

**Comment by davidwparker** [comment]
I'd disagree that it's not a problem, as there's been a 139025 views on this SO in 5 years: http://stackoverflow.com/questions/2778522/rails-update-attribute-vs-update-attributes

Obviously, just looking at the names only, it's surprising that they're different. Yes, there's documentation about it, which is a good first step, but my opinion is that I still think this should be deprecated. Whether that means much (probably not), is another story.

**Pull request closed without merging**
