### PR TITLE
Option not to line up column attributes in schema.rb

### PR DESCRIPTION
**Pull request by TimPetricola**
Column arguments are lined up for a given table in `schema.rb`. It is intended as a feature but it can get confusing in git diffs where whitespace are often added for columns with no changes. This PR adds a `ActiveRecord::SchemaDumper.standardized_argument_widths = false` option to avoid that.

Let's say we have an `address` table with the following schema:

``` rb
create_table "address", force: :cascade do |t|
  t.string "zipcode", limit: 5
end
```

Adding another column with a longer name would also change the line for `zipcode`:

``` diff
-   t.string "zipcode", limit: 5
+   t.string "zipcode",           limit: 5
+   t.string "extra_information", limit: 255
```

And generated `schema.rb` would now be:

``` rb
create_table "address", force: :cascade do |t|
  t.string "zipcode",           limit: 5
  t.string "extra_information", limit: 255
end
```

By setting `ActiveRecord::SchemaDumper.standardized_argument_widths` to `false`, we would have the following diff and schema instead:

``` diff
+   t.string "extra_information", limit: 255
```

``` rb
create_table "address", force: :cascade do |t|
  t.string "zipcode", limit: 5
  t.string "extra_information", limit: 255
end
```

### CODE REVIEW

**Comment by thewoolleyman** [comment]
+1, cleaner diffs are good.

**Comment by matthewd** [comment]
Can you expand on your reasoning behind keeping the `type_length` alignment?

**Comment by TimPetricola** [comment]
@matthewd My bad, it should have been there. I added a second `ActiveRecord::SchemaDumper.standardized_type_widths` option for this. It might be worth merging both though. What do you think?

**Comment by TimPetricola** [comment]
Any update on this one ? :)

**Comment by bdewater** [comment]
Personally I think this should be the default 😄  but since that is probably out of the question it should be documented (perhaps [here](https://github.com/rails/rails/blob/master/guides/source/active_record_migrations.md#schema-dumps-and-source-control)?) and of course have a changelog entry.

**Comment by prathamesh-sonpatki** [comment]
I don't think the documentation should go to the migration guide because even without this patch we want to check in these files in the source control. 

It should go the configuration guide [here](https://github.com/rails/rails/blob/master/guides/source/configuring.md#configuring-active-record). 

And we need changelog of course :)

**Comment by TimPetricola** [comment]
Now with a changelog entry and some documentation in the configuration guide :) @prathamesh-sonpatki

**Comment by rafaelfranca** [comment]
Could you squash your commits and rebase the branch?

**Comment by maclover7** [comment]
@TimPetricola Restarted the random failing Action Cable test job. Should be good now, hopefully. :)

**Comment by TimPetricola** [comment]
Thanks @maclover7, it fixed it :)

**Comment by dhh** [comment]
I'd prefer that we just make this the new style. No need to have this be configurable.

**Comment by rafaelfranca** [comment]
Better yet. I just prepared a patch to remove the config and make it the default.

**Comment by rafaelfranca** [comment]
Pushed in df84e98

**Comment by theGirrafish** [comment]
From reading the thread, I suppose there is no way to re-enable the old behaviour of formatting the schema for the latest Rails version?

**Comment by rafaelfranca** [comment]
That is right

**Pull request merged**
