### PR TITLE
Add support for basic CTEs by introducing Relation#with.

### PR DESCRIPTION
**Pull request by simi**
I'm using CTEs quite often in Rails applications and I think they deserve to be first class citizens in Active Record.

This is initial port of https://github.com/kmurph73/ctes_in_my_pg (which is based on https://github.com/DavyJonesLocker/postgres_ext) with removed `PG` dependency and without recursive support. Recursive support can be added later if needed, but I'm not sure about the API for now.

:information_source: ~~There is [one known problem](https://github.com/kmurph73/ctes_in_my_pg/issues/6), I'll take a look if it is still present and try to fix it as well.~~ fixed in this PR

### CODE REVIEW

**Comment by simi** [comment]
I have fixed problem with `{update|delete}_all` and added specs for that.

**Comment by booleanbetrayal** [comment]
Would love to see official support for CTEs in Rails. Hoping this PR is a step in the right direction.

**Review by jeremy — COMMENTED** [review]
This is cool. Thank you for contributing @simi. How would you explain its usage to Rails users? What should we share in the changelog and in the AR guides?

**Comment by vlado** [comment]
Hi @jeremy, glad to see interest for this topic again.

Things are explained and discussed in more details on this PR https://github.com/rails/rails/pull/37944. Maybe you can take a look at it also.

**Comment by jeremy** [comment]
Nice @vlado. Let's merge efforts into one PR. @simi?

**Comment by simi** [comment]
@jeremy sure, I'll need to fix some Arel internals (already part of this PR) to support update and delete as mentioned. I would submit separated pull request only for that first. Once that would be merged, we can continue at #37944.

Not sure about the guides (and overall communication to users). Some fo the usage examples are already at #37944, I can also try to share our usage of CTEs in our Rails app to prepare some valid usecases for later. Anyway I think we can work on documentation later (in followup pull request).

**Comment by jeremy** [comment]
Proceeding in #37944.

**Pull request closed without merging**
