### PR TITLE
Add test for parsing application/vnd.api+json

### PR DESCRIPTION
**Pull request by rodzyn**
I was intrigued by https://github.com/rails/rails/issues/21168 so I've added tests for parsing this.

### CODE REVIEW

**Comment by seuros** [comment]
For some reason TravisCI didn't pickup this one.

**Comment by rodzyn** [comment]
@seuros Just rebased that stuff to trigger CI (https://travis-ci.org/rails/rails/builds/76588935)

**Comment by arthurnn** [comment]
seems like CI is green. Dont you need to add what @radar suggested here https://github.com/rails/rails/issues/21168#issuecomment-135589569 ?

**Comment by rodzyn** [comment]
@arthurnn yeah, I'm planning to finally dig into that this week

**Comment by sgrif** [comment]
@rodzyn: Ping!

**Comment by bobintornado** [comment]
Seem this completes #20329

**Pull request merged**
