### PR TITLE
Replace `loop` to `until`

### PR DESCRIPTION
**Pull request by Neodelf**
Propose replace `loop` to `until` for better readability and increase speed execute.
The discussion at the [link](https://groups.google.com/forum/#!topic/rubyonrails-core/IxS0dEwhIdQ)

 /cc @fxn

### CODE REVIEW

**Comment by kaspth** [comment]
> increase speed execute

Please add a benchmark (using benchmark-ips) to your commit message and PR description proving this 😁

**Comment by Neodelf** [comment]
@kaspth no problem :)
```ruby
require "benchmark/ips"

NUMBER = 100_000_000

def old_slow
  index = 0
  loop do
    break if index > NUMBER
    index += 1
  end
end

def new_fast
  index = 0
  until false
    break if index > NUMBER
    index += 1
  end
end

Benchmark.ips do |x|
  x.report("new_fast") { new_fast }
  x.report("old_slow") { old_slow }
  x.compare!
end

Calculating -------------------------------------
            new_fast     1.000  i/100ms
            old_slow     1.000  i/100ms
-------------------------------------------------
            new_fast      0.650  (± 0.0%) i/s -      4.000  in   6.152696s
            old_slow      0.254  (± 0.0%) i/s -      2.000  in   7.873775s

Comparison:
            new_fast:        0.7 i/s
            old_slow:        0.3 i/s - 2.56x slower
```

**Comment by fxn** [comment]
The motivation for this change is not performance, but readability. No need for a benchmark in this particular PR.

**Comment by kaspth** [comment]
@fxn & @Neodelf 👍

**Pull request merged**
