### PR TITLE
Add postgres multirange support

### PR DESCRIPTION
**Pull request by gustavowt**
### Summary

Adding postgress [multirange](https://www.postgresql.org/docs/14/rangetypes.html#RANGETYPES-BUILTIN) to postgres adapter.
postgres 14 now supports multirange types that could can be translated as arrays of ranges on the rails layer.

This PR adds full support of all standard multirange types of postgres, such as:

 - datemultirange
 - tsmultirange
 - tstzmultirange
 - nummultirange
 - int4multirange
 - int8multirange

```Ruby
Schedule.create(periods: [
  Date.new(2022, 2, 2)...Date.new(2022, 3, 3),
  Date.new(2022, 4, 1)..Date.new(2022, 4, 5)
])
```
Are going to be computed as

```sql
INSERT INTO shedules VALUES (id,periods) VALUES (1, '{[2022-2-2],[2022-3-3],[2022-4-1,2022-4-5)}');
```

### CODE REVIEW

**Comment by yahonda** [comment]
Do you have some real world use case to use PostgreSQL multirange types with Rails?

**Comment by gustavowt** [comment]
Hey @yahonda of course.

I think the most useful part of the multirange is to create different representations of a single set of ranges. Currently at the company I'm working on we're heavily working with schedule management and there will have lots of overlapping checking for instance.

The idea of having multiple sets of timeranges for instance would be pre-compute gaps, extensions, holidays or any blockers or availability user could have. and simply check this by using the overlapping (`&&`) operator.

Of course there is many ways of doing this by maybe splitting those representations into rows using `tsrange` for instance, but it seems to me that multiranges are definitely a better implementation of that. 

Another usage I can see also for other types is the usage for instance is a drawing application where a `nummultirange` could represent a box, with the multirange object we could detect collisions or if the objects are totally to the right/left/adjacent to an any other object.

**Comment by gustavowt** [comment]
hey @yahonda do you think that this is something that rails-core still dont want to support? Is there something you guys want to discuss still? Otherwise I can maybe move this to a separated gem maybe, totally fine.

**Comment by yahonda** [comment]
Thanks for explaining your use case. 

I am still not sure this feature is useful for many users, and this pull request is relatively large.
It would be appreciated if you consider releasing this feature as a separate gem.

**Comment by ollym** [comment]
@gustavowt did you move this to a gem, if so where is it?

**Comment by ollym** [comment]
@yahonda Rails support arrays, ranges, interval types, index using/algorithm and other postgres-specific features and you draw the line here?

This PR would be immensely useful as imagine you want to represent a "offer" which can run on multiple date ranges. Right now you could set it up as:

```ruby
add_column :bookings, :date_periods, :daterange, array: true
```

And to query it you'd need to do something like:

```ruby
Booking.where('? <@ ANY(bookings.date_periods)', Date.today)
```

Which can't be indexed, and would be much nicer to represent instead as:

```ruby
add_column :bookings, :date_periods, :datemultirange
add_index :bookings, :date_periods, using: :gist
```

And now...

```ruby
Booking.where('? <@ bookings.date_periods', Date.today)
```

So much better and a huge feature in Rails' cap.

**Comment by ollym** [comment]
@yahonda please reconsider this.

**Comment by gustavowt** [comment]
> @gustavowt did you move this to a gem? If so, where is it?

I did not; it would be necessary for some monkey-patching that, unfortunately, I don't think would turn into a suitable solution.

**Comment by gustavowt** [comment]
@yahonda, any chance of reconsidering this? I could  work to recreate the PR

**Comment by gustavowt** [comment]
hey @ollym I've finally managed to extract this to a [gem](https://github.com/gustavowt/activerecord-multirange) this is still under development, missing specs, but fully functional

**Comment by ollym** [comment]
Awesome work @gustavowt, thanks! Desperately hoping that someone from Rails core team is able to pick this up I think this deserves to be part of the core.

**Pull request closed without merging**
