### PR TITLE
adds debug logging to actioncable connect

### PR DESCRIPTION
**Pull request by KeithP**
Getting actioncable working for the first time in production can be problematic: #22871
This change is intended to provide more DEBUG logging during connection to help people figure out what might be going wrong, say with their nginx configuration.

### CODE REVIEW

**Comment by eileencodes** [comment]
Thanks for the PR! Can you add a screenshot of what the new logging looks like when you don't have a valid request versus do?

**Comment by KeithP** [comment]
Example log entry with websockets working:
actioncable log working 2

Example log entry with websockets NOT working:
actioncable log not working

**Comment by eileencodes** [comment]
I think there's a lot of value in warning that it's not a valid web socket, but not sure about saying it is valid. If it's working I would assume it's valid. What do you think? Did you run into a situation where it helped to know it _was_ valid?

**Comment by KeithP** [comment]
This is for the classic situation where something works locally but when deployed in production it does not.
It useful to be able to see what the correct / working values are to compare.

**Comment by dhh** [comment]
Good thinking. I'd like to see the following changes:

```ruby
def invalid_request_message
  'Failed to upgrade to WebSocket (REQUEST_METHOD: %s, HTTP_CONNECTION: %s, HTTP_UPGRADE: %s)' % [
    env["REQUEST_METHOD"], env["HTTP_CONNECTION"], env["HTTP_UPGRADE"]
  ]
end

def successful_request_message
  'Successfully upgraded to WebSocket (REQUEST_METHOD: %s, HTTP_CONNECTION: %s, HTTP_UPGRADE: %s)' % [
    env["REQUEST_METHOD"], env["HTTP_CONNECTION"], env["HTTP_UPGRADE"]
  ]
end

# then use this
logger.error invalid_request_message

# and this
logger.info successful_request_message
```

**Comment by KeithP** [comment]
Thanks, have changed as suggested. 
Manually tested ok.

Here is the successful log extract:

Started GET "/cable" for 127.0.0.1 at 2016-02-10 18:00:01 +0000
Started GET "/cable/" [WebSocket] for 127.0.0.1 at 2016-02-10 18:00:01 +0000
Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: upgrade, HTTP_UPGRADE: websocket)

**Comment by dhh** [comment]
👍

**Comment by prasadpilla** [comment]
This came very hand while deploying Action Cable to prod, thanks! 👍

**Comment by KeithP** [comment]
Thanks for the feedback @prasadpilla, good to know it helped :)

**Pull request merged**
