### PR TITLE
Raise better error for `belongs_to` `nil` scopes

### LINKED ISSUE #20823: Belongs to with nil scope gives confusing error message
The issue can be reproduced by creating a belongs_to association with an optional scope which returns nil.

```
belongs_to :account, -> { nil }
```

This generates the following error when calling the parent association:
undefined method `visited' for nil:NilClass

The stack trace is not very useful either. It can be non-obvious locating the issue if the scope does not obviously return nil, or only sometimes does (for example, if there's an if statement).

### PR DESCRIPTION
**Pull request by maclover7**
Fixes #20823

### CODE REVIEW

**Comment by sgrif** [comment]
Can you provide context about this change in the commit message? What was the error message before? Why would `nil` ever get passed in here? Is it common enough that it's worth losing the duck typing? (In particular, this would break the ability to pass a hash).

**Comment by maclover7** [comment]
@sgrif:

- updated my commit message with more info
- I don't think it exactly matters _why_ we end up with `nil` (maybe there's a method that evaluated to nil that was called, doesn't explicitly have to have `nil` inside the brackets)
- Do we support duck typing with `ActiveRecord::Relation`? If there's a better way to make sure that this is a "valid" scope, I'm totally up for discussion 👍

**Comment by sgrif** [comment]
Yes, it does matter why. We shouldn't add complexity to the code base
without justification that is rooted in a real world use case

**Comment by matthewd** [comment]
*If* we're going to make a change here, I would think `|| all` would be the thing to do: this block is a scope, and defined scope blocks will treat nil as all.

But also, the error as written is simply wrong, because the value in question is the *result* of evaluating the "scope argument", not the scope argument itself.

Also also, the 'before' error shown in the commit message is pretty clearly not coming from the code we're looking at. Is this definitely fixing the actual reported problem?

Also also also, the change looks conspicuously like #20826, yet carries no credit to that effect.

**Comment by sgrif** [comment]
Agreed that `|| all` is the right call here.

**Comment by solojavier** [comment]
Can we close this issue? Unless there is a reason to move forward with it...

**Comment by kamipo** [comment]
Closing in favor of 925e6d5.

**Pull request closed without merging**
