### PR TITLE
Allow accepting `service` as a proc in `has_one_attached` and `has_many_attached`

### PR DESCRIPTION
**Pull request by yogeshjain999**
### Motivation / Background

This Pull Request has been created because `service` kwarg in `has_one_attached` and `has_many_attached` methods accepts only symbols as values. It allows to define a `service` at a class-level context. But in one of our requirements, we wanted to upload files based on user's region due to some regulations. So in order to allow defining a `service` at instance-level context, this PR makes the changes to accept `service` as a Proc as well.

### Detail

This Pull Request changes `has_one_attached` and `has_many_attached` logic where:

- `service` can be accepted either as a symbol or a proc
- Service configuration for symbols is validated on application boot but for procs, it'll validated at runtime.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Review by jonathanhefner — COMMENTED** [review]
I think this is a reasonable addition. :+1:  I've pushed a commit to refactor a bit.

I moved `validate_service_configuration` to `ActiveStorage::Blob` so that `CreateOne#attachment_service_name` can call it instead of duplicating the validation logic.  (`validate_service_configuration` relies on `ActiveStorage::Blob.services` anyway, so I think it makes sense.)

I also changed the tests to use a subclass of `User` instead of `class_eval`.  Using `class_eval` permanently adds the attachment reflections to `User`, which affects [the "reflecting on all attachments" test](https://github.com/rails/rails/blob/8e73e620b1072c831b81604449385dfbb60bdb63/activestorage/test/models/reflection_test.rb#L39-L45) (as you noticed).  But because tests are run in a random order, the `class_eval` statements may not run before the "reflecting on all attachments" test, [causing a flakey failure](https://buildkite.com/rails/rails/builds/101428#018b859d-0c90-4efc-a56b-0b138c621608/1182-1332).  Using a subclass per test isolates the attachment reflections to that test.

Looks like CI is having some issues right now, so I will re-trigger a build later.  But take a look and let me know what you think!

**Comment by yogeshjain999** [comment]
@jonathanhefner thanks, both changes looks good to me!!

Agree about not using `class_eval`, I was wondering same for existing tests and how the flaky didn't occur. But now I understood that all those tests raises exception and doesn't mutate the `User` 😄

**Comment by jonathanhefner** [comment]
Thank you, @yogeshjain999! :globe_with_meridians:

**Comment by swiknaba** [comment]
raises an error here: https://github.com/rails/rails/blob/v7.1.2/activestorage/lib/active_storage/service/registry.rb#L11

> activestorage-7.1.2/lib/active_storage/service/registry.rb:11
> `undefined method `to_sym' for #<Proc:0x00000001219b`
>
> services.fetch(name.to_sym) do |key|

**Comment by jonathanhefner** [comment]
@swiknaba This feature has not been released yet; it is not available in Rails 7.1.2.

**Pull request merged**
