### PR TITLE
Add ago/in words to time_ago_in_words

### PR DESCRIPTION
**Pull request by n-studio**
### Motivation / Background

I recently encountered the issue https://github.com/rails/mission_control-jobs/issues/136 on mission control and I realized that Rails didn't have a way to localize the word `ago` out of the box.

~This PR will break a lot of projects but I think it's a valuable add, and the update is pretty straightforward.~

EDIT: added `config.action_view.include_prefix_or_suffix_to_time_ago_in_words` to keep retro-compatibility.

### Details

Before:

```ruby
#   time_ago_in_words(3.minutes.from_now)                 # => 3 minutes
#   time_ago_in_words(3.minutes.ago)                      # => 3 minutes
```

After:

```ruby
#   time_ago_in_words(3.minutes.from_now)                 # => in 3 minutes
#   time_ago_in_words(3.minutes.ago)                      # => 3 minutes ago
```

Example of localization:

```yml
ja:
  datetime:
    distance_in_words:
      ago: "%{time}前"
      from_now: "%{time}後"
es:
  datetime:
    distance_in_words:
      ago: "hace %{time}"
      from_now: "en %{time}"
fr:
  datetime:
    distance_in_words:
      ago: "il y a %{time}"
      from_now: "dans %{time}"
```

### CODE REVIEW

**Comment by rafaelfranca** [comment]
I'm ok with this implementation, but I'm not sure about the feature. It isn't always that you want the `ago` on `in` in the text. 

If we change this in Rails, it should not be a global, but a per call argument, which in my view, just complicate the API of this method for a case that is rare.

I think this should just be a change in mission_control-jobs.

@dhh what do you think?

**Comment by n-studio** [comment]
@rafaelfranca Thank you for your comment!

If someone just wants the distance of time they still can use `distance_of_time_in_words`. I think that if you explicitly use `time_ago_in_words` rather than `distance_of_time_in_words`, you do want to have the `ago` or `in`.

**Comment by dhh** [comment]
Yeah, I see where this is coming from, but I don't like having a top-level toggle or the complicated implementation for this.  Mission control should just be hard-coded to English. It's an internal admin tool.

**Comment by MatheusRich** [comment]
@dhh @rosa @rafaelfranca I think this is useful, so I took a stab with different approach at https://github.com/rails/rails/pull/55405.

**Pull request closed without merging**
