### PR TITLE
Fix `rake db:migrate:status` with subdirectories

### PR DESCRIPTION
**Pull request by kamipo**

### CODE REVIEW

**Comment by kamipo** [comment]
### Steps to reproduce

```
$ git clone git@github.com:kamipo/rails_issue_25174.git
$ cd rails_issue_25174
$ bundle install
```

```
$ tree db
db
├── development.sqlite3
├── migrate
│   ├── 2015
│   │   └── 20150601010101_create_users.rb
│   └── 20160602020202_create_items.rb
└── seeds.rb

2 directories, 4 files
```

```
$ rake db:migrate
(in /Users/kamipo/work/rails_issue_25174)
== 20150601010101 CreateUsers: migrating ======================================
-- create_table(:users)
   -> 0.0014s
== 20150601010101 CreateUsers: migrated (0.0015s) =============================

== 20160602020202 CreateItems: migrating ======================================
-- create_table(:items)
   -> 0.0031s
== 20160602020202 CreateItems: migrated (0.0031s) =============================

$ rake db:migrate:status
```

### Expected behavior

```
$ rake db:migrate:status

database: /Users/kamipo/work/rails_issue_25174/db/development.sqlite3

 Status   Migration ID    Migration Name
--------------------------------------------------
   up     20150601010101  Create users
   up     20160602020202  Create items

```

### Actual behavior

```
$ rake db:migrate:status

database: /Users/kamipo/work/rails_issue_25174/db/development.sqlite3

 Status   Migration ID    Migration Name
--------------------------------------------------
   up     20150601010101  ********** NO FILE **********
   up     20160602020202  Create items

```

### System configuration
**Rails version**: 5.0.0.rc1

**Ruby version**: 2.3.0p0

**Comment by kamipo** [comment]
`db:migrate` supports subdirectories and have a test.

https://github.com/rails/rails/blob/v5.1.0.beta1/activerecord/test/cases/migrator_test.rb#L78-L85

But `db:migrate:status` doesn't work with subdirectories. It is due to
`Dir.foreach(path)` is not the same with `Dir["#{path}/**/[0-9]*_*.rb"]`.

I extracted `migration_files` and sharing it in the both to fix the
issue. And added tests for `db:migrate:status`.

**Comment by kamipo** [comment]
@pixeltrix Could you review the fix?

**Comment by pixeltrix** [comment]
I rebased and merged in b1459fce6e5b64e9b70351b472816b219af5d6fd

**Comment by kamipo** [comment]
Thank you!

**Comment by pixeltrix** [comment]
Backported to [5-0-stable] and [4-2-stable].

[5-0-stable]: https://github.com/rails/rails/commit/0320f640cdffef0ab8c268b8eec7f379166fae1f
[4-2-stable]: https://github.com/rails/rails/commit/612edc27db6a71ee75567f08f22642e282bc2732

**Pull request closed without merging**
