### PR TITLE
[ActiveStorage] Allow the usage of custom key format in Attached::Macros

### PR DESCRIPTION
**Pull request by LikitSaeLee**
### Summary

Currently the blob key is always generated using `generate_unique_secure_token`, the purpose of this PR is to allow users to use custom key when defining the attachment. 

For example:
```ruby
class User < ApplicationRecord
  has_one_attached :avatar, key_format: 'avatars/:hash/:filename.:extension'
  has_many_attached :pictures, key_format: 'pictures/:hash/:filename.:extension'
end
```

which will upload the file `example-avatar.png` to the following url `s3.amazonaws.com/bucket-name/avatars/2vAjTGganF63Uri3TjBwunbM/example-avatar.png`. In `Disk` service, it will also namespace the attachment because of `mkdir_p`.

The user can also change the default  key_format by doing
`config.active_storage.default_key_format = ":hash/:filename.:extension"`

Currently the supported tokens are `:hash` (random string), `:filename` and `:extension`. By default the key format is `:hash` which is the same as current implementation.

The benefits of this is that this feature allows the user to namespace their attachments according to their needs. Another reason is that some users might not always want the blob key to be random string.

I think this feature is backward compatible. Please let me know if the implementation is ok, i can always work around that. Also, whether we need more token type other than the ones that i implemented. :smile: 

### Other Information

How it works:

For every blob record, the key_format is being stored in `metadata`, which guarantee the blob will regenerate back the same key format. For old blobs the key_format by default is `:hash` 

and it would solve https://github.com/rails/rails/issues/32790

### CODE REVIEW

**Comment by kaspth** [comment]
I think this has too much customization. Changing the entire key format seems overwrought as well, when all you're looking for is a prefix.

Perhaps this would be clearer defined at the service level in storage.yml?

```yml
# config/storage.yml
aws:
  blob_key_prefix: ':attachment_name' # e.g. avatars/pictures
  …
```

That's my perspective.

r? @georgeclaghorn

**Comment by georgeclaghorn** [comment]
Thanks for the PR, but I still haven’t read a compelling case for this. On the flip side, interpolating user-provided values into storage keys is begging for trouble and we’re unlikely to support it.

**Comment by chab** [comment]
@georgeclaghorn thanks for hearing us. I haven't studied this particular PR implementation as it seems we first need to convince you about the use case. Let me try this first :)

As mentionned here https://github.com/rails/rails/issues/32790#issuecomment-410150517, a use case is multi-tenancy, (e.g. apartment gem), where you can end with models having the same id in different db schemas. e.g. Two tables `schema1.users` and `schema2.users` both can have a record with id 1. I understand that, with AS current implementation, this will result in the same file-system path for both these users with id 1, when in the database they're 2 distinct records (or i've missed something..have I?)

Today with Paperclip, we use interpolation to dynamically inject the `/:tenant/` somewhere in the path, e.g: https://stackoverflow.com/questions/25793505/make-custom-path-for-paperclip. This issue seems to block our migration from Paperclip to AS - without special patching code i mean.

wdyt?

**Comment by BKSpurgeon** [comment]
> On the flip side, interpolating user-provided values into storage keys is begging for trouble and we’re unlikely to support it.

hi @georgeclaghorn would you pls be able to elaborate on why "it's begging for trouble"? (i'm trying to understand the limitations of active storage in this regard).

> Thanks for the PR, but I still haven’t read a compelling case for this.

I can answer this from my point of view: if something happens to the rails app, then the bucket will be preserved with the data organised. plus generally speaking, there are many who want it. my two cents.

**Comment by swiknaba** [comment]
for future searches: https://github.com/rails/rails/commit/4dba136c83cc808282625c0d5b195ce5e0bbaa68

**Pull request closed without merging**
