### PR TITLE
tzinfo-data not present in a Windows OS

### PR DESCRIPTION
**Pull request by sivsushruth**
Logs an info saying Gem 'tzinfo-data' is not present. Please add gem 'tzinfo-data' to your Gemfile and run bundle install.

(Let me know if this chunk of code can be placed in a better location.)

### CODE REVIEW

**Comment by sivsushruth** [comment]
Fixes #19178

**Comment by sivsushruth** [comment]
fixes #19175

**Comment by matthewd** [comment]
The conditional here doesn't excite me. If someone's going to internalize that much detail about which systems provide usable tzdata by default, I think it should be the `tzinfo` gem itself.

Alternatively, can we detect the absence of usable tzdata directly, instead of guessing from the platform?

**Comment by sivsushruth** [comment]
@matthewd Yes, makes sense. Working on it now.

**Pull request closed without merging**
