### PR TITLE
Add tests for test/cases/adapters/mysql2/view_test.rb

### PR DESCRIPTION
**Pull request by yui-knk**
Basically copy from `test/cases/adapters/postgresql/view_test.rb`.

In MySQL `CREATE VIEW` cause an implicit commit.
By this behavior, we should set `use_transactional_tests` to `false`.
If not, `SAVEPOINT active_record_1` is run out of transaction and
`RELEASE SAVEPOINT active_record_1` cause error.

### CODE REVIEW

**Comment by sgrif** [comment]
Thank you for the excellent commit message.

**Comment by yui-knk** [comment]
> excellent commit message

If not those message, I will forget why I set `use_transactional_tests` to `false` :)

**Comment by yui-knk** [comment]
@sgrif I should add `require "models/book"` ??
[postgrel test dose not require such file](https://github.com/rails/rails/blob/master/activerecord/test/cases/adapters/postgresql/view_test.rb).

**Comment by senny** [comment]
@yui-knk instead of copying the test, can we have it globally and only run it for adapters that support views?

**Comment by yui-knk** [comment]
@senny  I tried to move tests to `test/cases/view_test.rb`

```ruby
if ActiveRecord::Base.connection.supports_views?
...
class UpdateableViewTest < ActiveRecord::TestCase
...
end
...
end
```

sqlite3 returns true if we call `supports_views?`. But in sqlite update, create, and delete are not permitted.
I should `supports_views_update?` or something to each Adapters?

**Comment by senny** [comment]
what about using `current_adapter?(:MysqlAdapter, :Mysql2Adapter, :PostgreSQLAdapter)` for now?

**Comment by yui-knk** [comment]
I think implement some method (ex: `supports_writable_views?`) is better.

`current_adapter?(:MysqlAdapter, :Mysql2Adapter, :PostgreSQLAdapter)` leaks implementation of Adapter.
For example, AR adapters have `supports_views?` and this method is used only [test/cases/view_test.rb](https://github.com/rails/rails/blob/master/activerecord/test/cases/view_test.rb#L58), so to implement a method which is used mainly tests is reasonable.

**Comment by senny** [comment]
@yui-knk for now I'm leaning towards the `current_adapter?` check. If I remember correctly `supports_views?` was introduced by me. It's debatable wether this was necessary as it was only used for tests. There are discussion about extending the migration DSL to support `create_view` and `drop_view` so this makes some sense. For the time being I'd rather not add more fine grained `supports_view_` methods until we know that there are uses outside of tests.

I hope that makes some sense.

**Comment by yui-knk** [comment]
@senny  OK, I'll have a think about it.

BTW,
> There are discussion about extending the migration DSL to support create_view and drop_view
I agree to add `create_view` and `drop_view`. Where these theme is discussed? I find issues, but I can not find out.

I think https://github.com/rails/rails/issues/21509 is related to how we support view :)

**Comment by yui-knk** [comment]
@senny  Updated!

**Comment by senny** [comment]
@yui-knk thanks :yellow_heart:

**Pull request merged**
