### PR TITLE
Add security.txt to rails app template

### PR DESCRIPTION
**Pull request by sebastiandeutsch**
### Summary

Security.txt defines a standard to help organizations define the process for security researchers to securely disclose security vulnerabilities.

### Other Information

https://securitytxt.org/

### CODE REVIEW

**Comment by schnittchen** [comment]
I would expect most people not touch this file, not knowing it even exists. Maybe we should only fill in safe defaults in the file then.

And what about adding a comment pointing _the developer_ to securitytxt.org and invite him/her to fill in at least some bare details?

**Comment by EdOverflow** [comment]
I agree with @schnittchen; a comment pointing to https://securitytxt.org/#generate could help make the process easier.

**Comment by sebastiandeutsch** [comment]
@EdOverflow @schnittchen I've added the link. I could also write a little rails/rake task which asks the user some infos on the CLI and then generates the file.

**Comment by georgeclaghorn** [comment]
> I would expect most people not touch this file, not knowing it even exists.

Agree. Thanks, but this file isn’t a good candidate for the app generator. People who want it in their apps can trivially add it.

**Comment by EdOverflow** [comment]
@georgeclaghorn: Could you please elaborate? Could the same not be said about [robots.txt](https://github.com/rails/rails/blob/master/railties/lib/rails/generators/rails/app/templates/public/robots.txt)? Why do you include one, but not the other?

**Comment by georgeclaghorn** [comment]
As I understand it, `robots.txt` is included primarily to avoid profligate 404 errors from crawlers, which pollute logs and trigger alerts from monitoring systems. There is no similar reason to include `security.txt` by default, especially with incorrect information.

**Comment by matthewd** [comment]
Moreover, we are not a proving ground for barely-nascent future specifications that [haven't even decided on their well-known filename](https://github.com/securitytxt/security-txt/issues/3#issuecomment-335011894).

**Comment by EdOverflow** [comment]
> [...] especially with incorrect information.

We could do the same thing as you have already done with the robots.txt file; just include a comment that directs users to the documentation.

> Moreover, we are not a proving ground for barely-nascent future specifications that haven't even decided on their well-known filename.

@matthewd: This point I completely agree with. It is too early for security.txt to be implemented, but what I was trying to figure out with @georgeclaghorn's comments was whether security.txt would be of interest to the Rails team once it has settled down and become an RFC.

**Comment by matthewd** [comment]
Even then, personally, I think I'd favour a recommendation in [the security guide](http://guides.rubyonrails.org/security.html): as @georgeclaghorn noted, there's a slight benefit to serving an empty robots.txt over a 404, but much less for less frequently-hammered well-known paths.

So, once it's a bit more established, I have no objection to encouraging its use... but IMO, a useless-until-populated file tucked inside `public/` isn't a particularly good way to do that. Notably, that's *not* why we ship the default `robots.txt`.

If anything, I'd imagine a scenario where lots of applications give a well-formed but useless (either empty, or full of example.com references) response for `security.txt` would harm, not benefit, its utility -- and thus ultimately its adoption. There's a reason 404 isn't spelled "200 Not Here Yet". :wink:

**Comment by EdOverflow** [comment]
> Even then, personally, I think I'd favour a recommendation in the security guide: [...]

I had not thought of that. This definitely sounds like a very good idea.

> So, once it's a bit more established, I have no objection to encouraging its use... but IMO, a useless-until-populated file tucked inside public/ isn't a particularly good way to do that. Notably, that's not why we ship the default robots.txt.

Absolutely. I did not mean to say that security.txt should be added now with this PR and then we wait for adoption. The other way round definitely makes more sense.

> If anything, I'd imagine a scenario where lots of applications give a well-formed but useless (either empty, or full of example.com references) response for security.txt would harm, not benefit, its utility -- and thus ultimately its adoption. There's a reason 404 isn't spelled "200 Not Here Yet". 😉

Yep, fully agree with this statement. Let's see how things progress and then maybe we can reopen this ticket or submit an issue to discuss this further.

**Comment by sebastiandeutsch** [comment]
A recommendation in the security guide is also perfectly fine.

**Pull request closed without merging**
