### PR TITLE
implement "truncate" for migrations against sqlite3 adapter

### PR DESCRIPTION
**Pull request by lostapathy**
Migrations that request a `truncate` against the sqlite3 adapter currently throw a `NotImplementedError.`  This PR implements this method and adds a test to verify that it's working.

In sqlite, "DELETE FROM [table]" is the correct syntax to implement this.  SQLite has a "Truncate Optimization" that, in most cases, treats that query as a truncation rather than a normal delete.  See, [SQLite docs](https://sqlite.org/lang_delete.html) under "The Truncate Optimization"

SQLite cannot apply this optimization when triggers exist, but it will still delete the rows.  That seems like acceptable behavior, and better than a  `NotImplementedError.` (edit: incorrectly said foreign keys, not triggers, originally)

### CODE REVIEW

**Comment by matthewd** [comment]
> SQLite cannot apply this optimization when foreign keys exist, but it will still delete the rows. That seems like acceptable behavior, and better than a NotImplementedError.

Hmm.. I'm not sure. If that were true, this would presumably belong up on AbstractAdapter.

But to me, this is a low level operation, and if the underlying engine doesn't support that operation, the right thing to do is to fail.

It's hard to draw the line between what's a variant spelling of a command, and what's emulation. 🤔

**Comment by lostapathy** [comment]
> But to me, this is a low level operation, and if the underlying engine doesn't support that operation, the right thing to do is to fail.

I thought about that, but I left it here because SQLite calls out this optimization specifically, where other adpaters may not.  I also mis-stated previously, the exception is when triggers exist, not FKs.

I understand where you’re coming from in this. At the same time, I stumbled upon this working in another library where migrations that work in Postgres or MySQL work fine but the code fails to run at all in SQLite.  It would be nice if the same code just worked everywhere. If one wants to write db-agnostic migrations, I’d rather SQLite use a path that might not optimize (in case of triggers) than have to write everything as a least common denominator (delete) that won’t optimize anywhere else.

**Comment by lostapathy** [comment]
Since @sgrif raised it on #31343, should I also be adding a test for this in `migration/compatibility_test.rb` or is that not needed as this was previously raising an exception?

**Comment by matthewd** [comment]
> or is that not needed as this was previously raising an exception?

Correct. We only care about ensuring migrations that previous worked, continue to work in the same way.

**Comment by kamipo** [comment]
Closing in favor of #34779.

**Pull request closed without merging**
