### PR TITLE
Add test for ActionController::ParameterEncoding::ClassMethods#param_encoding

### PR DESCRIPTION
**Pull request by takayamaki**
### Motivation / Background

This Pull Request has been created because I found missing test for [ActionController::ParameterEncoding::ClassMethods#param_encoding](https://api.rubyonrails.org/classes/ActionController/ParameterEncoding/ClassMethods.html#method-i-param_encoding).

### Detail

This Pull Request adds test for ActionController::ParameterEncoding::ClassMethods#param_encoding, refactor tests for more readbility, and rename some unclear named test cases .

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.
* [ ] CI is passing.

### CODE REVIEW

**Comment by p8** [comment]
Thanks @takayamaki for contributing to Rails.
Renaming the actions to descriptive names makes the tests more readable.
Adding the missing test seem like an improvement as well.
Can you squash you're commits?

**Comment by takayamaki** [comment]
Thanks for review!

>  Can you squash your commits?
Sure.
Which do you prefer that 2 commits(refactor and add test) or 1 commit?

**Comment by takayamaki** [comment]
I did it with 2commits for now.

If you prefer 1commit, please let me know.

**Comment by p8** [comment]
@takayamaki Sorry, just a single commit 😄 
https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#squashing-commits

**Comment by takayamaki** [comment]
> @takayamaki Sorry, just a single commit 😄 https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#squashing-commits

I did it.
I'll keep in mind for next time.

**Review by p8 — APPROVED** [review]

**Pull request merged**
