### PR TITLE
Consolidate `AbstractMysqlAdapter` and `Mysql2Adapter`

### PR DESCRIPTION
**Pull request by kamipo**
- Consolidate `AbstractMysqlAdapter` and `Mysql2Adapter`
- Remove `mysql2_adapter.rb` for prepare renaming
- Rename `abstract_mysql_adapter.rb` to `mysql2_adapter.rb`

To keep the history of `AbstractMysqlAdapter`.
https://github.com/kamipo/rails/blame/consolidate_abstract_mysql_adapter_and_mysql2_adapter/activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb

### CODE REVIEW

**Comment by maclover7** [comment]
Hmm, I think we're still going to need the abstract adapter for when/if the old `MysqlAdapter` gets gem-ified...

**Comment by vipulnsward** [comment]
@kamipo I may have missed this, who maintains the old adapter right now?

**Comment by vipulnsward** [comment]
Based on what @matthewd said here- https://github.com/rails/rails/pull/22642#issuecomment-165657501 , we should be waiting for the adapter to be out first.
Rails 5 is still not out, so that change of adapter removal hasn't affected many maybe?

Dropping it completely without a replacement is a big breaking change.

**Comment by arthurnn** [comment]
If I use another mysql client, (not mysql nor mysql2) , would I extend the Mysql2 adapter and change it?
Not sure if thats correct, seems like having an abstract mysql adpter make sense to me, so we can extent it and have a concrete adpter/gem implementation.

(FYI @charliesome @brianmario if you are interested in this.)

**Comment by brianmario** [comment]
> Not sure if thats correct, seems like having an abstract mysql adpter make sense to me, so we can extent it and have a concrete adpter/gem implementation.

Yeah I think keeping the abstract adapter is the right thing to do here. An argument could be made that the other database drivers should _also_ have abstract adapters, to make it easier for another implementation of those drivers to more easily integrate. But, since there aren't really any other implementations of those other drivers it's kinda hard to say the adapters should be abstracted ahead of time.

There are at least 2 implementations of mysql drivers though, so I think it makes sense to keep the common logic abstracted there 👍

**Comment by yahonda** [comment]
I'd like to know the status of this pull request and I personally wanted this pull request updated and merged. 

There was a plan to release ActiveRecord MySQL adapter as a separate gem but so far I do not see it and ActiveRecors has been changing. Not sure if there is a requirement to release ActiveRecord MySQL adapter as a separate gem.

**Comment by tenderlove** [comment]
👎 on removing the abstract adapter.  We're using it at work. 😱

**Comment by kamipo** [comment]
I agree. I'm closing it for now.

**Pull request closed without merging**
