### PR TITLE
Fix `QueryMethods#in_order_of` to handle empty order list

### LINKED ISSUE #43903: `ActiveRecord::Relation.in_order_of` produces invalid SQL with empty array
### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_valid_when_empty
    Post.in_order_of(:id, []).to_a
  end
end
```

### Expected behavior
Order by should be omitted if input array is empty:
```sql
Post Load (0.2ms)  SELECT "posts".* FROM "posts"
```

### Actual behavior
Invalid SQL generated:
```sql
Post Load (0.2ms)  SELECT "posts".* FROM "posts" ORDER BY CASE "posts"."id" ELSE 1 END ASC
```

Error details:
```
ActiveRecord::StatementInvalid: SQLite3::SQLException: near "ELSE": syntax error
```

### System configuration
**Rails version**: 7.0.0

**Ruby version**: 3.0.3

### PR DESCRIPTION
**Pull request by casperisfine**
Fix: https://github.com/rails/rails/issues/43903
Ref: https://github.com/rails/rails/pull/42061

Simply don't generate the case statement if the order list is empty
and fallback to default ordering.

cc @kddnewton @kaspth 

TODO:

  - [ ] backport to 7.0

### CODE REVIEW

**Comment by kddnewton** [comment]
Thanks for the fix @casperisfine, so I missed it in the first place!

**Comment by jonathanhefner** [comment]
Something I noticed from [this test](https://github.com/rails/rails/pull/43916/files#diff-079713db45df93841cc5db7f8058c799abe376b958f64e32df7af90f909a12f7R17-R22) is that Active Record's `in_order_of` behaves differently than [Enumerable#in_order_of](https://api.rubyonrails.org/v7.0/classes/Enumerable.html#method-i-in_order_of):

```ruby
posts = Post.all
posts.in_order_of(:id, order).pluck(:id)      # => [3, 4, 1, 2, 5, 6, 7, 8, 9, 10, 11]
posts.to_a.in_order_of(:id, order).pluck(:id) # => [3, 4, 1]
```

I feel like the two methods should be consistent, but I am unsure which is the preferred behavior.  Thoughts?

**Comment by rafaelfranca** [comment]
I think it should match the enumerable behavior.

**Comment by kddnewton** [comment]
I've added the PR here: https://github.com/rails/rails/pull/44097. This brings it in line with the enumerable version.

**Pull request merged**
