### PR TITLE
add note about adding scaffold.css to precompile array in engines guide[ci skip]

### LINKED ISSUE #19453: Problem on guides - Getting started with Engines
https://github.com/rails/rails/blob/master/guides/source/engines.md

on line 411: 
```
<%= stylesheet_link_tag "scaffold" %>
```

When start the server, and pointing to `http://localhost:3000/blorgh/articles`. An exception is thrown:
screen shot 2015-03-22 at 4 43 23 pm

Add one line to the lib/blorgh/engine.rb solved this issue:
```
module Blorgh
  class Engine < ::Rails::Engine
    isolate_namespace Blorgh
    
    # add line
    self.config.assets.precompile += %w( scaffold.css )
  end
end
```

Is it the right way to solve this?

### PR DESCRIPTION
**Pull request by mcfiredrill**
resolves #19453

### CODE REVIEW

**Comment by kaspth** [comment]
Shouldn't this happen in an assets initializer for the engine?

**Comment by mcfiredrill** [comment]
@kaspth 
I'm not sure honestly. I could change the instructions to say to make an initializer instead?

**Comment by rafaelfranca** [comment]
I'm not sure we should talk about scaffold CSS at all in this guide, it is not an assets added by the engine and I don't think people should use it at production. Lets remove the whole section altogether?

**Comment by mcfiredrill** [comment]
Thanks, I think the guide is simpler with that section removed. :+1:

**Pull request closed without merging**
