### PR TITLE
linkify the active_support/core_ext guide

### PR DESCRIPTION
**Pull request by pjump**
This makes it more useful, IMO.

(
Linkified with:

``` ruby
#!/usr/bin/env ruby
# -*- coding: utf-8 -*-

regexp = /^(\s*NOTE:\s+Defined\s+in\s+)`([^`]*)`(.*)$/
mapping = {
  "active_support" => "activesupport",
  "action_view" => "actionview",
  "action_controller" => "actionpack",
  "abstract_controller" => "actionpack",
  "action_pack" => "actionpack",
  "action_dispatch" => "actionpack",
  "active_job" => "activejob",
  "active_model" => "activemodel",
  "action_mailer" => "actionmailer",
  "active_record" => "activerecord",
}
prefix = "https://github.com/rails/rails/tree/#{ENV['RAILS_VERSION'] || 'master'}"

while $_ = gets
  $_.chomp!
  if $_ =~ regexp
    root = $2.partition("/").first
    puts "#{$1}[#{$2}](#{prefix}/#{mapping[root]}/lib/#{$2})#{$3}"
  else
    puts $_
  end
end
```

The hash is gotten through a command also. This should e more generally applicable, but I've only found these `Defined in` notes in the core_ext guide.
)

### CODE REVIEW

**Comment by fxn** [comment]
That's a good idea, but we cannot link to master for stable docs, the link should point to the file as is in the tag that corresponds to the release. Don't remember from memory how would that be implemented, will check when I get my computer.

**Comment by pjump** [comment]
Solved in the next commit. I'm probably getting the branch info from the wrong place, but it's really easy to change now.

**Comment by robin850** [comment]
Thanks for your patch @pjump, nice improvement! :+1:

Actually I would not solve the problem like that. What do you think about making the changes using Redcarpet ?

We are already treating paragraphs specifically for such kind of notes, so this is just another special case. Basically you just have to do the following:

~~~ruby
# In guides/rails_guides/markdown/renderer.rb

def paragraph(text)
  if text =~ /^\s*NOTE:\s+Defined\s+in\s+\<code\>([^`]*)\<\/code\>(.*)$/
    github_linkify($1)
  elsif text =~ /^(TIP|IMPORTANT|CAUTION|WARNING|NOTE|INFO|TODO)[.:]/
    # ...
~~~

And create the `github_linkify` method or whatever you call it with your code.

@fxn : What do you think about this approach ? Having an `.erb` extension for Markdown files seems weird as you have to escape ERB code inside it.

> we cannot link to master for stable docs, the link should point to the file as is in the tag that corresponds to the release

As guides are pushed when Rails is released, the content of the `RAILS_VERSION` file at this moment is right anyway, no ? For master (when `RAILS_VERSION` contains `alpha`), we just have to take the current commit (`git rev-parse HEAD`) if we want permalinks.

**Comment by pjump** [comment]
I think would have used `.md.erb` throughout, but since you've already gone down this route of regexp matching ...:

https://github.com/rails/rails/pull/20036

**Comment by pjump** [comment]
@robin850 I see. Personally, I think the imperative regexp matching is ugly, and brittle and that the all the docs would be better off as '.md.erb' files. (where TIP,IMPORTANT,CAUTION, etc. would be ruby methods). If needing to quote the '<%' et. al. erb tokens is a problem, you could have some `.md.tt` files where your special tokens would follow a different pattern, e.g., `<%tt` and still use erb to render that by using rake to escape <%, etc. translate <%tt etc. into <%, run it through erb, and then unescape the escaped <% etc.  

In keeping with what you've been doing so far, though, I would

**Pull request closed without merging**
