### PR TITLE
Remove gem check in guides/rails_guides.rb

### PR DESCRIPTION
**Pull request by yui-knk**
Now rails/Gemfile includes nokogiri and redcarpet,
so remove gem check from guides/rails_guides.rb

### CODE REVIEW

**Comment by schneems** [comment]
Build is failing

**Comment by yui-knk** [comment]
guides/ has no test so I think this PR never breaks tests.
Maybe https://travis-ci.org/rails/rails/builds/53372621 is effected.

**Comment by senny** [comment]
@yui-knk thank you. :yellow_heart:

**Comment by senny** [comment]
@yui-knk as a side note. These checks were not because our own Gemfile didn't include the gems but because this file was required by user applications. See cd7cc52

**Pull request merged**
