### PR TITLE
Fix CI failure for SanitizeHelperTest

### LINKED ISSUE #48313: SanitizeHelperTest#test_sanitized_allowed_tags_class_method and #test_sanitized_allowed_attributes_class_method failing
Managed to reproduce the CI failure at https://buildkite.com/rails/rails/builds/96697#0188593a-e48d-488c-9e0e-7e9b33e078de/1176-1185

### Steps to reproduce

```ruby
# Using Ruby 3.2.2
git clone https://github.com/rails/rails
cd rails
rm Gemfile.lock
bundle install
cd activeview
bin/test test/sanitize_helper_test.rb
```

### Expected behavior
It should pass.

### Actual behavior
```ruby
zzak@mbp16 rails % cd actionview
zzak@mbp16 actionview % bin/test test/template/sanitize_helper_test.rb
Running 9 tests in a single process (parallelization threshold is 50)
Run options: --seed 44838

# Running:

.....F

Failure:
SanitizeHelperTest#test_sanitized_allowed_tags_class_method [/private/var/folders/kg/6z9856y91t10b8nngbmf3pd40000gn/T/tmp.TcfAwtum/rails/actionview/test/template/sanitize_helper_test.rb:55]:
--- expected
+++ actual
@@ -1 +1 @@
-#<Set: {"strong", "em", "b", "i", "p", "code", "pre", "tt", "samp", "kbd", "var", "sub", "sup", "dfn", "cite", "big", "small", "address", "hr", "br", "div", "span", "h1", "h2", "h3", "h4", "h5", "h6", "ul", "ol", "li", "dl", "dt", "dd", "abbr", "acronym", "a", "img", "blockquote", "del", "ins"}>
+#<Set: {"a", "abbr", "acronym", "address", "b", "big", "blockquote", "br", "cite", "code", "dd", "del", "dfn", "div", "dl", "dt", "em", "h1", "h2", "h3", "h4", "h5", "h6", "hr", "i", "img", "ins", "kbd", "li", "ol", "p", "pre", "samp", "small", "span", "strong", "sub", "sup", "time", "tt", "ul", "var"}>



bin/test test/template/sanitize_helper_test.rb:50

.F

Failure:
SanitizeHelperTest#test_sanitized_allowed_attributes_class_method [/private/var/folders/kg/6z9856y91t10b8nngbmf3pd40000gn/T/tmp.TcfAwtum/rails/actionview/test/template/sanitize_helper_test.rb:60]:
--- expected
+++ actual
@@ -1 +1 @@
-#<Set: {"href", "src", "width", "height", "alt", "cite", "datetime", "title", "class", "name", "xml:lang", "abbr"}>
+#<Set: {"abbr", "alt", "cite", "class", "datetime", "height", "href", "lang", "name", "src", "title", "width", "xml:lang"}>



bin/test test/template/sanitize_helper_test.rb:58

.

Finished in 0.019089s, 471.4757 runs/s, 995.3376 assertions/s.
9 runs, 19 assertions, 2 failures, 0 errors, 0 skips
```

### System configuration
**Rails version**: main branch

**Ruby version**: ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]

### PR DESCRIPTION
**Pull request by zzak**
Fixes #48313 /cc @flavorjones

### CODE REVIEW

**Comment by flavorjones** [comment]
I would prefer for #48293 to get merged. These tests have been removed in that PR because they are too-tightly coupled to the implementation of rails-html-sanitizer.

**Comment by zzak** [comment]
Agree! Thanks for the quick feedback ❤️

**Comment by flavorjones** [comment]
Sorry this is causing failing builds. :disappointed:

**Comment by flavorjones** [comment]
Would you prefer for me to break that test-only change out from #48293 for a quick merge to fix the build?

**Comment by zzak** [comment]
@flavorjones Haha yeah, too many threads now, sorry about that. If possible a small backport-friendly fix (assuming this affects stable branches too) would be preferable not to disrupt other contributors who might be caught off-guard by a red check :bow:

**Comment by flavorjones** [comment]
Yeah, OK, need an hour or two but will do it tonight.

**Comment by flavorjones** [comment]
@zzak Actually let's get this merged. I'll rebase my other PR. This is fine for the interim. Sorry for the whiplash.

**Comment by flavorjones** [comment]
And I will take care of the other stable branches.

**Pull request closed without merging**
