### PR TITLE
Harmonize shell commands in dev guide [ci skip]

### PR DESCRIPTION
**Pull request by aried3r**
### Summary

Added `$` where necessary, as per https://github.com/rails/rails/pull/22517

Removed `bash` syntax highlighting. None of this is ShellScript, if anything
it's `console`, which would make the lines blue in GitHub, if there's any output, see
https://github.com/github/linguist/blob/935206e9ab30d3eaf974ecef3e467faa9dfcdca9/lib/linguist/languages.yml#L4432-L4443

### Other Information

The important part is adding `$` where it was previously left out. The part of removing `bash` is mainly because `bash` is the wrong syntax to highlight here, the most appropriate would be `console` as mentioned above, in GitHub it would result in blue text for the output of the command.
But, using `#` or `$` at the beginning of the line without any sample output doesn't do anything really except fix some cases where `bash` would see comments, see the examples:

#### `console` pro examples

Example, using `console`:
```console
$ rails dev:cache
Development mode is now being cached.
```
Using `bash`
```bash
$ rails dev:cache
Development mode is now being cached.
```

Another would be examples that use `#`:
`console` correctly handles `#`:
```console
# rails dev:cache
Development mode is now being cached.
```
`bash` sees a Shell Script comment:
```bash
# rails dev:cache
Development mode is now being cached.
```

#### No difference examples

Here's an example where the highlighting is off (I think), due to defining a language. First `bash`:
```bash
$ bundle exec rake test
```
Same with `console`:
```console
$ bundle exec rake test
```
Without anything:
```
$ bundle exec rake test
```

Since the document is not supposed to be consumed in its Markdown form anyway, it shouldn't make any difference for the rendered HTML.

Other projects have discussed the same https://github.com/civicrm/civicrm-dev-docs/issues/190#issuecomment-309182964. Others opted out of the prefix, because it could be confusing: https://github.com/react-boilerplate/react-boilerplate/issues/757

I couldn't find an official guidelines in the Rails docs, maybe it can be added if there isn't any?

### CODE REVIEW

**Review by schneems — CHANGES_REQUESTED** [review]
Bash looks fine 
9d90082d-149d-45a9-9e34-cb5f06d9790e

Also the target of this file is not github but our own documentation site. Please put the “bash” designation back.

The addition of $ is a good one. Modify the PR to only include that change and rebase into one commit and I’ll merge it.

**Comment by schneems** [comment]
A ping is prefered.

**Comment by aried3r** [comment]
ping @schneems, all done :)

**Comment by schneems** [comment]
Thanks!

**Pull request merged**
