### PR TITLE
Raise ArgumentError if attempting to transliterate nil

### PR DESCRIPTION
**Pull request by kmcphillips**
## Problem

When calling:
```ruby
ActiveSupport::Inflector.transliterate(nil)
```

The method raises with an unclear error:
```
NoMethodError: undefined method `empty?' for nil:NilClass
rails/activesupport/lib/active_support/multibyte/unicode.rb:215:in `tidy_bytes'
```

This is coming from `tidy_bytes` and `I18n.transliterate` both not handling `nil` either.

## Solution

Raise an `ArgumentError` explaining what the problem is and where it comes from.

Alternately we could pass through `nil`, since by definition it is also transliterated, but this is the least functionality change.

cc @rafaelfranca

### CODE REVIEW

**Comment by kirs** [comment]
```
irb(main):002:0> ActiveSupport::Inflector.transliterate(false)
NoMethodError: undefined method `empty?' for false:FalseClass
        from /Users/kir/Projects/opensource/rails/activesupport/lib/active_support/multibyte/unicode.rb:215:in `tidy_bytes'
        from /Users/kir/Projects/opensource/rails/activesupport/lib/active_support/inflector/transliterate.rb:61:in `transliterate'
        from (irb):2
        from tools/console:9:in `<main>'
```

@kmcphillips do you think we should also fix it for other kind of input as well?

**Comment by kaspth** [comment]
Thanks for the pull request! But I'm a little puzzled as to how this is makes the error clearer?

```
Cannot transliterate nil.
rails/activesupport/lib/active_support/multibyte/unicode.rb:215:in `tidy_bytes'
```

Or is there something I'm misunderstanding?

**Comment by kirs** [comment]
I think it makes sense to do `string = string.to_s` in the beginning of the method.

**Comment by kaspth** [comment]
> do you think we should also fix it for other kind of input as well?

@kirs I'm -1 on that, it seems like we're needlessly adding defensive coding.

Though a `to_s` call could be interesting 😊

**Comment by kmcphillips** [comment]
@kirs I thought about it. Was thinking it's overly defensive. But I like `.to_s`-ing it. We coerce in other places. Though I would then maybe `return if string.nil?` as we don't want to convert from `nil` to empty string.

@kaspth Is there a guide for content or error style? Could be anything:
* `Unable to transliterate value nil`
* `Can only transliterate a string value. Received nil.`

**Comment by kmcphillips** [comment]
```ruby
def transliterate(string, replacement = "?".freeze)
  return if string.nil?
  string = string.to_s     

  # the rest
end
```

👍 or 👎  on this?

It's a behaviour change, and stops a raise. But it's a behaviour change I like. It eliminates a raise, which would be great.

**Comment by kaspth** [comment]
@kmcphillips I'm interested in how you end up with `ActiveSupport::Inflector.transliterate(nil)` in your code base? Is there some snippet you can share?

Because just reading that isolated, it seems either a `to_s` or (implicitly) returning nil on a nil string could both be nonsensical for `transliterate`.

So I'm leaning toward that the `to_s` should belong in user code.

**Comment by kmcphillips** [comment]
@kaspth We call it directly for working with country/city/province names that have accents in them. Shipping APIs are kind of incredible at taking `Québec` and printing it to a shipping label as `Qu@™bec`.

My problem is that when we passed in a value that it didn't want, it raised in some other library code in a way that was awkward to figure out. I don't have a preference as to if it coerces to string or raises an `ArgumentError`. I just want the public API for this method to handle input cleanly.

**Comment by rafaelfranca** [comment]
Yes, the `to_s` belongs to the user code but the message can be better and raising an ArgumentError is the best way to improve the message. I'd go with:

```
raise ArgumentError unless string.is_a?(String)
```

Since there is no way of this code work with something that is not a string

**Comment by kaspth** [comment]
@kmcphillips I see the shipping labels like quibbling Québec 🤓

@rafaelfranca agreed.

**Comment by kmcphillips** [comment]
Changed to type checking the string. Updated the raise message.

**Comment by kaspth** [comment]
🤘

**Pull request merged**
