### PR TITLE
Fix problem with empty strings from cache

### PR DESCRIPTION
**Pull request by laomatt**
right now the caching won't trigger writing over an empty string returned from the cache store.  This will ensure that an option passed down called no_blanks, (no_blanks: true), will make it so that if the cache returns and empty string, we will trigger a write over.

### Motivation / Background

Right now if a key has an empty string from the cache store, an empty string will just be rendered to the page as the fragment.  For my app fragments kept coming up blank, and the writing was not being triggered.  So in a sense it was stuck.  This will ensure that an option passed down called blanks_ok, (blanks_ok: true/false), will make it so that if the cache returns and empty string, we will trigger a write over or it will return the empty string if it is set to true. (the default value is false, must explicitly pass true to get blank strings back)

This Pull Request has been created because my app had to way of escaping blank strings being returned from the cache.

### Detail

This Pull Request changes the way that caching writes are triggered.

### Additional information

For my app I simply monkey patched the action view helper, but I would like to move away from that and try to contribute bug fixes I found useful.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [ ] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by byroot** [comment]
Could you expand a bit about the use case? I don't quite understand why you are in this situation in the first place.

**Comment by laomatt** [comment]
> Could you expand a bit about the use case? I don't quite understand why you are in this situation in the first place.

So basically i was in a situation where my cache was returning an empty string for the key ("") and writing to the cache was never triggered, because "" technically reads as a valid value.

**Comment by byroot** [comment]
Yes that's my point. Empty string is a valid cache value and I see no reason not to treat it as such. I'm sure there is plenty of ways you can deal with this in your app. I don't think it's necessary to add complexity to the framework.

**Comment by laomatt** [comment]
I get your point, I monkey patched it in my app.

**Pull request closed without merging**
