### PR TITLE
nodoc for active support protected method [CI skip]

### PR DESCRIPTION
**Pull request by Gaurav2728**

### CODE REVIEW

**Comment by Gaurav2728** [comment]
cc @kaspth @senny  :bow:

**Comment by matthewd** [comment]
@Gaurav2728 please don't just cc everyone you can think of / have interacted with recently.

We prefer to keep addition/removal of `:nodoc:` in PRs, because it involves a decision to change whether a method is part of the published API.

**Comment by Gaurav2728** [comment]
@matthewd i haven't that intension. I got the Ans. by your reply. :blue_heart:   Thanks. !!

**Pull request merged**
