### PR TITLE
Add 'failed' notification about the connection failed event of WebSocket

### PR DESCRIPTION
**Pull request by ninjarz**
There is no way to know if the WebSocket connection that created by ActionCable is aborted before connected.

### CODE REVIEW

**Comment by kamciokamcio** [comment]
Any chance for merging this PR soon?

**Review by camaeel — APPROVED** [review]

**Comment by kamciokamcio** [comment]
@maclover7 Could you, please, accept this PR?

**Comment by matthewd** [comment]
What is the use case for this? "failed" implies something went wrong with the connection, which seems inconsistent with this method's purpose/intent.

**Comment by ninjarhyme** [comment]
@maclover7 This event will be triggered, if you cut off your network before 'onopen' event of WebSocket is triggered. (This is only one of the cases.) 
When this happens, the program keeps trying. And in the meantime, no one knows what has happened without this event.
Anyway, I just want to get the standard WebSocket close event and its error code to show some hints as reminders to users.

Also, please have a look at this link https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent for reference.

**Pull request closed without merging**
