### PR TITLE
Remove default reliance on Sass and CSS generators

### PR DESCRIPTION
**Pull request by dhh**
Modern web applications are more likely than not to use a CSS framework like Tailwind, Bootstrap, or Bulma. Rails shouldn't be generating per-model stylesheets as though we were still writing everything by hand.

Also, Sass has chosen to focus exclusively on dart-sass, which requires all manner of dependencies that Rails won't adopt by default. So decrease our reliance on Sass, and move it to being an optional extra.

### CODE REVIEW

**Comment by glaucocustodio** [comment]
Sad to see Sass not coming as default. The killer feature for me is nested syntax, it's a shame CSS still doesn't support it.

**Comment by brodock** [comment]
`sass` is becoming hard to use due to bad maintainership. They keep deprecating their libraries and the substitution version is worst everytime. They could have kept maintaining `ruby-sass` they decided to not, then there was libsass which would bring most but not all functionality and that across many languages, then they again they decided to deprecate that and move yet to another ecosystem that no one really cares (dart).

**Comment by glaucocustodio** [comment]
> `sass` is becoming hard to use due to bad maintainership. They keep deprecating their libraries and the substitution version is worst everytime. They could have kept maintaining `ruby-sass` they decided to not, then there was `libsass` which would bring most but not all functionality and that across many languages, then they again they decided to deprecate that and move yet to another ecosystem that no one really cares (dart).

the dart saas compiles to javascript, so I don't see why not using it

**Comment by jrochkind** [comment]
> The Rails Doctrine is that the menu is omakase, not a buffet: https://rubyonrails.org/doctrine/#omakase. This means offering one default setting or suggestion, but allowing substitutions.

Does this mean that Tailwind is becoming the Rails recommendation/supported option?

**Pull request merged**
