### PR TITLE
timeouts for debugging

### PR DESCRIPTION
**Pull request by jjb**
attempting to debug https://github.com/rails/rails/issues/49841

### CODE REVIEW

**Comment by jjb** [comment]
@rafaelfranca this bug isn't reproducible locally, so i was using CI for debugging

https://github.com/rails/rails/issues/49841

(if that's why you closed?)

**Comment by jjb** [comment]
thanks!

**Comment by jjb** [comment]
with this PR, the test is now unexpectedly succeeding, probably useful information for someone who has more time to debug this but I won't be able to any time soon.

**Comment by zzak** [comment]
Where you able to reliably reproduce the failure?

**Comment by jjb** [comment]
it is happening in master about 30-40% of the time https://buildkite.com/rails/rails/builds?branch=main

i didn't attempt to make it reliably fail locally

**Pull request closed without merging**
