### PR TITLE
[ci skip] Added a note about Github Codespaces' warning

### PR DESCRIPTION
**Pull request by azzenabidi**
### Summary

This edit should clarify any confusion around a persistent warning when setting up Github Codespaces to contribute to the Rails Framework. 

### Other Information

Related discussion: https://discuss.rubyonrails.org/t/issues-with-github-codespaces-setup-to-contribute-to-rails/79731

### CODE REVIEW

**Comment by yahonda** [comment]
Both `delayed_job` 4.1.10 and `delayed_job_active_record` 4.1.7 support Rails 7.
Then "Your lockfile doesn't include a valid resolution." warnings will disappear by following these steps.

* Command to update delayed_job delayed_job_active_record gems
```ruby
bundle update delayed_job delayed_job_active_record --conservative
bundle install
```

* Before running bundle update delayed_job delayed_job_active_record --conservative`

```ruby
$ bundle install
... snip ...
Using websocket-client-simple 0.3.0 from https://github.com/matthewd/websocket-client-simple.git (at close-race@e161305)
Your lockfile doesn't include a valid resolution.
You can fix this by regenerating your lockfile or trying to manually editing the bad locked gems to a version that satisfies all dependencies.
The unmet dependencies are:
* activesupport (>= 3.0, < 6.2), depended upon delayed_job-4.1.9, unsatisfied by activesupport-7.1.0.alpha
* activerecord (>= 3.0, < 6.2), depended upon delayed_job_active_record-4.1.6, unsatisfied by activerecord-7.1.0.alpha
Bundle complete! 77 Gemfile dependencies, 217 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

* After running `bundle update delayed_job delayed_job_active_record --conservative`

```ruby
$ bundle install
... snip ...
Using websocket-client-simple 0.3.0 from https://github.com/matthewd/websocket-client-simple.git (at close-race@e161305)
Bundle complete! 77 Gemfile dependencies, 217 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

Refer to these commits for detail.
https://github.com/collectiveidea/delayed_job/commit/8b6fd4b55d021acf263bbafeefb3ee8f44017f51
https://github.com/collectiveidea/delayed_job_active_record/commit/7bd1abbe3c437777cfdb2e95a46336902398ed03

**Comment by azzenabidi** [comment]
@yahonda Thanks! I will update the PR accordingly.

**Comment by azzenabidi** [comment]
@yahonda thanks! done :)

**Comment by rafaelfranca** [comment]
Instead of merging this we should just upgrade those gems in the Gemfile.lock.

**Comment by azzenabidi** [comment]
@rafaelfranca done :)

**Comment by yahonda** [comment]
This pull request should update `Gemfile.lock` file only. updating `yarn.lock` is out of this pull request scope.

**Pull request merged**
