### PR TITLE
Allow the use of custom Javascript engines in new apps.

### PR DESCRIPTION
**Pull request by Liceth**
### Summary

This will allow the use of custom Javascript engines in new apps using the --javascript-engine option.

There are others Javascript engines plugins beyond coffee-rails like [babel-rails](https://github.com/Liceth/babel-rails), [typescript-rails](https://github.com/typescript-ruby/typescript-rails), [elm-rails](https://github.com/fbonetti/elm-rails), etc.

### CODE REVIEW

**Comment by guilleiguaran** [comment]
Maybe we should call this `--javascript-engine` (we are using this name already for controllers/scaffold generators) and using `-e` as shortcut (`-j` is already used for `--javascript`)

**Comment by kaspth** [comment]
Agree on the `--javascript-engine` naming. I think there might be some code we can copy from there as well. Otherwise, looks good! 👏

**Comment by rafaelfranca** [comment]
What this does is only changing one line in the gemfile? If this is the case I'm not positive about this new configuration. It is easy to just swap the gem after the application is generated.

**Comment by guilleiguaran** [comment]
I think is not just about changing a line, it's about making Babel,TypeScript, and other options feel like they're first-class in new Rails apps.

**Comment by rafaelfranca** [comment]
I disagree. Making first class is way more than just exchanging the gem in the generated Gemfile. It is documenting, making sure the workflow is integrated, supporting the integration, etc. I don't think we are in this stage just yet.

Some reasons why i think this:

* [ruby-babel-transpiler is stuck in Babel 5](https://github.com/babel/ruby-babel-transpiler/pull/282).
* We have no experience with this setup in our applications.
* We have no previous history of any of the Rails maintainers and assets pipeline maintainers with those technologies.
* We are still departing from the tollset of the JavaScript community.

The latter for me is the main reason to not think we are adding first class support to our stack. We are already having many troubles trying to maintain sprockets exactly because we don't have context about many of the things we use. Right now, many of us are going to different directions of what this PR is trying to achieve and I think adding a half backed solution is not the direction we should take. If we want to add first class support to transpilers we should go with something that is already being used by us and battle tested. 

Like everything until now in Rails, I believe this should be extracted from one of ours applications and improved. Writing from scratch will not scale in the long term in my opinion.

**Comment by kamipo** [comment]
Closing since --javascript-engine option has been removed and replaced to Webpacker #33079.

**Pull request closed without merging**
