### PR TITLE
Make accessors generated by `Class#class_attribute` thread-safe.

### PR DESCRIPTION
**Pull request by sudoremo**
### Summary

This commit re-implements `Class#class_attribute` to be inherently thread-safe - without mutexes. The original implementation removed and re-added methods at runtime which could lead to severe concurrency issues (i.e. non-deterministic `NoMethodError` exceptions). This has been reported in issues #26758 and #14021.
#### API compliance

This implementation is a drop-in replacement for the existing functionality and features the same API and functionality as the original implementation. Rails' unit tests for this class still succeed without and adaptions required.
#### Performance

The new implementation manages to achieve safe concurrency without the use of Mutexes. This allows us to stay very fast on reads while heavily outperforming the original implementation on writes: The accessors generated by our proposal are about 15% slower on reads, but 1400% faster on writes than current class attribute accessors:

```
Performance benchmark of original implementation
================================================

reading low class attribute
                         10.277M (± 6.2%) i/s -     51.043M in   4.994305s
reading high class attribute
                          9.919M (± 8.6%) i/s -     49.075M in   5.006206s
writing low class attribute
                        782.276k (± 3.2%) i/s -      3.921M in   5.018056s
writing high class attribute
                        656.104k (± 5.3%) i/s -      3.279M in   5.013756s
r+w low class attribute
                        709.911k (± 6.0%) i/s -      3.574M in   5.054599s
r+w high class attribute
                        631.660k (± 4.1%) i/s -      3.164M in   5.017757s
    reading instance      2.970M (± 6.7%) i/s -     14.789M in   5.016777s
    writing instance     11.209M (± 4.4%) i/s -     55.922M in   4.999569s
```

```
Performance benchmark of our new implementation
===============================================

reading low class attribute
                          8.729M (± 8.0%) i/s -     43.365M in   5.018455s
reading high class attribute
                          9.057M (± 4.7%) i/s -     45.203M in   5.007582s
writing low class attribute
                         11.149M (± 5.2%) i/s -     55.583M in   5.001258s
writing high class attribute
                         10.979M (± 6.3%) i/s -     54.785M in   5.013769s
r+w low class attribute
                          6.852M (± 4.2%) i/s -     34.372M in   5.026380s
r+w high class attribute
                          6.952M (± 3.1%) i/s -     34.852M in   5.018324s
    reading instance      6.881M (± 4.0%) i/s -     34.478M in   5.021660s
    writing instance      9.055M (± 4.8%) i/s -     45.245M in   5.009464s
```

The benchmarking has been performed using [this script](https://gist.github.com/remofritzsche/ac164943975df102af6798ece234eb40).
#### Implementation details

As stated above, the key principle of this new implementation is not to dynamically remove and re-add methods at runtime. For performance reasons, we're using `class_eval` instead of `define_singleton_method` and `define_method` which provides a vast improvement in speed.
#### Reproducibility

Issue #26758 links [a script](https://gist.github.com/kalsan/cdecebb51830075af7bfdc058a4de1a1) which is able to reproduce the concurrency issues of the original implementation. It can only be reproduced in a jRuby environment. We reckon this is because of MRI's `GIL` behavior. The same test consistently succeeds on our implementation.

### CODE REVIEW

**Comment by remofritzsche** [comment]
We're currently working on the broken tests.

**Comment by remofritzsche** [comment]
We've now revised the implementation and think it now works as expected. A lot of the tests still fail though. As this is my first PR for Rails, I'm not quite sure what the problem is. The tests seem to fail on `master` as well. Should I have created the PR / branch based on one of the stable branches instead of against the master branch? And if so, how would I proceed?

And is our implementation generally feasible? We're absolutely relying on Rails to be thread-safe and need to eliminate the concurrency issues as quickly as possible so we really hope this comes through.

Thanks a lot for your help.

**Comment by matthewd** [comment]
Master seems fine: https://travis-ci.org/rails/rails/builds/166888838

And random sampling of the failures suggests they're in things that specifically use `class_attribute`, so I find it hard to imagine they're coincidental.

While I'd be fascinated to see a benchmark reflecting the change, `ObjectSpace.each_object(Class)` is not an acceptable solution to any problem. 

As with previous related issues, I'm curious about your use case which necessitates changing these pseudo-global values at (multi-threaded) runtime, but have no particular objection-in-principle to making this safe. It does need to keep working, though.

**Comment by remofritzsche** [comment]
Thanks a lot for your answer.

> And random sampling of the failures suggests they're in things that specifically use 
> class_attribute, so I find it hard to imagine they're coincidental.

We'll have a look at it for sure. But in errors like https://travis-ci.org/rails/rails/jobs/167111533, I can hardly imagine it has something to do with our change. When checking out the master, it succeeded on my local rails development kit. But I'll verify this again to be absolutely sure.

> While I'd be fascinated to see a benchmark reflecting the change, 
> ObjectSpace.each_object(Class) is not an acceptable solution to any problem.

We changed our code to using `ObjectSpace.each_object` out of a bare necessity as (this test)[https://github.com/rails/rails/blob/master/activesupport/test/executor_test.rb] (method `test_class_serial_is_unaffected`) fails in our original (much faster) implementation because we're inherently creating singleton classes by calling `singleton_class` in the instance attribute setter. Would it be an option to change this test case, or do you see any other workaround?

> As with previous related issues, I'm curious about your use case which necessitates 
> changing these pseudo-global values at (multi-threaded) runtime, but have no particular 
> objection-in-principle to making this safe. It does need to keep working, though.

The thing is, these concurrency issues happen even in Rails itself. We are using `class_attribute` ourselves quite heavily, but even without our tests still occasionally fail with exceptions that originate from Rails. Unfortunately, we couldn't create an isolated Rails app to reproduce these problems though as the concurrency issue only appears in very specific constellations.

So we'll make sure the other tests pass as good as we can and would love to hear your opinion on the executor test and whether there would be an alternative solution to that. But we strongly feel that removing and re-creating static methods at runtime and without any locking (the current implementation) is not the way to go and inevitably prone to concurrency issues.

Thanks a lot for your help and insights.

**Comment by pixeltrix** [comment]
Had a bit of a look at this today - we're using `class_attribute` for storing callbacks in `ActiveSupport::Callbacks` and even if we're not setting callbacks at runtime (someone maybe?) then redefining all those methods in tests must make the suite run slower than it should.

The main issue with the singleton class is that we support doing `object.singleton_class.setting = value` - something which I wasn't aware of and seems of little value as you have instance level writers anyway and don't know anyway of turning that singleton class into another object. If we remove the support for that the implementation becomes simple again - the `object.singleton_class.setting` syntax doesn't appear to have been document and it was added six years ago.

**Comment by matthewd** [comment]
The linked issues have been resolved by #29233

**Pull request closed without merging**
