### PR TITLE
Add Enumerable#index_with.

### PR DESCRIPTION
**Pull request by kaspth**
In the app I'm working on I've wished that index_by had a buddy that would
assign the hash value instead of the key multiple times.

Enter index_with. Useful when building a hash from a static list of
symbols. Before you'd do:

```ruby
POST_ATTRIBUTES.map { |attr_name| [ attr_name, public_send(attr_name) ] }.to_h
```

But now that's a little clearer and faster with:

```ruby
POST_ATTRIBUTES.index_with { |attr_name| public_send(attr_name) }
```

It's also useful when you have an enumerable that should be converted to a hash,
but you don't want to muddle the code up with the overhead that it takes to create
that hash. So before, that's:

```ruby
WEEKDAYS.each_with_object(Hash.new) do |day, intervals|
  intervals[day] = [ Interval.all_day ]
end
```

And now it's just:

```ruby
WEEKDAYS.index_with([ Interval.all_day ])
```

It's also nice to quickly get a hash with either nil, [], or {} as the value.

### CODE REVIEW

**Review by rafaelfranca — APPROVED** [review]

**Comment by jonathanhefner** [comment]
I've also needed this method on numerous occasions, but I named it [index_to](http://www.rubydoc.info/gems/casual_support/Enumerable:index_to).  What do you think of that name?

Also, for the last code snippet, I think you meant `WEEKDAYS.index_with { [ Interval.all_day ] }`, yes?

**Comment by albertoalmagro** [comment]
I like it, 👍

**Comment by khiav223577** [comment]
Wanna to have this method in ruby too! :+1:

**Comment by jonathanhefner** [comment]
@kaspth  Thank you for your response!  Even though it's too late to change, I still want to defend my name choice. 😉   The connection between `index_by` and `index_to` is like the connection between "a letter written by someone" and "a letter written to someone."  There is an implication of an arrow--in the case of a letter, the arrow from the writer to the reader; in the case of a `Hash`, the arrow from the key to the value.

Also, to me, `index_with` sounds more like an alias of `index_by`.  For example, I would have guessed `["abc"].index_with(&:upcase)` creates the index keys using `upcase`.

Either way, it's nice to have this in Rails.

**Comment by mcary** [comment]
I'm with @jonathanhefner: `index_with` sounds synonymous to `index_by`.  My first impression when I read the sample code is that I expect the block after the "with" to generate the index, not the value.

If this goes to Ruby, I could imagine one of these method names being clearer: 
* `index_for`
* `map_to`
* `with_values`
* `indexing`
* `indexing_values`
* `index_of`

`index_of` and `index_for` seem to have a clearer relationship to `index_with`, but `index_of` in some languages means what `Array#index` means in Ruby, so that's a potential source of confusion.  `indexing_values` is a bit long.  And `indexing` sounds more declarative than imperative, which might be confusing.  Same for `index_to` (suggested above).

`Proc#to_h(enumerable)` might be another way of generating an Hash from an enumerable and a proc, but using `proc` with a block is not as concise as passing a block to an Enumerable method, and maybe really the Enumerable should contain arrays of arguments rather than assuming only one argument...

**Comment by vaibhavatul47** [comment]
I agree with @mcary, that `index_with` gives an impression that the values from block will be used as keys in hash rather than values in hash. IMO, `map_to` is a great suggestion since:
1.  it describes the intention of what we want to achieve, not how its implemented.
2. its short and concise

**Comment by kaspth** [comment]
@jonathanhefner it's only too late once we've shipped Rails 6. At least I'm happy to keep going on this.

I'm still not on board with the `_to` versions. `index_to` makes me go: to whom? And I find a pneumonic like "index by key" and "index with value" just as obvious. `_with` wins because it flows better. `index_with_values` is closer and clearer, but then I don't mind some conciseness in the vein of select/collect/reject (note the similarity in wording there as well).

I can see how it sounds like a straight alias though.

**Comment by reggieb** [comment]
Would a better solution be to modify `.to_h` so that it takes a block which modifies the values of the resulting hash. Look at this example:

```ruby
class HashyArray < Array
  def to_h
    hash = if all? {|i| i.kind_of?(Array) && i.length == 2}
              super
            else
              Hash[self.map {|x| [x,x]}]
            end
    return hash unless block_given?
    hash.transform_values! {|v| yield(v)}
  end
end
```
With that modification the current behaviour still works:
```ruby
array = HashyArray.new([[:a, 1], [:b, 2]])
array.to_h  # => {:a=>1, :b=>2}
```
But if you pass a block, the block modifies the values:
```ruby
array = HashyArray.new([[:a, 1], [:b, 2]])
array.to_h { |v| v * 2 } # => {:a=>2, :b=>4}
```
If you just pass in a simple array, the resulting hash is each element as both key and value:
```ruby
array = HashyArray.new([1, 2, 3])
array.to_h # => {1=>1, 2=>2, 3=>3}
```
Then if you add a block:
```ruby
array = HashyArray.new([1, 2, 3])
array.to_h {|v| v * 2} # => {1=>2, 2=>4, 3=>6}
```

**Comment by reggieb** [comment]
On review - perhaps the main problem isn't the inability to pass in a block to `to_h`, but its behaviour with a simple array. If this was the normal behaviour for `array.to_h`:
```ruby
[1,2,3].to_h # => {1 => 1, 2 => 2, 3 => 3}
```
And the hash pair behaviour was just a special case:
```ruby
[[:a, 1], [:b, 2]] # => { a: 1, b: 2}
``` 
Then the `index_with` behaviour could be achieved with:
```ruby
hash = [1,2,3].to_h
hash.transform_values { |v| v * 2 } # => { 1 => 2, 2 => 4, 3 => 6 }
```
Which I think is easier to understand. It would also then be just as simple to modify the keys rather than the values:
```ruby
hash.transform_keys { |k| (k + 96).chr.to_sym } # => {a: 1, b: 2, c: 3}
```

**Comment by saraid** [comment]
I've always had this named `Array#expand` in my personal code:

```ruby
%w(one two three).expand(&:upcase)
=> {"one"=>"ONE", "two"=>"TWO", "three"=>"THREE"}
```

Admittedly has no relation to any of the other proposals, but I find it far more intuitive than `#index_with`.

**Comment by sj26** [comment]
Careful, these are not equivalent:

> ```ruby
> WEEKDAYS.each_with_object(Hash.new) do |day, intervals|
>   intervals[day] = [ Interval.all_day ]
> end
> ```
> 
> And now it's just:
> 
> ```ruby
> WEEKDAYS.index_with([ Interval.all_day ])
> ```

The difference being the first constructs a new array instance for each value of the hash, while the second uses the same array instance for each value. If you mutate this value, like appending new Interval instance to one of the weekday arrays, then they will cause different results. (I've hit this bug before. 😅)

In the first example, if assigned to `intervals`, and we assume `WEEKDAYS` is `['Monday', 'Tuesday', ...]`, and give `Interval` an arbitrary argument to `#new` to differentiate, the following will work as expected:

```ruby
intervals['Monday'] << Interval.new(1)
# intervals['Monday'] == [Interval.all_day, Interval.new(1)]

intervals['Tuesday'] << Interval.new(2)
intervals['Tuesday'] << Interval.new(3)
# intervals['Tuesday'] == [Interval.all_day, Interval.new(2), Interval.new(3)]
```

But in the second case:

```ruby
intervals['Monday'] << Interval.new(1)
# intervals['Monday'] == [Interval.all_day, Interval.new(1)]

intervals['Tuesday'] << Interval.new(2)
intervals['Tuesday'] << Interval.new(3)
# intervals['Tuesday'] == [Interval.all_day, Interval.new(1), Interval.new(2), Interval.new(3)]
# but also:
# intervals['Monday'] == [Interval.all_day, Interval.new(1), Interval.new(2), Interval.new(3)]
# and every other value, too.
```

**Pull request merged**
