### PR TITLE
Replace usage of `Array#&` with `Array#intersect?` for efficiency

### PR DESCRIPTION
**Pull request by ricardotk002**
### Motivation / Background

`Array#intersect?` was introduced in Ruby 3.1.0 and it's more efficient and useful when the result of the intersection is not needed as the benchmarks in the next sections show. It's also better for clarity and readability.

https://bugs.ruby-lang.org/issues/15198

### Detail
`Array#intersect?` is equivalent to `!(a1 & a2).empty?`, this PR replaces cases like this and other similar ones where the result is only a predicate.

### Additional information

Benchmark:

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", path: "./"
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"
  gem "benchmark-ips"
end

require "active_support"

SCENARIOS = [
  [(1..100).to_a, (90..200).to_a],    # Case 1
  [("a".."m").to_a, ("j".."z").to_a], # Case 2
  [(1..100).to_a, (101..200).to_a],   # Case 3
]

SCENARIOS.each_with_index do |values, n|
  puts
  puts " Case #{n + 1} ".center(80, "=")
  puts
  Benchmark.ips do |x|
    x.report("Array#?") { !(values[0] & values[1]).empty? }
    x.report("Array#intersect?") { values[0].intersect?(values[1]) }
    x.compare!
  end
end
```

Results:

```
==================================== Case 1 ====================================

ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin21]
Warming up --------------------------------------
             Array#?    34.221k i/100ms
    Array#intersect?    62.035k i/100ms
Calculating -------------------------------------
             Array#?    343.119k (± 1.1%) i/s -      1.745M in   5.087078s
    Array#intersect?    615.394k (± 1.1%) i/s -      3.102M in   5.040838s

Comparison:
    Array#intersect?:   615393.7 i/s
             Array#?:   343119.4 i/s - 1.79x  slower

==================================== Case 2 ====================================

ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin21]
Warming up --------------------------------------
             Array#?   103.256k i/100ms
    Array#intersect?   185.104k i/100ms
Calculating -------------------------------------
             Array#?      1.039M (± 1.3%) i/s -      5.266M in   5.066847s
    Array#intersect?      1.873M (± 1.6%) i/s -      9.440M in   5.041740s

Comparison:
    Array#intersect?:  1872932.7 i/s
             Array#?:  1039482.4 i/s - 1.80x  slower

==================================== Case 3 ====================================

ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin21]
Warming up --------------------------------------
             Array#?    37.070k i/100ms
    Array#intersect?    41.438k i/100ms
Calculating -------------------------------------
             Array#?    370.902k (± 0.8%) i/s -      1.891M in   5.097584s
    Array#intersect?    409.902k (± 1.0%) i/s -      2.072M in   5.055185s

Comparison:
    Array#intersect?:   409901.8 i/s
             Array#?:   370902.3 i/s - 1.11x  slower
```

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [ ] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by Earlopain** [comment]
There's also a rubocop rule for this https://docs.rubocop.org/rubocop/cops_style.html#stylearrayintersect

**Comment by rafaelfranca** [comment]
Does it make any noticeable different in the performance of the methods you changed? We don't accept changes based on microbenchmarks because they are just cosmetic and we don't accept cosmetics changes.

**Comment by Cosmo** [comment]
I would also argue that `x.intersect?(y)` reads better than `!(x & y).empty?`

**Comment by byroot** [comment]
None of these call sites are anywhere near a performance hotspot, so like Rafael said, the performance argument is a bit moot here.

But I'll merge this one because I indeed think it makes the code more readable, which was the intent of that Ruby feature, and in this particular case I find it valuable.

**Comment by ricardotk002** [comment]
Sorry about the late response here. I've been trying to identify any hot paths to benchmark them but I wasn't able to isolate the functionality enough to get conclusive results. I do agree it helps with readability. Thank you all for your time reviewing it!

**Pull request merged**
