### PR TITLE
Maintain html_safe? on sliced HTML safe strings

### PR DESCRIPTION
**Pull request by itsbagpack**
### Summary

This change allows for an HTML safe string to remain HTML safe even when accessed via a range. 

**Before**

```ruby
string = "<div>test</div>".html_safe
substring = string[-1..1]
substring.html_safe? # => false
```

**After**

```ruby
string = "<div>test</div>".html_safe
substring = string[-1..1]
substring.html_safe? # => true
```

cc @tenderlove @no-itsbackpack

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Thanks! Can you add a CHANGELOG entry?

**Comment by tenderlove** [comment]
The railties failures seem unrelated, so I'll merge this.

**Comment by rafaelfranca** [comment]
I thought that I already did 🤦‍♂️. Thanks

**Comment by SampsonCrowley** [comment]
I'm coming way late to the party but how is this not extremely dangerous?

**Comment by SampsonCrowley** [comment]
`"<wholetag>".slice[-1..-1]` would then give you a closing tag that's marked as html_safe to inject. is this not a problem because it would have to be developer error to use that piece anyways?

**Comment by flavorjones** [comment]
@SampsonCrowley I think the assumption here is that the string being operated on is marked "html safe" when it has been html-sanitized (for example, by `ActionView::Helpers::SanitizeHelper#sanitize`) or escaped (for example, by `ERB::Util.html_escape`).

In that case, any comments or dangerous tags (like `<script>`) will have been removed or escaped during sanitization, and so while a slice may not be well-formed, it's not malicious. If you are able to generate a string that, once it's been sanitized and marked safe, would have a malicious substring in it, please open an issue so we can discuss?

As a starting point, here's a script to generate two different "safe" HTML strings:

```ruby
#! /usr/bin/env ruby

require "action_view"
require "active_support"

class Sanitizer
  include ActionView::Helpers::SanitizeHelper
end

class Escaper
  include ERB::Util

  def escape(string)
    html_escape(string)
  end
end

original = %{<div><script>alert("xss")</script></div>}
# => "<div><script>alert(\"xss\")</script></div>"

safe = Sanitizer.new.sanitize(original)
# => "<div>alert(\"xss\")</div>"
safe.html_safe? # => true

safe = Escaper.new.escape(original)
# => "&lt;div&gt;&lt;script&gt;alert(&quot;xss&quot;)&lt;/script&gt;&lt;/div&gt;"
safe.html_safe? # => true
```

**Comment by SampsonCrowley** [comment]
@flavorjones sorry my original reply was missing the part marking the string as html_safe

Taking the original original comment as an example:

In the behavior before this PR: `str = "<script>".html_safe` would _not_ be escaped, and it shouldn't be because it is being explicitly marked as an actual html "safe" string, i.e. any unsafe characters have _already_ been properly formatted

*But* if you were to then call slice on it, `str[-1..-1]`, the previous behavior was that the string was then decidedly _not_ assumed safe for direct consumption because any html may no longer be properly formatted or escaped. In the previous call you would now have just a closing carrat `">"`, if you know as a developer that the string is still safe you could mark it as such, but otherwise it was previously assumed to no longer be safe for direct consumption

*Now*

`str[-1..-1]` will give you a closing carrat that is _still_ marked html "safe", even though it's not the original structure and may be improperly formatted or contain partial html.

So I don't understand how it's is safe to assume by default that a string that has been sliced from an html_safe string is _still_ html safe just because it _was_ html safe in its original full string

Or maybe I'm just misunderstanding the use case

**Pull request merged**
