### PR TITLE
Remove ActiveSupport::TimeZone.all cache

### PR DESCRIPTION
**Pull request by maclover7**
By removing the cache, this will finally solve #7245, which is still an
issue on Rails master. If there is a way to bust the cache or to add a
key to the `Concurrent::Map`, I'd be okay with that solution too.

ping @rafaelfranca

### CODE REVIEW

**Comment by david-crowder** [comment]
Just ran into this issue today and can verify that the proposed fix does indeed update the behavior to what one would expect.

**Comment by sgrif** [comment]
Given that this is potentially expensive, I'd rather we busted the cache manually when needed.

**Comment by maclover7** [comment]
By manually, do you mean provide an option to the user to do this? We could do something like this: 

```ruby
def all(reload = false)
  if reload
    @zones = zones_map.values.sort
  else
    @zones ||= zones_map.values.sort
  end
end

ActiveSupport::TimeZone.all(true) # <-- reload boolean
```

**Comment by sgrif** [comment]
No, I mean in the cases where the cache is invalid, we should bust it (I
believe `[]` is the only method that can invalidate it currently)

**Pull request closed without merging**
