### PR TITLE
Update Dev Container

### PR DESCRIPTION
**Pull request by andrewn617**
### Motivation / Background

Just a few small updates to the Dev Container setup for this repo.

### Detail

This Pull Request changes:
- use Ruby 3.3.3 as the default ruby version
- add default-mysql-client. I believe this was missed when switching to use the rails org ruby image

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by yahonda** [comment]
As far as I understand `default-mysql-client` is kind of a virtual package to install MySQL or MariaDB client for Ubuntu or Debian.

default-mysql-client of Debian "bookworm" installs mariadb-client, that is already added in this Dockerfile.

https://packages.debian.org/bookworm/default-mysql-client

**Comment by yahonda** [comment]
Ruby 3.3.3 has a known issue that does not install net-pop gem so the workaround to add this entry to applications Gemfile is required.

https://github.com/ruby/net-pop/issues/26#issuecomment-2176572171

```
# Needed until Ruby 3.3.4 is released https://github.com/ruby/ruby/pull/11006
gem 'net-pop', github: 'ruby/net-pop'
```

**Comment by yahonda** [comment]
https://github.com/rails/rails/pull/52293 has been opened.

**Comment by andrewn617** [comment]
@yahonda Thanks for the info about the the mariadb package. I missed that.

And sure I will close in favour of the other PR.

**Pull request closed without merging**
