### PR TITLE
Make rake db tasks work properly with sqlite when run not from the Rails root path.

### PR DESCRIPTION
**Pull request by Exoth**

### CODE REVIEW

**Comment by senny** [comment]
@Exoth is this patch still necessary? I just created a new app from `master` and did:

```
$ cd tmp
$ ../bin/rake db:migrate
$ ../bin/rake db:structure:dump
$ ../bin/rake db:structure:load
```

and it seemed to work fine. Maybe I didn't understand the issue correctly and used a wrong way to reproduce.

**Comment by Exoth** [comment]
The problem is for engines, not just apps. And I can still reproduce it as for Rails 4.2.1.

**Comment by Exoth** [comment]
I mean it probably brought me some problems in the apps too (it was long time ago, can't really remember), but the reproduction scenario I posted here https://github.com/rails/rails/pull/11979 still works.

**Comment by Exoth** [comment]
So you can be in some of the folders inside the rails root path (like you did with tmp), but you can't be outside, like if you create an engine, and run this rake take from the engine root, not dummy root.

**Comment by sgrif** [comment]
@Exoth Can you give us an example that demonstrates the problem for engines?

**Comment by Exoth** [comment]
The scenario to reproduce the problem is here: https://github.com/rails/rails/pull/11979

**Pull request closed without merging**
