### PR TITLE
Remove empty section from the instrumentation guides [ci skip]

### PR DESCRIPTION
**Pull request by santib**
### Summary

There is an almost empty section here https://guides.rubyonrails.org/active_support_instrumentation.html#rails-framework-hooks which looks a bit weird. 

I thought of having `Rails framework hooks` be the parent section for each of the Rails "components" (ActionController, etc) but given the length of each "component", then I changed my mind and thought that it might be better to just remove the title of the empty section but keep its message.

image

### CODE REVIEW

**Comment by p8** [comment]
Hmm, that does look weird.

I think I'm more in favor of making it the parent section.
The Rails Framwork Hooks title adds context. Only having "ActionController" doesn't say much by itself.
It also makes the last title, Creating custom events, stand out more.

We also do this for the Detailed Assocation Reference example: https://guides.rubyonrails.org/association_basics.html#detailed-association-reference

**Comment by jonathanhefner** [comment]
> I thought of having `Rails framework hooks` be the parent section for each of the Rails "components" (ActionController, etc) but given the length of each "component"

Hmm, I think I prefer that approach.  Compare the sidebars:

| "Rails framework hooks" removed | Subsections converted |
| --- | --- |
| remove-section | convert-subsections |

Also, there is [a link](https://github.com/rails/rails/blame/main/guides/source/active_support_instrumentation.md#L22) to the "Rails framework hooks" section at the start of the guide.

**Comment by santib** [comment]
@p8 @jonathanhefner Just made the suggested changes. Is there any way to preview my PR so to make sure that everything is fine? Also, all the anchors should remain unchanged AFAIK so it'd be just checking that the new table of contents looks good, right?

**Comment by jonathanhefner** [comment]
> Is there any way to preview my PR so to make sure that everything is fine?

If you run `rake guides:generate:html` in the `guides` directory, it will render HTML files into `guides/output`.

> Compared to your screenshot I left "Exceptions" outside of the `Rails framework hooks` section since I guess it also applies to custom events, doesn't it?

Yup, you're right, "Exceptions" should be its own section. :+1:

**Comment by jonathanhefner** [comment]
Thank you, @santib and @p8!

**Comment by zzak** [comment]
Looks like we ended up with re-shuffling things under the "Rails framework hooks" instead of removing it?

**Pull request merged**
