### PR TITLE
Replace `method_source` gem with stdlib equivalent

### PR DESCRIPTION
**Pull request by brasic**
The `method_source` gem was added to railties in https://github.com/rails/rails/pull/19216. It was used to determine the last line number of a given test method to support running tests by line number. But this is not something that requires an external dependency: Ripper can do this easily, and it has the added advantage of not using [repeated calls to `eval`](https://github.com/banister/method_source/blob/81d039c966ffd95d26e12eb2e205c0eb8377f49d/lib/method_source/code_helpers.rb#L66-L80) to do it.

Drop `method_source` and replace it with a simple handler for Ripper's `on_def` parser event.

I don't believe that there are any mainstream rubies at this point that can run Rails and don't support Ripper but correct me if I'm mistaken.

### CODE REVIEW

**Review by byroot — APPROVED** [review]
LGTM, however I don't think it's really worth giving it its own file and unit testing it.

Can you move that class inside `test_unit/runner.rb` and drop the tests? (assuming features relying on `definition_for` are already tested)

**Comment by brasic** [comment]
@byroot thanks, done!

> assuming features relying on definition_for are already tested

For the most part this is true although I added one test for functionality that I didn't see exercised (using multiple line number test selection syntax with `def test_` syntax)

**Comment by byroot** [comment]
Looks great, thank you!

I'll merge on green.

**Comment by rafaelfranca** [comment]
This doesn't work with tests defined using `test`. `on_def` will not run on those since there isn't a `def` from the in the source file. Reverting.

**Comment by rafaelfranca** [comment]
> I guess there must have been missing test coverage for that and I didn't consider it.

Yeah, existing test wasn't failing but I updated it in the revert PR to fail with those code changes.



> I'll retool and open a new PR that covers the test macro.

Thank you! Thank would be great.

**Comment by brasic** [comment]
I spent a long time sitting on a half-finished version of this, but I've finally opened https://github.com/rails/rails/pull/46644.

**Pull request merged**
