### PR TITLE
Change .format regex to allow for .format to be in the middle

### LINKED ISSUE #29402: :format in routes gets appended to url even if it's not there
### Steps to reproduce

Make route with :format in middle of string, observe format also appended to url
Testcase: https://gist.github.com/Voker57/8cad302dfb1bf14fefca5d3c7950eeb0

### Expected behavior
only :format is subsituted with format

### Actual behavior
format also gets appended to uri

### System configuration
**Rails version**: 5.1.1

**Ruby version**: 2.4.1

### PR DESCRIPTION
**Pull request by Voker57**
Fixes #29402

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Thank you for the pull request but why support the format in the middle of the URL? Any URL can be rewritten to accept the format in the end of the url. In your example in the issue `foo.com/test.json/bar` can be rewritten to be `foo.com/test/bar.json`. Why should we change the framework making it more complex and opening more edge cases in the API?

**Comment by Voker57** [comment]
I believe currently framework is supposed to support .format in middle of URI. So my PR doesn't change anything, it fixes a bug. Either docs should say that :format is only allowed at the end or :format should properly work anywhere. Not advocating for either, just submitting a patch for a bug that breaks my application developed with earlier version of rails.

**Comment by gmcgibbon** [comment]
Skimming through the guides, I can't see an example that would lead someone to believe that `:format` can/should be placed in the middle of a route path. Is there a use-case where this is needed? I think adding clarification to the docs would be a better answer than having to support this potentially unnecessary edge case.

**Comment by Voker57** [comment]
I can't see an example that would imply :format is special and can't be placed anywhere like all other :interpolations.

Usecase is using non-standard route model, I for example use /log/xml instead of log.xml. This might not be officially suggested but still should be either supported or special :format behavior documented.

**Comment by rafaelfranca** [comment]
If we want to support this we will need tests for this feature.

**Pull request closed without merging**
