### PR TITLE
Attend to options[default] even when include_blank

### PR DESCRIPTION
**Pull request by jkopczyn**

### CODE REVIEW

**Comment by jkopczyn** [comment]
Updated tests to match new behavior. This seems to me to be obviously superior, and does not appear to bring it out of line with any behavior elsewhere.

**Comment by jkopczyn** [comment]
This would address #23091

**Comment by vipulnsward** [comment]
@jkopczyn CI failed.

**Comment by jkopczyn** [comment]
That test has literally no connection to code I touched in this PR.

**Comment by vipulnsward** [comment]
@jkopczyn got it. You can probably do a rebase.

**Comment by jkopczyn** [comment]
Alright, tried that. I'm not enormously familiar with CI so I'm not sure what might affect it.

**Pull request closed without merging**
