### PR TITLE
Ensure references creates id before type

### PR DESCRIPTION
**Pull request by al2o3cr**
Prior to https://github.com/rails/rails/commit/d26704a15f88d384dd282425daa832affdb5f8c1, using `references` with `polymorphic: true` in a migration created an id column before creating the  corresponding type column.

After that commit, the order is reversed.

This PR restores the previous order and adds a test to prevent regressions.

I'm not aware of any production impact for the column ordering change, but it broke the schema linting on github/github.

/cc @tenderlove @eileencodes

### CODE REVIEW

**Review by tenderlove — APPROVED** [review]

**Comment by al2o3cr** [comment]
@tenderlove CI found something I missed, let's hope this new push fixes it :)

**Comment by al2o3cr** [comment]
Added some tweaks to ensure the changes from https://github.com/rails/rails/commit/3fea23171248fb419925501492d174a1ae419ff8 and https://github.com/rails/rails/pull/14143 aren't disturbed by this.

**Comment by kamipo** [comment]
I'm curious about the purpose of linting the column order in github/github.

I personally think there is no benefit to change the column order in Rails 6.0.

**Comment by al2o3cr** [comment]
@kamipo Github currently runs migrations from an empty DB in CI and verifies that the expected structures are produced, as old migrations need to be runnable for on-premises installs that only update periodically. We're currently working to reduce the number of migrations we keep around (nobody needs ancient ones like `002_private_repos.rb` anymore) but that work also relies on the linting to ensure correctness.

I'm not certain what the significance of column order is, but it's clearly important for *somebody* (thus column options like `after` and `first`). The order was reversed in the 4.2 -> 5.0 upgrade without a changelog entry or any other notice.

**Comment by kamipo** [comment]
Isn't enough implementing migration compatibility for 4.2?

| version | column order             | index column order       |   
|---------|--------------------------|--------------------------|
| 4.1     | `["foo_id", "foo_type"]` | `["foo_id", "foo_type"]` |
| 4.2     | `["foo_id", "foo_type"]` | `["foo_type", "foo_id"]` |
| 5.0     | `["foo_type", "foo_id"]` | `["foo_type", "foo_id"]` |
| 5.1     | `["foo_type", "foo_id"]` | `["foo_type", "foo_id"]` |
| 5.2     | `["foo_type", "foo_id"]` | `["foo_type", "foo_id"]` |

That was already made in the latest three release series.
So I don't think there is any benefit to change the column order in Rails 6.0 for most Rails 5 users.

**Comment by matthewd** [comment]
> That was already made in the latest three release series.

+1. We _might've_ considered changing a few versions ago (though I'm not sure how much it matters), but at this point, the current behaviour is the well-established one: I don't see how any argument that it _does_ matter could overcome the fact that it's now been this way for years.

**Comment by al2o3cr** [comment]
@matthewd FWIW, passing `after:` to `references` produces the opposite column order on 5.2, as tested [here](https://github.com/rails/rails/blob/d48f4ddfc8dd38b65f7a040c5c9c7d1468114d2d/activerecord/test/cases/migration/column_positioning_test.rb#L58) for instance.

"That bug's been there a long time" doesn't feel persuasive to me, especially since it was introduced with zero announcement / discussion / etc by a refactoring of code that lacked test coverage.

As an alternative, I can split out the refactoring & new test added here, leaving the existing behavior with a guard against future regressions and a clear extension point to override to get the old behavior for us at Github.

**Comment by matthewd** [comment]
> "That bug's been there a long time" doesn't feel persuasive

Of course not; a bug is a bug. "That arbitrary behaviour has been there a long time" is rather different, though. The previous ordering was also "introduced with zero announcement / discussion / etc, by [addition] of code that [clearly] lacked test coverage".

In fact, I can go further, and declare that the change was itself a bug fix: the natural order is [type, id] because that matches the [actually important] order in the index. 4.2 intentionally changed the index order, and inadvertently failed to change the table order to match; 5.0 (consciously or not) corrected that oversight.

Although we don't generally version bugfixes, if you really want to restore the behaviour *for 4.2 migrations* as @kamipo suggested, that seems unobjectionable.

I'm happy to lock in the current behaviour with a test; I'd have to look at the refactoring on its own merits.

But wouldn't it be easier to solve your internal problem by changing the affected migrations to define the two columns individually? It's clearly safe to do so, because you have a tool that will ensure your changes produce the same schema.

**Comment by al2o3cr** [comment]
@matthewd If there's a "natural order", then using `after:` results in the "wrong" order.

**Comment by matthewd** [comment]
Yeah; presumably that ("using `after:` results in the opposite order to normal") would've been true on 4.2 as well? That does sound like a possibly-compelling argument for your refactoring.

**Comment by al2o3cr** [comment]
@matthewd In 4.2, passing `after` to `references` meant it was passed to both the ID and type columns, resulting in type before ID. [ref](https://github.com/rails/rails/blob/4-2-stable/activerecord/lib/active_record/connection_adapters/abstract/schema_definitions.rb#L325)

The refactor in https://github.com/rails/rails/commit/d26704a15f88d384dd282425daa832affdb5f8c1 introduced a bug in 5.0.0, reported as https://github.com/rails/rails/issues/30496 and fixed in https://github.com/rails/rails/commit/3fea23171248fb419925501492d174a1ae419ff8 (released in 5.2) which also added tests that verified the column order was ID then type.

**Comment by eileencodes** [comment]
We ended up handling this at GitHub by deleting old migrations.

**Pull request closed without merging**
