### PR TITLE
fix #23779 fixing to use raw post data correctly on test_case

### LINKED ISSUE #23779: Test case use RAW_POST_DATA but it is not used anywhere
Hello guys,

Using rspec-rails on my project, I noticed a strange behavior, 

When I make a post sending a hash object like:

`{id: 1}`

the number 1 will be converted to String.

It doesnt happens with Minitest only on RSpec.

please consider this script:

[https://gist.github.com/leonardoprg/d667920604659294b42f](https://gist.github.com/leonardoprg/d667920604659294b42f)

If you guys take a look on the line 50, when using .to_json and sending a string as parameter to post method, it will works correctly.

Swimming in the code I noted that:

1. The problem is at `actionpack/lib/test_case.rb`
2. RSpec use the method post at [test_case.rb#L519](https://github.com/rails/rails/blob/4-2-stable/actionpack/lib/action_controller/test_case.rb#L519)

3. minitest doesn't use it.

The problem here is 
[test_case.rb#L598](https://github.com/rails/rails/blob/4-2-stable/actionpack/lib/action_controller/test_case.rb#L598
)

If RSpec try to send a string, it assume it will be a raw data (like an json object)  and set it to request env `RAW_POST_DATA`, Which is correctly.
but, the code that take care with this env var, is a middleware at:
[params_parser.rb#L42](https://github.com/rails/rails/blob/4-2-stable/actionpack/lib/action_dispatch/middleware/params_parser.rb#L42)

and it is never called, because the method on test_case just call the controller method as an plain object.

I will open a PR to correct this behaviour.

Regards,

### PR DESCRIPTION
**Pull request by leonardoprg**
This PR, is released to

[https://github.com/rails/rails/issues/23779](https://github.com/rails/rails/issues/23779)

Regards,

### CODE REVIEW

**Comment by leonardoprg** [comment]
@maclover7  Do you know why this PR doesn't launched Travis or github bot?

should I reopen this?

**Comment by maclover7** [comment]
Yeah -- try to close and reopen this.

**Comment by leonardoprg** [comment]
@maclover7  OK, thanks

works now. :+1:

**Comment by leonardoprg** [comment]
@maclover7  but don't assigned to anyone, some problem? or can keep it unassigned?

**Comment by rafaelfranca** [comment]
Does this issue happens in master branch? We need to check it before fixing an issue in 4-2-stable.

**Comment by leonardoprg** [comment]
@rafaelfranca  sorry about that, I will check if happens on master,

please disconsider this PR, I will open again after check it.

by the way,  do you guys have time to check this?

https://github.com/rails/rails/pull/23650

We need that to clean or code :) 

Regards,

**Comment by leonardoprg** [comment]
@rafaelfranca 
As mentioned here:

**Comment by rafaelfranca** [comment]
If we are not going to fix in rails 5 (what makes sense since we deprecated it) we should not change the behavior in rails 4.2 otherwise when you upgrade to Rails 5 you will get the previous behavior. That said I believe this is a won't fix. Thank you for the pull request

**Pull request closed without merging**
