### PR TITLE
Handle discarded connection pools when disabling query cache

### PR DESCRIPTION
**Pull request by casperisfine**
Initially reported at https://github.com/mperham/connection_pool/issues/173

If an application forks in the middle of a request of fork, it could cause the following error:

```
NoMethodError: undefined method `[]' for nil:NilClass
active_record/connection_adapters/abstract/connection_pool.rb:190:in `active_connection?'
```

### CODE REVIEW

**Review by rafaelfranca — APPROVED** [review]

**Comment by casperisfine** [comment]
There's some weird failures, I'll dig into them tomorrow.

**Comment by casperisfine** [comment]
@tisba could you share what your `fork` look like? e..g are you using `fork do` or just raw `fork` ?

**Comment by tisba** [comment]
We're using `Parallel.map(data, in_processes: 4)` (`parallel` gem, https://github.com/grosser/parallel, v1.22.1) from within a Sidekiq job. Looking at https://github.com/grosser/parallel/blob/v1.22.1/lib/parallel.rb#L528, I'd say it's using `Process#fork` with block. That's the only reference I could find in the gem regarding forking.

Let me know if this helps. I haven't spend much time yet to build a case to reproduce this issue, but can certainly try.

**Comment by casperisfine** [comment]
Hum, that's weird. I was talking with Matthew, and I'm not so sure about what is happening now, as the discard should only happen in the childrens, so we're kinda puzzled as how we get there.

A reproduction would certainly be nice.

**Comment by matthewd** [comment]
[Your backtrace](https://github.com/mperham/connection_pool/issues/173#issuecomment-1488465364) is consistent with what would happen if the main / forking process's connection pool(s) got discarded in the middle of execution.

But that's not supposed to happen. :confused:

The expected discard is here: https://github.com/rails/rails/blob/c15ee6e7b5065db3c46afa1f025b8e45f443604e/activerecord/lib/active_record/connection_adapters/pool_config.rb#L73

.. which only occurs in the forked child (which has a different PID from the one we've previously seen and stored):
https://github.com/rails/rails/blob/c15ee6e7b5065db3c46afa1f025b8e45f443604e/activesupport/lib/active_support/fork_tracker.rb#L41-L43

Can you confirm that the PID shown in the log (`3875249` in that example, though you'll obviously need to check it again with a fresh repro) is the main/root sidekiq process? 

Does it happen immediately / the first time the forking job is run, or after running okay for a while? 

Were you able to confirm that changing nothing but the `connection_pool` version is enough to break/fix it?

Assuming so, my only current speculation is that the `AS::ForkTracker#_fork` and new `ConnectionPool::ForkTracker#_fork` are conflicting in some way (despite them being trivial, nearly identical, and both prepended in a way that should allow them to stack perfectly). 

I have zero clue what that would entail -- even at the most extreme, I can't see how to break it even if you had a ConnectionPool instance whose construction block called Active Record. I'm only mentioning it in the hope it might help you find interesting places for putses, even though I don't even know what I'd be looking for at the moment.

One other specific thing you could check (again with no theory of why it would matter): does changing the order that `active_support/fork_tracker` and `connection_pool` are required [and thus, the order of the prepends] have any effect?

**Comment by tisba** [comment]
@matthewd I'll need some time, but will get back to your questions - hopefully with more data, and some code to reproduce.

**Comment by tisba** [comment]
Here is what I know so far:

* The problem did not occur again after we updated `net-http-persistent` to `4.0.2`
* We use forking very similar to what I posted [here](https://github.com/drbrain/net-http-persistent/pull/144#issuecomment-1490262509). The children are not actively using ActiveRecord themselves.
* During the incident, we had quite a bit of exception noise, duo to `Parallel::DeadWorker` (caused by dying worker process caused by `net-http-persisent`, see https://github.com/drbrain/net-http-persistent/pull/144).
* I am not entirely sure if the pid `3875249` is the parent, my guess is not (looking at our logs).
* From what I can reconstruct, the problem pretty much occurred right away when the code path that does the forking was invoked.

I tried for some time to build a minimal case to reproduce, but haven't had much success so far 😞

**Pull request closed without merging**
