### PR TITLE
Add migrations_paths option to model generator

### PR DESCRIPTION
**Pull request by gmcgibbon**
### Summary

Followup on https://github.com/rails/rails/pull/33760. Adds support for custom migrations path on `rails generate model`. Example:
```
bin/rails g model Room capacity:integer --migrations-paths=db/kingston_migrate
      invoke  active_record
      create    db/kingston_migrate/20180830151055_create_rooms.rb
```

r? @eileencodes 
/cc @rafaelfranca

### CODE REVIEW

**Comment by gmcgibbon** [comment]
This also fixes scaffold, I'll add a test case for this.

**Comment by eileencodes** [comment]
Looks good thanks!

**Comment by kaspth** [comment]
I'm curious why the user facing API is to pass the migration paths and not the simpler db name? 

Perhaps I'm extrapolating from the simple multi db database.yml with the primary database and then the animals.

But wouldn't it be easier to pass `--db=animals` and let Rails infer the migration paths from database.yml?

**Comment by eileencodes** [comment]
Let's change it to `--database` and have that lookup the database migrations paths from the configuration - assuming that the configuration is available to look it up from.

**Comment by gmcgibbon** [comment]
Sounds good, I'll get to work on it!

**Comment by spirobel** [comment]
I would have liked --migrations_paths more. For example discourse plugins live in their own directories without having their own db. https://github.com/discourse/discourse/tree/master/plugins/poll/db/migrate

**Pull request merged**
