### PR TITLE
Allow AC::Parameters as an argument to url_helpers

### PR DESCRIPTION
**Pull request by prathamesh-sonpatki**

### CODE REVIEW

**Comment by prathamesh-sonpatki** [comment]
@rafaelfranca I tried to fix https://github.com/rails/rails/issues/22832#issuecomment-168035633 here. But I will need some feedback whether this is the right place where we should add this check.

I added it here because due to `is_a? Hash` check, we were not passing `ActionController::Parameters` to `helper.call`.

**Comment by yui-knk** [comment]
Huge volume of warnings are raised :(
https://travis-ci.org/rails/rails/jobs/99959002
Can you remove these warnings? :heart_eyes: 

```
/home/travis/build/rails/rails/actionpack/lib/action_dispatch/routing/route_set.rb:288: warning: method redefined; discarding old extract_from_args
/home/travis/build/rails/rails/actionpack/lib/action_dispatch/routing/route_set.rb:288: warning: previous definition of extract_from_args was here
...
```

**Comment by prathamesh-sonpatki** [comment]
@yui-knk Fixed. Thanks :)

**Comment by rafaelfranca** [comment]
@prathamesh-sonpatki yes, it looks like the right place.

**Comment by prathamesh-sonpatki** [comment]
Thanks for confirming. I will add test cases.

**Comment by prathamesh-sonpatki** [comment]
@rafaelfranca Added test cases and CHANGELOG. Please review.

**Pull request merged**
