### PR TITLE
Stop deep duping query values of serialized attributes

### LINKED ISSUE #48652: ActiveRecord serialize stripping obj's attributes before sending the data to the serializer on rails 7.0.5
upgrading from rails **7.0.4.3** to **7.0.5** causes activerecord models with serialized params to break since the data sent to the serializer on **7.0.5** is now being passed to `deep_dup` before being sent to the serializer, and this makes activerecord objs passed inside the parameters to lose attributes.
this was changed on this commit [activerecord/lib/active_record/relation/predicate_builder.rb](https://github.com/rails/rails/commit/213972e1ef8b50d5a930fed52780846f674eb808#diff-b8fadd6d1ec091c30f94738b9b193b78ec90681790dd3a6aa79938b4dacbe904)

example of a case that this change is causing problems https://github.com/excid3/noticed/issues/296 

### Steps to reproduce
```ruby
#!/usr/bin/env ruby

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  gem 'rails', '= 7.0.5'
  # gem 'rails', '= 7.0.4.3'
  gem 'sqlite3'
  gem 'byebug'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :notifications do |t|
    t.json :params
  end

  create_table :comments do |t|
    t.string :body
  end
end

class DummyCoder
  def self.load(data)
    return if data.nil?
    puts "load"
    p data
    "dummy"
  end

  def self.dump(data)
    return if data.nil?
    puts "dump"
    p data
    raise "object has no id" if data[:comment].id.nil?
    "dummy"
  end
end

class Notification < ActiveRecord::Base
  serialize :params, DummyCoder
end

class Comment < ActiveRecord::Base
end

class TestWhereQueryWithSerializedParam < Minitest::Test
  def test_where_query_with_serialized_param
    comment = Comment.create(body: "1")
    notifications = Notification.where(params: {comment: comment}).last
    assert_equal notifications, nil
  end
end
```

### Expected behavior
calling Notification.where(params: {comment: comment}).last should not raise since the `data` variable on `DummyCoder.dump(data)`  method will have an id: `{:comment=>#<Comment id: 1, body: "1">}`

this was the behavior on rails 7.0.4.3 

### Actual behavior
calling Notification.where(params: {comment: comment}).last will raise since the `data` variable on `DummyCoder.dump(data)`  method wont have an id: `{:comment=>#<Comment id: nil, body: "1">}`
which is cause by this new change [activerecord/lib/active_record/relation/predicate_builder.rb](https://github.com/rails/rails/commit/213972e1ef8b50d5a930fed52780846f674eb808#diff-b8fadd6d1ec091c30f94738b9b193b78ec90681790dd3a6aa79938b4dacbe904)

### System configuration
**Rails version**: 7.0.5

**Ruby version**: 3.0.0

### PR DESCRIPTION
**Pull request by casperisfine**
Fix: https://github.com/rails/rails/issues/48652
Ref: https://github.com/rails/rails/pull/46048
Ref: https://github.com/rails/rails/issues/46044
Ref: https://github.com/rails/rails/pull/34303
Ref: https://github.com/rails/rails/pull/39160

This deep_dup was introduced to prevent the value stored in the query cache to be later mutated.

The problem is that `ActiveRecord::Base#dup` will return a copy of the record but with the primary key set to nil. One could argue that `#dup` shouldn't behave this way, but I think this ship has sailed (or has it?).

My initial fix was to instead call `type.cast` so that we'd dup serialized types in a more correct way. However there is a test that explictly ensure this doesn't happen: https://github.com/rails/rails/pull/39160

The reason isn't 100% clear to me, but if I get it correctly, it's to avoid a potentially costly operation upfront.

So instead we can call `deserialize(serialize(value))` for serialized attributes only.

This isn't very performant, but honestly it's kind of a miracle this even work. Querying by a serialized attribute is a very weird idea.

### CODE REVIEW

**Comment by casperisfine** [comment]
I bisected using the following script:

```ruby
require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  # gem 'rails', '= 7.0.5'
  gem 'rails', path: "/Users/byroot/src/github.com/Shopify/rails"
  gem 'sqlite3'
  gem 'byebug'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')

ActiveRecord::Schema.define do
  create_table :json_objs do |t|
    t.json :payload
  end
end

ActiveModel::Type::Helpers::Mutable.class_eval do
  def immutable_value(value)
    value
  end
end

class QueryCacheMutableParamTest < ActiveSupport::TestCase
  class JsonObj < ActiveRecord::Base
    self.table_name = "json_objs"

    attribute :payload, :json
  end

  class HashWithFixedHash < Hash
    # this isn't very realistic, but it is the worst case and therefore a good
    # case to test
    def hash
      1
    end
  end

  def setup
    ActiveRecord::Base.connection.enable_query_cache!
  end

  def test_query_cache_handles_mutated_binds
    JsonObj.create(payload: { a: 1 })

    search = HashWithFixedHash[a: 1]
    JsonObj.where(payload: search).first # populate the cache

    search.merge!(b: 2)
    assert_not_nil JsonObj.where(payload: search).first, "cache returned a false positive"
  end
end
```

Somehow, the bisect points to https://github.com/rails/rails/pull/48171 as the first "failing" (well passing) revision, which makes no sense to me, I really don't see how it could have an impact.

**Comment by casperisfine** [comment]
Argh, I figured it out. It's because that test uses a Hash subclass, so we enter the `if is_a?(Hash)` condition, and it's converted to a regular hash....

**Comment by casperisfine** [comment]
Ok, I think I have something that works. It's not ideal, but the expectation is that querying by a serialized attribute is very rare (it shouldn't even be supported IMHO), so not a huge deal if it incur some overhead.

**Comment by drewblas** [comment]
@casperisfine I thought I might add some context on where "query by serialized attribute" might be necessary (and maybe more common than realized:

At least in our case it's because the serialization is converting it to a global_id, and what is stored in the DB as a jsonb such as something like "{"request_task":{"_aj_globalid":"gid://app/Tasks/1d8ae84b-2b92-4ee0-8407-94b1d196ea3a"}}".   

So basically for consistency with how activejob does this whenever you pass in an object that needs to get passed to a worker as a param, except in this case being stored as in a regular DB column.

This is the gem we're using that causes the behavior (which we can of course look for other alternatives that have a better practice than this) - https://github.com/excid3/noticed

**Comment by casperisfine** [comment]
> At least in our case it's because the serialization is converting it to a global_id, and what is stored in the DB as a jsonb such as something like "{"request_task":{"_aj_globalid":"gid://app/Tasks/1d8ae84b-2b92-4ee0-8407-94b1d196ea3a"}}".

I see. I guess it makes sense, but I don't see how to make this performant though, as currently my patch will do a serializer roundtrip, so deserializing that GlobalID will be costly :/

**Comment by casperisfine** [comment]
Ok, trying something else in https://github.com/rails/rails/pull/48730

**Pull request closed without merging**
