### PR TITLE
Reduce loops in head route matching

### PR DESCRIPTION
**Pull request by vinistock**
### Summary

Reduce a few loops and allocations in `match_head_routes`. Basically, just avoided filtering multiple times and took advantage of the fact that we can mutate the routes parameter inside these private methods.

### Benchmark
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", require: "rails/all"
  gem "benchmark-ips"
  gem "benchmark-memory", require: "benchmark/memory"
end

module ActionDispatch
  module Journey
    class Router
      private

      def fast_match_head_routes(routes, req)
        head_routes = routes.select { |r| r.requires_matching_verb? && r.matches?(req) }
        return head_routes unless head_routes.empty?

        begin
          req.request_method = "GET"
          routes.select! { |r| r.matches?(req) }
          routes
        ensure
          req.request_method = "HEAD"
        end
      end
    end
  end
end

route_set = ActionDispatch::Routing::RouteSet.new
route_set.draw do
  get "/welcome" => "foo#bar", as: "welcome"
  get "/dummy_model" => "foo#baz", as: "dummy_model"
  get "/welcome/greeting", to: "welcome#greeting"
  get "/a/b(/:id)", to: "a#b"
end
router = route_set.router
req = ActionDispatch::Request.new(
  {
    "rack.version"      => [1, 1],
    "rack.input"        => StringIO.new,
    "rack.errors"       => StringIO.new,
    "rack.multithread"  => true,
    "rack.multiprocess" => true,
    "rack.run_once"     => false,
    "REQUEST_METHOD"    => "GET",
    "SERVER_NAME"       => "example.org",
    "SERVER_PORT"       => "80",
    "QUERY_STRING"      => "",
    "PATH_INFO"         => "/content",
    "rack.url_scheme"   => "http",
    "HTTPS"             => "off",
    "SCRIPT_NAME"       => "",
    "CONTENT_LENGTH"    => "0",
    "REQUEST_METHOD"    => "HEAD",
    "PATH_INFO"         => "/a/b/10"
  }
)

# Copy of the first step in find_routes to be able to micro-benchmark the match_head_routes method
filtered_routes = router.send(:filter_routes, req.path_info).concat router.send(:custom_routes).find_all { |r|
  r.path.match?(req.path_info)
}

puts "IPS"
Benchmark.ips do |x|
  x.report("match")      { router.send(:match_head_routes, filtered_routes, req) }
  x.report("fast_match") { router.send(:fast_match_head_routes, filtered_routes, req) }
  x.compare!
end

puts "MEMORY"
Benchmark.memory do |x|
  x.report("match")      { router.send(:match_head_routes, filtered_routes, req) }
  x.report("fast_match") { router.send(:fast_match_head_routes, filtered_routes, req) }
  x.compare!
end
```
### Results
```
IPS
Warming up --------------------------------------
               match    52.685k i/100ms
          fast_match    60.366k i/100ms
Calculating -------------------------------------
               match    606.333k (± 4.4%) i/s -      3.056M in   5.050991s
          fast_match    743.192k (± 3.0%) i/s -      3.743M in   5.040465s

Comparison:
          fast_match:   743192.4 i/s
               match:   606332.8 i/s - 1.23x  slower

MEMORY
Calculating -------------------------------------
               match   120.000  memsize (     0.000  retained)
                         3.000  objects (     0.000  retained)
                         0.000  strings (     0.000  retained)
          fast_match    40.000  memsize (     0.000  retained)
                         1.000  objects (     0.000  retained)
                         0.000  strings (     0.000  retained)

Comparison:
          fast_match:         40 allocated
               match:        120 allocated - 3.00x more
```

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Did you try to use a lazy enumerator to see if you could get the similar performance without making the code more complex?

**Comment by vinistock** [comment]
@rafaelfranca I didn't, but I'd be happy to explore lazy implementations and test them out. Do you have any particular design in mind? Also, did you find the code to be more complex now?

**Comment by rafaelfranca** [comment]
```ruby
verb_specific_routes = routes.lazy.select(&:requires_matching_verb?)
head_routes = match_routes(verb_specific_routes, req)
```

For example, so we don't have to duplicate the `select! { matches? } everywhere.

**Comment by vinistock** [comment]
I tried the following (which is pretty close to the original using lazy), but the results are not promising.
```ruby
module ActionDispatch
  module Journey
    class Router
      private

      def fast_match_head_routes(routes, req)
        verb_specific_routes = routes.lazy.select(&:requires_matching_verb?)
        head_routes = match_routes(verb_specific_routes, req).force # need to force to be able to check if it's empty
        return head_routes unless head_routes.empty?

        begin
          req.request_method = "GET"
          match_routes(routes, req)
        ensure
          req.request_method = "HEAD"
        end
      end

      def match_routes(routes, req)
        routes.select { |r| r.matches?(req) }
      end
    end
  end
end
```
Results
```
IPS
Warming up --------------------------------------
               match    63.188k i/100ms
          fast_match     8.642k i/100ms
Calculating -------------------------------------
               match    780.944k (± 2.7%) i/s -      3.918M in   5.020266s
          fast_match     86.548k (±13.2%) i/s -    432.100k in   5.059145s

Comparison:
               match:   780943.8 i/s
          fast_match:    86547.7 i/s - 9.02x  slower

MEMORY
Calculating -------------------------------------
               match    40.000  memsize (     0.000  retained)
                         1.000  objects (     0.000  retained)
                         0.000  strings (     0.000  retained)
          fast_match     1.696k memsize (     0.000  retained)
                        25.000  objects (     0.000  retained)
                         0.000  strings (     0.000  retained)

Comparison:
               match:         40 allocated
          fast_match:       1696 allocated - 42.40x more
```

**Comment by rafaelfranca** [comment]
wow. Lazy is pretty useless in this case. I wonder what is doing so much allocations.

**Pull request merged**
