### PR TITLE
Move `ActionDispatch::Mime` to `ActiveSupport::Mime`

### PR DESCRIPTION
**Pull request by maclover7**
This will now make ActionView independent of ActionDispatch (and thus
ActionPack). This also makes Rails' Mime code more easily usable by
other people!

ref #17030

### CODE REVIEW

**Comment by guilleiguaran** [comment]
This caused some errors in Travis build.

**Comment by maclover7** [comment]
Yep, just pushed fix for the broken tests.

**Comment by kaspth** [comment]
Don't like the idea of Active Support becoming a common grab bag for Action View and Action Pack.

@lukaszx0 worked on the original extraction, maybe he has some pointers of where to go 😁

**Comment by kaspth** [comment]
Eh, but then again it already is to an extent ¯\_(ツ)_/¯

**Comment by rafaelfranca** [comment]
Closing since this is not the way we are going.

**Pull request closed without merging**
