### PR TITLE
Local vars should exist in partials for falsy `:object:` values too

### PR DESCRIPTION
**Pull request by agis**
c67005f221f102fe2caca231027d9b11cf630484 made the local var in partials
available only if what passed to `:object` was truthy.

For example this would not make the local variable `foo` available inside the
partial:

```
render partial: 'foo', object: false
```

Fixes #17373.

### CODE REVIEW

**Comment by jurglic** [comment]
Could we get this fix into 4.0 and 4.1 as well? It doesn't help unless you upgrade from 3.2 straight to 4.2.

**Comment by rafaelfranca** [comment]
@jurglic backported to 4-1-stable in d2091b2

**Comment by jurglic** [comment]
That was fast, cheers :+1:

**Comment by jurglic** [comment]
Can you make into for 4.0 too?

**Comment by sgrif** [comment]
4.0 is no longer supported.

**Comment by jurglic** [comment]
Oh, completely forgot that!

Just to clarify, even if I prepare the PR, there will be no new release of 4.0? If that is not the case I'd be happy to do it.

**Comment by rafaelfranca** [comment]
@jurglic there will be no changes in the 4-0-stable branch of any nature.

**Pull request merged**
