### PR TITLE
[ci skip] Correct output for Upcase

### PR DESCRIPTION
**Pull request by dixitp012**

### CODE REVIEW

**Comment by matthewd** [comment]
This is pretty pointless: the example is to demonstrate that `mb_chars` does things that the built-in String does not. If we're going to update for Ruby 2.4 behaviour, the solution is to find something that `mb_chars` still does better than Ruby, not open the documentation with an example that suggests the whole thing exists for no reason.

(IIRC, there are still such things. If not, then we should instead show the pre-2.4 behaviour, and update the documentation to show it's only/primarily useful for pre-2.4 users.)

**Comment by kamipo** [comment]
hmm... should be reverted?

**Comment by dixitp012** [comment]
What about we document with correct example?

```
>> 'über'.upcase
=> "üBER"
>> 'über'.mb_chars.upcase.to_s
=> "ÜBER" 
```

**Comment by matthewd** [comment]
@dixitp012 a "correct" example would be nice... but that one isn't any more correct than `ǉ`, as far as I can see: it behaves as you showed in 2.3, and becomes `ÜBER` in 2.4.

**Comment by kamipo** [comment]
`ActiveSupport::Multibyte` is useful only for Ruby 2.2 and 2.3 because Ruby 2.4 supports Unicode 9.0.0, case mappings, and "true" extended grapheme cluster.
So the example should mention about that, I think.

**Comment by matthewd** [comment]
My first preference would be a legitimate example of `mb_chars` being better than `String` even in 2.4 (.. and 2.5). If we can't find one of those, the next best option is an example of it being better than Ruby 2.3 (which is what `ǉ` was), with appropriate wording around different version behaviours.

Note that we've been here before: https://github.com/rails/rails/pull/21684

@kamipo I have a vague memory of discussion (cc @jeremy maybe?) that concluded there were still cases that `mb_chars` was better at. But maybe that was back in 2.3 era.

**Comment by kamipo** [comment]
Yeah, Ruby 2.3 doesn't have Unicode case mappings and "true" extended grapheme cluster.
`ActiveSupport::Multibyte` is still useful for Ruby 2.3.

**Comment by kamipo** [comment]
Mentioned about Ruby 2.4 Unicode case mappings in #31275.

**Pull request merged**
