### PR TITLE
Remove unnecessary array allocation

### PR DESCRIPTION
**Pull request by gazay**
I'm investigating leaking memory problem in my project by analyzing objspace heap dumps. The problem not in this place, but I found that a lot of Array objects created here and it is unnecessary.

### CODE REVIEW

**Comment by kaspth** [comment]
We'll need a benchmark to be able to evaluate this :smile:

**Comment by gazay** [comment]
Ok, I'll try to make it today. Btw maybe you know why after `git push --force` travis doesn't restart?

**Comment by kaspth** [comment]
No, sorry. That's been happening for a while. Closing and reopening will make Travis run again.

**Comment by repinel** [comment]
Travis won't run by design. From http://docs.travis-ci.com/user/pull-requests
> Travis CI also currently doesn’t build pull requests when the upstream branch is updated. When this happens, GitHub will update the merge commit between the downstream and upstream branch, and send out a notifications. But Travis CI currently ignores this update, as it could lead to a large number of new builds on repositories with lots of pull requests and lots of updates on the upstream branches.

**Comment by sgrif** [comment]
While this change should be fine, I'd rather not merge this unless we have benchmarks showing that it is a *significant* hotspot in the context of a normal Rails app. The type map shouldn't be accessed much after boot for normal usage. (As a side note, I consider this to be something that should be fixed by the compiler, as it's basically the same optimization as https://github.com/jruby/jruby/pull/2562)

**Pull request closed without merging**
