### PR TITLE
Backport to 7-0-stable: MemoryStore: preserve entry ttl when incrementing (and race condition fix)

### PR DESCRIPTION
**Pull request by pjambet**
### Motivation / Background

Backports the fix from https://github.com/rails/rails/pull/46305

### Detail

Calling `Rails.cache.increment` drops the existing TTL, which is an issue on the current release of Rails, 7.0.

### Additional information

Some of the changes introduced in [the original
PR](https://github.com/rails/rails/pull/46305) were discarded, such as the `normalize_` methods, as well as the change that originated in [that PR](https://github.com/rails/rails/pull/45068) that sets a value if none exists.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by ghiculescu** [comment]
@byroot wdyt about backporting this?

**Comment by byroot** [comment]
Fine by me, but looking back at that PR, I'm not sure why I removed the synchronization, that may be a problem. I'll have a deeper look tomorrow.

Also backporting the CHANGLOG part as well would be good.

**Comment by pjambet** [comment]
I believe that it’s because write_entry takes care of the synchronization.

I’ll update the CHANGELOG as well

**Comment by pjambet** [comment]
Ran the test below locally on main and this branch and can confirm it seems like #46305 introduced a race condition by removing the `synchronize` wrapper.

Pushed a new commit to re-introduce the synchronize, not sure if we can deterministically test that though.

<details>
<summary>Tests I ran locally</summary>

On main:

```diff
diff --git a/activesupport/lib/active_support/cache/memory_store.rb b/activesupport/lib/active_support/cache/memory_store.rb
index 6450a910cd..c0b92801be 100644
--- a/activesupport/lib/active_support/cache/memory_store.rb
+++ b/activesupport/lib/active_support/cache/memory_store.rb
@@ -239,7 +239,7 @@ def modify_value(name, amount, options)
           version = normalize_version(name, options)
 
           entry = read_entry(key, **options)
-
+sleep 1
           if !entry || entry.expired? || entry.mismatched?(version)
             write(name, Integer(amount), options)
             amount
diff --git a/activesupport/test/cache/stores/memory_store_test.rb b/activesupport/test/cache/stores/memory_store_test.rb
index 651cae4b6a..f3c8ab2276 100644
--- a/activesupport/test/cache/stores/memory_store_test.rb
+++ b/activesupport/test/cache/stores/memory_store_test.rb
@@ -40,6 +40,20 @@ def test_increment_preserves_expiry
     end
   end
 
+
+  def test_increment_handles_increment_decrement_race_conditions
+    @cache = lookup_store
+    @cache.write("counter", 1)
+    threads = 2.times.map do
+      Thread.new do
+        @cache.increment("counter", 1)
+      end
+    end
+    threads.map(&:join)
+    assert_equal 3, @cache.read("counter", raw: true)
+  end
+
   def test_cleanup_instrumentation
     size = 3
     size.times { |i| @cache.write(i.to_s, i) }
```

On this branch:

```diff
diff --git a/activesupport/lib/active_support/cache/memory_store.rb b/activesupport/lib/active_support/cache/memory_store.rb
index 98ac081abd..e42b711e8d 100644
--- a/activesupport/lib/active_support/cache/memory_store.rb
+++ b/activesupport/lib/active_support/cache/memory_store.rb
@@ -192,6 +192,7 @@ def modify_value(name, amount, options)
           options = merged_options(options)
 
           if entry = read_entry(name, **options)
+            sleep 1
             num = entry.value.to_i + amount
             entry = Entry.new(num, expires_at: entry.expires_at, version: entry.version)
             write_entry(name, entry)
diff --git a/activesupport/test/cache/stores/memory_store_test.rb b/activesupport/test/cache/stores/memory_store_test.rb
index 9fefd0daf3..cdbe7f35a4 100644
--- a/activesupport/test/cache/stores/memory_store_test.rb
+++ b/activesupport/test/cache/stores/memory_store_test.rb
@@ -44,6 +44,19 @@ def test_increment_preserves_expiry
       assert_nil @cache.read("counter", raw: true)
     end
   end
+
+  def test_increment_handles_increment_decrement_race_conditions
+    @cache = lookup_store
+    @cache.write("counter", 1)
+    threads = 2.times.map do
+      Thread.new do
+        @cache.increment("counter", 1)
+      end
+    end
+    threads.map(&:join)
+    assert_equal 3, @cache.read("counter", raw: true)
+  end
 end
 
 class MemoryStorePruningTest < ActiveSupport::TestCase
```

</details>

**Pull request merged**
