### PR TITLE
Fix params merge regression

### PR DESCRIPTION
**Pull request by jtmkrueger**
### Summary

This is a duplicate of #42052 but for 6.1 stable

### CODE REVIEW

**Comment by lfalcao** [comment]
Duplicate https://github.com/rails/rails/pull/42020 ?

**Comment by jtmkrueger** [comment]
@lfalcao I believe so. This can probably be closed now.

**Comment by zzak** [comment]
Thanks! I think we don't normally open backport PRs until the bug is already fixed on `main` :bow:

**Comment by nicolem** [comment]
Now that this fix is on main, can we back port it to 6.1?

**Comment by jtmkrueger** [comment]
Happy to take the time to rebase if people think this can happen!

**Pull request closed without merging**
