### PR TITLE
Use a regular hash for holding inflections

### PR DESCRIPTION
**Pull request by chancancode**
This does not actually make anything threadsafe:
1. `@__instance__[locale] ||= new` is not atomic
2. The `Inflections` instance itself is clearly not threadsafe

For those reasons, protecting the hash access is rather pointless. So lets just be honest and not create an illusion of threadsafety here.

I could totally be missing something though – so I would love a review.

/cc @tenderlove @matthewd @fxn

### CODE REVIEW

**Comment by tenderlove** [comment]
I think it's fine. We should be setting these up at boot time anyway, so I don't think Thread safety would be a concern

**Comment by jeremy** [comment]
Why'd we make them thread-safe in the first place then? Multithreaded boot? Lazy-loaded inflections?

(We could switch `@__instance__[locale] ||= new` to `@__instance__.fetch_or_store(locale) { new }`, too)

**Comment by fxn** [comment]
Exactly, we talked a bit in the conference. I believe we need to make sure which is what we can prove from the API. Even though normally people modify this in initialzers, if formally you can do that later, like lazy-loading or who knows what crazy use-case, then I believe we cannot assume they won't change in the inflector's implementation (though you can program to favour the common use-case while supporting the rest somehow).

I don't know the answer off the top of my head.

**Comment by chancancode** [comment]
I think I figured it out. I'll update later when I get back to the hotel.

This is not to make defining or modifying the rules threadsafe (it's clearly not - for the two reasons I enumerated above). This is to guard the case where two threads/requests try to inflect (eg pluralize) with a locale that has no rules at runtime.

Assuming that we are okay with modifications being not threadsafe (as it is today - which makes sense imo), I think I can refactor it away while keeping access threadsafe. If someone feels strongly about it I could also fix it to make both sides threadsafe (by synchronizing modifications), I just don't really see the point of enabling/encouraging that.

**Comment by thedarkone** [comment]
> This is not to make defining or modifying the rules threadsafe (it's clearly not - for the two reasons I enumerated above). This is to guard the case where two threads/requests try to inflect (eg pluralize) with a locale that has no rules at runtime.

Exactly (source: me, https://github.com/rails/rails/commit/45448a578877f6a753492113d72cc3512a6f1720#diff-7981f69995a3750c52e68d1aa65d0c12R28).

**Comment by matthewd** [comment]
threadsafe != atomic.

`a_hash_some_other_thread_is_reading_right_now[a_key] = a_value` can *crash the process* on a non-GVL interpreter.

In general, and per 45448a578877f6a753492113d72cc3512a6f1720 / #8510 / many subsequent rants by @thedarkone :wink:, we should basically never use a Hash it can be seen from more than one thread (without explicit locking), *on penalty of crash*... even if we don't care to make the object behave truly consistently in the face of simultaneous manipulation.

**Comment by chancancode** [comment]
Yes. My suspicion was more arising from the fact that latter: two threads could clearly get the same instance of an existing inflections object which is very much not threadsafe.

Do we care about making that work also? Like I said it's not hard, but I'm not sure if it really benefits anyone.

However, if we don't - then I think we are pretty much asserting that the inflections cannot be modified past boot time? I think everyone agrees that it's what we would like that to be the case, but it is very implicitly encoded here.

I think we should either make it raise if the rules are modified past boot (first inflection) or make it actually threadsafe (by synchronizing the block form inflections method - as far as I can tell the non-block form is just internal and I am planning to remove it in the refactor). 


Are we basically saying

**Comment by matthewd** [comment]
> two threads could clearly get the same instance of an existing inflections object which is very much not threadsafe

Isn't it?

`@acronyms` isn't, because it's a Hash... but the rest seems pretty safe, with the obvious caveat that if two threads do conflicting things (e.g., add the same thing as a defined plural and as an uncountable), the result is unpredictable.

It's true that two threads could be inside an 'inflection definition block' at the same time, but that doesn't currently seem inherently unsafe.

---

It does seem that the current design implicitly assumes, in practice, that definitions will occur during single-threaded boot, and it only needs to account for concurrency while actually inflecting. But enforcing that seems architecturally tricky... "first inflection" is, IMO, unreasonable: one gem inflects something during its setup, and the next is no longer allowed to define things? (Even assuming our own boot process avoids ever inflecting -- I haven't checked.)

**Comment by chancancode** [comment]
This cannot be merged as-is, moving to #26804

**Pull request closed without merging**
