### PR TITLE
Debug statements for intermittently failing test

### PR DESCRIPTION
**Pull request by ghiculescu**
Trying to fix https://buildkite.com/rails/rails/builds/80833#38d8b1af-89e5-4712-a3fd-87dd53280752

### CODE REVIEW

**Comment by p8** [comment]
It's a weird bug. It always seems to fail on the same assertion:
```
 Expected `image_tag` to produce a match to (?-mix:<img src="\/images\/doesnotexist"), but did not: /stylesheets/doesnotexist.css
 ```

**Comment by ghiculescu** [comment]
yeah, it's pretty confusing. i haven't been able to replicate it locally.

**Comment by p8** [comment]
This one fails on another assertion: https://buildkite.com/rails/rails/builds/80820#ec5c2145-6056-4701-b4b2-1848ed80989d/2180-2188

**Comment by p8** [comment]
It also seems to only fail on ruby 2.7

**Comment by ghiculescu** [comment]
I guess I just gotta keep rebuildling until it fails

**Comment by ceritium** [comment]
Hi, for some reason, I made it fail on my rails-dev-box; I am trying to reproduce it again. Meantime I was able to do some debugging.

If I remember well, I did:
```ruby
      cases.each do |(view_method, tag_match)|
        app_file "app/views/posts/index.html.erb", "<%= #{view_method} '#{contents}', skip_pipeline: true %>"
        puts File.read("#{app_path}/app/views/posts/index.html.erb")

        app "development"

        class ::PostsController < ActionController::Base ; end

        get "/posts?debug_assets=true&view_method=#{view_method}" # to detect cache by URL things

        body = last_response.body
        puts body
        puts body.etag # I detected that the etag was the same that in the previous get request

        assert_match(tag_match, body, "Expected `#{view_method}` to produce a match to #{tag_match}, but did not: #{body}")
        sleep 1 # it was working with 1, but it was failing with lower numbers.
```

I did it with RVM instead of the default ruby version (I was investigating another error on ruby 3.1.0).

**Comment by ceritium** [comment]
JFYI: I can reproduce it again in a fresh rails dev box, rvm, and ruby 2.7.2. I had to run ` bundle update importmap-rails` because of an issue with `httparty` the version` 0.5.0`

There is anything that would you like to try aside from the content of this PR? If you can't reproduce it, we could meet for a pairing session if you need it.

**Comment by ceritium** [comment]
Debug info:

For the test
```
       app_file "app/views/posts/index.html.erb", "<% puts 'view_method', @view_method %><%= #{view_method} '#{contents}', skip_pipeline: true %>"
        puts 'file', File.read("#{app_path}/app/views/posts/index.html.erb")

        app "development"

        class ::PostsController < ActionController::Base
          def index
            @view_method = params[:view_method]
            puts 'action', SecureRandom.hex(10)
          end
        end

        get "/posts?debug_assets=true&view_method=#{view_method}"

        body = last_response.body
        puts 'body', body
        puts 'etag', last_response.etag
        assert_match(tag_match, body, "Expected `#{view_method}` to produce a match to #{tag_match}, but did not: #{body}")
        puts '----------------'

```

It is the output:

```
vagrant@rails-dev-box:/vagrant/rails/railties$ bin/test test/application/asset_debugging_test.rb:69
Run options: --seed 1241

# Running:

file
<% puts 'view_method', @view_method %><%= asset_path 'doesnotexist', skip_pipeline: true %>
action
3d32139abc07f9e12717
view_method
asset_path
body
/doesnotexist
etag
W/"81182d72fa8d9c325c601528bc68d86a"
----------------
file
<% puts 'view_method', @view_method %><%= image_path 'doesnotexist', skip_pipeline: true %>
action
bf3c84f27f842e0808ef
view_method
image_path
body
/images/doesnotexist
etag
W/"d5609b90b2784c0e84ac5855a53dcf5e"
----------------
file
<% puts 'view_method', @view_method %><%= video_path 'doesnotexist', skip_pipeline: true %>
action
4b25d4a6ac717c98550d
view_method
video_path
body
/images/doesnotexist
etag
W/"d5609b90b2784c0e84ac5855a53dcf5e"
F

Failure:
ApplicationTests::AssetDebuggingTest#test_public_path_and_tag_methods_are_not_over-written_by_the_asset_pipeline [/vagrant/rails/railties/test/application/asset_debugging_test.rb:106]:
Expected `video_path` to produce a match to (?-mix:\/videos\/doesnotexist), but did not: /images/doesnotexist
.
Expected /\/videos\/doesnotexist/ to match # encoding: ASCII-8BIT
#    valid: true
"/images/doesnotexist\n".


bin/test test/application/asset_debugging_test.rb:69



Finished in 2.540177s, 0.3937 runs/s, 2.3620 assertions/s.
1 runs, 6 assertions, 1 failures, 0 errors, 0 skips
```

As you can see the file content is fine, the action and the view are executed (we know it because of the `puts`) but `last_response` is returning the wrong content (the same that in the previous request).

My suspicion is that it's a problem related somehow with `rack-test`, but I can't prove it yet.

**Comment by ceritium** [comment]
Just for debugging, I tried with a different approach, I keep each request in a different "test" and it works well:

```ruby
    contents = "doesnotexist"
    cases = {
        asset_path:             %r{/#{contents}},
        image_path:             %r{/images/#{contents}},
        video_path:             %r{/videos/#{contents}},
        audio_path:             %r{/audios/#{contents}},
        font_path:              %r{/fonts/#{contents}},
        javascript_path:        %r{/javascripts/#{contents}},
        stylesheet_path:        %r{/stylesheets/#{contents}},
        image_tag:              %r{<img src="/images/#{contents}"},
        favicon_link_tag:       %r{<link rel="shortcut icon" type="image/x-icon" href="/images/#{contents}" />},
        stylesheet_link_tag:    %r{<link rel="stylesheet" href="/stylesheets/#{contents}.css" />},
        javascript_include_tag: %r{<script src="/javascripts/#{contents}.js">},
        audio_tag:              %r{<audio src="/audios/#{contents}"></audio>},
        video_tag:              %r{<video src="/videos/#{contents}"></video>},
        image_submit_tag:       %r{<input type="image" src="/images/#{contents}" />}
      }

    cases.each do |(view_method, tag_match)|
      test "test #{view_method} #{tag_match}" do
        app_file "app/views/posts/index.html.erb", "<% puts 'view_method', @view_method %><%= #{view_method} '#{contents}', skip_pipeline: true %>"
        puts 'file', File.read("#{app_path}/app/views/posts/index.html.erb")

        app "development"

        class ::PostsController < ActionController::Base
          def index
            @view_method = params[:view_method]
            puts 'action', SecureRandom.hex(10)
          end
        end

        get "/posts?debug_assets=true&view_method=#{view_method}"

        body = last_response.body
        puts 'body', body
        puts 'etag', last_response.etag
        assert_match(tag_match, body, "Expected `#{view_method}` to produce a match to #{tag_match}, but did not: #{body}")
        puts '----------------'
      end
    end
```

We could implement the tests that way if we don't found a solution for the current approach.

**Comment by ghiculescu** [comment]
Nice, that’s super helpful. I don’t have a lot of time to debug rack-test this week. Happy for someone else if they want to, but I also like your idea of just splitting out the tests and calling it a day. Want to make a PR for that?

**Comment by ceritium** [comment]
> Want to make a PR for that?

@ghiculescu, absolutely.

**Comment by ghiculescu** [comment]
https://github.com/rails/rails/pull/43178

**Comment by ceritium** [comment]
I was able to reproduce it consistently in older commits like the `v6.0.3.6` tag. I am not able to run the tests on previous versions because of the `mimemagic` issue.

**Comment by p8** [comment]
I'm not seeing anything weird either. The MockResponse is a not being reused and has a new object_id everytime.
https://buildkite.com/rails/rails/builds/80862#98be4cbd-0bbc-4686-96ae-f46da4d8f768/2064-2190

**Comment by p8** [comment]
Ah interesting... when I retry the same request, after it fails, it returns the same response again:
https://buildkite.com/rails/rails/builds/80872#271c96fc-9e07-4d3a-8c15-b3f42342e6cd/2088-3102
```
------ view_method: stylesheet_path
#<Rack::MockResponse:0x00007f161d3e5320 @original_headers={"X-Frame-Options"=>"SAMEORIGIN", "X-XSS-Protection"=>"1; mode=block", "X-Content-Type-Options"=>"nosniff", "X-Download-Options"=>"noopen", "X-Permitted-Cross-Domain-Policies"=>"none", "Referrer-Policy"=>"strict-origin-when-cross-origin", "Content-Type"=>"text/html; charset=utf-8", "ETag"=>"W/\"369245a10fd268a6273b5ac04a45d42d\"", "Cache-Control"=>"max-age=0, private, must-revalidate", "X-Request-Id"=>"e7369227-30f2-4c94-866f-097e4156c124", "Content-Length"=>"30"}, @errors="", @cookies={}, @status=200, @headers={"X-Frame-Options"=>"SAMEORIGIN", "X-XSS-Protection"=>"1; mode=block", "X-Content-Type-Options"=>"nosniff", "X-Download-Options"=>"noopen", "X-Permitted-Cross-Domain-Policies"=>"none", "Referrer-Policy"=>"strict-origin-when-cross-origin", "Content-Type"=>"text/html; charset=utf-8", "ETag"=>"W/\"369245a10fd268a6273b5ac04a45d42d\"", "Cache-Control"=>"max-age=0, private, must-revalidate", "X-Request-Id"=>"e7369227-30f2-4c94-866f-097e4156c124", "Content-Length"=>"30"}, @writer=#<Method: Rack::MockResponse(Rack::Response::Helpers)#append(chunk) /usr/local/bundle/gems/rack-2.2.3/lib/rack/response.rb:287>, @block=nil, @body=["/stylesheets/doesnotexist.css\n"], @buffered=true, @length=30>
"/stylesheets/doesnotexist.css\n"
------ view_method: image_tag
failed_response:
#<Rack::MockResponse:0x00007f161d3be928 @original_headers={"X-Frame-Options"=>"SAMEORIGIN", "X-XSS-Protection"=>"1; mode=block", "X-Content-Type-Options"=>"nosniff", "X-Download-Options"=>"noopen", "X-Permitted-Cross-Domain-Policies"=>"none", "Referrer-Policy"=>"strict-origin-when-cross-origin", "Content-Type"=>"text/html; charset=utf-8", "ETag"=>"W/\"369245a10fd268a6273b5ac04a45d42d\"", "Cache-Control"=>"max-age=0, private, must-revalidate", "X-Request-Id"=>"74a2cadd-e85e-4764-a9d3-758b31ebcdf2", "Content-Length"=>"30"}, @errors="", @cookies={}, @status=200, @headers={"X-Frame-Options"=>"SAMEORIGIN", "X-XSS-Protection"=>"1; mode=block", "X-Content-Type-Options"=>"nosniff", "X-Download-Options"=>"noopen", "X-Permitted-Cross-Domain-Policies"=>"none", "Referrer-Policy"=>"strict-origin-when-cross-origin", "Content-Type"=>"text/html; charset=utf-8", "ETag"=>"W/\"369245a10fd268a6273b5ac04a45d42d\"", "Cache-Control"=>"max-age=0, private, must-revalidate", "X-Request-Id"=>"74a2cadd-e85e-4764-a9d3-758b31ebcdf2", "Content-Length"=>"30"}, @writer=#<Method: Rack::MockResponse(Rack::Response::Helpers)#append(chunk) /usr/local/bundle/gems/rack-2.2.3/lib/rack/response.rb:287>, @block=nil, @body=["/stylesheets/doesnotexist.css\n"], @buffered=true, @length=30>
"/stylesheets/doesnotexist.css\n"
...trying again
#<Rack::MockResponse:0x00007f161d3a48c0 @original_headers={"X-Frame-Options"=>"SAMEORIGIN", "X-XSS-Protection"=>"1; mode=block", "X-Content-Type-Options"=>"nosniff", "X-Download-Options"=>"noopen", "X-Permitted-Cross-Domain-Policies"=>"none", "Referrer-Policy"=>"strict-origin-when-cross-origin", "Content-Type"=>"text/html; charset=utf-8", "ETag"=>"W/\"369245a10fd268a6273b5ac04a45d42d\"", "Cache-Control"=>"max-age=0, private, must-revalidate", "X-Request-Id"=>"bf791be9-38e2-449d-911e-d13973c7e3c6", "Content-Length"=>"30"}, @errors="", @cookies={}, @status=200, @headers={"X-Frame-Options"=>"SAMEORIGIN", "X-XSS-Protection"=>"1; mode=block", "X-Content-Type-Options"=>"nosniff", "X-Download-Options"=>"noopen", "X-Permitted-Cross-Domain-Policies"=>"none", "Referrer-Policy"=>"strict-origin-when-cross-origin", "Content-Type"=>"text/html; charset=utf-8", "ETag"=>"W/\"369245a10fd268a6273b5ac04a45d42d\"", "Cache-Control"=>"max-age=0, private, must-revalidate", "X-Request-Id"=>"bf791be9-38e2-449d-911e-d13973c7e3c6", "Content-Length"=>"30"}, @writer=#<Method: Rack::MockResponse(Rack::Response::Helpers)#append(chunk) /usr/local/bundle/gems/rack-2.2.3/lib/rack/response.rb:287>, @block=nil, @body=["/stylesheets/doesnotexist.css\n"], @buffered=true, @length=30>
"/stylesheets/doesnotexist.css\n"
```

**Comment by ceritium** [comment]
I think that it's not related to rack, I am investigating how rails reload the "views" on development.

**Comment by ceritium** [comment]
I think that I found the issue finally, it is my theory:

[`ActiveSupport::FileUpdateChecker.updated?`](https://github.com/rails/rails/blob/fa1a4b657c7167a8671a359a55de3f9b37f4330b/activesupport/lib/active_support/file_update_checker.rb#L61) is based on file size and timestamp. The file size will always match, but the timestamp will match only sometimes. That's the reason why tests pass when I add a sleep of 1 second.

I tried locally changing `if @last_watched.size != current_watched.size` with `if true` and the tests pass.

I don't know yet if https://github.com/rails/rails/pull/42985 is related, but in any case, we could improve `ActiveSupport::FileUpdateChecker.updated?` at least for testing.

Does it make sense for you?

**Comment by rafaelfranca** [comment]
Can we make the file size stop matching in that test for each check? Maybe add an extract char per iteration in the loop.

**Comment by ceritium** [comment]
I found that `@last_watched.size` doesn't mean the "file size", `last_watched` and current_watched` are arrays of files paths, for example:

```
["/vagrant/rails/activesupport/lib/active_support/locale/en.yml", "/vagrant/rails/activesupport/lib/active_support/locale/en.rb", "/vagrant/rails/activemodel/lib/active_model/locale/en.yml", "/vagrant/rails/activerecord/lib/active_record/locale/en.yml", "/vagrant/rails/actionview/lib/action_view/locale/en.yml", "/vagrant/rails/tmp/d20210908-54165-l53tj0/app/config/locales/en.yml", "/vagrant/rails/tmp/d20210908-54165-l53tj0/app/config/locales/en.yml"]
```

So an easy option that doesn't require modification of `ActiveSupport::FileUpdateChecker` would be to put each "case" in a different file.

**Comment by p8** [comment]
Yes, HEAD fails even though the file size is different:
```Expected `image_tag` to produce a match to (?-mix:<img src="\/images\/doesnotexist"), but did not: /stylesheets/doesnotexist.css```
https://buildkite.com/rails/rails/builds/80863#2dbf72ae-d13a-4bbb-bdf2-c8384217f94b/2092-2102

**Comment by ceritium** [comment]
I have some proposals:
- [Split the cases on individual tests](https://github.com/rails/rails/pull/43178), it is a bit slower
- [Create a template per case](https://github.com/rails/rails/compare/main...ceritium:asset-debugging-template-per-case?expand=1), ugly but faster than the previous one
- Just [sleep 1 second and touch the file](https://github.com/rails/rails/compare/main...ceritium:app-file-file-checker-aware?expand=1) to ensure that FileUpdateChecker detects the change, it is something that it's [already happening](https://github.com/rails/rails/blob/fa1a4b657c7167a8671a359a55de3f9b37f4330b/activesupport/test/file_update_checker_test.rb#L14) on FileUpdateCheckerTest. It is my favorite one.

**Comment by p8** [comment]
Maybe allow resetting the FileupdateChecker?

**Comment by p8** [comment]
Great work @ceritium !

What about disabling template caching for this test?
```
add_to_env_config "production", "config.action_view.cache_template_loading = false"
```
This should ignore the file watcher altogether:
https://github.com/rails/rails/blob/70470d7eed2086169881cc3328693a0f014b03f8/actionview/lib/action_view/railtie.rb#L93-L103

We adjust application config likes this in other places as well:
https://github.com/rails/rails/blob/70470d7eed2086169881cc3328693a0f014b03f8/railties/test/application/asset_debugging_test.rb#L58

**Comment by ceritium** [comment]
@p8, do you mean [this](https://github.com/rails/rails/compare/main...ceritium:disable-cache-template-loading?expand=1)? it is not working locally for me.

**Comment by p8** [comment]
Hmm yes, too bad it doesn't work :(

**Comment by ceritium** [comment]
@p8 @ghiculescu @rafaelfranca I created a PR with the sleep and touch approach https://github.com/rails/rails/pull/43185

**Comment by ghiculescu** [comment]
Awesome debugging, https://github.com/rails/rails/pull/43185 looks like a great solution to me.

**Comment by p8** [comment]
Not sure it's expected behaviour to have an optional sleep in `app_file`.

Maybe it's possible to use a custom file watcher?
Like we do here, but have it return true for `updated?` instead.
https://github.com/rails/rails/blob/f58f8e175e8674224c33a4f37544dae719f3aaf1/railties/test/application/loading_test.rb#L189-L197

Hmm, looking at that test, it's testing the exact behaviour that's causing the build to fail.

**Comment by ghiculescu** [comment]
https://github.com/rails/rails/pull/43188

**Pull request closed without merging**
