### PR TITLE
Set fully qualified reference name for base image

### PR DESCRIPTION
**Pull request by juliusrickert**
Explicitly set the fully qualified reference name to avoid issues in environments which set a different default registry. The registry at registry.docker.com is dual stack-compatible.

### Motivation / Background

This Pull Request has been created because the default Docker container image registry doesn't support IPv6.

### Detail

This Pull Request changes the base image's reference to a fully qualified one which offers dual-stack support.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [x] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by dhh** [comment]
I'm probably a bit thick here. But I don't understand neither the problem we're trying to solve nor the specific solution. When do you hit an issue with the fact that the default Docker container image registry doesn't support IPv6? What setup are you using where Docker build won't use IPv4?

**Comment by juliusrickert** [comment]
> When do you hit an issue with the fact that the default Docker container image registry doesn't support IPv6?

In IPv6-only setups. That's the obvious, but most severely limiting. The default Docker Hub registry endpoint remains one of the very few remaining services which aren't available via IPv6.

Besides that, Docker Hub imposes [rate limits based on IP addresses](https://docs.docker.com/docker-hub/download-rate-limit/#whats-the-download-rate-limit-on-docker-hub). Many users can only access the IPv4 Internet via (carrier-grade) NAT, where hundreds or even thousands of users share a single public IPv4 address.

Lastly, some VPS providers offer lower prices for IPv6-only instances, e.g., [Hetzner](https://www.hetzner.com/cloud#pricing), [Vultr](https://www.vultr.com/pricing/). IPv4 connectivity is then, if needed, provided by a reverse proxy like Cloudflare.
One could argue that these users could "just" change their container runtime's configuration to an IPv6-ready registry. But these small changes add up and hinder the deployment of IPv6-only environments.

**Comment by dhh** [comment]
Ah, I see. All good 👍

**Comment by rafaelfranca** [comment]
@juliusrickert I'm trying to understand why registry.docker.com doesn't have the ruby 3.3.1 tag even if hub.docker.com has it and I can't find anywhere in the internet any explanation of what registry.docker.com and who controls it, and why it has different images than docker hub. Can you help me with that? Otherwise we should revert this change and point to the official docker hub registry.

**Comment by juliusrickert** [comment]
> Can you help me with that?

No, I can't. I don't know either.
By now, `docker.io` has IPv6 support and providing the fully qualified name is no longer necessary.

**Comment by rafaelfranca** [comment]
> No, I can't. I don't know either.

That is fine. I imagine that would be the case, but maybe you knew something.

I think we can probably fully qualify with docker.io instead. I'll make the change.

**Pull request merged**
