### PR TITLE
Instrument ActiveSupport::Cache::MemoryStore#increment and #decrement

### PR DESCRIPTION
**Pull request by frederikspang**
### Motivation / Background

This Pull Request has been created because currently Rails.cache.increment current does not instrument the same way as RedisCacheStore and MemCacheStore does.

### Detail

This Pull Request changes instrumentation of MemoryStore, to align implementation details between Cache Stores.

### Additional information

If needed, I can enable testing this in https://github.com/rails/rails/blob/main/activesupport/test/cache/behaviors/cache_instrumentation_behavior.rb#L3 - That would require from testing side, that increment and decrement methods are instrumented across all cache stores.

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Unrelated changes should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [ ] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Looking the documentation it seems this is by design. Why do you need this to be instrumented in the memory store?

**Comment by rafaelfranca** [comment]
https://github.com/rails/rails/commit/85688a689edabdd65b3d50b8e336aef9d1d7e954

**Comment by frederikspang** [comment]
@rafaelfranca In this case, it's for APM monitoring. I see from the documentation, that it's the case, but I was unable to figure out why - And I couldn't think of a good reason not to keep behaviour the same across adapters.

**Comment by rafaelfranca** [comment]
Maybe to avoid overhead. But yeah, I could also not figure out. Regardless, this change should update the documentation as well.

**Comment by frederikspang** [comment]
I've given it a go with FileStore as well, to match all implementations, and initial tests. 
I'm seeing encoding errors locally, that I'll try to resolve tomorrow.

**Comment by frederikspang** [comment]
Drilling into it, there seems to be a discrepancy in how namespaces are handled in cache* events.

```
Event: ["cache_read.active_support", 2024-08-27 23:42:30.024358 +0200, 2024-08-27 23:42:30.025755 +0200, "93a7547a79f478c4d67c", {:key=>"mynamespace:key", :store=>"ActiveSupport::Cache::RedisCacheStore", :namespace=>"mynamespace", :compress=>true, :compress_threshold=>1024, :super_operation=>:fetch, :hit=>true}]
Event: ["cache_fetch_hit.active_support", 2024-08-27 23:42:30.026051 +0200, 2024-08-27 23:42:30.026064 +0200, "93a7547a79f478c4d67c", {:key=>"key", :store=>"ActiveSupport::Cache::RedisCacheStore", :namespace=>"mynamespace", :compress=>true, :compress_threshold=>1024}]

Event: ["cache_read_multi.active_support", 2024-08-27 23:44:00.537863 +0200, 2024-08-27 23:44:00.538504 +0200, "93a7547a79f478c4d67c", {:key=>["key", "key2"], :store=>"ActiveSupport::Cache::RedisCacheStore", :namespace=>"mynamespace", :compress=>true, :compress_threshold=>1024, :hits=>["key", "key2"], :super_operation=>:fetch_multi}]
```

@rafaelfranca I'm thinking, normalize this for all events?

**Comment by rafaelfranca** [comment]
Yes. I think we should. See https://github.com/rails/rails/pull/50008

**Comment by frederikspang** [comment]
I have altered the tests to assert for normalized keys, and updated instrumentation to emit keys as normalized - Also squashed commit into one.

**Pull request merged**
