### PR TITLE
Lets be consistent in the usage of behavior in code as well.

### PR DESCRIPTION
**Pull request by vipulnsward**
Prompted by: https://github.com/rails/docrails/commit/3b1b957b6f1482ce260c8f4ecaad6e5b2bbd8316

### CODE REVIEW

**Comment by sgrif** [comment]
We'd need a deprecated proxy at least. This is a breaking change to public API

**Comment by sgrif** [comment]
(And I'm not sure it's worth deprecating to be honest)

**Comment by vipulnsward** [comment]
True. This happens to be only such usage. We have around 350+ of preferred usage.

**Comment by sgrif** [comment]
Yup. If it weren't public API I would be all for it. But every breaking change has a cost.

**Comment by jeremy** [comment]
Def need to preserve compat.

[The original PR](https://github.com/rails/rails/pull/10021) was intended to make these behaviors available to other test frameworks, but I couldn't find any examples of it. [Most usage is vendoring](https://github.com/search?l=ruby&q=%22Rails%3A%3AGenerators%3A%3ATesting%3A%3ABehaviour%22+language%3ARuby&ref=searchresults&type=Code&utf8=✓) and copy/pasting.

**Comment by sgrif** [comment]
I'm going to close this, as even if we deprecate I don't think it's worth a breaking change for spelling

**Pull request closed without merging**
