### PR TITLE
Use __dir__ due to the new supported ruby version

### PR DESCRIPTION
**Pull request by untidy-hair**
Since we don't support 1.9 anymore, we can use **dir** when available. Thanks!

### CODE REVIEW

**Comment by rafaelfranca** [comment]
I'd say this change fall in the cosmetic change category, so I'd not merge even when we are ready to drop support to Ruby 1.9.

**Comment by untidy-hair** [comment]
Thank you for the comment @rafaelfranca!
As long as I have tried, \_\_dir\_\_ is faster than File.dirname(\_\_FILE\_\_).
```
2.2.0 :001 > require 'benchmark'
 => true 
2.2.0 :002 > Benchmark.bmbm do |x|
2.2.0 :003 >     x.report("File.dirname(__FILE__): ") { 1_000_000.times { File.dirname(__FILE__) }}
2.2.0 :004?>     x.report("__dir__") { 1_000_000.times { __dir__ }}
2.2.0 :005?>   end
Rehearsal ------------------------------------------------------------
File.dirname(__FILE__):    0.850000   0.000000   0.850000 (  0.851659)
__dir__                    0.490000   0.000000   0.490000 (  0.486263)
--------------------------------------------------- total: 1.340000sec

                               user     system      total        real
File.dirname(__FILE__):    0.840000   0.000000   0.840000 (  0.839412)
__dir__                    0.490000   0.000000   0.490000 (  0.489455)

```
If I'm missing something, please let me know.

**Comment by sgrif** [comment]
Unless you can show that this is a performance hotspot, we don't make changes from microbenchmarks.

**Comment by untidy-hair** [comment]
Okay, if you say so. Thanks.

**Pull request closed without merging**
