### PR TITLE
Create class Requirer

### PR DESCRIPTION
**Pull request by ysksn**
### Summary

```
active_support/core_ext/array
                          ├── access.rb
                          ├── conversions.rb
                          ├── extract_options.rb
                          ├── grouping.rb
                          ├── inquiry.rb
                          ├── prepend_and_append.rb
                          └── wrap.rb
```

In order to require files in `active_support/core_ext/array`, you always create a file like `active_support/core_ext/array.rb`.

``` ruby
# active_support/core_ext/array.rb
require 'active_support/core_ext/array/wrap'
require 'active_support/core_ext/array/access'      
require 'active_support/core_ext/array/conversions'     
require 'active_support/core_ext/array/extract_options'     
require 'active_support/core_ext/array/grouping'        
require 'active_support/core_ext/array/prepend_and_append'      
require 'active_support/core_ext/array/inquiry'
```

It's very clear, but too pain to do so every time.  Instead, I create `Requirer` class to require all of files in the directory which are in the directory same name as where `Require#require_all` called.

If you want to require all files in `active_support/core_ext/array`, but `wrap.rb`, your `active_support/core_ext/array.rb` should be like below.

``` ruby
# active_support/core_ext/array.rb
Requirer.new(__FILE__, exclude: %w(wrap)).require_all
```

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Thank you for the pull request. All these files are internal and I believe the previous code is clear in what it does and also documents better so people that is interested to know which files are required only need to look at the file content instead of having to look in the directory structure and the file content to see which files where excluded. That said we will keep the code as it is right now.

**Comment by ysksn** [comment]
i see :)

**Comment by jeremy** [comment]
This very inventive, nonetheless, @ysksn! Fun idea, implementation, and great test coverage ❤️

**Comment by ysksn** [comment]
@jeremy It's an honor to be said from you. Your words makes me work harder. Thank you :)

**Pull request closed without merging**
