### PR TITLE
Include form_with in form_helpers rails guide

### PR DESCRIPTION
**Pull request by Schwad**
### Summary

This follows on from a discussion with @dhh and @kaspth regarding new `form_with` functionality in Rails 5.1 and updating our guides to reflect that. https://github.com/rails/rails/issues/25197

This commit appends new guide documentation based on the [core docs](https://api.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html#method-i-form_with) and [release notes](https://guides.rubyonrails.org/5_1_release_notes.html)

### CODE REVIEW

**Comment by Schwad** [comment]
@dhh I would appreciate it if you and @kaspth would take a look at this.

Besides any cursory tweaks ('include this, do not include that') I am in two minds on how we present `form_with` in the guide.

Part of me thinks that iteration one would be simply getting the documentation around `form_with` in the guides in its own section, as shown here. As suggested I simply used https://api.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html#method-i-form_with and the release notes https://guides.rubyonrails.org/5_1_release_notes.html to inform the guide documentation.

If there is intent to move to `form_with` becoming the default Rails 'convention'; there should be discussion about a second iteration. That iteration could rewrite much of this guide to show `form_with` as the default interface and have cursory mentions of `form_tag` and `form_for` at the end. I am not saying we have to, but it's a discussion worth having.

Thanks much!

**Comment by dhh** [comment]
I think we should take the opportunity to completely revamp this guide. It should start out with the most common, conventional approach that most people are actually going to use. That's form_with. To start with this long exposition on form_tag, which most people and most apps should never use, doesn't make much sense to me.

We shouldn't even talk about form_for at all, except maybe as a footnote saying that this was an old style that's now soft deprecated.

**Comment by Schwad** [comment]
Thanks for the feedback! 

I’ll take a stab at the doc from a “form_with”-first perspective like you said, with a soft-deprecated look at form_for. Will ping again when it’s up. Thanks again

**Comment by Schwad** [comment]
Looks like I should have something up for review a week from Friday. Making good progress.

**Comment by Schwad** [comment]
The guide is revamped in this version. When we agree a final version I will be sure to squash. Deployed a copy of the latest revisions to Heroku for you to look at as well: http://revamped-form-helper-guide.herokuapp.com/

* There are no more references to `form_for` or `form_tag` except for the footnote that points to older documentation.

* All functionality that is now utilized with `form_with` has been updated.

* There is a note about the `remote: true` default and `local: true` option.

* There is a note about the ability for users to include non-attribute inputs on form builder now.

* Notes that `class` and `id` are no longer required in HTML hash.

Look forward to your feedback, thank you! :)

**Comment by dhh** [comment]
I think this is an improvement, but I'd like to continue after this going even further. The first example and introduction should be as this is most commonly used. Focus on the usage with models, since that's what everyone is going to do from the get-go. The example using get and /search is the exotic case, not the default case. Anyway happy to see this merged as an intermediary step.

**Comment by Schwad** [comment]
Thank you for the feedback. That makes sense. If we can get this merged then I will fire up another PR soon to focus on those next steps. Will link that to original issue and this PR as well.

**Comment by dhh** [comment]
👍

**Pull request merged**
