### PR TITLE
ActionMailer::Base#mail should allow overriding template_name for default template rendering when a block is passed

### PR DESCRIPTION
**Pull request by betesh**

### CODE REVIEW

**Comment by georgeclaghorn** [comment]
What's the use case for this? Seems equivalent to the following, but less clear:

```ruby
class MyMailer < ActionMailer::Base
  def hello
    mail do |format|
      format.html # Will render app/views/my_mailer/goodbye.html.erb
      format.text { render "hello" } # Will render app/views/my_mailer/hello.text.erb
    end
  end
end
```

**Comment by betesh** [comment]
@georgeclaghorn  It's not the equivalent to the code sample in your comment.  It's the equivalent to:

    class MyMailer < ActionMailer::Base
      def hello
        mail do |format|
          format.html { render "goodbye" } # Here we override the default
          format.text # This defaults to hello
        end
      end
    end

The use case is when you have numerous formats using the same custom template name, so that the following would become much more concise:

    class MyMailer < ActionMailer::Base
      def hello
        mail do |format|
          format.html { render "goodbye" }
          format.text  { render "goodbye" }
          format.pdf  { render "goodbye" }
          format.png  { render "goodbye" }
          format.csv  { render "goodbye" }
        end
      end
    end

See how much cleaner this is:

    class MyMailer < ActionMailer::Base
      def hello
        mail(template_name: 'goodbye') do |format|
          format.html
          format.text
          format.pdf
          format.png
          format.csv
        end
      end
    end

This example may not be the best, since we could avoid repetition just as easily using format.all:

    class MyMailer < ActionMailer::Base
      def hello
        mail do |format|
          format.all(:html, :text, :pdf, :png, :csv) { format "goodbye" }
        end
      end
    end

However, the syntax allowed by the PR is no less clear than that.  Is the following example any less clear than the above one?

    class MyMailer < ActionMailer::Base
      def hello
        mail(template_name: 'goodbye') do |format|
          format.all(:html, :text, :pdf, :png, :csv)
        end
      end
    end

**Comment by georgeclaghorn** [comment]
> It's not the equivalent to the code sample in your comment.

Right, sorry. Got the template names mixed up.

> However, the syntax allowed by the PR is no less clear than that.

IMO, it is.

**Comment by betesh** [comment]
>> However, the syntax allowed by the PR is no less clear than that.

> IMO, it is.

This syntax is already supported for the case where you are not passing a block.  This PR doesn't introduce new syntax, just more consistency.

**Comment by georgeclaghorn** [comment]
Right. I think the options are harder to reason about in the context of passing a block. The [documented case for passing a block](http://guides.rubyonrails.org/action_mailer_basics.html#mailer-views) is exactly the use case you described: "If you want more flexibility you can also pass a block and render specific templates or even render inline or text without using a template file."

**Comment by betesh** [comment]
> Right. I think the options are harder to reason about in the context of passing a block. 

That is why I was careful to document that `format.text { render }` will ignore the template_name option passed to `mail`.  I agree that that may not be intuitive, but I believe it is a rare case.

> The documented case for passing a block is exactly the one you described: "If you want more flexibility you can also pass a block and render specific templates or even render inline or text without using a template file."
That is a good reason to use a block **if you want more flexibility** then passing an options hash can support.  The goal of this PR was not more flexibility, but more DRY and a more consistent interface.

**Comment by rafaelfranca** [comment]
You have any example where `all` will not fit you case? I think it is very confusing this new option and how it changes the template lookup.

**Comment by betesh** [comment]
This PR was originally prompted by a situation where both the template name and the formats were being calculated on the fly.

    class MyMailer < ActionMailer::Base
      def some_mailer_method(args)
        # args may or may not have the key :template_name.
        # If it does not, the template_name should default to self.action_name

        if (some_condition)
          mail(args) # This works out-of-the-box
        else
          multipart_mail(args)
        end
      end

      private
      def multipart_mail(args)
        # How this PR would allow you to write this method:
        mail(args) do |format|
          format.all(:html, :text)
        end

        # How I tried to write this method when I realized the above does not work
        mail(args) do |format|
          format.all(:html, :text) { render (args[:template_name].to_s || action_name) }
        end
        # This does not work, because ActionMailer::Base#mail does not dup the hash before modifying it.
        # So if template_name key was present, it no longer is by the time it is evaluated in the block

        # How I actually coded this method:
        template_name = args.delete(:template_name).to_s || action_name
        mail(args) do |format|
          format.all(:html, :text) { render template_name }
        end
      end
    end

@rafaelfranca Does this answer your question about where `all` does not fit the case?  The issue isn't whether `all` works.  It's about avoiding duplication / making the multipart as simple as the one-part email.

**Comment by hundredwatt** [comment]
:+1:

I encountered this will implementing a plain-text only email option in a mailer where 2 actions share the same template. Here's a stripped down example:
```
  def full_email
    ...
    render_mailer
  end

  def summary_email
    ...
    render_mailer
  end

  def render_mailer
    mail(template_name: 'full_email') do |format|
      format.html unless plain_text?
      format.text
    end
  end
```

This resulted in a `ActionView::MissingTemplate` exception when I called `summary_email`

**Comment by byrnejb** [comment]
> That is why I was careful to document that format.text { render } will ignore the template_name
> option passed to mail. I agree that that may not be intuitive, but I believe it is a rare case.

This is a mistake in my opinion.  The principle of least surprise is violated and documenting that fact is not adequate compensation for such a departure.  If one wants to override in a subsequent block any of the options passed in the call to mail then the block should contain the keys to be overridden along with the values to use

```ruby
    mail( :to => recipients,
          :from => fm_address,
          :subject => subject,
          :template_name => "blog_notice",
          :template_path => File.dirname( __FILE__ ) + "/views"
        ) \
        do |format|
          format.text do
            render(
              :template_name => "blog_notice.text.erb",
              :template_path => File.dirname( __FILE__ ) + "/views"  )
          end
           format.html do
             render( < do something else but look for blog_notice.html.{erb,json,....) 
                             in  File.dirname( __FILE__ ) + "/views" > )
             end
        end
```

This is what I believe most people familiar with Ruby and Rails expect to happen and when it does not it is extremely confusing as to why it does not.

**Comment by sgrif** [comment]
Sorry, I don't think the use case for this is compelling enough. I recommend trying this as a gem and seeing if that gets adoption.

**Comment by byrnejb** [comment]
In fact, the present behaviour of action-mailer-4.2 in this case is so counter-intuitive that I raised this question on stackoverflow: https://stackoverflow.com/questions/33267704/rails-4-2-mailer

**Comment by betesh** [comment]
@byrnejb I want to make sure I understand you correctly:

1) This PR only fixes half the problem, because it would be more intuitive to always use the explicit `template_name` when there is one, even in `format.text {render }`

2) From the SO comment you linked to, it sounds like  `template_path` suffers from the same issue as `template_name`, and it would be appropriate to fix it in the same PR.

I'm not going to rush to address these points because this ticket is closed, but I want to document both those points in case the maintainers do agree to re-open.

**Comment by byrnejb** [comment]
On Thu, October 22, 2015 10:46, betesh wrote:
> @byrnejb I want to make sure I understand you correctly:
>
> 1) This PR only fixes half the problem, because it would be more
> intuitive to always use the explicit `template_name` when there is
> one, even in `format.text {render }`
>
> 2) From the SO comment you linked to, it sounds like  `template_path`
> suffers from the same issue as `template_name`, and it would be
> appropriate to fix it in the same PR.
>
> I'm not going to rush to address these points because this ticket is
> closed, but I want to document both those points in case the
> maintainers do agree to re-open.

I am not complete sure that I understand the problem myself.  I have a
specific situation that I am dealing with and trying to map that to
the more general case.

In my case I have an existing directory structure that contains a
mailer template that I wish to reuse in a web application.  I do not
want to copy that file to the standard RoR app/mailers sub-directory.
I also do not wish its name or location to depend upon the
action_controller that calls it. So I wish to specify the exact
location of the views to the mailer instance that I am using in the
web app.

I have not yet found any way to do this.  In my naivety I initially
tried this:

```ruby
    mail( :to => recipients,
          :from => fm_address,
          :subject => subject,
          :template_name => "hll_th_forex_commercial_rates_notice",
          :template_path => File.join(  "/",
                              File.dirname( __FILE__ ),
                              "/views" )
        )
```

But that did not work. I got this instead:

      Missing template
/home/byrnejb/Projects/Software/theHeart/code/hll_th_main/lib/hll_action_mailer/hll_th_forex_mailer/views/hll_th_forex_commercial_rates_notice
with "mailer". Searched in:
        *
"/home/byrnejb/Projects/Software/theHeart/code/hll_th_main/lib/hll_action_mailer/hll_th_forex_mailer/views"
       (ActionView::MissingTemplate)

Now, the files that I have are these:

ls -l
/home/byrnejb/Projects/Software/theHeart/code/hll_th_main/lib/hll_action_mailer/hll_th_forex_mailer/views/*

-rw-rw-r--. 1 byrnejb byrnejb  813 Oct 20 16:10
/home/byrnejb/Projects/Software/theHeart/code/hll_th_main/lib/hll_action_mailer/hll_th_forex_mailer/views/hll_th_forex_cacb_update_notice.text.erb

-rw-rw-r--. 1 byrnejb byrnejb 2010 Oct 20 16:10
/home/byrnejb/Projects/Software/theHeart/code/hll_th_main/lib/hll_action_mailer/hll_th_forex_mailer/views/hll_th_forex_commercial_rates_notice.text.erb


As I understood mailer to work one provides the base name of ones
templates to the mailer, or the mailer derives that name from the
method name that contains the call to mail, and then the mail method
appends the format (.text) and the generator (.erb) to arrive at the
actual name and searches the default and any provided path for a
match.  This is evidently not the case based on the results I obtained
and so I next tried this:

```ruby
    mail( :to => recipients,
          :from => fm_address,
          :subject => subject,
          :template_name =>
"hll_th_forex_commercial_rates_notice.text.erb",
          :template_path => File.join(  "/",
                              File.dirname( __FILE__ ),
                              "/views" )
        )
```

Specifying the explicit format and generator produced similar results:

      Missing template
/home/byrnejb/Projects/Software/theHeart/code/hll_th_main/lib/hll_action_mailer/hll_th_forex_mailer/views/hll_th_forex_commercial_rates_notice.text.erb
with "mailer". Searched in:
        *
"/home/byrnejb/Projects/Software/theHeart/code/hll_th_main/lib/hll_action_mailer/hll_th_forex_mailer/views"
       (ActionView::MissingTemplate)

So, at this juncture I tried working with the do render block with
even more bizarre (to me) results which I reproduced on my original
contents.  One of the artefacts of that experience is the presence of
the leading "/" in the template_path construction which the render
method evidently strips off and so I had to provide two. I understand
that I may not have grasped exactly how mailer is supposed to work
outside of a default Rails context but I cannot believe that something
that complains about the non-existence of a file that patently does
exist is itself working correctly.

ls -l
/home/byrnejb/Projects/Software/theHeart/code/hll_th_main/lib/hll_action_mailer/hll_th_forex_mailer/views/hll_th_forex_commercial_rates_notice.text.erb

-rw-rw-r--. 1 byrnejb byrnejb 2010 Oct 20 16:10
/home/byrnejb/Projects/Software/theHeart/code/hll_th_main/lib/hll_action_mailer/hll_th_forex_mailer/views/hll_th_forex_commercial_rates_notice.text.erb

So at this point action mailer is unusable for me in this application
and I am casting about for a replacement.

And I have to say again.  The implementation of this gem runs counter
to almost all my expectations.  I cannot fathom why a method that
provides for and is told exactly where to find an absolute pathname
known to exist does not do so.  If I am doing something obviously
wrong then I cannot see it.  I am not getting the results that I
expect and that I believe are reasonable expectations.

Unless I am repeatedly overlooking some subtle typo or have a
fundamental misapprehension of what this thing is supposed to do and
how it is supposed to be told how to do it then I have to think that
it is unusable outside of the RoR standard environment.

And yet this same controller works in a stand-alone application that
uses an earlier version of AM, albeit with slightly different syntax:

```ruby
    mail( :to => recipients, :from => fm_address, :subject => subject )\
      do |format|
        format.text do render( "views/hll_th_forex_cacb_update_notice"
) end
      end
  end
```

but using the same directory structure and view file names.

This does not work at all in AM-4.2 inside a full rails application.


-- 
***          e-Mail is NOT a SECURE channel          ***
        Do NOT transmit sensitive data via e-Mail
James B. Byrne                mailto:ByrneJB@Harte-Lyne.ca
Harte & Lyne Limited          http://www.harte-lyne.ca
9 Brockley Drive              vox: +1 905 561 1241
Hamilton, Ontario             fax: +1 905 561 0757
Canada  L8E 3C3

**Pull request closed without merging**
