### PR TITLE
docs: fix typo `articles_path`

### PR DESCRIPTION
**Pull request by tyankatsu0105**
### Motivation / Background

This Pull Request has been created because there is an typo in docs(getting_started)

### Detail

This Pull Request changes [REPLACE ME]

### Checklist

Before submitting the PR make sure the following are checked:

* [x] This Pull Request is related to one change. Changes that are unrelated should be opened in separate PRs.
* [x] Commit message has a detailed description of what changed and why. If this PR fixes a related issue include it in the commit message. Ex: `[Fix #issue-number]`
* [x] Tests are added or updated if you fix a bug or add a feature.
* [ ] CHANGELOG files are updated for the changed libraries if there is a behavior change or additional feature. Minor bug fixes and documentation changes should not be included.

### CODE REVIEW

**Comment by fatkodima** [comment]
That is correct. `articles_path` is for working with collections, like `GET /articles` .

**Comment by tyankatsu0105** [comment]
@fatkodima 
Thanks for speedy reply and I'm sorry for my misunderstand PR...

I'm beginner at Rails. I don't know why my application's this line is not work.
It not work when I click this link.
Could you tell me the reason?
https://github.com/tyankatsu0105/bulletin-board/blob/adba3d5db151c5e14c1c341ce71f1503fc587900/server/app/views/articles/show.html.erb#L7

**Comment by fatkodima** [comment]
I am not familiar with turbo, maybe this is the reason. Better to use stackoverflow for such questions.

**Comment by tyankatsu0105** [comment]
Thanks!!

**Pull request closed without merging**
