### PR TITLE
Disable Active Record partial_inserts by default in Rails 7.0

### PR DESCRIPTION
**Pull request by casperisfine**
Ref: https://github.com/rails/rails/pull/42355

[The justification for `partial_inserts` back in 2012](https://github.com/rails/rails/commit/144e8691cbfb8bba77f18cfe68d5e7fd48887f5e) was:

> This is more efficient, and also means that it will be safe to remove database columns without getting subsequent errors in running app processes (so long as the code in those processes doesn't contain any references to the removed column).

But since then `ignored_columns` is a much more reliable way to safely remove a column, and I doubt the reduced query size really help much.

Additionally, `partial_inserts` prevent removing the default value of a column in a safe way.

cc @matthieuprat

### CODE REVIEW

**Comment by matthieuprat** [comment]
Thank you for following up!

**Comment by ghiculescu** [comment]
This needs an entry in new framework defaults.

**Comment by byroot** [comment]
oops. Will do.

**Comment by byroot** [comment]
https://github.com/rails/rails/commit/7bcfe447eb7404d8e216e26f1609240039ac9a8a

**Comment by SkipKayhil** [comment]
> I wonder if we could write a lint rule for that 🤔

I think this is a good idea and I'd be willing to work on it. Do y'all think it belongs in `rubocop-rails` if its an internal framework rule? (and if not, where do y'all think the best place would be?)

**Comment by ghiculescu** [comment]
https://github.com/rails/rails/tree/main/tools feels like a good home for it. `rubocop-rails` is for users of Rails apps.

**Comment by javierjulio** [comment]
@ghiculescu @byroot I've noticed with other new Rails 7 framework default related PRs that you've had discussions where some may not apply correctly from the file but have to be declared earlier in the `config/application.rb` file for it to take effect.

I'm noticing with this `partial_inserts` flag that if its flipped (uncommented) in `config/initializers/new_framework_defaults_7_0.rb` and I run a rails console to insert a model with a column that has a database default, it is **NOT** taking effect but if I move it to `config/application.rb` it does. I also tested this with a rails server and form submission (SQL insert) to ensure it's not isolated to a rails console and the same issue applies there.

My conclusion is flipping this flag in `config/initializers/new_framework_defaults_7_0.rb` is not taking any effect if the app is still loading 6.1 defaults. It has to be moved to the `config/application.rb` file for it to switch to the new default. 😔

Should the comments for this flag in that defaults file be updated to follow a similar pattern like with the `cache_format_version` and `disable_to_s_conversion` changes to ensure the new default is taking effect?

**Comment by ghiculescu** [comment]
No, it should be flippable from new_framework_defaults.

Are you able to write a test to confirm it? The test would go in here: https://github.com/rails/rails/blob/main/railties/test/application/configuration_test.rb

Alternatively if you can show a minimal app or [executable test case](https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case) to show the issue that would be really helpful.

**Comment by javierjulio** [comment]
@ghiculescu now dealing with Zeitwerk and new framework defaults, I figured we were referencing ActiveRecord elsewhere which didn't occur to me at the time. This was the case and is why flipping the default in the `new_framework_defaults_7_0.rb` file had no effect. Sorry about that.

We had a `config/initializers/activerecord.rb` file with the following, I believe so we don't calculate this boolean each time we need it.

```
ACTIVE_RECORD_USING_REPLICAS = ActiveRecord::Base.configurations
  .configs_for(env_name: Rails.env, include_hidden: true)
  .any?(&:replica?)
```

Once I removed the reference (set constant to `false`) and the new `partial_inserts` default worked as expected. I've moved this constant to the helper class where it's used as its likely safer to reference `ActiveRecord::Base.configurations` then. Thanks and again sorry about that!

**Comment by ghiculescu** [comment]
All good. Thanks for the followup!

You probably want to use a lazy load hook for stuff like that if it's in an initializer: https://api.rubyonrails.org/classes/ActiveSupport/LazyLoadHooks.html

**Comment by javierjulio** [comment]
I put back the initializer `config/initializers/activerecord.rb` we had and updated it to use the hook you suggested as shown below and it's working as expected with the new default.

```ruby
ActiveSupport.on_load(:active_record) do
  ACTIVE_RECORD_USING_REPLICAS = ActiveRecord::Base.configurations
    .configs_for(env_name: Rails.env, include_hidden: true)
    .any?(&:replica?)
end
```

I should have realized we would need this when upgrading to Rails 7 since we had to do it elsewhere for registering custom ActiveModel and ActiveRecord types. Thanks again! ❤️

**Pull request merged**
