### PR TITLE
Fix many ruby 2.7 warnings for the 6.0 stable branch

### PR DESCRIPTION
**Pull request by casperisfine**
When possible I simply cherry-picked fixes from the master branch, but sometimes I had to redo them manually.

Here I started with ActiveSupport, I'm not sure I eliminated them all yet because the test suite is segfaulting on my machine. 

This is still a work in progress, but opening a PR give me a CI run which is helpful.

cc @rafaelfranca @Edouard-chin

### CODE REVIEW

**Comment by kaspth** [comment]
Looks like the build is green, do you want to get this part merged and start up a PR for the remaining warnings or just all in one?

**Comment by casperisfine** [comment]
@kaspth there was only one actionable warning left in activesupport, so I update the PR. 

I think it should be good to go after that.

There is still a huge chunk of warnings coming from `tzinfo`, but to get them fixed we need to upgrade to a new major version of `tzinfo`, so it doesn't seem ok for a tiny release.

**Comment by casperisfine** [comment]
Oh and the suite breaks because of a Deadlock, but it's also the case on master.

**Comment by kaspth** [comment]
Thanks!

> There is still a huge chunk of warnings coming from `tzinfo`, but to get them fixed we need to upgrade to a new major version of `tzinfo`, so it doesn't seem ok for a tiny release.

Yeah, that'll probably take some work. What do you mean about tiny release? Should be perfectly safe to require a newer tzinfo for 6.1, no?

**Comment by casperisfine** [comment]
> What do you mean about tiny release

Tiny as in `MAJOR.MINOR.TINY`. Only the new 2.0 has Ruby 2.7 fixes, but the interface changed a lot (see https://github.com/rails/rails/compare/master...Shopify:update-tzinfo-2.0, and it's not even green yet).

So it would be complicated to bump tzinfo to 2.0 in Rails 6.0.X.

That's why I started working on a PR to tzinfo to get a new 2.7 compatible 1.x release: https://github.com/tzinfo/tzinfo/pull/111

**Comment by kaspth** [comment]
Perfect!

**Comment by lucascaton** [comment]
Hi there! 👋

Is there any plans to release this fix in a `v6.0.3` or something, to solve the warnings?

Thanks!

**Comment by casperisfine** [comment]
I can't say when `6.0.3` will be released, AFAIK it still need a couple bugfixes. In the meantime you can point your Gemfile to the `6-0-stable` branch.

**Comment by lucascaton** [comment]
Got it, thanks @casperisfine! I thought it was fully fixed already :)

**Comment by sergey-alekseev** [comment]
Rails 6.0.3 has been [released](https://weblog.rubyonrails.org/2020/5/6/Rails-6-0-3-has-been-released/) :tada:  

---
To @lucascaton and everyone else who is subscribed and waiting.

**Pull request merged**
