### PR TITLE
Titleize inflector squashing "Id" at the end of a string

### PR DESCRIPTION
**Pull request by mubashirhanif**
Refer [Issue#26011](https://github.com/rails/rails/issues/26011)

The following changes were made based on the discussion.
## Changes:
1. Added `keep_id_suffix` check to [humanize](https://github.com/rails/rails/blob/f2489f493b794ee83a86e746b6240031acb8994e/activesupport/lib/active_support/inflector/methods.rb#L129).
2. Added `options` hash to [titleize](https://github.com/rails/rails/blob/f2489f493b794ee83a86e746b6240031acb8994e/activesupport/lib/active_support/inflector/methods.rb#L162) to utilize `keep_id_suffix` flag and keep the trailing '_id' in a string.
3. Added additional tests for both `humanize` and `titleize` with the `keep_id_suffix` set to `true`.

### CODE REVIEW

**Comment by starswan** [comment]
Maybe an extra test with an 'id' in the middle would be useful? Otherwise +1

**Comment by KlotzAndrew** [comment]
Hey! Can I help with getting this through?

**Comment by mubashirhanif** [comment]
I want to close this pull request to start a new one, because this branch has got a lot messy.
Please refer to new [PR#28480](https://github.com/rails/rails/pull/28480).

**Pull request closed without merging**
