### PR TITLE
Remove extra ast pass for Pattern#names

### PR DESCRIPTION
**Pull request by composerinteralia**
Before this commit #ast and #names were each doing a separate pass over
the journey ast. Since both of these methods are called for every route
definition, we can do that work up front in #initialize, consolidating
into a single pass through the ast.

I think we can also get rid of the `spec` alias, but I am planning to do
that in a separate PR to limit the scope of this one.

This is similar to the work done in #38901 and #39903, and the benchmark
results are similar:

```
Warming up --------------------------------------
              before     7.791k i/100ms
               after    15.843k i/100ms
Calculating -------------------------------------
              before     78.081k (± 1.4%) i/s -    397.341k in   5.089797s
               after    159.093k (± 1.8%) i/s -    807.993k in   5.080367s

Comparison:
               after:   159093.1 i/s
              before:    78081.2 i/s - 2.04x  (± 0.00) slower

MEMORY
Calculating -------------------------------------
              before   240.000  memsize (    40.000  retained)
                         4.000  objects (     1.000  retained)
                         0.000  strings (     0.000  retained)
               after   120.000  memsize (    40.000  retained)
                         2.000  objects (     1.000  retained)
                         0.000  strings (     0.000  retained)

Comparison:
               after:        120 allocated
              before:        240 allocated - 2.00x more
```

### CODE REVIEW

**Comment by eugeneius** [comment]
> Since both of these methods are called for every route definition 

This isn't quite true: `ast` is only called for routes that are [anchored](https://github.com/rails/rails/blob/3a1007b196c9c4a484cd3309cf458414441a0d97/actionpack/lib/action_dispatch/journey/routes.rb#L44), and `names` is only called for routes that [have a name](https://github.com/rails/rails/blob/3a1007b196c9c4a484cd3309cf458414441a0d97/actionpack/lib/action_dispatch/routing/route_set.rb#L595).

If I remove [these deprecations](https://github.com/rails/rails/blob/3a1007b196c9c4a484cd3309cf458414441a0d97/actionpack/lib/action_dispatch/routing/route_set.rb#L597-L609) (which will be gone before the next release), the application I work on which has 3897 routes sees 3892 calls to `ast` and 1738 calls to `names`.

I haven't benchmarked it yet, but I wonder if the cost of eagerly building `names` for unnamed routes will outweigh the savings from avoiding two AST passes for named ones.

**Comment by composerinteralia** [comment]
Eep! Good call. Yeah that changes things. I'm going to close this PR for now, since I mainly opened it on the way to what I am working on in https://github.com/composerinteralia/rails/commit/1dfaec6fa20d4986a0602485b92748598b70a8af, where I try to combine some of the passes in path/pattern with those in routing/mapper (it's still a work in progress).

**Comment by eugeneius** [comment]
Nice, that looks promising! Thanks for working on this, by the way; as someone whose app has _nearly four thousand routes_ I'm always willing to review PRs that improve their performance 😁

**Comment by composerinteralia** [comment]
Yeah, that is a lot of routes. Removing these extra ast passes won't be a huge win, but I'm hoping to chip away at it little by little.

You may also have thoughts about https://github.com/rails/rails/pull/39916, which is rather similar to this one.

**Pull request closed without merging**
