### PR TITLE
Fix ActiveModel::SecurePassword int argument bug

### PR DESCRIPTION
**Pull request by meinac**
With this fix you can set integer values to password

### CODE REVIEW

**Comment by chancancode** [comment]
Can you explain your use case a bit?

**Comment by chancancode** [comment]
To elaborate, I don't like the idea of randomly cohering input for no reason - a password is conceptually a string to me, and passing anything else is most likely an error. So unless there is a compelling reason/use case for this behaviour, I would rather leave it to the caller to produce a string here.

**Comment by meinac** [comment]
Actually bcrypt ruby allows you to use integers. If client sends you the password field as integer and if you don't write a custom writer to change it to string then you will get an error `undefined method empty for fixnum`. I think overriding writer to set password to string is not elegant. If bcrypt allows you to use integers why this module does not?

**Comment by aditya-kapoor** [comment]
The password is conceptually perceived a string but we would lose the value for the input like 01234 where the `to_s` would yield `668`.

This is the same problem which was raised in this [issue](https://github.com/rails/rails/issues/21463).

**Comment by meinac** [comment]
Actually in this pull request I'm not changing the type of the given password to string. This pr just fix the issue on checking whether given password is blank or not.

**Comment by rafaelfranca** [comment]
> If client sends you the password field as integer

This is a client error for me. So the client should be changed. How would a user input an integer password? Forms only return string parameters.

That said I'm closing this PR. Thanks

**Comment by meinac** [comment]
> Forms only return string parameters

But forms are not only way to interact with a server side application via HTTP. I saw this error while working on an API which accepts request from different applications like mobile apps and also desktop apps. Even if this is a client side error Rails application shouldn't respond with an internal server error by default.

**Comment by rafaelfranca** [comment]
Neither accept wrong data. Clients should always send strings as password.
If the clients are not you may want to teach them to do that writing a
validation. In my opinion this is validation concern.

**Comment by meinac** [comment]
> In my opinion this is validation concern

Yes you are right, this is a validation concern but in this case we are facing with another bug or performance issue about secure password module.
SecurePassword works before ActiveModel validations. So If you have a validation like length validation to check whether password is in 4...20 range or not, SecurePassword works before this validation. I think this is wrong because it tries to build a hash for password attribute even if it's not valid. For example in case of invalid password you can respond with a JSON in 20ms but with SecurePassword it will take around 90ms because it tries to build hash of invalid password. If we can build a DSL for password validation to work before secure password or SecurePassword module respects to the ActiveModel validations then we can check whether password is string or not or any kind of validation without performance problems. You may say 90ms minus 20ms is equal to 70ms and you can not conquer the world around 70ms but if you have an API which works for an application targets around 1 billion people than you have to take care of 1ms. I would like to fix this performance issue and I think it will solve the problem mentioned in this pr too.

**Comment by rafaelfranca** [comment]
Let's explore if we can change this behavior for sure.

**Comment by chancancode** [comment]
> The password is conceptually perceived a string but we would lose the value for the input like 01234 where the to_s would yield 668.

This is incorrect.

I believe you are describing something like this:

```irb
> 01234.to_s
=> "668"
```

The problem here is not the `to_s` call; it is that number **literals** starting with a `0` is interpreted as an Base 8 number. You can observe this without the `to_s` call:

```irb
> 01234
=> 668
```

As you can see, `to_s` or not doesn't change anything. Further, this is only a problem if in `irb` or if you are typing that in source. Anyway, this is irrelevant for the discussion here.

But this also brings up a good point of why sending the passwords as an integer from the client is a bad idea: *how do you send a password with a leading 0*? (The answer is you cannot; a number literal with a leading 0 is illegal JSON; and even if it parses in some non-compliant parsers, you will probably lose data or get incorrect results.)

* * *

So hopefully after that, we can all agree that *sending* passwords from the client as integers is fundamentally *incorrect*, so you should not do it.

However, if you are stuck with old/broken clients, I understand that it might not be easy to change all of them. **However**, this is really no different than handling any legacy clients that has bugs or send things in an old format. The correct place to handle this is on the controller, imo. If you know that your client is sending bad data, you can detect that in the controller, and fix the data before passing it into the rest of the system.

I think both @rafaelfranca and I maintain the position that doing that and containing the damage is better than bending our other APIs everywhere else.

**Pull request closed without merging**
