### PR TITLE
Add `activesupport` bug report template

### PR DESCRIPTION
**Pull request by seanpdoyle**
Introduce Active Support bug report templates for contributors to reproduce issues with a failing `Minitest::Test`.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
That is what generic is for. We don't name is with the framework name because we don't want every single framework to have its own bug report template

**Comment by seanpdoyle** [comment]
Maybe I'm misinterpreting the motivation for the specialized bug report templates, but out of all the frameworks that make up Rails, Active Support is the one that's most likely to be used **outside** the framework itself in an isolated way. 

Starting from that assumption, wouldn't it be a good candidate to have its own dedicated bug report template so that consumers can reproduce bugs outside the context of the larger Rails framework?

**Comment by rafaelfranca** [comment]
> Starting from that assumption, wouldn't it be a good candidate to have its own dedicated bug report template so that consumers can reproduce bugs outside the context of the larger Rails framework?

Isn't that generic? That is exactly what it is for `reproduce bugs outside the context of the larger Rails framework`

**Comment by rafaelfranca** [comment]
I think I see where your confusion is on. It is the fact that generic has `gem 'rails` line on the inline gemfile. That doesn't load the entire Rails framework. It installs it, yes, but it doesn't loads it. Only `require` loads things.

As you can see [generic only requires `active_support`](https://github.com/rails/rails/blob/main/guides/bug_report_templates/generic.rb#L15). So your script is exactly the same as generic, installing less things, but testing the same thing.

**Comment by seanpdoyle** [comment]
> So your script is exactly the same as generic, installing less things, but testing the same thing.

Could we re-open this PR so that I can exclude the new template file, but include the addition of an Active Support bug template that links to `generic.rb`?

**Comment by rafaelfranca** [comment]
I don't understand why we would do that. Just to list all frameworks?

We should read that page as: If a framework needs something specific, it will be different. If not, it is the generic one.

**Comment by matthewd** [comment]
I could imagine finding a gentle rephrasing of the generic link to include the words "Active Support", just because yes the shape of the rest of the list might have people scanning for it... and, per above, it's probably the headline use case of that template. 

"other issues, including Active Support"?

I'm honestly not a huge fan of the overall shape of the list in its current state -- like many parts of the guides, I feel like it started out reasonable and has now grown to be unwieldy. (And "link" as the link text 😟)

**Pull request closed without merging**
