### PR TITLE
Add rejoins

### PR DESCRIPTION
**Pull request by st0012**
Hello, my project recently need to rejoin some query, so I add the `rejoins` method.
And this is my first time contribute Rails, so there might be lack of test or I made some mistake, hope that won't bother you too much.

### CODE REVIEW

**Comment by senny** [comment]
@st0012 would you mind providing an example that showcases the need for `rejoins`. This will help to establish some context around the addition.

**Comment by st0012** [comment]
My project need a sortable module that can provide single api for sort model, like
```ruby
# recipe class
class Recipe < ActiveRecrod::Base
  belongs_to :user
  has_many :favorites
  sortable_on :id, with: :favorites, as: :favorited_at # use favorite's id to sort
end

# usage
user.favorite_recipes.sort_by_param(:favorited_at)
```
so the `sortable` module has an method to do the sorting

```ruby
    def use_param_to_sort(param)
      if sort_column[:table_name]
        # if sort by relation's column, we need to join other table to do the sorting
        joins(sort_column[:association_name]).reorder("`#{sort_column[:table_name]}`.#{sort_column[:column_name]} #{sort_column[:sort_type]}").distinct
      else
        # sort by same table's column
        reorder("`#{table_name}`.#{sort_column[:column_name]} #{sort_column[:sort_type]}")
      end
    end
```

But this will have a problem that if we have joined the same table before the sorting method, it will join twice after the sort_by_param method was called. So I need a method to clean up `joins_value` with something like `rejoins` before the `use_param_to_sort` method. And I think the scenario of using `rejoins` is a lot like the `reorder` method.

**Comment by senny** [comment]
@st0012 won't using `rejoins` in your example lead to another problem, where you reset a join that is actually necessary for the original query to work?

```ruby
Recipe.joins(:ingerdients).where("ingredients.amount > 100").sort_by_param(:favorited_at)
```

Using `rejoins` this will clear the `:ingredients` join and leave you with a broken query.

I'm not sure that `rejoins` is something as useful as `rewhere`. There are other parts of the relation that are dependent that a specific relation has been joined. For example `order` and `where`. using `rejoins` has the potential to break a lot of queries.

**Comment by st0012** [comment]
I think I need to provide a little more details about my situation, sorry.
Here's my user model:
```ruby
class User < ActiveRecord::Base
  has_many :favorites, -> { order(id: :desc) }
  has_many :favorite_recipes, through: :favorites, source: :recipe
end
```
And if I call `user.favorite_recipes`, activerecord will join favorites once. So if I joins favorites in my sorting method again, it will be double join.
The below SQL is generated when I call `user.favorite_recipes.sort_by_param(:favorited_at)` without `rejoins`
```sql
SELECT DISTINCT `recipes`.* FROM `recipes` INNER JOIN `favorites` `favorites_recipes` ON `favorites_recipes`.`recipe_id` = `recipes`.`id` INNER JOIN `favorites` ON `recipes`.`id` = `favorites`.`recipe_id` WHERE `recipes`.`deleted_at` IS NULL AND (`recipes`.`published_at` IS NOT NULL) AND `favorites`.`user_id` = 91  ORDER BY `favorites`.id DESC
```
It joins the `favorites` table twice. And this is what generated after I add rejoins:

```sql
SELECT DISTINCT `recipes`.* FROM `recipes` INNER JOIN `favorites` ON `favorites`.`recipe_id` = `recipes`.`id` WHERE `recipes`.`deleted_at` IS NULL AND (`recipes`.`published_at` IS NOT NULL) AND `favorites`.`user_id` = 91  ORDER BY `favorites`.id DESC
```

For now I only come up with this scenario that needs `rejoins`, but there might be other cases need it too I guess.

**Comment by senny** [comment]
@st0012 I understand your use-case but there problems I described [above](https://github.com/rails/rails/pull/21600#issuecomment-139858222) with the concept of `rejoins` that don't exist in the case of `rewhere` or `reorder`.

You could work around the issue by passing an option to `sort_by_param`. For example:

```ruby
user.sort_by_param(:favorited_at, join: true)
user.favorite_recipes.sort_by_param(:favorited_at, join: false)
```

Or design `sort_by_param` in a way that expects the necessary joins have happened in advance.

While these are not optimal I don't like the possible issues that `rejoins` bring to the table.

Let's get some more options though. /cc @rafaelfranca @sgrif

**Comment by sgrif** [comment]
I agree with everything @senny has mentioned on this issue. I think there simply isn't a compelling enogh use case presented for this.

**Comment by st0012** [comment]
ok, thanks for the advices :smile:

**Comment by st0012** [comment]
@senny sorry, one more question 
The joins method now using += method to add join values, would it be better checking duplicate value before adding new value?

**Comment by senny** [comment]
@st0012 honestly, I'm not sure. I can't think of an example where you'd want the exact same join to happen twice. If that's never a use-case we can check before adding. Let's wait for @sgrif , maybe he knows more.

**Pull request closed without merging**
