### PR TITLE
Update seeds.rb.tt

### PR DESCRIPTION
**Pull request by Cleggameg**
Rahm Emanual doesn't deserve to be in Rails.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Thank you for the pull request. This is a personal opinion and can not drive this kind of change. To avoid that in the future can you change the example to be less subjective to personal opinions?

Maybe:

```ruby
frameworks = Framework.create([{ name: 'Ruby on Rails' }, { name: 'Sinatra' }])
Developers.create(name: 'David', city: frameworks.first)
```

**Comment by shakycode** [comment]
Agreed, personal opinions don't belong in the repo

**Comment by Cleggameg** [comment]
Fair enough.

**Comment by rafaelfranca** [comment]
Hahaha. Better yet. I'll merge as soon the tests finish. Thank you

**Comment by Cleggameg** [comment]
Awesome, the city of Chicago thanks you!!

**Comment by nateberkopec** [comment]
Needs a squash, I think.

**Comment by rafaelfranca** [comment]
Merged in 207e2ad9e7be393d871b14da55d23343a22326f6

**Pull request closed without merging**
