### PR TITLE
ActiveSupport - add missing require

### PR DESCRIPTION
**Pull request by Schmitze333**
### Summary

When using #in_time_zone on a Time object the following error occurs:

```
.../gems/activesupport-7.0.2.2/lib/active_support/xml_mini.rb:184:in `current_thread_backend': uninitialized constant ActiveSupport::XmlMini::IsolatedExecutionState (NameError)
  from .../gems/activesupport-7.0.2.2/lib/active_support/xml_mini.rb:103:in `backend='
  from .../gems/activesupport-7.0.2.2/lib/active_support/xml_mini.rb:201:in `<module:ActiveSupport>'
  from .../gems/activesupport-7.0.2.2/lib/active_support/xml_mini.rb:11:in `<top (required)>'
  from .../gems/activesupport-7.0.2.2/lib/active_support/core_ext/array/conversions.rb:3:in `require'
  from .../gems/activesupport-7.0.2.2/lib/active_support/core_ext/array/conversions.rb:3:in `<top (required)>'
  from .../gems/activesupport-7.0.2.2/lib/active_support/duration.rb:3:in `require'
  from .../gems/activesupport-7.0.2.2/lib/active_support/duration.rb:3:in `<top (required)>'
  from .../gems/activesupport-7.0.2.2/lib/active_support/time_with_zone.rb:5:in `require'
  from .../gems/activesupport-7.0.2.2/lib/active_support/time_with_zone.rb:5:in `<top (required)>'
  from .../gems/activesupport-7.0.2.2/lib/active_support/core_ext/time/zones.rb:3:in `require'
  from .../gems/activesupport-7.0.2.2/lib/active_support/core_ext/time/zones.rb:3:in `<top (required)>'
```

This PR adds the missing require in `active_support/xml_mini.rb`.

### CODE REVIEW

**Comment by Schmitze333** [comment]
Maybe another occurrence of https://github.com/rails/rails/issues/43851.

**Comment by byroot** [comment]
cc @matthewd, anything blocking https://github.com/rails/rails/pull/44340 ?

@Schmitze333, yes you must `require "active_support"` before requiring any subparts. That may change in the future, but for now that's the fix you are looking for.

**Comment by Schmitze333** [comment]
@byroot 
Of course 🤦 . I'm sorry for wasting your time!

**Comment by byroot** [comment]
No worries. It's not really evident and you are far from the first one bitten by this.

**Comment by arthurnn** [comment]
I believe this should be merged in to keep consistency with AS framework files. 
A user of AS should be able to only require the files it needs and not everything. Thus, a file like activesupport/lib/active_support/xml_mini.rb requires all dependencies it needs at the top. But one: the `IsolatedExecutionState` 

For the xml_mini.rb file be self-suficient, we need to require `IsolatedExecutionState` class, like proposed here.

**Pull request closed without merging**
