### PR TITLE
Changed ActiveJob::Base to ApplicationJob in the Active Job guide [ci…

### PR DESCRIPTION
**Pull request by nikhilthombare**
### Summary

Provide a general description of the code changes in your pull
request... were there any bugs you had fixed? If so, mention them. If
these bugs have open GitHub issues, be sure to tag them here as well,
to keep the conversation linked together.
### Other Information

If there's anything else that's important and relevant to your pull
request, mention that information here. This could include
benchmarks, or other information.

Finally, if your pull request affects documentation or any non-code
changes, guidelines for those changes are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#contributing-to-the-rails-documentation)

Thanks for contributing to Rails!

… skip]

@prathamesh-sonpatki

### CODE REVIEW

**Comment by prathamesh-sonpatki** [comment]
Thanks a lot @nikhilthombare!

**Comment by prathamesh-sonpatki** [comment]
@nikhilthombare In future you can add `Fixes #25378` - The issue number that you were trying to fix in the commit message description and Github will close that issue automatically - https://help.github.com/articles/closing-issues-via-commit-messages/.

Thanks a lot :smile:

**Comment by prathamesh-sonpatki** [comment]
@rafaelfranca This needs to be backported.

**Comment by maclover7** [comment]
Backported to `5-0-stable` via 8b77387379aa2d40fb0c8db847e28567e392f3f0, `5-0-0` via 8b77387379aa2d40fb0c8db847e28567e392f3f0 (same commit).

**Pull request merged**
