### PR TITLE
Edge is tracking v7.1.0.alpha

### PR DESCRIPTION
**Pull request by peterberkenbosch**
### Summary

Edge is using v7.0.0.alpha2 as version currently, this commit updates that to the latest v7.0.0.rc1, this might need to be v7.0.0.rc2 or even v7.0.0?

### CODE REVIEW

**Comment by peterberkenbosch** [comment]
So reading up and this should be `7.1.0.alpha` really? Updated the PR just in case that's correct.

**Comment by rafaelfranca** [comment]
Thank you for the PR. It is incomplete though, so I'll do it myself.

**Comment by peterberkenbosch** [comment]
@rafaelfranca thanks! Looking at your PR what I missed ;)

**Comment by peterberkenbosch** [comment]
actually pretty silly I missed all the `gem_version.rb` and `package.json` files. Next time :)

**Pull request closed without merging**
