### PR TITLE
Capitalize submit button value

### PR DESCRIPTION
**Pull request by meinac**
Capitalize the value of submit button.

Closes #791.

### CODE REVIEW

**Comment by meinac** [comment]
/cc @spastorino 

I've discovered that there is a failing test case in action view even with already up-to-date master branch. I'll have a look at [this](https://github.com/rails/rails/blob/master/actionview/test/actionpack/controller/render_test.rb#L747).

Also there are some deprecation messages, I'll take a look at these too.

**Comment by matthewd** [comment]
Case-mangling and i18n really don't mix very well. :confused:

This works for the `de` translation only because it happens to put the noun at the beginning of the sentence.

**Comment by rafaelfranca** [comment]
Yeah, agree with @matthewd. I don't see any way to fix this issue in a satisfactory way so I prefer the keep the behavior the same it is since Rails 3.0.

Thank you for the pull request.

**Comment by meinac** [comment]
@matthewd do you know any case this fix doesn't work for?
To me there are only 2 cases;
+ Model name at the beginning of the sentence(de, tr, az, ...)
+ Model name inside of the sentence(en, ...)

**Comment by rafaelfranca** [comment]
Model name inside the sentence and the model name required to be capitalized.

**Comment by meinac** [comment]
:+1: I see, you are right. There may be some languages with noun should be capitalized inside of the sentence.
Thanks.

**Pull request closed without merging**
