### PR TITLE
Remove `DEFAULT NULL` for primary key column to support MySQL 5.7.3

### PR DESCRIPTION
**Pull request by yahonda**
This pull request addresses ActiveRecord unit tests error with MySQL 5.7.3_m13.

``` ruby
Mysql::Error: All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead: CREATE TABLE `accounts` (`id` int(11) DEFAULT NULL auto_increment PRIMARY KEY, `firm_id` int(11), `firm_name` varchar(255), `credit_limit` int(11)) ENGINE=InnoDB (ActiveRecord::StatementInvalid)
```

It would probably because of this [fix](http://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-3.html)

``` quote
Columns in a PRIMARY KEY must be NOT NULL, but if declared explicitly as NULL produced no error. Now an error occurs. For example, a statement such as CREATE TABLE t (i INT NULL PRIMARY KEY) is rejected. The same occurs for similar ALTER TABLE statements. (Bug #13995622, Bug #66987, Bug #15967545, Bug #16545198)
```

Also I was trying to find the reason why primary column can be `DEFAULT NULL` but it is set from the beginning.
https://github.com/rails/rails/commit/eac7cf0b0608132673220d9045b8ff51dc0804e1

``` ruby
 :primary_key => "int(11) DEFAULT NULL auto_increment PRIMARY KEY",
```

### CODE REVIEW

**Comment by pjg** [comment]
With Rails 2.3.5 and MySQL version 5.7.9 you need to have this bit as an initializer in `config/initializers/abstract_mysql_adapter.rb`:

```ruby
class ActiveRecord::ConnectionAdapters::MysqlAdapter
  NATIVE_DATABASE_TYPES[:primary_key] = "int(11) auto_increment PRIMARY KEY"
end
```

**Comment by lucascaton** [comment]
@pjg It worked here, thanks!

My 2 cents:
If anyone is using the gem `mysql2`, just use the class `ActiveRecord::ConnectionAdapters::Mysql2Adapter` instead.

**Comment by wbotelhos** [comment]
I had the same problem on MySQL 5.6.27 and 5.7.9 too.

@shyam-habarakada it worked, thanks!

**Comment by adlersantos** [comment]
@shyam-habarakada Thanks mate! The monkey patch works. Using Rails 4.0.13 and MySQL 5.7.9

The line
```ruby
require File.expand_path('../../lib/patches/abstract_mysql_adapter', __FILE__)
```
should go after `AppName::Application.initialize!` in `environment.rb`.

**Comment by BenjimanWhite** [comment]
@adlersantos @wbotelhos @lucascaton @pjg did any of you encounter the following issue while patching: https://gist.github.com/BenjimanWhite/3a8598c92ec8bdedd7f6

Creating the abstract_mysql_adapter.rb file and requiring it solved an issue I had when I ran `rake db:setup` but I am now encountering some issues (error is in the gist above) when I run specs.

Any ideas? Thanks for taking a look if you have the time =]

**Comment by wbotelhos** [comment]
If you have a dumped database it will work normally.
But during the `setup`, or similars, your schema will be loaded and MySQL will check the the null primary keys and raise the error.

By the way, using it on `config/initializers` is easier to avoid the manual `require`.

**Comment by pjg** [comment]
@BenjimanWhite the error you're seeing is because of the Rails' load order. Your `require` is executed before the full stack is loaded, so `ActiveRecord` is not yet available. If you use my solution (putting the whole thing inside `config/initializers/abstract_mysql_adapter.rb`) it should work.

**Comment by learnmews** [comment]
@pjg your patch worked for me as well with Rails 3.2 and MySQL 5.7. Thanks

**Comment by bater** [comment]
Thanks @pjg , my evironment is 
ruby 2.1.5p273
Rails 3.2.13
mysqld  Ver 5.7.9 for osx10.10 on x86_64

And it worked!!

**Comment by clemaster** [comment]
Had The same issue as @BenjimanWhite with pjg's solution.  Was getting this message with pjg's initializer: NameError: uninitialized constant ActiveRecord::ConnectionAdapters::MysqlAdapter::NATIVE_DATABASE_TYPES

Solved the issue by improving on pjs's solution.  Moved the initializer further down in the load order of initializers.  Renamed initializers/abstract_mysql_adapter.rb to z_abstract_mysql_adapter.rb.   That worked.  Tried renaming back and migrating down and up to make sure that was the solution.  Looks like initializer active_record_base.rb loads MysqlAdapters.

**Comment by wvengen** [comment]
For Rails 3, I needed to do this (initializer rename didn't work)

```ruby
# config/initializers/abstract_mysql_adapter.rb
ActiveSupport.on_load(:active_record) do
  class ActiveRecord::ConnectionAdapters::Mysql2Adapter
    NATIVE_DATABASE_TYPES[:primary_key] = "int(11) auto_increment PRIMARY KEY"
  end
end
```

**Comment by medicsmarket** [comment]
I used this command ` require File.expand_path('../../config/initializers/abstract_mysql2_adapter', __FILE__)`
and still its not loading the file
`LoadError: cannot load such file --config/initializers/abstract_mysql2_adapter`

**Comment by Bijendra** [comment]
@medicsmarket From which file you are trying to require this, 
say i'm in app/config/application.rb and a file at app/config/file1.rb
```
application.rb

require File.expand_path('../file1', __FILE__)
```

This will work.

**Comment by adayNU** [comment]
Did not have luck with the solutions above (My env: Rails 3.0.20, MySQL 5.7.13, Ruby 1.9.3p551). Was able to get around it by overwriting the ActiveRecord::ConnectionAdapters::ColumnDefinition class. See below:

```
class ActiveRecord::ConnectionAdapters::ColumnDefinition
  def sql_type
    type.to_sym == :primary_key ? 'int(11) auto_increment PRIMARY KEY' : base.type_to_sql(type.to_sym, limit, precision, scale) rescue type
  end 
end
```

**Comment by rishabh-tripathi** [comment]
For activerecord-3.2.11, this worked for me,

require 'active_record/connection_adapters/abstract_mysql_adapter'
class ActiveRecord::ConnectionAdapters::AbstractMysqlAdapter
  NATIVE_DATABASE_TYPES[:primary_key] = "int(11) auto_increment PRIMARY KEY"
end

**Comment by adlersantos** [comment]
A colleague encountered the same issue. If you've installed mysql through brew, [this SO answer](http://stackoverflow.com/questions/4359131/brew-install-mysql-on-mac-os/6378429#6378429) solved it seamlessly for us. 

Just sharing in case it works for some of us.

**Comment by nexar** [comment]
@adayNU's suggestion (29 June'16) finally worked for me!!  

Since I came across this problem much later, one idea I had for my config (Rails3.2 Ruby 1.9.3 and MySQL 5.7) was to update my mysql2 adapter to a later version which would have resolved this issue by now (Oct'17).  But I was worried whether anything else would break.

Just for info please can someone tell me whether I was on the right track with my thinking on this?

Thanks

**Pull request merged**
