### PR TITLE
Add full set of MySQL CLI options to support SSL authentication when using db:structure dump and load

### PR DESCRIPTION
**Pull request by drcapulet**
Backport of #20126 to 4.1-stable

### CODE REVIEW

**Comment by lukaszx0** [comment]
LGTM :+1:

**Comment by drcapulet** [comment]
Ping @matthewd, would it be possible to get this merged?

**Comment by lukaszx0** [comment]
Thanks @rafaelfranca !

**Comment by drcapulet** [comment]
Thanks @rafaelfranca!

**Pull request merged**
