### PR TITLE
[5-0-stable] Update bug report templates

### PR DESCRIPTION
**Pull request by bogdanvlviv**
Set Rails 5.0.7 in templates

### CODE REVIEW

**Comment by rafaelfranca** [comment]
No need to change those templates

**Comment by rafaelfranca** [comment]
I mean. The merge in this branch is fine, what I don't think is necessary is to bump the patch version in the template. The idea of this template is to match the users version, not the latest patch release of the series.

**Comment by kamipo** [comment]
I see, thanks for the detailed explanation. I agree with that.

**Comment by bogdanvlviv** [comment]
@rafaelfranca Thanks for the explanation.

I have a question in order to clarify:
> The merge in this branch is fine, what I don't think is necessary is to bump the patch version in the template. The idea of this template is to match the users version, not the latest patch release of the series.

Does this should work for `master` branch too, or only for `*-stable` branches? (We often bump version of rails in report templates on `master`, see https://github.com/rails/rails/pulls?q=is%3Apr+bug+report+templates+is%3Aclosed)

**Comment by rafaelfranca** [comment]
All branches. There is no reason to update those version on every release. I didn't comment on the current PRs to master and 5-2-stable because they were removing the `.rc1`.

**Pull request merged**
