### PR TITLE
ActionCable: Add a "welcome" and "ping" message type

### PR DESCRIPTION
**Pull request by danielrhodes**
### Summary

This pull request does three things:
1. Fixes inconsistencies in the ActionCable protocol between server and client in regards to the `ping` message by making ping a message type instead of an `identifier`.
2. Adds a `welcome` message type, which signals to clients the server is ready or has re-opened the connection.
3. Removes `ConnectionMonitor` as a subscriber, as this is no longer necessary when pings and welcome messages can be identified separately.
### Other Information

The `ping` message was being sent looking like:
`{"identifier": "_ping", "message": "3939939393"}`
whereas other messages were being sent to look like:
`{"type": "confirm_subscription" ...}`
Now the ping looks like:
`{"type": "ping", "message": "3939939393"}`

Consequently, this enabled some code to trick the client and tests to be removed and for some clean up in how the ConnectionMonitor works.

### CODE REVIEW

**Comment by maclover7** [comment]
Two quick comments:
1) Converting to message_types is already in progress via #23665
2) What does having an additional `welcome` message_type give us? I'm not really clear on the benefits...

@javan can you take a look at the CoffeeScript changes with this?

**Comment by danielrhodes** [comment]
@maclover7 Ha that's great. You're way ahead of me. As for the 'welcome' message, in trying to get 'ping' to become a message type I noticed that @lifo had made #23813 which used ping in such a way that a welcome message seemed more appropriate. I also like the idea that, especially when there is potentially authentication/the possibility that the server will reject the connection, the server sends a definitive message to the client saying you are connected: hence `welcome`.

**Comment by javan** [comment]
:heart:, except for one thing: `ConnectionMonitor#disconnected` isn't being called now since it's no longer a subscriber.

**Comment by jeremy** [comment]
Note, changes like this are going to be pretty tough to pull off in production. Connected clients on the old code won't understand the new pings, so the connection monitor will always think the connection is alive _but stale_ and it'll infinitely reconnect. Yikes.

Ideally, we could send the ping that the connected client expects, e.g. by knowing its protocol version, then let clients gradually move to the new version. Barring that, we could have clients disable themselves when they connect to a server with a newer protocol version, then let apps hook that to display a "New updates available, reload the page" type of message, or gracefully degrade to no live interaction.

We tried some workarounds to do a production upgrade across this change and it's really tough to manage with the tools we have on hand.

**Comment by maclover7** [comment]
Hmm, you mean version the "Action Cable protocol"? I'm :+1: on doing something along those lines

**Comment by danielrhodes** [comment]
@jeremy I was also affected by this and I authored the commit. :-) Ideally this protocol should be locked down as much as possible before final release, but you are right that there needs to be some versioning here. 

WebSockets has support for this in the form of the client sending protocols it can accept.

```http
Sec-WebSocket-Protocol: <protocol-name>
Sec-WebSocket-Version: <protocol-version>
```

Therefore the server could reject (or change its output) based on what the client asks for.

I believe browser websocket clients have support for the `Sec-WebSocket-Protocol` header, which is good enough.

**Comment by jeremy** [comment]
Super cool, @danielrhodes.

**Pull request merged**
