### PR TITLE
Bugfix activejob improper serialization and deserialization of scheduled_at

### PR DESCRIPTION
**Pull request by adamnoto**
### Summary

ActiveJob was not serializing and deserializing `scheduled_at` properly

### Other Information

We use ActiveJob with DelayedJob as adapter. And we are scheduling job in advance for monitoring purpose. However, `scheduled_at` value is always missing once because it's not even serialized, and also not deserialized as well if given. To achieve that, currently we are monkey patching the `ActiveJob::Core`.

This PR fix the issue.

### CODE REVIEW

**Comment by pixeltrix** [comment]
Hi @saveav - just to confirm the problem your seeing is that you can't access the scheduled_at data when the job is being performed, not that the job isn't being performed. I'm scheduling jobs in the future with a Delayed::Job backend myself and it's working fine.

**Comment by saveav** [comment]
@pixeltrix yes, correct. only when it's being performed do we lost access to the `scheduled_at` value of the job being performed.

**Comment by ignatiusreza** [comment]
Some clarification is required as to what `#scheduled_at` actually means.. as user of `Delayed::Job`, I was expecting that it will mimic `Delayed::Job#run_at`, which would changed value on failure.. but, some might also thing that it should return the time for when the job is originally set to run at, even after retry on failure..

**Comment by saveav** [comment]
no issue @pixeltrix what do you think about adding a new data that is implementation-agnostic? maybe like `first_scheduled_at` or the likes?

**Pull request closed without merging**
