### PR TITLE
Drop comments from structure.sql in postgresql

### LINKED ISSUE #28153: Remove comments from structure.sql for PostgreSQL adapter
When using the postgresql database adapter, run `rake db:structure:dump`. Note that the full version number is included in `db/structure.sql`:

```
-- Dumped from database version 9.5.4
-- Dumped by pg_dump version 9.5.4
```

 If we check it into git, that means that anyone with a different minor version of PostgreSQL server would have differences in the file after running `rake db:migrate`. Would you accept a pull request to remove all "--" comments from the resulting structure.sql?

### PR DESCRIPTION
**Pull request by aripollak**
Fixes #28153.

### CODE REVIEW

**Comment by matthewd** [comment]
I'm nervous about us mangling a file that's intended to be our "hands off, let psql handle it" escape hatch.

If these are the only differences you're seeing across machines, I'm somewhat surprised: as far as I know, Postgres makes no guarantees on the order it lists tables, for example. (And that's not even considering the explicit column-ordering mismatches that will appear from people running migrations in different orders.)

The specific danger that comes to mind is we don't know whether the line we're eating is truly a comment, or is part of a string literal.

**Comment by aripollak** [comment]
@matthewd Maybe we've gotten lucky, but it seems like the ordering has been pretty reliable across PostgreSQL versions and OSes. Your concerns certainly seem valid; what if we only restricted the removals to the specific headers at the top of the file?

**Comment by matthewd** [comment]
Yep, if just stripping until we hit the first non-comment line is sufficient, that sounds fine to me. 👍🏻

**Comment by aripollak** [comment]
Okay, I think this is better now. It removes any blank or `--` line before it sees a line that doesn't fit those criteria.

**Review by rafaelfranca — APPROVED** [review]

**Comment by matthewrudy** [comment]
I do something more involved in my project to try and avoid differences between postgres versions.
I believe this works for Postgres 9.4 -> 9.6

https://gist.github.com/matthewrudy/4400b3eee9f8dd7e15e4674359886c58

**Comment by raymondberg** [comment]
Note: This implementation created some interesting changes in file permission behavior. 

Now, the dumped structure will not inherit the file descriptor of the original (because a new descriptor is created by `TempFile` and moved), and that can change permissions of the file after every run. I'm not sure this is bug-worthy, but it definitely caused us a few hours of digging in trying to upgrade to Rails 5.1. 

This is particularly annoying when mixing with containerized solutions; any containerized run will change the file permissions from the user-created source. 

Hope this helps somebody in the future!

**Comment by malclocke** [comment]
Would there be any support for extending this to removing all comments?  I feel like if we are going to mess with the contents of this file the difference between removing some of the comments vs all of the comments is negligible.

There seems to be quite a lot of incremental changes to the comments in `pg_dump` output over time and in large teams we are constantly battling with diffs in `db/structure.sql`.  These diffs are almost always in the comments and not in the SQL.

I may also look into getting a patch into `pg_dump` to optionally suppress SQL comments from the output as that feels like the golden solution to me.

**Comment by matthewd** [comment]
@malclocke, see above:

> The specific danger that comes to mind is we don't know whether the line we're eating is truly a comment, or is part of a string literal.

A `pg_dump` option does seem the best way to achieve that safely.

**Comment by malclocke** [comment]
Looks like a patch to `pg_dump` is unlikely to get in https://www.postgresql.org/message-id/15151.1510026975%40sss.pgh.pa.us

**Pull request merged**
