### PR TITLE
Avoid i18n 1.1.0 for now

### PR DESCRIPTION
**Pull request by yahonda**
### Summary

This pull request workarounds railties CI failure at https://travis-ci.org/rails/rails/jobs/413582591
It is triggered by using i18n 1.1.0 just released Aug 7 https://rubygems.org/gems/i18n/versions/1.1.0

Will open an issue to i18n soon.

### Steps to reproduce

```ruby
$ cd railties
$ bundle update i18n
$ bundle exec ruby -w -Itest test/application/initializers/i18n_test.rb
```

### Actual result

```ruby
$ cd railties
$ bundle update i18n
$ bundle exec ruby -w -Itest test/application/initializers/i18n_test.rb
Run options: --seed 16202

# Running:

.......F

Failure:
ApplicationTests::I18nTest#test_config.i18n.fallbacks_=_true_initializes_I18n.fallbacks_with_default_settings [test/application/initializers/i18n_test.rb:220]:
expected fallbacks for :de to be [:de, :en], but were [:de].
Expected: [:de, :en]
  Actual: [:de]


rails test test/application/initializers/i18n_test.rb:216

..F

Failure:
ApplicationTests::I18nTest#test_config.i18n.fallbacks.map_=_{_:ca_=>_:'es-ES'_}_initializes_fallbacks_with_a_mapping_ca_=>_es-ES [test/application/initializers/i18n_test.rb:240]:
expected fallbacks for :ca to be [:ca, :"es-ES", :es, :en], but were [:ca, :"es-ES", :es].
Expected: [:ca, :"es-ES", :es, :en]
  Actual: [:ca, :"es-ES", :es]


rails test test/application/initializers/i18n_test.rb:237

F

Failure:
ApplicationTests::I18nTest#test_config.i18n.fallbacks_=_true_initializes_I18n.fallbacks_with_default_settings_even_when_backend_changes [test/application/initializers/i18n_test.rb:228]:
expected fallbacks for :de to be [:de, :en], but were [:de].
Expected: [:de, :en]
  Actual: [:de]


rails test test/application/initializers/i18n_test.rb:223

...F

Failure:
ApplicationTests::I18nTest#test_[shortcut]_config.i18n.fallbacks_=_[{_:ca_=>_:'es-ES'_}]_initializes_fallbacks_with_a_mapping_ca_=>_es-ES [test/application/initializers/i18n_test.rb:252]:
expected fallbacks for :ca to be [:ca, :"es-ES", :es, :en], but were [:ca, :"es-ES", :es].
Expected: [:ca, :"es-ES", :es, :en]
  Actual: [:ca, :"es-ES", :es]


rails test test/application/initializers/i18n_test.rb:249

..

Finished in 6.690818s, 2.6903 runs/s, 5.0816 assertions/s.
18 runs, 34 assertions, 4 failures, 0 errors, 0 skips
$
```

### CODE REVIEW

**Comment by yahonda** [comment]
Opened an issue to i18n https://github.com/svenfuchs/i18n/issues/427

**Comment by yahonda** [comment]
Reverting https://github.com/svenfuchs/i18n/pull/415 makes also CI green. 
Looks like this is an intended i18n change. I have no strong opinion which behavior is appropriate for Rails, though.

**Comment by robin850** [comment]
Even though this fixes the CI, it looks like this change is pretty "brutal" for a minor release of i18n. This may break people applications in the future. Shouldn't we set an upper bound inside Active Support's gemspec or provide a sort of compatibility layer for people upgrading i18n ?

**Comment by kamipo** [comment]
I think we could wait a response for https://github.com/svenfuchs/i18n/issues/427, whether https://github.com/svenfuchs/i18n/pull/415 will be reverted or not.

**Comment by lsylvester** [comment]
I have reviewed the documentation and configuration in Rails, and while this does break some cases, I think that it also resolves some bugs as well.

For the case `config.i18n.fallbacks = true`, this is broken by this change as it relied on the default being added in by i18n. This can be moved to the initialiser fairly easily, and then we will be compatible with both versions. This is the default config in production so it is the most important to fix.

The cases where fallbacks is an non empty Array (i.e. `config.i18n.fallbacks = [:tr, :en]`), it will continue to work correctly.

In the cases where fallbacks is an empty array or a hash (i.e. `config.i18n.fallbacks = []` or `config.i18n.fallbacks.defaults = []` or `config.i18n.fallbacks = {az: :tr}` or default in dev or test) there is a change in behaviour, in that it would default to the default local in i18n 1.0.X but not in 1.1.0. However, this is no documentation that I can see to suggest that it  would default to this, so I am not sure if that should be considered a bug in Rails.

I would suggest that for Rails 5.2.X, we should try to maintain existing behaviour with the default local injected into defaults if it is empty, and an additional configuration of `config.i18n.fallbacks = false` or `config.i18n.fallbacks.defaults = false` to disable the fallback to the default locale. 

For Rails 6.0.X (which can depend on `i18n ~> 1.1` we should only inject the default locale into the fallbacks if `config.i18n.fallbacks = true` or `config.i18n.fallbacks.defaults = true`

I will work on a PR for this, but any feedback on the approach would be appreciated.

**Comment by lsylvester** [comment]
@robin850 @kamipo I have a compatibility fix for this at #33574. Even if this commit is revered for 1.X versions, I think that they would want to reintroduce it at some point, so it would be better that Rails can handle both of the behaviours.

**Pull request merged**
