### PR TITLE
Shouldn't stop the user due to bcrypts limitation

### PR DESCRIPTION
**Pull request by krainboltgreene**
### Summary
1. Use keyword arguments instead of a hash, now that Ruby 2.2.2 is the minimum.
2. Allow the developer to modify some basic parts of the `has_secure_password` functionality, and not just validations.
3. No more bcrypt-level limitation on passwords!
### Other Information
- The blowfish algo: https://www.usenix.org/legacy/events/usenix99/provos/provos_html/node4.html
- django limited their password length to 4064 characters: https://www.djangoproject.com/weblog/2013/sep/15/security/
- Here is dropbox describing how they do passwords: https://blogs.dropbox.com/tech/2016/09/how-dropbox-securely-stores-your-passwords/
- Here's a video of facebook's approach: http://video.adm.ntnu.no/pres/54b660049af94

### CODE REVIEW

**Comment by georgeclaghorn** [comment]
Running passwords through Digest::SHA384.base64digest before hashing them is a breaking change:

```
irb(main):002:0> password = BCrypt::Password.create('secret', cost: 10)
=> "$2a$10$9AgyANDFJepP8Zh/P5hztODgB2I19r9VRwyN8bd6Ro7FS/bIj.fOS"
irb(main):003:0> BCrypt::Password.new(password).is_password?(Digest::SHA384.base64digest('secret'))
=> false
```

**Comment by krainboltgreene** [comment]
Correct.

**Comment by rafaelfranca** [comment]
Thank you so much for the pull request. Unfortunately we can't accept a backwards incompatible change. How do we make it backwards incompatible?

**Comment by krainboltgreene** [comment]
I guess you could do a rails version check?

Would it be an acceptable strategy to make a gem for old behavior and tell upgraders to use that gem until they fix their problem?

**Comment by georgeclaghorn** [comment]
> I guess you could do a rails version check?

A version check would not make this change backwards-compatible.

**Comment by rafaelfranca** [comment]
Having an extra gem also doesn't make it backwards compatible. Can we detect password that were not digested and gracefully make them digested and update the value in the database?

**Pull request closed without merging**
