### PR TITLE
Move Minitest out of test group in Gemfile.

### PR DESCRIPTION
**Pull request by tgxworld**
This reverts commit 8c48cd220648dc05c17def63d653fa98c3fab4de.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Travis disagree.

**Comment by tgxworld** [comment]
@rafaelfranca hmm this is weird. We're skipping the test group in Travis now so it shouldn't affect anything. I'll investigate later :smile:

**Comment by tgxworld** [comment]
@rafaelfranca The reason the tests were failing is because after removing it, the cache on Travis deletes the Minitest library and reinstalls it. However, it installs Minitest 5.5.1 which had changes that breaks the internal tests. In fact, our tests start to break on Minietst 5.3.4 onwards.

I decided to lock Minitest in the Gemfile to 5.3.3 because the previous code in `group :test` is no longer relevant.

**Comment by matthewd** [comment]
I think `< 5.3.4` is more descriptive. If we need to move the line, fine.. but I see no reason to editorialize it at the same time.

I'd also like to understand why it's safe to remove the gem call from those lib files.

**Pull request closed without merging**
